### ISSUE TITLE
Is it possible to share access via federation?

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/calendar#1001]
Hi, 
I have a private and a business nextcloud server. 

Is it possible to grant access on the calendar across the servers? Sharing the calender with the Federated-Cloud-ID from a user from the other server is not working. 

Maybe this cloud be a nice improvement?

Thanks and greetings!

**Comment by georgehrke** [comment]
Not possible, but it's planned: https://github.com/nextcloud/server/issues/1440
