### ISSUE TITLE
[Feature Request] Show Files In Calendar

### ISSUE THREAD

**Issue by theendcomplete** [nextcloud/calendar#1007]
Hi!
It would be great if there were an option of showing files sorted by uploaded date in calendar.
Maybe, there already is some solution? 
Thank you!

**Comment by Spartachetto** [comment]
Can I ask for clarification?

Do you want a calendar with a graphical representation of the files uploaded in each day? 
If so:
- the visualization could be cluttered
- probably you are talking of something that could be a widget of the dashboard app

**Comment by georgehrke** [comment]
> It would be great if there were an option of showing files sorted by uploaded date in calendar.

can you please describe a use case? 

> the visualization could be cluttered

I can only second @Spartachetto's comment here. 

> probably you are talking of something that could be a widget of the dashboard app

👍

**Comment by theendcomplete** [comment]
the case is ability to see files sorted by date
file in this calendar could be Events

example:
![image](https://user-images.githubusercontent.com/6422361/49795231-870d4080-fd4a-11e8-8fec-cf7e26c0de91.png)

Files in my case are something like a newsletter.
So my first thoughts are to visualize it in Calendar
Maybe, I'm trying to reinvent a wheel but I did not find anything like this searching in Apps...

**Comment by georgehrke** [comment]
Yes, I got that, but why do you need your files in the calendar? What is your workflow?

> So my first thoughts are to visualize it in Calendar

I have honestly never seen any calendar application do that.

> Maybe, I'm trying to reinvent a wheel but I did not find anything like this searching in Apps...

As far as i know this is not possible with any app right now.

**Comment by theendcomplete** [comment]
I don't need _files_ in caledar, I need filenames and a web link in full Event's info.
I need info about time they we shared structured by day.
This Calendar would be read-only.
The events would be created when files are shared to user.

Workflow is:
- admin shares some documents (newsletter) to many users
- user receives notification and reads it
The problem begins when count of files increases. It's not easy to find some newsletter that user received couple of months ago.
So displaying filenames on a calendar would be a great solution.

**Comment by georgehrke** [comment]
cc @tcitworld @skjnldsv @jancborchardt 

This really seems like a hack to me. If you have troubles finding old files in the files app, we should improve that instead of hijacking the calendar app for it.

Did you try the Activity app yet? 
It shows you a timeline of activities including files shared with you.
Maybe it would be good to have a date picker in the activity back to easily go back a couple of months? cc @nickvergessen

**Comment by skjnldsv** [comment]
Yes, this seems out of scope for the calendar app :)

**Comment by theendcomplete** [comment]
> Did you try the Activity app yet?

I\ve tried after you said (It was disabled in my installation)
It suits out workflow very well.
Thank you!

**Comment by jancborchardt** [comment]
Yeah, agree this is out of scope. It could be a separate app maybe connecting Files and Calendar?

Also, the uploads are shown in the Activity app by date, so that’s already doing it.

**Comment by LiverWurst** [comment]
> 
> 
> Yes, I got that, but why do you need your files in the calendar? What is your workflow?
> 
> > Package shipping with images of the attached labels. I track my arrival and departures via calendar
> > and need to be able to attach images to the event or the ability to link images to the event.
> 
> I have honestly never seen any calendar application do that.
> 
> > Teamup does this.
> 
> As far as i know this is not possible with any app right now.
>
>> Make it so.

**Comment by jancborchardt** [comment]
@LiverWurst browsing their site at https://www.teamup.com doesn’t really make it look like this is very present. Can you share screenshots of how they do it?

**Comment by georgehrke** [comment]
> Package shipping with images of the attached labels. I track my arrival and departures via calendar
and need to be able to attach images to the event or the ability to link images to the event.

What you want sounds like #298 

Please read the original description of this ticket. It's very different.
