### ISSUE TITLE
[Feature] Disable birthday calendar

### ISSUE THREAD

**Issue by scriptPilot** [nextcloud/calendar#101]
In my point of view there should be a checkbox in the preferences to diable the automatically created calendar completely. Maybe you could give me a hint what to change to do it before implementation of that feature? Regards!

**Comment by georgehrke** [comment]
You can just hide it, why do you need the ability to delete it completely? 

cc @jancborchardt

**Comment by scriptPilot** [comment]
The thing is it will be selected each time again after page reload ...
But isn't there any line of code I could simply stike out to disable this functionality - and - is it planned to setup a disabling function?

**Comment by georgehrke** [comment]
> The thing is it will be selected each time again after page reload ...

That's a bug, it should definitely save the state.
I'll check if this is an issue in the calendar app or the Nextcloud server.

**Comment by georgehrke** [comment]
The calendar app sends a correct request. Not being able to hide the birthday calendar is a bug in the server. please report it in https://github.com/nextcloud/server
