### ISSUE TITLE
[Feature Request] Allow HTML in Description field of event

### ISSUE THREAD

**Issue by unix0r** [nextcloud/calendar#1010]
Is it possible to allow html in the description field of an event?
Just added an unsorted list via an android calendar app and it only shows the html tags instead of the list:
![bildschirmfoto von 2018-12-12 12-36-25](https://user-images.githubusercontent.com/4679329/49867386-a10e5800-fe0a-11e8-9390-0d9459bc5685.png)

Using nextcloud 14.0.4 and Calendar App 1.6.4

**Comment by georgehrke** [comment]
I'm personally not a fan of this idea. This will just introduce a huge attack surface for XSS attacks ...

Does Android create html lists automatically or did you install some extension for it?
(I would personally recommend just using markdown for lists)

cc @tcitworld

**Comment by unix0r** [comment]
The event was created via the android app "Business Kalendar 2".

**Comment by charlescurley** [comment]
Rather than rendering HTML in the DESCRIPTION: field, look for and render X-ALT-DESC: fields. But @georgehrke is correct. Make it an administrator or user option, default off.

**Comment by georgehrke** [comment]
I'd be okay with Markdown if anything, but rendering HTML is a big no-go, since it will open the doors to a huge nightmare of XSS and other injection attacks.

"Business Kalendar 2" is not behaving standard complaint by putting HTML into the description field.

**Comment by ctr49** [comment]
It doesn't look like this has been solved, should we reopen or create a new issue for this request?

How about the following implementation:
- support Markdown in description text box of Nextcloud Calendar items (i.e. like a Deck card's description)
- store the md-formatted content in the DESCRIPTION parameter of the event 
- when accessed externally (is it possible to distinguish?) render the DESCRIPTION's field content as html using md2html if it contains Markdown
  - either represented inside the "X-ALT-DESC" (as per [RFC5545 3.8.8.2 Non-Standard Properties](https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.8.2)) parameter or as text/html content portion referenced by a "DESCRIPTION;ALTREP" parameter (as per [RFC5545 3.2.1 Alternate Text Representation](https://datatracker.ietf.org/doc/html/rfc5545#section-3.2.1)).

TBD:
- how to keep the content of DESCRIPTION and X-ALT-DESC/DESCRIPTION;ALTREP in sync? e.g. how to handle externally (e.g. in an external application) created/modified VEVENTS containing X-ALT-DESC/DESCRIPTION;ALTREP? render back to md using html2md?

**Comment by tcitworld** [comment]
This is tracked at https://github.com/nextcloud/calendar/issues/3234, feel free to repost your comment there.
