### ISSUE TITLE
ICS shared calendars not always loading

### ISSUE THREAD

**Issue by AmonBune** [nextcloud/calendar#1011]
Nextcloud 15.0.0
PHP 7.2

If I open up the calendar app for the first time, I see these exclamation marks.
![image](https://user-images.githubusercontent.com/15927695/49870539-f733c900-fe13-11e8-9893-f9fbb9fdb237.png)

As far as I know these marks mean "could not synchronize with the external calendar", which is strange, because if I reload the page a few times, like, 2 or 3 times, they load correctly.

After some F5s:
![image](https://user-images.githubusercontent.com/15927695/49870636-4679f980-fe14-11e8-9f17-2fae1b000cb4.png)

I just wanted you to know. It seems to still show the events from these calendars, but there's this icon...

**Comment by tcitworld** [comment]
Is there anything is the browser console?

**Comment by AmonBune** [comment]
@tcitworld 
![image](https://user-images.githubusercontent.com/15927695/49871034-65c55680-fe15-11e8-842f-ffcf26ac7dbe.png)

**Comment by tcitworld** [comment]
The message "Error requesting resource on remote server" tells us it's probably related to the connection with the server providing those ICS.

**Comment by AmonBune** [comment]
The server is Outlook.com. So it's their fault, and nothing can be done?

**Comment by georgehrke** [comment]
@AmonBune I assume that your server has possibly been blacklisted / throttled. Not much we can do.
