### ISSUE TITLE
RSVP missing from invite Mail Attachment.ics

### ISSUE THREAD

**Issue by leymannx** [nextcloud/calendar#102]
Owncloud on 1&1 Unlimited Plus Shared Hosting on Linux

```
$OC_Version = array(9,1,0,15);
$OC_VersionString = '9.1.0';
```

Nextcloud Calender App
`<version>1.4.0</version>`

OSX 10.12
OSX Mail 10.0 (3226)
OSX Calendar 9.0 (2155)
### Steps to reproduce
1. Setup OC, activate calendar app, activate contacts app, allow Share API, create 2 new users with personal email address set, add them in their contacts respectively.
2. User 1 creates event in calendar, adds attendee which is user 2.
3. User 2 has OSX, has setup calendar and contacts from OC, now gets invite mail, but "Accept", "Decline", "Ignore" buttons missing, same in OSX calendar app.
4. User 2 checks Mail Attachment.ics and notices that `RSVP=TRUE` is missing, whereas everything else looks fine.
5. Editing Mail Attachment.ics and adding `RSVP=TRUE` manually and open it again makes OSX calendar work as expected, buttons to accept, decline, ignore are appearing and status changes when clicked.
### Expected behaviour

RSVP=TRUE in *.ics file to accept invite.
### Actual behaviour

RSVP=TRUE missing in invite *.ics.
### Server configuration

**Operating system**:
Linux

**Web server:**
1&1 Unlimited Plus Shared Hosting

**Database:**
MySQL 5

**PHP version:**
7.0.11

**Server version:** (see your admin page)
?

**Calendar version:** (see the apps page)
1.4.0

**Updated from an older installed version or fresh install:**
No

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Don't get that app list, no third party stuff, just a fresh OC install with basic apps enabled.
```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'oczzzzzzzzz',
  'passwordsalt' => 'aBcDeFgHiJkLmNNNNNNNNNNN',
  'secret' => 'I like my rabbits more than my dog',
  'trusted_domains' => 
  array (
    0 => 'owncloud.tcbg.luv',
  ),
  'datadirectory' => '/homepages/99/d9999999/htdocs/owncloud/data',
  'overwrite.cli.url' => 'https://owncloud.tcbg.luv',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'db321',
  'dbhost' => 'db123.db.1and1.com',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'Daddy',
  'dbpassword' => 'Mommy',
  'logtimezone' => 'UTC',
  'installed' => true,
  'app.mail.transport' => 'php-mail',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'tcbg.luv',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
FF, Chrome, Safari

**Operating system:**
OSX 10.12

**CalDAV-clients:**
Calendar 9.0 (2155)
#### Mail Attachment.ics

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 3.5.0//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20160929T214805
DTSTAMP:20160929T214805
LAST-MODIFIED:20160929T214805
UID:d83xl27wcr
SUMMARY:Gumpi Gumpi
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CUTYPE=INDIVIDUAL;CN=Top Checker Boy:MAILTO:boy@tcbg.luv
ORGANIZER;CN=Top Checker Girl:MAILTO:girl@tcbg.luv
CLASS:PUBLIC
STATUS:CONFIRMED
DTSTART;TZID=Europe/Berlin;VALUE=DATE:20161001
DTEND;TZID=Europe/Berlin;VALUE=DATE:20161002
END:VEVENT
END:VCALENDAR
```

**Comment by georgehrke** [comment]
Can you reproduce the same behavior with Nextcloud?

**Comment by leymannx** [comment]
I'll try that. BRB

**Comment by leymannx** [comment]
Exactly the same.

Nextcloud
```
$OC_Version = array(9,1,0,16);
$OC_VersionString = '10.0';
```

Nextcloud Calendar App
`<version>1.4.0</version>`

PS:
Guess I'll switch to NC anyhow 👍

**Comment by georgehrke** [comment]
Okay, thx for checking. :)

I need to see if this is a bug in the calendar app or the Nextcloud server.
