### ISSUE TITLE
Simpler design for top part of navigation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#1021]
The current top part of navigation has a bunch of actions which are rarely needed:

![calendar nav before](https://user-images.githubusercontent.com/925062/50314089-cefc3800-04ad-11e9-9f07-4a3d2cae3e40.png)

This is a new proposal:
- A prominent (primary) "+ New event" button, which opens the event popover, by default a full-day event on _today_. Only this button has bold text.
- The "Today" button is put on the same line as it’s not soo important
- The day/week/month switcher is now just an icon indicating the current state. On click it opens a popover menu with a list of Day, Week, Month with the current one highlighted.

![calendar navigation top new](https://user-images.githubusercontent.com/925062/50314211-45993580-04ae-11e9-9203-bf3ff163ee7e.png)

cc @nextcloud/calendar

**Comment by tcitworld** [comment]
Interesting !

What about putting the "+ New event" on the right of the second line instead, to make this button more accessible, since the cursor will probably on this area of the screen initially?

**Comment by jancborchardt** [comment]
You mean switching the order from: "New event, Today, display toggle" to "Today, display toggle, New event"?

I'd rather first go with the initial proposal, as otherwise the primary action is strangely floating in space.

Another option is to put the "Today" button (probably icon only) and the display toggle on the first row with the date switcher as well. But this seems less ideal, especially as then 2 actions would have to be icons.

**Comment by georgehrke** [comment]
> The day/week/month switcher is now just an icon indicating the current state. On click it opens a popover menu with a list of Day, Week, Month with the current one highlighted.

I'm not sure if putting the views in a popover is the best decision. It's a very common, frequently used action. Many people use the month view to get an overview and then week view to look into some days in detail / to schedule events.

But maybe that can be connected with https://github.com/nextcloud/calendar/issues/796

**Comment by jancborchardt** [comment]
> I'm not sure if putting the views in a popover is the best decision. It's a very common, frequently used action. Many people use the month view to get an overview and then week view to look into some days in detail / to schedule events.

Just for reference, the new Google Calendar also does this.


And as a first step maybe we could simply put "Today" and the "Day / Week / Month" switcher on one row, not adding the "New event" button yet.

**Comment by georgehrke** [comment]
> And as a first step maybe we could simply put "Today" and the "Day / Week / Month" switcher on one row,

We had this before, but it broke if the translated strings are too long: https://github.com/nextcloud/calendar/issues/312

That's why we moved it into it's own row.

**Comment by georgehrke** [comment]
@jancborchardt Can you provide a small mockup of what clicking the "day/week/month switcher" should look like? (the popover)

Should we combine this with #508?

**Comment by jancborchardt** [comment]
@georgehrke it should basically just be an actions menu like at https://nextcloud-vue-components.netlify.com/#/Components?id=actions-1 :)

And yes, then there should of course be icons for day/week/month. I would recommend `view_day`, `view_week` and `view_module` from https://material.io/resources/icons/?search=view_&style=baseline

**Comment by georgehrke** [comment]
I was also wondering whether we should hide the `New calendar` and `New subscription` buttons by default. Most people don't add new calendars on a  daily basis.

**Comment by skjnldsv** [comment]
QUick note as I just notice this issue, the 4 square icons is the one used for the grid view, and I think it's not straightforward enough :)
We should aim for a better understandable icon.

**Comment by jancborchardt** [comment]
> I was also wondering whether we should hide the `New calendar` and `New subscription` buttons by default. Most people don't add new calendars on a daily basis.

@georgehrke this is specifically about the top part of the navigation. :) But yes, probably putting them on the bottom of the list is already good.



> QUick note as I just notice this issue, the 4 square icons is the one used for the grid view, and I think it's not straightforward enough :)
> We should aim for a better understandable icon.

In the Files app it’s also to change the view, so it’s partly fitting. But yes, this was also just used to quickly have something to improve upon, but so far there was no better proposal and it still communicates the "view" aspect very well, also for the calendar.
