### ISSUE TITLE
Make timed events the default instead of full day?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/calendar#104]
Also it would be pretty neat, if clicking on the time input fields, the event would switch from full day to time based automatically.
Less clicks more fun 😸

**Comment by georgehrke** [comment]
you can use the week view to select a time range ;)

**Comment by nickvergessen** [comment]
Hmm, so this only happens for the month-view?
But even so, I think most events are time range events. I only ever use the month view...

**Comment by georgehrke** [comment]
See https://github.com/nextcloud/calendar/issues/72

There is one suggestions to toggle the all-day when clicking the disabled time-field

**Comment by georgehrke** [comment]
Can we close this in favor of #72 ? :)

**Comment by nickvergessen** [comment]
I guess that would be sufficient enough as a solution, yes
