### ISSUE TITLE
Buttons not visible in dark theme

### ISSUE THREAD

**Issue by unix0r** [nextcloud/calendar#1042]
Hey guys,
just activated the new dark theme in nextcloud 15 and two buttons are not visible due to too dark color:

![bildschirmfoto von 2019-01-03 08-02-59](https://user-images.githubusercontent.com/4679329/50626357-077c2700-0f2e-11e9-98e0-70eefb00c5bc.png)

The Datepickers (left and right of Januar 2019) for changing the month are still black.

Maybe set them to the same color as the month string?
Edit:
leftarrow.svg and rightarrow.svg are the icons.

Calendar Version:  1.6.4
Nextcloud Version: 15.0.0.10

**Comment by tcitworld** [comment]
Confirmed and missed it in https://github.com/nextcloud/calendar/pull/941

**Comment by 0x4647** [comment]
Hi Artur,
I can confirm this also in my white theme.
Can you please check in the browser console if you get a 404 for the leftarrow.svg and rightarrow.svg?
I think the files are missing in the Calendar app completely ^^

Best regards.

**Comment by georgehrke** [comment]
@0x4647 That seems to be in issue in your particular instance. If you look at @unix0r's screenshot you can actually see the arrows, but they are simply black on a dark grey background.
