### ISSUE TITLE
Feature request : sharing busy / available information on an agenda only

### ISSUE THREAD

**Issue by dylanbob** [nextcloud/calendar#1044]
This is a feature request : to be able to share only busy/available information when sharing a calendar or all events without details.
This would be a great way for example to see limited information of my private agenda on my professionnal computer / system / calendar client.

### Steps to reproduce
1. Click on a calendar sharing button
2. Tick a box to select "not sharing details / only share busy-available information"
3. Get a public link to share the calendar / subscribe to it without the events details

### Expected behaviour
Just like the current sharing functionnality, but one can only see basic information on the calendar events : only start and end of each event (no text, no invitees, no location or category or reminders or whatever).

### Actual behaviour
There is no such functionnality as of now

### Server configuration
Not applicable. It would have to work just like the current sharing functionnality.

**Comment by git-darius** [comment]
This feature would be very helpful!

**Comment by georgehrke** [comment]
Please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting +1, 👍 etc. These kinds of comments just unnecessarily notify everyone subscribed to this issue. Thx! :)

**Comment by georgehrke** [comment]
This feature is already provided using Free/Busy for other users.
There is a feature request to share a busy only calendar with link: https://github.com/nextcloud/calendar/issues/725
