### ISSUE TITLE
Can't edit attendees list in the NextCloud calendar web app

### ISSUE THREAD

**Issue by SlavikCA** [nextcloud/calendar#1047]
### Steps to reproduce
1. New installation of Calendar app.
2. Open Calendar in the browser
3. Create event
4. Edit event

### Expected behaviour
As user, I should be able to edit attendees list

### Actual behaviour
There is no way (no controls) to edit attendees list

![nc-cal](https://user-images.githubusercontent.com/6293679/50732377-cef76b80-112e-11e9-83fd-6d55ec0f9db5.png)

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4 proxied via Nginx

**Database:**
MySQL

**PHP version:**
7.0

**Server version:** (see your admin page)
NextCloud 15.0

**Calendar version:** (see the apps page)
1.6.4 fresh & new install

**List of activated apps:**
Enabled:
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.0
  - deck: 0.5.2
  - drawio: 0.9.2
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.8.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.2
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sociallogin: 1.11.3
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - workflowengine: 1.5.0
Disabled:
  - accessibility
  - activity
  - admin_audit
  - contacts
  - encryption
  - federation
  - files_external
  - nextcloud_announcements
  - notifications
  - password_policy
  - sharebymail
  - support
  - survey_client
  - updatenotification
  - user_external
  - user_ldap

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.aidcim.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/cloud.aidcim.org\/",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "logfile": "nextcloud2.log",
        "loglevel": 1,
        "theme": "",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "onlyoffice": {
            "verify_peer_off": true
        }
    }
}
```
**Are you using external storage, if yes which one:**
no

**Are you using encryption:** 
no

### Client configuration
**Browser:**
Chrome 70

**Operating system:**
Win 10

**CalDAV-clients:**
N/A

#### Browser log
```
vendor.js:23203 Attempting to call a FullCalendar method on an element with no calendar.
a.warn @ vendor.js:23203

[DOM] Found 2 elements with non-unique id #frequency_select: (More info: https://goo.gl/9p2vKq) 

<select id="frequency_select" ng-options="repeat.val as repeat.displayname for repeat in repeat_options_simple" ng-model="properties.rrule.freq" class="ng-pristine ng-untouched ng-valid ng-not-empty"><option label="None" value="string:NONE" selected="selected">None</option><option label="Every day" value="string:DAILY">Every day</option><option label="Every week" value="string:WEEKLY">Every week</option><option label="Every month" value="string:MONTHLY">Every month</option><option label="Every year" value="string:YEARLY">Every year</option></select>

<select id="frequency_select" ng-options="repeat.val as repeat.displayname for repeat in repeat_end" ng-model="selected_repeat_end" class="ng-pristine ng-untouched ng-valid ng-not-empty"><option label="never" value="string:NEVER" selected="selected">never</option><option label="after" value="string:COUNT">after</option></select>
```

**Comment by tcitworld** [comment]
Did you read the text label in the area you're pointing at?

**Comment by SlavikCA** [comment]
shame on me...

**Comment by tcitworld** [comment]
No worries. You could open another issue to discuss how this label could be improved so that other people see it easier. ;)
