### ISSUE TITLE
Can't add WebCal calendar subscription

### ISSUE THREAD

**Issue by ngasull** [nextcloud/calendar#1056]
### Steps to reproduce
1. Access NextCloud with https
2. Go to calendar tab
3. Click "+ New Subscription"
4. Enter an `https` link to a webcal (tried Facebook events and a private Google calendar)
5. Confirm

### Expected behaviour
The calendar subscription is successful

### Actual behaviour
The following notification appears: "Severe error in webcal proxy. Please contact administrator for more information."

## Server configuration detail

**Operating system:** Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.22

**PHP version:** 

7.1.25
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, intl, json, ldap, mbstring, mcrypt, pcntl, PDO, session, pdo_sqlite, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

**Nextcloud version:** 13.0.8 - 13.0.8.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** snap

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.7
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_markdown: 2.0.5
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.8
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "apps_paths": [
        {
            "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "supportedDatabases": [
        "mysql"
    ],
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "cloud.gasull.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbtype": "mysql",
    "version": "13.0.8.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 0
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/72.0.3626.28 Chrome/72.0.3626.28 Safari/537.36

**Operating system:** Ubuntu 18.04

## Logs

<details><summary>Browser log</summary>

```
Console: (NB: all does happen before trying to add the calendar)
```
core.js?v=57f098ed-4:1563 Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
w @ core.js?v=57f098ed-4:1563
vendor.js:23280 Attempting to call a FullCalendar method on an element with no calendar.
vendor.js:23280 Attempting to call a FullCalendar method on an element with no calendar.
vendor.js:23280 Attempting to call a FullCalendar method on an element with no calendar.
vendor.js:23280 Attempting to call a FullCalendar method on an element with no calendar.
```

Network: content is sensitive, but the request to the added actually succeeds, and I can see the text content of the calendar through the dev tools.
```
</details>

<details><summary>Nextcloud log</summary>

```
Empty, even in debug level
```
</details>

<details><summary>Browser log</summary>

Console: (NB: all does happen before trying to add the calendar)
```
core.js?v=57f098ed-4:1563 Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
w @ core.js?v=57f098ed-4:1563
vendor.js:23280 Attempting to call a FullCalendar method on an element with no calendar.
vendor.js:23280 Attempting to call a FullCalendar method on an element with no calendar.
vendor.js:23280 Attempting to call a FullCalendar method on an element with no calendar.
vendor.js:23280 Attempting to call a FullCalendar method on an element with no calendar.
```

Network: content is sensitive, but the request to the added actually succeeds, and I can see the text content of the calendar through the dev tools.
</details>

**Comment by georgehrke** [comment]
You provided the browser log twice, but you didn't provide the server's error log. Can you please check if there is anything in there?

**Comment by georgehrke** [comment]
Maybe some workarounds with the cert file from https://github.com/nextcloud/calendar/issues/250 will work for you
