### ISSUE TITLE
Enhancement: Calender reminder e-mail to contain event start date

### ISSUE THREAD

**Issue by steff517** [nextcloud/calendar#1057]
I'm using a shared calendar and setup mail notifications when new events are added. The notification includes the information

- When was the event created
- Who created it
- The name of the event
- The calender in which it was created
- But I can't see the start date of the event. 
It takes me significant time to open the calendar and find the event (might be months in the future) to retreive that information.

As a simple solution, I'd just like to see the event start date and duration of the event in the e-mail. Optional: A direct link to the event which will open the calender with the event in view.

**Comment by georgehrke** [comment]
@nickvergessen This is activity related. Does this belong in the server or the activity app repo though?

**Comment by tcitworld** [comment]
Server, because we need to send more data to the activity app.

**Comment by steff517** [comment]
Why did you close it?

**Comment by georgehrke** [comment]
@steff517 Because this is the wrong repository. Please reopen in https://github.com/nextcloud/server

**Comment by steff517** [comment]
@georgehrke Okay, thanks
