### ISSUE TITLE
Reminders for "Contact Birthdays"?

### ISSUE THREAD

**Issue by steckerhalter** [nextcloud/calendar#106]
Since the "Contact Birthdays" calendar is read-only it is also not possible to set reminders for the birthdays which makes it easy to still miss these birthdays.

Could there be added a default reminder like one day in advance or something? I mean it's good to have the calendar but it's main purpose for me should be to help me not to forget birthdays which it now more or less only does by accident.

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by steckerhalter** [comment]
@georgehrke ah, okay :) thanks
