### ISSUE TITLE
Error: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/calendar#1064]
### Steps to reproduce
1. Sync calendar with iMac Calendar
2. see error in Log

![caldav_error_1502](https://user-images.githubusercontent.com/1473674/51074090-11fb9680-167b-11e9-995c-a1de44bcba09.PNG)

### Expected behaviour
Tell us what should happen
calendar sync without error

### Actual behaviour
Tell us what happens instead
error in Serverlog, but dates are updated

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7

**PHP version:**
7.3.1

**Server version:** (see your admin page)
15.0.2

**Calendar version:** (see the apps page)
1.6.4

**Updated from an older installed version or fresh install:**
updated from 14.0.4 to 14.0.6 to 15.0.2 (set to beta, update to 15.0.2 and changed back to stable)

**List of activated apps:**

Accessibility 1.1.0
Brute-force settings 1.3.0
Calendar 1.6.4
Deleted files 1.5.0
File sharing 1.7.0
Gallery 18.2.0
Log Reader 2.0.0
Notifications 2.3.0
Password policy 1.5.0
PDF viewer 1.4.0
Share by mail 1.5.0
Support 1.0.0
Text editor 2.7.0
Theming 1.6.0
Two Factor TOTP Provider 2.1.0
Update notification 1.5.0
Video player 1.4.0

### Client configuration
**Browser:**
latest Safari

**Operating system:**
MacOS Mojave (latest)

**CalDAV-clients:**
Apple Calendar

#### Web server error log
![caldav_error_1502](https://user-images.githubusercontent.com/1473674/51074090-11fb9680-167b-11e9-995c-a1de44bcba09.PNG)

#### Log file (data/nextcloud.log)
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? at /www/htdocs/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php#321
Could not find resource vendor/strengthify/jquery.strengthify.min.js to load
Could not find resource vendor/strengthify/jquery.strengthify.min.js to load

**Comment by georgehrke** [comment]
https://github.com/nextcloud/3rdparty/pull/186
