### ISSUE TITLE
Calendar changes view when CTRL+ENTER saving simple editor event

### ISSUE THREAD

**Issue by emilhem** [nextcloud/calendar#1065]
### Steps to reproduce
1. Press next/previous date (day/week/month)
2. Begin creating an event with the simple editor
3. While having the event name in focus press CTRL + ENTER to save the event
4. The event will save but day/week/month will change (not of the event though)

### Expected behaviour
The event should save and the currently view should remain

### Actual behaviour
The current view changes to the previous/next day/week/month

### Server configuration
**Calendar version:**
 1.6.4

**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.

### Client configuration
**Browser:**
Firefox 64.0

**Operating system:**
Linux 4.14.91 64 bit NixOS

#### Browser log
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). calendar:1:1
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info. core.js:20:2834
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). vendor.min.js:1:6857
Attempting to call a FullCalendar method on an element with no calendar.
vendor.min.js:1:315150
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://cloud.nextcloud.com/apps/calendar/js/public/vendor.min.js?v=56f4fcc4-0
Source Map URL: vendor.min.js.map[Learn More]
Attempting to call a FullCalendar method on an element with no calendar.
vendor.min.js:1:315150
Attempting to call a FullCalendar method on an element with no calendar.
```

**Comment by Malspherus** [comment]
Using the sidebar CTRL+ENTER doesn't work at all for me, neither in the simple nor in the advanced editor. My calendar version is 2.0.1, would be great to get this functionality back.

**Comment by rubo77** [comment]
> While having the event name in focus press CTRL + ENTER to save the event

doesn't work for me either on Ubuntu Firefox 78

**Comment by st3iny** [comment]
Has been implemented for both editors in the meantime.
