### ISSUE TITLE
Feature Request: Tasks Integration

### ISSUE THREAD

**Issue by alensiljak** [nextcloud/calendar#1067]
Apologies if this has been requested before, I could not find it in the issues list.

### Steps to reproduce
1. Open the calendar in any view

### Expected behaviour
Display Tasks (from Tasks app, not just whole-day events) on the calendar. The tasks are displayed on the task due date. Overdue tasks may also be displayed on today (configurable). This would help track the "floating events" (a concept I know of from Handspring Visor).

The concept is applied in, for example, [aCalendar+](https://play.google.com/store/apps/details?id=org.withouthat.acalendar) Android app.
I found one screenshot that illustrates the concept and the way task items could be displayed:
![image](https://user-images.githubusercontent.com/462445/51177630-6ba0d280-18c0-11e9-9255-6994c248acd1.png)
This approach would work for day and week views. On the month view, the tasks would be displayed just like whole-day events (with the additional check-box, of course).

### Actual behaviour
No tasks are displayed in the calendar at the moment. This requires separate tracking of "floating events"  in the Tasks app.

### Server configuration etc.
Calendar: 1.6.4

The rest is irrelevant.

**Comment by MisterY** [comment]
Ah, thanks. Sorry, I've gone through the list of both open and closed items containing the word "tasks" and "integration" (separately) and haven't seen it. The only conclusion is that I'm blind.
