### ISSUE TITLE
Invite attendees - how to change FROM field in eMail?

### ISSUE THREAD

**Issue by frank-github** [nextcloud/calendar#1092]
Using Nextcloud 15 with calendar 1.6.4

When creating a event with attendees, invitation eMail is coming from "über Nextcloud"
the recipients have no recognition effect, who is "über Nextcloud" (german)

is there any option to change this text, ex. using my name?

**Comment by georgehrke** [comment]
If you set a display name, it will say "Frank via Nextcloud". über is a really bad translation ...

**Comment by frank-github** [comment]
thanks for the quick answer and hint
> If you set a display name
sorry, where can I do this setting ?

**Comment by georgehrke** [comment]
For yourself in the personal settings.
As an admin you can set it for any user in the user settings. :)

**Comment by frank-github** [comment]
Unfortunately I am not a very experienced Nextcloud-Admin  :-(

In the personal setting of nextcloud I do not find any "display name", only "complete name", "eMail", "language", "phone number", ...   (translated by me from german)
Wrong place?

**Comment by georgehrke** [comment]
@frank-github Ok, but that's a server issue. Can you please reopen this issue https://github.com/nextcloud/server/issues using the complete issue template? Thx!
