### ISSUE TITLE
[Feature request] 5 days week

### ISSUE THREAD

**Issue by cl4x** [nextcloud/calendar#1095]
Hi, is possible to have 5 days week view (without Saturday and Sunday)?

TY

![immagine](https://user-images.githubusercontent.com/47188814/52000376-41a10000-24bd-11e9-83d7-8d73cc91cc9c.png)

**Comment by georgehrke** [comment]
#536

**Comment by georgehrke** [comment]
Please look for duplicates before creating new tickets in the future. Thx!

**Comment by cl4x** [comment]
Sorry, I tried but without finding the topic. I did not think it existed.
TY
