### ISSUE TITLE
Improvement for today marker

### ISSUE THREAD

**Issue by der-Daniel** [nextcloud/calendar#1104]
Inspired by the Outlook calendar, I think we can improve the marker for today.
This is what it looks like in Outlook.

![image](https://user-images.githubusercontent.com/7686866/52477015-e055ec80-2ba0-11e9-87a6-e1c0ae92605e.png)

I hacked a little html and came up with this.

```
<td class="fc-day-top fc-fri fc-today " data-date="2019-02-08">
  <div class="fc-day-marker" style="background-color:#0082C9; width: inherit; height: 3px;">
    <span class="fc-day-number" style="font-weight: bold; color:#0082C9">8</span>
  </div>
</td>
```

![image](https://user-images.githubusercontent.com/7686866/52476884-61f94a80-2ba0-11e9-8289-b07a282af895.png)

What do you think?

For Frodo!

**Comment by georgehrke** [comment]
We already improved the visibility of today in https://github.com/nextcloud/calendar/pull/850 :)
Did you see that already?

**Comment by georgehrke** [comment]
> I hacked a little html and came up with this.

As far as i can tell you only added css but didn't change the actual html structure, right?

**Comment by georgehrke** [comment]
cc @skjnldsv @nextcloud/designers

**Comment by der-Daniel** [comment]
> We already improved the visibility of today in #850 :)
> Did you see that already?

Yes, but I don't like the circle thing. So it's more like a different proposal to the today marker.

> > I hacked a little html and came up with this.
> 
> As far as i can tell you only added css but didn't change the actual html structure, right?

Yes, I just edited it with Chrome dev tools. It's more a proposal than pull request :)

**Comment by jancborchardt** [comment]
It does look very nice. :) However we don’t need 2 different colored "Today" markers.

- The solution with the bar has the drawback that it could be confused for the cell above as it’s directly on the border. The circled date is _inside_ the cell.
- The solution with the circled date reflects also what we do in the datepicker for the selected date, which is nicely consistent style.

So while this is really nice work @der-Daniel, the solution in #850 seems more fitting. But design help for Calendar is always welcome, please check out some of the other design issues :slightly_smiling_face:  https://github.com/nextcloud/calendar/issues?q=is%3Aopen+is%3Aissue+label%3Adesign

**Comment by der-Daniel** [comment]
alrighty then
