### ISSUE TITLE
Feature Request: Show Date and Time of calendar events in notification mails

### ISSUE THREAD

**Issue by DrRSatzteil** [nextcloud/calendar#1127]
### Steps to reproduce
1. User 1: Create new calendar entry
2. User 2 (has shared access to calendar of User1): Wait for calendar change notification via e-Mail
3. User 2: Read mail

### Expected behaviour
The mail should contain at least the name of the calendar entry together with the date and time. 

### Actual behaviour
Only the name of the calendar entry is shown (including the time when the entry was added) but not the date and time when the event will take place.

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
7.2

**Server version:** (see your admin page)
15.0.4

**Calendar version:** (see the apps page)
1.6.4

**Updated from an older installed version or fresh install:**
Updated

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/14127#issuecomment-462039632

**Comment by DrRSatzteil** [comment]
Sorry I could not find this issue. Thanks!
