### ISSUE TITLE
Can't delete single date in repeated calendar entry

### ISSUE THREAD

**Issue by scroom** [nextcloud/calendar#114]
Don't know If I should open this issue here or in the owncloud calendar repository. Due to the fact that we (a school) are thinking about changing from OC to NC and are already running a test instance of NC. I'm opening this bug here es well. (I've opened a bug report here as well: https://github.com/owncloud/calendar/issues/755)
### Steps to reproduce
1. Delete a single date in repeated calendar entry

### Expected behaviour
I should be asked whether I want to delete this single event or all the repeated calendar entries.

### Actual behaviour
All repeated calendar entries get deleted.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** mySQL

**PHP version:** PHP 5.5.9-1ubuntu4.17 (cli)

**Server version:** 9.0.4 (stable)

**Calendar version:** 1.4.0

If you need more information please don't hesitate to ask.

**Comment by georgehrke** [comment]
dup

**Comment by georgehrke** [comment]
looking for the original issue ...

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/7
