### ISSUE TITLE
Include more details in calendar notifications

### ISSUE THREAD

**Issue by bovender** [nextcloud/calendar#1142]
### Expected behaviour
The notification that I receive when someone adds an event to our shared calendar should include the date and time of the event.

### Actual behaviour
The notification includes only the name of the person who added the event, the calendar name, and the event title.

### Server configuration
*["You can use the Issue Template application to prefill most of the required information: https://apps.nextcloud.com/apps/issuetemplate" &rarr; This app is not offered for NC 15.]*

**Server version:** (see your admin page)
15.0.4

**Calendar version:** (see the apps page)
1.6.4

**Comment by georgehrke** [comment]
nextcloud/server#14127 (comment)
