### ISSUE TITLE
Improve grid/table in dark mode

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/calendar#1152]
![image](https://user-images.githubusercontent.com/16019165/53675795-74940a80-3c9a-11e9-86c3-ceb4701e6a15.png)

Maybe the same color for the lines as the color for other borders (e.g. Button). Maybe gray and not that thick. 

Currently this looks terrible if you select week or day.

**Comment by raimund-schluessler** [comment]
I would like to add that the today indicator looks quite bright in dark mode as well:

![screenshot-2019-3-4 kalender - nextcloud](https://user-images.githubusercontent.com/2496460/53721469-9ab8d680-3e63-11e9-8e4f-0d7d3a1a03ea.png)

**Comment by bcag2** [comment]
I close #1262 which duplicate this issue.
Here are my screen capture:
https://mycore.core-cloud.net/index.php/apps/gallery/s/G77KskCwum9deUR#

**Comment by georgehrke** [comment]
Dark mode has been vastly improved in #926

![8D9B9554-78E3-40F1-80ED-FA1D998E6059](https://user-images.githubusercontent.com/1250540/67145600-04ff7980-f283-11e9-8a7c-6674328d6422.png)
![A5423C50-49DD-4293-88EA-6EA1D83A0E58](https://user-images.githubusercontent.com/1250540/67145628-3aa46280-f283-11e9-9393-97375869b732.png)
