### ISSUE TITLE
Problem importing a calendar

### ISSUE THREAD

**Issue by charlescurley** [nextcloud/calendar#1162]
### Steps to reproduce
1. Import the attached icalendar file.

The attached file is extracted from a file with more than 700 events in it. All of the rest import successfully. Also, both this extract and the whole kazoo validate at https://icalendar.org/validator.html

### Expected behaviour
Event should import and display.

### Actual behaviour
NextCloud reports one failure to import.

## Server configuration detail

**Operating system:** Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** sqlite3 3.16.2

**PHP version:** 

7.0.33-0+deb9u3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 14.0.6 - 14.0.6.0

**Updated from an older Nextcloud/ownCloud or fresh install:** update

**Where did you install Nextcloud from:** upgrades from inside nextcloud.

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.4
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.8
 - dav: 1.6.1
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.8
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - unsplash: 1.1.3
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud",
        "nextcloud.localdomain",
        "localhost",
        "localhost.localdomain",
        "wli.ddns.info",
        "dzur",
        "dzur.localdomain"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/dzur.localdomain\/nextcloud",
    "dbtype": "sqlite3",
    "version": "14.0.6.0",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "production"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Vivaldi	2.3.1440.60 (Stable channel) (64-bit)  Note: log reports it as: ->192.168.10.1 - - [11/Mar/2019:15:55:19 -0600] "DELETE /remote.php/dav/calendars/charles/the-libertarian-calendar-1/ HTTP/1.1" 204 80 7 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36 Vivaldi/2.3.1440.60 "<-

**Operating system:** Debian 9.8 (stretch)

## Logs

<details><summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...

PUT https://wli.ddns.info:17800/remote.php/dav/calendars/charles/the-libertarian-calendar-1/Nextcloud-TV2RDS1XVR881A3R8TBCI8.ics 415 (Unsupported Media Type)
request @ core.js?v=e6cbd035-0:5729
create @ app.js:6149
(anonymous) @ app.js:1163
ve @ vendor.js:125
n @ app.js:1162
(anonymous) @ app.js:1211
Promise.then (async)
i.import @ app.js:1206
fn @ VM216:4
t @ vendor.js:13585
$eval @ vendor.js:10391
$apply @ vendor.js:10414
(anonymous) @ vendor.js:13589
dispatch @ core.js?v=e6cbd035-0:3
r.handle @ core.js?v=e6cbd035-0:3
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

From nextcloud-access.log

192.168.10.1 - - [11/Mar/2019:15:55:19 -0600] "DELETE /remote.php/dav/calendars/charles/the-libertarian-calendar-1/ HTTP/1.1" 204 807 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36 Vivaldi/2.3.1440.60"
192.168.10.1 - - [11/Mar/2019:15:55:24 -0600] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 975 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36 Vivaldi/2.3.1440.60"
192.168.10.1 - - [11/Mar/2019:15:55:24 -0600] "GET /index.php/csrftoken HTTP/1.1" 200 1164 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36 Vivaldi/2.3.1440.60"
192.168.10.1 - - [11/Mar/2019:15:55:33 -0600] "MKCOL /remote.php/dav/calendars/charles/the-libertarian-calendar-1/ HTTP/1.1" 201 823 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36 Vivaldi/2.3.1440.60"
192.168.10.1 - - [11/Mar/2019:15:55:33 -0600] "PROPFIND /remote.php/dav/calendars/charles/the-libertarian-calendar-1/ HTTP/1.1" 207 2692 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36 Vivaldi/2.3.1440.60"
192.168.10.1 - - [11/Mar/2019:15:55:33 -0600] "PUT /remote.php/dav/calendars/charles/the-libertarian-calendar-1/Nextcloud-TV2RDS1XVR881A3R8TBCI8.ics HTTP/1.1" 415 979 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36 Vivaldi/2.3.1440.60"
192.168.10.1 - - [11/Mar/2019:15:55:33 -0600] "REPORT /remote.php/dav/calendars/charles/the-libertarian-calendar-1/ HTTP/1.1" 207 941 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36 Vivaldi/2.3.1440.60"

```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...

PUT https://wli.ddns.info:17800/remote.php/dav/calendars/charles/the-libertarian-calendar-1/Nextcloud-TV2RDS1XVR881A3R8TBCI8.ics 415 (Unsupported Media Type)
request @ core.js?v=e6cbd035-0:5729
create @ app.js:6149
(anonymous) @ app.js:1163
ve @ vendor.js:125
n @ app.js:1162
(anonymous) @ app.js:1211
Promise.then (async)
i.import @ app.js:1206
fn @ VM216:4
t @ vendor.js:13585
$eval @ vendor.js:10391
$apply @ vendor.js:10414
(anonymous) @ vendor.js:13589
dispatch @ core.js?v=e6cbd035-0:3
r.handle @ core.js?v=e6cbd035-0:3
</details>

[bgd.ics.txt](https://github.com/nextcloud/calendar/files/2954436/bgd.ics.txt)

**Comment by georgehrke** [comment]
As far as i can tell, this was a bug in an earlier version of Sabre/DAV.
I can no longer reproduce this bug with Nextcloud 17, it imports just fine.

![E227D8E1-D6B2-4CFB-8BF6-9EBD2F2B6C6A](https://user-images.githubusercontent.com/1250540/67160420-ca641280-f350-11e9-93fc-57958bb581a3.png)
