### ISSUE TITLE
Better look for multiple days event with specific start and end hours

### ISSUE THREAD

**Issue by NastuzziSamy** [nextcloud/calendar#1163]
### Expected behaviour
It would be better if for an event, starting at a specific hour of a day and ending 5 days after at a specific hour is spliting and for the full 4 days, printed in the full day section, not as it is now

### Actual behaviour
![Screenshot_2019-03-12 Agenda - Nastuzzi](https://user-images.githubusercontent.com/24639904/54204605-d3485800-44d4-11e9-85d5-abdaabdc467b.png)

**Comment by georgehrke** [comment]
@NastuzziSamy Can you please report this upstream at https://github.com/fullcalendar/fullcalendar/

Thx!
