### ISSUE TITLE
Confusing RRULE message

### ISSUE THREAD

**Issue by sciurius** [nextcloud/calendar#1166]
### Steps to reproduce

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20190114T180613Z
LAST-MODIFIED:20190114T180613Z
DTSTAMP:20190114T180613Z
UID:s4rbinws-dvja-8ogc-rpo0-fmhuu5uqp5r6
SUMMARY:Sessie Steendam
RRULE:FREQ=MONTHLY;UNTIL=20191231T130000Z;BYDAY=3SA
EXDATE:20190216T130000Z
TRANSP:OPAQUE
STATUS:TENTATIVE
CLASS:PUBLIC
DTSTART;TZID=Europe/Amsterdam:20190119T140000
DTEND;TZID=Europe/Amsterdam:20190119T170000
LOCATION:Steendam
END:VEVENT
PRODID:-//Inf-IT//InfCloud 0.13.2rc1//EN
END:VCALENDAR
```

### Expected behaviour

The entry is shown on every last saturday of the month.

### Actual behaviour

The entry is shown on the monthly view in grey.
The defails pane shows "This event's repeating rule is not supported yet."
However, it seems that the occurrences are shown correctly giving the impression that this form of `RRULE` is already supported.

**Comment by georgehrke** [comment]
Editing that RRULE is not yet supported. So your only option is to reset it and add a new rrule

**Comment by sciurius** [comment]
Even though **editing** may not be supported yet, the rule seems to **work** correctly.
Resetting it does not allow anything similar to be set, so the repetition gets lost.

**Comment by georgehrke** [comment]
Exactly
