### ISSUE TITLE
No option to share the automatically generated birthday calendar

### ISSUE THREAD

**Issue by UserXH726** [nextcloud/calendar#1167]
### Steps to reproduce
1. Create a birthday value in a contact in Contacts App
2. An automatically created birthday calendar will appear in the calendar app.
3. Try to share the calendar the known way you share normal calendars.

### Expected behaviour
A share option.

### Actual behaviour
No share option

### Nextcloud
NC 15.0.5
Calendar 1.6.4
Contacts 3.0.5

**Operating system**:
Debian 8

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
7.0

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/2172

**Comment by UserXH726** [comment]
There is a misunderstanding.
I would like to share the birthday calendar without sharing the contacts.

**Comment by georgehrke** [comment]
Ah sorry.
But this is the wrong repository anyway.

Issues not exclusive to the web app belong to the server repo: https://github.com/nextcloud/server/issues
