### ISSUE TITLE
[Feature request] Activities created for calendar events should contain a link to the created/modified resource

### ISSUE THREAD

**Issue by j-ed** [nextcloud/calendar#1171]
### Expected behavior
For each calendar event, which has been created or modified, and activity is created, like e.g.
```
Sie haben das Ereignis *Geburtstagsfeier* im Kalender *Juergen* aktualisiert.
```
It should be possible to click on the name of the event (*Geburtstagsfeier*) and the name of the calendar (*Juergen*) and directly jump to the relevant resource, similar as it is handled for files and folders. 

### Actual behavior
All created calendar activities are created as pure text and didn't contain any link to the related event and calendar. This makes it difficult to identify the created or modified event because of possible duplicate names being used.

### Steps to reproduce
1. Open the calendar app and create an event.
2. Open the activities app and check-out the created activity of the event.
   **-> no link to the modified resource can be found in the activity.**

#### Server Configuration
OS: Linux 3.16.62
Web server: Apache2 2.4.37
Database: MariaDB 10.2.22
PHP version: 7.2.14
Nextcloud version: 15.0.5
Calendar app: 1.6.4

#### Client Configuration
Browser: Mozilla Firefox 65.0.2
Operating system: Windows 10

**Comment by tcitworld** [comment]
Same as https://github.com/nextcloud/activity/issues/170, needs https://github.com/nextcloud/calendar/issues/21 and v2.x

**Comment by j-ed** [comment]
@tcitworld Wow, it's always interesting under which subjects an issue is can be locked. I've searched the open issues in advance but didn't find the mentioned one.

**Comment by tcitworld** [comment]
Don't feel bad, Github search is pretty useless. 😄
