### ISSUE TITLE
Remove the warning that email reminders are not implemented

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#1172]
According to NC version in which https://github.com/nextcloud/server/pull/3044 will be released.

**Comment by vc7ee** [comment]
If anyone has more time, the warning could only be shown, when email is not configured on the admin side, tough highly unlikely.

**Comment by tcitworld** [comment]
There's also an option to enable the sending of these specific reminder emails.

**Comment by georgehrke** [comment]
There no longer is a warning since #926
