### ISSUE TITLE
[New Event] Default used calendar to previously used calendar

### ISSUE THREAD

**Issue by arthurlutz** [nextcloud/calendar#1174]
Follow up of #1173 

### Expected behaviour

1. Create Event, defaults to calendar A 
2. Create Event on Calendar B (manual switch)
3. Create Event defaults to calendar A

### Actual behaviour

1. Create Event, defaults to calendar A 
2. Create Event on Calendar B (manual switch)
3. Create Event defaults to calendar B
4. Create Event defaults to calendar B
5. Create Event on Calendar A (manual switch)
6. Create Event defaults to calendar A

### Versions

Nextcloud 13.0.6
Calendar 1.6.1

**Comment by georgehrke** [comment]
Duplicate of #9 

The first in the list will always be the default one.
