### ISSUE TITLE
Calendar interface unresponsive

### ISSUE THREAD

**Issue by Hrafnthor** [nextcloud/calendar#118]
### Steps to reproduce
1. Fresh installation of NextCloud as per [instructions from manual](https://docs.nextcloud.com/server/10/admin_manual/installation/source_installation.html)
2. Installation of Calendar from within NextCloud's app section.

### Expected behaviour
Calendar interface responding to clicks, displaying event creation dialog.

### Actual behaviour
No response from main calendar window. Side bar works for changing granularity of main calendar window and creating new calendars. No response on main calendar window.

### Server configuration
**Operating system**:
Linux - Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL 5.7.15

**PHP version:**
7.0.8

**Server version:** 
Nextcloud 10.0 (stable)

**Calendar version:** 
1.4.0

**Updated from an older installed version or fresh install:**
Fresh

Signing status:
No errors have been found.

**Are you using encryption:** yes/no
Yes

### Client configuration
**Browser:**
Firefox 49.0
Chome 53.0.2785.89 (64-bit)

**Operating system:**
Linux - Ubuntu 16.04

#### Browser log
The following happens on main window click
```
19:59:01.086 TypeError: component is null
Component.prototype.addSubcomponent()ical.js:2498
date()app.js:3175
patch()app.js:3287
VEvent.fromStartEnd()app.js:3661
select()app.js:235
trigger()fullcalendar.js:10114
FC.View<.trigger()fullcalendar.js:7821
FC.View<.triggerSelect()fullcalendar.js:8698
FC.View<.reportSelection()fullcalendar.js:8692
FC.Grid<.buildDayDragListener/dragListener<.interactionEnd()fullcalendar.js:3486
FC.DragListener<.trigger()fullcalendar.js:2528
FC.DragListener<.handleInteractionEnd()fullcalendar.js:2324
HitDragListener<.handleInteractionEnd()fullcalendar.js:2878
FC.DragListener<.endInteraction()fullcalendar.js:2311
.proxy/f()jquery.min.js:2
n.event.dispatch()jquery.min.js:3
n.event.add/r.handle()jquery.min.js:3
1ical.js:2498:1

**Comment by georgehrke** [comment]
Please open your browsers developer console and execute:
`jstz.determine().name()`;

If that returns UTC or ETC/UTC, this will be fixed with https://github.com/nextcloud/calendar/pull/69

**Comment by georgehrke** [comment]
most certainly a dup of https://github.com/nextcloud/calendar/issues/35

**Comment by Hrafnthor** [comment]
Return values are
"Etc/UTC"

So I'll wait for the update. Thx!

**Comment by georgehrke** [comment]
> So I'll wait for the update. Thx!

Yes :/
I'm sorry for the inconvenience. I'm afraid, but I don't know of any workaround for iceland at the moment.
