### ISSUE TITLE
Add more contrast to today's color

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#119]
It's difficult to distinguish on some screens.
![](https://framagit.org/framasoft/framagenda/uploads/825e479ee52a796f53433063e2419f59/white-on-white.png)

cc @raghunayyar @jancborchardt

**Comment by moy** [comment]
(I'm the one who reported in locally to framagenda, thanks @tcitworld for reporting upstream)

My initial problem is not today's color (i.e. yellow), but the grey grid is barely readable on my screen (very light grey on white background). #f8f8f8 on white background is really looking for trouble. In comparison, GitHub uses #dddddd (RGB 221) for most grey lines, and #eeeeee sometimes.

**Comment by tcitworld** [comment]
Sorry for misreading original issue. The css used here is the one from [fullcalendar](https://github.com/fullcalendar/fullcalendar) (so you might be interested in reporting the issue to them too), but we can override it here anyway.

**Comment by jancborchardt** [comment]
Thing is that the grid is not _that_ important. The whitespace is enough to distinguish, no? Like when you have events in there, it’s quite clear which time and especially the day they belong to. Often too visible grids distract from the real content more than helping.

**Comment by moy** [comment]
It *is* important. When I create an event on friday, I want to be able to drag&drop from the right time to the right time. For now, I essentially click blindly and cancel until I hit the right time. How do you create events without seeing the grid?

You may have a screen with bigger pixels than mine, but for me the lines are very thin, and really really hard to see (in normal sitting position, I don't see at all the half-hour lines, I have to bend forward to see them). And I have reasonably good eyes and tested both on a calibrated and non-calibrated monitor. Imagine the pain for someone with less good eyes than me, or another monitor.

**Comment by jancborchardt** [comment]
@moy thanks for describing your specific use-case! :) So for that what I find much easier is the already present time indicator on the event itself when drag&dropping:
![capture du 2016-10-19 10-59-35](https://cloud.githubusercontent.com/assets/925062/19512264/594fe04e-95eb-11e6-9412-2bb86f9e498e.png)
Instead of needing to check on the left bar for the time (which is far away and even hard to correlate the time _with_ thicker lines) you directly have it there.

**Comment by moy** [comment]
There's no time when you *create* the event, which is the use-case I described. You just have to guess where to start your drag&drop if you don't see the grid. Or you can do trial and error: click, oops, wrong time, try later. Click again, Oops, too early. Click again, bingo that's it.

And please, don't call "creating an event" a "specific use-case". There's nothing specific, really. Users want to create events or they wouldn't use a calendar.

**Comment by jancborchardt** [comment]
@moy you are completely right – I checked again and the grid lines are actually way lighter than in Files and user management. I adjusted the full-hour gridlines to the #eee used there. Please review the pull request at https://github.com/nextcloud/calendar/pull/140

And thanks a lot for the testing & feedback, sorry for the confusion! :)
