### ISSUE TITLE
Webcall address point to another domain

### ISSUE THREAD

**Issue by danicotillas** [nextcloud/calendar#1198]
### Steps to reproduce
1. I enter into the link to share the calendar.
2. I click on subscribe --> https://caracol.nodocomun.org/index.php/apps/calendar/p/Xoy8TstZCH9NnCM5/Nodo-Comn-Madrid
3. It goes to another domain. Instead of caracol.nodocomun.org it goes to pony.nodocomun.org.

**NOTE:** I use Nextcloud installation through Softacullous on a CPanel. Few months ago I was unable to update my Caracol install so I tried a new one called Pony on that second subdomain. Finally I could update Caracol and delete everything about Pony but now this bug has appeared.

### Expected behaviour
When you click on Subscribe it should remain on the caracol.nodocomun.org domain

### Actual behaviour
When you click on the Subscribe button it goes to pony.nodocomun.org

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Server version:** (see your admin page)

**Calendar version:** (see the apps page)

**Updated from an older installed version or fresh install:**

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by tcitworld** [comment]
That's not a calendar issue, probably an issue with your `config/config.php` or your vhost config.

**Comment by georgehrke** [comment]
@danicotillas If you need help resolving your issue, please ask on help.nextcloud.com
