### ISSUE TITLE
[feature request] Default Settings for Events (maybe by Calendar)

### ISSUE THREAD

**Issue by Pit-Storm** [nextcloud/calendar#1199]
Hi you all,

there is a big usability issue I would like to drop here. It should be possible to set a default behaviour of some settings of an event. Like Visibility to other users, default length of event. default calendar, default notification (see also #629 ) and others.

This should basically be able to set for the whole app, better would be specific for every calendar.

Thank you and kind regards.

**Comment by vallant** [comment]
I would love to see this feature!
Especially the possibility to choose the default calendar for events i'm missing very much.

**Comment by rkaraba** [comment]
The possibility to choose the default calendar would by indeed nice.
Like in Tasks where you can set Default list in settings

**Comment by georgehrke** [comment]
> there is a big usability issue I would like to drop here. It should be possible to set a default behaviour of some settings of an event. Like Visibility to other users, default length of event. default calendar, default notification (see also #629 ) and others.

**Comment by georgehrke** [comment]
> there is a big usability issue I would like to drop here. It should be possible to set a default behaviour of some settings of an event. Like Visibility to other users, default length of event. default calendar, default notification (see also #629 ) and others.

If you want specific options, please open a ticket individually. For the most things you requested there are already tickets ...

There are not gonna be individual settings for each calendar.
Please take some time and read this blog post: __[Choosing our preferences](https://ometer.com/preferences.html)__
