### ISSUE TITLE
User session expiration

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#1215]
See https://github.com/nextcloud/calendar/blob/master/controller/settingscontroller.php#L59

If `$userSession->getUser()` returs null, we have
```
Error: Call to a member function getUID() on null
```
The fix in is the vue branch
```php
$user = $userSession->getUser();
if ($user) {
  $this->userId = $user->getUID();
}
```

Even better would be to throw an appropriate exception, because it doesn't seem to be handled further down.

**Comment by georgehrke** [comment]
Implemented in https://github.com/nextcloud/calendar/pull/926

We don't use UserSession anymore. Where necessary, we inject `$userId` via DI directly.
