### ISSUE TITLE
Sharing URL contains a '#'

### ISSUE THREAD

**Issue by moy** [nextcloud/calendar#122]
### Steps to reproduce
1. Open the calendar => the URL looks like https://framagenda.org/index.php/apps/calendar/#
2. Add `#` to the end of the URL (some action do that automatically, but I can't find which one). The URL fragment does not impact the content, the full URL is now https://framagenda.org/index.php/apps/calendar/#
3. Share a calendar with public link, click the link icon

### Expected behaviour
The shared agenda should open with a URL like https://framagenda.org/index.php/apps/calendar/public/LQKQ2300PHASQ4MP

### Actual behaviour
The URL is incorrectly computed : `https://framagenda.org/index.php/apps/calendar/#/public/LQKQ2300PHASQ4MP` (notice the `#` in the middle). The private agenda is displayed instead.

I guess the code computing the URL did a string concatenation without stripping the URL fragment.

### Server configuration
I'm not the admin, but it's the framagenda instance (i.e. AFAIK version close to Git master)

**Comment by tcitworld** [comment]
Fixing it right now.

**Comment by tcitworld** [comment]
Fixed. Will update framagenda asap.
