### ISSUE TITLE
Add android style time picker

### ISSUE THREAD

**Issue by pbartyik** [nextcloud/calendar#1245]
This isn't a bug, but a feature request, if this isn't the right forum to ask so, please redirect me towards the correct channel.

Would be nice to have an android style time picker upon creating an event, as it would be more user friendly than the current one.

Current one:
![current time picker](https://user-images.githubusercontent.com/39059618/56658542-277d5500-669b-11e9-9574-c1609d5bcb6e.png)

Android time picker (more ergonomic):
![androittimepicker](https://user-images.githubusercontent.com/39059618/56658569-3f54d900-669b-11e9-963c-9eab4c81f112.png)

[Gif showing how it would work.](https://dragablz.files.wordpress.com/2015/04/clockdemo.gif) (24/12 HR notations should be inherited from general settings)

**Comment by georgehrke** [comment]
cc @nextcloud/designers 

@skjnldsv Was there a ticket about time-pickers in the server?

**Comment by skjnldsv** [comment]
@georgehrke no, but we have a new time picker already with the components :)

**Comment by georgehrke** [comment]
@skjnldsv Should we move this ticket to the vue components repo then? 

The same time picker should be used in all places imho.

**Comment by skjnldsv** [comment]
I'd say the new one is quite an enhancement already, so I think we should close this one?

**Comment by jancborchardt** [comment]
Yeah – the old one in the screenshot above looks bad, but the Android one is confusing as people don’t really use circular clocks anymore.

@skjnldsv can’t find a screenshot of the timepicker in the vue-components, is there any? :)

**Comment by georgehrke** [comment]
@jancborchardt See https://github.com/nextcloud/nextcloud-vue/pull/150 :)

**Comment by jancborchardt** [comment]
Right, there it was, thanks @georgehrke!

@skjnldsv what do you think about having a screenshot or gif of each component in the readme?

**Comment by georgehrke** [comment]
I will close this ticket. As @jancborchardt said, the Android one is confusing. I can only concur. I, as an iPhone user, often struggle with the time picker when using Android like once or twice a year.

The calendar app 2.0 will use the date picker shown in nextcloud/nextcloud-vue#150, which is more intuitive than the one we currently use.

**Comment by georgehrke** [comment]
Just as an addition: The android-clock is pretty america-centric. Most of the world is using 24 hour clocks: https://travel.stackexchange.com/a/34951

@pbartyik If you see any usability issues or have possible enhancements for the time-picker shown in https://github.com/nextcloud/nextcloud-vue/pull/150, please open a ticket in https://github.com/nextcloud/nextcloud-vue/issues

**Comment by skjnldsv** [comment]
> @skjnldsv what do you think about having a screenshot or gif of each component in the readme?

See https://github.com/nextcloud/nextcloud-vue/pull/272 :wink:

**Comment by pbartyik** [comment]
@georgehrke thanks, might open an issue there to get an optional 'android' style clock. I'm based in Europe, the picker works with 24 hours format as well, the gif I linked was for sake of principle of working, not an actual expectation :) I use a regular face watch (circular, not numeric), thus this format is more intuitive for me.

**Comment by skjnldsv** [comment]
> @georgehrke thanks, might open an issue there to get an optional 'android' style clock.

Please do after testing the new on (see latest contacts release for example)
We can do some improvements, but the clock design is out of scope for now. :/
Far too complicated to implemented ourselves and we're already deeply using another plugin! :)
