### ISSUE TITLE
feature request: new view: 4 weeks

### ISSUE THREAD

**Issue by singular-error** [nextcloud/calendar#1247]
Using Calendar 1.6.5

Actually there are 3 views: day / week / month

Like google-calendar, i'd like to have "4 weeks"-view.
The actual week then is always the top line.

Instead of the month-view, you always see the actual week and the next 3 weeks. That's imho relevant. 

+ you always see the actual week on top line of the page
+ you don't have to search 'today' on the whole page
+ you always see the next coming up 3 weeks
+ you're not overloaded with events in the past
+ view of a single day is big enough to see most events of that day

This would be very awsome. Thanks.

**Comment by georgehrke** [comment]
Closing in favour of #6 

Everything you asked for will be solved by #6 as well.
