### ISSUE TITLE
Timewarp when crossing DST in effect/DST not ineffect

### ISSUE THREAD

**Issue by jgrete** [nextcloud/calendar#125]
### Steps to reproduce
1. Create a new calendar entry (daily, at 3pm,repeat for ever) when DST is in effect (do this on 
    different devices and synchronize)
2. Look at the entries when DST has ended

### Expected behaviour
Whatever was the device you entered the time of all entries should be the same DST or not DST.

### Actual behaviour
In my timezone (Berlin: UTC+1h) the entries are deferred one hour (3pm@DST in effect becomes 4pm@DST not in effect) if enter the repeated entry on a smartphone synching via CalDAV (tried with 2 apps CalDAV and DavDroid).
When using the calender app itself all entries are OK

### Server configuration

**Web server:**
apache2

**Database: **
mariadb  10.0.22

**PHP version:**
5.6.26
**Server version:** (see your admin page)
nextcloud 10.0.1
**Calendar version:** (see the apps page)
1.4.0
**Updated from an older installed version or fresh install:**
Updated from 10.0.0
**Signing status (ownCloud/Nextcloud 9.0 and above):**
??
```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**
CalDAV and DAVDroid

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
Can you please provide an example ics file that was created with DavDroid?
I don't own an Android device

**Comment by jgrete** [comment]
OK, this is the contents:
```
BEGIN:VCALENDAR
PRODID:aCalendar
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
SUMMARY:TestTermin angelegt in a Calendar 
DTSTART:20161016T130000Z
DTEND:20161016T140000Z
RRULE:FREQ=DAILY
UID:20161013T093000Z-871@acalendar
DTSTAMP:20161013T093000Z
END:VEVENT
END:VCALENDAR
```
I do know much about ics-files but here the reference time seems to be zulu
and the DTSTART/DTEND seems to be correct (2h difference, DST in effect)

Juergen

**Comment by georgehrke** [comment]
Well, that's a bug in aCalendar then. 

> 20161016T130000Z

This time doesn't know any timezone. It's always 1pm in GMT.
In CEST that's 3pm and in CET thats 2pm.

It would work if it was `DTSTART;TZID=Europe/Berlin:20161016T150000

**Comment by jgrete** [comment]
Ok, thank you, I'll contact the author of aCalendar
Jürgen
