### ISSUE TITLE
Left and right arrows missing on main datepicker

### ISSUE THREAD

**Issue by nfp0** [nextcloud/calendar#1255]
### Steps to reproduce
1. Open calendar app
2. Verify that the main date picker has no arrows (see pic bellow), even though they are clickable.

![image](https://user-images.githubusercontent.com/11202422/56996498-a0e5dd80-6b9c-11e9-8120-50867390c493.png)

### Expected behaviour
Arrows should show up.

### Actual behaviour
Arrows don't show up.

### Server configuration

**Operating system**: ARMBIAN 5.73

**Web server:** 
**Database:**
**PHP version:**
All the defaults of the Nextcloud SNAP.

**Server version:** Nextcloud 15.0.7 SNAP version

**Calendar version:** 1.6.5 (bug was also present on previous versions)

### Client configuration
**Browser:** Bug verified on latest Firefox and Edge

**Operating system:** Windows 10 1809

#### Web server error log
```
[nextcloud.log](https://github.com/nextcloud/calendar/files/3133269/nextcloud.log)
```

**Comment by tcitworld** [comment]
Could you also provide informations on screen resolution, browser modules, eventual theme changes ?

**Comment by nfp0** [comment]
Yes of course!

Screen resolution is 1920x1080.
I believe I have never changed the theme, so it must be the default. Where can I check this?
I have tested this on 3 different browsers on 2 different computers. 2 Firefoxes and 1 Edge. The arrows never show up in any browser so it must be an issue server-side.

**Comment by nfp0** [comment]
I did no updates at all, so I don't know what fixed it (maybe a reboot), but the arrows are back to normal.
I'm closing this issue as no one else seems to have this problem.
