### ISSUE TITLE
dark theme, active days in white, it is too strong, especially on week view

### ISSUE THREAD

**Issue by bcag2** [nextcloud/calendar#1262]
Improvement ask (not bug):
with calendar 1.6.5 (with nextcloud 15)
I use dark theme.
I usually use _week view_, and the current day (a column) is displayed with white background. 
A gray background should be best!

**Comment by tcitworld** [comment]
Could you provide a screenshot ?

**Comment by BornToBeRoot** [comment]
https://github.com/nextcloud/calendar/issues/1152

**Comment by bcag2** [comment]
Right, duplicate #1152
