### ISSUE TITLE
no way to choose default calendar

### ISSUE THREAD

**Issue by tessus** [nextcloud/calendar#1268]
### Steps to reproduce
1. Open calendar app
2. Click on a day to create an entry

### Expected behaviour
The default calendar should be picked.
There's no way to choose and set a default calendar.

### Actual behaviour
The first calendar in the list is picked, which is the last calendar that had been created.

## Server configuration detail

**Operating system:** Linux

**Webserver:** Apache/2.4.39

**Database:** mysql 5.6.25

**PHP version:** 

7.2.18
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gnupg, SPL, hkct, ibm_db2, iconv, session, intl, json, mbstring, standard, mysqlnd, pcntl, PDFlib, mysqli, PDO, pdo_ibm, pdo_mysql, pdo_sqlite, Phar, posix, readline, Reflection, imap, shmop, SimpleXML, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, cgi-fcgi, apcu, imagick, mongodb, igbinary, sodium, redis, mcrypt, luasandbox, Zend OPcache

**Nextcloud version:** 15.0.7 - 15.0.7.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 14.0.10

**Where did you install Nextcloud from:** updater.phar

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - admin_audit: 1.5.0
 - announcementcenter: 3.4.1
 - apporder: 0.6.0
 - bookmarks: 1.0.2
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - contacts: 3.1.1
 - dav: 1.8.1
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_external: 1.6.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notes: 2.6.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - phonetrack: 0.5.0
 - provisioning_api: 1.5.0
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - systemtags: 1.5.0
 - tasks: 0.9.8
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - twofactor_totp: 2.1.2
 - twofactor_u2f: 2.1.3
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - activitylog
 - encryption
 - files_markdown
 - support
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "15.0.7.0",
    "installed": true,
    "forcessl": true,
    "loglevel": 2,
    "maintenance": false,
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "share_folder": "\/Shared",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logdateformat": "Y-m-d H:i:s O",
    "logtimezone": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "appstore.experimental.enabled": true,
    "trashbin_retention_obligation": "auto",
    "updater.release.channel": "production",
    "htaccess.RewriteBase": "\/",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "auth.bruteforce.protection.enabled": false,
    "theme": "",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0

**Operating system:** macOS 10.14.4

## Logs

Nothing in the logs.

**Comment by georgehrke** [comment]
Closing in favour of #9 

The default calendar should always be the top one

**Comment by tessus** [comment]
@georgehrke my point was that the default calendar was not the top one and also that there is no default calendar. so was my report a duplicate? the issue you referenced (the 3y old one) is about sorting the calendar list.

My issue was that when creating an event a random calendar is picked and I have to manually pick the "default" one (the one that waws created first).

**Comment by georgehrke** [comment]
Im against introducing a dedicated option field for the default calendar, but the default calendar selected in the editor will always be the first one In the list. So by making the list sortable, you can select the default one by moving it to the first position in the list.

**Comment by tessus** [comment]
Ah, I see. Somehow #9 seems dead though.

**Comment by georgehrke** [comment]
Nope, it’s still open and assigned to a milestone. Maybe we will even put it in 2.0.0 not sure
