### ISSUE TITLE
Do not add a task list

### ISSUE THREAD

**Issue by marbetschar** [nextcloud/calendar#1270]
### Steps to reproduce
1. Open the Nextcloud web interface
2. Navigate to the calendar 
3. Create a new calendar
4. Navigate to the Tasks
5. You'll see a task list was added with the same name as the added calendar

### Expected behaviour

No task list was added. Adding a calendar should not add itself as a task list.

### Actual behaviour

The same calendar object seems to be shown in calendar and task modules. This leads to unexpected behaviors such as when a calendar is deleted, all tasks of it are gone too. Or if the task list is deleted, all calendar events are suddenly missing. 

This issue is probably related to: https://github.com/nextcloud/tasks/issues/212

### Server configuration

https://cloud.linuxfabrik.io

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/8625
