### ISSUE TITLE
URL violates local access rules (NC 15.0.7 Calendar 1.6.5 "german")

### ISSUE THREAD

**Issue by gschenck** [nextcloud/calendar#1277]
### Steps to reproduce
1.   click "neues Abonnement" (new subscription)
2.   Type in `https://fcal.ch/privat/fcal_holidays.ics.php?hl=de&klasse=4&geo=3073`

### Expected behaviour
the subscipted calendar should appear

### Actual behaviour
Error mesage: "URL violates local access rules"

### Server configuration
- NC 15.0.7 
- Calendar 1.6.5 
- german locale

### How to fix
change in proxycontroller.php
`preg_match('/(^127\.)|(^192\.168\.)|(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)|(^::1$)|(^[fF][cCdD])/', $host)) {`

to 

`preg_match('/(^127\.)|(^192\.168\.)|(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)|(^::1$)|(^[fF][cCdD][0-9a-fA-F][0-9a-fA-F]:)/', $host)) {`

**Comment by lorenalexm** [comment]
Can confirm that this is present with English locale as well, though using an internal address instead of a properly mapped domain. Time has not allowed testing the preposed fix.

URL: http://192.168.3.54:7878/feed/calendar/Radarr.ics?apikey={redacted}
Error: "URL violates local access rules"

**Comment by ChadOhman** [comment]
I'm also seeing this issue.

`http://10.0.0.21:9283/api/calendar/ical?secret=yHagsNfCTQPyguodNxS************************`
Error: "URL violates local access rules"

**Comment by georgehrke** [comment]
@lorenalexm @ChadOhman In case you want to allow access to the local network, you have to set 
`php occ config:app:set dav webcalAllowLocalAccess --value yes`

**Comment by CaptAintHere** [comment]
Hitting same issue when trying to add `https://fcal.ch/privat/fcal_holidays.ics.php?hl=fr&klasse=4&geo=1066`. Your workaround works @gschenck, thank you!
