### ISSUE TITLE
Publish nightly builds to the new app store

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#129]
Use the API through Travis to publish nightly builds. Let's see how other apps do it...
https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#publish-a-new-app-release

**Comment by ChristophWurst** [comment]
I think we'd have to upload the private key to make that possible with the current app store implementation

> signature: A SHA512 signature over the archive using the app’s certificate, can be created using:
> openssl dgst -sha512 -sign ~/.nextcloud/certificates/APP_ID.key /path/to/app.tar.gz | openssl base64

@BernhardPosselt any idea how to solve this? Can we drop the signature requirement for nightly builds somehow to automate the process?

**Comment by BernhardPosselt** [comment]
I think you can encrypt stuff with travis' public key.

**Comment by BernhardPosselt** [comment]
Apart from that I'm unsure if its a good idea to use travis to publish releases. Your project is hosted in a container only with thousands of others. Seems like a high risk

**Comment by ChristophWurst** [comment]
So what's your solution for News? Will you publish nightly builds?

What are the alternatives to using Travis?

**Comment by BernhardPosselt** [comment]
As for App Store credentials: you can add co-maintainers (currently only in the admin interface) that can be used to upload your releases. That way if your token leaks, people do not have access to your account but only to the nightly account.

As for the certificate and News: currently no plans to publish nightlies but I'll probably do it on my own server.

**Comment by BernhardPosselt** [comment]
I don't think dropping signing from nightlies is a good idea since everything that may be present is harder to implement for API consumers and the signatures also act like a checksum

 @LukasReschke

**Comment by tcitworld** [comment]
For now it's on @Gomez's servers https://github.com/nextcloud/calendar/pull/81 but I thought it would be better for everyone to have them on the app store.

**Comment by BernhardPosselt** [comment]
PS: only one nightly build is currently stored on the store. Older nightlies will be deleted.

**Comment by georgehrke** [comment]
@BernhardPosselt Is there a plan to allow users to choose release channels for apps?
So you can either use the latest stable calendar release or the latest nightly release?

If not, what was the purpose of implementing nightlies in the app store (no offense)

**Comment by BernhardPosselt** [comment]
The machinery is there, it just has to be implemented in the server. From what I can see the implementation for 11 will be pretty basic because people were short on time. 

cc @LukasReschke

**Comment by georgehrke** [comment]
@BernhardPosselt @LukasReschke looking at the latest master, there is no way to choose a release channel for an app. Are there still plans to implement it?

**Comment by BernhardPosselt** [comment]
@georgehrke personally I don't have any plans to work on the server component.

**Comment by BernhardPosselt** [comment]
@georgehrke is there a ticket in the server repo yet?

**Comment by georgehrke** [comment]
If anything this: https://github.com/nextcloud/server/issues/2976#issuecomment-271262007
but not really either

**Comment by BernhardPosselt** [comment]
I'd file a new issue

**Comment by georgehrke** [comment]
Julius raised an issue for that in https://github.com/nextcloud/server/issues/7417

**Comment by tcitworld** [comment]
This should be handy when work on the Vue rewrite becomes usable.

**Comment by st3iny** [comment]
There still isn't a way for users to select a release channel for apps, the server issue was closed and we don't provide nightly builds anymore. Therefore I'm closing this issue.
