### ISSUE TITLE
Feature: Option to hide side calendar list

### ISSUE THREAD

**Issue by My-Random-Thoughts** [nextcloud/calendar#1299]
Option to completely hide the entire calendar list side bar, or change the threshold for the auto hide to kick in.

I have my calendar displayed on a screen hanging on the wall, but because the width is greater than the threshold of 768, the side calendar list is shown.  I would like the option to either change this threshold or hide it altogether.

(or if you can tell he which file to hack to do this myself - whatever I change it doesn't work)

**Comment by georgehrke** [comment]
Duplicate of ... (give me one second)
