### ISSUE TITLE
Endless requests for empty “files” (svg image data requests) 

### ISSUE THREAD

**Issue by Rello** [nextcloud/calendar#1300]
### Steps to reproduce
1. start a clean demo.nextcloud.com instance
2. install calendar app
3. access an empty calendar with Safari Browser

### Expected behaviour
A "silent" browser

### Actual behaviour
when I open the calendar app, there are several requests for “files” never finishing. My local instance only has 3 of them - but the demo.nextcloud.com should be a better reference.
![Screen Shot 2019-05-30 at 20 18 14](https://user-images.githubusercontent.com/13385119/58754142-80c27a80-84ca-11e9-9b12-97b721e8018f.png)

not happening on Chrome. When accessing the same URL in chrome, the only difference I could find is the number of `data: svg` images.
**All** seem to load in Chrome but  **some** of them get stuck on Safari
![Screen Shot 2019-05-30 at 20 23 13](https://user-images.githubusercontent.com/13385119/58754154-bb2c1780-84ca-11e9-8714-0c79535fb253.png)

because the continuous loading seems to keep the connection active and the Safari/CPU active.

### Server configuration
clean demo.nextcloud.com instance

**List of activated apps:**
calendar

**Comment by georgehrke** [comment]
@Rello Can you observe this in any other app?

I can't think of  anything that would trigger this within the calendar app, so i suspect it to be a general bug in the server

**Comment by georgehrke** [comment]
@tcitworld @skjnldsv Any idea?

**Comment by skjnldsv** [comment]
My guess is a 302.
Usually a request to files indicate a webserver issue that redirect to index.php and since the path doesn't exists, redirected to files

**Comment by tcitworld** [comment]
Yup, I would go with server configuration issue as well.

**Comment by georgehrke** [comment]
I'm also not able to reproduce this on the demo server:

![E6128375-FD19-4C42-9A8E-7D8BE2B05BE2](https://user-images.githubusercontent.com/1250540/67192405-d2c15980-f3f3-11e9-87db-b1519fec17f4.png)

(The demo server changed in the meantime, since this bug was initially reported)
