### ISSUE TITLE
Attendee

### ISSUE THREAD

**Issue by pricard32** [nextcloud/calendar#1306]
Custom tag for attendees

**Comment by georgehrke** [comment]
@pricard32 What exactly are you trying to tell us? :)
Is this a bug report? a feature request?

**Comment by pricard32** [comment]
Feature Request, sorry.. i'm pretty new to GitHub. 
When I add an Attendee, I want to add a custom tag beside him, like : Secretary or Technician.

**Comment by georgehrke** [comment]
@tcitworld What's your view on this?

**Comment by tcitworld** [comment]
Seems like a special usage, so overkill to me and probably hard to handle in a standard way.

**Comment by georgehrke** [comment]
I think what we could do is integrate even more with the contacts app and show job
Title / job position / company of the attendee on hover

**Comment by georgehrke** [comment]
> I think what we could do is integrate even more with the contacts app and show job
Title / job position / company of the attendee on hover

@skjnldsv @ChristophWurst Is this something that you could imagine having in the contacts menu? 
(The dropdown menu when clicking on an avatar)

**Comment by skjnldsv** [comment]
Like a small details popup before the actions list?

**Comment by georgehrke** [comment]
Yes, that's exactly what i had in mind :)

**Comment by skjnldsv** [comment]
Makes me think of this https://github.com/nextcloud/server/issues/6069#issuecomment-321992303

**Comment by georgehrke** [comment]
Closing in favour of https://github.com/nextcloud/nextcloud-vue/issues/617
