### ISSUE TITLE
Sharing NC calendar with Google does not work - webcal-link is not live

### ISSUE THREAD

**Issue by rollanders** [nextcloud/calendar#1321]
This havs been asked for many times. In the issue "Share NC Calendar with Google Calendar - No Updates! #706" it is claimed that the "https://mydomain.com/nextcloud/remote.php/dav/public-calendars/XXXXXXXXXXXXXXXX?export link is always up to date."
This may be true, but it is still an export link, which I suppose means it is not "live", ie does not provide new events. 
Google claims that if there is a "prenumeration" to a link that provide "live" information it should work. 
Is ther any such possibility in NC?

**Comment by georgehrke** [comment]
> This may be true, but it is still an export link, which I suppose means it is not "live", ie does not provide new events.

It does. Otherwise that link would not work as with Outlook, macOS ICalendar, etc. as other people said in #706 

> Google claims that if there is a "prenumeration" to a link that provide "live" information it should work.

Can you link me to some documentation of wherever you got that?

**Comment by georgehrke** [comment]
Anyway, beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.

The public calendar-sharing is part of the Nextcloud server, so please report tickets there:
https://github.com/nextcloud/server/issues

Please fill the complete issue template with precise reproduction steps!
and provide a link to that document from Google you referenced.

**Comment by rollanders** [comment]
"Google claims that if there is a "prenumeration" to a link that provide "live" information it should work.
Can you link me to some documentation or wherever you got that?"
We have Gsuite and I had chat-support. The representative sai that if this is an "export" link it is only a copy of the current situation. But if you claim that this link works in other non-google calendars they are apparently wrong. I will pot it in the correct place for clarity.

**Comment by georgehrke** [comment]
> The representative sai that if this is an "export" link it is only a copy of the current situation.

No, the export link always contains the latest version of the calendar. Even if you made changes since creating that share link.

**Comment by tcitworld** [comment]
Also Google Calendar definitely had a 24 or so hour cache a few years ago : https://webapps.stackexchange.com/a/49918

**Comment by rollanders** [comment]
That cache is if you make changes in the G-mail settings. It may take up to 24 hours before changes made will apply to all users of Gsuite. It has nothing to do with changes in events in tha calendar 
    Den lördag 15 juni 2019 11:47:27 CEST, Thomas Citharel <notifications@github.com> skrev:  
 
 
Also Google Calendar definitely had a 24 or so hour cache a few years ago : https://webapps.stackexchange.com/a/49918
