### ISSUE TITLE
Does not work in Edge or IE

### ISSUE THREAD

**Issue by rollanders** [nextcloud/calendar#1322]
Please see nextcloud/server#15957
In Edge and IE I can only use Files. No other app is working. Have tried it on the demo-site to0. Same result.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/issue_template.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md)

If you do not even tell us what version of Nextcloud / the calendar app you are using, we can't help you.

Please also include browser logs. That's important.

**Comment by rollanders** [comment]
I used the issue template in   nextcloud/server#15957. Can you read it from there or do I have to do it allower again? 


Steps to reproduce
Log in to site in one of these browsers. Files opens. Klick on any other Icon

Expected behaviour
The other app should be activated and opened

Actual behaviour
I get only a spinning wheel

Server configuration detail
Operating system: Linux 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64

Webserver: nginx/1.15.9 (fpm-fcgi)

Database: mysql 10.3.14

PHP version:

7.3.4-1+ubuntu18.04.1+deb.sury.org+3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

Nextcloud version: 16.0.1 - 16.0.1.1

Updated from an older Nextcloud/ownCloud or fresh install: No - fresh install

Where did you install Nextcloud from: I used script from c-rieger

Signing status
List of activated apps
Configuration (config/config.php)
Are you using external storage, if yes which one: local/smb/sftp/...

Are you using encryption:

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...

Client configuration
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

Operating system: Windows 10, updated

Logs
Web server error log
Nextcloud log
Browser log  But here we go again (unfortunately it does not work the same. Can you read at 


Steps to reproduce
Log in to site in one of these browsers. Files opens. Klick on any other Icon

Expected behaviour
The other app should be activated and opened

Actual behaviour
I get only a spinning wheel

Server configuration detail
Operating system: Linux 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64

Webserver: nginx/1.15.9 (fpm-fcgi)

Database: mysql 10.3.14

PHP version:

7.3.4-1+ubuntu18.04.1+deb.sury.org+3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

Nextcloud version: 16.0.1 - 16.0.1.1

Updated from an older Nextcloud/ownCloud or fresh install: No - fresh install

Where did you install Nextcloud from: I used script from c-rieger

Signing status
List of activated apps
Configuration (config/config.php)
Are you using external storage, if yes which one: local/smb/sftp/...

Are you using encryption:

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...

Client configuration
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

Operating system: Windows 10, updated

Logs
Web server error log
Nextcloud log
Browser log

**Comment by georgehrke** [comment]
I misunderstood your issue in the server, please see @skjnldsv's comment in the original thread: https://github.com/nextcloud/server/issues/15957#issuecomment-502462448
