### ISSUE TITLE
Part of the Popup window is out of the screen.

### ISSUE THREAD

**Issue by Sanyy** [nextcloud/calendar#1323]
### Steps to reproduce
1. select any day from 4th row on ~11" notebook.

### Expected behaviour
Popup window in the middle of the screen no matter which day i choose.

### Actual behaviour
Title row from Popup window is off the screen.

![nc](https://user-images.githubusercontent.com/17810774/59552545-f113d600-8f77-11e9-840f-4ad065a22e1e.png)

**Comment by georgehrke** [comment]
Please fill the **entire** issue template and tell is your screen resolution. Thx

**Comment by Sanyy** [comment]
**Resolution**:
1366x768

**Server Operating system**:
Ubuntu 18.04

**Web server:**
Apache

**PHP version:**
7.3

**Server version:** (see your admin page)
16.0.1

**Calendar version:** (see the apps page)
1.7.0

### Client configuration

**Browser:**
Firefox 67.0 / same for Iridium Version 2019.04 (Developer Build) Built on Ubuntu 16.04, running on LinuxMint 19.1 (64-bit)

**Operating system:**
Linux Mint 19.1 "Tessa" - Xfce (64-bit)

The problem seems to be this jumping here and there. Counting in pixels i think. It does not "see/count" the "Bookmarks Toolbar".
A simpler solution would be more useful -> In the middle of the screen always or whatever other users like.

**Comment by georgehrke** [comment]
In #926 we moved to popper.js, so problems like this should be resolved.
