### ISSUE TITLE
Failure importing ICS events with several EXDATE

### ISSUE THREAD

**Issue by s-a-m** [nextcloud/calendar#1325]
### Steps to reproduce
1. Export a calendar in ICS from Thunderbird's Lightning. Note it is a small calendar (37 events) and there is an event with several EXDATE. 
2. Validate that ICS in https://icalendar.org/validator.html and http://mozilla-comm.github.io/ical.js/validator.html (both correctly)
3. Import that ICS into NextCloud's Calendar app
4. The ICS is just partially imported, with one failure corresponding to the event with several EXDATE

### Expected behaviour
Since the ICS passes the validators, it is expected NextCloud would import it correctly. 

### Actual behaviour
The ICS is just partially imported, with one failure corresponding to the event with several EXDATE. Re-importing provides same result, skipping duplicates and same event failing. If the ICS is edited to remove that event, the ICS is imported correctly. Note it is a small ICS, and re-importing makes no changes, so I don't think #445 applies.

### Server configuration

Tested in https://demo.nextcloud.com with the default configuration. 

/settings/integrity/failed: 
No errors have been found.

**List of activated apps:**
Files, Activity, Gallery, Talk, Calendar, Deck

### Client configuration
**Browser:**
Firefox

**Operating system:**
Tried in Ubuntu 16.04 and Windows 10

**Comment by georgehrke** [comment]
Please provide server logs as requested in the issue template ...
