### ISSUE TITLE
Calender updates stopped working

### ISSUE THREAD

**Issue by cryptomilk** [nextcloud/calendar#1326]
nextcloud-16.0.1-lp150.1.1.noarch
nextcloud-apps-calendar-1.7.0-lp150.3.5.noarch

### Steps to reproduce

I'm trying to update my calendar in nextcloud, but it fails with KDE's KOrganizer and also with DavDroid on Android.

I don't see any errors on the server logs (`data/nextcloud.log`, apache), however KDE tells me what is wrong:

```
org.kde.pim.akonadiserver: Subscriber Akonadi::Server::NotificationSubscriber(0x7fa0e00505b0) identified as "AgentBaseChangeRecorder - 94306602796112"
parse error from icalcomponent_new_from_string. string= "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n  <s:exception>Sabre\\DAV\\Exception\\NotFound</s:exception>\n  <s:message>Calendar object not found</s:message>\n</d:error>\n"
org.kde.pim.davresource: DavGroupwareResource::onItemFetched: Failed to parse item data.  "https://nextcloud-server.org/remote.php/dav/calendars/user/personal/1560837254.R271.ics"
```

It looks like there is an invalid calendar entry, however I  can't find out how to identify it and possibly delete it. Let me know if I can provide more details or how to identify the right entry in the database.

Thanks!

**Comment by georgehrke** [comment]
If you have access to the database, you can search inside `oc_calendarobjects` for the `uri` `1560837254.R271.ics`

**Comment by cryptomilk** [comment]
I'm not able to find such an URI in the `calendarobjects`. The error vanished after clearing the akonadi cache for the resource. However I got another error:

```
org.kde.pim.davresource: Error when uploading item: 420 "There was a problem with the request. The item was not modified on the server.\nAn unexpected error (412) occurred while attempting to upload https://user@nextcloud-server.org/remote.php/dav/calendars/user/personal/46360a54-c0ab-494a-9ed1-75d15de6847e.ics. (412)."
```

After deleting this object, it seems to work again. Strange that some entries cause that eveything stops working. However I have no clue what caused this hickup :-(

**Comment by georgehrke** [comment]
> 46360a54-c0ab-494a-9ed1-75d15de6847e.ics (412)

HTTP Error 412 looks like Akonadi is trying to update an object that already exists, but it doesn't send an Etag (or an outdated one)

**Comment by cryptomilk** [comment]
Deleting the object in the database fixed the issue, everything is back to normal. I have no idea what went wrong. Feel free to close.
