### ISSUE TITLE
HTML field misspelled - sharing not working

### ISSUE THREAD

**Issue by Cacaonut** [nextcloud/calendar#1327]
### Steps to reproduce
1. Install the Calendar app
2. Click on share
3. Type in something

### Expected behaviour
autocomplete popup should appear

### Actual behaviour
Nothing appears

### Server configuration
**Operating system**: Gentoo Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**Server version:** 16.0.1

**Calendar version:** 1.7.0

**Updated from an older installed version or fresh install:** Updated from nextCloud 15

**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Its getting to much work for me now, however you don't need all of this information, because I already found the problem. Just open Developer Tools in your browser (I used Chrome) and inspect the text field, in which you would type the user or group to share your calendar with. There you can see that the fields `aria-expanded`, `aria-owns` and `aria-autocomplete` are misspelled. It has to be `area` instead of `aria`.

I'm sorry for my English if you can actually call it "English" :)

**Comment by Cacaonut** [comment]
Sorry, i didn't know there also is the field `aria-autocomplete` but it still does only work on Chrome if I replace it with `area-autocomplete`

**Comment by georgehrke** [comment]
Aria is not misspelled, please see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

**Comment by georgehrke** [comment]
Your bug is most likely https://github.com/nextcloud/calendar/issues/1297

**Comment by Cacaonut** [comment]
You're right, thanks
