### ISSUE TITLE
Cant share with everyone (virtual group)

### ISSUE THREAD

**Issue by tikoflano** [nextcloud/calendar#1330]
We use the **Everyone Group** app which adds a virtual group with everyone in it. When I try to share with everyone it shows in the search response, but when I click it nothing happens.

The Chrome DevTools network shows a POST request to `https://[mynextclouddomain]/remote.php/dav/calendars/alvaro/reuniones/` with `<o:share xmlns:o="http://owncloud.org/ns"><o:set><d:href xmlns:d="DAV:">principal:principals/groups/everyone</d:href><o:summary>Reuniones shared by alvaro</o:summary></o:set></o:share>` as payload.

The response is a 500 error with the content:

> <?xml version="1.0" encoding="utf-8"?>
> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
>   <s:exception>Doctrine\DBAL\Exception\SyntaxErrorException</s:exception>
>   <s:message>An exception occurred while executing 'SELECT `uid`, `displayname` FROM `users` `u` LEFT JOIN `preferences` `p` ON (`userid` = `uid`) AND (`appid` = 'settings') AND (`configkey` = 'email') WHERE (`uid`  COLLATE utf8mb4_general_ci LIKE ?) OR (`displayname`  COLLATE utf8mb4_general_ci LIKE ?) OR (`configvalue`  COLLATE utf8mb4_general_ci LIKE ?) ORDER BY `uid_lower` ASC LIMIT -1 OFFSET 0' with params ["%%", "%%", "%%"]:
> 
> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-1 OFFSET 0' at line 1</s:message>
</d:error>

**Comment by georgehrke** [comment]
This is caused by the everyone group app. Please report it in their repo
