### ISSUE TITLE
Wrong weekend for locale:Hebrew (Israel)

### ISSUE THREAD

**Issue by chenl** [nextcloud/calendar#1334]
### Steps to reproduce
1. Go the users Settings page
2. Set the Locale to: Hebrew (Israel)
3. Go to the Calendar App
4. Observe the days of week that are marked as weekends (gray)

### Expected behaviour
Weekend days in Israel should be Friday and Saturday.

### Actual behaviour
Weekdays are Saturday and Sunday.

### Server configuration

**Operating system**:
Ubuntu 18.04.2

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**

**Server version:**
15.0.8

**Calendar version:**
1.6.5

**Updated from an older installed version or fresh install:**
Fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:**
local: /media/data/nextcloud/

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
No

**Browser:**
Firefox

**Operating system:**
Kubuntu 18.04.2

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment]
Definitely an upstream issue. Need to check if in full calendar or moment.js

**Comment by georgehrke** [comment]
This was not solved by updating to FullCalendar 4 sadly.

I checked their source-code and everything related to weekends is hardcoded to Saturday and Sunday.

**Comment by georgehrke** [comment]
I created a ticket upstream: https://github.com/fullcalendar/fullcalendar/issues/5234

So this issue has two sides to it:
1. If you disable "Show weekends", the wrong weekends are hidden. This has to be fixed upstream in the referenced issue.
2. Wrong days are highlighted for weekend. That's something we can fix.
