### ISSUE TITLE
Display several calendars at the same time (by superposition)

### ISSUE THREAD

**Issue by gouessej** [nextcloud/calendar#134]
Hi

I'm a volunteer in a self-managed social center, the other activists chose to use a crappy competitor of NextCloud Calendar called [Brimbelles](http://brimbelles.com) which is free of charge but proprietary and requiring Adobe Flash plugin. I'd like to convince them to drop Brimbelles once for all as it can't be used on my mobile phone and plugin support within most famous web browsers is going to disappear but we need to display several calendars at the same time in order to use a lot less paper when printing them which is possible in Brimbelles but not in NextCloud Calendar.

We make one calendar per room, we need to be able to show both all events of a single room (better when we need to know when a room is available or not) and all events of all rooms (better for printing and for those who can't or don't access our online agenda).

Maybe we don't use the agenda correctly. If you know a workaround or another way of obtaining a similar result without this request for enhancement, let me know. For example, putting all events into a single calendar and using tags to choose which one to show/hide would be enough for us. Thanks.

**Comment by georgehrke** [comment]
> when printing them which is possible in Brimbelles but not in NextCloud Calendar.

I created a dedicated issue about adding print styles:
https://github.com/nextcloud/calendar/issues/136

> We make one calendar per room, we need to be able to show both all events of a single room 

You can just click the other calendars in the left sidebar to hide them.
(just click the name or the color left to it)

Is that what you wanted or am I misunderstanding your issue?

**Comment by gouessej** [comment]
Thank you for your quick reply. I'll try to clarify the needs of the end users as soon as possible, we use NextCloud Calendar on [Framagenda](https://framagenda.org). Someone told me: "As soon as we put two appointments at the same time, it becomes very difficult to read".

**Comment by georgehrke** [comment]
Can you please elaborate, what you mean by "very difficult to read" ;)

**Comment by gouessej** [comment]
I've just asked her to send me a screen capture so that I can tell you exactly what is wrong and how to improve the current situation.

**Comment by georgehrke** [comment]
The actual rendering is done by [fullcalendar](https://fullcalendar.io/js/fullcalendar-3.0.1/demos/agenda-views.html).
I'm not sure how easily we can influence the way events are rendered.

**Comment by gouessej** [comment]
I see what you mean now, thank you. Is it possible to increase the maximum number of (visible) events per day?

**Comment by georgehrke** [comment]
The event limit thing is actually something we need to discuss.
@jancborchardt Do you have an opinion?

With event limit / month view won't scroll:
<img width="1097" alt="calendar - nextcloud chromium today at 4 31 14 pm" src="https://cloud.githubusercontent.com/assets/1250540/19482152/736e326e-9550-11e6-866b-7cb8fca0f6e7.png">

Without event limit / month view begins to scroll:
<img width="993" alt="calendar - nextcloud chromium today at 4 30 01 pm" src="https://cloud.githubusercontent.com/assets/1250540/19482162/7e15cb6e-9550-11e6-80f5-2ea5b57f0f6d.png">

With the recent fixes to the sidebar the calendar list won't scroll together with the month view anymore.

**Comment by gouessej** [comment]
I assume that I can switch to fullscreen mode in my web browser before printing in order to mitigate the problem of scrolling.

**Comment by jancborchardt** [comment]
@georgehrke I think it’s fine to increase the event limit. Eventually it would be good to have continuous scrolling anyway (dreaming here) and then every event should be shown directly. Most people have few events a day anyway, but if you are busy then you also want to see everything.

**Comment by jancborchardt** [comment]
@georgehrke important would be that when you are in month view and the current days are the last of the month, is that the view scrolls to the bottom automatically to make these visible. The current day + future should always be in view as best as possible.
