### ISSUE TITLE
Better Import Diagnostics, please.

### ISSUE THREAD

**Issue by charlescurley** [nextcloud/calendar#1344]
### Steps to reproduce
1. Import an ical file with one or more events that Calendar doesn't like.
2.
3.

### Expected behaviour
Tell us what should happen

It would be nice to have better diagnostics, such as showing the offending line or VEVENT entry so one could improve one's icalendar generating tools.

### Actual behaviour
Tell us what happens instead

I get messages like, "Imported 933 out of 937, 4 failures".

### Server configuration

**Operating system**:

Debian GNU/Linux 9.9 (stretch)

**Web server:**

apache2	2.4.25-3+deb9u7

**Database:**

sqlite3

**PHP version:**

PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )

**Server version:** (see your admin page)

15.0.9

**Calendar version:** (see the apps page)

1.6.5

**Updated from an older installed version or fresh install:**

from an older installed version

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

"No errors have been found."

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```
root@dzur:/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.3
  - dav: 1.8.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - issuetemplate: 0.5.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.11.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - unsplash: 1.1.3
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - files_external
  - user_ldap
root@dzur:/var/www/nextcloud#

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

root@dzur:/var/www/nextcloud# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud",
            "nextcloud.localdomain",
            "localhost",
            "localhost.localdomain",
            "wli.ddns.info",
            "dzur",
            "dzur.localdomain"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/dzur.localdomain\/nextcloud",
        "dbtype": "sqlite3",
        "version": "15.0.9.1",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "production",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
root@dzur:/var/www/nextcloud# 

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**

vivaldi-stable	2.6.1566.44-1

**Operating system:**

Debian GNU/Linux 9.9 (stretch)

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

root@dzur:/var/log/apache2# cat access.log
::1 - - [05/Jul/2019:03:45:21 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:03:45:22 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:03:45:23 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:03:45:24 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:37:58 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:38:01 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:42:18 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:42:19 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:42:33 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:42:56 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:43:57 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:43:58 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:43:59 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:44:45 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:49:16 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:50:10 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:50:20 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:50:22 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:51:25 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
192.168.10.1 - - [05/Jul/2019:08:54:43 -0600] "-" 408 152 "-" "-"
::1 - - [05/Jul/2019:08:54:52 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:55:22 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:55:23 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:55:24 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:55:25 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:55:26 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:55:37 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:55:50 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:55:52 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:55:53 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:56:01 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:56:38 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:56:39 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:08:56:40 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
192.168.10.1 - - [05/Jul/2019:09:12:17 -0600] "-" 408 152 "-" "-"
192.168.10.1 - - [05/Jul/2019:09:18:48 -0600] "-" 408 152 "-" "-"
::1 - - [05/Jul/2019:09:47:26 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:09:47:27 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:10:02:33 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:10:02:35 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:10:03:58 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:10:03:59 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
192.168.10.1 - - [05/Jul/2019:10:10:38 -0600] "-" 408 3265 "-" "-"
::1 - - [05/Jul/2019:10:22:23 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:10:22:25 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
192.168.10.1 - - [05/Jul/2019:10:52:38 -0600] "-" 408 152 "-" "-"
192.168.10.1 - - [05/Jul/2019:10:58:38 -0600] "-" 408 152 "-" "-"
::1 - - [05/Jul/2019:12:25:05 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:12:25:06 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:12:25:09 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:13:18:11 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:13:18:12 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:13:18:13 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:13:34:19 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:13:34:20 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:13:34:25 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:13:36:24 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:13:36:25 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:13:38:13 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
::1 - - [05/Jul/2019:13:41:38 -0600] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2s (internal dummy connection)"
192.168.10.1 - - [05/Jul/2019:13:45:08 -0600] "-" 408 3265 "-" "-"
root@dzur:/var/log/apache2# 

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

Erm, over 1680658 bytes. Give me something relevant to grep on.

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
Where do I find it?

**Comment by georgehrke** [comment]
> I get messages like, "Imported 933 out of 937, 4 failures".

There should already be more information in the browser console.
Your problem might be related to #445 though.

> root@dzur:/var/log/apache2# cat access.log

The access.log is not really interesting here. The server log would be more interesting here.

> Erm, over 1680658 bytes. Give me something relevant to grep on.

The more recent logs? Logs mentioning Sabre or VObject?

**Comment by charlescurley** [comment]
On Fri, 05 Jul 2019 13:49:22 -0700
Georg Ehrke <notifications@github.com> wrote:

> > I get messages like, "Imported 933 out of 937, 4 failures".  
> 
> There should already be more information in the browser console.

The browser console shows (pasted unwrapped) for four failures in a
test import today:

core.js?v=dc0c52ee-0:3226 PUT https://wli.ddns.info:17800/remote.php/dav/calendars/charles/the-libertarian-calendar/Nextcloud-7IHRR0O2OBO5V20255P3RB.ics 415 (Unsupported Media Type)
request @ core.js?v=dc0c52ee-0:3226
create @ app.js:4016
(anonymous) @ app.js:1163
ve @ vendor.js:125
n @ app.js:1162
(anonymous) @ app.js:1211
Promise.then (async)
i.import @ app.js:1206
(anonymous) @ vendor.js:9023
t @ vendor.js:13585
$eval @ vendor.js:10391
$apply @ vendor.js:10414
(anonymous) @ vendor.js:13589
dispatch @ core.js?v=dc0c52ee-0:3
r.handle @ core.js?v=dc0c52ee-0:3
core.js?v=dc0c52ee-0:3226 PUT https://wli.ddns.info:17800/remote.php/dav/calendars/charles/the-libertarian-calendar/Nextcloud-GANQ3WW7QCUM6VSTL9B3SN.ics 415 (Unsupported Media Type)
request @ core.js?v=dc0c52ee-0:3226
create @ app.js:4016
(anonymous) @ app.js:1163
ve @ vendor.js:125
n @ app.js:1162
(anonymous) @ app.js:1211
Promise.then (async)
i.import @ app.js:1206
(anonymous) @ vendor.js:9023
t @ vendor.js:13585
$eval @ vendor.js:10391
$apply @ vendor.js:10414
(anonymous) @ vendor.js:13589
dispatch @ core.js?v=dc0c52ee-0:3
r.handle @ core.js?v=dc0c52ee-0:3
core.js?v=dc0c52ee-0:3226 PUT https://wli.ddns.info:17800/remote.php/dav/calendars/charles/the-libertarian-calendar/Nextcloud-MTHAGK66ZII4I6L8RCLGF.ics 415 (Unsupported Media Type)
request @ core.js?v=dc0c52ee-0:3226
create @ app.js:4016
(anonymous) @ app.js:1163
ve @ vendor.js:125
n @ app.js:1162
(anonymous) @ app.js:1211
Promise.then (async)
i.import @ app.js:1206
(anonymous) @ vendor.js:9023
t @ vendor.js:13585
$eval @ vendor.js:10391
$apply @ vendor.js:10414
(anonymous) @ vendor.js:13589
dispatch @ core.js?v=dc0c52ee-0:3
r.handle @ core.js?v=dc0c52ee-0:3
core.js?v=dc0c52ee-0:3226 PUT https://wli.ddns.info:17800/remote.php/dav/calendars/charles/the-libertarian-calendar/Nextcloud-02A7RYSPT099H62XI1UPX0Q.ics 415 (Unsupported Media Type)

Where might I find those intermediate files, e.g.
Nextcloud-02A7RYSPT099H62XI1UPX0Q.ics? 

> Your problem might be related to #445 though.

I doubt it. I am running the default Apache setup on my own computer,
and have not set any throttling that I recall.

> 
> > root@dzur:/var/log/apache2# cat access.log  
> 
> The access.log is not really interesting here. The server log would
> be more interesting here.
> 
> > Erm, over 1680658 bytes. Give me something relevant to grep on.  
> 
> The more recent logs? Logs mentioning Sabre or VObject?

The logs rotate daily, so log foo and foo.1 are of interest.

root@dzur:/var/log/apache2# grep -i vobject access.log access.log.1 error.log error.log.1 wli-* nextcloud-error.log nextcloud-error.log.1
root@dzur:/var/log/apache2# grep -i sabre access.log access.log.1 error.log error.log.1 wli-* nextcloud-error.log nextcloud-error.log.1
root@dzur:/var/log/apache2# 



> 



-- 
"When we talk of civilization, we are too apt to limit the meaning of
the word to its mere embellishments, such as arts and sciences; but
the true distinction between it and barbarism is, that the one
presents a state of society under the protection of just and
well-administered law, and the other is left to the chance government
of brute force."
- The Rev. James White, Eighteen Christian Centuries, 1889
Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB
https://charlescurley.com

**Comment by charlescurley** [comment]
I am now able to get a clean import. Here's what I did:

Installed Sabre locally.

Wrote a brain-dead validator based on the example on the Sabre web site.

Used that to validate my ical file, and adjusted my generator and source file accordingly. The errors were of two types: broken dates (I had inadvertently transposed some months and days in my source file), and character entity/accented issues.

Better error reporting would still be nice.

**Comment by georgehrke** [comment]
> Better error reporting would still be nice.

> 415 (Unsupported Media Type)

415 definitely means that there is some Sabre/VObject error message in the log, including more detailed infos .
