### ISSUE TITLE
Calandar disapeared sudenly...

### ISSUE THREAD

**Issue by Yagami-ya** [nextcloud/calendar#1347]
I have a question, can we recover a calandar if it has been deleted or simply disapeared by bug?

Mine worked fine and I just realized that my calandar was no more available, it seem to have sudenly disapeared from the list.

NextCloud 15.0.7
Calandar   1.6.5

**Comment by georgehrke** [comment]
Nope. If you deleted a calendar, it's gone.
(There is https://github.com/nextcloud/server/issues/1662 though).
