### ISSUE TITLE
Missing release that supports both v15 and v16

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/calendar#1359]
Version 1.6.5 of the calendar [supports both v14 and v15](https://github.com/nextcloud/calendar/blob/3ff76afd8ef1bfe9888fb349b893545289912cb2/appinfo/info.xml#L34) of Nextcloud. The next release, version 1.7.0, [only supports v16](https://github.com/nextcloud/calendar/blob/3bc261b629fd402727b0f9b8dc106e26069b2b62/appinfo/info.xml#L34).

The calendar is a wonderful, central part of Nextcloud. However, in the current situation, v1.7.0 cannot be installed on v15, and v1.6.5 is not compatible with v16, which means upgrading from v15 to v16 always disables it, which isn't a very good user experience.

Is there any chance we can get a bridge release, one that supports both v15 and v16, so we don't have this situation?

**Comment by georgehrke** [comment]
> Version 1.6.5 of the calendar supports both v14 and v15 of Nextcloud.

The link you posted is pointing to 1.6.4, __not__ 1.6.5.

1.6.5 supports Nc 15. see https://apps.nextcloud.com/apps/calendar

**Comment by kyrofa** [comment]
My apologies, I've updated the link, but the situation is the same. It supports both v14 and v15, like I said.

**Comment by kyrofa** [comment]
To be clear: the problem is that there is no release that supports _both_ v15 and v16.

**Comment by georgehrke** [comment]
Ah, sorry for being so slow, now i get what you mean.

v1.7.0 is not compatible with Nextcloud 15 or older, because it relies on features in the CalDAV server (mostly sharing with circles) and also contains breaking css changes, meaning v1.7.0 will have some broken styles on Nextcloud 14 and 15, but v1.6.5 will also have some broken styles on Nextcloud 16.

I totally understand that the current situation is unsatisfying, but i would like to see this solved in the Nextcloud server. When updating to the next major version, it should automatically update all apps where possible.

About your Nextcloud Snap issue: 
Is it possible for you to execute `occ app:update --all` after update? That should update all apps from the appstore.

**Comment by the-sane** [comment]
Auto-updating apps on the serverside has been discussed but they've decided against it for now.  Just wanted to note that in case it adds anything useful to the discussion:
https://github.com/nextcloud/server/issues/15416

**Comment by kyrofa** [comment]
> v1.7.0 is not compatible with Nextcloud 15 or older, because it relies on features in the CalDAV server (mostly sharing with circles) and also contains breaking css changes, meaning v1.7.0 will have some broken styles on Nextcloud 14 and 15, but v1.6.5 will also have some broken styles on Nextcloud 16.

Oh darn, I was afraid of that-- in that case, you did the only think you could have.

> I totally understand that the current situation is unsatisfying, but i would like to see this solved in the Nextcloud server.

Agreed completely.

> Is it possible for you to execute occ app:update --all after update? That should update all apps from the appstore.

Yeah that's an option we're investigating. Do you know if that will update disabled apps, as well?

**Comment by kyrofa** [comment]
> Do you know if that will update disabled apps, as well?

I can confirm that it does.

**Comment by pachulo** [comment]
How other people managed this update from 15 to 16 @georgehrke ? They all had to update and re-activate the Calendar app?

**Comment by georgehrke** [comment]
> They all had to update and re-activate the Calendar app?

I'm afraid so, yes. But please read my comment above.

**Comment by georgehrke** [comment]
This is a bug in the Nextcloud server:
Closing in favour of https://github.com/nextcloud/server/issues/15416
