### ISSUE TITLE
Birthday on 1st Jan not always shown in calendar, only sometimes

### ISSUE THREAD

**Issue by ecloudbizsolns** [nextcloud/calendar#138]
### Steps to reproduce
1. Create contact, enter birthdate as 1st January (year was 1960 in my use case)
2. Go to December 2016 view - birthday is shown in grayed out Jan 1 position (this is correct implementation)
3. Now go to Jan 2017 - nothing is shown.
### Expected behaviour

The birthday 'event' should be shown when the month is selected in which the 'event' occurs, and at all other times when the event occurs closely to the start/end of the previous/next month, respectively. ie:when in december view and the first day(s) of January are shown, then birthday events on those days should be shown. Identical for days at the end of the prior month, November in this scenario.
### Actual behaviour

Shown in December 2016 view (correctly in the grayed out section for 1st January)
Not shown at all in Jan 2017 view
### Server configuration

**Operating system**:
FreeBSD 10.3-RELEASE-p5
**Web server:**
nginx-1.10.1_2,2
**Database:**
sqlite3-3.14.1_1
**PHP version:**
php56-5.6.26
**Server version:** (see your admin page)
9.1.1
**Calendar version:** (see the apps page)
 Calendar 1.4.0
**Updated from an older installed version or fresh install:**
Updated (5.0.2?->6.x->7.0.2.1->7.0.15.2->8.0.15->8.1.10->8.2.8->9.0.5->9.1.1.3
Note: Originally installed as PBI (Puch Button Installer) on FreeNAS. Updated from 5.x thru to 7.0.2.1 on FreeNAS over some period of time. Then recently migrated to Nas4Free and manually rebuilt in a dedicated jail. Used native FreeBSD pkg (which installed 9.1.1). Manually removed and replaced with 7.0.15, migrated that to -> 8.0.15, etc etc all the way to 9.1.1.

This calendar event was not created until the system was already at 9.1.1, so it should not be a leftover from previous installs.

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
# sudo -u www php occ app:list
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.6
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - systemtags: 0.3.0
  - templateeditor: 0.1

**The content of config/config.php:**
# sudo -u www php occ config:list system
{
    "system": {
        "datadirectory": "\/media",
        "instanceid": "REMOVED",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED",
            "REMOVED",
            "REMOVED"
        ],
        "dbtype": "sqlite",
        "dbname": "owncloud",
        "version": "9.1.1.3",
        "installed": true,
        "updatechecker": false,
        "forcessl": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
```
### Client configuration

**Browser:**
Firefox 49 on Ubuntu/Mercury Browser on iOS (up to date iOS 9 on iPad)
**Operating system:**
Ubuntu14.04 and iOS9
**CalDAV-clients:**
Evolution on Ubuntu/native on iOS
#### Web server error log

```
No relevant log messages
```
#### Log file (data/owncloud.log)

```
No relevant log messages
```
#### Browser log

```
Nothing relevant.

Edits: Typos
```

**Comment by georgehrke** [comment]
As far as I can tell this was fixed with 1.4.1
Please speak up if I am wrong.
