### ISSUE TITLE
IOS Caldav connection does not work with spaces in user name

### ISSUE THREAD

**Issue by Mululu** [nextcloud/calendar#1391]
### Steps to reproduce
1. On IOS Open the Caldav settings 
2. Enter the URL, a user with spaces eg "name name2" and the password
3.Error "SSL not possible"

### Expected behaviour
Username with spaces should work

### Actual behaviour
Username with spaces does not work

### Server configuration

**Operating system**: Hosting

**Web server:** Apache

**Database:** MySQL Maria DB

**PHP version:** 7.3

**Server version:** (see your admin page)
16.0.3

**Calendar version:** (see the apps page)
1.7.0
**Updated from an older installed version or fresh install:**
Update

**Signing status (ownCloud/Nextcloud 9.0 and above):**
???

Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors

**List of activated apps:**
Calender, contacts Groupfolder

**Nextcloud configuration:**

**Are you using encryption:** no

### Client configuration
**Browser:** Google Chrome newest

**Operating system:**
Win 10 64bit
**CalDAV-clients:**
IOS iPhone X
#### Web server error log
No errors 
Insert your webserver log here
No errors

#### Log file (data/nextcloud.log)
No errors
Insert your nextcloud.log file here
No errors

#### Browser log
No errors
Insert your browser log here, this could for example include:
No errors

**Comment by tcitworld** [comment]
Server issue and duplicate from https://github.com/nextcloud/server/issues/15641
