### ISSUE TITLE
Event editor not fully visible on mobile browsers

### ISSUE THREAD

**Issue by cieska** [nextcloud/calendar#1401]
### Steps to reproduce
1. Open Calendar on Android Opera or Chrome web browsers.
2. Create a new event, Event Editor pops-up. 
3. [Create] button on the very bottom of the screen not visible. 

### Expected behaviour
Create Event box's elements should be dynamically spread to be fully visible (see attached screenshots).   

### Actual behaviour
When filing Event Editor fields you would like to crate event but [Create] button not visible.  
But works very well with Firefox browser, even if keyboard displayed (see attached screenshots).

### Server configuration
Nextcloud
Version: 16.0.4.1
Apps installed: 49
Apps updates available: 0
PHP
Version: 7.2.19
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 2 MB
Database
Type: mysql
Version: 5.7.27
Size: 134.7 MB

Ubuntu 18.04 
Apache2 (latest)

**Calendar version:** 
1.7.0

**Updated from an older installed version or fresh install:**
updated since NC 13

### Client configuration
Phone: OnePlus 5T 
Screen size: 6.01 inches
Resolution: 1080 x 2160

**Operating system:**
Android 9.0.8

Firefox 68.0.2
Opera 53.0.2569.141117
Chrome 76.0.3809.111

### Screenshots
Below the screenshot of Opera browser without [Create] button displaed

![InkedScreenshot_20190816-183755_LI](https://user-images.githubusercontent.com/41318524/63191857-206ac000-c059-11e9-8d45-f55a4389e07e.jpg)

Below a screenshot of Chrome browser without [Create] button displaed

![InkedScreenshot_20190816-184247_LI](https://user-images.githubusercontent.com/41318524/63191870-2b255500-c059-11e9-9b21-f25f2a0589db.jpg)

Below the screenshot of Firefox borwser with properly displayed [Create] button even with opened keyboard. 

![InkedScreenshot_20190816-184505_LI](https://user-images.githubusercontent.com/41318524/63191881-324c6300-c059-11e9-9856-e7133e2a628f.jpg)

**Comment by georgehrke** [comment]
Dup of https://github.com/nextcloud/calendar/issues/1079
