### ISSUE TITLE
Calendar: User Base is searchable even if Username AutoCompletion is turned off

### ISSUE THREAD

**Issue by Linuxfabrik** [nextcloud/calendar#1408]
### Steps to reproduce
* Fresh install of latest Nextcloud (16.0.4)
* Create two users with their email addresses, Alice and Bob
* Disable/turn off "Allow username autocompletion in share dialog. If this is disabled the full username or email address needs to be entered."
* Log in with "Alice"
* Open Calender App and create a new Appointment
* Under "More... > Attendees", invite Bob using his email address.

### Expected behaviour
The Calendar "Attendee" field should not search within the user base if the main setting "Allow username autocompletion in share dialog" is turned off. I expect I have to provide Bob's full email address to invite him.

### Actual behaviour
Even if username autocompletion is turned off, after three matching characters Bob is found in Nextcloud's user base and shown. Tested with local Database (MariaDB), untested with LDAP.

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache 2.4

**Database:** MariaDB 10.3

**PHP version:** 7.2

**Nextcloud version:** 16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** doesn't matter

**Where did you install Nextcloud from:** Downloaded from Nextcloud Site

### Client configuration
**Browser:** Any current Browser, tested on Linux

**Comment by georgehrke** [comment]
@Linuxfabrik Would you be up to sending a pull-request about this? :)

**Comment by kesselb** [comment]
> But this should perhaps also be documented in the dev documentation :)

Indeed. Do you think every app should implement this? I guess server should not expose this information to apps (if the flag is set). We may think about another name for the flag then.

**Comment by georgehrke** [comment]
This was fixed in #926 

see https://github.com/nextcloud/calendar/blob/master/lib/Controller/ContactController.php#L77L79
and https://github.com/nextcloud/calendar/blob/master/lib/Controller/ContactController.php#L128#L130

**Comment by pierreozoux** [comment]
For people passing by and wondering how to do before v2 is out, you could simply use:

https://github.com/nextcloud/calendar/blob/master/lib/Controller/ContactController.php

Works like a charm!
