### ISSUE TITLE
Querying calendar-home-set failed

### ISSUE THREAD

**Issue by arkraft** [nextcloud/calendar#141]
### Steps to reproduce
1. Install Nextcloud
2. Activate calendar app
3. Open calendar app
4. Create new calendar

### Expected behaviour
New calendar appears in the list

### Actual behaviour
Loading indicator keeps on spinning. List stays empty

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Caddy 0.9.3

**Database:** Mysql 5.5.52

**PHP version:** 7.0.12-1

**Server version:** 10.0.1 (beta)

**Calendar version:** 1.4.0

**Updated from an older installed version or fresh install:** fresh

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Integrity checker has been disabled. Integrity cannot be verified.
```

**List of activated apps:**

- activity: 2.3.2                
- admin_audit: 1.0.0             
- calendar: true                 
- comments: 1.0.0                
- contacts: 1.4.0.0              
- dav: 1.0.1                     
- federatedfilesharing: 1.0.1    
- federation: 1.0.1              
- files: 1.5.2                   
- files_pdfviewer: 0.8.1         
- files_sharing: 1.0.0           
- files_texteditor: 2.1          
- files_trashbin: 1.0.0          
- files_versions: 1.3.0          
- files_videoplayer: 0.9.8       
- firstrunwizard: 1.1            
- gallery: 15.0.0                
- notifications: 0.3.0           
- password_policy: 1.0.0         
- provisioning_api: 1.0.0        
- serverinfo: 1.1.1              
- survey_client: 0.1.5           
- systemtags: 1.0.2              
- templateeditor: 0.1            
- theming: 1.0.1                 
- updatenotification: 1.0.1      
- workflowengine: 1.0.1          

**The content of config/config.php:**

```php
{                                                                                 
    "system": {                                                                   
        "instanceid": "ocjvzas799uy",                                             
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                          
        "secret": "***REMOVED SENSITIVE VALUE***",                                
        "trusted_domains": [                                                      
            "***REMOVED SENSITIVE VALUE***"                                                
        ],                                                                        
        "datadirectory": "***REMOVED SENSITIVE VALUE***",    
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",                    
        "dbtype": "mysql",                                                        
        "version": "9.1.1.5",                                                     
        "dbname": "nextcloud",                                                    
        "dbhost": "localhost",                                                    
        "dbport": "",                                                             
        "dbtableprefix": "oc_",                                                   
        "dbuser": "***REMOVED SENSITIVE VALUE***",                                
        "dbpassword": "***REMOVED SENSITIVE VALUE***",                            
        "logtimezone": "UTC",                                                     
        "installed": true,                                                        
        "memcache.local": "\\OC\\Memcache\\APCu",                                 
        "appstore.experimental.enabled": true,                                    
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",                   
        "loglevel": 0,                                                            
        "mail_from_address": "nextcloud",                                         
        "mail_smtpmode": "smtp",                                                  
        "mail_domain": "***REMOVED SENSITIVE VALUE***",                                              
        "mail_smtpauthtype": "LOGIN",                                             
        "mail_smtpauth": 1,                                                       
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",                                        
        "mail_smtpport": "25",                                                    
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",                         
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",                     
        "mail_smtpsecure": "tls",                                                 
        "updater.release.channel": "beta",                                        
        "updater.secret": "***REMOVED SENSITIVE VALUE***",                        
        "maintenance": false                                                      
    }                                                                             
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**

### Client configuration
**Browser:** Chrome (v 53.0.2785.143 m) / Firefox (v 47.0.1)

**Operating system:** Windows 10

#### Browser log
```
Uncaught (in promise) CalDAV client could not be initialized - Querying calendar-home-set failed
```

**Comment by georgehrke** [comment]
Wild guess: Caddy 0.9.3 blocks PROPFIND requests?

**Comment by arkraft** [comment]
I have no entries in the error log, but in the access log i see this:
```
91.0.205.100 - [19/Oct/2016:10:29:34 -0400] "PROPFIND /remote.php/dav HTTP/1.1" 207 587
91.0.205.100 - [19/Oct/2016:10:29:34 -0400] "PROPFIND /remote.php/dav/principals/users/arkraft/ HTTP/1.1" 0 7422
```
The PROPFIND method returns a 207 code so i think it works. But i will try it with nginx, maybe caddy is really the problem

**Comment by arkraft** [comment]
You were right. I tested it with nginx and it works right away. I can see my calendars and create new ones. Seems like caddy has a problem with caldav/carddav requests.

**Comment by arkraft** [comment]
I have to take back the last sentence of my comment. Caddy can serve owncloud calendar, i just had a rewrite rule false which i took from a [blog post](https://denbeke.be/blog/webdevelopment/serving-owncloud-with-caddy/). One of the comments mentions a better rewrite rule and it worked. 
[Here](https://github.com/caddyserver/caddyserver.com/pull/77) is a full example of using nextcloud with caddy.
