### ISSUE TITLE
Recurrence-ID not handled correctly

### ISSUE THREAD

**Issue by pieplu** [nextcloud/calendar#142]
### Steps to reproduce
1. Add a reccuring event on your calendar
2. Sync your calandar with other client (thunderbird, android agenda, etc...)
3. Edit only one event, and change a thing (title, date, etc...)
### Expected behaviour

The edited event sould (visually) replace his event occurence
### Actual behaviour

The edited event is displayed aside his event occurence
#### Reccuring event created

![](https://framapic.org/lcdA8fNc0I9r/b3Mjn19HI0ba)
#### One event edited

![](https://framapic.org/zjI8CDcNS5ve/IOx60MnrXlaS)
### Server configuration

**Operating system**:

**Web server:** CentOS - Nextcloud

**Database:** sqlite

**PHP version:** 7

**Server version:** 9.54

**Calendar version:** 1.4.0

**fresh install:**

**Are you using encryption:** no
### Client configuration

**Browser:** Chromium, Chrome, Firefox

**Operating system:** Ubuntu 16.04, OSX 10.10

**CalDAV-clients:** Thunderbird, Agenda (Android), etc...
#### Browser log

```
No errors
```

**Comment by georgehrke** [comment]
related to https://github.com/nextcloud/calendar/blob/c118a9667abfe247854cd2b8729e4ff1dd05376f/tests/js/unit/models/veventModelSpec.js#L1044

**Comment by pieplu** [comment]
I have a similare issue.

On the same context, if we change (on nextcloud calendar) the recuring event, the "event alone" is not changed.
It's looks like the "link" bettween is not "understanded" by nextcloud calendar. On other client, it's work.


See hours: ![](https://framapic.org/pmSd6Gku7P2W/qUlwBu5Uu2hr)

**Comment by georgehrke** [comment]
> the "event alone" is not changed.

What do you mean by event alone?
Can you please switch your Nextcloud to english and tell me what exact button or setting you mean?

**Comment by pieplu** [comment]
After the 3 previous steps
* I click on the "recuring event"
* I change the start hour (12:00pm to 2:00pm)
* All "recuring event" are set to 2:00pm, except the event named "recuring event edited alone", still to 12:00pm

If I reproduce this same steps on thunderbird, or other client, the "recuring event edited alone" start hour change (like all "recuring event").

![](https://framapic.org/3mwrfjraw8q0/oRnttN2l0uGT)


If I export  the calendar, I show 2 events, with same **UID**, I think it's normal.
But nextcloud calendar looks like don't care if an other **VEVENT** exist with the same **UID**, and if he had to edit it.
```
BEGIN:VEVENT
CREATED:20161019T091600
LAST-MODIFIED:20161019T132117Z
DTSTAMP:20161019T132117Z
UID:ggbtr1ft628gmn1h2grs5rk9
SUMMARY:recurring event
STATUS:CONFIRMED
RRULE:FREQ=WEEKLY
X-MOZ-GENERATION:2
SEQUENCE:1
DTSTART;TZID=America/New_York:20170207T140000
DTEND;TZID=America/New_York:20170207T150000
END:VEVENT

BEGIN:VEVENT
CREATED:20161019T131917Z
LAST-MODIFIED:20161019T132117Z
DTSTAMP:20161019T132117Z
UID:ggbtr1ft628gmn1h2grs5rk9
SUMMARY:recurring event edited alone
STATUS:CONFIRMED
RECURRENCE-ID;TZID=America/New_York:20170214T120000
DTSTART;TZID=America/New_York:20170214T120000
DTEND;TZID=America/New_York:20170214T130000
X-MOZ-GENERATION:1
END:VEVENT
```


It's look's like a linked problem :)

**Comment by cyphar** [comment]
This also happens if you delete a single event in a recurring series of events -- you get a duplicate event that has been "cancelled".

**Comment by georgehrke** [comment]
> This also happens if you delete a single event in a recurring series of events -- you get a duplicate event that has been "cancelled".

Can you please elaborate on that?
Deleting one occurrence of a repeating event has nothing to do with recurrence IDs.
That's handled with EXDATE.

**Comment by georgehrke** [comment]
And EXDATE is supported just fine:
https://github.com/nextcloud/calendar/blob/master/tests/js/unit/models/veventModelSpec.js#L1221

**Comment by cyphar** [comment]
I'm using Google's Calendar app to delete the single entry and then using DavDroid to sync it. So it's possible that Google's Calendar app is doing something wrong -- I'd be happy to have a suggestion for a calendar app that isn't garbage. :P

**Comment by rygen** [comment]
I was about to post a new issue but noticed this describes it well. I'm also facing this bug when using the macOS's calendar via calDAV. 
To reproduce just set up a repeating event, then make some adjustments in the client - like changing the end time for one of the events only. It keeps the original unedited version on NextCloud and adds a new one with the edits.
