### ISSUE TITLE
No invitation email sent -> Swift_TransportException

### ISSUE THREAD

**Issue by balli1187** [nextcloud/calendar#1422]
### Steps to reproduce
1. set yahoo-Account in NC-Settings -> Basic settings -> Email server
2. create a new Event
3. invite someone via email

### Expected behaviour
- invitation email should be send to invitet Person

### Actual behaviour
`[dav]` Error: Swift_TransportException: Expected response code 250 but got code "550", with message "550 Request failed; Mailbox unavailable
" at <<closure>>

 0. /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 341
    Swift_Transport_AbstractSmtpTransport->assertResponseCode("550 Request fai ... n", [250])
 1. /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php line 305
    Swift_Transport_AbstractSmtpTransport->executeCommand("\r\n.\r\n", [250], [], false, null)
 2. /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 404
    Swift_Transport_EsmtpTransport->executeCommand("\r\n.\r\n", [250])
 3. /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 500
    Swift_Transport_AbstractSmtpTransport->streamMessage(Swift_Message {})
 4. /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 516
    Swift_Transport_AbstractSmtpTransport->doMailTransaction(Swift_Message {}, "<sender mail>", ["recipients mail>"], [])
 5. /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 206
    Swift_Transport_AbstractSmtpTransport->sendTo(Swift_Message {}, "<sender mail>", {"<recipients mail>"}, [])
 6. /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php line 71
    Swift_Transport_AbstractSmtpTransport->send(Swift_Message {}, [])
 7. /var/www/html/lib/private/Mail/Mailer.php line 180
    Swift_Mailer->send(Swift_Message {}, [])
 8. /var/www/html/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php line 255
    OC\Mail\Mailer->send(OC\Mail\Message {})
 9. <<closure>>
    OCA\DAV\CalDAV\Schedule\IMipPlugin->schedule(Sabre\VObject\IT ... e})
10. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([OCA\DAV\CalDAV\ ... "], [Sabre\VObject\I ... }])
11. /var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 384
    Sabre\Event\EventEmitter->emit("schedule", [Sabre\VObject\I ... }])
12. /var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 665
    Sabre\CalDAV\Schedule\Plugin->deliver(Sabre\VObject\IT ... e})
13. /var/www/html/apps/dav/lib/CalDAV/Schedule/Plugin.php line 180
    Sabre\CalDAV\Schedule\Plugin->processICalendarChange(null, Sabre\VObject\Co ... l}, ["mailto:<recipients mail> "], [], true)
14. <<closure>>
    OCA\DAV\CalDAV\Schedule\Plugin->calendarObjectChange(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {}, Sabre\VObject\Co ... l}, "calendars/Stephan/personal", true, true)
15. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([OCA\DAV\CalDAV\ ... "], [Sabre\HTTP\Requ ... e])
16. /var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php line 943
    Sabre\Event\EventEmitter->emit("calendarObjectChange", [Sabre\HTTP\Requ ... e])
17. /var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php line 801
    Sabre\CalDAV\Plugin->validateICalendar("BEGIN:VCALENDAR ... R", "calendars/Steph ... s", false, Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {}, true)
18. <<closure>>
    Sabre\CalDAV\Plugin->beforeCreateFile("calendars/Steph ... s", "BEGIN:VCALENDAR ... R", OCA\DAV\CalDAV\Calendar {}, false)
19. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([OCA\DAV\CalDAV\ ... "], ["calendars/Step ... e])
20. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1094
    Sabre\Event\EventEmitter->emit("beforeCreateFile", ["calendars/Step ... e])
21. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
    Sabre\DAV\Server->createFile("calendars/Steph ... s", "BEGIN:VCALENDAR ... R", null)
22. <<closure>>
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
23. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
24. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
25. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
26. /var/www/html/apps/dav/lib/Server.php line 316
    Sabre\DAV\Server->exec()
27. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
28. /var/www/html/remote.php line 163
    undefinedundefinedrequire_once("/var/www/html/a ... p")

PUT /nxtcld/remote.php/dav/calendars/Stephan/personal/Nextcloud-ABCDEFGHIJKLMNOPQRSTUVWXYZ.ics
from 111.222.333.444 by Stephan at 2019-08-22T14:12:12+00:00`

### Server configuration
**Operating system**: QNAP ATS

**PHP version:** 7.3.8

**Server version:** 16.0.4

- Invitation with Yahoo does not work.
- worked in May, when NC was set up
- Other mails from NC (notifications, e-Mail-config test) works well
- with other Mail provider (web.de) invitation works

I opened a discussion on help.nextcoud.com and they gues it could be caused by the  “Reply to” header in Invitation mails.

**Comment by georgehrke** [comment]
> I opened a discussion on help.nextcoud.com and they gues it could be caused by the “Reply to” header in Invitation mails.

Using ReplyTo is the expected behaviour at the moment and we are not looking forward to change that.

Hence i will close this as won't fix.

There are plans to integrate it better with the Mail App though, so that emails are automatically sent  using the email account of the user. https://github.com/nextcloud/server/issues/5080

**Comment by balli1187** [comment]
> 
> 
> > I opened a discussion on help.nextcoud.com and they gues it could be caused by the “Reply to” header in Invitation mails.
> 
> Using ReplyTo is the expected behaviour at the moment and we are not looking forward to change that.
> 
> Hence i will close this as won't fix.
> 
> There are plans to integrate it better with the Mail App though, so that emails are automatically sent using the email account of the user. [nextcloud/server#5080](https://github.com/nextcloud/server/issues/5080)

Do you agree, that the header causes the Problem? it's just a guess from another user....
Was it introduced with NC 16? Cause it worked in May, when i started with NC on 15.x.x

**Comment by georgehrke** [comment]
> Do you agree, that the header causes the Problem?

Possible, but I have no idea. Never tried it with Yahoo and it worked perfectly with every mailserver i have tried so far. If it works with other mail providers, i would just recommend using a different one.

> Was it introduced with NC 16? Cause it worked in May, when i started with NC on 15.x.x

No, we have been using the reply to field for a couple of years now

**Comment by balli1187** [comment]
> 
> 
> > Do you agree, that the header causes the Problem?
> 
> Possible, but I have no idea. Never tried it with Yahoo and it worked perfectly with every mailserver i have tried so far. If it works with other mail providers, i would just recommend using a different one.
> 
> > Was it introduced with NC 16? Cause it worked in May, when i started with NC on 15.x.x
> 
> No, we have been using the reply to field for a couple of years now

Sorry but in this case i don't understand closing the issue for this reason....
Can you imagine something else causing this problem?

**Comment by georgehrke** [comment]
> Sorry but in this case i don't understand closing the issue for this reason....
Can you imagine something else causing this problem?

No, I can't imagine anything else. But as you said yourself it works with other mail servers, so it must either be an issue in your email configuration in Nextcloud (did you try sending a test mail from the admin interface) or a configuration issue in the Mailserver.


> It may also occur when sending invitation from users mail adress?!

No, In that case it will use the FROM field with the actual user address and omit the REPLY TO field
