### ISSUE TITLE
Delete only one element of a repeating event

### ISSUE THREAD

**Issue by reiterbenjamin** [nextcloud/calendar#143]
### Steps to reproduce
1. Create a repeating event
2. Delete the event on one date

### Expected behaviour
I would expect that the app asks me if I want to delete the whole repeating event or just one element of it (so if I have a weekly repeated event and in one week the event doesn't take place I'd like to delete just this single event for this week, not the whole).

### Actual behaviour
The whole event is deleted

### Server configuration
**Calendar version:** 1.4.0

**Signing status (ownCloud/Nextcloud 9.0 and above):** Nextcloud 10.0.1

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/7
