### ISSUE TITLE
French traduction of TENTATIVE

### ISSUE THREAD

**Issue by GMo7944** [nextcloud/calendar#1435]
Calendar 1.7.0

### Steps to reproduce
 In an envent, there is 3 status : CONFIRMED ; TENTATIVE ; CANCELLED

In french ; TENTATIVE is traducted by Tentative and this in wrong.

### Expected behaviour

In this case, it should be : Provisoire

Thanks a lot for your job

Guillaume

**Comment by georgehrke** [comment]
@GMo7944 Can you please report / or just fix this at https://transifex.com/nextcloud ? :)

**Comment by sumnerevans** [comment]
Broken link: Here's the correct one: https://www.transifex.com/nextcloud/nextcloud/
