### ISSUE TITLE
Calendar-inbox: Accept / Reject and show responses in calendar

### ISSUE THREAD

**Issue by steckerhalter** [nextcloud/calendar#144]
So currently when someone creates an event and adds attendees it sends an email to those people and one has to use a client applications to be able to accept said event.

Shouldn't it also be possible to accept events via the Nextcloud web interface as well? Otherwise the calendar system is not really usable without an external client.

Thinking a bit further, if it would be possible to accept events in the web interface, the next step would be some kind of free/busy implementation.

Is there already some plan regarding these things?

**Comment by steckerhalter** [comment]
I reported this here first because I thought it would require changes to the server: https://github.com/nextcloud/server/issues/1811

**Comment by georgehrke** [comment]
> Is there already some plan regarding these things?

Yes, there is.
The search function is your friend ;)
https://github.com/nextcloud/calendar/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20free%20busy

https://github.com/nextcloud/calendar/issues/39

**Comment by georgehrke** [comment]
> Shouldn't it also be possible to accept events via the Nextcloud web interface as well? Otherwise the calendar system is not really usable without an external client.

@Gomez Is that already possible via the mail app?

**Comment by tcitworld** [comment]
I can do this last feature once https://github.com/nextcloud/calendar/pull/97 is done ;-)

**Comment by Gomez** [comment]
You mean ics import? Yes possible:
https://github.com/owncloudarchive/mail/pull/1473

**Comment by georgehrke** [comment]
@tcitworld I'm not sure how this is related to #97 
AFAIK we need to use the special INBOX calendar.

**Comment by mikeziri** [comment]
When I create an event and add attendees, does nextcloud send out email to them if email is configured?

**Comment by georgehrke** [comment]
@mikeziri Yes

**Comment by mikeziri** [comment]
@georgehrke awesome. tnx. I couldn't configure my email smtp yesterday to confirm it. it sure does. the only thing I still wanted to know, already mentioned above, is if the attendees that receive the email, get a way to rsvp via api link (yes, no, maybe).

keep up the good work

**Comment by georgehrke** [comment]
@mikeziri Yes, that's planned. See https://github.com/nextcloud/server/issues/2338

**Comment by tcitworld** [comment]
Related to https://github.com/nextcloud/server/issues/19568

**Comment by Mer0me** [comment]
Any update on this issue ? When will it be possible to accept/decline an invitation from de Web UI ? Can we help in some way ?

**Comment by Mer0me** [comment]
Sorry for the late answer, I don't receive all github notifications. I wish I can help in some way but I'm not an expert coder even if I can understand basic PHP and Javascript codes.
I'm about (mid-2022) to propose Nextcloud as a replacement of Exchange 2007/Outlook 2010 for 400+ users. I really need some (minor, from my point of view) improvements on the calendar interface like this (accept/decline from web interface, context menu on event with some actions...).
What can I do for you ?

**Comment by ChristophWurst** [comment]
If you want to contribute https://nextcloud.com/contribute/ should get you started.
If you want to support the project in the long run there is also https://nextcloud.com/enterprise/.

:v:

**Comment by Mer0me** [comment]
I'll do my best. I've already translated hundred of strings last week on transifex. But a roadmap for this kind of features is missing for us. This issue was opened in 2016 and it's a minor change (I guess) leading to major improvement. No offense, Nextcloud rocks however ! 
Unfortunately, my company is not ready to financially support open source projects like Nextcloud. I'm working on that too...

**Comment by ChristophWurst** [comment]
> I've already translated hundred of strings last week on transifex.

Thanks a lot :rocket:
