### ISSUE TITLE
Repeating event not shown on the Morning of the first day of the week

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/calendar#145]
### Steps to reproduce
1. Create a repeating event which runs over midnight and let it repeat over the weekend using the Webinterface.
2. Have a look at the event on Monday morning.

Example event causing the issue:

```
BEGIN:VCALENDAR
PRODID:-//ownCloud calendar v1.4.0
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20161020T130607
DTSTAMP:20161020T130607
LAST-MODIFIED:20161020T130607
UID:ujihvdbldzg
SUMMARY:Test
CLASS:PUBLIC
STATUS:CONFIRMED
RRULE:FREQ=DAILY;COUNT=3
DTSTART;TZID=Europe/Berlin:20161022T180000
DTEND;TZID=Europe/Berlin:20161023T060000
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```
### Expected behaviour

The event should be shown on Monday mornging.
### Actual behaviour

Monday morning is not shown in the UI. The following events are rendered correctly again.
### Server configuration

**Operating system**:
Debian Jessie

**Web server:**
Apache

**Database:**
Mysql 5.6

**PHP version:**
5.6

**Server version:** (see your admin page)
ownCloud 9.1.0

**Calendar version:** (see the apps page)
1.4.0

**Updated from an older installed version or fresh install:**
Updated

**Browser Log**
Nothing in the Javascript console.

I guess the issue should be reproducible with the provided VEVENT, but in case you need more info, let me know.

**Comment by georgehrke** [comment]
@raimund-schluessler Your language is set to german, right?

**Comment by raimund-schluessler** [comment]
@georgehrke Yes, it is. I did a quick test with English at which the event is not shown on Sunday morning. Hence, it is the first day of the week, not specifically Monday.

**Comment by georgehrke** [comment]
fix is in https://github.com/nextcloud/calendar/pull/174
