### ISSUE TITLE
Non-printable symbol in the description of a calendar event causes the whole calendar to disappear

### ISSUE THREAD

**Issue by sk197876** [nextcloud/calendar#1451]
### Steps to reproduce
1. Create a new calendar, e.g., "Test".
2. Add some events to the calendar "Test",
3. Add another event to the "Test" calendar and in the description field write "Universita".
4. Click "create".

### Expected behaviour
New event should appear.

### Actual behaviour
All events from calendar "Test" disappear

## Server configuration detail

**Operating system:** Linux 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 10.1.41

**PHP version:** 

7.3.8-1+ubuntu18.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, interbase, intl, json, ldap, exif, mysqli, odbc, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, recode, redis, shmop, SimpleXML, smbclient, snmp, soap, sockets, sqlite3, ssh2, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from previous NC

**Where did you install Nextcloud from:** Downloaded from nextcloud.com

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - audioplayer: 2.8.4
 - bookmarks: 2.0.3
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_markdown: 2.0.6
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - news: 13.1.6
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.2
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - ocsms: 2.1.3
 - password_policy: 1.6.0
 - polls: 0.10.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - spreed: 6.0.4
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.1
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "varifold.mimuw.edu.pl",
        "193.0.96.2"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/localhost\/nextcloud",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "ocsms"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** Ubuntu 18.04.3 LTS

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by georgehrke** [comment]
Can you please provide logs?

**Comment by sk197876** [comment]
/var/log/apache2/error.log:

[Wed Sep 04 00:07:50.427700 2019] [mpm_prefork:notice] [pid 27646] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1c configured -- resuming normal operations
[Wed Sep 04 00:07:50.427722 2019] [core:notice] [pid 27646] AH00094: Command line: '/usr/sbin/apache2'
[Wed Sep 04 00:07:50.431423 2019] [:error] [pid 5442] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Wed Sep 04 00:07:50.432209 2019] [:error] [pid 5442] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Wed Sep 04 12:04:51.390320 2019] [autoindex:error] [pid 19351] [client 127.0.0.1:48300] AH01276: Cannot serve directory /var/www/nextcloud/core/doc/user/_static/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Wed Sep 04 12:06:37.632048 2019] [autoindex:error] [pid 19352] [client 127.0.0.1:48390] AH01276: Cannot serve directory /var/www/nextcloud/core/doc/user/_static/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive

nextcloud.log: does not say anything about this issue.

Firefox console says (in Polish):

Błąd przetwarzania XML: nieprawidłowo sformowany
Obszar: https://varifold.mimuw.edu.pl/nextcloud/remote.php/dav/calendars/slawek/tttt-1/
Numer wiersza: 13, kolumna 27: tttt-1:13:27

Błąd przetwarzania XML: nieprawidłowo sformowany
Obszar: https://varifold.mimuw.edu.pl/nextcloud/index.php/apps/calendar/
Numer wiersza: 13, kolumna 27: calendar:13:27

**Comment by sk197876** [comment]
The problem is with the symbol with hex: 0x12.

**Comment by SoerenBusse** [comment]
Hey there, is there any update on this? We ran into the same issue during import of an external calendar, which contains the non-printable character 0x02.

@sk197876 How have you fixed it?

**Comment by sk197876** [comment]
> @sk197876 How have you fixed it?

I removed the special character from the description. I have no other suggestions.

**Comment by miaulalala** [comment]
can't reproduce
