### ISSUE TITLE
No email notification if event update

### ISSUE THREAD

**Issue by PittRo** [nextcloud/calendar#1455]
### Steps to reproduce
1. Calendar event invitation
2. invitation aceppted without change of day and time
### Expected behaviour
no notification by email
### Actual behaviour
notification by email

I would understand the notification if there are changes or the event is declined.
Notifications with nextcloud are really enough.

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

When reporting it in the server repo, please  **fill the entire issue template**.
