### ISSUE TITLE
Duplicate or copy/paste events

### ISSUE THREAD

**Issue by vince-from-nice** [nextcloud/calendar#1470]
Hello,

I need to duplicate or copy/paste events in my calendar. For now that feature doesn't exist so I have to continue to use Google Calendar :(

A related issue has already been opened (https://github.com/nextcloud/calendar/issues/113) but it has been closed without having a real solution.

Thanks, Vincent.

**Comment by georgehrke** [comment]
Please don't open duplicate issues for rejected requests.

See my response in #113: https://github.com/nextcloud/calendar/issues/113#issuecomment-304435902

**Comment by vince-from-nice** [comment]
Sorry but the reason why you've rejected the request is not clear.

The issue #17 is very different from the required solution. 

Could you please reopen the issue (#113 or that one) ?
