### ISSUE TITLE
Optimize bundle size

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#1474]
- [x] dynamic loading of locales in bundle 
- [ ] #1473 
- [x] replace Babel polyfill with core-js
- [x] Do not import Nextcloud/vue, but individual components 
- [ ] ...

**Comment by raimund-schluessler** [comment]
For Tasks the effect was not huge, but removing comments saved 35 kB https://github.com/nextcloud/tasks/pull/571

**Comment by georgehrke** [comment]
Only #1473 is left, closing this ticket then.
