### ISSUE TITLE
javascript errors in browser console when opening the calendar 

### ISSUE THREAD

**Issue by BigMichi1** [nextcloud/calendar#1477]
### Steps to reproduce
1. create a new user in nextcloud
2. open calendar
3.

### Expected behaviour
no errors in browser console

### Actual behaviour
3 errors are shown in the broser console:

    vendor.js:7159 TypeError: r.split is not a function
    at app.js:2922
    at vendor.js:9010
    at vendor.js:14605
    at e (vendor.js:9516)
    at e (vendor.js:9516)
    at i.$digest (vendor.js:10292)
    at i.$apply (vendor.js:10427)
    at HTMLInputElement.<anonymous> (vendor.js:14418)
    at HTMLInputElement.dispatch (jquery.js:4435)
    at HTMLInputElement._.handle (jquery.js:4121)

looks like there is an issue in this line
        timezone = timezone.split('_').join(' ');

### Server configuration

**Operating system:** Linux 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.9 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 

7.2.19-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bcmath, bz2, calendar, ctype, curl, dom, mbstring, facedetect, fileinfo, ftp, gd, geoip, gettext, gmp, horde_lz4, iconv, igbinary, imagick, imap, intl, json, ldap, libpuzzle, exif, mongodb, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, propro, raphf, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, ssh2, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, http, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Calendar version:** 1.7.1

**Updated from an older installed version or fresh install:** updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - apporder: 0.7.1
 - bookmarks: 2.0.3
 - calendar: 1.7.1
 - circles: 0.17.7
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_accesscontrol: 1.6.0
 - files_external: 1.7.0
 - files_pdfviewer: 1.5.0
 - files_retention: 1.5.1
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 4.1.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.17.0
 - maps: 0.1.2
 - metadata: 0.9.0
 - news: 13.1.6
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.2
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - passwords: 2019.9.0
 - phonetrack: 0.5.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - socialsharing_diaspora: 1.0.4
 - socialsharing_email: 1.0.5
 - socialsharing_facebook: 1.0.4
 - socialsharing_googleplus: 1.0.4
 - socialsharing_twitter: 1.0.4
 - spreed: 6.0.4
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_totp: 3.0.1
 - updatenotification: 1.6.0
 - user_external: 0.7.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - user_ldap

**Nextcloud configuration:**

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 1
    },
    "trusted_domains": [
        "mydomain.de"
    ],
    "dbtype": "pgsql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "https:\/\/mydomain.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "tls",
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "updater.release.channel": "stable",
    "defaultapp": "apporder",
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "mydomain.de",
                143,
                "tls",
                "mydomain.de"
            ]
        }
    ],
    "app_install_overwrite": [
        "calendar"
    ]
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36

**Operating system:** Fedora 30

**CalDAV-clients:** no

#### Browser log
```
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:30 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
i @ globals.js:30
2vendor.js:23910 Attempting to call a FullCalendar method on an element with no calendar.
a.warn @ vendor.js:23910
globals.js:30 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
i @ globals.js:30
vendor.js:7159 TypeError: r.split is not a function
    at app.js:2922
    at vendor.js:9010
    at vendor.js:14605
    at e (vendor.js:9516)
    at e (vendor.js:9516)
    at i.$digest (vendor.js:10292)
    at i.$apply (vendor.js:10427)
    at vendor.js:6542
    at g (vendor.js:6710)
    at XMLHttpRequest.p.onload (vendor.js:6648)
(anonymous) @ vendor.js:7159
2vendor.js:7159 TypeError: r.split is not a function
    at app.js:2922
    at vendor.js:9010
    at vendor.js:14605
    at e (vendor.js:9516)
    at e (vendor.js:9516)
    at i.$digest (vendor.js:10292)
    at i.$apply (vendor.js:10427)
    at app.js:299
(anonymous) @ vendor.js:7159
vendor.js:7159 TypeError: r.split is not a function
    at app.js:2922
    at vendor.js:9010
    at vendor.js:14605
    at e (vendor.js:9516)
    at e (vendor.js:9516)
    at i.$digest (vendor.js:10292)
    at i.$apply (vendor.js:10427)
    at app.js:497
    at app.js:3820
    at Array.forEach (<anonymous>)
(anonymous) @ vendor.js:7159
vendor.js:7159 TypeError: r.split is not a function
    at app.js:2922
    at vendor.js:9010
    at vendor.js:14605
    at e (vendor.js:9516)
    at e (vendor.js:9516)
    at i.$digest (vendor.js:10292)
    at i.$apply (vendor.js:10427)
    at HTMLInputElement.<anonymous> (vendor.js:14418)
    at HTMLInputElement.dispatch (jquery.js:4435)
    at HTMLInputElement._.handle (jquery.js:4121)
(anonymous) @ vendor.js:7159
vendor.js:7159 TypeError: r.split is not a function
    at app.js:2922
    at vendor.js:9010
    at vendor.js:14605
    at e (vendor.js:9516)
    at e (vendor.js:9516)
    at i.$digest (vendor.js:10292)
    at i.$apply (vendor.js:10427)
    at vendor.js:11251
    at ni.completeTask (vendor.js:11029)
    at vendor.js:3530
(anonymous) @ vendor.js:7159
(anonymous) @ vendor.js:6008
$digest @ vendor.js:10316
$apply @ vendor.js:10427
(anonymous) @ vendor.js:11251
completeTask @ vendor.js:11029
(anonymous) @ vendor.js:3530
vendor.js:7159 TypeError: r.split is not a function
    at app.js:2922
    at vendor.js:9010
    at vendor.js:14605
    at e (vendor.js:9516)
    at e (vendor.js:9516)
    at i.$digest (vendor.js:10292)
    at i.$apply (vendor.js:10427)
    at vendor.js:6542
    at g (vendor.js:6710)
    at XMLHttpRequest.p.onload (vendor.js:6648)
(anonymous) @ vendor.js:7159
(anonymous) @ vendor.js:6008
$digest @ vendor.js:10316
$apply @ vendor.js:10427
(anonymous) @ vendor.js:6542
g @ vendor.js:6710
p.onload @ vendor.js:6648
load (async)
(anonymous) @ vendor.js:6637
(anonymous) @ vendor.js:6494
(anonymous) @ vendor.js:6381
(anonymous) @ vendor.js:9657
(anonymous) @ vendor.js:9708
$digest @ vendor.js:10272
$apply @ vendor.js:10427
(anonymous) @ vendor.js:11251
completeTask @ vendor.js:11029
(anonymous) @ vendor.js:3530
vendor.js:7159 TypeError: r.split is not a function
    at app.js:2922
    at vendor.js:9010
    at vendor.js:14605
    at e (vendor.js:9516)
    at e (vendor.js:9516)
    at i.$digest (vendor.js:10292)
    at i.$apply (vendor.js:10427)
    at vendor.js:11251
    at ni.completeTask (vendor.js:11029)
    at vendor.js:3530
(anonymous) @ vendor.js:7159
(anonymous) @ vendor.js:6008
$digest @ vendor.js:10316
$apply @ vendor.js:10427
(anonymous) @ vendor.js:11251
completeTask @ vendor.js:11029
(anonymous) @ vendor.js:3530
setTimeout (async)
l.defer @ vendor.js:3530
e @ vendor.js:11236
(anonymous) @ app.js:1445
(anonymous) @ vendor.js:11243
completeTask @ vendor.js:11029
(anonymous) @ vendor.js:3530
vendor.js:7159 TypeError: r.split is not a function
    at app.js:2922
    at vendor.js:9010
    at vendor.js:14605
    at e (vendor.js:9516)
    at e (vendor.js:9516)
    at i.$digest (vendor.js:10292)
    at i.$apply (vendor.js:10427)
    at vendor.js:11251
    at ni.completeTask (vendor.js:11029)
    at vendor.js:3530
(anonymous) @ vendor.js:7159
(anonymous) @ vendor.js:6008
$digest @ vendor.js:10316
$apply @ vendor.js:10427
(anonymous) @ vendor.js:11251
completeTask @ vendor.js:11029
(anonymous) @ vendor.js:3530
setTimeout (async)
l.defer @ vendor.js:3530
e @ vendor.js:11236
(anonymous) @ app.js:1448
(anonymous) @ vendor.js:11243
completeTask @ vendor.js:11029
(anonymous) @ vendor.js:3530
```

**Comment by georgehrke** [comment]
@BigMichi1 Can you still reproduce the same behaviour in Calendar 2?

**Comment by BigMichi1** [comment]
no longer reproducible in calendar 2
