### ISSUE TITLE
Integrity check error: signature file missing

### ISSUE THREAD

**Issue by evolozzy** [nextcloud/calendar#1478]
### Steps to reproduce
1. Update to version 1.7.1
2.
3.

### Expected behaviour
Integrity check should return no errors.

### Actual behaviour
Integrity check returns the following error for signature. 
Integrity check looks for the file `signature.json` but cannot find it. 
While every other app has it, I couldn't see it in the `appinfo` folder.

### Server configuration

**Operating system**: OpenSUSE Leap 15.1

**Web server:** Apache

**Database:** mysql

**PHP version:** 7.25

**Server version:** (see your admin page) 4.2.33

**Calendar version:** (see the apps page) 1.7.1

**Updated from an older installed version or fresh install:** From older

**Signing status (ownCloud/Nextcloud 9.0 and above):** Nextcloud 16.0.4

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [calendar] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

#### Log file (data/nextcloud.log)
```
{"reqId":"sUVgwUNBoPWSLEFBP3mO","level":3,"time":"2019-09-09T05:04:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"\/occ","message":"file_get_contents(\/srv\/www\/nextcloud\/apps\/calendar\/appinfo\/signature.json): failed to open stream: No such file or directory at \/srv\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#41","userAgent":"--","version":"16.0.4.1"}
```

**Comment by georgehrke** [comment]
That's expected as we don't ship a `signature.json` anymore, we sign it when uploading it to the App Store

**Comment by Schmuuu** [comment]
Hello @georgehrke 

How can he avoid the warnings on the NC overview page then? The integrety check seems not informed that the apps are signed in the App Store then ;)
