### ISSUE TITLE
Calendars don't load - (evaluating 'T.propStat[0]')

### ISSUE THREAD

**Issue by maxtealfer** [nextcloud/calendar#1485]
Hello,

I have an issue with our calendar frontend.
With the previous version it has worked fine.
Now we cannot use it at all. Did anybody experience such an error before?
Thanks in advance for any help.

### Steps to reproduce
1, Log into nextcloud on web interface
2, Open the calendar app

### Expected behaviour
- events are visible
- events can be added
- calendars work correctly

### Actual behaviour
- no events are visible
- no events can be added
- enabled calendars show an octagon icon with an exclamation mark in it
  - tooltip message on icon advises to open the JS console
  - in JS console I can see the following entry (not an error): /remote.php/dav/calendars/[my-user-id]/personal/ - TypeError: undefined is not an object (evaluating 'T.propStat[0]') - app.js:3966
- newly added calendars behave the same
- reinstalling the app did not help in any ways 

## Server configuration detail

**Operating system:** Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.25

**PHP version:** 

7.2.15-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, json, ldap, exif, memcache, msgpack, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

**Nextcloud version:** 14.0.6 - 14.0.6.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12 to 13 then to 14

**Where did you install Nextcloud from:** nextcloud homepage

List of activated apps
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - admin_audit: 1.4.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.6.6
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - dav: 1.6.1
 - drawio: 0.9.3
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_accesscontrol: 1.4.0
 - files_downloadactivity: 1.3.0
 - files_external: 1.5.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - onlyoffice: 2.3.0
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - spreed: 4.0.4
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - user_ldap: 1.4.0
 - workflowengine: 1.4.0
Disabled:
 - encryption
 - external
 - files_clipboard
 - user_external

Configuration (config/config.php)

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "14.0.6.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "allow_self_signed": true,
    "theme": "",
    "loglevel": 2,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Memcached",
    "memcached_servers": [
        [
            "localhost",
            11211
        ]
    ],
    "onlyoffice": {
        "verify_peer_off": true
    },
    "updater.release.channel": "production",
    "data-fingerprint": "45fc3cf490612a3947ec2ed2b2ac274e",
    "activity_expire_days": 120
}

**Are you using external storage, if yes which one:** none

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15, Tested also on Chrome - same behaviour

**Operating system:** macOS 10.14.6

## Logs

Browser log

[Log] /remote.php/dav/calendars/88FD1D0A-272E-4FCD-BAB4-8BCA0CAB16E2/personal_shared_by_87146AE3-758A-419B-93BE-7C8B45680590/ – TypeError: undefined is not an object (evaluating 'T.propStat[0]') — app.js:3966 (app.min.js, line 1)
TypeError: undefined is not an object (evaluating 'T.propStat[0]') — app.js:3966
[Log] /remote.php/dav/calendars/88FD1D0A-272E-4FCD-BAB4-8BCA0CAB16E2/test/ (app.min.js, line 1)
TypeError: undefined is not an object (evaluating 'T.propStat[0]')
[Log] /remote.php/dav/calendars/88FD1D0A-272E-4FCD-BAB4-8BCA0CAB16E2/personal/ – TypeError: undefined is not an object (evaluating 'T.propStat[0]') — app.js:3966 (app.min.js, line 1)
TypeError: undefined is not an object (evaluating 'T.propStat[0]') — app.js:3966

**Comment by georgehrke** [comment]
Can you please post the result of /remote.php/dav/calendars/88FD1D0A-272E-4FCD-BAB4-8BCA0CAB16E2/personal_shared_by_87146AE3-758A-419B-93BE-7C8B45680590/  from the network console?

**Comment by maxtealfer** [comment]
Hello,

Here it is:

`<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/remote.php/dav/calendars/88FD1D0A-272E-4FCD-BAB4-8BCA0CAB16E2/personal_shared_by_87146AE3-758A-419B-93BE-7C8B45680590</d:href><d:propstat><d:prop><oc:calendar-enabled/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>`

**Comment by georgehrke** [comment]
@tcitworld Can you reproduce this?

I can't

**Comment by tcitworld** [comment]
> Nextcloud version: 14.0.6 - 14.0.6.0

Your version is unsupported, so that could explain things.

**Comment by maxtealfer** [comment]
We upgraded to 15.0.11 and this particular thing is fixed there. Thanks for the hint.
