### ISSUE TITLE
Feature Request: Event added by user needs Aproval of Calendarowner

### ISSUE THREAD

**Issue by tobyps** [nextcloud/calendar#1494]
Hi,
would it be possible to have an option that users can add an event to a shared calendar but the event is only shown to all users (the calendar is shared with) after aproval of the owner of the calendar?
thx

**Comment by georgehrke** [comment]
@tobyps Can you please describe the use-case?

**Comment by tobyps** [comment]
We have a room that can be reserved by putting the details in a list outside of the room. 
After we had a few times the problem, that we had collisions between events because some users grabbed good spots before a larger event (which needed more time to coordinate the dates) we established that the reservations had to be aproved.
That works quite good, but it would be great to move the planning into a calendar, so everybody can check when the room would be available without checking the physical list.
The feature would replicate this and make it possible for every user to create the event themselves, but all users would only see the approved events.
Of course there is always the option to just make the calendar read only and to let the owner enter the information. But as I don't if maybe somebody else could use is and how much work it would be (if it is even possible), I thought I ask.

**Comment by rkaraba** [comment]
there is some work on resource booking. 
https://help.nextcloud.com/t/resources-in-calendar-app/2409/13

**Comment by georgehrke** [comment]
Definitely nothing we implement for shared calendars.

Closing as Duplicate of  https://github.com/nextcloud/server/issues/17349
