### ISSUE TITLE
Allow archiving calenders

### ISSUE THREAD

**Issue by benwaffle** [nextcloud/calendar#1496]
I want to be able to hide calendars that I don't use anymore, without deleting the data.

**Comment by georgehrke** [comment]
@tcitworld Any opinion on this one? :) 

I don't think we need this nor am i aware of any other CalDAV software offering this.
Just export to ICS and store it in some folder ...

**Comment by tcitworld** [comment]
Yeah, I feel like it's related to what we discussed around https://github.com/nextcloud/calendar/issues/9, making sure unused calendar don't bother the user.

Otherwise just export the data or maybe see https://github.com/nextcloud/server/issues/1662

**Comment by georgehrke** [comment]
Closing in that case.
