### ISSUE TITLE
Don't see the save button on create a event on phone

### ISSUE THREAD

**Issue by noecom12** [nextcloud/calendar#1507]
### Steps to reproduce
1. open calander app on your pone
2. create a event
3. you don't see de save button
4. you don't can scrol down to see the save button

![Image of issues](https://i.ibb.co/bHNVjgX/Screenshot-20191002-202232.jpg)

### Expected behaviour
see the save button

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
debian
**Web server:**
apache2
**Database:**
MariaDB
**PHP version:**
7.2
**Server version:** (see your admin page)
16.0.5
**Calendar version:** (see the apps page)
1.7.1
**Updated from an older installed version or fresh install:**
Older installed versions
**Signing status (ownCloud/Nextcloud 9.0 and above):**
nextcloud 16.0.5
```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
`echnical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- news
	- EXTRA_FILE
		- vendor/arthurhoaro/favicon/resources/cache/url06cda0335c4acf2cd6035a1c46478678
		- vendor/arthurhoaro/favicon/resources/cache/urlbacfb3562ab4d90663cf7cb1add73ea0
		- vendor/arthurhoaro/favicon/resources/cache/url63ba660bb13761dd7b8e9ae7656d6b8e

Raw output
==========
Array
(
    [news] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [vendor/arthurhoaro/favicon/resources/cache/url06cda0335c4acf2cd6035a1c46478678] => Array
                        (
                            [expected] => 
                            [current] => aa5153befa5f7937f1746be201dd96ec9e187d74cd7b5817ff469105bbd68a2829cdaf2949fb15d68ca10946c505090fe0fa40b04f04d36bbd9bfdde6b10f2a3
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlbacfb3562ab4d90663cf7cb1add73ea0] => Array
                        (
                            [expected] => 
                            [current] => f3eca02a17853fd4fc917f862055ab863f1919a1503ccfac898fcf50d1e3e7615ca63cda792fea43f88a63dcba9fdf91f627a064514cc9e4f3f7e524866683ae
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url63ba660bb13761dd7b8e9ae7656d6b8e] => Array
                        (
                            [expected] => 
                            [current] => b8ece79493c3baf1f507b0ee66ccda2b2f78485e1221996fdc70d48830cf3def4a0b66ce061daf1530d59e38d5305df93e73f0602e9b2f9908de011a966d2445
                        )

                )

        )

)`
**List of activated apps:**
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.1
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.4
  - dav: 1.9.2
  - deck: 0.6.6
  - external: 3.3.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_downloadactivity: 1.5.0
  - files_external: 1.7.0
  - files_markdown: 2.1.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.17.0
  - metadata: 0.9.0
  - news: 14.0.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.2
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - passwords: 2019.9.0
  - polls: 0.10.2
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - socialsharing_email: 1.0.5
  - socialsharing_facebook: 1.0.4
  - socialsharing_twitter: 1.0.4
  - spreed: 6.0.4
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - circles
  - encryption
  - files_fulltextsearch_tesseract
  - firstrunwizard
  - scanner
  - socialsharing_diaspora
  - socialsharing_googleplus
  - support
  - user_backend_sql_raw
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "https:\/\/supergroup\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "data-fingerprint": "8f9d55829c8c6beb64ebc9c4f79efc6d",
        "log_type": "file",
        "logfile": "\/var\/www\/html\/nextcloud.log\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "updater.release.channel": "stable",
        "theme": "",
        "mail_sendmailmode": "smtp",
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Chrome
**Operating system:**
Android
**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by tcitworld** [comment]
Duplicate from #1079, thanks !
