### ISSUE TITLE
Add support of vjournal entries 

### ISSUE THREAD

**Issue by LightTemplar** [nextcloud/calendar#1514]
Please add support of vjournal entries. Or, if Nextcloud Calendar already has it, let CalDAV clients know it.
For now neither Kontact nor Evolution lets me create journals in the Nextcloud Calendar.

**Comment by georgehrke** [comment]
We decided that calendars should be default only be created with VEVENT support. Nextcloud itself supports VJOURNAL itself though. Please create calendars with VJOURNAL through Kontact or Evolution

**Comment by devvv4ever** [comment]
Just a small addition here: DAVx5 (on Android) can create collections with VJOURNAL on Android, too (on your Nextcloud). And there is a first Android app that can be used to store entries with this standard (it can also be synced via DAVx5 now). The name of this app is "jtx Board"

**Comment by LightTemplar** [comment]
@devvv4ever, thanks! That app looks very promising, I'll give it a try!

**Comment by devvv4ever** [comment]
You may want to follow also: https://github.com/nextcloud/tasks/issues/1955 :)

**Comment by ChristophWurst** [comment]
@nicolaheile I've run into that myself. Please file a new feature request for the ability to change the supported components of an existing calendar. We have to check the RFCs. This change might or might not be allowed.

**Comment by nicolaheile** [comment]
I fixed my existing calendars with this tip: https://github.com/nextcloud/server/issues/14992#issuecomment-530275707

"If you want to add VJOURNAL support to an existing calendar, just take a look at the table oc_calendars and alter the value of components from VEVENT to VEVENT,VJOURNAL."

**Comment by ChristophWurst** [comment]
Yeah. The idea of the feature request is to make this accessible for every user.

**Comment by tcitworld** [comment]
> We have to check the RFCs. This change might or might not be allowed.

It's not.

> Since this property is protected, it cannot be changed by clients using a PROPPATCH request.  However, clients can initialize the value of this property when creating a new calendar collection with MKCALENDAR.

https://www.rfc-editor.org/rfc/rfc4791.html#section-5.2.3

This means you can create a new calendar with any components you want, but not alter existing calendars supported components set. Doing this in the server can cause unexpected issues with clients.

**Comment by ChristophWurst** [comment]
Thank you @tcitworld

**Comment by QQ-War** [comment]
by change the components still there are no GUI, only 3rd party like jX board can see the content.
