### ISSUE TITLE
Allow to share calendar with circles

### ISSUE THREAD

**Issue by doobry-systemli** [nextcloud/calendar#1515]
It would be nice to allow sharing calendars with Nextcloud circles (from the [circles app](https://github.com/nextcloud/circles/)). Is this something that you plan to implement?

On shared Nextcloud instances without admin access, circles are the only way to maintain groups on your own. Would be nice if the calendar app would support them.

**Comment by georgehrke** [comment]
This is already working. Be sure to update to the latest version.

**Comment by georgehrke** [comment]
For reference: this is the pull-request that implemented it: https://github.com/nextcloud/calendar/pull/602

**Comment by doobry-systemli** [comment]
Oh thanks. I'm running Nextcloud 15.0.11 and Calendar App 1.6.6. According to release dates, those versions should ship the referenced merge requests. Still, circles are not offered as an option when trying to share calendars.

**Comment by georgehrke** [comment]
You need at least Nextcloud 16. (https://github.com/nextcloud/server/pull/14573#issue-258775550)

**Comment by doobry-systemli** [comment]
Thanks!
