### ISSUE TITLE
Abonement between two NC-Server won't work

### ISSUE THREAD

**Issue by MenkeWerbeagentur** [nextcloud/calendar#1527]
Hi,

### Steps to reproduce
I have two NC Server with the same IP. cloud.domain1.tld and cloud.domain2.tld
They own different companies but they work together.
Now one Member of domain1 will share his calendar to am member of the domain2

### Expected behaviour
see the abonement of the linked calendar

### Actual behaviour
But if we take the link for the Abonement we recieve:
"The remote server does not allow access to the calendar (HTTP {401} error)"

## Server configuration detail

**Operating system:** Linux 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.27

**PHP version:** 

7.2.23
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 16.0.5 - 16.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - announcementcenter: 3.5.1
 - apporder: 0.8.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - camerarawpreviews: 0.7.1
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - dashboard: 6.0.0
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_accesscontrol: 1.6.0
 - files_downloadactivity: 1.5.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trackdownloads: 1.5.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 4.1.3
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - richdocuments
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.menke.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.5.1",
    "overwrite.cli.url": "https:\/\/cloud.menke.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "theme": "",
    "loglevel": 2,
    "maintenance": false,
    "app_install_overwrite": [
        "documents"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Operating system:** Windows 7

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

loader.js:52 Refused to load the script 'https://cloud.cornexion.com/apps/firstrunwizard/js/firstrunwizard.js' because it violates the following Content Security Policy directive: "script-src 'nonce-N3V6eS9ZUlA1ZEpxaUF0V1Y2RzMwdjJURDZHczMwVE1oK09yN01XcUdKTT06aFpTWW51WW8wWVE4enpJQWVKYmxtc2oyV2ZiMnJ3eS84cXZPbnJDRmZPaz0='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ loader.js:52
cloud.cornexion.com/:1 Uncaught (in promise) Failed to load script from /apps/firstrunwizard/js/firstrunwizard.js
2about.js?v=759ef963-16:8 Uncaught (in promise) TypeError: Cannot read property 'open' of undefined
    at about.js?v=759ef963-16:8
2/index.php/apps/calendar/v1/proxy?url=https%3A%2F%2Fcloud.menke.de%2Findex.php%2Fapps%2Fcalendar%2Fembed%2FcGLZTFdrBqJ9dYdp:1 Failed to load resource: the server responded with a status of 422 ()
vendor.js:6694 GET https://cloud.cornexion.com/index.php/apps/calendar/v1/proxy?url=https%3A%2F%2Fcloud.menke.de%2Findex.php%2Fapps%2Fcalendar%2Fembed%2FcGLZTFdrBqJ9dYdp 422
</details>

**Comment by georgehrke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by tcitworld** [comment]
> But if we take the link for the Abonement we recieve:
> "The remote server does not allow access to the calendar (HTTP {401} error)"

Be sure to take the export link and not the public view link.

**Comment by MenkeWerbeagentur** [comment]
Hi,

i tried:
https://cloud.domain1.tld/remote.php/dav/principals/users/name/ 
<https://cloud./remote.php/dav/principals/users/menke//>
https://cloud.domain1.tld/remote.php/dav/ 
<https://cloud./remote.php/dav//>
https://cloud. 
<https://cloud.menke.de/remote.php/dav/calendars/menke///>.domain1.tld 
<https://cloud./remote.php/dav//>/remote.php/dav/calendars/name/ 
<https://cloud.menke.de/remote.php/dav/calendars/menke///>

everytime the same result.

Kind regards
Jens


------ Originalnachricht ------
Von: "Thomas Citharel" <notifications@github.com>
An: "nextcloud/calendar" <calendar@noreply.github.com>
Cc: "MenkeWerbeagentur" <menke@menke.de>; "Author" 
<author@noreply.github.com>
Gesendet: 13.10.2019 14:23:07
Betreff: Re: [nextcloud/calendar] Abonement between two NC-Server won't 
work (#1527)

**Comment by tcitworld** [comment]
You first need make the calendar accessible publicly by clicking « Share link », then on the public calendar page, get the link from the « download » button.
It should something like `/remote.php/dav/public-calendars/%some-id%?export`

**Comment by MenkeWerbeagentur** [comment]
Hi Thomas,

it was a little bit misleading to me. I didn't recognised to change the 
tab to the shared calender. And there to take the link from the upper 
right buttom. I searched all the time in the main calendar window.

Thanks a lot. Know it is working.
Can I write somewhere a little tutorial for the othe may have the same 
problem? Shall I post it to my formum question?

regards
Jens

------ Originalnachricht ------
Von: "Thomas Citharel" <notifications@github.com>
An: "nextcloud/calendar" <calendar@noreply.github.com>
Cc: "MenkeWerbeagentur" <menke@menke.de>; "Author" 
<author@noreply.github.com>
Gesendet: 13.10.2019 16:31:22
Betreff: Re: [nextcloud/calendar] Abonement between two NC-Server won't 
work (#1527)
