### ISSUE TITLE
How to get back contact birthdays after deletion

### ISSUE THREAD

**Issue by xMartin** [nextcloud/calendar#153]
I just deleted the item "contact birthdays". How do I get it back?

**Comment by georgehrke** [comment]
Do you have a command line access to the server? 

In that case use `php occ dav:sync-birthday-calendar`

**Comment by georgehrke** [comment]
btw, please ask stuff like this on https://help.nextcloud.com in the future.
It's no bug report, but only a simple question and there are many more people on around in our discourse to help you.

**Comment by jancborchardt** [comment]
@georgehrke sure it’s a question, but it points to a bug. ;) You can remove the birthday calendar, by accident or whatever, and not get it back.

How about we make it non-deletable, because you can already disable it / make it invisible? Or somehow make it re-addable via settings.

**Comment by georgehrke** [comment]
Well, you will be able to save it with https://github.com/nextcloud/calendar/pull/148 ;) 
AFAIK the birthday calendar is regenerated on every cron call. So it will reappear within 24 hours.

**Comment by jancborchardt** [comment]
Ok – so even after deletion it will reappear within 24 hours? Then that’s also strange. Either deletion is permanent until willful re-addition or we shouldn’t have it. ;)

**Comment by georgehrke** [comment]
I'm not sure about this regeneration, but this issue belongs in the server repo, because the birthday calendar is generated by the dav app.
The calendar handles it as an ordinary (read-only) calendar like any other.

**Comment by Pazu** [comment]
For what it's worth, after deleting Contact Birthdays in my 11.0.3 instance more than 24 hours has gone by, and cron has _not_ re-created Contact Birthdays.

**Comment by belidzs** [comment]
@Pazu I had the same problem and it turned out if you have deleted a birthday calendar as a user, you have to specify that user name exactly to have it regenerated for them:

In my case the command was `sudo -u www-data php occ dav:sync-birthday-calendar belidzs`
