### ISSUE TITLE
 Sharing backend for principals not found - ldap backend

### ISSUE THREAD

**Issue by k4tfish** [nextcloud/calendar#154]
I cannot share calenders with AD users. While searching for a contact to share, the app doesn't show any users. 

The following appears in the log: "Sharing backend for principals not found"

There was a similar issue in the oc calender app. https://github.com/owncloud/core/issues/238271

-- k4tfish - calendar 1.4.0

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
