### ISSUE TITLE
EXDATE not properly respected (floating EXDATE)

### ISSUE THREAD

**Issue by JD145** [nextcloud/calendar#1553]
I have a event series and deleted a single event with Thunderbird (synced via caldav). The deleted event still appears in the web interface (of course reloaded multiple times after deletion), but on Android (DAVx5 used) the single event is deleted correctly.
Is it possible that there is a bug in web interface?

**Steps to reproduce**
1. Import the attached [issue.ics](https://github.com/nextcloud/calendar/files/3752491/issue.ics.txt) (provided by an university)
2. Delete a single event using Thunderbird

**Expected behaviour**
The deleted event should also dissappear in the web interface.

**Actual behaviour**
The deleted event will be shown. In Thunderbird and Android Calendar App dissapear the event.

**Calendar app**
Calendar app version: 1.7.1
CalDAV-clients used: Thunderbird (60.9.0 (32-bit)) Lightning (6.2.9), DAVx5 (2.5.5-ose (302))

**Client configuration**
Browser: Firefox 69.0.3 (64-Bit)
OS: Windows 10 Pro 1903 (Build 18362.356)

**Server configuration**
Operating system: Debian 10.1
Web server: Nginx
Database; PostgreSQL
PHP version: 
Nextcloud version: 17.0.0 (fresh install)
List of activated apps:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - event_update_notification: 1.0.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0

Nextcloud configuration:
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/domain.com",
        "dbtype": "pgsql",
        "version": "17.0.0.9",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php"
    }
}
```

**Logs**
Web server error log (nginx):
[nextcloud_error.log](https://github.com/nextcloud/calendar/files/3752557/nextcloud_error.log)

Log file (data/nextcloud.log):
[nextcloud.log](https://github.com/nextcloud/calendar/files/3752540/nextcloud.log)

**Screenshots**
correct: 
![Thunderbird](https://user-images.githubusercontent.com/15321330/67235679-df6f9d00-f447-11e9-86bb-7d5379c15b9a.JPG)

wrong:
![web interface](https://user-images.githubusercontent.com/15321330/67235685-e26a8d80-f447-11e9-9c2d-efd735cece29.JPG)

**Comment by georgehrke** [comment]
Please fill **the entire template** and provide an example ics file.

**Comment by georgehrke** [comment]
There is a duplicate `EXDATE` for that day, That might be causing issues:
```
EXDATE:20200106T095000
EXDATE:20191230T095000
EXDATE:20191223T095000
EXDATE:20200106T085000Z
```

**Comment by georgehrke** [comment]
Still able to reproduce on 2.0.0 beta1.
Possibly upstream related.

**Comment by miaulalala** [comment]
Can't reproduce any longer
