### ISSUE TITLE
"Deep" link calendar views / change URL on navigation

### ISSUE THREAD

**Issue by fwolfst** [nextcloud/calendar#1558]
**Is your feature request related to a problem? Please describe.**
If I want to look up e.g. Summer of next year in the web-ui I have to click multiple times to change the month until I am "where" I want to be. Also, I cannot send a link to the xth week of year y to someone.

**Describe the solution you'd like**
I would like that if I navigate to january 2023 that the URL reflects that (e.g. `https://cloud.my/index.php/apps/calendar/years/2023/months/01/`, or `.../2023/01`) and that if I enter that URL I get that month view directly.

**Describe alternatives you've considered**
Using another calender client can make navigation easier, but I speak about the web-ui.

**Additional context**
Somewhat related to https://github.com/nextcloud/calendar/issues/21 .

**Comment by georgehrke** [comment]
Already implemented in Calendar 2.0.0 beta1

**Comment by fwolfst** [comment]
awesome. quickest positive issue reply ever ;) .
