### ISSUE TITLE
Show week numbers more nicely integrated

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#1571]
Currently week numbers get a whole column, which looks a bit off and complex:

![](https://user-images.githubusercontent.com/1250540/67218398-9a873e80-f426-11e9-863c-82b139e9271d.png)
(Screenshot nicked from you @georgehrke ;)

Nicer would be if they would just show in the top left of the leftmost column. Yes it would overlay the first day, but that also marks the beginning of that week.

**Comment by georgehrke** [comment]
I get your point, but this is how upstream implemented it.
The only way to get the way you suggested is implementing our own month and week views, which is honestly kind of an overkill just for the sake of placing the week number somewhere else. :)

**Comment by georgehrke** [comment]
Nevermind what i just said, upstream has an option for that: https://fullcalendar.io/docs/weekNumbersWithinDays

Let me set that.
