### ISSUE TITLE
Style regression in top left of navigation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#1572]
Just looking at it style-wise, the top left of the calendar regressed from looking light to now looking bulky:
![top left of calendar before](https://user-images.githubusercontent.com/925062/67331547-3182f200-f51e-11e9-9006-14ad9b78360f.png) ![top left of calendar](https://user-images.githubusercontent.com/925062/67331549-3182f200-f51e-11e9-9b93-254748516187.png)

The main thing that changed is that the month picker as well as the previous / next month arrows are now styled as buttons. This is not really necessary and we could remove that again. (As long as the focus and hover feedback is proper of course.)

**Comment by georgehrke** [comment]
> This is not really necessary and we could remove that again. 

It is necessary. We had multiple people requesting a DatePicker, because they never figured out they were actually able to click onto "Oktober 2019"

So if it's clickable, we should show it by styling it like a button imo.

**Comment by georgehrke** [comment]
Please keep in mind that there is a pending issue about a new design anyway :) 
https://github.com/nextcloud/calendar/issues/1021

**Comment by jancborchardt** [comment]
Right, if we go forward with https://github.com/nextcloud/calendar/issues/1021#issue-393233730 instead that’s good! :)
