### ISSUE TITLE
Embed calendar blocked by Content-Security-Policy : frame-ancestors 'self'

### ISSUE THREAD

**Issue by nderambure** [nextcloud/calendar#1584]
### Steps to reproduce
1. Create a new calendar
2. Share it as public
3. Go to the public link url
4. Copy the given embed under the calendar title and paste it in another web page on a different domain name

### Expected behaviour
The calendar should show up in the iframe

### Actual behaviour
The calendar is blocked by the parameter 

### Calendar app
**Calendar app version:** 1.7.1

### Client configuration
**Browser:** Chrome 77 / Firefox 70 / Safari 13.0.2

**Operating system:** MacOS 10.14.6

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache 2.4.38

**Database:** MariaDB 10.3.17

**PHP version:** 7.3.9

**Nextcloud Version:** 16.0.5

**Updated from an older installed version or fresh install:** Updated since 13.xx

**List of activated apps:** Calendar / Contacts / Deck / Tasks / Text

**Comment by georgehrke** [comment]
@tcitworld You know better about this issue. Isn't it a duplicate?

**Comment by georgehrke** [comment]
Okay, I reopened #169 for now. Thx!

**Comment by nderambure** [comment]
Thx ;)
