### ISSUE TITLE
Hide event details properties info buttons when event in read-only mode

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#1585]
It feels strange and is probably not needed since values are already present.

Also tooltips are bad UX on mobile, but that's another topic.

What do you think @georgehrke @jancborchardt?

![](https://user-images.githubusercontent.com/1250540/67618758-d38f2c80-f7f3-11e9-88ff-5c568f0bc9e4.png)

**Comment by jancborchardt** [comment]
Right, also the "All day" checkbox is redundant when it’s not editable.

**Comment by georgehrke** [comment]
> also the "All day" checkbox is redundant when it’s not editable.

Opened a dedicated issue for it https://github.com/nextcloud/calendar/issues/1589
