### ISSUE TITLE
year view

### ISSUE THREAD

**Issue by h-2** [nextcloud/calendar#159]
It would be really great to have a "year view" in addition to day/week/month. I have many use-cases, e.g. "vacation days/weeks", or "time I am in Berlin" or "time the project room is in use".... often it just really helps to be able to see which weeks have something set and which don't. It is quite cumbersome to click through the months....
Thank you very much!

PS: this was already suggested some time ago, by someone else: https://forum.owncloud.org/viewtopic.php?t=2127

**Comment by tcitworld** [comment]
This needs to be implemented upstream in https://fullcalendar.io/

**Comment by tcitworld** [comment]
See https://github.com/fullcalendar/fullcalendar/issues/2525. It should come up at some point.

**Comment by IwishIcanFLighT** [comment]
Any update on this feature? Would be awesome to have it for our plannings.

**Comment by tcitworld** [comment]
It's currently blocked by the issue linked above.

**Comment by p-try** [comment]
Fullcalendar supports custom views, so this does not necessarily need to be integrated there first. @h-2 if you are interested in this feature at short notice, have a look at my fork. I have not opened a pull request because I didn't develop it against the vue branch, but I'm planning to do so.

**Comment by iromeister** [comment]
It would be really great to have this for our year planning.

**Comment by georgehrke** [comment]
@p-try Thank you for looking into this issue, but since this is an accepted issue upstream, i would prefer to have it implemented in fullcalendar directly. Do you mind sending your pull-request to FullCalendar directly? 

In case it gets rejected for some reason, we can still implement it in the calendar directly.

**Comment by alexanderdd** [comment]
Hi @p-try, any news? two comments up you said you are planning to make a pull request at a later point.

**Comment by jadamec** [comment]
+1

**Comment by bernd-wechner** [comment]
> This needs to be implemented upstream in https://fullcalendar.io/

There is a plugin to fullcalender.io:

https://github.com/p-try/fullcalendar-yearview

that does the job. To wit it is fair to conclude that NextCloud could not just fullcalendar.io but fullcalendar.io with this plugin. It is IMHO well worth doing as it adds immense value to the NextCloud calendar.

**Comment by danir-de** [comment]
@tcitworld Wouldn't the plugin that @bernd-wechner  suggested remove this issue from the blocked list?

> https://github.com/p-try/fullcalendar-yearview

**Comment by tcitworld** [comment]
If it gets updated, yes. https://github.com/p-try/fullcalendar-yearview/issues/3

**Comment by bernd-wechner** [comment]
Just a heads-up that this has apparently been implemented upstream now:

https://github.com/fullcalendar/fullcalendar/issues/1140#issuecomment-1414516747

Here's hoping that Nextcloud can merge this in from upstream!

**Comment by miaulalala** [comment]
Fullcalendar has been updated to 6.1.1: https://github.com/nextcloud/calendar/pull/4965/files

**Comment by alexanderdd** [comment]
here is an online demo https://fullcalendar.io/docs/multimonth-grid-demo
and this is the related blogpost https://fullcalendar.io/blog/2023/01/multimonth-and-more

**Comment by tony-engineering** [comment]
I'm also interested into this feature. Would be highly appreciated :) Cheers

**Comment by pippcat** [comment]
Me too. Any timescale on when the upstream update will be merged?

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/calendar/pull/5248
