### ISSUE TITLE
Event svg header picture has a "nodata" title when using default picture

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#1593]
And it shows when hovering over the picture.

**Comment by georgehrke** [comment]
Should we set a different title or remove all titles from all SVGs?

**Comment by tcitworld** [comment]
I think it's still useful for a11y to have a title on the picture, but I'm not sure how to handle the default one (change the `nodata` value or remove it in this particular case).
Maybe @nextcloud/accessibility could help?

**Comment by georgehrke** [comment]
If we decide to keep a title for the illustration, we end up with the next problem that the titles are hardcoded in the svg and not translatable

**Comment by skjnldsv** [comment]
css and hide it?

**Comment by georgehrke** [comment]
Yes, browser tooltip, not v-tooltip.

**Comment by georgehrke** [comment]
And if we want to keep it for accessibility, "No data" and all the other titles are not exactly meaningful. It should describe the actual content, like "Illustration of event: Two empty clipboards"

**Comment by georgehrke** [comment]
Current proposal: Keep this issue open to tackle it in the long run, remove the current titles, because they don't add any meaningful value.

@tcitworld @skjnldsv Any objections? :)
