### ISSUE TITLE
Permissions for shared calendars

### ISSUE THREAD

**Issue by Skiingmax** [nextcloud/calendar#160]
Hi there.

Two questions:

1) Is this feature gone in 1.4.0? I cannot see it. [http://i.stack.imgur.com/6b5nR.png](http://i.stack.imgur.com/6b5nR.png)
2) Is there a way to "protect" a shared calendar, that another user cannot "unshare" (click on the trash icon) it by accident??

Thanks in advance!!!

Best
skiingmax

**Comment by georgehrke** [comment]
> Is this feature gone in 1.4.0? I cannot see it

Yes, it's gone. Beginning with Nextcloud 9 and Calendar 1.0 we use the CalDAV sharing standard that doesn't allow this options. 

> Is there a way to "protect" a shared calendar, that another user cannot "unshare" (click on the trash icon) it by accident??

As a sharer you can't protect it and you won't be able to. Sharees should be able to unshare calendars. Accident deletion will be prevented with https://github.com/nextcloud/calendar/issues/12

**Comment by Skiingmax** [comment]
Wow – THANKS for the fast reply @georgehrke !!!

Even if the answers were not as satisfying as supposed ;-)
