### ISSUE TITLE
Make illustrations accessible

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#1610]
The illustration should contain a translated title for accessibility

Related to https://github.com/nextcloud/calendar/issues/1593

**Comment by Derkades** [comment]
How should this be done? Add strings for each language to https://github.com/nextcloud/calendar/blob/master/src/utils/illustration.js? Automatically translate event titles to English then try to match it with the English strings?

If the former, by making an announcement on transifex I'm sure there are many people who would like to contribute (including myself)

**Comment by tcitworld** [comment]
See #1593, the intention was to have strings that describe the picture itself, not the associated term. However it's possible that having an a11y title for a picture which only purpose is illustration is useless. Maybe @nextcloud/accessibility has more opinions on this.

**Comment by tyrylu** [comment]
Personally, if the purpose is really to make the UI nicer and the picture has no other added value, i would not describe it, it would make the navigation only more cluttered.

**Comment by Derkades** [comment]
I'd imagine it would not be visible in the UI directly, but used as alt text for the image for example? The same strings can be used for word matching in event titles though

**Comment by st3iny** [comment]
Illustrations were removed recently.
