### ISSUE TITLE
deleting a repeated event kills all events instead of proposing what to delete

### ISSUE THREAD

**Issue by tykayn** [nextcloud/calendar#1611]
i have no idea if this issue is dependent on nextcloud calendar or one of its libs it uses for the GUI, but the fact that we have no option to delete one or all events of a repeatition is really bad UX.
by default deleting a repeated event is killing them all, it would be great to have some questions answer to know what to delete :
only this event,
all the serie,
only the events before this one,
only after.

**Comment by georgehrke** [comment]
#7 

Already fixed in Calendar 2.0.0
