### ISSUE TITLE
identify e-mail of participants in event invitation

### ISSUE THREAD

**Issue by nextgen-networks** [nextcloud/calendar#162]
It would be cool to change the UI ab bit to make it possible to identify the "right" e-mail address for participants with more than one e-mail selected from the internal DAV/contacts app.

### Steps to reproduce
see screenshots

contact has more than 1 email address:
![2016-11-03_contacts-more_than_one_mail_per_contact](https://cloud.githubusercontent.com/assets/21206978/19978052/e9436a7a-a1f5-11e6-94b4-02f8d604d575.jpg)

... and thus is shown multiple times in participant selection
![2016-11-03_calendar-names_but_no_mail-adress_shown_for_participants](https://cloud.githubusercontent.com/assets/21206978/19978091/10248ade-a1f6-11e6-883a-d8333a2b017e.jpg)

### Expected behaviour
participant preferred contact should/could be identified by showing the corresponding e-mail adress via tooltip at mouseover

### Actual behaviour
name is shown again via tooltip at mouseover (makes no sense ;-)

### Server configuration
**Calendar version:** (see the apps page)
1.4.0

**Comment by tcitworld** [comment]
Will be fixed by https://github.com/nextcloud/calendar/pull/108

**Comment by nextgen-networks** [comment]
@tcitworld: thanks for the hint! Glad to see its in focus already :-)

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/45
