### ISSUE TITLE
editing event times without punctuation

### ISSUE THREAD

**Issue by zian92** [nextcloud/calendar#1621]
**Is your feature request related to a problem? Please describe.**
When I plan or edit an event I want to specify the start and end time by typing only numbers, e.g. 1500 for 15:00.
**Describe the solution you'd like**
I would like to get my numbers parsed to a valid format that I don't need to worry about punctuation.

**Describe alternatives you've considered**

**Additional context**

**Comment by tcitworld** [comment]
Parsing dates when you don't know the format in advance is quite a hard thing to handle (UK has AM/PM for instance).
Also with upcoming version 2.0 this is delegated to a [vue component](https://nextcloud-vue-components.netlify.com/#/Components/DatetimePicker) we should transfer issue there.

**Comment by georgehrke** [comment]
Heavily related to #1144
