### ISSUE TITLE
Calendar  2.0.0 Beta 2

### ISSUE THREAD

**Issue by mikweb2017** [nextcloud/calendar#1633]
### Steps to reproduce
set new event

### Expected behaviour
event and was created

### Actual behaviour
was not created

## Server configuration detail

**Operating system:** Linux 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.27

**PHP version:** 

7.3.11
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, apcu, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, snmp, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache, xdebug

**Nextcloud version:** 17.0.1 RC1 - 17.0.1.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - calendar: 2.0.0-beta2
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.6
 - dashboardcharts: 0.1.2
 - dav: 1.13.0
 - event_update_notification: 1.0.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_external: 1.8.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - groupfolders: 5.0.4
 - issuetemplate: 0.5.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - onlyoffice: 3.0.2
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - spreed: 7.0.1
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - text: 1.1.1
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.2.0
 - workflow_script: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - admin_audit
 - encryption
 - richdocuments
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "ac-milan.mikweb.info",
        "www.ac-milan.mikweb.info"
    ],
    "objectstore": {
        "class": "\\OC\\Files\\ObjectStore\\S3",
        "arguments": {
            "bucket": "daniele",
            "autocreate": true,
            ",
            "hostname": "s3.hidrive.strato.com",
            "port": 443,
            "use_ssl": true,
            "region": "eu-central-1",
            "use_path_style": true
        }
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.1.0",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "3306",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "updater.release.channel": "beta",
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "calendar",
        "onlyoffice",
        "issuetemplate"
    ],
    "mail_smtpmode": "sendmail",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": 25,
    "mail_smtptimeout": 10,
    "mail_smtpsecure": "",
    "mail_smtpauth": false,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** S3

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

**Operating system:** windows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
\/JSResourceLocator.php","line":70,"function":"cacheAndAppendCombineJsonIfExist","class":"OC\\Template\\JSResourceLocator","type":"->","args":["\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud","core\/js\/merged-template-prepend.json"]},{"file":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/private\/Template\/ResourceLocator.php","line":78,"function":"doFind","class":"OC\\Template\\JSResourceLocator","type":"->","args":["js\/merged-template-prepend"]},{"file":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/private\/TemplateLayout.php","line":332,"function":"find","class":"OC\\Template\\ResourceLocator","type":"->","args":[["core\/js\/dist\/main","js\/merged-template-prepend","search\/js\/search","core\/l10n\/en","search\/l10n\/en","search\/js\/searchprovider","js\/files\/fileinfo","js\/files\/client"]]},{"file":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/private\/TemplateLayout.php","line":160,"function":"findJavascriptFiles","class":"OC\\TemplateLayout","type":"::","args":[["core\/js\/dist\/main","js\/merged-template-prepend","search\/js\/search","core\/l10n\/en","search\/l10n\/en","search\/js\/searchprovider","js\/files\/fileinfo","js\/files\/client"]]},{"file":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/private\/legacy\/template.php","line":183,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["guest",""]},{"file":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/private\/Template\/Base.php","line":131,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/private\/legacy\/template.php","line":273,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/base.php","line":676,"function":"printGuestPage","class":"OC_Template","type":"::","args":["","error",{"errors":[{"error":"Your data directory is invalid","hint":"Ensure there is a file called \".ocdata\" in the root of the data directory."}]}]},{"file":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/base.php","line":1056,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/ocs\/v1.php","line":33,"args":["\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/base.php"],"function":"require_once"},{"file":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/ocs\/v2.php","line":24,"args":["\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/ocs\/v1.php"],"function":"require_once"}],"File":"\/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/private\/Files\/ObjectStore\/S3ConnectionTrait.php","Line":123,"CustomMessage":"Could not create object for appdata_ocpfpgbqlsqb\/js\/core\/merged-template-prepend.js"},"userAgent":"Mozilla\/5.0 (compatible; Nextcloud Plesk Extension\/1.3.0; risto-rigoletto.de)","version":"16.0.4.1"}
{"reqId":"jV0lg3nVFzKdxXTAKA6y","level":3,"time":"2019-08-28T18:29:03+00:00","remoteAddr":"81.169.216.90","user":"--","app":"PHP","method":"GET","url":"\/nextcloud\/ocs\/v2.php\/cloud\/users\/admin?format=json","message":"OCP\\Files\\NotPermittedException: Could not create path at \/var\/www\/vhosts\/ac-milan.mikweb.info\/httpdocs\/nextcloud\/lib\/private\/Files\/Node\/Folder.php#185","userAgent":"Mozilla\/5.0 (compatible; Nextcloud Plesk Extension\/1.3.0; risto-rigoletto.de)","version":"16.0.4.1"}

```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:541
Initial settings: 
Object { appVersion: "2.0.0-beta2", firstRun: false, showWeekends: true, showWeekNumbers: true, skipPopover: true, timezone: "automatic" }
settings.js:85:2
[DEBUG] calendar: The calendar app is using version 2.2016j of the timezone database 
Object { app: "calendar", uid: "authenticated:admin" }
ConsoleLogger.js:44:10
[DEBUG] calendar: Current user principal is /nextcloud/remote.php/dav/principals/users/admin/ 
Object { app: "calendar", uid: "authenticated:admin" }
ConsoleLogger.js:44:10
TypeError: "t.$store.dispatch(...).then(...).catch(...).finally is not a function"
    beforeRouteEnter EditorMixin.js:596
    e vue-router.esm.js:2310
    confirmTransition vue-router.esm.js:2300
    confirmTransition vue-router.esm.js:2163
    confirmTransition vue-router.esm.js:2162
    VueJS 2
    
    tt
    
    qe
vue.runtime.esm.js:1888:4
    VueJS 5
    
    He
    
    Ue
    
    Ge
    
    tt
    
    qe
</details>

![calendar](https://user-images.githubusercontent.com/30271757/68206913-2627d000-ffce-11e9-8312-097458d458ba.PNG)

**Comment by georgehrke** [comment]
Can't reproduce with Firefox 71.

finally should be supported by Firefox since version 58
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

**Comment by georgehrke** [comment]
@tcitworld Can you reproduce this?

**Comment by georgehrke** [comment]
@mikweb2017 How did you install the beta?

**Comment by georgehrke** [comment]
Error is thrown here https://github.com/nextcloud/calendar/blob/v2.0.0-beta2/src/mixins/EditorMixin.js#L596

Although i do not see why.

**Comment by georgehrke** [comment]
I guess this is similar to this one: https://github.com/vuejs/vue-cli/issues/2012#issuecomment-409472321

We have to change from babel polyfill to core.js anyway. Let me look into that right away

**Comment by raimund-schluessler** [comment]
When you are already on it, you could also consider to use async/await instead of .then().catch().

**Comment by georgehrke** [comment]
Yes, but at that time, i wasn't sure whether we can hand over an async function to next (vue-router). need to check that first.

**Comment by mikweb2017** [comment]
> 
> 
> @mikweb2017 How did you install the beta?

downloaded directly from Github and uploaded via FTP to my server.
With Firefox 70.0.01 it works very well
