### ISSUE TITLE
Support US date format MM/DD/YYYY

### ISSUE THREAD

**Issue by tflidd** [nextcloud/calendar#165]
For the date picker, is it possible to support the US format as well?

Problem was brought up in the forum: https://help.nextcloud.com/t/regional-datetime-settings-for-the-datetime-picker/4272

**Comment by georgehrke** [comment]
It already is ...
<img width="527" alt="calendar - nextcloud chromium today at 10 27 33 pm" src="https://cloud.githubusercontent.com/assets/1250540/20033694/159aabbc-a3a7-11e6-9606-1ec8ae0bbe0c.png">
