### ISSUE TITLE
Shared calendar entry to crowded in the navigation

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/calendar#1655]
I guess the "Shared" text could just be omitted: 

![image](https://user-images.githubusercontent.com/3404133/68550903-a358a800-0407-11ea-8f63-5d19c92ad6b6.png)

cc @nextcloud/designers

**Comment by ma12-co** [comment]
Another option we have would be switching to the `AppContentListItem` component that we'll be using in talk, contacts and mail. That way we'd have double the height to organize all those elements.

![Screenshot_20191111_125356](https://user-images.githubusercontent.com/26852655/68585370-5b2a9b80-0482-11ea-8bbe-63af4695f6eb.png)

**Comment by georgehrke** [comment]
@juliushaertl The item is in the AppNavigation, not AppContentList :)

**Comment by georgehrke** [comment]
I'm fine removing it.
We already show the shared state with the opacity.

The idea was to have it consistently with Files, where you also have that label. But in the file-list there is obviously much more space, compared to AppNavigation.

**Comment by skjnldsv** [comment]
> @ma12-co The item is in the AppNavigation, not AppContentList :)

Yes, but Marco built a standard component that works in both locations (as same design and layout for mail/contacts/talk) :+1:

**Comment by jancborchardt** [comment]
We do have the 2-row component of course, but why should we use it for the Calendar here? :) It's for different use-cases where much more info is displayed.

If you look at Apple Calendar, Google Calendar etc, they have a very similar layout for the list as we have currently.

We shouldn't use components for the sake of using components. The components follow what makes sense design-wise.

In this case, removing the "Shared" text as @juliushaertl mentioned is already enough. We could also additionally see to combine the link icon and the avatar, but that's something separate.
