### ISSUE TITLE
Deleting recurring events (only one of them)

### ISSUE THREAD

**Issue by YXWVECWUHKAVHWQJRGLHKLHRJDNPQH** [nextcloud/calendar#1659]
Hi. I use the agenda Nextcloud on MacBook computer with Firefox. I meet a
bug on the deleting of recurring events. Indeed, when I delete a recurring event, all occurrences are deleted. I would like, like on the phone (iphone with standard calendar), to have the possibility to delete a single event of the occurrence
Thanks,
J.

**Comment by tcitworld** [comment]
Available in upcoming version 2.0. See #7
