### ISSUE TITLE
Fonts are too small

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/calendar#166]
![picture1](https://cloud.githubusercontent.com/assets/19711361/20040484/ea2375a6-a458-11e6-9483-57807bcbcb08.PNG)

A client just told me about an interesting behavior of the calendar on bigger screens 😁 If you look at this screenshot - I think you will agree that the whole "date, hour and day" stuff is not readable for everybody who hasn't eyes of an 😼

cc @nextcloud/accessibility @nextcloud/designers

**Comment by jancborchardt** [comment]
Yeah, I’m thinking the fonts-size of these elements should never be smaller than the other normal text. We can achieve less focus by using opacity: .5; for example.

What do you think @nextcloud/designers?

**Comment by eppfel** [comment]
Responsive properties would be the nicest solution, but I think @georgehrke working hard to improve things like that, so no rush.
:+1: For minimum font-size and opacity (although it shouldn't be a fixed value, but a relative one)
We should add this to the styleguide.

**Comment by georgehrke** [comment]
> Responsive properties would be the nicest solution, but I think @georgehrke working hard to improve things like that, so no rush.

I am? 🙈

**Comment by MariusBluem** [comment]
You should 😈😜 @georgehrke

**Comment by eppfel** [comment]
> ... things like that ...

@georgehrke 😉

**Comment by georgehrke** [comment]
@nextcloud/designers Anyone of you available for helping here? :)

**Comment by danieldude15** [comment]
I think font size should be proportional to event size on calendar.
Its really small for some events that cover most of the day for example.
