### ISSUE TITLE
Disable labels if the labels app is disabled

### ISSUE THREAD

**Issue by szaimen** [nextcloud/calendar#1690]
**Is your feature request related to a problem? Please describe.**
I actually don't know if it is a bug or a feature but I think if the labels app is disabled, the calendar app 2.0 shouldn't show labels as well.

**Describe the solution you'd like**
Please disable labels in the calendar app if the labels app is disabled.

**Describe alternatives you've considered**
Maybe you could handle it independently from the labels app, but then a setting to show or hide labels in calendar should be added.

**Additional context**
I haven't found an issue with this topic, so I created this one.

Btw: really nice update!

**Comment by georgehrke** [comment]
> I actually don't know if it is a bug or a feature but I think if the labels app is disabled, the calendar app 2.0 shouldn't show labels as well.

This is the intended behaviour, because the labels are not connected to the labels in the server.

> Maybe you could handle it independently from the labels app, but then a setting to show or hide labels in calendar should be added.

I really really don't see a need to disable it. Why would you want to disable it?

**Comment by szaimen** [comment]
The idea was, that if you don't use labels in the calendar app at all, they don't get shown.
But the current behavior makes sense since the labels aren't connected to the labels in the server.
So I going to close this issue.
