### ISSUE TITLE
Mark&Copy from read-only calender not possible with FF, only with IE11

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/calendar#1691]
### Steps to reproduce
1. Open a read-only calender from other user with IE11 and FF(70)

### Expected behaviour
You can Mark&Copy WITH BOTH Browser the Information from read-only calender

### Actual behaviour
Mark&paste only possible with IE11, NOT possible with FF

### Calendar app
Calender App 1.7.1
Nextcloud 17.0.1
Server Debian 10

See Screenshot below.

Could someone please make FF run for Mark&Copy

BTW: Reading information in FF (light-grey on white) is difficult.

Thanks.

![nextcloud ie ff calender mark+copy](https://user-images.githubusercontent.com/47995430/69773860-6117c080-1194-11ea-8846-a418cf3977a7.png)

**Comment by georgehrke** [comment]
Dup of https://github.com/nextcloud/calendar/issues/555
