### ISSUE TITLE
"Today/Heute" Button does not jump to actual day after midnight

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/calendar#1692]
Hello,

the "Today/Heute" Button do not jump to actual day after midnight.

E.g:
1st October: Open Calender at 22:00h - Calender shows 1st October. Ok.
Wait 4 hours until 2nd October 02:00h
Press "Today/Heute" Button. - Nothing happens. Calender still shos 1st October.

Expected: Jump to 2nd October

This also happens when you wake up your computer in the morning after sleep mode over night.

Could someone fix this please?
Thanks.

**Comment by georgehrke** [comment]
@pm-pm Can you please fill the entire issue template?
If you don't even tell us what version of Nextcloud / the calendar app you use, we can't help you 😉

**Comment by pm-pm** [comment]
ok, of course
Nextcloud 17.0.1 on Debian 10
Calender 1.7.1 (And calenders before)

**Comment by georgehrke** [comment]
This was actually fixed along with https://github.com/nextcloud/calendar/issues/678 in an earlier beta of Calendar 2.

**Comment by pm-pm** [comment]
Earlier beta of Calendar 2 ???
I don´t have Calendar 2 and don´t know what it is.

For me (and my/our Software) it is not solved.
Could you please answer when it will be solved IN THIS software? 

Within NC 17.0.?
or
Within NC 18?
or 
In 4 Weeks?
or 
Never?

*It is ok, if you will never fix it, but please give us an answer i can work with*

**Comment by georgehrke** [comment]
> I don´t have Calendar 2 and don´t know what it is.

Version 2.0 of this calendar app. See https://github.com/nextcloud/calendar/releases and https://github.com/nextcloud/calendar/milestones
