### ISSUE TITLE
Server side scheduling // configure e-mail for calendar

### ISSUE THREAD

**Issue by m707** [nextcloud/calendar#170]
Just switched from OC to NC in the hope it could fix a problem I am fighting with since this summer. First reported in mozillas bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1297009 who told me that it's the problem of the dav server, that has server side scheduling enabled. Reported it in the forum https://help.nextcloud.com/t/stopping-server-side-scheduling/4893 who asked to me ask for a feature request here.

### Steps to reproduce
I use NC 10 on debian jessie (distros apache/mysql etc). I configure 2 calendars private/work. Access the calendars using thunderbirds lightning, where you configure a specific e-mail address that should be used as "From" in invitaions me@private/me@work. 
Send invitations

### Expected behaviour
The invitaions should be send using the configured from address in lighting.
Moreover, I would expect a configure option which e-mail address to use for a specific calendar in the oc/nc calendar app in general.

### Actual behaviour
The invitaions are send using the admin e-mail address configured in NC 10 (!= me@private != me@work)

### Server configuration
Debian jessie, all distribution packages (apache, mysql, php). Switched yesterday form oc9.1 ot nc 10,  calendar 1.4.0.

```
failed:
No errors have been found.

**Comment by georgehrke** [comment]
> Access the calendars using thunderbirds lightning, where you configure a specific e-mail address that should be used as "From" in invitaions me@private/me@work.

I think these E-mail addresses are only used in Lightning and never send to the Nextcloud server. I'll try and also talk to the Lightning guys.

> Moreover, I would expect a configure option which e-mail address to use for a specific calendar in the oc/nc calendar app in general.

@jancborchardt What do you think about making it possible to enter one e-mail address per calendar.

**Comment by m707** [comment]
> I think these E-mail addresses are only used in Lightning and never send to the Nextcloud server. I'll try and also talk to the Lightning guys.

1. THX.

Yes. Before our summer break at work (incl. OC/lightning/TB update) lighting was sending these invitaions using TB. You could see the messages in the SEND folder of corresponding TB account - no O/NC server involved at all.
OTOH an option to configure an e-mail address to be used within NC would definately be the successor .... this way it should work as expected from other clients, too.

**Comment by cstackpole** [comment]
Greetings,
I think my problem might be related. I originally reported it on the [nextcloud forum](https://help.nextcloud.com/t/calendar-issues-since-upgrade-to-11/6439/2) but got no response there.

The short version, after updating from 10.0.2 to 11 I can no longer send calendar invites. When I create them, nothing happens. It used to send them out. Any help would be appreciated.
Thanks!

**Comment by georgehrke** [comment]
@cstackpole please report your issue in https://github.com/nextcloud/server

**Comment by biva** [comment]
It is apparently related to https://github.com/nextcloud/server/issues/2149

**Comment by kosli** [comment]
@m707 As I wanted to have back the old behaviour and use TB/lightning for sending out the mails, I commented out the Sabre IMipPlugin in the NC code, so now TB has back the control.

**Comment by biva** [comment]
@kosli Good news!
Could you give us more details on how to do that? I'm not an expert, but I'd really need your solution...
Thanks in advance!

**Comment by kosli** [comment]
@biva in the end i had only to disable the plugins in apps/dav/lib/Server.php
-> Disable the Schedule (when enabled, it disables the invitation functionality in lightning) and IMip (sends the mail) Plugins. 

Line 118:
    // calendar plugins
    $this->server->addPlugin(new \OCA\DAV\CalDAV\Plugin());
    $this->server->addPlugin(new \Sabre\CalDAV\ICSExportPlugin());
    // $this->server->addPlugin(new \OCA\DAV\CalDAV\Schedule\Plugin());  // disabled
    // $this->server->addPlugin(new IMipPlugin($mailer, $logger)); // disabled

**Comment by georgehrke** [comment]
Closing in favor of https://github.com/nextcloud/server/issues/2800
