### ISSUE TITLE
Share calendar permission – show only busy

### ISSUE THREAD

**Issue by andre5tz** [nextcloud/calendar#171]
I have a feature request: **share calendar permission with „show only busy“** for all events.

For sharing calendars I see two ways, 
- show all events with its content (standard)
- "can edit" all events

As far as I know there is the option "when shared show only busy" only for events.
I've searched for this option and looking for issues but could not find anything about it.

It would be glad if this could be added.

**Comment by georgehrke** [comment]
We won't implement this. Instead we will implement Free/Busy support
https://github.com/nextcloud/calendar/issues/39

This will allow other users to see when you are free while scheduling events

**Comment by phlegx** [comment]
Free/Busy support is important. But what if I want to really share my calendar to other users but I want to only show that I'm busy.

Example: Share my private calendar to my company. The company can only see that I'm busy and not what exactly I do.

**Comment by AldarisPale** [comment]
Although this ticket is closed I'm having the very same issue discussed here at hand.
My use case:
1. I run my personal calendar on Nextcloud.
2. The company I work for runs its calendar on Google Suite (think google calendar)
3. I'm a bit paranoid person - I don't want Google to know what I'm up to in my personal calendar.
4. I do want to see in Google Calendar that I'm busy with something though. If that's the case I will open up my Nextcloud instance and check what my plans are.

Currently, it seems, this is impossible. Am I correct?
