### ISSUE TITLE
Sync and alerts

### ISSUE THREAD

**Issue by guibarbas** [nextcloud/calendar#1716]
Hello good afternoon
I would like to answer two questions.

1 - How can I sync my calendars with Google Calendars?
I've already set up inside Google Calendars and inside Nextcloud Calendar (Google appointments don't show up in Nextcloud and Nextcloud shows don't show up in Google)
[https://prnt.sc/q9fti6](url)

2 - When I select the email alert, this message appears (Email reminders have not yet been implemented on the CalDAV server, so none will be sent.)
How can I adjust?
[https://prnt.sc/q9ft1v](url)

And also the alert via Popup does not work.

And finally, you refer me a good application to receive and view this calendar by phone?
I have an Android

Many thanks friends.
And sorry if this question is duplicated with another, I checked the cases here and found no similar ones.

**Comment by georgehrke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
