### ISSUE TITLE
Calendar data entry 

### ISSUE THREAD

**Issue by kalimuthu123** [nextcloud/calendar#1718]
hi @nextcloud  i am very much interested in those feature level based application s which are to be possible of data entry on thie calendar

**Comment by georgehrke** [comment]
I'm not quite sure i understand what you are requesting here.

Can you please use the [feature request template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/feature_request.md) (It's there for a reason, not just for fun 😉) and describe a problem you are facing and propose a way to fix it?

**Comment by georgehrke** [comment]
And please refrain from using (at)nextcloud, as it's mentioning every single person who is part of this organisation. Thx.

**Comment by kalimuthu123** [comment]
i  am need of a new feature of the data entry in particular dates and convert into excel as export option
thanks for your advices

![](https://github.githubassets.com/images/icons/emoji/unicode/1f609.png)

**Comment by georgehrke** [comment]
You have still not described what problem you are trying to solve ...

I honestly don't see a need to implement an Excel export feature. I'm pretty sure there are already plenty of tools out there that convert ICS to Excel (or at least CSV).

Can you please raise your question in our forum: https://help.nextcloud.com/c/apps/calendar
There might already be some threads about ICS to CSV.
