### ISSUE TITLE
random fuzzy UI elements

### ISSUE THREAD

**Issue by pbartyik** [nextcloud/calendar#1734]
UI elemends displayed seemingly randomly when switching between windowed and fullscreen mode.

Sometimes element displays clean when fullscreen and not when windowed, sometimes displays clean when windowed but not when fullscreen. I was so far unable to determine proper steps to reproduce.

So far I have seen only once that both states are displayed correctly in Qutebrowser.

When testing in firefox the issue is not present.

### Expected behaviour
UI displays correctly

### Actual behaviour
Fuzzy:
![screenshot_2019-12-19-071329](https://user-images.githubusercontent.com/39059618/71149667-9497b900-222f-11ea-9e72-96c3cee30445.png)

Nice and clean:
![screenshot_2019-12-19-071254](https://user-images.githubusercontent.com/39059618/71149635-8053bc00-222f-11ea-90d0-73a755f753e2.png)

### Calendar app
**Calendar app version:** 2.0.0-beta3

**CalDAV-clients used:** None, viewing in Qutebrowser

### Client configuration
**Browser:** qutebrowser v1.8.3
Backend: QtWebEngine (Chromium 73.0.3683.105)

**Operating system:** Arch linux, fully upgraded, kernel held back at 5.1.13

### Server configuration

**Operating system**: Ubuntu 18.04 LTS

**Web server:** nginx/1.17.5

**Database:** mysql

**PHP version:** 7.3.13-1+ubuntu18.04.1+deb.sury.org+1

**Nextcloud Version:** (see admin page, e.g. 17.0.2)

**Updated from an older installed version or fresh install:** updated from older manually

**List of activated apps:** if this is really needed I'll update the issue

**Nextcloud configuration:** if this is really needed I'll update the issue

#### Browser log
```
JQMIGRATE: Migrate is installed, version 1.4.1
main.js?v=db35f732-7:1095 oc_config is deprecated: use OC.config instead
He @ main.js?v=db35f732-7:1095
calendar.js?v=db35f732-7:2 Proxying an event bus of version 0.2.1 with 0.2.0
t @ calendar.js?v=db35f732-7:2
main.js?v=db35f732-7:1095 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
He @ main.js?v=db35f732-7:1095
calendar.js?v=db35f732-7:2 Use of eventRender as an event is deprecated. Please convert to a prop.
(anonymous) @ calendar.js?v=db35f732-7:2
4main.js?v=db35f732-7:1095 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
He @ main.js?v=db35f732-7:1095
DevTools failed to parse SourceMap: https://host/core/js/dist/main.js.map
DevTools failed to parse SourceMap: https://host/apps/calendar/js/chunks/calendar.16.881ada0e23fa51cb0736.js.map
DevTools failed to parse SourceMap: https://host/core/js/dist/share_backend.js.map
DevTools failed to parse SourceMap: https://host/apps/notifications/js/notifications.js.map
DevTools failed to parse SourceMap: https://host/apps/calendar/js/chunks/calendar.93.8392904d3c215292276a.js.map
DevTools failed to parse SourceMap: https://host/apps/calendar/js/calendar.js.map
DevTools failed to parse SourceMap: https://host/apps/files_videoplayer/js/main.js.map
```

**Comment by tcitworld** [comment]
Unfortunately [we don't support](https://github.com/nextcloud/calendar#earth_africa-supported-browsers) qutebrowser.
This seems to be a specific issue with browser rendering, so maybe try to disable GPU acceleration: https://github.com/qutebrowser/qutebrowser/issues/2671#issuecomment-343697516
