### ISSUE TITLE
Appointments do not show minutes when zero

### ISSUE THREAD

**Issue by sciurius** [nextcloud/calendar#1736]
### Steps to reproduce
1. Open the Calendar
2. Make an appointment starting at 08:20
3. Add an appointment starting at 10:00

### Expected behaviour
Displayed times should be "08:20" and "10:00".

### Actual behaviour
Displayed times are "08:20" and "10".

![scrot20191219145802](https://user-images.githubusercontent.com/1118804/71179453-7a31ff80-2270-11ea-9a0f-55e99e63c7c9.png)

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1) 2.0.0 beta 3

### Client configuration
**Browser:** (e.g. Firefox 48) Firefox 70.0

**Operating system:** (e.g. Arch Linux) Fedora 29

### Server configuration

**Operating system**: (e.g. Debian 8) DSM 6.2

**Web server:** (e.g. Apache, Nginx,...) Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL) MariaDB

**PHP version:** (e.g. 7.0.3) 7.3

**Nextcloud Version:** (see admin page, e.g. 17.0.2) 18.0.0 Beta 3

**Updated from an older installed version or fresh install:** Updated

**List of activated apps:** N/A

**Comment by georgehrke** [comment]
cc @nextcloud/designers @tcitworld 

I have to say that i prefer the short version, because it gives more space to the title.

**Comment by raimund-schluessler** [comment]
To me it also looks a bit off with the short version.

**Comment by georgehrke** [comment]
Ok, let's go for `10:00`

**Comment by georgehrke** [comment]
TIL: FullCalendar 4 is using `Intl.DateTimeFormat`

**Comment by georgehrke** [comment]
I'm currently unable to fix this due to what i believe to be an upstream issue: https://github.com/fullcalendar/fullcalendar/issues/5213

Postponing this issue to 2.0.1

**Comment by georgehrke** [comment]
Upstream is considering it a feature request, not a bug. In that case we will have to create a formattingPlugin and extend https://github.com/fullcalendar/fullcalendar/blob/44c16bb687c911318306f1c1d0e05bfb186cc9a7/packages/core/src/datelib/formatting-native.ts to implement it ourselves.

**Comment by ccoenen** [comment]
In germany this looks like this:

![grafik](https://user-images.githubusercontent.com/124909/72857328-9b499e00-3cbd-11ea-92e9-d1805b87fa76.png)

These formats should all be the same consistently to be able to quickly skim this list.

**Comment by miaulalala** [comment]
can't reproduce
