### ISSUE TITLE
Calendar is not synced in full

### ISSUE THREAD

**Issue by kallegit1950** [nextcloud/calendar#1737]
I sync my nextcloud calendar with Android (davdroid) and with Kontact (Linux KDE). In both cases only the last months are synced and not the full calendar. Since the issue occurs for two completely setups I assume that it is an issue with nextcloud calendar and not with the calendars receiving data from nextcloud. The nextcloud calendar shows in the browser all entries so they exist.

**Comment by tcitworld** [comment]
I don't know about KOrganiser, but DAVx5 only syncs the last 90 days by default, that's a config options in the account settings.

**Comment by georgehrke** [comment]
We are not aware of any issue with non-syncing events. I strongly agree with @tcitworld's suspicion here.
