### ISSUE TITLE
Wed translated as Hochzeit

### ISSUE THREAD

**Issue by bjoern-tantau** [nextcloud/calendar#1748]
I've only got a screenshot, couldn't reproduce it myself, but it looks like in the calendar the English day abbreviation "Sun" has been translated in German to "Sonne" (should be "So.") and "Wed" has been translated to "Hochzeit" (should be "Mi.").

![IMG-20191223-WA0000](https://user-images.githubusercontent.com/8307357/71351323-b072c600-2573-11ea-85bc-b9a9d61aa467.jpg)

**Comment by tcitworld** [comment]
Please provide at least server, app and browser version.

**Comment by georgehrke** [comment]
Closing, since we didn't receive any feedback and even the original reporter said:

> couldn't reproduce it myself
