### ISSUE TITLE
Easy copy event -- enhancement

### ISSUE THREAD

**Issue by MellowVoidUser** [nextcloud/calendar#1749]
Many time I have to copy an event. Until now I use Thunderbird lightning because of this, but if calendar would add a easy way to copy (and repeat copy) a event that would be awesome!

**Comment by tcitworld** [comment]
Copying events is duplicate from… #113 

Repeat copy is probably not really in the scope of this app, right @georgehrke ?

**Comment by georgehrke** [comment]
Duplicate of #113

**Comment by georgehrke** [comment]
> Repeat copy is probably not really in the scope of this app, right @georgehrke ?

I was planning to copy the RRULE, but not RDATE and EXDATE, in case that's what @MellowVoidUser refers to.
