### ISSUE TITLE
Cannot enter minutes manually off-slot

### ISSUE THREAD

**Issue by ToeiRei** [nextcloud/calendar#1756]
### Steps to reproduce
1. Open Calendar
2. Enter new Event - set begin to i.e. 10:15 (slots do not offer 15 min)
3. Select end

### Expected behaviour
Begin time should stay at 10:15

### Actual behaviour
As you leave the start time field, it gets reset to something else

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.0-beta3

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
none, webclient only

### Client configuration
**Browser:** (e.g. Firefox 48)
Google Chrome 79.0.3945.88

**Operating system:** (e.g. Arch Linux)
Gentoo Linux, Windows 10

### Server configuration

**Operating system**: (e.g. Debian 8)
Gentoo Linux

**Web server:** (e.g. Apache, Nginx,...)
Nginx

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0.3)
PHP 7.3.13 (cli) (built: Dec 29 2019 17:55:19) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
Nextcloud 18.0.0 RC1

**Updated from an older installed version or fresh install:**
Updated from an older install

**List of activated apps:**
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.4.0
  - calendar: 2.0.0-beta3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - impersonate: 1.4.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.10.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - piwik: 0.5.3
  - previewgenerator: 2.2.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 1.2.3
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_nextcloud_notification: 2.2.0
  - twofactor_totp: 4.1.1
  - unsplash: 1.1.4
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

**Comment by georgehrke** [comment]
Do you use Nextcloud in U.S. English or did you pick another locale / language?

**Comment by ToeiRei** [comment]
Locale: German (Austria)
