### ISSUE TITLE
Change the default user setting of skipPopover via global config (occ) for all users

### ISSUE THREAD

**Issue by Popyllol** [nextcloud/calendar#1787]
**Is your feature request related to a problem? Please describe.**
The problem is that we have a lot of people which are not expirienced enough in mouse usage to make a calendar entry with the popover editor (alias simple event editor), so they often take time to create an event and then click a little bit beside the window and get frustrated when they lose their entry completely.
To set the default skipPopover value for all users would reduce our need of service for this people.

**Describe the solution you'd like**
What I would love to have is the possibility to make a call like
`occ config:app:set calendar skipPopover --value 'yes'`
to set the default value.

**Describe alternatives you've considered**

**Additional context**

**Comment by georgehrke** [comment]
@Popyllol Feel free to send a pull-request for this.

https://github.com/nextcloud/calendar/blob/master/lib/Controller/ViewController.php#L88

**Comment by Popyllol** [comment]
> @Popyllol Feel free to send a pull-request for this.
> 
> https://github.com/nextcloud/calendar/blob/master/lib/Controller/ViewController.php#L88

Thank you, but this will went away when I upgrade. So... make it a config option would be great.

**Comment by Popyllol** [comment]
Perfect! So it will be the default for further versions? Right?

**Comment by georgehrke** [comment]
> So it will be the default for further versions?

If you or someone else implements it :)
