### ISSUE TITLE
Today in agendaWeek and agendaDay

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#1804]
We don't use the default full-calendar style for styling today, because the yellow color caused too many issues for too many users on different settings of screens.

For month we just put a circle around the day, which works just fine:
![0C286F05-3B47-4197-A621-89B451648FDD](https://user-images.githubusercontent.com/1250540/72338410-b49e8900-36c4-11ea-93c8-0be69885eb76.png)

In agendaWeek, we currently have the blue box with text:
![CE69CB65-466B-4869-A84B-52C30D5B32CF](https://user-images.githubusercontent.com/1250540/72338565-0b0bc780-36c5-11ea-9fb8-c7ea305fcf9d.png)

That used to look somewhat fine, but it's a problem since we replaced the header bar with a gradient.

One option would be to remove the background and just have a bold font:
![0F3BEE52-55A2-456B-BC05-6E4963844C56](https://user-images.githubusercontent.com/1250540/72338696-51612680-36c5-11ea-8229-020a6a8d11ab.png)
Please note that in addition to the bold font, today is always including the now indicator.

@nextcloud/designers What's your opinion on this?

**Comment by jancborchardt** [comment]
How about this:
![today indicator](https://user-images.githubusercontent.com/925062/72344287-2977c000-36d1-11ea-9abe-efe1b2ecc6ba.png)


It’s on the a inside the th:
```
background-color: var(--color-primary);
border-radius: var(--border-radius-pill);
padding: 2px 6px;
color: var(--color-primary-text);
```

Same can be used for the day view, as discussed @georgehrke :)

**Comment by georgehrke** [comment]
@jancborchardt Pull-request in https://github.com/nextcloud/calendar/pull/1805
