### ISSUE TITLE
Update links to documentation

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#1814]
https://docs.nextcloud.com/server/latest/user_manual/pim/calendar.html is fairly outdated

**Comment by tcitworld** [comment]
I had started https://github.com/nextcloud/documentation/commit/c078374ac001ca8d0ff7e56f32ba90c9c1962f8f a while ago.

**Comment by georgehrke** [comment]
Important things to add: 
- Email addresses must be unique for scheduling

**Comment by fds2610** [comment]
Dear all,
where can I find actual documentation about how to setup email adresses correctly for using nextcloud/calendar/caldav for multiple users ?
my invitations are being sent with the following "from:":
[Full Username] via Nextcloud <NCserver-email-address> like
Max Mustermann über Nextcloud <cloud@provider.net>
and replys automatically go back to the server-email which usualls shall process communication with internal users.
This leads to all replies to calendar-invitations are being sent to the admins...
Is this intended ?

**Comment by edent** [comment]
https://docs.nextcloud.com/server/latest/user_manual/pim/calendar.html is now broken. Shows as "File not found."

**Comment by tcitworld** [comment]
See https://docs.nextcloud.com/server/19/user_manual/pim/calendar.html in the meanwhile (you can adapt `19` to your version number).

**Comment by bernd-wechner** [comment]
That last link works but says:

```
There’s also an « embedding code » that provides an HTML iframe to embed your calendar into public pages.
```

Anyone care to explain where that `« embedding code »` can be found. I can't ...

I asked here too BTW:

https://help.nextcloud.com/t/where-can-i-get-the-calendar-embedding-code/91014

**Comment by tcitworld** [comment]
Replied on the forum.

**Comment by Cyrille37** [comment]
Hello

The page "official" page https://apps.nextcloud.com/apps/calendar, at bottom right in "resources", link to the broken link.

Cheers.

**Comment by edent** [comment]
This is still broken.

**Comment by tcitworld** [comment]
The links from https://docs.nextcloud.com work, and this is not related to the original topic.

**Comment by edent** [comment]
Where should I report the broken link on https://apps.nextcloud.com/apps/calendar?
Thanks.

**Comment by tcitworld** [comment]
It should be changed here https://github.com/nextcloud/calendar/blob/master/appinfo/info.xml#L24

`https://docs.nextcloud.com/server/latest/user_manual/en/pim/calendar.html` is the correct one.
