### ISSUE TITLE
Self added category difficult to remove

### ISSUE THREAD

**Issue by corvus-albus** [nextcloud/calendar#1819]
### Steps to reproduce
1. Add a new or edit an existing event and type a word in the category field, that is not part of the predefined set. The category will appear in the field.
2. If you reopen the event there is no possibility to remove this category. If you click at it, the predefined list will open. The new word is not added and you can't remove it by clicking at the word as you can do it with predefined categories.
3. Change the UI-language. The self added category will be removed. Predefined categories will be translated.

### Expected behaviour
Self added categories should appear on the list of categories for the choosen calendar. Then you should be able to remove them like the predefined categories. 
Those new categories should be kept while changing the language.

### Actual behaviour
Explained above.

### Calendar app
2.0.0 RC

### Client configuration
Firefox 72.0.1 (64-Bit)
Ubuntu Bionic

### Server configuration
**Operating system**: Ubuntu 18.04.3 LTS
**Web server:** Apache
**Nextcloud Version:** 17.0.1

**Comment by georgehrke** [comment]
> If you reopen the event there is no possibility to remove this category. If you click at it, the predefined list will open. The new word is not added and you can't remove it by clicking at the word as you can do it with predefined categories.

You can just use the delete button to remove the category, but I agree that the category should also be visible in the list so you can just unselect it.

> Change the UI-language. The self added category will be removed. Predefined categories will be translated.

I can't reproduce that when switching from english to german. Can you please try again and tell me what language you switched from and to?

**Comment by corvus-albus** [comment]
> You can just use the delete button to remove the category, but I agree that the category should also be visible in the list so you can just unselect it.

I searched for a "delete button", I can't see one. Do you mean the backspace key? In effect I realized, that you can delete the categories with the backspace key. The problem is: you don't see, which category you delete, because they are no longer displayed, when you click the edit-filed. 
Perhaps it is a good idea to leave the already choosen categories in the edit filed, than you can remove via backspace or enter a new one by typing at the free space on the right side.

> I can't reproduce that when switching from english to german. Can you please try again and tell me what language you switched from and to?

Sorry, I can't reproduce it as well. Perhaps it was too late and I forgot to update the event before switching the language. I will edit the title. Sorry for that.
