### ISSUE TITLE
Recurring Appointment - Changing a time doesnt work across Platforms

### ISSUE THREAD

**Issue by Elfearo** [nextcloud/calendar#1830]
Hi there,

i am currently setting up and testing a nextcloud platform for calendars mostly. When testing around i found out about a problem that might be because of nextcloud, or just the way calendar tools handle appointments:

Here´s the problem:

When making a recurring appointment its gets perfectly synced via all platforms (mac calendar, iphone, thunderbird). Deleting a single appointment or the whole group will work fine too. Thus changing the time of one single appointment makes the whole thing incomplete.

- When changing via mac everything works
- When changing via iphone everything works
- When changing via Thunderbird i can see the appointment get changed in the nextcloud and also in Thunderbird, though the Apple Devices dont realize the change.

Editing an already edited appointment via Apple will overwrite the change of Thunderbird and make the appointment synched on the state of the apple device again.

Any ideas why this might happen?

----

### Steps to reproduce
1. Set up nextcloud with latest calendar
2. Create a reccuring apppointment
3. Change the date of a single appointment within the reccuring one by either Apple Calendar (works for all tools then) or thinderbird calendar (apple calendar wont realize the change)
4. Check if the changes show up in other calendar tools

### Expected behaviour
All calendars should have the latest state

### Actual behaviour
Apple Calendar doesnt realize time changes in single parts of reccuring appointments, when changed via thunderbird calendar 

### Calendar app
2.0.0 / 1.7.2

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
Lightning / Iphone / MAC Calendar

**Operating system:** (e.g. Arch Linux)
MAC / Iphone

### Server configuration
Centos 7 / 8
Apache
Mariadb
PHP 7.0.2
17.0.2
Fresh installed

**List of activated apps:**
Calendar
Contacts

**Nextcloud configuration:**
Mostly default

**Comment by georgehrke** [comment]
So If I understand you correctly, this is not a bug report about the Nextcloud web calendar creating events that iOS / macOS or Thunderbird don't understand, but the problem is that iOS/macOS don't  understand the events created by Thunderbird?

**Comment by Elfearo** [comment]
Hello,

yes i am not quite sure where the problem occours. It might be thunderbird not making the events right, nextcloud not storing them right, or apple not refreshing them right. 

The deletion for example works fine. If i find time next week i will try to check with another calendar tool to maybe get a bit closer to where the problem is related.

**Comment by georgehrke** [comment]
In that case I would like to ask you to take your question to http://help.nextcloud.com/c/apps/calendar. Feel free to mention me over there, i have the same username as here. The bug tracker is only for things that we are sure about that they are bugs in our software, not general support requests.

I would be very interesting to see the actual events that you are syncing, the ics files.
Maybe there is a bug in thunderbird and its using some unsupported format.
