### ISSUE TITLE
V-Popover slowing down editor in Chromium-based browsers

### ISSUE THREAD

**Issue by szaimen** [nextcloud/calendar#1834]
There are a few performance problems with the new Nextcloud 17 release 2.0.0.

Very slow is especially:
- closing the main event editor (this is okay with firefox but very slow with chromium based browser)
- while having an event open in the main event editor, clicking on or creating another event (the simple editor is disabled)
- creating new events doesn't seem to be very fast as well (especially if the simple editor is enabled)  (this is okay with firefox but very slow with chromium based browser)
- deleting and saving events (maybe has to do with the slow closing?)  (this is okay with firefox but very slow with chromium based browser)

All options should react instantly without having to wait for it.
I think that's it for now. 

BTW: the simple editor seems to be not positioned next to the new event but always on the left which isn't how I would suspect it to work.

**Comment by szaimen** [comment]
@georgehrke I edited the issue. If you need more infos, please tell! 
Thanks!

**Comment by georgehrke** [comment]
Overall it should be much snappier and faster than Calendar 1.
I fear this particular issue is related to V-Popover. Will look into it.

**Comment by szaimen** [comment]
This is now much improved on NC20 with the altest calendar release.
