### ISSUE TITLE
Defining a default calendar

### ISSUE THREAD

**Issue by szaimen** [nextcloud/calendar#1835]
## Feature Request

As a Calendar user I have more than one calendar. When another users invites me to an event, it is not clear to which calendar the event is copied.

It would be really nice if I could define a default calendar for creating new events, since I am using most of the time a calendar, which is since the 2.0.0 release no longer on top. So as long as you cannot change the list order, I think this would be a nice addition. Thanks!

## Implementation

This option could be added to the settings&import section.

e.g. this is in Nextcloud Tasks already possible. Maybe you could copy some code from there?
![image](https://user-images.githubusercontent.com/42591237/72654844-a46efe00-3991-11ea-925b-bad86bac8246.png)

**Comment by j-ed** [comment]
Perhaps the selected calendar could also be used for creating events for which someone has received an invitation. By default such kind of events are currently always created in the default calendar named "personal" as described [here](https://github.com/nextcloud/server/issues/5040).

**Comment by trollepierre** [comment]
I am using 2 agendas: AgendaA and AgendaB.
When choosing AgendaB, I can create several events for AgendaB.
But at any time that my page is reloaded, I need to set AgendaB as "default" agenda for creating event.
Here is why, I would like to set a default agenda, which is not the first one, that I have imported.

**Comment by palegrand** [comment]
A default calendar could possibly solve the long-standing issue (in the 'server'-repo): Upon invitations, calendar "personal" is created although there is a valid calender #5040

**Comment by trollepierre** [comment]
any news about that?

**Comment by alexanderdd** [comment]
IMHO this is not an enhancement but a bug (actually severe, potentually leaking confidential infornation) see the report here https://github.com/nextcloud/calendar/issues/2323

**Comment by nickvergessen** [comment]
Just happened to me too. Picking the first one in alphabetic order is pretty meh.
Either "personal" is the default or the user should pick one, using the alphabetic first calendar (even when it's shared by someone else) is pretty meh

**Comment by jancborchardt** [comment]
What would be best design-wise:
- Remember which calendar was picked last for creating an event, in case you create a lot of events in another calendar in a row
- Put the "Personal" calendar always on top of the list (also in the dropdowns) so it is always quick to access.

**Comment by szaimen** [comment]
> * Put the "Personal" calendar always on top of the list (also in the dropdowns) so it is always quick to access.

But what if I have a different calendar that I want to use as default? (e.g. because I deleted the default personal calendar)

**Comment by nickvergessen** [comment]
This is not about solving the "being able to select a default" option. But it's a step to make life easier in the 99% case for now.

**Comment by szaimen** [comment]
I thought this issue was about being able to select a default calendar?

**Comment by nickvergessen** [comment]
Yes, and it can stay open if wished.

I meant that:
> Put the "Personal" calendar always on top of the list (also in the dropdowns) so it is always quick to access.

Would already solve the problem for most people and can therefor be done as a quick fix solving the issue for the first 99% until a "How to pick a default calendar" option that is being discussed/open since more than 1.5 years has been figured out.

**Comment by b3niup** [comment]
Hi, that's awesome that something is happening here :)
Having a lot of actively used calendars I'd much prefer "last used" one as a default for a temporary solution.

**Comment by jancborchardt** [comment]
@ChristophWurst as discussed, a simple selector as suggested by @szaimen above would be a good way to fix this.

**Comment by szaimen** [comment]
🎉🎉🎉🎉🎉

**Comment by jospoortvliet** [comment]
awesome!!!! This annoys me so often ;-)
