### ISSUE TITLE
Calendar-picker not visible

### ISSUE THREAD

**Issue by karan** [nextcloud/calendar#1837]
### Steps to reproduce
1. Install 2.0
2. Create 2 calendars
3. Try to create an event

### Expected behaviour
I should be able to choose which calendar the event belongs to

### Actual behaviour
I can't!

![image](https://user-images.githubusercontent.com/3261985/72659728-1ab33680-3979-11ea-9184-5784265848dd.png)

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.0

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
DAVx5, MacOS Calendar

### Client configuration
**Browser:** (e.g. Firefox 48)
Brave 1.0.1

**Operating system:** (e.g. Arch Linux)
MacOS

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
17.0.2

**Comment by georgehrke** [comment]
Works just fine for me.
Please provide a screenshot of the entire calendar and provide javascript logs as requested. Thx

**Comment by georgehrke** [comment]
Ah, I'm just seeing that you are using Brave. I will test that later, but please not that Brave is generally not considered a supported browser: https://github.com/nextcloud/calendar#earth_africa-supported-browsers

**Comment by karan** [comment]
Thanks for that. I can live with that (but if you do end up repro'ing, I have all my shields/adblocker disabled).

All I see in the js console is:

```
The escapeHTML library is deprecated! It will be removed in nextcloud 19.
```

No errors.

**Comment by karan** [comment]
This is not an issue - one of the two calendars I had is a shared Google calendar. So there's only one NC calendar.

**Comment by georgehrke** [comment]
Ah, ok!

Maybe we should rename "New subscription from link" to "New subscription from link (read-only)".
![40887B96-6D15-436B-89D0-291A3F03B90D](https://user-images.githubusercontent.com/1250540/73438558-8371ba00-434e-11ea-9198-ab122db0059c.png)
