### ISSUE TITLE
Add default alarms for ordinary calendars

### ISSUE THREAD

**Issue by enoch85** [nextcloud/calendar#184]
As we discussed [here](https://github.com/nextcloud/server/issues/1505#issuecomment-260682748) it would be nice to have the possibility to add default alarms to events in the ordinary calendar.

Something like this:
- None
- 9AM on day of birthday
- 1 day before (9AM)
- 2 days before (9AM)
- 1 week before (9AM)

@georgehrke 
> I don't think we will go for a dedicated input for each calendar.
But I can very well imagine adding a user-based option for all (non-birthday) calendars.
One for all day and one for timed events.

**Comment by georgehrke** [comment]
Closing in favour of https://github.com/nextcloud/calendar/issues/629
