### ISSUE TITLE
Calendar import very long

### ISSUE THREAD

**Issue by devcrafting** [nextcloud/calendar#1857]
**Is your feature request related to a problem? Please describe.**
About time to import, I imported a calendar with ~2000 events, it took some 15 minutes.

About progress, I saw by chance that clicking again on "Settings & import", I got a progress bar (and I also opened Developer Tools to see requests). Still I did not know if there was some errors. At the end, ([looking at code](https://github.com/nextcloud/calendar/blob/44a72d72e274428c4c0d49bcb9856e86dd64e2fb/src/components/AppNavigation/Settings/SettingsImportSection.vue#L200)), I expected some notification when it ends...but since it takes a lot of time, I perhaps missed the toast ? (I did not spend 15 min waiting for completion ^^)

**Describe the solution you'd like**
Upload the file on the server to import all events server-side instead of client side with lots of HTTP request. Client throttling fixed this [issue](https://github.com/nextcloud/calendar/issues/871), but server side would be probably faster (need to take care of the risk of timeout). Perhaps, batch imports (let's say 500 for example) would be good.  

For progress, it would be nice to have a NC notification resuming nb events failed/succeeded instead of a toast (diappear automatically) ?

**Describe alternatives you've considered**
None

**Additional context**
I am using Calendar 2.0.0

**Comment by georgehrke** [comment]
> About progress, I saw by chance that clicking again on "Settings & import", I got a progress bar

Yes, we should keep the settings area open. Let me open a separate ticket for that.

**Comment by georgehrke** [comment]
@devcrafting Can you generally say something about your server, load and network connection.
When testing this earlier, i easily managed to import between 30 and 40 thousand events in less than five minutes.

I'm not sure why it takes so long for you.

Generally saying uploading 2000 events is something you do very rarely, so it's not something i would prioritise at the moment.

The toast will indeed be hidden automatically after 30 seconds.
