### ISSUE TITLE
Keep settings open during import to show progress bar

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#1859]
Right now, clicking inside the import dialog causes a click outside event for the settings area and closes it automatically. Which results in the progress bar being hidden.

**Comment by georgehrke** [comment]
Requires https://github.com/nextcloud/nextcloud-vue/issues/834

**Comment by szaimen** [comment]
Hello, I just had a look at #2155, rebased it, fixed lint, tested it and it seems like it fixes the issue.

If you have docker installed locally, you can test this with:

```
docker run -it \
-e CALENDAR_BRANCH=bugfix/1859/keep_settings_open_during_import \
-p 127.0.0.1:8443:443 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```
