### ISSUE TITLE
Handling calendar invitations and responses using email

### ISSUE THREAD

**Issue by yanosz** [nextcloud/calendar#186]
Ref: https://help.nextcloud.com/t/handling-calendar-invitations-using-email/5168

From what I got, I can add participants to an event and they are invited by mail.
But: When I respond using the MUA, the response is sent to the authors private mailbox. Nextcloud doesn't get the status.

That's bad, since I need nextcloud to reflect the participant status of an event, if if no MUA updating the event using CalDav is present. This should happen without further processing at the site sending the invitation (Eg. logging in into nextcloud or acknowledging the response in nextcloud): In case of shared calendars, the participants status should be updated at once.

**Comment by tcitworld** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
