### ISSUE TITLE
Problem with birthday on Dec 31st

### ISSUE THREAD

**Issue by drupalwonder** [nextcloud/calendar#187]
Hi there,

First of all: Thanx a lot for doing such a great work :)

My problem: One of my contacts is born on December 31st (lets say Dolly is born on 1984-12-31), but the entry in the contacts birthday calendar is "Dolly (*1985)", so Dolly was made a year younger. Well that's charming for Dolly ... but it's a bug I suppose (and not a feature).

Nexcloud is running in version 10.

Has anybody an idea?

Greetz
Jürgen

**Comment by georgehrke** [comment]
The birthday calendar is generated in the nextcloud server and not in the calendar app.
Please reopen in https://github.com/nextcloud/server  and mention me
Thx :)
