### ISSUE TITLE
 Tab title not translated

### ISSUE THREAD

**Issue by nrgeen** [nextcloud/calendar#1871]
### Steps to reproduce
1. Open the calendar-app in monthly overview.

### Expected behaviour
In the German translation, the tab title of the month in the respective month should be in the same translation.

### Actual behaviour
In the German translation, the English translation of the month is in the tab title.
![Bildschirmfoto vom 2020-01-20 21-45-10](https://user-images.githubusercontent.com/7750335/72756800-a245b300-3bce-11ea-9521-8a9f5788a417.png)

### Calendar app
2.0.1

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 72.0.1

**Operating system:** (e.g. Arch Linux)
Fedora 31

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0.3)
7.3.13

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
18.0.0

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/blob/master/src/services/windowTitleService.js#L43
