### ISSUE TITLE
confirmation of attendace fails when there is a user with same email address as the creator of an event

### ISSUE THREAD

**Issue by walley** [nextcloud/calendar#1878]
### Steps to reproduce
1. have two user with same email address, be one of them
2. create new event, invite others
3. others clink on approve link in the email 

### Expected behaviour
invitation accepted.
user is presented with a message:
Your attendance was updated successfully.

### Actual behaviour
error message:
There was an error updating your attendance status.
Please contact the organizer directly.

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.1

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
none

### Client configuration
**Browser:** (e.g. Firefox 48)
firefox, chromium

**Operating system:** (e.g. Arch Linux)
windows and linux

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian buster

**Web server:** (e.g. Apache, Nginx,...)
apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
mariadb

**PHP version:** (e.g. 7.0.3)
PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
18rc2

**Updated from an older installed version or fresh install:**
updated

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```
nabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - apporder: 0.9.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.6
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_readmemd: 1.1.3
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - impersonate: 1.4.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.0.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_diaspora: 1.0.5
  - socialsharing_email: 1.0.6
  - spreed: 8.0.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 1.2.3
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - files_external
  - social

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.blah.elsewhere"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.9",
        "overwrite.cli.url": "http:\/\/nextcloud.hasici-ol.cz",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "log_type": "syslog",
        "loglevel": 0,
        "syslog_tag": "nextcloud",
        "defaultapp": "calendar",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "app_install_overwrite": [
            "maps",
            "social",
            "socialsharing_email",
            "socialsharing_diaspora",
            "circles",
            "files_markdown",
            "files_readmemd",
            "impersonate"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```
too big bcause of constant attacks, please be more specific.

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```
98000 lines since 19. 1.
228847 since the begining
must specify what exact lines are needed

#### Browser log
```
Insert your browser log here, this could for example include:
browser side works ok

**Comment by georgehrke** [comment]
E-Mail addresses need to be unique for scheduling to work.

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/17146

**Comment by walley** [comment]
that error message should be more descriptive:)

**Comment by lars-becker** [comment]
@georgehrke It would be really helpful if there would be a better error handling and/or a entry in the server log that produces a warning. But there was no indicator what was causing the problem. Therefore I almost opened a new issue, but luckily stumbled on this; took a look in the user database and could replicate it. 

We had the situation that most scheduling didn't work, which was because there were two info@ adresses: one for a general account of the secretary and the same mail entry for the admin account of the instance. I image that this might happen quite often.

**Comment by georgehrke** [comment]
@lars-becker See nextcloud/server#17146
