### ISSUE TITLE
No sharing of contact birthdays calendar while sharin an address book

### ISSUE THREAD

**Issue by drupalwonder** [nextcloud/calendar#188]
One more once: Is there an option to import the birthdays of the contacts in a shared address book into the birthday calendar?

The contact birthdays calendar works really fine with all contacts in my address book, but if I share my contacts with another nextcloud user he's getting all the contacs (including their birthdays), but the birthdays aren't shown in his contact birthdays calendar. Sharing my birthday calendar (based on my contacts) via abonnement doesn't work while the server's refusing to do so.

Any ideas? Thanks!

**Comment by georgehrke** [comment]
please reopen in core as well
