### ISSUE TITLE
Integrate navlink for month view

### ISSUE THREAD

**Issue by corvus-albus** [nextcloud/calendar#1880]
**Is your feature request related to a problem? Please describe.**
If you are in month view you can easy navigate to week or day view by the new integrated nav-links. That is really handy for getting an overview in month view and jump to specific days and create new events or have a closer look at some days/weeks. If you are at day or week level you can switch between those two also very easy. Only for switching back to month view, you have to take the nice dropdown menu, at the left side. If you look at a narrow display (smartphone) you have to make the left side visible first.

**Describe the solution you'd like**
It would be very nice to have a navlink to switch to month view integrated. I have modified a screen shot to demonstrate how it could look. (But I'm no web designer - it's only a for clarification). Clicking on  "M 01" or "M 1" shall lead you to the month view of the january.: 

German language:
![month_link](https://user-images.githubusercontent.com/26668681/72814030-acb28c00-3c64-11ea-93f8-fef7226b154c.png)

English: 
![month_link_en](https://user-images.githubusercontent.com/26668681/72814933-2eef8000-3c66-11ea-9497-317f3fa67d6c.png)

**Describe alternatives you've considered**
Sorry, no alternativ considered.

**Additional context**
screenshot above

Cheers 
corvus-albus

**Comment by georgehrke** [comment]
I'm not in favour of this idea.

`M1` is not a common term for January, while `W 4` (or even `KW` in german) is more common for week of the year. It's not self explanatory what `M1` does or stands for.

On top of that, as you explicitly mentioned devices with a narrow display: Putting two links right next to each other on a touch display will cause issues, because it makes it unnecessarily difficult to hit the right one.

**Comment by georgehrke** [comment]
@tcitworld What's your opinion here?

**Comment by tcitworld** [comment]
Yup, this can't do this exact proposition for the reason @georgehrke said. Depending on some locales abbreviation may be even longer (see below for French, which already has trouble with this).
![Screenshot_2020-01-21 Semaine 2 de 2020 - Agenda - Mon petit nuage](https://user-images.githubusercontent.com/2197836/72819701-ff447600-3c6d-11ea-870c-333483a54836.png)

We *could* have short month name on the next line, increasing the whole first line height, but is it worth it? Probably not.
