### ISSUE TITLE
Gantt viewer / planner of tasks and events?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/calendar#1881]
With better task and project integration it would be really nice if one could switch to a Gantt chart planner to develop a larger project plan.

There is a nice javascript frontend for that, which might be possible to add. Maybe as a separate but linked app like the Tasks app? See:
https://github.com/dangph2011/jQueryGantt

Gantt charts are widely used in enterprise environments, thus this would probably fit well to the new Hub focus.

Thanks for considering :)

**Comment by georgehrke** [comment]
I don't think this is something to be build directly into the calendar app.
Instead, you can just develop an app using the CalDAV interface to access the same data.

[c-dav library](https://github.com/nextcloud/cdav-library) and [calendar.js](https://github.com/georgehrke/calendar-js) make it fairly easy to access, read and modify the calendar-data.

I would suggest posting it in the [app-idea](https://help.nextcloud.com/c/feature/app-ideas) section of our forum.
