### ISSUE TITLE
reaction to an invitation: Notification 

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/calendar#1885]
I'm not sure, but maybe we want a email (outlook does it so) or a [server notification](https://github.com/nextcloud/notifications/) if a user reacts to an invitation.

**Comment by georgehrke** [comment]
We have email notifications already.

In app / notification is #144

**Comment by jakobroehrl** [comment]
@georgehrke 
There is no notification for the creator of the meeting, if one of the attendees accept/decline the meeting.

**Comment by georgehrke** [comment]
Those responses are part of the calendar-inbox and will be visible with #144

**Comment by georgehrke** [comment]
Let me rename #144 for clarity

**Comment by jakobroehrl** [comment]
Thanks! 👍
