### ISSUE TITLE
Working out should recognise "Gym" as event title.

### ISSUE THREAD

**Issue by rspencer01** [nextcloud/calendar#1888]
**Describe the solution you'd like**
Events titled "gym" to have illustration relating to working out.

**Additional context**
Requires a single line addition to
https://github.com/nextcloud/calendar/blob/85e9f76e570bb154071343245fc414d4b53f1e26/src/utils/illustration.js#L365
and possibly some localization.

**Comment by georgehrke** [comment]
@rspencer01 Would you mind just sending a pull-request since you already found the right line of code? :)

**Comment by rspencer01** [comment]
Can do. Will only get round to it later when I'm not at work, but thought I'd drop this here is in case some kind soul got to it faster.

On 23 January 2020 09:24:16 GMT, Georg Ehrke <notifications@github.com> wrote:
>@rspencer01 Would you mind just sending a pull-request since you already found the right line of code? :) 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/calendar/issues/1888#issuecomment-577596708
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SuperSandro2000** [comment]
Would this mark ``Gymnasium`` which is the German word for high school?

**Comment by rspencer01** [comment]
This is already a problem with English events such as _**Camp**aign for Better String Matching_ giving the camping image.  My suggestion would be to match space delineated words, which brings in trouble with multi-word matches and hyphens and the like and warrants a separate issue really.

**Comment by georgehrke** [comment]
> warrants a separate issue really

yes, we need a better matching. To only match for actual words only, not words containing other words. Something like `(?<![\w\d])abc(?![\w\d])`
