### ISSUE TITLE
montly-mode: scroll-bar instead of "more"

### ISSUE THREAD

**Issue by IABLinz** [nextcloud/calendar#1889]
Hi, I do have a question concerning the monthly-mode.

I would like to see all entries of every day, even if I have to scroll to see the whole month. In the old version it worked just like that and we appreciated that very much. Now only view appointments are shown each day and further appointments are summarized with „more“.
For my colleges it’s of great importance to see all appointments at one sight, in order to being able to plan and check appointments.

Is there a possibility to use the scroll-bar again? That would be awesome.

**Comment by georgehrke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
@IABLinz how many appointments are there usually per day?

We had the issue that with many appointments especially in the first week, the other weeks below were not shown, which was suboptimal as the month went on.

@georgehrke if it is possible to `#anchor` to the current week on loading the month view (after loading in the events) then we could change it again to show all events?

**Comment by georgehrke** [comment]
> if it is possible to #anchor to the current week on loading the month view (after loading in the events) then we could change it again to show all events?

No (or at least not easily), because we use progressive event rendering. So the position of a week, when first rendering the grid, is not the same as the position after rendering all events.

**Comment by georgehrke** [comment]
@IABLinz Please answer jan's question above. Thx!

**Comment by IABLinz** [comment]
Sorry it took me so long to answer, I was out of office. There are up to 50 appointments per day.

**Comment by georgehrke** [comment]
@tcitworld There seem to be two different groups of users here: Some that really like it and some that absolutely hate it. Should we make it configurable?

**Comment by Malspherus** [comment]
I'm generally in favour of making more things configurable. Calendars are often heavily used tools and even small inconveniences can sum up to problems over time. While too many options in the calendar itself may confuse users I think it should be fine to add some less frequently used ones on the per-user-settings page.

**Comment by IABLinz** [comment]
> 
> 
> @tcitworld There seem to be two different groups of users here: Some that really like it and some that absolutely hate it. Should we make it configurable?

that would be great

**Comment by tcitworld** [comment]
> There seem to be two different groups of users here: Some that really like it and some that absolutely hate it. Should we make it configurable?

Seems reasonable, as I've heard of people being quite disturbed by the "see more" functionality as well.

However the real issue here is to manage to put 50 events in the view at once (and there's definitely *a lot* more people that are using the calendar app like this than I thought).

**Comment by pm-pm** [comment]
**We thank god that this feature is back.**

Finally we don't have to play the game "[memory](https://de.wikipedia.org/wiki/Memory_%28Spiel%29)" anymore.

Please never switch off a feature without informing us before. Making it configurable immediately is the best way.
