### ISSUE TITLE
Calendar created talks in webinar mode

### ISSUE THREAD

**Issue by mokkin** [nextcloud/calendar#1890]
For better scheduling of webinars, meeting rooms in talk should be always in "webinar mode".
![DeepinBildschirmfoto_Bereich auswählen_20200123180640](https://user-images.githubusercontent.com/2938748/73006705-56cc1880-3e0b-11ea-90c9-95be2e256566.png)
![DeepinBildschirmfoto_Bereich auswählen_20200123180737](https://user-images.githubusercontent.com/2938748/73006709-592e7280-3e0b-11ea-9b92-b3407a8be8cf.png)

**Comment by georgehrke** [comment]
Duplicate of #1839
