### ISSUE TITLE
My calendars list is not loading

### ISSUE THREAD

**Issue by octopus-post** [nextcloud/calendar#1894]
Nextcloud: 17.0.2
Calendar app: 2.0.1
Browser: Google Chrome 79.0.3945.130

After updating the application Сalendar to version 2.0.1 I can not see the list of my calendars. I can’t create a new calendar, I can’t import the calendar. Other users see my public calendars.
![screenshot-10 171 136 193-2020 01 24-18_38_27](https://user-images.githubusercontent.com/47810706/73067348-09b77780-3edb-11ea-8604-51bb6e4eb684.png)

**Comment by georgehrke** [comment]
@octopus-post Can you please __fill the entire issue template__ like requested?

**Comment by octopus-post** [comment]
### Steps to reproduce
1. update the application Сalendar to version 2.0.1
2. click calendar in menu


### Expected behaviour
A list of my calendars should open

### Actual behaviour
The list of calendars is empty. I cannot add or import a new calendar. At the same time, other users see my shared calendars.


## Server configuration detail

**Operating system:** Linux 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64

**Webserver:** nginx/1.17.6 (fpm-fcgi)

**Database:** sqlite3 3.27.2

**PHP version:** 

7.3.13
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 17.0.2 - 17.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - announcementcenter: 3.6.1
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.1
 - cloud_federation_api: 1.0.0
 - dav: 1.13.0
 - deck: 0.8.0
 - drawio: 0.9.4
 - external: 3.4.1
 - extract: 1.2.3
 - federatedfilesharing: 1.7.0
 - files: 1.12.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - groupfolders: 5.0.5
 - impersonate: 1.4.0
 - issuetemplate: 0.6.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - ocr: 5.0.4
 - ojsxc: 3.4.4
 - onlyoffice: 4.1.1
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - support: 1.0.1
 - survey_client: 1.5.0
 - tasks: 0.11.3
 - text: 1.1.1
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - admin_audit
 - comments
 - contacts
 - encryption
 - federation
 - files_accesscontrol
 - files_external
 - files_fulltextsearch
 - fulltextsearch
 - fulltextsearch_elasticsearch
 - quicknotes
 - sharebymail
 - systemtags
 - user_ldap
 - user_usage_report

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "10.171.136.193",
        "nginx-server"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "version": "17.0.2.1",
    "overwrite.cli.url": "http:\/\/10.171.136.193",
    "installed": true,
    "onlyoffice": {
        "DocumentServerUrl": "\/ds-vpath\/",
        "DocumentServerInternalUrl": "http:\/\/onlyoffice-document-server\/",
        "StorageUrl": "http:\/\/nginx-server\/"
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "app_install_overwrite": [
        "extract",
        "onlyoffice",
        "files_accesscontrol",
        "ojsxc"
    ],
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Operating system:** Windows 10 Pro

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"9QdlyKm694JexxAle51t","level":0,"time":"2020-01-27T03:25:16+00:00","remoteAddr":"10.171.136.110","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OCA\\Support\\BackgroundJobs\\CheckSubscription job with ID 5 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"17.0.2.1"}
{"reqId":"yYRDlS4ZeeEmD7DQ32nf","level":0,"time":"2020-01-27T03:25:31+00:00","remoteAddr":"10.171.136.110","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OCA\\Files\\BackgroundJob\\ScanFiles job with ID 7","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"17.0.2.1"}
{"reqId":"yYRDlS4ZeeEmD7DQ32nf","level":0,"time":"2020-01-27T03:25:32+00:00","remoteAddr":"10.171.136.110","user":"--","app":"OC\\Files\\Cache\\Scanner","method":"GET","url":"\/cron.php","message":"!!! Path '' is not accessible or present !!!","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"17.0.2.1"}
{"reqId":"yYRDlS4ZeeEmD7DQ32nf","level":0,"time":"2020-01-27T03:25:32+00:00","remoteAddr":"10.171.136.110","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OCA\\Files\\BackgroundJob\\ScanFiles job with ID 7 in 1 seconds","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"17.0.2.1"}
{"reqId":"pS8gv1AxEx7DN9oM8cxy","level":0,"time":"2020-01-27T04:38:33+00:00","remoteAddr":"10.171.136.110","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 8","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"17.0.2.1"}
{"reqId":"pS8gv1AxEx7DN9oM8cxy","level":0,"time":"2020-01-27T04:38:33+00:00","remoteAddr":"10.171.136.110","user":"--","app":"DeleteOrphanedItems","method":"GET","url":"\/cron.php","message":"0 orphaned system tag relations deleted","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"17.0.2.1"}
{"reqId":"pS8gv1AxEx7DN9oM8cxy","level":0,"time":"2020-01-27T04:38:33+00:00","remoteAddr":"10.171.136.110","user":"--","app":"DeleteOrphanedItems","method":"GET","url":"\/cron.php","message":"0 orphaned user tag relations deleted","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"17.0.2.1"}
{"reqId":"pS8gv1AxEx7DN9oM8cxy","level":0,"time":"2020-01-27T04:38:33+00:00","remoteAddr":"10.171.136.110","user":"--","app":"DeleteOrphanedItems","method":"GET","url":"\/cron.php","message":"0 orphaned comments deleted","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"17.0.2.1"}
{"reqId":"pS8gv1AxEx7DN9oM8cxy","level":0,"time":"2020-01-27T04:38:33+00:00","remoteAddr":"10.171.136.110","user":"--","app":"DeleteOrphanedItems","method":"GET","url":"\/cron.php","message":"0 orphaned comment read marks deleted","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"17.0.2.1"}
{"reqId":"pS8gv1AxEx7DN9oM8cxy","level":0,"time":"2020-01-27T04:38:33+00:00","remoteAddr":"10.171.136.110","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 8 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.130 Safari\/537.36","version":"17.0.2.1"}

```
</details>

<details><summary>Browser log</summary>


</details>

**Comment by georgehrke** [comment]
Please also provide browser logs ...

There are always browser logs, even if they are just debug logs

**Comment by octopus-post** [comment]
[chrome_debug.log](https://github.com/nextcloud/calendar/files/4116114/chrome_debug.log)
This is the debug log of the Chrome browser.
PS. This problem has been detected in only one user. Other users open calendars without errors.

**Comment by georgehrke** [comment]
I meant the javascript browser log, which you can open with <kbd>cmd</kbd><kbd>option</kbd><kbd>i</kbd>

**Comment by octopus-post** [comment]
Did you mean that?
****************************************
JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:26 oc_config is deprecated: use OC.config instead
He @ globals.js:26
get @ globals.js:52
mounted @ App.vue:97
Vt @ vue.esm.js:1863
rn @ vue.esm.js:4222
insert @ vue.esm.js:3148
C @ vue.esm.js:6351
(anonymous) @ vue.esm.js:6570
t._update @ vue.esm.js:3948
r @ vue.esm.js:4069
gn.get @ vue.esm.js:4482
gn @ vue.esm.js:4471
(anonymous) @ vue.esm.js:4076
An.$mount @ vue.esm.js:9057
An.$mount @ vue.esm.js:11953
t._init @ vue.esm.js:5021
An @ vue.esm.js:5088
(anonymous) @ init.js:41
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=ad340851-35:1
ProxyBus.js:74 Proxying an event bus of version 0.2.1 with 1.1.2
e @ ProxyBus.js:74
(anonymous) @ index.js:22
i @ bootstrap:63
(anonymous) @ requesttoken.js:9
i @ bootstrap:63
(anonymous) @ index.js:25
i @ bootstrap:63
(anonymous) @ calendar.js?v=ad340851-35:2
i @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ calendar.js?v=ad340851-35:2
globals.js:26 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
He @ globals.js:26
i @ globals.js:38
(anonymous) @ l10n.js:103
(anonymous) @ l10n.js:98
translate @ l10n.js:121
t.translate @ index.js:60
additionalTimezones @ SettingsTimezoneSelect.vue:63
dn.get @ vue.runtime.esm.js:4479
dn.evaluate @ vue.runtime.esm.js:4584
(anonymous) @ vue.runtime.esm.js:4836
xd @ SettingsTimezoneSelect.vue?04a6:14
e._render @ vue.runtime.esm.js:3548
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
A @ vue.runtime.esm.js:5925
p @ vue.runtime.esm.js:6053
A @ vue.runtime.esm.js:5954
p @ vue.runtime.esm.js:6053
A @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
A @ vue.runtime.esm.js:5925
p @ vue.runtime.esm.js:6053
A @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
A @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
A @ vue.runtime.esm.js:5925
p @ vue.runtime.esm.js:6053
A @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
A @ vue.runtime.esm.js:5925
p @ vue.runtime.esm.js:6053
A @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
A @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
n @ vue.runtime.esm.js:3301
(anonymous) @ vue.runtime.esm.js:5978
A @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
A @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
e._init @ vue.runtime.esm.js:5018
wn @ vue.runtime.esm.js:5085
(anonymous) @ main.js:64
i @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ calendar.js?v=ad340851-35:2
Show 84 more frames
globals.js:26 oc_config is deprecated: use OC.config instead
He @ globals.js:26
get @ globals.js:52
(anonymous) @ ojsxc.js?v=ad340851-35:391
u @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
P @ jquery.js:3433
globals.js:26 oc_appswebroots is deprecated: use OC.appswebroots instead
He @ globals.js:26
get @ globals.js:52
(anonymous) @ ojsxc.js?v=ad340851-35:391
u @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
P @ jquery.js:3433
globals.js:26 oc_config is deprecated: use OC.config instead
He @ globals.js:26
get @ globals.js:52
(anonymous) @ ojsxc.js?v=ad340851-35:443
u @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
P @ jquery.js:3433
globals.js:26 oc_appswebroots is deprecated: use OC.appswebroots instead
He @ globals.js:26
get @ globals.js:52
(anonymous) @ ojsxc.js?v=ad340851-35:447
u @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
P @ jquery.js:3433
jsxc.js:184 State changed to INITIATING
jsxc.js:184 State changed to PREVCONFOUND
jsxc.js:184 check master
globals.js:26 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
He @ globals.js:26
i @ globals.js:38
parseMessage @ richObjectStringParser.js:31
renderedSubject @ Notification.vue:155
gn.get @ vue.esm.js:4482
gn.evaluate @ vue.esm.js:4587
(anonymous) @ vue.esm.js:4839
useLink @ Notification.vue:151
gn.get @ vue.esm.js:4482
gn.evaluate @ vue.esm.js:4587
(anonymous) @ vue.esm.js:4839
(anonymous) @ Notification.vue?b540:1
t._render @ vue.esm.js:3551
r @ vue.esm.js:4069
gn.get @ vue.esm.js:4482
gn @ vue.esm.js:4471
(anonymous) @ vue.esm.js:4076
An.$mount @ vue.esm.js:9057
An.$mount @ vue.esm.js:11953
init @ vue.esm.js:3127
(anonymous) @ vue.esm.js:5983
l @ vue.esm.js:5930
v @ vue.esm.js:6058
l @ vue.esm.js:5959
(anonymous) @ vue.esm.js:6482
t._update @ vue.esm.js:3948
_update @ vue.esm.js:8888
r @ vue.esm.js:4069
gn.get @ vue.esm.js:4482
gn @ vue.esm.js:4471
(anonymous) @ vue.esm.js:4076
An.$mount @ vue.esm.js:9057
An.$mount @ vue.esm.js:11953
init @ vue.esm.js:3127
(anonymous) @ vue.esm.js:5983
l @ vue.esm.js:5930
v @ vue.esm.js:6058
l @ vue.esm.js:5959
(anonymous) @ vue.esm.js:6521
t._update @ vue.esm.js:3951
r @ vue.esm.js:4069
gn.get @ vue.esm.js:4482
gn.run @ vue.esm.js:4557
vn @ vue.esm.js:4313
(anonymous) @ vue.esm.js:1989
Yt @ vue.esm.js:1915
Promise.then (async)
Kt @ vue.esm.js:1942
re @ vue.esm.js:1999
(anonymous) @ vue.esm.js:4405
gn.update @ vue.esm.js:4547
dt.notify @ vue.esm.js:739
set @ vue.esm.js:1064
mn.set @ vue.esm.js:4634
(anonymous) @ App.vue:178
Promise.then (async)
_fetch @ App.vue:173
mounted @ App.vue:94
Vt @ vue.esm.js:1863
rn @ vue.esm.js:4222
insert @ vue.esm.js:3148
C @ vue.esm.js:6351
(anonymous) @ vue.esm.js:6570
t._update @ vue.esm.js:3948
r @ vue.esm.js:4069
gn.get @ vue.esm.js:4482
gn @ vue.esm.js:4471
(anonymous) @ vue.esm.js:4076
An.$mount @ vue.esm.js:9057
An.$mount @ vue.esm.js:11953
t._init @ vue.esm.js:5021
An @ vue.esm.js:5088
(anonymous) @ init.js:41
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=ad340851-35:1
Show 16 more frames
vue.runtime.esm.js:1888 DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at yb (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=ad340851-35:2:2554002)
    at bb (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=ad340851-35:2:2553669)
    at http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=ad340851-35:2:2559603
    at Array.map (<anonymous>)
    at http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=ad340851-35:2:2559579
    at c (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=ad340851-35:2:1011658)
    at Generator._invoke (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=ad340851-35:2:1011411)
    at Generator.forEach.e.<computed> [as next] (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=ad340851-35:2:1012015)
    at wb (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=ad340851-35:2:2554446)
    at a (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=ad340851-35:2:2554650)
ze @ vue.runtime.esm.js:1888
Ze @ vue.runtime.esm.js:1879
Ue @ vue.runtime.esm.js:1839
(anonymous) @ vue.runtime.esm.js:1856
Promise.catch (async)
Qe @ vue.runtime.esm.js:1856
Kt @ vue.runtime.esm.js:4219
e @ vue.runtime.esm.js:4043
wn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
n @ vue.runtime.esm.js:3301
(anonymous) @ vue.runtime.esm.js:5978
A @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
A @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
dn.get @ vue.runtime.esm.js:4479
dn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
wn.$mount @ vue.runtime.esm.js:8415
e._init @ vue.runtime.esm.js:5018
wn @ vue.runtime.esm.js:5085
(anonymous) @ main.js:64
i @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ calendar.js?v=ad340851-35:2
jsxc.js:184 I am master.
jsxc.js:184 State changed to ESTABLISHING
jsxc.js:184 Try to attach
jsxc.js:184 SID: internal
jsxc.js:184 ATTACHED: null
jsxc.js:184 UI State changed to INITIATING
jsxc.js:184 Waiting for server capabilities
jsxc.js:184 Request server capabilities
jsxc.js:184 UI State changed to READY
jsxc.js:184 DSA key loaded
jsxc.js:184 State changed to READY

**Comment by mart1oeil** [comment]
I've the same problem with Firefox, i can't access anymore to my calendar

**Comment by tcitworld** [comment]
@mart1oeil Please post your browser logs to be sure this is the same issue, since @octopus-post has the following bug in their logs [which seems to be Chrome-related](https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte).
```
DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

**Comment by mart1oeil** [comment]
@tcitworld Ok, for now, I've downgraded to 1.7.2, and it's working. So I'll do it with the 2.1.0 but not today.

**Comment by octopus-post** [comment]
This is probably not a browser problem. The same issue exists in another browser. e.g. firefox:

`[DEBUG] calendar: Current user principal is /remote.php/dav/principals/users/uadm/ 
Object { app: "calendar", uid: "authenticated:uadm" }
ConsoleLogger.js:44:18
DOMException: "String contains an invalid character" vue.runtime.esm.js:1888:12
    VueJS 4
        ze
        Ze
        Ue
        Qe`

Or I'm wrong?

**Comment by mart1oeil** [comment]
Yeah, definitly right : As it is written "invalid character", I've changed my agenda with french accent characters (like é or è) to ascii names and that's working. So the problem is that the app does'nt use utf-8 but ascii, I think.

**Comment by octopus-post** [comment]
Hi. Will there be a bug fix update?

**Comment by octopus-post** [comment]
Updating to version 2.0.2 did not solve the problem. I do not see the list of calendars, I can not edit calendars. Other users see my calendars and can create their own.
`vue.runtime.esm.js:1888 DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Ym (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=620db7b7-35:2:2709306)
    at jm (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=620db7b7-35:2:2708973)
    at http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=620db7b7-35:2:2714867
    at Array.map (<anonymous>)
    at http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=620db7b7-35:2:2714843
    at c (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=620db7b7-35:2:1020387)
    at Generator._invoke (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=620db7b7-35:2:1020140)
    at Generator.forEach.e.<computed> [as next] (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=620db7b7-35:2:1020744)
    at Um (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=620db7b7-35:2:2709750)
    at a (http://10.171.136.193/custom_apps/calendar/js/calendar.js?v=620db7b7-35:2:2709954)`
![screenshot-10 171 136 193-2020 03 04-10_33_03](https://user-images.githubusercontent.com/47810706/75842945-64aa8b80-5e04-11ea-86aa-5284b10dad98.png)
![screenshot-translate google com-2020 03 04-10_36_01](https://user-images.githubusercontent.com/47810706/75842948-6a07d600-5e04-11ea-8ed0-d4ad0615d8cc.png)

**Comment by octopus-post** [comment]
UPDATE. I edit my calendars only on android

**Comment by crocodeev** [comment]
Have the same issue. Google Chrome log:
"Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range"
This only happend with two users with admin permissions

**Comment by georgehrke** [comment]
Could anyone of you please execute the following SQL statement and post the result (or send me [by email](mailto:georg.ehrke@nextcloud.com))?

```sql
SELECT `principaluri`, `uri` from oc_calendars;
```

**Comment by georgehrke** [comment]
Nevermind. I've been able to reproduce it.
