### ISSUE TITLE
No translation for button

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/calendar#1897]
No "Import calendar" translation for the import button. **Not present in Transifex.**

![obraz](https://user-images.githubusercontent.com/47037905/73075044-52f7cf00-3ebb-11ea-9db0-293b623c7e32.png)

Code:
https://github.com/nextcloud/calendar/blob/7a1e962c51bf418b4b13a31c9b2aa7b5f56741ce/src/components/AppNavigation/Settings/SettingsImportSection.vue#L31
https://github.com/nextcloud/calendar/blob/7a1e962c51bf418b4b13a31c9b2aa7b5f56741ce/src/components/AppNavigation/Settings/ImportScreen.vue#L50

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.1

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
18.0.0

**Comment by georgehrke** [comment]
They are on transifex. Any specific language you can't find them in? 

![63C0AF85-393C-443E-9DD3-13201BE479F7](https://user-images.githubusercontent.com/1250540/73075620-9d2d8000-3ebc-11ea-9a09-354695acb4dd.png)

**Comment by georgehrke** [comment]
They are also available in polish:
![55A79BE4-CEF2-4F82-9AF4-DE7127C885B3](https://user-images.githubusercontent.com/1250540/73075838-1cbb4f00-3ebd-11ea-9a3f-e34d549d2d1f.png)

**Comment by Valdnet** [comment]
@georgehrke Sorry.

Then this translation is not read:
https://github.com/nextcloud/calendar/blob/7a1e962c51bf418b4b13a31c9b2aa7b5f56741ce/l10n/pl.js#L85
https://github.com/nextcloud/calendar/blob/7a1e962c51bf418b4b13a31c9b2aa7b5f56741ce/l10n/pl.json#L83

**Comment by georgehrke** [comment]
This is an interesting bug 🤔

There seems to be a bug in extracting the translations / generating the .js/.json files.
Using the same string in t and as singular in n seems not supported.

**Comment by georgehrke** [comment]
Closing in favour of https://github.com/nextcloud/server/issues/19123

**Comment by Valdnet** [comment]
Resolved in: #2327.
