### ISSUE TITLE
show import calendar button below new calendar button if no writable calendars exist

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#19]

**Comment by georgehrke** [comment]
@jancborchardt You suggested this some time ago.
Actually having no calendar at all is a very rare use case, because you start with the default calendar.

**Comment by jancborchardt** [comment]
Yeah … showing it if no Calendars exists isn’t really something which comes up often.

Maybe on first run the settings area on the bottom left should be expanded by default. But that might be too much.

What do you think @nextcloud/designers

**Comment by eppfel** [comment]
Isn't calendar `personal` created for every new user anyway? Because in my local installation, it is that way and I can't remember configuring it.

**Comment by georgehrke** [comment]
@eppfel Yes, but it's still empty when you first launch the app.
That's why we want to prominently show an import button ;)

**Comment by stefan-niedermann** [comment]
what about something like a first-run-wizard-for-calendar app? Like a modal pop-up which explains how to import a calendar (with a big fat import-button)?

**Comment by georgehrke** [comment]
@stefan-niedermann I'm actually not sure about a first-run-wizard for the calendar.
If we implement some "do something on first run" feature, we can also just display the import button below your personal calendar and maybe add a tooltip that says "Get started by importing existing calendars"

**Comment by eppfel** [comment]
@stefan-niedermann  First run wizards have the problem, that they break context. I think @georgehrke proposal makes more sense.

**Comment by georgehrke** [comment]
@jancborchardt  @eppfel So, what way do we want to go?

1. expand settings area on first run
2. show important button below personal calendar on first run

I actually see an issue with the second approach. People don't learn where the actual import button is and might wonder why the import button is gone when opening the calendar app the second time.

**Comment by georgehrke** [comment]
Also, what's about rephrasing the label in the lower left corner from »Settings« to »Settings & Import«?

**Comment by eppfel** [comment]
> People don't learn where the actual import button is and might wonder why the import button is gone when opening the calendar app the second time.

You could trigger the toggle animation.

**Comment by georgehrke** [comment]
Okay, will do that :) 

Yay or Nay about renaming the settings label?

**Comment by eppfel** [comment]
Yay 👍
