### ISSUE TITLE
Undefined colour variable

### ISSUE THREAD

**Issue by mwalbeck** [nextcloud/calendar#1905]
Hi,

Just a little heads up, you have an undefined colour variable on line 154 in fullcalendar.scss. I think it's supposed to be --color-background-dark

https://github.com/nextcloud/calendar/blob/942a7ea44e6e6e2eb243f84ceade6714884671c8/css/fullcalendar.scss#L154

**Comment by georgehrke** [comment]
Thx! It should be `var(--color-main-background)`
