### ISSUE TITLE
Unable to insert URL with "&" in "New subscription from link"

### ISSUE THREAD

**Issue by shmca** [nextcloud/calendar#1906]
In a previous version of nextcloud calendar I war able to insert an URL like:
https://antiope.webuntis.com/WebUntis/Ical.do?school=XXX&id=XXXXX&token=xxxxxxxxxxxxxxxxxxxxxxxxxxx
The newsubscription ist shown as antiope.webuntis.com but it is not shown/downloaded anymore!
System information:
-nextcloud version 17.0.2
-calendar version 2.0.0 and 2.0.1
No errors are shown in the log files:
-nextcloud.log and my nextcloud error log file 
-error.log of the apache server
I use ubuntu 18.04.3 and 
-PHP 7.2.24-0ubuntu0.18.04.2 (cli) (built: Jan 13 2020 18:39:59) ( NTS )

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md)

Unless you fill out the issue template completely including all logs, we can't go ahead and help you.

**Comment by georgehrke** [comment]
Please also see https://github.com/nextcloud/server/issues/19126#issuecomment-575915098

And make sure that Cron is properly set up, check the oc_jobs and oc_calendarobjects table as explained in the referenced GitHub ticket.
