### ISSUE TITLE
No translation display

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/calendar#1912]
When creating a task or created task, the translation "in x days" is not displayed. In Transifex all current translations are translated.

![obraz](https://user-images.githubusercontent.com/47037905/73125854-0b04a500-3fac-11ea-9ea8-19313f95c610.png)

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.1
**Nextcloud Version:** (see admin page, e.g. 17.0.2)
18.0.0

**Comment by georgehrke** [comment]
Pull-request: #1932
