### ISSUE TITLE
A space character is visible

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/calendar#1915]
When creating a new calendar, a hard space character is displayed.

![obraz](https://user-images.githubusercontent.com/47037905/73138787-0224d980-4067-11ea-89b7-e534056108cb.png)

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.1

### Client configuration
**Browser:** (e.g. Firefox 48)
Firwfox 72.0.2

**Operating system:** (e.g. Arch Linux)
Win7

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
18.0.0

**Comment by georgehrke** [comment]
This is actually a server issue. Possible fix is in https://github.com/nextcloud/server/pull/18741

Let's keep this open as reference for now.

**Comment by Valdnet** [comment]
In Calendar 2.0.3 for Nextcloud 19.0.0, the error does not appear.
