### ISSUE TITLE
Illustration parsing uses substrings

### ISSUE THREAD

**Issue by rspencer01** [nextcloud/calendar#1916]
### Steps to reproduce
1. Create an event titled _Campaign for Better String Matching_
2. Notice the illustration is of camping
3. Puzzle

### Expected behaviour
The illustration should not be related to camping.

### Actual behaviour
The illustration is related to camping

### Fix
As mentioned in #1888 , the line given here https://github.com/nextcloud/calendar/blob/b9b47a17c1a1bd663011be7079d87533e94abcec/src/utils/illustration.js#L57 matches all substrings, including the "camp" in "campaign".  It should be replaced (at first blush) by a space-delimited checker that ensures that the entire word is matched.

This is an issue to track progress on this bug.

**Comment by georgehrke** [comment]
Something like https://regexr.com/4sv6e  should already do the trick.

**Comment by georgehrke** [comment]
@rspencer01 There is a fix in https://github.com/nextcloud/calendar/pull/1918

**Comment by rspencer01** [comment]
Wow.  Much speed.
