### ISSUE TITLE
Missing share icon in calendar list

### ISSUE THREAD

**Issue by stesser** [nextcloud/calendar#1922]
A fresh installation of NextCloud-18 works with respect to all other tested components, but does not allow calendar sharing (the "share API" setting is enabled).

Is there another setting that might disable calendar sharing for all users?

What debugging features are available in such a case (apparently no error, just a feature that seems to b disabled)?

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - apporder: 0.9.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - deck: 0.8.0
  - event_update_notification: 1.0.1
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_fulltextsearch: 1.4.1
  - files_lock: 0.8.1
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - flowupload: 0.1.8
  - fulltextsearch: 1.4.0
  - fulltextsearch_elasticsearch: 1.5.0
  - groupfolders: 6.0.0
  - impersonate: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.0.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocr: 5.0.5
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.1
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_gateway: 0.15.1
  - twofactor_nextcloud_notification: 2.2.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - w2g2: 3.0.1
  - workflowengine: 2.0.0

Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_reader
  - twofactor_admin
  - user_ldap
```

**Comment by georgehrke** [comment]
Please try to disable all browser extensions / add-ons. It's most likely some adblocker.

**Comment by georgehrke** [comment]
If that's not it, please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md)

Unless you fill out the issue template completely including all logs, we can't go ahead and help you.

**Comment by tcitworld** [comment]
> (the "share API" setting is enabled).

And the `File sharing` app enabled as well.

**Comment by stesser** [comment]
Well, Georg Ehrke provided the hint that let me get Calendar sharing to work, thanks a lot!

In fact, it was uBlock Origin, which was "all green" for this site (as well as uMatrix by default, since no foreign resources are used), but "Cosmetic Filters" were active and they cause the Share icons to vanish.

If there is interest in the cause, I attempt to analyze why these filters suppress these elements, but the issue is resolved for me (and all users of this server).

If this issue will not be resolved in the Calendar app, a note might be appropriate to inform users about the potential impact of the ad/tracking filter.

Thanks again for the extremely fast reply, which was also to the point ...
