### ISSUE TITLE
the style of the calendar differs from admin to normal user

### ISSUE THREAD

**Issue by cl4x** [nextcloud/calendar#1924]
Hi,
the display from users is totally different respect display from admin. On same browser, on all browsers. Show Attach. The problem is after the update Calendar 2.

From users is really unusable, the dark outline makes it difficult to read.

### Calendar app
**Calendar app version:** from 2.0

### Client configuration
**Browser:** Firefox 72.0.1 or Chrome 79.0.03945.117

**Operating system:** Windows and Linux

### Server configuration
**Operating system**: Debian 8
**Web server:** Apache
**PHP version:** 7
**Nextcloud Version:** 17.0.2
**Updated from an older installed version or fresh install:** update from NC16

From Admin
![fromAdmin](https://user-images.githubusercontent.com/47188814/73246656-71a5e080-41af-11ea-9108-8362df0481bf.JPG)

From User
![FromUSER](https://user-images.githubusercontent.com/47188814/73246658-71a5e080-41af-11ea-9797-d96a9bc6b1b9.JPG)

**Comment by georgehrke** [comment]
@cl4x This looks to me like the user in question enabled high contrast mode in accessibility.

**Comment by cl4x** [comment]
> 
> 
> @cl4x This looks to me like the user in question enabled high contrast mode in accessibility.

OMG!! 
I went crazy, I saw everything except this.

Thanks
