### ISSUE TITLE
New event popover positioning issue on double click

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/calendar#1925]
### Steps to reproduce

1. Create a new calendar.
2. Double click on the calendar window.

### Expected behaviour
The new event window should open in full visibility.

### Actual behaviour
A new event window opens with partial visibility.

![obraz](https://user-images.githubusercontent.com/47037905/73258876-e7697680-41c6-11ea-9f7d-271d17685d0e.png)

###Nextcloud version: (see Nextcloud admin page)
18.0.0

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.1

### Client configuration
**Browser:**
Firefox 72.0.2

**Operating system:**
Win7 and Win10

**Comment by georgehrke** [comment]
> Double click on the calendar window.

I hate it how Microsoft conditioned all windows users to double click everything they see 😂

If you just click once it works as expected.

**Comment by georgehrke** [comment]
Reproducible with double click.

**Comment by georgehrke** [comment]
@Valdnet Did you find other things that do not work as expected when double clicking instead of just clicking once?

**Comment by Valdnet** [comment]
@georgehrke I clicked a bit on the calendar and haven't found anything yet :stuck_out_tongue_winking_eye:.

**Comment by raimund-schluessler** [comment]
Doesn't need to be a fast double-click. It is enough to click the calendar event placeholder after the new event popover editor is opened.
