### ISSUE TITLE
Preserve duration when editing start time

### ISSUE THREAD

**Issue by castletonroad** [nextcloud/calendar#1929]
### Steps to reproduce
1. Set up repeating event with duration less than 1 hour: Monday 7.00-7.15am, repeat weekly on Mondays, end after 5 occurrences
2. Edit repeating event: change start date into the future by 10 weeks; select update this and all future events

### Expected behaviour
1. Repeating series of events should 'shift' 10 weeks into the future, with no other changes to the event

### Actual behaviour
1. Duration resets to 1 hour for the series.

### Calendar app
2.0.1

### Client configuration
Firefox 72.0.2

**Operating system:** (e.g. Arch Linux)
Raspbian Debian Buster

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian Buster

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0.3)
7.3.11-1

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
17.0.2

**Updated from an older installed version or fresh install:**
Update from 16.x.x

**List of activated apps:**
Enabled:
  - activity: 2.10.1
  - calendar: 2.0.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.8
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.1.1
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - accessibility
  - admin_audit
  - encryption
  - federation
  - files_external
  - files_rightclick
  - files_sharing
  - files_videoplayer
  - firstrunwizard
  - recommendations
  - serverinfo
  - sharebymail
  - support
  - survey_client
  - systemtags
  - text
  - user_ldap
  - weather

**Nextcloud configuration:**
root@raspberrypi4:/var/www/html/nextcloud# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.25",
            "theconstantines.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "overwrite.cli.url": "https:\/\/theconstantines.org\/nextcloud",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "trashbin_retention_obligation": "auto, 30",
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "calendar",
            "githubmergetracker"
        ],
        "updater.release.channel": "stable"
    }
}

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment]
Possibly related to #1914

**Comment by georgehrke** [comment]
I can't reproduce this bug.

I can reproduce the following though:
- When you change the start-date to something later than the end-date, it automatically sets the end date to the start date, meaning the event is 0 minutes long.
- 2.0.1 has a bug, where 0 minute long events are displayed as one hour: https://github.com/nextcloud/calendar/issues/1963

So since I'm not able to reproduce your bug, i assume that you have run into a combination of both. Can you confirm that?

**Comment by castletonroad** [comment]
I confirm I have just repeated this bug.

My repeating event has been moved forward (stating 10 weeks in the future).

The duration has been re-set in error to one hour (vs. the original 15 mins duration)

**Comment by georgehrke** [comment]
Is it reset to one hour in the view or also in the editor?

**Comment by castletonroad** [comment]
In view it shows as one hour. In the editor it shows as 7am start, 7am finish, so zero hour duration.

**Comment by georgehrke** [comment]
Okay, so my guess that you are affected by #1963 was corrected.

What we have to fix is preserving the original duration when editing the start time

**Comment by georgehrke** [comment]
There is a pull-request available in https://github.com/nextcloud/calendar/pull/2041
