### ISSUE TITLE
Move of particular event of a series schedule duplicates the event

### ISSUE THREAD

**Issue by dziemann** [nextcloud/calendar#193]
Maybe this is a feature request and not a bug, but moving a particular event from a series schedule in Outlook leads to a doupled event in the Calendar app, because the old event is not being deleted.

The move of a particular event of a series schedule is not supported by the Calendar app itself. Means, you can not move only one event of a series schedule in the Calendar app.

### Steps to reproduce
1. Create a series schedule in Outlook (e.g. fullday event every Monday) and sync to calendar
2. Move on particular event from Monday to Tuesday in Outlook and sync to calendar
3. Event is moved from Monday to Tuesday

### Expected behaviour
Event is properly synced with the calendar. Old event is being deleted and new event on Tuesday is being created

### Actual behaviour
The event is doubled. The old event on Monday is not being deletet and the new event on Tuesday is being created

### Server configuration
**Operating system**:
Linux
**Web server:**
Apache
**Database:**
MySQL 5.6
**PHP version:**
5.6
**Server version:** (see your admin page)
Nextcloud 10.0.1
**Calendar version:** (see the apps page)
1.4.0

**Updated from an older installed version or fresh install:**
fresh install
```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome (latest)
**Operating system:**
Windows 10
**CalDAV-clients:**
Outlook 2016

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/142
