### ISSUE TITLE
No events shown for day, only +x more

### ISSUE THREAD

**Issue by Helium314** [nextcloud/calendar#1931]
In monthly view at some zoom levels no events are shown for certain days, only "+x more".

At 100% zoom, everything looks fine
![100](https://user-images.githubusercontent.com/43007630/73343137-535be580-4280-11ea-9f6a-4aba6b6f149d.png)

At 110% zoom, events on 14th, 15th and 19th are replaced by "+2 more". This could be related to the events with multi-line titles, as does not happen on 20th.
![110](https://user-images.githubusercontent.com/43007630/73343196-7090b400-4280-11ea-9021-bd5be3f1724b.png)

At 160% zoom (probably uncommon, but still usable), some events disappear completely, again it might be related to the multi-line events.
![160](https://user-images.githubusercontent.com/43007630/73343437-f0b71980-4280-11ea-976a-443bad4cfa85.png)

Happens in Vivaldi 2.10 and Firefox 72.0.2 on Windows 7, 1920x1080.
Vivaldi 2.10 on Manjaro Linux, 100% zoom, 1.5x scaling using KDE, 3000x2000 looks similar to 110% zoom on Windows 7.

Nextcloud 17.0.2
Calender 2.0.1

**Comment by georgehrke** [comment]
@Helium314 Are the events, that are hidden on 14th and 15th, multiday events? If yes, can you tell me from what day to what day they  span?

**Comment by Helium314** [comment]
None of them are multiday,
On 14th there is one all-day event and one from 20:00 to 21:00, on 15th both events are all-day events.

**Comment by georgehrke** [comment]
But they have multiline titles?

**Comment by Helium314** [comment]
Two of them, you can still see it on the screenshots
