### ISSUE TITLE
Next month button skips one month the first time

### ISSUE THREAD

**Issue by probastaller** [nextcloud/calendar#1936]
### Steps to reproduce
1. Happened today for the first time. In case it has relation with the current date (ending month).
2. When clicking on the **Next Month** button for the first time  it goes from January to March skipping February
3. After that first time, it goes to next and previous months correctly.

### Calendar app
**Calendar app version: 2.0.1**

### Client configuration
**Browser:Firefox 72.0.1**

**Operating system: Linux Mint 19.1**

**Comment by raimund-schluessler** [comment]
Happens again after clicking `Today` button.

**Comment by georgehrke** [comment]
Yes, I was already able to reproduce it. On it ...

**Comment by georgehrke** [comment]
Fixed in #1937, will be part of 2.0.2
