### ISSUE TITLE
Can't share with users or groups?

### ISSUE THREAD

**Issue by EmJotGeh** [nextcloud/calendar#195]
Hi,

I'm using the calendar app on owncloud 9.1.1 and i can't see the share button. It's not possible to share with others. Any idea?

**Comment by georgehrke** [comment]
Please make sure you disable your adblockers for Nextcloud

**Comment by EmJotGeh** [comment]
ohhh yes, ok you solve my problem! Thanks

**Comment by tcitworld** [comment]
@georgehrke Maybe we could add this to some kind of a FAQ ?

**Comment by RealRancor** [comment]
Already there since longer time https://github.com/nextcloud/calendar/wiki/FAQs

**Comment by tcitworld** [comment]
In that case, maybe link to it from the issue template ?
