### ISSUE TITLE
Responsive illustrations

### ISSUE THREAD

**Issue by despens** [nextcloud/calendar#1956]
For users with small screens or who otherwise prefer not to see illustrations, it would be nice to have an option to turn them off.

**Comment by georgehrke** [comment]
We are not gonna add an option to hide illustrations all together.

Please provide some screenshots from smaller screens, where illustrations are too big. I'm happy to make them smaller / responsive in that case.

**Comment by despens** [comment]
Screenshot at 1440 physical pixel screen height, with default 200% scaling from OS:

![image](https://user-images.githubusercontent.com/571494/74612078-0d9c7b00-50d0-11ea-83e7-486a53b91b86.png)

Three input fields + update button are only reachable by scrolling.

The CSS theming app can be used to remove the illustration, that dislocates the event details closing :heavy_multiplication_x: button a little though:
```css
div.app-sidebar-header__figure {
  display: none;
}
```

**Comment by georgehrke** [comment]
If the screen's height is too small, we should switch to compact mode: 

![FDEBC721-0D2B-4613-BDC4-B7E130097C40](https://user-images.githubusercontent.com/1250540/75783733-50fa1900-5d61-11ea-863f-719ba95cc477.png)

**Comment by ctag** [comment]
> We are not gonna add an option to hide illustrations all together.

Would the project consider a pull request for this feature?

**Comment by georgehrke** [comment]
> > We are not gonna add an option to hide illustrations all together.
> 
> 
> 
> Would the project consider a pull request for this feature?

No, we want sensible defaults and not configuration options for every tiny detail.

If illustrations are too big on small screens, we should just make them smaller.

**Comment by georgehrke** [comment]
@ctag However, if you are willing to contribute a PR, it would be very much appreciated if you implemented the responsiveness.

The small preview i showed [further above](https://github.com/nextcloud/calendar/issues/1956#issuecomment-593970438) is easily done by setting `compact` to `true` in the `AppSidebar`: https://nextcloud-vue-components.netlify.com/#/Components/App%20containers?id=appsidebar

The only things that's really needed is the code that handles the window resize event and sets `compact` to `true` or `false` depending on whatever limits we decide on.

**Comment by ctag** [comment]
@georgehrke Understood. If I can find some time this week I'll see if I can put together that PR.

**Comment by ctag** [comment]
Had to tweak the CSS I use to hide these images. Sharing here in case it's useful.

```
.app-sidebar .illustration-header, .event-popover .popover-inner .illustration-header {
  height: 50px;
}

div.illustration-header svg {
  display: none;
}
```

And I found a resource that explains my thoughts on the illustrations better than I could:
https://www.youtube.com/watch?v=lFb7BOI_QFc

**Comment by st3iny** [comment]
Closing because illustrations were removed in the meantime.
