### ISSUE TITLE
Calendar 1.4.1 published at apps.owncloud.com has invalid signature

### ISSUE THREAD

**Issue by RealRancor** [nextcloud/calendar#196]
### Steps to reproduce
1. Have a working Calendar 1.4.0 on oC 9.1.2
2. Getting update notification that 1.4.1 is available
3. Update Calendar to 1.4.1

Seems the version 1.4.1 published at apps.owncloud.com has an invalid signature:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- App Certificate is not valid.

Raw output
==========
Array
(
    [calendar] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => App Certificate is not valid.
                )

        )

)
```

**Comment by georgehrke** [comment]
I can't reproduce this :/

Let me fire up an oC instance

**Comment by georgehrke** [comment]
@RealRancor I tried to fix the cert issue.
Can you validate that calendar2.tar.gz works? 

https://github.com/nextcloud/calendar/releases/tag/v1.4.1

**Comment by RealRancor** [comment]
@georgehrke Confirmed, the calendar2.tar.gz from the tag doesn't show this issue. Thanks for the quick fix.

**Comment by raoulbhatia** [comment]
@georgehrke I had the same error and calendar2.tar.gz works for me as well.

Thanks,
Raoul

**Comment by RealRancor** [comment]
Thanks for additional confirmation. So lets close this then.

**Comment by DNkRockzzzzZ** [comment]
It works yes. But why not in  Internet Explorer? It is loading and loading and loading. Look at the screenshot.
![bug](https://cloud.githubusercontent.com/assets/23698248/20610509/167ce31c-b29b-11e6-9c4a-63f8ff7ea6c9.jpg)
 is loading and loading.

**Comment by RealRancor** [comment]
@DNkRockzzzzZ Unrelated. Please don't hijack issues like this

**Comment by colidyre** [comment]
Is it also possible to fix this issue for the version which an admin can activate under /index.php/settings/apps simply by clicking "activate" in the Frontend (for convenience)?

OC 9.1.6.2
Calendar 1.4.1
