### ISSUE TITLE
Duration display issue with entries having a duration of a minute or less

### ISSUE THREAD

**Issue by urmel1960** [nextcloud/calendar#1963]
I do log phone calls or sms in a calendar on my phone and sync this calendar with a calendar in nextcloud. sms typically do not have a long duration - so start and end date and time are mostly the same .

Within nextcloud the entries are wrongly displayed: 

![grafik](https://user-images.githubusercontent.com/144102/73786365-664b4a00-4799-11ea-98d8-308f9ed10768.png)

This occurs for all entries having a duration od a minute or less.

### Calendar app
Calendar app version:2.0.1

### CalDAV-clients used: 
DAVx5

### Client configuration
**Browser:** Firefox 72.02

**Operating system:** Win 10 Enterprise x64

### Server configuration

**Operating system**: Ubuntu 18.04. LTS

**Web server:** Apache

**Database:** MariaDB

**PHP version:** PHP 7.2.24-0ubuntu0.18.04.2

**Nextcloud Version:** 18.0.0.

**Updated from an older installed version or fresh install:**
updated 
**List of activated apps:**

Enabled:
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - audioplayer: 2.9.0
  - audioplayer_editor: 0.2.0
  - audioplayer_sonos: 1.1.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - deck: 0.8.0
  - documentserver_community: 0.1.5
  - event_update_notification: 1.0.1
  - external: 3.5.0
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_downloadactivity: 1.7.0
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - fulltextsearch: 1.4.1
  - fulltextsearch_elasticsearch: 1.5.0
  - groupfolders: 6.0.1
  - groupquota: 0.1.2
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.2
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.1
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - terms_of_service: 1.4.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_nextcloud_notification: 2.2.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - accessibility
  - encryption
  - support
  - survey_client
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",  
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "forceSSLforSubdomains": false,
        "theme": "",
        "maintenance": false,
        "loglevel": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": false,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud.log",
        "appstoreenabled": true,
        "check_for_working_htaccess": true,
        "versions_retention_obligation": "auto, 2",
        "updater.release.channel": "stable",
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "twofactor_enforced": "false",
        "twofactor_enforced_excluded_groups": [],
        "mysql.utf8mb4": true,
        "mail_smtpsecure": "tls",
        "simpleSignUpLink.shown": false,
        "app_install_overwrite": [
            "bookmarks_fulltextsearch"
        ]
    }
}

**Comment by georgehrke** [comment]
@urmel1960 Is there any chance you can export that swisscom event and share the ics with us? Feel free to remove any personal data from it.

**Comment by georgehrke** [comment]
![37BFC5EC-C9BE-44E8-B170-E24105EAC615](https://user-images.githubusercontent.com/1250540/74730447-6b52d380-5246-11ea-9ce3-b235b74b55fe.png)

Shows the correct time for me. The only problem i see here is that it doesn't have a minimum height.

**Comment by urmel1960** [comment]
If you would look at my screenshot carefully you could see the problem. The example - marked in red and with circles shows the beginning at 8:05 and the end at 8:05 on the same day. In the graph on the calendar it is 08:05 to 09:05.

**Comment by urmel1960** [comment]
sorry closed by mistake - reopened

**Comment by urmel1960** [comment]
Hi there

Here is an example downloaded from nextcloud- not swisscom but o2 :-) - 
same issue

**Comment by urmel1960** [comment]
maybe the attachmet got lost - here it is again - ics not supported - sent zip
[9ed0670b-3b79-4cd0-a3d4-3c103ba59a1c.zip](https://github.com/nextcloud/calendar/files/4218981/9ed0670b-3b79-4cd0-a3d4-3c103ba59a1c.zip)
