### ISSUE TITLE
Highlight the event title in the simple editor, just like in the full editor

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/calendar#1965]
**Is your feature request related to a problem? Please describe.**
In the full calendar event box, the event title is highlighted automatically when creating a new item. In the simple event editor, this is not the case. You have to click the event title first.

**Describe the solution you'd like**
Highlighting the event title in the simple editor, so that you can immediately start typing when after having defined a time window in the week view.

**Comment by georgehrke** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/1930
