### ISSUE TITLE
sync shared calendars

### ISSUE THREAD

**Issue by livier** [nextcloud/calendar#1968]
**Is your feature request related to a problem? Please describe.**
I use a personal and I am part off another communautary nextcloud. 
I enjoy to see on my personal cloud the calenda(s) i have or the shares I can see on communautary one. 
Unfortunately, on the web UI  there is a big delay in the sync, an often I canot see the last changes fron communautary's nextcloud to mine. 
I checked that on android, with DAVx5 I get the update (mush sooner, or when I ask for sync. 

**Describe the solution you'd like**
- A bottom in each calendar imported for sync would be welcome

**Describe alternatives you've considered**
- A sync off all calendars on each cron job, would be nice too

**Comment by georgehrke** [comment]
This was fixed with https://github.com/nextcloud/server/pull/19215
