### ISSUE TITLE
Show shared Calendar in Web-Gui independently of the group-setting in the calendar app

### ISSUE THREAD

**Issue by demlak** [nextcloud/calendar#1971]
Scenario:
Only Group (A) is allowed to use Calendar app.

Group (A) creates calendar "newsharedcal" and shares it with Group (B) (which is not in the list of allowed groups to use calendar-app)

User from group (B) is able to use caldav link like:
https://server.tld/remote.php/dav/calendars/user_from_group(B)/newsharedcal_shared_by_user_from_group(A)/

But user_from_group(B) is not able to see calendar-app in the web-gui.

----------

Feature Request:
if a user has access to a calendar, the user should also see those calendars in the web-gui. -> independently of the group-setting in the calendar app.

would be nice to use the app as user_from_group(B) with settings/rights given by the shared calendar.. and nothing else

**Comment by georgehrke** [comment]
This is the excepted behaviour.

CalDAV is handled by the DAV app, for which you can neither set group-restrictions nor disable it.
The calendar app is simply a CalDAV-client running in your browser. If you disable it for a certain group, they can't access it.

**Comment by demlak** [comment]
excepted or expected?
You don't see a discrepancy between access via CalDAV is allowed but the app isn't shown?

**Comment by georgehrke** [comment]
> You don't see a discrepancy between access via CalDAV is allowed but the app isn't shown?

No, the app is just a CalDAV client. We also clearly communicate that to the admin.
The description in the app-management reads: "The Calendar app is a user interface for Nextcloud's CalDAV server. ..."

Meaning the data is stored in the CalDAV server and the calendar app is just one way of accessing it.

**Comment by demlak** [comment]
ok.. now i understand.. my fault
