### ISSUE TITLE
Change visibility of a calender proppatch call

### ISSUE THREAD

**Issue by Tazzios** [nextcloud/calendar#1976]
I use Nextcloud 18 on an shared webhosting where proppatch seems to be disabled.
When i want to change the visibility of a calender i get the "AH01623: client method denied by server configuration: 'PROPPATCH'" error.

I know it is mostly my own problem but :
1. Is a proppatch call really necessary when chancing only the visibility of a calendar / can this be changed? 
2. Is there a workaround so that i can set a new shared calendar visible to everyone / where is the settings saved for each user?

**Comment by tcitworld** [comment]
`PROPPATCH` is an WebDAV (including CalDAV) HTTP method to change properties on a node (such as a calendar or folder). Nextcloud uses this all over the place internally and externally, unfortunately you can't do much when your hoster has disabled it.

However there's no reason your host would disable this method, and you should definitely contact them about this issue.

**Comment by Tazzios** [comment]
Thanks for your reaction.
I also contacted the webhosting of course but there first reaction is that they won`t make such changes because it would impact every hosting. I will try to convince them to adjust it.
I only get that error in the errorlog when i try to change visibility. All other things works fine (file,contacts,decks, davx sync) That`s why i also would be happy workaround in an configfile or database like stated in 2. :)

**Comment by tcitworld** [comment]
> All other things works fine (file,contacts,decks, davx sync)

I can guarantee you'll encounter issues at some point.

> calendar visible to everyone

Enabling your own calendar is toggling a value in `oc_properties` with `propertypath='calendars/%user%/personal'` and `propertyname='{http://owncloud.org/ns}calendar-enabled'`.

Sharing a calendar to users is more complicated, requires inserting data into `oc_dav_shares`.

**Comment by Tazzios** [comment]
The calendar was already shared so adding a record for each user in 'oc_properties' did indeed the trick. Thanks for your time! I know that opening this issue wasn't 100% correct but it could help others.

At the webhosting they will discuss if the will enable the feature.

```
INSERT INTO `ownc_properties` ( `userid`, `propertypath`, `propertyname`, `propertyvalue`) VALUES
( '**USER**', 'calendars/**USER**/**Agendaname**_shared_by_**shareUSER**', '{http://owncloud.org/ns}calendar-enabled', '1');
```
