### ISSUE TITLE
Improve multiple "all-day" events display

### ISSUE THREAD

**Issue by jpbraun** [nextcloud/calendar#1977]
Please implement an option to show all "All Day" events (similar to Calendar 1.x)

**Comment by tcitworld** [comment]
All-day events are shown in month view just like other events. On week and day view, they are displayed on top of the interface (in a « All day » line). Where are you missing them ?

**Comment by jpbraun** [comment]
In the week view only the first all day events are shown
![2020-02-10_112705](https://user-images.githubusercontent.com/31374152/74142069-6c598480-4bf8-11ea-8c45-645f7705bbad.gif)

**Comment by tcitworld** [comment]
Sorry, brain missed the double `all` in "all all day events".

@georgehrke Also had some feedback where this is limiting.

**Comment by georgehrke** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/1889
