### ISSUE TITLE
Notifications settings

### ISSUE THREAD

**Issue by intervisionlord** [nextcloud/calendar#1978]
### Steps to reproduce
1. Create an event
2. Edit notifications
3. You coud notice that now it is not possible to create custom notification (e.g. at 15 min. before event ends)

### Expected behaviour
Ability to create custom notifications with various parameters

### Calendar app
**Calendar app version:** 2.0.1

**CalDAV-clients used:** WEB (nextcloud frontend)

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache+Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 17.0.3

**Updated from an older installed version or fresh install:** Updated

**List of activated apps:**

```
Enabled:
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - announcementcenter: 3.6.1
  - apporder: 0.9.0
  - audioplayer: 2.9.0
  - bookmarks: 2.3.4
  - breezedark: 17.0.7
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - checksum: 0.4.4
  - cloud_federation_api: 1.0.0
  - contacts: 3.1.8
  - dav: 1.13.0
  - extract: 1.2.3
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_retention: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - groupfolders: 5.0.5
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - metadata: 0.11.1
  - notes: 3.1.4
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - passwords: 2020.2.1
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - qownnotesapi: 20.1.0
  - recommendations: 0.5.0
  - sharerenamer: 2.7.3
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "twrc.ru"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.3.1",
        "overwrite.cli.url": "https:\/\/twrc.ru",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "calendar"
        ],
        "mysql.utf8mb4": true,
        "simpleSignUpLink.shown": false
    }
}
```

**Comment by tcitworld** [comment]
You can edit a notification by using the 3-dot menu next to a reminder and "Edit time".

**Comment by intervisionlord** [comment]
> You can edit a notification by using the 3-dot menu next to a reminder and "Edit time".

Yes, but in previous version i was able to define "before event start" notification and "before event end" notification.

Now i can't do it.
via edit menu i can change only time before or after event start (but not before or after event end)
(sry for my english)

**Comment by fahrstuhl** [comment]
I'm missing this functionality, too, it was present in previous versions. Setting reminders to after an event started is not straightforward right now. You have to set a reminder, click on "edit time", then set it to "on date" and set the time. Setting the reminder to "on date" first hides the "edit time" button. [Here's a short screen recording showing the problem](https://gfycat.com/densecanineflamingo).

**Comment by georgehrke** [comment]
That was removed on purpose in the process of simplifying a cluttered / unusable UI. Most other calendar applications like iCloud / macOS Calendar / Google calendar are not offering this either.

On top of that, support for alarms with a trigger relative the to events end is very bad, leading to wrong notifications on many devices.

Hence this is a no-fix for me.

Workaround is to simply set an absolute reminder instead.

**Comment by fahrstuhl** [comment]
Okay, but [the "Edit Time" button vanishing when setting an absolute date](https://gfycat.com/densecanineflamingo) is a separate bug, correct?

**Comment by intervisionlord** [comment]
Ehhh... what?
If i have an event at work for example some planned activity at datacenter i need to know when it started and i need to be notified when this works going to end.

And if i have several employers with different work schedule i need that they would be notifyed when works ends due to enable their services.

And this feature was disable because other companies are not offerinf this? sounds redicoulus... Great... let's make software as others do. No any other new and cool ideas...

**Comment by georgehrke** [comment]
> Okay, but the "Edit Time" button vanishing when setting an absolute date is a separate bug, correct?

Yes. Can you please open a dedicated bug report for that?

**Comment by fahrstuhl** [comment]
> > Okay, but the "Edit Time" button vanishing when setting an absolute date is a separate bug, correct?
> 
> Yes. Can you please open a dedicated bug report for that?

Done: #2001
