### ISSUE TITLE
Auto-import of ICS invitations from mail

### ISSUE THREAD

**Issue by ulysse26** [nextcloud/calendar#1981]
**Describe the solution you'd like**
Could ICS attachments received in Mail (event invitations) be directly imported in calendar ?
It does improve integration with external closed calendar, which always allow sending ICS invitations.

This solution includes Nextcloud/Calendar and Nextcloud/Mail .

**Additional context**
see [(https://github.com/nextcloud/mail/issues/2026)]

**Comment by georgehrke** [comment]
This issue is not related to the calendar app. The only app requiring changes here is the Mail app, where you already created an issue.
