### ISSUE TITLE
Allow repeat by hours

### ISSUE THREAD

**Issue by StyXman** [nextcloud/calendar#1988]
I try to setup a calendar entry that repeat every 12h, but the minimal repeat frequency is 1 day. I know it's unusual from a business oriented point of view, but I just want to share my kid's medicine doses and share it with my wife.

**Comment by georgehrke** [comment]
While [RFC5545](https://tools.ietf.org/html/rfc5545) technically allows repeating events hourly and by hour, I feel like this is a very specific use case. Too specific to clutter an already complex recurring interface with more inputs.

Furthermore, support for `SECONDLY`, `MINUTELY`, `HOURLY`, etc. is rather bad in most clients.

As a workaround, just create two separate events, one at 6am, the other at 6pm e.g.
