### ISSUE TITLE
Bad link & update question.

### ISSUE THREAD

**Issue by cstackpole** [nextcloud/calendar#2]
Greetings,

Two things:
1) The "ask for support" in the README still points to owncloud forums, not https://help.nextcloud.com/ .

2) If I am already running nextcloud 10 with the Calendar 1.3.3 from my time under owncloud, can I expect to just see an "upgrade app" appear for 1.4.0 or will I need to do something to ensure I am using this new nextcloud version of the calendar?

Thanks!

**Comment by georgehrke** [comment]
> 1) The "ask for support" in the README still points to owncloud forums, 

That was fixed :)

> 2) If I am already running nextcloud 10 with the Calendar 1.3.3 from my time under owncloud, can I expect to just see an "upgrade app" appear for 1.4.0 or will I need to do something to ensure I am using this new nextcloud version of the calendar?

It will just offer you to update. We have just not released 1.4.0 yet :)
