### ISSUE TITLE
[Enhancment] Accept calendar invitation directly in the invitation email

### ISSUE THREAD

**Issue by enoch85** [nextcloud/calendar#200]
In [this issue](https://github.com/nextcloud/server/issues/2071) I asked for better design for the emails being sent when inviting anyone to a event. This request is about the possibility to accept the invitation directly in the email, just like you can do with Google Calendar.

Right now you are presented with this (which is pretty nasty):

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 3.5.0//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Africa/Lagos
X-LIC-LOCATION:Africa/Lagos
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
TZNAME:WAT
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20161125T140909
DTSTAMP:20161125T140909
LAST-MODIFIED:20161125T140909
UID:1J4UQR666RZKWYABID5AF0QKT92XM3TB6JP2D8K0NIQ2VPZM2T9
SUMMARY:Julfest jobbet
LOCATION:Kontoret
CLASS:PUBLIC
STATUS:CONFIRMED
ORGANIZER;CN=Daniel Hansson:MAILTO:daniel@techandme.se
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CUTYPE=INDIVIDUAL;X-NC-
 GROUP-ID=0:MAILTO:daniel.hansson@orestad-linux.se
DTSTART;TZID=Africa/Lagos:20161220T160000
DTEND;TZID=Africa/Lagos:20161220T170000
END:VEVENT
END:VCALENDAR

``` 

I think it's a must have to be able to accept the invitation directly in the email, how can we compete with e.g. Google otherwise?

**Comment by enoch85** [comment]
cc @Espina2 @eppfel @georgehrke

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by enoch85** [comment]
@georgehrke Right, forgot about that. :)
