### ISSUE TITLE
WebCAL (iCAl) subscription not working

### ISSUE THREAD

**Issue by DavidDohmen** [nextcloud/calendar#2005]
### Steps to reproduce
1. Open calendar app and add new calendar
2. Select "new subscription from link" and paste a WebCAL link like this one: https://www.werk1.com/events/?ical=1

### Expected behaviour
The calendar subscription should be visible (It is visible in Google Calendar).

### Actual behaviour
The calendar events are not being displayed.

### Calendar app
2.0.1

### Client configuration
It was tested with Chrome 80.0.3987.106 and Firefox 72.0.2 -> Same faulty behaviour.
Windows 10 and Ubuntu 19.10 -> Same faulty behaviour

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18.04

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0.3)
7.0.3

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
18.0.1 (happened also on 18.0.1)

**Updated from an older installed version or fresh install:**
Updated (used to work in the previous versions)

**List of activated apps:**

  - accessibility: 1.4.0
  - activity: 2.11.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.2
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.4
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - logreader
  - nextcloud_announcements
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.ocell-analytics.com",
            "austausch.ocell-analytics.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.1.3",
        "overwrite.cli.url": "https:\/\/cloud.ocell-analytics.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "memcache.distributed": "\\OC\\Memcache\\APCu",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable"
    }
}

#### Web server error log (e.g. /var/log/apache)

[Tue Feb 18 06:25:02.904497 2020] [mpm_prefork:notice] [pid 937] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Feb 18 06:25:02.904536 2020] [core:notice] [pid 937] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 18 09:02:02.406958 2020] [access_compat:error] [pid 7167] [client 82.135.103.92:49901] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 10:00:25.561811 2020] [access_compat:error] [pid 11114] [client 82.135.103.92:63916] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 10:14:05.299944 2020] [php7:warn] [pid 12604] [client 82.135.103.92:65308] PHP Warning:  copy(/var/www/html/config/config.php.bkp): failed to open stream: Permission denied in /var/www$
[Tue Feb 18 10:18:55.675738 2020] [mpm_prefork:notice] [pid 937] AH00169: caught SIGTERM, shutting down
[Tue Feb 18 10:20:34.307790 2020] [mpm_prefork:notice] [pid 926] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Feb 18 10:20:34.319901 2020] [core:notice] [pid 926] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 18 10:21:32.849655 2020] [php7:warn] [pid 1004] [client 82.135.103.92:65531] PHP Warning:  copy(/var/www/html/config/config.php.bkp): failed to open stream: Permission denied in /var/www/$
[Tue Feb 18 10:21:40.702364 2020] [php7:warn] [pid 1211] [client 82.135.103.92:65533] PHP Warning:  copy(/var/www/html/config/config.php.bkp): failed to open stream: Permission denied in /var/www/$
[Tue Feb 18 14:24:57.857572 2020] [access_compat:error] [pid 7962] [client 82.135.103.92:49691] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:25:17.501153 2020] [access_compat:error] [pid 7962] [client 82.135.103.92:53429] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:25:26.963881 2020] [access_compat:error] [pid 7962] [client 82.135.103.92:58382] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:25:29.105719 2020] [access_compat:error] [pid 8032] [client 82.135.103.92:49705] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:25:45.973412 2020] [access_compat:error] [pid 4752] [client 82.135.103.92:53431] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:25:57.348571 2020] [access_compat:error] [pid 998] [client 82.135.103.92:58386] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:26:01.172802 2020] [access_compat:error] [pid 4752] [client 82.135.103.92:49711] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:26:02.477885 2020] [access_compat:error] [pid 995] [client 82.135.103.92:49713] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:26:17.952545 2020] [access_compat:error] [pid 7962] [client 82.135.103.92:53433] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:26:25.164991 2020] [access_compat:error] [pid 8070] [client 82.135.103.92:53435] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:26:29.384248 2020] [access_compat:error] [pid 998] [client 82.135.103.92:58393] AH01797: client denied by server configuration: /var/www/html/config
[Tue Feb 18 14:26:56.504389 2020] [access_compat:error] [pid 7962] [client 82.135.103.92:58397] AH01797: client denied by server configuration: /var/www/html/config

#### Log file (data/nextcloud.log)
 
It's empty

#### Browser log

Not available

**Comment by georgehrke** [comment]
Please read thru https://github.com/nextcloud/calendar/issues/1895 and check all the questions asked there.

Afterwards, please leave a comment in here whether that's solved your issue or not.

**Comment by DavidDohmen** [comment]
Here's what happended:

- After switching from AJAX to CRON in the administrator settings nothing changed at first.

- Severlal minutes later I reloaded and the interface showed me, that CRON couldn't run and that something is not configured properly... 

- I forced cron with `sudo -u www-data php -f cron.php` which took a couple of minutes. Afterward the calendar subscription was visible.

- I deleted and readded the calendar and it was invisible again. After 10 minutes the admin page shows me, that CRON has problems again.

**Comment by DavidDohmen** [comment]
I followed the instruction here: https://docs.nextcloud.com/server/18/admin_manual/configuration_server/background_jobs_configuration.html

and added this line `*/5  *  *  *  * php -f /var/www/nextcloud/cron.php` to crontab.

As expected 5 minutes later, I could see the calendar entries again.

The problem is solved for my now! Thanks for pointing me in the right direction!
