### ISSUE TITLE
Unable to enter date in birthday. Only picking up possible (but takes a long time)

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/calendar#2006]
Dear devs,

I think there's already an issue, but I cannot find it.
When I want to add a birthday to a contact, I only can select it with the date-picker.
I'm unable to type in the date directly. This would be much faster.
Can you help there??

Thanks, Tom

**Comment by georgehrke** [comment]
> When I want to add a birthday to a contact, I only can select it with the date-picker.

This is the calendar repo. Please open an issue in the repository of the contacts app.

**Comment by georgehrke** [comment]
can't spot an existing related issue: https://github.com/nextcloud/contacts/issues?utf8=✓&q=is%3Aissue+is%3Aopen+Birthday

**Comment by kangaroo72** [comment]
Damn. My fault, sorry :-)
