### ISSUE TITLE
UI Tweak: "Calendar" setting in Event Editor not prominent enough

### ISSUE THREAD

**Issue by simonspa** [nextcloud/calendar#2007]
This is a "bug" report on a possible design tweak concerning the event editor. In daily use I find it very inconvenient that the target calendar has been "downgraded" to a setting in the first tab of the event editor side panel. I see this as one of the most important settings, maybe even more important than the date and time.

It happened several times to me and other users that their new calendar entries accidentally ended up in the wrong (potentially a publicly shared!) calendar just because the item is not visible enough.

In the old pre-v2.0 interface, the calendar was one of the most prominent items of the edit panel.

**Comment by georgehrke** [comment]
Are you referring to the sidebar editor?

![02C260BD-18D7-4CA5-B4D1-62C50F415B33](https://user-images.githubusercontent.com/1250540/75041353-b37b2b80-54bc-11ea-8882-98e2d3a713f3.png)

While implementing it, we tried putting it directly below the time picker, but that took up too much space, while editing alarms, attendees, and the recurring information.

Furthermore, the details tab is the default one open. So the selected calendar is always among the information you see first.

(On top of that, even the illustration gives you a hint in what calendar the event is, because it's themed in the calendar's color).

**Comment by georgehrke** [comment]
👎 from my side.

Would be happy to hear other opinions @tcitworld @nextcloud/designers

**Comment by simonspa** [comment]
Hi @georgehrke 

yes, that's exactly the editor I was referring to. I do appreciate the images because they are pretty, even though they are not really helping in productivity (and take up space). Now that you say it I have noticed the theming using the calendar color - it wasn't apparent to me before.

I can understand that you need to economize on the available space - I still think this setting is too crucial to be "downgraded" to display an icon instead (that at least for me is the "meeting" icon in 95% of the cases and thus does not provide additional information at all).

**Comment by rkaraba** [comment]
For users in our company images are only distraction. They are confused now and often put entries  to wrong calendars. Please put the calendar settings back under the title.

**Comment by simonspa** [comment]
Maybe the images could be made optional? The great Passwords app does it that way: there is a setting with which the user can control whether images (in that case: website screenshots) are shown in the sidebar or not.

Apart from that I don't seem to be the only user to select the wrong calendar with the new layout. I dug a bit more and found out why: I work my way from top to bottom:

* Set event title
* Set event date/duration (I really hope #1576 gets fixed soon - it's so annoying to have to find and click the current date just for adjusting time)
* Next from the top are the tabs and since I often need a reminder, I select that tab
* I configure the reminder
* Click save event - done.

In that "flow" I don't even pass by the calendar setting.

**Comment by rkaraba** [comment]
Is there any progress on this isue?

**Comment by jancborchardt** [comment]
I agree that the calendar should be closer to the event title, especially seeing how many issues appear.

Since the images on the top are using the color from the calendar name, we could either combine that somehow and put the calendar dropdown above the title overlapping the image – or we can put it directly below.

**Comment by simonspa** [comment]
From my side both options would be viable and do the job I guess. So whatever you think looks better... :)

**Comment by rkaraba** [comment]
The calendar should be closer to title also in simplified editor

![obrázok](https://user-images.githubusercontent.com/20682075/82741891-7cd0dd80-9d57-11ea-9958-278d3705088b.png)

i liked the old one 

![obrázok](https://user-images.githubusercontent.com/20682075/82741917-dc2eed80-9d57-11ea-8f56-14b25c8d6fe9.png)

**Comment by georgehrke** [comment]
@jancborchardt Would you mind coming up with some mockups so we can decide what way to go? :)

**Comment by jancborchardt** [comment]
We can just put the calendar selector (without icon on left) below the event title and that's it. :)

**Comment by rkaraba** [comment]
Yes. Simple quick and elegant

**Comment by georgehrke** [comment]
@jancborchardt Should we apply the same change to the popover for consistency's sake?

**Comment by georgehrke** [comment]
@jancborchardt Please check out https://github.com/nextcloud/calendar/pull/2284 :)
