### ISSUE TITLE
Incorrect display of contributors as [object Object] in apps page after updating to 1.4.1

### ISSUE THREAD

**Issue by anmith** [nextcloud/calendar#201]
### Steps to reproduce
1. Using Nextcloud 10.0.1
2. Using Calendar 1.4.0
3. Update to Calendar 1.4.1

### Expected behaviour
Calendar should show names of crontributors in apps page

### Actual behaviour
Calendar shows list of [object Object] as contributors in apps page

### Server configuration
**Server version:** (see your admin page)
10.0.1 (stable)
**Calendar version:** (see the apps page)
1.4.1
**Updated from an older installed version or fresh install:**
Updated from 1.4.0
![140](https://cloud.githubusercontent.com/assets/3750050/20626710/c18783ea-b31b-11e6-9853-7db16125b6c8.PNG)
![141](https://cloud.githubusercontent.com/assets/3750050/20626715/c4f47498-b31b-11e6-86c1-37702d42a571.PNG)

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/199
