### ISSUE TITLE
Calendar app cannot add repeats to an event after the event is created

### ISSUE THREAD

**Issue by deanforrest** [nextcloud/calendar#2013]
After an event is created and a repeat is added to it through the web interface, the repeat will not appear in the calendar, and the repeat section of the event will no longer be available. However, running through the steps below using the iOS calendar through CalDAV works perfectly.

### Steps to reproduce
1. Create an event on the calendar, click "save"
2. Click on the previously created event, click "more", click on the "Repeat" tab and add a repeat for any range of time. Adding an "End repeat" option does not affect the resulting outcome.

### Expected behaviour
The event should add multiple occurrences on the calendar based on the repeat selected in the "more" section.

### Actual behaviour
Occurrences are not added to the specified calendar, and if the user navigates to the "Repeat" section of the event, "This event is the recurrence-exception of a recurrence-set. You can not add a recurrence-rule to it." will appear instead of the repeat options. Also, the simplified editor will not show the "Update this occurrence" or "Update this and all future" options in the simplified editor.

If the user follows steps 1 through 2 again but adds a time range for the given day (e.g. 4 PM to 7 PM), it cannot be deleted through the web interface, only through the calendar app on an iPhone connected to Nextcloud through CalDAV.

### Calendar app
**Calendar app version:** 2.0.1

**CalDAV-clients used:** CalDAV via iOS

### Client configuration
**Browser:** Firefox 74.04b & Google Chrome 79.0.3945.130

**Operating system:** Windows 10

### Server configuration

**Operating system**: Ubuntu Server 18.04.3

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2.24

**Nextcloud Version:** 18.0.0

**Comment by justin-sleep** [comment]
Here's an example of an event Calendar generated that produces this message for me:
```
BEGIN:VCALENDAR
PRODID:-//IDN nextcloud.com//Calendar app 2.0.1//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VEVENT
CREATED:20200224T033714Z
DTSTAMP:20200224T033714Z
LAST-MODIFIED:20200224T033714Z
SEQUENCE:1
UID:d287c5f9-e8f2-4323-96c7-9703a9a59b64
DTSTART;VALUE=DATE:20200106
DTEND;VALUE=DATE:20200107
SUMMARY:Test Event
RECURRENCE-ID;VALUE=DATE:20200106
END:VEVENT
END:VCALENDAR
```

If I try to delete it, the side panel hangs on the loading spinner, and I get `TypeError: "h.indexOf is not a function"` in the browser console; this might be unrelated, as Calendar deletes the event without a problem in my dev enviroment.

**Comment by deanforrest** [comment]
> If I try to delete it, the side panel hangs on the loading spinner, and I get `TypeError: "h.indexOf is not a function"` in the browser console; this might be unrelated, as Calendar deletes the event without a problem in my dev enviroment.

I do suspect it's an issue within the browser since I get the same TypeError in the console, but the DAV implementation for other devices works without a hitch. Could it be anything with the ical.js library that's currently used?

**Comment by georgehrke** [comment]
I don't think it's ical.js related, will look into it later today.

**Comment by georgehrke** [comment]
There is a work-in-progress Pull-request in https://github.com/nextcloud/calendar/pull/2026
