### ISSUE TITLE
calendar broken on master

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#202]
I just checked out the latest calendar on the latest server (which will become Nextcloud 11)

server state: 47646794b9426f40c12719d78c5a92a71570b4b2
calendar state: a40c8457bbe09007b60cc368f81939ce5059b434

This is how it looks like if I open the calendar:

![calendar](https://cloud.githubusercontent.com/assets/1589737/20628783/5a5e84a4-b328-11e6-8cd2-1f68dc5e7a3a.png)

cc @georgehrke

**Comment by tcitworld** [comment]
If you install from git, you need to run `make` before using it.
