### ISSUE TITLE
Daily agenda via email

### ISSUE THREAD

**Issue by brylie** [nextcloud/calendar#2021]
I have difficulty remembering appointments, so rely heavily on Nextcloud calendar to remind me of appointments across devices. Despite spending early reminder notifications, I still miss important events.

I am in the habit of checking my email early in the morning. It would be really helpful to receive a daily agenda via email in the morning so I could plan my day better. There is a daily agenda email feature in Google Calendar and Microsoft Outlook Online, but I would really prefer to use Nextcloud :-)

**Comment by georgehrke** [comment]
Feel free to post this suggestion in https://help.nextcloud.com/c/feature/app-ideas, but this is not something i would like to see in the main calendar app.

Nextcloud provides a simple PHP API for accessing calendar data, so it should not be too difficult to implement.

**Comment by brylie** [comment]
OK, that was swift.

**Comment by brylie** [comment]
Related discussion thread:
https://help.nextcloud.com/t/daily-calendar-agenda-via-email/72142
