### ISSUE TITLE
Bad "calendar.svg" link path

### ISSUE THREAD

**Issue by john4sp** [nextcloud/calendar#203]
### Steps to reproduce (Calendar Version 1.4.0 and 1.4.1)
# I have setup my ownCloud (9.1.2) with this Settings in the config.php:

'apps_paths' =>
 array (
  0 =>
   array (
    'path' => '/var/www/owncloud/apps',
    'url' => '/apps',
    'writable' => false,
   ),
  1 =>
   array (
    'path' => '/var/www/owncloud/apps-data',
    'url' => '/apps-data',
    'writable' => true,
   ),
  ),

# The Apache2 Config contains:

 Alias /owncloud /var/www/owncloud/
 <Directory /var/www/owncloud/>
 ...
 </Directory>

# So my ownCloud Link is like, to see the Loginpage:

https://<my-domain.com>/owncloud

# The Issue is that from the Calendar App, the calendar.svg path is not right and not get loaded.
# My Apache Log shows this:

"GET /apps-data/calendar/img/calendar.svg HTTP/1.1" 404

# But it must be "/owncloud/apps-data/calendar/img/calendar.svg".
# The App-Path works for all other Links/Apps...
# This is the only Object, that is not right.

# I must setup a RewriteRule in Apache to "fix" it:

RewriteRule ^/apps-data/calendar/img/calendar.svg$ /owncloud/apps-data/calendar/img/calendar.svg [R]

**Comment by georgehrke** [comment]
Is this the only app in apps-data?

**Comment by georgehrke** [comment]
Looks right from our side
https://github.com/nextcloud/calendar/blob/master/appinfo/application.php#L84L85

Seems to be a bug in ownCloud

**Comment by john4sp** [comment]
No, there are calendar, contacts, tasks and notes.

**Comment by georgehrke** [comment]
Contact generates the link just like the calendar:
https://github.com/owncloud/contacts/blob/master/appinfo/app.php#L35

**Comment by georgehrke** [comment]
please report in the own cloud core repo

**Comment by john4sp** [comment]
the app contacts are working...

**Comment by georgehrke** [comment]
Yes, we are generating this link just like the contacts app. => no error on our side
=> some error in this magic code:
https://github.com/owncloud/core/blob/master/lib/private/URLGenerator.php#L165

Do you have a folder called calendar in `/var/www/`?

**Comment by john4sp** [comment]
My owncloud folder is in /var/www/owncloud and my owncloud-data folder is in /var/owncloud.

**Comment by georgehrke** [comment]
Yes ...
but still, is there a folder calendar in `/var/www/`?

**Comment by georgehrke** [comment]
and do you use a theme?

**Comment by john4sp** [comment]
oh sorry, no ;-)

**Comment by john4sp** [comment]
no, i am not use a theme

**Comment by georgehrke** [comment]
but still, I see absolutely no issue the calendar side here.
Please report this in the own cloud core repo.

**Comment by john4sp** [comment]
okay, thx
