### ISSUE TITLE
Calendar invites: Sender is server instance, not user email address

### ISSUE THREAD

**Issue by gqgunhed** [nextcloud/calendar#204]
### Steps to reproduce
1. Create calendar entry and add attendees with email addresses
2. Submit/Save entry to calendar, invites are being sent to attendees (as expected BUT ...) 
3. Emails are always sent with "from: nextcloud@internal.domain", not from "user@internal.domain"

### Expected behaviour
Invites should be sent using the email address of the user (provided by user profile) creating the calendar entry. Using a central email makes responding, filtering, etc. impossible.
(internal domain is being converted when transmitted to the outside world, so no worries about that)

### Actual behaviour
All invites are being sent with "from: nextcloud@internal.domain" which is the central notification email set via Administration -> Additional Settings -> Email -> Using SMTP

### Server configuration
**Operating system**: FreeBSD 10.3

**Web server:** nginx-1.10.1_1,2

**Database:** mysql 5.6.33

**PHP version:** PHP5.6.27

**Server version:** (see your admin page) 10.0.1

**Calendar version:** (see the apps page) 1.4.1

**Updated from an older installed version or fresh install:** Update

**Signing status (ownCloud/Nextcloud 9.0 and above):** ?

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```
root@nextcloud:/usr/local/www/nextcloud # su -m www -c "php occ app:list"
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:                                                                                                               
  - activity: 2.3.2                                                                                                    
  - admin_audit: 1.0.0                                                                                                 
  - audioplayer: 1.3.1                                                                                                 
  - bookmarks: 0.9.0                                                                                                   
  - calendar: true                                                                                                     
  - comments: 1.0.0                                                                                                    
  - contacts: 1.5.2                                                                                                    
  - dav: 1.0.1                                                                                                         
  - direct_menu: 0.9.3                                                                                                 
  - documents: 0.13.1                                                                                                  
  - federatedfilesharing: 1.0.1                                                                                        
  - federation: 1.0.1                                                                                                  
  - files: 1.5.2                                                                                                       
  - files_external: 1.0.2                                                                                              
  - files_pdfviewer: 0.8.1                                                                                             
  - files_sharing: 1.0.0                                                                                               
  - files_texteditor: 2.1                                                                                              
  - files_trashbin: 1.0.0                                                                                              
  - files_versions: 1.3.0                                                                                              
  - files_videoplayer: 0.9.8                                                                                           
  - firstrunwizard: 1.1                                                                                                
  - gallery: 15.0.0                                                                                                    
  - mail: 0.6.0                                                                                                        
  - news: 9.0.4                                                                                                        
  - notifications: 0.3.0                                                                                               
  - password_policy: 1.0.0                                                                                             
  - provisioning_api: 1.0.0                                                                                            
  - serverinfo: 1.1.1                                                                                                  
  - survey_client: 0.1.5                                                                                               
  - systemtags: 1.0.2                                                                                                  
  - templateeditor: 0.1                                                                                                
  - theming: 1.0.1                                                                                                     
  - updatenotification: 1.0.1                                                                                          
  - workflowengine: 1.0.1                                                                                              
Disabled:                                                                                                              
  - encryption                                                                                                         
  - external                                                                                                           
  - files_accesscontrol                                                                                                
  - files_automatedtagging                                                                                             
  - files_retention                                                                                                    
  - ojsxc                                                                                                              
  - roundcube                                                                                                          
  - user_external                                                                                                      
  - user_ldap                                                                                                          
  - user_saml                                                                                                          

**The content of config/config.php:**

root@nextcloud:/usr/local/www/nextcloud # cat config/config.php  
```
<?php                                                            
$CONFIG = array (                                                
  'instanceid' => 'instanceid_here',                                
  'passwordsalt' => 'passwordsalt_here',            
  'secret' => 'secret_here',
  'trusted_domains' =>                                           
  array (                                                        
    0 => 'nextcloud.internal.domain,                             
  ),                                                             
  'datadirectory' => '/usr/local/www/nextcloud/data',                                
  'overwriteprotocol' => 'https',                                                    
  'overwrite.cli.url' => 'https://nextcloud..internal.domain',                         
  'dbtype' => 'mysql',                                                               
  'version' => '9.1.1.5',                                                            
  'dbname' => 'nextcloud',                                                           
  'dbhost' => 'db.internal.domain',                                                   
  'dbtableprefix' => 'oc_',                                                          
  'dbuser' => 'db_user_here',                                                           
  'dbpassword' => 'dbpassword_here',                                                    
  'logtimezone' => 'UTC',                                                            
  'installed' => true,                                                               
  'mail_smtpmode' => 'smtp',                                                         
  'mail_from_address' => 'nextcloud',                                                
  'mail_domain' => 'internal.domain',                                                 
  'mail_smtphost' => 'mail.internal.domain',                                          
  'mail_smtpport' => '25',                                                           
  'trashbin_retention_obligation' => 'auto, 30',                                     
  'versions_retention_obligation' => 'auto, 90',                                     
  'loglevel' => 2,                                                                   
  'maintenance' => false,                                                            
  'theme' => '',                                                                     
  'updater.secret' => 'updater_secret_hash',
  'appstoreenabled' => true,                                                         
  'appstoreurl' => 'https://apps.nextcloud.com/api/v0',                              
  'appstore.experimental.enabled' => false,                                          
  'apps_paths' =>                                                                    
  array (                                                                            
    0 =>                                                                             
    array (                                                                          
      'path' => '/usr/local/www/nextcloud/apps',                                     
      'url' => '/apps',                                                              
      'writable' => true,                                                            
    ),                                                                               
  ),                                                                                 
  'enabledPreviewProviders' =>                                                       
  array (                                                                            
    0 => 'OC\\Preview\\PNG',                                                         
    1 => 'OC\\Preview\\JPEG',                                                        
    2 => 'OC\\Preview\\GIF',                                                         
    3 => 'OC\\Preview\\BMP',                                                         
    4 => 'OC\\Preview\\XBitmap',                                                     
    5 => 'OC\\Preview\\MarkDown',                                                    
    6 => 'OC\\Preview\\MP3',                                                         
    7 => 'OC\\Preview\\TXT',                                                         
    8 => 'OC\\Preview\\Movie',                                                       
  ),                                                                                 
  'filelocking.enabled' => 'true',                                                   
  'memcache.locking' => '\\OC\\Memcache\\Redis',                                     
  'memcache.local' => '\\OC\\Memcache\\APCu',                                        
  'redis' =>                                                                         
  array (                                                                            
    'host' => '/var/run/redis/redis.sock',                                           
    'port' => 0,                                                                     
  ),                                                                                 
);  
```                                                                                 

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** Firefox/Chrome both current

**Operating system:** Linux/Windows/FreeBSD

**CalDAV-clients:** web-interface of nextcloud

**Comment by tcitworld** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by tcitworld** [comment]
By the way, sending emails on behalf of someone through another server leads to this kind of emails treated like spams (Yahoo for instance).

**Comment by gqgunhed** [comment]
Hi Thomas,
thanks for noting that but I am not sending emails on behalf of. I am using an in-house dovecot/postfix server with an internal DNS/email domain.
All emails travelling outside get their email addresses edited (before leaving towards the ISP) to become those official email addresses I use with my ISP. I don't want to use split-horizon DNS here.
So no on-behalf of - it's 1:1 mappings with internal (family) users and their official ISP based email-addresses.
I hope I didn't get you wrong with that :-)
Or are you referring to the additional email headers with more than one server increasing SpamAssassin rating?
This works flawlessly, so the setup should be fine.
Regards,
Gunther
