### ISSUE TITLE
Icon not shown after Upgrade from NC 17 to 18.0.1 in Firefox

### ISSUE THREAD

**Issue by tweinreich** [nextcloud/calendar#2049]
After upgrading from Nextcloud v17 to 18.0.1 the icon to switch between day / week / month view is missing in Firefox. Instead a grey, empty circle is shown.

![NC18-calendar-icon](https://user-images.githubusercontent.com/4059641/75828497-42851f00-5dac-11ea-9c90-e05886b0bdba.png)

Browser: Firefox 72.0.2
OS: Linux Mint 18.1 Serena

Chromium shows the icon.

**Comment by georgehrke** [comment]
Did you try cleaning your browser cache?

**Comment by tweinreich** [comment]
This is embarrassing but of course I did not do that and it was the reason. Thank you.
