### ISSUE TITLE
Blank screen when create new date by opened editor

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/calendar#2051]
### Steps to reproduce
1. Edit an existing calendar entry in the sidebar editor
2. Click in the grid view for a new event
3. Close the sidebar and you have a blank screen

### Expected behaviour
Sidebar closing and go back to the create event modal

### Actual behaviour
The sidebar and all other dates (complete grid view) gone away and you see an empty window

![image](https://user-images.githubusercontent.com/1473674/75988640-2f7c6700-5ef2-11ea-9b0d-e40a6bd8e2fa.png)

![image](https://user-images.githubusercontent.com/1473674/75988817-779b8980-5ef2-11ea-82ac-bf4dddaef7ce.png)

### Calendar app
2.0.2

### Client configuration
Chromium Edge

**Operating system:** (e.g. Arch Linux)
Windows 10 1909

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu

**Web server:** (e.g. Apache, Nginx,...)
Apache 2.4

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MySQL 5.7

**PHP version:** (e.g. 7.0.3)
7.4.2

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
18.0.1

**Updated from an older installed version or fresh install:**
updated from 15 > 16 > 17 > 18

**Comment by georgehrke** [comment]
@Dennis1993 Can you please provide javascript logs. Thx

**Comment by Dennis1993** [comment]
Of course! :)

![image](https://user-images.githubusercontent.com/1473674/75989016-c9dcaa80-5ef2-11ea-90a4-d3171fe9c076.png)

**Comment by tortuetorche** [comment]
Hi folks,

I've exactly the same bug, but with a different user interaction, see my screencast below (my starting page is `https://mynextcloud.com/apps/calendar/timeGridWeek/now`):

![Nextcloud Calendar 2 0 2 bug](https://user-images.githubusercontent.com/5038872/76016511-3ec4da00-5f1d-11ea-9098-704edae44c34.gif)

Have a good day,
Tortue Torche

**Comment by georgehrke** [comment]
This is an upstream issue in the fullcalendar library we are using:
https://github.com/fullcalendar/fullcalendar/issues/5266

I will try to see if the described workaround is working for the way we are using fullcalendar.

**Comment by tortuetorche** [comment]
Hi folks,

Any news on this issue? Because this is a major bug so I'll not update the `2.0.2` version on my Nextcloud production instance and I recommend everyone to do like me.
And if you already use the `2.0.2` version, I don't know if it's possible to downgrade the calendar application to the `2.0.1` version.

Have a good day,
Tortue Torche

**Comment by georgehrke** [comment]
The workaround described upstream does not work for our case.

@tortuetorche Downgrading is generally not supported, but if you just replace an already installed calendar `2.0.2` with the files of `2.0.1`, it will work. You might have to clear the browser cache.

> Because this is a major bug ...

Please note that:
1. The grid does not error every time you try to select a time-range, it requires certain steps of interaction before.
2. The "new event" button above the calendar-list is not affected by this and remains fully functional, no matter what interaction you did before.

**Comment by georgehrke** [comment]
Let's downgrade to fullcalendar 4.3.x for the meantime.

**Comment by tobox** [comment]
I am rolling out nextcloud in a company right now and need a solution to this problem. The project page says:

> Instead of setting everything up manually, you can just download the nightly builds or download a pre-release instead. Nightly builds are updated every 24 hours, and are pre-configured with all the needed dependencies.

The link to the nightly builds is dead. The link to the pre-releases just points to the releases, and the latest release has the bug. Downgrading is not supported. So what are my options to get something running without this annoying bug?

Regards

**Comment by georgehrke** [comment]
@tobox Did you actually read what i just wrote two comments above? 

https://github.com/nextcloud/calendar/issues/2051#issuecomment-598637807

>  Downgrading is generally not supported, but if you just replace an already installed calendar 2.0.2 with the files of 2.0.1, it will work. You might have to clear the browser cache.

**Comment by tobox** [comment]
Sorry, I forgot to mention that I tried that last week, but it failed. The login screen looked like this (translates into: App update required - start update):


![Screenshot_20200403_110218](https://user-images.githubusercontent.com/4719666/78343294-eaa02a80-759a-11ea-9924-22e06fb4cc89.png)

After a while (maybe some other user clicked on it) I saw only this (translates into "maintenance mode"):

![Screenshot_20200403_110330](https://user-images.githubusercontent.com/4719666/78343371-086d8f80-759b-11ea-82c8-eac51e7064bd.png)

Did I do something wrong? I just moved the nextcloud/apps/calendar outside of the nextcloud tree and unpacked 2.0.1 to that folder, and I also updated the file permissions.

**Comment by georgehrke** [comment]
@tobox Please ask support questions in our forum: https://help.nextcloud.com

**Comment by tobox** [comment]
I tried it 2 more times, and now it worked. This is what I did:

- disable the update notification app
- disable the calendar (2.0.2)
- shut down apache 
- replace calendar 2.0.2 with 2.0.1
- restart apache

I don't think all steps are neccessary, but at least it worked. The calendar app is now properly displayed in the list of installed apps (2.0.1 installed with update to 2.0.2 available).

**Comment by georgehrke** [comment]
Pull-request for downgrading fullcalendar: https://github.com/nextcloud/calendar/pull/2147
