### ISSUE TITLE
Feature request: Toggle switch for Full screen View / Calendar View

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/calendar#2052]
Hello,

on smaller screens (Note / Netbook) the weekly / monthly view gets cluttered  in cases of many entries they will be sometimes difficult to read ! Therefor a toggle switch full screen view / Calendar view would be most appropriate and helpful for navigation !

Regards, hitam4450

**Comment by tcitworld** [comment]
@hitam4450 Can you please fill the entire issue template like requested? And provide screenshots?

https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md

**Comment by hitam4450** [comment]
Hi, How can I provide screenshots, since the feature is NOT implemented ??????

It is NO BUG!

regards, hitam

**Comment by georgehrke** [comment]
I feel like you are trying to solve the same problem you already opened https://github.com/nextcloud/server/issues/15831 for.

**Comment by georgehrke** [comment]
Putting the webpage into fullscreen is a browser feature. I do not see the need to show a button for it:

![9C5E252B-6202-45B5-84B2-4F98D0D6689E-2](https://user-images.githubusercontent.com/1250540/76008645-4336c600-5f10-11ea-91be-53e18c96f461.jpg)

**Comment by georgehrke** [comment]
I'm closing this issue for two reasons:
- Putting the webpage in fullscreen is a browser feature, no need to add more buttons if the browser can already do it natively.
- nextcloud/server#15831 will be way more beneficial for smaller screens than putting the calendar in fullscreen, nextcloud/server#15831 is still open.

**Comment by georgehrke** [comment]
nextcloud/server#15831 is currently blocked by https://github.com/nextcloud/server/issues/16934, but we are working on a solution

**Comment by hitam4450** [comment]
@georgehrke 

Putting the webpage in full screen mode, still shows the left side pane and makes really no sense !

Thanks for reminding me that issue 15831 is stil WIP !
