### ISSUE TITLE
Option to hide calendar author/owner sidebar icons

### ISSUE THREAD

**Issue by BatmanAoD** [nextcloud/calendar#2056]
I'd like an option to hide the icons showing the owners of the calendars in the sidebar. In some cases, the owner is not relevant to the user. For instance, all the available calendars may have the same owner, or the calendars may belong to teams rather than individual owners. In these situations, the icons are more confusing than helpful.

![image](https://user-images.githubusercontent.com/2313807/76123533-0ae9c300-5fb6-11ea-9bbc-3eb46cd97270.png)

**Comment by georgehrke** [comment]
Feel free to use the Customs CSS app to hide the avatars, but we are not gonna add an option to hide it.
