### ISSUE TITLE
A way to disable calendar reminders through NextCloud

### ISSUE THREAD

**Issue by mikaelkolkinn** [nextcloud/calendar#2057]
**Is your feature request related to a problem? Please describe.**
After upgrading to the latest version of NextCloud and the latest Calendar app, I've been getting reminders for the calendar events through NextCloud. I already use other calendar programs and have them connected through CalDav. I don't need reminders from yet another app.

**Describe the solution you'd like**
A setting to toggle calendar reminders through the NextCloud notifications feature. Preferably also an admin setting to toggle the default behaviour.

**Describe alternatives you've considered**
Downgrading.

**Comment by tcitworld** [comment]
The admin setting you're looking for is in the groupware admin setting section.

**Comment by mikaelkolkinn** [comment]
> The admin setting you're looking for is in the groupware admin setting section.

Wow, thank you. I thought I had looked everywhere but apparently not.
