### ISSUE TITLE
Calendar 1.4.1: Unable to put an .ics file to a shared calendar

### ISSUE THREAD

**Issue by raoulbhatia** [nextcloud/calendar#206]
_(This is also tracked for DAVDroid via https://forums.bitfire.at/topic/1261/updating-existing-uploading-new-record-exception-at-bitfire-dav4android-exception-notfoundexception-404)_

Hi!

I've recently updated calendar 1.4.0 to 1.4.1 and owncloud from 9.1.1 to 9.1.2

Since then, I am unable to create/update events in a shared calendar via Android & DAVDROID:
```
HTTP RESPONSE:
h2 404 
cache-control: no-store, no-cache, must-revalidate
content-security-policy: default-src 'none';
content-type: application/xml; charset=utf-8
date: Mon, 28 Nov 2016 21:29:36 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
server: nginx
set-cookie: oc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
set-cookie: oc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
set-cookie: oc_remember_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
set-cookie: oc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
set-cookie: oc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
set-cookie: oc_remember_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
set-cookie: 51deba942f2c9=8ua4avovasdkmmhncfj2d6eu72; path=/; secure; HttpOnly
x-sabre-version: 3.0.9

<?xml version="1.0" encoding="utf-8"?>[LF]
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">[LF]
  <s:sabredav-version>3.0.9</s:sabredav-version>[LF]
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>[LF]
  <s:message>Principal with name users not found</s:message>[LF]
</d:error>[LF]
```

The only way I found to resolve this re-curring 404 error is to delete the added/modified event on Android - so to get rid if the scheduled upload - and re-add it via the owncloud web interface.

This used to work until the update to calendar 1.4.1 and owncloud 9.1.2.

Happy to provide more information to get this resolved.

Thanks,
Raoul

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
