### ISSUE TITLE
Add avatar to sharing list

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/calendar#207]
Currently the search dropdown and the list of shares don't use the displayname and the avatar. Instead it only shows the id (ugly on ldap). Both should be fixed.

**Comment by georgehrke** [comment]
The display name thing should be fixed with 1.4.1, can you validate that?

**Comment by georgehrke** [comment]
Is there a proper API or set of css classes and templates in the server to add the avatar?
cc @jancborchardt

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/master/js/app.js#L104 +
https://github.com/nextcloud/spreed/blob/master/js/app.js#L120-L124

**Comment by georgehrke** [comment]
regarding the label:
This was fixed here: https://github.com/nextcloud/calendar/commit/927f41220c4691dd2aa907747a1c09b989d85c00#diff-3f31cf29dabccac17dc76bf33ba73634

**Comment by nickvergessen** [comment]
Ah I pulled master, but didn't rebuild JS stuff, works now.

**Comment by nickvergessen** [comment]
Also I just noticed, when adding a sharee, the uid is displayed until a page refresh is done, so you seem have to missed one spot.

**Comment by georgehrke** [comment]
Indeed https://github.com/nextcloud/calendar/blob/master/js/app/service/calendarService.js#L541L553

apparently forgot to fix that one
