### ISSUE TITLE
Copy Talk room URL to location instead of description

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/calendar#2070]
I really like the button "create talk room for this event" - but it copies the room's URL into the event's description field. Since the Talk room is then usually the location where the meeting takes place, it would make more sense to me to apply the URL to the location field, instead of the description field.

**Comment by georgehrke** [comment]
I don't really want to mix up the two of them.
What if a meeting takes place in some office, but people who can't make it will join via Talk?

We are planning to add a dedicated Conference property to events:
https://github.com/nextcloud/calendar/issues/1758

Once we have that property, we can show it more prominently in the invitation email or even include it in the event reminder, so there is a "Join talk" button in the notification.

@wiswedel Does that make sense?

**Comment by wiswedel** [comment]
CONFERENCE property sounds good in general, but is that implemented in iOS, Thunderbird and Outlook so we don't lock users onto the web UI?

**Comment by georgehrke** [comment]
The `CONFERENCE` property is part of an official RFC (by Apple): https://tools.ietf.org/html/rfc7986

So I expect it to be adapted by iOS, Thunderbird and Android soon.
But nonetheless, it's only meant as an addition to the link in the description, not a replacement.

**Comment by wiswedel** [comment]
I expect the edge case of having several locations to be neglectable if weighed against the not-yet-and-who-knows-when implementation status of ```CONFERENCE``` across the usual client platforms.

plus market check: Zoom, Skype for Business and TeamViewer use the ```location``` field as well.

**Comment by georgehrke** [comment]
> plus market check: Zoom, Skype for Business and TeamViewer use the location field as well.

Well, I checked Google and it doesn't. ;) 

I guess the important question here is not whether it's in the description or the location field, but how do users open the Talk link.

If a user just copy and pastes the link from the event editor, I do not see a big difference whether it's in description or location. If we actually want to streamline the experience here, the reminder should contain a link to directly open the talk room.

cc @nextcloud/designers

**Comment by georgehrke** [comment]
My main problem here is that location should only contain one address or link for that matter.
Description does not have a limit for length or amount of links you include.

If the user did not provide a location so far, sure, we could put  the link into location.
But what if the user already entered a location? We should definitely not replace it with the link.

**Comment by wiswedel** [comment]
> If the user did not provide a location so far, sure, we could put the link into location.
> But what if the user already entered a location? We should definitely not replace it with the link.

Sure, but shouldn't that be easy to check and re-route to Description in case?

**Comment by st3iny** [comment]
This has been implemented in the meantime. I just tested it.
