### ISSUE TITLE
Question: IOS Caldav setup.

### ISSUE THREAD

**Issue by Dextroz** [nextcloud/calendar#2072]
I have a Nextcloud instance setup. Following [this](https://docs.nextcloud.com/server/18/user_manual/pim/sync_ios.html) guide to setup CalDAV however, I keep getting "Cannot connect using SSL". I have SSL setup using a reverse proxy. I am not sure what I am doing wrong.

Service discovery is working correctly. Heading to `/.well-known/carddav` or `.../caldav` redirects correctly.

I have tried:

1. Altering port to 443 and 80.
2. Using `example.com/remote.php/dav/principals/users/USERNAME/` as the url.

I have verified nothing is blocking the connection to my nextcloud instance. I am on the latest version of IOS. I have MFA on my account so I tried generating an app password and using this in the password field, still no luck. I see in the requests IOS is querying port 8443 which I don't have open. However, as I have said, I have tried altering to the port with no success.

Any other suggestions?

**Comment by georgehrke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
