### ISSUE TITLE
unable to share a calendar

### ISSUE THREAD

**Issue by giddhub** [nextcloud/calendar#2075]
Version 2.0.2

Since this Version the creation of a new calender has moved to the bottom of existing calendars. When creating a calendar the share option (the share icon) is not available. For the ones created before it is.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md)

Unless you fill out the issue template completely including all logs, we can't go ahead and help you.

**Comment by JDictus** [comment]
Hello, sharing a calendar to a person (no user found) or a group no longer works. Do you have an idea ?
Thank you
