### ISSUE TITLE
Delete single event in repeating events

### ISSUE THREAD

**Issue by Poachman** [nextcloud/calendar#208]
Our organization has weekly meetings, but some weeks we don't have the meetings.  For example, Christmas week we don't have any meetings, but I already have a repeating rule for our meetings.

If I try and delete a single meeting, it deletes the whole series.  It would be great to have the option when deleting to choose between deleting the whole series, or just the single event.  Just like Google Calendar works:
![Google Calendar Example](https://cloud.githubusercontent.com/assets/1891582/20729896/ced535ae-b638-11e6-82c1-a53a576e503a.png)

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/7

please search for existing issues before creating new ones

**Comment by Poachman** [comment]
I did try and search but came up with nothing.
