### ISSUE TITLE
Impossible to edit a calendar from another person when you have one 

### ISSUE THREAD

**Issue by zouhourahadji** [nextcloud/calendar#2088]
**Step to reproduce:** 

1. Login in to the calendar
2. Click on agenda  from another person to book a slot ( I have the edition rights)
3. Fill form (title + dates)

**Expected behaviour**
My slot is on the shared agenda

**Actual behaviour**
The slot is not shared but only on my own 

N.B. : when I delete my own agenda, it works.  

**Client configuration**
Browser: Chrome ( 80.0.3987.149)
Operating system: MacOS Catalina 10.15.3

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md)

Unless you fill out the issue template completely including all logs, we can't go ahead and help you.

**Comment by georgehrke** [comment]
@zouhourahadji Please fill the __entire__ issue template .....
