### ISSUE TITLE
Link with anchor to event or day

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#21]

**Comment by nickvergessen** [comment]
Subscribing for activity

**Comment by georgehrke** [comment]
lets split this up into two different PRs:
- [ ] link to day 
- [ ] link to event

**Comment by georgehrke** [comment]
requires the changes made to hash service in https://github.com/nextcloud/calendar/pull/256

**Comment by blizzz** [comment]
📢 #256 is already merged. :D

**Comment by tcitworld** [comment]
Will probably wait for https://github.com/nextcloud/calendar/issues/540 and vue-router.

**Comment by georgehrke** [comment]
Yes, let's wait for #540 here. Doesn't make much sense to implement it twice.

**Comment by caugner** [comment]
I'm not sure if you were already considering this, but the router value should maybe be empty if the current day/week/month is shown (to prevent newly added bookmarks from pointing to the day the bookmark was set).

**Comment by georgehrke** [comment]
@jancborchardt @skjnldsv Quick usability / design question.

When linking to an event that's recurring (e.g. from the activity app),
which occurrence should be opened?
1️⃣ The first one
2️⃣ The closest one in the future or if that's not available the most recent one

I would personally go for 2️⃣

**Comment by skjnldsv** [comment]
I would also say 2

**Comment by nickvergessen** [comment]
Definetly 2. otherwise you end up on a year(s) old date because someone just modified a recent event entry

**Comment by vaandefanel** [comment]
I prefer option 2. Can you add the possibility to specify an occurence ?

**Comment by georgehrke** [comment]
@vaandefanel Yes, there will be the option to link to a specific occurrence. The question was only what to do when linking to a recurring event when no specific  occurrence was given. :)

**Comment by jancborchardt** [comment]
Agree with everyone: Of course it should be the next upcoming one. :) (It’s already confusing that in invite mails sometimes the first occurence of a repeating event was listed. :D)
