### ISSUE TITLE
nextcloud18.02  after update calendar  to 2.0.2, it doesn't work

### ISSUE THREAD

**Issue by qdog988** [nextcloud/calendar#2101]
I have update nextcloud from 17.0.4 to 18.0.2, and update calendar to 2.0.2, and it success, but then the calendar doesn't work, click left button, no event page appear,and left panel Keep spinning，so anybody know how to deal the Situation， thanks

**Comment by georgehrke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
