### ISSUE TITLE
[18.0.3] Calendar goes whitescreen

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/calendar#2108]
Steps to reproduce on firefox:

Go from weekly view to daily view. Click anywhere on the calendar. Watch it go whitescreen.

![O5C5Nq826q](https://user-images.githubusercontent.com/7935624/77421460-2102cc00-6d89-11ea-9518-14041c790716.gif)

**Comment by georgehrke** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/2051

**Comment by georgehrke** [comment]
@Dragon988 Please use the issue template next time you open a ticket.

**Comment by Dragon988** [comment]
My bad, have a good day!
