### ISSUE TITLE
ALARM TRIGGER VALUE is DATE instead of DATETIME

### ISSUE THREAD

**Issue by tdelmas** [nextcloud/calendar#2128]
### Steps to reproduce
1. Create a full-day event on Firefox
2. Add an email reminder **on date** on Firefox
3. Sync with DAVx5

### Expected behaviour

The event is synced

### Actual behaviour

DAVx5 raise a cast error.

### Calendar app
**Calendar app version:**
@tcitworld EDIT : 2.0.2

**CalDAV-clients used:** DAVx5 version 2.6.5-ose from F-Droid

### Client configuration
**Browser:** Firefox 74 

**Operating system:** Windows

### Server configuration

No idea, sorry, it's https://framagenda.org

@tcitworld EDIT : 18.0.3

# Details

The event received by DAVx5 contains:

```
BEGIN:VALARM
ACTION:EMAIL
TRIGGER;VALUE=DATE:20200421
END:VALARM
```

But if I read correctly https://tools.ietf.org/html/rfc5545#section-3.8.6.3 the VALUE must be a DATE-TIME (and not a DATE).

So during sync DAVx5 displays "net.fortuna.ical4j.Date cannot be cast to net.fortuna.ical4j.DateTime".

The same problem was documented in DAVx5 for another field and another server there: https://forums.bitfire.at/topic/993/tasks-completed-date-cannot-be-cast-to-datetime

I think it worth mentioning #1940 even if it's not the same problem.

**Comment by georgehrke** [comment]
Related to https://github.com/georgehrke/calendar-js/issues/89, although no direct duplicate.

**Comment by georgehrke** [comment]
PR: https://github.com/nextcloud/calendar/pull/2129
