### ISSUE TITLE
Use yarn instead of npm

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#213]
* **much** faster
* cleaner output
* `yarn why` <3
* allows locking dependencies https://yarnpkg.com/en/docs/yarn-lock (at least better than npm shrinkwrap)

See. https://yarnpkg.com/en/docs/migrating-from-npm

**Comment by georgehrke** [comment]
yarn looks definitely interesting, but do you have real performance issues with npm? 

yarn takes 13 seconds, npm install does ~30seconds.
