### ISSUE TITLE
[discussion] Create Jitsi Link Button

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/calendar#2136]
Because Nextcloud Talk is only working for 3-4 users without the Nextcloud Enterprise subscription, we use Jitsi for that. 
My idea is to add a button, that gerates a Jitsi Link.
What are you thinking?
![grafik](https://user-images.githubusercontent.com/24530680/78128016-7daf5800-7415-11ea-8f87-c8751a19466c.png)

**Comment by tcitworld** [comment]
This may be done with a third-party app that uses https://github.com/nextcloud/calendar/pull/1045

And in the future, https://github.com/nextcloud/calendar/issues/812

**Comment by jakobroehrl** [comment]
@tcitworld 
Thank you. :)
How can I use #1045?
Or should I what unil #812 is implemented?

**Comment by georgehrke** [comment]
I agree with @tcitworld here. This is something that should be implement by another app. All things in the calendar UI should work out of the box, which jitsi doesn't, because you need a jitsi server for it.

You will have to wait for #812
