### ISSUE TITLE
subscriptions never updated after creation

### ISSUE THREAD

**Issue by palegrand** [nextcloud/calendar#2146]
Ever since I updated to calendar 2.0.1 changes/additions  shard calendars are not shown anymore.   
  
After creating a new subscription (mainly shared outlook-calendars with *.ics-link) the subscribed calendar shows nicely with all events after the first 'cron' run.  
cron does call \UpdateCalendarResourcesRoomsBackgroundJob regularely, executes without error but does NOT show updates in the calendar.     
Recommended update to Nexctcloud 18 did no change the behaviour

### Steps to reproduce
1. create subscription to foreign calendar (*.ics link)
2. subscribed calendar entries show nicely after first 'cron' run
3. change something in the 'other' calendar
4. The change does not show in Nextcloud after next cron run

### Expected behaviour
step 4 should show the updated/added entry from step 3 in Nextcloud-calendar
used to work like that before calendar 2.0.1

### Actual behaviour
subscribed calendar in Nextcloud shows the state it had after creation/first cron run and does not reflect any changes in the original calendar
* deleting and recreating the subscription (with the same link) shows nicely the current sate (including all changes) - but this state will never change (as above)
* cross-check: ICSx5 (Android) using the same link perfectly works as before, i.e. shows all updated entries

### Calendar app
**Calendar app version:**  2.0.2

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
DAVx5

### Client configuration
**Browser:** recent Firefox/chrome/Vivaldi.  
Problem is independent of the browser

**Operating system:** Windows 10, Debian 10

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 18.0.3
same behaviour as 17.0.3
 
**Updated from an older installed version or fresh install:** updated

**Comment by tcitworld** [comment]
Default subscription refreshing interval is of one week (unless the subscription itself asks for a different rate).
You may override it with something like:
```bash
./occ config:app:set dav calendarSubscriptionRefreshRate --value "P1D"
```
to refresh all of the server's subscriptions every day. Value is a [`DateInterval`](https://www.php.net/manual/fr/dateinterval.construct.php)

**Comment by palegrand** [comment]
@tcitworld: Thank you very much! I obviously missed that change. I set the calendarSubscriptionRefreshRate and it updates perfectly as before.

**Comment by tcitworld** [comment]
No worries, it still needs to be added to the documentation.

**Comment by laborb-sb** [comment]
I'm in the same boat.
May I ask, if there is planed to have a possibilty to set the interval from the User GUI? The interval in the calendar setting don't has any effect.
However, I tried to set some shorter intervals with occ for testing. But I got following error

`[dav] Error: Sabre\VObject\InvalidDataException: The supplied iCalendar duration value is incorrect: P30M at <<closure>>

0. /app/data/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php line 94
   Sabre\VObject\DateTimeParser::parseDuration("P30M")
1. /app/code/cron.php line 125
   OCA\DAV\BackgroundJob\RefreshWebcalJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-04-08T15:20:35+00:00`

**Comment by georgehrke** [comment]
@laborb-sb That’s no surprise, since P30M is an invalid value. Use PT30M

**Comment by hansdez** [comment]
For the past two weeks I thought that my ICS subscription wasn't working. Whenever I imported via the URL it would have all the appointments. But any new appointments or changes wouldn't show up.

I would then remove the subscription and re-add it.

Today I decided to search for a solution and after searching in the Github issues here, on the Nextcloud help forums and in the documentation, I finally found that there is default refresh rate of a week.

If it isn't possible to set the reset rate per subscription, might it then be an idea to change this refresh rate to once per day? That way people will have a bigger chance to realise that their subscription are actually working.

P.S. Thanks for making this essential app!

**Comment by georgehrke** [comment]
> If it isn't possible to set the reset rate per subscription, might it then be an idea to change this refresh rate to once per day? That way people will have a bigger chance to realise that their subscription are actually working.

This is already possible.

Use the `occ` tool to set a custom appValue for `dav calendarSubscriptionRefreshRate`.
https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php#L88

A per-calendar value is used, if the calendar data is providing any. (As in, if the calendar-feed is containing the information that it should be updated once an hour, Nextcloud remembers that and will update the calendar once an hour). You can also change it manually in the database if you really have to. See the `refreshrate` column of the corresponding subscription in the `oc_calendarsubscriptions` table.

**Comment by tcitworld** [comment]
See the docs as well : https://docs.nextcloud.com/server/18/admin_manual/groupware/calendar.html#refresh-rate

**Comment by hansdez** [comment]
I did indeed find it in the manual eventually. (Although I first found this link through Google https://docs.nextcloud.com/server/15/user_manual/pim/calendar.html, and read this about subscribing 'Finished. Your calendar subscriptions will be updated regularly.' I didn't realise until just now that I was reading an old manual).

My point is more about providing defaults that work wel for most use cases. Why is the default a week and not every day? Is doing a refresh that computationally intensive? Or do you have data showing that most people use these subscription links mostly for things like a holiday calendar which will barely ever change?

Unfortunately many of us can't trust the calendar-feed providing the right refresh information (or can influence that). In my case, for example, I have to deal with some Microsoft Outlook Web-feed that I am quite sure won't nicely validate (so happy it works at all to be honest).

**Comment by disolva** [comment]
I set the rate to 'PT5M' where I expect it to be 5 minutes. Is that correct? Because, it does not update after 5 mins. But also not after 1 week. I'm confused about what it actually it's set now. At least in the database, there is none refresh rate set to the subscripted calendar. Where can I (cross) check the setting?

> 
> ```shell
> ./occ config:app:set dav calendarSubscriptionRefreshRate --value "P1D"
> ```

**Comment by mirenbz** [comment]
I was having this same issue about remote calendars not syncing. Solved it thanks to @georgehrke 's fix: I was using time intervals without the `T`. This was throwing `refreshrate in database is invalid` errors in `nextcloud.log`. I set my `calendarSubscriptionRefreshRate` to  `PT6H` and everything \*seems\* to be working now. Thanks!
