### ISSUE TITLE
Long description box on 2.0.3

### ISSUE THREAD

**Issue by dominic-p** [nextcloud/calendar#2187]
### Steps to reproduce
1. Go to month view
2. Uncheck "Enable simplified editor"
3. Create an event that has a description and close it
4. Click on an event with a description

### Expected behaviour
The description box in the editor should be the same size as the event.

### Actual behaviour
The description box is crazy long

### Calendar app
**Calendar app version:** 2.0.3

**CalDAV-clients used:** NA

### Client configuration
**Browser:** Firefox 75.0

**Operating system:** Windows 10 1909

### Server configuration

**Nextcloud Version:** 18.0.3

I did a quick screen recording to demonstrate what I'm seeing because it's kind of hard to describe. Thanks, as always for the great calendar.

![Nextcloud Calender Issue - Long Description](https://user-images.githubusercontent.com/1195080/79399974-a8cb9880-7f39-11ea-9cb5-e896cb80a353.gif)

**Comment by georgehrke** [comment]
I'm not able to reproduce that with BrowserStack (Firefox 75, Windows 10) on Calendar 2.0.3 (Nextcloud 19 beta).

Can you please try cleaning the browser cache?

**Comment by dominic-p** [comment]
Thanks for the response. I tried clearing the cache, and unfortunately, the behavior is the same. I'm also seeing the same behavior on Edge. On Edge the Location box is also quite tall (it takes up maybe 1/4 of the vertical space on the screen).

Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

It may be unrelated, but the detail box feels like it takes longer to open as well since the 2.0.3 update.

Maybe it's an issue with Nextcloud 18 vs 19 beta? Are you able to reproduce on Nextcloud 18?

Another possible ingredient I just realized is that I do have a couple events with long descriptions. These aren't the events that I'm clicking on to test, but could it be scanning all events to find the longest description and then setting the height of the description box for all events to that of the longest?

**Comment by dominic-p** [comment]
@gary-kim, thanks for confirming. Yes, if I click in the description box and start typing it resizes to the correct size for me too. I just don't know why it's not opening to the correct size.

**Comment by dominic-p** [comment]
Looking at this more, it looks like a large height in pixels is set on the style attribute of the `<textarea>` for the Description:

```
<textarea placeholder="Add a description" rows="2" title="Description" style="overflow: hidden; overflow-wrap: break-word; height: 7734px;"></textarea>
```

I'm still not sure why. Even opening and closing dev tools while the sidebar is open corrects the problem.
