### ISSUE TITLE
[v2.x] Interface counter productive

### ISSUE THREAD

**Issue by dirigit** [nextcloud/calendar#2188]
**Is your feature request related to a problem? Please describe.**
I know - interface of Calendar v2.x is modern. But:

Did you ever count actions needed to add an event?
Did you compare it with interface of v1?

v2 is against any rule of usability in relation to productivity.

**Describe the solution you'd like**
A productive interface like in v1 to get things done fast without hazzles introduced in v2.

Thank you!

cu, diri

**Comment by raimund-schluessler** [comment]
Concrete things to improve would help here very much. A generic "the interface is bad" is not really helpful.

**Comment by dirigit** [comment]
It's easy to explain:

Ie in v1 you select date in month view in calendar. Popup window is shown. "whole day event" is deactived when clicking in time or date field. You can directly choose times for start and end as well as change dates without any scrolling.

v2:
Click date in month view. You have to deactivate "whole day" first to be able to change times. Then month view of calendar is shown.  You have to choose "change time" and you have to scroll through hours as well as minutes to assign start time. Afterwards you have to repeat this (choose time, scroll two times) for end as well.

Doing it other way around (end date / time first) start date / time will be set to same values like choosen in end.

In interface of v1 you are ready within two or three seconds. In v2 only scrolling for date and time takes more time.

Not to mention overlapping of date / time popup when popup window is at lower border of screen.

Sorry, it simply takes to much time to get things done. Not every modern interface is productive 

Have a look at MS Office 2007+ to get another example. Whenever you coded a frontend in Access you have overlapping windows without vanishing in background - starting with 2007 you have tabbed views where tabs are never closed by users, vanishing windows when preference is set to overlapping and so on.

Sorry, but it can be done better.

cu, diri

**Comment by habernal** [comment]
I didn't want to open a new bug for this (but we might do it for better tracking):

One bug report:
- The small title text input is 1) shrinked to left and 2) the arrow on its right-hand side has no functionality (and it's not even clear what functionality that should be...)

One suggestion:
- Get rid of the huge "sheet/clippers/whatever" graphics on top. It's eating valuable vertical space while having no additional value (and is not really semantically meaningful - Why are there the tiny dots? It doesn't look as a calendar either)

Hope it gives some concrete suggestions.

![Screenshot_2020-06-05_09-12-54](https://user-images.githubusercontent.com/11850778/83848058-96860380-a70d-11ea-9439-b91368dd65a5.png)

**Comment by georgehrke** [comment]
> The small title text input is 1) shrinked to left

#1576 

>  2) the arrow on its right-hand side has no functionality (and it's not even clear what functionality that should be...)

https://github.com/nextcloud/calendar/issues/2291

> Get rid of the huge "sheet/clippers/whatever" graphics on top.

#1956

**Comment by georgehrke** [comment]
> You have to deactivate "whole day" first to be able to change times. Then month view of calendar is shown. You have to choose "change time" and you have to scroll through hours as well as minutes to assign start time.

This issue is already being dealt with in https://github.com/nextcloud/calendar/issues/1576#issuecomment-618162976

It is planned to restore the old behavior of clicking at the time automatically taking you to the time-picker, not date-picker.

> In v2 only scrolling for time takes more time.

We committed to unifying the UI components used in Nextcloud and I'm very glad that we got rid of the mess having 2 different DatePickers, at least 4 different Select Modals, etc.

If you see severe usability issues with the Date/Timepicker, please open a ticket in the repo of the Nextcloud UI components, so we can discuss the issue there: https://github.com/nextcloud/nextcloud-vue

> Not to mention overlapping of date / time popup when popup window is at lower border of screen.

This was fixed upstream in the meantime:
![9510A0AC-E4C6-44B2-99C9-4A60D88DDE48](https://user-images.githubusercontent.com/1250540/83853185-309d7a00-a715-11ea-8b32-9199ffe6b3dc.png)
