### ISSUE TITLE
Picking a date in date-time-picker does not open time-picker

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#2198]
![860E3E39-73A8-427A-B713-F64EEECF6761](https://user-images.githubusercontent.com/1250540/79734322-d24c4180-82f6-11ea-9d24-de1ac054554c.png)

Workaround: just click "Pick a time" button

**Comment by georgehrke** [comment]
There is a video demonstrating the issue in https://github.com/nextcloud/calendar/issues/2265

**Comment by hansimausisteffiwurstbrot** [comment]
This bug is occuring (again?), tested on different Nextcloud instances.

**Comment by tcitworld** [comment]
@hansimausisteffiwurstbrot See #2983
