### ISSUE TITLE
Long Description Overflow

### ISSUE THREAD

**Issue by gary-kim** [nextcloud/calendar#2200]
### Steps to reproduce
1. Have a really long description
2. Open the simple editor

### Expected behaviour

The editor should stay within the available space

### Actual behaviour

![image](https://user-images.githubusercontent.com/47195730/79763388-99dc5000-8356-11ea-9277-bc54131be7e2.png)

### Calendar app
**Calendar app version:** 2.0.3

**CalDAV-clients used:** Web client

### Client configuration
**Browser:** Firefox 76.0b6 (64-bit)

**Operating system:** Ubuntu Derivative

### Server configuration

**Operating system**: Local development instance

**Web server:** `php -S localhost:8080`

**Database:** SQLite

**PHP version:** PHP 7.2.24

**Nextcloud Version:** master

**Updated from an older installed version or fresh install:** Nuked  old version

**Comment by probastaller** [comment]
Something similar occurs on detailed editor even when the description is just 1 or a few lines long.
After updating the event and opening it back to check, the textbox of the description hast grown far larger than the screen and you have to scroll down way too long to find the **Update** button again.

It only occurs when you click the event from having the side panel closed.

If you change from one event to another without closing the side info panel, it seems that the textbox is displayed accordingly to the text size.

But, if you close the panel, and reopen it by clicking an event with description, it will display again very oversized.

- Same version 2.0.3 in the web client of Nextcloud 18.0.4 in a Linux Mint server with nginx.

Hope this helps to fix it.

**Comment by georgehrke** [comment]
@probastaller See https://github.com/nextcloud/calendar/issues/2187

**Comment by probastaller** [comment]
Oh! thank you very much @georgehrke, my fault.

**Comment by jancborchardt** [comment]
Are https://github.com/nextcloud/calendar/issues/2849 and https://github.com/nextcloud/calendar/issues/2877 both duplicates of this?

**Comment by ChristophWurst** [comment]
I would say so :)
