### ISSUE TITLE
Allow user to freely set the default apointment duration

### ISSUE THREAD

**Issue by MartinSfromB** [nextcloud/calendar#2201]
Hey guys,
thanks for your work! I know it is possible but will you be so kind to add "45 minutes" to the defaultSlotDuration settings?

**Comment by georgehrke** [comment]
Can you elaborate on the use-case?

**Comment by MartinSfromB** [comment]
Sorry, I'm on the wrong way. Slot duration settings are fine. But slot duration settings set the default appointments duration an here I need my 45 minutes. So there should be an extra settings field for default appointment duration.

**Comment by georgehrke** [comment]
I'm personally not a fan of overloading the calendar with hundreds of settings for all minor nuances, but we have #812 in the works.

With what i have in mind, other apps will be able to listen when new events are created and change it however wanted, like changing the default duration, adding default categories, setting a default location, etc etc etc.
