### ISSUE TITLE
Default event properties (eg: yearly repetition) should be inferred from the event title.

### ISSUE THREAD

**Issue by dmbreakey** [nextcloud/calendar#2203]
I was recently setting up a calendar to track NPCs birthdays for Animal Crossing. While doing so, it became rapidly annoying to have to constantly manually set the repetition.

When creating a new event, Calendar should check for the presence of specific keywords in the title and assume certain default properties for the event as a result. For example, "birthday" should be a hint that the event should be defined with a Yearly repetition by default.

I think this should **only** be done for new events; not when editing an existing event.

The ability to edit this list of keywords and the default properties that get applied would be nice as well, but I assume that would not be a trivial addition, as the only reasonable place I can see to put such a UI would be in the Settings page.

**Comment by georgehrke** [comment]
Closing in favour of https://github.com/nextcloud/calendar/issues/17

**Comment by georgehrke** [comment]
I added the following to the description of #17

>  On top of that, it should also recognise keywords like weekly, monthly, yearly
