### ISSUE TITLE
Small / short dates in calendar view

### ISSUE THREAD

**Issue by Offerel** [nextcloud/calendar#221]
Sometimes, i have short events that runs only 5 Minutes. In this case, the event is only visible in the calendar app as a small line some poor pixels in the height. Is it possible to reformat them, so that i can read the subject, but i see also, that this is a short event? I came from Outlook.com and they have resolved this by making the eventbox a little bit indented. Maybe we can do here a similar thing. #

**Comment by georgehrke** [comment]
possibly an upstream issue, needs to be tested

**Comment by Offerel** [comment]
have found a small fix or workaround: i have added a custom theme and changed the class .fc-event. i added there `min-height: 15px;` with this, the  Subject is full visible.

**Comment by georgehrke** [comment]
Hm, not sure if that's an appropriate fix.
What happens when you create two 5 minutes events? One at 8:00am and the other one at 8:01.

Do you see both properly?

**Comment by Offerel** [comment]
If one event in the same calendar start at 08:00 and another at 08:01, they overlay a little bit, but both are clearly visible. But i think it's not so often, that one user has more than one event at the same time.

![screenshot_01](https://cloud.githubusercontent.com/assets/14041522/21822907/5db2b2e0-d779-11e6-8e7a-d6e14b717ccb.jpg)

**Comment by georgehrke** [comment]
I reported this upstream: https://github.com/fullcalendar/fullcalendar/issues/3881

**Comment by georgehrke** [comment]
https://fullcalendar.io/docs/agenda/agendaEventMinHeight/
