### ISSUE TITLE
Events with CREATED:00001231T000000Z are not imported

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/calendar#2213]
Exporting several calendar .ics files from Google Calender resulted in several events not being imported when loading them into Nextcloud Calendar. All of them had the following problem where somehow Google didn't have/export a `CREATED` date for an event and thus defaults it to `CREATED:00001231T000000Z` ([Searching for that value](https://www.google.com/search?client=ubuntu&channel=fs&q=%22CREATED%3A00001231T000000Z%22&ie=utf-8&oe=utf-8) shows other people running into this problem as well).

### Steps to reproduce
1. Import an `.ics` with one or more events containing `CREATED:00001231T000000Z`, e.g. the event below:

```
BEGIN:VEVENT
DTSTART;TZID=Europe/Amsterdam:20110104T100000
DTEND;TZID=Europe/Amsterdam:20110104T170000
RRULE:FREQ=WEEKLY;UNTIL=20110126T090000Z;BYDAY=MO,TU,WE,TH,FR
DTSTAMP:20200421T145117Z
UID:asdasdasdasdasdasd@google.com
CREATED:00001231T000000Z
DESCRIPTION:
LAST-MODIFIED:20110124T101158Z
LOCATION:
SEQUENCE:4
STATUS:CONFIRMED
SUMMARY:test summary text
TRANSP:OPAQUE
END:VEVENT
```

### Expected behaviour
Import events with faulty `CREATED` fields and set the `CREATED` date to some default

### Actual behaviour
Events with faulty `CREATED` fields aren't imported

### Calendar app
**Calendar app version:** 2.0.3

### Client configuration
**Browser:** Firefox 75.0

**Operating system:** Ubuntu 18.04

### Server configuration

**Operating system**: Ubuntu 18/04

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** 7.3.17

**Nextcloud Version:** 18.0.4

**Updated from an older installed version or fresh install:** Updated from 17

#### Log file (data/nextcloud.log)
I think the following part is most relevant, let me know if more logs are needed.
```
{
  "reqId": "***",
  "level": 4,
  "time": "2020-04-25T22:31:49+00:00",
  "remoteAddr": "***",
  "user": "***",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/calendars/***/***/1BA302CB-7A57-400B-A09E-8DCCEC4AC391.ics",
  "message": {
    "Exception": "Sabre\\DAV\\Exception\\UnsupportedMediaType",
    "Message": "Validation error in iCalendar: The supplied value (0-12-31T00:00:00Z) is not a correct DATE-TIME",
    "Code": 0,
  ...
}
```

**Comment by georgehrke** [comment]
Fixed in https://github.com/georgehrke/calendar-js/pull/134
