### ISSUE TITLE
Moving a single event from a periodic event gives false invitation

### ISSUE THREAD

**Issue by mokkin** [nextcloud/calendar#2215]
Today I moved by drag and drop a single event out of a bunch of a two weekly occurring event to another date (06.05.2020). For me this was fine, but the other attendee received an invitation with date 06.03.2020, that was the start date of this periodical event.

NC 18.0.4

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md)

Unless you fill out the issue template completely including all logs, we can't go ahead and help you.
