### ISSUE TITLE
Repeat every weekday or weekend

### ISSUE THREAD

**Issue by Irillit** [nextcloud/calendar#2216]
Hello, 
As far as I see, you doesn't have this feature. 

**Is your feature request related to a problem? Please describe.**
I feel confused about recurrent events in Calendar. We can repeat every day, every month and so on. Suppose we have a scrum meeting. We repeat every weekday, but don't gather at Sunday or Saturday. Or you can have something that occurs only on weekends, like some kind of language lessons.

**Describe the solution you'd like**
I'd like to add weekdays, weekends.

**Additional context**
Despite I have regular european schedule, some countries in Middle East will require to redefine weekend days.

**Comment by georgehrke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by tcitworld** [comment]
For clarification, this is already possible by selecting the appropriate days. If you have issues please continue on the forum linked above or see with Nextcloud GmbH for support.

![image](https://user-images.githubusercontent.com/2197836/80611756-527f4f00-8a3b-11ea-8b08-b68a45af6f41.png)

**Comment by Irillit** [comment]
Ok, thank you.
