### ISSUE TITLE
Change illustration to «Lunch»

### ISSUE THREAD

**Issue by ludenticus** [nextcloud/calendar#2218]
Right now, the illustration to "Lunch" is:
![image](https://user-images.githubusercontent.com/813198/80619124-dae4fc00-8a09-11ea-8892-88440570b232.png)

This seems adequate to a party, not to a regular lunch meeting. Hence, I suggest to use instead:
![image](https://user-images.githubusercontent.com/813198/80619211-010a9c00-8a0a-11ea-9984-6dbb86e5b3da.png)

**Comment by SuperSandro2000** [comment]
I need to agree with you that lunch looks like some dinner or date.
