### ISSUE TITLE
Add «food» terms to illustrations

### ISSUE THREAD

**Issue by ludenticus** [nextcloud/calendar#2219]
Some food related terms are missing for illustrations:
- Breakfast
![image](https://user-images.githubusercontent.com/813198/80619604-8a21d300-8a0a-11ea-9018-ab42f8ffad4c.png)

- Snack
- Food
- Meal
- Brunch
- Bread 
- Dessert
- Hamburger [There's one for Pizza]
- Drinks
- Wine, Whiskey, Bourbon, etc.
- Beer
- Soda
- Coffe, cappuccino, espresso, etc.

**Comment by SuperSandro2000** [comment]
Breakfast looks very different in many countries and for me the current breakfast picture looks like an unhealthy meal when you are on a day trip and nothing like anyone would eat for breakfast.

**Comment by georgehrke** [comment]
I have to agree with @SuperSandro2000 here. Food in general, but breakfast in particular is very different depending on country / culture.

**Comment by ludenticus** [comment]
Not only breakfast @SuperSandro2000 and @georgehrke. Nourishment patterns are culture-dependent. You don't always _seat_ in a chair by a table to eat, for instance. And it's far from usual to drink wine or take hamburgers before midday. However, current «Lunch» term triggers this:

![image](https://user-images.githubusercontent.com/813198/81846905-7604c800-9518-11ea-8ab8-354894c8ce8a.png)

My point is not an apology to political correctness. On the contrary. I only think it's nice to have some illustration whenever you type some terms. :wink:

**Comment by ludenticus** [comment]
Maybe as follow:

For: 
- Food
- Meal
- Brunch
- Dine / dining 
![image](https://user-images.githubusercontent.com/813198/81848385-a8afc000-951a-11ea-9eab-3eb7f50d38ba.png)

For:
- Coffee
![image](https://user-images.githubusercontent.com/813198/81930045-9d59a480-95ad-11ea-93c1-7fb27c37ff4b.png)

For:
- Tea
![image](https://user-images.githubusercontent.com/813198/81930193-df82e600-95ad-11ea-886e-c39b4a0e28c1.png)

For:
- Drinks
- Beer
- Whiskey, bourbon, tequila, vodka, martini, coctel
- Wine
![image](https://user-images.githubusercontent.com/813198/81930544-58823d80-95ae-11ea-99c9-f7fc01d1f76b.png)

**Comment by SuperSandro2000** [comment]
The only way to fix this would be to make the illustrations culture depended. Task for another time.

I really like the first three illustration but I think the subtitle for drinks is not that fitting.

**Comment by ludenticus** [comment]
Yeah, `drinks` is not that fitting. Maybe `Alcohol`?

**Comment by st3iny** [comment]
Thanks for the suggestions.

Illustrations were removed recently, so I'm closing this issue.
