### ISSUE TITLE
Circle not found when full name is given

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/calendar#2220]
A circle named `Test` is not shown when you type `test`, but shows up when you only type `tes`. This is because the api returns exact matches in `results.data.ocs.data.exact.circles` and not in `results.data.ocs.data.circles`, so exact matches are not considered by the Calendar app.

I fixed this for the circle sharing implementation of Tasks in https://github.com/nextcloud/tasks/pull/995. When this PR is merged I would send a PR for Calendar. So it would be nice, if you could have a look 😉

**Comment by tcitworld** [comment]
Is that an indended behaviour from the OCS API? Exact matches not being returned in `results.data.ocs.data.circles` as well?

**Comment by raimund-schluessler** [comment]
> Is that an indended behaviour from the OCS API? Exact matches not being returned in `results.data.ocs.data.circles` as well?

I don't know if it the best/intended behaviour, but in the files app the OCS API behaves the same and it doesn't create trouble there. So I think we should adjust to the current behaviour.

**Comment by raimund-schluessler** [comment]
PR is in #2233.
