### ISSUE TITLE
Be able to edit a public calendar without NC account

### ISSUE THREAD

**Issue by meaz** [nextcloud/calendar#2221]
Hi,

I wanted to share a NC calendar to some friends. They don't have any NC accounts so they can see my calendar, but can't add events in it.
That would be great to add an option when we share a calendar  so that people without accounts can add events in it.

**Comment by tcitworld** [comment]
Duplicate of https://github.com/nextcloud/server/issues/3509

**Comment by meaz** [comment]
Sorry for that, I close it.
