### ISSUE TITLE
add a timezone property to calendars.

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#223]
in order to comply with 5.2.2 of the CalDAV standard

   Conformance:  This property SHOULD be defined on all calendar
      collections.  If defined, it SHOULD NOT be returned by a PROPFIND
      DAV:allprop request (as defined in Section 12.14.1 of [RFC2518]).

**Comment by tcitworld** [comment]
So newly created calendars should have this property matching user defined timezone in the settings ?

**Comment by georgehrke** [comment]
It's exposed in cdav library: https://github.com/nextcloud/cdav-library/blob/master/src/models/calendar.js#L67

Needs to be implemented in calendarStore in vue
