### ISSUE TITLE
Rearrange calendars by visibility, improve sidebar for user with many calendars

### ISSUE THREAD

**Issue by loelkes** [nextcloud/calendar#2236]
**Is your feature request related to a problem? Please describe.**
Users can hide calendars but can't _hide_ them from the list on the left. In my setup Users have in average 20-25 calendars (mostly shared) that they need to be to access sometimes. 

<img width="341" alt="Screenshot 2020-05-04 at 17 36 49" src="https://user-images.githubusercontent.com/231909/80984433-22b2bb80-8e2e-11ea-9c90-33659698d259.png">

**Describe the solution you'd like**
Shift all hidden calendars to the bottom of the list.  This allows user to access and enable them if needed but otherwise they don't obstruct the list/view.

**Describe alternatives you've considered**
Can't think of a different or more easy way to make the list easier to use if you have more than 10 calendars.

**Additional context**
Calendar names hidden for privacy.

**Comment by loelkes** [comment]
Related to #9 and #773

I'm not talking about having the user arrange the calendars nor having it stored in the DAV or somewhere is. Move all hidden calendars somewhere so I don't have to look scroll because the one I want to see is at the bottom of the list.

**Comment by georgehrke** [comment]
I'm not sure about this change.
When clicking a calendar that is currently visible, it will jump down to the part with hidden calendars. This is really an unexpected behaviour.

On top of that, it's contradicting #9.

**Comment by georgehrke** [comment]
@tcitworld What's your opinion here?

**Comment by tcitworld** [comment]
Yeah, seems a bad idea too from my POV.

It would be more interesting to study these kind of cases to see why people use so many calendars (definitely not the first issue where this is bothering me) and how some sharing options or workflows can be improved.

**Comment by georgehrke** [comment]
> It would be more interesting to study these kind of cases to see why people use so many calendars (definitely not the first issue where this is bothering me) and how some sharing options or workflows can be improved.

Definitely!
I believe that many people used shared calendars for the purpose of Free/Busy, since we didn't offer it in the web before Calendar 2.0.

**Comment by AlexandreBonneau** [comment]
> Yeah, seems a bad idea too from my POV.
> 
> It would be more interesting to study these kind of cases to see why people use so many calendars (definitely not the first issue where this is bothering me) and how some sharing options or workflows can be improved.

I think people are using that many calendars because Google (and some other major players) ignored [RFC 5545, section 3.8.1.2xx](https://tools.ietf.org/html/rfc5545#section-3.8.1.2) about categories.
Since colors helps a lot getting a visual cue about what events are planned in a given day/week/month, lots of people now rely on having one calendar for each 'category', whilst they should really add category(ies) to events instead (see [the fullcalendar issue about that](https://github.com/fullcalendar/fullcalendar/issues/4356)).

About improving the sidebar for user with many calendars, perhaps being able to hide it would be a first step (hide the sidebar so more space is shown for the events, but still get access to the week dropdown).

**Comment by jancborchardt** [comment]
@georgehrke @tcitworld I’m also running into this issue, and would agree with @loelkes on sorting all the disabled calendars to the bottom.

> When clicking a calendar that is currently visible, it will jump down to the part with hidden calendars. This is really an unexpected behaviour.

Possibly what we can do here is that the change will not carry over immediately, but only on next load of the app / refresh?

![calendar list](https://user-images.githubusercontent.com/925062/89411270-7088d980-d725-11ea-95ef-f8b32dc91a94.png)

**Comment by raimund-schluessler** [comment]
With https://github.com/nextcloud/calendar/pull/2244 the calendar list is sortable by drag and drop. Wouldn't it be enough if the user can drag a calendar he doesn't want to see to the app of the list?

**Comment by jancborchardt** [comment]
@raimund-schluessler most people will not fiddle with the defaults, and the design should work well by default. :) Otherwise we require _every_ person who has this issue to solve it manually, and that’s just something we should fix.

Relevant reading on that: https://lawsofux.com/teslers-law

**Comment by raimund-schluessler** [comment]
Well, from the amount of feedback this issue got so far, I guess not everyone desperately wants their disabled calendars at the bottom. And automatically changing the sort order by the disabled status might be unexpected behavior for some people.

If you often have to disable and enable a calendar, I wouldn't want it at the bottom. And if you do it only rarely, manually dragging it to the bottom once seems like the better option to me.

**Comment by alexanderdd** [comment]
how about an option in the settings drawer in the bottom left  **"sort calendars: alphabetically/active at the top"**, alphabetically is default?
I think only powerusers will run into this problem, and they will find the setting. There are similar settings in other apps, like contacts where you can set if they are sorted by first/last name or last edit date.

**Comment by jancborchardt** [comment]
We are not going to introduce a sort setting for something as trivial as this. Remember all settings introduce code complexity, increase the testing matrix, and often don't actually make anything easier for users. Also see our design guidelines at https://nextcloud.com/design

Instead as said: Let's simply sort visible calendars up top.

**Comment by loelkes** [comment]
IMHO fixed with #2244 and fully discussed here. Thanks!
