### ISSUE TITLE
CalDav OPTIONS support

### ISSUE THREAD

**Issue by jpopovitch** [nextcloud/calendar#2237]
### Steps to reproduce
1. Open Gnome Evolution, add a New Calendar
2. tail -f /var/log/apache2/nextcloud_access.log|grep Evolution
3. Refresh Evolution Calendar

### Expected behaviour
The calendar should sync with Gnome Evolution client

### Actual behaviour
The CalDav calendar does not sync because Evolution CalDav makes an OPTIONS call that is 404'ed by NC.

### Calendar app
v2.0.3

**CalDAV-clients used:** 
Evolution v3.30.5-1.1 

**Operating system:** (e.g. Arch Linux)
Debian 10 Cinnamon

### Server configuration
Debian 10, Apache, MariaDB, Nextcloud v18.0.4 (continuously updated since v17), PHP v7.3

Enabled:
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - extract: 1.2.4
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_trashbin: 1.8.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.4
  - news: 14.1.6
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - telephoneprovider: 1.0.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - accessibility
  - encryption
  - federation
  - files_external
  - files_sharing
  - files_versions
  - password_policy
  - support
  - survey_client
  - systemtags
  - user_ldap

**Nextcloud configuration:**

    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domainmail.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "https:\/\/cloud.domainmail.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "theme": "",
        "loglevel": 3,
        "maintenance": false,
        "app_install_overwrite": [
            "files_readmemd"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        }
    }

#### Web server error log (e.g. /var/log/apache)
```
10.0.0.2 - - [04/May/2020:14:57:10 +0000] "OPTIONS /remote.php/dav/calendars/jim@k4vqc.com/personal/ HTTP/1.1" 404 5146 "-" "Evolution/3.30.5"
```

#### Log file (data/nextcloud.log)
```
Robust logging is disabled, only entry is from 1-may wrt update error.
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/20624

**Comment by jpopovitch** [comment]
wow, i searched for that exact thing and nothing came up.  Thx for the link.
