### ISSUE TITLE
Ability to hidden days and apply to iframe

### ISSUE THREAD

**Issue by SemaphoreOxalis** [nextcloud/calendar#2241]
Hi, _(sorry for y bad english)_
The option hidding WE is good buuut it could be better. In most of our case for us of our clients  we are not using sunday. 
The ideal things could be using hiddendays option in order to disable the desired days and not only WE or not WE. Clearer and profitable for "small" screen.

And it will be great if these option could apply to the embed/iframe view because it seems the WE or not not apply to a public iframe like weeks number.

Thank for all your hard work making cloud great again 👯

**Comment by tcitworld** [comment]
I would say no to a complex option to pick the specific days to hide or to show (you're just having one extra useless day shown). Opinion @georgehrke ?

As for public views hiding the weekend can be controlled globally by the admin through the `showWeekends` app option like this.
```bash
php occ config:app:set dav showWeekends --value "no"
```
This option sets also the default behavior for every user.

**Comment by SemaphoreOxalis** [comment]
Thanks for your opinion. I was thinking about a simple implementation with Checkbox and the https://fullcalendar.io/docs/hiddenDays implementation.

**Comment by georgehrke** [comment]
I agree with @tcitworld that this is too specific of a use-case. This feels like another use-case for #812, where we should just allow apps other apps to inject custom fullcalendar options.

**Comment by SemaphoreOxalis** [comment]
Ok I understand the logic even I think using an API for hidding some days is a bit overkill :D

**Comment by georgehrke** [comment]
Closing in favor of #812
