### ISSUE TITLE
Various different repetitions at different times for the same event

### ISSUE THREAD

**Issue by xsolinsx** [nextcloud/calendar#2246]
**Is your feature request related to a problem? Please describe.**
I need to set an event to repeat every Monday at 10:00 for 1h and every Thursday at 12:00 for 1h

**Describe the solution you'd like**
I would like to be able to specify various types of repetitions for an event also at different times

**Describe alternatives you've considered**
Create two separate repetitive events

**Additional context**
University lectures of the same subject that comes at different days in different times

**Comment by georgehrke** [comment]
> I need to set an event to repeat every Monday at 10:00 for 1h and every Thursday at 12:00 for 1h

Just create two recurring events in that case. This is too special of a use-case. 

While your request is technically supported by RFC 5545, most libraries and calendar software don't support expanding (or editing) multiple RRULES.
Furthermore RFC 5545 explicitly states, that there should not be more than one RRULE.
https://tools.ietf.org/html/rfc5545#section-3.6.1
