### ISSUE TITLE
Delete an event - spare some clicks

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/calendar#2247]
**Is your feature request related to a problem? Please describe.**
Do delete an event I need to:
1. click on the event (okay)
2. click at "more"
3. click at "..."
4. click at delete

**Describe the solution you'd like**
Give me the the ability to delete an event on overview of an event or latest at sidebar (which is without hiding behind "...".

**Additional context**
While testing appointments app I figured out it's actually a lot of clickwork to delete an event, and it becomes vastly annoying if you delete a bunch of them.

**Comment by georgehrke** [comment]
Duplicate of #1570
