### ISSUE TITLE
Add several calends to one appointment

### ISSUE THREAD

**Issue by quicknik1980** [nextcloud/calendar#2258]
Nextcloud has the application calendar. In this application you can create appointments. This appointments now can assigned to different calends like "privat", "work" etc. 

Feature Request: I want to assign more than one calendar to one appointment. 

Example: The executive office of a corporation manages the appointments of several different groups in the corporation. The executive Office creates an appointment for a meeting and wants to assign the calends of all groups that have to participate to the appointment. At the same time the executive office wants to have a overseeable calendar [application], so they doesn't want to duplicate all appointments.

with kind regards
quicknik1980

<img width="479" alt="Nextcloud Kalendar" src="https://user-images.githubusercontent.com/65111566/81496132-9254fa80-92b5-11ea-81ad-3831c63208b4.png">

**Comment by tcitworld** [comment]
I don't think iCalendar and CalDAV standards allow this kind of thing. You could tackle this by using attendees to events instead of sharing the whole calendar. See #167

**Comment by georgehrke** [comment]
As @tcitworld pointed out, something like this is not supported by the CalDAV nor the iCalendar standard
