### ISSUE TITLE
Lock color for external shared agenda

### ISSUE THREAD

**Issue by farvardin** [nextcloud/calendar#2277]
When someone share an agenda with me, I can define a color for this shared agenda (for example for not clashing with my own agendas), but if this person "customise" the colors for individual events (using for exemple all rainbow colors), my chosen color won't be used, the customised colors will be displayed instead (and maybe clash with my own colors).

By clashing with my own colors, I mean if the external agenda is using red, and my personal agenda is using green, it's ok, I can immediately notice what is related to myself, and what is related to the agenda shared by someone else. But if the other person has customised one shared event to be blue, and an other to be green, it'll be confusing.

It would be great to have an option to force the chosen color, a bit like this:
![image](https://user-images.githubusercontent.com/477243/82648258-ba2e5180-9c17-11ea-93ce-60513bd76302.png)

**Comment by georgehrke** [comment]
This seems like a very specific use-case, that affects only a tiny share of our user-base.
Have you thought about other ways to distinguish event-color and calendar-color?

cc @tcitworld @nextcloud/designers

**Comment by farvardin** [comment]
i don't think it's very specific, as long as you're getting shared calendars with other people in an organisation. 

If you decide to go with a color for your own agenda (green in my example), you don't have control over what other people will choose to customise their own events. You only have control over the default color for the shared calendar, but if their customise every event, you'll never see the default color.

**Comment by georgehrke** [comment]
> If you decide to go with a color for your own agenda (green in my example), you don't have control over what other people will choose to customise their own events. You only have control over the default color for the shared calendar, but if their customise every event, you'll never see the default color.

Yes, I understood the problem you are describing, but did you consider alternatives to the solution you proposed?

**Comment by farvardin** [comment]
What do you propose? 
I don't know how to do differently, I need to get informations from this external agenda (it's also automatically shared by the other person), but the way they customise EVERY event with a DIFFERENT color is really annoying. I can't force them to use the default color from their agenda, it's not under my control :smiley:

**Comment by farvardin** [comment]
I've looked how google calendar what handling this, they don't allow to change the colors, but at least when the default color has been changed, there is a reminder of the original calendar color:

![image](https://user-images.githubusercontent.com/477243/82661230-ed7adb80-9c2b-11ea-98dc-e220e6413a5c.png)

**Comment by jancborchardt** [comment]
Calendar name and color is shared just like the events in it, so any changes should be the same for all people. And if someone with edit permissions changes the color, it should be changed accordingly.

Otherwise it will get confusing when it comes to using shared systems, or displaying the calendar in a dashboard, or embedded on a website.

**Comment by farvardin** [comment]
yes, that's why I was asking for an override for display only.

**Comment by georgehrke** [comment]
@jancborchardt @tcitworld What do you think about the way Google uses to show a combination of calendar-colour and event-color (as shown in https://github.com/nextcloud/calendar/issues/2277#issuecomment-632631662)?

Should we discuss that in a follow up issue and close this one in favour of the new issue?

**Comment by jancborchardt** [comment]
> What do you think about the way Google uses to show a combination of calendar-color and event-color (as shown in [#2277 (comment)](https://github.com/nextcloud/calendar/issues/2277#issuecomment-632631662))?

Sure, in doubt we can do what Google Calendar does. :) However this doesn’t carry over to syncing with local clients, right?

**Comment by georgehrke** [comment]
I opened a new issue: https://github.com/nextcloud/calendar/issues/2290

Let's close this one in favor of #2290.

**Comment by tcitworld** [comment]
> Calendar name and color is shared just like the events in it, so any changes should be the same for all people. And if someone with edit permissions changes the color, it should be changed accordingly.

Unfortunately that's not the case, any sharee can set their own properties (such as calendar name and color) for any calendar that was shared with them, or am I missing something?

**Comment by georgehrke** [comment]
> Unfortunately that's not the case, any sharee can set their own properties (such as calendar name and color) for any calendar that was shared with them, or am I missing something?

No, you are right. But that's the expected behavior for me. As a user I definitely want to be able to change the color, so it doesn't overlap with a color of my own calendars. (Especially as the default calendar has a fixed color)
