### ISSUE TITLE
Use the arrow to save the event?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/calendar#2291]
**Is your feature request related to a problem? Please describe.**
I find it strange to always having to scroll down in the normal edior to and press the save button in order to save the event

**Describe the solution you'd like**
Why not making that arrow saving the event?

**Describe alternatives you've considered**
maybe remove that arrow and add a save button there?

**Additional context**
I am talking about that arrow:
![image](https://user-images.githubusercontent.com/42591237/83273564-eb38f400-a1cc-11ea-9fa1-c201bb850f58.png)

**Comment by georgehrke** [comment]
@nextcloud/designers 

I would actually opt for "remove arrow and leave it empty", because clicking it does not immediately change the title and might give a wrong sense of "something happened"

**Comment by szaimen** [comment]
And what about removing that arrow AND putting a save button next to the input field on the right to save the event? 

I think it is a bit odd always having to scroll down to save the event - the save button is currently not good visible down there, imho.

**Comment by jancborchardt** [comment]
@georgehrke sounds good!

And yes, regarding @szaimen’s remark about the Save/Update button: That should always be visible, that is sticky on the bottom of the viewport when the content is longer.

**Comment by georgehrke** [comment]
> And yes, regarding @szaimen’s remark about the Save/Update button: That should always be visible, that is sticky on the bottom of the viewport when the content is longer.

There is a separate issue about this in https://github.com/nextcloud/calendar/issues/1960
