### ISSUE TITLE
Calendar Becomes Distorted if long task name is used

### ISSUE THREAD

**Issue by compgeniuses** [nextcloud/calendar#2303]
The clandar view for items created on a calendar, becomes distorted if the name of the calendar item is very long.

This makes it even harder to clode the popup window, as well as to scroll up and view other items.

Maybe the best thing to do is, when the name is long, on the popup view, only show a select numbe rof sentences, and the rest to be visible when the full view is selected

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md)

Unless you fill out the issue template completely including all logs, we can't go ahead and help you.
