### ISSUE TITLE
New Setting panel

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#2304]
Bottom left is getting too crowded.

Needs to handle 
- Existing settings
- Defining a default calendar for creating new events https://github.com/nextcloud/calendar/issues/1835
- Free/Busy view https://github.com/nextcloud/calendar/issues/39
- Customize reminder type for automatically generated birthday events #130?

**Comment by georgehrke** [comment]
There is a WIP PR by Marco in the nc/vue repo: https://github.com/nextcloud/nextcloud-vue/pull/1286

**Comment by szaimen** [comment]
Lets continue in https://github.com/nextcloud/calendar/issues/5892 :)
