### ISSUE TITLE
Calendar sharing not possible

### ISSUE THREAD

**Issue by ml94** [nextcloud/calendar#2309]
### Steps to reproduce
1. New install of Nextcloud 19.0.0
2. Install of Calendarapp 2.0.3
3. Import and create new Calender from ICS
4. Sharing symbol is not visible.

### Expected behaviour
I will share my calendar to another Group.

### Actual behaviour
Nothing. Sharing symbol is not visible.

### Calendar app
Calendar app version: 2.0.3

### Client configuration
Browser: Firefox 77.0.1
Operating system: Windows 10

### Server configuration
Operating system: Ubuntu 20.04
Web server: Nginx 
Database: MariaDB
PHP version: 7.4.3
Nextcloud Version: 19.0.0

Complete new fresh install.

**List of activated apps:
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_notifications: 1.0.2
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - dav: 1.15.0
  - deck: 1.0.2
  - documentserver_community: 0.1.5
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - groupfolders: 6.0.6
  - impersonate: 1.6.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.5.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 4.2.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - side_menu: 1.7.0
  - support: 1.2.1
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - unsplash: 1.1.6
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - contactsinteraction
  - encryption
  - files_external
  - firstrunwizard
  - survey_client
  - systemtags
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***,
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwriteprotocol": "https",
        "logtimezone": "Europe\/Berlin",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "skeletondirectory": "",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "app_install_overwrite": [
            "admin_notifications",
            "documentserver_community"
        ],
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Comment by georgehrke** [comment]
If you have an Adblocker installed, please disable it for Nextcloud.

**Comment by ml94** [comment]
Ok, that was a quick fix. It works. Thank you!
Do you know the reason why the adblocker only blocks the share symbol?

**Comment by tcitworld** [comment]
You must have a list inside your Adblocker that is a little agressive and blocks everything that contains the `share` word, including this icon.
