### ISSUE TITLE
Calendar entry marked as busy is als busy for creator

### ISSUE THREAD

**Issue by bkolbe** [nextcloud/calendar#231]
Calendar shows only Busy when selecting as Busy. Also for the creating user. The creating user should see the Calendar-Item with full information

### Steps to reproduce
1. Create an Calendar item
2. Create Name "Test Meeting"
2. set "when shared show only busy"
3. Now the creator can only see "busy" not "Test Meeting". that is incorrect

### Expected behaviour
The creator should see "Test Meeting"

### Actual behaviour
The Calendar entry is changed to busy also for the creator

### Server configuration
Centos 7

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
php56
**Server version:** (see your admin page)
11.0.0
**Calendar version:** (see the apps page)
1.4.1
**Updated from an older installed version or fresh install:**
update from 10.0.2
**Signing status (ownCloud/Nextcloud 9.0 and above):**
Nextcloud
```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ldap

### Client configuration
**Browser:**
Chrome, Firefox

**Operating system:**
Windows, Lnux

**CalDAV-clients:**

d

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by georgehrke** [comment]
also please mention who created the calendar

**Comment by bkolbe** [comment]
I opend in server, and they say i have to reponen in calendar?

**Comment by georgehrke** [comment]
Please link the issue in the server repo :)

**Comment by tcitworld** [comment]
https://github.com/nextcloud/server/issues/2787
