### ISSUE TITLE
Change primary calendar

### ISSUE THREAD

**Issue by Natureshadow** [nextcloud/calendar#2323]
**Is your feature request related to a problem? Please describe.**

Events I am invited to always end up in the same hard-coded calendar. I once had two calendars — the one  created by Nextcloud for private events, and another one for personal business events. I have since moved the first one to a private Nextcloud and do not want to use this calendar anymore, and invitations directed to me on the Nextcloud in question all are business events.

Even worse (please open this as a security issue if you consider that necessary), if I delete that calendar, Nextcloud automatically chooses the enxt best calendar for upcoming invitations, *even if that calendar is shared or public*, thus leaking all invitations.

**Describe the solution you'd like**

I'd like to have a menu entry in the calendar context menu to choose a different primary calendar for invitations.

**Comment by georgehrke** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/1835
