### ISSUE TITLE
import: color icon cut off for long calendar names

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/calendar#2324]
### Steps to reproduce
1. create calendar with a long name (in my case, another user also shared that calendar with me, adding the username in the end)
2. import an .ics calendar to it

### Expected behaviour
the calendar should show the color icon on the left, aligned with other calendars

### Actual behaviour
color icon is cut off, looks weird:
![calendar prob](https://user-images.githubusercontent.com/28591861/84085736-8197c180-a9e6-11ea-876d-ceb10a779fdd.jpg)

### Calendar app
**Calendar app version:**  2.0.3

### Client configuration
**Browser:**  Firefox 77.0.1

**Operating system:** Linux Mint

### Server configuration

**Nextcloud Version:** 18.0.2

**Updated from an older installed version or fresh install:** updated

-------- please ask if u need more info ---------------

**Comment by georgehrke** [comment]
Pull-request: https://github.com/nextcloud/calendar/pull/2325
