### ISSUE TITLE
l10n: String not available at Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/calendar#2326]
https://github.com/nextcloud/calendar/blob/22e5c8199a2a463aff0ea3484d765f7521bffe6d/src/components/AppNavigation/Settings/SettingsImportSection.vue#L31

At release v19.0.0 and app v2.0.3 english string is visible on german UI.

**Comment by georgehrke** [comment]
Ah yes, @Valdnet mentioned that before. I thought i had fixed it already.

It's not properly extracted from the source, because we use the string once with translateSingular and once with translatePlural and somehow transifex or our extraction script is not too fond of that.

**Comment by georgehrke** [comment]
Pull-request: https://github.com/nextcloud/calendar/pull/2327

**Comment by rakekniven** [comment]
Damn, you are quick.

Thank you.
