### ISSUE TITLE
Reminder are not send to subscribers

### ISSUE THREAD

**Issue by pixi** [nextcloud/calendar#2329]
### Steps to reproduce
1. Create an cal-entry, either in NC web or any macOS cal
2. Set the reminder to anything (Notification or Email)
3. Wait for the sync…

### Expected behaviour
ANY reminder should appear in the subscription the same way as it is set in the master

### Actual behaviour
Nothing happens! NO reminder appears

### Calendar app
**Calendar app version:** 2.0.3

**CalDAV-clients used:**  macOS Calendar

### Client configuration
**Browser:** latest Brave

**Operating system:** 10.13.6

### Server configuration

**Operating system**: Linux 4.4.0-179-generic #209-Ubuntu

**Web server:**  Apache

**Database:** MySQL 5.7.28

**PHP version:** 7.4

**Nextcloud Version:** 18.0.6

**Updated from an older installed version or fresh install:** Updated

**List of activated apps:**

Activities for shared file downloads	1.7.0		
Activity	2.11.0
Auditing / Logging	1.8.0
Calendar	2.0.3
Comments	1.8.0
Contacts	3.3.0
Deleted files	1.8.0
File access control	1.8.1
File sharing	1.10.1
Notifications	2.6.0
Piwik/Matomo Tracking	0.5.4		
Privacy	1.2.0
Right click	0.15.2
Share by mail	1.8.0
Social sharing via email	2.0.0
Theming	1.9.0

**Nextcloud configuration:**

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
    1 => '',
  ),
  'datadirectory' => '/www/htdocs/',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '18.0.6.0',
  'dbname' => '',
  'dbhost' => '',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'appstoreenabled' => true,
  'updater.release.channel' => 'stable',
  'maintenance' => false,
  'loglevel' => 2,
  'mail_from_address' => '',
  'mail_smtpmode' => 'sendmail',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => '',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'mail_sendmailmode' => 'pipe',
  'mysql.utf8mb4' => true,
  'updater.secret' => '',
);

**Comment by georgehrke** [comment]
Please provide logs and tell us what cron mode you are using

**Comment by pixi** [comment]
> Please provide logs and tell us what cron mode you are using
Ok, what logs and where do I find them?

I am using "Cron (Use system cron service to call the cron.php file every 5 minutes.)" in NC and the cronjob settings of all-inkl. There the "HTTP user" and "HTTP password" is set.


If I just call NCs cron.php I get:
"{"data":{"message":"Backgroundjobs are using system cron!"},"status":"error"}"

If I call an other script in the same dir with the content:
<?php
exec("php ./cron.php  2>&1", $out, $result);
echo "Returncode: " .$result ."<br>";
echo "Ausgabe des Scripts: " ."<br>";
echo "<pre>"; print_r($out);
?>

I get:
Returncode: 0
Ausgabe des Scripts:

Array
(
)
"
but nothing happens.
But this tells me that scripts in this dir are executable by the system, cron.php just doesn't perform as expected.

**Comment by pixi** [comment]
btw, if I run `php cron.php` from the CLI inside the dir nothing happens either

**Comment by georgehrke** [comment]
You can find a `nextcloud.log` inside the data directory.

If you go to the cron section in the Nextcloud admin settings, when does it say that the cron-job was last executed? 
How often did you configure the cron-job to run?

**Comment by pixi** [comment]
The last two lines in the log:
{"reqId":"-ID-","level":3,"time":"2020-06-15T19:12:48+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"opendir(/tmp): failed to open dir: Permission denied at /www/htdocs/wUser/cloud/lib/private/TempManager.php#190","userAgent":"--","version":"18.0.6.0"}
{"reqId":"-ID-","level":3,"time":"2020-06-15T19:20:32+00:00","remoteAddr":"-IP-","user":"--","app":"PHP","method":"GET","url":"/cron.php","message":"opendir(/tmp): failed to open dir: Permission denied at /www/htdocs/wUser/cloud/lib/private/TempManager.php#190","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","version":"18.0.6.0"}

Even if I set the TempManager.php to 777 it doesn't change. Butit seems that it has something to do with the "tmpBaseDir".
I have the app (cloud) and the data (cloudData) in two different dir in the same root.


> If you go to the cron section in the Nextcloud admin settings, when does it say that the cron-job was last executed?

Two days ago, when I tried it last time (via CLI).


> How often did you configure the cron-job to run?

You mean the interval? First every 15 mins, then every 5 mins.

**Comment by georgehrke** [comment]
Well, your cron is not properly configured. So it's no surprise that you don't receive any notifications if the Nextcloud instance is not configured correctly.

> Even if I set the TempManager.php to 777 it doesn't change.

You don't have to change the permission of `TempManager.php`, but of the `/tmp` folder.

---

This is no bug report, but a support question. Please ask your question at https://help.nextcloud.com

There are already other people reporting similar error messages related to All-Inkl:
https://help.nextcloud.com/t/hosting-bei-all-inkl-com-erfahrungsaustausch/3347

**Comment by pixi** [comment]
This is put into the config.php
  'tempdirectory' => '/www/htdocs/wUser/tmp',
and the dir created has wUser/777 set but the error still exists.

Besides that, the cron-problem is not the bug in question! Calendar entries DO get transfered to subscribers. But the reminders within such an entry do NOT.

**Comment by georgehrke** [comment]
> Besides that, the cron-problem is not the bug in question! 

Notifications for Calendar events are send in the background cron-job. If it's not properly configured, no notifications will be sent.

> A reminder is e.g. something like "remind me 2 hours before this event happens"! This is run by the OS and not NC.

If the exported ics contains an `BEGIN:VALARM ... END:VALARM` block and your Calendar application on your Desktop / mobile device does not show you a reminder when you set an alarm to "Notification", then it is a bug in the desktop / mobile app.
Reminders of type "Email" are always handled by Nextcloud and require a properly configured cron.

**Comment by pixi** [comment]
> Notifications for Calendar events are send in the background cron-job. If it's not properly configured, no notifications will be sent.

You mean each alarm to any subscriber is sent by MY NC-installation? What if they're ofline? They don't get any reminders althought set in the event?


> If the exported ics contains an…

No, it does not!!! That is the issue I try to communicate. See screenshot below: the data a subscriber receives is missing the alarm.
No matter if the system runs properly or not it should appear in the ics-code, right?


These are the screenshots from an event.
NC-Webinterface:
![01_NC_Web_Source](https://user-images.githubusercontent.com/7418913/84703832-2d965b00-af59-11ea-958d-8e666be337f8.png)


NC in iCal - Source (even when I create an even in iCal the reminder gets transfered to the Web-Cal 
![02_NC_iCal_Source](https://user-images.githubusercontent.com/7418913/84703836-2ec78800-af59-11ea-9829-6e47c60c3f46.png)


NC in iCal - Subscriber
![03_NC_iCal_Subscriber](https://user-images.githubusercontent.com/7418913/84703840-2f601e80-af59-11ea-8f35-beb053e6255b.png)

**Comment by georgehrke** [comment]
Sorry for the misunderstanding, now I fully understand what you mean with Subscriber.

Nextcloud automatically removes alarms from read-only calendars, because most clients (including but not limited to the very popular Thunderbird Lightning plugin) need write access in order to acknowledge the receival of an alarm. So if you have reminders in a read-only calendar, you end up being spammed by alarms that you can't turn off.

**Comment by pixi** [comment]
How can I change that?
It doesn't make much sense to let ppl subscribe for events and then they can't get a reminder. I get complains from ppl. for not getting reminded!

Creating a rw-calendar means they can change the content of my events, right? And this would als require an account?

**Comment by georgehrke** [comment]
> How can I change that?

If you really want to remove it, comment out these lines:
https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalendarObject.php#L72L75

> Creating a rw-calendar means they can change the content of my events, right? And this would als require an account?

Yes and yes.

**Comment by pixi** [comment]
Ah, we're making progreess now! ;o)
I removed those lines completely. What does it take for coming into effect?

**Comment by pixi** [comment]
Btw, adding all-day events takes over a "Default" reminder, 09:00 the day before, but, again, not the individual reminder.

I'd love to change that default time too! Where can I do that?

And, most important: will the changes in the CalendarObject.php remain during NC-updates?

**Comment by pixi** [comment]
Does this have an influence on displaying the alaram?

https://github.com/nextcloud/server/blob/4cff3a3a86b726f1863da9196d8a7cb2a425785f/apps/dav/lib/CalDAV/CalendarObject.php#L137

**Comment by dumblob** [comment]
@pixi did you solve the all-day reminder issue? If so, how?
