### ISSUE TITLE
Phrasing "Settings" on public page is confusing

### ISSUE THREAD

**Issue by Phyks** [nextcloud/calendar#233]
Hi,

### Steps to reproduce
1. Add a calendar, share it publicly.
2. On the public URL of the calendar, try to access to the matching ICS file, to feed it into some external tool such as Google Agenda.

### Expected behaviour

There is no way to directly access (easily) the URL of the ICS file. I would have expected to have something like an input field with the URL of the ICS file somewhere, besides the "Download" button.

### Actual behaviour

The only solution I could find is to actually download the file, and rely on my browser to get the source URL of the ICS file, which is highly unpractical, and especially tricky for non-tech users.

### Server configuration

Latest version of NextCloud and calendar app as of today. The rest does not seem to be relevant for this issue.

Thanks!

**Comment by tcitworld** [comment]
To access the file, you can just click on the WebCal button on the public page and take the URL which has changed just below.

**Comment by Phyks** [comment]
Not sure, I guess this is "Parameters" in the left bottom corner, then "WebDAV" and then the URL in the field below. Indeed, this works and matches the expected behavior.

Still, it is quite difficult to find and a user might not go into the "Parameters" menu to get the ICal URL.

**Comment by georgehrke** [comment]
Yes, the label "Settings" is misleading. We should change it.

What about something like "Embed & Sync"?
Open for suggestions ;)

**Comment by jancborchardt** [comment]
Maybe best would be »Subscribe«? :)

**Comment by Phyks** [comment]
"Subscribe" does not convey the idea of embedding, provided by the iframe code. "Embed & Sync" looks nice. Or maybe two panels, one for "embed" and one for "sync"?

By the way, the "iCal" panel is called "WebDAV". Not sure it is explanatory enough for most people. Actually, I would not have realized that WebDAV was actually a standard iCal sharing. Maybe this could be renamed as well something like "iCal" or "ICS"? I think that will speak much to people, as they often have buttons to add "ICS file" or "iCal feed" to their calendar.

Finally, the default view in the current "Settings" panel is the "CalDAV" link. I think this behavior is a really good default for the private view (that is the calendar view behind authentication) because most likely users will be looking for a way to sync their agenda both ways, relying on standard protocols. However, when sharing an agenda with a public link, I think the need changes a bit and they will most likely want to sync it unidirectionnally to their own calendar, through an iCal feed. So I would put the current "WebDAV" as the default one.

Hope this helps :)

**Comment by georgehrke** [comment]
Oh, WebDAV is the wrong word. It's supposed to be WebCal

**Comment by georgehrke** [comment]
I have to agree with @Phyks that "Subscribe" does not convey the idea of embedding.
But I also favor Subscribe over Sync, so what's about:
»Embed & subscribe« ?
:)

**Comment by jancborchardt** [comment]
@georgehrke Embedding is not as important as Subscribe and it also comes later in the list, so let’s call it »Subscribe & embed«. :)

**Comment by Phyks** [comment]
@georgehrke Is there a specific reason to use the phrasing "WebCal" rather than "iCal" typically? I have typically in mind Google Calendar and Thunderbird with a link to "Add a calendar through an URL" explictly specifying "in iCal" format in the popups. I guess iCal is something that would mean more than Webcal for most people.

**Comment by georgehrke** [comment]
[WebCal](https://en.wikipedia.org/wiki/Webcal) is probably a more techie term. There is also this unofficial, yet very broadly used `webcal://` protocol to link to these ics files.

Anyway, I'm not really passionate about calling it »WebCal«. As long as we keep it consistent with other places in the app, I'm fine with a different name. Although I would prefer »iCal Feed« over »iCal«.

@jancborchardt What do you think about this?

**Comment by jancborchardt** [comment]
@georgehrke how is it called in most of the apps where you would paste that link? »iCal« I assume? So let’s change it to that, no?

**Comment by georgehrke** [comment]
There is no real consistent name.

<img width="1130" alt="google" src="https://cloud.githubusercontent.com/assets/1250540/22240506/d66a989a-e21b-11e6-806e-8d0ac7a13ab4.png">
<img width="624" alt="icloud" src="https://cloud.githubusercontent.com/assets/1250540/22240505/d66a94b2-e21b-11e6-8737-c8baca48a1b7.png">

**Comment by georgehrke** [comment]
As I said earlier, I'd prefer »iCal Feed« over »iCal« because - with feed in it - it automatically suggests that the content of this link updates over time.

**Comment by georgehrke** [comment]
it's still called settings, will fix that.

**Comment by jancborchardt** [comment]
Fixed by #319
