### ISSUE TITLE
Attendees for new meeting in shared calendar won't get notified if the calendar belongs to another account

### ISSUE THREAD

**Issue by blue995** [nextcloud/calendar#2340]
### Steps to reproduce
1. Correctly configured email server
2. You need two user accounts that belong to the same user group (e.g. "_user1_", "_user2_" in group "_test-group_")
3. Login as _user1_
4. Create a calendar _testcalendar_ and share it with _test-group_ (activate "can edit")
5. Login as _user2_
6. Create a meeting in _testcalendar_ and invite _user1_

### Expected behaviour
_user1_ should reveive an invitation email.

### Actual behaviour
_user1_ receives nothing, because _user2_ does not own the _testcalendar_ calendar. If _user1_ creates a meeting and invites _user2_ the notifications work as expected.

### Calendar app
**Calendar app version:** 2.0.3

### Client configuration
**Browser:** Chrome 83.0.4103.97

**Operating system:** Windows 10

### Server configuration

**Operating system**: Arch Linux

**Nextcloud Version:** 18.0.6

I use the [nextcloud:18.0.6](https://hub.docker.com/layers/nextcloud/library/nextcloud/18.0.6/images/sha256-08788012e3fb18e97082a55177498ff5c7af77de0f4847eceb9419999bf478e5?context=explore) docker image with docker-compose.

**Updated from an older installed version or fresh install:** Updated from 18.0.4

**List of activated apps:**

```
  - accessibility: 1.4.0
  - announcementcenter: 3.7.0
  - breezedark: 18.0.19
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - groupfolders: 6.0.6
  - groupquota: 0.1.2
  - impersonate: 1.5.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - registration: 0.4.7
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "18.0.6.0",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "file",
        "logfile": "nextcloud.log",
        "loglevel": "0",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

#### Log file (data/nextcloud.log)

**Nothing** interesting here. I expect something like  `Sent mail to "Array ( [****@***.***] => My Name ) " with subject "My Subject"`.

#### Browser log

Nothing interesting there.

**Comment by blue995** [comment]
If you cancel the event, each attendee will receive an email as expected.

`Sent mail to "Array ( [*******@***.***] => My Name ) " with subject "Cancelled: Test"`

**Comment by georgehrke** [comment]
See https://docs.nextcloud.com/server/19/user_manual/pim/calendar.html#invite-attendees-to-an-event

> Only the calendar owner can send out invitations, the sharees are not able to do that, whether they have write access to the event’s calendar or not.
