### ISSUE TITLE
Copy & Search

### ISSUE THREAD

**Issue by Beta0815** [nextcloud/calendar#2355]
Hi,

first, the App great, really.
But I miss the function to copy entries and "Search"

Is this planned in the near future?

Greetz

**Comment by georgehrke** [comment]
@Beta0815 When opening feature requests, please
(1) use the issue template
(2) create one issue per enhancement
(3) and search for existing issues!

**Comment by georgehrke** [comment]
Duplicate of #113 
Duplicate of #8
