### ISSUE TITLE
Wrong Abo Link

### ISSUE THREAD

**Issue by dominik34** [nextcloud/calendar#2358]
### Steps to reproduce
1. I want to share a Calendar as a webcal link
2. I click on "Share over Link" and on "Copy Abo Link

### Expected behaviour
I should get a Link like: https://mynextcloud.de/remote.php/dav/calendars/myusername/mycalendar (webcal-adress)

### Actual behavior
I'm getting the Link to download the .ics file:
https://mynextcloud.de/remote.php/dav/public-calendars/8GBydmLmdF6bPNKe?export

I think there is a wrong link deposited or its an translation bug because I'm using the German version.
The only way, getting the right "webcal Abo Link" as shown above, was by using the "Linkshare" Link and copying the Abo-Link from there. Because there the right webcal Link is deposited.

In my opinion the calendar-sharing options should be revised and mainly a bit different described to be more clearly which Link I will get whether I click on something....

I hope you're understanding my bad English and could fix this probably wrong link.

### Calendar app
Calendar app version: 2.0.3
Nextcloud Version: 18.0.6

**Comment by tcitworld** [comment]
The link is correct.

A webcal link is basically a link to a public ics file. The ics file will get updated when new events are added to the calendar.

**Comment by georgehrke** [comment]
As @tcitworld already pointed out, the link is correct.

> I should get a Link like: https://mynextcloud.de/remote.php/dav/calendars/myusername/mycalendar (webcal-adress)

This is not a webcal address, but the caldav address, which requires login via username and password.

> I'm getting the Link to download the .ics file:
> https://mynextcloud.de/remote.php/dav/public-calendars/8GBydmLmdF6bPNKe?export

Maybe there is a misunderstanding about what webcal is here, but that's exactly what webcal is: A simple link to an ics file.
Just copy that link into your calendar client (Whether that's Nextcloud, macOS/iOS calendar, ICSx⁵, etc.). It will regularly refetch the ICS file and show you the updated content.
