### ISSUE TITLE
Use autosize for location and description textareas

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#237]
Currently when you have a description or long location in the details sidebar, there will be scrolling inside of the scrollable sidebar. This is very ugly. ;)

Instead we should use autosize.js here just like in the Mail app: https://github.com/jackmoore/autosize

Might even be a possibility to consider for inclusion in the server since we should avoid having text fields scroll like that. cc @nextcloud/javascript

**Comment by georgehrke** [comment]
Did you try 1.4.1 or master?
we just introduced autosize in master 
https://github.com/nextcloud/calendar/pull/227

**Comment by jancborchardt** [comment]
I tested it in production, not master. So nice work! :)

Btw there is another textarea, the iframe one in the public share link, does this also work for that one? And does really _every_ textarea in the Calendar app now have autosize and `resize: none`?

**Comment by georgehrke** [comment]
I don't think autosize is important for the embed textfield. Most users don't understand the content of the embed field anyway. They are just supposed to copy it.

**Comment by georgehrke** [comment]
@jancborchardt ^ 

Please comment.

**Comment by georgehrke** [comment]
Closing.

All important ones have autosize.
The embed one doesn't need autosize in my opinion, because it will add a huge, not editable textarea to the interface. Furthermore most users don't understand the content of the embed textarea anyway, there are just supposed to copy&paste it somewhere.
