### ISSUE TITLE
Please add a button to delete a date earlier

### ISSUE THREAD

**Issue by sputnick-dev** [nextcloud/calendar#2372]
To remove a date, now it's very annoying.

You have to
 - click 'date'
 - click 'Plus'
 - click '(...)'
 - then remove the 'date'

SoGo have a better feature, when you first open the date, you can directly delete the date at this step.

Think of people with disabled finger, dividing clicking by 2 will be very helpful

Alternative way: enabling keyboard 'delete' button after clicking on a date

**Comment by georgehrke** [comment]
Duplicate of #1570
