### ISSUE TITLE
Animation for event details sidebar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#238]
Currently the right sidebar just appears. That’s very janky.

Instead, we should do it like in the Files app and have the same slide animation. @nextcloud/calendar – ideally it should be done in the server so that every time the sidebar appears in any app, it’s nicely animated. cc @nextcloud/javascript

**Comment by skjnldsv** [comment]
@jancborchardt can we use css instead? Like the slide animation of the menu on mobile?

**Comment by georgehrke** [comment]
There is a proper animation, but it only works the first time.

**Comment by arunikayadav42** [comment]
Is somebody working on this or can I please get started with this for my rgsoc 2018?

**Comment by skjnldsv** [comment]
@arunikayadav42 please do :)

**Comment by arunikayadav42** [comment]
@skjnldsv okay!thanks

**Comment by arunikayadav42** [comment]
Can anybody please help me get started with this issue?

**Comment by arunikayadav42** [comment]
Do I need to know scss for to solve this issue,please tell :)

**Comment by georgehrke** [comment]
This issue actually needs some debugging to find out whether it's a simple SCSS issue or actually some issue in our angularJS / javascript code.

**Comment by arunikayadav42** [comment]
so do I need to work on it or pick some other issue?

**Comment by georgehrke** [comment]
@tcitworld This seems to be related to the router view somehow. 
AppSidebar contains a transition itself.

Do you have any idea?

**Comment by tcitworld** [comment]
I don't see any. I'll have a deeper look later.

**Comment by georgehrke** [comment]
@tcitworld Were you able to figure out what's going wrong? :)

**Comment by georgehrke** [comment]
@tcitworld Move to 2.0.1?

**Comment by tomharristech** [comment]
This animation only works for me when I press the close on the sidebar - not when I click an event and the sidebar appears.
Nextcloud 17.0.0 Calendar 2.0.1 Firefox 72.0.1
