### ISSUE TITLE
first day of week

### ISSUE THREAD

**Issue by markushub** [nextcloud/calendar#2383]
**Is your feature request related to a problem? Please describe.**
In Germany the first day of week is the Monday. My nextcloud 18.0.6 with Calendar 2.0.3 says Sunday.
My language setting is German.

**Describe the solution you'd like**
Please detect the first day of week by language settings

**Describe alternatives you've considered**
no idea.

**Additional context**

**Comment by georgehrke** [comment]
What did you set the locale to?

**Comment by markushub** [comment]
I set to german without cramp
"Gebietsschema: Deutsch"

It comes "Die Woche startet am Montag" but in the month overview it starts with Sunday

**Comment by markushub** [comment]
I tried "Deutsch (Deutschland)" same effect

**Comment by georgehrke** [comment]
Duplicate of #1844 in that case.
