### ISSUE TITLE
Readable links for public calendars

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#239]
I shared a public link to our [Open Source Design](http://opensourcedesign.net) calendar at https://github.com/opensourcedesign/events/issues/49#issuecomment-267208684 and as you can see the link looks pretty strange:
https://cloud.nextcloud.com/apps/calendar/public/MIFAFLFJADIVX63I

Much nicer would be:
https://cloud.nextcloud.com/apps/calendar/public/opensourcedesign

It would be great if for calendars shared via link there’s a possibility to make the link look good like that. @nextcloud/calendar

**Comment by eppfel** [comment]
Also, I would like to improve the workflow to subscribe to public calendars. Right now, you have to go to the public calendar and click settings to get a URL you can subscribe to.

The public interface will mainly be used by non-nextloud users, so I propose removing the settings here (they are not saved anyway) and move the options directly under the calendar (to the download button).

Something like this:

<img width="966" alt="bildschirmfoto 2016-12-15 um 10 34 10" src="https://cloud.githubusercontent.com/assets/1899308/21218754/18bc47fe-c2b2-11e6-9b43-8a13dd219a5f.png">

Or would it even be possible to subscribe to the public share link with a redirect to the dav address?

**Comment by georgehrke** [comment]
We had this discussion in core ....
https://cloud.nextcloud.com/apps/calendar/public/opensourcedesign is guessable way to easy.

cc @LukasReschke

**Comment by jancborchardt** [comment]
@georgehrke so this would not be default of course. And with changing it comes the knowledge that it’s probably guessable. But in some cases you really want it to be guessable or at least rememberable or nice looking, because it is public anyway. :)

**Comment by LukasReschke** [comment]
Not a fan of choosable stuff. What would be okay for me is actually to have somewhat nice links by having /$identifier/$whateverPersonWants, for example /apps/calendar/public/JAKAOEN/opensourcedesign. The last thing we wouldn't even have to check as we could accept anything. (Google and Dropbox cheat on nice links like that as well)

In any enterprise environment scenario this feature would be contra productive. Ok for some home users but not really scaleable.

**Comment by georgehrke** [comment]
> Not a fan of choosable stuff. What would be okay for me is actually to have somewhat nice links by having /$identifier/$whateverPersonWants, for example `/apps/calendar/public/JAKAOEN/opensourcedesign`.

I like this idea by Lukas. We could automatically append the displayname (or uri) to the url.
@jancborchardt What do you think about this? :)

**Comment by eppfel** [comment]
>  /$identifier/$whateverPersonWants

I guess the contradiction is that we want it to be guessable, so you could actually remember it.
A public calendar for the purpose of being "really" public will be post and crawled anyway... IMO

**Comment by eppfel** [comment]
Just realizedy, you discussed this at hack week, I guess :grin:
