### ISSUE TITLE
Add "Pick a time" button to change the view to time-picker

### ISSUE THREAD

**Issue by rubo77** [nextcloud/calendar#2395]
When creating lots of new not-all-day entries on a certain day it would be handy to save some clicks:

If we always have a "Pick a time" button, that would uncheck "all day", then you could directly select the desired time.

**Comment by georgehrke** [comment]
Instead of adding more buttons we have to fix the actual problem:
If you click the part of the input field, where it shows the time, it should automatically open the time-picker instead of the date-picker.

See #1576
