### ISSUE TITLE
Week starts on Monday by new event calander picker

### ISSUE THREAD

**Issue by noecom12** [nextcloud/calendar#2397]
**Is your feature request related to a problem? Please describe.**
In the settings start the week on monday. By the New event calander picker not (see picter) 

**Describe the solution you'd like**
When the settings (***/nextcloud/index.php/settings/user) say the week start at monday. in the new event calader picker start it on monday.

**Describe alternatives you've considered**

**Additional context**

![Naamloos](https://user-images.githubusercontent.com/45128098/87476135-2af55700-c626-11ea-971c-f61b3fbe7200.png)

**Comment by georgehrke** [comment]
Already fixed in https://github.com/nextcloud/calendar/pull/2286
