### ISSUE TITLE
Turning off Activity and Groupware notification settings do not prevent android and iOS notifications.

### ISSUE THREAD

**Issue by SLYtiger16** [nextcloud/calendar#2398]
### Steps to reproduce
1. Disable All Calendar notifications in the Admin -> Settings -> Groupware -> Calendar Server area
2. Disable All Calendar notifications in the Admin -> Activity area
3. Alter/Create a Calendar event

### Expected behaviour
No notification or activity should occur

### Actual behaviour
Activity stream is not altered, Event notifications are still sent via push notification and notification app to all users the Calendar is shared with.

### Calendar app
**Calendar app version:** 2.0.3

**CalDAV-clients used:** NA

### Client configuration
**Browser:** Chrome / New MS Edge / Android / iOS

**Operating system:** Various

### Server configuration

**Operating system**: Ubuntu Server 20.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 19.0.0

**Updated from an older installed version or fresh install:** This has been regularly updated via stable channel since May with 18.

**List of activated apps:**
I will update later if needed. Not easy to access.

**Nextcloud configuration:**
I will update later if needed. Not easy to access.

#### Web server error log (e.g. /var/log/apache)
I will update later if needed. Not easy to access.

Insert your webserver log here
I will update later if needed. Not easy to access.

#### Log file (data/nextcloud.log)
I will update later if needed. Not easy to access.

Insert your nextcloud.log file here
I will update later if needed. Not easy to access.

![image](https://user-images.githubusercontent.com/36513817/87572208-d2a76f00-c690-11ea-9e73-1469978683f7.png)
![image](https://user-images.githubusercontent.com/36513817/87572438-244ff980-c691-11ea-87cf-94100d52abb5.png)

Despite the settings above: Android and iOS are blasted with notifications as events are changed.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md)

Unless you fill out the issue template completely including all logs, we can't go ahead and help you.

**Comment by SLYtiger16** [comment]
@georgehrke Will that work? The system is on a locked down vm, very hard to get files off of it, but I can if absolutely necessary

**Comment by georgehrke** [comment]
> Activity stream is not altered, Event notifications are still sent via push notification and notification app to all users the Calendar is shared with.

Can you elaborate what exact kind of notification you are receiving?
Reminders for events? Notifications about changes to the calendar?

**Comment by SLYtiger16** [comment]
@georgehrke  All of my users ... 50 or so right now are receiving push notifications for event changes like title edits and description edits and event creation.

**Comment by georgehrke** [comment]
You probably have https://apps.nextcloud.com/apps/event_update_notification installed, right?

**Comment by SLYtiger16** [comment]
@georgehrke shoot... I do.....

**Comment by SLYtiger16** [comment]
@georgehrke Yes it does seem to be working as expected now. Thank you, seems kind of obvious now but, but why is there an extra pp instead of a setting?

**Comment by favincen** [comment]
I experienced the same issue (very annoying at scale!), and solved it thanks to this thread.
But I second SLYtiger16's remark: why is there an extra app instead of a setting?
Or at least, why is there no indication in the settings that this application will keep sending notifications even if all notifications are disabled in the setting ? This is not a technical issue, but it is definitly an ergonomic and UX issue !
