### ISSUE TITLE
make calendar visible when selecting it in editor

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#24]

**Comment by georgehrke** [comment]
requires #209

**Comment by tcitworld** [comment]
Details ?

**Comment by georgehrke** [comment]
If you create/edit an event and select a calendar, that's currently disabled, it should be automatically enabled, so you can see other events in the calendar and make sure it does not conflict with them.

Also new/edited events just disappear at the moment, when the corresponding calendar is hidden. This can be very confusing to users.
