### ISSUE TITLE
Show proper emptycontent view for non-existing public calendar links

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#240]
Currently when you go to https://cloud.nextcloud.com/apps/calendar/public/non-existing-calendar there’s just an empty calendar. This calendar does not actually exist and there should be indication of that. Instead of the calendar view on the right, there should be an emptycontent-like view similar to the Files app for empty folders. :)

Saying something like:

> [icon-calendar]
> **Calendar does not exist**
> Maybe the link is wrong?

cc @nextcloud/calendar

**Comment by georgehrke** [comment]
Hm, definitely a good point, but I think we should go with an overlay.
The problem here is, that the php side of the calendar app can't determine whether or not a calendar exists. We first have to send a request to the CalDAV server to then see: Oh, it's a 404

**Comment by jancborchardt** [comment]
Yup, overlay is fine too. :) The important thing is that the basic style of the emptycontent is used, and there is actual feedback.
