### ISSUE TITLE
Highlighted horizontal lines in day/week view don't align with whole hours

### ISSUE THREAD

**Issue by laurens94** [nextcloud/calendar#2412]
### Steps to reproduce
1. Set the view selection to Day or Week view
2. Open the Settings & import panel
3. Set the slotDuration settings to 5 or 10 minutes

### Expected behaviour
I would expect the horizontal grid lines that align with the whole hour (e.g. 12 am, 1am etc.) to be visually more clearly than the other lines (e.g. 12:15, 12:30 etc.). 

This is sort of the case in the 20-minutes slot view:

![image](https://user-images.githubusercontent.com/5780704/88039378-c4050000-cb47-11ea-807d-6192dee76673.png)

### Actual behaviour
The highlighted horizontal lines are corresponding with intervals like 12:15 or 12:30. This is confusing because I tend to think in whole hours.

![image](https://user-images.githubusercontent.com/5780704/88038786-fcf0a500-cb46-11ea-8732-a7c4b85e65a1.png)

The 15-minutes slot view (shown below) doesn't really have the same problem, but it would be nice to highlight the whole hour lines because right now there is no clear distinction between the whole hour lines and half hour lines:

![image](https://user-images.githubusercontent.com/5780704/88040209-db90b880-cb48-11ea-90f7-095a659c2ee4.png)

### Calendar app
**Calendar app version:** 2.0.3

### Client configuration
**Browser:** Firefox 78.0.2

**Operating system:** Windows 10

**Comment by miaulalala** [comment]
Due to design changes the horizontal lines are no more.
