### ISSUE TITLE
Subscription calendar webcals link not working on ios

### ISSUE THREAD

**Issue by Bellusterra** [nextcloud/calendar#2416]
Hi @georgehrke ,
ios does not appear to be handling the webcals subscription link very well, I’m getting the message “Safari cannot open the page because the address is invalid.” when changing the link to begin with https:// the calendar gets added not as a subscription where it syncs but simply as a one time download of the calendar. Only when changing it to the webcal link without the “s” does it work as it is supposed to. I imagine others are having this issue too, and thought it would be good to bring up, as it may help with others who are wondering why their Nextcloud calendar is not syncing with their friends/family’s phones. Thank you.

**Comment by georgehrke** [comment]
related to https://github.com/nextcloud/calendar/issues/2197
