### ISSUE TITLE
Password Protect Shared Calendar link

### ISSUE THREAD

**Issue by rebel22lax** [nextcloud/calendar#2423]
I would like to set up a calendar with a team of 5 people so we can collaborate. From there the calendar will be shared with a larger group. I would like to password protect the link to further our security. I know i can set up an account for the 5 people but I would really just like to host the calendar. in a perfect world I would host the calendar give rights to the calendar to one other person and then let them manage it.

**Comment by georgehrke** [comment]
Duplicate of https://github.com/nextcloud/server/issues/20096
