### ISSUE TITLE
EXDATE

### ISSUE THREAD

**Issue by sherpadawan** [nextcloud/calendar#2424]
EXDATE or toher EX... parameters are not present in ics files when exporting a calendar.
Is it possible to add this in order to view ics file in another calendar (ICAL js lib, and fullcalendar)
Exceptions in recurrent event are not easy to isolate then.
thanks in advance.

**Comment by georgehrke** [comment]
Can you please provide proper reproduction steps?
I can't reproduce the described behavior, exporting `EXDATE`s works just fine for me.

```
BEGIN:VCALENDAR
PRODID:-//IDN nextcloud.com//Calendar app 2.0.3//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VEVENT
CREATED:20200728T064404Z
DTSTAMP:20200728T064420Z
LAST-MODIFIED:20200728T064420Z
SEQUENCE:3
UID:d29cd63d-5ffe-4faa-9834-b1493024f28d
DTSTART;VALUE=DATE:20200707
DTEND;VALUE=DATE:20200708
SUMMARY:recurring test
RRULE:FREQ=WEEKLY;COUNT=3;BYDAY=TU
EXDATE;VALUE=DATE:20200714
END:VEVENT
END:VCALENDAR
```

**Comment by sherpadawan** [comment]
When I use /?export a anonymou user or download link of the calendar as 
logged in user, there is no EXDATE ...

Relaitonship seems to be managed by means of siblings uid ...

How have you got the calendar ?

Guillaume

Le 28/07/2020 à 08:45, Georg Ehrke a écrit :

**Comment by georgehrke** [comment]
If you select to edit this and all future events, it splits up the event into two separate events. No EXDATE is expected there

**Comment by georgehrke** [comment]
Again: Can you please provide reproduction steps how you created those events? Thx

**Comment by sherpadawan** [comment]
Hello,

Thanks for your reply.

Steps are :

- I created an event with repeated occurences every 2 weeks.

- Then I edited a single occurence of this event chain, and modified it 
to be on another day (sunday instead of saturday)

Is it enough for you to understand my problem ?

Regards

Le 28/07/2020 à 18:58, Georg Ehrke a écrit :

**Comment by georgehrke** [comment]
> - Then I edited a single occurence of this event chain, and modified it
to be on another day (sunday instead of saturday)

This kind of action does not require an EXDATE. It just creates another instance with the same UID with a RECURRENCE-ID.

Also see https://tools.ietf.org/html/rfc5545#section-3.8.4.4

**Comment by sherpadawan** [comment]
Ok I will use RECURRENCE-ID

In which case EXDATE is generated as it is the RFC recommandation for 
DATE TIME exceptions ?

Thanks in advance

Le 29/07/2020 à 10:20, Georg Ehrke a écrit :
> to be on another day (sunday instead of saturday)

**Comment by georgehrke** [comment]
EXDATE is only used when you deleted individual instances of a recurrence-set.

**Comment by sherpadawan** [comment]
Ok ! So it is better to delete an occurence and add an new event !

Thanks

Le 29/07/2020 à 11:51, Georg Ehrke a écrit :
