### ISSUE TITLE
Show warning when leaving page while import still in progress

### ISSUE THREAD

**Issue by niowniow** [nextcloud/calendar#2425]
The issue here is manifold: 
1. It is not clear that an import is actually taking place and taking quite some time (#1857)
2. The import progress bar is not visible because the settings closes (#1859)
3. Even if 2 is fixed, it's not clear that the import bar is actually the import bar. It should be named as such!
4. When leaving the page during the import, the import is aborted, which happened to me since I did not understand that the import was not finished instantaneously.

### Steps to reproduce
Use the import calendar feature to import a calendar.  While the import is progressing change to a different Nextcloud page, e.g. Files.

### Expected behaviour
The user should be notified visually that an import is taking place.
If they want to leave the page, they should confirm that they want to abort the import.

### Actual behaviour
The page changes and the import stops.

### Calendar app
**Calendar app version:**  3.3.0

### Client configuration
**Browser:** Firefox 78.0.1

**Operating system:** Ubuntu 18.04

### Server configuration
Unknown

**Comment by georgehrke** [comment]
@niowniow Would you be interested in sending a pull-request to implement the warning? 

You have to register an event handler for `beforeunload` while the import is in progress.
https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Comment by niowniow** [comment]
Interested yes, but currently I do not have time to set up everything needed for development and to understand the existing code.

**Comment by miaulalala** [comment]
The import dialogue has changed to a modal and both tickets have been fixed. Closing this as completed.
