### ISSUE TITLE
[Request/Improvement] Entry's => CleanDB Meeting Entrys (for clean re-import/ re-sync from Handy)

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/calendar#2428]
**Is your feature request related to a problem? Please describe.**
Have wrong import the Trash-Pickup-Days in my Personal Meeting ,
this was wrong, i had to edit directly my mariadb for clean it up the Entry "Personal" of my account.

This could also happend with other Meeting-Entrys !

**Describe the solution you'd like**
In 
<b>Configuration & Import</b>
<b>[Clean Meeting Entry's]</b>
 [Import Calendar]
[X]...
[X]...
[X]...

<b>Clean Meeting Entry's</b> => Popup  WAPPER (to see, it is important) =>
```
<h1>Clean up your Meeting Entry's in the DB</h1>
<h3>->Warning if you clean the Entry's must you import ics or rebuild your Meetingentry's again !<-</h3>
<b>Entry's</b>
<hr> 
ID|Name         | Entry's (Nr.) |       Warning+ all will deleted checkbox                    | Cleanbuttons
----------------------------------------------------------------------------------------------------------------
2 Personal               165   Warning, all data in Personal is deleted in the DB !        [X]  [clean up/delete all entrys]
1 Birthdays of Contacts    4   Warning, all data in Birthdays is deleted in the DB !       [_]  [clean up/delete all entrys]<= gray
3 Trash-Pickup           164   Warning, all data in Trash-Pickup is deleted in the DB !    [_]  [clean up/delete all entrys]<= gray
4 Holyday's               90   Warning, all data in Holyday's  is deleted in the DB !      [_]  [clean up/delete all entrys]<= gray
5 Holiday's BW           120   Warning, all data in Holiday's BW  is deleted in the DB !   [_]  [clean up/delete all entrys]<= gray
6 Celebrations           111   Warning, all data in Celebrations is deleted in the DB !    [_]  [clean up/delete all entrys]<= gray
7 Celebrations BW         95   Warning, all data in Celebrations BW is deleted in the DB ! [_]  [clean up/delete all entrys]<= gray
```
an Button for clean all Cal-Entry's in the Meeting-Entry's  

**Describe alternatives you've considered**
i had must edit via PHPMyAdmin the Entry and have clean it up incl. rebuild ID-Number and ,VTODO.

**Additional context**
The Users should have the possibility for clean up his own entry's for fresh building up and hold the original Entry-Meeting-Name without extra delete and add without Administrator, therewith it is possible for hold the "ID" and the other in original in database and the original Place let untouched of the MeetingName

**Extra request**
maybe directly add a possibility for moving up or down the entrys ?

Thank you :)
and keep it up, i like it ! a big, fat :+1: Thumps up !

**Comment by georgehrke** [comment]
>  i had to edit directly my mariadb for clean it up the Entry "Personal" of my account.

Please do not touch the database directly. If you just delete rows from oc_calendarobjects without making other changes, you will end up with an inconsistent state.

> an Button for clean all Cal-Entry's in the Meeting-Entry's

What is the benefit over just deleting a calendar and recreating it on import.
Especially if you just imported it just minutes ago, it's unlikely that calendar already has shares or public links attached to it.

**Comment by georgehrke** [comment]
> therewith it is possible for hold the "ID" and the other in original in database and the original Place let untouched of the MeetingName

As a user, the database id should not concern you. It is never exposed to the user.

**Comment by blackcrack** [comment]
i know what i du, i have jesterday build up a Fedoraserver ,mariadb, samba and other and by the way have i create a nextcloud theme : https://www.blackysgate.de/files/folder-root/nextcloud/

>What is the benefit over just deleting a calendar and recreating it on import?
not need to recreate it.. easy erase the things what is inside as user in the user-account on mariadb, more not.
>As a user, the database id should not concern you. It is never exposed to the user.
so why should delete the whole database if its able only delete the entry's..

if you have scare "for me" 
>As a user, the database id should not concern you. It is never exposed to the user.
you have not to say me what i have concern on my Database/Mariadb ;) Sir..
i be since 1996 in the net.. and a bit older as u.. (like i guess) ;-)

an Wapper for delete the entrys and clean it up without delete the whole Name-Entry is need to give the user
a possible for clean up the things in the Entry ..

best regards
Blacky

**Comment by georgehrke** [comment]
> not need to recreate it.. easy erase the things what is inside as user in the user-account on mariadb, more not.

Your proposed UI actually takes more clicks:
1. Click a button to open the clean event modal
2. Click the checkbox on the calendar
3. Click clean

Deleting a calendar just takes two clicks:
1. Click the three-dot menu on the calendar entry
2. Click Delete

> so why should delete the whole database if its able only delete the entry's..

You are not deleting the whole database. You are just deleting one entry from oc_calendars ...

> you have not to say me what i have concern on my Database

Randomly making changes to the database is no supported way of using Nextcloud. 
Neither for the Calendar nor for any other component.
If you want to changes the calendar:
- use the web ui
- use CalDAV
- use the occ tool

--- 

Anyway, this is a 👎 for me.
The problem you are trying to solve occurs very rarely.
There already is a way to solve it (just delete the calendar), which actually takes less steps than your proposed solution.

**Comment by blackcrack** [comment]
i want not delete my calendar, i want clean the entrys..

because i use the entry's in different other webdav client's !!
and i whant not change the whole other..

i want hold the Calendarentrys.. 
you wrong.. 
thank you for closing it and make it more easy for you !

... impossible !
