### ISSUE TITLE
Calendar shared by link: overall design & left navigation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#243]
Currently a calendar shared by link looks like this:
![capture du 2016-12-15 02-36-40](https://cloud.githubusercontent.com/assets/925062/21208609/57b04476-c26f-11e6-99e0-fdd5a5dc911b.png)

Some thoughts:
- There’s no blue bar on top which clearly states »Nextcloud«. It’s not only a branding thing but also to know where you are. We do that everywhere else when sharing – Files, Spreed, Gallery etc.
- The left navigation looks a bit lost. We could have the calendar name a bit bigger like a h2 maybe? Similar to the »Files drop« feature in the server
- Also similar to the »Files drop«, it would be cool to not only show the user id in parentheses like `(jan)` but actually show a separate line with avatar and full name (fallback to username)
- Bug: the right border of the left navigation is not going through the whole way. The lower half (except next to settings) is basically missing.

What do you think @nextcloud/calendar @nextcloud/designers?

**Comment by eppfel** [comment]
Also, I would like to improve the workflow to subscribe to public calendars. Right now, you have to go to the public calendar and click settings to get a URL you can subscribe to.

The public interface will mainly be used by non-nextloud users, so I propose removing the settings here (they are not saved anyway) and move the options directly under the calendar (to the download button).

Something like this:

<img width="966" alt="bildschirmfoto 2016-12-15 um 10 34 10" src="https://cloud.githubusercontent.com/assets/1899308/21218754/18bc47fe-c2b2-11e6-9b43-8a13dd219a5f.png">

Or would it even be possible to subscribe to the public share link with a redirect to the dav address?

**Comment by georgehrke** [comment]
I think you have to distinguish two use-cases here.
You definitely want the nextcloud bar, when accessing the shared link directly.
But usually you don't want the Nextcloud bar when embedding it into other websites.

**Comment by jancborchardt** [comment]
@eppfel I tend to agree with moving the subscription settings directly there with the »Download« link too. Although the information architecture can be improved a bit more than just moving it there, because for example:
- the embed textarea doesn’t need to be open by default (seldom used feature)
- the CalDAV / WebCal toggle seems a bit strange
- just generally properly adjust the information hierarchy there :) Calendar name being most important. :)

**Comment by eppfel** [comment]
@jancborchardt Totally, just did not have the time to come up with it.

**Comment by georgehrke** [comment]
@tcitworld Do you want to take care of this? :)

**Comment by georgehrke** [comment]
I got some feedback at congress:
- we should make the webcal link clickable. iOS will automatically offer you to subscribe to it.
If you just have the link, you have to go to Settings > Calendar > Accounts > add a calendar > Others > subscribe to a calendar and then paste the link.

**Comment by tcitworld** [comment]
As a regular link then, so that you can still copy it through context menu on desktop on holding on mobile.

**Comment by nickvergessen** [comment]
Came here to state that I also miss the header/blue bar/brand on the public page.

**Comment by eppfel** [comment]
I think we have to make the bar default, because we want people to recognize Nextcloud.

So, there needs to be an extra route for embedding.

**Comment by georgehrke** [comment]
> So, there needs to be an extra route for embedding.

I would do it the other way around. We need an extra route for calendar with nextcloud bar, because we can't change the embed code already used by people on their website.

**Comment by eppfel** [comment]
I know this is bad 😁 , but when we pull the embed option out of the settings and rename it to "embed without top-bar" people could at least change it easily...

What would be the alternative? Show the public url with topbar as default, but with a new url `https://cloud.nextcloud.com/apps/calendar/public/MIFAFLFJADIVX63I/bar`. Would be fine with me, as long as it is the default URL we give out to users.

**Comment by georgehrke** [comment]
> What would be the alternative? Show the public url with topbar as default, but with a new url `https://cloud.nextcloud.com/apps/calendar/public/MIFAFLFJADIVX63I/bar`. Would be fine with me, as long as it is the default URL we give out to users.

Yes, I was thinking about something like this

**Comment by georgehrke** [comment]
<img width="1920" alt="nextcloud_chromium__today_at_3_45_46_pm" src="https://cloud.githubusercontent.com/assets/1250540/24105195/716a414a-0d84-11e7-8d39-682b3eedf0f6.png">

While adding the top bar, we have to opportunity to add some actions to the upper right corner.
What would these actions be? 

Download and Subscribe?

@jancborchardt @eppfel

**Comment by tcitworld** [comment]
Fine to me.

**Comment by georgehrke** [comment]
Also, do we want to offer "Subscribe & embed" in the embedded version at all?
