### ISSUE TITLE
.ics import partially fails (Calendar  1.4.1)

### ISSUE THREAD

**Issue by sparks305** [nextcloud/calendar#245]
### Steps to reproduce
1. import previously saved .ics from owncloud
2. import previously saved .ics from owncloud
3. import previously saved .ics from owncloud

### Expected behaviour
successfully import the entire calendar.

### Actual behaviour
Imports partial calendar, loading bar freezes partial way. I tired multiple times, with different calendars (.ics) and it only partially loads them.

### Server configuration
**Operating system**:
FreeNAS-9.10.1-U4 (ec9a7d3)
**Web server:**

**Database:**
mySQL
**PHP version:**
5.5
**Server version:** (see your admin page)
Nextcloud 10.0.2 (stable)
**Calendar version:** (see the apps page)

**Updated from an older installed version or fresh install:**
free install

**List of activated apps:**
calendar, ownnote
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
none
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by georgehrke** [comment]
Please provide logs, this is very important here

**Comment by georgehrke** [comment]
especially console log of your web browser.
