### ISSUE TITLE
Add fullcalendar export output

### ISSUE THREAD

**Issue by b4D8** [nextcloud/calendar#2460]
**Is your feature request related to a problem? Please describe.**
I am using the [fullcalendar](https://github.com/fullcalendar/fullcalendar) javascript library for some projects and would like to use the data stored in my Nextcloud CalDav to populate them.
Since Nextcloud Calendar is also using fullcalendar, this data should already be available in the required file format (fullcalendar's own proprietary dialect aka the [Event Object](https://fullcalendar.io/docs/event-object)).
However, as far as I know the only export outputs provided by Nextcloud Calendar are `ical` or `jcal` file formats which aren't natively compatible with the fullcalendar dialect.

**Describe the solution you'd like**
Provide an additional export output in fullcalendar's file format through `/remote.php/dav/public-calendars/5dDRSefsqB23eSR4N?export&accept=fullcalendar`.

**Describe alternatives you've considered**
Alternatives are fullcalendar deciding to be compatible with the universal format for calendar (`ical`) or just me (their users) keeping on building converters...

**Additional context**
Since the conversion is tedious, I believe many developers rely on Google Agenda being natively integrated in fullcalendar which isn't helping us [regain control](https://nextcloud.com/)...

**Comment by georgehrke** [comment]
This code is free software, feel free to study and reuse it.
But your feature request is way out of scope for this project.
