### ISSUE TITLE
Send e-mail for calendar entries in shared calendar

### ISSUE THREAD

**Issue by andreas-geissler** [nextcloud/calendar#2469]
Used Calendar Version: 2.0.3

**Is your feature request related to a problem? Please describe.**
As owner of a calendar I can create an event and e-mails are sent to the defined attendies, which works fine.
When the calendar is shared and edit-rights are given to other persons, these persons can create events in the shared calendar.
But for these events, no emails are sent to the attendies.

**Describe the solution you'd like**
If a calendar is shared and edit-rights are given, for events created by non-owner e-mails should be send to the attendies.

**Comment by georgehrke** [comment]
Closing in favor of https://github.com/nextcloud/server/issues/19827

**Comment by quentinDupont** [comment]
This problem is still present in Nextcloud 20 with Agenda 2.2.0.
I'm not sure to understand why it's linked with #19827, that's why i will also write the issue over there

**Comment by tcitworld** [comment]
See https://github.com/nextcloud/server/issues/26668
