### ISSUE TITLE
Define "File sharing" app as dependency

### ISSUE THREAD

**Issue by onny** [nextcloud/calendar#247]
### Steps to reproduce
1. Disable "File sharing" app
2. Open Calendar app

### Expected behaviour
You should not be able to disable the "File sharing" app while the Calendar app is enabled.

### Actual behaviour
Calendar app is broken now, "OS.share is undefined" error in console log

I skipped the other bug report parts since they are possibly not releated.

**Comment by georgehrke** [comment]
dup, looking for original

**Comment by tcitworld** [comment]
https://github.com/nextcloud/calendar/issues/205

**Comment by onny** [comment]
Oh cool thanks! Didn't notice the other issue
