### ISSUE TITLE
Repeat event every x weeks/days

### ISSUE THREAD

**Issue by Bennneeeet** [nextcloud/calendar#2473]
Hi :wave: 
it would be a great feature, if it's possible to repeat a event every 6 weeks (for example). That makes it possible to use the app to manage personal shifts etc.

Regards 
Bennneeeet :v:

**Comment by georgehrke** [comment]
That is already possible, please check the documentation or ask your question in the forum:

https://help.nextcloud.com

**Comment by Bennneeeet** [comment]
Thank you @georgehrke for your answer.
I missunderstood this option. Sorry.

But fyi: the link to the documentation is broken ([Nextcloud Appstore)](https://apps.nextcloud.com/apps/calendar): https://docs.nextcloud.com/server/latest/user_manual/pim/calendar.html
