### ISSUE TITLE
ability to show/hide left sidebar (hamburger icon always visible)

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/calendar#2475]
**Is your feature request related to a problem? Please describe.**
The left sidebar opens/closes automatically according to screen size. I would like to have more control if it is visible or not, on my big screen with side-by-side windows it happens often that room is wasted. Also, when it closes, it gives me to option to open it, but when it is open, I have no option to close it. The right sidebar gives me complete control if it is open or not, so the left should also do that.

**Describe the solution you'd like**
Always show the hamburger menu icon to open/close the left sidebar. 

_Would be cool if it was the same in all Nextcloud apps._

I like the way Asana does it:
Open sidebar:
![Unbenannt](https://user-images.githubusercontent.com/28591861/90443162-0cc6bf00-e0dc-11ea-891d-ff3fa6126808.png)
Closed sidebar:
![Unbenannt1](https://user-images.githubusercontent.com/28591861/90443193-1bad7180-e0dc-11ea-8839-83d386a86241.png)

I know you care about usability, so lets say an inexperienced user hides it by accident and is confused where the sidebar went - then the sidebar could be shown automatically when the user starts resizing the window.

**Comment by georgehrke** [comment]
This was already implemented in https://github.com/nextcloud/nextcloud-vue and updated in the calendar.
 We just need to release a new version.
