### ISSUE TITLE
Mobile menu position incorrect

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/calendar#248]
Seems related to calendar in public mode only.
![screenshot_20161215-133931](https://cloud.githubusercontent.com/assets/14975046/21224635/75e95492-c2cd-11e6-85be-e049b813583e.png)
![screenshot_20161215-133939](https://cloud.githubusercontent.com/assets/14975046/21224638/7b6bea2e-c2cd-11e6-82da-544624455373.png)

**Comment by georgehrke** [comment]
Sorry for this stupid question, but can you elaborate what's incorrect there?

**Comment by skjnldsv** [comment]
Eheh, my bad.
The menu icon on the top left is too low.

**Comment by georgehrke** [comment]
Ah, okay :) 

That's most certainly related to the missing nextcloud bar.
Adding that is for discussion in https://github.com/nextcloud/calendar/issues/243
