### ISSUE TITLE
improve tab index in editor

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#25]

**Comment by ccoenen** [comment]
my main gripe is with the `all day event` checkbox, as it is in the wrong place in my opinion. If you're entering stuff via keyboard, currently you have to

* title <kbd>Tab</kbd>
* calendar selection <kbd>Tab</kbd>
* start date <kbd>Tab</kbd> end date <kbd>Tab</kbd>
* now at all day event <kbd>spacebar</kbd> (uncheck all day event)
* <kbd>Shift-Tab</kbd> <kbd>Shift-Tab</kbd> <kbd>Shift-Tab</kbd> (get back to start time)
...

**Comment by georgehrke** [comment]
From a visual point of view I like the position of the all day button. we should just adjust the tab index :)

**Comment by eppfel** [comment]
As mentioned in #72 I would not want to block users. Maybe you can tab to the time fields to enable them? And if you actually want daily events you hit space after tabbing through. Not sure...
