### ISSUE TITLE
Groups show status of user with the same id

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/calendar#2511]
### Steps to reproduce
1. Have a user admin
2. Have a group admin
3. Type `ad` into the share dialog

### Expected behaviour
Groups have no status

### Actual behaviour
![Bildschirmfoto von 2020-08-26 13-21-20](https://user-images.githubusercontent.com/213943/91297770-284a5d80-e79f-11ea-92f9-ee867f3d1707.png)

**Comment by georgehrke** [comment]
Fixed with https://github.com/nextcloud/nextcloud-vue/pull/1348 already
