### ISSUE TITLE
Calendar isn't working anymore since update NC to 19.01 and 19.02

### ISSUE THREAD

**Issue by Tomscloud** [nextcloud/calendar#2512]
Hi there, i hope this isnt only my problem... 
but since i updated my NC from 18.07 to 19.01 and today to 19.02 the Calendar App isn't working anymore. I'm not possible to see any Calendar Event and also the CalDAV brings error...

### Client configuration
I try'd start it with Firefox V79, Chrom V84, MS-Edge, always clean the Browsers Cache, try'd with incognito mode, bute the result is always the same

![image](https://user-images.githubusercontent.com/68244104/91443862-37e7a600-e874-11ea-8a44-3ad04cd698ef.png)

### Calendar app
**Calendar app version: 2.0.3

**CalDAV-clients used: 3.8.2.0 in Outlook 365
Error: CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '408' ('Request Time-out')

**Operating system: Windows 10 1909

### Server configuration

**Operating system**: Debian 4.9.210-1 (Webhoster Easyname.at)

**Web server:** (e.g. Apache, Nginx,...)

**Database: mySQL 5.7.29

**PHP version: 7.3.8

**Nextcloud Version: 19.02

**Updated from an older installed version or fresh install: from 18.07 to 19.01 and today to 19.02

**List of activated apps:**
  - accessibility: 1.5.0  - activity: 2.12.0  - bruteforcesettings: 1.6.0  - calendar: 2.0.3  - cloud_federation_api: 1.2.0  - comments: 1.9.0  - contacts: 3.3.0  - contactsinteraction: 1.0.0  - dashboard: 6.0.0  - dav: 1.15.0  - drawio: 0.9.7  - event_update_notification: 1.0.2  - federatedfilesharing: 1.9.0  - federation: 1.9.0  - files: 1.14.0  - files_mindmap: 0.0.22  - files_pdfviewer: 1.8.0  - files_rightclick: 0.16.0  - files_sharing: 1.11.0  - files_trashbin: 1.9.0  - files_versions: 1.12.0  - files_videoplayer: 1.8.0  - firstrunwizard: 2.8.0  - logreader: 2.4.0  - lookup_server_connector: 1.7.0  - nextcloud_announcements: 1.8.0  - notes: 3.6.4  - notifications: 2.7.0  - oauth2: 1.7.0  - occweb: 0.0.7  - password_policy: 1.9.1  - photos: 1.1.0  - privacy: 1.3.0  - provisioning_api: 1.9.0  - ransomware_protection: 1.7.0  - recommendations: 0.7.0  - serverinfo: 1.9.0  - settings: 1.1.0  - sharebymail: 1.9.0  - support: 1.2.1  - survey_client: 1.7.0  - systemtags: 1.9.0  - tasks: 0.13.3  - text: 3.0.1  - theming: 1.10.0  - twofactor_backupcodes: 1.8.0  - updatenotification: 1.9.0  - viewer: 1.3.0  - workflowengine: 2.1.0

**Nextcloud configuration:**
{    "system": {        "instanceid": "***REMOVED SENSITIVE VALUE***",        "passwordsalt": "***REMOVED SENSITIVE VALUE***",        "secret": "***REMOVED SENSITIVE VALUE***",        "trusted_domains": [            "stillebacher.at",            "www.stillebacher.at"        ,        "memcached_servers": [            [                "\/data\/sockets\/memcached\/e95869-1139.sock",                11211            ]        ],        "datadirectory": "***REMOVED SENSITIVE VALUE***",        "overwrite.cli.url": "https:\/\/stillebacher.at",        "dbtype": "mysql",        "version": "19.0.2.2",        "dbname": "***REMOVED SENSITIVE VALUE***",        "dbhost": "***REMOVED SENSITIVE VALUE***",        "dbport": "",        "dbtableprefix": "oc_",        "mysql.utf8mb4": true,        "dbuser": "***REMOVED SENSITIVE VALUE***",        "dbpassword": "***REMOVED SENSITIVE VALUE***",        "installed": true,        "default_language": "de",        "appstoreenabled": true,        "appstore.experimental.enabled": true,        "enable_previews": true,        "updater.release.channel": "stable",        "theme": "",        "loglevel": 2,        "mail_domain": "***REMOVED SENSITIVE VALUE***",        "mail_from_address": "***REMOVED SENSITIVE VALUE***",        "mail_smtpmode": "smtp",        "mail_smtpauthtype": "LOGIN",        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",        "mail_sendmailmode": "smtp",        "mail_smtpport": "465",        "maintenance": false,        "mail_smtpauth": 1,        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",        "mail_smtpsecure": "ssl",        "app_install_overwrite": [            "dashboard",            "radio",            "occweb",            "files_external_onedrive",            "mindmap_app",            "dashboardcharts"        ],        "updater.secret": "***REMOVED SENSITIVE VALUE***"    },    "apps": {        "accessibility": {            "enabled": "yes",            "installed_version": "1.5.0",            "types": ""        },        "activity": {            "enabled": "yes",            "installed_version": "2.12.0",            "notify_email_calendar": "0",            "notify_email_calendar_event": "0",            "notify_email_calendar_todo": "0",            "notify_email_comments": "0",            "notify_email_favorite": "0",            "notify_email_file_changed": "0",            "notify_email_file_created": "0",            "notify_email_file_deleted": "0",            "notify_email_file_downloaded": "0",            "notify_email_file_restored": "0",            "notify_email_public_links": "0",            "notify_email_remote_share": "0",            "notify_email_shared": "0",            "notify_email_systemtags": "0",            "notify_setting_batchtime": "604800",            "notify_setting_self": "0",            "notify_setting_selfemail": "0",            "notify_stream_calendar": "1",            "notify_stream_calendar_event": "1",            "notify_stream_calendar_todo": "1",            "notify_stream_comments": "1",            "notify_stream_favorite": "1",            "notify_stream_file_changed": "1",            "notify_stream_file_created": "1",            "notify_stream_file_deleted": "1",            "notify_stream_file_downloaded": "1",            "notify_stream_file_favorite": "0",            "notify_stream_file_restored": "1",            "notify_stream_public_links": "1",            "notify_stream_remote_share": "1",            "notify_stream_shared": "1",            "notify_stream_systemtags": "1",            "types": "filesystem"        },        "audioplayer": {            "enabled": "no",            "installed_version": "2.11.2",            "types": "filesystem"        },        "audioplayer_sonos": {            "enabled": "no",            "installed_version": "1.1.1",            "sonos": "checked",            "types": "filesystem"        },        "backgroundjob": {            "lastjob": "171"        },        "bruteforcesettings": {            "enabled": "yes",            "installed_version": "1.6.0",            "types": ""        },        "calendar": {            "enabled": "yes",            "installed_version": "2.0.3",            "types": ""        },        "cloud_federation_api": {            "enabled": "yes",            "installed_version": "1.2.0",            "types": "filesystem"        },        "comments": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "logging"        },        "contacts": {            "enabled": "yes",            "installed_version": "3.3.0",            "types": ""        },        "contactsinteraction": {            "enabled": "yes",            "installed_version": "1.0.0",            "types": "dav"        },        "core": {            "backgroundjobs_mode": "ajax",            "enterpriseLogoChecked": "yes",            "installedat": "1531746325.6409",            "lastcron": "1598532724",            "lastupdateResult": "[]",            "lastupdatedat": "1598527214",            "oc.integritycheck.checker": "[]",            "public_files": "files_sharing\/public.php",            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",            "scss.variables": "8978f172a498e404dac4d0c8f4f5cb0b",            "shareapi_allow_public_upload": "no",            "shareapi_enable_link_password_by_default": "yes",            "theming.variables": "dbd195132c4c5710068861d8d6c69791",            "updater.secret.created": "1598524394",            "vendor": "nextcloud"        },        "dashboard": {            "enabled": "yes",            "installed_version": "6.0.0",            "types": ""        },        "dashboardcharts": {            "cachebuster": "1",            "enabled": "no",            "installed_version": "0.1.3",            "types": ""        },        "dav": {            "buildCalendarReminderIndex": "yes",            "buildCalendarSearchIndex": "yes",            "chunks_migrated": "1",            "enabled": "yes",            "installed_version": "1.15.0",            "regeneratedBirthdayCalendarsForYearFix": "yes",            "sendEventRemindersPush": "yes",            "types": "filesystem"        },        "drawio": {            "enabled": "yes",            "installed_version": "0.9.7",            "types": "filesystem"        },        "event_update_notification": {            "enabled": "yes",            "installed_version": "1.0.2",            "types": "logging,dav"        },        "federatedfilesharing": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": ""        },        "federation": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "authentication"        },        "files": {            "cronjob_scan_files": "500",            "default_quota": "10 GB",            "enabled": "yes",            "installed_version": "1.14.0",            "types": "filesystem"        },        "files_accesscontrol": {            "enabled": "no",            "installed_version": "1.8.1",            "types": "filesystem"        },        "files_downloadactivity": {            "enabled": "no",            "installed_version": "1.7.0",            "types": "filesystem"        },        "files_frommail": {            "enabled": "no",            "installed_version": "0.1.1",            "types": ""        },        "files_markdown": {            "enabled": "no",            "installed_version": "2.3.0",            "types": ""        },        "files_mindmap": {            "enabled": "yes",            "installed_version": "0.0.22",            "types": ""        },        "files_pdfviewer": {            "enabled": "yes",            "installed_version": "1.8.0",            "types": ""        },        "files_rightclick": {            "enabled": "yes",            "installed_version": "0.16.0",            "types": ""        },        "files_sharing": {            "enabled": "yes",            "installed_version": "1.11.0",            "types": "filesystem"        },        "files_texteditor": {            "enabled": "no",            "installed_version": "2.8.0",            "types": ""        },        "files_trashbin": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "filesystem,dav"        },        "files_versions": {            "enabled": "yes",            "installed_version": "1.12.0",            "types": "filesystem,dav"        },        "files_videoplayer": {            "enabled": "yes",            "installed_version": "1.8.0",            "types": ""        },        "firstrunwizard": {            "enabled": "yes",            "installed_version": "2.8.0",            "types": "logging"        },        "gallery": {            "enabled": "no",            "installed_version": "18.4.0",            "types": ""        },        "logreader": {            "enabled": "yes",            "installed_version": "2.4.0",            "levels": "11111",            "types": ""        },        "lookup_server_connector": {            "enabled": "yes",            "installed_version": "1.7.0",            "types": "authentication"        },        "mail": {            "enabled": "no",            "installed_version": "0.11.0",            "types": ""        },        "nextcloud_announcements": {            "enabled": "yes",            "installed_version": "1.8.0",            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",            "types": "logging"        },        "notes": {            "enabled": "yes",            "installed_version": "3.6.4",            "types": ""        },        "notifications": {            "enabled": "yes",            "installed_version": "2.7.0",            "types": "logging"        },        "oauth2": {            "enabled": "yes",            "installed_version": "1.7.0",            "types": "authentication"        },        "occweb": {            "enabled": "yes",            "installed_version": "0.0.7",            "types": ""        },        "password_policy": {            "enabled": "yes",            "enforceHaveIBeenPwned": "1",            "enforceNumericCharacters": "1",            "enforceUpperLowerCase": "1",            "installed_version": "1.9.1",            "types": "authentication"        },        "photos": {            "enabled": "yes",            "installed_version": "1.1.0",            "types": ""        },        "preferred_providers": {            "enabled": "no",            "installed_version": "1.7.0",            "provider_groups": "Familie",            "provider_token": "0d5fd8d829cde345c12a2f7e635d05e4",            "types": ""        },        "printer": {            "enabled": "no",            "installed_version": "0.0.3",            "types": "filesystem"        },        "privacy": {            "enabled": "yes",            "installed_version": "1.3.0",            "readableLocation": "at",            "types": ""        },        "provisioning_api": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "prevent_group_restriction"        },        "radio": {            "enabled": "no",            "installed_version": "0.6.6",            "types": ""        },        "ransomware_protection": {            "enabled": "yes",            "installed_version": "1.7.0",            "notes_include_biased": "yes",            "types": "logging"        },        "recommendations": {            "enabled": "yes",            "installed_version": "0.7.0",            "types": ""        },        "serverinfo": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": ""        },        "settings": {            "enabled": "yes",            "installed_version": "1.1.0",            "types": ""        },        "sharebymail": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "filesystem"        },        "spreed": {            "enabled": "no",            "installed_version": "9.0.3",            "project_access_invalidated": "1",            "stun_servers": "***REMOVED SENSITIVE VALUE***",            "types": "prevent_group_restriction"        },        "support": {            "SwitchUpdaterServerHasRun": "yes",            "enabled": "yes",            "installed_version": "1.2.1",            "types": "session"        },        "survey_client": {            "enabled": "yes",            "installed_version": "1.7.0",            "last_report": "{\"id\":\"oc7lhcox6vmw\",\"items\":[[\"server\",\"version\",\"18.0.4.2\"],][[\"server\",\"version\",\"18.0.4.2\"][][[\"server\",\"version\",\"18.0.4.2\"]\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"none\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"ajax\"],[\"php\",\"version\",\"7.2.27\"],[\"php\",\"memory_limit\",268435456],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",268435456],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"5.7.29\"],[\"database\",\"size\",8273920],[\"apps\",\"accessibility\",\"1.4.0\"],[\"apps\",\"activity\",\"2.11.0\"],[\"apps\",\"audioplayer\",\"2.10.0\"],[\"apps\",\"audioplayer_sonos\",\"1.1.1\"],[\"apps\",\"bruteforcesettings\",\"1.6.0\"],[\"apps\",\"calendar\",\"2.0.3\"],[\"apps\",\"cloud_federation_api\",\"1.1.0\"],[\"apps\",\"comments\",\"1.8.0\"],[\"apps\",\"contacts\",\"3.3.0\"],[\"apps\",\"dashboard\",\"6.0.0\"],[\"apps\",\"dashboardcharts\",\"disabled\"],[\"apps\",\"dav\",\"1.14.0\"],[\"apps\",\"drawio\",\"0.9.5\"],[\"apps\",\"event_update_notification\",\"1.0.2\"],[\"apps\",\"federatedfilesharing\",\"1.8.0\"],[\"apps\",\"federation\",\"1.8.0\"],[\"apps\",\"files\",\"1.13.1\"],[\"apps\",\"files_accesscontrol\",\"disabled\"],[\"apps\",\"files_downloadactivity\",\"disabled\"],[\"apps\",\"files_frommail\",\"disabled\"],[\"apps\",\"files_markdown\",\"disabled\"],[\"apps\",\"files_mindmap\",\"0.0.22\"],[\"apps\",\"files_pdfviewer\",\"1.7.0\"],[\"apps\",\"files_rightclick\",\"0.15.2\"],[\"apps\",\"files_sharing\",\"1.10.1\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"files_trashbin\",\"1.8.0\"],[\"apps\",\"files_versions\",\"1.11.0\"],[\"apps\",\"files_videoplayer\",\"1.7.0\"],[\"apps\",\"firstrunwizard\",\"2.7.0\"],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"logreader\",\"2.3.0\"],[\"apps\",\"lookup_server_connector\",\"1.6.0\"],[\"apps\",\"mail\",\"disabled\"],[\"apps\",\"nextcloud_announcements\",\"1.7.0\"],[\"apps\",\"notes\",\"3.5.1\"],[\"apps\",\"notifications\",\"2.6.0\"],[\"apps\",\"oauth2\",\"1.6.0\"],[\"apps\",\"occweb\",\"0.0.7\"],[\"apps\",\"password_policy\",\"1.8.0\"],[\"apps\",\"photos\",\"1.0.0\"],[\"apps\",\"preferred_providers\",\"1.6.0\"],[\"apps\",\"printer\",\"disabled\"],[\"apps\",\"privacy\",\"1.2.0\"],[\"apps\",\"provisioning_api\",\"1.8.0\"],[\"apps\",\"radio\",\"0.6.6\"],[\"apps\",\"ransomware_protection\",\"1.6.1\"],[\"apps\",\"recommendations\",\"0.6.0\"],[\"apps\",\"serverinfo\",\"1.8.0\"],[\"apps\",\"settings\",\"1.0.0\"],[\"apps\",\"sharebymail\",\"1.8.0\"],[\"apps\",\"support\",\"1.1.0\"],[\"apps\",\"survey_client\",\"1.6.0\"],[\"apps\",\"systemtags\",\"1.8.0\"],[\"apps\",\"tasks\",\"0.13.1\"],[\"apps\",\"text\",\"2.0.0\"],[\"apps\",\"theming\",\"1.9.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.7.0\"],[\"apps\",\"updatenotification\",\"1.8.0\"],[\"apps\",\"user_external\",\"0.5.0\"],[\"apps\",\"viewer\",\"1.2.0\"],[\"apps\",\"workflowengine\",\"2.0.0\"],[\"stats\",\"num_files\",6359],[\"stats\",\"num_users\",4],[\"stats\",\"num_storages\",6],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",5],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",0],[\"files_sharing\",\"num_shares_user\",0],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",0],[\"files_sharing\",\"num_shares_link_no_password\",0],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",            "last_sent": "1592500395",            "types": ""        },        "systemtags": {            "enabled": "yes",            "installed_version": "1.9.0",            "types": "logging"        },        "tasks": {            "enabled": "yes",            "installed_version": "0.13.3",            "types": ""        },        "text": {            "enabled": "yes",            "installed_version": "3.0.1",            "types": "dav"        },        "theming": {            "backgroundMime": "image\/jpeg",            "cachebuster": "9",            "enabled": "yes",            "imprintUrl": "***REMOVED SENSITIVE VALUE***",            "installed_version": "1.10.0",            "logoMime": "image\/png",            "name": "TomsCloud",            "slogan": "***REMOVED SENSITIVE VALUE***",            "types": "logging",            "url": "***REMOVED SENSITIVE VALUE***"        },        "twofactor_backupcodes": {            "enabled": "yes",            "installed_version": "1.8.0",            "types": ""        },        "updatenotification": {            "audioplayer": "2.11.0",            "bruteforcesettings": "1.6.0",            "calendar": "2.0.3",            "contacts": "3.2.0",            "core": "18.0.7.1",            "drawio": "0.9.7",            "enabled": "yes",            "files_frommail": "0.1.1",            "installed_version": "1.9.0",            "mail": "0.8.3",            "notes": "3.6.0",            "occweb": "0.0.7",            "preferred_providers": "1.7.0",            "radio": "0.6.5",            "ransomware_protection": "1.1.2",            "tasks": "0.13.2",            "types": "",            "update_check_errors": "0"        },        "user_external": {            "installed_version": "0.5.0",            "types": "authentication,prelogin"        },        "viewer": {            "enabled": "yes",            "installed_version": "1.3.0",            "types": ""        },        "workflowengine": {            "enabled": "yes",            "installed_version": "2.1.0",            "types": "filesystem"        }    }}]

#### Web server error log (e.g. /var/log/apache)
```
not possible, Webhoster Server
```
#### Log file (data/nextcloud.log)
```
[nextcloud.log](https://github.com/nextcloud/calendar/files/5136547/nextcloud.log)
```
#### CalDAV Log:
```
[log.txt](https://github.com/nextcloud/calendar/files/5136573/log.txt)

```

#### Browser log
```
Insert your browser log here, this could for example include:

how to do this?
```

**Comment by georgehrke** [comment]
> how to do this

<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.

**Comment by Tomscloud** [comment]
i got this:

Error: 
    D calendar.js:2
    r calendar.js:2
    t attachError.js:36
    t calendar.js:2
    t calendar.js:2
    onreadystatechange request.js:353
calendar.js:2:229968
    ze https://mysite.at/apps/calendar/js/calendar.js?v=308f49d2-9:2
    Qe https://mysite.at/apps/calendar/js/calendar.js?v=308f49d2-9:2
    Ge https://mysite.at/apps/calendar/js/calendar.js?v=308f49d2-9:2
    Ze https://mysite.at/apps/calendar/js/calendar.js?v=308f49d2-9:2
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://mysite.at/apps/calendar/js/calendar.js?v=308f49d2-9
Source-Map-Adresse: calendar.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://mysite.at/apps/notifications/js/notifications.js?v=308f49d2-9
Source-Map-Adresse: notifications.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://mysite.at/core/js/dist/main.js?v=308f49d2-9
Source-Map-Adresse: main.js.map

**Comment by georgehrke** [comment]
Looks like a network error.
Can you please check for failed requests in the network tab of the developer console?

**Comment by Tomscloud** [comment]
I see 2 Blocked Documents:
![grafik](https://user-images.githubusercontent.com/68244104/91658726-0e748780-eacb-11ea-908e-62e3912acea8.png)
![grafik](https://user-images.githubusercontent.com/68244104/91658738-28ae6580-eacb-11ea-8738-bd3b22e9c63f.png)

**Comment by georgehrke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by Tomscloud** [comment]
Thank you for your Information, i allready made an Post in the NC Forum, but it seems to be allone with this Problem...

**Comment by georgehrke** [comment]
You said that you are using a commercial Webhoster. They probably have some weird configuration that does not allow Nextcloud to work properly / blocks important requests.

Without knowing the exact config and error log, people in the Forum won't be able to help you.

**Comment by Tomscloud** [comment]
Hmmm, i think i will try a clean new installation, if this is also not working then i will setup NC in my own lokal Network...

**Comment by Tomscloud** [comment]
Hi, Calendar is working now, i can't say it was the update to V2.0.4, Case can be closed now...
