### ISSUE TITLE
2.0.4 is undocumented in CHANGELOG.md

### ISSUE THREAD

**Issue by strugee** [nextcloud/calendar#2517]
(Leaving out the issue template because this is a doc bug.)

**Comment by tcitworld** [comment]
Thx, you can read the [release notes](https://github.com/nextcloud/calendar/releases/tag/v2.0.4) in the meantime.

**Comment by georgehrke** [comment]
See the changelog on the stable branch: https://github.com/nextcloud/calendar/blob/stable2.0/CHANGELOG.md

**Comment by georgehrke** [comment]
Just for the sake of completion - adding it to master as well: https://github.com/nextcloud/calendar/pull/2518
