### ISSUE TITLE
Send Meeting Request by Logged-in User

### ISSUE THREAD

**Issue by Offerel** [nextcloud/calendar#253]
Could you please add a feature, that Meeting Invites/Requests are send via the E-Mail Address of the logged in User instead of the System User which is defined by the Admin?

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
