### ISSUE TITLE
What is "dddd"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/calendar#2535]
We have a new string at Transifex since today and I found related sourcecode

https://github.com/nextcloud/calendar/blob/9594a30460a66a7c0a6fcd23635c992b9c33b349/src/views/Dashboard.vue#L249

Why using "dddd" for week?

**Comment by georgehrke** [comment]
It's a week day, but as the [comment above](https://github.com/nextcloud/calendar/blob/9594a30460a66a7c0a6fcd23635c992b9c33b349/src/views/Dashboard.vue#L248) says

> // TRANSLATORS Please translate only the text in brackets and keep the brackets!

**Comment by georgehrke** [comment]
Should I add better examples to the translators comments, like This translates into Last Wednesday, etc. ?

**Comment by rakekniven** [comment]
Translator comments in vue files are not shown in Transifex :-(

**Comment by georgehrke** [comment]
@MorrisJobke Is there a way to adjust the extraction script to handle vue files as well? (when it comes to // TRANSLATOR comments)

**Comment by rakekniven** [comment]
@MorrisJobke Should I open a new issue? It is getting more and more important as people using vue more and more :-)
