### ISSUE TITLE
Thunderbird / Lightning lost the availbility to send invitiation mails

### ISSUE THREAD

**Issue by kosli** [nextcloud/calendar#254]
I suppose it happend in the upgrade to version 1.4.1 of the app. Since then the functionality in Thunderbird / Lightning (Add-On Version 4.7.4) to invite attendees (send out invitation mail) is disabled. I remember that this happened once with an upgrade of the app quite a while ago, and suddenly mails were sent out by the nextcloud server. Soon it was changed back and since then it worked flawlessly. 

I didn't find any option, neither in the app nor in nextcloud itself, to change the desired behaviour (it seems that the Calendar URL "informs" thunderbird that it is not allowed to send invitation emails?). 

thanks

**Comment by georgehrke** [comment]
most certainly not calendar app related

---

Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
