### ISSUE TITLE
App Admin page of Nextcloud 10 shows [object] entries in calendar app overview

### ISSUE THREAD

**Issue by SomeStrangeName** [nextcloud/calendar#255]
### Steps to reproduce
1. Have a initial nextcloud 10 version
2. Go to Apps page of Administrator view
3. Do an upgrade of the calendar app only to version to 1.4.1 by pressing the upgrade button
4. After page reload you see: 
```
Calendar 1.4.1
by [object Object],[object Object],[object Object] (AGPL-licensed) 
```
### Expected behaviour
Instead of [object Object] there should be a list of names.

### Actual behaviour
A list of objects is shown
by [object Object],[object Object],[object Object] (AGPL-licensed) 

### Server configuration
**Operating system**: Debian Jessie 

**Web server:** Apache

**Database:** MySQL

**Server version:** Nextcloud 10.0 (stable)

**Calendar version:**  1.4.1

**Updated from an older installed version or fresh install:** Update

**Comment by georgehrke** [comment]
The format how to store the authors name in the app's manifest changed from Nextcloud 10 to Nextcloud 11.

This is a very minor issue, won't fix
