### ISSUE TITLE
Endless scrollbar for calendar event with ':' in description

### ISSUE THREAD

**Issue by call-me-matt** [nextcloud/calendar#2560]
### Steps to reproduce
1. import this event: https://osmus.civicrm.org/civicrm/event/ical?reset=1&list=1&id=6
2. show details of the event

or:

1. create a new event
2. type `OpenStreetMap US: Connect 2020` into the description.
3. save the event.

### Expected behaviour
The description is shown propperly

### Actual behaviour
The description fields is correct when showing the preview, but the details in the sidebar are huge!
![image](https://user-images.githubusercontent.com/34400929/92300540-12d1f200-ef5c-11ea-8a08-b8cdb3cc428e.png)

### Calendar app
**Calendar app version:** 2.0.4

### Client configuration
**Browser:** bug present in Firefox 80.0.1, but not in Chromium Version 85.0.4183.83 

**Operating system:** Ubuntu

### Server configuration

**Web server:** Nginx

**Database:** MariaDB

**Nextcloud Version:** 19.0.2

**Updated from an older installed version or fresh install:** Updated

#### Browser log

The javascript console log:
`NONE` (sic,  RepeatFreqInterval.vue:63)

**Comment by georgehrke** [comment]
Does the description box resize to the expected size, when you click it and add a new line?

**Comment by georgehrke** [comment]
In that case, this would be a dup #2187

**Comment by call-me-matt** [comment]
Yes, it does, even when just adding a character!
