### ISSUE TITLE
Optional update notification if a event was changed

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/calendar#2564]
If an event was changed there is no update info sent to the attendees.
It would be nice to send an optional update after the event was changed.

**Comment by georgehrke** [comment]
Duplicate of https://github.com/nextcloud/server/issues/5222

**Comment by jakobroehrl** [comment]
Sorry, it's unclear to me what's the right repo: calendar or server

**Comment by georgehrke** [comment]
In this case Server, because sending out invitation emails is part of the dav app, which is in the server repo.
