### ISSUE TITLE
datepicker too small in width when 'calender weeks' active

### ISSUE THREAD

**Issue by AndreasVS** [nextcloud/calendar#2577]
### Steps to reproduce

* activate "calender weeks" ("Kalenderwochen anzeigen") in the lower left config.
* create new item by clicking in free space of a random day
* click in the start date field to see the date picker

### Expected behaviour

all days of the actual months and the calendar weeks should be inside the picker.

### Actual behaviour

because of the additional column, the items on the left and the items on the right side are on the border. The circle (when hovering) is only partially placed in the picker.

![calendar](https://user-images.githubusercontent.com/17129357/92915006-719bdd80-f42c-11ea-97a4-8af4ae14a7a6.png)

### Calendar app

Version 2.0.4

### Client configuration

Chrome 83
Windows 10

### Server configuration

I use a commercially hosted nextcloud-account so i don't know how to get all requested technical details.

**Comment by georgehrke** [comment]
https://github.com/nextcloud/nextcloud-vue/issues/1014
