### ISSUE TITLE
Multiple instances of the calendar app for booking resources and for planning 

### ISSUE THREAD

**Issue by rollanders** [nextcloud/calendar#2588]
In our organisation we use the current calendar only for bocking resources. Each room has its own calendar. We have currently 7 such calendars/resources. It works very well for our needs. 

However it would get complicated if we want to use the same calendar app for the planning of the personnel (3 persons) and group activities. 

A simple solution would be to have two parallel instances of the calendar-app for the booking of resources (called Resources) and personnel planning (called Planning).

**Comment by alexanderdd** [comment]
Hey, I don't think this is a good idea. Just use different calendars. Maybe you want to use colors or prefixes ("acti-" for activities, "plan-" for plannig) to show the difference.

**Comment by tcitworld** [comment]
#2713 might interest you

**Comment by rollanders** [comment]
Very interesting. Will follow

**Comment by alexanderdd** [comment]
@tcitworld I think we can close this? I don't think this makes sense for the product, and the use case can be achieved in other ways.

**Comment by tcitworld** [comment]
Sounds fine to me
