### ISSUE TITLE
Add ability to group some calendars into 1 category

### ISSUE THREAD

**Issue by rtanalytics** [nextcloud/calendar#259]
If you have many calendars, you would want to be able to group them into several categories.

**Comment by georgehrke** [comment]
How many calendars do you have?

We are planning to make the calendar list sortable: https://github.com/nextcloud/calendar/issues/9
That should cover most uses cases I suppose

**Comment by rtanalytics** [comment]
A use case I see useful is when you have users from different departments, then each department is group.

**Comment by georgehrke** [comment]
I'm voting against implementing this.

@tcitworld What's your call?

**Comment by thomas-mc-work** [comment]
I'd like to request the same. The use case is in my company to have an aggregated view of the vacation days of a group of employees. Also for business trips or other events where the employee isn't available.
