### ISSUE TITLE
Handle Calendar Subscription like a normal (read-only) Calendar

### ISSUE THREAD

**Issue by DragonDev1906** [nextcloud/calendar#2590]
**Is your feature request related to a problem? Please describe.**
After adding a subscription to a google calendar I can see the calendar in nextcloud, but I can't share it, nor can I get the Calendar to show up on Android (DAVx shows the calendar as Webcal and tells me "No Webcal-capable app found").
I would like to sync the google calendar through nextcloud to have a single place to be configured and so the communication to google isn't comming from my mobile phone. In addition the subscription can't be shared, which would be nice so I don't have to configure it for every account.

**Describe the solution you'd like**
Since the nextcloud UI handles the subscription like other calendars it would be nice if:

- [ ] The subscription calendar could be shared with other users (read-only)
- [ ] The subscription calendar would be accessible via CALDav, too (in addition to WEBCal)

**Additional context**
I had to modify the URL to the calendar according to the following template because I only had the embedded version:
https://calendar.google.com/calendar/embed?src={id}&ctz=Europe%2FBerlin
https://calendar.google.com/calendar/ical/{id}/public/basic.ics

Am I using / Have I configured the subscription wrong or why does the subscription callendar only appear in WebCal? It can't be because the subscription is read-only because shared calendars can be read-only, too.

**Comment by shushugah** [comment]
Agreed; We currently have an ICS file on our website, that we'd like to integrate within a shared calendar, but doesn't seem possible, even though the url itself is 100% public/no authentication involved https://techworkersberlin.com/events.ics

Source code: https://github.com/techworkersco/twc-site-berlin/blob/develop/calendar.data.html

**Comment by tcitworld** [comment]
> nor can I get the Calendar to show up on Android (DAVx shows the calendar as Webcal and tells me "No Webcal-capable app found").

You need to use https://icsx5.bitfire.at/ as a "Webcal-capable app".

> The subscription calendar would be accessible via CALDav, too (in addition to WEBCal)

Some clients don't support getting WebCal subscriptions through CalDAV (again, DAVx⁵ with ICSx⁵ does) so we wanted to allowlist them and [expose subscriptions as regular read-only cached calendars](https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/WebcalCaching/Plugin.php#L41-L47). Feel free to open specific issues [in the server repo](https://github.com/nextcloud/server/) to enable this for specific clients.

>  The subscription calendar could be shared with other users (read-only)

I've reopened https://github.com/nextcloud/server/issues/2902 over this.

**Comment by dpprdan** [comment]
In the meantime this is tracked at https://github.com/nextcloud/server/issues/1600
