### ISSUE TITLE
Invitations are not send with organizers Mail-Adress but nextcloud system address

### ISSUE THREAD

**Issue by beepab** [nextcloud/calendar#2591]
### Steps to reproduce
1. Create an event and invite someone
2. Click save

### Expected behaviour
The invited person should get an E-Mail from me as I am the organizer, not the nextcloud-server.

### Actual behaviour
The invited person gets an email from nextcloud@domain.tld. Titled "Surname Name in <Nextcloud-System-Name"
(additional: if inviting in thunderbird, mail is only titled "in <Nextcloud-System-Name" without Surname Name in front.

### Calendar app
**Calendar app version: 2.0.4 

**CalDAV-clients used: Thunderbird Lightning, Nextcloud-Calendar-WebApp

### Client configuration
doesnt matter

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache2

**Database:** Mysql

**PHP version:** 7.3.19-1~deb10u1

**Nextcloud Version:** 19.0.3

**Updated from an older installed version

**App-List**
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - announcementcenter: 3.8.1
  - appointments: 1.7.2
  - apporder: 0.11.0
  - audioplayer: 2.11.2
  - bbb: 1.0.2
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - circles: 0.19.5
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.0.5
  - documentserver_community: 0.1.7
  - drawio: 0.9.7
  - event_update_notification: 1.0.2
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - flowupload: 1.0.0
  - fulltextsearch: 1.4.2
  - geoblocker: 0.3.2
  - guests: 1.5.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 5.0.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - polls: 1.4.3
  - printer: 0.0.3
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quicknotes: 0.6.0
  - ransomware_protection: 1.7.0
  - recommendations: 0.7.0
  - scanner: 0.1.9
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - social: 0.3.1
  - spreed: 9.0.3
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.3
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - dashboardcharts
  - encryption
  - radio

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.3.1",
        "overwrite.cli.url": "http:\/\/10.1.3.166\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "ldapcontacts",
            "ldaporg",
            "mindmap_app",
            "printer",
            "social",
            "radio"
        ],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpdebug": true,
        "app.mail.verify-tls-peer": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "onlyoffice": {
            "verify_peer_off": true
        },
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "\"log_type": "owncloud",
        "logfile": "nextcloud.log",
        "mail_smtpauth": 1
    }
}
```

#### Web server error log (e.g. /var/log/apache)
-
Insert your webserver log here
-

#### Log file (data/nextcloud.log)
-
Insert your nextcloud.log file here
-

#### Browser log
-

**Comment by tcitworld** [comment]
> The invited person should get an E-Mail from me as I am the organizer, not the nextcloud-server.

Most Nextcloud installations don't have an email system that is set up to allow sending emails on behalf of regular users (users may have different/external email domains to the Nextcloud instance), so this is the only way this can work.

Most groupware suites (Thunderbird, Evolution, probably Outlook) allow to send emails directly to participants when you use them to manage events. In that case you can disable the *Send invitations to participants* option in Nextcloud's Groupware settings to avoid invitations being sent out twice.

**Comment by Peque** [comment]
@tcitworld Would you mind reopening and maybe just retagging it as a feature request?

Since Nextcloud brands itself as a "completely integrated content collaboration platform", it sounds reasonable to expect that feature (already implemented in Thunderbird/Evolution) from Nextcloud, at least some day. Don't you agree?

Maybe this is more like a Calendar and Mail apps integration, but I think there should be a way to do it from Nextcloud. :blush:

**Comment by tcitworld** [comment]
> Since Nextcloud brands itself as a "completely integrated content collaboration platform", it sounds reasonable to expect that feature (already implemented in Thunderbird/Evolution) from Nextcloud, at least some day. Don't you agree?

It's the same feature. Thunderbird/Evolution are mail clients that send the email themselves but Nextcloud is a server app that sends a mail on behalf of users. The only difference is that a different address is used to send the email in the process. This can indeed lower the trust that a invitee has in the email, but that's all I can see.

Since some users won't use the mail app or even have it configured, we would always need the server to send the invitations as a fallback anyway.

From a technical point of view, sending the invitations through the organizer's own email would require at least the mail app exposing a "kinda" public API (or such a thing moved to the server), which isn't planned AFAIK.

Since the original post was formatted as a bug report and not a feature request, I'd appreciate if you created a new proper feature request issue for this instead. :pray:

**Comment by Peque** [comment]
@tcitworld https://github.com/nextcloud/calendar/issues/2617
