### ISSUE TITLE
Style past events differently

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#26]

**Comment by alexanderdd** [comment]
For example, make past events grey? Or different shades of grey? Or desaturate the original color?

**Comment by sitnarf** [comment]
As a workaround, you can use Stylus or similar to apply custom CSS:

.fc-event-past {
    opacity: 0.5;
}

**Comment by ChristophWurst** [comment]
@nimishavijay @jancborchardt what do you think? Shall we do this?

**Comment by tcitworld** [comment]
Cancelled events titles are crossed out, so you can still differentiate with past events.
