### ISSUE TITLE
Export events to csv file

### ISSUE THREAD

**Issue by rtanalytics** [nextcloud/calendar#260]
It would be great for data analysts to have calendar events exported in CSV format.

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by tcitworld** [comment]
@georgehrke As for #261 I feel this feature would have bigger chances to happen here instead of the nc dav app.

**Comment by georgehrke** [comment]
@tcitworld but that means we would have to implement an ics to csv converter in JS and vice versa.
Not a big fan of this.

exporting and importing csv will clutter the interface while benefiting only very few users.
IMO this should either:
- go into the dav app with some console interface
- go into a dedicated app
