### ISSUE TITLE
reminder settings are broken in latest version (for Nc 20)

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/calendar#2604]
### Steps to reproduce
1. Create an appointment
2. Set a reminder
3. try to edit the time

### Expected behaviour
When creating the appointment, the 'old' method was quite OK and flexible. The new method is a bit confusing to me, but on my private server at least it works:
First pick a day:
![Screenshot_20200923_203503](https://user-images.githubusercontent.com/551757/94054744-4d50e100-fddc-11ea-8a80-58aadaa2340d.png)
Then edit the time:
![Screenshot_20200923_203546](https://user-images.githubusercontent.com/551757/94054792-5d68c080-fddc-11ea-903f-c700dbd38987.png)

This unfortunately does not work on cloud.nc.c with Nc 20RC1. hitting 'edit time' just does nothing there.

**Comment by rullzer** [comment]
Caused by https://github.com/nextcloud/calendar/blob/master/src/components/Editor/Alarm/AlarmListItem.vue#L26

However when you remove that you have to press the ... again to save.
I ahve no clue how to fix it.
