### ISSUE TITLE
blank calendar page

### ISSUE THREAD

**Issue by Docnight** [nextcloud/calendar#2607]
### Steps to reproduce
1. Updated from latest 19.x.x to 20.0.0 RC2

### Expected behaviour
Calendar should work

### Actual behaviour
Calendar page blank, while all other "app pages" work well

### Calendar app
2.1.2

### Client configuration
**Browser:** all browsers

**Operating system:** Win, OSX, ...

### Server configuration

**Operating system**: Shared Hoster (all-inkl.com)

**Web server:** Shared Hoster (all-inkl.com)

**Database:** MySQL

**PHP version:** 7.3 (also tried with 7.4)

**Nextcloud Version:** 20.0.0 RC2

**Updated from an older installed version or fresh install:** latest stable 19.x.x

**List of activated apps:**
Accessibility
1.6.0

Calendar
2.1.2

Collaborative tags
1.10.0

Comments
1.10.0

Contacts
3.3.0

Contacts Interaction
1.1.0

Custom CSS
1.7.0

Deleted files
1.10.1

Federation
1.10.1

File sharing
1.12.0

First run wizard
2.9.0

Log Reader
2.5.0

Monitoring
1.10.0

NextBackup
20.9.0

Nextcloud announcements
1.9.0

Notifications
2.8.0

Password policy
1.10.1

PDF viewer
2.0.1

Photos
1.2.0

Privacy
1.4.0

RainLoop
7.0.3

Recommendations
0.8.0

Right click
0.17.0

Share by mail
1.10.0

Support
1.3.0

Tasks
0.13.3

Text
3.1.0

Theming
1.11.0

Update notification
1.10.0

Usage survey
1.8.0

User status
1.0.0

Versions
1.13.0

Video player
1.9.0

Weather status
1.0.0

```
No command line access due to shared hoster!
```
Config.php:

<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxxxx',
  ),
  'datadirectory' => 'xxxxxxxxxxxx',
  'dbtype' => 'mysql',
  'version' => '20.0.0.8',
  'overwrite.cli.url' => 'http://xxxxxxxxx',
  'dbname' => 'xxxxxxxxxx',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'p94tb_',
  'mysql.utf8mb4' => false,
  'dbuser' => 'xxxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxxxxx',
  'installed' => true,
  'tempdirectory' => 'xxxxxxxxxxxxx',
  'mail_smtpmode' => 'sendmail',
  'mail_sendmailmode' => 'pipe',
  'mail_from_address' => 'xxxxxxx',
  'mail_domain' => 'xxxxxxxx',
  'maintenance' => false,
  'updater.release.channel' => 'beta',
  'theme' => '',
  'loglevel' => 2,
  'app_install_overwrite' => 
  array (
    0 => 'calendar',
    1 => 'contacts',
  ),
  'updater.secret' => 'xxxxxxxx',
);

```

### Logs
```
No access to server logs. nextcloud log is pretty huge and doesn't include any calendar entries.
```
### Additional Description of the issue
```
The calendar page is blank and also the source code between the <div> tags for the content of the calendar app is empty, so no calendar part is been loaded at all.
```

**Comment by tcitworld** [comment]
Did you try to force refresh the page? Or remove and reinstall the app (no data will be lost).

**Comment by r0xx5** [comment]
Same problem. Newest Firefox/Chrome opens the Calender-App correcty, but can't create events. It says always "the event does not exists" Older Browsers showing blank Page. Browser Console write following error: ReferenceError: ResizeObserver is not defined.

**Comment by Docnight** [comment]
Tried with my personal macbook with newest firefox. Works well. My business notebook Qin10 Firefox 68.12.0 shows blank page. Anything I can log or try to do?

**Comment by Docnight** [comment]
Updated firefox, works now.

**Comment by Dalker** [comment]
Same problem here. Rebooting and performing various system updates did not solve the problem.

**Comment by Dalker** [comment]
After more testing:

- server-side calendar is still correctly managed and served as caldav (can be sync'ed, updated, etc from android app and from thunderbird plugin)
- server-side production of web page showing calendar lags forever: "blank" calendar appears, and "turning arrow icon" stays eternally, never replaced by actual content - this via several client browsers, three different computers and two different ISPs

**Comment by tcitworld** [comment]
Possibly related to https://github.com/nextcloud/calendar/pull/2620

**Comment by Dalker** [comment]
This issue was resolved (at least for me) when updating to version 20.0.2 of Nextcloud. It was still present in the release candidate preceding that version.
Simultaneously, the integrated kanban board and task list apps started working properly as well.
Note that I had started updating from the beta channel after this issue started, which is why I am quite confident about which specific update solved it. I am now going back to updating only from Stable, as recommended for daily use.

**Comment by marty1885** [comment]
I'm still getting the issue (doesn't look like 2620) with Nextcloud 20.0.2. Am I doing something wrong?

**Comment by madsurgeon** [comment]
Same here with 20.0.4

**Comment by cottoa00** [comment]
Similar.. no main calendar window display.. silent fail. I'm on NC 20.0.2 (was a fresh build and first additions were calendar). Had a small calendar successfully loaded in 2.1.2 and before quitting decided to update to 2.1.3. That was when calendar display window disappeard. Same behavior in Firefox and Brave.
Developer tools/Console shows errors;
TypeError: e.replaceAll is not a function
TypeError: Cannot read property '$el' of undefined
followed by 4 GET (404)... 2 re: avatar and 2 others

**Comment by tcitworld** [comment]
Fixed in https://github.com/nextcloud/calendar/pull/2822, needs a new release. [Recent browsers](https://caniuse.com/mdn-javascript_builtins_string_replaceall) should work fine.

**Comment by cottoa00** [comment]
Know case is closed but just wanted to follow-up... was able to roll back to Cal 2.1.2 and problem cleared up... guess supported my older browser? All is good. Thanks for the cool link to the javascript browser compatibility webpage.
