### ISSUE TITLE
Import calendar events from CSV

### ISSUE THREAD

**Issue by rtanalytics** [nextcloud/calendar#261]
Suppose you have a list of events in csv, you would want to import it to your calendar.

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by stefan-niedermann** [comment]
@rtanalytics did you open an issue in the server repository? If yes, could you please paste a link here?

@georgehrke From my point of view it is unrelated where the actual storage backend is. Parsing and formatting a `CSV` file is definitely something that should be done on the client side - this app. When ready, it can should do the actual import and call the corresponding APIs with the new information - whether this API is located in the server or the calendar app does not really matter.

I'd like to ask you to rethink standpoint. There are multiple users which are expecting this feature as pendant to Google Calendars (which supports importing a `CSV` file).

**Comment by tcitworld** [comment]
From the related issue: https://github.com/nextcloud/calendar/issues/260#issuecomment-269078868, this makes more sense as an admin CLI command or a 3rd-party app.

**Comment by Jaxom99** [comment]
I'm in the same situation, and I can see the need still exists! See also https://github.com/nextcloud/calendar/issues/136#issuecomment-1268296884 from @kaffeeringe

The question was raised in https://github.com/nextcloud/calendar/issues/646 and https://github.com/nextcloud/calendar/issues/260 back in 2016. Maybe things have changed ?  There is a javascript' ics2csv handler here : https://github.com/johnyluyte/ICS-to-Excel-CSV/

With the recent withdrawal of this function from Thunderbird, users are kind of stuck. What could be a way forward ?

**Comment by techrivertree** [comment]
It would be very helpful if we could import csv files. Microcrap wont allow you to export an outlook calendar in ICS, only CSV. I am using nextcloud for the calendar\. Lets hope the devs add this capability.
