### ISSUE TITLE
Directly open event in sidebar when cmd key is pressed

### ISSUE THREAD

**Issue by rogelio-o** [nextcloud/calendar#2610]
Every time I want to open the sidebar I have to do two clicks. It's frustrating.

It'd be great if when de cmd (or ctrl) key is pressed the event would be directly open in the sidebar.

Another option could be open in the sidebar if double-clicking over the event slot.

If the feature is ok, I can make the contribution.

**Comment by kaleb** [comment]
What version are you on? On my instance, I click on an event once and the sidebar opens.

**Comment by rogelio-o** [comment]
I'm on 2.0.4, but I've also tried with master branch and the behaviour is the same: when you click on the event a pop up is open and you have to click "more" to open the sidebar.

**Comment by kaleb** [comment]
@rogelio-o I am 2.1.2 and do not have this issue.

**Comment by rogelio-o** [comment]
You're right, the sidebar is opened when you click on an event if you have a configuration property unchecked ("Activate simplified editor"). It also works on v2.0.4.

I'm closing the issue because this property is enough for me. I just didn't realize about it.

**Comment by kaleb** [comment]
@rogelio-o I had no idea what that checkbox did. Now I do. I will be leaving it checked! It should probably be the default.
