### ISSUE TITLE
Cannot activate/deactivate calender i Android webb browser

### ISSUE THREAD

**Issue by rollanders** [nextcloud/calendar#2616]
I have NC19.03 and Calendar 2.0.4 on Ubuntu18.04. When accessing the site in Android webbbrowser (chrome) I cannot activate/deactivate calendars. The only thing that happens when I touch the calendar name is that I can change its position. Same behaviour in NC20 RC3 and Calendar 2.1.2 
In fact the sharing and three dots icons do not work either. 
BUT found out this works in Android Firefox browser

**Comment by Eideard** [comment]
Yes we have the same problem. Same Version of Calendar on Ubuntu 20.04 Server.
Tested on a Samsung Galaxy XCover 4 with updated google chrome.
On my Honor 6X with updated google chrome its all fine!

**Comment by szaimen** [comment]
Fixed with https://github.com/nextcloud/calendar/pull/3475
