### ISSUE TITLE
Wrong time in editor

### ISSUE THREAD

**Issue by sinus-x** [nextcloud/calendar#2618]
The editor wrongly sets start and end time of an event.

The event was imported from `ical` file and had following format:

```ical
BEGIN:VCALENDAR
VERSION:2.0
PRODID:(identifier)
BEGIN:VEVENT
UID:20200929T130000Z-259437
DTSTART:20200929T130000Z
DTEND:20200929T145000Z
SUMMARY:(title)
LOCATION:(location)
END:VEVENT
END:VCALENDAR
```

### Steps to reproduce
1. Create an event starting at 15:00 CEST (Central European Summer Time, +02:00) by importing `ical` file cited above.
2. Click the event to open editor.

### Expected behaviour
Event is reported to start at 15:00.

### Actual behaviour
Event is reported to start at 13:00 (the event box itself is positioned correctly at 15:00).

### Calendar app
**Calendar app version:** 2.0.4
### Client configuration
**Browser:** Firefox 81

### Server configuration

**Operating system**: Debian

**PHP version:** 7.2.33

**Nextcloud Version:** 18.0.4

**Comment by GyroW** [comment]
I too have a similar issue with remote calendars. 
![2020-10-19_111558_](https://user-images.githubusercontent.com/8619043/96426290-57a8a400-11fd-11eb-8a47-e2c0544dcf1d.png)
![2020-10-19_111528_](https://user-images.githubusercontent.com/8619043/96426311-5e371b80-11fd-11eb-9d07-2ec417d863af.png)

Notice the discrepancy between the calendar view and the pop-up for remote calendars. 

## Calendar app

Calendar app version: 2.0.4

## Client configuration

Browser: Firefox 81

##Server configuration

Operating system: Raspbian ARM

PHP version: PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )

Nextcloud Version: 19.0.3

**Comment by kevinmoilar** [comment]
Fixed for me with update from Nextcloud 10.0.3 to 10.0.4 and Calendar app update to 2.3.2

**Comment by JB1985** [comment]
Hi, 

this Bug is still there.

![image](https://github.com/nextcloud/calendar/assets/9932751/4cbe7e91-4719-432b-89d3-058dfa27e897)

Nextcloud: 25.0.7
Calendar: 4.4.2

**Comment by ChristophWurst** [comment]
File a new ticket
