### ISSUE TITLE
Convert existing calendar without task list to calendar with task list

### ISSUE THREAD

**Issue by trvrcr** [nextcloud/calendar#2627]
I have a few calendars that I have shared with some people.
and I want to create a task list linked  to that calendar.

Is there an easy way of converting a calendar without task list to a calendar with task list?
so I am able to avoid having to:
- create new calendars with the extended functionality
- copy over all events
- share new calendar with everyone

**Comment by tcitworld** [comment]
You should be able to:
* create new calendars with task list support
* exporting the old calendar to an `.ics` file
* importing the file to the new calendars
* share new calendar with everyone

Unfortunately, the iCalendar/CalDAV specification doesn't describe how to convert from one type to another, so even if we handled this in server, the 3rd-party apps would be lost.

**Comment by trvrcr** [comment]
It's unfortunate it's not possible to convert.
I was able to use your instructions successfully.

Thank you

**Comment by sbrl** [comment]
No, that solution does not work @tcitworld. If you create a new calendar via the tasks app, you can't add any events to it even though it shows up in the calendar app.

**Comment by tcitworld** [comment]
>  If you create a new calendar via the tasks app

I didn't say to create a calendar in the tasks app. I said to create a new calendar with task support in the calendar app.
![image](https://github.com/nextcloud/calendar/assets/2197836/f779d6a1-bf61-4009-be45-7e7ee0d6d6d0)
