### ISSUE TITLE
no share button in firefox 50 but ok in chrome and firefox 52

### ISSUE THREAD

**Issue by ckiw** [nextcloud/calendar#263]
### Steps to reproduce
1. Go on calendar app v1.4.1 with firefox 50
2. There is no share button
3. If a calendar is already shared, the button and the menu are ok

Nothing specific in the console and fresh install
Easy to test on framagenda.org

**Comment by ckiw** [comment]
![Uploading Capture du 2016-12-26 15-10-44.png…]()

**Comment by tcitworld** [comment]
Is the Share API enabled in the administration settings ?

**Comment by ckiw** [comment]
Yes it is :) 

As I detected no problem in other browsers it must be problem in relation with the browser and not the specific configuration.

If you need more info, I'm here to help

**Comment by ckiw** [comment]
![img](https://cloud.githubusercontent.com/assets/3486286/21485129/2216cf64-cb9e-11e6-84d2-91e8c99962d2.png)

**Comment by ckiw** [comment]
and in chrome 
![img2](https://cloud.githubusercontent.com/assets/3486286/21485145/65f8142c-cb9e-11e6-8495-77ebf0b31d02.png)

**Comment by tcitworld** [comment]
Do you have any adblocker enabled on Firefox ? You can disable it for framagenda.org.
