### ISSUE TITLE
Calendar page is blank with locale zh_Hant_TW

### ISSUE THREAD

**Issue by yan12125** [nextcloud/calendar#2633]
### Steps to reproduce
1. Change Nextcloud locale to "zh_Hant_TW" Chinese (Traditional, Taiwan) from https://my-server/index.php/settings/user
2. Go to calendar page https://my-server/index.php/apps/calendar/dayGridMonth/now

### Expected behaviour
A working calendar

### Actual behaviour
The page is blank. It works again if I change the locale to English.

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.1.2

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
The Nextcloud calendar app

### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 80.0.1

**Operating system:** (e.g. Arch Linux)
Arch Linux

### Server configuration

**Operating system**: (e.g. Debian 8)
Arch Linux

**Web server:** (e.g. Apache, Nginx,...)
Apache 2.4.46

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
PostgreSQL 12.4

**PHP version:** (e.g. 7.0.3)
7.4.11

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
20.0.0

**Updated from an older installed version or fresh install:**
Updated from an older installed

**List of activated apps:**

```
  - activity: 2.13.1
  - admin_audit: 1.10.0
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - contacts: 3.4.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - files: 1.15.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - oauth2: 1.8.0
  - provisioning_api: 1.10.0
  - settings: 1.2.0
  - tasks: 0.13.3
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "version": "20.0.0.9",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "defaultapp": "calendar",
        "appstoreenabled": false,
        "log_type": "syslog",
        "config_is_read_only": true,
        "loglevel": 2,
        "maintenance": false,
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***"
    }
}
```

#### Web server error log (e.g. /var/log/apache)
```
<my IP> - - [08/Oct/2020:10:59:10 +0800] "GET /index.php/apps/calendar/dayGridMonth/now HTTP/2.0" 200 5124
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /core/js/dist/main.js?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /core/js/dist/files_fileinfo.js?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /core/js/dist/files_client.js?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /core/l10n/zh_TW.js?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /core/js/dist/unified-search.js?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/files/img/app.svg?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/activity/img/activity.svg?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/contacts/img/app.svg?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/calendar/img/calendar.svg?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/tasks/img/tasks.svg?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/settings/img/admin.svg?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/settings/img/apps.svg?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /core/img/logo/logo.svg?v=1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/calendar/l10n/zh_TW.js?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/calendar/js/calendar.js?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/settings/img/users.svg?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /apps/settings/img/help.svg?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /core/img/actions/logout.svg?v=ad00b8a1 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:11 +0800] "GET /index.php/avatar/yen/64?v=0 HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:12 +0800] "PROPFIND /remote.php/dav/ HTTP/2.0" 207 228
<my IP> - - [08/Oct/2020:10:59:12 +0800] "GET /apps/calendar/js/chunks/calendar.126.ed70695de3b7c5c1db83.js HTTP/2.0" 304 -
<my IP> - - [08/Oct/2020:10:59:12 +0800] "GET /ocs/v2.php/search/providers?from=%2Fapps%2Fcalendar%2FdayGridMonth%2Fnow HTTP/2.0" 200 232
<my IP> - - [08/Oct/2020:10:59:12 +0800] "PROPFIND /remote.php/dav/principals/users/yen/ HTTP/2.0" 207 689
<my IP> - - [08/Oct/2020:10:59:13 +0800] "PROPFIND /remote.php/dav/calendars/yen/ HTTP/2.0" 207 1965
```

#### Log file (data/nextcloud.log)
(Nothing new when I refresh the calendar page)

#### Browser log
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 utils.js:35:9
No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
[INFO] calendar: 
Initial settings:
	- AppVersion: 2.1.2
	- EventLimit: true
	- FirstRun: false
	- ShowWeekNumbers: false
	- ShowTasks: true
	- ShowWeekends: true
	- SkipPopover: true
	- SlotDuration: 00:30:00
	- TalkEnabled: false
	- TasksEnabled: true
	- Timezone: automatic
 
Object { app: "calendar", uid: "yen" }
ConsoleLogger.js:46:10
[DEBUG] calendar: The calendar app is using version 2.2019c of the timezone database 
Object { app: "calendar", uid: "yen" }
ConsoleLogger.js:42:10
RangeError: invalid language tag: "zh-hant_tw"
    el main.js:4060
    $c main.js:4031
    ua main.js:965
    processRawCalendarOptions main.js:7193
    _computeOptionsData main.js:7167
    ua main.js:965
    e main.js:6999
    t main.js:52
    mounted FullCalendar.js:21
    VueJS 13
    <anonymous> main.js:68
    Webpack 3
        o
        <anonymous>
        <anonymous>
vue.runtime.esm.js:1888:12
Fallback to locale en moment.js:83:11
[INFO] calendar: Updated moment locale: nextcloud-calendar-fake-locale-en-zh-tw 
Object { app: "calendar", uid: "yen" }
ConsoleLogger.js:46:10
TypeError: t is undefined
    handler FullCalendar.js:60
    VueJS 4
vue.runtime.esm.js:1888:12
TypeError: r is undefined
    handler FullCalendar.js:75
    VueJS 4
vue.runtime.esm.js:1888:12
TypeError: r is undefined
    handler FullCalendar.js:75
    VueJS 4
vue.runtime.esm.js:1888:12
session heartbeat polling started session-heartbeat.js:97:9
Uncaught TypeError: e.$refs.fullCalendar.getApi() is undefined
    mounted CalendarGrid.vue:197
    c index.js:27
CalendarGrid.vue:197
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, app: "unified-search", uid: "yen" }
ConsoleLogger.js:42:18
[DEBUG] calendar: Current user principal is /remote.php/dav/principals/users/yen/ 
Object { app: "calendar", uid: "yen" }
ConsoleLogger.js:42:10
TypeError: t is undefined
    handler FullCalendar.js:60
    VueJS 4
vue.runtime.esm.js:1888:12
TypeError: r is undefined
    handler FullCalendar.js:75
    VueJS 4
vue.runtime.esm.js:1888:12
TypeError: r is undefined
    handler FullCalendar.js:75
    VueJS 4
vue.runtime.esm.js:1888:12
```

**Comment by littlef0x** [comment]
Same here with locale 'Chinese (Simplified, China)'. Based on my test, all locales with a comma can result in blank page. As a workaround, you can change it to others without comma.
Browser logs (partial):

`RangeError: invalid language tag: "zh-hans_cn"
    el main.js:4060
    $c main.js:4031
    ua main.js:965
    processRawCalendarOptions main.js:7193
    _computeOptionsData main.js:7167
    ua main.js:965
    e main.js:6999
    t main.js:52
    mounted FullCalendar.js:21
    VueJS 13
    <anonymous> main.js:68
    Webpack 3
vue.runtime.esm.js:1888:12
Fallback to locale en moment.js:83:11
session heartbeat polling started session-heartbeat.js:97:9
Files_PDFViewer initialized for public page 
Object { isPublicPage: null, canDownload: true, isSecureViewerAvailable: false }
public.js:30:9
[INFO] calendar: Updated moment locale: nextcloud-calendar-fake-locale-en-zh-cn 
Object { app: "calendar", uid: "***" }
ConsoleLogger.js:46:10
TypeError: t is undefined
    handler FullCalendar.js:60
    VueJS 4
vue.runtime.esm.js:1888:12
TypeError: r is undefined
    handler FullCalendar.js:75
    VueJS 4
vue.runtime.esm.js:1888:12
TypeError: r is undefined
    handler FullCalendar.js:75
    VueJS 4
vue.runtime.esm.js:1888:12
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, app: "unified-search", uid: "***" }
ConsoleLogger.js:42:18
Uncaught TypeError: e.$refs.fullCalendar.getApi() is undefined
    mounted CalendarGrid.vue:197
    c index.js:27
    setTimeout handler*l index.js:38
    mounted CalendarGrid.vue:195
    VueJS 13
    <anonymous> main.js:68
    Webpack 3
CalendarGrid.vue:197
[DEBUG] calendar: Current user principal is /remote.php/dav/principals/users/***/ 
Object { app: "calendar", uid: "***" }
ConsoleLogger.js:42:10
TypeError: t is undefined
    handler FullCalendar.js:60
    VueJS 10
    addCalendar calendars.js:66
    g vuex.esm.js:840
    commit vuex.esm.js:462
    commit vuex.esm.js:461
    _withCommit vuex.esm.js:620
    commit vuex.esm.js:460
    commit vuex.esm.js:405
    t calendars.js:443
    t calendars.js:442
    u runtime.js:63
    _invoke runtime.js:293
    y runtime.js:118
    fe calendar.js:2
    i calendar.js:2
    promise callback*fe calendar.js:2
    i calendar.js:2
    ge calendar.js:2
    ge calendar.js:2
    getCalendars calendars.js:440
    g vuex.esm.js:847
    dispatch vuex.esm.js:512
    dispatch vuex.esm.js:402
    t Calendar.vue:215
    u runtime.js:63
    _invoke runtime.js:293
    y runtime.js:118
    Hp calendar.js:2
    i calendar.js:2
    promise callback*Hp calendar.js:2
    i calendar.js:2
    promise callback*Hp calendar.js:2
    i calendar.js:2
    Zp calendar.js:2
    Zp calendar.js:2
    beforeMount Calendar.vue:187
    VueJS 27
    <anonymous> main.js:68
    Webpack 3
vue.runtime.esm.js:1888:12
TypeError: r is undefined
    handler FullCalendar.js:75
    VueJS 10
    addCalendar calendars.js:66
    g vuex.esm.js:840
    commit vuex.esm.js:462
    commit vuex.esm.js:461
    _withCommit vuex.esm.js:620
    commit vuex.esm.js:460
    commit vuex.esm.js:405
    t calendars.js:443
    t calendars.js:442
    u runtime.js:63
    _invoke runtime.js:293
    y runtime.js:118
    fe calendar.js:2
    i calendar.js:2
    promise callback*fe calendar.js:2
    i calendar.js:2
    ge calendar.js:2
    ge calendar.js:2
    getCalendars calendars.js:440
    g vuex.esm.js:847
    dispatch vuex.esm.js:512
    dispatch vuex.esm.js:402
    t Calendar.vue:215
    u runtime.js:63
    _invoke runtime.js:293
    y runtime.js:118
    Hp calendar.js:2
    i calendar.js:2
    promise callback*Hp calendar.js:2
    i calendar.js:2
    promise callback*Hp calendar.js:2
    i calendar.js:2
    Zp calendar.js:2
    Zp calendar.js:2
    beforeMount Calendar.vue:187
    VueJS 27
    <anonymous> main.js:68
    Webpack 3
vue.runtime.esm.js:1888:12
TypeError: r is undefined
    handler FullCalendar.js:75
    VueJS 10
    addCalendar calendars.js:66
    g vuex.esm.js:840
    commit vuex.esm.js:462
    commit vuex.esm.js:461
    _withCommit vuex.esm.js:620
    commit vuex.esm.js:460
    commit vuex.esm.js:405
    t calendars.js:443
    t calendars.js:442
    u runtime.js:63
    _invoke runtime.js:293
    y runtime.js:118
    fe calendar.js:2
    i calendar.js:2
    promise callback*fe calendar.js:2
    i calendar.js:2
    ge calendar.js:2
    ge calendar.js:2
    getCalendars calendars.js:440
    g vuex.esm.js:847
    dispatch vuex.esm.js:512
    dispatch vuex.esm.js:402
    t Calendar.vue:215
    u runtime.js:63
    _invoke runtime.js:293
    y runtime.js:118
    Hp calendar.js:2
    i calendar.js:2
    promise callback*Hp calendar.js:2
    i calendar.js:2
    promise callback*Hp calendar.js:2
    i calendar.js:2
    Zp calendar.js:2
    Zp calendar.js:2
    beforeMount Calendar.vue:187
    VueJS 27
    <anonymous> main.js:68
    Webpack 3`
