### ISSUE TITLE
ics originating from Outlook doesn't import - with no complaint either

### ISSUE THREAD

**Issue by beccon4** [nextcloud/calendar#2635]
### Steps to reproduce
1. Change a recurring event and send it to its participant
2. import the ics into Nextcloud/Calender where the recurring event we're changing does not exists in Nextcloud yet. (*)
3. miss the event there

### Expected behaviour
Even when there is no event we can change, import the new time/place
(*) I'm part of a team with my client. We use Outlook there. To have important events in my own calendar/notification I import them into Nextcloud as a shadow calender for this event. For that I forward the Outlook invitation to my own email - dig it out from Rainloop and import it.

### Actual behaviour
Actually the ics imports fine, no complaints whatsoever but the event disappeared with no traces at all. 

### Calendar app
I run Nextcloud 20.0.0 with Calendar 2.1.2

**Comment by sigma67** [comment]
I can confirm that this is happening with all recurring events export from Microsoft calendar (outlook.com). Regular events import fine, recurring events don't show up in the imported calendar

**Comment by sigma67** [comment]
@hast0011

I believe I found the issue. Outlook.com/MS Exchange Server 2010 sets RRULE for repeating events **that never end** as follows:

`RRULE:FREQ=YEARLY;BYMONTHDAY=22;BYMONTH=7;UNTIL=20210721T220000Z`

The issue here is probably that UNTIL is **before** the event actually occurs, which leads to Nextcloud UI not displaying them

**Comment by sigma67** [comment]
Here's a simple gist to fix any ICS export from outlook.com with repeating events for use in Nextcloud:

https://gist.github.com/sigma67/7af772ecd1c5268b307a3db4229922d5

**Comment by tcitworld** [comment]
I'm not sure what we can do if Microsoft gives us wrong data like this. This is valid icalendar data, we can't really detect whether it's a bad behavior or an intended one.

**Comment by joshtrichards** [comment]
Microsoft seems to have fixed this. Tested just now via outlook.com:

```
RRULE:FREQ=YEARLY;INTERVAL=1;BYMONTHDAY=22;BYMONTH=7
```
