### ISSUE TITLE
the menu covers the date in list view

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/calendar#2637]
Open list view in calendar.

Nextcloud: 20.0
![obraz](https://user-images.githubusercontent.com/3769853/95581872-07318980-0a3a-11eb-9c0d-90a604674850.png)

**Comment by pawlosck** [comment]
![obraz](https://user-images.githubusercontent.com/3769853/95582191-9c348280-0a3a-11eb-9730-370faef0df6a.png)

**Comment by pawlosck** [comment]
https://github.com/nextcloud/contacts/issues/1816

**Comment by tcitworld** [comment]
https://github.com/nextcloud/server/issues/16934

**Comment by miaulalala** [comment]
New design solves this
