### ISSUE TITLE
Calendar in Estonian is mixed with Chinese

### ISSUE THREAD

**Issue by emenov** [nextcloud/calendar#264]
I'm using OC 9.1.3 stable.

When I select Estonian language, then I see it mixed with Chinese characters:
https://s29.postimg.org/92zetrlrb/owncloud_est_language_error.png

How can I fix it?

**Comment by tcitworld** [comment]
Can you check the translation's correct on transifex ? https://www.transifex.com/nextcloud/nextcloud/calendar/

**Comment by emenov** [comment]
Translation looks okay. I guess we have some other issue here. Would need a developer to look deeper into it.

**Comment by georgehrke** [comment]
We use the translations included in full calendar. There is probably an issue with the full calendar not recognizing the language code.

**Comment by georgehrke** [comment]
@emenov Which one did you select?
I can't seem to find estonian.

<img width="254" alt="langs" src="https://cloud.githubusercontent.com/assets/1250540/21955918/2f1686ec-da75-11e6-9e6c-34109b993a75.png">

**Comment by emenov** [comment]
@georgehrke 
I selected that one:
![vimg_20170114_191355](https://cloud.githubusercontent.com/assets/13866914/21956719/19035b5e-da8f-11e6-8d12-99b4ded14cb3.jpg)
