### ISSUE TITLE
Adding new entry not possible in 2.0.4 - says 'Invalid Date' on all dates

### ISSUE THREAD

**Issue by Digitale-Substanz** [nextcloud/calendar#2647]
### Steps to reproduce
1. Open Calendar app in browser
2. Click on a date or
3. Click on "+ Neuer Termin" blue button in the top left corner

### Expected behaviour
An input dialogue should open that already has pre-chosen the selected date range. The input form should load completely, so that fields can be filled in.

### Actual behaviour
The input dialogue starts to open. Applies to both, simple interface and advanced interface. Both open, but do not load completely. Instead, in the date fields it reads `Invalid Date`. Other input fields are not rendered, but only the loading spinner spins eternally. No data input is possible.

### Calendar app
**Calendar app version:** 2.0.4

**CalDAV-clients used:** DAVx5, Evolution, Gnome Calendar. Note, bug happens in the web app.

### Client configuration
**Browser:** Firefox 81.0, Chromium 85.0.4183.1

**Operating system:** Ubuntu Linux 18.04

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL 5.7.28

**PHP version:** 7.2.33

**Nextcloud Version:** 19.04

**Updated from an older installed version or fresh install:** Updated from older versions

**List of activated apps:** 

- Accessibility
- Activity
- Brute-force settings
- Calendar
- Collaborative tags
- Comments
- Contacts
- Contacts Interaction
- Deck
- Deleted files
- Federation
- File sharing
- First run wizard
- Log Reader
- Monitoring
- Nextcloud announcements
- Notifications
- ONLYOFFICE
- Password policy
- PDF viewer
- Photos
- Privacy
- Recommendations
- Right click
- Share by mail
- Support
- Tasks
- Text
- Theming
- Update notification
- Usage survey
- Versions
- Video player 

Please find attached a screenshot of advanced UI showing the error.

**Comment by tcitworld** [comment]
Please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md)

Unless you fill out the issue template completely including all logs, we can't go ahead and help you.

**Comment by Digitale-Substanz** [comment]
Updated the bug report according to issue template.

**Comment by Leprazoriy** [comment]
Same problem! And not work Nextcloud notifications for calendar app, for example Talk app notification work fine!

![Calendar](https://user-images.githubusercontent.com/72513510/96387362-2488f500-11aa-11eb-9575-b3b4ebb3ca0a.jpg)

**Comment by Leprazoriy** [comment]
Update! On one of my servers, I found that this error appears when trying to create a new event under the account of the first user (administrator). Regular users and other administrators do not have this error. If you deny the first user administrator rights and make him a regular user, the error still does not disappear. Also, on an identical server (cloud version, application version and other settings are completely the same), the error was not reproduced!

**Comment by Digitale-Substanz** [comment]
Issue seems not to be browser related. Also applies to Opera 72.0.3815.320. Calendar app in this stage is not usable anymore.

**Comment by tcitworld** [comment]
Closing in favor of #2662 which shows logs.
