### ISSUE TITLE
Email with event cancelation is send due to any action

### ISSUE THREAD

**Issue by mbreskovec** [nextcloud/calendar#2649]
### Steps to reproduce
1. Create an event and invite another participant. 
2. Do any update to event. 
3. Or let other attendee do any change or accept meeting. 
4. Wait for email with event cancelation. 

### Expected behaviour
Event will be updated or attendee acceptance will be shown. 

### Actual behaviour
Email (Czech language version) with information that "Invitation has been actualized", and then "Meeting 'meeting_name' with 'meeting_attendee' has been canceled. 

### Calendar app
**Calendar app version:** 2.0.4

**CalDAV-clients used:** OpenSync (Android) and iOS.

### Client configuration
**Browser:** Firefox 81.0.2 and Safari on iOS. 

**Operating system:** Kubuntu 18.04 LTS 64bit, Win10, iOS 14, Android 10 (Samsung) 

### Server configuration

**Operating system**: Ubuntu server 18.04 LTS 64bit

**Web server:** Apache 2.4.46 (Ubuntu) 

**Database:** MySQL v14.14 Distrib 5.7.31

**PHP version:** 7.4.11

**Nextcloud Version:** 19.0.4

**Updated from an older installed version or fresh install:** updated

**List of activated apps:**
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - audioplayer: 2.12.0
  - bookmarks: 3.4.3
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - checksum: 0.4.5
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_markdown: 2.3.1
  - files_mindmap: 0.0.23
  - files_pdfviewer: 1.8.0
  - files_readmemd: 1.1.4
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - keeweb: 0.6.3
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - occweb: 0.0.7
  - ocsms: 2.1.8
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - socialsharing_email: 2.1.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.4
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - encryption
  - groupfolders
  - issuetemplate
  - social
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [
            "Kamar\u00e1di"
        ],
        "htaccess.RewriteBase": "\/",
        "app_install_overwrite": [
            "calendar",
            "ocsms",
            "occweb",
            "social",
            "files_readmemd",
            "keeweb"
        ],
        "updater.release.channel": "stable"
    }
}

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by armaccloud** [comment]
This is a nasty bug.

Last evening at 11:34PM and this morning at 00:34AM  me and a client of mine with whom I have an appointment, received an "invitation canceled" email even though I did not cancel the event for my client. I did not change any details on the even either.

I noticed that event update emails aren't sent out anymore (update of location or description). Instead, this invitation canceled email at  later time (11:34 / 00:34).

How to go about troubleshooting this?

**Comment by mbreskovec** [comment]
I found one thing - I sync my Nextcloud calendar with the Samsung calendar on my mobile phone and if I manually set the Samsung calendar to accept the invite, the cancellation does not come and everything is fine.

**Comment by ChristophWurst** [comment]
> Last evening at 11:34PM and this morning at 00:34AM me and a client of mine with whom I have an appointment, received an "invitation canceled" email even though I did not cancel the event for my client. I did not change any details on the event either.

Could you check your access log for all requests sent to your Nextcloud at that time? As far as I know Nextcloud won't magically awake and do such things. It's more likely that a connected client changed some data and that cause the cancellation.

**Comment by armaccloud** [comment]
Hi @ChristophWurst ,

Thank you for your suggestion. Unfortunately, my logs were flooded by an issue with the Bookmarks app. I have tried to troubleshoot / find some information around that time but did not find any and deleted the logs to clean up space and deleted the Bookmarks app.

The issue has not occurred again so-far, but I will have to keep it in sight.

However, updates on calendar events are not sent out anymore, which seemed to have coincided with this issue. So, when I change the description or location of a calendar event to which a (external) email address is linked, there is no update mail sent out to it. I don't know whether this should be considered as a separate issue.

**Comment by balli1187** [comment]
Sorry for reopening this issue but seems i'm facing the same issue:

Calendar events are cancelled without being intended to be cancelled. As far as i noticed its only with events someone is invited to and its only canceled for the attendee (stays in my personal calendar without any changes).

I'm not sure how to provide the mentionied access log... So could anyone tell me how to do it?

Regards, Stephan
