### ISSUE TITLE
Repeat event fails on save and deletes the event

### ISSUE THREAD

**Issue by NukeManDan** [nextcloud/calendar#2657]
### Steps to reproduce
1. click a day on month view
2. set title on a new all day event
3. set reminders
4. set repeat (monthly) on day
5. click save (bottom of the card to edit the event)
6. card closes and event is not created.

Same behaviour for an *existing event* that you edit to repeat! It is *deleted*

### Expected behaviour
events repeating

### Actual behaviour
deleted events :sob:

### Calendar app
**Calendar app version:** 2.0.4

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

### Server configuration

**Operating system**: ubuntu

**Web server:** apache

**Database:** postgreslq

**Nextcloud Version:** 19.0.4

**Comment by miaulalala** [comment]
Can't reproduce
