### ISSUE TITLE
Day (1) / week (2) / month (3) shortcuts with special keys, like Alt

### ISSUE THREAD

**Issue by mmalisz** [nextcloud/calendar#2658]
I use Alt + number to navigate tabs in Firefox.

Therefore, when I try to navigate my browser tabs while the calendar is opened, I cannot do so, as it intercepts any key combination that has the hotkeys.

Related PR: #2195

### Steps to reproduce
1. Open multiple tabs.
2. Go to calendar web app.
3. Try to change the tabs with keyboard (Alt-1, Alt-2, Alt-3).

### Expected behaviour
The browser tabs should change.

### Actual behaviour
Calendar view changes between day, week, and month.

### Calendar app
**Calendar app version:** 2.0.4

### Client configuration
**Browser:** Firefox 81.0.2 (64 bit)

**Operating system:** Debian 10, 5.8.0-0.bpo.2-amd64, though the same happend on any kernel

**Comment by mmalisz** [comment]
Same happens on 2.1.2 and NC 10.0.2.

**Comment by miaulalala** [comment]
Fixed, tested both FF and Chrome
