### ISSUE TITLE
Calender not working in version 2.0.4

### ISSUE THREAD

**Issue by alexharvard** [nextcloud/calendar#2662]
### Steps to reproduce
Just using the calender app.

### Expected behaviour
Adding new calender entries.

### Actual behaviour
It's not possible to add a calender event.
When clicking "Neuer Termin" or just clicking into the calender is is showing up "von Invalid date um Invalid date bis Invalid date um Invalid date" instead of the date selected as it was in all previous versions.
![grafik](https://user-images.githubusercontent.com/66095010/96742887-ab64ea00-13c3-11eb-88c6-7e5cce8b3bf6.png)

### Calendar app
**Calendar app version:** 2.0.4

**CalDAV-clients used:** None

### Client configuration
**Browser:** Firefox 78.3.0esr, Vivaldi 3.4.2066.76

**Operating system:** Debian 10

### Server configuration

**Operating system**: Debian 10 with latest stable OS updates

**Web server:** Apache

**Database:** MariaDB 10.3.23

**PHP version:** 7.4.10

**Nextcloud Version:** 19.0.4

**Updated from an older installed version or fresh install:** Fresh install, issue since calender app update to 2.0.4

**List of activated apps:**

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - audioplayer: 2.12.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - camerarawpreviews: 0.7.8
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.1
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.1.2
  - duplicatefinder: 0.0.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - previewgenerator: 2.3.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.5
  - richdocumentscode: 4.2.800
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.4
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.5
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0

Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 1,
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "app_install_overwrite": [
            "radio"
        ],
        "theme": "",
        "loglevel": 2
    }
}

#### Browser log
No error output generated in the js console

**Comment by mlchai** [comment]
I'm seeing the same error on MacOS Catalina using Chrome. I do have some console output:
<img width="408" alt="Screen Shot 2020-10-27 at 9 56 35 AM" src="https://user-images.githubusercontent.com/58732/97335398-0b7fe400-183b-11eb-8929-5b8dc997121d.png">

**Comment by Digitale-Substanz** [comment]
I confirm having the same issue on Firefox 82.0 on Ubuntu 18.04. Possible duplicate, already described here: https://github.com/nextcloud/calendar/issues/2647

**Comment by tcitworld** [comment]
@Digitale-Substanz @mlchai @Leprazoriy 
Can you share the URL path before and after you click?

Please also post your own browser logs (just the ones added when clicking once).

**Comment by Digitale-Substanz** [comment]
URL path before I click: `/index.php/apps/calendar/dayGridMonth/now`
URL path after I click: `/index.php/apps/calendar/dayGridMonth/now/new/popover/0/1605978002/1605981602`

Console logs after clicking 'Add new' button ('Neuer Termin' in German)

```
TypeError: e.getters.sortedCalendars[0] is undefined
    createNewEvent calendarObjects.js:339
    g vuex.esm.js:847
    dispatch vuex.esm.js:512
    dispatch vuex.esm.js:402
    n calendarObjectInstance.js:1416
    l runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    EE calendar.js:2
    s calendar.js:2
    SE calendar.js:2
    SE calendar.js:2
    getCalendarObjectInstanceForNewEvent calendarObjectInstance.js:1416
    g vuex.esm.js:847
    dispatch vuex.esm.js:512
    dispatch vuex.esm.js:402
    t EditorMixin.js:654
    l runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    dg calendar.js:2
    s calendar.js:2
    Ag calendar.js:2
    Ag calendar.js:2
    t EditorMixin.js:645
    e vue-router.esm.js:2452
    confirmTransition vue-router.esm.js:2434
    confirmTransition vue-router.esm.js:2298
    confirmTransition vue-router.esm.js:2297
    VueJS 8
    init vue-router.esm.js:2919
    init vue-router.esm.js:2918
    updateRoute vue-router.esm.js:2308
    transitionTo vue-router.esm.js:2156
    confirmTransition vue-router.esm.js:2294
    r vue-router.esm.js:1895
    r vue-router.esm.js:1899
    f vue-router.esm.js:2274
    confirmTransition vue-router.esm.js:2437
    t EditorMixin.js:644
    l runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    dg calendar.js:2
    s calendar.js:2
    Ag calendar.js:2
    Ag calendar.js:2
    beforeRouteEnter EditorMixin.js:643
    confirmTransition vue-router.esm.js:2426
    f vue-router.esm.js:2252
    r vue-router.esm.js:1898
    Ee vue-router.esm.js:1906
    confirmTransition vue-router.esm.js:2404
    r vue-router.esm.js:1895
    r vue-router.esm.js:1899
    f vue-router.esm.js:2274
    Ie vue-router.esm.js:2055
    f vue-router.esm.js:2252
    r vue-router.esm.js:1898
    r vue-router.esm.js:1902
    r vue-router.esm.js:1899
    f vue-router.esm.js:2274
    beforeRouteUpdate Calendar.vue:265
    je vue-router.esm.js:2399
    f vue-router.esm.js:2252
    r vue-router.esm.js:1898
    r vue-router.esm.js:1899
    f vue-router.esm.js:2274
    <anonymous> windowTitleService.js:62
    f vue-router.esm.js:2252
    r vue-router.esm.js:1898
    Ee vue-router.esm.js:1906
    confirmTransition vue-router.esm.js:2282
    transitionTo vue-router.esm.js:2152
    push vue-router.esm.js:2519
    push vue-router.esm.js:2950
    push vue-router.esm.js:2949
    newEvent AppNavigationHeaderNewEvent.vue:70
    VueJS 3
EditorMixin.js:657:5

1
```

​

**Comment by Digitale-Substanz** [comment]
What does that mean 'no response to our request'? I did reply and share the requested data to the best of my abilities. What else would be needed to finally fix this issue?
