### ISSUE TITLE
share-icon missing

### ISSUE THREAD

**Issue by siegelfriedel** [nextcloud/calendar#2671]
Hello,

after installing nextcloud 20.0.1 via setup-nextcloud.php from the official repository on my webbspace (Strato.de, php-version 7.3, using one sql-database) I experienced missing share-icons to share the calendar read-only in the calendar-app.
Is this a known issue?
How can I fix that?

Thank you for any help

Siegfried

**Comment by tcitworld** [comment]
Disable you ad-blocker for this domain.
