### ISSUE TITLE
Missing border on current day in weekly and monthly view when using firefox

### ISSUE THREAD

**Issue by mwalbeck** [nextcloud/calendar#2679]
### Steps to reproduce
1. Open Firefox
2. Go to Nextcloud Calendar
3. Pick weekly or monthly view and see missing border on current day

The issue is not present in Chromium, specifically tested on Chromium 86.0.4240.111

### Expected behaviour
There should be a border on both left and right side of current day in weekly view and a border on all sides of current day in monthly view.

### Actual behaviour
Right border is missing from current day in weekly view, and right and bottom border is missing from current day in monthly view

### Calendar app
**Calendar app version:** 2.1.2

### Client configuration
**Browser:** Firefox 82.0

**Operating system:** Ubuntu 20.04

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Nginx

**Database:** Sqlite

**PHP version:** 7.4

**Nextcloud Version:** 20.0.1

**Updated from an older installed version or fresh install:** Updated from 20.0.0

![github-nextcloud-calendar-issue](https://user-images.githubusercontent.com/19759293/97785421-2dfc5f00-1ba5-11eb-9f0d-22b139b37301.png)

![github-nextcloud-calendar-issue-2](https://user-images.githubusercontent.com/19759293/97785442-48ced380-1ba5-11eb-93c6-685507ab5699.png)

**Comment by bryden** [comment]
The border is in fact there but it's not visible due to the background color being set 
If you right click on today, inspect element, and then edit the css in the developer console to add a z-index of -1 here:

For the monthly view:
```
.fc .fc-daygrid-day.fc-day-today {
    background-color: rgba(255, 220, 40, 0.15);
    background-color: var(--fc-today-bg-color, rgba(255, 220, 40, 0.15));
    **z-index: -1;**
}
```

And for the weekly view:
```
.fc-theme-standard td, .fc-theme-standard th {
    border: 1px solid #ddd;
    border: 1px solid var(--fc-border-color, #ddd);
    z-index: -1;
}
```

The borders will now show up properly. Unfortunately I don't have the time to submit a code commit right away but if this lingers I may pick it up eventually because it's bothering my eyes.

**Comment by spiezmaestro** [comment]
I noticed that this issue only occurs in Firefox (regardless if Breeze Dark or the default colors are active). When I logon in Chrome or Edge Chromium, all looks well. Hope this helps.

**Comment by mwalbeck** [comment]
Thanks for looking into it @bryden. I finally had some time myself to look more into it so I've put together a pull request with your findings.

**Comment by singhonscreen** [comment]
It is not working
