### ISSUE TITLE
Locale not respected in Calendar view

### ISSUE THREAD

**Issue by simonspa** [nextcloud/calendar#2681]
### Steps to reproduce
1. Set your NC language to English (US) but your Locale to German (Germany)
2. Go to the Calendar
3. Compare Month view and List view

### Expected behaviour
Locale should be observed everywhere, i.e. the way it is displayed in Settings below the Locale:

![image](https://user-images.githubusercontent.com/1677436/97960217-4b9e1400-1db1-11eb-9c66-b0ac0e4e1ab5.png)

### Actual behaviour
We have different displays in the different views
* In the "weekly" view, the locale setting seems to be ignored and the US-style date is shown ("11/03/2020" for today)
* In list view, the full German date is shown, including German month name ("3. Juli 2020")

Interestingly, the "weekly" issue seems to be resolved when switching locale to US and back to German.

### Calendar app
**Calendar app version:** 2.1.1

### Client configuration
**Browser:** Firefox 82

**Operating system:** Ubuntu 20.04

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4.11

**Nextcloud Version:** 20.0.1

**Updated from an older installed version or fresh install:** Update

**Comment by tcitworld** [comment]
Duplicate from #2663
