### ISSUE TITLE
multiple, indistinguishable matches for calendar invitees

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/calendar#2685]
### Steps to reproduce
1. Create an address book entry for a person who also has a user account on the current Nextcloud instance
2. Let that address book entry have either one or no email address
3. Go to the Calendar app
4. Create an event and invite that person

### Expected behaviour
* If the contact entry has no email address, I get one suggested invitee: the Nextcloud user
* If the contact entry has the same email address as the matching Nextcloud user name, I get one suggested invitee: the Nextcloud user
* If the contact entry has a different email address than the matching Nextcloud user name, I get two distingishable suggested invitees. Their email addresses get shown for better distinguishability (just like it works if the address book entry has multiple email addresses:

![parker_many](https://user-images.githubusercontent.com/1804221/98364385-fc661680-2030-11eb-82a6-477e14bba0cc.png)

### Actual behaviour
I get two suggested invitees which cannot be distinguished:

![parker_one](https://user-images.githubusercontent.com/1804221/98364409-0b4cc900-2031-11eb-838f-cf92dc6adbb6.png)

Especially for the case that the address book entry has no email address configured, it's dangerous to pick the wrong entry, since they would never get informed.

### System configuration:

* Nextcloud 20.0.1
* Calendar 2.1.2

## Initial evaluation

by @juliushaertl 

> Seems like calendar searches for users through the dav principals as well as the addressbooks and not merge common mail addresses.

**Comment by miaulalala** [comment]
Done - users are distinguished not just by email address but also by icon for teams and groups
