### ISSUE TITLE
Wrong single quote convertion

### ISSUE THREAD

**Issue by pulcov** [nextcloud/calendar#269]
### Steps to reproduce
1. Select French language
2. Create event and add pop-up alarm in reminders
3. Single quote is transform to `&#039;`

![image](https://cloud.githubusercontent.com/assets/16894464/21523820/c03e32da-cd11-11e6-9a97-a8c2e734992f.png)

**Comment by georgehrke** [comment]
Translation on transifex is correct

**Comment by georgehrke** [comment]
I think it's escaped twice. First by `t()` and then by angular.

**Comment by georgehrke** [comment]
fixed by #661
