### ISSUE TITLE
Cannot invite yourself on shared events

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/calendar#2690]
Because the calendar is always stating you're already invited, you cannot invite yourself on events that you don't own.
That makes it complicated if you have for example two calendars (one shared and one personal) but you are only syncing the personal to your phone, i'd like to receive the event on my own calendar.

https://github.com/nextcloud/calendar/blob/aaa064a9947748936029200e257c645853c466a7/src/components/Editor/Invitees/InviteesList.vue#L152

**Comment by raimund-schluessler** [comment]
Is this the same as #2659?

**Comment by skjnldsv** [comment]
Nice catch!
