### ISSUE TITLE
New event popover doesn't show all shared calendars

### ISSUE THREAD

**Issue by ahiiti** [nextcloud/calendar#2691]
Edit: After update to Nextcloud 20 and running `php occ maintenance:repair`, everything seems to work fine again.

 

### Steps to reproduce
Apparently, this issue only exists with already existing calendars, existing since older versions of nextcloud and calendar.
The starting point in this case is that users have a lot of calendars shared with one another, directly and via groups.

1. As the sharee, create a new event
2. In the 'New event' popover, click the calendar drop-down menu
3. The drop-down menu doesn't show all shared calendars to which the user has editing rights

### Expected behaviour
All calendars, to which the sharee has editing rights, should be available to create the event in.

### Actual behaviour
Some of the calendars, to which the sharee has editing rights, are not shown.

See this screenshot:
![image](https://user-images.githubusercontent.com/35613923/98745789-79d4b280-23b4-11eb-8384-58771feca95a.png)
For example, the calendar "Ferien" (and most others) is editable by the logged-in user. However, this calendar doesn't show up in the dialog.
When I inspect the document structure, I can see that there really aren't any other calendars in the drop-down menu than the visible ones.

### Calendar app
**Calendar app version:** 2.0.4

### Client configuration
**Browser:** Firefox 82

**Operating system:** Arch Linux, Windows

### Server configuration

**Operating system**: Debian 10

**Web server:** nginx/1.14.2

**Database:** mariadb  Ver 15.1 Distrib 10.3.23-MariaDB

**PHP version:** PHP 7.3.19-1~deb10u1

**Nextcloud Version:** 19.0.4

**Updated from an older installed version or fresh install:** Updated

**List of activated apps:**

  - accessibility: 1.5.0
  - activity: 2.12.1
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.1
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 7.1.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.5
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.5
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "(removed)"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "overwrite.cli.url": "(removed)",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "default_language": "de",
        "default_locale": "de_DE",
        "skeletondirectory": "",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```

#### Web server error log (e.g. /var/log/apache)
N/A

#### Log file (data/nextcloud.log)
N/A

#### Browser log
(no errors or related information in the log, not showing it here because it contains sensitive data)

**Comment by miaulalala** [comment]
Can't reproduce any longer.
