### ISSUE TITLE
Disable calendar event images

### ISSUE THREAD

**Issue by methbinge** [nextcloud/calendar#2697]
**Is your feature request related to a problem? Please describe.**
I don't want to see blacks in my Nextcloud event images. How do I disable the image suggestions?

**Describe the solution you'd like**
Plugin setting allowing the disabling of images.

**Describe alternatives you've considered**
Deleting the images, however they're regenerated on every update and deleting them is a chore.

**Additional context**
Blacks are in many of in the image suggestions of the Nextcloud calendar. I don't like seeing them. ![img](https://i.imgur.com/6RsfV1n.png)

**Comment by jancborchardt** [comment]
From our [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/), which is valid for all our online and offline spaces:

> **Be respectful**
> We do not tolerate personal attacks, racism, sexism or any other form of discrimination.

Hence I’ll close this issue and the associated pull request.
