### ISSUE TITLE
Color picker disappears when I want to pick a color for a calendar

### ISSUE THREAD

**Issue by drudgede** [nextcloud/calendar#2698]
### Steps to reproduce
1. Create a calendar
2. Click on the three dots next to the calendar name
3. Click on the color/edit color of the calendar and try to change it

### Expected behaviour
When clicking on the color, the color picker appears.
It should stay visible until one has picked a color

### Actual behaviour
The color picker disappears in the moment when I hover over it

![problem](https://user-images.githubusercontent.com/10487932/99099656-0bbe0480-25db-11eb-9ee1-5f8089f7087f.gif)

### Calendar app
**Calendar app version:** 2.0.4

**CalDAV-clients used:** Webfrontend

### Client configuration
**Browser:** Safari 14.0.1

**Operating system:** macOS Big Sur 11.0.1

### Server configuration

**Operating system**: Linux 4.19.0-12-amd64 x86_64

**Web server:** Apache

**Database:** MariaDB 10.3.25

**PHP version:** 7.3.24

**Nextcloud Version:** 19.0.4

**Updated from an older installed version or fresh install:** Updated

**List of activated apps:**

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - audioplayer: 2.12.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - documentserver_community: 0.1.8
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_antivirus: 3.0.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 6.1.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_gateway: 0.17.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - encryption
  - files_external
  - firstrunwizard
  - privacy
  - support
  - survey_client
  - systemtags
  - user_ldap

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE**",
            "***REMOVED SENSITIVE VALUE**"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": ***REMOVED SENSITIVE VALUE***,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": "false",
        "mysql.utf8mb4": true,
        "skeletondirectory": "",
        "updater.release.channel": "stable",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "htaccess.RewriteBase": "\/",
        "default_language": "de",
        "default_locale": "de_DE",
        "allow_user_to_change_display_name": true
    }
}
```

**Comment by miaulalala** [comment]
Can't reproduce any more.
