### ISSUE TITLE
[enhancement-proposed] Calendar shared by link with 'See only free/busy'

### ISSUE THREAD

**Issue by 6Xkljk8Vj7Tk1k4** [nextcloud/calendar#270]
Can you please add 'See only free/busy' setting in calendar share?

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
