### ISSUE TITLE
Norwegian localization shows date where hour-minute should be on appointments

### ISSUE THREAD

**Issue by OlavStornes** [nextcloud/calendar#2703]
When using my localized language (Norwegian), the time on calendar appointments does not show as expected. Other languages seems to work as intended on my system (limited testing with German, Swedish, English and Danish)

### Steps to reproduce
1. Use Norwegian ("Norsk Bokmål") as user language
2. Open/create an appointment which has a specified time (not a whole day)
3. Inspect the appointment

### Expected behaviour
Appointment should have ("til {DATE} på {HOUR-MINUTE}")

### Actual behaviour
Appointment has (til {DATE} på {DATE})

![image](https://user-images.githubusercontent.com/25202371/99248371-9fc0e380-2808-11eb-84cd-8be606d82cdb.png)

### Calendar app
**Calendar app version:** 2.1.2

**CalDAV-clients used:** Not related

### Client configuration
**Browser:** Firefox 82

**Operating system:** Windows 10

### Server configuration

**Operating system**: Docker on Synology

**Web server:** Apache

**Database:** MariaDB
**PHP version:** 7.4.12

**Nextcloud Version:** 20.0.1

**Updated from an older installed version or fresh install:**

**List of activated apps:** Assumed unrelated

**Nextcloud configuration:** Assumed unrelated

#### Web server error log (e.g. /var/log/apache)

Assumed unrelated

#### Log file (data/nextcloud.log)

Assumed unrelated

#### Browser log

Assumed unrelated

**Comment by raimund-schluessler** [comment]
That is a problem with the Transifex translation which has been fixed with https://github.com/nextcloud/calendar/commit/3d5fa71891cdcb4a025f82473bd6c24c83608e7f#diff-5f0377d850326cabf5680f65f92bbfc26d83982321030e6703ca4a91f4206590. Will be fixed with the next release.
