### ISSUE TITLE
Calendar broken in Nextcloud 20.0.2RC1 

### ISSUE THREAD

**Issue by datenleck** [nextcloud/calendar#2704]
Hi,
I've just updated to NC 20.0.2RC1 (Beta). Since then the calendar is not shown in the content page.
The headline is shown correctly.

Debian 10, Linux 5.8.0-0.bpo.2-amd64 x86_64
PHP Version: 7.4.12
Arbeitspeicher-Grenzwert: 512 MB
Maximale Ausführungszeit: 3600

**Comment by WebOscar** [comment]
Same issue here!

**Comment by datenleck** [comment]
Seems to bee solved in NC 20.0.2RC2 (Beta)  and  NC 20.0.2 (stable).

**Comment by tcitworld** [comment]
Most likely an asset cache issue. Try to force refresh the page or restart the php-fpm process.
