### ISSUE TITLE
Invitation emails not sent for shared calendar

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/calendar#2719]
### Steps to reproduce

1. Make sure you have either _sendmail_ or _SMTP_ configured on your nextcloud instance
2. Make sure you have two user account on the same Nextcloud instance - _User1_ and _User2_
3. Create a calendar as _user1_ and share this calendar with _user2_
4. Open the calendar as _user2_
5. Create an event as _user2_ and add an attendee

### Expected behaviour
A calendar invitation email is sent to the attendee.

### Actual behaviour
A calendar invitation email is not sent to the attendee

Note: When deleting the event, a cancellation email IS sent to the attendee! So the mechanism does work, just not for invitations.
Note: When creating an event as user1 (owner of the calendar), the email invitation IS sent to the attendee.

### Calendar app
**Calendar app version:** 2.1.2

### Client configuration
**Browser:** Firefox 83.0

**Operating system:** Pop_!OS 20.04

### Server configuration

Hosted at hostiso/cloudamo

**Nextcloud Version:** 20.0.2

**Updated from an older installed version or fresh install:** Updated

**Comment by tcitworld** [comment]
Duplicate from #2055, see https://github.com/nextcloud/server/pull/15676 and https://github.com/nextcloud/calendar/issues/2145 as well.
