### ISSUE TITLE
[wish] Make subscribed calendars shareable

### ISSUE THREAD

**Issue by caco3** [nextcloud/calendar#272]
NC11 has now the cool feature to subscribe to a calendar. This works great for Google calendars, thank you very much!

It would be great if I now could share those calendars with other NC members, like I can do this with my local calendars.

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
