### ISSUE TITLE
Calendar v.2.1.2 no longer syncs from Windows Calendar

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/calendar#2720]
After Updating to Calendar v.2.1.2 I can no longer synchronize events from any of my PCs with windows calendar with nextcloud calendar.

In practice, if I use a setting that has always worked as per documentation (setting icloud and then entering url for ios / mac) and creating a password for the application, inserting an event in the windows calendar is not synchronized in nextcloud. I state that the windows calendar with url ios / mac gives me account correction problem while with main caldav url I can synchronize events from nextcloud calendar to windows calendar but not vice versa.

Does anyone else have the same problem as me?

I attach photo setting with url caldav ios / mac

![Immagine](https://user-images.githubusercontent.com/35575744/100276302-9b5f9d80-2f61-11eb-8e58-90cc91db17f1.png)

![Immagine2](https://user-images.githubusercontent.com/35575744/100276320-a0245180-2f61-11eb-8410-98b282b453ee.png)

**Comment by tigernero79** [comment]
I want to clarify that if I put an event in nextcloud calendar I find it synchronized on the windows calendar, but the reverse does not work if I insert an event on the windows calendar I do not find it synchronized in nextcloud. in fact windows calendar always reports account problem but the procedure used is the one that has always worked. as if sending events doesn't work from win calendar to nextcloud calendar

**Comment by tigernero79** [comment]
i think with icloud option in windows calendar it tries to log in with username equal to email data not with actual username

[core] Warning: Login failed: 'nero79@icloud.com' (Remote IP: '192.168.6.1')

PROPFIND /remote.php/dav
from 192.168.6.1 at 2020-11-25T20:21:25+00:00

**Comment by tigernero79** [comment]
from what I can understand nextcloud calendar even if I feed it url ios / imac takes into account as username email fictitious date when creating account on windows calendare does not consider the nick nextcloud user how to solve?

**Comment by tigernero79** [comment]
I understood that by creating accound apple icloud in windows calendar it synchronizes the events of calendar nextcloud but when it is he who has to enter the events (I'm talking about windows calendar) he sends as username icloud email not the nick that is inserted in the ios url / mac looks at what I give as a nick in the settings and goes into error.

How do we solve?

**Comment by tcitworld** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH they offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise

--

The Nextcloud Calendar app is just a CalDAV client just like Windows Calendar, updating the app is not related to your issue. Anyway using the iCloud account feature to get for CalDAV support was never going to work long term, that's an issue with the Windows Calendar app.
