### ISSUE TITLE
Unneccesarry scrollbar

### ISSUE THREAD

**Issue by sinus-x** [nextcloud/calendar#2721]
### Steps to reproduce
1. Open the web calendar

### Expected behaviour
No scrollbars are visible.

### Actual behaviour
Both bottom and right scrollbars are visible, while having no effect -- the calendar box itself has one (see the screenshot).

### Configuration
**Calendar app version:** 2.0.4
**Nextcloud Version:** 18.0.4
**Browser:** Firefox 83

### Fix
Add `overflow-x: hidden` to the body class.

### Screenshots
The screenshot shows **before** and **after** the fix. It has a dark theme, but the issue remains even if i turned that off.
![calendar](https://user-images.githubusercontent.com/14353790/100355277-c1cd1980-2ff1-11eb-95ad-34d9b48a7826.jpg)

**Comment by tcitworld** [comment]
Thx, should have been fixed by https://github.com/nextcloud/calendar/pull/1809 in [2.1.0](https://github.com/nextcloud/calendar/releases/tag/v2.1.0).
