### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by gcclinux** [nextcloud/calendar#2724]
I would like to get email notification from the calendar on the day of the event.

**Is your feature request related to a problem? Please describe.**
No this is a feature enhancement request.

**Describe the solution you'd like**
Simple email to specific address when notification is due.

**Describe alternatives you've considered**
Currently using my own calendar I created and maintain.

**Additional context**
Not much to describe, simply like to receive emails when notification is due.

**Comment by tcitworld** [comment]
You need to activate sending mail notifications for events in the Admin Groupware settings.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH they offer this as part of the Nextcloud subscription. Learn more about this at nextcloud.com/enterprise
