### ISSUE TITLE
Share to user searching aproximate name/email

### ISSUE THREAD

**Issue by Thatoo** [nextcloud/calendar#2727]
### Steps to reproduce
1. I want to share a calendar to the user "Guégan Sophie"
2. I click on the share button
3. I start typing sophi
4. it doesn't show me the option to share to Guégan Sophie
5. I start typing Gueg
6. still no choice
7. Only if I type proper Guégan Sophie or at least Guég (with the accent!), it shows me the option to share my calendar to her
### Expected behaviour

As it is the case when I want to share a folder or when I look for a contact, if I start typing either soph, Soph, Guég, Gueg, guég ou gueg, it should offer me the option to select the user Guégan Sophie in order to share the calendar to her.
### Actual behaviour

If I don't start spelling exactly the name, it doesn't offer me any choice
### Calendar app

2.1.2
### Client configuration

**Browser:** (e.g. Firefox 48)
Firefox 78

**Operating system:** (e.g. Arch Linux)
Linux Mint 20, Ubuntu 20.04, Debian 10
### Server configuration

**Operating system**: (e.g. Debian 8)
Debian 10

**Web server:** (e.g. Apache, Nginx,...)
Nginx

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0.3)
7.3.x

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
20.0.2

**Updated from an older installed version or fresh install:**
Updated from 19.0.5

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.3
  - admin_audit: 1.10.0
  - appointments: 1.7.14
  - apporder: 0.11.0
  - auto_mail_accounts: 0.1.7
  - bbb: 1.1.2
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  - deck: 1.2.2
  - documentserver_community: 0.1.8
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.0.4
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.7.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.1
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - polls: 1.6.2
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.10
  - riotchat: 0.6.16
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - files_external
  - onlyoffice
  - spreed

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "URLOFOURCLOUD",
            "localhost",
            "192.168.1.251"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.2.2",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "overwrite.cli.url": "URLOFOURCLOUD",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwriteprotocol": "https",
        "onlyoffice": {
            "verify_peer_off": true
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "auto_mail_accounts": {
            "imap_host": "ssl0.ovh.net",
            "imap_port": "993",
            "imap_ssl_mode": "tls",
            "smtp_host": "ssl0.ovh.net",
            "smtp_port": "465",
            "smtp_ssl_mode": "tls",
            "email_address_suffix": ""
        }
    }
}
### Logs
#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```
#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by tcitworld** [comment]
Make sure the following option is checked in the admin share settings:
![image](https://user-images.githubusercontent.com/2197836/100984530-2258db00-354b-11eb-9c60-a0c70d72187c.png)

**Comment by Thatoo** [comment]
Indeed, this is checked. Otherwise, it would not work on when I share a folder or when I look for a contact.

**Comment by tcitworld** [comment]
Did you reproduce the issue with other usernames? The accent may be causing the issue somehow.

**Comment by Thatoo** [comment]
Yes, I did.
Again, it works fine for username with or without accent when we want to share files of when we are looking for contacts.
However, when we want to share a calendar, we should start writing exactly how the username starts (Uppercase and accent included). A username without accent face the same problem. I can't try with a username without uppercase as I don't have any.

**Comment by pierreozoux** [comment]
This is strange, I can't reproduce this issue on my side.

This is now old, @Thatoo can you still reproduce the issue, or did you find a workaround?

**Comment by Thatoo** [comment]
Very old, indeed, we just didn't share calendar to that person at that time.
Today, I don't have access to this nextcloud anymore to check how it is now.

**Comment by Thatoo** [comment]
Well, @pierreozoux , I tried and I guess the issue is that if the name has an accent such as Frédérique and one type Fred without the é but only a e, then nextcloud is not suggesting Frédérique whereas I would expect nextcloud to do so.

**Comment by joshtrichards** [comment]
I'm unable to reproduce this problem. I created an account named "sophie" with a display name of "Guégan Sophie". Searching /sharing works fine.

There are multiple spots where I could see this having been fixed over the years. Is anyone still able to reproduce this problem today?

**Comment by SebastianKrupinski** [comment]
Closing this as its no longer reproducible

<img width="638" height="528" alt="Image" src="https://github.com/user-attachments/assets/6af118b6-370f-45bd-84b8-2dd272aa1517" />
