### ISSUE TITLE
self-shared WebDAV link (ics) can not be subscribed in calendar

### ISSUE THREAD

**Issue by caco3** [nextcloud/calendar#273]
One of my PC clients (Outlook) periodically exports its calendar through WebDAV to my NC11. (This is the only way, so please do not suggest better ways).
I then share the ics file as a link (https:/***.ch/index.php/s/***)and try to subscribe it in the calendar.
How ever I get the following error (blue bar on top):
> Severe error in webcal proxy. Please contact administrator for more information.

There is no other error in the NC log!

### Steps to reproduce
1. Have an ics file in your NC installation
2. Share it through a link
3. Subscribe to this link in the NC calendar

### Expected behaviour
Subscription should work

### Actual behaviour
Severe error, see above

### Server configuration
**Operating system**:
FreeBSD
**Web server:**
Appache
**Database:**
Type: mysql
Version: 5.5.53
Size: 51.9 MB
**PHP version:**
Version: 5.6.29
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 511.0 MB
**Server version:** (see your admin page)
11.0.0 (daily, 30.12.2016)
**Calendar version:** (see the apps page)
1.4.1
**Updated from an older installed version or fresh install:**
fresh install, migrated DB
**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - files_automatedtagging
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
{
    "system": {
        "datadirectory": "\/home\/***\/owncloud_***",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "installedat": "1334086349.5631",
        "lastupdatedat": "1334087083.9888",
        "dbname": "***_owncloud",
        "dbhost": "***.mysql.db.internal",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "5083050d6af67",
        "maxZipInputSize": 419430400,
        "allowZipDownload": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 3,
        "trusted_domains": [
            "owncloud.***.ch",
            "www.***.ch",
            "***.ch"
        ],
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "***.ch",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, auto",
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by georgehrke** [comment]
please try copy and pasting the actual download link.
It should have a `?download` at the end.

**Comment by caco3** [comment]
I did not use the download link, but the share link (see OP)!

I just tested it with another publicly available calendar: http://www.derkalender.at/ics/derkalender_at_2017_v1b.ics (http://www.derkalender.at/ics_download)

Same result!

A download link would not work because it is password protected! (You get a 401 error)

**Comment by georgehrke** [comment]
> I did not use the download link, but the share link (see OP)!

please try the download link

**Comment by caco3** [comment]
@georgehrke Then I obviously get an 401 error:
> Der entfernte Server erlaubt keinen Zugriff auf den Kalender (HTTP {401} error)
Link: https://owncloud.***.ch/index.php/apps/files?dir=/&fileid=9322#

And with the share link  https://owncloud.***.ch/index.php/s/xxqcKXuCvJ2rurE I get: 
> Schwerer Fehler im webcal-Proxy. Bitte kontaktiere Deinen Administrator für weitere Informationen.

If I put the calendar into my web-root ( https://www.***.ch/derkalender_at_2017_v1b.ics), then it works.

So that means that we can't share such calendars from within Nextcloud...
That would be ok for me, how ever how should one figure this out?

**Comment by georgehrke** [comment]
no, please try `https://owncloud.***.ch/index.php/s/xxqcKXuCvJ2rurE?download`

**Comment by caco3** [comment]
@georgehrke Indeed, that seems to work. Note that the correct URL is
 `https://owncloud.***.ch/index.php/s/xxqcKXuCvJ2rurE/download`
(Slash instead of a question mark).

Now I will only have to check if the calendar also gets refreshed.

**Comment by georgehrke** [comment]
> Now I will only have to check if the calendar also gets refreshed.

It's cached for a certain time in  your browser, but its not long.

There is also an issue for adding auto discovery for these kind of links :)
https://github.com/nextcloud/calendar/issues/286

**Comment by rasos** [comment]
Subscribing a foreign ics calendar is still not possible and throws a webcal Proxy error. This issue should be re-opened. Adding /download to owncloud ics files is not a solution for other calendars, such as the example above https://github.com/nextcloud/calendar/issues/273#issuecomment-269863737 or when subscribing a calendar from GroupOffice - it shows the same webcal proxy error, even if the ics calendar is accessible without authorization.

Tested on nextcloud 11.0.4 with Calendar App 1.5.4

**Comment by tcitworld** [comment]
@rasos You should check the browser console for eventual logs, but it could just be a CORS issue with the remote server. Not much we can do here apart from https://github.com/nextcloud/server/issues/1497
