### ISSUE TITLE
Clickable links or URLs in Calendar fields (important for online meetings)

### ISSUE THREAD

**Issue by Jackalaq** [nextcloud/calendar#2730]
We are considering moving from TeamUp to NextCloud Calendar but after importing via CalDAV, we discovered that URLs and other links are not clickable.  This is used for details of online meetings.  I tried editing an event and typing new links into the description but that didn't work either, so isn't just an issue with importing plaintext.

**Comment by tcitworld** [comment]
Links are clickable when they are not editable (read-only share or publication): https://github.com/nextcloud/calendar/pull/2274 We can't make them clickable when you are editing them.

About links for conference details: https://github.com/nextcloud/calendar/issues/1758
