### ISSUE TITLE
The date view cannot be displayed properly after calendar download is enabled

### ISSUE THREAD

**Issue by rosker-jance** [nextcloud/calendar#2732]
Underlying environment:
centos7
PHP+NGINX
Software installation and deployment
The details are shown in the figure below
![日历](https://user-images.githubusercontent.com/75649738/101423620-79d4bd80-3934-11eb-8c8d-ff3c5982c80c.png)

**Comment by rosker-jance** [comment]
May I ask where I set it or what is missing?

**Comment by miaulalala** [comment]
can't reproduce. Did you download the app from the app store or from github?
