### ISSUE TITLE
Can't actualize entries

### ISSUE THREAD

**Issue by papagedhe** [nextcloud/calendar#2735]
Hello,
in my nextcloud instance (nextcloud 20 on raspberry pi 4) i can't update any entry in my calendar from within the nextcloud frontend in my browser.
I can update entries from my calendar-app on my smartphone or from outlook (sync-plugin).

Is this a known issue?

Kind regards,
David

**Comment by papagedhe** [comment]
I could solve the problem by deactivating modsecurity!

**Comment by tcitworld** [comment]
You can use the [community chat](https://help.nextcloud.com/) to discuss deployment issues.
