### ISSUE TITLE
add option to set an individual birthday calendar color

### ISSUE THREAD

**Issue by j-ed** [nextcloud/calendar#274]
## Expected behavior
It should be possible to set an individual color for the birthday calendar, because automatically assigned colors might not be the right choice. In my example it is difficult to see the light yellow on a white background. (keep in mind that there are many users who might not be able to differentiate light colors )

## Current behavior
It isn't possible to edit the birthday calendar color at all.
![20170103_nc_birthday_calendar_color](https://cloud.githubusercontent.com/assets/2572764/21608445/d009f53c-d1bc-11e6-99bc-f83fda021e20.png)

### Steps to reproduce
1. Open the Calendar app and check our the color of the birthday calendar.

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 10.0.2
Calendar app: 1.4.1

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
