### ISSUE TITLE
fix nightly builds

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#275]
the nightly builds are broken for a while, because there are dns issues with upload.portknox.de

please take a look @Gomez

**Comment by Gomez** [comment]
Oh, i missed a dns entry. Done. Lets close the issue if it is working tomorrow.

**Comment by georgehrke** [comment]
thank you :)

**Comment by georgehrke** [comment]
nightly build worked last night :) 

Thx a lot!
