### ISSUE TITLE
Share Nextcloud calender via Webcal

### ISSUE THREAD

**Issue by sushidave** [nextcloud/calendar#276]
Proposal: Add an option to share and subscribe to a Nextcloud calendar via Webcal - file format: .ics.

See forum post [Subscribing to a Nextcloud calendar via Webcal?](https://help.nextcloud.com/t/subscribing-to-a-nextcloud-calendar-via-webcal/6865)

**Comment by georgehrke** [comment]
please upgrade to Nextcloud 11 :) 
It's possible already

**Comment by georgehrke** [comment]
There is an issue to streamline that experience :)

https://github.com/nextcloud/calendar/issues/243

**Comment by sushidave** [comment]
Thanks, and good to know there's something in the pipeline.

May I ask you another question related to this?

The link provided unter WebDAV looks something like this:
https://cloud.domain.tld/remote.php/dav/public-calendars/XB3I2CBWF9XSL5EM?export

How can a subscriber get the URL ending in ".ics", for example if he needs it to subscribe to the calendar on iOS: Settings > Calendar > Accounts > add a calendar > Others > subscribe to a calendar > Server: example.com/cal.ics ?

**Comment by tcitworld** [comment]
iOS requires the URL to end with `.ics`?

**Comment by sushidave** [comment]
No, it works with the URL ending in ?export. My mind just sticked to old habits ;) Problem solved, thanks!

**Comment by jancborchardt** [comment]
@georgehrke so as a quick fix the »WebDAV« wording should be corrected to »Webcal, right? Or did you do that already?
