### ISSUE TITLE
color picker always jumps to slightly different color

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/calendar#2776]
### Steps to reproduce
1. create event, change color
2. click on three dots to open color picker with big range of colors
3. click to pick a color

### Expected behaviour
Click the color, get the color.
Or: Display only colors that are selectable, in a grid view (that would also help when you want to click the same color for multiple events)

### Actual behaviour
After selection, the circle (selected color) moves to the side. You never get the color you actually clicked, but a slightly different one.

### Calendar app
**Calendar app version:**  2.1.3

### Client configuration
**Browser:** Firefox 84.0

**Operating system:** Linux Mint

### Server configuration

**Nextcloud Version:** 20.0.4

If you need more info please tell me.

**Comment by tcitworld** [comment]
That's because the `COLOR` field [only supports CSS3 names](https://tools.ietf.org/html/rfc7986#section-5.9), and we try to match to the closest color available.
See details in https://github.com/nextcloud/calendar/issues/71
