### ISSUE TITLE
Show tasks with DUE date in calendar [$380]

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#28]
- [ ] per-user config option to enable this feature
- [ ] only available when tasks app is enabled
- [ ] tasks have a checkbox in front of them, clicking this checkbox will mark the task as done.
- [ ] clicking the task itself should take the user to the task app
  - [ ] when going back to the calendar: get back to the same time-range?
- [ ] if task was not solved on dedicated day, it keeps showing on today till you finish it

**Comment by doitux** [comment]
This is currently the last point i miss compared to google calendar. Please add this!

**Comment by bensoille** [comment]
Hi !
Wow, planned feature... Oooops, would be in 2038...

Tasks plugin is quite useless, then... Alas...
What a pity ! Assigning task to an user and viewing task in calendar is mandatory imho. Tasks plugin remains completely useless without these (minimal) features

Big thanks for the good work though

**Comment by georgehrke** [comment]
> Wow, planned feature... Oooops, would be in 2038... 

`Maybe some day` is just a placeholder, because this was not assigned to any milestone yet, but we definitely want this feature in the future.
If you don't get why 2038 read https://en.wikipedia.org/wiki/Year_2038_problem ;)

**Comment by bensoille** [comment]
> but we definitely want this feature in the future
How glad to read this !! Maybe I can help ? I'll try to have a look into code and make a PR asap, if only you want me to.
(if only i get enough time one day)

**Comment by unclev** [comment]
I would also suggest an option for treating tasks as events. As events are saved when Downloading calendar or Exporting event, but from the suggested implementation - tasks aren't.

**Comment by georgehrke** [comment]
That's not entirely true. Tasks ARE exported when you export a calendar.

**Comment by unclev** [comment]
I concur. The only concern - this may be not suitable for everyone.

**Comment by raimund-schluessler** [comment]
> I would also suggest an option for treating tasks as events. As events are saved when Downloading calendar or Exporting event, but from the suggested implementation - tasks aren't.

We could add an option to the Tasks app to download/export a single task, see https://github.com/nextcloud/tasks/issues/103

**Comment by returntrip** [comment]
This is quite an important feature if you want to get away from Google Keep (Keep displays tasks with a due date in the Calendar app)

**Comment by georgehrke** [comment]
Please don't comment with +1, 👍 etc. when you can't add anything new. It's only spamming contributors' mail inboxes for no reason.  Use [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead. THX! :)

**Comment by ashgoodman** [comment]
What bounty size would get immediate action on this?

**Comment by MisterY** [comment]
@unclev, Tasks are part of the Calendar data and, as @georgehrke pointed out, are exported with the rest. The result is that external calendar apps use and display tasks along with other calendar events (i.e. free aCalendar app for Android).
The request here is for **displaying** Tasks (and allowing their manipulation, i.e drag & drop, un/check, edit) in the web interface of NextCloud's Calendar.

**Comment by szaimen** [comment]
Any update on this?

**Comment by georgehrke** [comment]
>  clicking the task itself should take the user to the task app

@raimund-schluessler Does the task app offer a route so the calendar app can directly point to a task?

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler Does the task app offer a route so the calendar app can directly point to a task?

Yes, the app offers a route, see https://github.com/nextcloud/tasks/blob/master/src/components/TheRouter.js#L40:
```
'/calendars/:calendarId/tasks/:taskId'
```
where `:calendarId` is `calendar.url.split('/').slice(-2, -1)[0]` and `:taskId` is the task uri, e.g.:
```
nextcloud/index.php/apps/tasks/#/calendars/working/tasks/855F126C-D1F5-464A-BB9D-12878F7DB369.ics
```

**Comment by jakobroehrl** [comment]
Is it possible to change the due date by moving the task entry in the calender?

**Comment by bfritscher** [comment]
I started looking into how difficult it is to implement this, to start learning the codebase a first basic version is on PR #1798

![image](https://user-images.githubusercontent.com/338973/72225109-db07db80-3581-11ea-982d-d2669dea9526.png)

**Comment by SuperSandro2000** [comment]
I just added $10 on bountysource.

**Comment by zerknorscht** [comment]
Added $5
