### ISSUE TITLE
Share subscribed calendars through CalDAV

### ISSUE THREAD

**Issue by marmeladema** [nextcloud/calendar#281]
Hi all!

Would it be possible to share subscribed calendar through CalDAV as read-only calendars ?
My use case is that i have some friends sharing their google calendar with me and i don't want to rely on anotherr app on every devices and subscribe to all their ics calendars on all my devices.

Thanks for you answers !

P.S: maybe i should have here ask https://github.com/nextcloud/server/issues ?

**Comment by georgehrke** [comment]
There is a server issue already.
let me look for the id.

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/1600

**Comment by marmeladema** [comment]
Sorry i did not found it by myself !
