### ISSUE TITLE
Fail for CalDAV sync with added Email adresses in Calendar entry

### ISSUE THREAD

**Issue by weinic** [nextcloud/calendar#2812]
I have the following Errors when i added Email Adresses to the Calendar Entry in the "required participants" field.

Error 1

[PHP] Error: Error: Undefined offset: 1 at /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Mail/Message.php#83 at <<closure>>

 0. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Mail/Message.php line 83
    OC\Log\ErrorHandler::onError(8, "Undefined offset: 1", "/srv/dev-disk-b ... p", 83, {addresses: {nex ... "})
 1. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Mail/Message.php line 149
    OC\Mail\Message->convertAddresses({nextcloud%20adm ... "})
 2. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php line 257
    OC\Mail\Message->setTo({nextcloud%20adm ... "})
 3. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\CalDAV\Schedule\IMipPlugin->schedule(Sabre\VObject\IT ... e})
 4. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 361
    Sabre\DAV\Server->emit("schedule", [Sabre\VObject\I ... }])
 5. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 644
    Sabre\CalDAV\Schedule\Plugin->deliver(Sabre\VObject\IT ... e})
 6. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 346
    Sabre\CalDAV\Schedule\Plugin->processICalendarChange(Sabre\VObject\Co ... l}, Sabre\VObject\Co ... l}, ["mailto:christo ... "], [], true)
 7. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/lib/CalDAV/Schedule/Plugin.php line 149
    Sabre\CalDAV\Schedule\Plugin->calendarObjectChange(Sabre\HTTP\Request {}, Sabre\HTTP\Response {}, Sabre\VObject\Co ... l}, "calendars/admin/weinbauer-kalender", true, false)
 8. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\CalDAV\Schedule\Plugin->calendarObjectChange(Sabre\HTTP\Request {}, Sabre\HTTP\Response {}, Sabre\VObject\Co ... l}, "calendars/admin/weinbauer-kalender", true, false)
 9. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php line 909
    Sabre\DAV\Server->emit("calendarObjectChange", [Sabre\HTTP\Requ ... e])
10. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php line 750
    Sabre\CalDAV\Plugin->validateICalendar("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", false, Sabre\HTTP\Request {}, Sabre\HTTP\Response {}, false)
11. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\CalDAV\Plugin->beforeWriteContent("*** sensitive parameter replaced ***", OCA\DAV\CalDAV\CalendarObject {}, "*** sensitive parameter replaced ***", false)
12. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1139
    Sabre\DAV\Server->emit("beforeWriteContent", ["*** sensitive  ... e])
13. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 515
    Sabre\DAV\Server->updateFile("*** sensitive parameters replaced ***")
14. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
15. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:PUT", [Sabre\HTTP\Requ ... }])
16. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
17. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
18. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/lib/Server.php line 320
    Sabre\DAV\Server->exec()
19. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
20. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/remote.php line 167
    require_once("/srv/dev-disk-b ... p")

PUT /remote.php/dav/calendars/admin/weinbauer-kalender/661cfa0b-41e1-4b28-8edf-7416bc7f8faa.ics
from 109.41.192.177 by admin at 2021-01-12T11:44:10+01:00

**Comment by weinic** [comment]
Error 2

[webdav] Fatal: TypeError: idn_to_ascii() expects parameter 1 to be string, null given at <<closure>>

 0. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Mail/Message.php line 84
    idn_to_ascii("*** sensitive parameter replaced ***", 0, 1)
 1. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Mail/Message.php line 149
    OC\Mail\Message->convertAddresses({nextcloud%20adm ... "})
 2. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php line 257
    OC\Mail\Message->setTo({nextcloud%20adm ... "})
 3. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\CalDAV\Schedule\IMipPlugin->schedule(Sabre\VObject\IT ... e})
 4. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 361
    Sabre\DAV\Server->emit("schedule", [Sabre\VObject\I ... }])
 5. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 644
    Sabre\CalDAV\Schedule\Plugin->deliver(Sabre\VObject\IT ... e})
 6. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 346
    Sabre\CalDAV\Schedule\Plugin->processICalendarChange(Sabre\VObject\Co ... l}, Sabre\VObject\Co ... l}, ["mailto:christo ... "], [], true)
 7. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/lib/CalDAV/Schedule/Plugin.php line 149
    Sabre\CalDAV\Schedule\Plugin->calendarObjectChange(Sabre\HTTP\Request {}, Sabre\HTTP\Response {}, Sabre\VObject\Co ... l}, "calendars/admin/weinbauer-kalender", true, false)
 8. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\CalDAV\Schedule\Plugin->calendarObjectChange(Sabre\HTTP\Request {}, Sabre\HTTP\Response {}, Sabre\VObject\Co ... l}, "calendars/admin/weinbauer-kalender", true, false)
 9. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php line 909
    Sabre\DAV\Server->emit("calendarObjectChange", [Sabre\HTTP\Requ ... e])
10. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php line 750
    Sabre\CalDAV\Plugin->validateICalendar("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", false, Sabre\HTTP\Request {}, Sabre\HTTP\Response {}, false)
11. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\CalDAV\Plugin->beforeWriteContent("*** sensitive parameter replaced ***", OCA\DAV\CalDAV\CalendarObject {}, "*** sensitive parameter replaced ***", false)
12. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1139
    Sabre\DAV\Server->emit("beforeWriteContent", ["*** sensitive  ... e])
13. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 515
    Sabre\DAV\Server->updateFile("*** sensitive parameters replaced ***")
14. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
15. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:PUT", [Sabre\HTTP\Requ ... }])
16. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
17. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
18. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/lib/Server.php line 320
    Sabre\DAV\Server->exec()
19. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
20. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/remote.php line 167
    require_once("/srv/dev-disk-b ... p")

PUT /remote.php/dav/calendars/admin/weinbauer-kalender/661cfa0b-41e1-4b28-8edf-7416bc7f8faa.ics
from 109.41.192.177 by admin at 2021-01-12T11:44:10+01:00

**Comment by tcitworld** [comment]
Please fill the __entire__ [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md). It will be far easier to us to fix the issue if we have all the information.
