### ISSUE TITLE
Adding Calendar Event with "Location" Fails on NC20

### ISSUE THREAD

**Issue by bcampano** [nextcloud/calendar#2814]
On a brand new NC20 installation, when creating an event in Calendar we cannot include anything in the Location field otherwise we get a spinning indicator indefinitely. This happens when using the NC web interface. When using a CalDAV client, we get a generic “The server responded with an error.” message and the new event is not added to the calendar. Everything seems to work fine when creating an event as long as no Location information is entered.

We have been using NC 18 and 19 and just recently upgraded our production system to NC20 which also introduced this Location issue. We tried a virgin install of NC20 and the problem exists there as well. We are now stuck without any users being able to include Location information in their calendar events which is common practice to include addresses, conference call credentials, etc.

### Steps to reproduce
1. Navigate to Calendar
2. Click to create a new event
3. Enter text in the event description field along with some text in the Location field
4. Click on Save

### Expected behaviour
Event should be added to the calendar with Location information intact.

### Actual behaviour
Window gets stuck with circular waiting icon and never loads. Web page needs to be refreshed and the new event is never added to the calendar. NO ERROR MESSAGES in the LOG.

### Calendar app
V2.1.3

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
DAVdriod 2.0.5

### Client configuration
Safari 14.0.2
Chrome 87.0.4280.141

**Operating system:** (e.g. Arch Linux)
OSX Big Sur (Client)

### Server configuration

**Operating system**:
VPS Generic Linux
**Web server:** (e.g. Apache, Nginx,...)
Apache 2.4.46
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
10.3.27-MariaDB-log-cll-lve
**PHP version:** (e.g. 7.0.3)
7.2.33
**Nextcloud Version:** (see admin page, e.g. 17.0.2)
20.0.4
**Updated from an older installed version or fresh install:**
Both upgrade from V19.X and Fresh Install During testing
**List of activated apps:**
Basic set installed by default during installation of V20

**Comment by bcampano** [comment]
Can anyone help? In fact, we've gone back to NC19 and NC18 and are observing the same issue! We are going to need to move away from NC unless we can find a solution soon. It might be related to MariaDB so if anyone can help advise where event location data is stored in the DB we can see if there are some simple DB tweaks possible. Unfortunately it doesn't seem NC logs errors when we run into this issue and its 100% reproducible 100% of the time!

**Comment by miaulalala** [comment]
Works now
