### ISSUE TITLE
Error updating event participation when event creator uses mail address containing a plus (+)

### ISSUE THREAD

**Issue by nocin** [nextcloud/calendar#2817]
### Steps to reproduce
1. Create user with a mail address like: user+something@example.com
2. Create event and invite guests
3. Try to accept the invitation. It returns: "There was an error update your attendance status."

### Expected behaviour
Guest should be able to accept the invitation he got via mail.

### Actual behaviour
An error Page is shown with the following message:
"There was an error updating your attendance status.
Please contact the organizer directly.
user%2bsomething@example.com"

The plus sign "+" is converted to "%2".

### Calendar app
**Calendar app version:** 2.1.3

**CalDAV-clients used:** Event creation via Firefox v84.0.2 and also via Thunderbird 68.10.0 with TbSync Add-On on Linux Mint 20.

### Client configuration
**Browser:** Updating event participation via Chrome v79 

**Operating system:** MacOS Sierra 10.12.6

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** 	mysql 10.5.8

**PHP version:** 7.4.13

**Nextcloud Version:** 20.04

**Updated from an older installed version or fresh install:** Running the offical Nextcloud Docker Container with Docker-Compose.

**Comment by ImaCrea** [comment]
same here

**Comment by pierreozoux** [comment]
I don't think this is the + the issue. Maybe just a coincidence?

But with an external user email (not an email of a registered account), it just fails.

These is this bug on the server as well:
https://github.com/nextcloud/server/issues/21715

@nocin could you try with an email without +?

**Comment by nocin** [comment]
> @nocin could you try with an email without +?

That was exactly my solution back then. Changed my mail address from _user+something@example.com_ to _user@example.com_ and everything was fine. 

Just had a look at your mentioned issue 21715. Seems like it's the same error message, unfortunately they didn't inserted their used mail addresses. The screenshot posted has a blurred mail address, but it doesn't looks like it has a + in it.
Because in my case the solution was removing the +, I would think it's a different issue.

**Comment by pierreozoux** [comment]
I just tried with my gmail address, without plus and I had the error.

**Comment by quentinDupont** [comment]
> I just tried with my gmail address, without plus and I had the error.

I also have the same issue here, with adress without +.

In french the error message is "Une erreur s'est produite lors de la mise à jour de votre statut de présence.
Merci de contacter l'organisateur directement. <mail de l'organisateur·rice>"

**Comment by szaimen** [comment]
Lets track this in #15814
