### ISSUE TITLE
update breaks calendar 

### ISSUE THREAD

**Issue by hannob** [nextcloud/calendar#282]
### Steps to reproduce
1.Got a notification that there's an update for the calendar app
2.calendar no longer works, see attachment

### Expected behaviour
Calendar should work

### Actual behaviour
calendar shows garbage

### Server configuration
**Operating system**: Gentoolinux

**Web server:** apache

**Database:** mysql

**PHP version:** 7.0.14

**Server version:** 10.0.1

**Calendar version:** [doesn't show up for unclear reasons]

**Updated from an older installed version or fresh install:** updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.1
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_texteditor: 2.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - files_sharing
  - files_trashbin
  - gallery
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**

<?php
$CONFIG = array (
  'datadirectory' => '/home/hanno/websites/own.hboeck.de/data',
  'dbtype' => 'sqlite3',
  'instanceid' => 
  'passwordsalt' => 
  'version' => '9.1.1.5',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'defaultapp' => 'calendar',
  'trusted_domains' => 
  array (
    0 => 'own.hboeck.de',
  ),
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 
  'mail_smtppassword' => 
  'loglevel' => '0',
  'secret' => 
  'htaccess.RewriteBase' => '/',
  'appstore.experimental.enabled' => true,
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium

**Operating system:** Linux

**CalDAV-clients:** no

![nextcloud-calendar](https://cloud.githubusercontent.com/assets/990588/21765236/d7ebcdde-d667-11e6-9af3-1c4195580ecb.png)

**Comment by georgehrke** [comment]
please provide logs

**Comment by georgehrke** [comment]
(especially the web browser log)

**Comment by hannob** [comment]
The javscript log:
```
JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://own.hboeck.de/core/vendor/jquery/dist/jquery.min.map
```

Server log:
```
0.0.0.0 - - [09/Jan/2017:12:59:00 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1015 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
0.0.0.0 - - [09/Jan/2017:12:59:09 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1015 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
0.0.0.0 - - [09/Jan/2017:12:59:10 +0100] "GET /apps/calendar/ HTTP/1.1" 200 9620 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
0.0.0.0 - - [09/Jan/2017:12:59:10 +0100] "GET /core/js/oc.js?v=e1f45c7fec08de3315244263e5b4a93e HTTP/1.1" 200 1104 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
0.0.0.0 - - [09/Jan/2017:12:59:11 +0100] "GET /core/vendor/jquery/dist/jquery.min.map HTTP/1.1" 302 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
0.0.0.0 - - [09/Jan/2017:12:59:11 +0100] "GET /apps/calendar/ HTTP/1.1" 200 9613 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
0.0.0.0 - - [09/Jan/2017:12:59:11 +0100] "GET /cron.php HTTP/1.1" 200 20 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
0.0.0.0 - - [09/Jan/2017:12:59:11 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1015 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"

```

I'm actually not sure how to export the browser network log in a way that I can paste it... Can you point me to an instruction on how to do that?

**Comment by georgehrke** [comment]
Ah, I just saw the screenshot you attached. Can you please check if the sharing API and the file sharing app are enabled. There was a regression related to that in version 1.4.1. Will be fixed with the next update

**Comment by hannob** [comment]
The sharing api was enabled, but disabling it doesn't change anythin. I don't have the File Sharing app enabled.

Is there any quick fix (or downgrade instruction) I can apply so I can get access to my calendar back?

**Comment by georgehrke** [comment]
> The sharing api was enabled, but disabling it doesn't change anythin. I don't have the File Sharing app enabled.

Then try to enable both please :)

**Comment by hannob** [comment]
Enabling the File Sharing app and the sharing API did fix it, however not without another problem along the way:
* After enabling the file sharing app it told me that it needs to be updated.
* Yet the update didn't work, it always showed "an error occured" and made my installation unusable
* Doing the update over the commandline worked.

(This is more of a comment, but all this shows me that unfortunately it seems nextcloud still hasn't figured out working updates.)

**Comment by georgehrke** [comment]
I'm sorry for that inconvenience. That should definitely not happen and needs to be fixed.
Please report an issue in https://github.com/nextcloud/server

**Comment by georgehrke** [comment]
closing, as this issue is resolved from the calendar pov.
mentioned error was already fixed in https://github.com/nextcloud/calendar/pull/215 and just has to be released.
