### ISSUE TITLE
Shared calendar not found

### ISSUE THREAD

**Issue by JB1985** [nextcloud/calendar#2824]
After upgrade Nextcloud from 19.0.6 to 19.0.7 the shared calendars are not showing anymore on Nextcloud and not more in any Clients like Thunderbird lightning.

### Calendar app
**Calendar app version:** 2.0.4

**CalDAV-clients used:** Thunderbird Lightning

### Server configuration

**Operating system**: Debian Buster

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0.4

**Nextcloud Version:** 19.0.7

**Updated from an older installed version or fresh install:** Updated from 19.0.6

**List of activated apps:**

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - audioplayer: 2.13.1
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.3
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.2.3
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_linkeditor: 1.1.3
  - files_lock: 19.0.0
  - files_mindmap: 0.0.24
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - forms: 2.1.0
  - groupfolders: 7.1.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - polls: 1.6.3
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.11
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.8
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.6
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0

#### Web server error log (e.g. /var/log/apache)
```
XXX.XXX.XXX.XXX - - [18/Jan/2021:09:22:40 +0100] "PROPFIND /remote.php/dav/calendars/XXXX/personal_shared_by_XXXXX/ HTTP/1.1" 404 5749 "-" "DAVx5/2.4.0.1-ose (2019/04/05; dav4jvm; okhttp/3.12.1) Android/8.0.0"
```

#### Log file (data/nextcloud.log)
```
{"reqId":"LODdOotaUNE97FWhFpNX","level":0,"time":"2021-01-18T08:19:34+00:00","remoteAddr":"XXX.XXX.X.X","user":"XXXXXXX","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/calendars/XXXXX/","message":{"Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Message":"No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured","Code":0,"Trace":[{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/remote.php","line":167,"args":["/var/customers/webs/web1/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","Line":161,"CustomMessage":"--"},"userAgent":"iOS/12.4.5 (16G161) dataaccessd/1.0","version":"19.0.7.1"}


{"reqId":"Vfxk8FyPEvmZxRGKqa5x","level":0,"time":"2021-01-18T08:21:23+00:00","remoteAddr":"XXX.XXX.XXXX.XXX","user":"XXXXX","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/calendars/XXXXX/personal_shared_by_XXXXX/","message":{"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"Node with name 'personal_shared_by_XXXXX' could not be found","Code":0,"Trace":[{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":80,"function":"getChild","class":"OCA\\DAV\\CalDAV\\CalendarHome","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":976,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1678,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":363,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/customers/webs/web1/nextcloud/remote.php","line":167,"args":["/var/customers/webs/web1/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/customers/webs/web1/nextcloud/apps/dav/lib/CalDAV/CalendarHome.php","Line":178,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Thunderbird/78.6.1","version":"19.0.7.1"}

```

**Comment by tims-adb** [comment]
I have encountered a similar problem after upgrading from Nextcloud 20.0.4 → 20.0.5. Yet it seems to only occur if the shared **group name has an umlaut**. We have a "Geschäftsstelle" group, shared calendars invisible. When sharing the calendars with a new  group "Geschaeftsstelle", then the sharing works. @JB1985 : can you confirm?
The calendar had exactly the same problem one year ago, I remember that I wrote an issue here ... will try to find the issue from back then and reference it.

**Comment by tims-adb** [comment]
There is a more detailed issue discussion on the issue in the server repository: https://github.com/nextcloud/server/issues/25164

**Comment by JB1985** [comment]
I've updated to the latest Nextcloud 20 version. That seems to be the problem too.

It looks like both versions 19.0.7 and 20.0.5 have the problem.

**Comment by JB1985** [comment]
https://github.com/nextcloud/server/issues/25165
