### ISSUE TITLE
NC20.0.5/Calendar 2.1.3: Shared calendars with groups disappeared

### ISSUE THREAD

**Issue by manu-p** [nextcloud/calendar#2826]
### Steps to reproduce
1. Upgrade to NC20.0.5/Calendar 2.1.3
2. Open Calendar to see all shared calendars

### Expected behaviour
See your calendar(s) as namely and group shared calendar(s)

### Actual behaviour
See only your calendar(s) and namely calendar, not group shared calendar(s)

### Calendar app
2.1.3

**CalDAV-clients used:** whatever

### Client configuration
Whatever

**Operating system:** (e.g. Arch Linux)
Whatever

### Server configuration

**Operating system**: Ubuntu 18.04 LTS

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 20.0.5

Since 20.0.5/Calendar 2.1.3, calendars previously shared by users with users groups are no longer shared, although they appear in ones sharings.

Workaround: everyone unshare and share back again with the group(s) they want to share their calendars.

Running occ dav:remove-invalid-shares removes all the group shared calendars from everyone!

This is for calendars shared with users groups only, calendars shared with named users are not impacted.

**Comment by tcitworld** [comment]
Duplicate from #2825, see the issue in server.
