### ISSUE TITLE
Sharing to groups does not work

### ISSUE THREAD

**Issue by MarcusMerkel-sys** [nextcloud/calendar#2829]
--> 

### Steps to reproduce
1. search and add the group
2. give full approval to edit

### Expected behaviour
individuals in the group should have access to the calendar

### Actual behaviour
The permission for the group is not saved. For indivduals the workflow works. 

### Calendar app
**Calendar app version:** 2.1.3

**CalDAV-clients used:** //

### Client configuration
**Browser:** Safari 14.0.2, Chrome 87.0.4280.141

**Operating system:** MacOS 11.1

**Comment by tcitworld** [comment]
Duplicate from #2825, see the issue in server.
