### ISSUE TITLE
Sharing of calendars with groups that have a blank in the name does not work anymore

### ISSUE THREAD

**Issue by tommybaer** [nextcloud/calendar#2830]
Since the last update of the calendar app the sharing with group that have blank (e.g. "Test Group") in the name does not work anymore.

**Comment by hertz879** [comment]
This. Also I can't add new entries to calendars with a blank in their name either.
Happend after the last update from 20.0.4 to 20.0.5 on a Ubuntu VM installed with the official script.
There is no output in the log or browser console when trying to reshare the calendars.

**Comment by hertz879** [comment]
Oh, this seems to have already been fixed in #2825. Thanks for the fast fix!
