### ISSUE TITLE
[Feature Request] Allow to share imported calendars

### ISSUE THREAD

**Issue by Ich5003** [nextcloud/calendar#2832]
**Is your feature request related to a problem? Please describe.**
In our organisation we use Outlook to organize our rooms.
Outlook provides a public ICS, which allows us to import this calendar into Nextcloud.
At the moment, every user needs to import these on it's own, which is redundant work. 

**Describe the solution you'd like**
To make things easier, it would be nice if one is also able to share imported ICAL calendars within nextcloud.
Sharing as a link would also allow to embed it on a website.

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/server/issues/2902
