### ISSUE TITLE
Creating appointment in calendar selection calendars are missing (only 5 shown)

### ISSUE THREAD

**Issue by HSD-Oli** [nextcloud/calendar#2833]
Using nextcloudpi 20.4 calendar 2.1.3

Dear Developer

If I try to create a new appointment or change an existing appointment in calendar (I have 6 calendars) then in the selection list are always shown only 5 entries (Scrolling in list not possible). 

If I change user then another calendar is not shown.

All calendars are shared with group family consisting of 4 users. Only Personal and Birthdays are not shared.
Please check and correct that more than 5 calendars are shown in the selection list. (See screenshot)

Thanks Oliver
![2021-01-20 13_14_16-Januar 2021 - Kalender - HSD Familien-Cloud](https://user-images.githubusercontent.com/77731905/105176644-c90e3080-5b25-11eb-8d15-2ef73b868ac8.png)

**Comment by miaulalala** [comment]
Can't reproduce any more.
