### ISSUE TITLE
Display of week numbers not according to ISO8601

### ISSUE THREAD

**Issue by Sincopy** [nextcloud/calendar#2835]
### Steps to reproduce
1. Install Calendar App
2. Open Calendar App
3. Enable display of week numbers
4. Look at displayed week number for January 4th 2021.

### Expected behaviour
January 4th 2021 should be in week 1. Week numbers should be displayed in accordance to [ISO8601](https://en.wikipedia.org/wiki/ISO_week_date) which defines the first week of the year to be the one that has a Thursday in it. That, or a setting to switch between current and ISO behaviour. Upstream seems to have [a setting available](https://fullcalendar.io/docs/v4/weekNumberCalculation).

### Actual behaviour
January 4th 2021 is shown in week 2. This may be correct for some locales/interpretations, but is not according to the ISO standard.

### Calendar app
**Calendar app version:** 2.1.3

### Client configuration
**Browser:** Chrome 87.0.4280.141

**Operating system:** Windows 10

### Server configuration

**Operating system**: Official Docker Image of Nextcloud, app installed from app store.

**Database:** PostgreSQL

**Nextcloud Version:** 20.0.4

**Updated from an older installed version or fresh install:** Updated

**Comment by amo13** [comment]
Yes, I just got very confused by this and can confirm that the calendar app shows wrong week numbers.

**Comment by lapor-kris** [comment]
Yes the number of week is wrong on Nextcloud 24.0.2 and Calendar 3.4.2
It says 32nd week, but it should be 31st week.

**Comment by Walfou** [comment]
so any fix for this, or at least the ability to set the week numbering start manually?

**Comment by onny** [comment]
This is possibly fixed with the latest development version of the Calendar app (4.4.0-alpha2)

![image](https://user-images.githubusercontent.com/757752/233857918-36a4f08e-cfec-4c08-8e44-b79950dd953e.png)

I'm using the German locale which should fit ISO8601 in this case.

Could you give it a try?

**Comment by st3iny** [comment]
Yeah, this is probably fixed though https://github.com/nextcloud/calendar/pull/5111 and https://github.com/nextcloud/calendar/pull/5022.

**Comment by miaulalala** [comment]
> Yeah, this is probably fixed though #5111 and #5022.
