### ISSUE TITLE
Sharing calendar with groups having spaces or accentuation in their names does not work anymore

### ISSUE THREAD

**Issue by drossapinel** [nextcloud/calendar#2836]
### Steps to reproduce
1. Connect to NextCloud and open the Agenda app
2. Create or use an existing calendar
3. Try and share it to a group of users having space and/or accents in its name (ex. : "Calendrier Bâtiments" has a space and an accentued character)
4. It looks like it worked ! But if you change app and come back again to your calendar, you'll see that the sharing no longer exists
5. When connecting as one of the user of this group, you do not have access to this calendar

### Expected behaviour
It has worked for several months. It should allow to share calendars with groups of users, whatever their names

### Actual behaviour
Well, it doesn't anymore. If you replace "Calendrier Bâtiments" in the previous exemple by "Calendrier_Batiments" (without space, without accent), it works just fine !

### Calendar app
**Calendar app version: 2.1.3** (see apps admin page, e.g. 2.0.1)

**CalDAV-clients used: irrelevant, this happens in NextCloud Web** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser: Chrome Version 87.0.4280.141** (e.g. Firefox 48)

**Operating system: Windows 10** (e.g. Arch Linux)

### Server configuration

**Operating system: Linux 5.4.78-2-pve x86_64** (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database: mysql 10.3.17** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version: 7.3.20** (e.g. 7.0.3)

**Nextcloud Version: 20.0.5** (see admin page, e.g. 17.0.2)

**Updated from an older installed version or fresh install: Updated**

**Comment by tcitworld** [comment]
Duplicate from #2825, see the issue in server.
