### ISSUE TITLE
dashboard: events with status "cancelled" are displayed in the "upcoming events" field as if uncancelled

### ISSUE THREAD

**Issue by corvus-albus** [nextcloud/calendar#2844]
### Steps to reproduce
1. Create an event in the near future and change status to cancelled
2. Switch to dashboard and look at upcoming events. You will see the event without a sign that it is cancelled.

### Expected behaviour
There should be a sign, that the event is cancelled possibly similar to the  presentation in the calendar app: color with more transparency and stroked text. One could discuss if you should only show events that really happen but I prefer to be informed about cancelling.

### Actual behaviour
The cancelled event is displayed like it was not cancelled.

### Calendar app
2.3.1

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
none

### Client configuration
**Browser:** Firefox 84

**Operating system:** (e.g. Arch Linux)
Ubuntu 20.04

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 20.04
**Web server:** (e.g. Apache, Nginx,...)
apache2
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
mysql
**PHP version:** (e.g. 7.0.3)
7.4
**Nextcloud Version:** (see admin page, e.g. 17.0.2)
20.0.5
**Updated from an older installed version or fresh install:**
updated from 20.0.4
**List of activated apps:**
Accessibility 1.6.0, Activity 2.13.4, AppOrder 0.11.0, Auditing / Logging 1.10.0, Calendar 2.1.3, Carnet 0.23.7, Circles 0.20.6, Collaborative tags 1.10.0, Comments 1.10.0, Contacts 3.4.3, Contacts Interaction 1.1.0, Dashboard 7.0.0, Deck 1.2.3, Deleted files 1.10.1, External storage support 1.11.1, Federation 1.10.1, File sharing 1.12.2, First run wizard 2.9.0, Log Reader 2.5.0, Mail 1.7.2, Monitoring 1.10.0, Moodle integration 0.0.5, Nextcloud announcements 1.9.0, Notes 4.0.2, Notifications 2.8.0, Password policy 1.10.1, Passwords 2021.1.0, PDF viewer 2.0.1, Photos 1.2.3, Privacy 1.4.0, Recommendations 0.8.0, Right click 0.17.0, Share by mail 1.10.0, Support 1.3.0, Talk 10.0.5, Tasks 0.13.6, Text 3.1.0, Theming 1.11.0, Update notification 1.10.0, Usage survey 1.8.0, User status 1.0.1, Versions 1.13.0, Video player 1.9.0, Weather status 1.0.0, Default encryption module 2.8.1, Impersonate 1.7.0, LDAP user and group backend 1.10.2, Music 0.17.3, Notifications for calendar event updates 1.2.0, Preview Generator 3.1.0

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.5.2",
        "overwrite.cli.url": "",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "share_folder": "\/mit_mir_geteilt",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": 51,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "skeletondirectory": "",
        "overwriteprotocol": "https",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "ownpad",
            "ldaporg",
            "files_texteditor"
        ],
        "onlyoffice": {
            "verify_peer_off": true
        },
        "sharing.minSearchStringLength": 1,
        "sharing.maxAutocompleteResults": 15
    }
}
#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by tcitworld** [comment]
Duplicate from #2825, see the issue in server.
