### ISSUE TITLE
A recurring even can't be changed - "500" and rotating wheel in the sidebar

### ISSUE THREAD

**Issue by piiskop** [nextcloud/calendar#2846]
### Steps to reproduce
I'm not sure whether you can reproduce it without my data. I have a recurring event. I clicked it and sidebar opened. I changed the title and added a new participant. Then, I clicked the button for updating all the further occurrences.  The sidebar starts showing the rotating wheel and never stops. In console, it says:

/remote.php/dav/calendars/peacecop-kalmer/matemaatika/27D882C3-526A-4E4C-AE5B-636B57C1369B.ics:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

However, "nginx" nor "apache2" reports anything related. If I put the address to the address bar of the browser, it offers to download an "ICS"-file.

kalmer@test:/var/log/apache2$ tail /var/log/apache2/error.log
[Mon Jan 25 23:37:25.928478 2021] [authz_core:debug] [pid 250909] mod_authz_core.c(817): [client 127.0.0.1:35764] AH01626: authorization result of Require all granted: granted
[Mon Jan 25 23:37:25.928489 2021] [authz_core:debug] [pid 250909] mod_authz_core.c(817): [client 127.0.0.1:35764] AH01626: authorization result of <RequireAny>: granted
[Mon Jan 25 23:37:25.993535 2021] [authz_core:debug] [pid 236343] mod_authz_core.c(817): [client 127.0.0.1:35766] AH01626: authorization result of Require all granted: granted
[Mon Jan 25 23:37:25.993551 2021] [authz_core:debug] [pid 236343] mod_authz_core.c(817): [client 127.0.0.1:35766] AH01626: authorization result of <RequireAny>: granted
[Mon Jan 25 23:37:25.993650 2021] [authz_core:debug] [pid 236343] mod_authz_core.c(817): [client 127.0.0.1:35766] AH01626: authorization result of Require all granted: granted
[Mon Jan 25 23:37:25.993660 2021] [authz_core:debug] [pid 236343] mod_authz_core.c(817): [client 127.0.0.1:35766] AH01626: authorization result of <RequireAny>: granted
[Mon Jan 25 23:37:26.396472 2021] [authz_core:debug] [pid 236345] mod_authz_core.c(817): [client 127.0.0.1:35768] AH01626: authorization result of Require all granted: granted
[Mon Jan 25 23:37:26.396489 2021] [authz_core:debug] [pid 236345] mod_authz_core.c(817): [client 127.0.0.1:35768] AH01626: authorization result of <RequireAny>: granted
[Mon Jan 25 23:37:26.396589 2021] [authz_core:debug] [pid 236345] mod_authz_core.c(817): [client 127.0.0.1:35768] AH01626: authorization result of Require all granted: granted
[Mon Jan 25 23:37:26.396599 2021] [authz_core:debug] [pid 236345] mod_authz_core.c(817): [client 127.0.0.1:35768] AH01626: authorization result of <RequireAny>: granted

Thereby, "nginx" reports no error at all.

The browser's console has also other error messages:

Failed to load resource: the server responded with a status of 404 (Not Found)
/index.php/avatar/cH…NlcnMva2FsbWVy/32:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/ocs/v2.php/apps/use…m%40peetri.edu.ee:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/ocs/v2.php/apps/use…cecop%20kalmer%3A:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/index.php/avatar/pe…op%20kalmer%3A/32:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/index.php/avatar/kr…0peetri.edu.ee/32:1 Failed to load resource: the server responded with a status of 404 (Not Found)
6
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
32:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/ocs/v2.php/apps/use…k%40peetri.edu.ee:1 Failed to load resource: the server responded with a status of 404 (Not Found)
vue.runtime.esm.js:1888 Error
    at XMLHttpRequest.n.value.regeneratorRuntime.mark.regeneratorRuntime.wrap.e.abrupt.a.onreadystatechange (request.js:361)
Ve	@	vue.runtime.esm.js:1888

Once I click any event during that rotating wheel, the console gets more data:

request.js:339 PUT https://nextcloud.tennis24.ee/remote.php/dav/calendars/peacecop-kalmer/matemaatika/27D882C3-526A-4E4C-AE5B-636B57C1369B.ics 500 (Internal Server Error)
(anonymous) @ request.js:339
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
de @ calendar.js?v=f08e8186-14:2
i @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ request.js:117
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
de @ calendar.js?v=f08e8186-14:2
i @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ davObject.js:153
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
Ce @ calendar.js?v=f08e8186-14:2
i @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ davObject.js:35
(anonymous) @ calendarObjects.js:214
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
$ @ calendar.js?v=f08e8186-14:2
i @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
updateCalendarObject @ calendarObjects.js:211
(anonymous) @ vuex.esm.js:847
m.dispatch @ vuex.esm.js:512
dispatch @ vuex.esm.js:402
(anonymous) @ calendarObjectInstance.js:1505
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
G @ calendar.js?v=f08e8186-14:2
i @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
saveCalendarObjectInstance @ calendarObjectInstance.js:1489
(anonymous) @ vuex.esm.js:847
m.dispatch @ vuex.esm.js:512
dispatch @ vuex.esm.js:402
(anonymous) @ EditorMixin.js:413
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
pf @ calendar.js?v=f08e8186-14:2
i @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
save @ EditorMixin.js:400
(anonymous) @ EditorMixin.js:692
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
pf @ calendar.js?v=f08e8186-14:2
i @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
(anonymous) @ calendar.js?v=f08e8186-14:2
beforeRouteUpdate @ EditorMixin.js:659
(anonymous) @ vue-router.esm.js:2450
f @ vue-router.esm.js:2300
r @ vue-router.esm.js:1947
r @ vue-router.esm.js:1951
(anonymous) @ vue-router.esm.js:1948
(anonymous) @ vue-router.esm.js:2322
(anonymous) @ CalendarGrid.vue:245
f @ vue-router.esm.js:2300
r @ vue-router.esm.js:1947
(anonymous) @ vue-router.esm.js:1948
(anonymous) @ vue-router.esm.js:2322
(anonymous) @ windowTitleService.js:66
f @ vue-router.esm.js:2300
r @ vue-router.esm.js:1947
xe @ vue-router.esm.js:1955
Fe.confirmTransition @ vue-router.esm.js:2330
Fe.transitionTo @ vue-router.esm.js:2203
t.push @ vue-router.esm.js:2544
(anonymous) @ vue-router.esm.js:2963
Xe.push @ vue-router.esm.js:2962
(anonymous) @ eventClick.js:86
(anonymous) @ eventClick.js:45
e.trigger @ main.js:4606
n.handleSegClick @ main.js:7679
(anonymous) @ main.js:140
Show 64 more frames
vue-router.esm.js:2008 Uncaught (in promise) Error: Navigation aborted from "/dayGridMonth/now/edit/sidebar/L3JlbW90ZS5waHAvZGF2L2NhbGVuZGFycy9wZWFjZWNvcC1rYWxtZXIvbWF0ZW1hYXRpa2EvMjdEODgyQzMtNTI2QS00RTRDLUFFNUItNjM2QjU3QzEzNjlCLmljcw==/1612164300" to "/dayGridMonth/now/edit/sidebar/L3JlbW90ZS5waHAvZGF2L2NhbGVuZGFycy9wZWFjZWNvcC1rYWxtZXIvbWF0ZW1hYXRpa2EvN0JCMzM0QTQtQ0M4Ri00QzBDLThGOUEtRjcxN0EyOTQ4QTZFLmljcw==/1611645900" via a navigation guard.
    at De (vue-router.esm.js:2008)
    at vue-router.esm.js:1999
    at vue-router.esm.js:2304
    at EditorMixin.js:695
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.throw (runtime.js:118)
    at pf (calendar.js?v=f08e8186-14:2)
    at a (calendar.js?v=f08e8186-14:2)

I did the same procedure with another event and for that event, no "500"-error was generated, however after a seemingly successful update, that event is gone for good. How can I restore it?

### Expected behaviour
The event can be changed without anomalies.

### Actual behaviour
The particular event can't be changed.

## Server configuration detail

**Operating system:** Linux 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.3.25

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.6 - 20.0.6.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - audioplayer: 3.0.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.3
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.3
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_external: 1.11.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_texteditor: 2.14.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - forms: 2.1.0
 - gpxmotion: 0.1.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.8.0
 - maps: 0.1.8
 - metadata: 0.12.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 2.1.2
 - password_policy: 1.10.1
 - photos: 1.2.3
 - polls: 1.6.3
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - registration: 0.6.0
 - scanner: 0.2.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather: 1.7.4
 - weather_status: 1.0.0
 - wopi: 3.5.6
 - workflowengine: 2.2.0
Disabled:
 - dicomviewer
 - drawio
 - drop_account
 - emlviewer
 - encryption
 - external
 - files_automatedtagging
 - files_external_gdrive
 - ojsxc
 - richdocuments
 - spreed
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.tennis24.ee"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.6.1",
    "overwrite.cli.url": "https:\/\/nextcloud.tennis24.ee",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "app_install_overwrite": [
        "onlyoffice",
        "dashboard",
        "files_external_gdrive",
        "dicomviewer",
        "calendar"
    ],
    "tempdirectory": "\/projektid\/nextcloud\/data",
    "overwriteprotocol": "https",
    "mysql.utf8mb4": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "has_rebuilt_cache": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
Request URL: https://nextcloud.tennis24.ee/remote.php/dav/calendars/peacecop-kalmer/matemaatika/27D882C3-526A-4E4C-AE5B-636B57C1369B.ics
Request Method: PUT
Status Code: 500 Internal Server Error
Remote Address: 80.235.6.91:443
Referrer Policy: no-referrer
Cache-Control: no-store, no-cache, must-revalidate
Connection: keep-alive
Content-Length: 262
Content-Security-Policy: default-src 'none';
Content-Type: application/xml; charset=utf-8
Date: Mon, 25 Jan 2021 21:42:14 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Referrer-Policy: no-referrer
Server: nginx/1.18.0 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: et-EE,et;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 1501
Content-Type: application/xml; charset=UTF-8
Cookie: oc_sessionPassphrase=djYYJt0nfO3s13mK64%2F0FxV%2BNsF6yLTu1l0sfSfAnUHIC829dkREfyMVw7hDHIw6tC%2BeS97OyRhPCOx5BPfK1NODYV5j0qT5lHzB2Ulvb8bgClnD6hAFHjojDamv%2FY8J; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; i18next=et-EE; ocd6olbmfjx1=2d129c52bcb4ea30bd006feb846537f4; nc_username=peacecop-kalmer; oct73v7ell46=7t256c27ma7uo4kb00625ai8jq; nc_token=VPwfjVs54LafcQhHi1cdqlQ5l0jQlzE3; nc_session_id=7t256c27ma7uo4kb00625ai8jq
Depth: 0
Host: nextcloud.tennis24.ee
If-Match: "fdc105ce22020522df0a885e876fa294"
Origin: https://nextcloud.tennis24.ee
requesttoken: HV5swCG6Fyo/PFGfPt15agEJtHVZ8A6GFWx26PXbRNo=:SB8erXjufGd6URDreLM1LFNx/UYWm1a3XCRBhd6OI4o=
sec-ch-ua: "Chromium";v="88", "Google Chrome";v="88", ";Not\\A\"Brand";v="99"
sec-ch-ua-mobile: ?1
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Mobile Safari/537.36
X-NC-CalDAV-Webcal-Caching: On
X-Requested-With: XMLHttpRequest
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
VERSION:2.0
PRODID:-//IDN nextcloud.com//Calendar app 2.1.3//EN
BEGIN:VEVENT
CREATED:20210121T101127Z
DTSTAMP:20210125T213107Z
LAST-MODIFIED:20210125T213107Z
SEQUENCE:2
UID:404bd1f1-e18c-468f-9126-3bc4b406e1ea
DTSTART;TZID=Europe/Tallinn:20210125T092500
DTEND;TZID=Europe/Tallinn:20210125T101000
LOCATION:Peetri Lasteaed-Põhikool: A248
SUMMARY:Õpiabi: 6.E (KriTam)
RRULE:FREQ=WEEKLY;BYDAY=MO;UNTIL=20210201T072459Z
RELATED-TO;RELTYPE=SIBLING:f5251bea-b6f3-4294-a1e7-84de55e463f2
RELATED-TO;RELTYPE=SIBLING:77a1a38f-2022-4b72-a84b-5a8d969b6a1c
RELATED-TO;RELTYPE=SIBLING:bb56f84a-8d71-41c7-b261-3165ac6d1e44
RELATED-TO;RELTYPE=SIBLING:99bebee0-0c38-42ca-9596-a31de5e0ae55
RELATED-TO;RELTYPE=SIBLING:e2248753-a91b-48fe-b112-885fcc1875a9
RELATED-TO;RELTYPE=SIBLING:4a33b7ac-dc23-4fc5-be3d-8b1fd04af661
ATTENDEE;CN=kristel.tamm@peetri.edu.ee;CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACT
 ION;ROLE=REQ-PARTICIPANT;RSVP=TRUE;SCHEDULE-STATUS=1.1:mailto:kristel.tamm@
 peetri.edu.ee
ORGANIZER;CN="peacecop kalmer:":mailto:pandeero@gmail.com
EXDATE;TZID=Europe/Tallinn:20210125T092500
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Tallinn
BEGIN:DAYLIGHT
TZOFFSETFROM:+0200
TZOFFSETTO:+0300
TZNAME:EEST
DTSTART:19700329T030000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0300
TZOFFSETTO:+0200
TZNAME:EET
DTSTART:19701025T040000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
	c) ...
</details>

**Comment by tcitworld** [comment]
Please provide nextcloud.log as well.

**Comment by piiskop** [comment]
[nextcloud.log.gz](https://github.com/nextcloud/calendar/files/5870084/nextcloud.log.gz)

**Comment by miaulalala** [comment]
Possibly related to #3282

**Comment by miaulalala** [comment]
Can't reproduce any more.
