### ISSUE TITLE
Mini editor isn't so mini when event descriptions are long

### ISSUE THREAD

**Issue by astrosticks** [nextcloud/calendar#2849]
### Steps to reproduce
1. Open an event in the mini editor
2. Make sure the event has a long description, such as those that come with Zoom invites

### Expected behaviour

The description field should have a max-height set and scrollable y-overflow.

### Actual behaviour

![image](https://user-images.githubusercontent.com/32315760/106031174-d1b1ba00-6083-11eb-8c3a-80e70efcea7d.png)

### Calendar app
**Calendar app version:** Sorry, can't check! Not an admin.

### Client configuration
**Browser:** Firefox 78.6.1esr

**Operating system:** Debian Buster

**Comment by jancborchardt** [comment]
Can confirm, same happens with WebEx invites. You have to delete a lot of the content to be able to see the basic info up top as the modal content does not scroll as expected:
![long description scroll issue](https://user-images.githubusercontent.com/925062/134893001-45e20eeb-120c-4612-8318-aa7695886a88.png)

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/2200
