### ISSUE TITLE
incomplete event title

### ISSUE THREAD

**Issue by doitux** [nextcloud/calendar#2853]
When having a 30 minutes grid and adding a 45 minutes event the event title is placed in a new line but not complete visible. 30 and 60 minutes are okay. This  happens in timeGridWeek and timeGridDay.

![Incomplete-Title](https://user-images.githubusercontent.com/1719554/106243507-cf796800-6209-11eb-9e0b-b25f279b3743.png)

Calendar: 2.1.3
NC: 20.0.6

**Comment by goebbe** [comment]
Just to add to the issue: 
- The information about the timing in the event seems to be redundant, here.  It is very easy to see when the event starts and stops, anyway. 
One approach could be to write the event name in the first line  and the information about the timing afterwards (e.g. second line).   
- It would also be great if the "title" of the event would be readable in very short (e.g. 15 minute) events (in a 30 minute grid) - this would require to cut some of the vertical space in the first line.

**Comment by szaimen** [comment]
Does this still happen?

**Comment by doitux** [comment]
No, there seems to be a fix which expands the 45 minutes event to 60 minutes in the grid: 

![grafik](https://user-images.githubusercontent.com/1719554/135399730-eb1e8970-7bbc-4399-a1c2-655b624526fa.png)

**Comment by szaimen** [comment]
Thanks for confirming

**Comment by goebbe** [comment]
I believe the size of the event should respect the start-time and end-time.
I.e. an event that stops at 14:00h should not overlap with an event that starts at 14:00h.
The solution should be to put the title of the event in the first line, if there is not enough space for the title in the second line.  

![Screenshot from 2021-09-30 15-28-19](https://user-images.githubusercontent.com/35854226/135464140-4b451a6d-43c0-4688-a039-c4f90c855766.png)

**Comment by szaimen** [comment]
Please open a new issue for that. Thanks!

**Comment by ChristophWurst** [comment]
@goebbe thanks a lot for the feedback! If you create a new ticket you can use the "Reference in new ticket" action from the ... menu of your comment and github will copy over the text :)

**Comment by goebbe** [comment]
@ChristophWurst thanks!  I opened a new ticket for the "overlapping events"

**Comment by miku86** [comment]
Hey folks,

I think this is not fully fixed.

![2021-10-04_15-35](https://user-images.githubusercontent.com/7271016/135861191-28980749-5c0d-4559-a9c6-1d6a06cb37a9.png)

```
Nextcloud 21.0.0
Calendar 2.3.4
```

Greetings
Michael
