### ISSUE TITLE
Through agenda, being able to add usergroup of attendees to an event

### ISSUE THREAD

**Issue by julian70400** [nextcloud/calendar#2854]
I don't understand actually with the 20.0.6, with an huge association (hundred of users in differents nextcloud usergroups) how can I add a group of attendees. If I have 3 groups of 30 attendees, I need to enter 90 attendees manually.. It's a bit annoying

I just want to be able to simply add my nextcloud usersgroup in the attendees options.

Actually, I have no solution for this problem, and as far as I know, I am not the only one in this case. I am really surprised that a such feature doesn't exists. Nextcloud have an excellent approach of group whith every others features (share agenda, files, notes, tasks, etc..), but, nothing about an event.

Thanks !

**Comment by tcitworld** [comment]
Duplicate from #167
