### ISSUE TITLE
Dark theme missing inverted icons

### ISSUE THREAD

**Issue by rullzer** [nextcloud/calendar#2865]
I just checked

![2021-02-05_11-29](https://user-images.githubusercontent.com/45821/107023501-079f1e80-67a7-11eb-8970-b91083fa972c.png)

We miss some icons it seems.

**Comment by rullzer** [comment]
mm,m chrome also shows them. let me clear firefoxes cache.
yep.,..

**Comment by tcitworld** [comment]
To be fair people and myself often encounter CSS issues like that which are resolved after a browser cache force refresh, not sure why I've only heard about it with this app though.
