### ISSUE TITLE
Support HTTPS for WebCal

### ISSUE THREAD

**Issue by treiher** [nextcloud/calendar#287]
Please add support for retrieving WebCal calendars via HTTPS.

### Expected behaviour
Subscribing to a WebCal calendar with the following URL should work:
`https://USERNAME:PASSWORD@HOST/url/to/calendar`

The calendar should then be retrieved via HTTPS.

### Actual behaviour
Subscribing to a WebCal calendar is only possible without specification of protocol (see also Issue #70):
`USERNAME:PASSWORD@HOST/url/to/calendar`

The calendar will be retrieved via HTTP. This leaks the calendar data and also the user credentials in the case of basic auth.

### Server configuration
**Server version:** 11.0.0

**Calendar version:** 1.4.1

**Comment by georgehrke** [comment]
> Subscribing to a WebCal calendar is only possible without specification of protocol 

That's not true.
You can use no protocol, `webcal://`, `http://`, `https://`

**Comment by georgehrke** [comment]
to me, this is a dup of #70

**Comment by georgehrke** [comment]
If you use `webcal://`, it will first try `https://` and if that doesn't work fallback to `http://`

**Comment by georgehrke** [comment]
You commented in #70 already, please keep the discussion there.

**Comment by georgehrke** [comment]
I just double checked.
I was able to subscribe to some private google calendar url using `https://`
