### ISSUE TITLE
Deselecting / selecting calendar

### ISSUE THREAD

**Issue by Dieter15** [nextcloud/calendar#2871]
I have NC 20.0.7 installed, including the NC Calendar app (actual version). It is possible to import iCal files.

The current implementation only allows the following actions for any given calendar (when right-clicking the mouse):

1. Edit name of calendar
2.     Edit color (assigned to calendar) ; extremely IMPORTANT :frowning:
3.     Copy private link
4.     Download
5.     Delete

I suggest to enhance the list of features for deployment in NC21 or latest in NC22:

1. Allow for deselection / reselection of any existing calendar. The calendar data should be retained when deselecting a calendar, but the calendar entries should not displayed as long as the calendar in question is deselected. Reselecting it should result in redisplaying its data.
2. Deleting an event should not be too complicated as it is now. One has to mark the event, click on button “More”, click on the three dots and finally selecting “delete”. Deploy DELETE button already at the level when marking / selecting the event.
3. Do not allow the built-in calendar “contacts_of_birthday” to have duplicates. When dropping (NOT deselecting) an address book, and re-importing a new version of that address book, the birthdays appear twice or even manyfold. The Calendar app should do a good housekeeping to ensure that every event mentioned in any address book is displayed in the calendar “contacts_of_birthday” only once. One can do this in the command line with “sudo -u www-data php ./occ dav:sync-birthday-calendar USERNAME”, but why to do it manually when NC could do this automatically by itself?

**Is your feature request related to a problem? Please describe.**
Not related

**Describe the solution you'd like**

**Describe alternatives you've considered**
No alternatives known

**Additional context**
No any other context

Kind regards
Dieter

**Comment by tcitworld** [comment]
> Allow for deselection / reselection of any existing calendar.

Click on the calendar name.

> Deleting an event should not be too complicated as it is now.

See #1570 to add a way to delete an event directly from the popover

> Do not allow the built-in calendar “contacts_of_birthday” to have duplicates. 

Seems to be an issue, as the background job to sync birthdays does pretty much the same as the command. Follow https://github.com/nextcloud/server/issues/25643 for updates.
