### ISSUE TITLE
Calendar sharing not working with whitespaces in group name

### ISSUE THREAD

**Issue by Flachzange** [nextcloud/calendar#2872]
The following bug affects our nextcloud production instance massively as all our group names contain whitespaces.

### Steps to reproduce
1.Create two Accounts A and B in Nextcloud
2. Assign Account A to a group named "Group G"
3. With Account B share your personal calendar (or any other) with "Group G"

### Expected behaviour
Account A is able to view the shared calendar from B as he is part of "Group G"

### Actual behaviour
Account A cannot see the shared calendar. Reason is the whitespace in the group name.

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.4
**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
n/a
### Client configuration
n/a

**Operating system:** (e.g. Arch Linux)
n/a

### Server configuration

**Operating system**: (e.g. Debian 8)
Unkown Linux 5.4.0-64-generic x86_64

**Web server:** (e.g. Apache, Nginx,...)
Unknown

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB 10.5.6

**PHP version:** (e.g. 7.0.3)
7.3.26

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
19.0.8

**Updated from an older installed version or fresh install:**
Updated
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/server/issues/25165, will be fixed in 19.0.9 & 20.0.8.
