### ISSUE TITLE
Calendar share with group does not work (even vanishes)

### ISSUE THREAD

**Issue by enaut** [nextcloud/calendar#2876]
### Steps to reproduce
1. create a calendar
2. share with group (not circle)
3. logout and login to group member

### Expected behaviour

The Calendar should be visible and shared with the group member

### Actual behaviour
The Calendar is not shared and even after going back to the sharing account it is not listed as shared anymore. Sharing to circles and to individual accounts works as expected.

There have been shares by group in place before the 20.0.5 update and after the update they vanished... (or around that time)

### Calendar app
**Calendar app version:** 2.1.3

**CalDAV-clients used:** Nextcloud

### Client configuration
**Browser:** Firefox

**Operating system:** Fedora 32

### Server configuration

**Operating system**: Fedora 32

**Web server:** Nginx

**Database:**  MariaDB

**PHP version:** 7.4.15

**Nextcloud Version:** 20.0.7

**Updated from an older installed version or fresh install:** updated

**Comment by tcitworld** [comment]
Duplicate from nextcloud/server#25165, will be fixed in 19.0.9 & 20.0.8.

**Comment by enaut** [comment]
sorry and thanks for fixing!
