### ISSUE TITLE
Event Preview too large to fit on screen for subscribed calendars

### ISSUE THREAD

**Issue by swedgwood** [nextcloud/calendar#2877]
### Steps to reproduce
1. Create an event in a subscribed calendar (such as an Outlook or Google calendar that you are subscribed to using the `.ics` link) with a long description (such as a Google meet invite)
2. Click on it to show the preview in Nextcloud

### Expected behaviour
I would expect the preview to fit on the screen, and possibly the extended contents to be navigable using a scroll bar, or to be truncated and accessible via the 'Show more details' button.

### Actual behaviour
In firefox:
![eventtoobig](https://user-images.githubusercontent.com/28223854/107370116-7992a300-6ada-11eb-9d51-ad81accbbebe.png)
(I also tested it in a Firefox Private Window with my extensions disabled, giving the same result)

In chrome:
![eventtoobigchrome](https://user-images.githubusercontent.com/28223854/107370123-7bf4fd00-6ada-11eb-9aa6-dfb7c7447a89.png)
Chrome doesn't seem to wrap the links, making it also extend off the screen to the right

### Calendar app
**Calendar app version:** 2.1.3

**CalDAV-clients used:** Nextcloud Calendar in the browser

### Client configuration
**Browser:** Firefox 85.0 (64-bit), and Chromium Version 88.0.4324.146 (Official Build) (64-bit)

**Operating system:** Pop!_OS 20.10

### Server configuration

**Operating system**: Ubuntu 20.04.2 LTS (Ubuntu Server)

**Web server:** Nginx (tunelled through Cloudflare)

**Database:** PostgreSQL

**PHP version:** 7.4.3

**Nextcloud Version:** 20.0.7 (although I have also had this issue on previous versions)

**Updated from an older installed version or fresh install:** Updated from older, I think it was 20.0.4 when i first installed it.

**List of activated apps:**

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - music: 1.0.0
  - news: 15.3.1
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<my domain here>"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.7.1",
        "overwrite.cli.url": "<my domain here>",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

#### Web server error log (e.g. /var/log/apache)
N/A

#### Log file (data/nextcloud.log)
N/A

#### Browser log
There is nothing here except deprecation warnings

### Note

- This looks like it might a duplicate of https://github.com/nextcloud/calendar/issues/2849 although that issue specifically refers to the mini editor, not the preview.
- **The event in the pictures is from a calendar subscription (an .ics link)**, I have not tested this with a regular event.
- I can temporarily mitigate this by zooming out until it is small enough for me to click the more details button, which displays properly.
- When zoomed out (on Firefox, haven't tested Chrome), the description box seems to jut out of the preview box (the title seems to jut out as well?)
![weirdshape](https://user-images.githubusercontent.com/28223854/107372017-ddb66680-6adc-11eb-83cb-fae5d4fc842e.png)

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/2200
