### ISSUE TITLE
Date picker partly hidden behind calendar view, invisible UI elements

### ISSUE THREAD

**Issue by TheRealCrusher** [nextcloud/calendar#2880]
### Steps to reproduce
1. Create a new or edit an existing calendar event 
2. Click on start date to open date picker 

### Expected behaviour
Date picker should be completely visible

### Actual behaviour
Date picker is partly obscured by calendar view on the left of it.
The left column of dates in the date picker as well as the "previous year" UI element are hidden. The elements are still clickable, but can only be identified by context.

### Calendar app
**Calendar app version:** 2.1.3

### Client configuration
**Browser:** Firefox 84.0.1 x64

**Operating system:** Windows 7

### Server configuration

**Operating system**: Ubuntu 18.04.5 LTS

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.27

**Nextcloud Version:** 20.0.7.1

**Updated from an older installed version or fresh install:** Installed on earlier minor version of v20

![grafik](https://user-images.githubusercontent.com/76921122/107519818-fdb75a00-6bb0-11eb-8c79-c707f29306fb.png)

**Comment by rtyler** [comment]
I can also confirm that I see this with version 2,3.1 in the latest Firefox on Linux (89.0) as well. Took me a while to figure out where Sunday was!

**Comment by lascapi** [comment]
Hi, I got a similar issue with or without week number enabled. I checked Chromium based and Firefox (v.92) navigators. 

The date picker is under the calendar as you can see : 
![iridium_Q5ay5zYTXv](https://user-images.githubusercontent.com/6562527/127022694-f2a7fa70-c494-490e-b1ba-805ca068b661.png)

With NextCloud 21.0.3 and Calendar 2.3.1.

**Comment by ChristophWurst** [comment]
Same problem in the recurrence dialogue when you set an end date for the rule

**Comment by raimund-schluessler** [comment]
This can be overcome by setting `:append-to-body="true"` for the DatetimePicker, but it needs a bit of effort, since this will not work / break in the SimpleEditor.

**Comment by TheRealCrusher** [comment]
In Calendar v. 2.3.3 the issue seems to be resolved. On high resolution displays the picker is positioned correctly and its content fully visible. On lower resolution displays the picker seems to float independent of the date fiels, but in a suitable position. Also all content is visible.

Can anyone else verify that it is indeed fixed? @lascapi, how about you?

**Comment by raimund-schluessler** [comment]
It is not fixed for me here (NC 22.1.1, Calendar 2.3.3, Firefox).

**Comment by rtyler** [comment]
Unfortunately I can also confirm that 2.3.3 in Firefox 91.0.1 presents the same behavior as before :cry:

**Comment by lascapi** [comment]
Hi, I just tried with Calendar v. 2.3.3 with NextCloud 21.0.3 and 21.0.4 and it's still present for me with: 
- Firefox 93 
- Firefox 91 
- Chromium 89. 

My screen is a:
- 15" 
- 1920x1080 
- 125%  
- windows 10

**Comment by raimund-schluessler** [comment]
Fix is in https://github.com/nextcloud/calendar/pull/3469.
