### ISSUE TITLE
FullAcces to shared calendar

### ISSUE THREAD

**Issue by BEESUPPORT** [nextcloud/calendar#2892]
As in 
[https://help.nextcloud.com/t/einen-kalender-fur-einen-anderen-nutzer-komplett-freigeben/107946/6] described, we want to give fullacces rights to specific users in Nextcloud, so they can even take notice of privat entrys. 

Example: 
The boss makes a privat entry with a checkup by his doctor. Marked as occupied to inform his workers he is not available. 
Her or his secretary, with read/write access to his or her calender, sees also "occupied" only.
The boss does a phonecall to get the doctors address while driving from the secretary. 
The adress is written in the privat enty. The secretary can't access this information. 

The needed feature ist to give special Users more rights for my calendar then every other users, to access this information.
In some scenarios there ist a deputy in the backofficem, wich has to takes acces to those notes. 

My suggested solution is a further option in the sharing-options for the specific calendar to give someone fullaccess.  

Regards
Stefan

**Comment by tcitworld** [comment]
This is called calendar delegation and is [already implemented in server](https://github.com/nextcloud/server/pull/16666), but only some macOS clients support this.

For a Nextcloud Calendar interface, see https://github.com/nextcloud/calendar/issues/2706

**Comment by BEESUPPORT** [comment]
@tcitworld 
So, we use the Nextcloud Frontend only. 
When the feature ist implemented already, there has to be a workflow to give this controls either per shell or there is a option in the webfrontend we don't know. Please give us a hint.

**Comment by tcitworld** [comment]
Sorry not not being clear. The feature is not yet available in the Nextcloud Calendar front-end, follow the issue linked above for updates.

**Comment by BEESUPPORT** [comment]
Oh ah, yes. I'm a stupid moron for nor regonizing the issue link.
It was my mistake
