### ISSUE TITLE
Make it easier/ faster to delete events

### ISSUE THREAD

**Issue by goebbe** [nextcloud/calendar#2893]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to **delete events**. 
At the moment deleting takes four steps to delete an event:  
1. Click event  2. Click "more"  3. Click "three point menu"  4. Click "delete"
This feels rather **slow** and cumbersome. Especially when I have to delete several events in a row. 

Deleting events is one of my most used features of a calendar - here is my personal shortlist: 
Create, Modify, Delete, Navigate, Search    :-) 

**Describe the solution you'd like**
- Add a small **Delete Button** to the "simple event editor" that opens when right-clicking on an event. 

**Describe alternatives you've considered**
- Add a **Keyboard-Shortcut**  (click on an event - when the "simple event editor" opens, allow me to delete the event by pressing "Del" or "Backspace".  

**Additional context**
I am aware that it is currently not possible to undo "delete" - however I don't see a real problem when deleting a single event.
- possibly one should ask for confirmation before deleting a series of events.   
- ask for confirmation - but allow choosing "Don't ask me again" in the confirmation dialogue.

**Comment by ChristophWurst** [comment]
> Add a small **Delete Button** to the "simple event editor" that opens when right-clicking on an event

This is what we should do. It will also work nicely on devices without a keyboard.

**Comment by alexanderdd** [comment]
Some people (like me) use the sidebar editor as default. (I never see the simple editor)

In sidebar editor, there should be **a delete button next to the save button** at the bottom (not in the three dot menu). [Btw the save button will soon be always visible, "sticky"]

Agree?

**Comment by CorentinS6** [comment]
> > Add a small **Delete Button** to the "simple event editor" that opens when right-clicking on an event
> 
> This is what we should do. It will also work nicely on devices without a keyboard.

Hello,
What's new about that ?
Best regards
