### ISSUE TITLE
Failing to parse valid ICS calendars & events

### ISSUE THREAD

**Issue by nezroy** [nextcloud/calendar#2894]
Parsing vCalendar data using Sabre is defaulting to strict mode. This is causing ICS events produced by some tools to fail when they include properties such as "X-ENTOURAGE-TZID", even though many other tools & validators would consider these OK.

Sabre's vCal parsing can handle these ICS files just fine, but only if the `VObject\Reader::read` method is passed the `VObject\Reader::OPTION_FORGIVING` parameter. However, the call to the read method in `validateICalendar` (in Plugin.php) does not set this parameter.

The call to this method should default to enabling the "forgiving" option. Alternatively, a plugin setting could at least allow us to enable this option on demand.

**Comment by nezroy** [comment]
Oh, sorry this is happening in the Sabre lib, I was thinking this method was called directly from the calendar plugin. Nevermind :)

**Comment by tcitworld** [comment]
Also the calendar app is only a CalDAV client, the server is the `dav` app in https://github.com/nextcloud/server.
