### ISSUE TITLE
Calendar cannot be shared with users or groups with an empty space in their name

### ISSUE THREAD

**Issue by nilskamm** [nextcloud/calendar#2908]
### Steps to reproduce
1. Create a group with the name "Nils Test"
2. Share a calendar to the group "Nils Test" and give rights if you want
3. Reload the calendar website
4. The group "Nils Test" is no longer shown in the shares

### Expected behaviour
The group should still be there and everyone in the group should have access to the calendar.

### Actual behaviour
As in the Steps to reproduce. The group is no longer shown and no access is granted.

### Calendar app
**Calendar app version:**
2.1.3

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
none

### Client configuration
**Browser:**
Firefox 86

**Operating system:**
Windows 10

### Server configuration

**Operating system**: 
unknown - Webhosting

**Web server:** 
Apache

**Database:**
MySQL

**PHP version:**
7.4.14

**Nextcloud Version:**
20.0.7 (fresh installation)

**Comment by tcitworld** [comment]
Duplicate from nextcloud/server#25165, will be fixed in 19.0.9 & 20.0.8.
