### ISSUE TITLE
Choose a timezone for new events

### ISSUE THREAD

**Issue by rhiaro** [nextcloud/calendar#2912]
I frequently need to create events on a calendar that are scheduled in a timezone different to the one I am in, and the locale of my nextcloud instance.

This becomes a problem with daylight savings, specifically that daylight savings in, eg. the UK and USA are out of sync, and that many countries don't use daylight savings at all. When I create a new event I'd like to be able to, for example, specify the time in a US timezone, so that it stays in sync with daylight savings shifts in the US, and the UI still shows it correctly in my local time, whether I'm in a place that uses daylight savings or not.

(Please let me know if this is already possible - besides hand editing the ICS file and re-importing it.)

**Comment by tcitworld** [comment]
When creating an event you can specify the timezone.
![image](https://user-images.githubusercontent.com/2197836/108972773-f0f03700-7683-11eb-930d-846623438a59.png)

**Comment by rhiaro** [comment]
D'oh yeah, after looking for this for weeks, I just found it after posting this issue, somehow, and came back here to close it myself. Sorry! Thanks!

**Comment by miku86** [comment]
Got a question regarding this.

Is it intentional that changing the timezone of the start doesn't change the timezone of the end?

**Comment by tcitworld** [comment]
@miku86 Probably not, feel free to open an issue to discuss this!
