### ISSUE TITLE
Copy event from subscribed calendar

### ISSUE THREAD

**Issue by DuncanLithgow** [nextcloud/calendar#2915]
**Is your feature request related to a problem? Please describe.**
I have subscribed to my own google calendar as part of a migration away from google. I would like to be able to copy events from my Google calendar.

**Describe the solution you'd like**
A simply button to copy an event to my own calendar. Maybe changing the event 'download' button into a dropdown menu which includes a 'duplicate' option which downloads and adds an event in one action.

**Describe alternatives you've considered**
I could download one or multiple events manually and add them again manually.

**Comment by tcitworld** [comment]
Should be covered by https://github.com/nextcloud/calendar/issues/113 and fixed with https://github.com/nextcloud/calendar/pull/2621

**Comment by DuncanLithgow** [comment]
so those fixes will also work for subscribed calendars? I didn't see that mentioned.
