### ISSUE TITLE
contact birthdays with no year given are shown with (*1604) in calendar

### ISSUE THREAD

**Issue by wetsixteen** [nextcloud/calendar#292]
### Steps to reproduce
1. add contact "Contact Name" in iOS contacts app, give birthday as today without year
2. open calendar app in webUI
3. see (*1604) as year of birth in new entry for today

### Expected behaviour
"Contact Name (*)" is displayed

### Actual behaviour
"Contact Name (*1604)" is displayed

### Client configuration
**CardDAV-clients:** iOS 10.2 Contacts app

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by wetsixteen** [comment]
I dont think this is a server issue.

**Comment by georgehrke** [comment]
it is, trust me
