### ISSUE TITLE
Share calendars externally

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/calendar#2941]
I would like to be able to share a calendar with users of another nextcloud instance, without link sharing. I want to know, who gets my calendar. 

And I want to allow them to share my calendar with users and groups on their instance.

**Comment by kaulex99** [comment]
Just want to put a bit more attention on this feature request. Essential request in my opinion.

**Comment by tcitworld** [comment]
This is https://github.com/nextcloud/server/issues/1440 (and possibly https://github.com/nextcloud/server/issues/19994 for the resharing part).
