### ISSUE TITLE
Transfer calendar from one user to another

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/calendar#2945]
It would be very useful for me to be able to transfer the ownership of a calendar to another. I know, I can do this via import/export. But that means the other user has to set all permissions anew and the external link changes.

**Comment by tcitworld** [comment]
You can do this with the `occ dav:move-calendar` command https://docs.nextcloud.com/server/21/admin_manual/configuration_server/occ_command.html#dav-label

**Comment by kaffeeringe** [comment]
Cool! Thank you. So there's only a UI missing?

**Comment by tcitworld** [comment]
Well this shouldn't be a common operation, and should be doable only by an admin, so CLI seems enough. Otherwise you should rely on shares / dedicated fake user that holds some calendars / calendar delegation.

**Comment by kaffeeringe** [comment]
I can't access ssh. I have to contact our service-provider for that.
