### ISSUE TITLE
close icon in sidebar is not translated

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/calendar#2952]
### Steps to reproduce
1. Open sidebar with details of event
2. Move mouse over close icon
3. See tooltip

### Expected behaviour
Tooltip is translated

### Actual behaviour
Tooltip is not translated

![close_1](https://user-images.githubusercontent.com/34692335/111506154-a37a5d80-8749-11eb-9d3e-0dffecd9a349.png)

### Versions
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
I'm an user not an admin, don't know how to see version of app
**Nextcloud**
20.0.7.1
Tested today with https://demo2.nextcloud.com/

**Comment by Valdnet** [comment]
In version 2.1.3 there is a translation. Please check that it is translated in your native language.

**Comment by raimund-schluessler** [comment]
This is a problem of the vue-components. Some strings to translate are not extracted correctly, see https://github.com/nextcloud/nextcloud-vue/pull/1776 and, hence, are not translated.

**Comment by tcitworld** [comment]
Closing this issue here then.
