### ISSUE TITLE
Possibility to add a Nextcloud circle as attendees for an event [$250]

### ISSUE THREAD

**Issue by m4us1ne** [nextcloud/calendar#2954]
It would be nice to invite a Circle that , ~~even without being part of it~~

# Related issues
* To add Nextcloud groups (user management, including LDAP) as attendees for an event, see #2955
* To add Nextcloud contact groups as attendees for an event, see #167
* To add a Nextcloud talk group as attendee for an event, see #2956

**Comment by tcitworld** [comment]
> even without being part of it

Disagree on this part. Circle should work just like general groups and the share flow should be the same as in Files.

Inviting circles is already talked into #167, so closing here.

**Comment by m4us1ne** [comment]
the problem we have with  #167 is that it does not include circles in the description and we would like to put a bounty specific on the implementation of that feature. the description of #167 does not inclued circles and thus putting a bounty on it could lead to not solving our problem.

**Comment by tcitworld** [comment]
In that case, reopening here and splitting #167 into multiple issues.

There's heavy work coming up on Circles, so we'll probably wait for evolutions before starting work here.

**Comment by tcitworld** [comment]
@m4us1ne Note that we don't use Bountysource anymore.

**Comment by m4us1ne** [comment]
@tcitworld are there alternatives to support the development on a specific issue?

**Comment by tcitworld** [comment]
You can get a [Nextcloud Subscription](https://nextcloud.com/enterprise/) or [contact freelancers](https://help.nextcloud.com/c/nextcloud-freelancing/48).

**Comment by DJaeger** [comment]
Bounty-URL:
https://www.bountysource.com/issues/97216062-invite-a-circle-to-a-calendar-event

**Comment by tcitworld** [comment]
Reopening until #5420 is merged
