### ISSUE TITLE
Floating Time Zones

### ISSUE THREAD

**Issue by Grimace780** [nextcloud/calendar#2958]
An event in a floating time zone appears at the same time regardless of which time zone the user is in.

Example: I want to schedule a workout for 10am Fridays. But do that workout at 10am in my current time zone. Meaning if I’m in the Mountain time zone I"m doing the workout at 10am Mountain but if I move to the Pacific time zone that workout is done at 10am Pacific.

This is from the perspective of someone migrating from the Apple iCloud.

**Comment by tcitworld** [comment]
Can't check right now but there should be a "None" item on the bottom of the timezone list that should do exactly that if I recall correctly.

**Comment by raimund-schluessler** [comment]
> 
> 
> Can't check right now but there should be a "None" item on the bottom of the timezone list that should do exactly that if I recall correctly.

I see a "floating" timezone, but I didn't check if it does as requested.

**Comment by Grimace780** [comment]
> > Can't check right now but there should be a "None" item on the bottom of the timezone list that should do exactly that if I recall correctly.
> 
> I see a "floating" timezone, but I didn't check if it does as requested.

Missed this earlier and floating seems to work as intended.  I shall mark this as complete / resolved.  thank you.
