### ISSUE TITLE
Selecting a calendar to import

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/calendar#2963]
It is not possible to select a calendar to import. The window is inactive.

![obraz](https://user-images.githubusercontent.com/47037905/112206017-bd1e1800-8c15-11eb-96dc-ab8e1d34c685.png)

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.1.3 

### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 86.0.1

**Operating system:** (e.g. Arch Linux)
Win10

### Server configuration

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
20.0.8 and 21.0.0

**Comment by raimund-schluessler** [comment]
Could it be, that there is only this single calendar existing?

**Comment by Valdnet** [comment]
No. There are several calendars.

**Comment by raimund-schluessler** [comment]
Weird. Are they writable? I just tried it, and I can select any calendar present.

**Comment by Valdnet** [comment]
I can save events in calendars. I can also import the calendar as new. But I can't choose which calendar to import on.

**Comment by Valdnet** [comment]
You must take into account that the calendar selection window is inactive (gray).

**Comment by raimund-schluessler** [comment]
> 
> 
> You must take into account that the calendar selection window is inactive (gray).

Yes, I saw that. Maybe the file you want to import only contains VTODOs (tasks) and none (or only "New calendar") of your calendars supports VTODOs. Then you can't import this file into the other calendars.

**Comment by Valdnet** [comment]
> Yes, I saw that. Maybe the file you want to import only contains VTODOs (tasks) and none (or only "New calendar") of your calendars supports VTODOs. Then you can't import this file into the other calendars.

It is correct. This is VTODOs (tasks). It works fine on another calendar. Thanks a lot for the clarification 🥇.
I am closing the issue.
