### ISSUE TITLE
Create event -> move to other calendar -> change dates shows event twice for original and new calendar

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#2964]
### Steps to reproduce
0. Create a secondary calendar if you don't have one
1. Open monthly view
2. Click and drag to create a multi-day event
3. Give the event a name and save
4. Open the calendar info box and move the event to another calendar
5. Change the dates of the moved event

### Expected behavior
The event shows once

### Actual behaviour
The event shows for the old and new calendar

After a refresh the problem is gone, so I assume this has to do with remnant data in the Vue store or similar.

![Bildschirmfoto von 2021-03-24 09-10-49](https://user-images.githubusercontent.com/1374172/112276993-9695c680-8c81-11eb-91ed-374450bad14d.png)

### Calendar app
**Calendar app version:** master as of today

**Comment by TimonPllkrn** [comment]
I had the same problem even without changing the date.
1. create new event
2. move to another calendar
3. move to third calendar
4. event is shown twice, but second one does not exist

![calendarBug](https://user-images.githubusercontent.com/64217916/114165817-3fece580-992d-11eb-8757-58dbaa35cb69.gif)

**Comment by miaulalala** [comment]
Can't reproduce
