### ISSUE TITLE
Design issues with date picker in free/busy view when week numbers are on

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#2965]
### Steps to reproduce
1. Enable week numbers in the bottom left
2. Create an event
3. Add at least one attendee
4. Open free/busy view
5. Open the date picker in the modal

### Expected behaviour
Smooth design

### Actual behaviour
![Bildschirmfoto von 2021-03-24 09-24-30](https://user-images.githubusercontent.com/1374172/112278181-db6e2d00-8c82-11eb-83e3-f74c6a54a39f.png)

### Calendar app
**Calendar app version:** lastest master of today

### Browser
FF86

**Comment by lascapi** [comment]
Hi, I got a similar issue with or without week number enabled. I checked Chromium based and Firefox (v.92) navigators. 

The date picker is under the calendar as you can see : 
![iridium_Q5ay5zYTXv](https://user-images.githubusercontent.com/6562527/127022694-f2a7fa70-c494-490e-b1ba-805ca068b661.png)

**Comment by GretaD** [comment]
I cannot reproduce it with FF and Brave, same for @szaimen

**Comment by tcitworld** [comment]
Related to https://github.com/nextcloud/calendar/issues/2880 ?

**Comment by GretaD** [comment]
> Related to #2880 ?

this i can reproduce and already have a fixup, but for the one that Christoph reported above, i cannot reproduce it. Can you btw?

**Comment by ChristophWurst** [comment]
can't reproduce anymore
