### ISSUE TITLE
Calendar menu expands when I click Edit name/color

### ISSUE THREAD

**Issue by GretaD** [nextcloud/calendar#2966]
### Steps to reproduce
1. Open calendar and click the action menu in any of your calendars
2. Click Edit colour/name

### Expected behaviour
The calendar doesn't expand and the menu arrow doesnt "jump" away from the menu
### Actual behaviour
![caleditnameexpand](https://user-images.githubusercontent.com/12728974/112278036-af52ac00-8c82-11eb-9a01-5b688854601c.png)

### Calendar app
**Calendar app version:** master

### Client configuration
**Browser:** FF
**Operating system:** Ubuntu

**Comment by GretaD** [comment]
this bug still exist even after nextcloud/nextcloud-vue#1967

**Comment by raimund-schluessler** [comment]
> this bug still exist even after [nextcloud/nextcloud-vue#1967](https://github.com/nextcloud/nextcloud-vue/pull/1967)

Because the fix is only in nextcloud/vue@4.x and Calendar still uses 3.x

**Comment by GretaD** [comment]
this is fixed on vue 4
