### ISSUE TITLE
Android Calendar App

Is it possible to create an android calendar app to Nextcloud Calendar like Google Calendar ?  
Thanks for reading.

### ISSUE THREAD

**Issue by PavelDelhomme** [nextcloud/calendar#2975]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tcitworld** [comment]
https://docs.nextcloud.com/server/21/user_manual/en/pim/sync_android.html#contacts-and-calendar
