### ISSUE TITLE
Mail about "Invitation updated" doesn’t say what actually happened

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#2984]
**Is your feature request related to a problem? Please describe.**
When you invite someone for an event, and they accept, you get a notification mail with the subject "Re: Event title" and a big "Invitation updated", with the event details below. It is unclear what was actually updated.

**Describe the solution you'd like**
Instead of "Invitation updated", it could say "Christoph accepted the invitation" or "Thomas rejected the invitation" or whatever fits. Maybe even in the subject already like: "`Name` accepted the invitation for `event name`" so it’s quickly visible and can then be deleted/archived.

**Additional context**
![image](https://user-images.githubusercontent.com/925062/112827025-1363de80-908e-11eb-81a8-9a39e8e934a3.png)

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/3919
