### ISSUE TITLE
Sharing calendar with groups: not working (it's working with a user)

### ISSUE THREAD

**Issue by chatlumo** [nextcloud/calendar#2985]
### Steps to reproduce
1. I share a calendar with a user, everything goes as expected.
2. I share a calendar with a group, if I refresh the calendar page, no share has been added to the group, as if there was no recorded.
3. Having done some tests, I realize that if the group name is in one word without a space, the permission is well recorded. If there is a space in the name, like "Bureau National", it doesn't persist and the sharing is not done.

Do you have any idea why?

### Expected behaviour
A calendar shared with the selected group

### Actual behaviour
The group is not persistent

### Calendar app
**Calendar app version:** 2.2.0

### Client configuration
**Browser:** Chrome 89.0.4389.90

### Server configuration

**PHP version:** 7.2.34

**Nextcloud Version:** Nextcloud 20.0.8

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/server/issues/17610 https://github.com/nextcloud/server/issues/25165
