### ISSUE TITLE
not calneder invitations possible after owncloudupdate to 9.1.2 /Thunderbird-Lightning

### ISSUE THREAD

**Issue by josbuero** [nextcloud/calendar#299]
Hello, since yesterday we were able to invite people via e-mail to our appointments out of thunderbird/lightning. It didn't mattereven if they were using ical/outlook/thunderbird/android etc.

yesterday we did the serverupdate of owncloud to version 9.1.2 and it is not working anymore
Steps to reproduce

    create aapointment
    enter adresses for invitation
    save

Expected behaviour

    thunderbird created a mesage if we would like to sendthe invitation
    thinderbird sends invitation

Actual behaviour

nothing happens after saving of new appointment, and no message is sent
in the window for new appointament in "invitation" (see screenshot) the field for "send invitation" is gray and not clickable as it was till yesterday befor the update
Server configuration

Operating system:
macSierra
Web server:
apache
Database:
mysql5
PHP version:
7
Server version: (see your admin page)
9.1.2
Calendar version: (see the apps page)
1.4.1
Updated from an older installed version or fresh install:
updated
![bildschirmfoto 2017-01-18 um 10 32 28](https://cloud.githubusercontent.com/assets/16100381/22058906/f777cb30-dd6a-11e6-9d46-dbaddbf1027e.png)

**Comment by georgehrke** [comment]
This is a problem of the ownCloud server and has nothing to do with the Nextcloud calendar app.
Please report it in the corresponding oc repo
