### ISSUE TITLE
add option to reshare subscribed calendars

### ISSUE THREAD

**Issue by ctr49** [nextcloud/calendar#3002]
**Is your feature request related to a problem? Please describe.**
As a Nextcloud user in a collaborative environment I am managing a few calendars that I also share with certain groups. The workflow is usually me managing appointments and a group of (internal & external) people using the calendar. However, some appointments have external, dynamic data sources already. Currently I have to instruct every single user to subscribe to the external data source to see the external calendar in NC. When the reference to the external calendar changes, I have to repeat this over and over which is cumbersome.

**Describe the solution you'd like**
Instead, I would like to only subscribe the external calendar once myself and then (internally & externally) share it to others through NC just like my own calendars.

**Describe alternatives you've considered**
As mentioned in the problem description I'm currently managing this manually. Importing the calendar and then sharing it is not an option as there are frequent updates in the external calendar.

**Comment by ChristophWurst** [comment]
Tracked in https://github.com/nextcloud/server/issues/1600
