### ISSUE TITLE
Time Picker empty in some cases

### ISSUE THREAD

**Issue by ksteinb** [nextcloud/calendar#3020]
### Steps to reproduce
1. Click on a date
2. Wizard for new event pops up with "all day event" active
3. unselect "all day event"
4. choose "Pick date" 

### Expected behaviour
There should be a time selectable

### Actual behaviour
Time picker is empty

### Calendar app
**Calendar app version: 2.2.0 ** (see apps admin page, e.g. 2.0.1)

This happens only if the picker is choosen from clicking on the date directly.
If you choose "New Event" in the left corner it works almost ok
It works also if you click on the date and then choose  "More"

**Comment by yan12125** [comment]
Could you check if #2983 describes your issue?

**Comment by tcitworld** [comment]
Sounds indeed like a duplicate from #2983
