### ISSUE TITLE
Import of ics causes: No valid files found, aborting import

### ISSUE THREAD

**Issue by Morodar** [nextcloud/calendar#3035]
### Steps to reproduce
I've attached a reduced ics export as an example of the calendar system (StarPlan) my university provides.

0. Download [splan.txt](https://github.com/nextcloud/calendar/files/6364290/splan.txt) and replace `.txt` with `.ics` 
1. Open https://nextcloud.mydomain.any/apps/calendar
2. Click on `Settings & Import` at the bottom left 
3. Click `Import calendar`
4. Select the `splan.ics` file 

### Expected behaviour
The ics file should be imported successfully.

### Actual behaviour
An error message shows up at the top right:
```
No valid files found, aborting import✖  
splan.ics could not be parsed✖
```
The browser console shows:
```
Error: invalid date-time value: "--T::"
@ SettingsImportSection.vue:209
```
### Note

The iCalendar Validator <https://icalendar.org/validator.html> is able to validate `splan.ics` and does not find any errors. 

### Calendar app
**Calendar app version:** 2.2.0

**CalDAV-clients used:** None

### Client configuration
**Browser:** 
- Firefox 87.0 
- Chromium 89.0.4389.114 (64-bit)

**Operating system:**

- Ubuntu 20.10
- Windows 10 Pro

### Server configuration

**Operating system**: Debian 10 buster

**Web server:** nginx/1.14.2

**Database:** MaariaDB 10.3.27

**PHP version:** 7.4.14

**Nextcloud Version:** 21.0.1

**Updated from an older installed version or fresh install:** Updated from an older installed version

**List of activated apps:**

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - audioplayer: 3.1.0
  - breezedark: 21.0.6
  - calendar: 2.2.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - polls: 1.8.1
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.1.2
  - support: 1.4.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - theming_customcss: 1.8.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - encryption
  - survey_client
  - user_ldap
```

**Nextcloud configuration:**

```
system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.2",
            "nextcloud.mydomain.any"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/nextcloud.mydomain.any",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true
    }
}

```

#### Web server error log (e.g. /var/log/apache)
```
No server side errors
```

#### Log file (data/nextcloud.log)
```
File is empty
```

#### Browser log
```
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 8 globals.js:60:15
Error: invalid date-time value: "--T::"
    fromDateTimeString ical.js:5901
    decorate ical.js:781
    _decorate ical.js:2939
    _hydrateValue ical.js:2922
    getFirstValue ical.js:3068
    value property.js:458
    value abstractComponent.js:544
    value abstractComponent.js:550
    value abstractComponent.js:550
    value calendarComponent.js:144
    value icalendarParser.js:271
    value icalendarParser.js:171
    n SettingsImportSection.vue:207
    m runtime.js:63
    _invoke runtime.js:293
    M runtime.js:118
    mo calendar.js:2
    i calendar.js:2
    promise callback*mo calendar.js:2
    i calendar.js:2
    Ao calendar.js:2
    Ao calendar.js:2
    processFiles SettingsImportSection.vue:157
    VueJS 33
SettingsImportSection.vue:209
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 264 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 248 globals.js:60:15
```

**Comment by mmetzler1** [comment]
I can confirm the error.
I have installed Nextcloud 20.0.11 - 20.0.11.1
and an test.ics file (300 entries) fails showing 0 from 1 imported.
Google imports the same test.ics file without problems (all entries).
If there is a log file to help - please name what file you need.

**Comment by mmetzler1** [comment]
here the nextcloud.log (only the last part of the message...):
SUMMARY:TG13-2 ET \r\nDTSTART:20220726T112000\r\nDTEND:20220726T125500\r\nDESCRIPTION:FALSCH\r\nLOCATION:R???\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nSUMMARY:TG11 SOTE \r\nDTSTART:20220727T135000\r\nDTEND:20220727T152500\r\nDESCRIPTION:FALSCH\r\nLOCATION:R140\r\nEND:VEVENT\r\nEND:VCALENDAR",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php","Line":885,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"20.0.11.1"}

**Comment by miku86** [comment]
Do you have `EXDATE` lines in your `ICS` file?

There is an [existing issue](https://github.com/nextcloud/calendar/issues/1553) about this. After removing the `EXDATE` lines, it works for me. But the calendar is messed up.

**Comment by Morodar** [comment]
> Do you have `EXDATE` lines in your `ICS` file?

The example [splan.txt](https://github.com/nextcloud/calendar/files/6364290/splan.txt) does not contain `EXDATE`.

**Comment by marcelmu** [comment]
I'm facing the same issue, even without the EXDATE Line. 

The ICS I'm trying to import:

`BEGIN:VCALENDAR
PRODID:QIS-LSF HIS eG
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
METHOD:PUBLISH
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20211007T121500
DTEND;TZID=Europe/Berlin:20211007T153000
RRULE:FREQ=WEEKLY;UNTIL=20220210T235900Z;INTERVAL=2;BYDAY=TH
LOCATION:****
DTSTAMP:20210929T072151Z
UID:177191462092
DESCRIPTION:
SUMMARY:****
CATEGORIES:****
END:VEVENT
END:VCALENDAR`

**Comment by AyupMike** [comment]
Same here - even with a simple example `.ics` import I can't get it to work.

Tested on the NextCloud demo server also with no joy:

```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
METHOD:PUBLISH
BEGIN:VEVENT
CREATED:20100728T172127Z
LAST-MODIFIED:20180206T151726Z
DTSTAMP:20191006T184832Z
UID:M2CD-7BFB1C3D-89BB-46A6-9B25-35D5045BF7C5
SUMMARY:Meeting
STATUS:CONFIRMED
DTSTART:20090615T103000Z
DTEND:20090615T123000Z
DESCRIPTION:Meeting with Steven
END:VEVENT
BEGIN:VEVENT
CREATED:20100728T172127Z
LAST-MODIFIED:20180206T151726Z
DTSTAMP:20191006T184832Z
UID:M2CD-705A3DD1-8B37-4471-B805-7D132DC9A351
SUMMARY:Christmas
STATUS:CONFIRMED
DTSTART:20091126T170000Z
DTEND:20091126T210000Z
END:VEVENT
END:VCALENDAR
```

**Comment by tcitworld** [comment]
@marcelmu @AyupMike Both of your ics data import correctly in latest versions and have nothing to do with the original issue. Make sure you empty the trashbin before retrying.

For the original issue, this is caused by the invalid empty lines like
```
RDATE:
```

The https://icalendar.org/validator shouldn't mark it as valid, the line can't be empty as per https://github.com/mozilla-comm/ical.js/issues/462 https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.5.2

@Morodar Please report the issue to the calendar software vendor, as it seems the same issue currently also happens on their demo server: https://www.progotec.de/starplan/mobile

**Comment by Morodar** [comment]
@tcitworld Thanks for the investigation!

I wrote an mail to progotec and a mail to icalendar.org about this topic.

**Comment by Morodar** [comment]
I got a response. Progotec confirmed the bug (due to a old ical4j) and will fix it in the next release.
