### ISSUE TITLE
XPathResult not defined on IE based browsers

### ISSUE THREAD

**Issue by joekir** [nextcloud/calendar#304]
### Steps to reproduce
1.  Visit the Calendar in Internet Explorer 11
2. The background JavaScript errors, spinners run indefinitely, for the user it looks as though the Calendar is not loading.

### Expected behaviour
Calendar should load (verified in latest Chromium and Firefox) 

### Actual behaviour
Error thrown from line 278 of
/js/vendor/davclient.js/lib/client.js

`XPathResult is not defined.`

It will be thrown from other locations in this file too. Wherever `XPathResult.ANY_TYPE` is used.

### Server configuration
**Server version:** (see your admin page)
Nextcloud 11.0.1 (stable)

**Calendar version:** (see the apps page)
1.5.0

### Client configuration
**Browser:**
Internet Explorer 11
version: 11.0.9600.18538

**Operating system:**
Microsoft Surface RT

**Comment by joekir** [comment]
It would be great if the fix is as trivial as replacing `XPathResult.ANY_TYPE` with `0` for Microsoft based browsers. (see https://developer.mozilla.org/en-US/docs/Web/API/XPathResult)

**Comment by georgehrke** [comment]
It's not just a matter of `XPathResult`, IE doesn't support `XPath` at all.

IE is not supported (see https://github.com/nextcloud/calendar#supported-browsers)

**Comment by joekir** [comment]
My user can only use IE as the windows store on that device does not provide other browser implementations. (Not your problem, just giving a user story context)

@georgehrke So my question, are client side DOM features the reason why IE is not supported, or is there more to it? It seemed that the other apps functioned without issue on IE when I tested yesterday.

If its the XPath implementation perhaps a polyfiller approach like https://github.com/google/wicked-good-xpath could be suitable?

**Comment by georgehrke** [comment]
- XPath doesn't work
- Promises don't work
- writing CSS that works in IE is a real pain. (Edge actually does a decent job)
- it doesn't support `Array.from` 
- We use a few ES6 features that are not transpiled by Babel 
  - ES6 support sucks in IE (https://kangax.github.io/compat-table/es6/#ie11) 

and finally at some point (rather sooner than later) we want to get rid of babel, because a few important things can't be transpiled properly.

**Comment by tcitworld** [comment]
Can't your users use Microsoft Edge ?

**Comment by georgehrke** [comment]
Maybe check if you can find CalDAV plugins for outlook that work with Windows RT. That's probably the best solution for your user imho.

**Comment by georgehrke** [comment]
> Can't your users use Microsoft Edge ?

Just checked, Edge is only Windows 10+ and not Windows 8 RT

**Comment by tcitworld** [comment]
> Maybe check if you can find CalDAV plugins for outlook that work with Windows RT. That's probably the best solution for your user imho.

https://nextcloud.com/blog/nextcloud-offers-caldav-synchronizer-for-outlook-users/

> Just checked, Edge is only Windows 10+ and not Windows 8 RT

Then the only choice is to upgrade. Even Microsoft will drop Windows 8 at some point.

**Comment by joekir** [comment]
@tcitworld Unfortunately WinRT is a "walled garden" so users can't install arbitrary binaries such as the one in the sychronizer post.

I think the best approach for this user will be to use a CalDAV on their phone and just avoid usage on WinRT. 

Thanks for the suggestions!
