### ISSUE TITLE
Nextcloud Calendar Newsletter | Email Notifications

### ISSUE THREAD

**Issue by aheider** [nextcloud/calendar#3046]
Dear community,
just wanted to inform you that there is a great NC app which interfaces with NC Calendar and creates Email newsletters from Nextcloud calendars:
[https://github.com/mziech/nextcloud-calendar-news](Nextcloud Calendar News)

The author does not want to go through the hassles of adding it to the NC app store. It works on NC20, other I did not test.

Maybe this functionality can be incorporated into main NC Calendar app somehow?

**Comment by tcitworld** [comment]
It definitely belongs in a dedicated app. This calendar app is only a caldav client, and shouldn't do direct database accesses like this app is doing.
