### ISSUE TITLE
Send an email with an overview of upcoming events

### ISSUE THREAD

**Issue by basti1982** [nextcloud/calendar#3047]
Similar to the functionality in Google Calendar, where you can setup a daily email with today's events, it would be nice if an user could receive an email in a configurable interval with upcoming events of an selected period. This should be configurable for each calendar. For example:

- Send an email every day at 8:00 am with the events of the current day
- Send an email every Monday at 7:00 am with the upcoming events for the current week

**Comment by tcitworld** [comment]
See #3046, this doesn't belong to this app, but it would be fine in another app.
