### ISSUE TITLE
Add view (month/week/day) switch buttons (in general datepicker)

### ISSUE THREAD

**Issue by keunes** [nextcloud/calendar#3048]
**Is your feature request related to a problem? Please describe.**
I usually use the month view. Just now I tried opening the week view to have more details. However, I don't see any way to get back to the month view. I searched the settings (bottom left) and through there discovered the shortcuts. However, that's not really easy to discover.

**Describe the solution you'd like**
When clicking on the date selector (top left), have three buttons/indicators below the calendar that allow to quickly switch the view: month / week / day.

**Describe alternatives you've considered**
Adding a dropdown menu in the Settings, but that's not very discoverable either, and isn't as intuitive (it's not really a setting, because views can be switched by clicking e.g. on week or day number.

**Additional context**
n/a

**Comment by raimund-schluessler** [comment]
The view selection is at the top left.

<img width="253" alt="Screenshot_2021-04-29 April 2023 - Kalender - Nextcloud" src="https://user-images.githubusercontent.com/2496460/116597853-68617180-a926-11eb-8a87-b647f2546718.png">

**Comment by keunes** [comment]
Hah, thanks! For me it displayed this:
![afbeelding](https://user-images.githubusercontent.com/11229646/116598687-6d72f080-a927-11eb-95dd-a749343a382c.png)
After a force refresh, it shows again.
Sorry for the noise.
