### ISSUE TITLE
calendar app - subscription (ics) not syncronised

### ISSUE THREAD

**Issue by mhoeppner-le** [nextcloud/calendar#3049]
Hello,
in a calendar from a subscription *.ics the continuous syncronisation does not work.
If I establish the calendar via the ics link, it is reading all calendar data in a correct way.
However if there are any changes in the original calendar - in my case on https://www.supersaas.de with a link like webcal://www.supersaas.de/info/webcal/xxxxx.ics - it will not be reflected in the nextcloud calendar.
If I make a new subscription for the SAME link, all new data are shown!
Where is the mistake here?
BR Matthias

**Comment by tcitworld** [comment]
Subscriptions in the Nextcloud calendar app are cached for one week. https://docs.nextcloud.com/server/21/user_manual/en/pim/calendar.html#subscribe-to-a-calendar
Admins can change the refresh rate if needed: https://docs.nextcloud.com/server/21/admin_manual/groupware/calendar.html#refresh-rate

**Comment by Polyknikes** [comment]
I have the same problem with my nextcloud. The subscription calendars add correctly but never refresh after initially being added. Did you ever find a solution to this problem? The above answer regarding changing the refresh rate did not work for me, but I am also using the HanssonIT VM version of nextcloud so its possible there is a confounding factor.

**Comment by mhoeppner-le** [comment]
php occ config:app:set dav calendarSubscriptionRefreshRate --value "P1D"
worked for me,
we set the value to P1H, means refresh every (1) hour,
Check the following site for possible values (link from the site above):
[https://www.php.net/manual/de/dateinterval.construct.php](url)

**Comment by Polyknikes** [comment]
This will reveal what a newbie I am, but when I enter that command I get "Could not open file php". Am I not doing this from the right environment?

Thanks

**Comment by mhoeppner-le** [comment]
I'm not sure here too (for work on the console I have to read a lot in the net ... :-))
But you have to be inside the folder, where the occ data is in. Currently I do not remember where it is but you will find it - ie. use "find".

**Comment by ChristophWurst** [comment]
Please see https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html or consult https://help.nextcloud.com/ :)
