### ISSUE TITLE
Weird info in reminder tab

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/calendar#3054]
### Steps to reproduce
1. Create an event
2. Open reminder tab
3. 
```
BEGIN:VALARM
ACTION:NONE
TRIGGER;VALUE=DATE-TIME:19760401T005545Z
X-WR-ALARMUID:52FE17B4-B4AD-4E07-B817-B64D6CA173C6
UID:52FE17B4-B4AD-4E07-B817-B64D6CA173C6
X-LIC-ERROR;X-LIC-ERRORTYPE=PROPERTY-PARSE-ERROR:Parse error in property na
 me: ACKNOWLEDGED
END:VALARM
```

### Expected behaviour
Shows beautiful info

### Actual behaviour
![Bildschirmfoto von 2021-05-03 09-31-24](https://user-images.githubusercontent.com/213943/116852225-35540200-abf4-11eb-8c99-75e34547b3d2.png)
* Shows `{timezoneId}` placeholder
* Shows something about the year 1976 where neither the calendar, nor a user nor the event existed.

### Calendar app
**Calendar app version:** 2.2.0

**CalDAV-clients used:** Viewed in Web, added via "Mozilla Calendar"?

### Client configuration
**Browser:** FF 88

**Operating system:** Ubuntu 20.04 LTS

### Server configuration

**Nextcloud Version:** 21.0.1

**Updated from an older installed version or fresh install:** Installed with 9.0

**Comment by tcitworld** [comment]
The event was created in the web calendar app or somewhere else ? There's a lot of different proprietary prefixes here : `X-WR` is Microsoft, `X-LIC` seems to be Lightning ?

**Comment by ChristophWurst** [comment]
`PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN`

**Comment by miaulalala** [comment]
Can't reproduce, also, we don't have a reminder tab any more
