### ISSUE TITLE
Can't set timezone

### ISSUE THREAD

**Issue by jvasile** [nextcloud/calendar#3056]
### Steps to reproduce
1. Open calendar
2. See warning about setting timezone
3. Look for place to set current time zone and default tz for new events.  It doesn't exist.

### Expected behaviour
There should be a way to set my timezone so it displays all the events in that tz.  Also so that when I add an event the timezone is already set. 

Also, the warning text should provide instructions on where to look to set this timezone.  Maybe it should even take advantage of the fact that it's part of a web browser UI and provide a link.

### Actual behaviour
I just kind of stare at the screen and wonder about the state of the world.  What even is a timezone anyway?

(Also, the tz picker failed when adding a new event.  I "type to search timezone", pick one and when I click to "Please select timezone" it just takes me back to "type to search timezone")

### Calendar app
**Calendar app version:** 2.2.1

**CalDAV-clients used:** None

### Client configuration
**Browser:** Firefox 88

**Operating system:** Linux

### Server configuration

**Operating system**: Debian

**Web server:** None

**Database:** Postgres

**PHP version:** Whatever your docker image installs as of today

**Nextcloud Version:** 21.0.1

**Updated from an older installed version or fresh install:** Fresh

**List of activated apps:** 
 Accessibility
1.7.0
Featured
Activity
2.14.3
Featured
Calendar
2.2.1
Featured
Circles
0.21.1
Featured
Collaborative tags
1.11.0
Featured
Comments
1.11.0
Featured
Contacts Interaction
1.2.0
Featured
Dashboard
7.1.0
Featured
Deleted files
1.11.0
Featured
Federation
1.11.0
Featured
File sharing
1.13.1
Featured
First run wizard
2.10.0
Featured
Group folders
9.0.1
Featured
Log Reader
2.6.0
Featured
Monitoring
1.11.0
Featured
Nextcloud announcements
1.10.0
Featured
Notifications
2.9.0
Featured
Password policy
1.11.0
Featured
PDF viewer
2.1.0
Featured
Photos
1.3.0
Featured
Privacy
1.5.0
Featured
Recommendations
1.0.0
Featured
Right click
1.0.0
Featured
Share by mail
1.11.0
Featured
Social sharing via email
2.2.0
Featured
Social sharing via Twitter
2.2.0
Featured
Support
1.4.0
Featured
Text
3.2.0
Featured
Theming
1.12.0
Featured
Update notification
1.11.0
Featured
Usage survey
1.9.0
Featured
User status
1.1.1
Featured
Versions
1.14.0
Featured
Video player

**Comment by miaulalala** [comment]
Fixed
