### ISSUE TITLE
empty time selection list

### ISSUE THREAD

**Issue by KarlEffinger** [nextcloud/calendar#3074]
Hi Community!
Since a while I am experiencing the following problem:
When I set up a new date in the calendar, the flag "all day event" ('Ganztägig') is set. If I then uncheck this, click into the date-and-time field and then click on the "choose time" ('Zeit auswählen') button, the list is empty:
![grafik](https://user-images.githubusercontent.com/26634326/117789550-be001d00-b248-11eb-8f91-8879bcdbcfa1.png)

**Calendar app version: 2.2.1
**Browser: Firefox 88.0.1
   Microsoft Edge 44.18362.449.0
**Operating system: Win10 Pro

### Server configuration
**Operating system: NextcloudPi
**Nextcloud Version: 20.0.8

**Comment by tcitworld** [comment]
Duplicate from #2983 (fixed in upcoming release).
