### ISSUE TITLE
WebDAV

### ISSUE THREAD

**Issue by m1l4n89** [nextcloud/calendar#3076]
Hi,
I'm testing this app, but I'd like to attach a calendar from a mail server.

I found the option to add a calendar via iCal. But I would need to attach a writable calendar via WebDAV.

You are planning to add this features ?

Thank you in advance for your reply

**Comment by tcitworld** [comment]
What do you mean *attach* ? Subscribe to a calendar ics file accessible through WebDAV?

If the issue is http auth, see #70
