### ISSUE TITLE
Sharing calendars with LDAP groups fails, if LDAP is organized in multiple organizational units

### ISSUE THREAD

**Issue by c-schwamborn** [nextcloud/calendar#3077]
I assume a configured and working ldap connection for users and groups.
Let me point out here that I can see all goups and can use them as well in other aspects of the nexcloud, such as filesharing.
We need those department structures for management delegation and other organizational purposes.

### Steps to reproduce
1. create a first ldap group at `cn=testgroup1,ou=groups,dc=domain,dc=priv`
2. create a second ldap group at `cn=testgroup2,ou=groups,ou=departmentx,dc=domain,dc=priv`
3. create a calendar and share it with both groups (they are both visible and selectable)
4. log out and in again, or switch to any other nc app like 'files'
5. go back to calendars

### Expected behaviour
I would assume for the calendar to be shared with both goups.

### Actual behaviour
The calendar is still shared with `testgroup1`, but `testgroup2` residing in `departmentx` is gone from the list of shared groups/users. All groups in `ou=groups,dc=domain,dc=priv`will work, but everything in other organizational units disappears after any other operation.

### Calendar app
**Calendar app version:** 2.2.1

**CalDAV-clients used:** doesn't matter here

### Client configuration
**Browser:** Firefox 86

**Operating system:** Debian Linux (Bullseye)

### Server configuration

**Operating system**: Debian Buster

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 21.0.1

**Updated from an older installed version or fresh install:** fresh install

**List of activated apps:**
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.1
  - circles: 0.21.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.4.2
  - documentserver_community: 0.1.9
  - drawio: 1.0.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.11.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - forms: 2.2.4
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - notify_push: 0.1.7
  - oauth2: 1.9.0
  - onlyoffice: 6.3.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - polls: 1.8.3
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.1.2
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - encryption

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.some-university.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.some-university.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "default_phone_region": "DE",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}

### Logs
during those operations there wasn't any log entry regarding those issues

**Comment by islamadel** [comment]
SAME ISSUE HERE: i can select a nested ldap group for sharing in the calendar, but it doesn't get applied. when i change the page and open the calendar again, the sharing gets removed for that group.

**Comment by c-schwamborn** [comment]
This issue disappeared finally after upgrading to Nextcloud 21.0.4 and it's current apps but i don't know specifics about what code changes/fixes are responsible for that change in behaviour. Sadly no one with insight of the code ever responded to this issue or documented the corresponding patch id.

**Comment by islamadel** [comment]
The issue has been fixed by the version 21.0.4 for the Calendars only. Issue still exists for Contacts!

**Comment by c-schwamborn** [comment]
Thanks for reopening the issue, I actually didn't test this with contacts.

**Comment by miaulalala** [comment]
Since there's an existing ticket for Contacts I'm closing this as it was fixed
