### ISSUE TITLE
Line between today and tomorrow is missing in Firefox

### ISSUE THREAD

**Issue by MicRaving** [nextcloud/calendar#3090]
In the week view, the line separating today and tomorrow is gone in the newest version of the calendar. Reproducable in Firefox. Not reproducable in Edge.
![Screenshot 2021-05-18 105519](https://user-images.githubusercontent.com/7791810/118622542-b4863000-b7c7-11eb-8ac2-ae2646a98389.jpg)

**Comment by st3iny** [comment]
This applies to the month view too:
![Bildschirmfoto von 2021-06-01 10-51-34](https://user-images.githubusercontent.com/1479486/120295562-888aa480-c2c7-11eb-91db-ee451c13996f.png)

**Comment by st3iny** [comment]
The lines are back in the newest version of Firefox (v89). @MicRaving Could you test again?

**Comment by raimund-schluessler** [comment]
> 
> 
> The lines are back in the newest version of Firefox (v89). @MicRaving Could you test again?

It's still an issue for me with Calendar 2.2.2 and Firefox v89.0.

![Screenshot 2021-06-08 at 13-40-05 Juni 2021 - Kalender - Nextcloud](https://user-images.githubusercontent.com/2496460/121178712-1e41a900-c85f-11eb-92d0-3449dc24ac80.png)

**Comment by st3iny** [comment]
This is very strange. The lines are shown on my production (NC v21, Calendar v2.2.2) and testing instance (NC and Calendar master) with Firefox v89.0. However, they have very bad contrast and are hard to see.

I tested https://github.com/nextcloud/calendar/pull/2971 and the lines were solid again.

## Before
![Screenshot 2021-06-11 at 10-00-20 June 2021 - Calendar - Nextcloud](https://user-images.githubusercontent.com/1479486/121652551-0c991500-ca9c-11eb-935a-ba97e6d94503.png)

## After
![Screenshot 2021-06-11 at 10-00-36 June 2021 - Calendar - Nextcloud](https://user-images.githubusercontent.com/1479486/121652567-115dc900-ca9c-11eb-8128-18c5a854a5a9.png)

**Comment by st3iny** [comment]
Fixed by https://github.com/nextcloud/calendar/pull/2971.
