### ISSUE TITLE
Show attendance state for resources to reflect iCal properties

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#3100]
In the iCal file, the following line that is produced for resources' attendance states should be reflected in the UI:

`ATTENDEE;CN=ConfRoom2;CUTYPE=ROOM;PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT;SC`

The state can also be `DECLINED`. 

After a reload of the calendar overview the page displays correctly.

TO DO:

- [ ] Add a poll for the resource state each time the sidebar opens

**Comment by ChristophWurst** [comment]
> Add a poll for the resource state each time the sidebar opens

And also when the event is saved. Resources are scheduled immediately by the server. This state should be reflected.
