### ISSUE TITLE
Time selection options not showing for new event creation

### ISSUE THREAD

**Issue by lowellfriesen** [nextcloud/calendar#3106]
When I attempt to create a new event by clicking on a date on the calendar itself, the options to select a time for the event do not appear.

**My environment**

OS: Ubuntu 20.04
Browser: Firefox and Chrome
Nextcloud version: 21.0.2
Calendar version: 2.2.1

**Description of Issue**

When accessing the calendar in a browser, event creation via clicking on a date in calendar behaves differently than when clicking on "+ New Event" in the top left-hand corner.

_Clicking on + New Event_

Clicking on the date/time box opens a mini calendar.  Clicking on a date in the mini calendar, opens a window with options to select hour, minute, and AM/PM.  This is the expected behaviour that is absent from event creation as described next.

_Clicking on date in main calendar_

Clicking on the date/time box again opens a mini calendar.  However, clicking on a date in the mini calendar, only opens a window with options to select AM/PM. The options to select hour and minute do not appear.

**Comment by tcitworld** [comment]
Duplicate from #2983, fixed in next version.
