### ISSUE TITLE
Separate language and date format settings

### ISSUE THREAD

**Issue by mortie** [nextcloud/calendar#311]
Hey,

Nextcloud's calendar app currently determines what date format to use from your language. However, lots of people want to use Nextcloud with English language without American date format settings. I, for example, vastly prefer using most software in English, but would rather have either Norwegian or ISO-8601 date formatting. There's also many countries with different date format rules than the US, but where most of the population speak English. Please consider separating the language setting from the date format setting.

I'm sorry for ignoring the issue template, but most of it seemed to be irrelevant, since this isn't a bug but rather an issue with the design.

**Comment by georgehrke** [comment]
closing in favor of https://github.com/nextcloud/server/issues/1781
