### ISSUE TITLE
Long text in Settings & Import section overlaps sidebar

### ISSUE THREAD

**Issue by cappuMUC** [nextcloud/calendar#3111]
### Steps to reproduce
1. Set interface language to German
2. Open Calendar app
3. Expand "Einstellungen & Import" in the left sidebar

### Expected behaviour
All shown text should be within the boundaries of the sidebar

### Actual behaviour
Long text overlaps the sidebar
![grafik](https://user-images.githubusercontent.com/9985266/119655957-6d80e600-be2a-11eb-867d-6240bc035553.png)

### Calendar app
**Calendar app version:** 2.2.1

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:** Tested on Firefox 88.0.1 and Chrome 86.0.4240.111

**Operating system:** Ubuntu 20.04

### Server configuration

**Nextcloud Version:** 21.0.2

**Comment by tcitworld** [comment]
Is there a shorter version of the string that would work better?

https://github.com/nextcloud/calendar/issues/2304 will help avoid such things.

**Comment by cappuMUC** [comment]
> Is there a shorter version of the string that would work better?
> 
> #2304 will help avoid such things.

It may help to change the "pro Ansicht" to "pro Tag" as in my experience the setting only affects the month view. Nonetheless #2304 would be the better option.

**Comment by miaulalala** [comment]
Fixed
