### ISSUE TITLE
Today button/link not working when the translation for it is too long

### ISSUE THREAD

**Issue by kaksikanaa** [nextcloud/calendar#312]
Today button/link is not working / is in the wrong row when the translation for it is too long. Please see the attached image of the current behaviour.

### Steps to reproduce
1. Fresh install of Nextclud 11.0.2
2. Fresh install of the default calendar app
3. User using language where the "Today" word is longer then 5 characters like in finnish "Tänään" which is 6 characters long
![capture2](https://cloud.githubusercontent.com/assets/15322015/22174797/56c3ee4e-dfef-11e6-93c4-614e972154c2.png)

### Expected behaviour
The link / button should be it is default row/line with other links / buttons

### Actual behaviour
Today button falls one row/line below other and it not working, when you click the button it only shows add new calendar dialog.

### Server configuration
Debian Jessie
Apache 2.4
Mysql 5.7
PHP 5.6

Nextclud 11.0.2 (Fresh install)
Calendar 1.5.0 (Just activated the app from the apps page)
Admin page passes all checks ok.

**Comment by georgehrke** [comment]
<img width="272" alt="calendar - nextcloud chromium today at 3 59 18 pm" src="https://cloud.githubusercontent.com/assets/1250540/22596019/15a92024-ea2a-11e6-9c4e-f5de08515a27.png">

This layout should work for locales with long translations, but sadly also creates too much whitespace on locales with short translations.

Maybe we can use the current layout as default and if the translations are too long, use the layout from the screenshot. I thinks some flexbox magic should do the trick.

cc @eppfel @jancborchardt

**Comment by georgehrke** [comment]
@skjnldsv Is this possible with flexboxes?

**Comment by skjnldsv** [comment]
@georgehrke It should! Do you want me to make a pr?

**Comment by georgehrke** [comment]
That would be awesome :) 

So, the current one line layout for short translations and the two line layout for long translations :)

**Comment by skjnldsv** [comment]
You got it!

**Comment by eppfel** [comment]
I think the solution is an improvement, so :+1: But we could also think about icons. They might not be directly decoded by the user, but I feel the navigation could be a little cleaner.

Ans could we make the left, right and datepicker button a button group, just like day, week and month?

**Comment by georgehrke** [comment]
I think something like this would be very intuitive, but would require rather large icons: ![](https://i.stack.imgur.com/2HN7V.png)

Alternatively there is this concept:
![](https://camo.githubusercontent.com/79fbbe14a0695e740489cf6d35b9e405ad15f438/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3333383838352f3539363936302f65356336323335612d636263622d313165322d386433372d6366633034346563666535392e706e67)

But it's definitely harder to parse.

**Comment by eppfel** [comment]
I like how Google mimics the change in layout in the their Android calendar app:

![screenshot_20170207-191312](https://cloud.githubusercontent.com/assets/1899308/22704898/aa0264e6-ed69-11e6-8884-d40932e7849a.png)

And for the today icon the current date, yes.

**Comment by skjnldsv** [comment]
God I love minimal design!
We need a different icon for Week though :)

**Comment by jancborchardt** [comment]
As for the space constraints, we could do a dropdown for the view instead of a radiobutton set. Showing the current view, and clicking on it reveals the other options in a popdown menu just like for the file actions. Then next to it would be the »Today« button.

That way we can show the icon and the text next to it also.

**Comment by georgehrke** [comment]
Hm, I'm not so sure about that tbh. I think changing the view happens too often to force the user to make 2 clicks instead of 1.

**Comment by jancborchardt** [comment]
Ok, I mean making the Today button full width is also fine. :)

**Comment by kaksikanaa** [comment]
Thank you all for this fix, it works nicely!
