### ISSUE TITLE
Calendar broke Nextcloud

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/calendar#3120]
### Steps to reproduce
1. Add a few day events in previous weeks all with an invite to someone
2. Note that Nextcloud stops responding (504); even restarting Nextcloud and the whole server doesn't bring Nextcloud back up
3. `occ:disable calendar` and Nextcloud works again (and Calendar also works again when I run `occ:enable calendar`)

### Expected behaviour
- Adding events without an error
- and in the case of an error to not crash the whole Nextcloud instance
- and in the case of crashing the whole of Nextcloud to at least don't crash Nextcloud after a restart of Nextcloud

### Actual behaviour
All Nextcloud URLs give a 504

### Calendar app
**Calendar app version:** 2.2.2

### Client configuration
**Browser:** Firefox 88.0.1

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Nginx 1.21.0

**Database:** PostgreSQL 12.7

**PHP version:** 7.4.19

**Nextcloud Version:** 21.0.2

#### Log file (data/nextcloud.log)
I looked at the logs but there were no logs coming from the Calendar app. Any ideas how I can help to find out what happened?

**Comment by tcitworld** [comment]
> I looked at the logs but there were no logs coming from the Calendar app.

The calendar app is only a CalDAV client, the immense majority of the logic (including sending invitations) happens in the server, so I'd say your fix would only be a side effect.

The only tip I can give is having a look at the rest of the logs, sorry.

**Comment by siccovansas** [comment]
@tcitworld thanks for your response! I found a couple of logs like this:

`{"reqId":"***","level":1,"time":"2021-05-28T14:38:03+00:00","remoteAddr":"***","user":"***","app":"no app in context","method":"PUT","url":"/remote.php/dav/calendars/***/***/***.ics","message":"Deprecated event type for \\OCA\\DAV\\CalDAV\\CalDavBackend::updateCalendarObject: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","version":"21.0.2.1"}`

Is this relevant?

**Comment by tcitworld** [comment]
No, that's only some depreciated stuff notices.

**Comment by siccovansas** [comment]
Ok thanks :)!

I guess I won't be able to give more info, so I'll close this.
