### ISSUE TITLE
Request: contact birthdays color change

### ISSUE THREAD

**Issue by Peque** [nextcloud/calendar#313]
It seems that currently it is not possible to change the contact birthdays event color in the calendar. You can do that, however, with other calendars, using the "Edit" button:

![screenshot from 2017-01-21 21-13-25](https://cloud.githubusercontent.com/assets/526577/22177482/af1d51c8-e01e-11e6-92df-62f8afc35a4f.png)
![screenshot from 2017-01-21 21-13-17](https://cloud.githubusercontent.com/assets/526577/22177485/b86fb090-e01e-11e6-95f6-db68d2c2ef5d.png)

Which is missing in contact birthdays:

![screenshot from 2017-01-21 21-13-44](https://cloud.githubusercontent.com/assets/526577/22177475/a63a3652-e01e-11e6-9c01-25f6a3b75c40.png)

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/2965
