### ISSUE TITLE
Sidebar event actions menu is not aligned with the input element

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3137]
![Bildschirmfoto von 2021-06-01 17-54-17](https://user-images.githubusercontent.com/1374172/120354136-80038f80-c302-11eb-8519-3ddbb267dfa3.png)

Both elements should be leveled.

**Comment by ChristophWurst** [comment]
@GretaD ticket for you possibly? :)

**Comment by raimund-schluessler** [comment]
This comes from the vue components and it is like this for ages. So not really a regression I would say. @skjnldsv
