### ISSUE TITLE
Vertical bars are almost invisible in week view

### ISSUE THREAD

**Issue by claell** [nextcloud/calendar#314]
At first I thought there are no vertical bars at all, but they are only not really visible. This makes it harder to read the calendar when there are not many events.
![bildschirmfoto vom 2017-01-22 22-09-45](https://cloud.githubusercontent.com/assets/6171135/22186023/c05d66d6-e0ef-11e6-82ee-9c27ec1b0ad6.png)

**Comment by georgehrke** [comment]
cc @nextcloud/designers @jancborchardt

**Comment by georgehrke** [comment]
@claell What version are you on? (both Nextcloud and calendar versions)

**Comment by claell** [comment]
Nextcloud version 11.0.1, calendar 1.5.0

**Comment by eppfel** [comment]
I would need to see some proposals for comparison. Not a big issue IMO, but, yes vertical bars could be stronger than horizontal ones.

**Comment by claell** [comment]
Just checked on another monitor and there the lines are better visible, but also could be stronger.

**Comment by jancborchardt** [comment]
The vertical bars could be exactly colored like the stronger horizontal bars, but no stronger.

**Comment by claell** [comment]
@jancborchardt I think this is already the case currently.

**Comment by jancborchardt** [comment]
Yeah, so I think it’s proper. The horizontal bars to delineate the time are more important because it’s smaller steps. Weekdays are very wide already so easier to distinguish. If the vertical bars would be darker they would take precedence over the horizontal ones, which is wrong.

**Comment by claell** [comment]
Then I suggest to make both darker and/or stronger.
A few mockups:
Darker lines:
![c05d66d6-e0ef-11e6-82ee-9c27ec1b0ad62](https://cloud.githubusercontent.com/assets/6171135/22249114/f6d4e6d2-e241-11e6-8289-d1817b1727f7.png)

I did a quick research how this is handled in analog calendars and they often use a different vertical delimiter:
![c05d66d6-e0ef-11e6-82ee-9c27ec1b0ad61](https://cloud.githubusercontent.com/assets/6171135/22249113/f5d36fc4-e241-11e6-85ad-e141b1c5fd1b.png)
![c05d66d6-e0ef-11e6-82ee-9c27ec1b0ad612](https://cloud.githubusercontent.com/assets/6171135/22249115/f7c57c0a-e241-11e6-8c5d-e6d12a5f1723.png)

**Comment by eppfel** [comment]
Nice work :+1:

Kind of like the gaps approach, but I don't believe it fits the nextcloud look. Would need to see it with context.

Maybe do not interrupt the horizontal separater between all-day- and not-all-day events? 🤔 

And can you try, the idea of @jancborchardt making it just the same width as the horizontal separater?

**Comment by claell** [comment]
I did some more mockups showing them in context and without interrupting the horizontal separator.

As I am using only an image manipulation program it is hard to modify width.
But I just had a closer look and it seems @jancborchardt was right. The width of both horizontal and vertical lines are equal (1px) and only the color is different.

![mockup 1](https://cloud.githubusercontent.com/assets/6171135/22254226/404a6118-e254-11e6-9c6a-824b0ffed271.png)
![mockup 2](https://cloud.githubusercontent.com/assets/6171135/22254232/419a70bc-e254-11e6-9112-1533051d3ab3.png)

Darker:
![mockup 3](https://cloud.githubusercontent.com/assets/6171135/22254233/42a4a0fe-e254-11e6-936b-972b375678c1.png)
![mockup 4](https://cloud.githubusercontent.com/assets/6171135/22254236/43bf70ea-e254-11e6-96f8-dae29b21c767.png)

**Comment by jancborchardt** [comment]
Great stuff @claell! :) I really like the vertical separation via whitespace (also in the header) and I think it fits our style of showing less and using whitespace rather than additional lines.

Do you want to start a pull request with that? :) By the way, I also added you to the designers team, so welcome! :tada:

**Comment by claell** [comment]
Thanks :)

I have almost no experience with js or webdesign unfortunately, so I don't know how to achieve what I have mocked up.

Also I don't know how to test the changes afterwards.

**Comment by jancborchardt** [comment]
@claell this actually is a very good starter issue to get into CSS I would say. :) Just right-click the calendar in your browser and inspect it. There should be some border-right or border-left attributes in the CSS you can set to `none` to make the border go away. Then you can use padding-left and padding-right on each of the td elements to achieve the whitespace.

If you need more help, us @nextcloud/designers are glad to support you and help you get involved! :)

**Comment by claell** [comment]
I played around a bit with the inspector yesterday but didn't find the right things to change.

I managed to remove the horizontal borders, but I don't get the vertical lines "cut".

**Comment by eppfel** [comment]
@claell The layout is a bit cheated. I had a quick look at it yesterday. There is one table overlaying the other. You have to edit both of them.

**Comment by claell** [comment]
But I think I cannot change the space between horizontal borders with padding, as this is just resizing the borders around the content afaik: http://stackoverflow.com/questions/339923/set-cellpadding-and-cellspacing-in-css/10994718#10994718

**Comment by georgehrke** [comment]
@claell @jancborchardt @eppfel How do we want to proceed here? :)

**Comment by jancborchardt** [comment]
As far as I can see the horizontal lines are darker. :) Made in a PR some weeks ago I think.

**Comment by Dennis1993** [comment]
#421 Maybe this is a improvement? I changed the color a little bit

**Comment by claell** [comment]
Sorry for late reply. As I told before, I did not know how to implement the mockups I created. So if nobody else is trying to do this, I guess what #421 does is fine.
