### ISSUE TITLE
Auto detect times information in titles

### ISSUE THREAD

**Issue by raphaelbastide** [nextcloud/calendar#3143]
It would be great to parse event’s titles for time information. With such a feature, a title would be sufficient to autofill the hour details and that would save a lot of time for advanced users. I think google calendar does that.

Some examples:
- Title = "Meeting with Elen at 10" => fills the event to 10:00
- Title = "School 7am to 4pm" fills the event from 7am to 4pm
- Title = "De 18h à 20h chorale" fills the event from 6pm to 8pm

Note: I think the titles are already parsed to change the illustration.

**Comment by tcitworld** [comment]
Duplicate from #17
