### ISSUE TITLE
Left and right arrows are missing

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/calendar#315]
I just pulled master and the icons are not displayed, because the buttons have no width for me.
> ![bildschirmfoto vom 2017-01-23 14-27-57](https://cloud.githubusercontent.com/assets/213943/22205681/33b18508-e178-11e6-98c8-4ca271e6812c.png)

**Comment by georgehrke** [comment]
@jancborchardt @eppfel probably some server change? 

The entire calendar doesn't go to well with new button styles :/

**Comment by eppfel** [comment]
Yes, new inputs, but they are discussed right now, so might be reverted to some point nextcloud/server#3203

**Comment by eppfel** [comment]
Ok, so the changes discussed is just the shadows and will probably reverted in nextcloud/server#3204. 

But the other changes persist since nextcloud/server#3187
