### ISSUE TITLE
Don't show search results from the past (by default)

### ISSUE THREAD

**Issue by ruedigerkupper** [nextcloud/calendar#3157]
Searching through calendars using the "magnifying glass" icon yields search results for "all time" sorted by date. Meaning: If several events match the search (like a yearly recurring event), the first matches I see are from past events that may be long ago.
For example, if I search for a yearly recurring event in my private calendar, the first matches date as far back as 2013. But, naturally, I am interested in finding the next occurrence in the future, not in the past.
It might be good to have the option to search the past if the user wants that, but it should not be the default. The default should be to only search the future.

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/server/issues/27353

**Comment by ruedigerkupper** [comment]
Oh, sorry, didn't find that one :-/.
