### ISSUE TITLE
Action menu next to event title in sidebar is misaligned

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3161]
### Steps to reproduce
1. Create and save a new event
2. Open it in the sidebar

### Expected behaviour

The event title input and the action menu trigger are on the same height roughly

### Actual behaviour

![Bildschirmfoto von 2021-06-07 09-00-30](https://user-images.githubusercontent.com/1374172/120974128-0d663a00-c770-11eb-90b7-d7a884f6e550.png)

### Calendar app
**Calendar app version:** master and likely 2.2.0 or even earlier

cc @GretaD

**Comment by tcitworld** [comment]
Isn't that https://github.com/nextcloud/calendar/issues/3137 ?

**Comment by ChristophWurst** [comment]
Damn. Deja vu.
