### ISSUE TITLE
Add "Delete all items permanently now" for the trash bin

### ISSUE THREAD

**Issue by GretaD** [nextcloud/calendar#3171]
I would like to have an option  "Delete all items permanently now" text link below the "Deleted items will be permanently deleted after 30 days" in case I have too many deleted events/calendars on my "Deleted items". Deleting them one by one takes a lot of time.

-The action should have a confirmation dialog.

**Comment by ChristophWurst** [comment]
Implementation idea: we won't need a dedicated route on the server for this right now, let's just iterate over the listed items and send deletion requests one after the other (or with a bit of concurrency).
