### ISSUE TITLE
[Feature Request] Linked / Imported external calendars should be shareable

### ISSUE THREAD

**Issue by Gunnar-GO** [nextcloud/calendar#3180]
If i insert a link of an external Calendar, it is shown to me and works for my systems. But i can't share them internal.

For example i get the trash information an some local goverment services by an link to an ics file. at the moment i can't share them, every user in my cloud needs to set the same calendar.

share them internal would be make this much more easier.

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/server/issues/2902
