### ISSUE TITLE
Longer Reminder Periods

### ISSUE THREAD

**Issue by who8mypnuts** [nextcloud/calendar#3182]
**Is your feature request related to a problem? Please describe.**
It would be very helpful to have more than two days in advance reminders on events that are scheduled in the calendar.

**Describe the solution you'd like**
Here's an arbitrary example: I've scheduled in my calendar to pay my quarterly estimated taxes. I need to be reminded two weeks in advance in order to ensure that money is moved and available and to get the check written and mailed (yes, the federal taxes are still by check).

**Describe alternatives you've considered**
I suppose one alternative would be to schedule the item two weeks minus two days in advance in order to get the reminder a the right time, but that would only clutter up the calendar.

**Comment by tcitworld** [comment]
You can click on « Edit time » and set a delay in weeks.
![image](https://user-images.githubusercontent.com/2197836/121475240-709cda00-c9c5-11eb-9900-baa166514a85.png)
