### ISSUE TITLE
Show more information about rooms and resources

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3183]
**Is your feature request related to a problem? Please describe.**

If you use a resource back-end app like https://github.com/nextcloud-gmbh/calendar_resource_management there is a lot of (meta) data about the available rooms and resources, like the building and story of a room, as well as its capacity. Right now we only show the display name of a room. This is very limiting and in organizations with lots of rooms the search is not practical.

![Bildschirmfoto vom 2021-06-10 09-17-27](https://user-images.githubusercontent.com/1374172/121481720-b7420280-c9cc-11eb-8365-f53f7a584c87.png)
^ the current design

**Describe the solution you'd like**

Resources have attributes: Name, place, contact, capacity, accessibility, projector, whiteboard, etc. which need to be shown <https://github.com/nextcloud/server/blob/cc4e6630db13effc85383320ecd0b7487ec1475a/lib/public/Calendar/Room/IRoomMetadata.php#L36-L92>
  * [x] Name should be main line
  * [x] Capacity and place could be subline
  * [x] Availability or free/busy, would only show if people switch availability to "any" (requires https://github.com/nextcloud/calendar/issues/3417)
    * Can show as modal, with the free/busy widget
    * As a user I would prefer that the availability is included in the details of the search results. This of course means that the currently selected time has to be factored into the search query and the server has to evaluate this property.

**Describe alternatives you've considered**

N/a

**Additional context**

N/a

**Comment by alexanderdd** [comment]
Your link is broken, I think you meant https://github.com/nextcloud/calendar_resource_management

**Comment by jancborchardt** [comment]
Question first off: Should this not be shown for the "location" field instead of the "sharing" tab?

**Comment by ChristophWurst** [comment]
No. Location and resources are two things.

**Comment by alexanderdd** [comment]
It is different things from the tech side. But for a user, the location (i.e. address) is very similar/related to the room (i.e. Campus B, building 43, room7). Might lead to confusion.

But well, atm rooms are found under the tab "attendees"... but this problem is discussed somewhere else, right?

**Comment by ChristophWurst** [comment]
We plan to put rooms and resources on a separate tab.
