### ISSUE TITLE
Advanced search for rooms and resources

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3184]
**Is your feature request related to a problem? Please describe.**

We have a text input to add attendees to a meeting. The same search input is used to look for rooms and resources.

![Bildschirmfoto vom 2021-06-10 09-17-27](https://user-images.githubusercontent.com/1374172/121482396-6d0d5100-c9cd-11eb-9ae6-0171162c0eca.png)

This works for very simple scenarios, but for practical use one will need a more advanced search. This might include attributes like the capacity or the wheelchair accessibility of a room.

**Describe the solution you'd like**

I'm not sure if we can do this as some kind of string-based advanced search like on github, as in `meeting capacity:8` because that will only work with tech savvy people. Multiple inputs for those attributes could work better. We can do some research on other solutions to find out some common patterns.

* [x] https://github.com/nextcloud/calendar/issues/3270 Move Reminders & Repeating from tabs to details, then we can have a "Rooms & resources" tab (needs shorter name)
* [x] #3291
* [x] #3183
* [x] #3417
* [x] #3419
* [x] #3420
* [x] #3418
* [x] https://github.com/nextcloud/documentation/issues/7516
* [x] https://github.com/nextcloud/documentation/issues/7517
* [x] https://github.com/nextcloud/documentation/issues/7518

**Describe alternatives you've considered**

N/a

**Additional context**

This has a soft dependency on https://github.com/nextcloud/calendar/issues/3183 as we otherwise don't show the detailed properties of a advanced search result.

**Comment by alexanderdd** [comment]
(before thinking about this, we should make it more clear that this tab is not only for attendees but also for rooms and resources -- is there a separate issue for this already? maybe have a different icon for rooms and resources, e.g. square as opposed to the round icons/avatars for users, or have a completely separate tab?)

Somehow you need to **trigger the advanced search**, some ideas:
1.  when you click/tap into the search field, show a ":mag: advanced search" button in the drop down window. When you already typed something, show the first search results and show a ":mag: advanced search" at the bottom of the drop down window (ideally floating, so you can still scroll through search results while the advanced search button stays visible). This is similar to google mail search box.
2. have a button with a filter symbol at the right of the search box
3. have an "advanced search"/"show filters" button below the search box. (bad: not visible once you clicked into the search box and started typing)


**advanced search UI**: _(the biggest problem here is that this * will * be confusing if users and rooms are searched through the same search box.. am I searching for barrier-free rooms or handicapped attendees?)_

I think regular input fields/radio buttons would be best.

- Meeting capacity: (number input field)
- Accessible: (checkbox)

**Comment by tcitworld** [comment]
This will require significant changes in the backend, extending [principal-property-search](http://www.webdav.org/specs/rfc3744.html#REPORT_principal-property-search) to support extra props for this (we only support email and name for now).

**Comment by ChristophWurst** [comment]
Thanks for the input @alexanderdd @tcitworld.

We'll have a call today at 2AM CET at https://cloud.nextcloud.com/call/gqff69i8 to discuss this feature. Everyone is very welcome to join us :)

I'll post our findings here afterwards.

**Comment by ChristophWurst** [comment]
Here are the notes

* [ ] Move Reminders & Repeating from tabs to details, then we can have a "Rooms & resources" tab (needs shorter name)
* [ ] Resources have attributes: Name, place, contact, capacity, accessibility, projector, whiteboard, etc. which need to be shown <https://github.com/nextcloud/server/blob/cc4e6630db13effc85383320ecd0b7487ec1475a/lib/public/Calendar/Room/IRoomMetadata.php#L36-L92>
  * [ ] Name of course main line
  * [ ] Capacity and place could be subline
* [ ] Filtering resources: Line below the input field
  * [ ] Capacity (defaults to min how many participants already are in the event)
  * [ ] Availability (defaults to Available only)
  * [ ] 3-dot action menu with list of checkboxes
    * [ ] Room type: Any, Meeting room, Lecture hall, Seminar room, Other
    * [ ] Projector
    * [ ] Whiteboard
    * [ ] Accessibility
* [ ] Then when added, the 3-dot menu would be on the right for each entry, showing the same details but read-only of course
* [ ] Location can be prefilled from location of the room (Google does this) but not override if something is already set
* [ ] Ideally we would show e.g. 5 suggested rooms before people search
  * [ ] Could prioritize your recently or most used rooms
* [ ] Availability or free/busy, would only show if people switch availability to "any"
  * [ ] Can show as modal, with the free/busy widget

**Comment by miaulalala** [comment]
After testing this with a prop search via curl, I have found that the calendar_resource_management in combination with calendar already does a lot.

1) There is an xml namespace for the resources / room props - http://nextcloud.com/ns which is already resolved via `\OCA\DAV\CalDAV\ResourceBooking\AbstractPrincipalBackend::searchPrincipalsByMetadataKey`

2) There is a metadata table for both rooms and resources (`oc_calendar_rooms_md, oc_calendar_resources_md`)  which will contain the set resource attributes such as capacity, etc as a key value pairs:
![image](https://user-images.githubusercontent.com/7427347/123970638-952f1500-d9b9-11eb-9dbc-52c40680fd97.png)

3) For a capacity search for example, the current query in `searchPrincipalsByMetadataKey` would have to be adjusted, since it's not looking for any values `larger than` or `smaller than`

4) the frontend will need adjustments to send these queries to DAV


cURL example for a prop search on capacity:

```bash
curl 'http://nextcloud.local/remote.php/dav/' \
  -X 'REPORT' \
  -H 'Connection: keep-alive' \
  -H 'X-NC-CalDAV-Webcal-Caching: On' \
  -H 'requesttoken: *******************************************' \
  -H 'DNT: 1' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'Depth: 0' \
  -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Mobile Safari/537.36' \
  -H 'Content-Type: application/xml; charset=UTF-8' \
  -H 'Accept: */*' \
  -H 'Origin: http://************************* \
  -H 'Accept-Language: en-GB,en;q=0.9,de-AT;q=0.8,de;q=0.7,ko-KR;q=0.6,ko;q=0.5,fr-FR;q=0.4,fr;q=0.3,en-US;q=0.2,pl;q=0.1' \
  -H 'Cookie: oc_sessionPassphrase=*********************************; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; nc_username=admin; XDEBUG_SESSION=XDEBUG_ECLIPSE; ocnxfo9svy29=81sfkbch9tlo6d55hrl2p3bseo; nc_token=s4PkQkPPJfUFppijSB8lUjBluOD07aCy; nc_session_id=81sfkbch9tlo6d55hrl2p3bseo' \
  --data-raw '<x0:principal-property-search xmlns:x0="DAV:" test="anyof"><x0:property-search><x0:prop><x2:room-seating-capacity  xmlns:x2="http://nextcloud.com/ns"/></x0:prop><x0:match>1</x0:match></x0:property-search><x0:prop><x1:calendar-user-type xmlns:x1="urn:ietf:params:xml:ns:caldav"/><x1:calendar-user-address-set xmlns:x1="urn:ietf:params:xml:ns:caldav"/><x0:principal-URL/><x0:alternate-URI-set/><x2:room-seating-capacity  xmlns:x2="http://nextcloud.com/ns"/></x0:prop><x0:apply-to-principal-collection-set/></x0:principal-property-search>' \
  --compressed \
  --insecure;
```

The XML in question:

```xml
<x0:principal-property-search xmlns:x0="DAV:" test="anyof">
    <x0:property-search>
        <x0:prop>
            <x2:room-seating-capacity  xmlns:x2="http://nextcloud.com/ns"/>
        </x0:prop>
        <x0:match>1</x0:match>
    </x0:property-search>
    <x0:prop>
        <x1:calendar-user-type xmlns:x1="urn:ietf:params:xml:ns:caldav"/>
        <x1:calendar-user-address-set xmlns:x1="urn:ietf:params:xml:ns:caldav"/>
        <x0:principal-URL/>
        <x0:alternate-URI-set/>
        <x2:room-seating-capacity  xmlns:x2="http://nextcloud.com/ns"/>
    </x0:prop>
    <x0:apply-to-principal-collection-set/>
</x0:principal-property-search>
```

The multistatus response from DAV

```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
    <d:response>
        <d:href>/remote.php/dav/principals/calendar-rooms/calendar_resource_management-con_room_2/</d:href>
        <d:propstat>
            <d:prop>
                <x1:calendar-user-type xmlns:x1="urn:ietf:params:xml:ns:caldav">ROOM</x1:calendar-user-type>
                <d:principal-URL>
                    <d:href>/remote.php/dav/principals/calendar-rooms/calendar_resource_management-con_room_2/</d:href>
                </d:principal-URL>
                <d:alternate-URI-set>
                    <d:href>mailto:confroom2@test.com</d:href>
                </d:alternate-URI-set>
                <x2:room-seating-capacity xmlns:x2="http://nextcloud.com/ns">1</x2:room-seating-capacity>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
        <d:propstat>
            <d:prop>
                <x1:calendar-user-address-set xmlns:x1="urn:ietf:params:xml:ns:caldav"/>
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>
```

So it works but
1) needs a bit of fiddling with how queries are run on the key value pairs for the meta data
2) it needs a fronted implementation that sends the right queries.

**Comment by alexanderdd** [comment]
When working on rooms and resources, can you please keep in the back of your mind that a later implementation of https://fullcalendar.io/docs/vertical-resource-standard-demo or https://fullcalendar.io/docs/timeline-standard-view-demo would be absolutely **f**a**n**t**a**s**t**i**c**, see this issue https://github.com/nextcloud/calendar/issues/2713 

Not sure if this influences anything you do at the moment, I don't understand it well enough =)

**Comment by miaulalala** [comment]
> Room type: Any, Meeting room, Lecture hall, Seminar room, Other

Are we predefining the room types or are we leaving it to the users which types of rooms they would like to have?

**Comment by miaulalala** [comment]
Also, should we separate the room-fetures into separate meta data entries?

![image](https://user-images.githubusercontent.com/7427347/124120143-b05e5b00-da73-11eb-8804-e418dd147bcd.png)

**Comment by ChristophWurst** [comment]
> Are we predefining the room types or are we leaving it to the users which types of rooms they would like to have?

In the design call we said this is most likely free for users to define.



> Also, should we separate the room-features into separate meta data entries?

If this is necessary for the search then yes. But I guess it could also stay as is and be sent as serialized array, right? Like `room-features` => `PHONE,TV` and then you get only rooms that have those two things

**Comment by miaulalala** [comment]
The result set returned to the AbstractPrincipalCollection::searchPrincipal should only contain principal paths

![image](https://user-images.githubusercontent.com/7427347/125408694-736f5e00-e3bb-11eb-84da-04921e8912cb.png)

**Comment by miaulalala** [comment]
A multi property search:

```xml
<?xml version="1.0"?>
<x0:principal-property-search xmlns:x0="DAV:" test="allof">
    <x0:property-search>
        <x0:prop>
            <x2:room-features xmlns:x2="http://nextcloud.com/ns"/>
        </x0:prop>
        <x0:match>PHONE,TV</x0:match>
    </x0:property-search>
    <x0:property-search>
        <x0:prop>
            <x2:room-seating-capacity xmlns:x2="http://nextcloud.com/ns"/>
        </x0:prop>
        <x0:match>100</x0:match>
    </x0:property-search>
    <x0:prop>
        <x1:calendar-user-type xmlns:x1="urn:ietf:params:xml:ns:caldav"/>
        <x0:principal-URL/>
        <x0:alternate-URI-set/>
        <x2:room-features xmlns:x2="http://nextcloud.com/ns"/>
    </x0:prop>
    <x0:apply-to-principal-collection-set/>
</x0:principal-property-search>
```

**Comment by ChristophWurst** [comment]
@st3iny FYI added https://github.com/nextcloud/calendar/issues/3291 to the list. I think that was meant to be here but we forgot to add it when the ticket was split :)
