### ISSUE TITLE
Updating or Changing a Meeting Makes It Say it Doesn't Exist

### ISSUE THREAD

**Issue by Remioactive** [nextcloud/calendar#3187]
I can make a new meeting and that works fine but if i try and change the times or date it will try and load but wont the loading wheel just go forever and when i refresh the page then click back onto the meeting it will say the the meeting doesnt exist but i can still see the block for it on the claender.

just wondering if anyone else is having the problem or is it just my company and its on more then one of our servers and its always the same  problem 

and if anyone has any ideas on how to fix this please let me know ive been trying to figure this out for sometime

**Comment by tcitworld** [comment]
Please fill the issue template so that we can help you.
