### ISSUE TITLE
Updating or Changing Already Made Meetings Makes Them Say They Dont Exist and Not Update

### ISSUE THREAD

**Issue by Remioactive** [nextcloud/calendar#3188]
### Steps to reproduce
1.Make a new meeting
2.Update anything to do with the meeting
3.Refresh the page and click on the meeting again

### Expected behaviour
The meeting should change to the new updated info

### Actual behaviour
The change wont load and it says the meeting doesnt exist

### Calendar app
2.2.2 NC ver 21

WebDEV (I Think I dont know to be honest)

### Client configuration
Chrome but does it on any PC Browser

**Operating system:** (e.g. Arch Linux)

### Server configuration

Ubuntu 21 or 22

Apache

MariaDB

**PHP 7.0.3

NextCloud 21

**Updated from an older installed version or fresh install:**

**List of activated apps:**
Polls
Accessibility
Activity
Appointments
AppOrder
Auditing / Logging
Automated PDF conversion
BigBlueButton Integration
Calendar
Circles
Collaborative tags
Comments
Contacts Interaction
Custom menu
Dashboard
Data Request
Deck
Deleted files
Element for Nextcloud
External sites
Federation
File access control
File sharing
First run wizard
Group folders
Log Reader
Mail
Mind Map
Monitoring
Nextcloud announcements
Notifications
Notifications for calendar event updates
ONLYOFFICE
Password policy
Passwords (Legacy Support Release)
PDF viewer
Photos
Pico CMS
Piwik/Matomo Tracking
Privacy
Quick notes	
Recommendations	
Registration	
Right click	
Share by mail	
Simple poll for Nextcloud Talk	
Support	
Talk	
Talk Matterbridge	
Text	
Theming	
Two-Factor TOTP Provider	
Update notification	
Usage survey	
User status	
Versions	
Video player	
Weather status

Nothing to do with calendar in the logs and have no access to the files. they are done by another team and i can not get a hold of them.

**Comment by tcitworld** [comment]
Sorry about that, but I have to ask you if you correctly click the "Save" button on the bottom of the editor so that the event is correctly saved...

Apart from that, can you open your browser's devtools (F12) and check for messages appearing in the console tab when you save the event. If you can, check the Network tab as well for errors, and post what you find.

**Comment by Remioactive** [comment]
vue.runtime.esm.js:1888 
Error
    at XMLHttpRequest.regeneratorRuntime.wrap.e.abrupt.a.onreadystatechange (request.js:361)

is the only error that show in the menu and i just checked i im hitting save so its not that

**Comment by tcitworld** [comment]
This looks like https://help.nextcloud.com/t/cannot-create-calendar-entry/87107 but it's not very informative.

**Comment by Remioactive** [comment]
the thing is i can create a new evenet i just cant update or change it

i can also deleted it

**Comment by Remioactive** [comment]
https://user-images.githubusercontent.com/82468033/121568100-b1ace280-c9f5-11eb-8648-2295be846183.mov

this is what im dealing with

**Comment by miaulalala** [comment]
Fixed
