### ISSUE TITLE
Option to set a calendar as transparent for free/busy

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3193]
**Is your feature request related to a problem? Please describe.**

If you create a calendar it's currently always considered for free/busy scheduling. There are cases where you don't want this, e.g. for a calendar that is supposed to be used for a group, then the owner (the person who shared) shouldn't be seen as blocked for the shared events. But also sometimes you might create a calendar for something that isn't an actual event where you are busy, and you don't want to set your availability to free for every event you create in there.

**Describe the solution you'd like**

Offer users a checkbox on the calendar action menu where they can toggle the free/busy transparency.

**Describe alternatives you've considered**

N/a

**Additional context**

* The standardized property https://icalendar.org/CalDAV-Scheduling-RFC-6638/9-1-caldav-schedule-calendar-transp-property.html
* Handling in Sabre https://github.com/sabre-io/dav/blob/c1afdc77a95efea6ee40c03c45f57c3c0c80ec22/lib/CalDAV/Schedule/Plugin.php#L890-L894

**Comment by naelfe** [comment]
Or if you have a separate calendar for your cities garbage disposal, where you simply import the ical for the whole year but are marked busy for every other day.
Would be indeed handy to set the hole calendar as transparent. It's too much extra work for me to change the ical every time manually, because they tend to change it a couple of times during the year :D

**Comment by miaulalala** [comment]
Seems group / shared calendars are always treated as transparent as per:

https://github.com/nextcloud/server/blob/ad78f7e48e7f03fc6c3f47a8972d122cde275d97/apps/dav/lib/CalDAV/CalDavBackend.php#L416

so any calendar that is shared should not have this checkbox.

**Comment by ChristophWurst** [comment]
I suggest to show the checkbox read-only and unchecked, or some text. Then this will also be easy to understand for users.

**Comment by miaulalala** [comment]
> I suggest to show the checkbox read-only and unchecked, or some text. Then this will also be easy to understand for users.

You mean for shared and subscription calendars?
