### ISSUE TITLE
Appointment descripton disappears when changing visibility to other users

### ISSUE THREAD

**Issue by plauzenbaer** [nextcloud/calendar#320]
### Steps to reproduce
1. added an appointment "visit library" to my shared calender (1 share with one user, and one group)
2. change the visibility for other in "Details" and "when shared show only busy"
3. the appointment "visit library" was automatically renamed to "busy"

### Expected behaviour
the added appointment in a shared calender should be keeping the appointment title for the
creator user and should show "busy" to the other users who are shared users

### Actual behaviour
see steps to reproduce #3

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 

**Server version:** (see your admin page)

**Calendar version:** (see the apps page)
1.5.0

**Updated from an older installed version or fresh install:**
Updated from earler version

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/server/issues/2787#issuecomment-274550136
