### ISSUE TITLE
Remove some border-left from core styles in calendar

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#321]
Recent changes in the server css had quite bad consequences for the calendar :/ 

cc @nextcloud/designers 

1.
<img width="255" alt="1" src="https://cloud.githubusercontent.com/assets/1250540/22329288/e3c7d196-e3c0-11e6-9f8a-a1ee3249eda6.png">

The left border is a real overkill here. Just get rid of it?

2.
<img width="250" alt="2" src="https://cloud.githubusercontent.com/assets/1250540/22329290/e3ebeaae-e3c0-11e6-9e74-0c76aa855273.png">

The left border is a real overkill here. Just get rid of it?

3.
<img width="269" alt="3" src="https://cloud.githubusercontent.com/assets/1250540/22329289/e3ea23c2-e3c0-11e6-9247-25a5bbe834e6.png">

- Did you change a lot of table css? The date picker is too big now :/
- I like the left border at the `26`, but the bottom and right borders look weird.
- some server css change killed the prev/next button (https://github.com/nextcloud/calendar/issues/315)

**Comment by skjnldsv** [comment]
Fixed in https://github.com/nextcloud/server/pull/3260
