### ISSUE TITLE
ship minified versions of everything in js/vendor/

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#323]

**Comment by tcitworld** [comment]
Couldn't we just bundle them inside `js/public/app.min.js` ?

**Comment by georgehrke** [comment]
I thought about something very similar. Bundling them inside `js/public/vendor.min.js`
Will check both approaches

**Comment by tcitworld** [comment]
Btw, webpack2 has the tree shaking feature which could be quite useful here.

**Comment by georgehrke** [comment]
I asked @schiessle if we run into any license issues with this.
He said, we just have to make sure to include license and copyright headers in the vendor.js, then we can omit them in the minified one. (but we need to ship both)

**Comment by georgehrke** [comment]
- [ ] drop davclient.js, its part of the Nextcloud server and also always included, no need to include it twice
- [ ] hsl_to_rgb_converter doesn't contain license header

**Comment by tcitworld** [comment]
>  He said, we just have to make sure to include license and copyright headers in the vendor.js, then we can omit them in the minified one. (but we need to ship both)

Couldn't we just a [COPYING-README](https://github.com/nextcloud/server/blob/master/COPYING-README) file like the one in server ?

**Comment by georgehrke** [comment]
That's something @schiessle has to answer

**Comment by georgehrke** [comment]
> Couldn't we just have a COPYING-README file like the one in server ?

I actually doubt that, because without headers you can't distinguish which code belongs to which project and is licensed under what license.

**Comment by tcitworld** [comment]
OK, (but when nextcloud used asset-pipeline, it was the same 😄 )

**Comment by georgehrke** [comment]
but that was dropped 🙈

**Comment by georgehrke** [comment]
and actually, files for the asset pipeline were generated by the user. It was not directly shipped.
