### ISSUE TITLE
In calendar app, link to talkroom is not clickable

### ISSUE THREAD

**Issue by olafkewl** [nextcloud/calendar#3233]
When creating a meeting in calender + talkroom, link in description and received mail is not clickable (not a HREF).

How to reproduce :

- Create a new meeting
- Select attendees
- Click "Create Talk room for this event"

Then, none in the Calendar App or in the received mail the address is clickable, this is confusing for "non-advanced" users.
Version : 20.0.3 (from docker : nextcloud:latest)

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/calendar/issues/2730

The `DESCRIPTION` field can only contain raw text, not HTML with links. 
As the calendar editor section also needs to be editable it's hard to make links actual ones. Same goes for events received by mail, the description is raw text as well and can't be rendered as a real link.

In the future, this property will allow rich text descriptions https://github.com/nextcloud/calendar/issues/3234
Other options would be to use the `CONFERENCE` or `URL` properties, but those aren't much supported either.
https://github.com/nextcloud/calendar/issues/1758
https://github.com/nextcloud/calendar/issues/2895
