### ISSUE TITLE
Event timezone not taken in account when displaying event

### ISSUE THREAD

**Issue by tchernobog** [nextcloud/calendar#3241]
Hi,

my Calendar version is 2.2.2.

when trying to import my Outlook 365 work calendar inside NextCloud as an external .ics link, I am seeing several events which are shown with the wrong time in the Web UI. This seems to happen because Office 365 doesn't use only Olsen data, but has an extra list of own timezone aliases.

Timezones are also defined at the start of the VCALENDAR, so they should be recognized without any external reference. I would expect Calendar to be able to use them. If an external database for aliases is needed, https://unicode-org.github.io/cldr-staging/charts/37/supplemental/zone_tzid.html has a list.

Example (I removed other events/cruft to produce a MWE):

```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:Calendar
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:India Standard Time
BEGIN:STANDARD
DTSTART:16010101T000000
TZOFFSETFROM:+0530
TZOFFSETTO:+0530
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T000000
TZOFFSETFROM:+0530
TZOFFSETTO:+0530
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DESCRIPTION:Try out if NextCloud imports this successfully.
UID:040000008200E00074C5B7101A82E00800000000200A6B786E64D701000000000000000
 0100000002A7CD820555AEA4E8E923DD8BE563816
SUMMARY:Example event
DTSTART;TZID=India Standard Time:20210621T193000
DTEND;TZID=India Standard Time:20210621T203000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20210619T112713Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Immaterial
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR
```

With my calendar following CEST, this shows an event at 19:30 on 2021-06-21 in my local timezone instead of shifting it to account for the timezone difference.

**Comment by tcitworld** [comment]
Odd, they seem to be correctly listed in our aliases database https://github.com/nextcloud/calendar/blob/master/timezones/zones.json

**Comment by tchernobog** [comment]
You are right, the timezone is there. However, the following event as returned by `/remote.php/dav/calendars/matteo/outlookoffice365com-1/` is displayed in the wrong timezone. I.e. in my local timezone. I am trying to debug it.

```
BEGIN:VEVENT
DESCRIPTION:Description Removed
SUMMARY:Summary Removed
DTSTART;TZID=India Standard Time:20210518T173000
DTEND;TZID=India Standard Time:20210518T180000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20210724T081739Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:4
LOCATION:Location Removed
X-MICROSOFT-CDO-APPT-SEQUENCE:4
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

**Comment by tchernobog** [comment]
It appears that I get start dates and end dates looking like this:

```
{
    "_mutable": true,
    "_subscribers": [
      null
    ],
    "_innerValue": {
      "_time": {
        "year": 2021,
        "month": 7,
        "day": 20,
        "hour": 17,
        "minute": 30,
        "second": 0,
        "isDate": false
      },
      "_cachedUnixTime": 1626802200,
      "_pendingNormalization": false,
      "timezone": "India Standard Time",
      "zone": {
        "expandedUntilYear": 0,
        "changes": [],
        "tzid": "floating"
      }
    }
  };
  ```
  
Note how there is a `timezone` property set, but the `zone` (which I guess is what the ICAL library uses) has no corresponding `tzid`. This leads `getInTimezone()` to fail to adjust the date before display.

**Comment by tchernobog** [comment]
So, I still trying to narrow it down. I was thinking this was a problem in `nextcloud/calendar-js`, but after writing a unit test it appeared the same input works when the parser is invoked from calendar-js, but fails when invoked through `nextcloud/calendar`.

Using a debugger, I see that the following code takes a different path:

```javascript
	_registerTimezones() {
		for (const [tzid, timezone] of this._timezones) {
			if (!this._defaultTimezoneManager.hasTimezoneForId(tzid)) {
				this._defaultTimezoneManager.registerTimezone(timezone)
			}
		}
	}
```

When using calendar-js directly, the `_defaultTimezoneManager.registerTimezone()` method is called. In `nextcloud/calendar`, it is not.
