### ISSUE TITLE
Long WebCal URL not accepted

### ISSUE THREAD

**Issue by dadosch** [nextcloud/calendar#325]
### Steps to reproduce
1. Insert a long url to the web calendar abonement box
i.e. from moodle: http://demo.moodle.net/calendar/export_execute.php?preset_what=courses&preset_time=recentupcoming&username=teacher&authtoken=35b0202e4f270c4cc9864e46dad56cb0c90ed382 (this is just to show the format, its **NOT** reachable on this host)
2. this will fail

### Expected behaviour
it should save the url in the database and add the calendar to the list

### Actual behaviour
in nextcloud it says `Fehler beim Speichern des WebCal-Kalenders (error on saving webcal calender)`
in the log it complains about  `Data too long for column 'displayname' `

### Server configuration
**Operating system**:
Ubuntu 16.04.1
**Web server:**
nginx
**Database:**
mysql
**PHP version:**
7
**Server version:** (see your admin page)
11.0.1 (stable)
**Calendar version:** (see the apps page)
 1.5.0
**Updated from an older installed version or fresh install:**
updated from older one

**Comment by georgehrke** [comment]
Thx for the bug report.

We will just have to cut of the display name at some point.

**Comment by georgehrke** [comment]
For the record: Displayname has a length of 100

**Comment by godfuture** [comment]
Just had this issue with "http://www.schulferien.org/media/ical/deutschland/ferien_baden-wuerttemberg_2017.ics?k=och0WuIKpGyFuh5ygZXeLnePHD83I3KzIGJLY9EEEGpu3cvH36YSy1qmNTZ1ex3-ISxy3BXcZRIWYum1VWKR71v6IOydqo8pH6Ma-DvZTeU".

Why not letting the user fill the displayName?

**Comment by georgehrke** [comment]
> Why not letting the user fill the displayName?

You can change the display name after creating it

**Comment by godfuture** [comment]
> You can change the display name after creating it
Why not saving the display name first and afterwards the URL? Or both in the same time?

**Comment by georgehrke** [comment]
Most public calendar links contain a name already. So why ask for it if in > 90% of the cases we can already use a proper one.
