### ISSUE TITLE
Feature request : default text for Description

### ISSUE THREAD

**Issue by tombou** [nextcloud/calendar#326]
Hi,

I want to know if there is a way to have a pre-filled description field. I want when a user creates a new events, there is some guideline to follow. Here is an example :

```
Name:
Phone:
Notes:
```

I've look into the code and there is a place to put "default" but it seems that they are not used somewhere. There is a way to do it or it can be a new feature? Thanks

**Comment by georgehrke** [comment]
If you want to implement it, this is the place to go: https://github.com/nextcloud/calendar/blob/c359ba3ededccddb7a24b0b776c8bcec36917b53/js/app/factory/icalFactory.js#L60

I'm not sure this is something we are gonna implement. What do you try to achieve by having Name, phone and notes?
Maybe it would make more sense to add the person with name as an attendee and just use the entire description field for notes.

cc @jancborchardt

**Comment by georgehrke** [comment]
Actually this place should be better: https://github.com/nextcloud/calendar/blob/c359ba3ededccddb7a24b0b776c8bcec36917b53/js/app/models/veventModel.js#L361

**Comment by tombou** [comment]
The user use the calendar for entering some basics informations as the same time they plan it. So this way, they can't forget any informations. There is more fields than these three actually.

**Comment by georgehrke** [comment]
@tcitworld What do you think about this feature?

**Comment by tcitworld** [comment]
Not necessary IMHO.

**Comment by georgehrke** [comment]
This is a really special feature request with very rare use cases.
Too special and too rare for the nextcloud calendar in our opinion.

As said above, if you are interested in implementing this on your own, VEventModel is the place to go.
This should be as easy as:
```javascript
simple.description = `Name:
Phone:
Notes:
`;
```

**Comment by tombou** [comment]
It works better in iCalFactory for me. I've added this line and it's fine with me. Thanks

event.updatePropertyWithValue('description','Name:\nPhone:\nNotes:')
