### ISSUE TITLE
Usage of generateOcsUrl

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/calendar#3262]
Since @nextcloud/router@2.0.0 (updated in https://github.com/nextcloud/calendar/pull/3012), `generateOcsUrl` does not contain a trailing slash anymore, see https://github.com/nextcloud/nextcloud-router/blob/master/CHANGELOG.md#200---2021-04-07

So (without having run the code), I wonder if theses usages (which assume a trailing slash, if I am right), still work properly:

https://github.com/nextcloud/calendar/blob/eb5414b09eefe770e17def1e83924972a1ba1018/src/services/talkService.js#L36

https://github.com/nextcloud/calendar/blob/eb5414b09eefe770e17def1e83924972a1ba1018/src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue#L185

@ChristophWurst @tcitworld @st3iny

**Comment by raimund-schluessler** [comment]
I just realized we have the same problem in Tasks, and there it does not work anymore https://github.com/nextcloud/tasks/issues/1651. So, very likely a problem here as well.

**Comment by st3iny** [comment]
I just tested a bit and can confirm that this breaks some features of calendar.
