### ISSUE TITLE
blank screen with calendar 2.3.0-RC.1 and Nextcloud 22RC1

### ISSUE THREAD

**Issue by BernieO** [nextcloud/calendar#3267]
### Steps to reproduce
1. Upgrade path: NC21.0.2 -> NC 22RC1
2. Install and enable calendar 2.3.0-RC.1 (downloaded archive from github)
3. open calendar app in Nextcloud

### Expected behaviour
calendar app displays the calendars

### Actual behaviour
blank screen except for the blue Nextcloud-Header with the app symbols

### Calendar app
**Calendar app version:** 2.3.0-RC.1

### Client configuration
Firefox 89.0.2
Safari 14.1.1

**Operating system:** macOS 11.4

### Server configuration
**Operating system**: Debian 10
**Web server:** nginx
**Database:** SQLite3
**PHP version:** 7.3.27-1~deb10u1

**Nextcloud Version:** 22RC1

Let me know, if you need any logs

**Comment by tcitworld** [comment]
Can you open your browser console (F12) and post any message that appear when you load the page.

**Comment by BernieO** [comment]
<img width="1173" alt="Bildschirmfoto 2021-06-28 um 11 32 57" src="https://user-images.githubusercontent.com/16474697/123614407-9834d480-d804-11eb-80be-e1857ddfe4b5.png">

**Comment by tcitworld** [comment]
The issue seems to be `laden fehlgeschlagen`... where the script file is missing. Did you try to force refresh the page (Ctrl + F5) ?

**Comment by BernieO** [comment]
Yes, I did force refresh the page with CMD+R and CMD+Shift+R (I am on a mac) a couple of times. Also restarting the Browser or rebooting the computer didn't help. I get the same result with opening the calendar in a private browsing tab.

Apart from that I didn't metion yet that I had no problems with NC22b5 and Calendar 2.3.0-alpha3

I just noticed, that the calendar-data from the dashboard also isn't loaded (spinning wheel forever). Maybe that has also to do with it?
<img width="686" alt="Bildschirmfoto 2021-06-28 um 12 29 27" src="https://user-images.githubusercontent.com/16474697/123622425-7d665e00-d80c-11eb-84b5-ed039d5ed811.png">

**Comment by BernieO** [comment]
Since this is a testing instance with SQLite3 and no confidential data, I could also upload the installation as a zip file if that is of any help.

**Comment by st3iny** [comment]
@BernieO Thanks for reporting your issue.

We released v2.3.0 today. Could you try running the final release and check if the error persists?

**Comment by st3iny** [comment]
Did you build the javascript artifacts using the most recent npm version (v7.x.x)? You have to compile them manually if you use an archive from this repository because it only contains the source code 

Compile the artifacts by running: `npm ci && npm run build`

**Comment by tcitworld** [comment]
@BernieO Otherwise to avoid the need to build make sure to pick the tarball and not the source code package. 

It was forgotten in the release 2.3.0 https://github.com/nextcloud/calendar/releases/tag/v2.3.0 but it's always accessible from https://apps.nextcloud.com

**Comment by nickvergessen** [comment]
Release files are now uploaded in this org https://github.com/nextcloud-releases/calendar/releases/

**Comment by BernieO** [comment]
I am not sure which version I downloaded. Maybe one without artifacts. This was probably my mistake - Sorry.
I'll keep an eye on the proper version next time. 

Anyhow: I downloaded release 2.3.0 and it works out of the box.
Thanks for the support and keep up the good work! 👍
