### ISSUE TITLE
Error in semantic version update

### ISSUE THREAD

**Issue by storm1er** [nextcloud/calendar#3269]
Hi,

Based on https://semver.org/ : 

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

In the changelog of 2.3.0:

```
Dropped webcals support
```

Therefore it may have been 3.0.0 instead of 2.3.0

**Comment by storm1er** [comment]
Also, webcal support is still displayed in the readme and appears in the store. You may wanna change that also.

**Comment by raimund-schluessler** [comment]
This was changed in https://github.com/nextcloud/calendar/pull/3212 and I would rather consider it a bugfix, since webcals did never really work and is not well supported. It is about webcal over https, hence webcal**s** (notice the `s` at the end).
Webcal support is still present, so the readme is correct.

**Comment by tcitworld** [comment]
Yeah I should have improved the wording here to make it clear. 😬

**Comment by storm1er** [comment]
> With this release, we adopt semantic versioning. This will make it more clear what is contained in a release. As we introduce a minor feature, the multiple-email support, we therefor release this as 22.1.0, not 22.0.1.

![I see](https://forum.wordreference.com/attachments/post-14251-eddie-murphy-i-see-what-you-di-paqx-jpeg.22077/)

Congrats for the switch, It will be better for everyone ;)

**Comment by tcitworld** [comment]
I don't this it had to do with this issue. 😊
