### ISSUE TITLE
Separate attendee and resource tabs

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#3270]
**Describe the solution you'd like**
Separate the room/resource search and list from the attendee tab into its own tab. This paves the way for further improvements to the resource/room search.

**Additional context**
First item of https://github.com/nextcloud/calendar/issues/3184#issuecomment-866201361.

**Comment by st3iny** [comment]
@tcitworld @ChristophWurst 

Do we need to show avatars for resources and rooms? I think we should get rid of them because they always default to generated avatars. Or is there a way to associate avatars with room/resources in a meaningful way that I don't know of?

**Comment by tcitworld** [comment]
No, only Nextcloud users and contacts have avatars.

**Comment by ChristophWurst** [comment]
So there are no real avatars but we can still use the two letter placeholders right? @jancborchardt @nimisha-vijay do you have preferences?

**Comment by tcitworld** [comment]
Yes, through the Avatar component `isNoUser` prop.
With a room name such as `Room 1, 2, 3, A, B, C` it looks fine:
![image](https://user-images.githubusercontent.com/2197836/123984793-396a8900-d9c5-11eb-9673-ea8501bca74c.png)
![image](https://user-images.githubusercontent.com/2197836/123985232-96fed580-d9c5-11eb-982c-ab4a9b82e051.png)

But if the room is named `Room n°1,2,3` it won't be useful, as all letters will be the same.
![image](https://user-images.githubusercontent.com/2197836/123984754-2d7ec700-d9c5-11eb-8bac-bc1f12e56b64.png)
![image](https://user-images.githubusercontent.com/2197836/123985126-80587e80-d9c5-11eb-994f-c217788148cb.png)

However, the colors changing may be enough of an indicator.

On the other side, we could use this picture to differentiate between rooms and resources (and even map some icons to the resource types defined in `calendar_resource_management`).

**Comment by nimisha-vijay** [comment]
Yeah, rooms can also be named using numbers like Room 101, 102, 103, etc, in which case it would just show R1 for everything. I don't think we can cover all the ways rooms can be named so just using the two letters sounds good enough.

I was also thinking if it is necessary to show some distinction between users and rooms/resources? Maybe using a square with rounded corners for rooms/resources (is that possible?), with an icon in one of the corners to indicate the type of resource, if there's enough space.
What do you think?

**Comment by ChristophWurst** [comment]
> I was also thinking if it is necessary to show some distinction between users and rooms/resources?

There will be a tab for attendees and one for resources and rooms. So I don't think that's necessary.
