### ISSUE TITLE
Issues with the trash bin

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/calendar#3271]
I have found various issues with the trash bin in the latest master of Calendar on Nextcloud server latest master.

- [x] #3329

![Screenshot 2021-06-29 at 23-08-02 Week 27 of 2021 - Calendar - Nextcloud](https://user-images.githubusercontent.com/2496460/123867757-0d9cc400-d92f-11eb-84de-759ceb324c6c.png)

- [x] #3330

- [x] #3331
```
[ERROR] calendar: could not restore /nextcloud/remote.php/dav/calendars/admin/trashbin/objects/2898.ics 
Object { app: "calendar", uid: "admin", error: TypeError }
ConsoleLogger.js:41:16
    log ConsoleLogger.js:41
    error ConsoleLogger.js:63
    e Trashbin.vue:225
    A runtime.js:63
    _invoke runtime.js:293
    w runtime.js:118
    h calendar-main.js:2
    s calendar-main.js:2
    (Async: promise callback)
    h calendar-main.js:2
    i calendar-main.js:2
    m calendar-main.js:2
    m calendar-main.js:2
    restore Trashbin.vue:173
    click Trashbin.vue:1
    VueJS 63
```
Checking in the Tasks app shows that the task got restored correctly anyway.

- [x] #3332

**Comment by tcitworld** [comment]
* The date seems fine at first, then goes mad after a few seconds (probably a parsing error)
![image](https://user-images.githubusercontent.com/2197836/123961975-36659d80-d9b1-11eb-9693-2083b65278f2.png)

**Comment by raimund-schluessler** [comment]
Events/Tasks with very long descriptiong overflow to the right and make the buttons disappear:
![Screenshot 2021-07-05 at 21-50-00 Week 28 of 2021 - Calendar - Nextcloud](https://user-images.githubusercontent.com/2496460/124513403-0bc57b80-dddb-11eb-9b98-26a26a62c7b7.png)

**Comment by raimund-schluessler** [comment]
It is not really clear what is a calendar and what is an event/task (first one is a calendar, second one a task):

![Screenshot 2021-07-09 at 09-53-04 Woche 27 aus 2021 - Kalender - Nextcloud](https://user-images.githubusercontent.com/2496460/125043744-8cb29a80-e09b-11eb-92c6-30aac78f54fa.png)

**Comment by ChristophWurst** [comment]
cc @GretaD @nimisha-vijay. I suggest we split this into separate tickets. Those items all make sense to me.

**Comment by raimund-schluessler** [comment]
I think I fixed most issues here for the trash bin implementation in Tasks https://github.com/nextcloud/tasks/blob/master/src/components/AppNavigation/Trashbin.vue:
![Screenshot 2021-07-21 at 11-55-32 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/126470542-962543e8-c9b5-4401-a0a6-750df2ca0bab.png)

![Screenshot 2021-07-21 at 11-58-39 Aufgaben - Nextcloud](https://user-images.githubusercontent.com/2496460/126470871-03bb1dd2-b7ba-442a-be13-e0a074c735bc.png)


I will send some PRs to incorporate the changes for the Calendar app trash bin. Should be relatively easy as I initially copied the component from the Calendar repo.

**Comment by GretaD** [comment]
thats great, let me know if you need somebody to test them

**Comment by raimund-schluessler** [comment]
I send PRs for all issues in this thread but one. Items with long titles or calendar names still kind of overflow, but with #3333 it is not as severe anymore, because now the whole trash bin just scrolls in x-direction. I would still propose to handle it by ellipsising the long strings instead of making the trash bin scroll. If this is agreed on, I will send another PR after the others are in to handle it like in the Tasks app.

**Comment by GretaD** [comment]
> I send PRs for all issues in this thread but one. Items with long titles or calendar names still kind of overflow, but with #3333 it is not as severe anymore, because now the whole trash bin just scrolls in x-direction. I would still propose to handle it by ellipsising the long strings instead of making the trash bin scroll. If this is agreed on, I will send another PR after the others are in to handle it like in the Tasks app.

yeah, we can add this as a polish in the design ticket (that we should open soon :) )

**Comment by ChristophWurst** [comment]
4/4 tasks done
