### ISSUE TITLE
change minimum height to 15mins

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/calendar#3275]
### Steps to reproduce
1. Have time steps of 30mins
2. create an event that is 15min or shorter

### Expected behaviour
The event should be fill a 15min-high slot (note that there are thin grey lines that show how long 15mins are, and that the event text is small enough to fit in a 15min slot).

### Actual behaviour
The event looks like it is 30mins long. Note the inconsistency with the time/duration and with the display of event text in these three examples:
![Bildschirmfoto vom 2021-06-30 23-30-49](https://user-images.githubusercontent.com/28591861/124034363-65086600-d9fb-11eb-9286-9ef265ba369f.png)

### Comments
Slightly **related**  to https://github.com/nextcloud/calendar/issues/2644 which was fixed by https://github.com/nextcloud/calendar/pull/3121

### Calendar app
**Calendar app version:** 2.3.0

### Client configuration
**Browser:** Firefox 89.0.2

**Operating system:** LinuxMint

### Server configuration

**Nextcloud Version:** 20.0.10

......................Please ask if you need more details.

**Comment by fpoulain** [comment]
Hi,
I am facing the same issue. See https://github.com/nextcloud/calendar/commit/cec87e133a55b9b37f844586b44eeea2cdb902b8#commitcomment-53418639

**Comment by ChristophWurst** [comment]
:eyes: mrtumnus

Also see https://github.com/nextcloud/calendar/issues/3310 for some more feedback

**Comment by ValterMollar** [comment]
Hi,
I am facing the same issue.
As a workaround i modified: 
`/var/www/html/nextcloud/apps/calendar/css/fullcalendar.scss`
changing: 
```
putting .fc-v-event {
        min-height: 4em;
}
```
in
```
putting .fc-v-event {
        min-height: 2em;
}
```
and it seems to work.

**Comment by ygoe** [comment]
This is a real drama here. I'm only using the week view in all calendars I use. I believe in Nextcloud 13 it was still okay-ish. (There were plenty of other instabilities, some of which are now fixed.) Then I upgraded to v20 or so (when I had a supported PHP version) and this became completely unusable for zero-duration appointments. The box height was almost zero and no text could be read at all. Now I upgraded to v21 and it's the other extreme, every short appointments makes the impression of going a bit more than a full hour, even more confusing the reader!

What is so hard to get this right? The old (ancient) Palm Desktop calendar from 2 decades ago did this right, but modern software (or maybe modern "developers") just aren't capable of these basics anymore. Nextcloud is so bad and becoming worse with each version.

The suggestion to set the box height to 15 min will make it unreadable again! Instead, the box height should be one line of text, maybe in a slightly smaller font, as already shown. It cannot be scaled to a fixed time, it needs to ba scaled to the font height. Anything else will cause problems sooner or later. If you don't understand this today, try it out and see the bug reports for v22.

**Comment by mrtumnus** [comment]
This has been addressed in #3272.  There was a name change of the one-line short event class, which resulted in these events not getting the special shorter minimum height of 15 min.

**Comment by mrtumnus** [comment]
@ValterMollar Your workaround is close, but this would still result in cut-off 2-line events when the event length is somewhere between 15 and 30 min.  Something better would be (this constrains the minimum to the short-type event):

.fc-v-event.fc-timegrid-event-short {
        min-height: 2em;
}

**Comment by mrtumnus** [comment]
With the workaround above, here's what @alexanderdd's example looks like:
![image](https://user-images.githubusercontent.com/1738198/125781822-3a2f57c7-61c6-43a8-8764-a1175d5ce4af.png)

**Comment by alexanderdd** [comment]
@mrtumnus so I add the code snippet from two comments above to the custom css field in settings? (After enabling the custom css app)

**Comment by mrtumnus** [comment]
Yep, that should do it. Might need to force refresh to get it to reload,
but that's what I'm using now.

**Comment by alexanderdd** [comment]
@mrtumnus @jonathantreffler @ChristophWurst  please triage this issue

**Comment by mrtumnus** [comment]
> @mrtumnus @JonathanTreffler @ChristophWurst please triage this issue

I'm not sure how to "triage".  I don't see anywhere to change labels; may not have permissions.  Can someone else disposition this issue?  The fix I mentioned above (#3272) is already in the roadmap for [v2.4.0](https://github.com/nextcloud/calendar/milestone/25).

**Comment by szaimen** [comment]
Fixed with https://github.com/nextcloud/calendar/pull/3272

**Comment by alexanderdd** [comment]
It works, thank you!!
