### ISSUE TITLE
Sharing single contacts and events

### ISSUE THREAD

**Issue by PackElend** [nextcloud/calendar#328]
I posting as suggest on the nextcloud forum in my thread Sharing single contacts and events by @MariusBluem. [This thread is already active in contacts](https://github.com/nextcloud/contacts/issues/111) but I duplicating it in order that it won't get forgotten for events.

I'm sick and tired setting up endless address bocks and calendar,depending with whom I going to share it with (wife, familly, friend, wokr, etc)
I would super happy if I could share single contacts and event with multiple nextcloud user.
Nextcloud has those features in-house so imho there isn't any extra programming necessary, isn't it?
All what would be necessary is to integrate nextcloud's sharing algorithm into contacts and calendar apps or do I miss some obstacles?

Should it be implemented @nextcloud/calendar 

I wouldn't mind to help dev as far as I can.

**Comment by georgehrke** [comment]
There are currently no plans to implement Single event sharing.
We had this feature before Nextcloud 9, but we switched to the standardized CalDAV sharing.
CalDAV sharing doesn't offer single event sharing.

Instead you can just invite people as attendees and share it this way.

**Comment by PackElend** [comment]
the way it is currently discussed in [contacts](https://github.com/nextcloud/contacts/issues/111) might be proper way.

**Comment by georgehrke** [comment]
This is not a real solution imho. 

Attendees don't work for you?

**Comment by PackElend** [comment]
Attendees are involved in the event but I would like to have guest.
They just shell see the event bit not being annoyed but it's notifications
setting.
It's purely informational.
The  suggested solution would even allow to work with groups like foreign
guest, friends and family.

The best would be even if calendar creates new CalDav calendars for each
receiver and/or group.  That would even allow non nextcloud user to
subscribe to my shared events.

The CalDav core remains untouched by this approach.

On Feb 3, 2017 18:16, "Georg Ehrke" <notifications@github.com> wrote:

This is not a real solution imho.

Attendees don't work for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nextcloud/calendar/issues/328#issuecomment-277306424>,
or mute the thread

**Comment by georgehrke** [comment]
> Attendees are involved in the event but I would like to have guest.

You can label attendees as "not attending"

> They just shell see the event bit not being annoyed but it's notifications
setting.

If you invite people to an event, everyone can decide on their own whether and when to get noficiations.

**Comment by georgehrke** [comment]
see above comment, can be achieved with attendees.

Closing
