### ISSUE TITLE
Repeating events are not converted to single events when setting reoccurance to 0

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#3282]
When an event was created with a repetition, the webUI does not allow to remove the repetition. The user can set the repetition to 0 days, but the event will still be a series with only one occurrence.

Setting the repetition frequency to none does the same thing. The even has no reoccurances, but is still a repeating event in the webUI AND on the calDAV interface.

**Comment by st3iny** [comment]
Bump at #3323
