### ISSUE TITLE
Sidebar editor usability

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#3289]
Followup to https://github.com/nextcloud/calendar/issues/3273, https://github.com/nextcloud/calendar/pull/3277 and https://github.com/nextcloud/calendar/pull/3278

The usability of our sidebar editor is not great at the moment. Up to version 2.2 you could scroll the whole sidebar. Recently, there has been a change in nextcloud-vue which made the top sticky and only the tabs scrollable. This is fine on large screens, but on small screens there is not enough height left for the tab view.

## Describe the solution you'd like
Make the whole sidebar scrollable again. This requires to either (partially) revert https://github.com/nextcloud/nextcloud-vue/commit/a6f48808d77e1f1a78f43b379be6375b7469790d or make the tab scrolling optional.

### Currently:

https://user-images.githubusercontent.com/1479486/124273466-55df0080-db40-11eb-9712-58d66932a297.mp4

### Without the changes from nextcloud-vue:

https://user-images.githubusercontent.com/1479486/124273469-56779700-db40-11eb-9061-476d936e91e1.mp4

**Comment by st3iny** [comment]
cc @GretaD @raimund-schluessler @tcitworld

**Comment by tcitworld** [comment]
Asking @skjnldsv opinions as well since they made the change in the library.

**Comment by raimund-schluessler** [comment]
I don't think this is a problem of the vue-components (at least not in version 4.0.x). In Tasks, we use nextcloud-vue@4.0.2 and the sidebar scrolls just fine on small screens (also the top part):

![sidebarscroll](https://user-images.githubusercontent.com/2496460/124276941-bbcd8700-db44-11eb-8a09-41e374714d80.gif)

**Comment by st3iny** [comment]
> I don't think this is a problem of the vue-components (at least not in version 4.0.x). In Tasks, we use nextcloud-vue@4.0.2 and the sidebar scrolls just fine on small screens (also the top part):

IMO, having 2 nested scroll bars is not great either. If we already have the outer scroll bar then what is the point of the tiny inner scroll bar just for tab contents? Maybe @skjnldsv can enlighten us about the reasoning behind those changes.

Thanks for pointing us to a solution though.
