### ISSUE TITLE
Design of month view

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/calendar#3300]
## Is your feature request related to a problem? Please describe.
* The current day is the start of the orientation inside the calendar grid but currently it is hard to find (especially if there are many colored events inside the month view).  
* I can't tell the current month from the days of the previous or next month. 

## Describe the solution you'd like
As a user of the calendar, I want an improved design which emphasizes relevant information, because it helps to get orientaition inside the calendar grid.

## Describe alternatives you've considered
Proposal as mockup: 

The current day (today) is more dominant and better/faster to identify. The darkening of days of the previous and following months emphasize the current month, which is the one of interest.

![grafik](https://user-images.githubusercontent.com/26707476/124504600-1a566780-ddc8-11eb-85cf-c19c519973c7.png)

Added CSS: 
```
.fc-daygrid-day.fc-day.fc-day-other, .fc .fc-daygrid-day.fc-day-today.fc-day-other {
	background-color: var(--color-background-dark) !important;
}

.fc-day-today .fc-daygrid-day-top {
	background-color: var(--color-primary);
}

```

Comparing current view:
![grafik](https://user-images.githubusercontent.com/26707476/124505474-dc5a4300-ddc9-11eb-97fa-9c55fa354332.png)

**Comment by szaimen** [comment]
@dartcafe do you mind opening a PR with your proposal for discussion? Thanks! :)

**Comment by dartcafe** [comment]
sure
