### ISSUE TITLE
New event: click on calender selection makes event disappear from calendar view

### ISSUE THREAD

**Issue by caugner** [nextcloud/calendar#3301]
### Steps to reproduce
1. Go to calendar.
2. Click at any time in the calendar to open the "New event" form on the right.
3. Notice that the event is displayed in the calendar view.
4. Click on the calendar select (below the "Event title" field).

### Expected behaviour
The new event should still be displayed in the calendar.

### Actual behaviour
The new event disappears from the calendar.

### Calendar app
**Calendar app version:** 2.3.0

**CalDAV-clients used:** Thunderbird Lightning (but issue affects web view)

### Client configuration
**Browser:** Firefox 91 (Nightly)

**Operating system:** Windows 10

### Server configuration

**Operating system**: (unknown)

**Web server:** Nginx

**Database:** MariaDB 10.3.30

**PHP version:** 7.4.16

**Nextcloud Version:** 20.0.9
**Updated from an older installed version or fresh install:** (unknown)

**List of activated apps:**

```
Accessibility
Activity
Calendar
Collaborative tags
Comments
Contacts Interaction
Dashboard
Deck
Deleted files
Federation
File sharing
First run wizard
Log Reader
Monitoring
Nextcloud announcements
Notifications
Password policy
PDF viewer
Photos
Privacy
Recommendations
Right click
Share by mail
Support
Tasks
Text
Update notification
Usage survey
User status
Versions
Video player
Weather status
Auditing / Logging
Default encryption module
Group folders
LDAP user and group backend
Theming
```

**Nextcloud configuration:**

(No access)

#### Web server error log (e.g. /var/log/apache)

(No access)

#### Log file (data/nextcloud.log)

(No access)

#### Browser log

(No browser log entry when the bug occurs.)

**Comment by GretaD** [comment]
I think this is a duplication of this one: #2968. Can you confirm @caugner ?

**Comment by caugner** [comment]
Good catch, I can confirm that clicking anywhere in the editor makes the event disappear in the calendar, so definitely a duplicate.
