### ISSUE TITLE
After updating to 2.3, web interface opens (almost) all the shared calendars

### ISSUE THREAD

**Issue by provelo-ict** [nextcloud/calendar#3306]
### Steps to reproduce
1. Have calendar 2.2.2 installed
2. Have many many calendars shared with eachothers, some shown in the web interface, most hidden
3. Update to calendar 2.3 
4. Reload the calendar app

### Expected behaviour

Only the calendars selected before the upgrade are shown, those which were hidden remain hidden.

### Actual behaviour

Most calendar (but not all - I haven't found what specific caracteristic of the calendar caused this. I would guess it is the ones that weren't explicitely shown and then hidden) shared with the user are shown.

In our case, that means 100+ calendars which need to be manually closed. It makes the interface very slow (our bad for having so many calendars so broadly shared).

I suppose this is related to the item "Show shared calendars by default" in the [changelog](https://github.com/nextcloud/calendar/releases/tag/v2.3.0) so I was not sure whether I should fill a bug or a feature request for a button to hide all calendars at once. Or an option not to have this default.

### Calendar app

Calendar app version: 2.3 

**CalDAV-clients used:** Thunderbird Lighting and DAVX5 mainly. But in this case it's on the web interface

### Client configuration
**Browser:** Firefox 89** (e.g. Firefox 48)

**Operating system:** Debian 11

### Server configuration

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 20.0.11

**Updated from an older installed version or fresh install:** updated from many older version (back in Owncloud times...)

**Comment by ChristophWurst** [comment]
sounds related to https://github.com/nextcloud/calendar/issues/3022. the default was changed in v2.3. now shared calendars are shown by default until they are hidden. before they were hidden until you manually unhid them.

**Comment by provelo-ict** [comment]
Thanks @ChristophWurst for pointing that out.

I understand there is a choice to be made regarding the default behavior and will not argue against the choice that has been made (I guess in most case it is relevant).

By any chance, do you know where the "hidden-shown" switch lies in the database, so that I can switch it manually to "hidden" for my users?

**Comment by tcitworld** [comment]
Unfortunately this can't be done easily.

You'll need to insert into `oc_properties` the following entries for each calendar:
| id | userid | propertypath | propertyname | propertyvalue |
|---|---|--|--|--|
| (autoincrement) | `myuser` | `calendars/myuser/calendarname` | `{http://owncloud.org/ns}calendar-enabled` | 0
