### ISSUE TITLE
Distribute invitations to group members

### ISSUE THREAD

**Issue by cetcondor** [nextcloud/calendar#3312]
**Is your feature request related to a problem? Please describe.**
When you create a calendar date and want to invite colleagues to it, you have to add each individual manually. A time-consuming task.

**Describe the solution you'd like**
It would be really helpful that one can choose an entire group as participants. The group members should automatically receive individual invitations, so that each person can accept or decline.

**Describe alternatives you've considered**
A joint calendar would not help because the group members can not accept/decline individually.

**Additional context**
Consideration about compatibility with CalDAV: It's probably not necessary that Nextcloud 'remembers' that a group was invited. It is probably enough for most use-cases that the group is split up to individual persons once the invitations are out.

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/calendar/issues/2955 or https://github.com/nextcloud/calendar/issues/167
