### ISSUE TITLE
write to shared calenders is ignored [if userspace is full]

### ISSUE THREAD

**Issue by produnis** [nextcloud/calendar#332]
### Steps to reproduce
1. Set up Nextcloud 11 with calendar 1.5.0
2. Create a calender for user A, share it with user B, give B write permission
3. Login as user B, edit calendar of user A
4. These edits are ignored
5. This error is given via Nextcloud Webpage (Firefox) and THunderbird Lightning(Client)

### Expected behaviour
Edits are saved in user A's calendar

### Actual behaviour
Edits are ignored

### Server configuration
**Operating system**: Linux 2.6.32-5-openvz-amd64

**Web server:** Apache/2.4.10 (Debian)

**Database:** MySQL 5.5.53 

**PHP version:** PHP Version 5.6.29-0+deb8u1

**Server version:** 11.0.1

**Calendar version:** 1.5.0

**Updated from an older installed version or fresh install:** fresh

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocfa1BLAFOOBARxpt1wdp',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => 'www.produnis.de',
  ),
  'datadirectory' => '/var/www/produnis.de/www./nextcloud/data',
  'overwrite.cli.url' => 'http://www.produnis.de/nextcloud',
  'dbtype' => 'mysql',
  'version' => '11.0.1.2',
  'dbname' => 'BLAd',
  'dbhost' => '10.0.0.FOO',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'DONALDTRUMP',
  'dbpassword' => 'SEEECREEET',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/... NO

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:** Firefox

**Operating system:** Arch linux

**CalDAV-clients:** Thunderbird Lightning

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by produnis** [comment]
I just found the solution:
The Webspace for User B was limited to 100 MB. These 100 MBs are reached, so there is "no space left". As a result, even calendar events are NOT SAVED

Maybe, nextcloud should state something like "Event not saved as you run out of space" or so...
in data/netxloud.log there is an error message like this...

**Comment by georgehrke** [comment]
Dup of https://github.com/nextcloud/server/issues/3085
