### ISSUE TITLE
Moving events back and forth between calendars causes trash bin conflicts

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/calendar#3325]
Moving an event to a different calendar B and back to the original calendar A is broken at the moment, because the original event is still present in calendar A due to how the trash bin works. See https://github.com/nextcloud/tasks/issues/1685 for the original report.

**Comment by tcitworld** [comment]
Shouldn't this be a server issue then?

**Comment by ChristophWurst** [comment]
depends on how moving works. I haven't checked the code yet.

**Comment by raimund-schluessler** [comment]
> Shouldn't this be a server issue then?

I guess this depends on what is intended here. There are multiple solutions and I am not sure what is the most logical one.

My tendency is to say that moving events should not create a trash bin entry, since the event is not deleted. This would restore compatibility with all clients. In that case, it's a Server issue.

**Comment by gohrner** [comment]
> My tendency is to say that moving events should not create a trash bin entry, since the event is not deleted. This would restore compatibility with all clients. In that case, it's a Server issue.

Note that a client which support multiple server connections may also move an event from one calender on one server to another calendar on a completely different server, of which the first server does not know anything.

This will look like a "delete" for the first server.

I'd vote for allowing to silently overwrite events in the trashbin, which also then restores the events from the trashbin.

This will fix the protocol for all clients, I'd presume.
