### ISSUE TITLE
Event END before BEGIN

### ISSUE THREAD

**Issue by michaelletzgus** [nextcloud/calendar#333]
Hi all,

current versions of the calendar app (nextcloud online demo, nightly from 2017-02-05) allow to enter dates and times which place the end before the begin.

Reproduce:
* Create new event
* Enter begin and end using the widgets
* Save it

Expected behaviour:
Do not allow this!
Pop up warning and/or correct the date/time automagically to the shortest meaningfull duration.

Actual behaviour:
Event is accepted with negative duration. 

Browser:
Firefox 51.0.1@Linux, no Javascript-error nor any other obvious problems in Firfox' console while creating the event.

Best regards
 Michael

**Comment by georgehrke** [comment]
please search for existing issues before creating new ones ...
thx

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/11
