### ISSUE TITLE
Deleted tasks show up as `Untitled event`

### ISSUE THREAD

**Issue by GretaD** [nextcloud/calendar#3330]

**Comment by GretaD** [comment]
Hey @raimund-schluessler . I cannot reproduce this one. CHeck if im testing it right.
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/12728974/125796719-363d9611-82ed-4cb7-9bda-2d0b720953f4.gif)

**Comment by raimund-schluessler** [comment]
> Hey @raimund-schluessler . I cannot reproduce this one. CHeck if im testing it right.
> 
> ![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/12728974/125796719-363d9611-82ed-4cb7-9bda-2d0b720953f4.gif)
> 
> 
> 
> 

@GretaD This is about *tasks/vtodos*, not events. Please create and delete a task in the Tasks app and check how it appears in the Calendar app trash bin.
