### ISSUE TITLE
Reccuring events can not be changed

### ISSUE THREAD

**Issue by AolAol** [nextcloud/calendar#334]
### Steps to reproduce
1.create a series of events recurring daily
2. you can not change/delete a single element of a recurring event (web-gui does not offer "this event or all events")
3.change/delete one of the events via external app (iphone, ical, thunderbird, ...)
4.web-view is wrong

### Expected behavior
1. The series of events should be editable via web-gui as on any other calendar (iphone, ical, thunderbird, ...)
2. It should show with single elements changed (via external apps (like iphone, ical, thunderbird, ...)

### Actual behavior
Calendar server behaves correctly, web-gui does not reflect actual data

### Server configuration
**Operating system**: ubuntu 16.04.1

**Web server:**apache 2.4.18

**Database:**mysql 5.7.17

**PHP version:**7.0.13

**Server version:** 11.0.1

**Calendar version:** 1.5.0

**Updated from an older installed version or fresh install:**both tested

**Signing status (ownCloud/Nextcloud 9.0 and above):**Nextcloud

**Comment by georgehrke** [comment]
Please search for existing events before creating new ones ......
thx

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/7

https://github.com/nextcloud/calendar/issues/142

**Comment by AolAol** [comment]
Sorry,

my searching did not give me those entries.

Br,
Andreas
