### ISSUE TITLE
Accept appointment invitations via the web interface

### ISSUE THREAD

**Issue by Tealk** [nextcloud/calendar#3341]
**Is your feature request related to a problem? Please describe.**
I would like to share appointments with different people in which they can accept or cancel individually.
I noticed that there is no such option in the web interface.
But on the iPhone I can do this without any problems 

**Describe the solution you'd like**
I would like to have an option on the web interface where you can accept or decline invitations, like you can on the iPhone.

**Describe alternatives you've considered**
I do not think that there is a suitable alternative to this

**Additional context**
![image](https://user-images.githubusercontent.com/12276250/126074225-006354c2-1323-4358-98f9-2e1115dc3985.png)

**Comment by sunjam** [comment]
This might need to be implemented in the appointments app.  Just food for thought

**Comment by Tealk** [comment]
> This might need to be implemented in the appointments app.

As far as I have seen, this app has its very own interface.
I just want to be able to click on a calendar entry and say yes or no.

**Comment by tcitworld** [comment]
Very related to #144

**Comment by Tealk** [comment]
Oh ok I must have used the wrong search terms, sorry

**Comment by ChristophWurst** [comment]
can we close this as duplicate?

**Comment by Tealk** [comment]
Yes i think so
