### ISSUE TITLE
Avatar loading issue on Nextcloud 22.0.0 and Calendar 2.3.1

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/calendar#3349]
Hi team,

If you add ppl, the avatars don't seem to load correctly, see this vid on tech-preview.nextcloud.com with user christine ([login details here](https://cloud.nextcloud.com/index.php/f/3406050)).

https://user-images.githubusercontent.com/551757/126483635-99e70862-a82e-4a9e-ac7e-b63a13a27392.mp4

Sometimes it shows the generic images for some, but not the actual user-chosen avatars:
<img width="406" alt="Screenshot_20210721_134652" src="https://user-images.githubusercontent.com/551757/126483754-5bf381e1-380b-4344-a0a9-56ede8b93578.png">

In Inspect, you see:

```
<img data-v-5baa2f3a="" src="/avatar/Christine%20Schott/32" srcset="/avatar/Christine%20Schott/32 1x, /avatar/Christine%20Schott/64 2x, /avatar/Christine%20Schott/128 4x" alt="">
```

Which doesn't seem to work. If you replace it with this, it does:
```
<img data-v-5baa2f3a="" src="/avatar/christine/32?v=5" srcset="/avatar/christine/64?v=5 2x, /avatar/christine/128?v=5 4x" alt="" >
```
That's the content from the user avatar in the top-right of the window.

<img width="242" alt="Screenshot_20210721_134955" src="https://user-images.githubusercontent.com/551757/126484097-f081824f-d86b-4052-a52a-a7394cc03984.png">

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/calendar/issues/3099

**Comment by jospoortvliet** [comment]
that's caught quickly, sorry for the duplicate, @tcitworld

**Comment by tcitworld** [comment]
That's because I've had a WIP PR on this for a while now. :sweat_smile:
