### ISSUE TITLE
re-layout issue on Nextcloud 22.0.0 and Calendar 2.3.1

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/calendar#3350]
When opening the sidebar, often the main area doesn't properly resize. Can't really figure out why - it sometimes works, sometimes not. Using latest Chromium on tech-preview.nextcloud.com

https://user-images.githubusercontent.com/551757/126484392-743c25db-774c-4d21-b207-d287c7cc570f.mp4

**Comment by ChristophWurst** [comment]
@st3iny are you aware of anything?

**Comment by st3iny** [comment]
Not at all. I'm using mostly Firefox and can't remember encountering this issue. Maybe its exclusive to Chrome or gone by now?

**Comment by miaulalala** [comment]
Fixed with the latest fullcalendar update
