### ISSUE TITLE
Handle multiple VCALENDAR blocks when importing ics file

### ISSUE THREAD

**Issue by thatsatoffee** [nextcloud/calendar#336]
### Steps to reproduce
1. Click Import Calendar button
2. Select ICS calendar file and upload it

### Expected behaviour
Contents of the calendar file should appear along with a new calendar.

### Actual behaviour
Received notification: "Calendar.ics - File is empty"

### Server configuration
**Operating system**: Raspbian Jessie

**Web server:** Apache 2.4.10
 
**Database:** MySQL 5.5.54

**PHP version:** PHP 5.6.29

**Server version:** Nextcloud 11.0.1 (stable)

**Calendar version:** Calendar 1.5.0

**Updated from an older installed version or fresh install:** Fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):** Sorry, but no idea what that means.

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:** 

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder

Enabled:
  - activity: 2.4.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "appstoreurl": "https:\/\/api.nextcloud.com\/v1",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "nc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_domains": [
            "<omitted>",
            "<omitted>"
        ],
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** No.

**Are you using encryption:** No.

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:** Firefox 50.1.0

**Operating system:** Linux Mint 18

**CalDAV-clients:** Irrelevant, none connected

#### Web server error log
```
[no entries whatsoever since installation of calendar app]
```

#### Log file (data/owncloud.log)
```
[nothing regarding calendar in any way, shape or form]
```

#### Browser log
```
[after selecting a file for uploading, nothing at all appears in the network log (except for regular notifications]
```

**Comment by georgehrke** [comment]
Can you please provide a cleaned version of the ics? 

Import works just fine for me, must be related to your ics data.

**Comment by thatsatoffee** [comment]
I'll try and get around to cleaning the ICS as soon as I can. For now, I can tell you that it's exported from Owncloud 4.0.4, also here's a single entry that looks pretty much like most of the rest of the entries (values in <angle brackets> have been manually replaced):

```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
CREATED:20101225T123155Z
LAST-MODIFIED:20101229T055831Z
DTSTAMP:20160318T093809Z
UID:<some id>@google.com
SUMMARY:California
STATUS:TENTATIVE
ATTENDEE;CN=<my name>;PARTSTAT=ACCEPTED;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTI
 CIPANT;X-NUM-GUESTS=0:mailto:<email>
CATEGORIES:http://schemas.google.com/g/2005#event
DTSTART:20110219T130000Z
DTEND:20110306T084000Z
X-LIC-ERROR;X-LIC-ERRORTYPE=VALUE-PARSE-ERROR:No value for LOCATION proper
 ty. Removing entire property:
SEQUENCE:0
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

Entries are separated by one blank line.

Many of the entries were indeed added through Thunderbird into a Google Calendar before I moved to Owncloud.

One additional piece of info: I tried a freshly installed Chromium for uploading the file to make sure it wasn't related to any of my browser addons, but that too didn't work (same error). It's still curious to me that no network traffic is happening, is the file parsed locally using JavaScript?

**Comment by thatsatoffee** [comment]
Apologies for the delay.

I didn't get around to cleaning my ics of every bit of personal information, however I compared it to a calendar exported by Google Calendar and found the problem: every single `VEVENT` in the calendar exported by owncloud was wrapped in its own `VCALENDAR`. After I removed every occurence of `{BEGIN|END}:VCALENDAR` except the very first and last, I was able to import my calendar (or at least schedule the import, it's still importing as of now which I'll attribute to the fact that my nextcloud instance is running on a Raspberry Pi).

I don't know enough about the iCalendar format to decide whether the plugin should be able to handle a file with several `VCALENDAR` sections, so I won't be closing this issue and instead wait for someone else to decide.

**Comment by georgehrke** [comment]
> I don't know enough about the iCalendar format to decide whether the plugin should be able to handle a file with several VCALENDAR sections, so I won't be closing this issue and instead wait for someone else to decide.

In theory multiple `VCALENDAR` blocks are not supported in the iCalendar format, but this is a special case.
The predecessor of this calendar app exported "broken" (as in multiple `VCALENDAR` blocks) ics files. That's why we should definitely add support for it.

**Comment by georgehrke** [comment]
btw, you don't have to provide a cleaned version of the ics anymore. Knowing it contains multiple `VCALENDAR` blocks should be enough to reproduce it.

**Comment by janLo** [comment]
I have the same problem with an export from davical.
