### ISSUE TITLE
Provide ICS link on public calendar web site

### ISSUE THREAD

**Issue by Kondamon** [nextcloud/calendar#338]
### Steps to reproduce
1. Share a calendar (share public link) 
2. Open this public link
3. Open the preferences

### Expected behaviour
There is no section which provides the .ics link.

You have to know that you need to add **?export** to the end of the link like this:
https://SERVER/remote.php/dav/public-calendars/ABCDEFGHIJKLM?export

Just this link can be imported to  e.g. Google Calendar (import external link) or OSX calendar via new calendar subscription.

### Actual behaviour
Just a CalDAV or WebDAV address is shown. This can't be imported in OSX calendar or Google calendar. You would need a password.

### Server configuration

**Server version:** Nextcloud 11.0.1 (stable)

**Calendar version:**  Calendar 1.5.0

**Comment by georgehrke** [comment]
It's WebCal (probably still called WebDav in your version)

**Comment by Kondamon** [comment]
OK, but shouldn't there be a .ICS link anywhere?

Most of the people want to import an calendar to an existing interface (e.g. Google calendar or on a mobile phone) and not checking another calendar on a web interface.

**Comment by georgehrke** [comment]
The WebDav link has the ics format.

**Comment by Kondamon** [comment]
Ok, sorry I didn't see this. For me at the beginning both links looked like the same. I was looking for an link ending with .ics and didn't find one on the page and with Google I found a solution. I'm not a very high skilled user. Just know some basics ;-)

For me it's now a bit unclear why there is a CalDAV link on a public calendar site. I think you always need a password and username for CalDAV, isn't it? Then it would make no sense for me providing a CalDAV link on an public site for external people who have no user account on the nextcloud server.

However, perhaps you could just consider to change the description to something more end user friendly? For example, something like this?
"CalDAV-Adresse für Clients" -> "Only for Clients with username"
"WebDAV-Adresse für Abonnements" -> "Subscription (ICS)"

**Comment by georgehrke** [comment]
> For me it's now a bit unclear why there is a CalDAV link on a public calendar site. I think you always need a password and username for CalDAV, isn't it? Then it would make no sense for me providing a CalDAV link on an public site for external people who have no user account on the nextcloud server.

This CalDAV endpoint doesn't require authentication

> However, perhaps you could just consider to change the description to something more end user friendly? For example, something like this?
"CalDAV-Adresse für Clients" -> "Only for Clients with username"
"WebDAV-Adresse für Abonnements" -> "Subscription (ICS)"

already renamed in the latest development version

**Comment by georgehrke** [comment]
It's called iCal-Feed now: https://github.com/nextcloud/calendar/blob/master/templates/part.publicinformations.php#L57
