### ISSUE TITLE
Edge case of free-busy does not show grey background

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3380]
### Steps to reproduce
1. Invite people with busy schedules to a meeting
2. View the free-busy view

### Expected behavior

Grey background for all slots where at least one person is busy.

### Actual behavior

Small glitch at 10:20 to 10:30 or something like that and at 13:30 to 14:00

![Bildschirmfoto von 2021-07-30 09-20-43](https://user-images.githubusercontent.com/1374172/127616485-428abf95-2a1e-46d2-8a59-5185ca8cf33b.png)

### Calendar app
**Calendar app version:** v2.3.1

Ref #3168 where @st3iny fixed a similar issue
Ref https://github.com/nextcloud/calendar/issues/3170 which would help develop this and prevent regressions

**Comment by miaulalala** [comment]
I can't reproduce:

![image](https://github.com/nextcloud/calendar/assets/7427347/c0934eff-b269-461e-99b3-771423cf91f7)

![image](https://github.com/nextcloud/calendar/assets/7427347/fc903fb1-593d-4883-b8f1-e64dcd9f13ee)
