### ISSUE TITLE
Calendar picker is not fully visible

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/calendar#3392]
![calendar picker not visible](https://user-images.githubusercontent.com/3769853/127776275-32c86e43-45cb-4a3d-94aa-1edbb944b62f.png)

### Steps to reproduce
1. Create event with Reminder -> "on date"
2. Open calendar picker

### Expected behaviour
Calendar picker should be full visible

### Actual behaviour
Calendar picker is not fully visible -> Look at screenshot

### Calendar app
2.3.1

### Client configuration
Firefox 90 for Ubuntu

**Operating system:** (e.g. Arch Linux)
Kubuntu

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 20.04

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
Sqlite3

**PHP version:** (e.g. 7.0.3)
7.4.3

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
21.02

**Comment by st3iny** [comment]
This is already fixed and will be included in the next releases (v2.3.2 and v2.4.0).

Ref https://github.com/nextcloud/calendar/pull/3370
