### ISSUE TITLE
Variable name instead timezone name

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/calendar#3393]
![variable name instead timezone name](https://user-images.githubusercontent.com/3769853/127776625-9e1e1071-d7f2-4754-ab8d-b4a543fe2ae5.png)

### Steps to reproduce
1. Create event with Reminder -> "on date"

### Expected behaviour
Timezone name should be visible

### Actual behaviour
Variable name is vible -> Look at screenshot

### Calendar app
2.3.1

### Client configuration
Firefox 90 for Ubuntu

**Operating system:** (e.g. Arch Linux)
Kubuntu

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 20.04

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
Sqlite3

**PHP version:** (e.g. 7.0.3)
7.4.3

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
21.02

**Comment by st3iny** [comment]
I can reproduce this bug on master branch as well. While editing the event and adding new alarms the timezone is displayed correctly. However, after saving the event, doing a reload and editing it again, the variable is not replaced anymore.

I suspect that `alarm.absoluteTimezoneId` is null or undefined here:
```js
			return t('calendar', 'on {time} ({timezoneId})', {
				time: moment(alarm.absoluteDate).locale(locale).format('LLLL'),
				timezoneId: alarm.absoluteTimezoneId,
			})
```
https://github.com/nextcloud/calendar/blob/7e9eced900e02b7601c10cf9f703a15770763c44/src/filters/alarmFormat.js#L100
