### ISSUE TITLE
Week view: date should be responsive

### ISSUE THREAD

**Issue by ya-d** [nextcloud/calendar#3397]
### Steps to reproduce
1. Open calendar.
2. Select week view.
3. Narrow window or open on mobile device.

### Expected behaviour
Date header should be reduced in width to fit column → strip year first, than month, than day to only show day of the week (don't know of international rules)

### Actual behaviour
Date string stays the same independently of column width → dates overlap each other and are rendered unreadable

Also visable: the whole view is quite unusable as no information for events is displayed. Only time of beginning which is already implied by the position in the grid. See #3103. 

### Calendar app
**Calendar app version:** 2.3.1

![image](https://user-images.githubusercontent.com/30781876/128488353-d65aace8-6930-42ef-82c0-ad5cf0806ff5.png)

**Comment by raimund-schluessler** [comment]
Fixed with https://github.com/nextcloud/calendar/pull/3376.

**Comment by ya-d** [comment]
Thanks! I only looked for issues, not PRs 😉
