### ISSUE TITLE
Send event description as text in attendee invitation emails

### ISSUE THREAD

**Issue by nolens** [nextcloud/calendar#340]
Hello,

When inviting attendees for events, calendar app is sending the .ics file via email. So far, so good.

But there is a **problem** with the current implementation:
In the current format of the invitation email, there is nothing else included but the plain .ics file. This might be _confusing_ to the recipients of the email, because as a consequence, important information what the event is actually about is not shown in the email, but only in the .ics file itself. 

There are **three major downsides** to this behavior:

1. There is no way for the attendee to evaluate wether the event is actually relevant for them and wether they would like to attend, as she/he can only see what the event is about by opening the .ics file. Many calendar clients do not show the description until the invitation is accepted. In this (realistic) scenario, attendees can only judge upon relevancy of the event until actually accepting it. This does not make sense, from my perspective.

2. There is something else that might be adding to the attendees confusion here: The sender address of the invitation emails is not the individual users address, but the general nextcloud email address - in my case "cloud@......net“. This makes it even harder for recipients to find out who is actually inviting them - and also whether the event is relevant to them.

3. Strict email spam filters have the behavior to sort out emails which do not contain any text content, but only an .ics file attachment. Not good either. 

So here are **two proposals** how to overcome this:

- add the content of the "description" field of the calendar event to the email that is being sent to attendees

- make sure that invitation emails are being sent from the individual nextcloud user address and _not_ from the "general" nextcloud account. 

What do you think?

Thanks and best regards

Thomas

**Comment by tcitworld** [comment]
> In the current format of the invitation email, there is nothing else included but the plain .ics file

Not sure about this, but do other clients support the message as a calendar invitation if it's done otherwise ?

**Comment by nolens** [comment]
It is a standard procedure from MS Outlook to send text with .ics attachments. 

So I would be very much astonished if any Email or calendar client has a problem with text in the email body...

**Comment by georgehrke** [comment]
Issues like these corresponding the CalDAV server belong in the [server repo](https://github.com/nextcloud/server).

And there are already two corresponding issues:
https://github.com/nextcloud/server/issues/2338
https://github.com/nextcloud/server/issues/2778
