### ISSUE TITLE
Encrypted calendar invitations

### ISSUE THREAD

**Issue by Lukas2112** [nextcloud/calendar#3403]
Is your feature request related to a problem? Please describe.
Unencrypted calendar invitations.

Describe the solution you'd like
Option to be able to upload an OpenPGP key or keychain so that the invitation could be sent encrypted to the internal and external appointment invitees.

Describe alternatives you've considered

Additional context

**Comment by ChristophWurst** [comment]
You could give https://github.com/tacruc/gpgmailer a try.
