### ISSUE TITLE
Add confirm() when deleting a calendar/event

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#341]
Yes, blocking modals suck, but right now there is no undo action. We are at a dead end with #148 and #149 and it will take at least another 2 or 3 months before https://github.com/nextcloud/server/issues/1662 is implemented and released as stable.

A blocking modals still sucks less than accidentally loosing an entire calendar.

**Comment by raimund-schluessler** [comment]
I know, @jancborchardt does not like modals, but maybe you want to have a look how the Tasks app does it: https://github.com/owncloud/tasks/pull/354.

**Comment by georgehrke** [comment]
Really like that idea :) 

Will probably use it here too.

**Comment by jancborchardt** [comment]
Ok … but I really hope we can gonforward with undo.

cc @nextcloud/javascript @ChristophWurst

**Comment by brantje** [comment]
It's possible to replace the default confirm function with a more styled one.
Example here: http://jsfiddle.net/k5uDw/16/

**Comment by skjnldsv** [comment]
Careful, the undo on tasks doesn't fit the css guidelines!

**Comment by raimund-schluessler** [comment]
> Careful, the undo on tasks doesn't fit the css guidelines!

Yes, the implementation in the Tasks app is older than https://github.com/nextcloud/server/pull/3024

**Comment by georgehrke** [comment]
> doesn't fit the css guidelines

Can I find these guidelines somewhere? ;)

**Comment by skjnldsv** [comment]
@georgehrke https://github.com/nextcloud/server/issues/2798
And https://docs.nextcloud.com/server/11/developer_manual/app/css.html

Not fully completed. Dev manual will be updated asap (need free time 😢  )
