### ISSUE TITLE
Get participant language and save it, so that invitation emails are sent with the correct language

### ISSUE THREAD

**Issue by PVince81** [nextcloud/calendar#3414]
### Steps

1. Have two users Alice and Bob
2. Login as "Alice"
3. Set the language to French "fr_FR" in the personal setting
4. Create a calendar event
5. Go to participants
6. Add user "Bob" as participant
7. Save the event
8. Check email for Bob

### Expected result
Email received by Bob is in English.

### Actual result
Email received by Bob is in French.

### Version
The one on c.nc.com

**Comment by tcitworld** [comment]
The server respects the attendee `LANGUAGE` properly so the issue is that the attendee dav search doesn't ask (in propfind) & return (no support from server anyway) the user language. The attendee contacts API search seems to have the contact language set properly.

**Comment by tcitworld** [comment]
Requires https://github.com/nextcloud/server/issues/28449 and https://github.com/nextcloud/cdav-library/issues/533
