### ISSUE TITLE
Show room suggestions

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3418]
Extracted from https://github.com/nextcloud/calendar/issues/3184

Requires https://github.com/nextcloud/calendar/issues/3543

**Comment by jancborchardt** [comment]
> not entirely convinced about finding out room availability only after saving, we can discuss with @jancborchardt as well later and fine tune a nicer workaround

Can you expand on that @st3iny @ChristophWurst? That would sound indeed a bit like a chore then to find an actually available room. :)

**Comment by ChristophWurst** [comment]
We'll have to test what's possible or not.
