### ISSUE TITLE
Dates in the upper row gets gibberish in week-view after update when accessed in mobile phone

### ISSUE THREAD

**Issue by rollanders** [nextcloud/calendar#3422]
I am on NC19.0.13. Want to update to at least NC20. But after the update the calendar view in the mobile (Android) gets gibberish. Before the update the dates were truncated and shown on two lines in the weekly wiew. Now the dont and they cover each other. and gets unreadable. Because of this I cannot upgrade. 
 
Before update (Calendar 2.0.5)
![image](https://user-images.githubusercontent.com/36486009/129851073-a82328cf-5055-40ca-8e22-93a29ae5385d.png)

After the update (Calendar 2.3.1)
![image](https://user-images.githubusercontent.com/36486009/129851137-e2191c4c-37fc-4599-a80e-00de6367bae3.png)

**Comment by tcitworld** [comment]
Should be fixed by https://github.com/nextcloud/calendar/pull/3376 (not perfect, but at least not gibberish) and related PRs in next version.
