### ISSUE TITLE
Better integration of Spreed to calendar

### ISSUE THREAD

**Issue by MagTheDev** [nextcloud/calendar#3429]
**Is your feature request related to a problem? Please describe.**
1. Add support for event invites that don't require email
2. Add the ability to accept/cancel events
3. Add a button in Upcoming events on Dashboard + in calendar to join call if meeting has a Talk link attached

**Describe the solution you'd like**
1. You can create invites to events without you and the person you're inviting to have their email set, everything would be processed internally

2. Basically, when someone invites you to an event in their calendar, it would be displayed 
    in your calendar and/or on dashboard (maybe with a checkmark or an X),  from which you could then 
    proceed to accept/cancel invitation. 
![image](https://user-images.githubusercontent.com/49731971/130938048-70e21670-9776-4f5e-8e62-e002248824c7.png)
![image](https://user-images.githubusercontent.com/49731971/130939840-0067ec45-a9ca-4d9f-ac76-ef9431e58891.png)

3. Every event with a Talk link attached would just have some sort of icon (maybe talk logo?), which when you clicked would redirect you to call
![image](https://user-images.githubusercontent.com/49731971/130938999-0db0f995-0f79-47fc-ab3b-2fc863ef57e6.png)
![image](https://user-images.githubusercontent.com/49731971/130940018-f2b3a093-7679-48f7-9e3f-852c227e89e9.png)

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by ChristophWurst** [comment]
Some of the improvements overlap with https://github.com/nextcloud/calendar/issues/3429

**Comment by tcitworld** [comment]
@ChristophWurst Wrong issue :p

**Comment by ChristophWurst** [comment]
But it's the truth. This totally overlaps with #3429 :see_no_evil:

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/issues/1839 is the one I wanted to link
