### ISSUE TITLE
l10n: There are no new translations of the Polish language in versions 2.3.2 and 2.3.3

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/calendar#3440]
In version 2.3.2 and 2.3.3, no new translations for the Polish language are added. They were downloaded from Transifex in [commits](https://github.com/nextcloud/calendar/commits/master/l10n/pl.js), but as of Jul 7, 2021 they were no longer added to the install versions.

@ChristophWurst Please check why this happened 😉.

**Comment by ChristophWurst** [comment]
because 2.3.3 was built from the stable2.3 branch. new translations go only into master. Translations are not backported because strings from master could be different in stableX and then other messages are lost. v2.4 will have your new translations
