### ISSUE TITLE
Missing icon of repeat tab

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#3443]
### Steps to reproduce
1. Open the sidebar to edit an event.

### Expected behaviour
All tab icons should be visible.

### Actual behaviour
The icon for repeat is missing.

### Calendar app
**Calendar app version:** master

Ref https://github.com/nextcloud/calendar/pull/3338#pullrequestreview-713612778
Caused by https://github.com/nextcloud/calendar/pull/3430

![Screenshot 2021-08-31 at 13-30-53 August 2021 - Calendar - Nextcloud](https://user-images.githubusercontent.com/1479486/131495442-04054123-92b4-4530-87a4-4731637b2a1b.png)

**Comment by ChristophWurst** [comment]
is it not related to caching? Ususaly those tab icons show after a refresh

**Comment by st3iny** [comment]
Not this one. Even tried `occ maintenance:repair` without success.

This seems to be an issue with the styling. I tried to set the width and height of the icon manually and then it is shown.

**Comment by ChristophWurst** [comment]
From https://github.com/nextcloud/calendar/issues/3184

> Move Reminders & Repeating from tabs to details, then we can have a "Rooms & resources" tab (needs shorter name)

So that tab has to move anyway, please don't spend too much time on fixing the icon but let's move the entire tab :wink:

**Comment by st3iny** [comment]
> From #3184
> 
> > Move Reminders & Repeating from tabs to details, then we can have a "Rooms & resources" tab (needs shorter name)
> 
> So that tab has to move anyway, please don't spend too much time on fixing the icon but let's move the entire tab wink

Ah right. I totally forgot about this one. Let's just ignore the missing icon for now :smile:
