### ISSUE TITLE
Preserve date when editing datetime with keyboard

### ISSUE THREAD

**Issue by FabianUntermoser** [nextcloud/calendar#3444]
Reproduce with:

1. Input a end date
2. Input a end time with the keyboard and press enter
3. the end date is reset to today

**Comment by ChristophWurst** [comment]
Can you also reproduce with the raw picker from https://nextcloud-vue-components.netlify.app/#/Components/Pickers?id=datetimepicker ?

**Comment by FabianUntermoser** [comment]
@ChristophWurst How exactly can I use the raw picker?
Do I have to builid nextcloud locally and swap the component or can I somethow enable this component in my selfhosted nextcloud instance?

**Comment by raimund-schluessler** [comment]
@FabianUntermoser How do you even use the keyboard to enter a time in the Calendar app? I couldn't find a way to do so, to be honest.

Anyway, we have similar issue in the Tasks app https://github.com/nextcloud/tasks/issues/1816, but there we use separate pickers for date and time.

**Comment by FabianUntermoser** [comment]
@ChristophWurst @raimund-schluessler 

I just noticed I meant to put this issue in the task's repo. The calender date works fine!

Sorry for the inconvenience! Closing this
