### ISSUE TITLE
Use material design icons?

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/calendar#3445]
In nextcloud-vue we now use material design icons provided by vue-materials-design-icons package. The Tasks app also already uses these icons (if you need a reference how this would look).

The icons are then bundled in the Javascript file and won't cause separate requests or briefly miss on first load anymore (also issues like https://github.com/nextcloud/calendar/issues/3443 would be a bit more unlikely).

Is it desired that we also migrate this app (and others later) to use these icons? If so, I would like to start working on this.

Since this is a general decision @jancborchardt @skjnldsv @ChristophWurst @tcitworld @nextcloud/designers should probably decide here.

**Comment by ChristophWurst** [comment]
No objections from my side. Sounds good :)
