### ISSUE TITLE
Calendar events < 2x(time increment) display too large

### ISSUE THREAD

**Issue by chenel** [nextcloud/calendar#3448]
Hi,

I'm using Calendar app version 2.3.3. on Nextcloud 21.0.4.  I've observed the behavior below on Firefox 91.0.2 and Chrome 92.0.4515.159 on ubuntu 20.04 (Linux).  This install has been upgraded numerous times.
(Server config, if relevant, is Ubuntu 20.04, Apache 2.4.41, PHP 7.4.)

I find that when I have calendar events that are shorter than twice the "time interval" set in the settings, they display too large by one time increment.  E.g.:

![calendar](https://user-images.githubusercontent.com/15690871/131842619-207b9243-f459-4ca3-8dbb-58d8b1d35018.png)
Here the event highlighted by the blue rectangle at the right side is only half an hour, but it takes up two half-hour increments visually.  (The rest of the screenshot is included so that you can see where the time increments lie.)

I've noticed that if I make the time increment smaller in the settings, the behavior persists at 20m but the event is the shown as the correct size once I get down to 15m, which suggests that there's an off-by-one issue when the event is less than twice the interval.

I can insert logfiles if they are deemed to be relevant, but the behavior happens every time, so logfiles seem less useful.  If requested I'm happy to add however.

**Comment by nybhtw** [comment]
Ha I've had this issue for a couple of months now, finally get time to address this, and right when someone else happens to post this.  Very cool.

I posted my details on the Nextcloud forum here: https://help.nextcloud.com/t/calendar-displays-events-longer-than-the-set-time/122662

I have two instances of Nextcloud, one at my office as version 21.0.4 installed on Ubuntu Server 18.04 in a VM inside of XCP-NG, and Calendar version 2.3.2.  

The one I have at my home does not have this issue, version 

Also on Ubuntu Server in a VM inside of XCP-NG.  Calendar version 

In the calendar, where an event is in the calendar set for 15 minutes, it shows as a 30 minute event. The 30 minute event is displayed as 30 or 45 minutes.

I have tried using the time increment setting to 15 and 30 minutes. When it is set to 15 minute time increments, 15 minute events show up as 30 minutes, and 30 minute events show up as 30 or 45 minutes.

When the time increment is set to 30 minutes, the same results occur. Some 30 minute events will appear as one hour in this setting.

Occasionally, when an event is immediately before or after another, the earlier event will actually be correctly displayed, and the following event will not. When there are multiple events (deck tasks and calendar events overlapping) then some are incorrect and some are correct.

I tested this on both displayed on Firefox 91.0.2 or Chrome 92.0.4515.159.

I have my calendars synchronizing on Thunderbird 78.11.0, where the events are shown correctly, as in a 15 minute event is displayed as 15 minutes, and so on.

Thank you all for your help.  I'm not sure what else to provide.  I just signed up for GitHub to report this as a bug after a reply on the Nextcloud Forum suggested I check to see if there was a bug report, and if not, then create one.

Here’s a few screen shots where you can see, in day and week view, how the times are off:

![image](https://user-images.githubusercontent.com/90003991/131906009-d12be975-040d-4e81-98c0-fed1a069206e.png)

![image](https://user-images.githubusercontent.com/90003991/131906081-bc4a4ef6-f72b-481e-8f98-962db954d04e.png)

**Comment by tcitworld** [comment]
Is this the same issue than #3275 ?

**Comment by chenel** [comment]
Ah, yes, it looks like it is!  I apparently didn't find the right words to search when I was looking for previous issues. :(

**Comment by tcitworld** [comment]
No worries, thanks for the confirmation!
