### ISSUE TITLE
Timepicker ununderstandable

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/calendar#345]
I think of myself as a person that is able to understand the concept of time. But how the hell am I supposed to create an event for 14:00 here? And why are there numbers twice?

<img width="530" alt="screen shot 2017-02-20 at 10 31 26" src="https://cloud.githubusercontent.com/assets/878997/23119299/f1c36094-f757-11e6-91e2-c0f82f3c9c3e.png">

cc @georgehrke On c.nc.c

**Comment by georgehrke** [comment]
There are supposed to be am/pm labels. oO
will check
