### ISSUE TITLE
On birthdays, Calendar displays the year of birth instead of the age

### ISSUE THREAD

**Issue by Kalytis** [nextcloud/calendar#3456]
### Steps to reproduce
1. Adding a birth date including the year in a contact card
2. Activating the birthday calendar in NC

### Expected behaviour
On the birthday, after the name, Calendar should show the age of the person.

### Actual behaviour
After the name, Calendar shows the year of birth.

### Calendar app
**Calendar app version:** v2.3.3

**CalDAV-clients used:** Thunderbird Lightning, Nextcloud web app, Etar Calendar

Thanks by advance

**Comment by raimund-schluessler** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/940

**Comment by tcitworld** [comment]
Also related https://github.com/nextcloud/server/issues/12462

**Comment by Kalytis** [comment]
Hi, the problem still occurs, any news on this please ?
