### ISSUE TITLE
In Dark Mode the button to switch between day/week/month is invisible

### ISSUE THREAD

**Issue by freekvh** [nextcloud/calendar#3461]
I can fill in all the details in text, but these screenshots say it all, the button to select day/week/month/list has the same color as the background and it thus took me some time to find it.

Not hovering:
![image](https://user-images.githubusercontent.com/12241293/132473332-1c2e82b6-eeb9-433f-b335-a74b330db711.png)

Hovering and clicked:
![image](https://user-images.githubusercontent.com/12241293/132473197-49bc5026-2607-4e07-b966-fde95be906d2.png)

**Comment by raimund-schluessler** [comment]
I suspect this is a browser cache issue (especially since other icons are also missing). Please reload the page with clearing the cache (should work with Ctrl + F5).

Anyway such icon problems should be fixed by #3447 as well.

**Comment by freekvh** [comment]
> 
> 
> I suspect this is a browser cache issue (especially since other icons are also missing). Please reload the page with clearing the cache (should work with Ctrl + F5).
> 
> Anyway such icon problems should be fixed by #3447 as well.

Ah, indeed, this worked, apologies. The button could still be a bit clearer though, but that is probably indeed helped by #3447 then :)

![image](https://user-images.githubusercontent.com/12241293/132474717-1ece86a6-0827-4fa1-a979-ee47bca10eaa.png)

Thank you for the swift reply, I'll close this.

**Comment by raimund-schluessler** [comment]
Hm, the icons still have the wrong color, they should be white in dark mode. Works fine here, maybe give it another refresh 🙈

**Comment by freekvh** [comment]
> 
> 
> Hm, the icons still have the wrong color, they should be white in dark mode. Works fine here, maybe give it another refresh 🙈

ok, clearing all site cache data in FireFox indeed did the trick finally, I had this going for a very long time, thanks!!

![image](https://user-images.githubusercontent.com/12241293/132477549-e5cb5530-42c7-4e2a-b035-46c3f599ba67.png)
