### ISSUE TITLE
There was no plugin in the system that was willing to handle this POST method

### ISSUE THREAD

**Issue by sporykhin** [nextcloud/calendar#347]
Hey

I'm trying to implement nextcloud file sharing solution that uses sabre/dav as backend for Calendar web application. In the web browser everything is really nice. Then I connected Calendar.app to this service I got only limited feature list - I cant share calendar and cant send email invitation on some event.
Also I have a lot of errors in server log with main point - Sabre\DAV\Exception\NotImplemented: HTTP/1.1 501 There was no plugin in the system that was willing to handle this POST method.

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
/var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')

Is it system misconfiguration or some bug?

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
