### ISSUE TITLE
Provide appointment slots for a given time span via REST API

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3477]
* Extrapolate slots based on availability, duration, increment, …
 * Exclude days where the max number of slots is reached
 * Exclude slots that are not available a booking conflict
    + Requires https://github.com/nextcloud/server/pull/28970
    + https://github.com/nextcloud/calendar/issues/3193 would possibly be a good addition to the logic. We need to get access to calendar properties to filter out the transparent ones. This is possibly a task for later on. If so, let's create a separate ticket so we don't forget.

**Comment by miaulalala** [comment]
PR here: #3470
