### ISSUE TITLE
Ability to Clone/Duplicate Calendar items for future appts

### ISSUE THREAD

**Issue by sbs0518** [nextcloud/calendar#3485]
As NextCloud is intended to be a self-hosted platform with like functionality to Google etc., the Calendar app for NC while very nice, lacks this one very desired feature that I am able to use in Google Calendar but not here.

In Google Calendar, when you single-left-click a calendar item, it brings up a dialog for that appointment.  In that dialog is a 3-dot menu that allows you to select a "Duplicate" option which then opens a detail screen so that a future date/time can be selected and then clicking ok adds that new item to the calendar.  This is a major time saver in that the user does not have to recreate all of the associated details of the cloned/duplicated appointment.

Screenshot provided for clarity.
![2021-09-15 09_15_14-Google Calendar - September 2021 and 39 more pages - SBS - Microsoft​ Edge](https://user-images.githubusercontent.com/90774233/133440516-93736af9-b9fa-4dd5-b10e-d8c90fb62488.png)

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/113
