### ISSUE TITLE
Calendar monthly view unreadable in Firefox

### ISSUE THREAD

**Issue by MultiCoreNop** [nextcloud/calendar#3487]
### Steps to reproduce
1. open monthly view

### Expected behaviour
Events should be readable

### Actual behaviour
They are not

### Calendar app
Breaking change is from 2.2.2 -> 2.3.1
'offending' commit is 953d4913f52d01e96d38e29f7e2d24767b6ec638
On a first glance it seems to be the update of externals (I would guess fullcalendar/daygrid - but did not check that).

### Client configuration
**Browser:**
Bug appears on
Firefox 91.0.2
Firefox on Android

Google Chrome has no problems and renders correctly.

**PHP version:**
7.3

**Nextcloud Version:**
20.0.5
20.0.9
22.1.1

Not all calendar entries are on top of each other. This happens for several "calendars", but not for all events. I could not yet find a pattern when a day is scrambled and when it is not.

Calendar 2.2.2
![nextcloud-calendar 2 2 2](https://user-images.githubusercontent.com/244375/133797114-bf305593-e507-478d-994c-a3cea90e8ee3.jpg)
Calendar 2.3.1
![nextcloud-calendar 2 3 1](https://user-images.githubusercontent.com/244375/133797120-d8ac62d1-7d95-4a07-83f3-4b079a77a452.jpg)

**Comment by szaimen** [comment]
Hi, is this still happening in the latest calendar release?

**Comment by MultiCoreNop** [comment]
No, it did not happen anymore since some time already. Only "empty slots" do occur occasionally, but at least it's readable. I'll close this one then.
Thanks for the reminder!
