### ISSUE TITLE
global timezones broken

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#35]
from @wrexroad

### Steps to reproduce
1. Create a new event by clicking a date on the calendar.
2. Click the "More" option.
3. Select UTC, GMT, or Z timezone.
4. Click "Create" (or "Update" for an existing event).

### Expected behaviour
A new event with a global timezone should be created.

### Actual behaviour
The creating the event fails silently and the sidebar does not close.

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
Nextcloud 9.0.53 (stable)
**Calendar version:** (see ownCloud apps page)
1.3.1 (Also tested on GitHub master branch commit 8addb4).
**Updated from an older ownCloud or fresh install:**
Freshly built from GitHub repo.
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

### Client configuration
**Browser:**
Chrome
**Operating system:**
Fedora 24

**Comment by georgehrke** [comment]
@wrexroad you said you were looking forward to fixing it this weekend. Can you send the pull request against this repository? :)

**Comment by wrexroad** [comment]
Yes, I will push the update here. It looks like this is going to get bumped until tomorrow though.
