### ISSUE TITLE
event which ends before it starts

### ISSUE THREAD

**Issue by beccon4** [nextcloud/calendar#350]
### Steps to reproduce
1. Create an event in calendar which end date is before start date

### Expected behaviour
The calendar complains and refuses saving.

### Actual behaviour
It created the event, it appeared as normal in the calendar - it even sync'ed with Android but failed to appear in evolution ((evolution:31809): calendar-gui-CRITICAL **: e_week_view_add_event: assertion 'start <= end' failed)

It applies both to single and reucurring events.

### Server configuration
Linux, Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7

**Server version:** (see your admin page)
11.0.1 (stable)

**Calendar version:** (see the apps page)
1.5.0

**Updated from an older installed version or fresh install:**
fresh install

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/11

**Comment by georgehrke** [comment]
please search for existing issues before creating new ones! thx :)

**Comment by beccon4** [comment]
searched for start and end :-) Thank you.
