### ISSUE TITLE
Integrate appointments on the profile page

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3541]
Ref https://github.com/nextcloud/server/pull/28139

@jancborchardt @nimishavijay please spec how this should work, ideally with a few screenshots that demonstrate the expected interaction

* What will be rendered if the profile's users has no appointment configurations?
* What will be rendered if the profile user has one publicly visible appointment configuration?
* What will be rendered if the profile user has more than one publicly visible appointment configuration?

For your information, *appointment configuration* is the technical term for one of the appointment slot patterns that you can possibly create. Example: *Coffee call*, *Lunch at the buffet*, *Consultation* and so on. Users can have none or as many appointment configurations as they like.

**Comment by jancborchardt** [comment]
On Profile, it would just be a link (in the form of a button) to the "Public appointment booking page" as listed in https://github.com/nextcloud/calendar/issues/3484

If someone has multiple appointment configurations, we can go multiple ways depending on what is possible in the remaining time:
- Have an overview page for different appointment configurations, like Calendly does
- Have a dropdown in the Profile info settings to choose the appointment configuration you want the button on your profile page to link to

**Comment by ChristophWurst** [comment]
> On Profile, it would just be a link (in the form of a button) to the "Public appointment booking page" as listed in #3484

FYI I've created https://github.com/nextcloud/calendar/issues/3542 because the overview page and the booking page are two different features.

**Comment by ChristophWurst** [comment]
Done with https://github.com/nextcloud/calendar/pull/3574
