### ISSUE TITLE
Public appointment configurations overview page

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3542]
*Have an overview page for different appointment configurations, like Calendly does*

From https://github.com/nextcloud/calendar/issues/3541#issuecomment-941056439

This page will show all public appointment slots of one user, or none if there are none or no public ones.

**Comment by jancborchardt** [comment]
For reference already, this is how it looks for Calendly, just a simple grid overview with the person’s avatar and name on top (the description we could leave out for first version – we could put the Profile link though if it’s enabled?). You can test it directly via https://calendly.com/jantest/
![Calendly overview shared](https://user-images.githubusercontent.com/925062/137119412-60827ee6-8498-49f3-9d84-cab9ccccd007.png)

**Comment by ChristophWurst** [comment]
Shall we copy this design for our page?

**Comment by ChristophWurst** [comment]
> As mentioned in the chat: How about actually putting it on the Profile directly?

The profile API only allows us to render exactly one link: https://github.com/nextcloud/server/issues/28139#issuecomment-941031840.

With this limitation I don't see a way around an overview page for now.



> Only question is: What happens if the Profile is disabled?

As I read from your description the profile page will be the one and only entry point for someone to discover public appointment slots of another user, right? Like if you create a *coffee call* config for everyone but disable your profile, I'm simply out of luck. I can still book an appointment if you share your link. But I won't be able to discover that booking page myself, yep.

**Comment by nimishavijay** [comment]
The overview page would probably be best for the first version of this. The Calendly design looks good, we can go ahead with that. Suggestions for design from my end: 
- have the Nextcloud header bar on top with the logo like always do
- get rid of the "card background" and have all the configs directly on the page
- include a link to the person's Profile in the description part
- the colour next to each config would be of the calendar that that particular config is associated with
- less vertical whitespace between the config cards 

What do you think?

**Comment by ChristophWurst** [comment]
> the colour next to each config would be of the calendar that that particular config is associated with

For clarification there is no such limitation that you need one calendar per config. So I assume for the simple setups the color would always reflect the color of the *personal calendar* and all configs have the same background color.

**Comment by ChristophWurst** [comment]
There are two aspects of calendars for a config
* Calendars to check for conflicts (none, one or many)
* Calendar to write the booked appointment (exactly one)

Configs will be shown underneath the calendars, similar to circles in Contacts. They are a separate list: https://github.com/nextcloud/calendar/issues/3483
