### ISSUE TITLE
can not share calendar with more than one calendar [ resolved, not a bug]

### ISSUE THREAD

**Issue by jerome-diver** [nextcloud/calendar#356]
Used with Nextcloud-11.0.2
### Steps to reproduce
1. create 2 calendar
2. share first calendar (user list is find)
3. try to share with the second calendar (user list never find... it's like there is no user or group)

### Expected behaviour
it should be possile to share more than one calendar.
The user/group list should appear for the second calendar.

### Actual behaviour
User list does not appear, so it is impossible to share the second calendar.

### Server configuration
**Operating system**: arch linux

**Web server:** nginx

**Database:** postgresql

**PHP version:** 7

**Server version:** (see your admin page)

**Calendar version:** (see the apps page) 1.5.1

**Updated from an older installed version or fresh install:**updated from nextcloud 10, last updated calendar version on march, the 2 of year 2017

**Signing status (ownCloud/Nextcloud 9.0 and above):** nextcloud-11.0.2

**Comment by georgehrke** [comment]
can't reproduce

**Comment by georgehrke** [comment]
please provide logs as requested in the issue template

**Comment by jerome-diver** [comment]
hi @georgehrke, 
finaly it is not an issue.
I had to change option for share in personnal configuration.
then it works fine.
Sorry for wrong alert issue, it was my fault.
good job guys, have a good day.

**Comment by georgehrke** [comment]
> I had to change option for share in personnal configuration.

Which option? :)

**Comment by georgehrke** [comment]
@jerome-diver Can you please tell me which option you changed? :)

**Comment by jerome-diver** [comment]
@georgehrke, yes sure.
I do enable in "administration" page, inside "share" tab, the share groupe autority check box for be able to share with other group than the user one (my user is the admin one, and users are in "users" group.
That was why it didn't works (that is logically normal and this is not a bug).
Thank you

**Comment by georgehrke** [comment]
Ah, ok :) 

Thx
