### ISSUE TITLE
Overlapping menu button in list view

### ISSUE THREAD

**Issue by mokkin** [nextcloud/calendar#3564]
Nextcloud 22
Firefox 93.0
![image](https://user-images.githubusercontent.com/2938748/137900196-757429e8-00f9-44a3-880a-4b0214e55501.png)

**Comment by GretaD** [comment]
Hello Mokkin, 
thank you for your report,

we are aware of the problem and its a problem that is preset on all apps, but it is not an easy fix it as its not a matter of adding some space on top. We are discussing about solutions and eventually we will fix it for all the apps.
