### ISSUE TITLE
Calendar search results in chronological order?

### ISSUE THREAD

**Issue by jkpirie** [nextcloud/calendar#3569]
Hi everyone,
I guess that this is a feature request but might just as easily be a bug report?  
When I type a search string into the unified search box, top right of NC I get a list of all instances of that string which is really cool and exactly what I want to happen.  However, the calendar results seem to be displayed in a totally random order which is not really useful in the context of a Calendaring app.  I have an extensive calendar reaching back several years which I use for reference to the past as well as present and future data.  
An example of my use would be keeping track of date expired stock.  If I search for an item name I am used to being presented with all instances of that item in a date ordered list from, for example, Fastmail calendar.  In Nextcloud calendar I get a list but the first one in the list can be from 2015 and then followed by a similar item from 2023 and so on.  I find I cannot use the Calendar app for what I want to because of this.  
Is it possible to amend this behaviour at some point? i.e. get a chronological list of results from the Calendar app even just from today's date into the future?  

Many thanks for all your work, I only wish I had the ability to assist.

James

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/server/issues/27353
