### ISSUE TITLE
Reminder text isn't shown correctly

### ISSUE THREAD

**Issue by enboig** [nextcloud/calendar#357]
### Steps to reproduce
1. Configure your account in catalan
2. Create a sound alarm

### Expected behaviour
You should read `So d'alarma`

### Actual behaviour
You read `So d&#039;alarma`

**Comment by tcitworld** [comment]
Please checkout the translations here : https://www.transifex.com/nextcloud/nextcloud/ to propose a change.

**Comment by enboig** [comment]
I already checked:
https://www.transifex.com/nextcloud/nextcloud/translate/#ca/calendar/98255641?q=alarm
It appear to be ok there.

**Comment by tcitworld** [comment]
Since the strings in expected behaviour and actual behaviour are the same, what's the issue ?

**Comment by enboig** [comment]
Sorry, I didn't chek my first post after posting it. The actual behavior is "So d & # 0 3 9 ; alarma"

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/269

**Comment by georgehrke** [comment]
indeed seems like an issue with t

@tcitworld can you report a bug in the server repo? :)
