### ISSUE TITLE
unknown timezone (America/Argentina/Buenos_Aires) back to UTC

### ISSUE THREAD

**Issue by verahert** [nextcloud/calendar#358]
### Steps to reproduce
1. Open the calendar with this adress .../index.php/apps/calendar/ or .../index.php/apps/calendar

### Expected behaviour
It should load the calendar app

### Actual behaviour
Isn't loading the calendar app and message say: 
"You are in an unknown timezone (America/Argentina/Buenos_Aires), falling back to UTC"

### Server configuration
**Operating system:** Debian 8.6

**Web server:** nginx/1.6.2

**Database:** mysql  Ver 15.1 Distrib 10.0.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.0.12-1~dotdeb+8.1 (cli) ( NTS )

**Server version:** Nextcloud 11.0.2

**Calendar version:** Calendar 1.5.1

**Updated from an older installed version or fresh install:** Updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc2329pm0f1v',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'nextcloud.melflix.net',
  ),
  'datadirectory' => '/emli2/Nextcloud',
  'overwrite.cli.url' => 'https://nextcloud.melflix.net:8443',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextclouduser',
  'dbpassword' => ,
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'appstore.experimental.enabled' => true,
  'updater.release.channel' => 'stable',
  'loglevel' => 3,
  'maintenance' => false,
  'theme' => '',
  'updater.secret' => 
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox 51.0.1

**Operating system:** Windows 10 x64

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
1. Please provide logs
2. What do you mean with "isn't loading". Can you attach a screenshot please?

**Comment by verahert** [comment]
The calendar APP load but my calendars stay in loading state:

![image](https://cloud.githubusercontent.com/assets/26186661/23580564/f06ee396-00e2-11e7-93d2-86a589fe5db0.png)

I've cleaned all logs, put loglevel = 0 and restart nextcloud the I reproduce the error and the nextcloud.log has:

{"reqId":"gKg288Fv6E7IgebSYR7i","remoteAddr":"190.55.176.116","app":"no app in context","message":"Invalidating session tokens older than 2017-03-03T16:57:53+00:00","level":0,"time":"2017-03-04T16:57:53+00:00","method":"GET","url":"\/cron.php","user":"--","version":"11.0.2.7"}

{"reqId":"gKg288Fv6E7IgebSYR7i","remoteAddr":"190.55.176.116","app":"no app in context","message":"Invalidating remembered session tokens older than 2017-02-17T16:57:53+00:00","level":0,"time":"2017-03-04T16:57:53+00:00","method":"GET","url":"\/cron.php","user":"--","version":"11.0.2.7"}

**Comment by georgehrke** [comment]
Please provide JavaScript browser logs :)

**Comment by verahert** [comment]
Use of attributes’ textContent attribute is deprecated. Use value instead.  app.min.js:2:4429
The resource from “https://nextcloud.melflix.net:8443/apps/files/” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).  (unknown)
The resource from “https://nextcloud.melflix.net:8443/apps/files/” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

**Comment by asoliverez** [comment]
I have exactly the same issue, with the same timezone

**Comment by bastoGrande** [comment]
Exactly the same problem here!

**Comment by georgehrke** [comment]
@verahert @asoliverez @bastoGrande Was this issue introduced with 1.5.1 or didn't you use any earlier versions.

**Comment by bastoGrande** [comment]
I experience it since 1.5.1,but unfortunately I don't know if it already exist before. 

I know, not a big help..

**Comment by asoliverez** [comment]
It's new. I've used 1.5.0 and previous versions and it was working fine

**Comment by verahert** [comment]
The problem appear after I upgrade Nextcloud to version 11.0.2

**Comment by georgehrke** [comment]
This was introduced with 1.5.1
Fixing it ...

**Comment by waeltken** [comment]
Would be great to see this merged.

**Comment by bastoGrande** [comment]
So it seems that my second problem will not be fixed with this issue (or is maybe already fixed?).

Should I create a new issue or how do you guys handle this?

**Comment by georgehrke** [comment]
> Should I create a new issue or how do you guys handle this?

one issue per bug. Please create a new issue ;)

**Comment by georgehrke** [comment]
@waeltken There is another bug I want to fix. Events should load even if it falls back to UTC. That's not the case at the moment.

**Comment by waeltken** [comment]
@georgehrke saying you won't merge this until there is a fix for the fallback to UTC bug?

**Comment by georgehrke** [comment]
> @georgehrke meaning you won't merge this until there is a fix for the fallback to UTC bug?

Correct, but I'm looking forward to fixing this later today or later this week. I don't intend to keep this PR open for weeks
