### ISSUE TITLE
Add option to select a specific illustration.

### ISSUE THREAD

**Issue by SteffoSpieler** [nextcloud/calendar#3584]
**Is your feature request related to a problem? Please describe.**
Sometimes I have a calendar entry which name doesn't fit the set terms of the illustrations.

**Describe the solution you'd like**
I think it would be great if we could select an illustration when clicking on the illustration (e.g. in the sidebar)

**Describe alternatives you've considered**
Changing the name of the calendar entry to show the correct illustration, but sounding really bad.

**Comment by ChristophWurst** [comment]
cc @nextcloud/designers

**Comment by tcitworld** [comment]
Would require to save the setting into a specific `X-Nextcloud-Illustration` iCalendar property just for this, not sure if worth it. Maybe first try to improve matching?

**Comment by SteffoSpieler** [comment]
> Maybe first try to improve matching?

That could be done, but there will always be something missing from the matching. So yes, improving the matching would be a good idea, but in the end it would be more work to add more and more keywords when something is missing instead of adding the specific `X-Nextcloud-Illustration` property once.

**Comment by ChristophWurst** [comment]
We also have to be reasonable with the what is configurable for the user and what is not. Personally I think this goes a bit too far, hence I would definitely rather improve the matching than add a UI control for this.

**Comment by st3iny** [comment]
Closing because illustrations were removed in the meantime.
