### ISSUE TITLE
Add option to attach a file to an event

### ISSUE THREAD

**Issue by PA3LIT0** [nextcloud/calendar#3587]
**Is your feature request related to a problem? Please describe.**
Many times I would like to attach a file/files to a specific event but unfortunately there is no option to that yet :(

**Describe the solution you'd like**
I think the best solution would be to add something similar to the image below (example from the deck nextcloud app):
![image](https://user-images.githubusercontent.com/71569166/139540138-4cadd127-4f96-4e19-9e69-c46e59c247bd.png)

Popup when clicking "share from files":
![image](https://user-images.githubusercontent.com/71569166/139540179-a098e644-e960-41f0-b027-472a82c3a6e6.png)

**Describe alternatives you've considered**
Add link in the "description" section of an event, but that would look very bad and would be very impractical

**Comment by tcitworld** [comment]
Duplicate from #298
