### ISSUE TITLE
Changing a recurring event leads to misleading email

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/calendar#3618]
- have a 1:1 call every Tuesday at 9-10
- other change it one time to e.g 9:30 - 10
- I receive this mail:
![image](https://user-images.githubusercontent.com/5836855/140873692-061dedcb-ec63-4dcf-a3a2-e85732a6ee4e.png)

--> this shows only start of recurring event, but it should show what changed (e.g. that today it is 9:30-10:00).
In calendar/Thunderbird I can see the updated event.

**Comment by ChristophWurst** [comment]
Please report at https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C+0.+Needs+triage&template=Bug_report.md. Invitations are sent by the CalDAV back-end.
