### ISSUE TITLE
No Cal Invitations 

### ISSUE THREAD

**Issue by rabadumpf** [nextcloud/calendar#363]
### Steps to reproduce
1. create appointment
2. enter adresses for invitation
3. save

### Expected behaviour
thunderbird created a mesage if i would like to send the invitation
thinderbird sends invitation

### Actual behaviour
nothing happens after saving of new appointment, and no message is sent
in the window for new appointament in "invitation" the field for "send invitation" is gray and can´t click.

### Server configuration
**Operating system**:
Windows 10, ubuntu 16.10, linuxmint 18.1
**Web server:**
apache2
**Database:**
mysql 5.7.17
**PHP version:**
7.0.15
**Server version:** (see your admin page)
apache 2.4.18
**Calendar version:** (see the apps page)
1.5.1
**Updated from an older installed version or fresh install:**
updated
**Signing status (ownCloud/Nextcloud 9.0 and above):**
nextcloud 11.0.2
```

```

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
