### ISSUE TITLE
Make it possible to rename "contact_birthdays" 

### ISSUE THREAD

**Issue by kbabioch** [nextcloud/calendar#364]
I'm glad that there is this feature (show birthdays of contacts) in the calendar app. However, it seems that the name of the appropriate calendar is hard-coded to `contact_birthdays`. This is a good-enough default value, but it seems that it cannot be changed. I have multilingual nextcloud instance, so it would be great, if this string could be changed by the user (and/or localized into the choosen language at least).

**Comment by tcitworld** [comment]
Personal default calendar and contacts birthday contacts should be already translated in user's language (maybe only for new users).

Anyway, beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
