### ISSUE TITLE
Calendar widget is empty after update to 22.2.2

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/calendar#3649]
calendar: 2.3.4

same with: 23.0.0 RC2 and v2.4.0 RC1

![image](https://user-images.githubusercontent.com/24530680/141645076-14bad1f0-97c5-487c-8c33-497ec77007dd.png)

**Comment by flatterrich** [comment]
the same here

**Comment by ChristophWurst** [comment]
I can reproduce with one of the two productive instances that I have access to. So this bug seems to depend on some event data.

**Comment by ChristophWurst** [comment]
![Bildschirmfoto von 2021-11-15 11-06-59](https://user-images.githubusercontent.com/1374172/141762753-0ffa566e-9882-4440-a228-adfbee51c733.png)

So for me it's this code https://github.com/nextcloud/calendar/blob/b12b1d5acda168fa6715fdbb2384119493eb8e67/src/store/calendars.js#L590-L595

**Comment by ChristophWurst** [comment]
With https://github.com/nextcloud/calendar/pull/3651 we should gain more insights. Will tag an RC2 once it's in and then we can try again :pray:

**Comment by ChristophWurst** [comment]
For me it's all the todo items in my calendar. Redacted example:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:+//IDN bitfire.at//ical4android
BEGIN:VTODO
DTSTAMP:20190825T082453Z
UID:494fbd55-4c0c-4e56-bffa-39c1df8c8b0c
SEQUENCE:1
CREATED:20190825T073208Z
LAST-MODIFIED:20190825T082416Z
SUMMARY:redacted
STATUS:IN-PROCESS
END:VTODO
END:VCALENDAR
```

**Comment by tcitworld** [comment]
I have the issue with all kind of items : recurring events, birthday calendars, todos, simple events.

**Comment by tcitworld** [comment]
Note : the Tasks dashboard widget works properly with the same set of todos.

**Comment by jakobroehrl** [comment]
With RC2:
![image](https://user-images.githubusercontent.com/24530680/141775632-da3b7383-e03e-4948-a690-51469cb2e602.png)

**Comment by ChristophWurst** [comment]
if you expand the `{response: n}` then you'll see the event/task data causing this

**Comment by jakobroehrl** [comment]
That are the deck cards:
![image](https://user-images.githubusercontent.com/24530680/141791511-ec972782-23a3-4989-b253-7d85813ee352.png)

But if I disable deck it's also not showing any data in the calendar widget

**Comment by ChristophWurst** [comment]
![Bildschirmfoto von 2021-11-15 20-12-17](https://user-images.githubusercontent.com/1374172/141840263-f0a45dee-1184-40fa-a4ae-5f3372ad23fd.png)

it throws right there inside calendar-js. but the argument is a property as far as I can tell. this could be an issue with the build, and therefore not show locally with the dev/watch bundles. I'll keep digging.

**Comment by svankan** [comment]
> I have the issue with all kind of items : recurring events, birthday calendars, todos, simple events.

I have the same problem after upgrading to Nextcloud version: 21.0.6.2 and calendar: 2.3.4.

**Comment by larwood** [comment]
I have not yet updated and am still on 22.2.0 but I did update the Calendar App to 2.3.4 this morning and the widget is now broken for me as well.

**Comment by Nonlinearsound** [comment]
Christoph, same error here. On my instance the logger shows me that there are two events being loaded, which is right a my calendar only holds two elements. I attached two ics files for you to this reply. Maybe you'll find some attribute that is not formatted right?

[DA454A53-C990-4EC3-AF6A-E99F054CAD8E.ics.txt](https://github.com/nextcloud/calendar/files/7552475/DA454A53-C990-4EC3-AF6A-E99F054CAD8E.ics.txt)

[9DF693D8-0E7F-472F-A0DC-E34CBBBAD21A.ics.txt](https://github.com/nextcloud/calendar/files/7552478/9DF693D8-0E7F-472F-A0DC-E34CBBBAD21A.ics.txt)

**Comment by dcommisso** [comment]
Same problem here. Also, mobile calendar no longer synchronizes with nextcloud calendar, maybe it's related?

Nextcloud version: 22.2.3
calendar version: 2.3.4

**Comment by blizzz** [comment]
> Same problem here. Also, mobile calendar no longer synchronizes with nextcloud calendar, maybe it's related?
> 
> Nextcloud version: 22.2.3 calendar version: 2.3.4

I cannot confirm the calendar sync issue, this continues to work well for me.

**Comment by flatterrich** [comment]
for me too, only widget without function

**Comment by jakobroehrl** [comment]
Sync is working without any problems and calendar, too.
Only the dashboard widget is the problem on my installation.

**Comment by dcommisso** [comment]
> Same problem here. Also, mobile calendar no longer synchronizes with nextcloud calendar, maybe it's related?
> 
> Nextcloud version: 22.2.3 calendar version: 2.3.4

Never mind, it turns out that there was a problem with calendar mobile app. I apologize.

**Comment by larwood** [comment]
This issue is now resolved for me after updating to v2.4.0 on NC 22.2.3

**Comment by bcutter** [comment]
Yes I can confirm. Even this bug is not listed in the fix section of the release notes, its's now finally working again.

**Comment by KwisatzJim** [comment]
I'm on 27.1.0 and it shows events in upcoming days but not today. I have 5 items on my calendar for today and none of them show on the dashboard widget
