### ISSUE TITLE
Side panel takes long time to load

### ISSUE THREAD

**Issue by leviia** [nextcloud/calendar#3650]
### Steps to reproduce

On one of our instance with a lot of account the side panel take about 30 seconds to load with the spinning wheel.
It happen on the website only

### Expected behaviour

it should load quicker

### Calendar app
2.3.4

After digging a little it seems the this is this request that take a long time to load:
```
PROPFIND https://server.name/remote.php/dav/calendars/${user}/
```
When you look at the database (mariadb in our case) you can see the request being done:
```
SELECT * FROM `oc_properties` WHERE `propertypath` = 'calendars/${user}/personal'
```
And this request take about 5s on our database (9 GB database)
As there is multiple of them you have to wait about 30s to have the answer. 

But I can make it way faster by doing this request:
```
SELECT * FROM `oc_properties` WHERE userid = '${user}' and `propertypath` = 'calendars/${user}/personal';
```
Here it takes only 0.001s 

here is the output 

```
MariaDB [hostname]> SELECT * FROM `oc_properties` WHERE `propertypath` = 'calendars/${user}/personal';
+---------+---------+----------------------------+------------------------------------------+---------------+
| id      | userid  | propertypath               | propertyname                             | propertyvalue |
+---------+---------+----------------------------+------------------------------------------+---------------+
| 9051553 | ${user} | calendars/${user}/personal | {http://owncloud.org/ns}calendar-enabled | 1             |
+---------+---------+----------------------------+------------------------------------------+---------------+
1 row in set (5.431 sec)

MariaDB [hostname]> SELECT * FROM `oc_properties` WHERE userid = '${user}' and `propertypath` = 'calendars/${user}/personal';
+---------+---------+----------------------------+------------------------------------------+---------------+
| id      | userid  | propertypath               | propertyname                             | propertyvalue |
+---------+---------+----------------------------+------------------------------------------+---------------+
| 9051553 | ${user} | calendars/${user}/personal | {http://owncloud.org/ns}calendar-enabled | 1             |
+---------+---------+----------------------------+------------------------------------------+---------------+
1 row in set (0.001 sec)

```
Is it a good idea to make this change in the code (add ```userid = '${user}' ```  in the request) ?
Can someone do it ? 

All the best 

Arnaud

**Comment by leviia** [comment]
Hello 

Does anyone have the same issue ? 

All the best 

Arnaud

**Comment by ChristophWurst** [comment]
> When you look at the database (mariadb in our case) you can see the request being done:
> 
> ```
> SELECT * FROM `oc_properties` WHERE `propertypath` = 'calendars/${user}/personal'
> ```

Fixd by https://github.com/nextcloud/server/pull/30392.
