### ISSUE TITLE
implement a scheduling UI 

### ISSUE THREAD

**Issue by ArnY** [nextcloud/calendar#366]
When one has to invite multiple collaborators to an event, a scheduling UI is most often required. The UI allows the user to select attendees and automatically sees their availability on the chosen timerange. Zimbra's scheduler looks like this:
![zimbra](https://cloud.githubusercontent.com/assets/138363/23940479/560ed1d6-0965-11e7-883e-d47e1ee42f3b.png)

**Comment by georgehrke** [comment]
Please search for existing issues before creating new ones ...

**Comment by georgehrke** [comment]
That's what https://github.com/nextcloud/calendar/issues/39 is about

**Comment by ArnY** [comment]
Errr.. I have been looking for this for the last hour, and it never showed up in my searchs! Sorry about the 2 last issues I opened, then. Thanks.

**Comment by n0whereRuoxi** [comment]
@ArnY How is this feature going?
