### ISSUE TITLE
After updating to Nextcloud 22.2.3, Upcoming Events Empty and Create A New Event Does Not Work.

### ISSUE THREAD

**Issue by worksmarter** [nextcloud/calendar#3660]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update to 22.2.3

### Expected behavior
Upcoming Events Should be populated from Calendar.
Create A New Event Should work as normal.
### Actual behavior
Upcoming Events Not Populated on Dashboard
Create A New Event From Upcoming Events On Dashboard hangs on page with "Page Unresponsive"
### Server configuration

**Operating system:**
CentOS 7
Operating system: Linux 3.10.0-1160.45.1.el7.x86_64 nextcloud/server#1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64

Webserver: Apache/2.4.51 (Unix) OpenSSL/1.0.2k-fips (fpm-fcgi)

Database: mysql 10.2.41

PHP version: 8.0.12

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, standard, mysqlnd, pcntl, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, pspell, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, cgi-fcgi, apcu, brotli, imagick, mailparse, mcrypt, memcache, memcached, redis, sodium, ssh2, uploadprogress, Zend OPcache

Nextcloud version: 22.2.3 - 22.2.3.0

Updated from an older Nextcloud: 22.2.2

Where did you install Nextcloud from: online updater

<details><summary>Signing status</summary></details>
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.8.0
 - activity: 2.15.0
 - apporder: 0.13.0
 - calendar: 2.3.4
 - camerarawpreviews: 0.7.13
 - checksum: 1.1.2
 - circles: 22.1.1
 - cloud_federation_api: 1.5.0
 - comments: 1.12.0
 - contacts: 4.0.6
 - contactsinteraction: 1.3.0
 - dashboard: 7.2.0
 - dav: 1.19.0
 - deck: 1.5.5
 - external: 3.9.0
 - federatedfilesharing: 1.12.0
 - federation: 1.12.0
 - files: 1.17.0
 - files_markdown: 2.3.4
 - files_pdfviewer: 2.3.1
 - files_rightclick: 1.1.0
 - files_sharing: 1.14.0
 - files_trashbin: 1.12.0
 - files_versions: 1.15.0
 - files_videoplayer: 1.11.0
 - firstrunwizard: 2.11.0
 - groupfolders: 10.0.0
 - logreader: 2.7.0
 - lookup_server_connector: 1.10.0
 - maps: 0.1.9
 - music: 1.4.1
 - nextcloud_announcements: 1.11.0
 - notes: 4.2.0
 - notifications: 2.10.1
 - oauth2: 1.10.0
 - password_policy: 1.12.0
 - photos: 1.4.0
 - privacy: 1.6.0
 - provisioning_api: 1.12.0
 - rainloop: 7.1.2
 - recommendations: 1.1.0
 - serverinfo: 1.12.0
 - settings: 1.4.0
 - spreed: 12.1.2
 - support: 1.5.0
 - survey_client: 1.10.0
 - tasks: 0.14.2
 - text: 3.3.0
 - theming: 1.13.0
 - twofactor_backupcodes: 1.11.0
 - updatenotification: 1.12.0
 - user_status: 1.2.0
 - viewer: 1.6.0
 - weather_status: 1.2.0
 - workflowengine: 2.4.0
Disabled:
 - admin_audit
 - bruteforcesettings
 - encryption
 - files_external
 - files_trackdownloads
 - mail
 - richdocuments
 - sharebymail
 - systemtags
 - user_ldap

```
</details>

or 

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "my.domain.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "22.2.3.0",
    "overwrite.cli.url": "https:\/\/vapor.userveit.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "integrity.check.disabled": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "theme": "",
    "maintenance": false,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_sendmailmode": "pipe",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "default_phone_region": "US",
    "loglevel": 3,
    "logdateformat": "F d, Y H:i:s",
    "logtimezone": "America\/New_York",
    "has_internet_connection": true,
    "connectivity_check_domains": [
        "www.nextcloud.com",
        "www.startpage.com",
        "www.eff.org",
        "www.edri.org"
    ],
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "rainloop"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

```

### Client configuration
**Browser:**
Chrome, Firefox
**Operating system:**
Windows 10 x64
### Logs

<!--- Nothing to report-->

#### Web server error log: Nothing to report
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
Nothing to report
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
Nothing to report
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/3649
