### ISSUE TITLE
Appointments time should be in a new line

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#3667]

**Comment by st3iny** [comment]
@GretaD  @ChristophWurst Isn't this already implemented? 

![Screenshot 2021-11-19 at 11-11-04 Nextcloud](https://user-images.githubusercontent.com/1479486/142605705-f6f61211-c6fe-467a-b3f9-47ec930a73c2.png)

**Comment by ChristophWurst** [comment]
indeedy!
