### ISSUE TITLE
Show link to server's availability settings

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3670]
**Is your feature request related to a problem? Please describe.**

As a user I might wonder where I can change the availability settings. Since those are part of caldav and therefore server, they are not found in the Calendar app. Calendar is just one possible front-end. Yet for a user this is neither obvious nor should they have to know.

**Describe the solution you'd like**

Link to the Nextcloud 23 settings page added in https://github.com/nextcloud/server/pull/27466.

Don't link to anything on 22 or lower.

**Describe alternatives you've considered**

n/a

**Additional context**

Ref https://github.com/nextcloud/server/pull/27466

Originally reported internally by @jospoortvliet

**Comment by szaimen** [comment]
https://github.com/nextcloud/activity/pull/621 might be of some inspiration for this
