### ISSUE TITLE
Shared calendar stopped syncing

### ISSUE THREAD

**Issue by danielkoch** [nextcloud/calendar#3677]
### Steps to reproduce
1. Use Nextcloud 22.2.3
2. Use Calendar app 2.3.4
3. Create a minimum of two users and share calendar with other user(s) - with additional groups or without

### Expected behaviour
The sharing as described worked month and years. Since around 3 weeks the sharing for one user is not working anymore. New calendar entries are not shown in the "shared view". The entries are available but the "shared users" does't see them.

There is no error message, no logging. Currently I don't have an idea how to debug this. I found this: https://help.nextcloud.com/t/problems-with-shared-calender-to-show-events-accepted-via-outlook/124987 but not sure if the cause is a outlook entry.

### Actual behaviour
Tell us what happens instead

### Calendar app
**Calendar app version:** 2.3.4

### Client configuration
**Browser:** all

**Operating system:** Linux

### Server configuration

**Operating system**: Ubuntu 20.04.3 LTS

**Web server:** Apache with Nginx as proxy

**Database:** MariaDB 10.3.31

**PHP version:** 7.4.3

**Nextcloud Version:** 22.2.3

**List of activated apps:** More less only default/shipped apps

#### Web server error log (e.g. /var/log/apache)
No logging

#### Log file (data/nextcloud.log)
No logging

**Comment by HumanG33k** [comment]
We currently face to the same kind of issue. 

Issue with share calendar, invitation and tasks,  when we have several calendar users may have to wait 5 minutes to get their calendar. 

Nothing in log, serveur side or client side. 

We currently use apache2 with  mpm_itk.

I m curious about if the calendar app have been benchmark with several data.

**Comment by danielkoch** [comment]
Just for information: Issue sill exists with the latest `v3.0.0`.

I tried to find the cause of this issue. Found the following differences:

1. Entries that are "working"(are visible have the value `0` in field `classification` in the table `oc_calendarobjects`
2. Entries that are *not* working have the value `1` in field `classification` in table `oc_calendarobjects`

**Comment by temporarium** [comment]
I want to chime in since I had a similar issue and discovered a comment that set me on the right track to resolve it (in my case): https://github.com/nextcloud/calendar/issues/723#issuecomment-364224589

Also, have a look at this setting in your event definition:
![2021-12-15_09-16](https://user-images.githubusercontent.com/4754345/146203091-8fd2107b-5a1e-4464-9f1e-1555861c8680.png)

**Comment by danielkoch** [comment]
Hello @temporarium. Thanks for you hint/comment! Indeed this was the cause on Nextcloud side. If I change this option it works again!

Maybe for others: The root cause was trigged by Outlook. I use https://caldavsynchronizer.org for synchronizing appointments with Nextcloud. For some reason the default  "Sensitivity level" was set/changed to "Personal" (setting in Outlook: File, Options, Email: send messages). This triggers on NC the mentioned option.
