### ISSUE TITLE
Design Arrow Buttons for changeing (Day, Week, Month too small)

### ISSUE THREAD

**Issue by florom** [nextcloud/calendar#3679]
Hi Devs,

I think it was different before. I really do not understand why it is smaller now 
therefore I think it is a bug.

Nextcloud: 22.2.3
Calendar: 2.3.4
Browser PC: Firefox 94.0.1
Browser Android: Firefox 94.1.2

1, Open Calender
2, Klick on next month --> Button almost unklickable in Browser (PC) and definetly untouchable in Browser Phone.

Enhancement: Larger by default 

Screenshot:
![image](https://user-images.githubusercontent.com/32240626/142834027-5619cc57-3866-42d5-a124-3ce7248fb32d.png)

Thank you.

**Comment by raimund-schluessler** [comment]
I can confirm, that they are narrower now. Since they are buttons/clickable elements, they should actually be at least 44 pix wide, no?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/issues/29591 is where I reported this

**Comment by szaimen** [comment]
I think this is fixed in the meantime
