### ISSUE TITLE
Calendar Icon missing in menu

### ISSUE THREAD

**Issue by bastoGrande** [nextcloud/calendar#368]
### Steps to reproduce
1. Nextcloud instance with calendar-app 

### Expected behaviour
Icon is visible

### Actual behaviour
Icon is not shown

### Server configuration
**Operating system**: CentOS

**Web server:** Apache 2.2

**Database:** MySQL

**PHP version:** 7.0.8

**Server version:** 11.0.2

**Calendar version:** 1.5.1

**Updated from an older installed version or fresh install:** Updated from 1.5.0

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here:
`No errors have been found.`
```

**List of activated apps:**
Enabled:
  - calendar: 1.5.1
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - files_versions
  - firstrunwizard
  - serverinfo
  - survey_client
  - systemtags
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oczlzc627zwt",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***"                                            ,
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 3,
        "updater.release.channel": "stable",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false,
        "theme": ""
    }
}
```

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Win8.1

**Comment by bastoGrande** [comment]
The problem I found was the path for the svg-icon as shown in the following screenshot:

![missing-icon](https://cloud.githubusercontent.com/assets/15093263/23683162/408bc2d2-0376-11e7-8736-4cc2b79ec246.PNG)

Only the calendar app is missing the nextcloud (part of the path). All other apps start with nextcloud/restOfPath/

**Comment by georgehrke** [comment]
That's really weird, because contacts and calendar use exactly the same routine to generate the path:
https://github.com/nextcloud/calendar/blob/master/appinfo/application.php#L102
https://github.com/nextcloud/contacts/blob/master/appinfo/app.php#L35

**Comment by georgehrke** [comment]
Though it's weird that the contacts app uses a callback oO

**Comment by bastoGrande** [comment]
The same problem appears with the standard-menu. So it's not a problem of the direct-menu-app.

**Comment by georgehrke** [comment]
Doc says closure is preferred, will try that:
https://github.com/nextcloud/server/blob/8b95bd29ee5131721ff2644936309fd75c1ab956/lib/private/NavigationManager.php#L73

**Comment by georgehrke** [comment]
@bastoGrande Do you mind to help testing #369 ? :)

**Comment by bastoGrande** [comment]
Well, I guess I can try, but don't no how? :)

**Comment by georgehrke** [comment]
you can test this by replacing the content of `apps/calendar/appinfo/application.php` with the content of https://raw.githubusercontent.com/nextcloud/calendar/9b6db3b4aad3ebfd85057e0e0456dac2a6252056/appinfo/application.php :)

**Comment by tcitworld** [comment]
Don't see why updating from 1.5.0 would have changed this. Even more, it's correctly shown on all of my instances with the same configuration.

**Comment by bastoGrande** [comment]
well I replaced it and did a "ctrl+f5" refresh and the icon is still missing... :S

**Comment by bastoGrande** [comment]
That's actually a good point. I couldn't imagine to be the first and only one, who is experiencing it, but forgot to write it...

**Comment by georgehrke** [comment]
> well I replaced it and did a "ctrl+f5" refresh and the icon is still missing... :S

Hm. :/ 

The problem is that neither @tcitworld nor me can reproduce your bug :/

**Comment by bastoGrande** [comment]
I just tried to edit in the browser the path of the icon. Nothing happened, so where is the icon supposed to be? Under what path can I normally find it?

**Comment by georgehrke** [comment]
> Under what path can I normally find it?

It's supposed to be inside `apps/calendar/img/calendar.svg`

**Comment by georgehrke** [comment]
Does this file exist in your Nextcloud installation? :)

**Comment by bastoGrande** [comment]
sorry.. just had to get to the beach. it was about time, since the last time! 🙂 

so yes, the file `apps/calendar/img/calendar.svg` exist. after downloading it, I tried to open it with Inkscape, but didn't work, well at least I didnt't see anything that looks like logo.. so that's why I think, somehow my icon-file got corrupted.. anyone an idea?

so i will try to get the original from the repository and check if this changes something or maybe there is another problem with my Inkscape installation.. 
weird day, today.. 😕

**Comment by bastoGrande** [comment]
well it didn't got corrupted (same content), but what the heck is going on? 
I can't open the calendar.svg with my Inkscape installation. 
**Can anyone confirm?** 

Because I already successfully worked with Inkscape and had no problems before.

**Comment by bastoGrande** [comment]
well I still don't have an idea what exactly is going wrong.

1. can anybody try to open the calendar.svg and confirm to see the calendar symbol? 
2. can anybody me show/tell what img-path he/she has in his/her functioning nc-instance?

thx!

**Comment by georgehrke** [comment]
> can anybody try to open the calendar.svg and confirm to see the calendar symbol?

I see the (white) calendar icon

> can anybody me show/tell what img-path he/she has in his/her functioning nc-instance?

it's `apps/calendar/img/calendar.svg` for me

**Comment by bastoGrande** [comment]
>it's apps/calendar/img/calendar.svg for me
well, that's great, because it is the same for me

> I see the (white) calendar icon
mhm, that's not so great.. what program do you use to open it?

**Comment by georgehrke** [comment]
> well, that's great, because it is the same for me

Well, because my nextcloud instance is in http://nextcloud.dev/index.php
So that's the expected behavior 

> mhm, that's not so great.. what program do you use to open it? I tried paint.net (with plugin) and Inkscape and both didn't show me anything with the svg from my instance and the one from the repository.

Sketch on macOS. I can also just open the svg in Firefox / Chromium and Safari

**Comment by georgehrke** [comment]
<img width="997" alt="files - nextcloud chromium today at 9 15 29 pm" src="https://cloud.githubusercontent.com/assets/1250540/24016778/bd5636ee-0a8d-11e7-88ae-fb23ae6c5147.png">

and if i move nextcloud to a subfolder, the path to the svg changes as well. Just as expect.

**Comment by bastoGrande** [comment]
well, what could be the problem, that this recognition fails? because i have installed my nextcloud-instance into a subfolder. 
could it be that #358 could break this recognition? (I don't think so, but who knows?)

**Comment by georgehrke** [comment]
> could it be that #358 could break this recognition

No, it's very very very very unlikely that these bugs are related.

**Comment by bastoGrande** [comment]
>No, it's very very very very unlikely that these bugs are related.

ok

>**well, what could be the problem, that this recognition fails?**

**Comment by georgehrke** [comment]
I guess it's some configuration issue on your side, but that's only a wild guess. 
Actually I'm really clueless at the moment. It's also not related to Firefox on Windows:
<img width="1136" alt="dashboard firefox today at 10 14 28 pm" src="https://cloud.githubusercontent.com/assets/1250540/24018873/fce32ab2-0a95-11e7-8208-f98a5680831b.png">

I tried different configurations but I had no luck reproducing your issue.

**Comment by bastoGrande** [comment]
well, it's just an icon.. I try to forget it.. thank you for your effort!
I learnt a lot and I think that is the point what we should keep in mind about this "bug"...

**Comment by bastoGrande** [comment]
hehe, one big 🤦‍♂️ for me! 

I just never thought it could be a caching problem, but I don't know why I never thought about it, because now it's super obvious to me! 
Found the hint [here](https://github.com/nextcloud/server/issues/3800)..

You can forget this never existing bug and thanks again for your help!
