### ISSUE TITLE
v3.0.0-beta1: can't save appointment

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/calendar#3706]
{status: "fail", data: "Invalid value for availability"}
data: "Invalid value for availability"
status: "fail"

![image](https://user-images.githubusercontent.com/24530680/143491595-23074240-90f7-4b67-8a9e-b48e6a90ebe1.png)

![image](https://user-images.githubusercontent.com/24530680/143491624-1bf99b2a-e1be-4aa3-ad66-fb5c26f82c6f.png)
![image](https://user-images.githubusercontent.com/24530680/143491637-2edbaeb0-28bc-4c9f-8186-42104ad224dd.png)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/pull/3703 should fix this. I'll publish another prerelease tomorrow.

**Comment by jakobroehrl** [comment]
This is working, now! 
What does the visibility do? On "private" I can access the appointments page nevertheless as a non logged in user.

**Comment by ChristophWurst** [comment]
We'll try to clarify this. Public = listed on profile page. Private = only accessible for those who have the link.

**Comment by jakobroehrl** [comment]
OK, thanks. This is working. 
Maybe it would be helpful to change the description:
private: show only if you have the link
public: shows on the profile page

on the profile page: could we change the ... into a calendar icon? I overlooked it.
![image](https://user-images.githubusercontent.com/24530680/143561654-b9987900-6171-42ae-a0e4-a2f531646172.png)

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/calendar/pull/3713

**Comment by ChristophWurst** [comment]
> on the profile page: could we change the ... into a calendar icon? I overlooked it.

https://github.com/nextcloud/calendar/blob/12ef68eb89fc54a737ae2ee8df9533b17c84c056/lib/Profile/AppointmentsAction.php#L103-L105 possible if we change that
