### ISSUE TITLE
Can't save appointment if there is no mailserver configured

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/calendar#3707]
The user get's no error:

![image](https://user-images.githubusercontent.com/24530680/143557170-5bf72647-221d-420e-af9d-57ade0bceb84.png)

v3.0.0-beta2

**Comment by ChristophWurst** [comment]
ah yes.

I wonder how we can detect this more gracefully. `\OCP\Mail\IMailer` does not allow us to check if emails are configured.

**Comment by ChristophWurst** [comment]
@nickvergessen do you know a possible workaround? I'm sure we have the same problem somewhere else

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/8813667112dc3a387234f522baa7e430d58b4249/lib/GuestManager.php#L177-L182

At least Talk will also silently die :-X
