### ISSUE TITLE
Event is not shown when opend from the dashboard or notifications

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/calendar#3712]
NC23 + Calendar 3 (maybe the problem is already in earlier versions there)
Klick on an event in the dashboard or in a event notification:

![image](https://user-images.githubusercontent.com/24530680/143563030-f2e6654e-a4ec-45e0-842e-f137e15f8c31.png)

**Comment by tcitworld** [comment]
Probably the same issue than https://github.com/nextcloud/server/issues/29117

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/calendar/issues/2960
