### ISSUE TITLE
Appointment Three Dot Menu "Copy Link" does not work

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#3739]
The "Copy Link" option does not copy the link to the clipboard.

![image](https://user-images.githubusercontent.com/7427347/143849696-eda1ff77-ec1e-4ee8-a148-f33bdf72a2a6.png)

**Comment by ChristophWurst** [comment]
check your console? the browser might block it

**Comment by ChristophWurst** [comment]
could you add a console error log to https://github.com/nextcloud/calendar/blob/99d170991b54948cfd9933533c9aece57c779c1b/src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue#L107-L111 for the early return?

**Comment by miaulalala** [comment]
Ok the changes you added are working insofar as I don't have the copy button displayed any more :+1:
