### ISSUE TITLE
Implement notifications by email (sent from the server)

### ISSUE THREAD

**Issue by kbabioch** [nextcloud/calendar#375]
The Google calendar allows for notifications to be sent via mail. While I can setup such events with the Google calendar app for a Nextcloud calendar (using a DAVdroid account) this does not work, and I don't get any email notification at all. Mail notifications are often more useful than the native notification subsystem of the client itself, since it can be used for automation, etc.

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
