### ISSUE TITLE
Incorporate Calendar Transparency in Event Conflic Check

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#3756]
Currently, any event, irregardless of the TRANSP property, blocks an appointment slot from being available.

Add a check in \OCA\Calendar\Service\Appointments\EventConflictFilter::filter to not remove events that have the property TRANSP set to TRANSPARENT.

**Comment by miaulalala** [comment]
@ChristophWurst hasn't this been done?

**Comment by ChristophWurst** [comment]
I guess so
