### ISSUE TITLE
executeStatement is not available in Nextcloud 21

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#3763]
```
Error: Call to undefined method OC\DB\QueryBuilder\QueryBuilder::executeStatement() in /var/www/framadrive/apps/calendar/lib/Db/BookingMapper.php:86
Stack trace:
#0 /var/www/framadrive/apps/calendar/lib/Service/Appointments/BookingService.php(209): OCA\Calendar\Db\BookingMapper->deleteOutdated(86400)
#1 /var/www/framadrive/apps/calendar/lib/BackgroundJob/CleanUpOutdatedBookingsJob.php(53): OCA\Calendar\Service\Appointments\BookingService->deleteOutdated()
#2 /var/www/framadrive/lib/public/BackgroundJob/Job.php(80): OCA\Calendar\BackgroundJob\CleanUpOutdatedBookingsJob->run(NULL)
#3 /var/www/framadrive/lib/public/BackgroundJob/TimedJob.php(61): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#4 /var/www/framadrive/cron.php(128): OCP\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#5 {main}
```

Should be replaced by `execute` until we require Nextcloud 22. Note that there's two uses of `executeStatement` in `BookingMapper.php`.

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1) 3.0

### Server configuration

**Nextcloud Version:** (see admin page, e.g. 17.0.2) 21

**Comment by ChristophWurst** [comment]
Appointments doesn't work with 22 and older due to the missing calendar write support. We could also just make the background job exit early.

**Comment by tcitworld** [comment]
We could consider it as a good opportunity to have some static analysis tools and put some procedures to check for calls to depreciated methods when the minimum version is bumped. :smirk:
