### ISSUE TITLE
False Link to the Manual

### ISSUE THREAD

**Issue by vatolin** [nextcloud/calendar#3771]
In Calendar 2.3.4 on Nextxloud 22.2.3 on www.domain.tld/index.php/settings/apps/installed/calendar you'll find on the right side of the window "Dokumentation für Benutzer" - documentation for users. The given link https://docs.nextcloud.com/server/latest/user_manual/en/pim/calendar.html leads to "file not found".

**Comment by ChristophWurst** [comment]
This is a regression of https://github.com/nextcloud/documentation/pull/7633.

https://github.com/nextcloud/calendar/blob/master/appinfo/info.xml#L24 has to be updated. @vatolin would you like to make this your first contribution to this app? :)

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests for some docs about pull requests if you are not familiar.

**Comment by ChristophWurst** [comment]
@GretaD could you have a look if @vatolin doesn't respond?

**Comment by GretaD** [comment]
@vatolin i took over this one, but if you want to contribute on the code/documentation, i can find some other small issues for you to start :)
