### ISSUE TITLE
Recurring events block all appointment slots

### ISSUE THREAD

**Issue by bnjbvr** [nextcloud/calendar#3781]
I'm using Nextcloud based on the Docker image, and have updated to the latest version as to as benefit from the new calendar app, including the appointments feature about which I'm very excited!

Unfortunately, it doesn't seem to work: when I create an appointment (leaving all default values, maybe setting a title just so as to validate the form), then the preview page doesn't show any available slots at all, for any of the dates for which it should be available.

Skimming at the browser dev console, I see that the requests to fetch the list of available time slots works fine and returns a 200 http code, with a small JSON object that has status set to success, and an empty accompanying data array.

I'm using latest stable Firefox, in case that matters, and I haven't tried on other browsers.

Please let me know if/how I can help debug this! And thanks for all the work on this app and Nextcloud in general <3

**Comment by ChristophWurst** [comment]
We are obswrving this as well, but only on one specific instance. If you run into the same bug then creating a new empty calendar and using that as target will result in available slots. So the problem seem to be the conflict checks.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/pull/3773 is our first attempt at improving this.

**Comment by tcitworld** [comment]
I can confirm the issue and the workaround.

**Comment by ChristophWurst** [comment]
Do you have the ability to attach a debugger to your server? Are you familiar with xdebug? :)

**Comment by ChristophWurst** [comment]
> I can confirm the issue and the workaround

Oh. So after @miaulalala's patch slots show up? So it was some calendar objects other thatn VEVENT's that conflicted?

**Comment by tcitworld** [comment]
> Do you have the ability to attach a debugger to your server?

I'd rather not in production but I'll test locally with a calendar export.

**Comment by ChristophWurst** [comment]
You're a genius! I can now reproduce the issue locally on my dev instance. It's all the recurring events that show up as conflicts.

**Comment by ChristophWurst** [comment]
If I'm not mistaken it's `\OCA\DAV\CalDAV\CalDavBackend::search` that needs better support for recurring events. It only checks if the events ends before the requested start and starts before the requested end.

**Comment by ChristophWurst** [comment]
> We might have luck throwing it into `\Sabre\CalDAV\Backend\AbstractBackend::validateFilterForObject` as it is done in `\OCA\DAV\CalDAV\CalDavBackend::calendarQuery`.

This seems to do the trick: https://github.com/nextcloud/server/pull/30048. Recurring events no longer block slots in general. But when they overlap with the requested time range only the actually conflicting slots are filtered out.
