### ISSUE TITLE
Allow shared calendars as appointment conflict calendars

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3786]
**Is your feature request related to a problem? Please describe.**

As a user I might have calendars shared to me by other users, e.g. a company-wide calendar.

**Describe the solution you'd like**

It would be nice if I could select that shared calendar for appointment conflicts as well. Then company-wide events would also block appointment slots.

**Describe alternatives you've considered**

N/a

**Additional context**

- [x] https://github.com/nextcloud/server/issues/30068

**Comment by violoncelloCH** [comment]
in general, being able to chose which calendars are treated as conflict calendars for appointments would be useful!

**Comment by ChristophWurst** [comment]
> in general, being able to chose which calendars are treated as conflict calendars for appointments would be useful!

Coming with v3.1 https://github.com/nextcloud/calendar/pull/3770

**Comment by reos-rcrozier** [comment]
I was about to make a feature request similar to this, but am going to comment here instead. 

In our case most often Appointments are to be used for arranging meetings with an external party (who can't see shared calendars). For this reason it would be most useful to have an Appointments URL that can be a combination of the public Appointment calendars of several users. 

For example, if several people in the company are trying to arrange an appointment with some external party you would ideally send them one link which provides the appointments available that work for all three employees. This would be really handy.

This seems different from what you propose because one has to set up a new Appointments set for every combination of users to be present at a meeting.

**Comment by Blechlawine** [comment]
would this also apply to subscription calendars as well? Or just calendars shared within nextcloud?

**Comment by reos-rcrozier** [comment]
@Blechlawine if you're rpelying to me, I was only thinking of calendars shared withing Nextcloud, but actually I mean the _Appointments_ calendars shared within Nextcloud, 

My idea is users can set up their own appointments calendars, just as one can now, and I could somehow select from them to make the combined appointments calendar.

**Comment by Blechlawine** [comment]
@reos-rcrozier I was replying to op, but what your're describing sounds very useful as well

**Comment by ChristophWurst** [comment]
I'm sure there are cases where subscriptions as conflict source make sense :+1: 

I just don't know if the change is in scope for this ticket when someone picks it up. We can re-evaluate afterwards and create a another ticket if not.

**Comment by rasos** [comment]
We have an organization wide calendar with team meetings which is shared by an organization-admin account. That should be definitely be taken into account when checking for conflicts to offer free time slots.

**Comment by pjrobertson** [comment]
It seems like the server isse was fixed in NC 24.0.8 and 25.0.2 - does this mean that we can revisit this issue now?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/issues/30068 was closed by a script

**Comment by pjrobertson** [comment]
You're right, I missed that. I was trying to investigate this today. It seems like it should actually be possible right now though, without changing the server.

Right now the calendars are taken from `selectableConflictCalendars()` [here](https://github.com/nextcloud/calendar/blob/main/src/components/AppointmentConfigModal.vue#L238). This in turn gets its base calendars to filter from the store getter `ownSortedCalendars()`. 

Could we not just add a new getter/get the base calendars and then make sure not to filter out the `.filter(calendar => !calendar.isSharedWithMe)`. I'll submit a PR with this thinking

**Comment by ChristophWurst** [comment]
Try but I don't think it will work. The backend logic will fail to access those calendars and therefore conflicts are not detected.

**Comment by pjrobertson** [comment]
I put out a PR #5934, but I think I understand what you're saying now. I'm still struggling to set up a testing environment that includes my local calendar app, so haven't been able to test if this actually works or not

**Comment by ChristophWurst** [comment]
You can find some resources for dev envs at https://nextcloud.com/developer

**Comment by pjrobertson** [comment]
Yeah, I've been through that multiple times but there's little info on testing an existing app, and when I tried it it was throwing all sorts of errors. I unfortunately don't have time to debug for half a day :(

**Comment by viktorix** [comment]
+1 🙏

**Comment by bentuna** [comment]
Is this already usable somewhere? I tested with Nextcloud 30.0.6 and Calendar 5.1.0 and the feature is not present.
