### ISSUE TITLE
share with groups

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/calendar#3796]
Please add the function that appointments can be shared with groups.

**Comment by ChristophWurst** [comment]
mind following our templates? https://github.com/nextcloud/calendar/issues/new?assignees=&labels=enhancement-proposed%2C+0.+to+triage&template=feature_request.md&title=

the request is ambiguous. are you talking about the new appointments feature? or regular events? what kind of groups? contact groups? nextcloud user groups? :)

**Comment by R7JANV1** [comment]
nextcloud user groups
