### ISSUE TITLE
Multiline entry titles

### ISSUE THREAD

**Issue by hinz1** [nextcloud/calendar#3799]
In the calendar app it used to be possible to include line breaks into the "title" of an entry. This was a feature we had to use quite often to provide Information at a glance for our staff. After upgrading to 3.0.1 (from an admittedly very outdated version) the titles are squeezed into one line ending with an ellipsis if too long. 
We'd be very grateful for any possibility to get multi-line entry titles back, be it by manually inserting NLs or - even better - by having automatic responsiveness there. Another option might be to include a title attribute or the like so one can see the full title entry by mousing over.

**Comment by ChristophWurst** [comment]
would you mind following the issue template when opening a feature request? https://github.com/nextcloud/calendar/issues/new?assignees=&labels=enhancement-proposed%2C+0.+to+triage&template=feature_request.md&title=
