### ISSUE TITLE
Disable buttons after clicking to prevent double click actions

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#38]
- [x] new calendar / subscription
- [x] edit calendar / subscription
- [x] share calendar

**Comment by RosaGeorge31** [comment]
I'd like to take up this issue.

**Comment by georgehrke** [comment]
@RosaGeorge31 Yes, please :) If you have any questions please don't hesitate to ask!

**Comment by RosaGeorge31** [comment]
Hey I wanted to know which file should the modification be made in?

**Comment by georgehrke** [comment]
The vue `.once` event modifier might also be helpful here.

**Comment by georgehrke** [comment]
This was already solved in #926 

All buttons will be immediately disabled or replaced by loading spinner.
