### ISSUE TITLE
Display of buttons broken with french translation

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#380]
This is how it displays on Nextcloud 11.
![selection_031](https://cloud.githubusercontent.com/assets/2197836/24207528/68c510a8-0f21-11e7-8db9-899277fecbb3.png)

Moreover, the  « New agenda » button overlaps the « Today » button, so this last button doesn't work.

**Comment by georgehrke** [comment]
Duplicate of (one sec)

**Comment by tcitworld** [comment]
Thanks, couldn't find it.
