### ISSUE TITLE
Appointment booking mobilepage vertical scrolling 

### ISSUE THREAD

**Issue by Ben-Ro** [nextcloud/calendar#3808]
If i share an appointment Page, the datepicker and slots aren't vertical aligned, but horizontal aligned. On mobile Devices (e.g. iPhone 12 mini, IOS 15) only the first part is visible, the datepicker and timeslots aren't visible, only after horizontal scrolling. 

The three containers with user-info, date and slot selection should be vertically aligned and not horizontal. Could be fixed with flex-wrap.

Not sure if it helps, but the userstory would be:
I as an unexperienced user want to open the appointment booking page on a Phone, and see everything required to book an appointment without scrolling 

### Steps to reproduce
1. Share an Appointment booking Page
2. Open Page on Phone Browser
3. Don't see the second and third container

### Expected behaviour
All three containers should be visible

### Actual behaviour
Only the user-info Container is visible

### Calendar app
**Calendar app version:** newest

**CalDAV-clients used:** None, Browser

### Client configuration
**Browser:** Safari, Chrome (newest versions)

**Operating system:** iOS, MacOS

### Server configuration

**Operating system**: Debian 8

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4.26

**Nextcloud Version:** 23.0.0

**Updated from an older installed version or fresh install:** Updated

### Logs
It's CSS Bug, so no logs

**Comment by ChristophWurst** [comment]
mind sharing screenshots?

**Comment by ChristophWurst** [comment]
Thanks!

**Comment by Ben-Ro** [comment]
I'm new to doing stuff on such big OSS projects, so sorry if i misunderstand the label or the correct way of doing things.
I already created a [fix with the one line of CSS missing](https://github.com/Ben-Ro/calendar/commit/208753523dd98a804db9a91ac9cb5dc6791ba40f).
Should i now open a pull request or is there anything other to do before merging this?

**Comment by ChristophWurst** [comment]
No worries. Please open a pull request.
