### ISSUE TITLE
Limit time rows in day view

### ISSUE THREAD

**Issue by rakshazi** [nextcloud/calendar#381]
### Steps to reproduce
1. Open nextcloud calendar app
2. Change view to `Day`

### Expected behaviour
I want to limit time (hour) rows from 12am-11pm to 8am-6pm view, because all our company employees (nextcloud users) work only in this time interval.

### Actual behaviour
I see all time rows from 12am to 11pm

Can I solve this problem myself or you can implement this as feature for calendar app?

Than you.

**Comment by georgehrke** [comment]
Fullcalendar allows it to fix it on your own: https://fullcalendar.io/docs/display/businessHours/

Nothing we gonna change in the calendar app though

**Comment by rakshazi** [comment]
Please, tell where I need to insert this config?

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/blob/master/js/app/directives/fullCalendarDirective.js#L86

**Comment by rakshazi** [comment]
Thank you!

**Comment by wo80** [comment]
I'm new to NextCloud and this was the first thing I was missing. Here's what I did:
* login to server
* go to nextcloud subdirectory `apps/calendar/js`
* replace `,eventOrder:[` with `,slotMinTime:'08:00',slotMaxTime:'18:00',eventOrder:[` in file `calendar-main.js` (adjust timeslot as needed)

The `fullcalendar` options are in [src/components/CalendarGrid.vue](https://github.com/nextcloud/calendar/blob/main/src/components/CalendarGrid.vue#L133) and `slotMinTime`, `slotMaxTime` have to be added, see [stackoverflow](https://stackoverflow.com/questions/13710528/how-to-show-only-opening-hours-in-fullcalendar) question.

Shell commands:
```bash
cd /var/www/nextcloud/apps/calendar/js

# Make backup in case we're breaking something
sudo cp calendar-main.js calendar-main.js.bak

# Should return 1
awk 'END{print _}{_+=NF-1}' FS=',eventOrder:\\[' < calendar-main.js

# Should return a number N > 0
awk 'END{print _}{_+=NF-1}' FS='slotMinTime' < calendar-main.js

# Add slotMinTime and slotMaxTime options
sudo sed -i 's/,eventOrder:\[/,slotMinTime:\x2708:00\x27,slotMaxTime:\x2718:00\x27,eventOrder:\[/g' calendar-main.js

# Should return N+1
awk 'END{print _}{_+=NF-1}' FS='slotMinTime' < calendar-main.js
```
