### ISSUE TITLE
Appointments - Are other calendars taken into consideration for conflicts ?

### ISSUE THREAD

**Issue by Kalytis** [nextcloud/calendar#3811]
### Steps to reproduce
1. Having multiple calendars on Nextcloud Calendar
2. Adding an event in one
3. Setting up Appointments on the other one
4. Trying to book an appointment at the time and date of the event of step 2

### Expected behaviour
Appointment slot should not be available for booking

### Actual behaviour
Appointment slot is available, hence putting the risk for a customer to book at a time where I won't be available

### Calendar app
3.0.1

**CalDAV-clients used:** Nextcloud Calendar webUI, Thunderbird Lightning, DAVx5+ETAR

### Client configuration
**Browser:** Firefox 95.0

**Operating system:** Ubuntu 21.10

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** ?

**Nextcloud Version:** Nextcloud Hub II 23.0.0

**Updated from an older installed version or fresh install:** Updated

**List of activated apps:**

**Comment by Kalytis** [comment]
ADDENDUM : I see from other projects (i.e AntennaPod) that it's possible to explain steps and answer to triage question via a form instead of plain text... would it be possible to enable it here please ? Thanks a lot !

**Comment by ChristophWurst** [comment]
> ADDENDUM : I see from other projects (i.e AntennaPod) that it's possible to explain steps and answer to triage question via a form instead of plain text... would it be possible to enable it here please ? Thanks a lot !

https://github.com/nextcloud/groupware/issues/13 good point :+1: 

v3.1 will come with a calendar picker for additional conflict calendars https://github.com/nextcloud/calendar/pull/3770

**Comment by Kalytis** [comment]
> > ADDENDUM : I see from other projects (i.e AntennaPod) that it's possible to explain steps and answer to triage question via a form instead of plain text... would it be possible to enable it here please ? Thanks a lot !
> 
> [nextcloud/groupware#13](https://github.com/nextcloud/groupware/issues/13) good point +1
> 
> v3.1 will come with a calendar picker for additional conflict calendars #3770

Thanks for your answer, and for your hard work !
