### ISSUE TITLE
Calendar of event cannot be changed after creation

### ISSUE THREAD

**Issue by mputzi** [nextcloud/calendar#3838]
### Steps to reproduce
1. create event, user has more than one calendar with editing rights
2. try to change calendar of event by selecting new calendar for event
3. calendar stays the same, no matter what has been selected

### Expected behaviour
When selecting a new calendar for an event, the event should be reassigned to that calendar.

### Actual behaviour
The calendar the event is assigned to stays the same.

### Calendar app
**Calendar app version:**  3.0.3

### Client configuration
**Browser:** Firefox 95.0

**Operating system:** Manjaro Linux 

### Server configuration

**Operating system**: Ubuntu 20.04.3

**Web server:** NGINX

**Database:** MariaDB 

**PHP version:** 7.4.3

**Nextcloud Version:**  22.2.3

**Updated from an older installed version or fresh install:** Updated from older version

**List of activated apps:** 
 Accessibility 1.8.0
Activity 2.15.0
Analytics 4.0.2
Announcement center 6.1.1
AppOrder 0.13.0
Audio Player 3.2.2
Automated PDF conversion 1.7.0
**Calendar 3.0.3**
Circles 22.1.1
Collabora Online 4.2.3
Collabora Online - Built-in CODE Server 21.11.6
Collaborative tags 1.12.0
Comments 1.12.0
Contacts 4.0.7
Contacts Interaction 1.3.0
Dashboard 7.2.0
Deck 1.5.5
Deleted files 1.12.0
Draw.io 1.0.2
External sites 3.9.0
Extract 1.3.3
Federation 1.12.0
File sharing 1.14.0
First run wizard 2.11.0
GpxPod 4.3.0
LDAP user and group backend 1.12.1
Log Reader 2.7.0
Mail 1.11.4
Markdown Editor 2.3.5
Monitoring 1.12.0
Nextcloud announcements 1.11.0
Notifications 2.10.1
Password policy 1.12.0
PDF viewer 2.3.1
Photos 1.4.0
Polls 3.4.2
Privacy 1.6.0
Quota warning 1.13.0
Recommendations 1.1.0
Right click 1.1.0
Share by mail 1.12.0
Support 1.5.0
Talk 12.2.2
Tasks 0.14.2
Text 3.3.0
Theming 1.13.0
Update notification 1.12.0
Usage survey 1.10.0
User status 1.2.0
Versions 1.15.0
Video player 1.11.0
Weather status 1.2.0
Welcome 1.0.1

**Nextcloud configuration:**
```
{
    "system": {
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "logtimezone": "Europe\/Berlin",
        "cron_log": true,
        "loglevel": 2,
        "log_rotate_size": 104857600,
        "default_phone_region": "DE",
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": ""
    }
}
```
### Logs

no errors in logs.

**Comment by mputzi** [comment]
Using DAV-Client existing events can be reassigned to a new calendar. Only the edit event form in the nextcloud app seems to be affected.

Using the "simple editor" in Calendar 3.0.3 for reassigning a calendar results in not ending spinner overlay:
![Screenshot_20211222_074516](https://user-images.githubusercontent.com/5164032/147047896-173c9fcf-58c1-4f4f-aafd-a47486264845.png)

**Comment by tcitworld** [comment]
@mputzi Please check browser logs as well, as there should be something here if it hangs like this.

**Comment by tobox** [comment]
Same problem here, and reverting to 3.0.2 was not possible (nextcloud auto-updated to 3.0.3 immediately).

Workaround: change the order of calendars on the left so that the calendar you want to use is at the top. Then create the event, and the top-most calendar is selected by default.

**Comment by ChristophWurst** [comment]
> Using the "simple editor" in Calendar 3.0.3 for reassigning a calendar results in not ending spinner overlay:

I run into this when I move from one calendar to the other and then back. It's a known regression: https://github.com/nextcloud/calendar/issues/3325

**Comment by ChristophWurst** [comment]
> * create event, user has more than one calendar with editing rights
> * try to change calendar of event by selecting new calendar for event
> * calendar stays the same, no matter what has been selected

I'm not able to reproduce.

**Comment by heikojansen** [comment]
I can confirm the original report and the workaround described by @tobox (though I need to reload the page after rearranging the calendars in the left column before that takes effect for a new event).

Regarding the question by @ChristophWurst : I did not create any new calendars. I just tried to add a new event in an already existing calendar by clicking at the appropriate date and time position in my week view, then tried to change the pre-selected calendar in the form shown in the right column.

**Comment by szaimen** [comment]
Might be due to https://github.com/nextcloud/calendar/blob/f39e31fec11708970f975dc83e49246decce95dd/src/views/EditSidebar.vue#L95

Shouldn't that be `@select-calendar` instead of `@selectCalendar` ? 

This change was made in https://github.com/nextcloud/calendar/pull/3424

**Comment by ChristophWurst** [comment]
Vue should convert camel case to kebab case but worth a try

**Comment by philippeladame** [comment]
> I can confirm the original report and the workaround described by @tobox (though I need to reload the page after rearranging the calendars in the left column before that takes effect for a new event).

Same here. I confirm both issue and workaround. NC 23 + Firefox (same problem with Chrome).

**Comment by raimund-schluessler** [comment]
> Vue should convert camel case to kebab case but worth a try

No, they are not equivalent. We learned that already in https://github.com/nextcloud/calendar/pull/3410/commits/bf44d031af521ab640db33fde4b723f2a74c21db. So `@select-calendar` is correct.

**Comment by ChristophWurst** [comment]
My bad. I'll fix this next week.

**Comment by pm-pm** [comment]
Hello,
is there any possibility to fix it (temporarily) by manually editing a file?
Thanks.

**Comment by ChristophWurst** [comment]
@pm-pm no.

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/calendar/pull/3846

**Comment by amsel54** [comment]
First of all thanks for the great work you are doing in the nextcloud and ass. projects.

Actually I am not sure what is the actual status of this bug. Recetly I tested the calendar in nextcloud 24.0.1 an calender 3.4.2 and have still the same behaviour:
- created a new calendar 'calendar2'
- created an event within my personal calendar
- open the event in the simple editor and change to 'calendar2' and close with 'update'
- reopen in simple editor -> still personal calendar
- change to 'calendar2' again close with 'update'
- the editor hangs
- reload browser page
- reopen event with simple calendar -> there it shows 'calender2'
- checking my caldav sync of 'calender2' in thunderbird -> no sync of the event
- this changes if I reopen the event and change something, for example the give a place and close via 'update'
- now the event is synced

it seems that stroing a changed calendar value does not work properly
