### ISSUE TITLE
Starting day of the week (Sunday vs Monday)

### ISSUE THREAD

**Issue by fengshaun** [nextcloud/calendar#384]
Nextcloud 10, Calendar 1.5.1

There is currently no way to set the starting day of the week (Sunday vs Monday) and it defaults to Sunday. It would be beneficial to have this as a configurable option.

**Comment by tcitworld** [comment]
The first day of the week is currently determined based on your language
There are plans for a dedicated region input in the server:
nextcloud/server#1781

**Comment by vladislavivanistsev** [comment]
Sorry, but it make no sense that you determine the first day based on language. Please make an option for choosing the day.

**Comment by websafe** [comment]
I need to have NextCloud in English (because it's easier to find/report bugs and the UI works with Eenglish as expected) but I want to have Monday as my first day of week in the calendar. The Tasks module has a `Start of week` setting. Would be great to have this in the calendar module too.

**Comment by georgehrke** [comment]
@websafe Please read @tcitworld's comment above. ;) 

We won't have a dedicated start of week input, but there will be a locale setting in the server. So you will be able to select english as language and Poland as locale.

**Comment by KaiRo-at** [comment]
Locale just doesn't cut it. Not even everyone living in the US wants Sunday as the first day of the week in their calendars, even if the pretty surely want US English locale settings. Making first day of the week locale-dependent has been FAIL state in every calendar app so far, but I guess every one of them needs to go 10 years or more and have a bloody nose before they realize it.

**Comment by evilphish** [comment]
I can only second what @KaiRo-at pointed out. There should be a dedicated first day of the week setting. I use English as a language even though this is not my mother tongue but in science, where I work with people from numerous different nationalities and backgrounds, this is a good common denominator. Of course the locale has to stay that way as well as I do not want others to mistake a period for a comma where numbers are concerned, etc. However all of us in our research center use Monday as the first day of the week. Implementing this setting therefore makes a lot of sense. Additionally, customizability is one of the main strengths of open source projects. Otherwise we can all just buy Apple and do it "their way". 

So please, give us a dedicated fdotw setting :)

**Comment by adamoell** [comment]
I have set my language to English (British), and the calendar is rendered Monday-first. UK calendars are pretty much universally Sunday-first. That is a clear bug. I can set my language to English (US), but then the dates are rendered the wrong way around. So, the calendar default for English (British) needs to be Sunday-first (this is a bug), while I would also support the call for a user/admin configurable parameter (this is a feature request). Thanks!

**Comment by freddie-freeloader** [comment]
Almost every calendar app gives me the choice for the starting day of the week - independent of my locale settings. It's super confusing for me to switch from other applications to Nextcloud Calendar. For this reason, I do not use the Nextcloud Calendar anymore. Most other stuff about the calendar is great!

Please consider reopening this issue.

**Comment by fazlerabbi37** [comment]
please reconsider this issue and re-open it.
ccing @tcitworld @georgehrke just to make this pop in your notification. :disappointed:

**Comment by noci2012** [comment]
This is becoming a nightmare... 
Same with setting up DEBIAN, it can;t be setup US, settings and then select UTC as a Timezone... weird.
Some tools using language as base for selecting all non-languagy things,
same for locales.. They should provide defaults. and the default should be able to be overriden.
Selecting English & US settings makes stuff work for me better (some software requires LC_ALL=C.. )
No Sunday is the first day?... (i am EU based btw),

**Comment by edumerco** [comment]
Please, let each person choose whatever it needs... 
Thanks a lot. :)

**Comment by lpulley** [comment]
Using locale makes _no sense_ for this. I use ISO dates, Monday first, 24-hour time, and US spelling. There is _no locale that does this_, or anything close to it. There should **absolutely** be user settings for 12/24 hours, Sunday/Monday first, US/UK/ISO date format, etc. like in **every major platform**.

If you think that locale-only is the right way to do this, you're ignoring a huge part of your userbase.

**Comment by sergilazaro** [comment]
This issue makes using nextcloud calendar a non-starter for me. A problem gets a wrong solution and complaints ignored.

**Comment by lpulley** [comment]
Is it possible to add a custom locale as a workaround for this?

**Comment by edumerco** [comment]
Maybe I didn't get it, but is it a fix available or was decided not to work on it? Thanks...

**Comment by noci2012** [comment]
AFAICT support that was inside calendar has been actively removed. So i HOPE but have serious doubts it will ever get fixed...

**Comment by erchbox** [comment]
Some people star their working week on Sundays, others on Monday independently of their country of residence.
The starting day of the week should be a setting based on the user preference not related at all to the locale settings.

**Comment by mschilli87** [comment]
@lpulley: I am in your boat. Did you ever find a viable solution?
I found 'English (Ireland)' to check most of my boxes (date are not ISO but at least day first, year last - so in some reasonable order :wink:). Unfortunatley, NextCloud is the only place I encountered where that locale results in Sunday being the first day of the week, deviating from other systems I have encountered.
Also, there is 'English (Germany)' amongst the locales I can choose from on NextCloud. While I have no clue what that is supposed to be, I have yet to meet a single German person to start their week on Sunday. Yet, the 'English (Germany)' locale does just that.
Did I miss the actual reason why this feature that is requested by many over years is opposed by the maintainers? Is there some implementation challenge or heavy maintenance burden I do not see or is this just a case of (American) ignorance? There have been so may good arguments here plus this feature is absolute standard in any other calendar I came across in the last decade.

To me, this issue makes the calendar useless.
So I'd probably stop using Nextcloud if I can't find a solution for this.
I actually missed important appointments because I got confused by the layout that is forced on me without explanation.

Please understand that I am not here to complain.
I want to find a solution.
I am willing to contribute.
But AFAICT, a PR would likely be rejected because you *want* your software to be broken. :wink:
Apparently, even politely asking for feedback is considered spam.
I find this whole issue very irritating and quite frankly alienating.

So I hope I am just misreading the discussion and somebody can shine a light on why the situation has to be as bad as it is right now and maybe there is some sort of hack to make it work: I have root access to the machine running Nextcloud; There *must* be a way to trick this broken calendar app into doing what so many of us want!

**Comment by binyamin** [comment]
> We won't have a dedicated start of week input, but there will be a locale setting in the server. So you will be able to select english as language and Poland as locale.

@georgehrke Perhaps I am confused. How does the start of the week relate to locale? Conceptually, [it's much earlier than the ISO 8601](https://en.wikipedia.org/wiki/Monday#Religious_observances) which defined Monday as the first day of the week.

Also, are you willing to give us a *reason* why you "won't" implement this feature? Doing so can mitigate a certain amount of further pushback.

**Comment by mschilli87** [comment]
@binyamin: I assume intended to link [here](https://en.wikipedia.org/wiki/Monday#Position_in_the_week). :wink:

Besides, since my last mesage did not receive any response in months, I since migrated away and simply stopped using this piece of software that apparently is unmaintained now. :frowning:

**Comment by lpulley** [comment]
> I since migrated away and simply stopped using this piece of software

Yep. There are enough calendar alternatives that I'm not going to fight this one for date formats when others make it easy.

**Comment by masterwishx** [comment]
Will we get option to change first day of week?
I leave in Israel for very long time but Hebrew is not my first language.
If I choose Hebrew for local I'm getting first day Sunday but also some text in Hebrew in nextcloud. 
But I need all nextcloud in my first language where first day is Monday. But in Israel I need first day Sunday. 
Please fix it

**Comment by tcitworld** [comment]
@masterwishx Please open your own issue.

**Comment by Waltibaba** [comment]
> I have set my language to English (British), and the calendar is rendered Monday-first. UK calendars are pretty much universally Sunday-first. That is a clear bug. I can set my language to English (US), but then the dates are rendered the wrong way around. So, the calendar default for English (British) needs to be Sunday-first (this is a bug), while I would also support the call for a user/admin configurable parameter (this is a feature request). Thanks!

It's funny since a corollary of @tcitworld 's statement is that they cannot possibly be correct or even internally consistent. What is the English language default first weekday? In India, South Africa, Jamaica, New Zealand, USA, Canada, UK or any other offically English-speaking country/locale?

**Comment by timmyreal** [comment]
Five years since the first post and Nextcloud still hasn't figured it out. lol

**Comment by AIndoria** [comment]
How in the world is this still a problem?

**Comment by cabo40** [comment]
Sorry @tcitworld, can you please open this issue again to make it more visible and increase the chances of  a PR?

**Comment by mschilli87** [comment]
@cabo40: AFAIR there is no interesting in ever fixing this (or even getting it fixed) since this is not considered a bug but a feature by the Nexcloud developer. :shrug:
I'd recommend using *any* other app for your calendar, since you'll have a hard time finding another one lacking such basic internationalization features.

**Comment by cabo40** [comment]
Thank you vm Cristoph!

**Comment by ChristophWurst** [comment]
@jancborchardt @nimishavijay  would it be ok to put a setting into the bottom left setting menu (or modal one day)? The default value can still be derived from the locale. But we can offer users to overwrite that.

**Comment by erchbox** [comment]
5 years seems like too much to get a simple request served. Thanks Christoph for reopening this case. Hopefully it won't take Nexcloud Team 5 more years to provide a solution.   ;-)
Cheers!

**Comment by ChristophWurst** [comment]
I'm sorry @erchbox but there is a slight misunderstanding. I'm reopening this for discussion and to align with designer on how this could be done. We do not plan to have anyone work on this from our team at this time.

**Comment by masterwishx** [comment]
Still good to have it in future, I can use calendar becose in my case, my first language Russian but leaving in Israel for very long time. So I need first day sanday but when I change it in local to Israel I also have Hebrew text in file dates but I need it russian. :(

**Comment by nimishavijay** [comment]
I think it makes sense to have this in the bottom left settings :)

**Comment by categulario** [comment]
@ChristophWurst @nimishavijay yes, that seems like the correct place for this setting.

**Comment by tcitworld** [comment]
Having the setting on the server side could benefit other apps (Tasks, Deck) and components (Datepicker) that make use of a week view. We would just override https://github.com/nextcloud/server/blob/ff58cd52279cccfbda0cc4683f1194d6c7ee283b/lib/private/Template/JSConfigHelper.php#L250 with an user value.

**Comment by jytou** [comment]
After being bitten for the n-th time by the starting day as a Sunday in my calendar, I definitely second this - everyone should be able to select a starting day, independently of other settings such as language or locale: they may be loosely related, but only *loosely*. :) It could certainly be on the server in order to benefit other apps.

**Comment by gilbsgilbs** [comment]
I have a local branch implementing this. I originally also wanted to support switching between meridian and non-meridian time formats.

As I found a locale that was good-enough for my use-case, I've lost motivation. But if somebody wants to finish up the work it should be a fairly easy task and good first issue: https://github.com/gilbsgilbs/calendar/compare/main...gilbsgilbs:calendar:custom-first-day

(Note that tests are missing on my branch, and the meridian feature does not work yet. However, as far as I remember, changing first day of week did work)

**Comment by bendev25689** [comment]
just to show there is interest in this issue, I would much prefer an interface such as the following, present in synology calendar.  
Much more versatile than relying on locale info which no-one can agree on.
![image](https://github.com/nextcloud/calendar/assets/41620719/cc157de6-3220-4b31-acaf-500303cbf1e3)

**Comment by masterwishx** [comment]
I think this problem needs be fixed long time ago in nextcloud ...

**Comment by politas** [comment]
The fact is, even if you have a locale that sets "week starts on" to Monday, Calendar is not respecting that. #5022 was supposed to fix that, but as of Calendar 4.5.2, it still isn't (Can we please have #2663 re-opened for that issue?

But seriously, this should be a user setting in calendar to allow override of the locale setting. People have requirements for their calendar that go beyond where they happen to live!

**Comment by bunk3m** [comment]
I see this as a serious issue with the NextCloud calendar.  As many have noted above, you absolutely have to be able to make specific adjustments for personal preferences.  In addition, we have to have the manual ability to change mistakes.  For example.  EN-CA English for Canada.  We have a mixed dictionary with British and US spelling of words.  Granted this isn't about the Calendar but it's a symptom of the rest.  We use metric for everything except for paper, buying groceries (mix of metric and imperial).  Good luck finding a ream of A4 paper here.  Nope, nada, nothing.  
Our date format is 2023-10-22 not 2023/10/22.  Most people use AM/PM but a lot of us use a 24 hour clock.  
I've seen people suggest English-UK but that local screws up our dictionary and the date format isn't right.  Every other software system allows fine tuning of these settings as one person posted drop downs above.
Sure, most people will be OK but the point of having a digital cloud based solution is that anyone can use it and set it up as they wish.  Allowing the individual to override the standard (not always correct) locale settings is essential.

**Comment by karolyi** [comment]
subscribing for notifications

**Comment by didvids** [comment]
Australian here. Setting the locale to 'English (Australia)' results in 'Week starts on Sunday'. Incorrect, needs a fix.

**Comment by KaKi87** [comment]
Also, I noticed the existence of an "English (World)" option, that indicates "Week starts on Monday", but when selected, calendar week still starts on Sunday.

On the other hand, "English (United Kingdom)", which also indicates the same thing, does make the calendar behave as advertised, although there's a 1-second delay for it to apply at each calendar page load.

Additionally, the locale dropdown isn't ordered alphabetically.

**Comment by masterwishx** [comment]
i have `(Auto) Asia/Jerusalem` in calendar but still have first day `Monday` instead of `Sunday` becouse of `Russian` in Local Settings.
Maybe just to add choosing in calendar setting start day like in all other calendars ?

**Comment by mschilli87** [comment]
Nextcloud celebrates its 8th birthday. This bug is over 7 years old. Maybe it is time to close this as wontfix because realistically nobody seems to care enough?

**Comment by KaKi87** [comment]
I am strongly against that and would rather keep regularly reminding the maintainers that their community is still waiting for this feature.

**Comment by edumerco** [comment]
Me too, don't close it.

7 years or of 8 deserves some attention to satisfy this little need of so 
many people of si many cultures. :)

2 jun. 2024 11:15:02 KaKi87 ***@***.***>:

**Comment by bunk3m** [comment]
> Nextcloud celebrates its 8th birthday. This bug is over 7 years old. Maybe it is time to close this as wontfix because realistically nobody seems to care enough?

They may not care enough but perhaps someone in the community will fix what is a problem for a lot of people.  This is table stakes for a calendar tool.  If you want to play with the big boys, you have to provide some basic configuration options for people.

What is doubly silly is the holiday calendar subscribe is also day off.  I haven't gotten around to logging a bug for this.  So there is more than one issue to fix.

**Comment by edumerco** [comment]
Thank you very much @st3iny !!! :clap: :clap: :clap:

**Comment by jancborchardt** [comment]
Thanks to everyone for your patience, sorry that sometimes some things take longer. :) Please keep the reports coming, and also use the :+1: functionality on issues, because this helps us estimate how much impact an issue has.

Hope you will enjoy the upcoming release! :heart:
