### ISSUE TITLE
Show loading animation when importing a (bigger) calendar

### ISSUE THREAD

**Issue by CodeAlDente** [nextcloud/calendar#3843]
I've just realized that there is no "feedback" in terms of a loading animation or some sort of it when you import a ICS file which might be bigger. In my case it was a calendar with 120 events. It took about 20 seconds but as I didn't get any response in that time I thought it might didn't get through. Just seconds before I wanted to take a look at the console log the events have been imported. That was shown in a box at the top right hand corner.
Wouldn't it be better to show a loading animation or even progress bar with the remaining time it needs to import the calendar? Or any other visual feedback for the user to indicate that the process is being handled?

**Comment by ChristophWurst** [comment]
I would appreciate if you could change your feature request to the format of the template https://github.com/nextcloud/calendar/issues/new?assignees=&labels=enhancement-proposed%2C+0.+to+triage&template=feature_request.md&title=
