### ISSUE TITLE
Send event invitation to the person who booked an appointment

### ISSUE THREAD

**Issue by Bubu** [nextcloud/calendar#3855]
**Is your feature request related to a problem? Please describe.**
After clicking the confirmation link for an appointment, I'd expect to be mailed a proper event invitation to add to my local calendar.

Currently this doesn't happen.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
Addding the event to the confirmation email as described here: https://github.com/nextcloud/calendar/issues/3852#issuecomment-1002146079

This would probably have way more potential for confusion if users forget to also click the confirmation link.

**Additional context**
See #3852

**Comment by 42ske** [comment]
In addition the confirmation mail should contain:
- date and time of the appointment as text
- free text which can be set in the appointement's options
- a link to cancel the appointment again
- an ics-file with the appointment including infos which can be defined in the options
