### ISSUE TITLE
Tiny scrollbar - difficult to use

### ISSUE THREAD

**Issue by rexxmagnus** [nextcloud/calendar#3856]
**Is your feature request related to a problem? Please describe.**
It's very difficult to select the scroll bar on the calendar interface - the default styling is 'thin' which doesn't fit with the rest of Nextcloud, and if you're one of those people who drags the scrollbar with the mouse, it can be very frustrating to select it.

**Describe the solution you'd like**
I'd like to see the scrollbars on the calendar app the same width as the rest of nextcloud, making it more accessible.

**Describe alternatives you've considered**
I've overridden the styling in the theming section at the moment, but this isn't a viable permanent fix.

**Comment by ChristophWurst** [comment]
sceenshot? what scroll bar specifically?

**Comment by rexxmagnus** [comment]
The most notable case is on the right of the main monthly calendar display
![image](https://user-images.githubusercontent.com/1889538/147643948-27774ce1-62f6-488d-bb88-3093f754baed.png)

It gets overridden by a stylesheet loading as fcbe-9b56-server.css on a declaration covering almost all html elements. I presumed the fcbe part was to do with the calendar. But actually, investigating it now, it seems that stylesheet appears on other apps, so it may be a general theming issue (I'm using dark and breeze dark, so maybe I need to take it up with the theme producers).

**Comment by ChristophWurst** [comment]
Then it's likely a global rule in https://github.com/nextcloud/server
