### ISSUE TITLE
occ upgrade: The table with name 'db.oc_calendar_appt_configs' already exists

### ISSUE THREAD

**Issue by jernst** [nextcloud/calendar#3857]
Database migration fails with "table already exists" when upgrading to Nextcloud 22.2.3, calendar 3.0.1, with `occ upgrade -v -v`:
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2021-12-28T20:30:25+00:00 Setting log level to debug
2021-12-28T20:30:25+00:00 Repair step: Repair MySQL collation
2021-12-28T20:30:25+00:00 Repair info: All tables already have the correct collation -> nothing to do
2021-12-28T20:30:25+00:00 Repair step: Repair SQLite autoincrement
2021-12-28T20:30:25+00:00 Repair step: Copy data from accounts table when migrating from ownCloud
2021-12-28T20:30:25+00:00 Repair step: Drop account terms table when migrating from ownCloud
2021-12-28T20:30:25+00:00 Updating database schema
2021-12-28T20:30:25+00:00 Updated database
2021-12-28T20:30:25+00:00 Updating <calendar> ...
2021-12-28T20:30:26+00:00 Doctrine\DBAL\Schema\SchemaException: The table with name 'db.oc_calendar_appt_configs' already exists.
2021-12-28T20:30:26+00:00 Update failed
2021-12-28T20:30:26+00:00 Maintenance mode is kept active
2021-12-28T20:30:26+00:00 Resetting log level
```

Maybe the migration already happened, but it is not recognizing that and tries again?

Ideas:
* manually drop that table before next attempt to upgrade: but that might lose data?
* manually change the schema version (which I assume exists somewhere ... where?)
* maybe there is a ''--force" somewhere?

All ideas / help appreciated. /cc @ShauneDonohue

**Comment by ChristophWurst** [comment]
> Maybe the migration already happened, but it is not recognizing that and tries again?

Nextcloud should only run them once.

**Comment by ChristophWurst** [comment]
It's the migration https://github.com/nextcloud/calendar/blob/main/lib/Migration/Version2040Date20210908101001.php that ran twice apparently. I do not have an explanation for that scenario.

**Comment by jernst** [comment]
How do we get this installation working again? I assume there is some kind of schema version identifier somewhere that maybe we could increment manually?

**Comment by ChristophWurst** [comment]
Nextcloud keeps track of the executed migrations in the `migrations` table

**Comment by jernst** [comment]
Turns out there is no entry for calendar in that table at all. Selection:
```
| app                   | version                     |
+-----------------------+-----------------------------+
| activity              | 2006Date20170808154933      |
| activity              | 2006Date20170808155040      |
...
| activity              | 2011Date20201207091915      |
| audioplayer           | 2102Date20200712193332      |
| audioplayer           | 2102Date20200712203332      |
| audioplayer           | 2102Date20200712213332      |
| audioplayer           | 3002Date20210019213332      |
| bookmarks             | 000014000Date20181002094721 |
| bookmarks             | 000014000Date20181029094721 |
...
| bookmarks             | 004005000Date20210918124721 |
| contactsinteraction   | 010000Date20200304152605    |
| core                  | 13000Date20170705121758     |
...
```

Seems we are going to try and `INSERT INTO oc_migrations( app, version ) VALUES( "calendar", "2040Date20210908101001" );` and see where that leads.

**Comment by jernst** [comment]
Comparing with a working install, it turned out that many rows in the migrations table were missing. Several apps were affected, and in some cases more than one row was missing for an app.

We currently have no information on how this happened, but it is not out of the question that the migration was interrupted on the original run.

Q: do the migrations run, and is the migrations table updated within a single transaction? Probably not?

I'm closing this because this appears to be a one-off. If not, we can always reopen.

**Comment by ChristophWurst** [comment]
If you run into this another time please open a report at https://github.com/nextcloud/server. This app doesn't have any influence on the tracking of migrations. This is done by the server component.
