### ISSUE TITLE
Calendar ignores ical DESCRIPTION;ALTREP when updating event description

### ISSUE THREAD

**Issue by cm-schl** [nextcloud/calendar#3863]
Discussion started at Bugzilla of the Thunderbird Project: [1748002](https://bugzilla.mozilla.org/show_bug.cgi?id=1748002)
Preamble: Thunderbird introduced formatting options for event descriptions that are saved via CalDAV as `DESCRIPTION;ALTREP`. Thunderbird always saves a HTML version (formatted) and a plain text version of the event description like defined in [RFC5545](https://datatracker.ietf.org/doc/html/rfc5545#section-3.2.1).

### Steps to reproduce
1. Use Thunderbird Version 91 to create an event with text in the description field, for example the word "test". The event gets saved correctly on the CalDAV server. The description field of the VEVENT contains:
`DESCRIPTION;ALTREP="data:text/html,%3Cbody%3Etest%3C%2Fbody%3E":test`
2. Open Nextcloud Calendar and edit the event description text to "1111111111111111test". Now the VEVENT on the server looks like this:
`DESCRIPTION;ALTREP="data:text/html,%3Cbody%3Etest%3C%2Fbody%3E":1111111111111111test`
3. Open the event in Thunderbird. The event description only contains "test" because Thunderbird shows the content of `ALTREP`.

### Expected behaviour
After a discussion at bugzilla.mozilla.org ([1748002](https://bugzilla.mozilla.org/show_bug.cgi?id=1748002)) it seems not correct that Nextcloud updates only the plaintext version of the event description without modifying or deleting the alternative representation under `ALTREP`. Other CalDAV clients like mobile phone apps seem to delete everything under `ALTREP` when the plaintext version has been modified by the user.
The problem is that actually the user does not see modifications made via Nextcloud (for example in shared calendars) and therefore overwrites these changes if he tries to update the event description using Thunderbird.

Naturally the best solution would be if Nextcloud Calendar would show the formatted version instead of the plaintext version 😉, but at the moment it seems important that Thunderbird users aren't going to overwrite changes made using Nextcloud.

### Actual behaviour
As you can see Nextcloud only updates the plain text description, but the HTML description in ALTREP isn't updated nor deleted.

### Calendar app
**Calendar app version:** 3.0.4

**CalDAV-clients used:** Thunderbird Lightning, DAVx5, Simple Calendar (Android) for tests

### Client configuration
**Browser:** Firefox 91.4.1

**Operating system:** Windows 10

**Nextcloud Version:** 21.0.7

**Comment by tcitworld** [comment]
Thanks for the bug report.

As a sidenote, we will probably use [RFC9073's `STYLED-DESCRIPTION`](https://www.rfc-editor.org/rfc/rfc9073.html#section-6.5) for rich text formatting if we ever have this feature (see #3234), not `ALTREP`.

**Comment by benbucksch** [comment]
The bug comes from the data being inconsistent now. When the description changes, the properties of the description field are no longer valid.

The expected minimal behavior is that NextCloud, when writing the `DESCRIPTION` field, also deletes the properties of the description field, which are now outdated.

So, the fix here should be trivial: When setting `DESCRIPTION`, just delete all properties of `DESCRIPTION`, including `ALTREP`. That avoids the bug.

**Comment by benbucksch** [comment]
* From Thunderbird, before modification:
  `DESCRIPTION;ALTREP="data:text/html,%3Cbody%3Etest%20one%3C%2Fbody%3E":test one`
* After modification in NextCloud - Actual result:
  `DESCRIPTION;ALTREP="data:text/html,%3Cbody%3Etest%20one%3C%2Fbody%3E":test two`
* After modification in NextCloud - Expected result:
  `DESCRIPTION:test two`

Given that the property parameters describe the property (not the whole calendar item, just this property), and the property changed, it's reasonable to assume that the parameters which described the old property are no longer valid.

**Comment by Gorendal** [comment]
The same issue comes with X-ALT-DESC, which is used by other clients like Outlook and eM-Client to add an HTML representation of the description value. Would it be possible to delete the field, too, once the description is changed in Nextlcoud?

**Comment by max65482** [comment]
This should be fixed in #3924. All parameters should be deleted upon modification of the description. Can you give exact reproduction steps or excerpts from ics files?

**Comment by benbucksch** [comment]
@Gorendal Could you file a new ticket about that, and mention the new ticket number here?

While it's the same symptom, the cause is different, because ALTREP is a "parameter" of the modified DESCRIPTION property, whereas X-ALT-DESC is a completely different property. It needs a different fix.

**Comment by st3iny** [comment]
@Gorendal @benbucksch Please refer to #4744.

**Comment by Gorendal** [comment]
@st3iny @benbucksch is there still something to be done from my side?
Sorry, I am new to GitHub. So I haven't got the complete picture how this all works yet.

**Comment by benbucksch** [comment]
@Gorendal No. Possibly in reaction to your comment, st3iny filed a new ticket #4744, which captures the problem that you raised. (It is a different problem that this ticket here, and this ticker here is already fixed, therefore it needed a new ticket.)

Good news is that #4744 was already fixed, so the problem you mentioned should be fixed now. It was even backported to NextCloud 3.5.x and 4.1.x.

You can test the next NextCloud release, whether it fixes your issue. Otherwise, there's nothing more to do.

**Comment by benbucksch** [comment]
@Gorendal Please make your comments at#4744, not here, as it's offtopic here. Thank you.

**Comment by st3iny** [comment]
@Gorendal The fix is yet to be released. It will most likely be included in v4.1.1 and any later version.
