### ISSUE TITLE
Follow up to design changes in month view

### ISSUE THREAD

**Issue by szaimen** [nextcloud/calendar#3865]
@dartcafe please delete the above mentioned code again since @jancborchardt agreed to make it globablly for all views.

---

```
		.fc-event {
			box-shadow: 0px 0px 0px 1px var(--color-primary-light) !important;
		}
```
and
```
		&.fc-col-header-cell {
			background-color: var(--color-primary-light);
		}
```
is probably still missing from the global styling though...

_Originally posted by @szaimen in https://github.com/nextcloud/calendar/pull/3817#discussion_r778673360_

**Comment by jancborchardt** [comment]
Just to clarify if this relates to that: I misspoke in my original comment at https://github.com/nextcloud/calendar/pull/3817 – the header should only be primary-light in the day and week view, _not_ in month view (where only the cell should be primary-light of course). :)

**Comment by dartcafe** [comment]
Do you mean that?

current | changed 
-|-
![grafik](https://user-images.githubusercontent.com/26707476/148373726-496bc01c-53f1-4a52-aa61-b972b5910ee0.png) | ![grafik](https://user-images.githubusercontent.com/26707476/148373735-2b5ed129-76ec-4573-834f-d5f3f6d23eb7.png)

**Comment by jancborchardt** [comment]
@dartcafe ah more confusion, sorry. To clear it up:
- Month view is totally perfect as it is in your "current" screenshot above, no changes needed :+1: 
- Week view as shown in your screenshot at https://github.com/nextcloud/calendar/pull/3817#issuecomment-1005236265 is also great, no changes needed :+1: 
- Day view as shown in your screenshot at https://github.com/nextcloud/calendar/pull/3817#issuecomment-1005236265 needs color-primary-light in the table header still :)
