### ISSUE TITLE
Cannot change calendar events, in which i was invited by other people

### ISSUE THREAD

**Issue by Bolli84** [nextcloud/calendar#3866]
### Steps to reproduce
1. I got an invite by another person on the same cloud
2. Accept the invite
3. Want to change anything in this event e.g. Appointment color, calendar (if you use more then one)
4. No option to change the content is available

### Expected behaviour
It should be possible to change the content. 

### Actual behaviour
No dropdown is visible

### Calendar app
**Calendar app version:** 3.0.4

### Client configuration
**Browser:** Chrome 96

**Operating system:** (e.g. Arch Linux)

### Server configuration
**Web server:** Apache
**Database:** MariaDB
**Nextcloud Version:** 22.2.3
**Updated from an older installed version or fresh install:** Updated

**Comment by GretaD** [comment]
Hello @Bolli84,

What steps did you follow to try to change the calendar event?

The steps would be, you open your Nextcloud calendar, click the **event**, then on the popup click **More**. The side bar on the right will be open and there you can edit.

If you did the steps below, can you please tell me or sent a screenshot what is shown?

**Comment by Bolli84** [comment]
hello @GretaD 

Here we go and I already did that, since I use the calendar long time and it worked in the past.

When I create an appointment i got the following:
![1](https://user-images.githubusercontent.com/37924972/148516290-5d839122-69e6-46a0-83d6-3860a8ec13c9.png)

When someone else created the appointment and invites me:
![2](https://user-images.githubusercontent.com/37924972/148516369-d979fe75-c0a3-400e-bf03-3c65b9d0ea4e.png)

You can see in picture 1, the boxes for changing the contents are available and it is possible to move it. in Picture 2, it is not possible to change it, except the title.

**Comment by GretaD** [comment]
Ah, yes, that is correct, only the owner can change the event that they created, they need to give you access for that. I thought, you couldn't changed it even though you were supposed to. If you want to know more about how to use/share calendar please refer to https://help.nextcloud.com/ as this repository here on github is for developers and for technical problems.,

**Comment by Bolli84** [comment]
If I import an event (*.ics) INTO MY Calendar, I am not able to change it? 
e.g. I use the mail app and import an calendar-event I got invited to. then i cannot change it?

Second: if someone invites me, the entry always goes to the "personal" calendar. but if I do not want it there but in another calendar?

In the past, that was possible.

**Comment by miaulalala** [comment]
This could be related to the fix here: https://github.com/nextcloud/calendar/pull/3424

@st3iny can you confirm if we made the invitee unable to edit the calendar picker? :pray:

**Comment by raimund-schluessler** [comment]
> @st3iny can you confirm if we made the invitee unable to edit the calendar picker? 🙏

Yes, you did:
https://github.com/nextcloud/calendar/pull/3424/files#diff-a884ae967dfa6d1fdecb3b291f56f261735e7e0dc0b47a3e1b968d19ddd9cd83R94

**Comment by miaulalala** [comment]
He thanks Raimund, but I just merged, the PR is by Richard :smile_cat:

**Comment by raimund-schluessler** [comment]
> He thanks Raimund, but I just merged, the PR is by Richard 😸

Sorry, no offense, this was not meant as "you personally", rather as "you, the developers". But yeah, let's agree it's Richards fault 😆🙈

**Comment by st3iny** [comment]
As I'm the one who submitted the PR I want to clarify two things:

1. This does not appear to be the edge case I mentioned in the PR. It only applies to editing events within shared (read-write) calendars.
2. Yes, it is correct that your use case was possible before my PR but it was not in line with the official specifications. The invitee may not edit an event he/she was invited to. Instead, he/she is only allowed to edit the name, reminders and accept/decline. This limitation applies to many other clients as well (e.g. Thunderbird).

**Comment by raimund-schluessler** [comment]
> As I'm the one who submitted the PR I want to clarify two things:
> 
>     1. This does not appear to be the edge case I mentioned in the PR. It only applies to editing events within shared (read-write) calendars.
> 
>     2. Yes, it is correct that your use case was possible before my PR. However, it was not in line with the official specifications. The invitee may not edit an event he/she was invited to. Instead, he/she is only allowed to edit the name, reminders and accept/decline. This limitation applies to many other clients as well (e.g. Thunderbird).

But here it looks like you cannot change events that are located in your own calendar (as in you created the calendar) if you are an attendee and not the organizer. This seems weird to me. Is this really what the specification implies?

**Comment by st3iny** [comment]
> > As I'm the one who submitted the PR I want to clarify two things:
> > ```
> > 1. This does not appear to be the edge case I mentioned in the PR. It only applies to editing events within shared (read-write) calendars.
> > 
> > 2. Yes, it is correct that your use case was possible before my PR. However, it was not in line with the official specifications. The invitee may not edit an event he/she was invited to. Instead, he/she is only allowed to edit the name, reminders and accept/decline. This limitation applies to many other clients as well (e.g. Thunderbird).
> > ```
> 
> But here it looks like you cannot change events that are located in your own calendar (as in you created the calendar) if you are an attendee and not the organizer. This seems weird to me. Is this really what the specification implies?

Events that you get invited to will be placed inside your personal calendar and thus will be read only. Otherwise, the event should be editable if the calendar is writeable. It's hard to tell without looking at the invitees tab.

**Comment by Bolli84** [comment]
I added the attendee tab image
 ![3](https://user-images.githubusercontent.com/37924972/148557873-960d7162-377d-440a-bee6-37cadddf2710.png)

Situation: I have one calendar "personal", one calender "golf" one calendar "out-for-beer"
My wife can see the calendar "personal" :-) everything I got an invite from by beer or golf-friends, the invite is unchangeable (even no delete!!) in my personal calendar. 

If that is the specification, the systematic of multiple calendars and shared calendars with restrictions is useless.

**Comment by Bolli84** [comment]
Another point on it: 
If the organizer of a reocurring leaves the team or dies, NO ONE chan change or remove it.

Looking into outlook or teams, I can delete the event for me as well as I can move it to different calendars, which I own (shared ones and private ones).

**Comment by SergeyMosin** [comment]
Here are a couple of use-case when a calendar owner can not edit/delete events in own calendar because event `ORGANIZER` email does not match owner email: https://github.com/SergeyMosin/Appointments/issues/279#issuecomment-1010498737

**Comment by st3iny** [comment]
> Another point on it: If the organizer of a reocurring leaves the team or dies, NO ONE chan change or remove it.
> 
> Looking into outlook or teams, I can delete the event for me as well as I can move it to different calendars, which I own (shared ones and private ones).
> 
> I understand, Time, Date, Location, Description shall not be changeable by invitees. The rest does not make sense to have it RO.
> 
> @st3iny which is the specification you are talking about?

@Bolli84 We discussed your ideas internally and came to the conclusion that we should definitely allow deleting invitations. Moving invitations between calendars seems to be a good idea too but needs some testing as this might break the propagation of invitation responses.

---

> Here are a couple of use-case when a calendar owner can not edit/delete events in own calendar because event ORGANIZER email does not match owner email: SergeyMosin/Appointments#279 (comment)

@SergeyMosin Thank you for the triage. Especially use case 1 seems to be a big problem. We'll need to refactor/fix the whole owner vs. attendee vs. organizer detection logic to fix that properly.

**Comment by Bolli84** [comment]
@st3iny in the meantime, since this issue I reverted back to version 3.0.2, which was the solution for now. 
Changing the selected calendar does NOT impact the appointment/event at all.  If you need someone to test it, send me the package :-)

**Comment by berkaycagir** [comment]
> @st3iny in the meantime, since this issue I reverted back to version 3.0.2, which was the solution for now. Changing the selected calendar does NOT impact the appointment/event at all. If you need someone to test it, send me the package :-)

How did you revert back to it? Just downloading [this](https://github.com/nextcloud/calendar/releases/tag/v3.0.2) and overwriting the current calendar directory?

**Comment by st3iny** [comment]
> > @st3iny in the meantime, since this issue I reverted back to version 3.0.2, which was the solution for now. Changing the selected calendar does NOT impact the appointment/event at all. If you need someone to test it, send me the package :-)
> 
> How did you revert back to it? Just downloading [this](https://github.com/nextcloud/calendar/releases/tag/v3.0.2) and overwriting the current calendar directory?

Downgrading is not supported. Usually, you revert to a full backup if you need to downgrade. 

However, we decided to revert the whole read-only PR (https://github.com/nextcloud/calendar/pull/3424) because of the issues that you all have discovered. We also plan to release the fix next week.
