### ISSUE TITLE
Fail to display some french symbols

### ISSUE THREAD

**Issue by Wenzel** [nextcloud/calendar#387]
### Steps to reproduce
1. Put nextcloud in french
2. Open calendar app
3. add new event
4. go to reminder
5. configure an alert window

### Expected behaviour
The sentence `Fenêtre d'alerte 15 minutes avant l'évenement` should be displayed

### Actual behaviour
What is displayed : `Fenêtre d&#039;alerte 15 minutes avant l'évenement`
![translation](https://cloud.githubusercontent.com/assets/964610/24332900/36b934a2-1257-11e7-82a6-7760093e931c.png)

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 5

**Server version:** 11.0.2

**Calendar version:**  calendar: 1.5.0

**Updated from an older installed version or fresh install:** updated from owncloud

### Client configuration
**Browser:** Chromium

**Operating system:** Fedora

**Comment by georgehrke** [comment]
please use the search before creating new bug reports

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/269

**Comment by Wenzel** [comment]
I used the search, but i didn't find anything.
