### ISSUE TITLE
Timezone information not uniformaly applied

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/calendar#3882]
### Steps to reproduce
1. Get a calendar invitation with an event from another timezone and add it to the calendar

### Expected behaviour

The event is displayed with the local timezone or the timezone information is displayed if the timezone is different than the current ont

### Actual behaviour

The date displayed in month view is in the local timezone, date in the detail views is in the other timezone without timezone information. This is confusing.

Detail sidebar:

![image](https://user-images.githubusercontent.com/23653902/149414017-594a8eb0-50b4-4c4f-af38-0c10a905b620.png)

Month view of the same event:

![image](https://user-images.githubusercontent.com/23653902/149414092-187bba57-0af6-499c-a94a-407045e9fb74.png)

### Calendar app
**Calendar app version:** Latest stable release

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:** Firefox 95

**Operating system:** openSUSE tumbleweed

**Comment by st3iny** [comment]
Thanks for the report.

I can't reproduce this on master. In the grid it's shown in the local tz and in the sidebar it is shown in the event tz with tz information next to it.

![Screenshot_20220114_102503](https://user-images.githubusercontent.com/1479486/149491733-a2002f2a-bd74-4a5c-a57b-069a654104ed.png)
