### ISSUE TITLE
blank page on calendar with 3.0.5 and Nextcloud < 22.2.3, multiple browsers

### ISSUE THREAD

**Issue by yeupou** [nextcloud/calendar#3897]
### Steps to reproduce
on a working installation (calendar working in CalDAV with thunderbird and the phone app)
1. open a browser (firefox 96, chromium 97) to the calendar page, with any user

### Expected behaviour
to show the calendar

### Actual behaviour
the calendar part of the page is blank - there is only the nextcloud top menu

in nginx logs are some "SSL_write() failed while sending response to client" errors logged. everything works besides the calendar

### Calendar app
**Calendar app version:** 3.0.5

**CalDAV-clients used:** not involved, working with CalDAV

### Client configuration
**Browser:** (e.g. Firefox 48)
Mozilla Firefox 96.0.1
Chromium 97.0.4692.71 built on Debian bookworm/sid, running on Debian bookworm/sid

**Operating system:** (e.g. Arch Linux) Devuan GNU/Linux

### Server configuration

**Operating system**: (e.g. Debian 8)   Devuan 4.0

**Web server:** (e.g. Apache, Nginx,...)  Nginx

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)  MariaDB

**PHP version:** (e.g. 7.0.3)   7.4

**Nextcloud Version:** (see admin page, e.g. 17.0.2)   22.2.0

**Updated from an older installed version or fresh install:** both, first updated, then removed/fresh install

**List of activated apps:**

Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - apporder: 0.14.0
  - bookmarks: 10.0.3
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.5
  - camerarawpreviews: 0.7.15
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - contacts: 4.0.7
  - contactsinteraction: 1.3.0
  - cookbook: 0.9.9
  - dav: 1.19.0
  - drawio: 1.0.2
  - emlviewer: 1.0.0
  - encryption: 2.10.0
  - event_update_notification: 1.4.0
  - extract: 1.3.3
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_3d: 0.3.3
  - files_antivirus: 3.2.2
  - files_automatedtagging: 1.12.0
  - files_external: 1.13.0
  - files_markdown: 2.3.5
  - files_pdfviewer: 2.3.0
  - files_readmemd: 1.2.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - firstrunwizard: 2.11.0
  - geoblocker: 0.5.2
  - groupfolders: 10.0.2
  - impersonate: 1.9.0
  - keeweb: 0.6.8
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - maps: 0.1.10
  - metadata: 0.15.0
  - notes: 4.3.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - previewgenerator: 3.4.1
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.13.0
  - ransomware_protection: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - survey_client: 1.10.0
  - suspicious_login: 4.1.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
Disabled:
  - comments
  - dashboard
  - epubreader
  - federation
  - files_reader
  - files_videoplayer
  - music
  - nextcloud_announcements
  - sharebymail
  - support
  - user_ldap
  - user_status
  - weather_status

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "cloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.0.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 7,
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 3,
        "theme": "",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "keeweb",
            "files_readmemd",
            "files_reader",
            "emlviewer",
            "files_fulltextsearch_tesseract",
            "epubreader",
            "files_3d"
        ],
        "mail_sendmailmode": "pipe",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false
    }
}

#### Web server error log (e.g. /var/log/apache)

no error in logs

#### Log file (data/nextcloud.log)

empty since last rotation

#### Browser log

Nothing that stands out besides
'La ressource à l’adresse « https://*REMOVED SENSITIVE VALUE**/apps/files/ » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).calendar'

**Comment by yeupou** [comment]
So, I updated to Nextcloud 22.2.3 and everythink is back to normal.

I do not know if Nextcloud allows it, but Calendar 3.0.5 should maybe me marked as incompatible with Nextcloud < 22.2.3.

**Comment by joshtrichards** [comment]
> So, I updated to Nextcloud 22.2.3 and everything is back to normal.
