### ISSUE TITLE
Event can be moved between calendars exactly once

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#3898]
### Steps to reproduce
The word "editor" refers to the simple editor.

1. *Optional:* Make sure that you have at least 2 calendars.
2. Create a new event and save it.
3. Edit the event again, move it to another calendar and save it.
4. **Problem 1:** Edit the event again and you will see that the change of calendar was applied in the grid but not in the editor.
5. Refresh the page.
6. Edit the event again and now the editor shows the correct calendar.
7. Change the calendar of the event again and save it.
8. **Problem 2:** The spinner will load forever. There is also an error in the console.

### Problem 1

![Screenshot 2022-01-21 at 10-18-30 January 2022 - Calendar - Nextcloud](https://user-images.githubusercontent.com/1479486/150500738-ca2c06b1-7031-41e5-8e25-ff69af25a190.png)

### Problem 2

![Peek 2022-01-21 10-11](https://user-images.githubusercontent.com/1479486/150500451-fbae1450-3520-4447-950f-fded7011223d.gif)

### Expected behaviour
I should be able to change the calendar of an event as often as I please.

### Actual behaviour
I can move an event exactly once between calendars. Starting from the second time it will always fail. 

Another thing I noticed it that every time I move an event from one calendar to another, the "old" event will be put into the trash bin. The moved event (in the new calendar) will stay in the grid and the old event (with the previous calendar) will be placed in the trash bin.

### Calendar app
**Calendar app version:** main

### Logs
<details>
  <summary>Browser log</summary>

```
[Vue warn]: Error in v-on handler (Promise/async): "Error"

found in

---> <SaveButtons> at src/components/Editor/SaveButtons.vue
       <VPopover>
         <Popover>
           <EditSimple> at src/views/EditSimple.vue
             <Content>
               <Calendar> at src/views/Calendar.vue
                 <App> at src/App.vue
                   <Root> vue.runtime.esm.js:619

Error: 
    b dist.js:1
    _ dist.js:1
    A dist.js:1
    onreadystatechange dist.js:1
    request dist.js:1
    request dist.js:1
    move dist.js:1
    move dist.js:1
    _callee$ calendarObjects.js:220
    u runtime.js:63
    _invoke runtime.js:294
    v runtime.js:119
    asyncGeneratorStep calendarObjects.js:1
    _next calendarObjects.js:3
    _asyncToGenerator calendarObjects.js:3
    _asyncToGenerator calendarObjects.js:3
    moveCalendarObject calendarObjects.js:254
    wrappedActionHandler vuex.esm.js:851
    dispatch vuex.esm.js:516
    boundDispatch vuex.esm.js:406
    _callee5$ calendarObjectInstance.js:1815
    u runtime.js:63
    _invoke runtime.js:294
    v runtime.js:119
    asyncGeneratorStep calendarObjectInstance.js:13
    _next calendarObjectInstance.js:15
    _asyncToGenerator calendarObjectInstance.js:15
    _asyncToGenerator calendarObjectInstance.js:15
    saveCalendarObjectInstance calendarObjectInstance.js:1826
    wrappedActionHandler vuex.esm.js:851
    dispatch vuex.esm.js:516
    boundDispatch vuex.esm.js:406
    _callee2$ EditorMixin.js:523
    u runtime.js:63
    _invoke runtime.js:294
    v runtime.js:119
    asyncGeneratorStep EditorMixin.js:1
    _next EditorMixin.js:3
    _asyncToGenerator EditorMixin.js:3
    _asyncToGenerator EditorMixin.js:3
    save EditorMixin.js:537
    _callee3$ EditorMixin.js:558
    u runtime.js:63
    _invoke runtime.js:294
    v runtime.js:119
    asyncGeneratorStep EditorMixin.js:1
    _next EditorMixin.js:3
    _asyncToGenerator EditorMixin.js:3
    _asyncToGenerator EditorMixin.js:3
    saveAndLeave EditorMixin.js:571
    only EditSimple.vue:420
    VueJS 4
    saveThisOnly SaveButtons.vue:93
    VueJS 33
vue.runtime.esm.js:1897
```

</details>

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/3325?

**Comment by st3iny** [comment]
> Duplicate of #3325?

Looks like it.
