### ISSUE TITLE
Subcribtion of a public calendar

### ISSUE THREAD

**Issue by b90g** [nextcloud/calendar#3916]
I hope i didnt miss something, i couldnt find anthing off with that link except comming from a microsoft server...

### Steps to reproduce
1. Subscribe to https://anwendungen.bielefeld.de/bi/termine.asp#
2.
3.

### Expected behaviour
Appointments show up or an error message about malformed7non rfc-compilant files 

### Actual behaviour
Nothing

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
Latest
**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
Clients: OutLook, Thunderbird
### Client configuration
**Browser:** (e.g. Firefox 48)
FireFox latest
**Operating system:** (e.g. Arch Linux)
Debian
### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)
Nginx
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0.3)
7.4 Afaik
**Nextcloud Version:** (see admin page, e.g. 17.0.2)
22.x
**Updated from an older installed version or fresh install:**
didnt work on 19 doesnt work on 22
**List of activated apps:**
Circles,
KeeWeb,
Contacts,
Calendar,
Groupfolders,
UserSAML,

**Nextcloud configuration:**
on request
#### Web server error log (e.g. /var/log/apache)
on request
#### Log file (data/nextcloud.log)
on request
#### Browser log
nothing

**Comment by tcitworld** [comment]
Is the issue about the lack of feedback when adding an invalid calendar subscription? If so, that's https://github.com/nextcloud/server/issues/30825

Feel free to reopen with more details if that's not it.

**Comment by b90g** [comment]
Thanks, not sure, the calender from my report doesnt seem to work with nextcloud calendar, but with thunderdbird and outllok.

i will subscribe to the feedback issue and if nextcloud finally gives feedback i will reopen here what feedback i got.

**Comment by tcitworld** [comment]
Yeah, it's not really invalid, https://icalendar.org/validator.html only gives some warnings.

The parser shouldn't choke on this kind of warnings, but this is another issue.
