### ISSUE TITLE
Avatar not loading in AvatarParticipationStatus Component

### ISSUE THREAD

**Issue by lucasra1** [nextcloud/calendar#3923]
I have looked through the code a bit and it seems to happen in the `AvatarParticipationStatus? Component. Apparently it is only provided the display name and the email. It passes the display name as the userid to the `Avatar` component, which tries to load the profile picture with the display name instead of the userid.

### Steps to reproduce
1. Have a user
  - Username: john
  - Display Name: John Doe
  - Email: j.doe@example.com
2. Open the edit Sidebar for an event and add John Doe (Autocomplete works fine)
3. As soon as John Doe is listed as an Attendee, the avatar doesnt show.

### Expected behaviour
See the Avatar of Attendees

### Actual behaviour
Avatar and Link not functional

### Calendar app
**Calendar app version:** 3.0.5
**Nextcloud Version:** 23.0.0

#### Browser log
```
GET https://nextcloud.example.com/avatar/John%20Doe/32 404
GET https://nextcloud.example.com/ocs/v2.php/apps/user_status/api/v1/statuses/John%20Doe 404
```

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/calendar/issues/3099, see WIP in https://github.com/nextcloud/calendar/pull/3101
