### ISSUE TITLE
add Online Status to events 

### ISSUE THREAD

**Issue by D3nn7** [nextcloud/calendar#3931]
**Is your feature request related to a problem? Please describe.**
The feature is not directly related to a problem. 

**Describe the solution you'd like**
It would be nice to be able to set the online status in a calendar event. This should be set when the event starts.

**Comment by tcitworld** [comment]
Can you add more details to explain what you mean and what's the online status you're talking about?

**Comment by D3nn7** [comment]
Yes, no problem :) I mean the user status from Nextcloud.
I would like to have the possibility to set the user status for this event in a calendar entry.

For example:
```
Event: Cinema
User Status:🎦 In Cinema
Date: 05 Feb 2022 19:00
```

So if the event "_Cinema_" starts at 7pm, the user status should be set to the value "🎦 In Cinema" set by the user.

**Comment by ChristophWurst** [comment]
related: https://github.com/nextcloud/server/issues/27990

**Comment by tcitworld** [comment]
Thanks for the details! Should we keep this issue or is the server issue enough (it would be handled in server anyway) ?

**Comment by ChristophWurst** [comment]
If I understand it correctly then this feature request is a bit more specialized than the *show busy when I have a busy event*.

We should have the simpler integration first before we jump into any details.

**Comment by SebastianKrupinski** [comment]
Hi @D3nn7 

Is the change we made here sufficient? https://github.com/nextcloud/server/issues/27990

**Comment by SebastianKrupinski** [comment]
Perfect. Thank you for letting us know.
