### ISSUE TITLE
Share calendar with Everyone

### ISSUE THREAD

**Issue by bwduncan** [nextcloud/calendar#3938]
Hi, thanks for a great project!

**Is your feature request related to a problem? Please describe.**
I'm trying to share a calendar with the entire organisation.

**Describe the solution you'd like**
I'd like to be able to share with the "Everyone" group which appears in the "Users" view. This would be the easiest solution, but it doesn't appear in the "sharing" drop-down.

**Describe alternatives you've considered**
I can create, and manage, an "All Users" group manually, but this is fragile. We have added most users to a set of smaller groups, so I could share with these separately.

Another solution would be a "group calendar" as described by #3044

**Comment by tcitworld** [comment]
Sharing is a core Nextcloud feature, there's not much we can do. You may use the following app to create an « everyone » group: https://apps.nextcloud.com/apps/group_everyone

**Comment by bwduncan** [comment]
That's perfect, thank you!
