### ISSUE TITLE
Jumping to another event from sidebar

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#394]
When editing an event in the sidebar, you have to click twice to edit it.
The first time to close the sidebar and the second time to open the event for editing.

Clicking another event should open it in the sidebar directly

reproducible when "skip simple event editor" option is enabled.

**Comment by jones1008** [comment]
I don't know if this is fixed yet but this already works for me...
But what I noticed is that when you edit one event and then click on another without closing the sidebar, the UI of the calendar in the background adapts as if the sidebar would be closed.

This is also just reproducable in day, week and month sector and  only with the "skip simple event editor" option enabled.

**Comment by georgehrke** [comment]
Closing in favor of #724
