### ISSUE TITLE
Unable to build the calendar module

### ISSUE THREAD

**Issue by miroirdelame** [nextcloud/calendar#3940]
### Steps to reproduce
1. `git clone https://github.com/nextcloud/calendar.git`
2. `make dev-setup`
3. `make`

### Expected behaviour
The calendar module is built without error

### Actual behaviour
`Oops! Something went wrong! :(

ESLint: 8.8.0

ESLint couldn't find the plugin "eslint-plugin-import".

(The package "eslint-plugin-import" was not found when loaded as a Node module from the directory "/tmp/calendar".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-import@latest --save-dev

The plugin "eslint-plugin-import" was referenced from the config file in ".eslintrc.js » @nextcloud/eslint-config".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! calendar@3.0.0 lint: `eslint --ext .js,.vue src`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the calendar@3.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

If i Try to install it manually, another unmet dependency triggers an error. There are dozens of them, until a dependency version deadlock.

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
HEAD

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)

### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)
Debian 11
NPM 6.14.16

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)

**PHP version:** (e.g. 7.0.3)

**Nextcloud Version:** (see admin page, e.g. 17.0.2)

**Updated from an older installed version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by ChristophWurst** [comment]
what version of node/npm do you use?

**Comment by miroirdelame** [comment]
@ChristophWurst : NPM 6.14.16

**Comment by ChristophWurst** [comment]
and node?

**Comment by ChristophWurst** [comment]
you need npm7. there was also a big warning when `npm i` was run telling you about incompatible engines ;-)

https://github.com/nextcloud/calendar/blob/f6775c8c783923a934df48ccbed021b9759a40b6/package.json#L84

**Comment by miroirdelame** [comment]
Node 14.19.0

You mean this warning (there is no other one) ?
`This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!`

I'll upgrade npm and give it another try tomorrow. Thanks a lot for your answer !

**Comment by ChristophWurst** [comment]
exactly. npm is trying its best, but it's ending up with something that isn't usable
