### ISSUE TITLE
Reminders of group events get send to not only attendees of said event but to everyone in the group.

### ISSUE THREAD

**Issue by D0n1elT** [nextcloud/calendar#3946]
First of all, you're all doing a great job. ^^

I wanted to say this is my first contribution and I'm not 100% sure of the terminology. ^^

### Steps to reproduce
1. Create a group with the following members:
  - `peter@example.com`
  - `max@example.com`
2. Create new calendar and share calendar with the new group (with write-access.)
3. Create a new event in the new calendar.
4. Activate a reminder: 5 mins before the event.
5. Under attendees: Invite the following people:
  - `john@example.com`
  - `jane@example.com`

### Expected behaviour
* `john@example.com` & `jane@example.com` should receive an invitation.
* `john@example.com` & `jane@example.com` should receive a reminder e-mail 5 minutes before the event.

### Actual behaviour
* `john@example.com` & `jane@example.com` receive an invitation.
* `john@example.com` & 
* `jane@example.com` &
* `peter@example.com` &
* `max@example.com` receive a reminder e-mail 5 minutes before the event.

### Calendar app
Cloned via git. `3.1.0-alpha.1` f89c089921191fc31ba2d5d30186026b69af6623 https://github.com/nextcloud/calendar.git

### Server configuration
**Apache2 on Debian 11**
**Database:** SQLite
**PHP version:** 7.4.25
**Nextcloud Version:** cloned via git. c605ef1f432dcd48ba4b3b8cc82551c234dc4f64 https://github.com/nextcloud/server.git

**List of activated apps:**

```
Enabled:
  - accessibility: 1.10.0
  - calendar: 3.1.0-alpha.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_sharing: 1.16.0
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - lookup_server_connector: 1.12.0
  - oauth2: 1.12.0
  - provisioning_api: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - systemtags: 1.14.0
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - testing
  - user_ldap
```

**Nextcloud configuration:**

config.php
```
<?php
$CONFIG = array (
  'instanceid' => 'oc2cnl5cuc6p',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => '10.0.2.5',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'sqlite3',
  'version' => '24.0.0.4',
  'overwrite.cli.url' => 'http://10.0.2.5',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'debug' => true,
  'app_install_overwrite' => 
  array (
    0 => 'richdocuments',
    1 => 'richdocumentscode',
    2 => 'announcementcenter',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'daniel',
  'mail_domain' => 'example.com',
  'mail_smtphost' => '***',
  'mail_smtpname' => '***',
  'mail_smtppassword' => '***,
  'force_language' => 'en',
);

```

We thought of a new settings option for this issue. (Second option from the bottom)
![grafik](https://user-images.githubusercontent.com/16420080/153434776-3c7bdcd3-ba37-49a0-b718-aa49ef38765a.png)

**Comment by ChristophWurst** [comment]
> First of all, you're all doing a great job. ^^

:pray: 

---

So I think this might be a mix of things. First, the calendar sharing currently has a few quirks. https://github.com/nextcloud/server/issues/26668 will tackle this. Not sure if it has influence for (shared) calendars and reminders.

Otherwise this could also be related to https://github.com/nextcloud/server/issues/21370. Again, not sure.

**Comment by D0n1elT** [comment]
Hey, thanks for your answer.

I'm new to Nextcloud but I think https://github.com/nextcloud/server/issues/21370 is not related to this problem since
1. They are talking about non-shared calendars.
2. There is already a fix [6497](https://github.com/kominoshja/server/commit/6497f4712ccb88e4437cd08d0aee316b47fe4dd1) but I could reproduce my issue using latest `master` branch.

Also do you think the default behavior should be changed or should it be possible to switch behaviors like shown above?

**Comment by D0n1elT** [comment]
I would say this issue can be closed since it's not actually an issue of `calendar` but `core`.
