### ISSUE TITLE
Import of a previously exported calendar fails

### ISSUE THREAD

**Issue by discoverSlow** [nextcloud/calendar#3947]
### Steps to reproduce
1. Create a new calendar, say "testcal".
2. Create a new event in this calendar, say "testevent".
3. Download the calendar (creates an .ics file).
4. Delete  "testevent" in "testcal", so "tescal" is empty now.
5. Import the downloaded calendar: in "Import" choose the .ics file previously created and choose "testcal" as the calendar to import into).

### Expected behaviour
The .ics file should be imported. 

### Actual behaviour
Result is an error message:  "Import ist teilweise fehlgeschlagen. 0 von 1 importiert".
In the English version this would read as "Import partially failed. Imported 0 of 1".
(I only have the german version).

### Calendar app
3.0.5

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
not relevant
### Client configuration
**Browser:** Firefox 96.0.3 (64 bit)

**Operating system:** Windows 10

### Server configuration

**Operating system**:   Ubuntu 20.04.1 LTS

**Web server:**  nginx/1.19.6

**Database:** mariadb  Ver 15.1 Distrib 10.4.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:59) ( NTS )

**Nextcloud Version:** 22.2.3

**Updated from an older installed version or fresh install:**  updated from an older version 

**List of activated apps:**

Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.5
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.7
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_admin: 3.2.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_notifications
  - encryption
  - files_videoplayer
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED SENSITIVE VALUE",
            "REMOVED SENSITIVE VALUE"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/cloud.baders.online",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logfile": "\/var\/nextcloud_data\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "auth.bruteforce.protection.enabled": "false",
        "maintenance": false,
        "data-fingerprint": "02af941e1f22ceec4dd4c39caff25d48",
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "admin_notifications"
        ],
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        }
    }
}

### Logs

root@john:/var/log# cat /var/log/nginx/error.log | tail -10
2022/02/11 01:58:36 [error] 312476#312476: *64 access forbidden by rule, client: 109.237.103.123, server: cloud.baders.online, request: "GET /.env HTTP/1.1", host: "88.134.59.149"
2022/02/11 09:46:10 [warn] 312476#312476: *1321 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream, client: 88.134.59.149, server: cloud.baders.online, request: "GET /js/activity/activity-sidebar.js?v=923c4802-0 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "cloud.baders.online"
2022/02/11 10:35:27 [error] 312476#312476: *2153 access forbidden by rule, client: 88.134.59.149, server: cloud.baders.online, request: "GET /.well-known/nodeinfo HTTP/2.0", host: "cloud.baders.online"

**Comment by tcitworld** [comment]
Please provide browser logs (F12), as the errors should be logged in it when trying to import.

**Comment by ChristophWurst** [comment]
this might be a tash bin conflict. there is another ticket about this.

**Comment by discoverSlow** [comment]
I added a browser log file. Hope this helps..
[log.txt-main.9120.moz_log.txt](https://github.com/nextcloud/calendar/files/8048178/log.txt-main.9120.moz_log.txt)
.
Interesting observation:  
If in the last step of "Steps to reproduce"  I import the .ics file into the calender "Personal" rather than "testcal",  the import works.
(Though I did not test it, I assume that the import would work with any calendar different from "testcal").

**Comment by BernieO** [comment]
> this might be a tash bin conflict. there is another ticket about this.

Deleting the event permanently from the trashbin before importing the ics-file makes the import work. Also does changing the UID of the event in the downloaded ics-file before reimporting it.

So this indeed looks like a trashbin conflict.

Here are the issues about that for reference:
- nextcloud/calendar: [https://github.com/nextcloud/calendar/issues/3325](https://github.com/nextcloud/calendar/issues/3325)
- nextcloud/server: [https://github.com/nextcloud/server/issues/30096](https://github.com/nextcloud/server/issues/30096)
