### ISSUE TITLE
Ability to select first day of the week

### ISSUE THREAD

**Issue by rodrigoaguilera** [nextcloud/calendar#396]
### Steps to reproduce
1. Install a demo nextcloud on https://demo.nextcloud.com and enable calendar
2. See that Sunday is the first day of the week and I see no setting to change that
3. Changing my personal locale changes the first day of the week

### Expected behaviour
Like the tasks app it should have a choice about what is the first day of the week for the interface to override the option on my current language.

Actually it makes no sense for me why the option is in the tasks app

### Actual behaviour
No option to change the first day of the week

**List of activated apps:**

calendar
tasks

**Comment by georgehrke** [comment]
please use the search before creating new issues, this was reported a couple of times already.
Won't fix, there will be a region setting in the nextcloud server

**Comment by georgehrke** [comment]
see https://github.com/nextcloud/calendar/issues?q=is%3Aissue+first+day+is%3Aclosed for example ;)
