### ISSUE TITLE
Color indicator circle of disabled calendars is almost invisible

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/calendar#3966]

**Comment by JuliaKirschenheuter** [comment]
I guess it will be fixed via #3955 
@ChristophWurst , @nimishavijay , @st3iny , @GretaD what are you think about it?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/pull/3960#issuecomment-1042998982 yes, looks like this won't be an issue anymore.

**Comment by GretaD** [comment]
yes. Julia please upload some screenshots when you work/open on design ticket so its easier for us to understand the ticket ✌️

**Comment by ChristophWurst** [comment]
we can leave this open until https://github.com/nextcloud/calendar/pull/3960 is done. I've added the ticket reference to the pull request description so github will close it for us.
