### ISSUE TITLE
Layout glitch in attendee list

### ISSUE THREAD

**Issue by nicolasfella** [nextcloud/calendar#3979]
### Steps to reproduce

1. Have a specific event with attendees
2. Open the event
3. Open the attendees list

### Expected behavior

All attendees in a list

### Actual behaviour

The first attendee is displaced and overlaps with the search field'
![Screenshot_20220221_233532](https://user-images.githubusercontent.com/6377822/155034429-8c8e62da-22be-480c-8476-b8c132031e12.png)

### Calendar app version

3.0.6

### Browser

Firefox 97.0.1

### Client operating system

Linux

**Comment by nicolasfella** [comment]
ical for the event:

BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20220216T144657Z
LAST-MODIFIED:20220216T145622Z
DTSTAMP:20220216T145622Z
UID:ee66edbb-e328-44ae-9e97-af8ecc1458d5
SUMMARY:Redacted meeting
ORGANIZER;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT:mailto:redacted1@foo.org
 
ATTENDEE;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT:mailto:redacte
 d2@foo.com
ATTENDEE;RSVP=TRUE;CN=Re Dacted;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICI
 PANT:mailto:redacted3@gmx.de
DTSTART;TZID=Europe/Berlin:20220222T123000
DTEND;TZID=Europe/Berlin:20220222T133000
TRANSP:OPAQUE
LOCATION:somewhere
SEQUENCE:1
END:VEVENT
END:VCALENDAR

**Comment by ChristophWurst** [comment]
> PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN

so you created this event with Thunderbird, nor our Calendar app. That is an important detail for reproduction.

**Comment by nicolasfella** [comment]
> > PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
> 
> so you created this event with Thunderbird, nor our Calendar app. That is an important detail for reproduction.

To be precise, someone else created the event, sent me the ics file and I uploaded it in the Nextcloud web interface using "Import calendar"

**Comment by Davr3n** [comment]
I too have this issue.
In my case:

- If I create an event via the UI the attendee list is fine 
- If I create using Samsung Calendar then sync via DAVx5 - I get the below
- If I import an ics into Samsung Calendar then sync via DAVx5 - I get the below

![layout - Copy](https://user-images.githubusercontent.com/7320204/157089483-206f3b98-a6d4-42ea-8406-4070a6ed34ca.jpg)

**Comment by st3iny** [comment]
Related console log message:

```
[Vue warn]: Invalid prop: type check failed for prop "avatarLink". Expected String, got Null 

found in

---> <AvatarParticipationStatus> at src/components/Editor/AvatarParticipationStatus.vue
       <OrganizerListItem> at src/components/Editor/Invitees/OrganizerListItem.vue
         <InviteesList> at src/components/Editor/Invitees/InviteesList.vue
           <AppSidebarTab>
             <AppSidebarTabs>
               <AppSidebar>
                 <EditSidebar> at src/views/EditSidebar.vue
                   <Content>
                     <Calendar> at src/views/Calendar.vue
                       <App> at src/App.vue
                         <Root>
```
