### ISSUE TITLE
legend color is only shown for calendars without items

### ISSUE THREAD

**Issue by faulix** [nextcloud/calendar#398]
### Steps to reproduce
1. Create 2 different calendars
2. Add an appointment to 1 calendar
3. Look at the calendar overview

### Expected behaviour
The calendar color is shown for each calendar

### Actual behaviour
The colors are shown only for the calendars, which have a scheduled appointment in the selected time.
<img width="241" alt="bildschirmfoto 2017-04-02 um 20 23 45" src="https://cloud.githubusercontent.com/assets/19248888/24589909/048b1b30-17e3-11e7-81ea-731e30cb2e30.png">

**Comment by georgehrke** [comment]
> The colors are shown only for the calendars, which have a scheduled appointment in the selected time.

This has absolutely nothing to do with whether or not there are scheduled events in the time-frame.
The calendar Arbeit is just disabled. Click on the name to enable it ;)

**Comment by faulix** [comment]
That's embarrassing, thanks @georgehrke
