### ISSUE TITLE
Color picker for the agendas

### ISSUE THREAD

**Issue by Spheerys** [nextcloud/calendar#4]
Hi ,

Is it possible to replace the limited color chooser by a color picker ?

**Comment by tcitworld** [comment]
Color input is now supported by over 70% of users, including Safari 10 users. Time to get this in ? http://caniuse.com/#feat=input-color

**Comment by georgehrke** [comment]
That means we would have to drop Safari9 support, but I'm fine with that. (ref https://github.com/nextcloud/calendar/issues/67)
Safari 10 is also available on older OS X releases like yosemite, so it's not a big deal.

**Comment by tcitworld** [comment]
iOS is still an issue though.

**Comment by georgehrke** [comment]
AFAIK we can check if the browser supports it with:
```
const input = document.createElement('input');
input.setAttribute('type', 'color');
if (input.type === 'color) => supported
```

So I suggest to only display the color picker when its supported, but don't provide a fallback.

**Comment by Bullnados** [comment]
Is this feature in 1.5.1 like in changelog written or is that for Milestone 1.6.0?
I ask cause i haven't an advanced color picker.

**Comment by georgehrke** [comment]
it only works in modern browsers, which one do you use?

**Comment by Bullnados** [comment]
52.0 64bit FF
But it seems that was an adblock issue. 
Disabling-->Reload-->New Picker
Also with adblock enabled new picker still visible :+1:
