### ISSUE TITLE
Allow user to change color from shared calendar

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#400]
If userA shares calendarA with userB, userB is not able to change the color of calendarA in his calendar. This can create a situation where userB has multiple calendars with the same color and can't do anything about it.

Therefore it would be good to allow the users to change the colors for all calenders they see, no matter if they own it or if it is a shared calendar.

**Comment by georgehrke** [comment]
Server issue, please help testing https://github.com/nextcloud/server/pull/3620 ;)
