### ISSUE TITLE
[Appointments][Calendar] (German) translation incomplete

### ISSUE THREAD

**Issue by nursoda** [nextcloud/calendar#4004]
### Steps to reproduce

1. Set localization to "German (Du)"
2. Use app (admin settings, personal settings, new/edit appointment overlay, sharee view) and watch out for translation glitches

### Expected behavior

All texts should be localized ;)

### Actual behaviour

Some translations are missing:

In my opinion, "Termin" is the generic term to be used in Calender. But that's already used for "Appointment".
![grafik](https://user-images.githubusercontent.com/8425483/156072908-ef4cc714-6b94-4c94-ba69-f23611821817.png)

While the new/edit appointment dialog is 100% german, the personal settings is not:
![grafik](https://user-images.githubusercontent.com/8425483/156072477-d0660392-8bb6-4a8f-9899-23b35ded4da0.png)

### Calendar app version

3.1.0

### CalDAV-clients used

Webinterface only

### Browser

Firefox 97.0.1

### Client operating system

Arch Linux

### Server operating system

Arch Linux

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

23.0.2

**Comment by daCaPo** [comment]
Don't know how to quickly provide a patch, but in the de*.js*-files, the "+ " must be removed from "+ New event" and "+ Neuer Termin", respectively, so the strings can match. (The plus-symbol is not part of the string, but an SVG graphic).

**Comment by ChristophWurst** [comment]
I've backported the latest translations in https://github.com/nextcloud/calendar/pull/4007.

This unfortunately happened because we changed UI strings shortly before branching into a stable branch.

**Comment by ChristophWurst** [comment]
The availability is part of server. Not sure why that lacks translations.
