### ISSUE TITLE
Use CheckboxBlankCircleOutline if calendar is disabled

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/calendar#4005]
### Is your feature request related to a problem? Please describe.

After https://github.com/nextcloud/calendar/pull/3960 when a calendar is disabled, only the color of the icon-bullet is changed to `var(--color-text-lighter)`. This makes it not obvious that the calendar is disabled, because it's just a different color. If you happen to have calendars with a similar color, or have a color-impaired vision, you are a bit lost.
See here for example:
![Screenshot 2022-03-01 at 09-52-36 Woche 9 aus 2022 - Kalender - Nextcloud](https://user-images.githubusercontent.com/2496460/156136681-0aafb34d-d00b-41aa-a464-191697d4fd72.png)

### Describe the solution you'd like

Use a different icon for disabled calendars: `CheckboxBlankCircleOutline` here
https://github.com/nextcloud/calendar/blob/b9576fcab2e0d1f20c974128f673057a1a9dc976/src/components/AppNavigation/CalendarList/CalendarListItem.vue#L33-L36

This would solve the problem:
![Screenshot 2022-03-01 at 09-54-22 Woche 9 aus 2022 - Kalender - Nextcloud](https://user-images.githubusercontent.com/2496460/156136950-7424b80a-b4d8-4cd4-a100-6a01505a9a1b.png)

@JuliaKirschenheuter @nimishavijay For the design here.

**Comment by nimishavijay** [comment]
Good point! Your solution would work great 🚀
