### ISSUE TITLE
no visual feedback if the user unshares a calendar

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#401]
Tested with Calendar 1.5.2 and Nextcloud 11.

Steps to reproduce:

1. setup two users, userA and userB
2. userA shares a calendar to userB
2. userA unshares the same calendar again from userB

Expected behavior:

The share entry for user B should immediately disappear. If it takes same time the unshare-button should turn into a spinner until the operation was completed.

Actual behavior:

No visual feedback, also the share entry doesn't disappear. For the user it looks like clicking the unshare button has no affect at all. Only after userA reloads the page the share disappears.

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/378
