### ISSUE TITLE
Loading endless calendar event info panel if shared via a link and if a atendee is specified

### ISSUE THREAD

**Issue by raimondsstraume** [nextcloud/calendar#4011]
### Steps to reproduce

1. Create calendar event, provide atendee
2. Share calendar via link
3. Open shared calendar via link, select event

Event withoud atendee info panel loads
![without](https://user-images.githubusercontent.com/100778895/156373230-03ffcf8d-e4ff-4615-bd3e-dc0dc90893e9.png)

Event with atendee loading endless
![with](https://user-images.githubusercontent.com/100778895/156373385-91035565-30df-4b36-93d5-365dfb1cc57b.png)

### Expected behavior

Shared calendar via link event with atendee show detailed event information in side panel

### Actual behaviour

Shared calendar via link event with atendee side panel loading endless

### Calendar app version

3.1.0

### Browser

Google Chrome 99.0.4844.51

### Client operating system

Windows 11

### Server operating system

Ubuntu server 20.04

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 7.4

### Nextcloud version

23.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - calendar: 3.1.0
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.8
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - drawio: 1.0.2
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - geoblocker: 0.5.4
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.3
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_external: 2.1.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - bruteforcesettings: 2.3.0
  - dashboard: 7.3.0
  - encryption
  - files_external
  - firstrunwizard: 2.12.0
  - richdocuments: 5.0.2
  - user_ldap
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.2.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "lv",
        "force_language": "lv",
        "default_locale": "lv_LV",
        "force_locale": "lv_LV",
        "default_phone_region": "LV",
        "simpleSignUpLink.shown": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "app_install_overwrite": [
            "user_external",
            "drawio"
        ],
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "***REMOVED SENSITIVE VALUE***",
                    993,
                    "ssl",
                    "***REMOVED SENSITIVE VALUE***",
                    true,
                    false
                ]
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}
```

### Browser log

```Text
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'emailAddress')
    at getCurrentUserPrincipalEmail (principals.js:103:92)
    at r.forEachGetter.t._wrappedGetters.<computed> (vuex.esm.js:881:12)
    at Bn.<anonymous> (vuex.esm.js:140:12)
    at bn.get (vue.runtime.esm.js:4495:25)
    at bn.evaluate (vue.runtime.esm.js:4597:21)
    at Bn.getCurrentUserPrincipalEmail (vue.runtime.esm.js:4851:17)
    at Object.get [as getCurrentUserPrincipalEmail] (vuex.esm.js:671:39)
    at o.userAsAttendee (EditorMixin.js:234:61)
    at bn.get (vue.runtime.esm.js:4495:25)
    at bn.evaluate (vue.runtime.esm.js:4597:21)
```

**Comment by karlisi** [comment]
The same from Mozilla Firefox 97.0.1 and Microsoft Edge Version 98.0.1108.62, Windows 10 21H2

**Comment by jk-ozlabs** [comment]
I was seeing the same thing here; with a backtrace through `userAsAttendee`, accessing `this.$store.getters.getCurrentUserPrincipalEmail`, which returned `undefined`.

I see you're authenticating against IMAP; I'm using LDAP here, but it looks like the underlying issue was that my user profile didn't have an email address set. This is visible through the standard User settings, and because I'm using a LDAP backend, the Email setting is not configurable.

 In my case, it was a matter of configuring the LDAP backend with the correct `ldapEmailAttribute`, so the profile gets a valid email. Is there something similar with the IMAP user backend config?

**Comment by karlisi** [comment]
Because of authentication against IMAP server we all have our primary e-mail address set.

**Comment by frie** [comment]
I observe the same problem in two different installations: one using internal authentication, the other by keycloak / oidc_login. In both cases email addresses are assigned to the user creating the appointment. BTW: when adding any attendee it seems that the user creating the appointment is also added as "organizer". Even when removing other attendees the "organizer" will be leftover and cause the trouble described here. Nextcloud also allows adding bare email addresses as attendees.

	TypeError: t.principalsById[t.currentUserPrincipal] is undefined
	    getCurrentUserPrincipalEmail principals.js:103
	    e vuex.esm.js:881
	    n vuex.esm.js:140
	    VueJS 3
	    get vuex.esm.js:671
	    userAsAttendee EditorMixin.js:229
	    VueJS 3
	    isViewedByAttendee EditorMixin.js:65
	    VueJS 3
	    fn EditSidebar.vue:1
	    r VueJS
	    _ AppSidebar.js:88
	    VueJS 14
	    e EditorMixin.js:657
	    u dist.js:1
	    _invoke dist.js:1
	    S dist.js:1
	    bx attendee.js:59
	    o attendee.js:59
	    promise callback*bx attendee.js:59
	    o attendee.js:59
	    promise callback*bx attendee.js:59
	    o attendee.js:59
	    yx attendee.js:59
	    yx attendee.js:59
	    e EditorMixin.js:657
	    S vue-router.esm.js:290
	    init vue-router.esm.js:392
	    VueJS 19
	    init vue-router.esm.js:3002
	    init vue-router.esm.js:3002
	    updateRoute vue-router.esm.js:2414
	    transitionTo vue-router.esm.js:2263
	    confirmTransition vue-router.esm.js:2401
	    r vue-router.esm.js:2000
	    r vue-router.esm.js:2004
	    h vue-router.esm.js:2380
	    confirmTransition vue-router.esm.js:2540
	    e EditorMixin.js:636
	    u dist.js:1
	    _invoke dist.js:1
	    S dist.js:1
	    bx attendee.js:59
	    o attendee.js:59
	    yx attendee.js:59
	    yx attendee.js:59
	    beforeRouteEnter EditorMixin.js:634
	    confirmTransition vue-router.esm.js:2535
	    h vue-router.esm.js:2361
	    r vue-router.esm.js:2003
	    St vue-router.esm.js:2008
	    confirmTransition vue-router.esm.js:2397
	vue.runtime.esm.js:1897:4

**Comment by MaZayITVert** [comment]
Hello! Could you please let me know when this bug will be fixed? My situation is repeated with a link to the sharing calendar.
