### ISSUE TITLE
dashboard upcoming events removed too early

### ISSUE THREAD

**Issue by portno12** [nextcloud/calendar#4013]
### Steps to reproduce

1. set timezone on nextcloud profile
2. add upcoming events widget to the dashboard
3. add a calendar event
4. observe time on dashboard of upcoming event
5. observe the event get removed before the event starts

### Expected behavior

the event remains listed under "today" until at least its start time, but no later than end time. after either of those then it disappears, not before

### Actual behaviour

events are removed from "today" some time before they actually start

### Calendar app version

3.1.0

### Browser

firefox 97.0.1

### Client operating system

windows and fedora

### Server operating system

fedora 35 server

### Web server

Apache

### Database engine version

PostgreSQL

### PHP engine version

Other

### Nextcloud version

23.0.2

### Updated from an older installed version or fresh install

Fresh install

### Additional info

installed nextcloud from helm using default php and apache web server

**Comment by tcitworld** [comment]
> set timezone on nextcloud profile

On the profile? The locale is not the same as the timezone. The locale can be set in the personal info settings section, but the timezone can be only set in the calendar app itself (defaults to automatic detection).

It's possible something isn't working correctly on the dashboard widget itself.

**Comment by portno12** [comment]
what should i look at to determine if its the dashboard widget or not?
