### ISSUE TITLE
Add support for PHP v8.1

### ISSUE THREAD

**Issue by Atomisirsi** [nextcloud/calendar#4018]
### Is your feature request related to a problem? Please describe.

For Arch users the default PHP version is now v8.1, but this package limits support to PHP v8.0 as maximum version.

### Describe the solution you'd like

Please add support for PHP v8.1 or change the limit in the appinfo.

### Additional context

I have locally changed the PHP version limit and everything seems to work as expected - at least after a brief look.

**Comment by Atomisirsi** [comment]
I should have had a look into the pull requests first: PR #3996 already handles this topic!

**Comment by ChristophWurst** [comment]
This can be closed in favor of https://github.com/nextcloud/groupware/issues/27
