### ISSUE TITLE
Navigation toggle overlaps with the week numbers

### ISSUE THREAD

**Issue by T-bond** [nextcloud/calendar#4021]
### Steps to reproduce

1. Enable the ,,Show week numbers" setting
2. Check that the navigation toggle overlaps the week numbers.

### Expected behavior

The navigation toggle not overlapping the content, in any configuration.

### Actual behaviour

Navigation toggle overlapping the content.
![image](https://user-images.githubusercontent.com/3778556/156946568-f5eaab1a-3143-425a-88f8-fabd29286f86.png)

### Calendar app version

3.0.6

### CalDAV-clients used

Nextcloud Web

### Browser

Firefox Developer Edition 98.0b8

### Client operating system

Arch linux

### Server operating system

Debian

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.0

### Nextcloud version

Nextcloud Hub II (23.0.2)

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by ChristophWurst** [comment]
I suppose this is a duplicate of https://github.com/nextcloud/groupware/issues/2

**Comment by T-bond** [comment]
Ups. Yeah, I think so.
