### ISSUE TITLE
Appointments availability does not respect "All day" events

### ISSUE THREAD

**Issue by reos-rcrozier** [nextcloud/calendar#4023]
### Steps to reproduce

1. Create an "All day" event in a calendar you are using for Appointments
2. Create an Appointments availability set that overlaps with the All day event
3. View the Appointments URL link and see that appointment slots can still be selected for that day

### Expected behavior

The Appointments should respect All day type events as it does normal calendar events. At the very least this should be a possibility when setting up the appointments set. 

### Actual behaviour

 The Appointments URL link and presents appointment slots can still be selected for the day where an A;; Day event is in the calendar. 

### Calendar app version

3.1.0

### CalDAV-clients used

Thunderbird Lightning

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by maximelehericy** [comment]
I am NOT having the same issue.
Dates where I planned a whole day event, no appointment can be booked.
NB: on whole day events, in many calendar apps, the default availability is usually set a free instead of busy.
@reos-rcrozier are you sure your whole day events availabilty is busy ?

**Comment by ChristophWurst** [comment]
> @reos-rcrozier are you sure your whole day events availabilty is busy ?

That was very likely the issue. Same issue reported in https://github.com/nextcloud/calendar/issues/4699.
