### ISSUE TITLE
"New calendar" has 2 tab stops, 1 link and 1 button – should just be 1 button

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/calendar#4029]

**Comment by jancborchardt** [comment]
@JuliaKirschenheuter referencing this mockup I mentioned in the call: https://github.com/nextcloud/calendar/issues/3965#issuecomment-1048681112 :)

**Comment by ChristophWurst** [comment]
Resetting the status as there is no work done currently.

**Comment by JuliaKirschenheuter** [comment]
"New calendar" was redesigned and current issue was closed via https://github.com/nextcloud/nextcloud-vue/pull/2555#issuecomment-1084295809.
