### ISSUE TITLE
Public calendars: Allow to specify, which view is displayed by default

### ISSUE THREAD

**Issue by RiSK1979** [nextcloud/calendar#403]
Please implement the option, to specify,  in which way a public shared calendar is displayed by default, when opening it via link. This way you could pre-decide if such a calendar should show the current day, week, or month.

This could by done by a "?view=day" like that: 
https://cloud.nextcloud.com/apps/calendar/public/MIFAFLFJADIVX63I?view=day 

A calendar link like that would open the respective calendar with day view by default.

Thanks for considering!

**Comment by georgehrke** [comment]
What's the use case here?

**Comment by RiSK1979** [comment]
Consider you wanna share the agenda for an one day or week event, where you have multiple events in parallel. This way you could implement the day or week view into your event website.  The month view would be useless here.

I'm currently experiencing this with a volleyball tournament that we are planning. It's a single day event, with 3 matches taking place at the same time (on different fields). By default a shared nextcloud calendar opens in month view, which isn't suitable here. Our users would have to switch the calendar view always everytime they are revisiting our even website manually to day view, to see the whole plan.

And consider it the other way around, if you have a calendar with lots of events scattered upon weeks /months, the day view won't be used by default.

Get what I'm up to?

**Comment by georgehrke** [comment]
You are actually running into two issues here:
- it opens in month view instead of day view
- furthermore it opens today instead of the day of the tournament

**Comment by georgehrke** [comment]
I would be fine with adding support for the parameter "view=agendaDay / agendaWeek / month", but I would do it without adding a UI element for it.

**Comment by georgehrke** [comment]
The "always opens today" issue could be fixed with https://github.com/nextcloud/calendar/issues/21

**Comment by tcitworld** [comment]
> I would be fine with adding support for the parameter "view=agendaDay / agendaWeek / month", but I would do it without adding a UI element for it.

It depends, since we want to change the position of the embeed code, if we have some kind of modal, we can add this kind of element. Or at least document this parameter.

**Comment by georgehrke** [comment]
added link to a view in https://github.com/nextcloud/calendar/issues/21#issuecomment-269091361
