### ISSUE TITLE
Disable appointments feature

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/calendar#4030]
### Is your feature request related to a problem? Please describe.

We are using Calendar App to schedule internal and external meetings but not to make public or private appointments. The link to create Appointment slots is always visible, and is confusing for our users. 

### Describe the solution you'd like

We would to be able to enable/disable appointment functionality based on group.

**Comment by ChristophWurst** [comment]
Added via https://github.com/nextcloud/calendar/pull/4288
