### ISSUE TITLE
Give the detected MIME-type in the error message if it's not accepted by the import process

### ISSUE THREAD

**Issue by CDSoft** [nextcloud/calendar#4053]
### Steps to reproduce

1. Let Thunderbird handle ICS files (e.g. add `application/x-extension-ics=userapp-Thunderbird-TN70F1.desktop` to `~/.config/mimeapps.list`)
2. Start a web browser (tested with both Firefox and Chrome)
3. Connect to a Nextcloud server
4. Import a valid ICS file

### Expected behavior

The ICS file should be imported.

### Actual behaviour

The browser shows an error message about unsupported file type and the ICS file can not be imported.

### Calendar app version

3.2.0

### Browser

Firefox 98 and Google Chrome 99.0.4844.51 (64 bits)

### Client operating system

Xubuntu 21.10

### Server operating system

Raspios Bullseye arm64 lite

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 7.4

### Nextcloud version

23.0.2

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.2.0
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.8
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.2.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "FR",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MP4",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ]
    }
}
```

### Additional info

Removing `application/x-extension-ics=userapp-Thunderbird-TN70F1.desktop` from `~/.config/mimeapps.list` fixes the problem.

The error message (`'{filename} is an unsupported file-type'`) could be more informative (e.g. asking to check the ICS association in `mimeapps.list` on Linux).

**Comment by tcitworld** [comment]
I'm not sure I see how changing the application association changes the MIME type reported by the browser. In anycase there's not much we can do if the browser gives us the wrong information.

We could give the detected MIME type in the error message though.

**Comment by dami0n** [comment]
just a note.  i just spent a few hours trying to import .ics files into a new install of nextcloud 24.0.2 from my linux mint system.  i tried chrome, firefox, brave browser all to no avail.  i repeatedly got "is an unsupported file-type".  i looked at some of the validation source code and it looks like the import was failing very early on some basic file detection.  i thought maybe it had to do with operating system case translation or locale settings.  i took the SAME files, logged into the SAME nextcloud install on a macbook using the SAME version of chrome and it worked as expected.  some OS bug here.  ill try to figure more closely.
