### ISSUE TITLE
Radio inputs to set reminder's notification type to email are missing after last updates

### ISSUE THREAD

**Issue by aledef** [nextcloud/calendar#4054]
### Steps to reproduce

1. Create/modify an event
2. Set a reminder

### Expected behavior

Radio inputs allowing to set reminder's notification type to email should be in reminder's dropdown menu

### Actual behaviour

Radio inputs allowing to set reminder's notification type to email are missing after last calendar app updates

### Calendar app version

3.2.0

### CalDAV-clients used

DAVx5

### Browser

Firefox 98.0, Chrome 99.0.4844.51

### Client operating system

Windows

### Server operating system

Linux

### Web server

Nginx

### Database engine version

MySQL

### PHP engine version

PHP 7.4

### Nextcloud version

23.0.2

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by raimund-schluessler** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/4032.
