### ISSUE TITLE
Remove periods from attendee/resource/room status

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#4072]
### Is your feature request related to a problem? Please describe.

![Bildschirmfoto von 2022-03-15 16-24-03](https://user-images.githubusercontent.com/1374172/158412003-f45e01aa-60c2-4e29-b36b-bd1152d87fe3.png)

^ this is what the status looks like today.

### Describe the solution you'd like

![Bildschirmfoto von 2022-03-15 16-25-06](https://user-images.githubusercontent.com/1374172/158412147-41b892d7-20e8-43ba-ac2b-2b9cf5ddc0c8.png)

no periods at the statuses because they feel out of place for our user interface design

### Describe alternatives you've considered

N/a

### Additional context

@nimishavijay @jancborchardt :+1: or :-1:?

**Comment by nimishavijay** [comment]
Looks great!
