### ISSUE TITLE
Visually distinguish event invitations by their status

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#4075]
### Is your feature request related to a problem? Please describe.

Currently, a user can't distinguish between events that are accepted, tentative or declined. This information can not be seen at a glance and needs user interaction to become visible through clicking on the event.

### Describe the solution you'd like

Make the event status discernible by changing the look of the text:

Tentative events / unaccepted events could be in italics:

![image](https://user-images.githubusercontent.com/7427347/158549483-6fd66b45-3238-477e-b74e-03bd11d6b8db.png)

Declined Events should be stricken through

![image](https://user-images.githubusercontent.com/7427347/158549126-b1f14542-5781-414f-b171-cf778996bde2.png)

### Describe alternatives you've considered

None

### Additional context
cc @nextcloud/designers

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/3869?
