### ISSUE TITLE
Disable Availability

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/calendar#4077]
Hello,

I wish we could disable the Availability tab that was introduced in the user settings when nextcloud 23 was updated.

I don't use the calendar and Talk in my professional and personal instances, so the tab is not useful to me and I would like to be able to deactivate it.

**Comment by tcitworld** [comment]
You mean in the groupware settings section? I'm not sure how this is an inconvenience, we don't do that for all other features, there's probably many other things in the settings you never use.

This section is added by the server itself, not the calendar app, so disabling/removing this app won't hide it.

If you absolutely need this as soon as possible, the following CSS hides the section link in the sidebar, that you can use with a theme or [`theming_customcss`](https://apps.nextcloud.com/apps/theming_customcss):
```css
.app-settings #app-navigation li a[href="/settings/user/groupware"] {
  display: none;
}
```

**Comment by JordanDIG** [comment]
> You mean in the groupware settings section? I'm not sure how this is an inconvenience, we don't do that for all other features, there's probably many other things in the settings you never use.
> 
> This section is added by the server itself, not the calendar app, so disabling/removing this app won't hide it.
> 
> If you absolutely need this as soon as possible, the following CSS hides the section link in the sidebar, that you can use with a theme or [`theming_customcss`](https://apps.nextcloud.com/apps/theming_customcss):
> 
> ```css
> .app-settings #app-navigation li a[href="/settings/user/groupware"] {
>   display: none;
> }
> ```

Thank you very much I was able to hide the shortcut in the settings

**Comment by tcitworld** [comment]
Great! Just note that there may be other groupware-related settings in this section in the future.

**Comment by JordanDIG** [comment]
Yes I will check 😉

**Comment by jcweald** [comment]
Adjusting the custom CSS as follows worked for me

```
.app-settings #app-navigation li[data-section-id="availability"] {
  display: none;
}
```
