### ISSUE TITLE
Set default event visibility for events of a shared calendar to CONFIDENTIAL instead of PUBLIC

### ISSUE THREAD

**Issue by dev-cb** [nextcloud/calendar#4086]
### Is your feature request related to a problem? Please describe.

We are using mostly macOS Calendar app as a client. Since the delegation feature is not working properly I was lloking for another solution. The "sharing with another user" function is useless since it is basically the same than a public share link.

Think of this:
User-1 shares his work calendar with User-2.
User-2 should only see the events but not the names or attendees or other details (=classification confidential).
The default settings for events within a shared calendar is: `'PUBLIC': 'When shared show full event'`
User-1 would have to set every single event via NC UI to `'CONFIDENTIAL': 'When shared show only busy'` → That is not applicable.

Also in terms of privacy it would be great to set the default to CONFIDENTIAL and only allow certain events to be PUBLIC.
OR if necessary, share the entire calendar via a link.

Best case scenario:
Configuration of the default setting for a shared calendar!

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/server/issues/11214

**Comment by tcitworld** [comment]
See #827, #944 and #531 too.
