### ISSUE TITLE
Calendar first day by locale affect to some nextcloud Lang data

### ISSUE THREAD

**Issue by masterwishx** [nextcloud/calendar#4087]
### Steps to reproduce

1.Langue Russian (Monday) 
2. Change region to Hebrew or Hebrew (Israel) 
3.then same data in Hebrew 

### Expected behavior

I needs all language data in My first language but first day is Sunday 

### Actual behaviour

Some data in Hebrew instead of my first language 

### Calendar app version

Lasted

### CalDAV-clients used

Davx5

### Browser

Chrome

### Client operating system

Win 10 

### Server operating system

Unraid (Linux x64) Linuxserver Docker amd64

### Web server

Other

### Database engine version

MariaDB

### PHP engine version

PHP 7.4

### Nextcloud version

Last

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
..
```

### Nextcloud configuration

```Text
..
```

### Web server error log

```Text
..
```

### Log file

```Text
..
```

### Browser log

```Text
..
```

### Additional info

I leave in Israel for very long time but Hebrew is not my first language.
If I choose Hebrew for local I'm getting first day Sunday but also some text in Hebrew in nextcloud.

Like files changed data in files

But I need all nextcloud in my first language where first day is Monday. 
But in Israel I need first day Sunday.
Please fix it
Or maybe we can get option to change first day of week like in other calendars?

**Comment by masterwishx** [comment]
Also i have ('default_phone_region' => 'IL',) in config.php

You can see hebrew date in right

![image](https://user-images.githubusercontent.com/28630321/159077234-e605cd06-9927-4604-885f-5a487fc39a5e.png)

**Comment by st3iny** [comment]
The first day of the week is currently tied to your locale setting.

**Comment by st3iny** [comment]
There already is a feature request to manually set and override the first day of the week to solve issues like yours.

I'm closing this in favor of https://github.com/nextcloud/calendar/issues/384.
