### ISSUE TITLE
Re-importing deleted event fails as long as the event is still in the NC trash bin

### ISSUE THREAD

**Issue by helge17** [nextcloud/calendar#4091]
### Steps to reproduce

When re-importing a deleted event (with the same UID) in a DAV client as ICS the import fails.

I use KDE KOrganizer (KO), but I suppose this happens with all other DAV clients as well.

1. KO: 1st import event.ics - OK   - Created in KO & NC
2. KO: 1st delete event     - OK   - Deleted in KO & NC and moved to trash bin in NC
3. KO: 2nd import event.ics - fail - Created in KO, but not in NC (NC gives a http 400 error on PUT request from KO)
4. KO: 2nd delete event     - OK   - Deleted in KO
5. NC: Empty trash bin      - OK
6. KO: 3th import event.ics - OK   - Cerated in KO & NC

### Expected behavior

I would expect that the re-import works. NC should ignore (or purge?) events in the trash bin when importing events with the same UID.

### Actual behaviour

Re-import fails. Event is created in the DAV client, but not in NC.

### Calendar app version

3.2.2

### CalDAV-clients used

KOrganizer

### Browser

Firefox 91.7.0esr

### Client operating system

Debian

### Server operating system

Debian

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 7.4

### Nextcloud version

23.0.2

**Comment by barrydegraaff** [comment]
I can confirm this issue.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/30096
