### ISSUE TITLE
Calendar Event Modal doesn't update Calendar visually when moving event from one calendar to another one

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#4093]
### Steps to reproduce

1. Have two calendars that are not the "Personal" Calendar.
2. Move an event from one calendar to the other
3. The event changes it's calendar colour
4. check the modal again

### Expected behavior

The event modal calendar is the one I selected previously

### Actual behaviour

The event modal calendar is still the old calendar.

### Calendar app version

3.2.2

### CalDAV-clients used

Web

### Browser

Chrome

### Client operating system

Ubuntu

### Server operating system

Ubuntu

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.0

### Nextcloud version

NC24 - dev

### Updated from an older installed version or fresh install

Updated from an older version

### Additional info

![image](https://user-images.githubusercontent.com/7427347/159259505-eca70b5d-0f4a-4028-8257-4ce7e15dadce.png)

Destination was: /remote.php/dav/calendars/admin/work/127C6807-2E7C-444E-86EC-75224913EEC9.ics

**Comment by ZID-TU-Graz** [comment]
We can confirm this issue.
PHP 8.0, Nextcloud 24.0.4, Calendar-App 3.5.0

**Comment by ChristophWurst** [comment]
Alternative reproduction steps in https://github.com/nextcloud/calendar/issues/4655
