### ISSUE TITLE
Recurrences have a save button that doesn't have a clear function

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#4094]
### Steps to reproduce

1. Open an event and add a recurrence:

![save](https://user-images.githubusercontent.com/7427347/159266136-42304fcc-fdc7-4117-a0cf-7917b73ca0d7.jpeg)

### Expected behavior

A visible save button that works and lets me add a second reminder

### Actual behaviour

The button removes the reminder even though the hint says "save".

### Calendar app version

3.2.2

### CalDAV-clients used

Web

**Comment by ChristophWurst** [comment]
Before I add a reminder
![Bildschirmfoto von 2022-03-21 18-25-47](https://user-images.githubusercontent.com/1374172/159329793-d4d36660-09a7-4c07-b76c-f28e65c483dc.png)

After I've added a reminder
![Bildschirmfoto von 2022-03-21 18-25-53](https://user-images.githubusercontent.com/1374172/159329819-63769dc7-2385-4034-a44c-26ab73401971.png)

The *Update* button is at the bottom. But I don't see a button *Save*. The action you hover is the recurrence *Edit* action, right?

**Comment by miaulalala** [comment]
Sorry, of course it's the recurrence. Looks like the button outline still shows even though the edit button disappears.

The tooltip also shows the text "Save" as shown in the screenshot above.

**Comment by GretaD** [comment]
I can reproduce the error but it doesnt look exactly like Anna's screenshot
![2buttonssave](https://user-images.githubusercontent.com/12728974/171396253-9288dd0a-3c32-4aff-9a20-55a807747123.png)


I have a working "save" button on top right but when i click end repeat on a certain date, a second button pops ups that doesnt do anything and that i cannot find it on the code  😐 
will have a double look soon

**Comment by ChristophWurst** [comment]
## v3.3.1 (production)

![Bildschirmfoto vom 2022-06-01 16-39-40](https://user-images.githubusercontent.com/1374172/171431330-fa7fe086-48ca-46c3-99a3-b6694f79998e.png)

## v3.4.0 (dev)

![Bildschirmfoto vom 2022-06-01 16-39-12](https://user-images.githubusercontent.com/1374172/171431365-aa4db090-db7f-467d-b603-d3b11d506905.png)

So I can neither reproduce the original bug nor your floating button.

**Comment by GretaD** [comment]
so its not a saving button, its the calendar icon. The saving button is the first one only, thats why i dont find it on the code

**Comment by ChristophWurst** [comment]
@miaulalala has to re-check the problem. https://github.com/nextcloud/calendar/blame/main/src/components/Editor/Repeat/Repeat.vue has been a material icon for a while and the checkmark shows for both of us.

**Comment by miaulalala** [comment]
Right, I don't know why but I do not have the calendar icon in Chrome:

![image](https://user-images.githubusercontent.com/7427347/173062137-31a60899-0765-487e-83c7-039c5bd53e6a.png)

I force cleared the npm cache and did `npm ci && npm run build` with the browser cache disabled in Chrome.

also, what's the purpose of the icon anyway? Does it have an action attached for you @ChristophWurst @GretaD ? For me it doesn't trigger anything.

**Comment by GretaD** [comment]
> also, what's the purpose of the icon anyway? Does it have an action attached for you @ChristophWurst @GretaD ? For me it doesn't trigger anything.

The icon itself should be migrated to material design thats why it doesnt show,  im already working on it
But can you reproduce your initial scenario?

**Comment by GretaD** [comment]
WHile on this pr: https://github.com/nextcloud/calendar/pull/4268
it looks like this:

![saverecur](https://user-images.githubusercontent.com/12728974/173094704-07b0d41c-3317-4981-b733-19e67370d146.png)

**Comment by miaulalala** [comment]
Right, the original save button is now fully functional. As the calendar icon not showing is a know issue that is being fixed, I will close this ticket now.
