### ISSUE TITLE
Timezone inconsistent between dashboard, modal and fullCalendar

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#4096]
### Steps to reproduce

1. Create an event at 10am some day in the future
2. Have browser / laptop and Nextcloud timezone set to the same values
3. Change browser / laptop timezone ( I changed mine to Boisie, America in the Ubuntu settings dialogue, seems to do the trick)
4. The dashboard still shows 10am 
![image](https://user-images.githubusercontent.com/7427347/159310982-1e6bbaa3-7db2-49c6-a109-662229e6f745.png)

6. The fullCalendar subtracted 7 hours and now shows 3am
![image](https://user-images.githubusercontent.com/7427347/159311018-685119c9-c1e0-4b3e-85cf-6213664da19d.png)

7. The modal also still shows 10am
![image](https://user-images.githubusercontent.com/7427347/159311077-033d4af2-4c5d-46f2-bb1b-3f05f1663787.png)

8. The side view also still shows 10am 
![image](https://user-images.githubusercontent.com/7427347/159311165-90423d2d-04fa-4e50-a948-b2527b9fb11d.png)

### Expected behavior

All times are either re- calculated to the new timezone, or kept at the old timezone.

### Actual behaviour

The displayed times are all different.

### Calendar app version

3.2.2

### CalDAV-clients used

Web

### Browser

Chrome

### Client operating system

Ubuntu

### Server operating system

Ubuntu

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.0

### Nextcloud version

NC24 - dev

### Updated from an older installed version or fresh install

Updated from an older version

### Additional info

Let the user set their timezone themselves?

**Comment by tcitworld** [comment]
Possibly related to #4013

**Comment by st3iny** [comment]
The same applies to the trash bin. The times displayed there do not respect the configured time zone and are always displayed in local time.

**Comment by st3iny** [comment]
> 6. The modal also still shows 10am
>
> 7. The side view also still shows 10am

Those two points are probably not bugs. The displayed time in the pickers depends on the selected time zone (globe symbol on the right).

**Comment by fschrempf** [comment]
Could it be that a similar issue is still persistent when I search for calendar items in the global search bar. I see several items that have a wrong starting time, whereas the time is correct in calendar view and elsewhere.

@st3iny Would you mind taking a quick look at the code to check if the fix also needs to be applied for the search results? Thanks!
