### ISSUE TITLE
Accept/decline/tentative actions shown for (read-only) shared calendar

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#4097]
### Steps to reproduce

1. As user A create a calendar as user A
2. As user A Share the calendar read-only with user B
3. As user B click on the event

### Expected behavior

There is nothing to click or change for user B.

### Actual behaviour

User B can click *Accept*/*Decline*/*Tentative* on the read-only event.

![Bildschirmfoto von 2022-03-22 13-51-52](https://user-images.githubusercontent.com/1374172/159494259-84babc5d-f97b-4d40-ab90-2049865b95f1.png)

In contrast I can update participation on the copy in my personal calendar.

If the calendar is shared with write permissions, the update works, but I wonder if we shouldn't hide the buttons as well. This might be debatable.

### Calendar app version

3.2.2

### Additional info

This is an edge case of the new feature https://github.com/nextcloud/calendar/issues/144. cc @st3iny

**Comment by st3iny** [comment]
> If the calendar is shared with write permissions, the update works, but I wonder if we shouldn't hide the buttons as well.

I tested this edge case and it works fine. The response is propagated correctly to both events if either of the two is updated.
