### ISSUE TITLE
Update of calendar fails: gets extracted into subfolder

### ISSUE THREAD

**Issue by caco3** [nextcloud/calendar#410]
Note:
This might also be a core issue, how ever I only had the issue with the calendar but not with the other apps!

The update of the calendar fails because it gets extracted into a subfolder.

### Steps to reproduce
1. Have calendar 1.5.1
2. Update to 1.5.2 within the Apps menu

 ## Expected behaviour
Successful update

### Actual behaviour
Calendar gets extracted into  apps/calendar/calendar instead of apps/calendar/.
As a solution I had to move it manually from the subfolder into the upper folder.

### Server configuration
**Web server:**
Appache

**Database:**
MYSQL

**PHP version:**
7.x

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Where did you install Nextcloud from:**
Web

**Signing status:**

No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - activitylog: 0.0.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - deck: 0.1.2
  - direct_menu: 0.10.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_downloadactivity: 1.0.1
  - files_external: 1.1.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - qownnotesapi: 17.3.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - calendar.2
  - encryption
  - files_automatedtagging
  - user_external
  - user_ldap
  - user_saml

**Nextcloud configuration:**
{
    "system": {
        "datadirectory": "\/home\/***\/owncloud_***",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "installedat": "1334086349.5631",
        "lastupdatedat": "1334087083.9888",
        "dbname": "***_owncloud",
        "dbhost": "***.mysql.db.internal",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "5083050d6af67",
        "maxZipInputSize": 419430400,
        "allowZipDownload": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 3,
        "trusted_domains": [
            "owncloud.***.ch",
            "www.***.ch",
            "***.ch"
        ],
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "***.ch",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, auto",
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable"
    }
}

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
Recent FF/Chrome

**Operating system:**
Linux, what else!

### Logs
-
#### Nextcloud log (data/nextcloud.log)
-

#### Browser log
-

**Comment by georgehrke** [comment]
i just double checked version 1.5.2. It's packaged correctly.

Please report this in core
