### ISSUE TITLE
Vertical size of event blocks are not representative of actual duration

### ISSUE THREAD

**Issue by andreas-traexler** [nextcloud/calendar#4112]
### Steps to reproduce

1. Add a new event with an uneven time duration
![image](https://user-images.githubusercontent.com/33902715/160622151-8bfce796-6a90-4679-9605-a80718d12c50.png)

As can be seen, the event is only 3 minutes long, but it takes up half an hour in the view

### Expected behavior

Duration should be visualized correctly relative to other events according to their time

### Actual behaviour

Events always take up the next block

### Calendar app version

3.2.2

### Browser

Microsoft Edge

### Client operating system

Windows 10

### Server operating system

Ubuntu 20.04

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 7.3

### Nextcloud version

23.0.3

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
Calendar
```

**Comment by tcitworld** [comment]
The event has a minimum height for the information to be readable, it makes no sense to show something otherwise.
