### ISSUE TITLE
Template or Clone Feature for Events

### ISSUE THREAD

**Issue by jahknem** [nextcloud/calendar#4116]
### Is your feature request related to a problem? Please describe.

Add the beginning of the semestre, I'll add all my lectures, tuitions and other repeating events to nextcloud. Each time I do that it will take at least half an hour to do so as I have to add Title, Date, Time, Location, Reminders, Recurrence, and if I'm the one hosting the event also Attendees and Resources. This takes time and this amount of time is unavoidable for one single event. However, as I have to do that for each individual event anew, it also takes time for each individual event, even if they are very similar, with being added to the same calendar, having the same reminder and recurrence. 

### Describe the solution you'd like

Instead of doing a lot of the same steps repeatedly I'd like to be able to create event templates or be able to copy an event. If I have the same lecture Thursday afternoon and friday morning, in the same room with the same people, I'd like to be able to copy the thursday event and paste it to friday morning.

### Describe alternatives you've considered

An alternative which, in my opinion, would be less entry user friendly, would be to add a button for a further time at which the event will take place. For example I will create an event which will take place on the 31.03.2022 at 3 PM, but also at 7 PM on the same day. However I believe that would make the UI needlessly cluttered and complex

**Comment by ChristophWurst** [comment]
If you use https://github.com/nextcloud/calendar/issues?q=is%3Aissue+is%3Aopen+clone you'll find https://github.com/nextcloud/calendar/issues/113 and the linked PR https://github.com/nextcloud/calendar/pull/2621.

**Comment by tcitworld** [comment]
And specifically about event templates, this seems out of the scope of this app.
