### ISSUE TITLE
Implement usage of function keys

### ISSUE THREAD

**Issue by jahknem** [nextcloud/calendar#4118]
### Is your feature request related to a problem? Please describe.

Using the calendar only works using the mouse or touch. There is no way to use keyboard controls for faster access to functions, e.g. deleting, moving or editing the event in any way

### Describe the solution you'd like

I'd like to be able to manipulate my events using function keys on my keyboard, e.g. "Delete", "Insert", "Ctrl+X/C/V"

### Additional context

I'm sorry for so many issues at the same time. They piled up and I only now had time to submit them

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/issues?q=is%3Aissue+is%3Aopen+shortcuts leads to https://github.com/nextcloud/calendar/issues/157
