### ISSUE TITLE
Different visibility when sharing

### ISSUE THREAD

**Issue by SomeThink1729** [nextcloud/calendar#4134]
### Is your feature request related to a problem? Please describe.

I would like to share my calendar with my friends. But with some friends I want to share my whole calendar, which right now is possible without any problems. Furthermore I want to share my calendar to other people but with a different visibility.

### Describe the solution you'd like

I would like to have a general option when sharing:

- show all
- show only busy

Hence when creating a meeting I would like to have a standard option (to be configured) which is then overwritten by the sharing option except it's set to something else.

Example:
I want to share everything, except the choir meeting. I only choose at the choir meeting to hide it. Then I share and select the option to show everything.

### Describe alternatives you've considered

It would be possible to create two calendars and sychronize them except for different visibilities.

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/server/issues/11214 (and more issues listed in https://github.com/nextcloud/calendar/issues/4086#issuecomment-1072698662)
