### ISSUE TITLE
Caldav Import

### ISSUE THREAD

**Issue by rhinozeross** [nextcloud/calendar#4135]
### Is your feature request related to a problem? Please describe.

Hello Guys! 
We have the feature to share our Nextcloud Calendars via Caldav.
But It is not possible to integrate a Nextcloud Calender via Caldav into another Nextcloud Calender.
For example: i have a few Associations i'm active in and both have their own Nextcloud Instance. I want to have all of my different Calenders in One place = one of the Nextcloud instances but not on my phone,
Another Example is that i want to share one of my Calendars with someone from another Association with their own Nextcloud, without the need to make this person a new Account on our Nextcloud(because then he needs to have an account on every nextcloud:/)

### Describe the solution you'd like

I would like to be able to import a Calender not via ics File but via CalDav URL

### Additional context

It would really be fantastic to get this feature and I am willing to pay a bounty for that;)
Thank you in Advance for your Feedback, your Effort and your really hard work:)

**Comment by tcitworld** [comment]
This is either #1440 if you need write access to the calendars, otherwise just make public the calendars on Nextcloud A and subscribe to them on instance B ([adjust refresh rate](https://docs.nextcloud.com/server/latest/admin_manual/groupware/calendar.html#refresh-rate) if needed).

**Comment by rhinozeross** [comment]
Hey! thank you for your reply:) how can i subscribe a calender to instance B? there is only the option to import via ics.file not via URL or anything...

**Comment by tcitworld** [comment]
![image](https://user-images.githubusercontent.com/2197836/161947418-ca0177a6-642e-4bbb-8992-479745e1b685.png)


https://docs.nextcloud.com/server/latest/user_manual/en/groupware/calendar.html#subscribe-to-a-calendar

**Comment by rhinozeross** [comment]
Thank you sooo much for your Help!!

**Comment by florom** [comment]
@rhinozeross 
Probably this is of intereset for you too. So you know what you are doing:
https://help.nextcloud.com/t/sync-share-google-calendar-nextcloud-calendar/114131/5?u=florom
