### ISSUE TITLE
Navigation icon is hard to find

### ISSUE THREAD

**Issue by fab920** [nextcloud/calendar#4136]
### Steps to reproduce

1. Open the calendar 
2. Look for the calendar icon

The icon is placed over the content is very hard to see. Especially on mobile.

![calendar](https://user-images.githubusercontent.com/71835291/161983687-e47e303c-e3ba-4ade-8522-461ebcff78ea.jpeg)

### Expected behavior

The icon should be better visible. Either using a color, some kind of skrim as background or placing somewhere else.

### Actual behaviour

The icon is hardly visible.

### Calendar app version

 3.2.2

### Browser

desktop and mobile browsers

### Nextcloud version

23.0.2

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/groupware/issues/2
