### ISSUE TITLE
vue devtools doesn't detect calender in development mode.

### ISSUE THREAD

**Issue by 0xc0Der** [nextcloud/calendar#4138]
### Steps to reproduce

1. enable calendar app in development mode.
2. 
3.

### Expected behavior

vue devtools detects calendar.

### Actual behaviour

it does not.

**Comment by 0xc0Der** [comment]
i used `make watch-js`.

**Comment by tcitworld** [comment]
Did you follow https://github.com/nextcloud/nextcloud-vue#using-vue-devtools-in-firefox ?

**Comment by 0xc0Der** [comment]
i did follow it and it worked, thank you for your help. :smile:

**Comment by 0xc0Der** [comment]
is there any chance that you make this the default behavior?

**Comment by tcitworld** [comment]
Nope, this is set for security reasons. Possibly we could make this automatic if `"debug" => true` in the `config.php` file.
