### ISSUE TITLE
subscribed calendar not available to the client

### ISSUE THREAD

**Issue by tessus** [nextcloud/calendar#414]
Please forgive me, if this has been mentioned already, but I couldn't find any documentation about this.

If I create a new calendar, the new calendar shows up on the client when refreshing the calendar base url.
If I subscribe to a calendar, the calendar never shows up on the client. Funny thing is that the _Contact birthdays_ calendar, which is also listed in the _subscription_ section, is available to the client.

Maybe I'm wrong, but it seems to me that this is not right. What do you think?

If this is a bug, my env is nc 11.0.2 with calendar 1.5.2. no errors in any log files.

**Comment by tcitworld** [comment]
See https://github.com/nextcloud/server/issues/1497
