### ISSUE TITLE
Default visibility per calendar

### ISSUE THREAD

**Issue by nicoe** [nextcloud/calendar#416]
This is more a feature request then a bug.

The default visibility is PUBLIC it would be nice if there was a default visibility per calendar.

**Comment by georgehrke** [comment]
please describe a valid use-case

**Comment by nicoe** [comment]
* Georg Ehrke  [2017-04-12 11:23 +0200]: 
>please describe a valid use-case

I have two calendars in my current setup one is my personal calendar
the other one is a work calendar.

I'd like to share my personal calendar with my coworker so that he
knows that I am not available at this time but not the details of what
I am doing. And it will be the case for all event in my personal
calendar.

There might be another way to do it then setting the Visibility
parameter but I haven't found it.

**Comment by georgehrke** [comment]
What you are looking for is Free/Busy support ;)

https://github.com/nextcloud/calendar/issues/39
