### ISSUE TITLE
Import caldav/webcal/ics calendar external link to existing NC calendar

### ISSUE THREAD

**Issue by ValentinDrean** [nextcloud/calendar#4160]
### Is your feature request related to a problem? Please describe.

I have several calendars outside of my NC instance, some of them are webcal://, some of them are .ics

### Describe the solution you'd like

I wan't to import them in the same Nextcloud Calendar so people from all of those external calendars can see and share their events =)

### Describe alternatives you've considered

I do know that best solution would be to invite them all inside NC Calendar Instance, but that's not possible here.
╮(─_─)╭

Also I thought I could import external calendar inside read-only NC calendar, then automatically sync both calendars from within NC. Sorry I'm not a calendar developper here, maybe this is silly but if it's more simple I'll take that solution, I have cli access to my nc.

**Comment by tcitworld** [comment]
You can subscribe to external calendars: https://docs.nextcloud.com/server/latest/user_manual/en/groupware/calendar.html#subscribe-to-a-calendar

**Comment by ValentinDrean** [comment]
I'm sorry, I think this is not what I'm looking for, what I would like to have is to subscribre external calendars INTO one same **existing NC calendar**.

**Comment by tcitworld** [comment]
If that's what you really want you can programmatically use the CalDAV API to import ics files into your own calendar - or download and import the ics files manually of course - but that's not an use case we commonly encounter, sorry.
