### ISSUE TITLE
Extend the sidebar editor to full width on small screens

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#4161]
### Is your feature request related to a problem? Please describe.

On small screens the sidebar editor can take more than 50% of the available width. The grid is squished to the point were it becomes unreadable.

![image](https://user-images.githubusercontent.com/1479486/163582205-18bde407-2230-453e-8f9a-c7ef0f2bad06.png)

### Describe the solution you'd like

I propose to extend the sidebar editor to the whole width. Like we do it in Mail when viewing threads.

### Additional context

Followup to #4133

**Comment by szaimen** [comment]
Shouldn't this be rather a default for the vue component?

**Comment by szaimen** [comment]
> Shouldn't extending the sidebar to the full width on mobile rather be a default for the vue component?

cc @jancborchardt @nimishavijay @skjnldsv

**Comment by skjnldsv** [comment]
Should be for the vue components

**Comment by szaimen** [comment]
PR in https://github.com/nextcloud/nextcloud-vue/pull/2747
