### ISSUE TITLE
Error: Return type of OCA\Calendar\Db\AppointmentConfig::jsonSerialize() 

### ISSUE THREAD

**Issue by Synochy** [nextcloud/calendar#4189]
### Steps to reproduce

1.Install nextcloud 24
2.Install PHP8.1
3.Look at error journal

### Expected behavior

No entry in journal

### Actual behaviour

Error: Return type of OCA\Calendar\Db\AppointmentConfig::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/nextcloud/apps/calendar/lib/Db/AppointmentConfig.php#186

### Calendar app version

3.2.2

### Server operating system

Debian 10

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.1

### Nextcloud version

24

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by tcitworld** [comment]
A calendar release with PHP 8.1 compatibility has not yet been published: https://github.com/nextcloud/calendar/pull/3996

Follow https://github.com/nextcloud/groupware/issues/27 for updates
