### ISSUE TITLE
no VTIMEZONE for "all day" events causes display issues in CALDAV client

### ISSUE THREAD

**Issue by eheimer** [nextcloud/calendar#419]
I've been having problems with my "all day" events syncing with my android calendar app.  On the android app, the event is shown one day earlier than it is in Nextcloud web interface.  I did some troubleshooting and narrowed it down to the VTIMEZONE section not being included in the calendardata when the record is created.

### Steps to reproduce
1. create an "all day" event in the calendar web interface
2. observe in the database, in the calendardata field, there is no VTIMEZONE section.
3. after mobile calendar app syncs, observe event shows up on wrong day
4. in nextcloud calendar web interface, edit event and uncheck "all day", save the event.
NOTE: i've configured my calendar in nextcloud (manually, via the database) to have a default timezone, so this auto-fills when I uncheck "all day" and save.
5. after saving the event, edit the event and re-check the "all day" check box, save the event again
6. observe in the database, the calendardata field now contains the VTIMEZONE section
7. after mobile calendar app syncs, observe event now shows up on the correct day

### Expected behaviour
If your calendar is configured with a specified timezone in the database, the VTIMEZONE section should be created for "all day" events

### Actual behaviour
no VTIMEZONE section, so calendar app on android assumes UTC

### Server configuration

**Operating system**: debian

**Web server: apache

**Database: mysql

**PHP version: 5

**Server version:** Nextcloud 11.0.2 (stable)

**Calendar version:** 1.5.2

**Updated from an older installed version or fresh install:**
upgraded today from 9.0 - same problem was observed in that version, was hoping upgrade would fix it

**Signing status (ownCloud/Nextcloud 9.0 and above): **

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.

```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - deck: 0.1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ojsxc: 3.1.1
  - password_policy: 1.1.0
  - passwords: 20-beta9
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - bookmarks
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_mv
  - files_retention
  - gallery
  - notes
  - passwords.old
  - tasks
  - user_external
  - user_saml

```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

{
    "system": {
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "instanceid": "ocvkozw5olgy",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "spinach2.heimerman.org"
        ],
        "datadirectory": "\/var\/owncloud\/",
        "overwrite.cli.url": "http:\/\/spinach2.heimerman.org\/owncloud",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Chicago",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "logfile": "\/var\/www\/owncloud\/data\/nextcloud.log",
        "theme": "",
        "trashbin_retention_obligation": "auto",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "ldapIgnoreNamingRules": false,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** SSL

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox

**Operating system:** windows

**CalDAV-clients:** android calendar

**Comment by georgehrke** [comment]
All-Day events are timezone agnostic. I suspect this is a bug in your android app.
Which android app do you use?

**Comment by eheimer** [comment]
That seems logical.  I am using aCalendar:  https://play.google.com/store/apps/details?id=org.withouthat.acalendar

However, I just checked the stock android calendar app, and it displays the same way (incorrectly).  I am using zpush for the syncing.  I wonder if that is the problem?

**Comment by georgehrke** [comment]
>  I am using zpush for the syncing. I wonder if that is the problem?

That might be it. I never heard any complains from people using [Davdroid](https://davdroid.bitfire.at):
- [Google Play](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&referrer=utm_source%3Dhomepage)
- [FDroid](https://f-droid.org/repository/browse/?fdfilter=Davdroid&fdid=at.bitfire.davdroid)

**Comment by eheimer** [comment]
I came across this in the Z-Push forums: https://forums.zarafa.com/showthread.php?13209-BackendCalDAV-Timezone-Problems&highlight=timezone

That seems like the same problem I'm seeing.  They link to a JIRA issue which has been resolved (https://jira.z-hub.io/browse/ZP-1112), so I will try updating zpush and report back.

**Comment by eheimer** [comment]
zpush 2.3.5 solves this issue.  Thanks for your feedback!
