### ISSUE TITLE
Please add Persian Shamsi/Jalali Calendar

### ISSUE THREAD

**Issue by SinaBina** [nextcloud/calendar#4200]
### Is your feature request related to a problem? Please describe.

Changing the locals to Persian does not change the Calendar type to Shamsi/Jalali.

### Describe the solution you'd like

Please add Persian Shamsi/Jalali Date.Many users including myself are having hard time working with Georgian calendar.Thank you.

**Comment by mahdiar** [comment]
Yes! It's a necessary feature.

**Comment by miaulalala** [comment]
Unfortunately, the underlying library doesn't support Shamsi/Jalari Calendars yet: https://github.com/fullcalendar/fullcalendar/issues/1813

Until it has been implemented in Fullcalendar, we can't offer this option.

**Comment by Pouya47** [comment]
> Unfortunately, the underlying library doesn't support Shamsi/Jalari Calendars yet: [fullcalendar/fullcalendar#1813](https://github.com/fullcalendar/fullcalendar/issues/1813)
> 
> Until it has been implemented in Fullcalendar, we can't offer this option.

Hi,
Fullcalander support Shamsi/Jalali by change locale to **fa** now!
