### ISSUE TITLE
Event title not fully readable in the right side panel

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/calendar#4210]
### Is your feature request related to a problem? Please describe.

When I look at the details of a diary event of a colleague who has shared his diary with me in read-only mode (right-hand side panel), I cannot read its title if it is a bit long. In this case the title is cut off and ends with ellipsis.
![2022-05-11_10-07](https://user-images.githubusercontent.com/33763786/167806753-af7a5f15-fb57-42f5-b0f2-5b34508f0bd7.png)
 

### Describe the solution you'd like

Remove the ellipsis and display the full title of the event, with line breaks if necessary, as in the simplified display
![2022-05-11_10-42](https://user-images.githubusercontent.com/33763786/167808126-4dcf57ba-4a79-4b39-9c74-89ae73a94faa.png)
.

### Describe alternatives you've considered

Display an information bubble with the full title when the cursor is hovered over it (Simple HTML attribute ; example: title="{full title of the event}")
![2022-05-11_10-27](https://user-images.githubusercontent.com/33763786/167806842-2a3bf063-cafa-47e0-8e7f-25537b336ea6.png)
.

**Comment by tcitworld** [comment]
I think we could allow two lines + title attribute. Opinions @nextcloud/designers?

**Comment by raimund-schluessler** [comment]
Allowing two lines needs to be done in the vue-components. There is a long standing PR that never got finished/merged:
https://github.com/nextcloud/nextcloud-vue/pull/1788

Adding a Tooltip with the full title is possible easily, we just need to set the `title-tooltip` prop accordingly.

**Comment by nimishavijay** [comment]
Agreed, 2 lines sounds good! If the name is longer than 2 lines then we can ellipsise and use a tooltip :)

**Comment by Jerome-Herbinet** [comment]
> Agreed, 2 lines sounds good! If the name is longer than 2 lines then we can ellipsise and use a tooltip :)
> 

This would be nice.

**Comment by Jerome-Herbinet** [comment]
@juliushaertl what do you think about this issue ?

**Comment by Jerome-Herbinet** [comment]
I think I've found a great CSS property to manage that (with it, it's even possible to choose number of line before displaying "...". Can somebody just help me find the CSS or vue file I shlould edit ? I struggled a lot to find it ... without success ? Once somebody can give me the information, I'll create a PR.

**Comment by Jerome-Herbinet** [comment]
Check my Pull Request 🙂
#3295

**Comment by miaulalala** [comment]
PR has not been merged:

https://github.com/nextcloud-libraries/nextcloud-vue/pull/4194
