### ISSUE TITLE
Invisible option selection window

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/calendar#4219]
### Steps to reproduce

1. Change the language to Polish.
2. Select app settings.

### Expected behavior

Visible check box of options.

### Actual behaviour

Invisible option selection window with a longer text string:

![obraz](https://user-images.githubusercontent.com/47037905/168540022-4f7a5c9a-b150-4bec-8cc5-d717cd852633.png)

### Calendar app version

3.3.0

### Browser

Firefox 100.0

### Database engine version

MySQL

### PHP engine version

PHP 7.4

### Nextcloud version

24.0.0

**Comment by brasofilo** [comment]
Also happening to me, PT_BR, Calendar 3.3.0:

![image](https://user-images.githubusercontent.com/1542052/169186896-f36476aa-4727-4cd6-8f37-94ed3a1b4430.png)
