### ISSUE TITLE
Enbedded iframe calendar does not set up to brower default language

### ISSUE THREAD

**Issue by Elm7** [nextcloud/calendar#422]
Hi,
the public page does show up in french, but the embedded cal in an iframe even with 
 <lang="fr"> shows up in english (with sundays as first week day). 

Is there a way to set displayed language directly in the url adresse ?

**Comment by georgehrke** [comment]
The language should be determined based on the language set in the browser. Is it not for you?

**Comment by georgehrke** [comment]
if not, you can set a default lang for your nextcloud instance in the config.php with
`'default_language' => 'fr',`

**Comment by Elm7** [comment]
Thanks. It seems to be set in the config.php because if I set Firefox content lang to "en" the calendar is still in french in the web page. The problem only occurs when I display the calendar in another page using an iframe : it displays in english there and not in French as it is in the direct calendar web page.

**Comment by georgehrke** [comment]
So setting `'default_language' => 'fr',` in the config.php fixed your issue?

**Comment by Elm7** [comment]
Well, this is not my instance, so I was trying to guess. I'll ask the admin if it is the case and come back here.

**Comment by tcitworld** [comment]
Could it be that the parent page where you include the iframe is `<html lang="en">` ?

**Comment by Elm7** [comment]
Nope, it is <html lang="fr"> 
thx

**Comment by tcitworld** [comment]
@Elm7 We responded you about the `'default_language' => 'fr'` being in `config.php` through email, it is indeed.

**Comment by Elm7** [comment]
Thanks @tcitworld for the answer. (Sorry, I did not get the email for a reason I do not know)

**Comment by Elm7** [comment]
So I have done more test (I should have done it before to save you time, sorry). It is ok with chromium.
The problem comes from firefox browser (maybe a bug in langage setting…). What fixed the issue was : go to preference, content, and set "us" or another as first langage, then reset «fr» as first langage again. Load the page with embed calendar : issue fixed.

You can close the issue. Thank you and have nice days.

**Comment by tcitworld** [comment]
Should have started by asking that. Thanks.
