### ISSUE TITLE
Check a focus for "show busy items" modal window

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/calendar#4229]
### Is your feature request related to a problem? Please describe.

Accessibility issue.

When booking a time for a meeting with a colleague there’s a function for checking availability which opens a modal window ("Show busy times"). Focus is not moved into the modal but to the “Save” button.

Make sure, that the first focus goes to the first form element inside of modal window.

**Comment by st3iny** [comment]
The focus is moved to first element on pressing tab and it's trapped inside the modal on latest nextcloud-vue master.
