### ISSUE TITLE
Slashes in User Group names break Calendar App

### ISSUE THREAD

**Issue by flesser** [nextcloud/calendar#424]
### Steps to reproduce
1. Create a Group containing a slash, e.g. "Foo/Bar"
2. add a user to it
3. try to use the calendar app as that user

### Expected behaviour
Calendar app works, showing calendars

### Actual behaviour
Calendar fails to load or create calendars,
the spinners in the left sidebar keep spinning.
The PROPFIND request to `remote.php/dav/principals/users/<username>/` fails (404) with a message like `Unable to find Principal Foo` ("Foo" being the first part of the group name before the slash).

After removing the user from the offending group and adding him to another (slashless) group, the Calendar App works as expected.

### Server configuration
**Operating system**: Linux hostname 3.2.41-042stab120.5 #1 SMP Tue Oct 25 22:31:12 MSK 2016 x86_64

**Web server:** Apache/2.2.22 (Debian) (cgi-fcgi)

**Database:** mysql 5.5.54

**PHP version:** 5.6.30-1dotdeb+7.1
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, json, mbstring, pcntl, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cgi-fcgi, PDO, apcu, curl, gd, imagick, imap, intl, ldap, mcrypt, memcache, mysql, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, readline, sqlite3, mhash, apc, Zend OPcache

**Nextcloud version:** 11.0.2 (stable) - 11.0.2.7

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated from older ownCloud

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "occcfc3dac15",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "domain.tld",
        "www.domain.tld"
    ],
    "datadirectory": "\/media\/nextcloud-data",
    "dbtype": "mysql",
    "version": "11.0.2.7",
    "dbname": "dbname",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "loglevel": 1,
    "default_language": "de",
    "maintenance": false,
    "mail_from_address": "***",
    "mail_smtpmode": "php",
    "mail_domain": "domain.tld",
    "log_rotate_size": 209715200,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "overwritewebroot": "\/nextcloud",
    "overwrite.cli.url": "\/nextcloud",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trashbin_retention_obligation": "auto",
    "updatechecker": false,
    "htaccess.RewriteBase": "\/nextcloud\/",
    "theme": "",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:**
All options activated, but not in use

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) rekonq/2.4.2 Safari/537.21

</details>

**Comment by flesser** [comment]
maybe related to https://github.com/nextcloud/server/issues/2954 ?

**Comment by tcitworld** [comment]
Vers probably. Not much we can do on this side.

**Comment by georgehrke** [comment]
@flesser What was the name of the user?

**Comment by georgehrke** [comment]
@flesser please answer my previous question :)

**Comment by flesser** [comment]
@georgehrke sorry for the delayed reply, the user name was `cg-heidelberg`

**Comment by georgehrke** [comment]
my fault, needs info should have been removed

**Comment by georgehrke** [comment]
I can no longer reproduce this bug with Calendar 2.0.0 beta1. 
Closing
