### ISSUE TITLE
Event title focus got thicker

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#4252]
### Steps to reproduce

1. Create an event
2. Open the simple editor

### Expected behavior

:sunglasses: 

### Actual behaviour

![Bildschirmfoto vom 2022-06-01 16-36-02](https://user-images.githubusercontent.com/1374172/171430698-ada35a39-387a-4d18-a998-4a9347cfe7f6.png)

### Calendar app version

3.4

### Nextcloud version

25

### Additional info

@nimishavijay @jancborchardt was this an intended change I've missed?

**Comment by jancborchardt** [comment]
This seems related to the accessibility fixes for focus, @JuliaKirschenheuter @marcoambrosini? Maybe 1px thinner would be good indeed, or what do you think?

**Comment by JuliaKirschenheuter** [comment]
> This seems related to the accessibility fixes for focus, @JuliaKirschenheuter @marcoambrosini? Maybe 1px thinner would be good indeed, or what do you think?

Ok, we can do it. I would say this is a NC-Vue issue, is't it?

**Comment by ChristophWurst** [comment]
> This seems related to the accessibility fixes for focus

Then I suspect https://github.com/nextcloud/mail/issues/6510 to be the same "problem".

**Comment by JuliaKirschenheuter** [comment]
> Then I suspect https://github.com/nextcloud/mail/issues/6510 to be the same "problem".

how could we combine this stuff in one ticket? (it is all around different focus styles, i guess cross-app)
