### ISSUE TITLE
Event displaying problem after changing its associated calendar

### ISSUE THREAD

**Issue by johnguery** [nextcloud/calendar#4257]
### Steps to reproduce

1. Create an event
2. Update the event 
3. Change the selected calendar by another one
4. Drag&drop the event anywhere
5. Validate your change

### Expected behavior

The event should have the color updated (related to the selected calendar)

### Actual behaviour

It displays the events twice : it duplicates the first, so we can see two events with the two calendars colors
Just need to refresh the page and only the event with the right calendar is displayed

### Calendar app version

	3.3.1

### Browser

Chrome 102.0.5005.63

### Client operating system

Windows 10

### Server operating system

Debian 10

### Web server

Nginx

### Database engine version

MySQL

### PHP engine version

PHP 8.0

### Nextcloud version

22.2.3

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by miaulalala** [comment]
Can't reproduce
