### ISSUE TITLE
Move the Repeat component so it can be used by nextcloud/tasks

### ISSUE THREAD

**Issue by RayBB** [nextcloud/calendar#4258]
### Is your feature request related to a problem? Please describe.

The problem is that nextcloud/tasks doesn't support recurring tasks.
Here is the open issue: https://github.com/nextcloud/tasks/issues/34

In order to support recurring tasks it will need a UI for selecting the recurrence (to create the RRULE).

As I've dug into this I realized that this repo (nextcloud/calendar) has an excellent UI for selecting recurrence [here](https://github.com/nextcloud/calendar/blob/v3.3.2/src/components/Editor/Repeat/Repeat.vue). It would make sense to share this component instead of copy/pasting or writing from scratch.

If this makes sense to the maintainers of this repo, I think we should come this component over to the shared repo.
PS: I posted about this on the nextcloud/tasks issue [here](https://github.com/nextcloud/tasks/issues/34#issuecomment-1146744792).

### Describe the solution you'd like

To the best of my understanding there are a few steps:
1. Add the [Repeat component](https://github.com/nextcloud/calendar/blob/v3.3.2/src/components/Editor/Repeat/Repeat.vue) to https://github.com/nextcloud/nextcloud-vue
2. Use the repeat component in nextcloud/calendar
3. I can use the Repeat Component in nextcloud/tasks

I don't know either of these codebases very well. I'm not sure if there would be any refactoring needed to make this component work for both use cases. I would appreciate an guidance.
As it stands, I'm not sure where calendarObjectInstance (required by the Repeat Component) would come from when used in [AppSidebar.vue](https://github.com/nextcloud/tasks/blob/master/src/views/AppSidebar.vue). Maybe from the tasks [calendarObject](https://github.com/nextcloud/tasks/blob/master/src/models/calendarObject.js).

I'm guessing there will be other problems ahead but generally this component's UI is what we want.

### Describe alternatives you've considered

1. Copy/Paste the code into nextcloud/tasks. I've actually already started this just to play around with it. However, I don't think the kind folks at nextcloud want to maintain two components that are nearly identical like that.
2. Write a new UI for selecting recurrence. This is possible, but doesn't seem like a good use of anyone's energy.

If anyone has further alternatives please let me know I'd love to hear it :)

### Additional context

If anyone who knows nextcloud's codebase well is willing to chat with me about the process it would be extremely appreciated. You can contact me on [Twitter](https://twitter.com/RayScript), or I'm in the Matrix [Nextcloud-calender room](https://matrix.to/#/#nextcloud-calendar:matrix.org). 

Here's a video of the component I'd like moved (just the recurrence part):
https://user-images.githubusercontent.com/921217/172266763-36012b2c-e9cf-40df-a7dc-fdecdbfe7270.mp4

I've been talking with @BaderSZ about this. He is helping do some of the under the hood changes to support the RRULE.
@raimund-schluessler [said](https://github.com/nextcloud/tasks/issues/34#issuecomment-1113608903) he doesn't have time to implement the feature for nextcloud/tasks but he seems receptive to having someone else work on it.

**Comment by BaderSZ** [comment]
I could file a MR if it is preferred, but could someone from the project confirm if that's desired before I start working on it? :smile:

**Comment by szaimen** [comment]
Cc @st3iny @ChristophWurst

**Comment by raimund-schluessler** [comment]
I would say we simply copy the code required to the Tasks repository and adjust it there. We did the same with the code for the trash bin. Having it in a shared repository is more effort than having it duplicated (once) and is anyway only reasonable if there is a lot of further development planned for this component.

If it turns out that more apps need it, or maintaining it twice is too much effort, we can still reevaluate that decision.

Regarding the question where `calendarObjectInstance` comes from, this is provided by calendar-js. For this reason we plan to use it in the Tasks app too, see https://github.com/nextcloud/tasks/issues/1739. I think this is a requirement for supporting repeating Tasks. But let's discuss this in the Tasks repository.
