### ISSUE TITLE
Nextcloud Calendar as full CalAV read/write client 

### ISSUE THREAD

**Issue by mkrecek234** [nextcloud/calendar#4261]
### Is your feature request related to a problem? Please describe.

- Nextcloud calendar should support to connect to other private CalDAV calendars, supporting viewing and editing of events
- Currently only ics subscriptions are offered

### Describe the solution you'd like

- Add external CalDAV account to your personal calendars, with full read/write access
- Eventually provide a virtual Free/Busy Calendar which merges all events of selected internal and external calendars in one

Why is it so important?
Because the standard solution today in most companies is that there is one email/calendar server (supporting mail invitations out of your ActiveSync calendar etc.), and people have also private calendars on other servers linked to their private address.

Nextcloud solutions like Polls/Appointments would benefit from this, as your Nextcloud calendar could combine all calendars and offer perfect Free/Busy times for Polls/Appointment applications.

### Describe alternatives you've considered

Not available on the market

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/calendar/issues/2766
