### ISSUE TITLE
Tasks do not appear in web calendar after creating them into thunderbird

### ISSUE THREAD

**Issue by bvn13** [nextcloud/calendar#4264]
### Steps to reproduce

1. Create calendar with tasks
2. Subscribe to calendar into Mozilla Thunderbird (Linux)
3. Create a task into Thunderbird

### Expected behavior

The task should appear in web version of calendar

### Actual behaviour

The task seems not created in web calendar, but in Android Application into section "Previous actions" the action about task creating is present. And Thunderbird shows the task into "current tasks" section.

### Calendar app version

	3.3.1

### CalDAV-clients used

Thunderbird on Linux

### Browser

Vivaldi

### Client operating system

Fedora Linux 35 (Workstation)

### Server operating system

Ubuntu 20.??, Docker

### Database engine version

PostgreSQL

### Nextcloud version

23.0.3 from docker

**Comment by raimund-schluessler** [comment]
You need to have `Show tasks in calendar` enabled (left bottom settings section in the Calendar app) and the task has to have a due date (otherwise the Calendar app has no clue where to show it).

**Comment by bvn13** [comment]
You are correct! My task had no due date. It was the clue.
