### ISSUE TITLE
Better designed emails when sharing calendar

### ISSUE THREAD

**Issue by enoch85** [nextcloud/calendar#427]
Today we use standard templates that contains mostly text. It works, but isn't that pretty. What I suggest is to improve the design so that it looks more professional. I've seen some great work by @Espina2 the past weeks, and I'd really like to see some suggestions regarding an improvment of the mails that are sent to users.

As an external user of Nextcloud (someone that uses Nextcloud sends a link to someone that doesn't) the first impression is the mail they get with either a calendar invitavion or a shared link. To attract more users to use Nextcloud and make a switch from Google or some other provider I belive it's crucial that our soulution looks better.

Google Calendar invitation:
![markering_002](https://cloud.githubusercontent.com/assets/4511254/20173548/09531524-a73a-11e6-8afc-f92ded462dc4.png)

The server emails are merged by @MorrisJobke and now it's only the calendar emails left.. It currently looks like this in Thunderbird:
![calendar](https://cloud.githubusercontent.com/assets/4511254/25436996/41a285f2-2a95-11e7-90a0-4ceaf31abb75.png)

It would be great if that also was merged before 12 is release so that we can close this issue.

Thank you! :)

Copy pasted from here: https://github.com/nextcloud/server/issues/2071

**Comment by enoch85** [comment]
cc @georgehrke

**Comment by georgehrke** [comment]
Invitation emails are part of the nextcloud server.

The email template when publicly sharing a calendar we can update for sure :)

**Comment by MarkusAmshove** [comment]
Hi,

I'll hijack this issue instead of opening a new one, I hope this is okay :-)

Today I tried to invite people to a appointment via the "Teilnehmer" (don't know how it called originally in english) tab within the calendar.

However, the invitied people didn't get an email, is this the expected behavior?

I tried to send a test email in the nextcloud administration settings and it worked

**Comment by tcitworld** [comment]
> However, the invitied people didn't get an email, is this the expected behavior?

No, but please open a new issue.

**Comment by georgehrke** [comment]
@enoch85 There is a work in progress in https://github.com/nextcloud/calendar/pull/476 :)

**Comment by enoch85** [comment]
@georgehrke <3
