### ISSUE TITLE
Action menu doesnt work on new event popover

### ISSUE THREAD

**Issue by GretaD** [nextcloud/calendar#4270]
### Steps to reproduce

1. Create new event/or open an existing one on popover view
2. Click action menu on top right
3. 

### Expected behavior

The menu is open

### Actual behaviour

Menu doesnt open
![menu-calendar-simple-editor](https://user-images.githubusercontent.com/12728974/173092827-20dfb368-360f-4b81-8080-ad36a2734a7c.png)

### Calendar app version

latest

**Comment by szaimen** [comment]
I think the bug is more that the 3-dot menu should not be shown for new events...
