### ISSUE TITLE
Action menu doesnt work on new/existing event sidebar

### ISSUE THREAD

**Issue by GretaD** [nextcloud/calendar#4271]
### Steps to reproduce

1. Create a new event, open an existing event and click more
2. Click the menu on top right
3.

### Expected behavior

The menu is open

### Actual behaviour

Nothing happens and the menu is not open
![sidebar-menu](https://user-images.githubusercontent.com/12728974/173093214-94e8e2b0-e7f3-4ce7-9f46-ededbe89bedd.png)

### Calendar app version

latest

**Comment by szaimen** [comment]
addressed with https://github.com/nextcloud/calendar/pull/4280?

**Comment by GretaD** [comment]
Yes, thanks Simon
