### ISSUE TITLE
problems with requests to app/calendar/ after update (core & app)

### ISSUE THREAD

**Issue by quenenni** [nextcloud/calendar#428]
The complete report is here: https://github.com/nextcloud/contacts/issues/205 (with the contact app)

The problem is exactly the same. The 2 js & 2 css calls to apps/calendar/js/.. return a "302 Found" with 0byte.
```
{"reqId":"9WKaTYpy7o0+tTu+jnoG","remoteAddr":"xxx.xxx.xxx.xxx","app":"calendar","message":"Could not find resource file \"\/apps\/calendar\/js\/public\/vendor.min.js\"","level":3,"time":"2017-04-27T17:26:34+00:00","method":"GET","url":"\/index.php\/apps\/calendar\/","user":"admin","version":"11.0.3.2"}
{"reqId":"9WKaTYpy7o0+tTu+jnoG","remoteAddr":"xxx.xxx.xxx.xxx","app":"calendar","message":"Could not find resource file \"\/apps\/calendar\/js\/public\/app.min.js\"","level":3,"time":"2017-04-27T17:26:34+00:00","method":"GET","url":"\/index.php\/apps\/calendar\/","user":"admin","version":"11.0.3.2"}
{"reqId":"9WKaTYpy7o0+tTu+jnoG","remoteAddr":"xxx.xxx.xxx.xxx","app":"calendar","message":"Could not find resource file \"\/apps\/calendar\/css\/public\/vendor.min.css\"","level":3,"time":"2017-04-27T17:26:34+00:00","method":"GET","url":"\/index.php\/apps\/calendar\/","user":"admin","version":"11.0.3.2"}
{"reqId":"9WKaTYpy7o0+tTu+jnoG","remoteAddr":"xxx.xxx.xxx.xxx","app":"calendar","message":"Could not find resource file \"\/apps\/calendar\/css\/public\/app.min.css\"","level":3,"time":"2017-04-27T17:26:34+00:00","method":"GET","url":"\/index.php\/apps\/calendar\/","user":"admin","version":"11.0.3.2"}
```

I can't find in the old dir the same files requested here, so I can't test that.

It's also very strange that the missing requested files aren't present in the github code page when I select the version 1.4.1 that was working with my old instance.

As the same problem occurs with the 2 external app I'm using, I'm wondering if this is an app problem or a core one (they are making no sense to me).

**Comment by georgehrke** [comment]
I just double checked. The file is there in the latest release. (https://github.com/nextcloud/calendar/releases/tag/v1.5.2)

Seems to be a bug in the updater. Please report in https://github.com/nextcloud/server/issues

**Comment by quenenni** [comment]
Indeed.. Nice. Thanks.

But why this 1.5.2 (https://github.com/nextcloud/calendar/tree/v1.5.2)  doesn't have them.
The tree for 1.5.2 is not the same as for the tag 1.5.2? Very confusing.

**Comment by georgehrke** [comment]
> The tree for 1.5.2 is not the same as for the tag 1.5.2? Very confusing.

Because vendor.js and vendor.min.js are bundled locally after running the Makefile ;) 
There is no point in checking them in.

**Comment by quenenni** [comment]
Ho.. indeed. Totally!
That's my bad..  I'm so used to clone projects where you don't have to compile before using it that I completely forgot that was the case here.
And I guess it's the same for the contact app.

Big thanks for your help and the time spent for my foolishness ;)
