### ISSUE TITLE
No release tarball for 3.3.2

### ISSUE THREAD

**Issue by dvzrv** [nextcloud/calendar#4284]
### Steps to reproduce

1. Try to download prebuilt source tarball for 3.3.2 (because https://github.com/nextcloud/calendar/releases/tag/v3.3.2 exists)

### Expected behavior

A release tarball can be downloaded at https://github.com/nextcloud-releases/calendar/releases

### Actual behaviour

There is no release for 3.3.2 at https://github.com/nextcloud-releases/calendar/releases

### Calendar app version

3.3.2

### CalDAV-clients used

n/a

### Browser

n/a

### Client operating system

Arch Linux

### Server operating system

Arch Linux

### Nextcloud version

24.0.0

### Additional info

I'm maintaining the package for Arch Linux

**Comment by tcitworld** [comment]
It doesn't seem to be published. https://apps.nextcloud.com/apps/calendar

**Comment by ChristophWurst** [comment]
I must have used the wrong repo to create the build and therefore the release automation didn't run. I've published https://github.com/nextcloud-releases/calendar/releases/tag/v3.3.2 now to trigger https://github.com/nextcloud-releases/calendar/actions/runs/2493386663

**Comment by ChristophWurst** [comment]
Fixed
