### ISSUE TITLE
month view part-time event missing event dot

### ISSUE THREAD

**Issue by tgly307** [nextcloud/calendar#4290]
### Steps to reproduce

1.update calendar to 3.4.0-RC1
2.check month view

### Expected behavior

Part-time event has a event dot before event describe like before to confirm which calendar belong to

### Actual behaviour

no event dot
![](https://user-images.githubusercontent.com/25153311/173729486-a023a911-f455-4c2c-a409-822d3265cb6a.png)

### Calendar app version

3.4.0-RC1

### Browser

chrome 102

### Client operating system

win10

### Server operating system

centos7

### Web server

Apache

### Nextcloud version

23.0.0

**Comment by ChristophWurst** [comment]
We need to revert the backport.

https://github.com/nextcloud/calendar/pull/4324

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/calendar/pull/4351
