### ISSUE TITLE
Events do not render correctly

### ISSUE THREAD

**Issue by GretaD** [nextcloud/calendar#4291]
### Steps to reproduce

1. Open calendar on white theme
2. Icons are white and you cannot see reminder icons or group icons  
3. The text overflows the event

### Expected behavior

I can see the icons on white theme and the text will not overflow

### Actual behaviour

You can see only icons on second row because its highlighted 
![icons-white-cal](https://user-images.githubusercontent.com/12728974/173811155-88c932d6-ab42-4a4c-a0ba-f169c3877add.png)

### Calendar app version

latest

### Additional info

Possible regression of https://github.com/nextcloud/calendar/pull/4085

**Comment by ChristophWurst** [comment]
Another one: https://github.com/nextcloud/calendar/issues/4290
