### ISSUE TITLE
New Appointments dont show up on Android DAVX Calendar

### ISSUE THREAD

**Issue by moboter** [nextcloud/calendar#4297]
### Steps to reproduce

1.Create new Appointment
2.Synchronize Account on Android Device
3.Appointment doenst show up

### Expected behavior

1.Create new Appointment
2.Synchronize Account on Android Device
3.Appointment shows up

### Actual behaviour

1.Create new Appointment
2.Synchronize Account on Android Device
3.Appointment doenst show up

### Calendar app version

3.3.2

### CalDAV-clients used

Davx5 VErsion 2.5.3 https://play.google.com/store/apps/dev?id=7085816884079006362&hl=de&gl=US

### Browser

Firefox 91

### Client operating system

Android

### Server operating system

Linux

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 7.4

### Nextcloud version

22.2.8

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by tcitworld** [comment]
You didn't say so, but I imagine they show up in the web calendar even if you refresh the page?

**Comment by moboter** [comment]
Correct works fine on the website

**Comment by moboter** [comment]
It only took 24 Hours and a server reboot
Its working again
