### ISSUE TITLE
Appointment: exclusion in timetable

### ISSUE THREAD

**Issue by michel-thomas** [nextcloud/calendar#4302]
### Is your feature request related to a problem? Please describe.

Not a bug, but a functionality I suppose essential because my free for appointment timetable is not regular.

### Describe the solution you'd like

Because I have not a regular availability for appointments, I would be able to define some exclusion to avoid booking at unwanted date/hour.

[Appointment app](https://apps.nextcloud.com/apps/appointments) shows draft events in calendar, so we can move or delete them. I think this more flexible.

So I need a way to see when appointment is open for subscriber, and a way to move or delete these if needed.

### Describe alternatives you've considered

Still using [Appointment app](https://apps.nextcloud.com/apps/appointments) event if GUI is not so friendly.

### Additional context

Many thanks for this work!

**Comment by matpen** [comment]
@michel-thomas you seem to require the ability to specify date-ranges that are made available for appointments: would you think that this overlaps with what is requested in https://github.com/nextcloud/calendar/issues/4141? Should we perhaps merge the two issues?

**Comment by michel-thomas** [comment]
Sorry for the delay!

Yes, this could solve my needs. Both issues can be merged.

Thanks
