### ISSUE TITLE
Calendar event editing not working in mont view

### ISSUE THREAD

**Issue by aledef** [nextcloud/calendar#4322]
Nextcloud version: 24.0.2

The issue I am facing:
Calendar event editing not working when calendar is in mont view

Steps to replicate it:

1. Open calendar app in mont view
2. Try to edit an event

The issue started after last NC & calendar app update

### Expected behavior

Events editing should be working in month view

### Actual behaviour

The Ui stops working

### Calendar app version

3.4.0

**Comment by miaulalala** [comment]
Duplicate of #4313
