### ISSUE TITLE
Changes only visible after reloading

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/calendar#4334]
### Steps to reproduce

1. create an event
2. delete an event

### Expected behavior

- Event should be created
- Event should be removed

### Actual behaviour

changes are displayed only after the page is reloaded.

### Calendar app version

3.4.1

### CalDAV-clients used

web

### Browser

Firefox 91

### Client operating system

Windows 10

### Server operating system

Ubuntu

### Web server

Apache

### Database engine version

PostgreSQL

### Nextcloud version

23.0.6

### Additional info

Nextcloud AIO

**Comment by marcmn74** [comment]
The same behaviour here. Calendar Version 3.4.1. Company with around 100 employees.

**Comment by olanwe** [comment]
Is this issue only affecting the month view? Could be the same problem as #4336. (At least this is the only way I am able to reproduce it on NC 24.0.2)

**Comment by versus167** [comment]
> Is this issue only affecting the month view? Could be the same problem as #4336. (At least this is the only way I am able to reproduce it on NC 24.0.2)

I can reproduce the problem in weekly-view (24.0.1snap1)

**Comment by versus167** [comment]
To flesh out the problem a bit more: When someone else changes appointments, the notification already appears in the upper right corner. But in the calendar itself the change does not appear or only after reload.

**Comment by JuliaKirschenheuter** [comment]
Was resolved via https://github.com/nextcloud/calendar/pull/4351
