### ISSUE TITLE
Wrong year is displayed sometimes

### ISSUE THREAD

**Issue by tkteun** [nextcloud/calendar#434]
### Steps to reproduce
1. In the calendar view, go to December 2015 in month view.
2. Skip to the next month.

### Expected behaviour
January 2016 should be displayed

### Actual behaviour
The indicator (sometimes) displays January 2016 as January 2015.

Might this be because 2015 has 53 weeks?

### Server configuration
Locale is English UK so the weeks start on Mondays.

**Operating system**: Arch
**Web server**: Nginx
**Database:** MariaDB
**PHP version:** 7.1.4
**Server version:** 11.0.2
**Calendar version:** 1.5.2
**Updated from an older installed version or fresh install:** Update
**Signing status (ownCloud/Nextcloud 9.0 and above):** No errors have been found.
**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - encryption: 1.4.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - direct_menu
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - files_trashbin
  - keeweb
  - mail
  - news
  - radio
  - user_external
  - user_ldap
  - user_saml
**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "forcessl": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "singleuser": false,
        "updatechecker": false,
        "htaccess.RewriteBase": "\/owncloud"
    }
}

**Are you using external storage, if yes which one:** local
**Are you using encryption:** yes
**Are you using an external user-backend, if yes which one:** N/A

### Client configuration
**Browser:** Vivaldi & FF
**Operating system:** LMDE2
**CalDAV-clients:** N/A

#### Browser log
```
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
warn @ moment-with-locales.js:282
DevTools failed to parse SourceMap: https://***REMOVED SENSITIVE VALUE***/core/vendor/jquery/dist/jquery.min.map
DevTools failed to parse SourceMap: https://***REMOVED SENSITIVE VALUE***/apps/calendar/js/public/app.min.js.map
DevTools failed to parse SourceMap: https://***REMOVED SENSITIVE VALUE***/apps/calendar/js/public/vendor.min.js.map
DevTools failed to parse SourceMap: https://***REMOVED SENSITIVE VALUE***/apps/calendar/css/public/app.min.css.map
DevTools failed to parse SourceMap: https://***REMOVED SENSITIVE VALUE***/apps/calendar/css/public/vendor.min.css.map
```

**Comment by zirydy** [comment]
I just discovered this bug as well. It occurs with January 2016 (wrongly displayed as "January 2015") for me as well, such that my calendar essentially has two January 2015s (January 2015 & January 2016).

Using Nextcloud 11.0.3 and Calendar App 1.5.3.

**Comment by georgehrke** [comment]
@zirydy Please provide information about the language you use.

**Comment by zirydy** [comment]
@georgehrke 
I'm using "Deutsch (Persönlich)" with the start of the week set to Monday.

**Comment by zirydy** [comment]
@georgehrke 
I just upgraded my NC instance to 11.0.4 RC1 and this issue seems to have gone away for me. Just an update.

**Comment by Nils160988** [comment]
I can also confirm this issue for Nextcloud version 12.0.3 with calendar 1.5.5 and German language.
Instead of "Januar 2017" it shows "Januar 2016", the same is true for 2016/2015, but not for January 2015 which is shown correctly.
