### ISSUE TITLE
Exceptions in recursive events are not shown correctly

### ISSUE THREAD

**Issue by strk** [nextcloud/calendar#435]
I'm having .ics files with recursive events and exceptions. Thunderbird/lightning show the exception event and not the standard one, but the nextcloud/calendar UI shows both, resulting in much confusion.

This is with calendar version 1.5.2 on nextcloud 11.0.3.

I'm not sure how Thunderbird/lightning is determining which event is an exception to which other, anyway it works fine there. And it works in Outlook, which is what generated the .ics file.

Attempts to edit the event with the UI tells that `This event's repeating rule is not supported yet.` so I guess that's part of the problem...

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/142

fix will be part of next release
