### ISSUE TITLE
Week view don't work as spected from 3.4.1 update

### ISSUE THREAD

**Issue by Carly7777** [nextcloud/calendar#4357]
### Steps to reproduce

1. Go to calendar app
2. Activate week view

### Expected behavior

If appointments overlap, the text should only appear in the appropriate appointment box

### Actual behaviour

In the case of overlapping appointments, the text is displayed outside of the appointment and overlaps

### Calendar app version

3.4.1

### Browser

Firefox, Edge, Chrome

### Client operating system

Windows 10/11

### Server operating system

Linux

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

24.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Calendar, Contacte, Picture and Talk
```

**Comment by miaulalala** [comment]
Could you update to the pre-  release (3.4.2-rc.1) and check if this still happens?

**Comment by miaulalala** [comment]
There will be a release for 3.4.2 today - it should be available to you tomorrow latest! :)
