### ISSUE TITLE
In shared calendars add support to delete only self created events

### ISSUE THREAD

**Issue by maldag** [nextcloud/calendar#436]
We have a coming up use case:
- Use a calendar to plan room occupancy.
- One account creates n-Calendars for n-Rooms

We need the following permissions:
1. The secretary can do everything with the calender (add, edit, delete)
2. Staff members can see all events, add events and _move self-created events_
3. Other users can see all events in read-only mode.

Regarding point 1 and 3 things should be possible right now to my understanding. I just don't know about point 2.

**Comment by tcitworld** [comment]
> The secretary can do everything with the calender (add, edit, delete)

Events or the calendars themselves ?

Editing and deleting an event takes the same permissions, I don't think we can do much to change it unfortunately.

**Comment by maldag** [comment]
I think the secretary should be able to add, edit, move and delete all events in the calendar and should therefore create it.

Concerning 3, is there a distinction between delete an event or delete a event that I have created? I don't know if the CalDAV Protocol offers such a thing.

**Comment by georgehrke** [comment]
> I don't know if the CalDAV Protocol offers such a thing.

Not that I'm aware of. It's possible to add access control for calendars, but not single events.

**Comment by georgehrke** [comment]
I'd vote to close this issue, because it's not possible with standard CalDAV.
Edit/Delete permissions are only given on a per calendar, not on a per event basis.
This will probably lead to plenty of unexpected results in CalDAV clients.

@tcitworld Your opinion?

**Comment by tcitworld** [comment]
Agreed.
