### ISSUE TITLE
Recurrent event : notification unclear when change date/time of only one event

### ISSUE THREAD

**Issue by francoisPE** [nextcloud/calendar#4363]
### Steps to reproduce

I have nextcloud 23.0.6, calendar 3.4.1
In parameter, email notification is checked

1. Set an recurring event, for example daily, start the 15th of july at 10:00, with several guests
2. Change event of the 17th of july : move hour of this event to 14:00
3. Notification sent to guests, mention date 15th of july, 10:00. Notification is unclear about what is modified and how it is modified

### Expected behavior

step 3. slightly different
--> Notification sent to guests, mentionning old 15th of July 10:00 and new date 17th of july, 14:00. 

### Actual behaviour

step 3 is
Notification sent to guests, mention date 15th of july, 10:00. Notification is unclear about what is modified and how it is modified

### Calendar app version

3.4.1

### CalDAV-clients used

web interface

### Browser

firefox

### Client operating system

Windows 10

### Server operating system

ubuntu 20.04

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

23.0.6

### Web server error log

```Text
NA
```

### Log file

```Text
NA
```

**Comment by ChristophWurst** [comment]
Covered by https://github.com/nextcloud/calendar/issues/3919.
