### ISSUE TITLE
Disabling "Send email" does not stop nc from sending email invitations to attendee

### ISSUE THREAD

**Issue by pboguslawski** [nextcloud/calendar#4372]
### Steps to reproduce

Create event in nc calendar UI with attendee test@example.com and (before saving such event) press "..." by the test@example.com and uncheck "Send email" checkbox there. Save event.

### Expected behavior

 After saving/updating/removing event e-mail messages should not be sent to attendees with  "Send email" option disabled.

### Actual behaviour

E-mail messages with calendar events are sent to all attendees regardless of "Send email" option state.

### Calendar app version

3.4.0

### Nextcloud version

24.0.2

**Comment by ChristophWurst** [comment]
I think there is another ticket about this but I'm unable to find it right now

**Comment by rotdrop** [comment]
There is at least a stale issue in the NC server here:  nextcloud/server#26561, right now I also did not find an issue here in the calendar app.

I think the point is a misinterpretation -- or different possible interpretations -- of the RSVP parameter for the attendees. It is documented (AFAIK) to designate the expectation of the organizer "Please reply to my invitation", but this might not automatically imply that email notifications are not sent -- it is just that the organizer does not expect replies to those notifications.

If one browses through the NC server CalDAV code then luckily there are only very few lines of code which deal with the RSVP, e.g.:

https://github.com/nextcloud/server/blob/8ee52d35b82541381d23779bdce77450311166a6/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L262-L263

and

https://github.com/nextcloud/server/blob/8ee52d35b82541381d23779bdce77450311166a6/apps/dav/lib/CalDAV/Schedule/Plugin.php#L212-L217

The first quoted lines disable the response buttons in the notification email (i.e. RSVP=FALSE receives notifications) and the second location seems to deal with responses sent by RSVP=FALSE attendees (which are ignored).

So: this is somehow a bug as the ideas about what RSVP implies seems to differ between the Nextcloud server back-end and this calendar app. So in case one accepts the RSVP handling of the NC server, then simply the label of the menu item is wrong, as it raises the expectation that the notifications to the attendees are controlled which is not the case. Instead in the server backend RSVP somehow controls whether participants are "allowed" to reply to an invitation.

Just writing this now as I was considering just now to somehow manage a list of persons absent from rehearsals and stumbled over this nice button in the front-end to then find that the NC server back end has another idea about RSVP.

So I would be happy if the menu label could be changed to "Request Confirmation" or something, meaning "Request a reply from the notified attendee".

The other possibility would be to change the behaviour of the NC CalDAV server code ;)

**Comment by rollanders** [comment]
Maybe I found a solution? In the Groupware  settings, I can deactivate Sent invitation to attendees. It seems to work.
