### ISSUE TITLE
Cannot delete one event in a multi-repeat event

### ISSUE THREAD

**Issue by unclepipsNC** [nextcloud/calendar#439]
### Steps to reproduce
1. Create an event which repeats weekly for an indefinite period
2. Pick one of the events at some date in the future and try to delete it - it deletes every event in the list, not just that one event.

### Expected behaviour
On google calendar (which I was using before migrating to NextCloud calendar), if I tried to delete an event which was part of a repeated event it would ask me whether I wanted to delete just this one event, or every event in the future or every event ever (the last option is what NextCloud calendar is doing).

### Actual behaviour
The whole event gets deleted :-( with no confirmation either!!

I am using DAVdroid on my Android phone to sync the calendar to my phone. If I delete the entry from the phone's app, I get the expected options so I selected "Delete ONLY THIS event". The event disappears on my phone's calendar :-) However, when the phone sync's to nextcloud the event doesn't get deleted, but instead a second single event is added which is "greyed out" and has a line through it, indicating it is a cancelled event.

### Server configuration

**Operating system**: NextCloud appliance for VMWare (from Tech and Me) v11.0.3 (stable)

**Web server:**NextCloud appliance for VMWare (from Tech and Me) v11.0.3 (stable)

**Database:**NextCloud appliance for VMWare (from Tech and Me) v11.0.3 (stable)

**PHP version:**NextCloud appliance for VMWare (from Tech and Me) v11.0.3 (stable)

**Server version:** (see your admin page) v11.0.3 (stable)

**Calendar version:** (see the apps page) v1.5.2

**Updated from an older installed version or fresh install:** Fresh Intall

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
No errors have been found.
```

**List of activated apps:**
Activity 2.4.1
Collaborative tags 1.1.3
Comments 1.1.0
Deleted files 1.1.0
Federation 1.1.1
File sharing 1.1.1
First run wizard 2.0
Gallery 16.0.0
Log Reader 2.0.0
Nextcloud announcements 1.0
Notifications 1.0.1
Password policy 1.1.0
PDF viewer 1.0.1
Server info 1.1.1
Share by mail 1.0.1
Text editor 2.2
Enable only for specific groups
Update notification 1.1.1
Usage survey 0.1.5
Video player 1.0.0
Calendar 1.5.2
Contacts 1.5.3
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/... no, local

**Are you using encryption:** yes/no: no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... DAVdroid

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Firefox or Chrome or Edge(lol) or IE

**Operating system:** Windows 10 Enterprise Anniversary Edition

**CalDAV-clients:**
DAVdroid

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

#### Log file from nextcloud login
Fatal	webdav	Sabre\VObject\Recur\NoInstancesException: This recurrence rule does not generate any valid instances

    /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php - line 1680: Sabre\VObject\Recur\EventIterator->__construct(Object(Sabre\VObject\Component\VCalendar), 'qmi0qm1f83uas2k...')
    /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php - line 909: OCA\DAV\CalDAV\CalDavBackend->getDenormalizedData('BEGIN VCALENDAR...')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Calendar.php - line 201: OCA\DAV\CalDAV\CalDavBackend->createCalendarObject('14', 'Nextcloud-TPXM3...', 'BEGIN VCALENDAR...')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1072: Sabre\CalDAV\Calendar->createFile('Nextcloud-TPXM3...', 'BEGIN VCALENDAR...')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('calendars/phils...', 'BEGIN VCALENDAR...', NULL)
    [internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/lib/Server.php - line 231: Sabre\DAV\Server->exec()
    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}

	2017-05-08T12:04:46+0100
Fatal	webdav	Sabre\VObject\Recur\NoInstancesException: This recurrence rule does not generate any valid instances

    /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php - line 1680: Sabre\VObject\Recur\EventIterator->__construct(Object(Sabre\VObject\Component\VCalendar), 'qmi0qm1f83uas2k...')
    /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php - line 909: OCA\DAV\CalDAV\CalDavBackend->getDenormalizedData('BEGIN VCALENDAR...')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Calendar.php - line 201: OCA\DAV\CalDAV\CalDavBackend->createCalendarObject('13', 'Nextcloud-863C1...', 'BEGIN VCALENDAR...')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1072: Sabre\CalDAV\Calendar->createFile('Nextcloud-863C1...', 'BEGIN VCALENDAR...')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('calendars/phils...', 'BEGIN VCALENDAR...', NULL)
    [internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/lib/Server.php - line 231: Sabre\DAV\Server->exec()
    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}

**Comment by georgehrke** [comment]
please use the search function before creating new bug reports ;)

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/7

**Comment by unclepipsNC** [comment]
DOH! I did look at the titles of the other 82 issues before submitting, but missed number 7 :-(  will book an appointment at Specsavers ;-)
