### ISSUE TITLE
Concurrent editing a view isn't supported by UI

### ISSUE THREAD

**Issue by sascha08-15** [nextcloud/calendar#4409]
### Steps to reproduce

1. Open your calendar in 2 separated tabs (view A and B)
2. Create an event (you can't see the event created in view A in view B)
3. Refresh the views (A and B)
4. Change the time of an appointment on B (you can't see the change in A)

### Expected behavior

The update should be immediately propagated back to the browser (Ajax or Websocket, ...)

### Actual behaviour

Any update on one view isn't shown on the other. This is especially severe when I update my calendar with my mobile device and look on an outdated view in my browser during work.

### Calendar app version

3.4.2

### Browser

Latest chrome

### Client operating system

Linux and Windows

### Server operating system

Ubuntu

### Web server

Apache

### Database engine version

MariaDB

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/31

**Comment by sascha08-15** [comment]
OK Sorry, didn't see #31
