### ISSUE TITLE
Re-Importing Ics File After Event Deletion Fails

### ISSUE THREAD

**Issue by Nesaijn** [nextcloud/calendar#4412]
### Steps to reproduce

1. Import .ics file with an event and uid entry
2. Delete the imported event
3. Import the .ics file again

### Expected behavior

The event should be imported without issues.

### Actual behaviour

It says that it could not be imported for some reason.

### Calendar app version

3.4.2

### CalDAV-clients used

Nextcloud Webclient and gnome-calendar

### Nextcloud version

 24.0.1

### Browser log

Console Log shows:

```
PUT https://cloud.foo.com/remote.php/dav/calendars/nesaijn/personal/11E6A3A7-8FCE-4C8A-BB60-CC118A383C60.ics 400 (Bad Request)
```

In the network log I found this response payload for the corresponding request:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>Deleted calendar object with uid already exists in this calendar collection.</s:message>
</d:error>
```

### Additional info

I also noticed that in a second try the URI was different:

```
/remote.php/dav/calendars/nesaijn/personal/D614A304-6539-401F-86CC-77FB0C85E454.ics
```

I am not quite sure if the last part with the .ics suffix is the randomly created UID as an attempt to work around this kind of issue but if this is the case it does not seems to work when the calendar event has an UID entry itself.

**Comment by Nesaijn** [comment]
This may be an issue related to the trash can feature?
Other than that I think issues like #2065 and #1508 could be a good approach to this problem. But the handling of the event/entry in the trashcan also needs to be regarded, if that is even part of the problem.

**Comment by r2evans** [comment]
A related issue in server https://github.com/nextcloud/server/issues/30096 was closed last year, though it is still happening. Can a dev comment please?

**Comment by r2evans** [comment]
Yes, it should be resolved. The log showed the same symptom (http `400` return), unfortunately the docker container was restarted after an update and I can't find the log entry. (Nor can I trigger it _now_, but it persisted for several deletion attempts.) When I can, I will add to this issue. (In general, the calendar has been acting a little wonky recently, unable to edit/delete some entries (https://github.com/nextcloud/server/issues/44830), unable to import others, and it is not always repeatable across multiple calendars. I'm on 28.0.4, I think the problems started in the last few months, cannot nail it down to a specific date/version.)
