### ISSUE TITLE
Date picker is not intuitive

### ISSUE THREAD

**Issue by PVince81** [nextcloud/calendar#4414]
### Steps to reproduce

1. Click "from" in an event to change it
2. Select a time
3. Now intend to change the date, we see the date at the top of the dropdown
4. Repeatedly click the date at the top and be frustrated that nothing happens
5. Click outside to close the date picker, believing that reopening it might allow to select the date
6. Reclick "from", date picker opens, time selection again. Arghh
7. Then slow down a bit and notice the barely visible "Pick date" button at the bottom, click it. Finally!

### Expected behavior

It should be intuitive/obvious how to go back to date selection.

Either clicking the date at the top should bring back date selection.
Or the "Pick date" button needs to be at the top, because hierarchically one first picks a date and then a time.

Or, the least, make the button more flashy and visible because currently it looks disabled.

### Actual behaviour

Total confusion, see steps.

This happens to me almost every time. In total probably happened 20+ times, so even though I end up finding the "Pick date" button, I still run into those loops, especially when in a rush.

<img width="160" alt="image" src="https://user-images.githubusercontent.com/277525/183375409-04eeb74b-3169-4523-87a8-e3bbb8ae2665.png">

See "Pick date" button looks disabled and is barely visible.

### Calendar app version

the one from c.nc.com

### Additional info

I'm aware that the date picker might be swapped out for accessibility reasons.

I've still raised this issue in case we do want to fix this, even minimally, with potential backports.

**Comment by PVince81** [comment]
closing as duplicate of https://github.com/nextcloud/nextcloud-vue/issues/1666

**Comment by JuliaKirschenheuter** [comment]
Accessibility ticket: https://github.com/nextcloud/nextcloud-vue/issues/1666
