### ISSUE TITLE
ENCODING=BASE64,BASE64 is not valid for this document type

### ISSUE THREAD

**Issue by IgorA100** [nextcloud/calendar#4427]
### Steps to reproduce

1. Import calendar (*.ics) with inline attachment.
2. File example: [AHD (1).zip](https://github.com/nextcloud/calendar/files/9324692/AHD.1.zip)

### Expected behavior

The import should complete successfully

### Actual behaviour

Import error, console message:

> <?xml version="1.0" encoding="utf-8"?>
> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
>   <s:exception>Sabre\DAV\Exception\UnsupportedMediaType</s:exception>
>   <s:message>Validation error in iCalendar: ENCODING=BASE64,BASE64 is not valid for this document type.</s:message>
> </d:error>

### Calendar app version

3.5.0-alpha.1 https://github.com/nextcloud/calendar/pull/4251

### Nextcloud version

24.0.3

### Additional info

I understand that a full-fledged import of inline attachments has not yet been implemented. Although RFC2445 specifies support for inline attachments https://www.ietf.org/rfc/rfc2445.txt
I really want to be able to work with inline attachments.

**Comment by tcitworld** [comment]
The issue seems to be in calendar-js or ical.js which adds an extra `ENCODING=BASE64` parameter.
