### ISSUE TITLE
Copy / Paste events

### ISSUE THREAD

**Issue by livier** [nextcloud/calendar#4437]
### Is your feature request related to a problem? Please describe.

When I have to make another date event same as another (exept date) I would like a copy paste feature in Nextcloud's UI

### Describe the solution you'd like

In the (...) menu on right, after "Exporter" et "Supprimer" there would be Copier (Cut) 
Puis dans le menu de gauche, "nouvel évènement" should have a "Coller" option

### Describe alternatives you've considered

Using thunderbird to access my calendar an there benefit from the require feature.

**Comment by ChristophWurst** [comment]
I think https://github.com/nextcloud/calendar/issues/113 will cover this requirement.
