### ISSUE TITLE
month view no longer sorted chronologically

### ISSUE THREAD

**Issue by nrgeen** [nextcloud/calendar#4443]
### Steps to reproduce

1. Update to version 3.4.3.
2. Open the month view in the calendar. Several calendars are visible.

### Expected behavior

The appointments are displayed chronologically in the respective day.

### Actual behaviour

Although the appointments are entered on the correct day and also with the correct time, the sorting is not comprehensible.

### Calendar app version

3.4.3

### Browser

Firefox 104

### Client operating system

Windows 11, Fedora 36

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

24.0.2

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by simonjones49** [comment]
Same issue on Arch with PHP8.1

**Comment by tcitworld** [comment]
Related to https://github.com/nextcloud/calendar/pull/4431 @st3iny ?

**Comment by st3iny** [comment]
Yeah, that is a regression we had to take in order to fix a more severe visibility bug. We have to wait until the bug is fixed upstream in FullCalendar until we can revert the order changes again.

**Comment by ChristophWurst** [comment]
Blocked by https://github.com/fullcalendar/fullcalendar/issues/6608. We can close the ticket once the upstream ticket is resolved, released and brought into our app.

**Comment by tgly307** [comment]
same issue

**Comment by mhazan01** [comment]
any workaround ? this is really upsetting

**Comment by st3iny** [comment]
@mhazan01 See my and Christophs comment. There is nothing we can do right now.

**Comment by mhazan01** [comment]
any way to reverse to a prior version that didn't have that bug ?

**Comment by pm-pm** [comment]
Why is there no WARNING before updating?

**Comment by dinosmm** [comment]
Is this sorted in 3.5.0? It's not mentioned in the changelog that shows in the Nextcloud app page.

**Comment by ChristophWurst** [comment]
There were no database migrations from 3.4.2 to 3.4.0 or event 3.5.0 https://github.com/nextcloud/calendar/compare/v3.4.3..v3.5.0 so you can go back to 3.4.2 if you prefer the previous state.

**Comment by moboter** [comment]
Howto revert to previous app version
(assuming that the database structure hasnt changed)
Disable Calendar App  in nextcloud
delete calendar from from nextcloud/apps/
Download previous version from
https://apps.nextcloud.com/apps/calendar/releases?platform=22#22
and extract it do nextcloud/apps/calendar
check folder permissions
aktivate calendar app

**Comment by moboter** [comment]
Also shared calendar entries are not grouped anymore

**Comment by stvhay** [comment]
during postfix install getting
```
/etc/cron.daily/mailinabox-postgrey-whitelist: line 13: file: command not found
```

**Comment by stvhay** [comment]
Install just completed. Getting an internal server error when visiting /admin. No logs on /var/log/nginx/

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by JoshData** [comment]
@stvhay You're in the wrong repository. (Apologies, this issue was linked from https://github.com/mail-in-a-box/mailinabox/pull/2083 where I think @stvhay meant to reply.)

**Comment by smoebody** [comment]
> @mhazan01 See my and Christophs comment. There is nothing we can do right now.
The mentioned bug is almost a year old and no sign of being fixed soon whatsoever. I vote for a workaround in order to fix the regression. In my opinion the impact is to severe to wait for an undisclosed time period.

**Comment by ChristophWurst** [comment]
Sure. What do you suggest as a workaround?

**Comment by smoebody** [comment]
From what I understand the issue related to #4431 the missing events only effect the week view. How about applying the `eventOrder` change from #4431 only in week view?

**Comment by ChristophWurst** [comment]
That sounds worth a test!

**Comment by ximex** [comment]
have the same problem
![grafik](https://user-images.githubusercontent.com/1078640/190627477-2d460d27-db65-4c5c-8f58-5c05e9fa4f44.png)

**Comment by moboter** [comment]
> Is there a version where the workaround can be tested I could install ? When delete Calendar from apps and untar this [version](https://github.com/nextcloud-releases/calendar/releases/download/v3.4.2/calendar-v3.4.2.tar.gz), going to the calendar page shows an upgrade page instead. For sure, once the upgrade is finished, my downgrade is reversed.

Im Running 3.4.2 dont forget to check folder permissions.

**Comment by kb8cb40j1av39c02** [comment]
Like a month later and this is sadly still an issue. Luckily was able to downgrade my calendar to V3.4.2 and it's fixed now.
Are there plans already to fix the sorting in the latest version of calendar for nextcloud?

**Comment by dinosmm** [comment]
Yay, thank you so much for fixing this!
Will this be available in 3.5.x or will it only be on 4.0.0 (which I assume means we have to wait for NC 25)?

**Comment by tcitworld** [comment]
This has been backported to 4.0.1 (already released) and 3.5.x (not yet released).

**Comment by st3iny** [comment]
Keep in mind that we didn't fix the issue. We just applied the workaround proposed by @smoebody. 

We have still have to wait for a proper upstream fix in FC to be able to fully revert my changes.

**Comment by mhazan01** [comment]
Thank you very much for implementing the workaround and updating the app.
