### ISSUE TITLE
ACPu no longer supported when updating from Calendar 3.4.3 to 3.5.0?

### ISSUE THREAD

**Issue by creopard** [nextcloud/calendar#4454]
### Steps to reproduce

1. Update from Calendar 3.4.3 to 3.5.0 with ACPu enabled
2. Nexcloud will stop the upgrade and switch to "maintenance mode"
3. trying to upgrade in the shell via `php occ upgrade` will show the following log:
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Updating <calendar> ...
/opt/cpanel/ea-php73/root/usr/bin/php: 
symbol lookup error: /opt/alt/php80/usr/lib64/php/modules/apcu.so: undefined symbol: pcre2_match_data_create_from_pattern_8
```
4.  Disabling ACPu in "config.php" via  `//'memcache.local' => '\\OC\\Memcache\\APCu',` will make it possible to perform the upgrade successfully and to disable the "maintenance mode"
5. Enable ACPu again in "config.php" again and everything should be fine...
6. However, when opening https://domain.com/index.php/settings/admin in the browser, Nextcloud immediately switches to the  "maintenance mode" again until I disable ACPu again in "config.php"

### Expected behavior

Calendar 3.5.0 should work with ACPu enabled

### Actual behaviour

see "Steps to reproduce"

### Calendar app version

3.5.0

### CalDAV-clients used

not relevant

### Browser

Firefox 103

### Client operating system

Windows 10

### Server operating system

CloudLinux

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

24.0.4

### List of activated apps

```Text
- accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.5.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_downloadactivity: 1.13.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - passwords: 2022.8.20
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - circles: 23.0.0
  - encryption
  - federation: 1.13.0
  - files_external
  - files_pdfviewer: 2.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - user_ldap
  - user_status: 1.3.1
  - weather_status: 1.0.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "installed": true,
        "default_phone_region": "DE",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "10,30",
        "versions_retention_obligation": "10,30",
        "loglevel": 0,
        "cron_log": true,
        "log_rotate_size": 5242880,
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "maintenance": false,
        "theme": "",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "allowNightlyUpdates": [],
        "mail_sendmailmode": "smtp",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "bruteforcesettings"
        ]
    }
}
```

### Web server error log

Nothing

### Log file

Nothing helpful found

### Browser log

Nothing helpful found

### Additional info

The only workaround is to downgrade to Calendar 3.4.3

**Comment by ChristophWurst** [comment]
> ### PHP engine version
> 
> PHP 8.0

Would be good to know the specific version. Have you checked if your "CloudLinux" distro offers a php update?

**Comment by tcitworld** [comment]
Hi,
You've noticed the issue by upgrading the app but it's just a symptom. The issue is with your PHP system installation.
```
symbol lookup error: /opt/alt/php80/usr/lib64/php/modules/apcu.so: undefined symbol: pcre2_match_data_create_from_pattern_8
```

If you installed apcu from PECL, I'd try upgrading it.

**Comment by creopard** [comment]
Unfortunately it's a shared hosting envrionment, so I guess I'll need to reach out to the sysadmins.

However, I'm wondering what (breaking?) changes took place in v3.5.0 that this error did not occur in v3.4.3.

**Comment by ChristophWurst** [comment]
None

**Comment by tcitworld** [comment]
I think the upgrade process just makes use of apcu at some point and that's why you have the output, but otherwise upgrading from 3.4.2 would probably have done the same thing with your current environment.

**Comment by creopard** [comment]
@ChristophWurst I'd like to add my workaround for future reference or other users experiencing that issue:

1. comment the line `'memcache.local' => '\\OC\\Memcache\\APCu',` in "config.php", so APCu is disabled
2. make sure the Nextcloud instance "complains" about the unset _PHP Memor Cache_ in "settings/admin"
3. downgrade from Calendar v3.5.0 to v3.4.3
4. reinstall Calendar v3.5.0
5. uncomment the line `'memcache.local' => '\\OC\\Memcache\\APCu',` in "config.php", i.e. enable APCu again
6. success: this procedure seems to circumvent the installation issue as hinted by @tcitworld and the Nextcloud instance won't suddenly switch to "maintenance mode" anymore when opening the "https://domain.com/index.php/settings/admin" with the browser.
