### ISSUE TITLE
Email sent when appointment is used

### ISSUE THREAD

**Issue by Ecphrasis** [nextcloud/calendar#4456]
### Is your feature request related to a problem? Please describe.

When someone makes an appointment with the link, the owner doesn't know anything, he have to check the calendar. So he can miss the appointment.

### Describe the solution you'd like

When someone creates a appointment, a mail is sent to the owner of the calendar when the appointment is confirmed for example.

**Comment by nickian** [comment]
I agree. I am not sure how this was overlooked. It's 100% necessary to send an email confirmation to both the person who owns the calendar and to the person requesting a meeting.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/3630. This was not overlooked.
