### ISSUE TITLE
Calendar does not even Open, instead showing errorscreen

### ISSUE THREAD

**Issue by L00tz1ffer** [nextcloud/calendar#4457]
### Steps to reproduce

1. Install fresh Owncloud instance
2. open Calendar

### Expected behavior

On Click on the Calendar button in the top left cornor Calendar should open...

### Actual behaviour

> Interner Serverfehler
>Der Server konnte die Anfrage nicht fertig stellen.
>
>Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an deinen Server-Administrator.
>
>Weitere Details können im Server-Protokoll gefunden werden.
>
>Technische Details
>Entfernte Adresse: 2003:e6:170b:3f89:417a:e3a9:f11e:4315
>Anfragekennung: YxH9GTt1ssFxo289_jbM-QAADFM

![Screenshot 2022-09-02 150517](https://user-images.githubusercontent.com/88904868/188152190-4553a07f-11b9-4c5e-b2a0-85d254b6d635.png)

### Browser

Chrome

### Client operating system

Windows 10

### Server operating system

I dont know which System Strato uses - i guess Ubuntu

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

24

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
no admin privileges available on strato webspace
```

### Nextcloud configuration

```Text
no admin privileges available on strato webspace
```

### Web server error log

```Text
log not available on strato
```

### Log file

```Text
Errorlog: 

> OCP\AppFramework\QueryException: Could not resolve OCA\Calendar\Controller\ViewController! Class "OCA\Calendar\Controller\ViewController" does not exist
/mnt/web201/e0/05/511953205/htdocs/lootziffers-welt/nc/lib/private/AppFramework/Utility/SimpleContainer.php - line 133:

OC\AppFramework\Utility\SimpleContainer->resolve()

/mnt/web201/e0/05/511953205/htdocs/lootziffers-welt/nc/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465:

OC\AppFramework\Utility\SimpleContainer->query()

/mnt/web201/e0/05/511953205/htdocs/lootziffers-welt/nc/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 437:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/mnt/web201/e0/05/511953205/htdocs/lootziffers-welt/nc/lib/private/AppFramework/App.php - line 159:

OC\AppFramework\DependencyInjection\DIContainer->query()

/mnt/web201/e0/05/511953205/htdocs/lootziffers-welt/nc/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main()

/mnt/web201/e0/05/511953205/htdocs/lootziffers-welt/nc/lib/base.php - line 1023:

OC\Route\Router->match()

/mnt/web201/e0/05/511953205/htdocs/lootziffers-welt/nc/index.php - line 36:

OC::handleRequest()
```

**Comment by tcitworld** [comment]
The upgrade seems to have failed, files seems to me missing from your install. If going to the app management section still works, remove the app and reinstall it.

**Comment by L00tz1ffer** [comment]
Reinstall Done - Errors Gone
