### ISSUE TITLE
Focus feedback of time zone button is too large

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#4461]
### Steps to reproduce

1. Create a new event
2. Use tab to focus the timezone switcher in one of the date fields

### Expected behavior

The focus feedback does not extend far out of the containing input field.

### Actual behaviour

![image](https://user-images.githubusercontent.com/925062/188447887-0d2055e1-af67-45cc-80d7-0fd75e756cd9.png)

### Calendar app version

Current on tech-preview, 3.5.0, but already happened before

**Comment by JuliaKirschenheuter** [comment]
@jancborchardt can you reproduce it for current master branch?

![image](https://user-images.githubusercontent.com/6078378/194526544-22e3a2b1-d509-4c1e-9c8e-1b629a974231.png)
