### ISSUE TITLE
Contact pictures wonn´t show up

### ISSUE THREAD

**Issue by WeT-Klb** [nextcloud/calendar#447]
When i add a new contact in Nextcloud 11 contacts app and try to attach a picture it won´t show up.
I am told the Picture is too big if it it more than 1MB - but when i use a smaller one 240x240 less than 1MB it won´t appear.
Weired Thing is the same Picture in contacts app on Owncloud 8.2.11 works perfektly.

### Server configuration
**Operating system**: Linux Qnap-TS251 4.2.8 #1 SMP Wed May 3 01:11:54 CST 2017 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 5.5.51

**PHP version:** 5.6.30
Modules loaded: Core, date, ereg, libxml, pcre, ctype, dom, fileinfo, filter, hash, json, SPL, openssl, posix, Reflection, SimpleXML, session, tokenizer, xml, xmlreader, xmlwriter, cgi-fcgi, imagick, zlib, curl, calendar, iconv, gd, standard, PDO, sqlite3, mysqlnd, pdo_mysql, pdo_sqlite, mysql, mysqli, Phar, zip, bcmath, dba, mbstring, ftp, gettext, imap, ldap, exif, mcrypt, pcntl, shmop, soap, sockets, wddx, xmlrpc, xsl, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:** 
From Qnap-Forum (http://www.qoolbox.fr/NextCloud_11.0.3.qpkg.zip)

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
  - activity: 2.4.1
 - calendar: 1.5.2
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - weather: 1.4.1
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_external
 - files_retention
 - templateeditor
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ockhacm3wrjl",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.241",
        "wet-klb.dyndns.org"
    ],
    "datadirectory": "\/share\/CACHEDEV1_DATA\/.qpkg\/NextCloud\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/192.168.1.241:90\/nextcloud",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "Nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "maintenance": false,
    "updater.release.channel": "stable",
    "mail_smtpmode": "php",
    "mail_smtpauth": 1,
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "securesmtp@t-online.de",
    "mail_smtpport": "567"
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

**Operating system:**
Windows 7 Ultimate 64bit

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by georgehrke** [comment]
Wrong repo, this is calendar ;)
