### ISSUE TITLE
ICS export doesn't contain DESCRIPTION for VALARM

### ISSUE THREAD

**Issue by hackbaellchen** [nextcloud/calendar#4490]
### Steps to reproduce

1. Create an event in a calendar using the browser and add a reminder (if not added automatically)
2. Export calendar to `.ics` (in my case by sharing an export link)

### Expected behavior

The `VALARM`-field should have an editable or default (Google calendar uses "This is an event reminder") `DESCRIPTION`-field.

### Actual behaviour

Generated event reminders `VALARM` are missing the `DESCRIPTION`-field, which is mandatory according to [RFC5545](https://www.rfc-editor.org/rfc/rfc5545#section-3.6.6).

### Calendar app version

3.5.0

### Browser

Firefox 104.0.2

### Client operating system

Windows 10 21H2

### Server operating system

Debian 11

### Nextcloud version

24.0.4, docker image nextcloud:24.0.4-apache

### Updated from an older installed version or fresh install

Updated from an older version

### Additional info

I am using the python library [ics](https://pypi.org/project/ics/) to parse the exported calendar from nextcloud. When loading, `ValueError: A VALARM must have at least one DESCRIPTION` is thrown.

**Comment by rscmbbng** [comment]
Can reproduce with `ics>=0.7,<0.8` and `Calendar 3.4.2`

**Comment by tcitworld** [comment]
It should just be about adding the description property in these two places:
https://github.com/nextcloud/calendar-js/blob/c15736727eae56844b3c966ed4ae6a7f49eab042/src/components/root/abstractRecurringComponent.js#L769-L772
https://github.com/nextcloud/calendar-js/blob/c15736727eae56844b3c966ed4ae6a7f49eab042/src/components/root/abstractRecurringComponent.js#L786-L790

Apparently when the action is `AUDIO` the `DESCRIPTION` isn't required, so we need handling here (even though we don't support that in Calendar itself - yet?).

Also I wonder if we correctly add `SUMMARY` when action is `EMAIL` as well. :thinking:

**Comment by miaulalala** [comment]
> It should just be about adding the description property in these two places: https://github.com/nextcloud/calendar-js/blob/c15736727eae56844b3c966ed4ae6a7f49eab042/src/components/root/abstractRecurringComponent.js#L769-L772 https://github.com/nextcloud/calendar-js/blob/c15736727eae56844b3c966ed4ae6a7f49eab042/src/components/root/abstractRecurringComponent.js#L786-L790
> 
> Apparently when the action is `AUDIO` the `DESCRIPTION` isn't required, so we need handling here (even though we don't support that in Calendar itself - yet?).
> 
> Also I wonder if we correctly add `SUMMARY` when action is `EMAIL` as well. 🤔

Bless you for this Thomas, I was looking for the export function 😅

**Comment by JulienPalard** [comment]
Can reproduce with calendar 3.5.2 (on framagenda.org instance).

**Comment by tcitworld** [comment]
Will be fixed by #4683

**Comment by st3iny** [comment]
Fixed by https://github.com/nextcloud/calendar/pull/4683.
