### ISSUE TITLE
Attendee-Autocomplete: show e-mail address behind name

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#45]
cc @schiessle

**Comment by georgehrke** [comment]
otherwise a user is not able to distinguish which email address is used.

**Comment by tcitworld** [comment]
With long names much of the space is already taken. I guess you mean below the name.

**Comment by tcitworld** [comment]
Unfortunately the files_sharing ShareesAPI only gives us the name of the user. Therefore we have to reimplement `ShareesAPI#search`

**Comment by georgehrke** [comment]
Sorry, should have added a proper description 🙈 
This is not about the sharing dialog, but about the autocompletion for attendees in the events editor sidebar on the right.

**Comment by tcitworld** [comment]
Nope, my mistake, didn't read the title enough. :see_no_evil:

**Comment by tcitworld** [comment]
However I guess the sharing dialog has the same issue.

**Comment by georgehrke** [comment]
Hm, I don't think so.
The sharing dialog only returns one item for each user.

In the sidebar we read the attendee information straight grin the user's address book. Therefore one attendee (aka one contact in the address book) can have multiple email addresses
