### ISSUE TITLE
CWeeks are shown wrong

### ISSUE THREAD

**Issue by GretaD** [nextcloud/calendar#4507]
### Steps to reproduce

1. Open Calendar and go to Calendar settings
2. Check the option "show week numbers"
3. Look at the days on the calendar header

### Expected behavior

The week has the right week days

### Actual behaviour

Wrong week days are shown

### Additional info

The first day of 37th week is September 12 and ends on September 18.
on our app is: 
<img width="1021" alt="Screen Shot 2022-09-12 at 10 49 18 AM (2)" src="https://user-images.githubusercontent.com/12728974/189694227-0477a66b-637f-4fba-9ef4-abc519da70d3.png">

**Comment by ChristophWurst** [comment]
without nextcloud or app version it's gonna be hard to reproduce

**Comment by tcitworld** [comment]
Duplicate from #4318, #3032 ?
