### ISSUE TITLE
Birthday Calender show age not year of birth

### ISSUE THREAD

**Issue by raffisweb** [nextcloud/calendar#4509]
### Is your feature request related to a problem? Please describe.

Birthday Calender automatically shows birthday dates of related contacts and after the name it shows the year of birth, e.g. Rafael (1984).

### Describe the solution you'd like

Would be nice to see the age of a person instead of having to calculate it from the year of birth.

### Describe alternatives you've considered

Showing both or choosing between year and age would be great.

### Additional context

Other calender apps do this already

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/940
