### ISSUE TITLE
Undefined index: defaultColor at /var/www/html/apps/calendar/templates/part.fullcalendar.php#28	

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/calendar#451]
Undefined index: defaultColor at /var/www/html/apps/calendar/templates/part.fullcalendar.php#28	 

on c.nc.c, it seems to be triggered when opening a public calendar.

cc @georgehrke

**Comment by georgehrke** [comment]
Can't reproduce with latest master anymore, hence will be fixed with the upcoming 1.5.3

**Comment by georgehrke** [comment]
defaultColor is included in all templates since https://github.com/nextcloud/calendar/pull/372/files#diff-b143e1db4ce6ee8d3c38bca02fbb4d5dR201
