### ISSUE TITLE
Inconsistent, incorrect and missing information in the appointment booking (client side)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/calendar#4512]
### Steps to reproduce

1. Set up an appointment, without needing to touch the advanced settings. Just enter the surname, location and description. 
2. Test the appointment booking by filling in all the fields after choosing a date and a time slot. Then click on "Book the appointment" to receive an e-mail requesting confirmation of your booking.

### Here are your appointment settings : 
![2022-09-13_13-59](https://user-images.githubusercontent.com/33763786/189897659-acd327e1-03bd-4b6d-911d-2ca8dc22a826.png)
**The problem :** No problem here

### Here is the booking popup (missing information) : 
![2022-09-13_13-57](https://user-images.githubusercontent.com/33763786/189897819-25b08562-21af-4939-b541-d4a610cf36cd.png)
**The problems :**
- Date is missing (once in the popup, we don't know or can't easily remember what date we have selected)
- Location (Red bubble n°2 in the previous screenshot) is missing. I think it is important and consistent to have all the information about the appointment. The location is an important part of the information, as is the title, for example. By the way, this information does belong in the e-mail afterwards but I think it should also appear here.

### Here is the e-mail requesting confirmation of your booking (wrong information) : 
![2022-09-13_14-02](https://user-images.githubusercontent.com/33763786/189898728-ac4e26df-71b1-4e8e-8f66-576b15666229.png)
**The problems :**
- The "John Doe" information (Green bubble n°1 of the 2nd screenshot) is wrong. "Partner meeting" should appear instead (Red bubble n°1 of the first screenshot) 
- The "Bla bla bla bla bla !" information (Green bubble n°3 of the second screenshot) is wrong. "Lorem ipsum dolor sit amet ..." should appear instead (Red bubble n°3 of the first screenshot) 

### Last problem (UX) :
![2022-09-13_14-28_1](https://user-images.githubusercontent.com/33763786/189901107-078d1954-1208-49b1-b119-7d27f62e2a83.png)
- IMO, this confirmation screen should be in the colors of the instance (color, logo and background image of the instance theme)
- The customer should receive a final booking confirmation email; this is not the case, and is a little confusing... and some people may rightly believe that the booking is not properly validated. The email should contain again all the information that was already in the confirmation request email (taking into account my comments above)... and also the message and link that you have on the confirmation screen (browser) : 
```
Thank you. Your booking from September 13, 2022 3:30 PM to September 13, 2022 3:35 PM has been confirmed.
Book another appointment:
See all available slots
```

### Expected behavior

Everything is listed in "Steps to reproduce".

### Actual behaviour

Everything is listed in "Steps to reproduce".

### Calendar app version

3.5.0

### CalDAV-clients used

DAXx5, Thunderbird Lightning ...

### Browser

Firefox 104

### Client operating system

Ubuntu Desktop 20.04 LTS

### Server operating system

Centos

### Web server

nginx/1.23.1 (fpm-fcgi)

### Database engine version

mysql 10.4.22

### PHP engine version

8.0.19

### Nextcloud version

24.0.5

### Updated from an older installed version or fresh install

Update from an older installed version

### List of activated apps

```
Enabled:
 - accessibility: 1.10.0
 - activity: 2.16.0
 - apporder: 0.15.0
 - calendar: 3.5.0
 - carnet: 0.24.5
 - circles: 24.0.1
 - cloud_federation_api: 1.7.0
 - collectives: 1.5.0
 - comments: 1.14.0
 - contacts: 4.2.0
 - contactsinteraction: 1.5.0
 - dashboard: 7.4.0
 - dav: 1.22.0
 - deck: 1.7.1
 - duplicatefinder: 0.0.15
 - extract: 1.3.5
 - federatedfilesharing: 1.14.0
 - federation: 1.14.0
 - files: 1.19.0
 - files_accesscontrol: 1.14.1
 - files_lock: 24.0.1
 - files_mindmap: 0.0.26
 - files_pdfviewer: 2.5.0
 - files_rightclick: 1.3.0
 - files_sharing: 1.16.2
 - files_trashbin: 1.14.0
 - files_versions: 1.17.0
 - files_videoplayer: 1.13.0
 - files_zip: 1.1.2
 - firstrunwizard: 2.13.0
 - forms: 2.5.1
 - groupfolders: 12.0.1
 - guests: 2.2.0
 - impersonate: 1.11.0
 - logreader: 2.9.0
 - lookup_server_connector: 1.12.0
 - mail: 1.13.8
 - nextcloud_announcements: 1.13.0
 - notes: 4.5.1
 - notifications: 2.12.1
 - oauth2: 1.12.0
 - password_policy: 1.14.0
 - photos: 1.6.0
 - polls: 3.7.0
 - privacy: 1.8.0
 - provisioning_api: 1.14.0
 - quicknotes: 0.8.1
 - recommendations: 1.3.0
 - richdocuments: 6.2.0
 - serverinfo: 1.14.0
 - settings: 1.6.0
 - sharebymail: 1.14.0
 - spreed: 14.0.4
 - support: 1.7.0
 - survey_client: 1.12.0
 - systemtags: 1.14.0
 - text: 3.5.1
 - theming: 1.15.0
 - theming_customcss: 1.11.0
 - twofactor_backupcodes: 1.13.0
 - updatenotification: 1.14.0
 - user_ldap: 1.14.1
 - user_migration: 1.1.0
 - user_retention: 1.7.0
 - user_status: 1.4.0
 - viewer: 1.8.0
 - weather_status: 1.4.0
 - workflowengine: 2.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - sharerenamer: 3.0.1
 - workspace: 1.2.2
```

### Nextcloud configuration

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc24.test.mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "24.0.5.1",
    "overwrite.cli.url": "https:\/\/nc24.test.mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nc24.test.mydomain.fr\/nextcloud.log",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 8,
        "timeout": 0
    },
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "skeletondirectory": "",
    "logtimezone": "Europe\/Paris",
    "updater.release.channel": "stable",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "default_language": "fr",
    "default_phone_region": "FR",
    "defaultapp": "files",
    "trashbin_retention_obligation": "20,40",
    "versions_retention_obligation": "auto,40",
    "check_for_working_wellknown_setup": false,
    "quota_include_external_storage": false,
    "cron_log": true,
    "has_internet_connection": true,
    "updatechecker": true,
    "appstoreenabled": true,
    "filelocking.enabled": true,
    "session_keepalive": true,
    "knowledgebaseenabled": true,
    "allow_user_to_change_display_name": true,
    "enable_previews": true,
    "enable_avatars": true,
    "auth.bruteforce.protection.enabled": true,
    "loglevel": 0,
    "log_rotate_size": 104857600,
    "mail_smtpauth": 1,
    "mail_smtpport": 465,
    "session_lifetime": 86400,
    "remember_login_cookie_lifetime": 1296000,
    "preview_max_filesize_image": 50,
    "activity_expire_days": 120,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "maintenance": false,
    "sharing.enable_mail_link_password_expiration": true,
    "sharing.mail_link_password_expiration_interval": 3600,
    "has_rebuilt_cache": true,
    "app_install_overwrite": [
        "workspace",
        "groupfolders"
    ]
}
```

### Web server error log

Can be provided if necessary.

### Log file

Can be provided if necessary.

### Browser log

Can be provided if necessary.

**Comment by Jerome-Herbinet** [comment]
Thanks for applying the tags @ChristophWurst; since you did it, I've added and updated some information to make this issue more intelligible.

**Comment by miaulalala** [comment]
The last issue (additional confirmation email) has been partly solved. We now send an additional email.

I agree about the location. And I think the description and so on should also be added. the question is where. VEVENTs have one DESCRIPTION and one SUMMARY property each. COMMENT is not supported by our backend at the moment. I will think about this some more.

The templating is also an issue I agree with, it should not use the NC background / Logo but whatever is set in the instance.

**Comment by pjrobertson** [comment]
I think the issues here are fixed and working in NC 26 and the latest calendar app so I think this can be closed.

Here's what an email looks like now:



<img width="537" alt="Screen Region 2023-05-27 at 10 46 20" src="https://github.com/nextcloud/calendar/assets/150431/b81c5d71-5875-4425-8c5a-828d0128b59b">


I would say it's a bit overwhelming/too much information but the issues here are fixed at least.

**Comment by Jerome-Herbinet** [comment]
Thanks, @pjrobertson, for the test ; I also notice that all labels finally fit with fields content. 
I agree with you about perhaps too much information, or the presentation of information should be improved, but this could be discussed in another issues (and PR) :-)

**Comment by Jerome-Herbinet** [comment]
I think that this issue can be closed (I made some new successful tests with Nextcloud 29).
