### ISSUE TITLE
Improve "New calendar" button

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#4525]
### Is your feature request related to a problem? Please describe.

The "New calendar" button is inconsistent with the general design of Nextcloud.

### Describe the solution you'd like

Remove the plus from the text and the plus icon from the right side. Instead, add a plus icon to the left side.

![new-calendar-redesign](https://user-images.githubusercontent.com/1479486/191469730-9a42c9f4-2201-4cc6-89d6-83baf6b902d2.png)

**Comment by szaimen** [comment]
See https://github.com/nextcloud/calendar/pull/4082

**Comment by st3iny** [comment]
Fixed by #4539
