### ISSUE TITLE
Duplicated events don't get synced properly

### ISSUE THREAD

**Issue by devNan0** [nextcloud/calendar#4538]
### Steps to reproduce

1.Create a event via WebUI or any CalDav client
2.Duplicate that event via the WebUI

### Expected behavior

Duplicated event to be synced properly via CalDav

### Actual behaviour

Duplicated event doesn't get synced properly via CalDav

But if i do this in the WebUI:
- Set "Show as" on the duplicated event to "Free"
- Hit Update
- Set "Show as" on the duplicated event back to "Busy"
- Hit Update

The event appears on my android

### Calendar app version

3.5.0

### CalDAV-clients used

DAVx5

### Browser

91.13.0esr (64-bit)

### Client operating system

Debian Bullseye / Andoird 11

### Server operating system

Debian Bullseye (Nextcloud runs in Docker)

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

24.0.5

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by max65482** [comment]
Same issue for Thunderbird.
Interestingly, re-subscribing to the calendar is a workaround here.

**Comment by max65482** [comment]
Observation: I can only reproduce the issue with calendars that aren't my first calendar in the list. Duplicating works fine with the first calendar.
