### ISSUE TITLE
Appointment confirmation page background

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#4545]
### Steps to reproduce

1. Create an appointment config
2. Open the booking page
3. Book a slot
4. Click the confirmation link in the email

### Expected behavior

A nice page

### Actual behaviour

![Bildschirmfoto vom 2022-09-23 18-59-18](https://user-images.githubusercontent.com/1374172/192013953-8e1a11df-d3a7-4c0a-9a6a-81e8086eb118.png)

### Calendar app version

v4

**Comment by JuliaKirschenheuter** [comment]
![image](https://user-images.githubusercontent.com/6078378/193548019-8575d4e7-1466-4fa2-9c58-017992a3faa1.png)

What are you thinking about this alternative?

**Comment by ChristophWurst** [comment]
Looks good :+1:
