### ISSUE TITLE
[HELP] How do i integrate the nextcloud calendar to thunderbird?

### ISSUE THREAD

**Issue by JunkyardCat** [nextcloud/calendar#455]
im currently using thunderbird in windows and using the lightning addon but whenever i synch it gives me error (the calendar Personal is momentarily not available)

**Comment by georgehrke** [comment]
Please use https://help.nextcloud.com for general questions

**Comment by georgehrke** [comment]
There is a dedicated subforum for the calendar: https://help.nextcloud.com/c/apps/calendar
