### ISSUE TITLE
Multiselect looks strange in some cases on NC25, latest RC

### ISSUE THREAD

**Issue by szaimen** [nextcloud/calendar#4550]
### Steps to reproduce

Install latest RC on NC25

### Expected behavior

it should look great

### Actual behaviour

it doesnt

See 
![image](https://user-images.githubusercontent.com/42591237/192360285-2548cae7-20f3-4dcd-9ccd-d5b8c195a566.png)
and 
![image](https://user-images.githubusercontent.com/42591237/192360333-26a82692-42be-4882-acec-8c0bf3c1fccf.png)

**Comment by ChristophWurst** [comment]
Please report this in \@nextcloud/vue

**Comment by szaimen** [comment]
but if this is really a vue isssue, why does it look good in the sidebar?
![image](https://user-images.githubusercontent.com/42591237/192476600-801e888c-bfb8-471b-9a06-243241f2cfae.png)

**Comment by ChristophWurst** [comment]
I don't know.

**Comment by szaimen** [comment]
Maybe @st3iny has an idea? :)

**Comment by st3iny** [comment]
Ahhh, the usual Multiselect breakage. I'll take a look.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/3252 related?
