### ISSUE TITLE
Permissions on shared calendars

### ISSUE THREAD

**Issue by GPMueller** [nextcloud/calendar#456]
The "can edit" permissions give users/groups permission to edit others' permissions. Sharing a calendar (esp. with a group) is thus impractical as anyone can remove the group's (and/or their own...) permission to add dates etc. (also by accident).

My suggestion would be to **give a lower level of permissions by default** to "can edit" (i.e. editing dates etc., but not permissions) and (if needed) add one more item to the `...` menu, e.g. "Share Permissions".

As a side note: in my opinion the following permission levels would be practical
- can edit and delete anything inside and also the whole calendar
- can edit permissions and anyone's dates etc.
- can add dates and edit their own
- can only view

**Comment by georgehrke** [comment]
The behavior will change with Nextcloud 12. Only the owner will be able to change the sharing settings.
