### ISSUE TITLE
No sorting (month/list)

### ISSUE THREAD

**Issue by SebastianBerlin** [nextcloud/calendar#4565]
### Steps to reproduce

1. open calendar
2. open day grid month or list

### Expected behavior

chronological sorting

### Actual behaviour

non-chronological sorting
![sorting](https://user-images.githubusercontent.com/7254827/193229511-9fe9bd53-74c9-460e-9e1e-03e47b6523ae.png)

### Calendar app version

newest (and at least for a couple of months)

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

newest

### Additional info

I don't see any option to set up the sorting, so it has to be a bug, right?

**Comment by tcitworld** [comment]
Duplicate from #4443
