### ISSUE TITLE
clicking the add new calendar button and moving the mouse out of the modal makes the modal jump at the top left corner of the window

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/calendar#4574]
### Steps to reproduce

1. Go to calendar view
2. click add new calendar
3. a modal appears
4. move the mouse out of the modal
5. the modal jumps to the left top corner, half hidden behind the app ribbon.

![image](https://user-images.githubusercontent.com/87175513/193548789-0c830f6f-1a18-4033-9160-ebdee93123d5.png)

### Expected behavior

modal stays where it is

### Actual behaviour

modal jumps

### Browser

firefox last version

### Nextcloud configuration

```Text
c.nc.c
```

**Comment by st3iny** [comment]
I can reproduce this bug by opening the actions menu by clicking on the list entry. If I click on the three dot menu (on the right), it works fine.

**Comment by st3iny** [comment]
Will be fixed by the next nextcloud-vue bump.
