### ISSUE TITLE
After an appointment is settled, the requester does not receive any calendar invitation.

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/calendar#4578]
### Is your feature request related to a problem? Please describe.

Vocabulary:
Bob - external, the requester for the appointment
Maria - the calendar owner (organizer)

Appointment does book a calendar slot in the owner's calendar (Maria).
BUT does NOT send ANY calendar invitation to the person requesting the appointment.

Even after the appointment is booked, if Maria wants to change the title and the location for an online meeting, changes are not communicated to Bob the requester.

The requester only receives an invitation if the time schedule of the slot changes (which makes no sense 🙃)

This is really confusing for the requester, as this gives the impression that the confirmation didn't work.

I am using that feature with customers, and they constantly come back to me unsure about if the meeting has been scheduled or not.

### Describe the solution you'd like

As soon as the appointment is confirmed by the requester, a calendar invitation should be sent BOTH to the calendar owner (Maria) and to the requester (Bob).

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/calendar/issues/3855
