### ISSUE TITLE
Calender entries not sorted by date

### ISSUE THREAD

**Issue by cnoelker** [nextcloud/calendar#4588]
### Steps to reproduce

1.Create two or more appointments on the same date
2.Check on the Month view: They are not sorted
3.

### Expected behavior

Appointments should be display in chronologic order

### Actual behaviour

The last date seems to be at first position

### Calendar app version

3.5.0

### Browser

Firefox

### Server operating system

Ubuntu

### Web server

Apache

### Nextcloud version

23.0.10

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/4443
