### ISSUE TITLE
Simple event editor has unusable date picker

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#4589]
### Steps to reproduce

1. Click into your calendar grid to create an event
2. Pick start/end time

### Expected behavior

I can pick and confirm with *Ok*

### Actual behaviour

![Bildschirmfoto vom 2022-10-10 09-34-46](https://user-images.githubusercontent.com/1374172/194819096-b6bbe649-9770-4c63-9cdb-9c92fca450d6.png)

### Calendar app version

4.0

**Comment by ChristophWurst** [comment]
Okay, good enough. Guess our internal instance doesn't ship that fix yet.

**Comment by ChristophWurst** [comment]
We have higher priority tasks at the moment, as discussed.

**Comment by JuliaKirschenheuter** [comment]
Further work should be done  here https://github.com/nextcloud/calendar/issues/4626

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/4532, fixed with https://github.com/nextcloud/calendar/pull/4537
