### ISSUE TITLE
"New Calendar" cretation modal jumps to top left corner

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#4612]
### Steps to reproduce

1. Go to calendar
2. Click on "New Calendar" option
3. Choose any of the three options
4. The popup / modal that gets triggered is rendered in the left topmost corner:

![image](https://user-images.githubusercontent.com/7427347/195603172-9b4a4dfe-dfb8-4fdf-9a69-f449faf39eb1.png)

### Expected behavior

The calendar creation modal replaces the three options modal

### Actual behaviour

The new modal gets rendered in the left top corner.

### Calendar app version

v4.0.0-rc.1

### CalDAV-clients used

Web

### Browser

Chrome

### Client operating system

c.nc

**Comment by miaulalala** [comment]
Duplicate

**Comment by ChristophWurst** [comment]
duplicate of?

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/4574
