### ISSUE TITLE
Appointments moible view is cutting of information

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#4614]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/7427347/195604005-564cbf28-7a0a-4075-a4c1-c7f440f802e0.png)

### Expected behavior

Full screen modal, content is ordered one below the other
cc @nextcloud/designers 

### Actual behaviour

Content doesn't adjust to screen width

### Calendar app version

v4.0.0-rc.1

### CalDAV-clients used

Web

### Browser

Chrome

### Client operating system

Ubuntu

### Server operating system

c.nc

**Comment by ChristophWurst** [comment]
tlc?

**Comment by miaulalala** [comment]
tender loving care
