### ISSUE TITLE
SSL/TLS secure link

### ISSUE THREAD

**Issue by Nicoprogrammeur** [nextcloud/calendar#4623]
### Is your feature request related to a problem? Please describe.

I would like to synchronize my Zimbra calendar in Nextcloud Calendar.
We can't integrate Calendar links secured by SSL/TLS, i.e. a login and password.

### Describe the solution you'd like

Integrate a small form for the login and the password when you put a calendar link

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/70
