### ISSUE TITLE
 New Calendar Event by Email 

### ISSUE THREAD

**Issue by kolja82** [nextcloud/calendar#463]
Hallo

Can you add the feature to add a new calendar event by sending an email?

Like this:

to: calander@domain.de
Subject: 20.05.2017 13:00 Lunch
Text: Remember to call the Resturant

Kolja

**Comment by georgehrke** [comment]
@kolja82 Can you please explain a legitimate use-case? 

Why does  a caldav client on your phone / desktop doesn't serve the purpose?

**Comment by pixelipo** [comment]
My guess is automation - you could set a mail forwarder based on a certain filter (From and/or Title)

**Comment by georgehrke** [comment]
@pixelipo You could also forward it to a python script that makes some caldav calls to create a new event ;) 

If @kolja82 is not able to provide a legitimate use-case I will close this. I can't come up with any common use-case, that can't be used by simply using a caldav client.

**Comment by georgehrke** [comment]
no response, closing
