### ISSUE TITLE
Importing calendars from Outlook

### ISSUE THREAD

**Issue by gandalf46** [nextcloud/calendar#464]
Nextcloud V11.0.3
After importing a Outlook Calendar (2013) Nextcloud sends invitations even for expired dates.

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.

There already is an issue in the server repo.
https://github.com/nextcloud/server/issues
