### ISSUE TITLE
Attendee displayed twice

### ISSUE THREAD

**Issue by nursoda** [nextcloud/calendar#465]
Calendar 1.5.3 on NC12.0 (release) on debian 8.8, Client: FX on Win/Lin

### Steps to reproduce
1. Have two users A and B, each of them sharing their default calendar with each other, enable "can modify"
2. A creates a meeting, invites B within
3. B accepts the meeting

### Expected behaviour
A and B see one entry for A and one for B

### Actual behaviour
- in NC web interface: A and B see one entry for A and two entries for B
- in Thunderbird Calendar, A and B see one entry for A and one for B (as expected)

**Comment by georgehrke** [comment]
Might be related to https://github.com/nextcloud/calendar/issues/437

**Comment by georgehrke** [comment]
@nursoda Did you create the event and add the attendees in Thunderbird or the Nextcloud calendar app?

**Comment by nursoda** [comment]
I created the meeting in NC calendar app and invited a valid NC user therein.
NC sends out invitations.
The attendee accepted BY MAIL (in Thunderbird).
After that, I see B's appointment twice in the app while in TB Cal, it's still one.

**Comment by nursoda** [comment]
We only noticed that only since NC 12.

**Comment by georgehrke** [comment]
Hm. Sounds like a server issue then. Will investigate first though.

**Comment by georgehrke** [comment]
As far as i can tell this should be fixed with https://github.com/nextcloud/calendar/pull/921
