### ISSUE TITLE
Let user select default calendar

### ISSUE THREAD

**Issue by nursoda** [nextcloud/calendar#466]
Calendar 1.5.3 on NC12.0 (release) on debian 8.8, Client: FX on Win/Lin

### Steps to reproduce
1. create a second calendar, name it (say "MyCalendar"), and delete the default calendar "personal"
2. let someone else invite you to a meeting

### Expected behaviour
The user should
(1) either not be able to delete the default calendar "personal"
(2) or the user should be able to select which of his calendars invitations go to ("default calendar")

### Actual behaviour
Currently, if "personal" doesn't exist, it's silently created on-the-fly.

Problem is, that if you - like me - only use e.g. Thunderbird Calendar and more or less only use the web interface to maintain the NC server and apps, you don't notice that you have a new calendar, and appointments therein.

**Comment by georgehrke** [comment]
> Currently, if "personal" doesn't exist, it's silently created on-the-fly.

If you have another calendar in place, no new calendar should be created. Please report this in https://github.com/nextcloud/server

**Comment by nursoda** [comment]
Will do that, thanks.
