### ISSUE TITLE
InvalidSignatureException

### ISSUE THREAD

**Issue by laolux** [nextcloud/calendar#4663]
### Steps to reproduce

1. run `php occ integrity:check-app calendar` on nextcloud server.

### Expected behavior

Nothing should be returned as integrity check passes.

### Actual behaviour

Integrity check fails and

      - EXCEPTION:
        - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
        - message: Signature data not found.

gets returned. Additionally, get a warning in Administration->Overview.

### Calendar app version

4.0.1

### CalDAV-clients used

Thunderbird

### Browser

Firefox 106

### Client operating system

Fedora

### Server operating system

Debian

### Web server

Apache

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.0.18

### Updated from an older installed version or fresh install

Updated from an older version

### Additional info

Might be related to [https://github.com/nextcloud/related_resources/issues/106](https://github.com/nextcloud/related_resources/issues/106).

**Comment by ChristophWurst** [comment]
As the output says, there is no signature data for this app.
