### ISSUE TITLE
Import ICS file (re)invites all attendees, past and present

### ISSUE THREAD

**Issue by GanimanSwift** [nextcloud/calendar#467]
### Steps to reproduce
1. Export calendar in ICS format from mail client
2. Import ICS file to Nextcloud Calendar
3. Emails invitations are (re)sent to all attendees from all past/present appointments

### Expected behaviour
Emails should not automatically be sent to attendees.  This should either be disabled or be an option when importing an ICS file.

### Actual behaviour
Lots of people got e-mailed that should not have, because they were already invited from the old calendar system.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.0.15

**Server version:** (see your admin page)
11.03

**Calendar version:** (see the apps page)
1.5.3

**Updated from an older installed version or fresh install:**
Updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.4.1
  - calendar: 1.5.3
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - news: 10.2.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_saml

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "oczqfqizvq5x",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/nextcloud",
        "overwrite.cli.url": "http:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "nextcloud",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextcloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "loglevel": 2,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "***REMOVED SENSITIVE VALUE***",
                11211
            ]
        ]
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

nfs mount to data directory in default location

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP
#### LDAP configuration (delete this part if not used)

+-------------------------------+-----------------------------------------------------------+
| Configuration                 |                                                           |
+-------------------------------+-----------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                         |
| hasPagedResultSupport         |                                                           |
| homeFolderNamingRule          |                                                           |
| lastJpegPhotoLookup           | 0                                                         |
| ldapAgentName                 | uid=***REMOVED SENSITIVE VALUE*** |
| ldapAgentPassword             | ***                                                       |
| ldapAttributesForGroupSearch  |                                                           |
| ldapAttributesForUserSearch   |                                                           |
| ldapBackupHost                |                                                           |
| ldapBackupPort                |                                                           |
| ldapBase                      | dc=***REMOVED SENSITIVE VALUE***                                         |
| ldapBaseGroups                | dc=***REMOVED SENSITIVE VALUE***                                         |
| ldapBaseUsers                 | dc=***REMOVED SENSITIVE VALUE***                                         |
| ldapCacheTTL                  | 600                                                       |
| ldapConfigurationActive       | 1                                                         |
| ldapDynamicGroupMemberURL     |                                                           |
| ldapEmailAttribute            | mail                                                      |
| ldapExperiencedAdmin          | 0                                                         |
| ldapExpertUUIDGroupAttr       | cn                                                        |
| ldapExpertUUIDUserAttr        | cn                                                        |
| ldapExpertUsernameAttr        |                                                           |
| ldapGroupDisplayName          | cn                                                        |
| ldapGroupFilter               | (|(cn=***REMOVED SENSITIVE VALUE***)(cn=***REMOVED SENSITIVE VALUE***))                                       |
| ldapGroupFilterGroups         | ***REMOVED SENSITIVE VALUE***;***REMOVED SENSITIVE VALUE***                                                   |
| ldapGroupFilterMode           | 0                                                         |
| ldapGroupFilterObjectclass    |                                                           |
| ldapGroupMemberAssocAttr      | uniqueMember                                              |
| ldapHost                      | ldaps://***REMOVED SENSITIVE VALUE***                                  |
| ldapIgnoreNamingRules         |                                                           |
| ldapLoginFilter               | (&(&(|(objectclass=posixAccount)))(uid=%uid))             |
| ldapLoginFilterAttributes     |                                                           |
| ldapLoginFilterEmail          | 0                                                         |
| ldapLoginFilterMode           | 0                                                         |
| ldapLoginFilterUsername       | 1                                                         |
| ldapNestedGroups              | 0                                                         |
| ldapOverrideMainServer        |                                                           |
| ldapPagingSize                | 500                                                       |
| ldapPort                      | 636                                                       |
| ldapQuotaAttribute            |                                                           |
| ldapQuotaDefault              | 5 GB                                                      |
| ldapTLS                       | 0                                                         |
| ldapUserDisplayName           | displayname                                               |
| ldapUserDisplayName2          |                                                           |
| ldapUserFilter                | (&(|(objectclass=posixAccount)))                          |
| ldapUserFilterGroups          |                                                           |
| ldapUserFilterMode            | 0                                                         |
| ldapUserFilterObjectclass     | posixAccount                                              |
| ldapUuidGroupAttribute        | auto                                                      |
| ldapUuidUserAttribute         | auto                                                      |
| turnOffCertCheck              | 0                                                         |
| turnOnPasswordChange          | 0                                                         |
| useMemberOfToDetectMembership | 1                                                         |
+-------------------------------+-----------------------------------------------------------+

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.

There already is an issue in the server repo.
https://github.com/nextcloud/server/issues
