### ISSUE TITLE
Update app screenshot to Nextcloud 25 design

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#4675]
### Is your feature request related to a problem? Please describe.

https://raw.githubusercontent.com/nextcloud/screenshots/master/apps/Calendar/view_week.png shows the old design

### Describe the solution you'd like

Update
- [x] README
- [x] info.xml (app store)

**Comment by szaimen** [comment]
The readme screeenshot wasnt updated?

**Comment by szaimen** [comment]
Seems like it is this one: https://github.com/nextcloud/screenshots/blob/master/apps/Calendar/view_week.png
