### ISSUE TITLE
Modal windows "create appointment", "edit appointment" or "Trash bin" cause an error "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/calendar#4676]
### Steps to reproduce

1. Open modal window
2. Loading takes too long
3. See an error:

``` 
Error in nextTick: "RangeError: Maximum call stack size exceeded"
found in
---> <NcModal>
```

and 

```Maximum call stack size exceeded```

### Expected behavior

No error to expect

### Actual behaviour

Modal window takes too long and opening cause an error

### Calendar app version

3.5.1

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/nextcloud-vue/issues/3386 https://github.com/nextcloud/nextcloud-focus-trap/issues/2

**Comment by JuliaKirschenheuter** [comment]
Closing issue because of https://github.com/nextcloud/nextcloud-vue/issues/3386 https://github.com/nextcloud/nextcloud-focus-trap/issues/2
