### ISSUE TITLE
Appointments Talk integration

### ISSUE THREAD

**Issue by ChildLearningClub** [nextcloud/calendar#4680]
### Is your feature request related to a problem? Please describe.

Many appointments are online now, I'm sure this is already being worked on, but if not, having the option to auto generate a talk link and add it to the appointment email similar to how the appointments app does it.

### Describe the solution you'd like

Admin can chose if they want to enable the option to generate online meeting links.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/3480

**Comment by ChildLearningClub** [comment]
Sorry @ChristophWurst, searched and didn’t see the other.

**Comment by ChristophWurst** [comment]
No problem
