### ISSUE TITLE
Appointments time zone picker overlaps list of slots

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#4698]
### Steps to reproduce

1. Create a "Appointments" calendar
2. Open the booking page

### Expected behavior

Nicely aligned view to select a date

### Actual behaviour

TImezone hides some of the dates:

![grafik](https://user-images.githubusercontent.com/1589737/198569964-22bf7ee1-43d2-47c3-bfb8-6ae04bdfd073.png)

### Calendar app version

4.0.2

### Browser

Firefox 105.0.2 and Chrome 106

**Comment by miaulalala** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/4615 ?
