### ISSUE TITLE
Appointments: all day events are ignored 

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#4699]
### Steps to reproduce

1. Setup a calendar with a all days event
2. Setup "Appointments" for the same calendar
3. Try to book a appointment

### Expected behavior

No available slots on the days with the all day event

### Actual behaviour

People can still book appointments:

![grafik](https://user-images.githubusercontent.com/1589737/198577691-9ea1db51-1767-41ba-8149-36ab859cc4fa.png)

Calendar (as you can see, at Nov, 03 is a all day event):

![grafik](https://user-images.githubusercontent.com/1589737/198577907-6d0165b5-b311-40d7-8f43-9aaab256034e.png)

### Calendar app version

4.0.2

**Comment by ChristophWurst** [comment]
Have you set yourself as *busy* for the all day event?

**Comment by schiessle** [comment]
> Have you set yourself as _busy_ for the all day event?

Ah, indeed. This was the issue. The calendar entry was set to "free". I wonder what's the idea of this distinction?
I created the all-day event with Thunderbird where I don't have this distinction and it seems that a all-day events get synced as "free". When I create a one hour event with Thunderbird it is synced as "busy" to the calendar.

Is there a deeper sense I behind it, which I don't get?

**Comment by schiessle** [comment]
@ChristophWurst I did some tests:

1. Thunderbird: all day events are written to our calendar as "free"
2. acalendar (Android): all day events are written to our calendar as "busy"
3. Outlook: all day events are written to our calendar as busy

This means that appointment booking is broken for all people who manage their calendar with Outlook or Thunderbird. IMHO a major drawback. I think we should think about how to fix it. Maybe set all new calendar entries which are send from a 3rd party client always to "busy"?

As I can't distinguish with Thunderbird between "busy" and "free" maybe the field is even empty when send to our server and we just need to change the default if the entry doesn't contain a value?

Should we discuss it here and re-open the ticket or should I create a new ticket for it?

**Comment by tcitworld** [comment]
I'm not sure about Outlook as I can't test, but Thunderbird's all-day events being set to `TRANSPARENT` instead of `OPAQUE` is a 9 year old issue: https://bugzilla.mozilla.org/show_bug.cgi?id=998281. Someone in this very issue says Outlooks works as expected.

As we can't know if the value is an issue or a valid one, I'd say we can't do much.

**Comment by ChristophWurst** [comment]
I agree with @tcitworld. We can't know if the event sent from a 3rdparty client intentionally set the event to *free* by user input or because of a bug.

It has to be possible create full day events with *free* status.

What we already do is only consider an event *free* if it has `TRANSP` set to `TRANSPARENT`. Anything else is considered busy. So the use case of a client not setting a status is already covered by the appointments feature. Evidence: https://github.com/nextcloud/calendar/blob/9efe190f72ed99d86c1e6842240a85c704c87015/lib/Service/Appointments/EventConflictFilter.php#L75-L76

**Comment by simonSlamka** [comment]
@ChristophWurst 

I seem to be having this issue as well, however, I only use the Nextcloud web calendar. I do not use any 3rd party calendar app. I have all my events set to make me busy and in addition, they're even in the same calendar as my appointments. It still doesn't create a conflict.

The setting that I had hoped would help was the option to select calendars used to check for conflicts, but the option is greyed out:
![image](https://user-images.githubusercontent.com/51794014/199418705-e50bc109-d366-4f2d-8118-9b03d092b133.png)

Any help, please?
This essentially makes the appointments feature unusable for me. People just schedule events over other events that were supposed to have marked me as busy.

**Comment by ChristophWurst** [comment]
@simonSlamka see https://github.com/nextcloud/calendar/issues/4697.

**Comment by simonSlamka** [comment]
> @simonSlamka see #4697.

Alright, awesome. Thanks.

It sucks that you can't actually use the calendars from Deck. I have like 15 decks all in my calendar app and it would be super cool if it would take those into consideration, too. But that's a different matter.

**Comment by simonSlamka** [comment]
I can confirm that this fixes the ignore issue. Adding additional calendars, even if different from the calendar where your actual events are, fixes the issue.

Like, my setup is Work and Personal (and bunch of others from Deck, but those are irrelevant in this instance).
Creating a calendar for my school stuff and adding it to the dropdown fixed the issue, even though most of my events are in my Work calendar.

**Comment by schiessle** [comment]
To be honest, I don't see a lot of reasons to chose a deck calendars as conflict calendar. Deck calendars only contain due dates for tasks but no appointments which keeps you busy for a certain amount of time.

On the other hand I don't see why we should define what makes sense and what doesn't. There are other read-only calendar which people might want to chose for conflict checking as well. That's why I opened a dedicated feature request for it: https://github.com/nextcloud/calendar/issues/4714

**Comment by simonSlamka** [comment]
> To be honest, I don't see a lot of reasons to chose a deck calendars as conflict calendar. Deck calendars only contain due dates for tasks but no appointments which keeps you busy for a certain amount of time.
> 
> On the other hand I don't see why we should define what makes sense and what doesn't. There are other read-only calendar which people might want to chose for conflict checking as well. That's why I opened a dedicated feature request for it: #4714

Fair enough. But like you said, it *could* still be useful for people to be able to do it. Appreciate the feature request.
