### ISSUE TITLE
Europe/Moscow timezone is wrong

### ISSUE THREAD

**Issue by p5n** [nextcloud/calendar#470]
Europe/Moscow timezone is wrong in /nextcloud/apps/calendar/timezones. I did not completely understand how these files are generated, but it is needed to change +0400 to +0300 in EUROPE-MOSCOW.ics.

May be it is 3rd party issue or it is needed to regenerate them against latest tzdata.

My calendar package was built from https://github.com/nextcloud/calendar/archive/v1.5.3.tar.gz

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/82
