### ISSUE TITLE
Moscow time zone bug

### ISSUE THREAD

**Issue by art-shutter** [nextcloud/calendar#471]
A simple long-standing bug: wrong time zone setting in /timezones/EUROPE-MOSCOW.ics

The recognized offset should be **GMT +0300 (no daylight saving)**, while the file has the offset of **+0400** in the current release version.

Reference and the history of time zone change: https://en.wikipedia.org/wiki/Moscow_Time

![2017-05-25_10-45-55](https://cloud.githubusercontent.com/assets/19182088/26440987/67bdc202-4137-11e7-9f00-a6168d7f2b62.png)

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/82
