### ISSUE TITLE
Improve usability of colour picker

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#4711]
### Is your feature request related to a problem? Please describe.

Currently, changing the calendar colour is cumbersome and unintuitive.

I have to click three times to change the calendar colour.

![image](https://user-images.githubusercontent.com/7427347/199470426-7b8a84d8-ed4f-47c6-ac57-772f683c170b.png)

### Describe the solution you'd like

Auto save the colour as soon as it is picked and remove the unintuitive right arrow from the colour field.

### Describe alternatives you've considered

use the NC ue colour picker
https://nextcloud-vue-components.netlify.app/#/Components/NcPickers?id=nccolorpicker

**Comment by st3iny** [comment]
This will be fixed by https://github.com/nextcloud/calendar/pull/4515. I'll hopefully find some time to finalize it soon :see_no_evil:
