### ISSUE TITLE
Public Calender bottom part off-screen

### ISSUE THREAD

**Issue by aikitori** [nextcloud/calendar#4715]
### Steps to reproduce

1. Create public link from a calender
2. Visit the link

### Expected behavior

Calender should respect new Design. Background should visible on all endges 

### Actual behaviour

Buttom part of the Calender is outside the screen.

Privat Calender App:
![grafik](https://user-images.githubusercontent.com/88290076/199938597-96329d34-ed8e-4ed3-8bd3-4732013165cf.png)

Public Link:
![grafik](https://user-images.githubusercontent.com/88290076/199938689-37a2fa69-e5e2-4402-974a-f7d05bb9977f.png)

It looks like this css-rule is the troublemaker. When i deactivate it in the browser console, the calender looks correct.
https://github.com/nextcloud/calendar/blob/main/css/public.scss#L27

```

#body-public .content {
  min-height: 100% !important;
}
```

**Workarround:**

Use CostumCSS App and create a more specific css rule:

```

#body-public .content.app-calendar-public {
  min-height: 0% !important;
}
```

### Calendar app version

4.1.0

### Browser

Firefox 106

### Client operating system

Windows/Linux Mint

### Server operating system

Ubuntu 22.04

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.0

### Nextcloud version

25.0.1

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by SakshiT25** [comment]
Hey, I'm interested in working on this issue.

**Comment by ChristophWurst** [comment]
Go ahead @SakshiT25 :)

**Comment by SakshiT25** [comment]
Hi, I have made my changes in the file using gitpod. Could you please tell me the command to run the application on it or any other application to test my changes?

**Comment by SakshiT25** [comment]
@ChristophWurst  @aikitori Hi, I have made my changes in the file using gitpod. Could you please tell me the command to run the application on it or any other application to test my changes?

**Comment by ChristophWurst** [comment]
Could you please open the changes as a pull request? https://docs.github.com/en/pull-requests
