### ISSUE TITLE
remove double user identification on Cals

### ISSUE THREAD

**Issue by punkyard** [nextcloud/calendar#4719]
### Is your feature request related to a problem? Please describe.

hi
not long ago, the shared calendars have seen their display evolved.
Now, when a Calendar is shared, the creator is identified twice:
in between the brackets and in the user icon. why twice?
it's not elegant and hardens the reading 
![calendar user x2](https://user-images.githubusercontent.com/59349105/200023349-396e982f-0514-422b-8acb-7f9535961449.png)

plus, into brackets is given the user name, not full name, which could lead to a security issue as it could be used to attempt to login with it, when full user name can't permit to log in.

### Describe the solution you'd like

could you please remove the text in between the brackets please?

and please keep a Talk weblink through the user icon ;)
Thanks

**Comment by miaulalala** [comment]
For me it is actually the calendar name and then the user by whom it was shared:

![image](https://user-images.githubusercontent.com/7427347/200529324-77a36292-234b-4586-a529-76aff62a9ba4.png)


I think the user by whom it was shared is acceptable and makes sense. As you can't remove youself from a shared calendar, you need the information whom to approach if you want to be removed from a calendar share.

**Comment by punkyard** [comment]
thanks @miaulalala 
same for me, as for you, it reads:

> Project (Bob)        Bob's icon

So Bob twice
I think Bob's icon is just enough and fine

one year ago the name of the user who shared the cal wasn't into brackets - if I not wrong
just the name of the calendar is easier to read, and **nicer in a public view**

you suggesting i rename the calendar
but we have many users, so i won't rename every calendar for every user!


If there was a link to Talk in Bob's icon -as it is in other places- it would be just great
