### ISSUE TITLE
"Undelivered Mail Returned to Sender" should be sent to user, not admin

### ISSUE THREAD

**Issue by quentinDupont** [nextcloud/calendar#4738]
### Is your feature request related to a problem? Please describe.

When a user mistype or enter a wrong email in participants, a email is sent to the admin (email address defined in NC settings → Basic settings → Email server)

### Describe the solution you'd like

When a user mistype or enter a wrong email in participants, a email should be sent to the user

**Comment by tcitworld** [comment]
`Undelivered Mail Returned` to Sender is a bounce message notification sent by your email provider system (Postfix, Exim, …), not Nextcloud itself. 

There's no way to for Nextcloud to know if a mail is really sent once it's given to the email system it's configured with, apart from using a dedicated IMAP/POP3 inbox to detect bounces, as some newsletter software do. That would be over-engineering in the case of Nextcloud.

**Comment by quentinDupont** [comment]
Yes ok I get it !
