### ISSUE TITLE
Calendar doesn't use date formatstring from locale setting

### ISSUE THREAD

**Issue by paultheweird** [nextcloud/calendar#4739]
### Steps to reproduce

1. Setup nextcloud
2. Install calendar app
3. Have a user with Dutch locale
4. Observe time in calendar in 24h format (no more am/pm: GOOD!), but also observe 11/14/2022 (month/day/year: not so good ;-) )

### Expected behavior

Dates should be rendered using the format string from the users' locale (e.g. day-month-year, for Dutch locales).

### Actual behaviour

Dates are rendered using the (in my opinion, silly) American format of month/day/year.

I noticed time did get fixed from the am/pm weirdness to "normal" 24h times when changing the locale setting for the user, but this didn't apply for dates (tried logging out and back in again to no avail).

### Calendar app version

4.1.0

### CalDAV-clients used

(just nextcloud native client in the browser)

### Browser

Firefox 106.0.2

### Client operating system

OpenBSD -current

### Server operating system

OpenBSD -current

### Web server

Other

### Database engine version

MariaDB

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.0

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
Enabled:
  - activity: 2.17.0
  - calendar: 4.1.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud configuration

```Text
{
    "system": {
        "integrity.check.disabled": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "dbtype": "mysql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpass": "XS7LqIVDhnfyls0snfPN",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "hpdw.nl"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "25.0.0.18",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/nextcloud",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "openssl": {
            "config": "\/etc\/ssl\/openssl.cnf"
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}
```

### Additional info

I'm running nextcloud on OpenBSD httpd, the webserver included in the OpenBSD distribution. I have nextcloud installed from packages (working great so far - thanks for a very cool product!)

Seems to be a simple case of a forgotten format string conversion for locale settings; I've provided configuration and the list of installed apps anyway. Hope it's easy to reproduce on other environments!

**Comment by louwers** [comment]
Duplicate #4177

**Comment by st3iny** [comment]
I tried to reproduce this on the latest main and it seems fixed. There were some improvements to locale handling in the meantime that likely fixed your issue.

If not, please **do not hestitate** to reopen the ticket or create a new one. Thanks :)

**Comment by logotu** [comment]
/reopen
I have the same issue on 31.0.0 with locale "German (Austria)" or "German" can not fix it with the described procedure.

**Comment by SebastianKrupinski** [comment]
Duplicate of #6359
