### ISSUE TITLE
Option adding time after appointment is saved but not displayed in th UI

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/calendar#4743]
### Steps to reproduce

1. Create an appointement schedule
2. Tick the box 'Time after an appointment'
3. Set a time
4. Click "Update"
5. Reopen the appointment schedule with the 3 dot menu

### Expected behavior

Time after an appointment should be set to the value defined previsoulsy.

### Actual behaviour

Time after an appointment is displayed as if nothing was set.
![image](https://user-images.githubusercontent.com/87175513/202673480-5f5cd335-e8f4-4b0c-9d3a-472a16e32cd2.png)

However, the feature is working correctly, meaning that if I've set once time after an appointement, that time is actually booked when somedy request a meeting with me.

NB: the behavior of time BEFORE the appointment is normal.

### Calendar app version

c.nc.c

**Comment by ChristophWurst** [comment]
@st3iny :eyes:

**Comment by juliuspopp** [comment]
Can confirm this with Calendar 3.5.4.
But in my case, the time does not seem to be applied, I want buffers of 30 and 60 minutes with a duration of 60 minutes, and I could book one appointment at 9.15 am and can book another at 10.45, so only the pre-buffer/padding is taking effect.
I'll edit this comment if it was a caching thing and the change takes effect later.
