### ISSUE TITLE
Appointment booking, people should be able to set a title

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#4773]
### Is your feature request related to a problem? Please describe.

All booked appointments have the same default name in my calendar, the name I gave it when I setup appointments. This makes it quite confusing if multiple people booked a appointment

### Describe the solution you'd like

When booking a appointment people can define at the moment their name, email address and the description. There should be another input field "topic" this topic should be set as event title. Or maybe even something like "[title] - booked by [name]"

**Comment by 42ske** [comment]
If you rework the booking options, it would be fine if you also could have a look at these suggestions: https://github.com/nextcloud/calendar/issues/4110

Thanks a lot!

**Comment by ChristophWurst** [comment]
Likely a duplicate of https://github.com/nextcloud/calendar/issues/4263

**Comment by schiessle** [comment]
I agree, it is a duplicate. Let's close this one. I will add my suggestions how to solve it to the other ticket
