### ISSUE TITLE
Option to start week on Monday

### ISSUE THREAD

**Issue by Isvvc** [nextcloud/calendar#478]
For me, the week starts on Monday, so having the online calendar client differ from my mobile clients can be confusing and can throw off my perception of time when things aren't aligned as I'm used to seeing them. An option to change the day the week starts on would be nice.

**Comment by georgehrke** [comment]
The first day of the week is currently determined based on your language
There are plans for a dedicated region input in the server:
https://github.com/nextcloud/server/issues/1781
