### ISSUE TITLE
Asynchronous update of calendar 

### ISSUE THREAD

**Issue by sascha08-15** [nextcloud/calendar#4797]
### Is your feature request related to a problem? Please describe.

I don't update the calendar page on my browser so I sometimes don't see new updates, e.g. added invites.

### Describe the solution you'd like

As a nextcloud user,
I want the nextcloud calendar to update without the need of refreshing the entire site. On new calendar items, I expect to push the server new events to the browser. 
Such that I am always sure I look at the actual calendar invites and not an outdated version and I can avoid reloading the page.

**Comment by tcitworld** [comment]
Duplicate from #31
