### ISSUE TITLE
Calendar Button: "Copy primary CalDAV address" not working

### ISSUE THREAD

**Issue by AlexanderZuehr** [nextcloud/calendar#4799]
### Steps to reproduce

Open Nextcloud calendar.
Open Calendar settings.
Click on "Copy primary CalDAV address"

### Expected behavior

It should copy the primary CalDAV address.

### Actual behaviour

Error Message: CalDAV link could not be copied to clipboard.

![Bildschirm­foto 2022-12-12 um 15 20 49](https://user-images.githubusercontent.com/76497172/207068944-50a90241-b26e-45e8-9277-8667656215ad.png)

![Bildschirm­foto 2022-12-12 um 15 18 50](https://user-images.githubusercontent.com/76497172/207068664-342ac77b-7cda-43cf-b5e4-4d287490c2ed.png)

### Calendar app version

4.1.0

### Client operating system

macOS

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

25.0.2

### Updated from an older installed version or fresh install

None

**Comment by tcitworld** [comment]
Fixed in #4729, not yet released
