### ISSUE TITLE
Cannot change time zone in Web interface

### ISSUE THREAD

**Issue by nickmontfort** [nextcloud/calendar#4804]
### Steps to reproduce

1. Open calendar.
2. Click to add a new calendar entry.
3. Click on either globe symbol to change the time zone.

Note that it is also possible to use the keyboard in the interface:

3. Tab through until either globe symbol is highlighted by a circle.
4. Press Enter/Return. 

The same problem is seen in both the simplified editor and the editor in the sidebar.

### Expected behavior

Time zone selection menu appears.

### Actual behaviour

Nothing.

### Calendar app version

4.1.0

### CalDAV-clients used

Web client

### Browser

Tried on Firefox 107.0, Chromium 108.0.5359.98 

### Client operating system

Pop!_OS

### Server operating system

Ubuntu

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 7.4

### Nextcloud version

Nextcloud Hub 3 (25.0.2)

### Updated from an older installed version or fresh install

Updated from an older version

### Additional info

May relate to #4802.

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/calendar/pull/4764
