### ISSUE TITLE
Better highlighting of "today" in calendar (month-view)

### ISSUE THREAD

**Issue by andypfau** [nextcloud/calendar#4806]
Since switching to NC 25.x, the current day in the calendar is barely highlighted. I am normally using the month-view, and when I enter that page, I would love to see today's cell at first glance.

Instead, the current day uses the same colors as the days of the previous or next month. The number of the day is emphasized in bold, sure, but if you've got a busy calendar, that does not help much.

This is what I see in Firefox, both under Windows or Linux:
![cal_dark](https://user-images.githubusercontent.com/50749532/207542449-fe9b2398-27c9-4e71-a3f0-e65a6e2ede8a.jpg)
![cal_light](https://user-images.githubusercontent.com/50749532/207542458-31b75ab2-f530-4007-9f03-dfc0ceaec15a.jpg)

This is all fine until your calendar has hundreds of entries!

I added a CSS entry in the admin theming settings, to make it look like this:
![cal_dark_hack](https://user-images.githubusercontent.com/50749532/207542457-edce36e7-01c7-4392-864a-22303ea5187b.jpg)

CSS:
`.fc-daygrid-day.fc-day-today {  box-shadow: 0px 0px 0px 4px var(--color-primary) inset; }`

This is of course just a hack from a design-amateur, and it even overlaps with calendar entries, so it is ugly, but it works for me. Even in my regular calendar (which is quite packed) I can visually spot the current day at first glance.

I am sure the design experts at NC have better ideas. Another option would be e.g. a different background color, but the theme colors are quite limited here, and I guess that will also get invisible once your calendar gets full.

You can consider this feature request low-prio, as I have my own workaround with the CSS theming :-)

**Comment by nsk7even** [comment]
In the previous versions of Nextcloud, the number of the today entry was highlighted by an orange (standard theme) circle background. This was perfectly sufficient to identify today at a glance.
Of course, each other geometric form would work also. When using the headline for the highlightning, there is no collision with any contents and there is enough space.

**Comment by SakshiT25** [comment]
Hey, adding _.ui-state-highlight_ and _.ui-state-hover classes_ on the anchor element in the Js file might help in highlighting the date-picker in the calendar.

**Comment by klauweg** [comment]
> CSS:
> `.fc-daygrid-day.fc-day-today { box-shadow: 0px 0px 0px 4px var(--color-primary) inset; }`

Please excuse my dumb question, but where does that have to go?

**Comment by klauweg** [comment]
> Please excuse my dumb question, but where does that have to go?
Ok, i found a custom CSS App and i suppose it must be installed. At least entering the css snippet there works.

**Comment by naelfe** [comment]
I was thinking about posting the exact same thing. Have my thumbs up!
Figured a simple yellow (maybe customizable) border for the current day would work perfectly.

**Comment by nsk7even** [comment]
> Ok, i found a custom CSS App and i suppose it must be installed. At least entering the css snippet there works.

Thank you for this!

I put the solution from the merge request into the custom CSS app and now the circle is back:

```
.fc-day-today .fc-daygrid-day-number
{
			background: var(--color-primary);
			color: var(--color-primary-text);
			border-radius: 50%;
}
```
Intermediate solution, until the updated CSS is released.
(as I don't use it, I skipped the weekly CSS)

![image](https://user-images.githubusercontent.com/6367390/216772570-8f7e7e67-7069-44eb-9d14-34192a23ae74.png)

**Comment by alexanderdd** [comment]
@ChristophWurst I think this can be closed? In NC 30 the date number is highlighted, as wished for.
