### ISSUE TITLE
Unable to use a CalDAV client to sync Calendars to which NC is subscribed to

### ISSUE THREAD

**Issue by likyng** [nextcloud/calendar#481]
### Steps to reproduce
1. Subscibe to an ical calendar on nextcloud, ie. a shared Google Calendar
2. Add the Nextcloud calendar account to iOS
3. Try to select/download the Google Calendar

### Expected behaviour
The Google Calendar should show up on my iPhone, as nextcloud's own calendars do. Furthermore, the iPhone would only have to pull one server to refresh all calendars instead of pulling multiple different servers, one for each calendar.

### Actual behaviour
The Google Calendar does not show up on the iPhone (no error, just not visible).

### Server configuration

**Operating system**:
Arch Linux

**Web server:**
Nginx 1.12

**Database:**
mariadb 10.1.23 (mysql)

**PHP version:**
7.1.5

**Server version:** (see your admin page)
12

**Calendar version:** (see the apps page)
1.5.3

**Updated from an older installed version or fresh install:**
Fresh install of NC11 -> Update to NC12

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**
 Activity
2.5.2

Collaborative tags
1.2.0

Comments
1.2.0

Deleted files
1.2.0

External storage support
1.3.0

Federation
1.2.0

File sharing
1.4.0

First run wizard
2.1

Gallery
17.0.0

Log Reader
2.0.0

Monitoring
1.2.0

Nextcloud announcements
1.1

Notifications
2.0.0

Password policy
1.2.2

PDF viewer
1.1.1

Share by mail
1.2.0

Text editor
2.4.1

Theming
1.3.0

Update notification
1.2.0

Usage survey
1.0.0

Versions
1.5.0

Video player
1.1.0

Brute-force settings
1.0.2

Calendar
1.5.3

Contacts
1.5.3

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** None

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 53

**Operating system:** Arch Linux / Windows 10

**CalDAV-clients:** iOS 10.2

#### Web server error log
```
Insert your webserver log here
Will insert later
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
Will insert later
```

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/1497
