### ISSUE TITLE
Calendar widget results are not identical on web and iOS

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#4813]
### Steps to reproduce

Compare iOS widget and web UI:

| iOS | Web UI |
|---|---|
| ![image](https://user-images.githubusercontent.com/7427347/207850905-2ee6780f-7872-45c5-bc62-a3e7c591af0b.png) | ![image](https://user-images.githubusercontent.com/7427347/207851109-c7664309-42fc-47b2-9c31-366a2d2f8b32.png) |

### Expected behavior

The events displayed are identical and in the same order

### Actual behaviour

The events displayed are not identical and not in the same order.

In addition, the recurrences are not using the closest date but the initial RRULE date.

### Calendar app version

4.1.0

### CalDAV-clients used

iOS, web

### Server operating system

c.nc

**Comment by marinofaggiana** [comment]
@miaulalala some news here ?

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/server/pull/40541?

**Comment by st3iny** [comment]
Indeed. Also by #5417.
