### ISSUE TITLE
Trigger an iMIP email when responding to an invitation via Web UI

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#4819]
### Is your feature request related to a problem? Please describe.

Currently, accepting / declining an email via the InvitationResponsecontroller doesn't trigger a scheduling email / iMIP email to the ORGANIZER. Information is lost and I would have to manually look into my calendar to see if the attendees have responded.

### Describe the solution you'd like

Integrate the InvitationResponseController's scheduling logic into the Sabre event lifecycle and trigger the correct events to the iMIPPlugin reacts to the scheduling event.

### Describe alternatives you've considered

none

### Additional context

Follow up to https://github.com/nextcloud/calendar/issues/3919

**Comment by ChristophWurst** [comment]
> Information is lost

How?
