### ISSUE TITLE
Erro ao agendar um compromisso no Calendar

### ISSUE THREAD

**Issue by dundofilho2022** [nextcloud/calendar#4837]
### Steps to reproduce

1.ao tentar criar um agendamento clicando no botão agendar compromisso aparece um erro
![agendamento no CALENDAR](https://user-images.githubusercontent.com/121438964/209551548-788ab163-034a-4a6a-bfe4-6f477ae37e38.png)

2.
3.

### Expected behavior

deveria acontecer o agendamento do compromisso no horário escolhido

### Actual behaviour

apresentasse erro e não procegue para as etapas seguintes, confome mostra o tutorial do Calendar
![agendamento no CALENDAR](https://user-images.githubusercontent.com/121438964/209551717-2ee190a4-8bb5-4bad-8270-9af804ded41a.png)

### Calendar app version

versão 4.1.2

### Client operating system

windows 11

### Server operating system

linux

### Web server

None

### Database engine version

SQlite

### PHP engine version

PHP 7.4

### Nextcloud version

versão 25.0.2

### Updated from an older installed version or fresh install

Fresh install

**Comment by ChristophWurst** [comment]
Please submit a ticket in English.
