### ISSUE TITLE
Error creating an appointment

### ISSUE THREAD

**Issue by dundofilho2022** [nextcloud/calendar#4839]
### Steps to reproduce

1.When creating an appointment, it shows an error as shown in the image
![teste agendamento](https://user-images.githubusercontent.com/121438964/209661773-a5bcd236-c285-4b00-a4dd-7d39a489ea54.png)

2.
3.

### Expected behavior

proceed according to the application's tutorial

### Actual behaviour

shows error as picture
![teste agendamento](https://user-images.githubusercontent.com/121438964/209663141-5e2275ea-49b0-4850-8333-90c2a676f444.png)

### Calendar app version

4.1.2

### Server operating system

linux

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

25.0.2

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
Apps              versions


Activity	2.17.0

Calendar	4.1.2

Circles	25.0.0	

Collaborative tags	1.15.0	

Comments	1.15.0	

Contacts Interaction	1.6.0	

Dashboard	7.5.0	

Deleted files	1.15.0	

Federation	1.15.0	

File sharing	1.17.0	

First run wizard	2.14.0	

Forms	3.0.2	

Log Reader	2.10.0	

Monitoring	1.15.0	

Nextcloud announcements	1.14.0	

Notifications	2.13.1	

Notifications for calendar event updates	2.0.0	

Password policy	1.15.0	

PDF viewer	2.6.0	

Photos	2.0.1	

Privacy	1.9.0	

Recommendations	1.4.0	

Related Resources	1.0.3	

Right click	1.4.0	

Share by mail	1.15.0	

Support	1.8.0	

Text	3.6.0	

Update notification	1.15.0	

Usage survey	1.13.0	

User status	1.5.0	

Versions	1.18.0	

Weather status	1.5.0
```

**Comment by ChristophWurst** [comment]
do you get any new entries in data/nextcloud.log when this happens?

**Comment by dundofilho2022** [comment]
Good morning, I'm sending the log file nextcloud, forgive me for my lack of knowledge, if I analyze the file I will not know how to identify the problem, if you can help me I will be very grateful. Thank you very much.
[nextcloud log.log](https://github.com/nextcloud/calendar/files/10332238/nextcloud.log.log)

**Comment by miaulalala** [comment]
Is the email RAY19671967@GMAIL.COM in the logs valid? Do you have SMTP set up for your instance?

{"reqId":"NrJUtjKD6IlRGtamzU8v","level":3,"time":"2022-12-21T18:54:12+00:00","remoteAddr":"191.6.36.7","user":"Porto Silva","app":"appointments","method":"POST","url":"/index.php/apps/appointments/form?p=p0&v=1671648757313","message":"Can not send email to RAY19671967@GMAIL.COM","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","version":"25.0.2.3","data":{"app":"appointments"}}

**Comment by dundofilho2022** [comment]
Again I ask that I apologize for the lack of knowledge, but how do I check if I have SMTP configured on my instance. The email sim is valid, my nextcloud is installed in a subdomain in the Hostinger provider. As I would to check this smtp installation and configure it. I appreciate it right now.

**Comment by miaulalala** [comment]
Go to Administration Settings, and in the section Administration you will find Basic Settings. There you can set up SMTP, which means being able to send emails via your Nextcloud. Please be aware that Gmail likely won't work, as far as I know Gmail doesn't like to be used for SMTP. If you have a hosting package, you might be able to create an email account in your hosting and use that. I'm sure your hosting support can tell you the SMTP configuration for your email, or you might even find it displayed somewhere.

Here's the docs as well: https://docs.nextcloud.com/server/25/admin_manual/configuration_server/email_configuration.html

**Comment by dundofilho2022** [comment]
Good afternoon, the problem was solved, I used the suggestion to use email created in my hosting. Thank you so much for everyone's help, the ideas were very fruitful and ended up solving my problem. I'm sorry i took so long to answer.
