### ISSUE TITLE
Replace TRIGGER:-PT1D with TRIGGER:-P1D

### ISSUE THREAD

**Issue by ThomasDaheim** [nextcloud/calendar#484]
When trying to synchronize my Nextcloud (v11.0.3) calendar (v1.5.3) with MS Outlook using https://github.com/aluxnimm/outlookcaldavsynchronizer I get an error message for some events.

I had created an issue there (https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/194) including an ics sample. Feedback from the team is that there is an error in the ics for a special case:

_The alarm trigger has an invalid duration, since it is 1 day before without a time it must be
TRIGGER:-P1D
instead of
TRIGGER:-PT1D_

So now I have created an issue on your side :-) Happy to help resolving this with add. info if required.

Thanks,
Thomas

**Comment by georgehrke** [comment]
@ThomasDaheim Did you create the ics yourself in the web interface or was it generated by the birthday calendar?

**Comment by ThomasDaheim** [comment]
That ics is part of the error message that outlookcaldavsynchronizer creates when trying to sync. Also it list an URL giving a link to an .ics in my nextcloud. So I would assume the ics was created there.

**Comment by georgehrke** [comment]
Yes, but can you guess by it's name (BIRTHDAY OF XYZ) whether it was created by the birthday calendar or by yourself? That makes an important difference here ;)

**Comment by ThomasDaheim** [comment]
Hi,

anything I could do to make some progress here? E.g. concrete calendar entries for verification?

If anyone would point me into the direction of the code in question I could give it a try myself...

**Comment by ThomasDaheim** [comment]
Had a look at my entries and there was exactly one with TRIGGER:-PT1D. After updating that manually synchronization with Outlook works like a charm :-)

Not sure how and how often something like this happens. So no idea if there is something that could be improved in the calendar... Therefore, closing this defect for now.
