### ISSUE TITLE
Export calendars with 4.2.0 gives TypeError: Cannot read properties of null (reading 'getUTCFullYear')

### ISSUE THREAD

**Issue by loelkes** [nextcloud/calendar#4844]
### Steps to reproduce

1. Upgrade the Calendar app to 4.2.0
2. Export a calendar

### Expected behavior

Browser should download an *.ics file after selecting a calendar and clicking on `Export`.

### Actual behaviour

1. First click on `Export`: nothing happends
2. Sencond click on `Export`: Browser redirects to https://cloud.example.com/apps/calendar/remote.php/dav/calendars/foo.bar/mycalendar/?export (export calendar `mycalendar` for user `foo.bar`) and shows a blank page.

### Calendar app version

4.2.0

### CalDAV-clients used

N.A.

### Browser

Version 108.0.5359.124 (Official Build) (x86_64)

### Client operating system

macOS 13.0.1

### Server operating system

Debian

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### Browser log

```Text
calendar-main.js?v=3d9d60f7-29:2 TypeError: Cannot read properties of null (reading 'getUTCFullYear')
    at Object.getMarkerYear (calendar-main.js?v=3d9d60f7-29:2:5127703)
    at lw.startOfMonth (calendar-main.js?v=3d9d60f7-29:2:5134741)
    at lw.startOf (calendar-main.js?v=3d9d60f7-29:2:5134123)
    at c (calendar-main.js?v=3d9d60f7-29:2:5155994)
    at dateProfileGeneratorClass.buildRangeFromDuration (calendar-main.js?v=3d9d60f7-29:2:5156113)
    at dateProfileGeneratorClass.buildCurrentRangeInfo (calendar-main.js?v=3d9d60f7-29:2:5155272)
    at dateProfileGeneratorClass.build (calendar-main.js?v=3d9d60f7-29:2:5154506)
    at calendar-main.js?v=3d9d60f7-29:2:5252592
    at Vk._handleAction (calendar-main.js?v=3d9d60f7-29:2:5252731)
    at Hk.runTask (calendar-main.js?v=3d9d60f7-29:2:5248584)
```
```


### Additional info

_No response_

**Comment by miaulalala** [comment]
I can confirm and reproduce

**Comment by loelkes** [comment]
Just found out: if I manually access `https://cloud.example.com/remote.php/dav/calendars/foo.bar/mycalendar/?export` the calendar es exported as expected.

**Comment by CapSel** [comment]
I have same problem with export but different error: #4863

**Comment by halleypontes** [comment]
I am running the same Calendar and Nextcloud version the OP is and I am also having the same problem when attempting to export my calendar. Manually accessing the link does not work. This wasn't an issue in the previous version of my Nextcloud instance.

The error log I get:

[index] Error: Exception: OCA\Calendar\Controller\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/custom_apps/calendar/lib/Controller/SettingsController.php' line 71 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Calendar\Con ... {}, "setConfig")
1. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OCA\\Calendar\\ ... r", "setConfig", OC\AppFramework\ ... {}, ["view","calendar.settings.setConfig"])
2. /var/www/html/lib/base.php line 1047
   OC\Route\Router->match("/apps/calendar/v1/config/view")
3. /var/www/html/index.php line 36
   OC::handleRequest()

POST /index.php/apps/calendar/v1/config/view
from XX.XX.XX.XX by admin at 2023-01-03T01:34:28+00:00

**Comment by miaulalala** [comment]
@halleypontes the error is from accessing the url directly? Can you please post the full log entry? You can find it in your nextcloud.log in your data directory.

**Comment by st3iny** [comment]
> I am running the same Calendar and Nextcloud version the OP is and I am also having the same problem when attempting to export my calendar. Manually accessing the link does not work. This wasn't an issue in the previous version of my Nextcloud instance.
> 
> The error log I get:
> 
> [index] Error: Exception: OCA\Calendar\Controller\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/custom_apps/calendar/lib/Controller/SettingsController.php' line 71 at <>
> 
> 0. /var/www/html/lib/private/AppFramework/App.php line 172
>    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Calendar\Con ... {}, "setConfig")
> 1. /var/www/html/lib/private/Route/Router.php line 298
>    OC\AppFramework\App::main("OCA\Calendar\ ... r", "setConfig", OC\AppFramework\ ... {}, ["view","calendar.settings.setConfig"])
> 2. /var/www/html/lib/base.php line 1047
>    OC\Route\Router->match("/apps/calendar/v1/config/view")
> 3. /var/www/html/index.php line 36
>    OC::handleRequest()
> 
> POST /index.php/apps/calendar/v1/config/view from XX.XX.XX.XX by admin at 2023-01-03T01:34:28+00:00

At first glance, this errors does not seem to be related to the original issue.

**Comment by halleypontes** [comment]
Thank you for your response. I can't access the Nextcloud installation folders /var/www from Linode (deployed through their marketplace app). It says directory doesn't exist. Any way to work around this? I have root access. Thank you.

> @halleypontes the error is from accessing the url directly? Can you please post the full log entry? You can find it in your nextcloud.log in your data directory.
> 
> 
> 
> From the other issue: 
> 
> 
> 
> ```
> 
> {
> 
>   "reqId": "XH5JPZQHzAEEskBLQ4SJ",
> 
>   "level": 3,
> 
>   "time": "2022-12-31T11:24:39+00:00",
> 
>   "remoteAddr": "89.69.69.250",
> 
>   "user": "capsel",
> 
>   "app": "index",
> 
>   "method": "POST",
> 
>   "url": "/index.php/apps/calendar/v1/config/view",
> 
>   "message": "OCA\\Calendar\\Controller\\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/custom_apps/calendar/lib/Controller/SettingsController.php' line 71",
> 
>   "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0",
> 
>   "version": "25.0.2.3",
> 
>   "exception": {
> 
>     "Exception": "Exception",
> 
>     "Message": "OCA\\Calendar\\Controller\\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/custom_apps/calendar/lib/Controller/SettingsController.php' line 71",
> 
>     "Code": 0,
> 
>     "Trace": [
> 
>       {
> 
>         "file": "/var/www/html/lib/private/AppFramework/App.php",
> 
>         "line": 172,
> 
>         "function": "dispatch",
> 
>         "class": "OC\\AppFramework\\Http\\Dispatcher",
> 
>         "type": "->",
> 
>         "args": [
> 
>           {
> 
>             "__class__": "OCA\\Calendar\\Controller\\SettingsController"
> 
>           },
> 
>           "setConfig"
> 
>         ]
> 
>       },
> 
>       {
> 
>         "file": "/var/www/html/lib/private/Route/Router.php",
> 
>         "line": 298,
> 
>         "function": "main",
> 
>         "class": "OC\\AppFramework\\App",
> 
>         "type": "::",
> 
>         "args": [
> 
>           "OCA\\Calendar\\Controller\\SettingsController",
> 
>           "setConfig",
> 
>           {
> 
>             "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
> 
>           },
> 
>           [
> 
>             "view",
> 
>             "calendar.settings.setConfig"
> 
>           ]
> 
>         ]
> 
>       },
> 
>       {
> 
>         "file": "/var/www/html/lib/base.php",
> 
>         "line": 1047,
> 
>         "function": "match",
> 
>         "class": "OC\\Route\\Router",
> 
>         "type": "->",
> 
>         "args": [
> 
>           "/apps/calendar/v1/config/view"
> 
>         ]
> 
>       },
> 
>       {
> 
>         "file": "/var/www/html/index.php",
> 
>         "line": 36,
> 
>         "function": "handleRequest",
> 
>         "class": "OC",
> 
>         "type": "::",
> 
>         "args": []
> 
>       }
> 
>     ],
> 
>     "File": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
> 
>     "Line": 165,
> 
>     "Previous": {
> 
>       "Exception": "TypeError",
> 
>       "Message": "OCA\\Calendar\\Controller\\SettingsController::setConfig(): Argument #2 ($value) must be of type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225",
> 
>       "Code": 0,
> 
>       "Trace": [
> 
>         {
> 
>           "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
> 
>           "line": 225,
> 
>           "function": "setConfig",
> 
>           "class": "OCA\\Calendar\\Controller\\SettingsController",
> 
>           "type": "->",
> 
>           "args": [
> 
>             "view",
> 
>             null
> 
>           ]
> 
>         },
> 
>         {
> 
>           "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
> 
>           "line": 133,
> 
>           "function": "executeController",
> 
>           "class": "OC\\AppFramework\\Http\\Dispatcher",
> 
>           "type": "->",
> 
>           "args": [
> 
>             {
> 
>               "__class__": "OCA\\Calendar\\Controller\\SettingsController"
> 
>             },
> 
>             "setConfig"
> 
>           ]
> 
>         },
> 
>         {
> 
>           "file": "/var/www/html/lib/private/AppFramework/App.php",
> 
>           "line": 172,
> 
>           "function": "dispatch",
> 
>           "class": "OC\\AppFramework\\Http\\Dispatcher",
> 
>           "type": "->",
> 
>           "args": [
> 
>             {
> 
>               "__class__": "OCA\\Calendar\\Controller\\SettingsController"
> 
>             },
> 
>             "setConfig"
> 
>           ]
> 
>         },
> 
>         {
> 
>           "file": "/var/www/html/lib/private/Route/Router.php",
> 
>           "line": 298,
> 
>           "function": "main",
> 
>           "class": "OC\\AppFramework\\App",
> 
>           "type": "::",
> 
>           "args": [
> 
>             "OCA\\Calendar\\Controller\\SettingsController",
> 
>             "setConfig",
> 
>             {
> 
>               "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
> 
>             },
> 
>             [
> 
>               "view",
> 
>               "calendar.settings.setConfig"
> 
>             ]
> 
>           ]
> 
>         },
> 
>         {
> 
>           "file": "/var/www/html/lib/base.php",
> 
>           "line": 1047,
> 
>           "function": "match",
> 
>           "class": "OC\\Route\\Router",
> 
>           "type": "->",
> 
>           "args": [
> 
>             "/apps/calendar/v1/config/view"
> 
>           ]
> 
>         },
> 
>         {
> 
>           "file": "/var/www/html/index.php",
> 
>           "line": 36,
> 
>           "function": "handleRequest",
> 
>           "class": "OC",
> 
>           "type": "::",
> 
>           "args": []
> 
>         }
> 
>       ],
> 
>       "File": "/var/www/html/custom_apps/calendar/lib/Controller/SettingsController.php",
> 
>       "Line": 71
> 
>     },
> 
>     "CustomMessage": "--"
> 
>   },
> 
>   "id": "63b01c028a013"
> 
> }
> 
> ```
> 
> 
> 
> Looks like the view param isn't working right.

**Comment by rohano17** [comment]
Seams to be a wrong construction of the URL(Calender name "small"):
In nextloud webpage not working:
https://<mydomain>.noho.st/nextcloud/apps/calendar/nextcloud/remote.php/dav/calendars/lutz/small/?export
working in separate browser tab:
https://<mydomain>.noho.st/nextcloud/remote.php/dav/calendars/lutz/small/?export
or by deleting manually apps/calendar/nextcloud/ from the URL produced in nextcloud calender app,
also works for me.

**Comment by halleypontes** [comment]
> Seams to be a wrong construction of the URL(Calender name "small"): In nextloud webpage not working: https://mydomain.noho.st/nextcloud/apps/calendar/nextcloud/remote.php/dav/calendars/lutz/small/?export working in separate browser tab: https://mydomain.noho.st/nextcloud/remote.php/dav/calendars/lutz/small/?export or by deleting manually 'apps/calendar/nextcloud/' from the URL produced in nextcloud calender app, also works for me.

The issue has now been fixed with the latest update of the Calendar app (v 4.2.1). Glad it wasn't a problem with my setup.
