### ISSUE TITLE
When sharing calendar to group it does not show up

### ISSUE THREAD

**Issue by cazee** [nextcloud/calendar#485]
On a fresh nextcloud 12.0.0 installation with calendar app 1.5.3 enabled, i have an issue when sahring the calendar to a group. It does not show up for the group members when they open their calender app. It does show up, when I share the calendar with them directly.

### Steps to reproduce
1. share calendar to a group
2. log on with a group members account
3. open calendar app

### Expected behaviour
user sees the shared calendar

### Actual behaviour
user does not see the shared calendar

### Server configuration
**Operating system**:

**Web server:** apache

**Database:** MySQL

**PHP version:** 7.1.1

**Server version:** 12.0.0

**Calendar version:** 1.5.3

**Updated from an older installed version or fresh install:** fresh

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
```

**Nextcloud configuration:**

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox 53.0.3

**Operating system:** windows 10

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

Please also mention the groups name
