### ISSUE TITLE
Continuos spamming of iMIP invitation emails

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#4867]
### Steps to reproduce

Under certain circumstances which I haven't completely understood yet, the scheduling logic is continuosly triggered for VEVENTs, leading to continuos spamming of iMIP emails to all attendees.

This might be combo of another bug and some new behaviour.

My current theory is that it has to do with the SCHEDULE-AGENT.

The UID is 5bcd4a2217bf78b4a316823701142d5f4537a51d, still waiting on a full ics for the VEVENT.

Putting this in Calendar as it might be the Calendar app itself that triggers the changes? Havent investigated that yet.

THEORY!!! We have shortened mail addresses and longer ones.

I have two attendee entries here for the same email:

```
ATTENDEE;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=SM;SCHEDULE-STATU
 S=1.1;ROLE=:mailto:sm@nextcloud.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE;SCHEDULE-STATUS=1
 .1:mailto:sm.withlastname@nextcloud.com
```

Still doesn't explain why the email is sent again and again but it could be a start.

### Expected behavior

The iMIP logic is triggered once

### Actual behaviour

An iMIP email is triggered every 5 minutes.

### Calendar app version

v4.2.0-rc1

### CalDAV-clients used

Thunderbird, Web

### Server operating system

c.nc

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

### Web server error log

```Text
Nothing in the logs
```

### Log file

```Text
Nothing in the logs
```

### Browser log

```Text
Nothing in the logs
```

**Comment by pierreozoux** [comment]
@miaulalala it looks a lot like:
https://github.com/nextcloud/calendar/issues/4875

I will close as duplicate, but feel free to reopen, or comment if you feel I'm wrong.
