### ISSUE TITLE
Feature Request: Show group details (e.g. members)

### ISSUE THREAD

**Issue by brunt82** [nextcloud/calendar#487]
### Steps to reproduce
1. Create a group 1 and add the users user A, user B and user C to this group.
2. Now user A creates a new calendar and share it with the group 1.
3. User B and user C get the new calendar of group 1 automatically (cool). 

### Expected behaviour
An additional menu option with the option "Details". This will contain information like:
- Owner of the group (the group description may be changed by the user)
- sharing information (in this case it is shared with "group 1", which may be expanded to list the users)
- calendar exists since ...
- ...

### Actual behaviour
Currently group members has no possibility to find out, who is member of the group. The search option only displays users, not groups.

### Client configuration
**Browser:** Chrome, FF

**Comment by georgehrke** [comment]
> Owner of the group (the group description may be changed by the user)

This will be provided in Calendar 2.0 with Vue.
see https://github.com/nextcloud/calendar/pull/926#issuecomment-442797815

> sharing information (in this case it is shared with "group 1", which may be expanded to list the users)

This is something we don't want. You should not be able to tell who else is in a system-group. You can use Circles instead.

> calendar exists since ...

We don't store that information, but if you use Activity you can check in your activity stream.
