### ISSUE TITLE
ENCODING=QUOTED-PRINTABLE fails to import an .ics

### ISSUE THREAD

**Issue by Rilgamon** [nextcloud/calendar#4871]
### Steps to reproduce

1. Trying to import an .ics (see attachment) with a list of trash collecting dates fails
[abfallkalender.ics.txt](https://github.com/nextcloud/calendar/files/10332128/abfallkalender.ics.txt)
2. After removing ;ENCODING=QUOTED-PRINTABLE from the .ics import works

### Expected behavior

Should import flawless

### Actual behaviour

Import fails

### Calendar app version

4.2.0

### CalDAV-clients used

nextcloud calendar app

### Browser

all

### Client operating system

linux

### Server operating system

debian

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
Can you share your logs?

**Comment by Rilgamon** [comment]
```
[webdav] Fehler: Sabre\DAV\Exception\UnsupportedMediaType: Validation error in iCalendar: ENCODING=QUOTED-PRINTABLE is not valid for this document type. at <<closure>>

 0. /var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php line 766
    Sabre\CalDAV\Plugin->validateICalendar()
 1. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\CalDAV\Plugin->beforeCreateFile()
 2. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1094
    Sabre\DAV\Server->emit()
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 504
    Sabre\DAV\Server->createFile()
 4. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPut()
 5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
 8. /var/www/nextcloud/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
 9. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
10. /var/www/nextcloud/remote.php line 171
    require_once("/var/www/nextcl ... p")
```

**Comment by miaulalala** [comment]
Right, looks like the 3rd party librar doesn't understand the ENCODING param even though it's part of the [standard](https://datatracker.ietf.org/doc/html/rfc5545#section-3.2.7).

An upstrream PR might be in order, but I don't have time at the moment :/

You could either try to make one happen yourself at https://github.com/sabre-io/dav/ - you could make the changes to the \VObject\Component\VEvent::getValidationRules method and add the ENCODING parameter. This would also mean either decoding the parameter before continuing on with the calendaring logic so we can display it without a hassle everywhere else, or adding code to the frontend on our side.

Or it might take some time for a fix.

If you want to give it a shot I will be more than happy to helpy ou get this done :)

**Comment by Rilgamon** [comment]
It took me three years to submit it as a bug because of my limited time.
I'll take a look into the library but cant promise anything.
Seems nobody else cared all this time so its no problem to wait a little longer.

**Comment by Rilgamon** [comment]
For now I opened a ticket to remind me to look into this https://github.com/sabre-io/dav/issues/1435

**Comment by miaulalala** [comment]
Thanks a ton!

**Comment by tcitworld** [comment]
The issue is not with Sabre, which understands the `ENCODING` parameter correctly, but with your file, which doesn't respect the standard.
The only values allowed for `ENCODING` in an iCalendar document are `8BIT` and `BASE64` as per the specification @miaulalala linked to. That's what Sabre restricts it to in the following code: https://github.com/nextcloud/3rdparty/blob/57f68f13ac9e67941f7b7d52b2363548f277f2ae/sabre/vobject/lib/Property.php#L566-L567

You may close the above linked issue.

What's the source of the provided .ics file? The [product identifier](https://datatracker.ietf.org/doc/html/rfc5545#section-3.7.3) isn't really helpful (`Foobar Corporation//NONSGML Foobar`). If it's a common issue, we can try to repair the file before importing it.

**Comment by miaulalala** [comment]
Damn, looks like I didn't read the standard right - thanks for checking and correcting me!

**Comment by twobaker** [comment]
Hi,
Perhaps it is not explicitly included in the standard. But I have also received individual calendar entries from a service provider that contain SUMMARY;ENCODING=QUOTED-PRINTABLE: and then cannot be read in. It might therefore be a good idea to intercept this. The ENCODING comes from [RFC2045](https://datatracker.ietf.org/doc/html/rfc2045#section-6.7), if I am interpreting this correctly. I don't know if it has anything to do with the calendar entry being sent by email (MIME encoding).

The application could probably avoid some errors if it could interpret these entries.

Thank you
