### ISSUE TITLE
Feature Request: Show categories

### ISSUE THREAD

**Issue by brunt82** [nextcloud/calendar#488]
### Steps to reproduce
1. Connect Nextcloud with an CalDAV-Client, which supports categories (like TB or Outlook)
2. Create an event and add a category for it.
3. Open web client but categories are not displayed.

### Expected behaviour
The added categories of an event are displayed (e.g. in event details).

### Actual behaviour
There are no categories in web client. But important: the categories will **not** disappear while editing the event with the web client and re-synchronizing with the CalDAV-Client. 

### Client configuration
**Browser:** Chrome, FF

**CalDAV-clients:** Thunderbird 52, Outlook 2016

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/107

**Comment by brunt82** [comment]
Sorry. I searched for similar issues for the first issues, but not for this. :-(
