### ISSUE TITLE
calendar deletion not working

### ISSUE THREAD

**Issue by JojoBr0** [nextcloud/calendar#4886]
### Steps to reproduce

1. open new settings modal
2. press delete button

### Expected behavior

remove the selected calendar

### Actual behaviour

calendar can't be deleted error

### Calendar app version

4.2.1

### Browser

Brave 1.46.144

### Client operating system

Windows 11

### Server operating system

Ubuntu 22.04

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.2

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by miaulalala** [comment]
Any logs / error messages please? Either from your console or nextcloud log :pray:

**Comment by JojoBr0** [comment]
console error:
![calendar_deletion_error](https://user-images.githubusercontent.com/92635650/211013668-a062dbfd-05e1-4e7a-bb04-dff37a47ea26.png)

no error in nextcloud log

**Comment by JojoBr0** [comment]
after some more investigation I found out that the error was caused by a wrong setting in the web server by myself
