### ISSUE TITLE
UI for editing calendar shares' name loses focus on every character typed

### ISSUE THREAD

**Issue by e-jim** [nextcloud/calendar#4890]
### Steps to reproduce

1. Edit a share's name
2. Modify "rapidly" (I'm not a pro typer) the name of the calendar

### Expected behavior

The new name should reflect what has been typed

### Actual behaviour

The focus is lost for half a second for every character that is being typed. 
Hence, the field "loses" some input.
It only works if you type very slowly.

For example, here I typed (or tried to) "This is the new name":

[Github.webm](https://user-images.githubusercontent.com/5951377/211544229-425223b6-70bc-4d74-a68a-001c66204623.webm)

### Calendar app version

4.2.1

### Browser

Firefox 108.0.2

### Client operating system

Debian Linux and Windows

### Server operating system

Ubuntu Server 20.04

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 7.4

### Nextcloud version

25.0.2

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by ChristophWurst** [comment]
this is the new sharing dialoge. @st3iny can you reproduce?

**Comment by st3iny** [comment]
Yes, I can reproduce the issue on latest main.

**Comment by oktayacikalin** [comment]
For me, it's even worse - the focus won't come back. So for now I have to write the name down somewhere else, copy and paste it here.

**Comment by raimund-schluessler** [comment]
I don't know if it's related or even the cause, but after every character typed, a `PROPPATCH` to the server is sent, to save the name changed. So you can only type the next character after the request finished, I guess. I think it would be better to save the name only after the modal is closed, or at least debounce the requests, so it happens maybe a second after the last character typed.

**Comment by st3iny** [comment]
> I don't know if it's related or even the cause, but after every character typed, a `PROPPATCH` to the server is sent, to save the name changed. So you can only type the next character after the request finished, I guess. I think it would be better to save the name only after the modal is closed, or at least debounce the requests, so it happens maybe a second after the last character was typed.

Good catch! Actually, what you proposed is supposed to happen. Maybe the debounce logic is broken.

**Comment by raimund-schluessler** [comment]
@st3iny This issue became better with #4894, but it is not completely fixed yet. If you stop typing for a second now, `saveNameDebounced` kicks in, saves the name and the input loses focus. So you cannot type further directly, you have to click the input field again. That is a bit annoying. The name should simply be saved in the background, without interfering with the input.

The other possibility would be to save changes to the calendar only after you confirm saving them, e.g. with a save button. But that would be a different design approach and I don't know what was decided here.

**Comment by st3iny** [comment]
> @st3iny This issue became better with #4894, but it is not completely fixed yet. If you stop typing for a second now, `saveNameDebounced` kicks in, saves the name and the input loses focus. So you cannot type further directly, you have to click the input field again. That is a bit annoying. The name should simply be saved in the background, without interfering with the input.
> 
> The other possibility would be to save changes to the calendar only after you confirm saving them, e.g. with a save button. But that would be a different design approach and I don't know what was decided here.

The input should not be disabled during saving. This fixes this issue once and for all.
