### ISSUE TITLE
Display Day of the week in list view on the left next to the date

### ISSUE THREAD

**Issue by jdaviescoates** [nextcloud/calendar#4891]
### Is your feature request related to a problem? Please describe.

Feature request. When viewing in list view (my default and preferred view), I'd like the Day or the week to also be displayed in the lefthand side instead of all the way to the right.

### Describe the solution you'd like

I'd like the Day of the week to be displayed alongside the date here:
![image](https://user-images.githubusercontent.com/7427347/212674198-a0066309-689a-4c69-b541-691b04925ece.png)

**Comment by miaulalala** [comment]
I have the day displayed, but on the rightmost side. Do you have that too?

![image](https://user-images.githubusercontent.com/7427347/212669888-a087e87a-d5ed-4717-9d80-80cdda9f2195.png)

**Comment by jdaviescoates** [comment]
> I have the day displayed, but on the rightmost side. Do you have that too?
> 
> ![image](https://user-images.githubusercontent.com/7427347/212669888-a087e87a-d5ed-4717-9d80-80cdda9f2195.png)

Hah, I do! I don't know how I missed that, thanks!

I think I'd still prefer it to be on the left hand side alongside the date, but I guess I can close this now then! :laughing:

**Comment by SakshiT25** [comment]
Hello @miaulalala, would like to work on this issue if it's still open and nobody's working on it.

**Comment by miaulalala** [comment]
Thanks @SakshiT25 that would be awesome!

@nextcloud/designers any input on the design?

Something like this?

| Before | After | 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/7427347/214039209-d6025270-2c4f-45c6-a248-b9a9473cd26a.png) | ![image](https://user-images.githubusercontent.com/7427347/214039107-9781f146-c70d-44fc-b5f0-ae50d58e2f28.png) |

And then remove the Day of the week from the right hand side?

**Comment by jancborchardt** [comment]
Yes, sounds good! :) I would slightly adjust the format like this so it’s more easy to scan for the date number:
> 1. January 2023, Friday
> 2. January 2023, Saturday
> 3. January 2023, Sunday

So "date, day" instead of the other way around.

**Comment by SakshiT25** [comment]
@miaulalala Hey. Can you please assign me this issue? I'm not able to access the .js files.
Thank you.

**Comment by miaulalala** [comment]
> @miaulalala Hey. Can you please assign me this issue? I'm not able to access the .js files. Thank you.

You're going to need to set up a dev environment and create a pull request if you'd like to implement changes :) we don't edit directly on github, but you can fork the app and create a PR in the fork. This should allow you to create a branch directly from GH if you so desire, but you could also setup a proper dev environment: https://help.nextcloud.com/t/tutorial-how-to-set-up-a-nextcloud-development-environment-on-mac-or-ubuntu/145462

**Comment by SakshiT25** [comment]
@miaulalala @jancborchardt Hey, Thanks for your above instructions, I tried following the same and was able to set up the environment as mentioned. However, I might be needing your help in order to reproduce the issue so that we can identify the exact file where the changes need to be done, could you please help me with this info?
I was able to find the files appnavigationheader.js and ViewList.vue which might need to be updated but I wanted to be sure if I am heading in the right direction and thus need your inputs for the same. Thanks In advance!!

**Comment by SakshiT25** [comment]
@miaulalala @jdaviescoates @jancborchardt @ChristophWurst Hey. Just wanted to follow up on the above, do we have any inputs on it? Thank you.

**Comment by miaulalala** [comment]
Hi @SakshiT25 , looks like the list view is in Fullcaledar, a library. We adjust the width of the columns here: apps/calendar/src/fullcalendar/rendering/dayHeaderDidMount.js:29

That might gibe you a starting point. Then you probably need to ajust some css.

**Comment by SakshiT25** [comment]
Hey, my apologies I was out sick last week. 
I'm trying to reconnect to the environment but am not able to connect to the server and it's getting stuck on this page. (attached below)
I also tried reinstalling docker and rebooting the system but still facing the same issue.
<img width="1440" alt="Screenshot 2023-04-18 at 11 09 22 AM" src="https://user-images.githubusercontent.com/65718952/232681662-efa5f389-a555-4995-b769-7a271aaf688b.png">

**Comment by miaulalala** [comment]
Looks like your install script is stalling. What's in your nextcloud logs? you can find them in your root in the data folder.

**Comment by SakshiT25** [comment]
These are logs in the Docker container.
<img width="1440" alt="Screenshot 2023-04-18 at 5 10 46 PM" src="https://user-images.githubusercontent.com/65718952/232782036-8ce900f6-6a71-4fef-9ebb-ac113463fc80.png">

**Comment by miaulalala** [comment]
This looks close: https://github.com/linuxserver/docker-nextcloud/issues/280

**Comment by SakshiT25** [comment]
Hey, I raised the PR on the 21st. Kindly acknowledge.
Thank you.

**Comment by miaulalala** [comment]
> Hey, I raised the PR on the 21st. Kindly acknowledge. Thank you.

Hi @SakshiT25 , please see my colleague's comment here: https://github.com/nextcloud/calendar/pull/5138#issuecomment-1516075391
