### ISSUE TITLE
Feature Request: Setting default timezone for new event

### ISSUE THREAD

**Issue by b3** [nextcloud/calendar#490]
When creating a new event, the timezone used for the event is not the one I would like to use nor the one of the host computer. In my case every-time I created a new event it is attached to *Europe/Berlin*, when my host and (real timezone) is *Europe/Paris*. I thus have to modify the Timezone manually for every new event.

One should be able to set the default timezone to use for new event (if one work mainly overseas for instance).

The app should have a way to set the default timezone somewhere.

I am using Nextcloud 12.0.0 and Calendar 1.5.3.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/issue_template.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md)

**Comment by georgehrke** [comment]
> The app should have a way to set the default timezone somewhere.

I don't agree with that. We should rather fix the bug, that we detect the wrong timezone for you ;)

**Comment by b3** [comment]
Why not. In that case any idea how the timezone is detected? By Calendar or by the core Nextcloud?

**Comment by georgehrke** [comment]
We use a library called [jstz](https://bitbucket.org/pellepim/jstimezonedetect). The latest calendar release 1.5.3 still ships version 1.0.5 of jstz. The upcoming 1.6.0 calendar will ship 1.0.6 (jstz).

I'm very sure that the update will already fix your issue.

**Comment by georgehrke** [comment]
Does this website show you Europe/Berlin or Europe/Paris?

https://pellepim.bitbucket.io/jstz/

**Comment by b3** [comment]
Europe/Berlin

**Comment by JuliusFreudenberger** [comment]
jstz does not care about your gdop
geographic location as long as the time zone is correct 
This is explained here: https://pellepim.bitbucket.io/jstz/

**Comment by georgehrke** [comment]
closing in favor of https://github.com/nextcloud/calendar/issues/586
