### ISSUE TITLE
Feature Request: Ability to choose what event to delete (on deleting a recurrent event)

### ISSUE THREAD

**Issue by b3** [nextcloud/calendar#491]
When one is to delete a particular event on a recurrent event (event with periodic repetition), then the full event is detroyed (will all occurences).

In other calendar tools in such case the app ask if one would like to destroy :
* only this event
* every further events
* all events

IMHO, Calendar should mimic this globally accepted behavior.

**Comment by georgehrke** [comment]
@b3 Please use the search function before creating new issues ;)

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/7

**Comment by b3** [comment]
I did it, but I missed this one.

Sorry.

**Comment by patricktokeeffe** [comment]
fwiw, the search results direct people here since #7 summary doesn't contain relevant search terms
