### ISSUE TITLE
Feature Request: Allow to choose the final date of a repetition when creating a new event

### ISSUE THREAD

**Issue by b3** [nextcloud/calendar#492]
When creating a new event which must be repeated (with multiple occurences) the only choices to set the end is :
* never
* after *n* repetitions

One easier experience should to also have a third choice enabling the user to choose the date of the last repetition (preferably with a clickable calendar) as it is the case in a lot of calendar tool.

Using nextcloud 12.0.0 and Calendar 1.5.3.

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/10

**Comment by b3** [comment]
OK I definitively need to wear my glasses, I missed this one too.

Sorry again.

**Comment by patricktokeeffe** [comment]
Don't feel bad - there are no keywords in #10 only screenshots so it doesn't show up in searches.
