### ISSUE TITLE
disableAppointments ignored in 4.2.1

### ISSUE THREAD

**Issue by pboguslawski** [nextcloud/calendar#4922]
### Steps to reproduce

1. Disable appointments feature `occ config:app:set calendar disableAppointments --value='yes'`

### Expected behavior

No appointments feature in UI.

### Actual behaviour

Appointments feature present in UI.

### Calendar app version

4.2.1

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

### Additional info

No such problem in v3.5.0.

**Comment by tcitworld** [comment]
Fixed in https://github.com/nextcloud/calendar/pull/4916
