### ISSUE TITLE
Failing integrity check after upgrade from owncloud 9.1.5 to 9.1.6

### ISSUE THREAD

**Issue by paulstewartis** [nextcloud/calendar#493]
### Steps to reproduce
1. Upgrade ownCloud from version 9.1.5 to 9.1.6 using the web interface.
2. Re-enable calendar app.
3.

### Expected behaviour
After upgrading and enabling the app, the app should work normally and pass integrity check.

### Actual behaviour
App is failing integrity check.

### Server configuration

**Operating system**: OpenSUSE Leap 42.2

**Web server:** Apache/2.4.23

**Database:** mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:** PHP 7.0.7

**Server version:** (see your admin page) 9.1.6

**Calendar version:** (see the apps page) 1.4.1

**Updated from an older installed version or fresh install:** 9.1.5

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.

```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: true
  - dav: 0.2.7
  - documents: 0.13.1
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - news: 9.0.4
  - notifications: 0.3.0
  - ownnote: 1.08
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "515dfc4320244",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/srv\/owncloud_data",
        "dbtype": "mysql",
        "version": "9.1.6.2",
        "installed": true,
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "maintenance": false,
        "singleuser": false,
        "forcessl": true,
        "theme": "",
        "trusted_domains": [
            "some.host.name",
            "192.168.1.114"
        ],
        "mail_smtpmode": "php",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "paul",
        "mail_domain": "some.host.name",
        "overwrite.cli.url": "\/owncloud\/",
        "appstore.experimental.enabled": true,
        "loglevel": 3,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/owncloud"
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome Version 58.0.3029.110 (64-bit)

**Operating system:** OpenSUSE Leap 42.2

**CalDAV-clients:** iPhone

**Comment by georgehrke** [comment]
This is the [Nextcloud](https://nextcloud.com) calendar bug tracker. The nextcloud calendar app only supports Nextcloud. If you have an issue with the ownCloud calendar, please report a bug at their bug tracker.
