### ISSUE TITLE
calendar.tar.gz contains unnecessary  img/.DS_Store file

### ISSUE THREAD

**Issue by hannob** [nextcloud/calendar#494]
The nextcloud calendar plugin contains a .DS_Store file, which is a metadata file from OS X finder. This shouldn't cause any problems, but it is unnecessary and should be removed.

The file is not part of the git repository and actually the .gitignore file already contains .DS_Store and thus tries to make sure such files don't get committed. So it seems this got introduced somewhere in the process from repository to tarball.

**Comment by georgehrke** [comment]
Good catch! thx for reporting.
