### ISSUE TITLE
Notifications not being sent to group for group calendar event

### ISSUE THREAD

**Issue by colans** [nextcloud/calendar#4945]
### Steps to reproduce

1. Create a group.
2. Add members to the group.
3. Create a calendar for the group.
4. Add a recurring event.
5. Add an e-mail notification.

### Expected behavior

An e-mail notification gets gets sent to everyone in the group.

We're not relying on attendees here because of https://github.com/nextcloud/server/pull/15676 so notifications should go to group members, right?

### Actual behaviour

No e-mail gets sent.

### Calendar app version

3.5.2

### CalDAV-clients used

The Web app

### Browser

Firefox 109.0 (64-bit)

### Client operating system

Pop!_OS (essentially Ubuntu) GNU/Linux

### Server operating system

Debian

### Web server

Apache

### Database engine version

None

### PHP engine version

None

### Nextcloud version

23.0.1

### Updated from an older installed version or fresh install

Updated from an older version

### Additional info

I didn't fill in info that didn't seem relevant, but I can get details if necessary (just not easily).

**Comment by tcitworld** [comment]
IIRC, reminder emails are always sent to attendees only, not sharees.

**Comment by colans** [comment]
So maybe this is a feature request then, and not a bug.  In any case, if attendees don't make sense in a group context (see https://github.com/nextcloud/server/issues/26668), then shouldn't we be relying on the group members for performing actions such as sending notifications?

**Comment by ChildLearningClub** [comment]
I think related to #2329. @colans do you have "Share reminder notifications to calendar shares as well"

![Screenshot 2023-06-07 091143](https://github.com/nextcloud/calendar/assets/25701774/fb857b98-3338-4212-aae3-381506aa4c15)
You can find these settings in the "Groupware" section on the "Administration settings"

It is also not made clear and I propose that the devs consider making this easier to understand from within Nextcloud itself but in the [calendar documentation](https://docs.nextcloud.com/server/19/user_manual/pim/calendar.html#setup-reminders):  
you will find this note:

![Screenshot 2023-06-07 113230](https://github.com/nextcloud/calendar/assets/25701774/c89a435a-923a-4553-8e4c-dbbebe32b34f)

Which means that whoever you want to get the reminders has to have the "can edit" box enabled

![Screenshot 2023-06-07 113524](https://github.com/nextcloud/calendar/assets/25701774/bd2cc987-cf31-4635-9782-b4f1311caea3)

What also has not been made clear is that for the user you are sharing the calendar with that now is able to get notifications, but also edit the calendar, is that when they do make edits it changes the master calendar. So there is currently no way for them to edit the calendar with their own desired notifications or whatever without changing it for everyone. I suppose creating a shared calendar that is shared and at the same time a copy to allow for individual user customization is not an easy task.

**Comment by colans** [comment]
@ChildLearningClub Thanks for this, but I don't appear to have that option in the settings:

![image](https://github.com/nextcloud/calendar/assets/1258265/2eda879b-87a2-4672-a9d4-ad26ad1d358f)

This is core version 23.0.1, and Calendar 3.5.7.  Are these too old?

**Comment by ChildLearningClub** [comment]
@colans I think that might be the case, I do believe these options became available in one of the later releases. Is there some reason you are not on one of the more recent ones?

**Comment by colans** [comment]
I didn't even know we were on an old version.  I'm currently discussing upgrade options with our provider.  Thanks for helping me figure it out.  I can report back afterwards.

**Comment by colans** [comment]
We upgraded, those options are there, and I haven't heard any complaints.
