### ISSUE TITLE
unable to sync calendar through CalDav if TOTP (2FA) is enabled

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/calendar#4946]
### Steps to reproduce

1. Enable TOTP (2FA) in the nextcloud instance
2. Try to sync the calendar with outlook using CalDAV synchronizer connecting to the private calendar link
3. the app synchronizer will trigger an authentication error.
4. If TOTP (2FA) is disabled, everything will work perfectly

### Expected behavior

There could be a way to sync the calendar using CalDAV having TOTP enabled.

### Actual behaviour

the CalDav synchronizer will trigger an authentication error.

### Calendar app version

4.2.3

### CalDAV-clients used

CalDav Synchronizer for Outlook

### Browser

Chrome

### Client operating system

Windows 10

### Server operating system

Docker

### Web server

Nginx

### Database engine version

MySQL

### PHP engine version

PHP 8.0

### Nextcloud version

25.0.1

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - approval: 1.0.12
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.3
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - collectives: 2.2.1
  - comments: 1.15.0
  - contacts: 5.0.3
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_lock: 24.0.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - forms: 3.0.4
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - notifications: 2.13.1
  - notify_push: 0.5.0
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
   - previewgenerator: 5.1.1
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - serverinfo_hetzner: 1.16.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.3
  - suspicious_login: 4.3.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
   - twofactor_totp: 7.0.0
  - viewer: 1.9.0
   - weather_status: 1.5.0
   - workflowengine: 2.7.0
Disabled:
   - encryption
  - firstrunwizard: 2.12.0
  - nextcloud_announcements: 1.12.0
  - photos: 2.0.0
  - privacy: 1.7.0
  - recommendations: 1.3.0
  - support: 1.6.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - updatenotification: 1.14.0
   - user_ldap
  - user_status: 1.4.0
```

**Comment by tcitworld** [comment]
That's intended. There's no way to use CalDAV with your main password and 2FA.
You need to use an app password, see https://docs.nextcloud.com/server/latest/user_manual/en/session_management.html#managing-devices

**Comment by vagner-dias** [comment]
Oh! it is in the very ending of the screen. I did not see that!

thank you!
