### ISSUE TITLE
Calendar App Sharing Auto-Complete Doesn't Show Users

### ISSUE THREAD

**Issue by ProjectMoon** [nextcloud/calendar#4970]
### Steps to reproduce

1. Create calendar.
2. Click edit calendar on left side of screen.
3. Try typing username into sharing box.

### Expected behavior

The username typed should come up. Clicking user should add the user to a list of people the calendar is shared with.

### Actual behaviour

Either the wrong or no username comes up. Groups do show up, though. When you click on a result from the auto-complete, the user/group doesn't get added to the sharing list. (in fact, sharing list is rendering as empty on other calendars too).

Checking the network traffic in the browser developer tools shows that auto-complete API endpoint is called, and correct results returned. These do not show up in the UI, though.

### Calendar app version

4.2.3

### Browser

Firefox 109

### Client operating system

Gentoo Linux, Ubuntu Linux

### Server operating system

Docker

### Web server

Other

### Database engine version

None

### PHP engine version

None

### Nextcloud version

25.0.3

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by ProjectMoon** [comment]
This is from a Hetzner storage share. I'm not sure if I can get the Nextcloud log from it. But if I can, I will add it later.

**Comment by gv-sothebys-jeffverk** [comment]
This can be closed. It was due to cosmetic filtering in uBlock Origin.

**Comment by ProjectMoon** [comment]
This can be closed. It was due to cosmetic filtering in uBlock Origin.
