### ISSUE TITLE
Feature request: Clone an entry to a new date

### ISSUE THREAD

**Issue by macemoneta** [nextcloud/calendar#499]
Would like the ability to clone a calendar entry, with all reminders, etc. to a new date.

This is distinct from a repeating event since changes to one entry are not propagated to the repeated entries.

An example would be a bill that has to be paid periodically, but not on the same date (or day of the week). Each entry could then be edited to have its own annotations (e.g., title, description).

Essentially, it's a copy/paste for the entire entry, not just a field.

**Comment by georgehrke** [comment]
@macemoneta please use the search function before creating new issues ;)

**Comment by georgehrke** [comment]
dup of #113 

This will be implemented along #17
