### ISSUE TITLE
Calendar Exception OC\IntegrityCheck\Exceptions\InvalidSignatureException

### ISSUE THREAD

**Issue by viceldan** [nextcloud/calendar#500]
### Steps to reproduce
1. Updating Owncloud to version 9.1
2. 
3.

### Expected behaviour
Calendar should work in the same way as before

### Actual behaviour
Code integrity check failed, a warning with that message came up.
Click on 'list invalid files' shows Exception for calendar.

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
Server Version: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g
**Database:**
mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:**
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Server version:** (see your admin page)
ownCloud 9.1.6 (stable)
**Calendar version:** (see the apps page)
1.4.1
**Updated from an older installed version or fresh install:**

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.

Raw output
==========
Array
(
    [calendar] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate has been revoked.
                )
        )
)
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - documents: 0.13.1
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.4
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - onlyoffice
  - user_external
  - user_ldap

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment]
see #498

**Comment by tilghman** [comment]
For those of us who got to this issue by searching the error message (albeit for other modules), the correct course of action is to delete the offending modules from the apps/ directory, as upgrading from Owncloud to Nextcloud did not result in their automatic deletion.
