### ISSUE TITLE
new event dialog changed to 12-hour format instead of 24-hour format

### ISSUE THREAD

**Issue by sonologic** [nextcloud/calendar#501]
### Steps to reproduce
1. Upgrade to nextcloud 12.0 w/ calendar 1.5.3
2. Create calendar
3. Create event in calendar

### Expected behaviour
Time selection is in 24-hour format (15:30).

### Actual behaviour
Time selection is in 12-hour format (3:30 PM).

### Server configuration

**Operating system**:
FreeBSD 11.0-RELEASE-p9

**Web server:**
nginx-1.12.0_3,2

**Database:**
mariadb100-server-10.0.31

**PHP version:**
php70-7.0.19

**Server version:** (see your admin page)
12.0.0

**Calendar version:** (see the apps page)
1.5.3

**Updated from an older installed version or fresh install:**
Update from 11.0.3

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap

```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "5259541d194ce",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/usr\/home\/owncloud\/data",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "trusted_domains": [
            "cloud.metro.cx"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**

Firefox 52.0.2 (64-bit)

**Operating system:**

Ubuntu 16.04.2 LTS

**CalDAV-clients:**

n/a

#### Web server error log
```
n/a
```

#### Log file (data/nextcloud.log)
```
n/a
```

#### Browser log
```
n/a
```

**Comment by georgehrke** [comment]
see https://github.com/nextcloud/calendar/issues/283
