### ISSUE TITLE
Can no longer specify specific color value for calendar

### ISSUE THREAD

**Issue by dinandmentink** [nextcloud/calendar#5013]
### Steps to reproduce

1. Create a new calendar or update an existing one.
2. Click the color to change it.
3. There's no longer a hex input. 

### Expected behavior

There used to be an option to enter a hexadecimal color value. Although I can still select any color I can not specifically set it to exactly the hexadecimal value I want:

![image](https://user-images.githubusercontent.com/17289887/220857144-71c9187f-40be-4b79-b2c2-7b868fda4516.png)

### Actual behaviour

I would like to be able to set a hexadecimal rgb value, or some other input like hsl, rgb, as long as I can specify the value.

### Calendar app version

4.2.4

### Browser

Chromium and Firefox

### Client operating system

Ubuntu (don't think it differs with windows or mac though).

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

25.0.3

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
@st3iny could this be because of https://github.com/nextcloud/calendar/pull/5008?

**Comment by st3iny** [comment]
> @st3iny could this be because of #5008?

Hmm, this PR doesn't change the frontend. I'll give it a test.

**Comment by st3iny** [comment]
This is a change in our nextcloud-vue component library. The "advanced" fields are now hidden by default.

Ref https://github.com/nextcloud/nextcloud-vue/pull/3324

**Comment by dinandmentink** [comment]
Wow. I'm impressed by the turn-around time on this issue. Thanks!

**Comment by xteaun** [comment]
So how do I turn on the advanced color picker? I only see the basic one on a fresh install.

**Comment by dinandmentink** [comment]
No new version of calendar was released since this fix was merged.

**Comment by xteaun** [comment]
> No new version of calendar was released since this fix was merged.

Oh, so I have to wait for a new version? Okay! Thanks for your reply! :)
