### ISSUE TITLE
Event update is sent (via email) only if date/time changes (not on title/description/location change)

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/calendar#5047]
### Steps to reproduce

Consider two users: Bob is internal, Alice external user.
1. Bob creates an event, and invites Alice, via her email address.
2. Bob clicks "Save" to create the event
4. Alice receives the invitation email, and import the ics event in her calendar (btw, Nextcloud mail feature is broken https://github.com/nextcloud/mail/issues/7444, so to reproduce, either use a third-party calendar app, or download locally the event and import it from the calendar settings)
5. Alice now has Bob's event in her calendar.

6. Bob wants to change the title or the description or the location of the event
7. Bob goes into the event details, changes what he needs, and clicks "update" to save the changes.

### Expected behavior

Alice should receive a calendar update with title/description/location changed

### Actual behaviour

Alice receives nothing

### Calendar app version

c.nc.c or t.nc.c/ltd

### CalDAV-clients used

Thunderbird, Nextcloud calendar

### Browser

Firefox 110.0.1 (64-bit)

### Client operating system

Windows

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
Duplicate at https://github.com/nextcloud/calendar/issues/4428.

https://github.com/nextcloud/calendar/issues/4428#issuecomment-1217994489 for more info on why this currently happens. The backend doesn't consider the changes significant enough.
