### ISSUE TITLE
Today. OWNCLOUD 10.01 installed. CALENDAR doesn't work.... :(

### ISSUE THREAD

**Issue by Markes08** [nextcloud/calendar#505]
Hello,

we have updated our OWNCLOUD today. to 10.01
At the moment the following Issue comes doing installation:

"Die Signatur konnte nicht überprüft werden. Bitte kontaktiere die App-Entwickler und überprüfe deinen Admin-Bildschirm."

Could anyone Help me?

Best Regards,
Markes

**Comment by tcitworld** [comment]
See https://github.com/nextcloud/calendar/issues/498

**Comment by georgehrke** [comment]
Please see https://github.com/nextcloud/calendar/issues/498
