### ISSUE TITLE
The edit dialog shows a different time for an event than in the week/month display.

### ISSUE THREAD

**Issue by baermb** [nextcloud/calendar#5051]
### Steps to reproduce

1. Have an event in a Time Zone other than the the hosts TZ.
2. Look at event in Week or Month view, notice the start time.
3. Click on an event to edit it.
4. Displayed start time in dialog doesn't match.

### Expected behavior

1. Show a matching time to the week/month display.
This could simply be done by displaying the TimeZone of the event alongside the time in the edit dialog. The way it is now, if the event TZ doesn't match the hosts TZ, the time of the event by itself has very little meaning (e.g. IIRC there are TZs that are off by minutes as well as hours so that both the hours and the minutes of an event time become somewhat meaningless without the TZ.)

One can deduce that the time is wrong and my first guess ever time is going to be a TZ issue. But now a user has to go into a separate dialog (i.e. the TZ dialog) to figure out when the event actually occurs.

### Actual behaviour

Edit dialog shows a different time for the event than in the week/month display.

### Calendar app version

4.2.4

### Browser

Firefox 110

### Client operating system

Fedora 36

### Server operating system

Ubuntu 22.04

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

25.0.4

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
- activity: 2.17.0
  - bookmarks: 12.0.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.4
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.4
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
```

### Nextcloud configuration

```Text
"system": {
        "overwrite.cli.url": "https:\/\/localhost\/nextcloud",
        "dbtype": "mysql",
        "version": "25.0.4.1",
        "dbtableprefix": "oc_",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "calendar",
            "apporder"
        ],
        "mysql.utf8mb4": true,
        "default_phone_region": "US",
        "default_locale": "en_US",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "opcache.interned_strings_buffer": "16"
    }
```

**Comment by baermb** [comment]
I don't think it's a duplicate of #5301. The issue on #5031 looks to be a missmatch between a google calendar link and what shows up in nextcloud. (and google tends to have problems with daylight savings, which may be the cause there)

This has nothing to do with a google calendar. It's solely nextcloud created events. The time shown on the week/month displays are in the TZ of the host machine.  This makes total sense. The problem is that the time shown on the edit dialog is in the TZ that it was created with.  **But** there is no indication which TZ that is or even that it is a different TZ than the host machine's. All you see is an hour:minutes in week/month and a different hour:minutes in the edit dialog.

**Comment by tcitworld** [comment]
#5031 is about a different time shown in the edit dialog from the event view, it doesn't matter what the event source is.
