### ISSUE TITLE
Feature request: Send invitation mail for room changes

### ISSUE THREAD

**Issue by brunt82** [nextcloud/calendar#506]
### Steps to reproduce
1. Create an appointment and add an attendee to it.
2. Attendee accepts the appointment.
3. Meeting creator (owner) changes the room of the appointment.

### Expected behaviour
Nextcloud should send an e-mail about the room change as it does while changing the date or time of an appointment.

### Actual behaviour
No e-mail is sent. 

In my mind a room change may have the same priority like the date / time of a meeting.

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by brunt82** [comment]
MANS! Please set policies for your own and follow them. I already open such a feature for the server and it was closed yesterday: https://github.com/nextcloud/server/issues/5222
