### ISSUE TITLE
allow admins to add holidays calendars

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/calendar#5060]
### Is your feature request related to a problem? Please describe.

i have found that it is fairly easy to add an holidays calender using webcal as per https://github.com/nextcloud/server/issues/1363 however it is fairly involved for non tech savy users, requiring each and every user to add their own holiday calendar is bit tedious to do in an organisation

### Describe the solution you'd like

i'd like to be able to add a holiday calendar as an admin for everyone else on the server, so that it becomes a simple toggle for time to turn it on/off

**Comment by tcitworld** [comment]
Very related to https://github.com/nextcloud/calendar/issues/962. I have created an 3rd-party app to easily subscribe to holiday calendars: https://apps.nextcloud.com/apps/holiday_calendars, but that doesn't solve the fact that subscriptions can't be shared https://github.com/nextcloud/server/issues/1600

**Comment by Fuseteam** [comment]
yes very related but not quite the same, i don't mind subscribing to a google calendar, i just don't want to do that for every account xd
that said your app and https://github.com/nextcloud/server/issues/1600 does sounds like interesting workaround

**Comment by jancborchardt** [comment]
I would close this in favor of https://github.com/nextcloud/calendar/issues/962 though – whether an admin creates that calendar and shares it with everyone, or everyone does it on their own, is very similar. :) Let’s keep it together in one issue. :)
