### ISSUE TITLE
Improve sidebar display of Calendars

### ISSUE THREAD

**Issue by privatemaker** [nextcloud/calendar#5083]
### Is your feature request related to a problem? Please describe.

The sidebar in the Calendar app is not as clear and delineated as it could be. This becomes more acute when Calendars come from more than a single user and/or App. The primary things which I find issue with:

- Which Calendars belong to me, which are shared?
- Which Calendars come from other Apps?

I have only been using `Calendar` with the app `Deck`  and  `Appointments` both of which integrate differently. What I am proposing (could theoretically) work for other app integrations which I personally have maybe not encountered.

### Describe the solution you'd like

The design composition I created below strives to achieve the following:

- Clearly separate `Personal` from `Shared` Calendars to their own sections
- Separates `Deck` Calendars to their own section
- Adopts more standardized element for `+ New calendar`
- Reduces repeated words (Curious Croissants, Deck) to decrease cognitive load
- Shows `shared` icon for Calendars shared by you #4869

<img src="https://user-images.githubusercontent.com/49612519/227734530-b25c8a2a-067d-4025-995d-7067acb096a0.png" width="85%">

### Describe alternatives you've considered

I experimented with a few other configurations of titles and image placement of sharing users avatar, as well as using  subtitles instead of grouping calendars, but in the end I think the example above is best.

### Additional context

Relates to #4869 and builds on top of the improvements done in #4515

I'm not sure best workflows for suggestions like this. I am a designer but also a dev- so if @nextcloud/designers (or whoever needs to) gives me a :+1: I would take a stab an implementing this 😊

**Comment by tcitworld** [comment]
@nextcloud/designers

**Comment by raimund-schluessler** [comment]
I like this idea. But in order to fix #4869 as well, an indicator showing if a calendar is shared *by* you is missing.

**Comment by privatemaker** [comment]
@raimund-schluessler I see, thanks for clarifying i've updated my design composition to account for that state!

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler I see, thanks for clarifying i've updated my design composition to account for that state!

Thanks a lot, I think that would work great.

**Comment by bkaless** [comment]
We use nextcloud with approx. 400 usern. The sidebar and therefor the calendar app is not usable at all as the page loads extremly slow. 

I would like to see:

- new shared calendars are deactivated per default
- a search box at the top enables me to search for a specific calendar
- a button enables me to deactivate all calendars despite mine.

**Comment by st3iny** [comment]
I like your mockup a lot! It would certainly clean up the sidebar. Let's wait what our designers have to say about it.

**Comment by privatemaker** [comment]
> from my side we can go ahead with it!

Cool. Seems overall positive response so far... I will start familiarizing myself with the codebase shortly! :smile: 

> are you interested in joining Nextcloud design further?

@jancborchardt ja, bitte!

**Comment by CorentinS6** [comment]
Hi,
this is also close to #5156

**Comment by nimishavijay** [comment]
I think this is great as well! I especially like removing the repeated sharer names and the addition of the AppNavigationCaption for creating a new calendar :)

Adding a couple more ideas here:

- [ ] Change the shown/hidden indicator from a filled/outlined circle to a colored checkbox 
- [ ] Group hidden calendars in a separate section

|  |  |
|--|--|
| ![image](https://github.com/nextcloud/calendar/assets/52440189/676e176d-6d95-4fc4-a3cb-d4cc591849b4) | ![image](https://github.com/nextcloud/calendar/assets/52440189/4863dd5e-e038-43da-8ad6-58548e70bb74) |

What do you think? Also cc @nextcloud/designers for any feedback :)

**Comment by GVodyanov** [comment]
> Can someone tell me what the current status is? I'm not that familiar with git or GitHub and I'm not quite sure how the teams are organised and the processes are structured.
> 
> Is it already certain that these changes will be part of a new version of calendar? If so, do you know when (at least approximately)?

Hey! I'll start working on it now, and we'll try to get it a new version as soon as possible
