### ISSUE TITLE
NC11: header right buttons on public shared calender are shown on the left

### ISSUE THREAD

**Issue by michag86** [nextcloud/calendar#509]
### Steps to reproduce
1. share a calender by link
2. open the shared calendar

![grafik](https://user-images.githubusercontent.com/6691165/27181547-47f5d3ea-51d8-11e7-9f69-4ed03af2f4f1.png)

Only NC11 is affected. If you add this, it works:
![grafik](https://user-images.githubusercontent.com/6691165/27181621-a1030048-51d8-11e7-83b4-c60498ef041f.png)

### Expected behaviour
Subscribe and Download button are shown right

### Actual behaviour
Subscribe and Download button are shown left. Both are not usable!

### Server configuration
**Operating system**: Linux ekaptest.thlv.de 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64

**Web server:** Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.10 (apache2handler)

**Database:** mysql 5.5.52

**PHP version:** 7.0.10
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - calendar: 1.5.3
 - comments: 1.1.0
 - dav: 1.1.1
 - deck: 0.1.4
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notes: 2.2.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - user_ldap: 1.1.2
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_external
 - files_retention
 - firstrunwizard
 - templateeditor
 - user_external
 - user_saml
```
</details>

**Comment by georgehrke** [comment]
@michag86 As you already provided a possible fix, do you mind sending a pull request? :) 

The code in question is here: 
https://github.com/nextcloud/calendar/blob/master/templates/public.php#L13
