### ISSUE TITLE
Display event alarms in calendar

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#51]
https://tools.ietf.org/html/rfc4791#section-7.8.5 might come handy here

https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by cwmke** [comment]
The current discussion seems to be going towards notifications showing up through the Nextcloud Notifications app. Would this still send notifications through the browser so that they show up in my OS's notification area?

**Comment by georgehrke** [comment]
@cwmke I don't think native OS notifications should be implemented solely in the calendar app. They should be available for any notification. 

@nickvergessen Are there plans to use the [Browser Notification API](https://developer.mozilla.org/en-US/docs/Web/API/notification) with the notifications app? :)

**Comment by cwmke** [comment]
@georgehrke I agree. That would be great to have all Nextcloud notifications integrated with the browser's api.

**Comment by nickvergessen** [comment]
> Are there plans to use the Browser Notification API with the notifications app? :)

This is done since 2015, sorry you are late to the party…

**Comment by nickvergessen** [comment]
Please keep in mind, that when you publish notifications, this will also trigger push notifications on our apps and the desktop client.
So this should be optional at least, because otherwise you receive duplicate notifications on each device (your calendar app/client and your nextcloud app/client) (or even three times when you have the website also open)

**Comment by cwmke** [comment]
@nickvergessen When you dismiss a notification in one place is it dismissed in the others as well?

**Comment by nickvergessen** [comment]
Well "yes", but the sync client might have already triggered the desktop notification and the your calendar and nextcloud app on the phone also create the notifications at the same time.

**Comment by cwmke** [comment]
@georgehrke: To me it seems to make more sense to treat Calendar as any other calendar client that has it's own notifications separate from Nextcloud Notifications similarly to how Evolution or Thunderbird functions.

**Comment by georgehrke** [comment]
This was implemented in the server and will be part of Nextcloud 17.
https://github.com/nextcloud/server/pull/3044
