### ISSUE TITLE
"Update this and all future" generates excess events for events with a fixed number of repetitions

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/calendar#5110]
### Steps to reproduce

1. generate a repeating event with a given number of repetitions, say "daily 5 times"
2. change anything but the first event, say we modify the last one in the series
  - to have a concrete example: write the string "test" to the location input
  - "any" other change should do as well
  - changing any instance but the first one triggers this problem
4. hit "Update this and all future"

### Expected behavior

Only the edited event and all **already existing** future events should be updated, but the total number of events in the series should stay the same.

### Actual behaviour

If the series has N events and we change the M-th instance then we end up with (M-1) + M events. Example:

- 5 events
- change the last one
- we have 9 events

It is quite clear why: the first (M-1) events are copied to their own recurring events seriers with (M-1) events and a new series is started with the M-th event. However, than one just inherits the recurrence rules which in this case say: you have 5 repetitions. So we finally have two event series, one with (M-1) and the other one with M events.

### Calendar app version

4.3.1

### CalDAV-clients used

Just using THIS CalDAV client

### Browser

FF 111.0

### Client operating system

Linux

### Server operating system

Gentoo Linux

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.1

### Nextcloud version

26

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/3283?

**Comment by ChristophWurst** [comment]
Nothing to be sorry about. You've raised that we should probably backport the fix: https://github.com/nextcloud/calendar/pull/5058#issuecomment-1488409004.
