### ISSUE TITLE
Hide events in the past

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/calendar#5114]
### Is your feature request related to a problem? Please describe.

I like my calendar distraction free but sometimes looking at my calendar can be very overwhelming.

### Describe the solution you'd like

I would like to have the option to blend out all the events that are already in the past.
Having an option for each calendar but also globally would be good, since I might still want to see past events from one calendar, but not from the other.

### Describe alternatives you've considered

Not really, I could deleted events from the past, but that wouldn't work for subscriptions and it would also make it impossible to look at them again if I need to.

**Comment by ChristophWurst** [comment]
@jancborchardt @nimishavijay for triage

**Comment by ChristophWurst** [comment]
Not exactly what you are asking for but https://github.com/nextcloud/calendar/issues/26 could be helpful, too.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/4777
