### ISSUE TITLE
Fix menu toggle overlapping calendar grid

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#5121]
### Is your feature request related to a problem? Please describe.

The menu toggle overlaps with the calendar grid.

### Describe the solution you'd like

The menu toggle should not overlap with the grid.

## Fix grid views (month, week and day)

Decrease toggle button top margin (and height) to make it fit in the existing grid header. Some apps like Talk already do some micro-adjustments, which are fine.

![grafik](https://user-images.githubusercontent.com/1479486/229126157-3caf7f6c-86a5-49c0-aa67-1a6ec6ec4192.png)

## Fix list view

_To be discussed ..._

![grafik](https://user-images.githubusercontent.com/1479486/229125710-c6f016db-f500-4ae5-bf8b-a9ec4461139f.png)

### Describe alternatives you've considered

_None_

### Additional context

This has been approved by our designers: https://github.com/nextcloud/groupware/issues/2#issuecomment-1490417158

**Comment by jancborchardt** [comment]
@st3iny so list view can definitely use some further design improvements, but a padding-left on the leftmost column is what we need to do. We can’t do the horizontal spacing since the date header is sticky.

**Comment by st3iny** [comment]
Fixed by #5391
