### ISSUE TITLE
Highlight current day in small calendar in left navigation bar too

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#513]
The small calendar in the left navigation bar should have the current day highlighted too, and ideally the weekend too.

![screenshot from 2017-06-19 19-41-46](https://user-images.githubusercontent.com/925062/27298055-7ea62a3c-5527-11e7-9641-956139311ced.png)

Should be done the same way as for the main calendar: light yellow for current day, grey for weekend.

cc @nextcloud/calendar

**Comment by georgehrke** [comment]
Was implemented with #533
