### ISSUE TITLE
Feature request - Assign nextcloud tags to events

### ISSUE THREAD

**Issue by buttle** [nextcloud/calendar#514]
Hi all,

It would be very handy to assign nextcloud tags to events and then search/filter events by a tag or combination of tags.

Some tag examples:
* Project names (filter all events for a project).
* Meeting rooms (manage rooms)
* Subject (filter events by subject matter)

Is this idea reasonable to include in Calendar?

Cheers.

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/107

**Comment by buttle** [comment]
@georgehrke Thanks a lot. :) That would be a big step towards simple project management!
