### ISSUE TITLE
Event disappears from iOS calendar when moving between calendars

### ISSUE THREAD

**Issue by shepda** [nextcloud/calendar#5144]
### Steps to reproduce

1. Create a second calendar in Nextcloud calendar
2. In Nextcloud calendar create an event in the first calendar
3. In iOS Calendar edit the event and move the event to the second calendar.

### Expected behavior

The event is displayed correctly in the iOS calendar in the second calendar

### Actual behaviour

The user can see the event changed to the second calendar in iOS calendar briefly then it disappears, even after refreshing the calendars.

### Calendar app version

4.3.3

### CalDAV-clients used

iOS calendar

### Browser

Firefox 112

### Client operating system

Arch Linux

### Server operating system

Fedora

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.1

### Nextcloud version

26.0.0

### Updated from an older installed version or fresh install

Updated from an older version

### Additional info

In case it helps:

1. After moving the event in iOS calendar to the second calendar the event is displayed correctly in the Nextcloud calendar in the second calendar and the Nextcloud Activity logs shows that the event has been moved from the first to the second calendar

2. The event still doesn't display in the iOS calendar if the event is subsequently updated in the Nextcloud calendar

**Comment by eweinhold** [comment]
These Events are also not visible on MacOS Calendar, although they are listed in anNextcloud Website ICS export - they are not shown on iOS or MacOS System Calendars :(

**Comment by ChristophWurst** [comment]
check the Nextcloud Calendar trash bin (bottom left). Are the events there?

**Comment by shepda** [comment]
After the event disappears from the iOS calendar it is displayed in the Nextcloud calendar correctly (in the updated calendar) and it's not in the Nextcloud calendar trash bin.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/4735
