### ISSUE TITLE
Subscribe to a public calendar on iOS: Connection over SSL failed

### ISSUE THREAD

**Issue by sushidave** [nextcloud/calendar#515]
### Steps to reproduce
1. Share the calendar via Web interface.
2. Copy the link: https://cloud.***.com/apps/calendar/public/****************
3. Create a calendar subscription on iOS, enter the link with or without preceding https://, tap Next.

### Expected behaviour
Calendar connects seamlessly

### Actual behaviour
Error message: Connection over SSL failed. Want to proceed without SSL?
Calling the URL via web browser shows no error.

### Server configuration

**Operating system**:
 Linux 3.10.0
**Web server:**
 Apache 5.6.26
**Database:**
 mysql 10.1.21
**PHP version:**
 5.6.26
**Server version:** (see your admin page)
11.0.3
**Calendar version:** (see the apps page)
1.5.2
**Updated from an older installed version or fresh install:**
Updated

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
https
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Operating system:**
iOS 10.3.2

**Comment by georgehrke** [comment]
> https://cloud.***.com/apps/calendar/public/**************** 

This is not a subscription url. This is the public webpage that displays the calendar.
If you are on iOS, just open `https://cloud.***.com/apps/calendar/public/****************` in your browser and click subscribe in the top.

It will automatically offer you to subscribe to that calendar.

**Comment by sushidave** [comment]
Thanks, but I don't' see any "subscribe" on top of the page on Safari. However, there is a burger bar. When clicked it shows a download button and links for CalDAV / iCalfeed and code for iframe. Is this how it is supposed to be and what's the path to take?

**Comment by georgehrke** [comment]
Then you should update to the latest Calendar 1.5.3, where we changed the design of the public page, or just use the iCalfeed link for creating the subscription in iOS

**Comment by sushidave** [comment]
@georgehrke Ok! Calendar app updated to 1.5.3. 

The Subscription and Download buttons are hard to access cause they now appear behind the NC logo, so the design needs to be improved a bit.

By extracting and copying the iCal feed URL from the source code I was able to create the calendar subscription on iOS. Now it works, yaay!

Would it make sense to provide the iCal feed URL on the calendar app's interface already?
