### ISSUE TITLE
External uid is shown in calendar list

### ISSUE THREAD

**Issue by brantje** [nextcloud/calendar#516]
### Steps to reproduce
1. Create a calendar
2. Share it with an external user (in my cause LDAP user)
3. Click add

### Expected behaviour
The display name should be shown

### Actual behaviour
![image](https://user-images.githubusercontent.com/2758767/27497864-ed384a74-585c-11e7-8bc5-f8fbe9b20889.png)
The uid is shown

**Comment by georgehrke** [comment]
#459
