### ISSUE TITLE
Not all user/group are available in the "share" widget (missing scrollbar ?)

### ISSUE THREAD

**Issue by ratermir** [nextcloud/calendar#5169]
### Steps to reproduce

open Calendar app

in the left menu - calendar list - click on "Modify" (the pencil) icon

click to the "share" textbox, type part of the share name. The list must be long enouhg.

you can see only "subset" of available names to share. I can't be mode accurate since the share I want to choose is "Ani", which is the first in the list. This one is not available and I can't navigate to it any way. 

### Expected behavior

All users / groups are available (either using scrollbar, extend the windown size or any other way)

### Actual behaviour

See attached screenshot - the "Ani" is missing and there is no way how to navigate to it. The workaround I found is to choose croups that are visible (then they disapear from the list and the list moves down), then select required item (Ani) and then remove the one added for the workaround. Pretty complicated. 

![ksnip_20230428-111345](https://user-images.githubusercontent.com/52619304/235111635-691ba185-9ff5-4331-8d99-be8ff72149a3.png)
![ksnip_20230428-112845](https://user-images.githubusercontent.com/52619304/235111656-704c2871-9e21-4c63-9d28-c64457678f42.png)

### Calendar app version

4.3.3

### CalDAV-clients used

N/A

### Browser

Chrome 110.0.56 (and more versions), Firefox (several vesions)

### Client operating system

Linux - ofitial docker image 

### Server operating system

OpenSuSE 15.3

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.6

### Updated from an older installed version or fresh install

Updated from an older version

### Browser log

```Text
The log is empty (no error nor message) after Calendar is open.
```

**Comment by JohannesGGE** [comment]
Fixed by: https://github.com/nextcloud/calendar/pull/5323
