### ISSUE TITLE
Default calendar broken after upgrade to NC 12.0

### ISSUE THREAD

**Issue by onny** [nextcloud/calendar#517]
### Steps to reproduce
1. Load the calendar app

### Expected behaviour
Default calendar should load all events, even after upgrade to NC 12.0

### Actual behaviour
Other calendars and remote subscription loads finde. Default calendar keeps loading for a while and fails with the message "Some events in this calendar are broken"

### Server configuration

**Operating system**: ArchLinux x86_64

**Web server:** Nginx 1.12

**Database:** Mysql

**PHP version:** 7.1.6

**Server version:** up-to-date

**Calendar version:** 1.5.3

**Updated from an older installed version or fresh install:** updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "527b7f969713e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/usr\/share\/webapps\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "mysql.pi",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "cron_log": true,
        "maxZipInputSize": 5145728000,
        "allowZipDownload": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trusted_domains": [
            "nextcloud.project-insanity.org",
            "http-new.pi"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "project-insanity.org",
        "mail_smtpmode": "php",
        "mail_from_address": "nextcloud",
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "https:\/\/nextcloud.project-insanity.org"
    }
}
```

**Are you using external storage, if yes which one:** None

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** firefox 54

**Operating system:** ArchLinux x86_64

**CalDAV-clients:** NC Calnedar

#### Web server error log
```
No relevant web server error log
```

#### Log file (data/nextcloud.log)
```
No log concerning calendar app, even in debug mode
```

#### Browser log
```
No browser log concerning calendar app
```
I attached the corrupt .ics file:

[default calendar-2017-06-25.zip](https://github.com/nextcloud/calendar/files/1100374/default.calendar-2017-06-25.zip)

**Comment by onny** [comment]
Reimport the ICS file with a different user succeeds but 400+ errors remain. I'm unable to tell what the errors are and how they occured in the first place ... Maybe via. CalDAV sync on Android (DavDroid)?
![2017-06-29-144115_swaygrab](https://user-images.githubusercontent.com/757752/27688002-479eda5c-5cd9-11e7-8da6-e8e936854963.png)

**Comment by georgehrke** [comment]
My guess would be that the ICS parser in the server got more strict with Nextcloud 12. Will look into this early next week.

**Comment by georgehrke** [comment]
I can no longer reproduce this with Calendar 2.0 beta1.

The ics imports and loads just fine. Also checked May / June / July 2017 - no errors
