### ISSUE TITLE
New contact when group is activated creates one group for each letter of that group

### ISSUE THREAD

**Issue by dschrempf** [nextcloud/calendar#518]
### Steps to reproduce
1. Click on a group `GROUP`
2. Click `New contact`

### Expected behaviour
A contact should be created that is in `GROUP`.

### Actual behaviour
A contact is created that is in groups `G`, `R`, `O`, `U` and `P` :-).

Nextcloud version 11.0.3
Calendar version 1.5.3

**Comment by georgehrke** [comment]
Please create contact issues in the contact repo, not the calendar one ;)

**Comment by dschrempf** [comment]
Right, thank you :-).
