### ISSUE TITLE
Calendar - Appointments - Check additional calendar for conflict - no support for shared and extern calendars

### ISSUE THREAD

**Issue by All0ne** [nextcloud/calendar#5182]
### Is your feature request related to a problem? Please describe.

When I provide options for booking an appointment for office hours I cannot provide all the calendars necessary to check for conflicts. It is only possible to add own calendars and not shared (team calendars) or external calendars in checking for conflicts. This leads to conflicts in the appointment booking.

### Describe the solution you'd like

Add also the possibility to check shared and extern calendars for conflicts.

### Describe alternatives you've considered

its working in the App Appointments https://apps.nextcloud.com/apps/appointments
but for endusers gets confused by setting up 2 different "appointments"-apps

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/3786
