### ISSUE TITLE
4.4.0-alpha.2: Migration step 'OCA\Calendar\Migration\Version4004Date20230414163505' is unknown

### ISSUE THREAD

**Issue by nursoda** [nextcloud/calendar#5191]
### Steps to reproduce

I get a migration error when updating to 4.4.0-alpha.2

### Expected behavior

No error :)

### Actual behaviour

update:check
Update for calendar to version 4.4.0-alpha.2 is available.
1 update available

app:update --all
calendar new version available: 4.4.0-alpha.2
Error: Database error when running migration 4004Date20230414163505 for app calendar
Migration step 'OCA\Calendar\Migration\Version4004Date20230414163505' is unknown
calendar updated

### Calendar app version

 4.4.0-alpha.2

### Server operating system

Arch Linux

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

Other

### Nextcloud version

26 latest beta

### Updated from an older installed version or fresh install

None

### List of activated apps

```Text
many
```

### Additional info

Please add PHP 8.2 to the issue template

**Comment by nursoda** [comment]
Running `occ upgrade` fixes the issue:

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: files_frommail
Updating <calendar> ...
Updated <calendar> to 4.4.0-alpha.2
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
```

**Comment by juliushaertl** [comment]
@ChristophWurst SInce you've mentioned this in a few other tickets, I've been thinking if this was related to the apcu autoloader cache which is not refreshed during app upgrade:

https://github.com/nextcloud/server/blob/d293293cdaf10745459e98cce70412882241fdec/lib/base.php#L609

Ideally we'd have a prefix including app versions, but might be too early in the request to do that, so maybe we can workaround by adding a apcu_clear_cache during the app upgrade process

**Comment by ChristophWurst** [comment]
> I think the more recent problem is just there for new classes where the cached authoritative autoloader is reused.

I think it's two problems combined

1) Authoritative class loader doesn't get refreshed like you describe. The old version has an outdated class map. New classes are not loaded
2) With https://github.com/nextcloud/mail/pull/7924 we intentionally disabled the server autoloader. I think that was actually helpful as fallback when an app's autoloader failed.

**Comment by ppascher** [comment]
My nextcloud was unreachable as well after trying to upgrade the calendar app. Error Log was full of the following line:
```
PHP Fatal error:  Class OC\AppFramework\Utility\SimpleContainer contains 5 abstract methods and must therefore be declared 
abstract or implement the remaining methods (OCP\IContainer::_user_func, OCP\IContainer::/Server.php:282$5, 
OCP\IContainer::registerparameter, ...) in /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php on line 47
```
I just did what the error message showed and added the word "abstract" in front of the simple Container class definition on line 47 in `/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php` after which the server worked again and I got a web GUI prompt to finish updating the calendar app.
Not sure if this is a good solution as I have no idea what the implications are of making SimpleContainer abstract.

**Comment by melroyvandenberg** [comment]
Yep same..

**Comment by Tuffiglig** [comment]
I think it is, becuase i got the exact same message and problem with Nextcloud 25.0.7.
`# sudo -u www-data php /var/www/nextcloud/occ app:update --all
calendar new version available: 4.4.0
Error: Database error when running migration 4004Date20230414163505 for app calendar
Migration step 'OCA\Calendar\Migration\Version4004Date20230414163505' is unknown`

As mentioned by @nursoda the command
`sudo -u www-data php /var/www/nextcloud/occ upgrade`
was fixing it.

But nothing less, i would prefer to not seeing it in a not beta version of Nextcloud :-/

**Comment by nursoda** [comment]
All betas were fine, just the release had this issue (again).

**Comment by ChristophWurst** [comment]
Scan your nextcloud installation for SimpleContainer.php files and post the paths

**Comment by nursoda** [comment]
AFTER executing `occ upgrade` it's just `lib/private/AppFramework/Utility/SimpleContainer.php` on all my instance. All other occurrences are in updater-UUID/backups/nextcloud-VERSION-NUMBER` (and in manually made backups outside the paths that are accessible for the instance).

**Comment by nursoda** [comment]
> And before there were two? What paths?

Can't say, don't know.

**Comment by ChristophWurst** [comment]
@ppascher could you please check?

**Comment by ppascher** [comment]
> @ppascher could you please check?

I just have one file 'SimpleContainer.php':
```
sudo find /var/www/nextcloud/ -iname '*simplecontainer*' -type f
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php
```

I also checked my backup folder but it's the same path.

I have since then reverted the manual change to SimpleContainer.php and removed "abstract" from line 47 and have not been getting any more errors (presumably because the update to the calendar app is already completed?).

I checked my log again from when the update to the calendar app was started but not completed yet and there are actually 2 error messages:
```
[08-Jun-2023 13:39:21 Europe/Berlin] PHP Fatal error:  Class OC\AppFramework\Utility\SimpleContainer contains 5 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\IContainer::_user_func, OCP\IContainer::/Server.php:282$5, OCP\IContainer::registerparameter, ...) in /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php on line 47

[08-Jun-2023 13:39:24 Europe/Berlin] PHP Fatal error:  Class OC\AppFramework\Utility\SimpleContainer contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\IContainer::registerService) in /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php on line 47
```

Please let me know if you need any other information.

**Comment by muchachagrande** [comment]
4.4.1 update was fine

**Comment by ChristophWurst** [comment]
Thanks @ppascher
