### ISSUE TITLE
Timetracker / Calendar integration

### ISSUE THREAD

**Issue by tonymurray** [nextcloud/calendar#5194]
### Is your feature request related to a problem? Please describe.

The Calendar could be integrated with the Timetracker application

Depending on a person's profession, a work day typically comprises not just meetings and appointments, but also blocks of time doing 'work' (designing, programming, writing reports, researching etc)

Many jobs/projects require people to account for time spent on projects/clients/tasks/admin.

A 'time recorder' is typically awkward to use. (e.g work 'timers' perhaps only useful appropriate to some particular people/tasks)

A calendar is an excellent VISUAL way to record/account for time spent on clients/projects/administration.
Thus a calendar not only focused on upcoming 'appointments', but also a journal of past 'activities'

### Describe the solution you'd like

Integrate the Calendar app with the Time tracker app. 

Time Entries in the calendar could be assigned 'project' and 'tag' originating from the Timetracker app, and  appear as entries / in reports within the Timetracker app.

### Describe alternatives you've considered

The "Dotproject" application had a calendar that could be used in this way.
Dotproject is for the most part discontinued https://github.com/dotproject/dotProject

**Comment by ChristophWurst** [comment]
Some trackers offer to export their tracked items via a subscription (.ics link). You can add those in the Calendar. That works. I use it that way.

I am pretty sure time tracking, as a feature, is out of scope for this app.

If there is a time tracking app for Nextcloud it can integrate its data into the Calendar: https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/groupware/calendar.html#calendar-providers

**Comment by ChristophWurst** [comment]
https://github.com/mtierltd/timetracker/issues/186

**Comment by phileastv** [comment]
If Nextcloud Task does a time tracking utility like in this issue https://github.com/nextcloud/tasks/issues/75 it would be awesome it to be integrated into Calendar !

For refence, here is the time tracking feature in Hey Calendar.

![Kapture 2024-02-14 at 11 12 49](https://github.com/nextcloud/calendar/assets/20335741/f0488ffd-f047-4785-860a-a66651dd6e28)
