### ISSUE TITLE
Android Client : button for full rescan/reupload of folders selected for sync

### ISSUE THREAD

**Issue by thsnielsen** [nextcloud/calendar#520]
### Steps to reproduce
1. While having folders checked for synchronization - unknown problems arise, and for some odd reason synchronization stops (as i have seen a number of times) then normal troubleshooting starts - are there blocked files on the server - delete them on server - these files are not re-uploaded once back to normal and next time the android client syncs the folder from where the picture or file came from.
You may even chose to delete the account on the device, and recreate it - then no more files older that the date of the creation of the account are uploaded - no matter if the files are on the server or not
2. Normally synchronization picks up again if you manually tags a file for upload to server, but all new files arrived since the stop of sync until manual upload will not never synced.
3.i am sure there are other scenarios, where files on the device are left un-uploaded

### Expected behaviour
At next scan the non-uploaded files should be detected, and uploaded, but for the case where a file was purposely deleted on the server, it creates a conflict - should this file be re-uploaded or not - rather not i would say. But sometimes you just wish to make sure, that the complete folder marked for sync on the phone IS on the %é_è-'çàçe server.
Therefore the need for a "redo complete deep dive sync of folders marked for sync" "with/without overwrite" of existing files (the overwrite could be interesting in case of corruption on the server (sd card about to hang up, cryptolock etc)

### Actual behaviour
not possible to get missing files onto the server once sync has decided to omit them, unless finding out yourself which files are missing, and manually tagging them for upload

### Server configuration

**Operating system**:Raspbian 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

**Web server:**
apt-cache show nginx      
Package: nginx
Version: 1.10.3-1
Installed-Size: 91

**Database:**
Package: mariadb-server-core-10.1
Source: mariadb-10.1
Version: 10.1.22-3
Architecture: armhf

**PHP version:**
php -v
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies

**Server version:** (see your admin page)
12.0.0
Here connected remotely i discovered my USB storage is down, so i have to provide the rest of the details later, when i have cooled down my storage (bloody heatwave)- sorry about that

**Calendar version:** (see the apps page)
Unknown at this time

**Updated from an older installed version or fresh install:**
Upgraded from 11

**Signing status (ownCloud/Nextcloud 9.0 and above):**
Unknown at this time

Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
Will come to that ...

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
External USB disks used but mounted local (and of course now that i write on this issue, the disk cabinet overheated, and the whole nextcloud storage is down :-/

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder


### Client configuration
Android client 1.4.3

### Logs
#### Web server error log
I guess again no error  because it is working as designed

#### Log file (data/nextcloud.log)
Nothing is synced i guess no relevance for server log - otherwise please ask, and i will provide for the desired scenario

#### Browser log
No log from Android client at hand

**Comment by georgehrke** [comment]
Your bug report is completely unrelated to the calendar.

Please report it in the correct repo

**Comment by thsnielsen** [comment]
You are right - sorry about that - not sure how i ended up here.... will move
- thanks for the note.

**Comment by georgehrke** [comment]
no problem :)
