### ISSUE TITLE
Windows 11 Widget

### ISSUE THREAD

**Issue by philippstappert** [nextcloud/calendar#5203]
### Is your feature request related to a problem? Please describe.

I really don't want to open the full calendar app all the time, it would be great if i could just swipe from left and see my next/upcoming calendar events.

### Describe the solution you'd like

It is possible, to integrate some web-app widgets into the Windows 11 Widget-Bar.

https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/widgets

I'd love to see this feature.

**Comment by tcitworld** [comment]
As per your link, PWA widgets is a very experimental technology, available on a very restricted subset of devices (Windows 11, Microsoft Edge with a special feature flag). We should *at least* wait for more interest from other browser vendors before looking into this (it's not even proposed to the community [yet](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/PWAWidgets/README.md)).
