### ISSUE TITLE
requests to the DC controller every 5 seconds

### ISSUE THREAD

**Issue by loopguard404** [nextcloud/calendar#5208]
### Is your feature request related to a problem? Please describe.

I have a calendar connected to roundcube via caldav, in the logs and in tcpdump I see calls to the user server every 5 seconds. Along with this, the ldap user also sends 3 requests to the DC server. For what ? and why ? And can it be controlled? For example, reduce the time to access the DC controller

### Additional context

 "PROPFIND /remote.php/dav HTTP/1.1" 207 645 "-" "sabre-dav/4.4.0 (http://sabre.io/)" "-"
 "PROPFIND /remote.php/dav/principals/users/user_3671/ HTTP/1.1" 207 587 "-" "sabre-dav/4.4.0 (http://sabre.io/)" "-"
 "PROPFIND /remote.php/dav/calendars/user_3671/ HTTP/1.1" 207 2214 "-" "sabre-dav/4.4.0 (http://sabre.io/)" "-"

**Comment by ChristophWurst** [comment]
Sound like you have a question

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/issues/new/choose
