### ISSUE TITLE
Feature Request: Widget

### ISSUE THREAD

**Issue by Twilek-de** [nextcloud/calendar#521]
I am using the nextcloud calendar together with a humhub installation. Is it possible to show a list of coming events as a widget to embed into the side or a very small calendar. Is there already some way to do this?

**Comment by georgehrke** [comment]
You can try to use the public sharing iframe for that.
But generally you can access all your events via CalDAV and we won't implement something like this in the Nextcloud calendar.

**Comment by georgehrke** [comment]
> Is there already some way to do this?

Did you check if there is something like a generic CalDAV widget for HumHub?

**Comment by Twilek-de** [comment]
There is a humhub calendar module, but it is far less powerful and lacks all Caldav features, I thought that maybe I can manually invoke the mobile view of the nextcloud calendar, It is not that big a deal in the end, I just thought that if there was a simple solution I would implement it.

**Comment by georgehrke** [comment]
You can try to share the calendar publicly and just embed the public sharing site. But that will be read-only.

**Comment by Twilek-de** [comment]
Read-only would be enough. But the resulting page does not play very nice with the very low resolution.
