### ISSUE TITLE
propagate shared calendars and ical abonnements via WebDAV

### ISSUE THREAD

**Issue by huberste** [nextcloud/calendar#522]
When syncing the Calendar via WebDAV (e.g. with an android device), shared calendars and ics abonnements are not propagated to the syncing device. This results in all calendars shown in the web surface (own personal calendars, shared calendars and ics imported calendars). When using a mobile device (in my case with DAVDroid), only personal calendars are shown in the client, resulting in limited usability as shared calendars and ics imports are not shown.

**Comment by georgehrke** [comment]
dup of a core issue, searching ...

**Comment by georgehrke** [comment]
And in fact they are propagated, but DavDroid doesnt support it

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/1497
