### ISSUE TITLE
Name text-box loses focus after every typed letter

### ISSUE THREAD

**Issue by Cwpute** [nextcloud/calendar#5221]
### Steps to reproduce

1. Create a new calendar
2. In the left panel, click on the pen button next to the newly created calendar's name to edit it
3. Click on the text-box containing the name of the calendar to edit it

### Expected behavior

The text-box should retain the focus until the user clicks outside the text-box.

### Actual behaviour

Focus is lost after every typed letter: 
![firefox_vxcm9vWpxy](https://github.com/nextcloud/calendar/assets/80604512/223a37fd-0cdd-4eb2-ae43-7d9c062c5e0f)
(notice how the colour of the box's contour changes, as if the mouse cursor wasn't detected for a second, and then detected again)

### Browser

112.0.2 (32 bits)

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

### Additional info

I am an end-user from [girofle.cloud](girofle.cloud) thus i'm not able to provide more information on the Nextcloud instance they are using, but it's pretty much up to date to my knowledge, and well-maintained.

**Comment by Cwpute** [comment]
Another issue has been reported regarding a text-box losing focus in an unexpected manner: 
* https://github.com/nextcloud/calendar/issues/3108

Two other issues also reported reported regarding the color-picker losing focus in a similar manner:
* https://github.com/nextcloud/calendar/issues/3107
* https://github.com/nextcloud/calendar/issues/2698

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/4890?

**Comment by Cwpute** [comment]
Not a dupe, because we didn't report this éehavior for the same windows…
But the way the text-box reacts is exactly the same, so both issues must certainly share the same causes.
