### ISSUE TITLE
Cannot select conflict calendars in Appointments Config View when *exactly* two calendars exist

### ISSUE THREAD

**Issue by pjrobertson** [nextcloud/calendar#5223]
### Steps to reproduce

1. Install Nextcloud 27, Calendar v4.3.3 (note: this feature used to work, but possible upgrade to 4.3.3 from 4.3.2 caused an issue)
2. Ensure you have **exactly** 2 calendars you own on your account
3. Enable Appointments feature is enabled and set working hours
4. Go to Calendar > Appointments > "+"
5. Select a calendar for 'Calendar' option. Try to select alternative calendars for 'Additional calendars to check for conflicts'.
6. Note that the option is disbled/cannot select:
<img width="911" alt="Screen Region 2023-05-15 at 19 42 22" src="https://github.com/nextcloud/calendar/assets/150431/038dd247-ca91-4e8e-91d2-05d8def00a0c">

### NOTE:
If you add a 3rd calendar, you will note that this now works. However if you have only 2 calendars, the feature does not work.

I have checked that the javascript is working correctly - when you have just 2 calendars, the [`selectableConflictCalendars()`](https://github.com/nextcloud/calendar/blob/main/src/components/AppointmentConfigModal.vue#LL230C3-L230C30) correctly returns the 1 remaining calendar. But the view itself is disabled and I don't know how to enable it.

### Expected behavior

I should be able to select alternative calendars from the conflict option.

### Actual behaviour

Unable to select any calendars

### Calendar app version

4.3.3

### CalDAV-clients used

-

### Browser

Firefox 113.0.1 and 113.0.5

### Client operating system

macOS

### Server operating system

Ubuntu

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

26.0.1

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.18.0
  - auto_groups: 1.5.1
  - calendar: 4.3.3
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dav: 1.25.0
  - deck: 1.9.2
  - external: 5.1.0
  - federatedfilesharing: 1.16.0
  - files: 1.21.1
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - impersonate: 1.13.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.1.1
  - notifications: 2.14.0
  - notify_push: 0.6.2
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - passwords: 2023.5.30
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recognize: 4.0.1
  - registration: 2.1.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - spreed: 16.0.3
  - systemtags: 1.16.0
  - tasks: 0.14.5
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "172.93.220.164",
            "box.smartairfilters.com",
            "box.smartairfilters.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "26.0.1.1",
        "overwrite.cli.url": "https:\/\/box.smartairfilters.com\/",
        "defaultapp": "files",
        "simpleSignUpLink.shown": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": "true",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 120",
        "versions_retention_obligation": "auto, 180",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "logtimezone": "Asia\/Shanghai",
        "htaccess.RewriteBase": "\/",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF"
        ],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "maintenance": false,
        "skeletondirectory": "",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "default_phone_region": "us",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis"
    }
}
```

### Log file

```Text
Nothing specific to calendar in log.
```

### Browser log

```Text
No errors in console.
```

### Additional info

Previously worked before upgrading to 4.3.3

**Comment by ChristophWurst** [comment]
> Ensure you have at least 2 calendars you own on your account

https://github.com/nextcloud/calendar/issues/4697?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/blob/999601ecb80b8a544b6d2c233529d5c3554eed31/src/components/Shared/CalendarPicker.vue#L52-L54C5

**Comment by ChristophWurst** [comment]
> when exactly 2 calendars exist

Yes: https://github.com/nextcloud/calendar/issues/4697 :)

**Comment by pjrobertson** [comment]
OK great. Thanks! Adding a 3rd calendar is a workaround. Can you point me to where in the code I should look at for fixing this?

**Comment by pjrobertson** [comment]
OK, great find! I have submitted a PR. :)

**Comment by AkhilSinghRana** [comment]
Also, It would be nice if the app can check for conflicts in the google calendar that I am subscribed to!
