### ISSUE TITLE
Add more repeat options for events

### ISSUE THREAD

**Issue by huberste** [nextcloud/calendar#523]
It would be nice to have the option to have a certain event repeated e.g. on the last of every month (!), or every second and fourth thursday in a month, everys Monday, Wednesday and Friday or only weekdays, on weekends, ...

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/10

**Comment by georgehrke** [comment]
Please search for existing issues before creating new ones, thx ;)
