### ISSUE TITLE
Update Mexican Timezone

### ISSUE THREAD

**Issue by MarianoRD** [nextcloud/calendar#5234]
### Steps to reproduce

1. Setup a Calendar event with Mexico City timezone
2. Check date and time of the event

### Expected behavior

Use GMT-6

### Actual behaviour

Uses GMT-5

### Calendar app version

4.3.3

### Browser

Firefox 113.0

### Server operating system

Debian

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 7.4

### Nextcloud version

25.0.6

### Updated from an older installed version or fresh install

Updated from an older version

### Additional info

Mexico recently stopped using DST (https://www.timeanddate.com/time/change/@3996063) which is breaking a lot of services due to not updating to the latest timezone information.

**Comment by tcitworld** [comment]
Should be fixed in https://github.com/nextcloud/calendar-js/pull/583, brought-in just recently https://github.com/nextcloud/calendar/pull/5233
