### ISSUE TITLE
Timezone selector has wrong z-index

### ISSUE THREAD

**Issue by jjasoncool** [nextcloud/calendar#5235]
**Describe the bug**
Timezone selector has wrong z-index

**To Reproduce**
1. Go to 'calendar app'
2. Click on 'any date'
3. you need popout window to add some event.
4. click the global icon.
5. the error z-index show.

**Expected behavior**
Just normal show timezone selector.

**Screenshots**
![圖片](https://github.com/nextcloud/calendar/assets/24731867/b81e8c92-bbef-4e3f-a914-10816a27d60a)

**Client details:**
 - OS: any OS
 - Browser firefox
 - Version latest
 - Device: desktop

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/calendar/issues/5143

**Comment by jjasoncool** [comment]
Still not fixed after update to 4.3.4

**Comment by ChristophWurst** [comment]
I don't think 4.3 has the fix. https://github.com/nextcloud/nextcloud-vue/pull/4014 went into nc/vue 7.11.0, which didn't go into the 4.3 line https://github.com/nextcloud/calendar/blob/stable4.3/package.json#L59.

4.4 will have the fix https://github.com/nextcloud/calendar/blob/stable4.4/package.json#L59
