### ISSUE TITLE
Option to disable public sharing

### ISSUE THREAD

**Issue by baltaner** [nextcloud/calendar#525]
### Steps to reproduce
0. users are authenticated by ldap
1. Click on sharing-icon
2. Checkbox to public sharing appears
3.

### Expected behaviour
I disabled "Allow users to share by link" in nextcloud configuration
I enabled "Allow apps to use share-API"

I expect that there is no public sharing possible in calendar-app

### Actual behaviour
Public sharing is possible!

### Server configuration

**Operating system**:
ubuntu 16.04
**Web server:**
apache 2.4
**Database:**
mysql 5.7.18
**PHP version:**
7.0.18
**Server version:** (see your admin page)
12.0.0
**Calendar version:** (see the apps page)
1.5.3

**Comment by georgehrke** [comment]
Please report in the server repo as well
@tcitworld

**Comment by tcitworld** [comment]
Fix is coming, writing test...
