### ISSUE TITLE
feature request: attachments for events

### ISSUE THREAD

**Issue by madbob** [nextcloud/calendar#527]
The ability to link files and folders to events, took from Files, would be extremely useful: the folder for that meeting, the slides for that presentation, the ticket for that fly...
The Mail app has a beautiful widget to pick contents from Files, but I'm unsure if that could be reused (or, even better, integrated into the NextCloud core framework).

**Comment by georgehrke** [comment]
@madbob Please use the search before creating new issues ;)

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/298
