### ISSUE TITLE
The event will be displayed at the position one hour earlier in the Chrome browser

### ISSUE THREAD

**Issue by midaw1** [nextcloud/calendar#528]
### Steps to reproduce
1. Create any event in a calendar. Start 16:00 and end 17:00. Save it's.
2. The event will be displayed at the position one hour earlier in the Chrome browser.
3. The problem occurs for an event with timezone = Europe / Moscow.

### Expected behaviour
The event is displayed in the right place. As in the Internet explorer.

### Actual behaviour
The event will be displayed at the position one hour earlier in the Chrome browser.

### Server configuration
Ubuntu 16.04 LTS (Updated)
Apache 2.4.18-2ubuntu3.3
MariaDB 10.0.29-0ubuntu0.16.04.1
PHP 1:7.0+35ubuntu6
Nextcloud 12.0.0
Calendar 1.5.3

**Updated from an older installed version or fresh install:**
Fresh install

**Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.**
No errors have been found.

**List of activated apps:**
Standard apps and apps:
Calendar
Contacts
External storage support

**PHP timezone:**
Europe/Moscow

![screenclip 1](https://user-images.githubusercontent.com/15746074/27861696-864a5f28-618a-11e7-8671-a86641e3cf5e.png)
![screenclip 2](https://user-images.githubusercontent.com/15746074/27861699-8807a776-618a-11e7-96ab-499b16f0842b.png)
![screenclip 3](https://user-images.githubusercontent.com/15746074/27861702-89ab2ada-618a-11e7-876c-531d022c3d2f.png)

**Comment by georgehrke** [comment]
It seems like the calendar detects different timezones depending whether you use Internet Explorer or Chrome. 

Which of the events was created in Chrome and which one in Internet Explorer? (talking about "push" and "asdasd".

What timezone does Chrome and Internet Explorer display in https://pellepim.bitbucket.io/jstz/ ?

**Comment by midaw1** [comment]
> What timezone does Chrome and Internet Explorer display in https://pellepim.bitbucket.io/jstz/ ?
Chrome: Europe/Moscow
IE: Asia/Dubai
Really: Europe/Moscow

**Comment by midaw1** [comment]
> Which of the events was created in Chrome and which one in Internet Explorer? (talking about "push" and "asdasd".
All events were created in Chrome.
But if you create an event in IE, it does not display correctly in both browsers ...

**Comment by georgehrke** [comment]
Closing as dup of https://github.com/nextcloud/calendar/issues/496
