### ISSUE TITLE
Always show calendar-picker for read-only shared events

### ISSUE THREAD

**Issue by Kaor** [nextcloud/calendar#529]
1. have multiple shared calendar by another users

### Expected behaviour
for example on hover have the name of the owner of an event

### Actual behaviour
show nothing in text, just color

### Server configuration
Nextcloud 11.0.3
Calendar 1.5.3

Tests on firefox last version

**Comment by georgehrke** [comment]
Is this a feature request or a question? 

If it's a question:
No, that's not possible.
The server does not store who created an event.

**Comment by Kaor** [comment]
twice,
the server know the calendar where the event is store,
the server know the owner of the calendar,
i dont understand

**Comment by georgehrke** [comment]
If you create the event in calendar shared with you, the server only stores that the event was created in that calendar, not who created the event.

**Comment by Kaor** [comment]
i understand
i just want the name of the owner of the calendar + the color 
that was able in previous version of calendar

**Comment by georgehrke** [comment]
You should see the owner in the calendar name. It should be "calendar name (owner)". 

E.g. Personal (Admin)

**Comment by Kaor** [comment]
yes but not on an event

**Comment by Kaor** [comment]
![capture du 2017-07-05 13 18 37](https://user-images.githubusercontent.com/5570992/27862224-87a22672-6184-11e7-9668-97229e1e752d.png)

**Comment by georgehrke** [comment]
Because you have only one writable calendar. In that case we don't show the list.

**Comment by georgehrke** [comment]
<img width="586" alt="calendar - nextcloud chromium today at 1 20 32 pm" src="https://user-images.githubusercontent.com/1250540/27862281-c098e380-6184-11e7-9ee3-652408fcb4c3.png">

If you have multiple calendars and some of them are shared with you, you will see the owner's name.

**Comment by Kaor** [comment]
you're right ! it works !
of course, i just have to add a test calendar to my 200 users ? ;-)

**Comment by georgehrke** [comment]
Ah, now I get it. If the calendar is shared read-only and the user has only one writable calendar, they will not see the calendar name even for read-only shared events.

That's a bug.

**Comment by Kaor** [comment]
cooooooooool, i find a bug ?
great day for me, thanks for your great help !
