### ISSUE TITLE
l10n: String does not need to get translated.

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/calendar#5296]
https://github.com/nextcloud/calendar/blob/4a638f88e21ac28986ebc51e7a5e542c6bc598ca/lib/Service/Appointments/BookingCalendarWriter.php#L117

Reported at Transifex.

**Comment by tcitworld** [comment]
This was done on purpose, but maybe I'm wrong here: https://github.com/nextcloud/calendar/pull/5229#discussion_r1194664857

**Comment by tcitworld** [comment]
Not in 99% of case, but RTL languages would invert the two placeholders if I'm not mistaken.

**Comment by meskobalazs** [comment]
I'd also add that in Hungarian the typographically correct dash is the en dash here, that's what I am using now, so IMHO in general these should be translatable.
