### ISSUE TITLE
l10n: Context needed, please add translator comment

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/calendar#5297]
https://github.com/nextcloud/calendar/blob/4a638f88e21ac28986ebc51e7a5e542c6bc598ca/lib/Listener/AppointmentBookedListener.php#L86-L89

Reported at Transifex.

**Comment by tcitworld** [comment]
An easy fix is to prefix the line with something like:
```php
// TRANSLATORS Title for the Talk conversation name that will be created for the appointment
```

**Comment by tcitworld** [comment]
Edited the help comment above to reflect that

**Comment by tcitworld** [comment]
This string should also have positional placeholders btsw
