### ISSUE TITLE
Calendar App update unsuccessfull in NC-aio 26

### ISSUE THREAD

**Issue by GUNT0815** [nextcloud/calendar#5298]
### Steps to reproduce

- upgrade to Nextcloud-aio 6
- running for one day
- via admin user in nextcloud gui: app updates
- unsuccessfull for calendar app with error message "An error occurred during the request. Unable to proceed."
- nextcloud webui not reachable afterwards, webpage message: "Aktualisierung erforderlich
Da automatische Updates in der config.php deaktivert sind, nutzen Sie bitte den Updater über die Kommandozeile.
Für weitere Hilfen, schauen Sie bitte in die [Dokumentation](https://docs.nextcloud.com/server/26/go.php?to=admin-cli-upgrade)."
- manual update try via commandline -> looks like successful, but was not - unchanged situation
- remark: caldav is also not working

### Expected behavior

caldendar app is successfully updated and running

### Actual behaviour

- Message after calendar app update try: "An error occurred during the request. Unable to proceed."
- Nextcloud as a whole stops working. Message: "Aktualisierung erforderlich
Da automatische Updates in der config.php deaktivert sind, nutzen Sie bitte den Updater über die Kommandozeile.

Für weitere Hilfen, schauen Sie bitte in die [Dokumentation](https://docs.nextcloud.com/server/26/go.php?to=admin-cli-upgrade)."

### Calendar app version

3.4

### CalDAV-clients used

davx5

### Browser

chrome

### Client operating system

windows 11 pro

### Server operating system

unraid

### Web server

Apache

### Database engine version

None

### PHP engine version

PHP 8.1

### Nextcloud version

26

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
not able to provide
```

### Nextcloud configuration

```Text
not able to provide
```

### Web server error log

```Text
not able to provide
```

### Log file

```Text
not able to provide
```

### Browser log

```Text
not able to provide
```

### Additional info

Opened the same issue on github for nextcloud-aio

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/all-in-one/discussions/2716#discussioncomment-6118612 and below

**Comment by thomas-mc-work** [comment]
Outcome form the linked issue:

    occ upgrade

That command executes the update on a CLI level, which seems to be required here. But this shouldn't happen for a minor app update. So still not sure about the cause of it.

**Comment by szaimen** [comment]
From https://github.com/nextcloud/all-in-one/discussions/2716#discussioncomment-6118613:

> The bug is reported to https://github.com/nextcloud/calendar/issues/5191  and will be fixed with https://github.com/nextcloud/calendar/pull/5295

**Comment by AbelLykens** [comment]
Can confirm it works using `occ upgrade` after receiving the error.

**Comment by GretaD** [comment]
I will release a patch today with the fixup

**Comment by GretaD** [comment]
this is fixed here: https://github.com/nextcloud/calendar/pull/5295 please update to 4.4.1

**Comment by 0xErnie** [comment]
The update from 4.3.* to 4.4.1 was unsuccessfull on my nc 26.0.2.
An` occ upgrade` resolved the problem.
