### ISSUE TITLE
NC12.0.0 + PHP-fpm + Calender-App = 100% CPU usage

### ISSUE THREAD

**Issue by hollerauer** [nextcloud/calendar#530]
Only a reverence to a NC-forum-post:
https://help.nextcloud.com/t/php-fpm-using-100-cpu/14731/6

**Comment by hollerauer** [comment]
Second topic facing this problem:
https://help.nextcloud.com/t/after-update-11-0-3-to-12-final-from-beta-chan-calendar-loading-infinitly-and-php-fpm-100-cpu-usage/12876/1

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issuesg

**Comment by hollerauer** [comment]
Isn't it possible to move an issue to another repository?

**Comment by georgehrke** [comment]
No, otherwise I would have done that.

But honestly I think it's a configuration issue

**Comment by tcitworld** [comment]
We use https://github-issue-mover.appspot.com/ for the different wallabag repo, maybe we could give it a try ?
