### ISSUE TITLE
Error: Database error when running migration 4004Date20230414163505 for app calendar

### ISSUE THREAD

**Issue by solracsf** [nextcloud/calendar#5304]
### Steps to reproduce

1. `occ app:update --all`
2. Error: Database error when running migration 4004Date20230414163505 for app calendar", "Migration step 'OCA\\Calendar\\Migration\\Version4004Date20230414163505' is unknown
3. `occ upgrade` fixes the instance
4. Same error on 2 different instances

### Expected behavior

Migration is fine

### Actual behaviour

Error.

### Calendar app version

4.4.1

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.7

### Updated from an older installed version or fresh install

Updated from an older version

### Log file

```Text
Error: Database error when running migration 4004Date20230414163505 for app calendar", "Migration step 'OCA\\Calendar\\Migration\\Version4004Date20230414163505' is unknown
```

**Comment by melroy89** [comment]
Duplicate: https://github.com/nextcloud/calendar/issues/5191

**Comment by ChristophWurst** [comment]
Yes

**Comment by solracsf** [comment]
>The new release 4.4.1 should fix this issue again.. Correct?

But...this is the 4.4.1 release I'm trying to install 😞

**Comment by drhirn** [comment]
> The new release 4.4.1 should fix this issue again.. Correct?

Unfortunately not. Had the same error than @solracsf. And after that I'm getting:

```
The files of the app files_trashbin (files_trashbin), files_versions (files_versions) were not replaced correctly. Make sure it is a version compatible with the server.
```

NC 26
Tried to update from Calendar 4.3.4 to 4.4.1

**Comment by ChristophWurst** [comment]
The calendar release does not fix upgrade errors with files version or files trashbin. What we fixed is the missing class error.

**Comment by solracsf** [comment]
@ChristophWurst it is not fixed on my side apparently...

**Comment by Struppie** [comment]
maybe also worth to take a look into this related issue? [2727](https://github.com/nextcloud/all-in-one/issues/2727)

**Comment by flozz** [comment]
I tried to update calendar from v4.3.4 to 4.4.1 and I still have the db migration issue. 

![20230610_192238](https://github.com/nextcloud/calendar/assets/971438/930c0ae9-7e87-4242-a867-0c871679ae32)

**Comment by sksksksk** [comment]
same here. From 4.3.5 to 4.4.1 on latest nextcloud 25 series.
After the error, when trying to view another page on nextcloud, I was presented with the maintenance screen, telling me that an update was pending. I confirmed to proceed with the update, and everything was resolved

**Comment by Struppie** [comment]
@flozz @sksksksk Solution mentioned in above link to issue [https://github.com/nextcloud/all-in-one/issues/2727](2727)

**Comment by Phoenix1747** [comment]
> same here. From 4.3.5 to 4.4.1 on latest nextcloud 25 series.
> After the error, when trying to view another page on nextcloud, I was presented with the maintenance screen, telling me that an update was pending. I confirmed to proceed with the update, and everything was resolved

Same here.

Only that after clicking on that "proceed update" button, I got another error, telling me to refresh the website. After doing so, the server is now completely crashed Error 503. Great.

**Comment by ChristophWurst** [comment]
> After doing so, the server is now completely crashed

logs?

**Comment by ChristophWurst** [comment]
> @ChristophWurst it is not fixed apparently...

Provide us with your nextcloud.log entries written during the upgrade. What is the error you get with 4.0.1?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/issues/5191#issuecomment-1585861575 as a counter example

**Comment by ChristophWurst** [comment]
What PHP version do you all use and what are your opcache settings? I could imagine that the old (and faulty) autoloader was still active because opcache didn't clear early enough.

**Comment by ChristophWurst** [comment]
The 4.4.1 release does contain an autoloader mapping for

```
'OCA\\Calendar\\Migration\\Version4004Date20230414163505' => $baseDir . '/lib/Migration/Version4004Date20230414163505.php',
```

in vendor/composer/autoload_classmap.php.

**Comment by solracsf** [comment]
@ChristophWurst `opcache.cli` is disabled, and app update has been performed on CLI. Using PHP v8.1.

```
{
  "reqId": "xivzUkHEkn4kLH2esu1D",
  "level": 3,
  "time": "2023-06-09T22:06:41+02:00",
  "remoteAddr": "",
  "user": "--",
  "app": "app:update",
  "method": "",
  "url": "--",
  "message": "Failure during update of app \"calendar\"",
  "userAgent": "--",
  "version": "25.0.7.1",
  "exception": {
    "Exception": "Exception",
    "Message": "Database error when running migration 4004Date20230414163505 for app calendar\nMigration step 'OCA\\Calendar\\Migration\\Version4004Date20230414163505' is unknown",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/lib/private/legacy/OC_App.php",
        "line": 1008,
        "function": "migrate",
        "class": "OC\\DB\\MigrationService",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Installer.php",
        "line": 200,
        "function": "updateApp",
        "class": "OC_App",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/core/Command/App/Update.php",
        "line": 107,
        "function": "updateAppstoreApp",
        "class": "OC\\Installer",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php",
        "line": 255,
        "function": "execute",
        "class": "OC\\Core\\Command\\App\\Update",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 1009,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Command\\Command",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 273,
        "function": "doRunCommand",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 149,
        "function": "doRun",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Console/Application.php",
        "line": 214,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/console.php",
        "line": 100,
        "function": "run",
        "class": "OC\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/occ",
        "line": 11,
        "args": [
          "/var/www/nextcloud/console.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/DB/MigrationService.php",
    "Line": 420,
    "Previous": {
      "Exception": "InvalidArgumentException",
      "Message": "Migration step 'OCA\\Calendar\\Migration\\Version4004Date20230414163505' is unknown",
      "Code": 0,
      "Trace": [
        {
          "file": "/var/www/nextcloud/lib/private/DB/MigrationService.php",
          "line": 513,
          "function": "createInstance",
          "class": "OC\\DB\\MigrationService",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/DB/MigrationService.php",
          "line": 416,
          "function": "executeStep",
          "class": "OC\\DB\\MigrationService",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/legacy/OC_App.php",
          "line": 1008,
          "function": "migrate",
          "class": "OC\\DB\\MigrationService",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/Installer.php",
          "line": 200,
          "function": "updateApp",
          "class": "OC_App",
          "type": "::",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/nextcloud/core/Command/App/Update.php",
          "line": 107,
          "function": "updateAppstoreApp",
          "class": "OC\\Installer",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php",
          "line": 255,
          "function": "execute",
          "class": "OC\\Core\\Command\\App\\Update",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
          "line": 1009,
          "function": "run",
          "class": "Symfony\\Component\\Console\\Command\\Command",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
          "line": 273,
          "function": "doRunCommand",
          "class": "Symfony\\Component\\Console\\Application",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
          "line": 149,
          "function": "doRun",
          "class": "Symfony\\Component\\Console\\Application",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/Console/Application.php",
          "line": 214,
          "function": "run",
          "class": "Symfony\\Component\\Console\\Application",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/console.php",
          "line": 100,
          "function": "run",
          "class": "OC\\Console\\Application",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/occ",
          "line": 11,
          "args": [
            "/var/www/nextcloud/console.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/var/www/nextcloud/lib/private/DB/MigrationService.php",
      "Line": 498
    },
    "message": "Failure during update of app \"calendar\"",
    "exception": [],
    "CustomMessage": "Failure during update of app \"calendar\""
  },
  "id": "6485eb2000ae9"
}
```

**Comment by ChristophWurst** [comment]
I was able to trigger it myself with an upgrade from 4.3.0 to 4.4.1

![image](https://github.com/nextcloud/calendar/assets/1374172/4ddd7a54-331f-41df-a1be-5929265ce255)

The issue is that https://github.com/nextcloud/calendar/pull/5295 fixes the autoloader but the autoloader fix for an upgrade only takes affect for *future* upgrades. So 4.4.2 or 4.5.0 will be fine only :s

**Comment by ChristophWurst** [comment]
4.4.0 and 4.4.1 removed from https://apps.nextcloud.com/apps/calendar/. Tomorrow I'll

1) Make sure we get out a release with a revert of the feature that needs a migration, but fix the autoloader
2) Do another release with the migration and a then working autoloader
3) Find out why server remains in maintenance mode after a failed migration. It should just disable the app

**Comment by flozz** [comment]
I just updated 4.3.4 to 4.3.5 without any issue :)

**Comment by ChristophWurst** [comment]
A verbose summary of what went wrong: https://help.nextcloud.com/t/post-mortem-analysis-composer-authoritative-classloader/163969

Thanks for the reports and system infos, everyone.

**Comment by flozz** [comment]
4.3.5 updated to 4.4.2 flawlessly :ok_hand:

**Comment by ChristophWurst** [comment]
This is done. The reverted feature will revive with v4.5.
