### ISSUE TITLE
Daily email digest

### ISSUE THREAD

**Issue by DouisLavid** [nextcloud/calendar#5314]
### Is your feature request related to a problem? Please describe.

The problem I am facing is trying to get an overview of the events in my calendar, without having to open the calendar, but through a notification system.

### Describe the solution you'd like

What I would like is to receive a daily email at the start of the day (say at 6 in the morning, but that probably should be adjustable) with a summary of the events planned for the day.

### Describe alternatives you've considered

Right now, it is only possible to receive one (or several) email notifications for an event, but it is not possible to set the notification at a fixed time the day of the event. Having such emails grouped into one is also impossible.

**Comment by tcitworld** [comment]
There's an application doing that : https://apps.nextcloud.com/apps/calendar_news

**Comment by DouisLavid** [comment]
Oh thank you very much :) I have not quite figured out the configuration options yet, but the app looks awesome !

**Comment by DouisLavid** [comment]
Oh thank you very much :) I have not quite figured out the configuration options yet, but the app looks awesome !
