### ISSUE TITLE
Feature Request: Tweak Default Start Time

### ISSUE THREAD

**Issue by dominic-p** [nextcloud/calendar#532]
### Steps to reproduce
1. Create an event (it defaults to "All Day")
2. Uncheck the All day Event checkbox
3. The start time for the event is set at 12 AM

It's a minor thing, but I don't have too many events that start at midnight. :) Google Calendar currently defaults to 10 AM which is a nice feature in my opinion. As it is now, if a user unchecks the "All day Event" checkbox and forgets to update the start time, they can get reminders in the middle of the night.

Again, it's a minor issue, but I thought I would bring it up. Keep up the great work.

**Comment by georgehrke** [comment]
cc @jancborchardt 

10am seems like a good choice.

btw, you can also click on the disabled time-input to choose a time right away without disabling allday first :)

**Comment by dominic-p** [comment]
Thanks for the quick response. That's a nice tip about clicking on the time input first, I didn't know you could do that.

**Comment by jancborchardt** [comment]
Absolutely agree, I have the same issue with the Android calendar app Etar.

Defaulting to 10 AM is good, and setting the end time to 11 AM.
