### ISSUE TITLE
Privat Share of a native Nextcloud Calendar

### ISSUE THREAD

**Issue by Riariseriam** [nextcloud/calendar#5328]
### Is your feature request related to a problem? Please describe.

Situation:
1. I created a calendar ("Calendar A") in my Nextcloud ("Nextcloud A") account (not linked to google or else). I integrated it into my OS / iOS etc. It works perfectly.

2. Then I created another calendar ("Calendar B") in my second Nextcloud ("Nextcloud B") for the App "Appointments". 

3. Now I'd like to "stream" Calendar A from Nextcloud A to Nextcloud B to use it as the source for appointments to check for available time slots.

Problem:
-> I could now make Calendar A public and follow it with Nextcloud B - BUT: I don't want it to be public. I'd like to have the opportunity to import a **privat link for Calendar** A.

-> With my Google Calendar I can generate a private Link to do that (a non public url). Nextcloud does show me the Option of Copying a private Link but if I try to integrate that, it does not ask for authentication or else and is therefor not showing any events. Did I do something wrong, or is it really something nobody had asked for yet?

Sorry in advance, if this is the wrong place for my request or if I did not explain it correctly. Please be nice I am totally new here.

### Describe the solution you'd like

I'd like to find the option to Copy a private Link with a non public address from Calendar A inside Nextcloud's Calendar App (Web Application)

**Comment by ChristophWurst** [comment]
Generate an internal link and use it as subscription on the other instance

**Comment by ChristophWurst** [comment]
![image](https://github.com/nextcloud/calendar/assets/1374172/39101bea-a743-44e7-b8fb-a2a3b56700d2)

**Comment by Riariseriam** [comment]
OMG I should've waited until the update was done. Just updated my NC-version and there it is...Thank you though! And sorry!

**Comment by ChristophWurst** [comment]
no worries

**Comment by Riariseriam** [comment]
Hi again, It was late yesterday...I do now see the additional button (share link and Internal Link) but it still does not work. I saw a couple of discussions about federated calendar sharing which would solve my issue too, but couldn't see, what the status on this is. Is this still an ongoing process? If yes, could somebody please tag the issue here, so I can follow the progress and maybe could contribute some use cases?

**Comment by Riariseriam** [comment]
> Generate an internal link and use it as subscription on the other instance

Does not work :/
