### ISSUE TITLE
Feature suggestion: logging to support debugging of the Calendar App

### ISSUE THREAD

**Issue by kreil** [nextcloud/calendar#535]
We observe a number of erratic issues when adding a subscription to the private link of a google calendar. Sometime the subscription request hangs forever, for a calendar that worked perfectly fine before, and again some time later. Sometimes the subscription completes, but no events are shown.

Is there a log that we can consult to see at what stage the calendar app might run into problems?

If not, may I kindly request to add some form of logging for debugging?

**Comment by georgehrke** [comment]
Did you check the JavaScript log?

**Comment by kreil** [comment]
Ah, we'll check!

Many thanks,
David
