### ISSUE TITLE
subscription vs download?

### ISSUE THREAD

**Issue by kreil** [nextcloud/calendar#537]
Perhaps my understanding of the Calendar App is wrong - I thought that by adding a URL to an .ics file, that would link my nextcloud calendar to an external calendar - with changes at the external calendar reflected on my nextcloud calendar more or less real-time.

That does not seem to be the case: When I add a subscription to a google calendar (private ics link), the nextcloud calendar is populated with the currently stored events. When I add an event on google, however, that does not seem to propagate to my nextcloud calendar. Perhaps related, I apparently cannot edit or add events to a subscribed to calendar.

Is that both as design intended, or is that an error in my setup?

**Comment by georgehrke** [comment]
> When I add an event on google, however, that does not seem to propagate to my nextcloud calendar.

Subscriptions are cached for two hours, give it some time to refresh ;) 

>  Perhaps related, I apparently cannot edit or add events to a subscribed to calendar.

Subscriptions are read-only. That's by design and won't be changed.

**Comment by kreil** [comment]
Ah, thank you very much!

Is there a document where I could have found out without bothering you on
the github issue tracker?

Many thanks,
David

**Comment by georgehrke** [comment]
> Is there a document where I could have found out without bothering you on
the github issue tracker?

I'm afraid not yet, but we are working on improving the calendar documentation.

**Comment by kreil** [comment]
Thank you for your fast an generous help. I really appreciate it. I'm very
excited by the nextcloud project, and we're trying to wean our research
institute off google, as that's blocked both in China and in many hospitals
and regulatory agencies in the US and Europe.

Best regards,
David

**Comment by MariusBluem** [comment]
> I'm afraid not yet, but we are working on improving the calendar documentation.

Subscription vs. Sharing - good idea 😅🙈 #docs

**Comment by kreil** [comment]
If I can meaningfully contribute I would be happy to do so.

Best regards,
David

**Comment by MariusBluem** [comment]
@kreil Very much stuff to do yet, since we have no calendar-documentation at all at the moment. I am currently working on it. Would be great to have your review when my pull request is open 💪

**Comment by kreil** [comment]
Great, please let me know when/what I can do. I must admit we're absolute
beginners in nextcloud but working in IT for the last two decades, so
perhaps good guinea pigs for draft documentation.

From our perspective, a lot of people will be switching from google cloud
products, so it may be helpful to have short sections highlighting
differences in philosophy / feature sets.

/bw
