### ISSUE TITLE
.ics imported event has wrong date

### ISSUE THREAD

**Issue by langfingaz** [nextcloud/calendar#5373]
### Steps to reproduce

1. Download the `.ics` file https://cloud.privacy1st.de/s/7kTHqKcpNWLJ92L containing only one event.
2. Import the `.ics` file in your browser with the Nextcloud calendar app and select one existing calendar.

### Expected behavior

3. There should be a new event in the selected calendar. It should have the date 2023-08-14.

This is the relevant part of the event from the `.ics` file:

```ics
DTSTART;TZID=Europe/Berlin:2023-08-14T081800
DTEND;TZID=Europe/Berlin:2023-08-14T113100
```

### Actual behaviour

3. There is a new event in the calendar with the date 2022-12-08.

### Calendar app version

4.4.3

### CalDAV-clients used

None

### Browser

Firefox 115.0.2

### Client operating system

Arch Linux

### Server operating system

Nextcloud Docker Image

### Web server

Nginx

### Database engine version

Maria DB

### Nextcloud version

26.0.3

### Updated from an older installed version or fresh install

Updated from older version.

### Log file

I checked my log but there is no new entry that appeared.

### Additional info

This is the full content of the `.ics` file:

```ics
BEGIN:VCALENDAR
X-LOTUS-CHARSET:UTF-8
VERSION:2.0
PRODID:http://www.bahn.de
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
UID:bahn2023-08-14081800
CLASS:PUBLIC
SUMMARY:Erlangen -> Berlin Hbf (tief)
DTSTART;TZID=Europe/Berlin:2023-08-14T081800
DTEND;TZID=Europe/Berlin:2023-08-14T113100
DTSTAMP:2023-07-21T194800Z
DESCRIPTION:Reise: Erlangen nach Berlin Hbf (tief)\nDatum: 14.08.2023\n\nab Erlangen 08:18\nan Berlin Hbf (tief) 11:31\n\nReisen Sie entspannt und ohne Ticketkontrolle. Nutzen Sie den Komfort Check-in sobald Sie Ihren Sitzplatz erreicht haben. Einfach und schnell unter https://www.img-bahn.de/s3/prod/kci/index.html?dbkanal_009=KCI-Kalenderexport#/dl/Q01WVUdL/mTk5PM6P9FFC8mRU7jVhtw==/2\n\nAlle Angaben ohne Gewähr. Fahrplanänderungen vorbehalten. Bitte prüfen Sie kurz vor der Reise den aktuellen Fahrplan unter: www.bahn.de
X-ALT-DESC;FMTTYPE=text/html:<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/ 12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head></head><body lang=DE><div class=WordSection1><p class=MsoNormal>Reise: Erlangen nach Berlin Hbf (tief)<br>Datum: 14.08.2023<br><br>ab Erlangen 08:18<br>an Berlin Hbf (tief) 11:31<br><br>Reisen Sie entspannt und ohne Ticketkontrolle. Nutzen Sie den Komfort Check-in sobald Sie Ihren Sitzplatz erreicht haben. Einfach und schnell unter <a href="https://www.img-bahn.de/s3/prod/kci/index.html?dbkanal_009=KCI-Kalenderexport#/dl/Q01WVUdL/mTk5PM6P9FFC8mRU7jVhtw==/2">www.bahn.de/jetzt-einchecken</a>.<br><br>Alle Angaben ohne Gewähr. Fahrplanänderungen vorbehalten. Bitte prüfen Sie kurz vor der Reise den aktuellen Fahrplan unter: www.bahn.de<br></p></div></body></html>
END:VEVENT
END:VCALENDAR
```

**Comment by auroraanna** [comment]
This doesn't seem to be an issue with Nextcloud Calendar but with the format of the date used in your provided iCalendar file.

**Comment by auroraanna** [comment]
Other tools are parsing the start and end date the same as Nextcloud calendar.

**Comment by auroraanna** [comment]
You didn't provide a valid iCalendar file. According to https://icalendar.org/iCalendar-RFC-5545/3-3-5-dhave ate-time.html you can't dashes in between the year and hour, and in between the hour and the second. I found this out by [validating your iCalendar file](https://icalendar.org/validator.html#results).

**Comment by auroraanna** [comment]
Assuming that a DB service automatically exported your file, it exported it wrongly. You should contact the DB about this, it is not the fault of Nextcloud Calendar afaik.

**Comment by langfingaz** [comment]
> You didn't provide a valid iCalendar file. According to https://icalendar.org/iCalendar-RFC-5545/3-3-5-date-time.html you can't dashes in between the year and hour, and in between the hour and the second. I found this out by [validating your iCalendar file](https://icalendar.org/validator.html#results).

Thanks for having a look and identifying the problem. Please excuse the efforts caused. I will inform DB about this.
