### ISSUE TITLE
Allow CSV importing

### ISSUE THREAD

**Issue by techrivertree** [nextcloud/calendar#5375]
### Is your feature request related to a problem? Please describe.

Cannot upload CSV calendars.

### Describe the solution you'd like

Add the option to upload calander data from CSV files. Mircrocraps outlook only allows exports as CSV.

### Describe alternatives you've considered

Online converters (full of viruses, ads, etc). Three different github programs (none would work or install correctly).

**Comment by tcitworld** [comment]
Unfortunately implementing CSV parsing would be out of the scope of this app (picking which columns match which type, etc.).

It seems recent Outlook versions have ICS export support?
https://support.microsoft.com/en-us/office/export-an-outlook-calendar-to-google-calendar-662fa3bb-0794-4b18-add8-9968b665f4e6
