### ISSUE TITLE
Assign attendees as Talk room participants when creating a room from an event

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5376]
### Is your feature request related to a problem? Please describe.

As a user I want to be able to create a new event, assign attendees and create a Talk room for the event. This works already,  but is limited. I'm the moderator of the conversation. The attendees see the room URL in the event description, but don't see the conversation in Talk until they click the link. Once the tab is left the conversation vanishes from their rooms again.

For a scheduled meeting this could mean that attendees do not see a call notification because they are not in the room.

### Describe the solution you'd like

Attendees should automatically be added as participants of the created conversation, as long as their email can be associated with a Nextcloud user.
If another attendee is added to the event later on, it has to be added as participant as well.
If an attendee is removed, it must not be removed from the participants in Talk.
Attendees who can't be associated with a Nextcloud user (no match or more than one match) shall be ignored. If no user is found the attendee is likely an external person.

### Describe alternatives you've considered

N/a

### Additional context

N/a

**Comment by tcitworld** [comment]
> If another attendee is added to the event later on, it has to be added as participant as well.

That can be handled by event listeners in the Talk app.

> Attendees who can't be associated with a Nextcloud user (no match or more than one match) shall be ignored. If no user is found the attendee is likely an external person.

Could make sense to make the room public and send them the link then (into the invitation email sent by scheduling).

**Comment by ChristophWurst** [comment]
Adding participants is easy: https://nextcloud-talk.readthedocs.io/en/latest/participant/#add-a-participant-to-a-conversation

BUT the Talk API expects a *user ID* while in Calendar we only have *emails* for the attendee identification. We will need to translate between the two identifiers.

**Comment by ChristophWurst** [comment]
We can use https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-api-overview.html?highlight=isp#auto-complete-and-user-search for the mapping.
