### ISSUE TITLE
Appointment: Show some indicator that the free slots are still loaded

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#5384]
### Steps to reproduce

I have a quite large calendar and also selected multiple calendars to check for free slots. This means that the search takes quite some time.

During the loading time the user see this:

![grafik](https://github.com/nextcloud/calendar/assets/1589737/2e380a22-0f5b-45fe-9689-5d418ab8bd88)

This might make them think that there are no appointment slots available. If they are not used to talk they don't know about the "No slots available" message they should wait for. This might results in people click to quick through the dates and don't find all available slots or none at all.

### Expected behavior

Some indicator that the free slots are still loaded.

Maybe a message like `Wait a moment... looking for available slots. <a spinner>`

### Actual behaviour

no indicator that available slots are still loaded

### Calendar app version

4.4.3

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by st3iny** [comment]
Fixed by https://github.com/nextcloud/calendar/pull/4289.
