### ISSUE TITLE
Improve handling of links for online events

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5389]
### Is your feature request related to a problem? Please describe.

As a user of online meetings I want a smooth experience for links I have to open to join a call.

### Describe the solution you'd like

1. Write the conference URL into the location field when creating Talk rooms for an event. https://github.com/nextcloud/calendar/pull/5395
2. Implement a clickable link for the location field. https://github.com/nextcloud/calendar/pull/5355
3. Render the location field as a clickable link in the appointment notification mail (if it contains a link). https://github.com/nextcloud/server/pull/39753

### Additional context

This is an alternative approach to https://github.com/nextcloud/calendar/issues/1758 while it's poorly supported by other clients.

**Comment by tcitworld** [comment]
I don't think 3. can be made with the current email template system. Maybe with the help of https://github.com/nextcloud/server/pull/38093 ? :smirk_cat:

**Comment by ChristophWurst** [comment]
``\OCA\DAV\CalDAV\Schedule\IMipService::addMoreOptionsButton`` renders the "More options…" in emails. Can we use that?
