### ISSUE TITLE
Quand je décline le rendez vous directement sur l'évenement sa envoi un mail d'acceptation et pas un mail de déclinement.

### ISSUE THREAD

**Issue by mat97411974** [nextcloud/calendar#5406]
### Steps to reproduce

1. Je vais sur l'agenda.
2. Je clique sur le plus pour ajouter les horaires de rendez-vous possible.
3. Puis-je test de prendre un rendez-vous ?
4. Quand le rendez-vous est pris par une autre personne, je le vois comme un événement.
5. Et quand je vais sur l'événement est, je clique sur décliné le rendez-vous ça envoie un message d'acceptation et pas un message de refus, mais si je passe par le mail pour décliner ça fonctionne ?

### Expected behavior

Quand, je clique sur décliner. Il doit avoir un envoyer de message de refus.

### Actual behaviour

Quand, je clique sur décliner. Il envoie un message d'acceptation.

### Calendar app version

4.4.4

### Browser

Firefox 115.0.3 (64 bits)

### Client operating system

windows

### Server operating system

ubuntu

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

26.0.4

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
Hi @mat97411974. Please file a ticket in English. Cheers
