### ISSUE TITLE
Fix Loading animation of appointment booking

### ISSUE THREAD

**Issue by hamza221** [nextcloud/calendar#5409]
### Is your feature request related to a problem? Please describe.

When booking an appointment, After filling the information and clicking the 'Book the appointment'  button.
The button stays enabled (You can start multiple requests ) and no indication that it's loading.
![image](https://github.com/nextcloud/calendar/assets/40746210/0b0a97d9-5d69-4c1b-8bf9-5722717014df)

### Describe the solution you'd like

Disable the button and add loading animation

**Comment by tcitworld** [comment]
Isn't that already done wit https://github.com/nextcloud/calendar/pull/5244 ?

**Comment by hamza221** [comment]
[Screencast from 2023-08-11 18-52-12.webm](https://github.com/nextcloud/calendar/assets/40746210/1946e810-dad7-4c51-a37a-6762100fb26b)
on latest main :/

**Comment by hamza221** [comment]
It was just broken, The Pr should fix it
