### ISSUE TITLE
Button "Create a Talk room" not visible when adding appointment

### ISSUE THREAD

**Issue by jonas2515** [nextcloud/calendar#5413]
### Steps to reproduce

1. Click the "+" button to create a new appointment
2. Button "Create a Talk room" is not shown

### Expected behavior

The button "Create a Talk room" should be visible.

### Actual behaviour

The button "Create a Talk room" is hidden, even though NC Talk is correctly configured and the app is enabled. This was independently reproduced on 3 differently configured Nextcloud instances.

From debugging the server, it seems like everything is in place and the Talk app is correctly reported as enabled to the client.

### Calendar app version

4.4.4

### Browser

Firefox and chromium

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

27.0.2

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
Switch to the attendee tab

**Comment by jonas2515** [comment]
Sorry if I was unclear: I didn't mean the button to create a talk room for a new event, but the one that enables automatically creating talk rooms for booked appointments via the Appointements feature.

In the feature presentation from nextcloud, it looked like this:

![Bildschirmfoto 2023-07-07 um 12 28 50](https://github.com/nextcloud/calendar/assets/4084097/c20a5f88-4b6c-41a7-841e-9057bd1f6704)

**Comment by karthikiyengar** [comment]
I can confirm this behaviour on Nextcloud Hub 5 (27.0.2) with Snap ([related forum issue](https://help.nextcloud.com/t/nextcloud-hub-5-does-not-show-option-to-create-a-talk-room-for-appointments/169158))

**Comment by miaulalala** [comment]
Unfortunately this feature had to be disabled because of issues with the upgrade: https://github.com/nextcloud/calendar/pull/5306

But it will be back with 4.5.0 which is due to be released soon. If you like, you can try the Release Candidate:
https://github.com/nextcloud-releases/calendar/releases/tag/v4.5.0-rc1
