### ISSUE TITLE
Convert new calendar with task list to a list of tasks on the nextcloud tasks application

### ISSUE THREAD

**Issue by brahimjarallah** [nextcloud/calendar#5424]
###  feature request related to a problem: 
When we create a "**_new calendar with task list_**"  we cannot convert their tasks thats we have been created manually on calendar day view or week view (with tasks clicked by mouse) ==>  **to be converted to the nextcloud "Tasks" application**.

(we appreciate that the same things to be done with the the default nextcloud calendar without task list)

###  the solution i'd like

Make the "new Calendar with task list" **to be convertable to the nextcloud "Tasks" application**
(like "`ticktick` android app" calendar can be converted to task list and tickable)

(we appreciate that the same things to be done with the the default nextcloud calendar without task list)

**Comment by brahimjarallah** [comment]
??????????????

**Comment by tcitworld** [comment]
Calendars with task list can hold both events (`VEVENTS`) and tasks (`VTODO`). Events can only be edited in the calendar app and tasks only in the Tasks app (but they can appear in the calendar view).

Going from that, there's the following limitations :
* Events cannot be converted to tasks. The common information in both objects is very low, so the benefit wouldn't be great.
* Calendars with task lists can not be converted to calendars only (or task lists only).

**Comment by brahimjarallah** [comment]
the problem is that we have to always add tasks manually on tasks app yet we couldn't add them on calendar view directly without the headache of adding due date and time for every task? understood??

**Comment by brahimjarallah** [comment]
> Calendars with task list can hold both events (`VEVENTS`) and tasks (`VTODO`). Events can only be edited in the calendar app and tasks only in the Tasks app (but they can appear in the calendar view).
> 
> Going from that, there's the following limitations :
> 
> * Events cannot be converted to tasks. The common information in both objects is very low, so the benefit wouldn't be great.
> * Calendars with task lists can not be converted to calendars only (or task lists only).


the problem is that we have to always add tasks manually on tasks app yet we couldn't add them on calendar view directly without the headache of adding due date and time for every task? understood??

**Comment by brahimjarallah** [comment]
??!!

**Comment by tcitworld** [comment]
If the issue is that you want to create and manage tasks in the calendar app, please open a new dedicated issue to that extent.
