### ISSUE TITLE
Certificate Revoked 

### ISSUE THREAD

**Issue by wjwieland** [nextcloud/calendar#543]
### Steps to reproduce
1. Start ownCloud web interface
2. Warning appears

### Expected behaviour
Clean start of ownCloud web interface.  There should be no warnings of integrity checks.

### Actual behaviour
Opens with the following warning(for administrator only):
"There were problems with the code integrity check. More information..."

Following the link:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.

Raw output
==========
Array
(
    [calendar] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate has been revoked.
                )

        )

)
### Server configuration

**Operating system**: Ubuntu 16.04
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch

**Web server:**  
Apache2

**Database:** 
MySQL

**PHP version:** 
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )

**Server version:** (see your admin page) 
9.1.6

**Calendar version:** (see the apps page) 
1.4.1

**Updated from an older installed version or fresh install:** 
Updated

**Signing status (ownCloud/Nextcloud 9.0 and above):** 
"Example Domain

This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission."

More information...
**List of activated apps:**
```Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - notifications: 0.3.0
  - systemtags: 0.3.0
  - tasks: 0.9.4
  - templateeditor: 0.1
Disabled:
  - documents
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - files_texteditor
  - files_versions
  - firstrunwizard
  - ownnote
  - provisioning_api
  - updatenotification
  - user_external
  - user_ldap

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "ocx1beox5uba",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "wjwieland.dvrdns.org",
            "192.168.0.15",
            "wjwieland.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.6.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "wjw",
        "mail_domain": "wjwieland.com",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "maintenance": false,
        "updatechecker": false,
        "loglevel": 2,
        "defaultapp": "calendar",
        "mail_smtphost": "mail.wjwieland.com",
        "mail_smtpport": "587",
        "theme": ""
    }
}

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:**
no


### Client configuration
**Browser:** 
Google Chrome 
Version 59.0.3071.115 (Official Build) (64-bit)

**Operating system:**
Ubuntu 16.04
Window 10

**CalDAV-clients:**

### Logs
[error.log.zip](https://github.com/nextcloud/calendar/files/1165932/error.log.zip)
[owncloud.log.zip](https://github.com/nextcloud/calendar/files/1165936/owncloud.log.zip)
[browser.log.zip](https://github.com/nextcloud/calendar/files/1165938/browser.log.zip)

**Comment by georgehrke** [comment]
#489

**Comment by georgehrke** [comment]
#498 sorry
