### ISSUE TITLE
Calendar sharing does not work with group with accentued characters in their names

### ISSUE THREAD

**Issue by Reventl0v** [nextcloud/calendar#544]
### Steps to reproduce
0. Install the calendar app;
1. Create two groups, named "group 1" and "É group 2" (for example);
2. Create an user "user" and add it to the two groups;
2. Create two calendar, calendar "É calendar 1" and "É calendar 2";
3. Share "É calendar 1" with "group 1", "É calendar 2" with "É group 2";

### Expected behaviour
Both the "É calendar 1" and "É calendar 2" should appear when you log in as "user" and go to the calendar tab.

### Actual behaviour
Only the "É calendar 1" appears.

### Server configuration

Basic docker setup, with mariadb and nginx, with nextcloud-fpm.

I reproduced this issue on someone's else instance, so it seems reproductible, so i'm not putting a lot of details in this bugreport, but I can if this is really needed.

**Comment by georgehrke** [comment]
First of all, please use the entire issue template. There is a reason it's there. You didn't even name the Nextcloud / calendar version you use.

Furthermore, as stated on top of the issue template:
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by Reventl0v** [comment]
Hi.

« Migration and CalDAV issues belong in the server repo! https://github.com/nextcloud/server/issues »

Well, it is not this clear this means the calendar app is just a caldav client running in the browser, and that the problem was with the caldav server and not with the client running in the browser.

But, since you seem this arbitrary about it, so that should be the case.

And, yeah, the versions, sorry about that, but of course latest version of everything, and up to date.

Have a nice day.

**Comment by georgehrke** [comment]
> And, yeah, the versions, sorry about that, but of course latest version of everything, and up to date.

Latest version of what? ;) 

of Nc 11 or Nc 12?

**Comment by Reventl0v** [comment]
Well, I was assuming NextCloud 12 was the latest version, as 12 > 11. I guess the usual order on the integers does not work with nextcloud.

**Comment by georgehrke** [comment]
This might be a duplicate of https://github.com/nextcloud/server/issues/4885

**Comment by Reventl0v** [comment]
Yeah indeed. Thanks for the hint, and sorry about having reported this in the wrong repo. I guess i'll stick to non accentued for the moment.

Bye
