### ISSUE TITLE
Calendar import sends email notifications to event attendees

### ISSUE THREAD

**Issue by 0gcr** [nextcloud/calendar#545]
### Steps to reproduce
1. Log into the Nextcloud web interface
2. In the Activity settings, verify that the "Mail" option is **unchecked** for "A calendar was modified", "A calendar event was modified", and "A calendar todo was modified"
3. Go to the Calendar application
4. Download an existing calendar with many multi-participant events to a file via the ".../Download" function
5. Create a new calendar
6. Import the file just downloaded into the new calendar via the "Settings & Import/Import calendar" function

### Expected behaviour
All calendar events should be imported into the new calendar. No other actions of any kind should be taken. In particular, no emails or other notifications should be sent.

### Actual behaviour
Calendar events are successfully imported, but for many (often distant) past events, **email notifications/invitations are sent to participants!** This is _extremely_ undesirable. All notifications and invitations should be completely disabled during calendar import, and notifications for past events should never be sent in any case.

### Server configuration
**Operating system**: FreeBSD hostname.domain.tld 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #2: Sat Feb 25 00:05:15 CST 2017     root@hostname.domain.tld:/usr/src/sys/amd64/compile/ALTQ amd64

**Web server:** Apache/2.4.26 (FreeBSD) OpenSSL/1.0.2k-freebsd PHP/5.6.31 (apache2handler)

**Database:** mysql 5.6.37

**PHP version:** 5.6.31
Modules loaded: Core, date, ereg, libxml, pcre, Reflection, SPL, hash, session, apache2handler, standard, apcu, bz2, ctype, curl, dom, mbstring, fileinfo, filter, gd, mysqlnd, iconv, json, ldap, exif, mysql, openssl, PDO, posix, SimpleXML, smbclient, sqlite3, tokenizer, xml, xmlwriter, zip, zlib, pdo_mysql, pdo_sqlite, Phar, wddx, xmlreader, xsl, mhash, apc, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from ownCloud:
2016
Jul  3 23:32:59 hostname pkg: owncloud upgraded: 9.0.2 -> 9.0.3
Jul 21 16:39:56 hostname pkg: owncloud upgraded: 9.0.3 -> 9.0.4
Jul 24 23:03:39 hostname pkg: owncloud upgraded: 9.0.4 -> 9.1.0
Sep 13 09:57:55 hostname pkg: owncloud upgraded: 9.1.0 -> 9.1.0_1
Oct 16 15:10:16 hostname pkg: owncloud upgraded: 9.1.0_1 -> 9.1.1
Oct 25 22:31:12 hostname pkg: nextcloud-10.0.1 installed
Oct 26 02:10:13 hostname pkg: owncloud-9.1.1 deinstalled
Dec 13 20:18:59 hostname pkg: nextcloud upgraded: 10.0.1 -> 10.0.1_1
Dec 28 11:30:15 hostname pkg: nextcloud upgraded: 10.0.1_1 -> 11.0.0
2017
Jan 18 16:58:20 hostname pkg: nextcloud upgraded: 11.0.0 -> 11.0.1
Mar  7 11:41:15 hostname pkg: nextcloud upgraded: 11.0.1 -> 11.0.2
May 11 19:24:47 hostname pkg: nextcloud upgraded: 11.0.2 -> 11.0.3
May 25 22:33:50 hostname pkg: nextcloud upgraded: 11.0.3 -> 12.0.0

**Where did you install Nextcloud from:** Official FreeBSD package repo

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[No errors have been found.]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - checksum: 0.3.5
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.0.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - encryption
 - files_pdfviewer
 - files_videoplayer
 - user_external
 - user_ldap
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>
{
    "instanceid": "ocw8ytdjhyvn",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.domain.tld"
    ],
    "datadirectory": "\/usr\/local\/www\/nextcloud\/data",
    "overwrite.cli.url": "https:\/\/cloud.domain.tld:8443",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "forceSSLforSubdomains": true,
    "preview_libreoffice_path": "\/usr\/local\/bin\/libreoffice",
    "mail_from_address": "nextcloud",
    "mail_smtpmode": "php",
    "mail_domain": "domain.tld",
    "loglevel": 0,
    "theme": "",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "trashbin_retention_obligation": "auto, 90",
    "htaccess.RewriteBase": "\/",
    "session_lifetime": 21600,
    "remember_login_cookie_lifetime": 259200,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "smtp.domain.tld",
    "mail_smtpport": "25"
}
</details>

**Are you using external storage, if yes which one:** External storage is enabled, but not used for calendars
Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OC\Files\Storage\DAV
    [2] => \OCA\Files_External\Lib\Storage\OwnCloud
    [3] => \OCA\Files_External\Lib\Storage\SFTP
    [4] => \OCA\Files_External\Lib\Storage\AmazonS3
    [5] => \OCA\Files_External\Lib\Storage\Dropbox
    [6] => \OCA\Files_External\Lib\Storage\Google
    [7] => \OCA\Files_External\Lib\Storage\Swift
    [8] => \OCA\Files_External\Lib\Storage\SFTP
    [9] => \OCA\Files_External\Lib\Storage\SMB
    [10] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
[nextcloud.log.txt](https://github.com/nextcloud/calendar/files/1168720/nextcloud.log.txt)
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/2855
