### ISSUE TITLE
Remove clipboards icon on top of each calendar event

### ISSUE THREAD

**Issue by foss-** [nextcloud/calendar#5467]
### Is your feature request related to a problem? Please describe.

Currently when showing details of a calendar event there is an icon showing two clipboards at the top. This icon looks very dated and adds no value.
![1](https://github.com/nextcloud/calendar/assets/5708172/7fba3b16-905b-4bc5-aa0f-81dc21ea1f16)

### Describe the solution you'd like

Removing that icon and just showing the event title, maybe with slightly bigger font size, would make for better UX.
This is what Apple does with their event UI:
![2](https://github.com/nextcloud/calendar/assets/5708172/48700945-d173-47a8-967a-8adebf9aa06f)

**Comment by ChristophWurst** [comment]
:eyes: @jancborchardt @marcoambrosini @nimishavijay

**Comment by marcoambrosini** [comment]
I think that we should remove these yes

**Comment by ChristophWurst** [comment]
@marcoambrosini just the clipboard or all of the illustrations?

![image](https://github.com/nextcloud/calendar/assets/1374172/4732d05c-dedb-4029-9d40-256cc32b7f6c)

**Comment by marcoambrosini** [comment]
I would remove all illustrations, I don't think they're adding any value. cc @nextcloud/designers

**Comment by szaimen** [comment]
There is https://github.com/nextcloud/calendar/issues/3543 btw where it would also be removed so I'd agree 👍

**Comment by tcitworld** [comment]
For reference, the issue where adding the illustrations was discussed : https://github.com/nextcloud/calendar/issues/968

**Comment by foss-** [comment]
> For reference, the issue where adding the illustrations was discussed : #968

Are Microsoft and Google still using event based icons in 2023? Can't see it in Microsoft Outlook Calendar https://support.microsoft.com/en-us/office/welcome-to-your-outlook-calendar-6fb9225d-9f9d-456d-8c81-8437bfcd3ebf however Google Calendar seems to use event based icons, at least on mobile, as per first screenshot on https://workspace.google.com/intl/en/products/calendar/ (see yoga and lunch event).

Personal opinion: still not a fan of this concept. Personally using Android (SimpleCalendar), iOS and macOS with Apple Calendar and wasn't even aware that context based icons for calendar events were a thing, since on those apps that concept does not exist.

**Comment by foss-** [comment]
https://github.com/nextcloud/calendar/issues/3543 got closed by https://github.com/nextcloud/calendar/pull/5675.
Does that change include Nextcloud finally getting rid of those 90s icons in calendar events?

**Comment by ChristophWurst** [comment]
@foss- you can see the details in https://github.com/nextcloud/calendar/pull/5675.
