### ISSUE TITLE
Appointment booking with automated talk room creation: incomplete room name

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#5472]
### Steps to reproduce

1. Setup a appointment calendar and enable automated talk room creation
2. book a appointment
3. look at the created talk room

### Expected behavior

As I would expect and also according the code: https://github.com/nextcloud/calendar/blob/main/lib/Listener/AppointmentBookedListener.php#L87

The room should be names `<appointment name> with <person who booked it>`

### Actual behaviour

The room is just called `<appointment name>`

Tested on c.nc.com 27.1.0 RC3

### Calendar app version

4.5.0-rc2

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
@miaulalala could you debug this please?

**Comment by miaulalala** [comment]
I can't reproduce:

![image](https://github.com/nextcloud/calendar/assets/7427347/73058aa8-0344-45f9-9337-f335cf5fbb5a)

**Comment by schiessle** [comment]
I just tested it again and it works now for me as well... As so often, the problem was in front of the screen :see_no_evil: 

I still had a link to a static room in the appointment setting and the static room was named "appointment name". After I removed it the link, right room was created and added to the event.

Sorry for the noise.
