### ISSUE TITLE
README documentation out of date

### ISSUE THREAD

**Issue by privatemaker** [nextcloud/calendar#5478]
### Steps to reproduce

1. Read the README.md
2. Clone the repo
3. Run the command `make`

### Expected behavior

As a new contributor to Calendar, I want to easily following instructions in the README.md file of how to start developing. 

Currently, I am stuck on the first step of `Build the app` documentation, as the `make` command does not complete successfully.

### Actual behaviour

After many steps `make` seems to complete correctly, but the `make` command ends with an error about about a missing `phpunit.xml` file.

### Calendar app version

3be608530450eb509b38d761b4003e369413ecf7

### Server operating system

Debian 12

### Nextcloud version

28

### Updated from an older installed version or fresh install

fresh install

### Web server error log

```Text
...

Test Suites: 60 passed, 60 total
Tests:       356 passed, 356 total
Snapshots:   25 passed, 25 total
Time:        63.094 s
Ran all test suites.
phpunit -c phpunit.xml
Could not read "phpunit.xml".
make: *** [Makefile:43: test-php] Error 1
```
```


### Log file

_No response_

### Browser log

_No response_

### Additional info

Console error log

```
...

Test Suites: 60 passed, 60 total
Tests:       356 passed, 356 total
Snapshots:   25 passed, 25 total
Time:        63.094 s
Ran all test suites.
phpunit -c phpunit.xml
Could not read "phpunit.xml".
make: *** [Makefile:43: test-php] Error 1
```

**Observations and debugging**

- Using the 2 year old `phpunit.unit.xml` fails with errors
- Running `composer run test` seems to complete successfully

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/twofactor_totp/pull/1149 as a reference. The makefile is mostly obsolete. We can recommend npm i, composer i and npm run build (or dev)
