### ISSUE TITLE
Cannot move ownership of appointments

### ISSUE THREAD

**Issue by yamlfd** [nextcloud/calendar#548]
1. Create user foo@bar.com
2. Add some contacts
3. Create user foo to get rid of "@bar.com" in username

Or do it like this with user_external module:
```
'user_backends' => array(
    0 => array(
      'class' => 'OC_User_IMAP',
      'arguments' => array(
        0 => '{mail.example.com:993/imap/ssl/readonly}', 'example.com'
      ),
    ),
  ),
```
4. Run "sudo -u www-data php occ files:transfer-ownership foo@bar.com foo" to move the data
5. Appointments are lost and cannot transfered.

### Expected behaviour
Data must not get lost.

### Actual behaviour
Data loss

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 12.0

**Calendar version:** 1.5.3

**Updated from an older Nextcloud or fresh install:** No

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/5158
