### ISSUE TITLE
[Feature request] Grouping of calendars

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/calendar#549]
I am discussing a project with a large size customer (>1400 staff) at several locations and he is very much keen of **grouping calendars** for each location. A member of location a should only see calendars assigned to location - and - group a and not the calendars of location b or c.

regards, hitam4450

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/259

**Comment by georgehrke** [comment]
> A member of location a should only see calendars assigned to location - and - group a and not the calendars of location b or c.

So just create 3 calendars. a, b and c and share it with write access with everyone who is supposed to access it.

There is absolutely no reason that 1400 employees would share their personal calendar with all 1399 other employees.
