### ISSUE TITLE
Allow guests for created Appointment Talk rooms

### ISSUE THREAD

**Issue by drfinkus** [nextcloud/calendar#5496]
### Is your feature request related to a problem? Please describe.

The new "Create a Talk room" feature does not allow guests by default, and there is no setting for the Appointment to enable guests.

For us, 99% of the appointments booked are with guests. This means that we need to manually go and enable guests for every appointment. In practice, many of our users either don't know how to do that or they forget to do it, which creates a lot of friction. 

In many cases the guests simply miss their appointment; they are greeted with a login page, they don't understand what's going on, and they just go away. 

### Describe the solution you'd like

I would like to have an "Allow guests" checkbox in the Appointment settings page, right below the "Create a Talk room" checkbox.

If "Allow guests" is checked, the new Talk room should allow guests.

### Describe alternatives you've considered

One can manually go and set the new Talk room to allow guests, but, as mentioned, in practice many times we forget to do it, and it creates a lot of friction.

**Comment by miaulalala** [comment]
Makes sense. @ChristophWurst what do you think?

**Comment by ChristophWurst** [comment]
That's a bug. Appointment rooms were supposed to be public.
