### ISSUE TITLE
Allow encryption of calendar/parts of calendar via gpg/keybase or other

### ISSUE THREAD

**Issue by mannp** [nextcloud/calendar#550]
As the encryption module doesn't really add value according to most threads that I have read, perhaps allow users to encrypt all or part of a calendar details so confidential data is secured in case the nextcloud server is compromised.

The QNotes app does similar by allowing the importing of a keybase or gpg key and a button press allows encryption/decryption of that data.

Thanks for your consideration.

**Comment by MariusBluem** [comment]
Again: this is backend! And there is an issue where we discuss this :)

**Comment by georgehrke** [comment]
@MariusBluem I think @mannp is referring to a client side encryption in the calendar app. But no other CalDAV client will be able to read this, so it's 👎 for me.

**Comment by mannp** [comment]
@georgehrke I am and they can read it, they just pass the encrypted text through as a text string.
