### ISSUE TITLE
Widget calendar : régression d'affichage des évènements à venir dans le tableau de bord

### ISSUE THREAD

**Issue by littlewolf59** [nextcloud/calendar#5504]
### Steps to reproduce

1. ordre des évènements sans classement chronologique
2. affichage d'évènement devant être à demain, alors qu'ils se déroulent 2 jours plus tard
3. affichage de calendriers qui parait aléatoire

### Expected behavior

affichage erroné

### Actual behaviour

affichage correct

### Calendar app version

4.5.1

### Browser

firefox/brave

### Client operating system

w11

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

27.1.1

### Updated from an older installed version or fresh install

None

### List of activated apps

```Text
sans intérêt
```

### Nextcloud configuration

```Text
sans intérêt
```

**Comment by miaulalala** [comment]
Hi, can you please edit your ticket to be in English?

**Comment by littlewolf59** [comment]
Fixé par la version 4.5.2 de calendar
