### ISSUE TITLE
Drag and drop of an event of a series

### ISSUE THREAD

**Issue by florianrusch** [nextcloud/calendar#551]
Regarding the [comment](https://github.com/nextcloud/calendar/issues/7#issuecomment-307943785) of @dominic-p, it would be great if a new, standalone event will be created if you change the time of a single event of the series by drag and drop. 

For example, I have at the moment the problem, that I have my work time as a series. At the end of each day, I edit the work time for today, to log how long I've worked.
But when I use the drag and drop function of the NC Calendar UI, every event of the series gets the time of the dragged event.

### Steps to reproduce
Drag an event of a series and take a look at all other events in the series. (Past and future events)

### Expected behavior
Just the time of the dragged event should be edited.

### Actual behavior
All events of the series getting the time of the dragged event.

### Client configuration
**Browser:** Google Chrome
**Operating system:** Windows, Linux, OSx
**CalDAV-clients:** Calender App, Business Calendar

**Comment by georgehrke** [comment]
Let's handle this in #7

**Comment by florianrusch** [comment]
Okay, I've thought it would be nice to seperate it from the in #7 discussed dialog. In my opinion this a two different things.
