### ISSUE TITLE
Group-Sharing Fails If Group Name Contains a Slash

### ISSUE THREAD

**Issue by mwaeckerlin** [nextcloud/calendar#552]
Current Nextcloud 12, currently released calendar app (as of today):

Sharing calendars does not work for groups containing a slash.

Reproduce:
 - New instance of NC12 with calendar app
 - admin creates a new user in three groups:
    - testgroup
    - test-group
    - test/group
 - admin add himself to the three groups
 - admin ceates three calendars:
    - cal1 shared with testgroup
    - cal2 shared with test-group
    - cal3 shared with test/group
 - admin logs out, log in with new user
 - user sees cal1 and cal2 but not cal3

**Comment by georgehrke** [comment]
This is a server issue, let me look for the ticket.

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/4885

will be fixed with 12.0.1 :)

**Comment by mwaeckerlin** [comment]
@georgehrke, what means server issue? Are you sure?

Sharing files works on NC12, also the group folders app works. Only calendar does not, so I suppose it's app related.

**Comment by georgehrke** [comment]
@mwaeckerlin The calendar app is only a CalDAV-client running in your browser.
The actual CalDAV (and CardDAV) servers are part of the `dav` app which belongs to the server.
