### ISSUE TITLE
Some Samsung calendar entries are not synced from Nextcloud to Thunderbird

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#5521]
### Steps to reproduce

1. Create a calendar entry with the default calendar app from Samsung on my smartphone
2. Entry is synced correctly to Nextcloud (c.nc.com v27.1.2)
3. Thunderbird (115.3.1) doesn't sync the entry

### Expected behavior

Thunderbird can sync the calendar from entry from Nextcloud

### Actual behaviour

Calendar entry doesn't show up in Thunderbird, I triggered the sync multiple times manually. Unfortunately I don't see any related error message in the Thunderbird log.

If I modify the calendar entry in the Nextcloud web interface, Thunderbird syncs it fine. I tried to find out what's the difference but couldn't spot anything obvious. Maybe some of the experts see something.

When I download the whole calendar from Nextcloud after the entry was created from my Samsung smartphone the entry looks like this:

````
BEGIN:VEVENT
DTSTAMP:20231009T204446Z
UID:585be715-ca69-4b92-bfdc-40bc45367cc2
SUMMARY:Mila
DTSTART;TZID=Europe/Berlin:20231010T124500
DTEND;TZID=Europe/Berlin:20231010T131500
BEGIN:VALARM
TRIGGER:-PT10M
ACTION:DISPLAY
DESCRIPTION:Mila
END:VALARM
END:VEVENT
````

Thunderbird is not able to sync it. Than I edit it with Nextcloud, I change the Reminder from 10M to 11M, the new entry looks like this:

````
BEGIN:VEVENT
DTSTAMP:20231010T093033Z
UID:585be715-ca69-4b92-bfdc-40bc45367cc2
SUMMARY:Mila
DTSTART;TZID=Europe/Berlin:20231010T124500
DTEND;TZID=Europe/Berlin:20231010T131500
SEQUENCE:0
LAST-MODIFIED:20231010T093033Z
BEGIN:VALARM
TRIGGER:-PT11M
ACTION:DISPLAY
DESCRIPTION:Mila
END:VALARM
END:VEVENT
````

Now Thunderbird syncs it quite fine.

I was hoping to see any difference in the format (e.g. time) which causes the error. But both entries look alsmost identically to me (beside the edit information).

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
> I was hoping to see any difference in the format (e.g. time) which causes the error. But both entries look alsmost identically to me (beside the edit information).

`SEQUENCE:0` seems to be the important difference

**Comment by ChristophWurst** [comment]
Yet I can not reproduce. The event 

```
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTAMP:20231009T204446Z
UID:585be715-ca69-4b92-bfdc-40bc45367cc4
SUMMARY:Mila
DTSTART;TZID=Europe/Berlin:20231010T124500
DTEND;TZID=Europe/Berlin:20231010T131500
BEGIN:VALARM
TRIGGER:-PT10M
ACTION:DISPLAY
DESCRIPTION:Mila
END:VALARM
END:VEVENT
END:VCALENDAR
```

sent to Nextcloud either either with the Calendar app import or a manual curl PUT is synced down to Thunderbird without issues.

**Comment by schiessle** [comment]
I digged a bit deeper into it as well and it might be a Thunderbird bug which sometimes lose track about already synced entries if offline support is enabled: https://bugzilla.mozilla.org/show_bug.cgi?id=1713625

Probably not much we can do here. My initial hope was that there are some issues in the format and we can solve it by normalizing stuff which come in. But this is obviously not the case here.
