### ISSUE TITLE
Appointment expansion does not take into account recurrence exceptions

### ISSUE THREAD

**Issue by bed7** [nextcloud/calendar#5537]
### Steps to reproduce

1. Create periodic events.
2. Create appointments in these slots.
3. Change the time or duration of a recurring event over a week
4. Preview appointments

### Expected behavior

Appointment slots become available when a weekly event is modified (time or duration)

### Actual behaviour

Free slots are not updated when a weekly event is modified for a shorter duration or moved.
You must delete the event and create a new one to obtain the expected result.
Looks like the weekly repeat of the event was still there in the calendar.

### Calendar app version

4.5.2

### CalDAV-clients used

Thunderbird Lightning / IOs calendar

### Client operating system

windows/ios

### Server operating system

Arch Linux

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

27.1.2

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
To make sure I understand the issue:

Create a config
Config creates slots
Slots are booked
The booked event is modified manually
-> The free slots on the booking page should take into account having more time to fit in slots but don't

Is that correct?

**Comment by bed7** [comment]
yes but I'm talking about a weekly event present in the calendar.
And I add that an event over the day or over several days does not block the slots

**Comment by miaulalala** [comment]
So it's a recurring event and you modify one in the series?

**Comment by bed7** [comment]
that's it

**Comment by miaulalala** [comment]
Related PR: https://github.com/nextcloud/server/pull/40541

**Comment by miaulalala** [comment]
From what I can tell, this is an issue with the `expand` function here:

https://github.com/nextcloud/3rdparty/blob/7c4db392c7f7bfb94f6735db9fa541ce05e84939/sabre/vobject/lib/Component/VCalendar.php#L284

Even though the master event should not be returned for this day, the \Sabre\VObject\Recur\EventIterator::getEventObject function returns a clone of the master event instead of the recurrence exception, so, returning the same date and time as the master event, not the recurrence exception.

**Comment by miaulalala** [comment]
Ok, apparently it is expected that when the recurrence is expanded with parameters startDate and endDate and the parameters don't fit within that parameter, it returns the master instance https://github.com/sabre-io/vobject/issues/421

**Comment by miaulalala** [comment]
So, I tested this with a DAILY recurrence rule where I modified the second event of the recurrence. I could not reproduce the issue.

Can you please share the VEVENT that you created, with the recurrence @bed7 ? You can export your event in the three- dot menu. Please use the first event in the series to do so.

Thanks!

**Comment by miaulalala** [comment]
Recurrence:

![image](https://github.com/user-attachments/assets/f3fadead-470e-425e-a578-6e14d630692f)


Slots for the 26th:

![image](https://github.com/user-attachments/assets/475bb30c-bbdf-4b4b-aa46-a543a6d4d624)


Slots for the 27th:

![image](https://github.com/user-attachments/assets/3ed3c4c2-eb8b-446e-ba17-2202e9b9f945)

**Comment by miaulalala** [comment]
Can't reproduce
