### ISSUE TITLE
ability to schedule an event on every 3rd wednesday of the month (or similar patterns)

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/calendar#5541]
### Is your feature request related to a problem? Please describe.

I have an appointment every 3rd wednesday of the month, due the different lengths of a month i cannot express this properly in terms of "repeat every x weeks on x day"

### Describe the solution you'd like

I would like to be able to schedule an appointment for every 3rd wednesday of a month or every 4th friday of a month

### Describe alternatives you've considered

checking every month and making sure it is on the correct day, or looking into if there is mathematically way to set a repeat pattern in terms of "repeat every x weeks on x day" perhaps with multiple repeating appointments

**Comment by drpetersen** [comment]
Doesn't this already work out of the box? For me, it does:

![Screenshot_20231214_163220](https://github.com/nextcloud/calendar/assets/9879249/320a34b4-6e85-43c9-849d-3b752c76d97e)

**Comment by keunes** [comment]
It does yes. I'm wondering if this has been added recently - couldn't find it before so I gave a thumbs-up but I've used the feature last week.

**Comment by miaulalala** [comment]
Can do this as well.

**Comment by Fuseteam** [comment]
hi thanks, i overlooked that. i didn't think to try with "month"
