### ISSUE TITLE
This recurrence rule does not generate any valid instances

### ISSUE THREAD

**Issue by strk** [nextcloud/calendar#5543]
### Steps to reproduce

1. Create an event from google android occurring every 2 years
2. Synchronize the calendar to nextcloud, using DAVx5
3. Get an error upon syncronizing

### Expected behavior

The calendar event is synchronized

### Actual behaviour

```
HTTP RESPONSE
Response{protocol=http/1.1, code=500, message=Internal Server Error, url=https://oc.kbt.io/remote.php/dav/calendars/sandro/personal/5ab658d7-892d-49e1-af24-693103ef1c0f.ics}
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\VObject\Recur\NoInstancesException</s:exception>
  <s:message>This recurrence rule does not generate any valid instances</s:message>
</d:error>
```

### Calendar app version

 4.5.2

### CalDAV-clients used

DAVx5

### Server operating system

debian

### Web server

None

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.2

### Nextcloud version

27.1.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
I don't think it's relevant
```

**Comment by strk** [comment]
The ics:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:DAVx5/4.3.6.1-ose ical4j/3.2.12 (com.google.android.calendar)
BEGIN:VEVENT
DTSTAMP:20231020T091737Z
UID:5ab658d7-892d-49e1-af24-693103ef1c0f
SEQUENCE:4
SUMMARY:some event
DESCRIPTION:Annuale
DTSTART;TZID=Europe/Rome:20230201T090000
DTEND;TZID=Europe/Rome:20230201T100000
RRULE:FREQ=YEARLY;WKST=SU;UNTIL=20250131T225959Z
EXDATE;TZID=Europe/Rome:20230201T090000
EXDATE;TZID=Europe/Rome:20240201T090000
CLASS:PUBLIC
BEGIN:VALARM
TRIGGER:PT0S
ACTION:DISPLAY
DESCRIPTION:some event
END:VALARM
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Rome
LAST-MODIFIED:20230104T023643Z
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR

```

**Comment by miaulalala** [comment]
Looks like the error happens here:

https://github.com/nextcloud/3rdparty/blob/3ffd8c6d5152645e770bdbe6a5422f5d919aea64/sabre/vobject/lib/Recur/EventIterator.php#L192

The issue is - your recurrence specifies a date of 2023-02-01 and a recurrence set of every two years, but excludes the 2023-02-01 and the 2024-02-01and ends on 2025-01-31. So the Sabre logic is correct, there is no valid recurrence. You can test if setting your end date for the recurrence to 2025-02-02 will solve this. I can't really determine why Google would handle this as a valid recurrence.

**Comment by strk** [comment]
I've now got rid of that ics file but I think the way I produced was first make a valid one and then removing more and more events until no event was left...
In any case the server internal error (500) was over-scary, as I wasn't sure if other .ics files were being synchronized or not
