### ISSUE TITLE
Adding attendees to a foreign calendar does not create an own calendar entry

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/calendar#5545]
### Steps to reproduce

1. Create or use an Event in a foreign Calendar, where you have rights to create
2. Add a user from your instance as attendee (Who also does not own the calendar)
3. The Event won't appear in Attendees calendar (not your own and not in others)

### Expected behavior

1. Create or use an Event in a foreign Calendar, where you have rights to create
2. Add a user from your instance as attendee
3. click save (so far so good)
4. Event should appear in each attendees calendar (without relaoding the page)

### Actual behaviour

* We have a Calendar which is owned by a dummy user called "Central". The Purpose of this Calendar, is to announce general events, which are either open to join, or not jet assigned. 
* The following bug does not appear, if the person who invites, own the calendar
* We want to be able that any person with the rights may assign attendees. Which works fine, if you own the calendar
* If you don't own the calendar, the event does not appear after save (and not after reload #5441)

### Calendar app version

4.5.2

### Browser

Firefox 118

### Client operating system

Windows 10

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

27.1.1

### Updated from an older installed version or fresh install

None

**Comment by tcitworld** [comment]
I'd say related to https://github.com/nextcloud/server/issues/26668 (invitations are not sent for shared calendars)
