### ISSUE TITLE
Holidays In Calendar, #962 Proposal Not Workable

### ISSUE THREAD

**Issue by drankinatty** [nextcloud/calendar#5551]
### Is your feature request related to a problem? Please describe.

In the Nextcloud calendar, holidays are not shown. This is a significant limitation and is very frustrating.

The issue was addressed 4-years ago in [Easily add holidays #962 (closed)](https://github.com/nextcloud/calendar/issues/962), and several proposal were made to have users configure *webcal* holidays, and an additional "app" was created [Holiday Calendars (untested app)](https://apps.nextcloud.com/apps/holiday_calendars) None of the the proposals provide a supported way to get holidays in the calendar, and the untested app hasn't been updated for Nextcloud Version 27.

The holidays need to be part of the Nextcloud calendar itself, not some 3rd party retrieval or app. Making a fundamental part of the calendar reliant on something external to Nextcloud is unworkable.

Why? For example the "app" is an *Untested* app:

![nc-calendar-holidays-untested-app](https://github.com/nextcloud/calendar/assets/9997638/9d70b70d-4f6a-49bb-acef-b4470553f6d3)

and results in any problems not being supported by Nextcloud.

Further, the *Calendar Holidays* app isn't even available for Nextcloud Version 27.  It has not been updated in over six-months and the last release download is available for is Nextcloud Version 26, e.g.

![nc-calendar-holidays-v3](https://github.com/nextcloud/calendar/assets/9997638/f9693af9-a214-4eb9-beb6-530cfb926801)

Fundamental features in Nextcloud apps need to be part of Nextcloud itself.

### Describe the solution you'd like

I would like to see Nextcloud provide calendar holidays. It can't take that much to create a table holding the holidays by country code and just have that provide holidays for the calendar. (the indication there is a holiday on a date should also be part of the day-header, next to the numeric date rather than taking up space for a normal calendar event)

### Describe alternatives you've considered

I've reviewed [Easily add holidays #962 (closed)](https://github.com/nextcloud/calendar/issues/962) options and looked at [Holiday Calendars (untested app)](https://apps.nextcloud.com/apps/holiday_calendars), but really do not want "Untested" (unsupported) apps that are not even updated for my current version of Nextcloud as part of my Nextcloud server install. The current alternatives are simply not workable. 

### Additional context

That's pretty much it. The Nextcloud calendar just need holidays that are provided as part of the app that don't rely on some 3rd party to maintain (or not).

Keep up the great work! (and if you want to show the calendar event details on mouseover instead of having to click an event -- that would be welcomed too)

**Comment by tcitworld** [comment]
> The holidays need to be part of the Nextcloud calendar itself, not some 3rd party retrieval or app. Making a fundamental part of the calendar reliant on something external to Nextcloud is unworkable.

The Nextcloud Calendar app 4.4+ has a build-in holiday calendar, so I didn't bother updating the Holiday Calendars app anymore, (even though the feature set is a little different).
https://docs.nextcloud.com/server/latest/user_manual/en/groupware/calendar.html#subscribe-to-a-holiday-calendar

Ref. https://framagit.org/framasoft/nextcloud/holiday_calendars/-/issues/7
