### ISSUE TITLE
Web UI dashboard "upcoming events" widget only shows personal calendar

### ISSUE THREAD

**Issue by snagglewest** [nextcloud/calendar#5563]
### Steps to reproduce

update from 27.0.1 to 27.1.2
Calendar widget is empty

### Expected behavior

Web UI dashboard "upcoming events" widget should show upcoming events

### Actual behaviour

Calendar widget is empty except for personal calendar.  Any linked calendars or newly created calendar events are not shown

### Calendar app version

4.5.2

### Browser

Chrome, Edge & Firefox

### Client operating system

Windows 10 & 11, Ubuntu 22.04, mint 21.2

### Server operating system

Ubuntu 22.04

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

27.1.3

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.2
  - cfg_share_links: 4.2.0
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - dashboard: 7.7.0
  - dav: 1.27.0
  - external: 5.2.1
  - externalportal: 1.2.0
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - passwords: 2023.10.30
  - previewgenerator: 5.3.0
  - provisioning_api: 1.17.0
  - ransomware_protection: 1.14.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.2
  - richdocumentscode: 23.5.503
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.10.3
  - support: 1.10.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.14.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - activity: 2.19.0 (installed 2.15.0)
  - circles: 27.0.1 (installed 22.0.0)
  - contactsinteraction: 1.8.0 (installed 1.2.0)
  - encryption: 2.15.0
  - federation: 1.17.0 (installed 1.11.0)
  - photos: 2.3.0 (installed 1.6.0)
  - privacy: 1.11.0 (installed 1.6.0)
  - recommendations: 1.6.0 (installed 1.1.0)
  - spreed: 17.1.2 (installed 17.1.2)
  - survey_client: 1.15.0 (installed 1.10.0)
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.***REMOVED SENSITIVE VALUE***",
        ],
        "0": "apache_disable_rewrite_ip=0",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "remember_login_cookie_lifetime": 31536000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "auto_logout": false,
        "default_language": "en",
        "force_language": "en",
        "default_locale": "en_US",
        "force_locale": "en_US",
        "default_phone_region": "US",
        "auth.bruteforce.protection.enabled": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logfilemode": 416,
        "loglevel": 1,
        "log_rotate_size": 104857600,
        "logtimezone": "America\/New_York",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "enable_previews": true,
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "maintenance": false,
        "theme": "",
        "allow_local_remote_servers": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "files_texteditor",
            "extract",
            "richdocumentscode",
            "ransomware_protection",
            "documentserver_community",
            "files_downloadactivity"
        ],
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "jpeg_quality": "60"
    }
}
```

### Additional info

The title says it all.  It's been reported and marked as fixed but it still persists.

https://github.com/nextcloud/calendar/issues/5477
https://help.nextcloud.com/t/web-ui-dashboard-upcoming-events-widget-only-shows-personal-calendar/173084

**Comment by miaulalala** [comment]
@st3iny

**Comment by reiner1959-coder** [comment]
I faced that after version 4.4.5 for me there is also an issue not showing birthday calendar on dashboard.

**Comment by snagglewest** [comment]
With the exception of the users personal calendar, no calendar events show in the web UI dashboard widget.  That includes user created calendars, the birthday calendar and external calendar subscriptions.
My users used the feature every single day so it's a big deal for us.  It just baffles me that this hasn't gained any traction.

**Comment by sihui62** [comment]
No traction at all:

https://github.com/nextcloud/calendar/issues/5495
https://help.nextcloud.com/t/dashboard-upcoming-events-show-x-years-ago/170313

**Comment by SKB-CGN** [comment]
Same here.
Before it was showing all calender events.
Now it's only showing my trash-calendar.

Can it be configured some how?

**Comment by snagglewest** [comment]
Not a real fix but you can get the widget working again by reverting to V4.4.5.  These directions (Ubuntu 20.04/Apache2) work but you'll probably won't survive a NC upgrade.  At least my users are happy again until a real fix comes along.
====================
1. Disable the calendar app in admin settings

2. move to app directory
cd /var/www/html/nextcloud/apps

3. rename calendar directory to old or delete it completely
# sudo mv calendar calendar-old

4. download version 4.4.5 of calendar
# sudo wget -q https://github.com/nextcloud-releases/calendar/releases/download/v4.4.5/calendar-v4.4.5.tar.gz

5. Extract new version of calendar
# sudo tar xvf calendar-v4.4.5.tar.gz

6. change directory owner & group to www-data www-data (or whatever owner:group you use)
# sudo chown -R www-data:www-data calendar

7. re-enable the calendar app in admin settings

====================

**Comment by ralfbgithub** [comment]
@snagglewes Thank you !!! 
https://github.com/nextcloud/calendar/issues/5477 is now fixed for me

**Comment by snagglewest** [comment]
Still not fixed after upgrading to NC 27.1.5 & calendar 4.6.0

On  the bright side the downgrade to calendar 4.4.5 kludge still works.

Just keep in mind that upgrading NC automatically upgrades calendar to 4.6.0 and the problem is back.  If you're following the above downgrade instructions delete the old calendar folder rather than renaming it and keeping it.  NC will complain about the old folder if it's still in the app directory when you upgrade NC.

**Comment by drunktankpink** [comment]
Thanks, @snagglewest this also worked for me. 

However, I am now unable to see events from subscribed calendars, even though the calendar shows in the left-hand panel. I am not sure if this is the same for anyone else?

**Comment by scharmach** [comment]
The widget is also not showing tasks anymore if you've set your calendar to show tasks within it.

Noticed this with 4.6.4 (released today), reverting to version 4.4.5 fixed this as well.

I'm really surprised about the state that the widget is in right now.

**Comment by BaerHub** [comment]
For those, who are running Nextcloud as **LXC Container** or with **nginx**:

1. Disable the calendar app in admin settings

2. move to app directory
`cd /usr/share/webapps/nextcloud/apps-appstore`

3. rename calendar directory to old or delete it completely
`mv calendar calendar-old`

4. download version 4.4.5 of calendar
`wget -q https://github.com/nextcloud-releases/calendar/releases/download/v4.4.5/calendar-v4.4.5.tar.gz
`
5. Extract new version of calendar
`tar xvf calendar-v4.4.5.tar.gz`

6. (**optional**) change directory owner & group to www-data www-data (or whatever owner:group you use)
`chown -R www-data:www-data calendar`

7. re-enable the calendar app in admin settings

**Comment by DeBaschdi** [comment]
still not fixed in NC 29.0.0

**Comment by BaerHub** [comment]
can confirm, still NOT FIXED

**Comment by kesselb** [comment]
Thanks for your bug report :+1: 

I've worked on two patches, which are also scheduled for the upcoming releases of Nextcloud 28 (2024-05-23) and Nextcloud 29 (2024-05-23), to address some issues regarding the upcoming events widget.

1) Bring back events from subscribed calendars: https://github.com/nextcloud/server/pull/44752

2) Fix an issue with reoccurrence:  https://github.com/nextcloud/server/pull/45222

I've added a link to the second issue to close this bug report when the patch is merged. 

I hope, but cannot say for sure, if those patches already enough. 
Please log a fresh issue if your issue is still there with Nextcloud 28.0.6 or Nextcloud 29.0.0.1.

It's often helpful to let us know if the problem exists with your personal calendar, a shared calendar (by you or to you), or a calendar subscription. Moreover, exporting an ICS file is often helpful.

Thank you and stay tuned!

**Comment by ralfbgithub** [comment]
Thank you, Daniel.

I'll keep my fingers crossed ;-)

**Comment by kesselb** [comment]
@scharmach I'm afraid the missing tasks are not fixed by https://github.com/nextcloud/server/pull/44752 and https://github.com/nextcloud/server/pull/45222. I logged a new issue: https://github.com/nextcloud/server/issues/45333.

**Comment by kesselb** [comment]
> Please log a fresh issue if your issue is still there with Nextcloud 28.0.6 or Nextcloud 29.0.1.

I missed the merge window for 28.0.6 and 29.0.1. 
They are scheduled now for 28.0.7 and 29.0.2.

**Comment by ralfbgithub** [comment]
Calendar widget is working again with 28.0.7 for me
Thx :-)

**Comment by BaerHub** [comment]
same here, its finally working! Thanks guys!

**Comment by DeBaschdi** [comment]
Working in 29.0.3, thx
