### ISSUE TITLE
Search and Agenda View

### ISSUE THREAD

**Issue by eltrentin** [nextcloud/calendar#557]
Would be interesting to have two new features as in Google Calendar:
1. Search --> inside "title" and "description" of an event that show the result in Agenda View Mode
2. AgendaView --> have a list of event grouped by day as in Google Calendar having a new botton near month, day, week. ![screenhunter_665 aug 08 17 59](https://user-images.githubusercontent.com/10931327/29081646-68aa4958-7c63-11e7-950b-f9b3fc3cc278.jpg)

Thanks a lot
AF

**Comment by georgehrke** [comment]
@eltrentin Please search for existing issues before creating duplicates.

And as a little note for the future: Please create one issue per bug / feature request

**Comment by georgehrke** [comment]
#8 

#402
