### ISSUE TITLE
Is-it possible to have a iCalendar link to share my calendar ?

### ISSUE THREAD

**Issue by BjH14** [nextcloud/calendar#558]
Hello
I would like to share a calendar made in nextcloud (framagenda), using an iCal link.
It would permit me to show my nextcloud calendar in other applications, such as a Google Agenda (Google Agenda is used by a team I'm a part of, and we all share our agendas).
I didn't find this possibility, could someone help me ?
If it's not already possible, maybe an idea for the future of this project ?
Thanks

**Comment by georgehrke** [comment]
We introduced public sharing with Nextcloud 11

Please make sure you are running at least Nc11

**Comment by BjH14** [comment]
Thank you for your answer.
I have checked, the system I use (framagenda) is running on 11, so I think the problem comes from me !
But I only found how to share an agenda by a link and then I can have an iFrame, or a link to a page.
Is there a way to obtain an iCalendar link ? Could you help me to find it ?
Thanks

**Comment by georgehrke** [comment]
In the public sharing link, there are two buttons in the upper right corner.
Subscribe and download.

Right click the subscribe button and copy the link. There you got your iCalendar link :)

**Comment by BjH14** [comment]
Thank you for your answer.
I have checked, the system I use (framagenda) is running on 11, so I think the problem comes from me !
But I only found how to share an agenda by a link and then I can have an iFrame, or a link to a page.
Is there a way to obtain an iCalendar link ? Could you help me to find it ?
Thanks

**Comment by georgehrke** [comment]
@tcitworld Which calendar version is framagenda running? :)

**Comment by BjH14** [comment]
It works !
Thank you very much !

**Comment by tcitworld** [comment]
Latest version 1.5.3, but with the public calendar page fix. NC at 11.0.3, will update to 12 next week.
