### ISSUE TITLE
Publish from Thunderbird to a nextcloud calendar

### ISSUE THREAD

**Issue by BjH14** [nextcloud/calendar#559]
Hello
I've seen on thunderbird that it is possible to publish an agenda to a WebDAV server.
https://support.mozilla.org/en-US/kb/exporting-and-sharing-a-calendar

But I don't know which adress to write (the WebDAV URL).

I created an agenda in Nextcloud (framagenda), then I shared it, I used the shared adress to put in Thunderbird, but it doesn't work.

I precise that I need to use Thunderbird in that way (publish from it, not sync from Nextcloud) because the agenda I need to publish on Nextcloud comes from another service of agenda (supporting only CalDAV). Then I can't share this other agenda with my nextcloud agenda simply by using the "iCalendar" way.

Do you know if what I need is possible ?
Thanks

**Comment by georgehrke** [comment]
> I created an agenda in Nextcloud (framagenda), then I shared it, I used the shared adress to put in Thunderbird, but it doesn't work.

When you want to add your Nextcloud calendars to thunderbird, you have to setup each calendar on it's own.

Next to each calendar are three dots. Click on the dots and select the »Link«
This link you can use for syncing with thunderbird

**Comment by tcitworld** [comment]
>  I've seen on thunderbird that it is possible to publish an agenda to a WebDAV server.

As far as I can understand, this is for exporting the calendar as a iCalendar file, on a WebDAV server *as a file*.

Nextcloud can't publish subscriptions from external sources. However, I'm getting confused why you need to publish a calendar if you already have the external source. If you just want it to run inside Nextcloud, just add it as a subscription.

**Comment by tcitworld** [comment]
>> I've seen on thunderbird that it is possible to publish an agenda to a WebDAV server.

> As far as I can understand, this is for exporting the calendar as a iCalendar file, on a WebDAV server as a file.

It's probably possible to use the WebDAV URL from Framagenda to give it a try : https://framagenda.org/remote.php/webdav/

**Comment by BjH14** [comment]
Thank you for your very fast help ! (and sorry for my bad english)
The problem I have is that I need to use (for my job) an agenda system in which the agendas can't be shared by iCalendar, but only using WebDAV.
It's not a problem with Thunderbird/Ligntning, but actually I need to put my job agenda directly in Nextcloud.
You mean that there is a way to "subscribe" to my job agenda in my Nextcloud agenda, using WebDAV ?
I'm not sure to understand. So, if I understand well, do you know where I can do so in Nextcloud (framagenda) ?

**Comment by tcitworld** [comment]
>  You mean that there is a way to "subscribe" to my job agenda in my Nextcloud agenda, using WebDAV ?

Yup, just paste your link here on the sidebar :

![selection_094](https://user-images.githubusercontent.com/2197836/29116477-32c05736-7cfb-11e7-9803-19f5e428effd.png)

If you need a login and password to connect, the link should be like `http(s)://user:password@restofthelink`
Reminder : this is only a subscription, not a calendar so it **will not be synced** with other clients.

**Comment by BjH14** [comment]
Thank you for your help.
Unfortunately, here it doesn't work. I think I have not found what to write precisely after the "@".
I think it's possible the server of my job has a special configuration.
I will continue to search, thank you, you have given me the right way !

**Comment by tcitworld** [comment]
If (and only if) you need authentication for `https://mydomain.tld/mypath/mycalendar`, you would have to write `https://myuser:mypassword@mydomain.tld/mypath/mycalendar`.
If the server has [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) badly or not configured, it may forbid you to do it. Anyway, you may find more informations in the browser logs, since everything happens inside your browser.

**Comment by georgehrke** [comment]
I think @BjH14's question was answered. Closing.
If not, please speak up
