### ISSUE TITLE
"Could not book the appointment. Please try again later or contact the organizer."

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5597]
### Steps to reproduce

1. Create a public appointment config
2. Have someone book a meeting with you

### Expected behavior

They can book

### Actual behaviour

They get an error

### Calendar app version

4.5

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
Asked for debug logs to be enabled. I think it's \OCA\Calendar\Service\Appointments\BookingService::getAvailableSlots that's not working properly. We pass two timestamps; when extrapolating for the day, it's the timestamp for the whole day, but when booking it's the start and end date of the slot. The calculations could be off my a few seconds and the slot wouldn't fit.

**Comment by miaulalala** [comment]
We're missing the log lines from the conflict checker which means the slots are already empty. adding more logging just to be sure.

**Comment by bentuna** [comment]
After further testing with Nextcloud 28.0.2 and Calendar 4.6.5, we can say that:
- the error occurs with every duration above 60 minutes
- in every case where duration > increment
- in every second slot from the available slot list, when duration is double of increment.

**Comment by ChristophWurst** [comment]
@bentuna please file a new ticket so this isn't lost.
