### ISSUE TITLE
New shared calendars appear in wrong sidebar section

### ISSUE THREAD

**Issue by tcrass** [nextcloud/calendar#560]
Hi there,

we suspect something has changed in the behaviour of the calender app somewhere in the course of upgrading from NextCloud 11 to 12. 

We started off with a number of users (let's call them A, B, C...), all belonging to a group called "shared".
Every user had shared his/her calender to the "shared" group, an while every user's personal calendar appeared on top of the calendar app sidebar (right unter "+ New Calendar"), the other users' shared calendars were displayed further down under "+ New Subscription".

### Steps to reproduce
1. User A creates a new calendar "NewCalA" and shares it with group "shared".
2. User B opens the calendar app.

### Expected behaviour
User B should find the NewCalA calendar in the "New Subscription" section, where all other calenders previously subscribed to are shown.

### Actual behaviour
User B finds NewCalA in the upper section labelled "New Calendar".

### General server configuration

**Operating system:** Linux <servername> 3.16.0-4-686-pae #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) i686

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 5.5.57

**PHP version:** 5.6.30-0+deb8u1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - ereg
 - libxml
 - openssl
 - pcre
 - zlib
 - bcmath
 - bz2
 - calendar
 - ctype
 - dba
 - dom
 - hash
 - fileinfo
 - filter
 - ftp
 - gettext
 - SPL
 - iconv
 - mbstring
 - session
 - posix
 - Reflection
 - standard
 - shmop
 - SimpleXML
 - soap
 - sockets
 - Phar
 - exif
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xml
 - xmlreader
 - xmlwriter
 - zip
 - apache2handler
 - PDO
 - curl
 - gd
 - imap
 - json
 - ldap
 - mcrypt
 - mysql
 - mysqli
 - pdo_mysql
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - readline
 - sqlite3
 - mhash
 - Zend OPcache
 - xdebug
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.1 - 12.0.1.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 12.0.0, which was upgraded from 11.something

**Where did you install Nextcloud from:**  Official download site

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - bruteforcesettings
 - encryption
 - files_external
 - gallery
 - notes
 - tasks
 - user_external
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocg431v0rz52",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "<servername>/cloud",
    "dbtype": "mysql",
    "version": "12.0.1.5",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_from_address": "cloud",
    "mail_smtpmode": "php",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "loglevel": 2,
    "theme": "",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36

**Operating system:** Debian Stretch

**Comment by georgehrke** [comment]
Did you change the calendar to be writable for the others?

Writable calendars appear in the shared section

Please excuse my brevity and typos.

**Comment by georgehrke** [comment]
Closing because my questions where never answered ...
