### ISSUE TITLE
Translation not working : Year View (month still in english)

### ISSUE THREAD

**Issue by JPG-JPG-JPG** [nextcloud/calendar#5611]
### Steps to reproduce

1.just select Year view
(locale = french)

### Expected behavior

month should be translated (in french) in Year view

### Actual behaviour

Month are still in english instead of french (my case)

### Calendar app version

4.6.0

### Browser

firefox / chrome Latest

### Client operating system

W11

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

27.1.3

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by miaulalala** [comment]
Can confirm, the month names are still in english. Feature was introduced in https://github.com/nextcloud/calendar/pull/5248

**Comment by tcitworld** [comment]
Duplicate of #5461

**Comment by JPG-JPG-JPG** [comment]
it seems to work now. Thanks !
