### ISSUE TITLE
Language independent time format and first day of week

### ISSUE THREAD

**Issue by asfethan** [nextcloud/calendar#562]
### Steps to reproduce
1. use nextcloud in EN (US) language
2. first day of week is sunday
3. time format is 12h
4. this behaviour isn't changeable

### Expected behaviour
User will be able to choose time format and other related things independently of language setting.
Many of europeans are using english as their primary language (eg.: primary for work, business, etc..) but also the 24h time format which is typical for western europe. Also week is starting with Monday there.
Please don't force users to use UI language they don't want or to work in locale which isn't appropriate for their location or custom. 

### Actual behaviour
User isn't able to change date/time format related stuff in calendar app. 

### Server configuration

**Operating system**:  Debian GNU/Linux

**Web server:** Apache 2.4.x

**Database:** MySQL 5.6

**PHP version:** 7.x

**Server version:** 12.0.2

**Calendar version:** 1.5.3

**Updated from an older installed version or fresh install:** updated

**Signing status (ownCloud/Nextcloud 9.0 and above):** Nextcloud 12

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/1781
