### ISSUE TITLE
System calendars (Same as Group folder with Calendar)

### ISSUE THREAD

**Issue by Zulgrib** [nextcloud/calendar#564]
Greetings, it would be useful to have "System calendars" that are managed by administrators and pushed to specific groups with appropriate permissions. (Either write or read/write depending on groups the user is in and configuration)

Similar feature already exist for folders thanks to [Group folders](https://apps.nextcloud.com/apps/groupfolders)

It would be normal continuity to be able to apply this to calendars.

**Comment by tcitworld** [comment]
You could use the [default groups](https://apps.nextcloud.com/apps/defaultgroup) app and share with the group your calendar.

**Comment by georgehrke** [comment]
As @tcitworld said, this is already available with group sharing.
