### ISSUE TITLE
Add  ICS calendar not work

### ISSUE THREAD

**Issue by EVOTk** [nextcloud/calendar#5641]
### Steps to reproduce

1.    Open the calendar app
2.    Click on "+ New calendar" -> "New subscription from link (read-only)"
3.    Enter a valid URL to an ICS calendar file ( **example** webcal://espace-corchade-metz.net/wordpress/?post_type=tribe_events&ical=1&eventDisplay=list from https://espace-corchade-metz.net/wordpress/evenements/  ) .

### Expected behavior

Events added to my calendar

### Actual behaviour

The calendar is added but there are no events

### Calendar app version

4.6.1

### Browser

Firefox 120

### Client operating system

Windows 10

### Server operating system

Linux

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

28.0.0

### Updated from an older installed version or fresh install

None

### Additional info

The same webcal link displays events correctly in the calendar
![image](https://github.com/nextcloud/calendar/assets/45015615/44b17706-1103-4fd0-b18f-d2332fec014e)

I don't know when it stopped working, but before I had no problems. Maybe since I switched to Nextcloud 28.

Thx for help

**Comment by tcitworld** [comment]
Please add `nextcloud.log` details when you add the calendar. Increase the log verbosity if needed.

**Comment by EVOTk** [comment]
Hello
[nextcloud.txt](https://github.com/nextcloud/calendar/files/13751112/nextcloud.txt)

Thank you for your reply. Can you tell me if adding this calendar to Nextcloud works for you?

**Comment by hhigel-bdf** [comment]
Have same problem at least since upgrade to [Nextcloud Hub 7](https://nextcloud.com/) (28.0.0). Calendar App version 4.6.1.
Similar issue: https://github.com/nextcloud/server/issues/42257

**Comment by smolinde** [comment]
Similar issue here!

**Comment by Mat-DB** [comment]
Here as well a similar issue!

**Comment by dennysubke** [comment]
The same for me. Will there be a fix for 28.0.2?

**Comment by miaulalala** [comment]
Duplicate https://github.com/nextcloud/server/issues/42143

**Comment by murdikog** [comment]
Still not working in 28.0.3 .

**Comment by murdikog** [comment]
Still not working in 28.0.4.................

**Comment by smolinde** [comment]
Hi everyone, I have most recent Nextcloud 28.0.4 installed on Ubuntu 23.10 Server (x64) on a Raspberry Pi 5. Everything works since 28.0.3 and I think you should try reinstall the Calendar app. If this doesn't help, go to your CLI, run ```sudo mysql``` and delete relevant database entries in all calendar tables (but don't delete the tables themselves!) and also make sure that the settings/configuration tables (e.g. oc_appconfig) don't have any rows containing Calendar app rows. This should definitely help. Worked for me at least.

**Comment by murdikog** [comment]
Thanks for your help, I'll try that ☺️

**Comment by BaerHub** [comment]
> Hi everyone, I have most recent Nextcloud 28.0.4 installed on Ubuntu 23.10 Server (x64) on a Raspberry Pi 5. Everything works since 28.0.3 and I think you should try reinstall the Calendar app. If this doesn't help, go to your CLI, run `sudo mysql` and delete relevant database entries in all calendar tables (but don't delete the tables themselves!) and also make sure that the settings/configuration tables (e.g. oc_appconfig) don't have any rows containing Calendar app rows. This should definitely help. Worked for me at least.

i tried that, removed calendar app, removed all table entries in calendar tables, still same issue

**Comment by murdikog** [comment]
Thanks for the tip! 😌
