### ISSUE TITLE
Some events are missing, when switching the week

### ISSUE THREAD

**Issue by slideup-benni** [nextcloud/calendar#566]
### Steps to reproduce
1. Create multiple calendars (i'm unsing 16 + 3 external ics)
2. Create or import events (maybe recurring)
3. press ">" (next week) until it reloads all calendars.
4. not all events loaded (after that you can go back)

### Expected behaviour
All events should be visible
![test1](https://user-images.githubusercontent.com/12446028/29457285-d2ed4014-8419-11e7-8d02-280a71563e6f.PNG)

![test4](https://user-images.githubusercontent.com/12446028/29457908-d09a0d26-841c-11e7-85ab-a693efbae701.png)

### Actual behaviour
some events are missing (maybe only imported? recurring?)
![test5](https://user-images.githubusercontent.com/12446028/29457831-76de74ca-841c-11e7-87e7-9b9ab73ee28b.PNG)

The response of the ajax-requests after reloading contains only:
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"/>
```

![test3](https://user-images.githubusercontent.com/12446028/29457901-ca951f2e-841c-11e7-94d3-ccbed2171568.png)

### Server configuration
**Operating system:** Linux 4.4.35-1-pve #1 SMP Fri Dec 9 11:09:55 CET 2016 x86_64

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 10.0.32

**PHP version:** 5.6.30-0+deb8u1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - ereg
 - libxml
 - openssl
 - pcre
 - zlib
 - bcmath
 - bz2
 - calendar
 - ctype
 - dba
 - dom
 - hash
 - fileinfo
 - filter
 - ftp
 - gettext
 - SPL
 - iconv
 - mbstring
 - session
 - posix
 - Reflection
 - standard
 - shmop
 - SimpleXML
 - soap
 - sockets
 - Phar
 - exif
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xml
 - xmlreader
 - xmlwriter
 - zip
 - apache2handler
 - PDO
 - apcu
 - curl
 - gd
 - intl
 - json
 - mcrypt
 - mysql
 - mysqli
 - pdo_mysql
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - readline
 - sqlite3
 - mhash
 - apc
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**  download

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

 (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.2.1
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_antivirus: 1.0.0.0
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_snapshots: 0.1.1
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 11.0.5
 - nextant: 1.0.8
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - updatenotification: 1.2.0
 - user_external: 0.4
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - apporder
 - encryption
 - files_external
 - ocr
 - ownnote
 - richdocuments
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "updatechecker": false,
    "instanceid": "oc8pv17vcmkk",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.63",
        "zzzz"
    ],
    "datadirectory": "\/mnt\/ocdata",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_from_address": "noreply",
    "mail_domain": "zzzz.de",
    "theme": "",
    "loglevel": 0,
    "maintenance": false,
    "overwrite.cli.url": "https:\/\/zzz.zzzz.de",
    "overwritewebroot": "\/",
    "forcessl": true,
    "updater.release.channel": "stable",
    "trusted_proxies": [
        "10.3.1.8"
    ],
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED_FOR"
    ]
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Operating system:** Windows 8

No Errors in Javascript-Console

I'm using a nginx-reverse proxy

**Comment by georgehrke** [comment]
Is there anything relevant in your nginx or nextcloud log? 

I'm pretty sure this is related to your  nginx reverse proxy.

**Comment by georgehrke** [comment]
Actually, if the server is sending not complete responses, this is a bug in the CalDAV server.

Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.

Please double check that this is no bug in your nginx reverse proxy (which i think is most likely), then report this issue in the Nextcloud server repo:
https://github.com/nextcloud/server/issues
