### ISSUE TITLE
Cannot see subscribed calendar anymore

### ISSUE THREAD

**Issue by andreasjacobsen93** [nextcloud/calendar#567]
Today my subscribed calendar stopped showing, and the following error was present in the web console.
```
GET https://***/index.php/apps/calendar/v1/proxy?url=https%3A%2F%2Fdk.***.net%2Fweb%2F***%2Fdb1%2Fpublic%2Fri6906gg70X1x6Q8Q3Qy1Y69Z05425X65YZ60Z956Y555Q2ZY4n0gQ5203.ics 422 (Unprocessable Entity)
  | (anonymous) | @ | vendor.js:6458
-- | -- | -- | --
  | y | @ | vendor.js:6292
  | u | @ | vendor.js:6179
  | l | @ | vendor.js:9350
  | (anonymous) | @ | vendor.js:9391
  | $digest | @ | vendor.js:9941
  | $apply | @ | vendor.js:10085
  | (anonymous) | @ | vendor.js:13021
  | dispatch | @ | core.js:3
  | r.handle | @ | core.js:3
```
and clicking the link shows an error: "CSRF check failed"
I'm using NC 12.0.2 on Ubuntu

**Comment by georgehrke** [comment]
> and clicking the link shows an error: "CSRF check failed"

That's the expected behavior.

>  422 (Unprocessable Entity)

Please enable the debug mode and try again. The re should be some logs.

**Comment by georgehrke** [comment]
And please check the network console of your browser. There should be a more verbose error message in there too

**Comment by andreasjacobsen93** [comment]
It was solved by removing the calendar and adding it again from the source.

**Comment by georgehrke** [comment]
Hm :/ 
ok
