### ISSUE TITLE
Unexpected behavior dashboard "Upcoming events" widget

### ISSUE THREAD

**Issue by jpmv27** [nextcloud/calendar#5695]
### Steps to reproduce

1. Have Calendar with upcoming events
2. Have Dashboard with Upcoming events widget
3. Open Dashboard

### Expected behavior

Upcoming events are listed in the widget

### Actual behaviour

Upcoming events not listed or incompletely listed.

Two different users. Two different behaviors.

User 1: Event ten days from today, multiple intermediate events between now and then.
Only the event ten days away is being displayed.

User 2: Multiple events three, four, and 10+ days away. No events are displayed.

### Calendar app version

4.6.3

### CalDAV-clients used

DAVx5

### Browser

Firefox 121.0.1

### Client operating system

Windows 10

### Server operating system

CentOS

### Web server

Apache

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.2

### Nextcloud version

27.1.5

### Updated from an older installed version or fresh install

Updated from an older version

### Log file

```Text
No errors in logs
```

### Additional info

Logs and additional info can be provided upon request, if required

**Comment by jpmv27** [comment]
Updated Calendar app to 4.6.4. No change in behavior.
Did observe some errors in logs during update.
Screen shot attached.
![image](https://github.com/nextcloud/calendar/assets/1688977/8f3c2c83-108d-4903-86c6-0e7199bec13c)

**Comment by sgofferj** [comment]
Same issue.

NC 27.1.6 in Docker 24.0.7 on Ubuntu 22.04
PHP 8.2.15, Zend 4.2.15, Zend OPcache 8.2.15
Nginx 1.25.3
mariadb  Ver 15.1 Distrib 10.5.23-MariaDB
Calendar app 4.6.4
Browsers: Chrome & Firefox latest on Ubuntu 22.04 and Windows 10

**Comment by jpmv27** [comment]
Not sure whether related or not: one of the users experiencing this issue have a calendar that is "disabled" in the sidebar (open circle instead of filled circle) and they are reporting that events from this "disabled" calendar are showing up in the dashboard.

Still seeing original issue of missing events.

Current versions:
NC 27.1.6
Calendar 4.6.5

**Comment by jpmv27** [comment]
Another observation.
We are in Easter timezone, DST is in effect.
Today is Wednesday, it is currently 20:30.
There is an upcoming appointment at 10:00 on Friday.
The dashboard is showing that appointment as happening "tomorrow".

**Comment by sgofferj** [comment]
Problem persists in NC 28.0.2, Calendar 4.6.6

**Comment by McLibboc** [comment]
Same here. This makes the widget completely useless.

**Comment by mclang** [comment]
Noticed similar problem.

Except for me _Upcoming Events_ -widget does show local Nextcloud calendar events but not external Google ones as it did before updating to Nextcloud v27.
Furthermore, an event in local calendar that is scheduled on Thursday is displayed as _tomorrow_ although today is Tuesday.

**Comment by gurbina93** [comment]
Nothing shown on my widget except personal calendar. Everything else is excluded.

**Comment by DriedPlumber** [comment]
As others, I have to confirm that google imported calendars are not showing in Nextcloud Hub 7 (28.0.4)
Even when I manually change from imported calendar reminder time in NC, card "Upcoming events" is empty.

**Comment by kesselb** [comment]
Thanks for your bug report :+1: 

I've worked on two patches, which are also scheduled for the upcoming releases of Nextcloud 28 (2024-05-23) and Nextcloud 29 (2024-05-23), to address some issues regarding the upcoming events widget.

1) Bring back events from subscribed calendars: https://github.com/nextcloud/server/pull/44752

2) Fix an issue with reoccurrence:  https://github.com/nextcloud/server/pull/45222

I've added a link to the second issue to close this bug report when the patch is merged. 

I hope, but cannot say for sure, if those patches already enough. 
Please log a fresh issue if your issue is still there with Nextcloud 28.0.6 or Nextcloud 29.0.0.1.

It's often helpful to let us know if the problem exists with your personal calendar, a shared calendar (by you or to you), or a calendar subscription. Moreover, exporting an ICS file is often helpful.

Thank you and stay tuned!

**Comment by jpmv27** [comment]
Thanks!
Unfortunately I'm stuck on NC 27 while waiting for some other apps to be supported on 28+.
Hopefully others who have encountered this can test sooner.

**Comment by kesselb** [comment]
> Please log a fresh issue if your issue is still there with Nextcloud 28.0.6 or Nextcloud 29.0.0.1.

I missed the merge window for 28.0.6 and 29.0.1. 
They are scheduled now for 28.0.7 and 29.0.2.

**Comment by jpmv27** [comment]
Can confirm it is fixed in NextCloud 27.1.11
