### ISSUE TITLE
a more inclusive illustration for wedding event

### ISSUE THREAD

**Issue by benoit-dd** [nextcloud/calendar#5696]
### Is your feature request related to a problem? Please describe.

the current image for wedding depicts a straight couple. 

https://github.com/nextcloud/calendar/blob/main/img/illustrations/wedding.svg

### Describe the solution you'd like

I'd like to have a more gender neutral pic that could be also relevant for gay or lesbian weddings : 
 - a couple of rings could do the job (sorry, can't make a picture myself : example: https://commons.wikimedia.org/wiki/File:Rings.png)

**Comment by tcitworld** [comment]
I think all the illustrations are expected to be removed in an event details redesign, right @st3iny

**Comment by st3iny** [comment]
Yes, the illustrations will go soon. I'm currently working on removing them as part of the event editor redesign.

Ref https://github.com/nextcloud/calendar/issues/3543
Ref https://github.com/nextcloud/calendar/pull/5675
