### ISSUE TITLE
Find next free slot(s) for all participants of a meeting automatically

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5697]
## Is your feature request related to a problem? Please describe.

As the organizer of an event I can use the free/busy view to see if the selected attendees are free on a day. If the selected slot doesn't work, I need to change the time window myself. This can be cumbersome.

## Describe the solution you'd like

Calculate the next slot(s) that work for all selected attendees and let me move the event there with one single click.

## Implementation

1. Get the meeting duration from the current end time - start time.
2. Determine a date (days) range of current start until current start + 5 days.
3. Make a free busy request for each day until 3 slots are found where all attendees are free.
4. If there is at least one slow, show its start and end time as clickable suggestion
5. Apply the start/end time to the event on click

## Additional context

Conflicts with the changes of https://github.com/nextcloud/calendar/issues/39 so it's best tackled after.

Idea brought up by @ShGKme.

**Comment by jancborchardt** [comment]
Sounds like a great idea as discussed, and could improve the free/busy view outside of what we can edit within Fullcalendar. :) Just a few suggestions on the bottom, and if you click them the calendar display automatically switches.

**Comment by ChristophWurst** [comment]
In addition to the suggestions inside the modal @nimishavijay had the idea to already show the info in the editing sidebar. Something like detecting if all selected attendees are free at the currently selected time. If not, suggest x alternatives where they are.

**Comment by ChristophWurst** [comment]
@nimishavijay where should we put the suggestions? at the bottom under date and time?

https://github.com/nextcloud/calendar/issues/39#issuecomment-1941811737

**Comment by nimishavijay** [comment]
> at the bottom under date and time?

What do you think about placing it above the date and time? This makes sure that the date and time is like a final summary of what is selected.

![image](https://github.com/nextcloud/calendar/assets/52440189/221f731d-3302-47ab-8d8c-7708d1ff4dea)

- [ ] when you select a time from the NcSelect, the selected time in the fullcalendar component should also change
- [ ] The format of the date/time shown in the NcSelect and the bottom summary date tome should be the same

Not completely convinced about showing the suggested times in the sidebar, that would be a nice-to-have follow up anyway.

**Comment by ChristophWurst** [comment]
Docs at https://github.com/nextcloud/documentation/pull/11689

**Comment by alexanderdd** [comment]
@ChristophWurst probably the "to review" label can be removed?
