### ISSUE TITLE
Missing 'Nextcloud' logo when accessing shared calendar

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/calendar#571]
Steps to reproduce:

1. From the left sidebar of of the Calendar app, share the calendar publicly:
![contacts-share-publicly](https://user-images.githubusercontent.com/31063993/29574387-b04a9d68-8761-11e7-8f86-b972c51390e2.png)
2. Open the link, the header bar looks similar to this:
![contacts-share-publicly-missing-logo](https://user-images.githubusercontent.com/31063993/29574496-0846a8d6-8762-11e7-8818-cb131466049e.png)

Expected result:
- A Nextcloud logo on the top left

Actual result:
- Misplaced text instead of a logo

**Comment by georgehrke** [comment]
Must be related to some changes in Nc 13 alpha
