### ISSUE TITLE
checkbox and text has not the same line height 

### ISSUE THREAD

**Issue by bergart** [nextcloud/calendar#572]
### Steps to reproduce
1. add a new event in your calendar app and hit the more button to add an attendee 
2. click on the attendee and look at the upcoming line with the checkbox

### Expected behaviour
same line height

### Actual behaviour
not the same line height (see image)

**Nextcloud version:** 12 and above

![selection_008](https://user-images.githubusercontent.com/22152652/29618753-6dcca090-8819-11e7-8335-8249b144a300.png)

### Server configuration
**Operating system**:  Linux 4.10.0-32-generic #36~16.04.1-Ubuntu x86_64

**Web server:** nginx/1.10.3 (Ubuntu)

**Database:** MariaDB v.10.0.31

**PHP version:** 7.0.22

**Server version:** 13

**Calendar version:** 1.5.3

**Updated from an older installed version or fresh install:** fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):**

**List of activated apps:**

```
Enabled:
  - calendar: 1.5.3
  - comments: 1.3.0
  - dav: 1.4.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - lookup_server_connector: 1.1.0
  - oauth2: 1.1.0
  - provisioning_api: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 2.1.2
  - systemtags: 1.3.0
  - theming: 1.4.0
  - twofactor_backupcodes: 1.2.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - testing
  - user_ldap
```

**Nextcloud configuration:**

```
Enabled:
  - calendar: 1.5.3
  - comments: 1.3.0
  - dav: 1.4.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - lookup_server_connector: 1.1.0
  - oauth2: 1.1.0
  - provisioning_api: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 2.1.2
  - systemtags: 1.3.0
  - theming: 1.4.0
  - twofactor_backupcodes: 1.2.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - testing
  - user_ldap
root@apfelbaum:/var/www/nextcloud# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "ocbkwifn1tsq",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.1.1.161"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/10.1.1.161",
        "dbtype": "mysql",
        "version": "13.0.0.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "debug": true
    }
}
```

**Are you using external storage, if yes which one:** -

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 55.0.2 (64-bit), Chromium  v.60.0.3112.78 

**Operating system:** Linux 4.10.0-32-generic @ 16.04.1-Ubuntu x86_64

**CalDAV-clients:**

#### Web server error log
```
It's a styling issue, so no server log is needed.
```

#### Log file (data/nextcloud.log)
```
It's a styling issue, so no server log is needed.
```

#### Browser log
```
It's a styling issue, so no server log is needed.
```

**Comment by georgehrke** [comment]
Please use the full issue template.
We definitely need information about the used browser / os etc here

**Comment by bergart** [comment]
[PR #580](https://github.com/nextcloud/calendar/pull/580)

**Comment by georgehrke** [comment]
The pull-request was already merged in September :)
