### ISSUE TITLE
Dashboard not showing today's remaining upcoming events

### ISSUE THREAD

**Issue by bcutter** [nextcloud/calendar#5720]
### Steps to reproduce

1. Check with "/apps/dashboard"
2. Have a look at the calendar dashboard element

### Expected behavior

Remaining events of today are shown

### Actual behaviour

![grafik](https://github.com/nextcloud/calendar/assets/13799156/616456f7-8474-4bdf-a192-3b852eff21e6)

Of course there are several remaining events for the rest of today.

### Calendar app version

4.6.4

### Browser

Firefox 122

### Client operating system

Windows 11

### Server operating system

Raspberry Pi OS

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

27.1.5.1

### Updated from an older installed version or fresh install

Updated from an older version

### Web server error log

```Text
Nothing related
```

### Log file

```Text
Nothing related
```

### Browser log

```Text
Nothing related
```

### Additional info

Accidentally discovered this, did not use the dashboard in the last time. But checked other open issues related to the Dashboard, could not find something closely similar.

**Comment by DEADC1DE** [comment]
Same here.
[Nextcloud Hub 7] (28.0.2 RC4)
Nextcloud AIO on Ubuntu 22.04.3 LTS
Calender App 4.6.4

**Comment by bcutter** [comment]
Randomly checking my own issues today I discovered this has been solved meanwhile.

NC 28.0.8.1 with calendar app version 4.7.12.

Must have been fixed somewhere in the last months, silently. @joshtrichards please advise if closing this issue is fine (confirmation it is fixed by other users needed?).

**Comment by joshtrichards** [comment]
Yes, I believe this case was covered in by @kesselb's recent efforts in https://github.com/nextcloud/calendar/issues/5628#issuecomment-2099276533
