### ISSUE TITLE
Pressing 'Enter' inside the 'Email' field of an attendee should not create / update the meeting

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/calendar#574]
Steps to reproduce:

1. Create a new meeting by pressing somewhere on our calendar item view
2. Enter a title for your meeting, e.g. __Test__
3. Go to the "Attendees" tab and enter something in the "Email address of attendee" field, e.g. __test@test.com__
4. Press Enter

Expected result:

- New attendee should be added

Actual result:

- Meeting is created without adding the attendee

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/502
