### ISSUE TITLE
Meeting updates not sent to attendees

### ISSUE THREAD

**Issue by MrPinrel** [nextcloud/calendar#5744]
### Steps to reproduce

1. Create a meeting and invite 2 attendees. Meeting invite emails are sent.
2. Open the meeting using thunderbird, the nextcloud calendar web page, or an iOS device using the native calendar app. Update the meeting description or location. No meeting update emails are sent. 
3. Open the meeting using thunderbird, the nextcloud calendar web page, or an iOS device using the native calendar app. Add an additional attendee. No meeting update emails are sent. 
4. If the date/time of the meeting changes, updates are sent.

### Expected behavior

I would expect all attendees to get a meeting update when meeting details such as name of the meeting, location, or description are changed. The behavior for #2 and #3 above should be the same as for #4.

### Actual behaviour

No meeting update invites are sent unless the date/time of the meeting changes.

### Calendar app version

5.6.4

### CalDAV-clients used

Thunderbird, iOS Calendar App

### Browser

Chrome

### Server operating system

Synology DSM

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.0

### Nextcloud version

28.0.2

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by ChristophWurst** [comment]
> ### Nextcloud version
> 
> 28.0.2
> ###

https://github.com/nextcloud/server/issues/43115?

**Comment by flortsch** [comment]
https://github.com/nextcloud/server/issues/41084

**Comment by MrPinrel** [comment]
Hi there,

I just installed 28.0.5 and it appears that the issue has been fixed. Thanks!

Marcos
