### ISSUE TITLE
🍱 Interactive widget for calendars

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5746]
## Is your feature request related to a problem? Please describe.

As a Calendar user I want to embed a calendar in a Text document, Collectives page or Talk message.

## Describe the solution you'd like

Offer an interactive widget for calendars. Only people with read access to my calendar should see any contents. For others the widgets has to be empty.

![image](https://github.com/nextcloud/calendar/assets/1374172/d500e885-e58f-4812-b92b-6c3e084259fc)

## Implementation

Shared calendars can be embedded into iframes. Ideally we can leverage this feature.

## Work packages

- [x] Embed shared calendars read-only (accessible to anyone)
- [x] Embed private calendars read-only (but interactive with click handling and navigation)
- [ ]  User docs

## Follow-ups

- Embed private calendars with write support (only for the owner and sharees with write permission)

## Describe alternatives you've considered

N/a

## Additional context

* https://github.com/nextcloud/server/issues/42550
* https://github.com/nextcloud/calendar/issues/5701

**Comment by ChristophWurst** [comment]
@hamza221 could you please check what's left to do? User docs?

**Comment by hamza221** [comment]
and the text styling bug, or should I open a new issue for it?
<img width="932" alt="image" src="https://github.com/nextcloud/calendar/assets/40746210/5ad7926c-c02f-4d4c-ab17-4e443e378dd7">

**Comment by ChristophWurst** [comment]
yes we can tackle that separately :+1:

**Comment by hamza221** [comment]
> yes we can tackle that separately 👍

#5970
