### ISSUE TITLE
Lost *Free for all* feature in free/busy

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5754]
### Steps to reproduce

1. Create an event and invite someone else
2. Look at free/busy

### Expected behavior

See white blocks only when *everyone* is free and gray instead for when individuals are free.

This was added in https://github.com/nextcloud/calendar/pull/2918.

### Actual behaviour

White for individuals are free but when others are blocked

![image](https://github.com/nextcloud/calendar/assets/1374172/981d252f-af07-4d81-b26a-a8324a29e3b7)

### Calendar app version

4.6

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2024-02-22 19-42-24](https://github.com/nextcloud/calendar/assets/1374172/5e78ac07-ec6d-42c8-acb8-a668a84f5acc)

Logged by Firefox when I browse through free-busy. This could be related.

**Comment by st3iny** [comment]
I think you are right Christoph. The syntax I used is wrong it should be:
`for await (const [...] of asyncGenerator) {...}`.

See the example at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGenerator#async_generator_iteration
