### ISSUE TITLE
Calendar picker: Ugly spacing between and around buttons

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#5777]
### Steps to reproduce

1. Have multiple calendars.
2. Open the editor.
3. Look at the calendar picker.

### Expected behavior

It should look nice and buttons should be aligned to the right.

### Actual behaviour

The buttons have a weird margin.

![grafik](https://github.com/nextcloud/calendar/assets/1479486/e5c88c5c-6a10-44ff-9bf8-7aa9a9274e0f)

### Calendar app version

main

### Additional info

This is a regression from #5648. We had to bump the version of nextcloud/vue from 8.3 to 8.6 last minute to fix some build error.

**Comment by st3iny** [comment]
cc @GVodyanov

**Comment by GVodyanov** [comment]
While solving another bug found:
![image](https://github.com/nextcloud/calendar/assets/76647797/9eb2f777-5efc-47d1-8fe1-dfdfa997d529)

**Comment by st3iny** [comment]
Can't be reproduced any longer.
