### ISSUE TITLE
Asia/Yekaterinburg TimeZone

### ISSUE THREAD

**Issue by MrEgenius** [nextcloud/calendar#579]
Hello!

Current timezone file ASIA-YEKATERINBURG.ics is incorrect because YEKT timezone is +0500 GMT and without summer time offset.
Current content of file:
BEGIN:VCALENDAR
PRODID:-//tzurl.org//NONSGML Olson 2012j//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Asia/Yekaterinburg
TZURL:http://tzurl.org/zoneinfo-outlook/Asia/Yekaterinburg
X-LIC-LOCATION:Asia/Yekaterinburg
BEGIN:STANDARD
TZOFFSETFROM:+0600
TZOFFSETTO:+0600
TZNAME:YEKT
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
END:VCALENDAR

Right content is:
BEGIN:VTIMEZONE
TZID:Asia/Yekaterinburg
X-LIC-LOCATION:Asia/Yekaterinburg
BEGIN:STANDARD
TZOFFSETFROM:+0500
TZOFFSETTO:+0500
TZNAME:YEKT
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE

Please, fix Yekateriberg timezone in ASIA-YEKATERINBURG.ics file.

Thank you.

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/82
