### ISSUE TITLE
Duplicating an event with attendees should reset attendence status and RSVP

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5793]
### Steps to reproduce

1. Create an event with two attendees
2. Wait for them to accept
3. Duplicate the event with new dates (because the same type of meeting happens again)

### Expected behavior

Invites are sent out like the firs time.

### Actual behaviour

Attendance status of the previous meeting are copied.

### Calendar app version

4.6

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
I can't edit the dates either at the moment with latest main

**Comment by ChristophWurst** [comment]
@GVodyanov could you look into this after feature freeze?
