### ISSUE TITLE
App should continously save calendars as files that sync to clients as backup (like the files)

### ISSUE THREAD

**Issue by fnadde42** [nextcloud/calendar#583]
Tried to search for this feature but either I'm blind or it doesn't exist. Please enlighten me. It has happened that a server goes down and calendar disappears from all devices connected to it. Would be nice to have a file locally to continue use calendar until server is up again. Same thing goes with Tasks and Contacts but I'll have to create issues on them respectively.

### Expected behaviour
When calendar in app is changed, it should be able to save an `.ics` file on a specified place in *Files*.

### Actual behaviour
User has to regularly manually save to file or create script backing up calendar.

### Server configuration

**Calendar version:** 1.5.3

**Comment by georgehrke** [comment]
> Please enlighten me. It has happened that a server goes down and calendar disappears from all devices connected to it.

What clients do you use? oO
When a client is offline or can't connect to the server it should just display its latest state and sync new changes once its online again or the server is available again.

**Comment by georgehrke** [comment]
Generally I'm not a big fan of this, because writing to a file each time after the calendar changed will massively decrease performance.

**Comment by tcitworld** [comment]
> because writing to a file each time after the calendar changed will massively decrease performance.

Better to use the cron task for this.

**Comment by fnadde42** [comment]
> When a client is offline or can't connect to the server it should just display its latest state and sync new changes once its online again or the server is available again.

Weird. I got a connection issue with DavDroid and then it disconnected and disappeared. Might be a bug or shit behind screen ¯\_(ツ)_/¯. Gonna try it out.

> will massively decrease performance

Big nope! Don't want mandatory features slowing things down. IF this were to be a feature it would surely be an optional one, but as you have stated, this might be not be a problem at all if the client works as you described.

**Comment by georgehrke** [comment]
> Weird. I got a connection issue with DavDroid and then it disconnected and disappeared.

Do you run some reverse proxy in front of Nextcloud? 
Maybe there is a misconfiguration

**Comment by fnadde42** [comment]
> Do you run some reverse proxy in front of Nextcloud?
Maybe there is a misconfiguration

No, but I tired to simulating server disconnect and remembered my problem. Calendar app "[Ethar](https://f-droid.org/packages/ws.xsoh.etar/)" and issue app "[Tasks](https://f-droid.org/packages/org.dmfs.tasks/)" does not allow exporting their content. So even if they are stored locally there is no way to export them. That's why I like the [everything is a file](https://en.wikipedia.org/wiki/Everything_is_a_file) concept so that I can store them offline as easily handled files.

At one point, I _only_ used the online calendar and when my cloud-server went down and I didn't have the time to fix it, I had my cloud files offline on my computer but not my calendar, contacts and tasks. Having the option to store a synced file (with a performance notice) of the calendar or a guide to fix it with a Cronjob would be wonderful.

**Comment by georgehrke** [comment]
This should help you :) 

https://uriesk.wordpress.com/2015/02/13/backup-your-caldav-calendar-with-cadaver/
Just make sure to use the up-to-date CalDAV / CardDAV urls with `/remote.php/dav/`

**Comment by georgehrke** [comment]
I hope you don't mind if I go ahead and close this issue.

The Nextcloud CalDAV server already allows to easily export entire calendars, so if you want to do a backup, just create a little script and set up a cron job. 

If you have further questions how to write that script or want to ask other users if they already have a similar script, just ask at https://help.nextcloud.com/c/apps/calendar

**Comment by fnadde42** [comment]
Thanks for the link. It seems to be the best way to solve this.
