### ISSUE TITLE
No three dot menu in sidebar editor

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#5835]
### Steps to reproduce

1. Open sidebar editor
2. Look for three- dot menu
3. It's not there

### Expected behavior

I have the same three- dot menu as in the simple editor

### Actual behaviour

No three- dot menu

### Calendar app version

4.7.0 - beta.1

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
Fixed in 4.7.0-beta.1

**Comment by miaulalala** [comment]
c.nc:

![image](https://github.com/nextcloud/calendar/assets/7427347/ad6dd4cc-500a-427b-bec2-01e51fea922f)

**Comment by st3iny** [comment]
I can't reproduce this on c.nc.c.

Keep in mind that the menu is not shown for new events as it doesn't have any entries.

**Comment by st3iny** [comment]
Related fix at https://github.com/nextcloud/calendar/pull/5830

**Comment by miaulalala** [comment]
Fixed by https://github.com/nextcloud/calendar/pull/5830
