### ISSUE TITLE
Sync issue on Apple devices

### ISSUE THREAD

**Issue by TheMBeat** [nextcloud/calendar#5838]
### Steps to reproduce

1. Use one Account on two devices (IPhone and IPad)
2. Create an event in device a
3. this event doesn’t show up on device b

### Expected behavior

Events should be Sync.

### Actual behaviour

The event is always missing on one device m.

### Calendar app version

4.6.6 

### CalDAV-clients used

Apple calendar

### Server operating system

Ubuntu in Docker 

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.2

### Nextcloud version

Latest

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by miaulalala** [comment]
Can you check your logs on the nextcloud side to see if anything is showing for the user?

**Comment by democraticArts** [comment]
Hi miaulalala, I found the logs and an information about a calendar update. That was the solution. Thanks!

**Comment by TheMBeat** [comment]
Every is fine since we use accounts for every device.
