### ISSUE TITLE
Misplaced "Event does not exist" in the sidebar

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5839]
### Steps to reproduce

1. Open an invalid event URL

### Expected behavior

Centered empty content view

### Actual behaviour

![image](https://github.com/nextcloud/calendar/assets/1374172/5f4d5f29-6be8-429b-b075-2812936c73fa)

### Calendar app version

4.7

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
This seems similar to https://github.com/nextcloud/mail/issues/9343

**Comment by JuliaKirschenheuter** [comment]
@ChristophWurst I've tried to reproduce it on different screen sizes + different browsers, but it seems good to me ;(

![Screenshot from 2024-04-18 15-44-20](https://github.com/nextcloud/calendar/assets/6078378/583e031d-f72a-4b14-9e7a-895636d62d66)

**Comment by ChristophWurst** [comment]
Simplified editor vs sidebar editor maybe?

**Comment by ChristophWurst** [comment]
Open `/apps/calendar/timeGridWeek/now/edit/sidebar/nope/1713418200`

**Comment by miaulalala** [comment]
Fixed by https://github.com/nextcloud/calendar/pull/5935
