### ISSUE TITLE
Pick a calendar for new event difficult to spot

### ISSUE THREAD

**Issue by kesselb** [nextcloud/calendar#5855]
### Steps to reproduce

1. Have write access to more than one calendar
2. Click + Event
3. Try to pick a different calendar

### Expected behavior

I think it should be a bit easier to spot that you can change the calendar by pressing on it ;)

### Actual behaviour

![Screenshot from 2024-03-18 17-24-49](https://github.com/nextcloud/calendar/assets/3902676/de510ff2-c303-4031-af46-572b84506131)

### Calendar app version

c.nc.com

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
@GretaD ran into this as well.

From the design review call: there should be a caret icon next to the calendar name to indicate that the element is interactive.

@nimishavijay the current design looks very clean but at the cost of usability. I think it is still worth considering changing this back to a standard NcSelect that users know from other places in Nextcloud. We only use this type of select in Calendar.

**Comment by ChristophWurst** [comment]
The expected design is in https://github.com/nextcloud/calendar/issues/3543#issuecomment-942326325. The current design misses the caret icon.

**Comment by jancborchardt** [comment]
> From the design review call: there should be a caret icon next to the calendar name to indicate that the element is interactive.

This is already a good fix. Additionally to this, on hover/focus of the element it could also show the border around the dropdown element. Showing it all the time will make it much busier again though.

**Comment by st3iny** [comment]
Yeah, we discussed this in the latest review and I totally forgot about this one. Adding a caret sounds good.
