### ISSUE TITLE
Align heights and widths for inputs in EditorSidebar

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#5864]
### Is your feature request related to a problem? Please describe.

Some inputs have a height of 36px, some of 44px. 
The flexbox is aligning items without care, giving the select for the day/week/month a large width. 
Additionally the margin between checkboxes is missing for the bottom row. 
The bottom margin is different from the other fields. 

Details tab for reminders:

| Current | Suggested |
|--------|--------|
| ![image](https://github.com/nextcloud/calendar/assets/7427347/55edfe0a-1cc1-401b-b4d5-674558ca9fe3) | ![image](https://github.com/nextcloud/calendar/assets/7427347/e4a71800-23dd-46fa-b9ca-bc21cbc6141e) | 

Resources tab:
| Current | Suggested |
|--------|--------|
| ![image](https://github.com/nextcloud/calendar/assets/7427347/2c6b3793-0534-4944-a5a9-499f7206eabb) | ![image](https://github.com/nextcloud/calendar/assets/7427347/0aa40928-325c-4d5e-8de4-380d696d5b78) |

### Describe the solution you'd like

See screenshots.

**Comment by miaulalala** [comment]
Also, don't know if it's my rheumy old eyes but the border radius on the two different inputs looks different as well. But that might just be me.

**Comment by ChristophWurst** [comment]
I think this is an inconsistency between vanilla HTML `<input>` elements and Nc* components.

The same happens in Mail:

![image](https://github.com/nextcloud/calendar/assets/1374172/25a046f4-16be-4b9c-8c5a-af41ce70421a)

(password is taller than email)
