### ISSUE TITLE
calendar 'persönlich' automatically re-created on every invitation?

### ISSUE THREAD

**Issue by palegrand** [nextcloud/calendar#588]
each user has a calendar named by his first name, shared for the others.
    
Whenever an user creates an appointment and invites a different user (choosing the nc account name) an email is sent out and the entry is created in the target account... basically as desired... BUT:  
The entry does not go into the users calendar (first name),instead  **a new calendar 'persönlich' is created** and the entry goes in there.

we never used any calendar named 'persönlich'. 

## Question
how can I assign/change the calendar an invitation is created in? is 'persönlich' hardwired in some kind?
 
### Steps to reproduce
1. add new appointment for user A and invite user B
2.calendar 'persönlich' gets created for user b and the entry goes in there
3. deleting the calendar 'persönlich' 
4. restart from 1: same behaviour

### Expected behaviour
the entry should be added to the existing main calendar of the user

### Actual behaviour
calendar 'persönlich' gets created each time if it doesn't exist

### Server configuration
Nextcloud 12.02 on Debian Stretch
**Calendar version:** 1.53

**Updated from an older installed version or fresh install:** updated from NC 9/10/11

**Signing status (ownCloud/Nextcloud 9.0 and above):**

**Comment by georgehrke** [comment]
server issue and actually a dup of a different one
looking for server issue ...

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/5040

**Comment by palegrand** [comment]
Thanks - I obviously used the wrong keywords and missed this entry.
