### ISSUE TITLE
Don't push nextcloud version to owncloud users

### ISSUE THREAD

**Issue by RealRancor** [nextcloud/calendar#59]
https://apps.owncloud.com/content/show.php/Calendar?content=168707 was updated with version 1.4.0 which includes the following release note:

> Bugfix: Adjust colors to Nextcloud

Instead of pushing this change to ownCloud users create a new app entry at apps.owncloud.com or revert this change to stay "neutral".

**Comment by georgehrke** [comment]
> Adjust colors to Nextcloud

The color this is referring to is the default color of calendars. I don't think users care if the default color is a light blue or a dark blue

**Comment by georgehrke** [comment]
The default color is only used when a calendar has no color in the db, which is very unlikely to happen. When creating a calendar the default color is red

**Comment by RealRancor** [comment]
Ok, thats ok. However you're still pushing a new version containing only "Nextcloud" to ownCloud users:

https://github.com/nextcloud/calendar/blob/v1.4.0/appinfo/info.xml#L11

Please either update the description or release 1.4.0 as a new app.

**Comment by georgehrke** [comment]
When releasing it as a new app Nextcloud users won't see that there is an update available. And right now I, as an app developer, have to deal with the fact, that both share one App Store.

**Comment by RealRancor** [comment]
Then please update the description to "Calendar GUI for ownCloud / Nextcloud's CalDAV server" to stay neutral.

**Comment by jancborchardt** [comment]
@RealRancor what’s the problem here? @georgehrke, @raghunayyar and @tcitworld as the Calendar app developers can do what they want with the Calendar. If there is a new version which also benefits users of the other server component, why not push it to the appstore?

This desire to control the volunteers instead of seeing it as a true community is exactly what also drove me away from ownCloud, and why Nextcloud was created.

**Comment by RealRancor** [comment]
The problem is that a version of the Calendar App is pushed to ownCloud users with only references to "Nextcloud".

Sure, developers of that app can do what they want. However they should be either neutral in all that NC / oC drama or should push out 1.4 as the NC app and keep 1.3.x as the (currently unmaintained) oC app.

**Comment by tcitworld** [comment]
I intend to maintain the oC app for a while (i.e : take this code and make it stay compatible with ownCloud) , but I will certainly not remove every NC-related changes (for instance https://github.com/owncloud/calendar/commit/e211d0bab31626ac8ece4f49f2565d4d4e8d2c71) that don't break it on oC.

**Comment by RealRancor** [comment]
@tcitworld Thumbs up for that. Unfortunately that wont solve the issue i've described later that the NC version of the app is already pushed to oC users without any notice as 1.4 wasn't released as a new app but as the existing app.

Or is it guaranteed that the 1.4 version is also running for all oC users you're pushing the update out?

**Comment by tcitworld** [comment]
> Or is it guaranteed that the 1.4 version is also running for all oC users you're pushing the update out?

If the update is pushed to the oC store, then it's oC compatible.
