### ISSUE TITLE
Calendar widget shows events in the order of creation _not_ in the order of schedule

### ISSUE THREAD

**Issue by kubuntu-newbie** [nextcloud/calendar#5902]
### Steps to reproduce

Create 6 events that all belong to the same calendar (calendar 1) so they show up on the widget (making widget full)
Create a new event in the _same_ calendar (calendar 1) that is supposed to occur _before_ the first event from the group before

all events could be on the same day or different days

### Expected behavior

all events show up in the order of the time of their occurence / schedule, with the new event showing up before the 5 from original 6

### Actual behaviour

this new event will not show up on the widget at all
note 1: if you now change to what calendar event belongs to (for example to calendar 2) it will show up

note 2: not to make it too complicated, but another test case - first 6 events belong to 2 different calendars and for as long as the _new_ event is also in one of the original 2 calendars it will not show up even though it's the earliest of 7. Changing new event's calendar to a new calendar (calendar 3) will make it show up in the dashboard.

### Calendar app version

4.6.7

### CalDAV-clients used

none, looking at the dashboard of a nextcloud in the browser

### Browser

Firefox 123.0.2

### Client operating system

ubuntu, fedora

### Server operating system

TrueNAS Scale 23.10.2

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.2

### Nextcloud version

28.0.4 (Kubernetes version 1.6.59, Train: charts)

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
calendar
bookmarks
tasks
deck
photos
```

### Nextcloud configuration

```Text
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "overwritehost": "nextcloud.home:9001",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": true,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.home"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.4.1",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "default_phone_region": "US",
        "maintenance_window_start": 9,
        "filelocking.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 30036
        }
    }
}
```

### Additional info

this bug makes it very difficult to track events that were scheduled as recurring events resulting in having a lot of events missing from the dashboard with "tommorow's" events showing up and "today's" events missing

same thing happens in other types of installations, snap, manual etc, so I don't think it's OS dependent

**Comment by kubuntu-newbie** [comment]
this issue doesn't appear in snap installation of Nextcloud Hub 6 (27.1.8) that has calendar app version 4.7.1 installed

**Comment by kesselb** [comment]
Thanks for your bug report :+1: 

I've worked on two patches, which are also scheduled for the upcoming releases of Nextcloud 28 (2024-05-23) and Nextcloud 29 (2024-05-23), to address some issues regarding the upcoming events widget.

1) Bring back events from subscribed calendars: https://github.com/nextcloud/server/pull/44752

2) Fix an issue with reoccurrence:  https://github.com/nextcloud/server/pull/45222

I've added a link to the second issue to close this bug report when the patch is merged.

I could reproduce your problem, and it's also seems fixed by the second patch. 
Please log a fresh issue if your issue is still there with Nextcloud 28.0.6 or Nextcloud 29.0.0.1.

Thank you and stay tuned!

**Comment by kesselb** [comment]
> Please log a fresh issue if your issue is still there with Nextcloud 28.0.6 or Nextcloud 29.0.0.1.

I missed the merge window for 28.0.6 and 29.0.1. 
They are scheduled now for 28.0.7 and 29.0.2.
