### ISSUE TITLE
calendar sync @ iphone not working with special chars in password

### ISSUE THREAD

**Issue by btk999** [nextcloud/calendar#591]
Hi,

not sure if im in the right section here, i just recognized a problem and wanted to let you know :)

The Caldav-Sync does not work on iphone with the provided link (in my case its https://cloud.abc.tld/remote.php/dav/principals/users/me/), if the user **password contains a special char** (in my case it was "ü"). 

So with ü in the pw: error msg on iphone, without (just Test123 for example) it works fine.

im using nextcloud 12.0.2 on nginx with the provided config of the nextcloud manual and mariadb, php7, no 2-factor-auth.

Maybe you can check this and see if you can reconstruct my issue?

Thanks!

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

Thanks! :)
