### ISSUE TITLE
Move from Circles to Teams

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/calendar#5911]
### Is your feature request related to a problem? Please describe.

With https://github.com/nextcloud/server/issues/42433 we rebranded circles as teams which should also be reflected in shared calendars.

### Describe the solution you'd like

Current state:
![1024-982](https://github.com/nextcloud/calendar/assets/1315170/8bb92149-594d-4a36-bbdb-16fbe3fa7e43)

Display of a team (formerly circle) in other apps, i.e. Deck:
![648-1024](https://github.com/nextcloud/calendar/assets/1315170/f86765d3-39eb-4f83-9449-29dabfaa94b0)

So the bare minimum would be:
* replace the circle icon with the teams icon (supporting dark/light theming) https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Agroups%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4024

A more polished option would be to have it aligned with the display in Deck:
* replace the circle icon with the teams icon (supporting dark/light theming) https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Agroups%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4024
* embed it on a circular background to have it have the same size as the other lines' avatars
* add the suffix `(Team)`

### Describe alternatives you've considered

none

### Additional context

As mentioned part of aligning with the https://github.com/nextcloud/server/issues/42433 global feature

**Comment by ChristophWurst** [comment]
For https://github.com/nextcloud/contacts/pull/3818 we did because we didn't want to show "teams" for older releases.

Do we need to cut old version off for Calendar too? It's tricky now that we are in RC

**Comment by AndyScherzinger** [comment]
Well, just replacing the icon should be fine for this very moment. Beware that we already replaced it with the referenced one within the circles frontend itself on at least 28.

**Comment by AndyScherzinger** [comment]
For reference https://github.com/nextcloud/contacts/pull/3665
