### ISSUE TITLE
Handle 507 replies when user has exceeded his quota storage

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#592]
### Steps to reproduce
1. Have an account with quota exceeded
2. Try to create an event

### Expected behaviour
Event should be created

### Actual behaviour
When clicking « save », the event isn't created / showed, nothing happens

### Server configuration

**Server version:** 12.0.2

**Calendar version:** latest

### Details

This happened when we were creating users with a default quota of 5MB on Framagenda but there we having the default files of a standard Nextcloud installation, which are over 6MB.

Reply was 507 with the following content:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\InsufficientStorage</s:exception>
  <s:message/>
</d:error>
```

**Comment by georgehrke** [comment]
Missing error handling here is a bug, yes
but I think an InsufficientStorage exception should never be thrown for CalDAV or CardDAV

**Comment by tcitworld** [comment]
See https://github.com/nextcloud/server/issues/6447

**Comment by tcitworld** [comment]
Doesn't happen anymore on 24.
