### ISSUE TITLE
Odd mismatch between timezone handling (monthly view incorrect, edit pane correct for the very same event)

### ISSUE THREAD

**Issue by user83918491** [nextcloud/calendar#593]
### Steps to reproduce
1. Server timezone: Europe/Berlin
2 . Client/Browser timezone (as recognized by jstz): Europe/Berlin
3. New Subscription of events with timezone Europe/Copenhagen (e.g. https://tekniskmuseum.dk/events/2017-07-12/?ical=1)
4. Change to calendar month which has events of step 3. (e.g. July 2017)
5. Click on one of the events of step 3. such that the right-side detailed edit panel opens (e.g. Parkbanen kører)
6. Note the difference in shown times in the calendar month view and in the right-side panel for the very same event!

### Expected behaviour
Both times, i.e. the one shown on the monthly view and the one in the edit panel, should be equal and correct (e.g. 12:00 in above case).

### Actual behaviour
Edit panel shows correct time (e.g. 12:00 in above case) while monthly view shows wrongly shifted event times (e.g. 14:00 in above case).

### Server configuration

**Operating system**:
Server: Nextcloud on Raspberry Piv3
Client: Chromium browser on Ubuntu working machine

**Server version:** (see your admin page)
12.0.2

**Calendar version:** (see the apps page)
1.5.3.

**Comment by georgehrke** [comment]
> as recognized by jstz

Did you check this in the js console?

**Comment by user83918491** [comment]
>> as recognized by jstz

> Did you check this in the js console?

Checked here https://pellepim.bitbucket.io/jstz/

**Comment by georgehrke** [comment]
Can you please try executing `jstz.determine().name()` in the js console of the calendar app, just to be on the safe side? :)

**Comment by user83918491** [comment]
```
> jstz.determine().name()
< "Europe/Berlin"
```

**Comment by radioagent** [comment]
Hello! See the same behaviour. My time zone is Moscow. In edit mode in nextcloud i specify 14.00, in monthly view i see 12.00. Displacement is 1 hour. 
If i specify 14.00 in Thunderbird, i will see 13.00 in Thunderbird and in Monthly view of nextcloud.

Please, let me know if can give you more info. Will glad to do all that is possible.

Best regards,
Igor

**Comment by georgehrke** [comment]
@user83918491 @radioagent Do you use some privacy protecting Chrome plugins? 

We've seen similar issues in Tor and Firefox if you modify certain rules in `about:config`
see https://github.com/nextcloud/calendar/issues/711

**Comment by radioagent** [comment]
> Do you use some privacy protecting Chrome plugins?
No, i did not used. Currently i do not see this problem. All works correctly. I uses nextcloud 13 , latest version. And latest version of firefox and thunderbird. May be this problem already fixed?

**Comment by georgehrke** [comment]
I can't reproduce this bug with the given webcal link.
I'm very sure that if this wasn't fixed already in an earlier release, https://github.com/nextcloud/calendar/pull/743 finally fixed it.
