### ISSUE TITLE
Get rid of bower

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/calendar#594]
As the landing page of [bower](https://bower.io/) states, they recommend to use Yarn (+webpack) instead of bower. Since we already use gulp here, I propose to use Yarn + Gulp instead of bower.

I adjusted the build environment for the Tasks app already and everything works fine just without bower now. The only problem is, that the currently used datepicker is not available over NPM and also it's github repository cannot be used since it doesn't contain a package.json. The solution to this would be to check in the datepicker into the Calendar repository (or to use a different datepicker 😉).

If you want to, I can send a PR.

**Comment by georgehrke** [comment]
We already talked about this in https://github.com/nextcloud/calendar/issues/540 :)

**Comment by raimund-schluessler** [comment]
So... You want to use NPM5 over Yarn? Most comparisons I had a look on stated that Yarn is still faster than NPM5.

**Comment by tcitworld** [comment]
However, npm is installed along with NodeJS, so I'm to get back with that. I don't bother much for a few milliseconds.
PR welcomed. :)

**Comment by raimund-schluessler** [comment]
I will send a PR to remove bower, but I think switching back to npm should be a separate PR.

**Comment by georgehrke** [comment]
Are the yarn and npm lock file compatible with each other? 

I'd be very happy if we supported both. If yarn is installed on a user's system, use it. 
Otherwise fall back to npm but still be fully functional.

**Comment by tcitworld** [comment]
> Are the yarn and npm lock file compatible with each other?

They are not. Discussion is here: https://github.com/yarnpkg/yarn/issues/3614

**Comment by georgehrke** [comment]
Hmm, in that case I would vote for npm. Yarn is yet another dependency someone has to install when they want to contribute to the calendar app. NPM comes by default with Node.js.

Earlier on we decided for yarn because npm4 was so terribly slow, but nowadays npm5 is \*almost* as fast as yarn.

**Comment by georgehrke** [comment]
Fixed by @tcitworld last week
