### ISSUE TITLE
Displayname is missing on public sharing site

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#596]
works on Nextcloud 11, is broken on Nextcloud 12 and master

It's supposed to show the displayname, but it shows the user id.
Might be a server-side issue. Subject to investigation.

![847b51f4-baf0-473f-9271-57dc0db21b61](https://user-images.githubusercontent.com/1250540/30341784-9b5f049c-97f7-11e7-8889-da2aa19eb66e.jpg)

**Comment by nickvergessen** [comment]
Also most of the time displaying this message might also look a bit stupid.
E.g. I embeded a calendar on our website, and no the calendar is not "shared" with teh visitor, it's embeded on the website, so not displaying this message would be desired...

**Comment by georgehrke** [comment]
> E.g. I embeded a calendar on our website, and no the calendar is not "shared" with teh visitor, it's embeded on the website, so not displaying this message would be desired...

I think in that case we should introduce a new design for embedding. Where we put the month name, view names and today above the grid and make the grid full width.

cc @jancborchardt

**Comment by jancborchardt** [comment]
Yup @georgehrke, good call on special embedding view without sidebar.

Still, this issue is separate and should be fixed. :)
