### ISSUE TITLE
Incorrect year display for January

### ISSUE THREAD

**Issue by GillesF08** [nextcloud/calendar#599]
In month view, the year for January is not correct. When moving back in time it goes March 2017 -> February 2017 -> **January 2016** -> December 2016.
However, when moving to the futur it is correct: December 2017 -> January 2018 -> February 2018.

It seems to affect only the current and past years. Next year and the ones after look correct.

### Steps to reproduce
1. Set month view 
2. Switch to previous month
3. After reaching February 2017, January 2016 will appear

### Expected behaviour
Before February 2017 should be January 2017

**Operating system**: Xubuntu 16.04

**Web server:** Apache2

**Database:** MariadB

**PHP version:** PHP7

**Server version:** 12.0.1

**Calendar version:** 1.5.4

**Comment by georgehrke** [comment]
Github offers a search function, please use it ;)

https://github.com/nextcloud/calendar/issues/434
