### ISSUE TITLE
v1.5.4 - missing file alert after app installation

### ISSUE THREAD

**Issue by j-ed** [nextcloud/calendar#600]
### Expected behavior
All required files should be delivered with a new app release or checksums should only be generated for shipped files.

### Actual behavior
After I've upgrade the calendar app to v1.5.4 a missing file alert was displayed. I checked the directory and indeed a `.gitignore` file doesn't exist in the root directory of the calendar app. I downloaded the file from the repository, stored it in the directory and kicked-off a new file/system consistency check which results in a "**All checks passed**". 
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- calendar
	- FILE_MISSING
		- .gitignore

Raw output
==========
Array
(
    [calendar] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.gitignore] => Array
                        (
                            [expected] => 2ebfa9d965d970eb2f3356f80cbff785c90c9a0d7634b406e49cd4e311826eb4abb482d8be75557cff491837881af2795fc4bd3a8e8d42b24c56d3b53b9b5dee
                            [current] => 
                        )

                )

        )

)
```

### Steps to reproduce
1. update the Calendar app
2. wait until the file/system consistency check has been run.
3. check result

#### Server Configuration
OS: Linux 3.16.46
Web server: Apache2 2.4.26
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.2
Calendar app: 1.5.4

#### Client Configuration
Browser: Mozilla Firefox 55.0.3
Operating system: Windows 7

**Comment by georgehrke** [comment]
But u can still use 1.5.4, right?

**Comment by Schmuuu** [comment]
I just updated as well and don't see this issue. The mentioned file doesn't exist on my server and still I don't have this error message. Could it be a migration issue or something due to installing test versions earlier?

**Comment by georgehrke** [comment]
My changes to the makefile caused this, but if the calendar is just working fine despite that error I see no reason for a 1.5.5.
We will just fix it with 1.6.0

**Comment by tcitworld** [comment]
Same, I didn't get the message, but IIRC the integry checks are done by cron.

**Comment by tcitworld** [comment]
> We will just fix it with 1.6.0

@georgehrke Hmm. Maybe before, since : https://nextcloud.com/blog/help-test-nextcloud-12.0.3/ 🙈

**Comment by j-ed** [comment]
@georgehrke The app works as expected, except that the integrity check line is shown at the top of the Nextcloud window.

**Comment by blizzz** [comment]
> @georgehrke The app works as expected, except that the integrity check line is shown at the top of the Nextcloud window.

Aye, this does not look cool and less technical people may get worried and suspicious. Not a great upgrade experience.

**Comment by Nono-m0le** [comment]
agreed on the statement above

**Comment by banjosi** [comment]
I copied the .gitignore file from the repository into ./calendar as a temporary solution to remove the message from the top of the window (integrity check finishes now with success)

**Comment by orenwf** [comment]
curled the .gitignore file from this repo into the calendar folder, but now getting an invalid hash error on the file instead of the "missing" error

**Comment by Aersaud** [comment]
curled the RAW file as @orenwf did above using curl -LJO . All security checks are now passing.

**Comment by axelrathey** [comment]
Hi, I have the same problem like @orenwf. Copying the .gitignore file from here to the calendar folder will bring an invalid hash instaed of the "missing" error. What do you (@Aersaud) mean with "curl -LJO"? I can only use ftp to upload the file to the server, as it is hosted at a hosting provider.
Thanks Axel

**Comment by axelrathey** [comment]
Ok, now it works for me. I installed curl on my wndows 7 an then I run the following command:

"curl -LJO https://raw.githubusercontent.com/nextcloud/calendar/master/.gitignore" to load the file to my local PC.
"https://raw.githubusercontent.com/nextcloud/calendar/master/.gitignore" ist the RAW url oft the .gitignore file. There are buttons "Raw" "Blame" "History" in github. You need "Raw" to see the url of .gitignore
 Then I uploaded .gitignore via ftp to the hosted webspace in the calendar directory.
After this you have to tell nextcloud to recheck the files.

Axel

**Comment by ds4a** [comment]
@Aersaud many thanks! Your 'curl -LJO' solution also worked for me.

**Comment by avalx** [comment]
@axelrathey, this workaround using curl works for me as well - thanks!

**Comment by georgehrke** [comment]
Calendar 1.5.5 fixes this
