### ISSUE TITLE
Not possible to add appointments via WebUI

### ISSUE THREAD

**Issue by br4yd** [nextcloud/calendar#6017]
### Steps to reproduce

1. Try to add an appointment
2. See error message
3. Check protocols

### Expected behavior

Appointment should be added.

### Actual behaviour

Appointment can't be added via WebUI. It can be added via external clients that sync via CalDAV though. I.e. Thunderbird or DavX5.

### Calendar app version

4.7.4

### CalDAV-clients used

WebApp

### Browser

Brave 1.65.126

### Client operating system

Windows 10

### Server operating system

Debian // Nextcloud-AIO

### Web server

Apache

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.2

### Nextcloud version

29

### Updated from an older installed version or fresh install

Updated from an older version

### Web server error log

```Text
[webdav] Fehler: iCalendar objects must at least have a component of type VTODO
	PUT /remote.php/dav/calendars/<USER REDACTED>/standard/FC8FBB5F-93B9-40EC-A4FB-FCBBBD1DF766.ics
	von <IP REDACTED> von <USER REDACTED> um 21.05.2024, 13:15:19
```

**Comment by cm-schl** [comment]
Can't reproduce this on a fresh install. Does this affect all your calendars?

**Comment by br4yd** [comment]
Hello, thanks for the fast reply. I'll check as soon as I'm home.

**Comment by br4yd** [comment]
Hi, 

it's happening for all existing calendars but not for calendars I'm freshly creating.

**Comment by miaulalala** [comment]
Are calendars that you are trying to add events to calendars created by deck perchance?

**Comment by br4yd** [comment]
> Are calendars that you are trying to add events to calendars created by deck perchance?

No, it's my usual calendar I used the past months to add all my tasks to in Nextcloud and it was originally created in the calendar app.

**Comment by br4yd** [comment]
Interestingly for some reason it works again. The Nextcloud did a restart in the meantime. Maybe this fixed it. I'm not sure, since I don't know the original issue.
