### ISSUE TITLE
Time zone selection not working for new event popup

### ISSUE THREAD

**Issue by SebastianKrupinski** [nextcloud/calendar#6025]
### Steps to reproduce

1. Click on a day in the Calendar to create a new event
2. Try to change the timezone

### Expected behavior

Time zone selection drop down should show.

# note: the time zone selection works when used in the side bar

### Actual behaviour

Nothing happens

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by st3iny** [comment]
Related to https://github.com/nextcloud-libraries/nextcloud-vue/issues/4917

**Comment by SebastianKrupinski** [comment]
> Related to [nextcloud-libraries/nextcloud-vue#4917](https://github.com/nextcloud-libraries/nextcloud-vue/issues/4917)

@st3iny not sure if that is totally related. I tested this with Brave (Chrome Engine) and FireFox. And this was broken on both browsers.

**Comment by st3iny** [comment]
No, it's not fully related but the fix proposed by susnux works here.
