### ISSUE TITLE
Remove occ signing from Make file

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/calendar#604]
The app store already has the ZIP or TAR ball signed, there's no need to also sign using occ. This is just errorprone as the last release has shown 😉 

cc @georgehrke

**Comment by georgehrke** [comment]
> The app store already has the ZIP or TAR ball signed, there's no need to also sign using occ.

Can you elaborate on that? Is that documented anywhere?

**Comment by LukasReschke** [comment]
> Can you elaborate on that? Is that documented anywhere?
<img width="1249" alt="screen shot 2017-09-24 at 19 59 10" src="https://user-images.githubusercontent.com/878997/30785185-d8ceeec2-a162-11e7-830f-6d37e51123f3.png">

**Comment by georgehrke** [comment]
Yes, already doing that. I wasn't aware that this was replacing the traditional occ signing command.
