### ISSUE TITLE
Event entries with UTF-8 BOM elements in Text are not loaded, shown and after export cannot be imported

### ISSUE THREAD

**Issue by fuco809** [nextcloud/calendar#6043]
### Steps to reproduce

1. example file attached - which where exported from a nextcloud calendar
2. import calendar to new calendar fails (1 of 2)
3. calendar not loads. (when selected month is oct 2024)
[test-utf8-bom-event.ics.txt](https://github.com/user-attachments/files/15552064/test-utf8-bom-event.ics.txt)

### Expected behavior

online created events should automatically strip UTF8 BOM Codes oder other unliked char elements

### Actual behaviour

![bomsceeni](https://github.com/nextcloud/calendar/assets/14198012/dcd8a8c3-cb8a-4d8d-8da8-6c6989d51fb4)

elements like "NBSP" or "xEF xBF xBE" are not removed and makes some troubles (not showing events, export/import errors).

### Calendar app version

4.7.4

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

27.1.9

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by tcitworld** [comment]
This could be fixed with a dedicated repair step in the `calendar-js` libary : https://github.com/nextcloud/calendar-js/tree/main/src/parsers/repairsteps/icalendar

**Comment by sanskar-soni-9** [comment]
Hi, I was digging into it and found that its not BOM but Unicode Special Non-characters i.e. U+FFFE & U+FFFF. As if it was BOM then U+FEFF should also break and cause errors but it worked well when I tested it.

Raising PR in calendar-js repo 🙂

[Unicode.org](https://www.unicode.org/faq/private_use.html#sentinel6) | [Wikipedia](https://en.wikipedia.org/wiki/Specials_(Unicode_block))
