### ISSUE TITLE
Calendar shares are working with groups but not with single users

### ISSUE THREAD

**Issue by b-lsa** [nextcloud/calendar#606]
### Steps to reproduce
1. share an existing calendar with a user (with a group the share works correctly!)
2. set the user to 'can edit' 
3. reload the calendar and have a look into the sharing details of the calendar. Now you see the same user twice, but only one entry is marked 'can edit'. (btw: the user can't edit the shared calendar!)

I've found two entries in the 'oc_dav_shares'-table at the database for the 'resourceid'. One is
with the right principaluri-scheme: principals/users/[USERNAME] but a wrong value: access=3 
the other is wrong in principaluri-scheme: principals/users/[DISPLAYNAME] but right value: access=2

The second database-entry is made at the moment you click 'can edit'.

**Comment by tcitworld** [comment]
Please fill the issue template with Nextcloud and calendar app versions.

**Comment by georgehrke** [comment]
This most likely belongs into the server repo, but lets wait for the entire issue template

**Comment by b-lsa** [comment]
The missing issue template, sry:

### General server configuration

**Operating system:** Linux 4.4.87-18.29-default #1 SMP Wed Sep 13 07:07:43 UTC 2017 (3e35b20) x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 10.0.31

**PHP version:** 7.1.9
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - pcre
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - SimpleXML
 - standard
 - xml
 - mysqlnd
 - apache2handler
 - apcu
 - ctype
 - curl
 - dom
 - fileinfo
 - gd
 - gettext
 - iconv
 - imagick
 - json
 - mbstring
 - mysqli
 - openssl
 - PDO
 - pdo_mysql
 - pdo_sqlite
 - posix
 - sqlite3
 - tokenizer
 - xmlreader
 - xmlwriter
 - zip
 - zlib
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install version 12


**Where did you install Nextcloud from:**  opensuse repository


**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** own user management

<details>
        <summary>Signing status</summary>

```
{
    "core": {
        "EXTRA_FILE": {
            "CloudLogin.php": {
                "expected": "",
                "current": "0bffc0e5c1d21809cd5cb93adf53a569a1c1c3e2d9aa8bae987db3af5e31d5c1edbc3b16776cb8408c0d8171e26ed34a1ccc241f12e988668357547b619decd6"
            }
        }
    }
}
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - circles: 0.12.4
 - dav: 1.3.0
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - comments
 - contacts
 - files_accesscontrol
 - files_external
 - firstrunwizard
 - gallery
 - groupfolders
 - ransomware_protection
 - systemtags
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocyu636f736s",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "\/srv\/www\/htdocs\/nextcloud\/data",
    "skeletondirectory": "\/srv\/www\/htdocs\/nextcloud\/themes\/blsa\/core\/skeleton",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "default_language": "de_DE",
    "theme": "blsa",
    "auth.bruteforce.protection.enabled": false,
    "token_auth_enforced": false,
    "maintenance": false,
    "loglevel": 2
}
```
</details>


### Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Operating system:** every opration system

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

no significant informations in log

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

no significant informations in log

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by lapseofreason** [comment]
The bug also affects Nextvloud v11.0.5.

**Comment by georgehrke** [comment]
@tcitworld Do you agree this is a server bug?

**Comment by georgehrke** [comment]
most likely related to https://github.com/nextcloud/calendar/pull/623
