### ISSUE TITLE
clicking on accept / decline invitation link only works if all nextcloud users have unique E-Mail adresses

### ISSUE THREAD

**Issue by tom-ch1** [nextcloud/calendar#6071]
### Steps to reproduce

1. add an attendant to an event -> a mail is sent
2. In your E-Mail client, click on accept in the body of the mail -> opens a browser window

### Expected behavior

the invitation should be accepted

### Actual behaviour

An error msg appears: "An error occurred while updating your attendance status. Please contact the organizer directly."

### Calendar app version

4.7.4

### CalDAV-clients used

Business Calendar

### Browser

any

### Client operating system

any

### Server operating system

Debian 12

### Web server

Apache

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.1

### Nextcloud version

27.1.10

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - audioplayer: 3.4.1
  - bookmarks: 13.1.3
  - bruteforcesettings: 2.7.0
  - calendar: 4.7.4
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.3
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - data_request: 1.14.0
  - dav: 1.27.0
  - deck: 1.11.4
  - documentserver_community: 0.1.17
  - drawio: 2.1.4
  - external: 5.2.1
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_bpm: 1.4.0
  - files_external: 1.19.0
  - files_markdown: 2.4.1
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_retention: 1.16.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - forms: 3.4.7
  - gpxpod: 5.0.13
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - maps: 1.2.0
  - notes: 4.10.0
  - notifications: 2.15.0
  - oauth2: 1.15.2
  - onlyoffice: 9.2.2
  - passman: 2.4.9
  - password_policy: 1.17.0
  - passwords: 2023.12.32
  - phonetrack: 0.8.1
  - photos: 2.3.0
  - polls: 6.4.1
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - qownnotesapi: 24.4.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.10
  - richdocumentscode: 24.4.201
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.12.0
  - snappymail: 2.36.3
  - spreed: 17.1.9
  - support: 1.10.1
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - theming: 2.2.0
  - theming_customcss: 1.16.0
  - twofactor_backupcodes: 1.16.0
  - unroundedcorners: 1.1.3
  - unsplash: 2.2.1
  - updatenotification: 1.17.0
  - uppush: 1.4.3
  - user_pwauth: 2.8.1
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - analytics: 4.13.0 (installed 4.13.0)
  - apporder: 0.15.0 (installed 0.15.0)
  - circles: 27.0.1 (installed 25.0.0)
  - cms_pico: 1.0.21 (installed 1.0.21)
  - encryption: 2.15.0
  - gpxedit: 0.0.14 (installed 0.0.14)
  - gpxmotion: 0.1.0 (installed 0.1.0)
  - jsloader: 1.5.0 (installed 1.5.0)
  - music: 1.11.0 (installed 1.11.0)
  - nextcloud_announcements: 1.16.0 (installed 1.5.0)
  - ojsxc: 5.0.0 (installed 5.0.0)
  - ownpad: 0.9.5 (installed 0.9.5)
  - radio: 1.0.3 (installed 1.0.3)
  - suspicious_login: 5.0.0
  - talk_simple_poll: 1.3.1 (installed 1.3.1)
  - telephoneprovider: 1.0.3 (installed 1.0.3)
  - text: 3.8.0 (installed 3.3.1)
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
  - weather: 1.7.7 (installed 1.7.7)
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "version": "27.1.10.2",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "default_phone_region": "CH",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "updatechecker": true,
        "maintenance": false,
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 365",
        "updater.release.channel": "stable",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "passman",
            "deck",
            "files_texteditor",
            "files_bpm",
            "files_external_dropbox",
            "apporder",
            "files_markdown",
            "jsloader"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }
}
```

### Additional info

the user who created the invitation has the same E-Mail address as another user. As soon as the E-Mail Addresses are made unique, the accept-link works.

**Comment by hinformatik** [comment]
Why has this issue been closed?

**Comment by miaulalala** [comment]
> So this calendar breaking issue persists for 5 years and nobody tried to fix it yet?

if you read the related ticket would know it's not simply something that can be fixed. The linked tickets contain possible solutions but they all come with drawbacks.

The easiest "solution" is to not allow duplicate email addresses, which, if you're an admin, you can make this a policy. Use LDAP or another user backend and provision your accounts from there.

**Comment by hinformatik** [comment]
The ammount of nonsene in this issue is buffeling.
1. There should be a warning in nextcloud that states that calendar invites will not work if you try to create a user with a duplicate email.
2. The error message that appears if you try to accept an invite should be more helpful.
3. Why not disallow creating duplicate mail accounts completely and solve this issue that way?

**Comment by tom-ch1** [comment]
I opened this issue to make it very easy and clear what the problem (and the workaround) is.
It is, however, still a bug, whether you want to fix it or not. 

Closing this issue is fine for me, I solved it for myself and I wanted to make a clean and clear ticket for others to find and possibly somebody to fix. I hope someday it will be solved for others as well.

**Comment by tom-ch1** [comment]
> > I opened this issue to make it very easy and clear what the problem (and the workaround) is. It is, however, still a bug, whether you want to fix it or not.
> > Closing this issue is fine for me, I solved it for myself and I wanted to make a clean and clear ticket for others to find and possibly somebody to fix. I hope someday it will be solved for others as well.
> 
> Hello tom-ch1! I would like to know the workaround that you are following to solve this. Thank you in advance!

I made all E-Mail addresses unique
