### ISSUE TITLE
Allow for "Travel Time" or similar property (as implemented in iOS)

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#6072]
### Is your feature request related to a problem? Please describe.

This will allow users to add Travel Time to their Calendar events.

With the OpenStreetMap integration / picker, this would be a nice new feature in the Calendar.

Screenshots:

![image](https://github.com/nextcloud/calendar/assets/7427347/53fd6cb3-8b44-4d0e-89e6-efdc245842bc)

![image](https://github.com/nextcloud/calendar/assets/7427347/8c3abe92-e861-4106-b41d-c01e1e4e616e)

Example ics

``` ics
BEGIN:VEVENT
CREATED:20240610T123957Z
DESCRIPTION:- VS: 1. XXX XXXXXX\n- dddddddddd ddddddddd\n- Letzt
 es 9-Ball entfällt\n- dddddddd 4 Spiele gewonnen = Ende
DTEND;TZID=Europe/Berlin:20240622T163000
DTSTAMP:20240619T100011Z
DTSTART;TZID=Europe/Berlin:20240622T133000
LAST-MODIFIED:20240617T113105Z
LOCATION:JHJHJHJH\nJHDKJJSAD\, Deutschland
SEQUENCE:3
SUMMARY:🎱 HDJSHKJSAH ddddddddddd
TRANSP:OPAQUE
UID:842E46B0-FD9A-439E-9C61-B53C031B3XXX
URL;VALUE=URI:
X-APPLE-CREATOR-IDENTITY:com.apple.calendar
X-APPLE-CREATOR-TEAM-IDENTITY:0000000000
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-MAPKIT-HANDLE=CAESlgII2TIa
 dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
 dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
 dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
 dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
 dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
 GpADAQ==;X-APPLE-RADIUS=70.58737439943614;X-APPLE-REFERENCEFRAME=1;X-TIT
 LE="JHJHJHJHdsdadssadasds\nJHDKJJSAD\, Deutschland":geo:00.100000,0.0000
 77
X-APPLE-TRAVEL-DURATION;VALUE=DURATION:PT45M
X-APPLE-TRAVEL-START;ROUTING=CAR;VALUE=URI;X-ADDRESS="L ddddd, 00000 dddd
 ein, Deutschland";X-APPLE-MAPKIT-HANDLE=CAESgQIIrk0Qlp2Jqu2Ox6APGhIJqw2p
 dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
 dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
 dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
 dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
 KyBSaWRlIElkc3RlaW4QACoCZGVAAA==;X-APPLE-RADIUS=000.0000000000000;X-APPL
 E-REFERENCEFRAME=0;X-TITLE=Park + Ride dddddddddd:geo:00.100000,0.000000
END:VEVENT

```

### Describe the solution you'd like

I'd like to be able to pick a start point from the calendar if I set a location for an event (that location should also be integrated into OpenStreetMaps when available, i. e. when the location is an address or GEO point).

If there's the option of calculating the travel time, it should be added as well.

### Additional context
iOS documentation:

https://support.apple.com/de-de/guide/calendar/icl43600/mac

**Comment by miaulalala** [comment]
cc @nextcloud/designers

**Comment by tcitworld** [comment]
See #581 as well

**Comment by miaulalala** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/6072

**Comment by miskovics** [comment]
@miaulalala Is this ticket closed as a duplicate of this very same ticket? I really would like to have this feature. In which ticket is this tracked?
