### ISSUE TITLE
no option to create appointments anymore

### ISSUE THREAD

**Issue by rototom** [nextcloud/calendar#6078]
### Steps to reproduce

click on "create appointment" (or something like this)

### Expected behavior

form opens to edit details of appointment

### Actual behaviour

no option to create one

### Calendar app version

4.7.6

### Browser

Firefox, Safari

### Client operating system

Macos, Windows

### Web server

Other

### Database engine version

MySQL

### PHP engine version

None

### Nextcloud version

28.0.6

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - assistant: 1.1.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.7.6
  - calendar_resource_management: 0.7.0
  - circles: 28.0.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.3
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.2
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_automatedtagging: 1.18.0
  - files_external: 1.20.0
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - flow_notifications: 1.8.0
  - forms: 4.2.4
  - groupfolders: 16.0.7
  - impersonate: 1.15.0
  - integration_openai: 2.0.1
   - lookup_server_connector: 1.16.0
  - mail: 3.7.1
  - memories: 7.3.1
  - notes: 4.10.0
  - notifications: 2.16.0
  - notify_push: 0.6.12
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - passwords: 2024.6.20-build5519
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recognize: 6.1.1
  - recommendations: 2.0.0
  - registertocontact: 0.0.1
  - registration: 2.4.0
  - related_resources: 1.3.0
   - richdocuments: 8.3.8
  - settings: 1.10.1
  - sharebymail: 1.18.0
   - spreed: 18.0.8
  - support: 1.11.1
  - survey_client: 1.16.0
   - systemtags: 1.18.0
  - tables: 0.7.3
  - tasks: 0.16.0
  - text: 3.9.1
   - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_email: 2.7.4
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_reminder: 1.1.0
  - twofactor_totp: 10.0.0-beta.2
   - twofactor_webauthn: 1.4.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflow_pdf_converter: 1.13.0
  - workflowengine: 2.10.0
 Disabled:
  - announcementcenter: 6.8.1 (installed 6.8.1)
  - appointments: 2.1.4 (installed 2.1.4)
  - call_summary_bot: 1.1.1 (installed 1.1.1)
  - collectives: 2.12.0 (installed 2.12.0)
  - context_chat: 2.1.2 (installed 2.1.2)
  - encryption: 2.16.0
  - external: 5.3.1 (installed 5.3.1)
  - federation: 1.18.0 (installed 1.17.0)
  - files_markdown: 2.4.1 (installed 2.4.1)
  - files_rightclick: 0.15.1 (installed 0.15.1)
   - firstrunwizard: 2.17.0 (installed 2.16.0)
  - gptfreeprompt: 1.0.2 (installed 1.0.2)
  - gpxpod: 5.0.18 (installed 5.0.18)
  - integration_deepl: 1.1.3 (installed 1.1.3)
  - journal: 0.0.5-a1 (installed 0.0.5-a1)
  - logreader: 2.13.0 (installed 2.12.0)
   - maps: 1.4.0 (installed 1.4.0)
  - nextcloud_announcements: 1.17.0 (installed 1.17.0)
   - pandoc: 0.7.0 (installed 0.7.0)
  - photos: 2.4.0 (installed 2.4.0)
  - polls: 7.1.1 (installed 7.1.1)
   - printer: 0.0.5 (installed 0.0.5)
  - riotchat: 0.17.3 (installed 0.17.3)
  - serverinfo: 1.18.0 (installed 1.18.0)
   - sharelisting: 1.2.0 (installed 1.2.0)
  - social: 0.6.1 (installed 0.6.1)
   - solitaire: 1.0.0 (installed 1.0.0)
  - suspicious_login: 6.0.0
   - talk_matterbridge: 1.28.0-0 (installed 1.28.0-0)
  - timemanager: 0.3.14 (installed 0.3.14)
  - user_ldap: 1.19.0
  - workflow_ocr: 1.28.1 (installed 1.28.1)
```

**Comment by miaulalala** [comment]
Do you mean this?

![image](https://github.com/nextcloud/calendar/assets/7427347/8add9d6f-abc0-4fbf-9835-a1068239f3da)

**Comment by miaulalala** [comment]
Can you please check your config to see if `disableAppointments` is set?

**Comment by rototom** [comment]
It’s a hetzner storageshare so I don’t have access to the config directly. But it used to work quite good and I don’t think they set it off.

**Comment by miaulalala** [comment]
Can you inquire with their support?

**Comment by rototom** [comment]
I did, but they didnt find anything.

**Comment by rototom** [comment]
I found the config.php:
`{
    "skeletondirectory": "\/var\/www\/html\/themes\/hetzner\/skeleton",
    "simpleSignUpLink.shown": false,
    "blacklisted_files": [],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "appstoreurl": "https:\/\/apps.your-storageshare.de",
    "allow_local_remote_servers": true,
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "files_external_allow_create_new_local": false,
    "loglevel": 2,
    "log_type": "syslog",
    "updatechecker": false,
    "updater.server.url": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "beta",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "28.0.6.1",
    "overwrite.cli.url": "https:\/\/nx50270.your-storageshare.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "default_language": "de",
    "default_locale": "de",
    "default_phone_region": "DE",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "syslog_tag": "nextcloud-nx50270",
    "upgrade.disable-web": true,
    "templatedirectory": "\/var\/www\/html\/core\/skeleton\/Templates\/",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\Krita",
        "OC\\Preview\\HEIC"
    ],
    "activity_expire_days": "31",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": "6379",
        "timeout": "1.5",
        "dbindex": "0"
    },
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "app_install_overwrite": [
        "printer",
        "files_rightclick",
        "twofactor_reminder",
        "talk_matterbridge",
        "mindmap_app"
    ],
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": [],
    "maintenance": false,
    "maintenance_window_start": 23,
    "davstorage.request_timeout": 10800,
    "mail_sendmailmode": "smtp",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memories.exiftool": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/exiftool-amd64-glibc",
    "memories.vod.path": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/go-vod-amd64",
    "trusted_domains": [
        "nx50270.your-storageshare.de",
        "cloud.teamsterntaler.de",
        "www.teamsterntaler.de"
    ]
}`

**Comment by rototom** [comment]
Found the config.php:
`{
    "skeletondirectory": "\/var\/www\/html\/themes\/hetzner\/skeleton",
    "simpleSignUpLink.shown": false,
    "blacklisted_files": [],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "appstoreurl": "https:\/\/apps.your-storageshare.de",
    "allow_local_remote_servers": true,
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "files_external_allow_create_new_local": false,
    "loglevel": 2,
    "log_type": "syslog",
    "updatechecker": false,
    "updater.server.url": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "beta",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "28.0.6.1",
    "overwrite.cli.url": "https:\/\/nx50270.your-storageshare.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "default_language": "de",
    "default_locale": "de",
    "default_phone_region": "DE",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "syslog_tag": "nextcloud-123456789",
    "upgrade.disable-web": true,
    "templatedirectory": "\/var\/www\/html\/core\/skeleton\/Templates\/",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\Krita",
        "OC\\Preview\\HEIC"
    ],
    "activity_expire_days": "31",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": "6379",
        "timeout": "1.5",
        "dbindex": "0"
    },
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "app_install_overwrite": [
        "printer",
        "files_rightclick",
        "twofactor_reminder",
        "talk_matterbridge",
        "mindmap_app"
    ],
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": [],
    "maintenance": false,
    "maintenance_window_start": 23,
    "davstorage.request_timeout": 10800,
    "mail_sendmailmode": "smtp",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memories.exiftool": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/exiftool-amd64-glibc",
    "memories.vod.path": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/go-vod-amd64",
    "trusted_domains": []
    ]
}`

**Comment by rototom** [comment]
Are there any dependencies to this feature to work, which I may have disabled or so?

**Comment by miaulalala** [comment]
No it's all integrated into the calendar app. If you have any logs, could you check for "appointment" or "booking" as a string?

**Comment by miaulalala** [comment]
Oh do you have an email address set for the user account? If not, then the appointments feature won't work.

**Comment by rototom** [comment]
email is set, im waiting for hetzner for the logs.

**Comment by rototom** [comment]
Deactivating assistant solves this for me. Thank you!
