### ISSUE TITLE
files_sharing app required as dependency 

### ISSUE THREAD

**Issue by gbcreation** [nextcloud/calendar#608]
I want to share my calendar with other users of my Nextcloud server. When I click on the Share Calendar icon/button near the name of my calendar in the left panel, nothing happens. I tried with Firefox 55, and Chromium 61 (also with the `--disable-extensions` to ensure there is no extension conflicting with the calendar sharing feature).

### Steps to reproduce
1. Just click on the Share Calendar button/icon near the name of a calendar

### Expected behaviour
It should display some options to configure the calendar sharing.

### Actual behaviour
No options displayed. Nothing happens.

### Server configuration

**Operating system**: ArchLinux
**Web server:** Nginx 1.12.1
**Database:** MariaDB 10.1.26
**PHP version:** 7.1.9
**Server version:** 12.0.2
**Calendar version:** 1.5.5
**Updated from an older installed version or fresh install:** Updated from an older version
**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - audioplayer: 2.1.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - contacts: 1.5.3
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_clipboard: 0.6.4
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.3
  - metadata: 0.5.0
  - music: 0.5.1
  - nextant: 1.0.8
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.1.4
  - ownbackup: 17.5.0
  - password_policy: 1.2.2
  - phonetrack: 0.0.3
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.0
  - rainloop: 5.0.2
  - ransomware_protection: 1.0.3
  - richdocuments: 1.12.34
  - serverinfo: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - comments
  - encryption
  - federation
  - files_antivirus
  - files_sharing
  - firstrunwizard
  - sharebymail
  - survey_client
  - systemtags
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "oc1jnihw4x59",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.xxx.xxx",
            "mylocaldomain.net"
        ],
        "datadirectory": "\/mnt\/data",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "forcessl": true,
        "mail_smtpmode": "php",
        "mail_from_address": "owncloud",
        "mail_domain": "mylocaldomain.net",
        "loglevel": "0",
        "overwritewebroot": "\/cloud",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "\/cloud",
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/optapps",
                "url": "\/optapps",
                "writable": false
            }
        ],
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/cloud"
    }
}
```

**Are you using external storage, if yes which one:** local
**Are you using encryption:** Not the encryption provided by Nextcloud. dm-crypt at the system level.
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 55.0.3 (64 bits) and Chromium 61
**Operating system:** ArchLinux
**CalDAV-clients:** None

#### Browser log

```
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
"Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info."  core.js:1563:2834
```

**Comment by tcitworld** [comment]
Is the Sharing feature activated in the Nextcloud administration section ? Do you have an adblocker ?

**Comment by gbcreation** [comment]
Here is my configuration in the Nextcloud administration section:
![spectacle x28078](https://user-images.githubusercontent.com/454315/30663345-a36437a8-9e4a-11e7-8b87-989cb7674554.png)

Using the settings above, nothing appears when I click on the Share Calendar button/icon near the name of my calendar in the Calendar app.

If I enable **Allow users to share via link**, and i click on the Share Calendar icon/button near the name of my calendar, there is only a **Share link** checkbox that appears. When I check this box, there is only a **Public access** label that appears like this:
![spectacle d28078](https://user-images.githubusercontent.com/454315/30663529-36eb9ba6-9e4b-11e7-8c38-c73310114307.png)

But this is not what I want. I don't want to share my calendar using a public link. I would like to share it only to other users of my Nextcloud server, and configure the rights they could have (can share, can edit, etc). Something similar to this screenshot shown in this answer on superuser.com: https://superuser.com/questions/593424/owncloud-multiple-users-in-one-calendar/656989#656989

![](https://i.stack.imgur.com/6b5nR.png)

I have an adblocker (uMatrix on Firefox / uBlock Origin and uMatrix on Chromium). I know there could be a problem when using an adblocker as explained in this issue: https://github.com/nextcloud/server/issues/866. But I have the same behavior when I launch Chromium without extensions with `chromium --disable-extensions`.

What additional information may I give you to determine the cause of this problem?

**Comment by georgehrke** [comment]
@tcitworld Might this be related to your fix for respecting the option to disable public sharing?

**Comment by tcitworld** [comment]
Will look at this.

**Comment by crbble** [comment]
Any news on this?

**Comment by gbcreation** [comment]
Many thanks @crbble !
Indeed, after enabling the File Sharing app, I can now share my calendar with other users of my Nextcloud server. I thought this app was only required to share files, as its name implied, not at all to share calendars. Very confusing!

**Comment by georgehrke** [comment]
>  I thought this app was only required to share files, as its name implied, not at all to share calendars. Very confusing!

This is obviously not the expected behavior.
Reopening ...

**Comment by hieronymousch** [comment]
I can confirm this behaviour on nextcloud 13, works again after re-enabling file sharing app

**Comment by georgehrke** [comment]
Implemented in https://github.com/nextcloud/calendar/pull/926
