### ISSUE TITLE
Color picker to narrow choices

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/calendar#61]
Version 1.4:

Adding Color to a calendar is limited to 8 choices only!

In my case I do run 11 different Calendars..already!

Should be more !

regards, hitam4450

**Comment by georgehrke** [comment]
@hitam4450 please use the issue template and search for existing bugs before creating new ones ...

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/4
