### ISSUE TITLE
upgrade apps 4.7.8 -> 4.7.9 is buggy

### ISSUE THREAD

**Issue by Zweihorn** [nextcloud/calendar#6116]
### Steps to reproduce

1. NC 28.0.7
2. macOS 13.6.7 Intel with Safari Version 17.5 (18618.2.12.111.5, 18618)
3. Web-GUI for NC Apps and announced calendar 4.7.9 update
4. _Klick left on calendar 4.7.8_ row **update button** for upgrading **results in weather app info** strangely

![Bildschirmfoto 2024-07-04 um 00 59 41](https://github.com/nextcloud/calendar/assets/4863737/841b9285-c61b-40b4-9f7e-bccb192e987f)

![Bildschirmfoto 2024-07-04 um 00 59 24](https://github.com/nextcloud/calendar/assets/4863737/6b6f4ff7-272c-47fe-b5e1-ea92a9ba28ad)

### Expected behavior

Update of calender app from 4.7.8 to 4.7.9

### Actual behaviour

No single upgrade was possible even after log-out and log-in.

Upgrade was only activated by general _update all_ instead.

### Calendar app version

4.7.8 / 4.7.9

### Browser

Safari Version 17.5 (18618.2.12.111.5, 18618)

### Client operating system

macOS 13.6.7 Intel

### Server operating system

GNU/Linux Debian 12.6 Bookworm

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

28.07

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by joshtrichards** [comment]
This might be related to nextcloud/server#42249 which is fixed in v29, but the v28 backport is still pending nextcloud/server#44327

Unless you're saying this somehow only impacts the Calendar app.

**Comment by Zweihorn** [comment]
Server business and not your cup of tea apparently.

THX
