### ISSUE TITLE
Version 1.5.5 is sending wierd emails to members of a calendar entry

### ISSUE THREAD

**Issue by mfechner** [nextcloud/calendar#612]
### Steps to reproduce
-  You get an invitation to an event by email (attached ical file), add this calendar event to your nextcloud calendar

### Expected behaviour
Nextcloud should not send email to the members of this invitation

### Actual behaviour
Each person that is invited by this invitation is receiving an email from the nextcloud system.
It looks like I have invited them, which is wrong, I just received an invitation which I accepted.
This results in double calendar entries.

**Comment by tcitworld** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues and point over to this issue.

Also, depending on your Nextcloud version, it may be related to https://github.com/nextcloud/server/pull/5841

**Comment by georgehrke** [comment]
I don't think this is related to nextcloud/server#5841

@mfechner as @tcitworld said, please create an issue in https://github.com/nextcloud/server/issues  and please use the entire issue template. There is a reason it's there ;)
