### ISSUE TITLE
Mozilla Lightning: 'Primary CalDAV address' incomplete for integration

### ISSUE THREAD

**Issue by EDavidF** [nextcloud/calendar#614]
I hope this is enough info:

### Steps to reproduce
1. Copy 'Primary CalDAV address' from NC web GUI;
2. Paste into 'Location' with CalDAV selected in New Calendar-On the Network in Lightning;
3. Connect.

### Expected behaviour
Lightning should connect to server and integrate calendar.

### Actual behaviour
Lightning tries to connect and gets an error (yellow "!" triangle and message 'The calendar XXX is momentarily not available'- which never changes)

### Fix
'Primary CalDAV address'  gives this: https://server.dom/remote.php/dav/

   Should be: https://server.dom/remote.php/dav/calendars/USERNAME/CALENDARNAME

### General server configuration

**Operating system:** Linux pelvis 4.8.0-59-generic #64-Ubuntu SMP Thu Jun 29 19:38:34 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.29

**PHP version:** 7.0.18-0ubuntu0.16.10.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - igbinary
 - imap
 - intl
 - json
 - exif
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - redis
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 11.0.4 (stable) - 11.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  YOUR ANSWER HERE

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.4.1
 - calendar: 1.5.5
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - federatedfilesharing: 1.1.1
 - files: 1.6.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - tasks: 0.9.5
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - encryption
 - external
 - federation
 - files_accesscontrol
 - files_automatedtagging
 - files_external
 - files_pdfviewer
 - files_retention
 - files_videoplayer
 - systemtags
 - templateeditor
 - theming
 - user_external
 - user_ldap
 - user_saml
 - weather
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "oc6i9ni2j0rz",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "127.0.0.1",
        "192.168.1.70",
        "pelvis.ddns.net"
    ],
    "datadirectory": "\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbtype": "mysql",
    "version": "11.0.4.1",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 6379
    },
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "eric",
    "mail_domain": "buffalobillgoesiceskating.net",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "mail.buffalobillgoesiceskating.net",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "loglevel": 2,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by tcitworld** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

Also, this is an issue with Lightning not being able to get the list of calendars, it works pretty well with other tools such as KOrganizer, Gnome Online Accounts or DAVdroid.

**Comment by georgehrke** [comment]
As @tcitworld already said, other applications support auto discovery. Unfortunately this feature has not yet been implemented in Thunderbird.

That's why we show the link for every calendar when you click the three dots.

Also, if we replaced it with `https://server.dom/remote.php/dav/calendars/USERNAME/CALENDARNAME`, how are we supposed to display ONE link?
