### ISSUE TITLE
Redesign app settings toggle so it looks like Files in Nextcloud 30

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#6141]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/nextcloud/calendar/assets/1374172/a3fb485f-d348-4838-b26a-0a0806293d26)
vs
![image](https://github.com/nextcloud/calendar/assets/1374172/090b61d5-da38-413a-9f57-b3d66b790875)

### Describe the solution you'd like

Make the Calendar one look like Files
* Shouldn't be highlighted
* Shouldn't be pill style

**Comment by GVodyanov** [comment]
Should be fixed by using latest nextcloud vue https://github.com/nextcloud-libraries/nextcloud-vue/commit/8c75d88c27b1a085b0ea610a38327b21980c3600

Do you confirm @st3iny ?

**Comment by ChristophWurst** [comment]
border radius yes but we also have to make it left-aligned. not sure if that is also handled by nc/vue already?

**Comment by st3iny** [comment]
True, but the styling is still a bit off compared to files. It should be a `tertiary` button but currently looks like a `secondary` button. Also the padding doesn't seem to be matching. The button on files is slightly more padded and bigger overall.
