### ISSUE TITLE
Calendar actions menu is too wide

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#6142]
### Steps to reproduce

1. Open the app
2. Click *...* next to a calendar

### Expected behavior

Narrow menu (@nimishavijay how narrow exactly?)

### Actual behaviour

![image](https://github.com/nextcloud/calendar/assets/1374172/ff88356b-49c6-4d68-a292-4a26673db62f)

### Calendar app version

4.8

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
If all action menues should have a maximum width this change should go into nextcloud/vue

**Comment by ChristophWurst** [comment]
Contacts: 
![image](https://github.com/nextcloud/calendar/assets/1374172/1727b663-c109-4d2d-a50b-fd87bbb2675b)

we need to fix this in nextcloud/vue. @jancborchardt @nimishavijay what is the max width actions should have?

**Comment by GVodyanov** [comment]
Found where it needs to be changed @ChristophWurst https://github.com/nextcloud-libraries/nextcloud-vue/blob/a98fa7a2b7f0ac42d4ba46cf20c5020a5f428fec/src/assets/action.scss#L83

I propose `180px`

**Comment by marcoambrosini** [comment]
Let's make it depend on the clickable area:
`calc(var(--default-clickable-area) * 5))` = 170px

**Comment by GVodyanov** [comment]
Closing as is not needed, see https://github.com/nextcloud-libraries/nextcloud-vue/pull/5807#pullrequestreview-2191598387
