### ISSUE TITLE
Overlapping colors in calendar color picker and unused choose button

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#6145]
### Steps to reproduce

1. Open the app
2. Open the edit modal of a calendar
3. Click the calendar color

### Expected behavior

Good design

### Actual behaviour

![image](https://github.com/nextcloud/calendar/assets/1374172/a38020d4-5116-4d44-9cca-b6142f4f6259)

* [x] Overlapping bubbles
* [ ] *Choose* does not do anyhting

### Calendar app version

4.8

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by st3iny** [comment]
For reference, this is how it looks on 29

| Palette | Advanced |
| --- | --- |
| ![Bildschirmfoto_20240716_094126](https://github.com/user-attachments/assets/ce340fa3-30f2-4d8d-a17c-8fd005c38dc3) | ![Bildschirmfoto_20240716_094142](https://github.com/user-attachments/assets/993ee9ca-3d8e-4056-b8ca-bd40c017370e) |

**Comment by ChristophWurst** [comment]
> _Choose_ does not do anyhting

It is because of https://github.com/nextcloud-libraries/nextcloud-vue/pull/5499. @susnux I'm not sure how apps should handle the submit event in the simple mode of the color picker. The app can process the selection but it can't close the picker, can it?

**Comment by st3iny** [comment]
It seems like a bug to me. There is no prop to control the open state from the outside but there is an event `update:open` which would suggest an `open` prop.

### Component props

https://nextcloud-vue-components.netlify.app/#/Components/NcPickers?id=nccolorpicker

![grafik](https://github.com/user-attachments/assets/5b7aaf7c-7132-497c-b3e3-fe80d87469d2)

**Comment by st3iny** [comment]
The open state can be controlled from the outside via the `shown` prop or synced via `shown:sync`. The prop is currently not documented as it is passed down to `NcPopover` via `v-bind`.

So we could add an open state variable `showColorPicker` to data and listen to the `submit` event to actually apply the color.

### Example

```vue
<NcColorPicker :shown.sync="showColorPicker" @submit="setColor">...</NcColorPicker>
```

**Comment by ChristophWurst** [comment]
Nice, thank you!
