### ISSUE TITLE
appointments: internationalization i10n for confirmation email & calendar entries not correct

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/calendar#6156]
### Steps to reproduce

1. language: EN. 
2. create an appointment
3. another person with no Nextcloud account and with their machine/browser set to language ESP books an appointment - page is shown in esp, confirmation email they get is in ESP - good.

### Expected behavior

organizer of the appointment gets confirmation email in EN

### Actual behaviour

organizer of the appointment gets confirmation email in ESP

### Calendar app version

4.7.8

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

28.0.6

### Updated from an older installed version or fresh install

None

### Additional info

let me know if you need more info

**Comment by alexanderdd** [comment]
@miaulalala wow that was quick!!! :rocket: 

I just noticed that the calendar entries that are generated from appointments also follow the language of the user who books the appointment -> should follow language of the user who created the appointment.

should I open a new issue for this?

**Comment by miaulalala** [comment]
> @miaulalala wow that was quick!!! 🚀
> 
> I just noticed that the calendar entries that are generated from appointments also follow the language of the user who books the appointment -> should follow language of the user who created the appointment.
> 
> should I open a new issue for this?

Nah I'll reopen this one, I've seen that too
