### ISSUE TITLE
Calendar 1.5.5 - Update

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/calendar#616]
Notification reports Calendar update 1.5.5 - nothing available form Github!
regards, hitam4450

![nc_message](https://user-images.githubusercontent.com/9738727/30905908-7e07671a-a376-11e7-8436-9fe0f970ae16.png)

**Comment by georgehrke** [comment]
It is on GitHub: https://github.com/nextcloud/calendar/pull/605

This release doesn't contain any real bug fixes but only a signing issue
