### ISSUE TITLE
The event disappears when you change the month to an event that repeats every year

### ISSUE THREAD

**Issue by emptipat** [nextcloud/calendar#6160]
### Steps to reproduce

1. Create event (15 July 2024), repeat every year and push button "save"
2. Update event for the 15 August 2024 and push button "Update this and all future"
3. Result. The event has disappeared in 2024 and the event in 2025 is July 15 instead of August 15.

### Expected behavior

The event should appear on August 15, 2024 and August 15, 2025

### Actual behaviour

The event has disappeared in 2024 and the event in 2025 is July 15 instead of August 15.

### Calendar app version

4.7.11

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

29.0.3

### Updated from an older installed version or fresh install

None

**Comment by spipau** [comment]
Same here, when I create an event which should repeat itself every second month and never ends, the event is not displayed, this does not work:

![Bildschirmfoto vom 2024-07-17 19-30-26](https://github.com/user-attachments/assets/72db9796-0b39-48bd-9a88-9a77526841b4)

**Comment by emptipat** [comment]
Rewrite this bug https://github.com/nextcloud/calendar/issues/6437  to have label 0. totriage
