### ISSUE TITLE
Redistribute applicaiton

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/calendar#617]
Hey, I'm planning on modifying some functionality of the calendar and then redistribute it privately on my nextcloud server.  
Now I have 2 questions: 
The first one is that how to build the app and prepare it to distribute? Does running ``gulp run build`` in the ``js`` dir suffice? what else should I do?  What directories should be present in production build?  
The second one is that after building the project, How can I instruct my own server to install the app? Is there some directory in nextcloud that I should put this app in that?

**Comment by georgehrke** [comment]
>  planning on modifying some functionality of the calendar and then redistribute it privately on my nextcloud server.

Depending on what you are going to change we might be happy to take it in upstairs ;) 

> The first one is that how to build the app and prepare it to distribute? Does running gulp run build in the js dir suffice? what else should I do? What directories should be present in production build?

`make appstore`

>  Is there some directory in nextcloud that I should put this app in that?

`/apps/` inside the Nextcloud dir

**Comment by mehrdaad** [comment]
> Depending on what you are going to change we might be happy to take it in upstream ;)
Described in [618](https://github.com/nextcloud/calendar/issues/618).  
I'm trying to change date type from Gregorian to Jalali. 

> make appstore
So, after running this command, which directory should I copy to ``/apps`` folder inside Nextcloud.

**Comment by georgehrke** [comment]
`make appstore` will create a `calendar.tar.gz` inside `build/artifacts/`

**Comment by ahangarha** [comment]
> I'm trying to change date type from Gregorian to Jalali 

Any update?

**Comment by mehrdaad** [comment]
Yes it's done
