### ISSUE TITLE
How to change date type of moment

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/calendar#618]
I noticed you are using moment, for date and time usage.  
Is there a central place to change date type or load a specific plugin?  
I notice that ``moment`` is used in ``calcontroller.js`` but it's not defined anywhere.  
Can give a hint about this problem?

**Comment by georgehrke** [comment]
> Can give a hint about this problem?

moment is loaded by the Nextcloud server already.

**Comment by georgehrke** [comment]
moment itself refers to http://momentjs.com

**Comment by mehrdaad** [comment]
> moment is loaded by the Nextcloud server already.
So how would I change date type on moment?  
Can give a hint about that?

**Comment by georgehrke** [comment]
You can find the moment.js documentation here: http://momentjs.com/docs/

**Comment by mehrdaad** [comment]
I know how to change locale in moment, But what is the appropriate way to change it in Nextcloud or this calendar way?

**Comment by georgehrke** [comment]
The locale is currently determined based on a users language but there will be a dedicated locale setting soon: https://github.com/nextcloud/server/issues/1781

**Comment by mehrdaad** [comment]
Can give a hint which file does that thing?

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/blob/6ca4b9eee9793419179b8abb0440bb1e8e5cf38f/core/js/js.js#L1297

**Comment by mehrdaad** [comment]
Thanks. Can I ask you question if I encounter a problem?

**Comment by mehrdaad** [comment]
@georgehrke one question, I saw the file you pointed me. Where is the moment variable initialized?  
Also, does that project use any package manager and build file?!! I saw nothing related to that

**Comment by georgehrke** [comment]
> Where is the moment variable initialized?

moment itself is being defined here: https://github.com/nextcloud/server/blob/master/core/vendor/moment/min/moment-with-locales.min.js

> Also, does that project use any package manager and build file?!! I saw nothing related to that

That project = moment? 
Apparently they use grunt, see https://github.com/moment/moment/

**Comment by mehrdaad** [comment]
> That project = moment?

Nope I mean nextcloud server, I wanted to add another dependency project, but couldn't find any dependency manger, build tool around.

**Comment by georgehrke** [comment]
> Nope I mean nextcloud server, I wanted to add another dependency project, but couldn't find any dependency manger, build tool around.

Not really. add it in `core/vendor` and then add it to `core/js/core.json`

> Ok, where is the un-minified code? I want to modify it.

There is only the minified version in the nextcloud server. If you want to modify it, you will have to grab the unmodified version from momentjs.com

Questions regarding extending the Nextcloud server itself are best placed in #nextcloud-dev on freenode
