### ISSUE TITLE
Today highlight is shown round

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#6183]
### Steps to reproduce

1. Open the app

### Expected behavior

Boxy design
![Bildschirmfoto vom 2024-07-19 07-21-56](https://github.com/user-attachments/assets/2d9bab72-1281-4608-a61a-79c13392a375)

### Actual behaviour

![Bildschirmfoto vom 2024-07-19 07-22-03](https://github.com/user-attachments/assets/da11cb35-a387-4284-9500-8814b8777ae5)

### Calendar app version

4.8

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
@nimishavijay change or leave?

**Comment by ChristophWurst** [comment]
@marcoambrosini ?

**Comment by marcoambrosini** [comment]
i'd go with `--border-radius-small`
