### ISSUE TITLE
Default reminder at event start labeled as "a few seconds"

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#6185]
### Steps to reproduce

1. Open the app
2. Open the settings menu at the bottom left
3. Open the default reminders select menu

### Expected behavior

Something like 
![image](https://github.com/user-attachments/assets/89f5b5ad-c665-4682-a196-4abd15a668e3)

### Actual behaviour

![Bildschirmfoto vom 2024-07-22 08-54-06](https://github.com/user-attachments/assets/bb693e83-7e8b-4914-a394-e35b783bdbc6)

### Calendar app version

4.8

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by abdou6666** [comment]
Hello, I am new to OSS and interested in contributing. Is someone working on this issue?

**Comment by ChristophWurst** [comment]
Nobody is working on this. Feel free to experiment with it. 

https://nextcloud.com/developer/ for assistance.

**Comment by GretaD** [comment]
closed here: https://github.com/nextcloud/calendar/pull/6249/files
