### ISSUE TITLE
[stable4.7] Attendees text overlapping, unreadable (illegible)

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/calendar#6217]
### Steps to reproduce

1. add an attendee
2. see this: 
![image](https://github.com/user-attachments/assets/9d42e27a-9643-455f-b1d2-e6f11f632b36)

### Expected behavior

text should be readable

### Actual behaviour

not readable (legible)

### Calendar app version

This is on c.nc.com - cannot check versions

### Browser

Firefox 128.0.3

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

29.0.4

### Updated from an older installed version or fresh install

None

### Additional info

This is on c.nc.com - cannot check versions

**Comment by miaulalala** [comment]
Can't reproduce on c.nc (5.0.0-beta3) and stable4.7

**Comment by miaulalala** [comment]
I was wrong - it's still there:

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/issues/6150 missing a backport?

**Comment by miaulalala** [comment]
Fixed with https://github.com/nextcloud/calendar/pull/6232
