### ISSUE TITLE
LDAP backend: unable to write on other user's shared calendar. "No DN found" shown on logs

### ISSUE THREAD

**Issue by dsrom** [nextcloud/calendar#624]
### Steps to reproduce
1. configure LDAP auth backend
2. create a calendar on user A and share it with user B with write permission
3. log in as user B and try to add an entry to A's calendar

### Expected behaviour
In user B's drop-down list for allowed calendars, A's calendar should be shown.

### Actual behaviour
A's calendar is not shown.

### General server configuration

**Operating system:** Linux dd11226 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 5.7.15

**PHP version:** 7.0.20-nmm1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - bcmath
 - bz2
 - calendar
 - ctype
 - dom
 - hash
 - filter
 - ftp
 - gettext
 - SPL
 - iconv
 - json
 - mbstring
 - posix
 - Reflection
 - session
 - standard
 - shmop
 - SimpleXML
 - soap
 - exif
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xml
 - xmlreader
 - xmlwriter
 - zip
 - cgi-fcgi
 - propro
 - raphf
 - http
 - mysqlnd
 - PDO
 - curl
 - fileinfo
 - gd
 - gender
 - gmp
 - htscanner
 - imagick
 - imap
 - interbase
 - intl
 - ldap
 - mailparse
 - mcrypt
 - mongodb
 - mysqli
 - OAuth
 - odbc
 - pdo_dblib
 - pdo_mysql
 - PDO_ODBC
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - Phar
 - pspell
 - recode
 - SourceGuardian
 - sqlite3
 - tidy
 - xsl
 - ionCube Loader
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from Nextcloud 12.0.2

**Where did you install Nextcloud from:**  web hoster's utility

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP (openLDAP)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - apporder: 0.4.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.3
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ownnotes: 0.0.2
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - activity
 - admin_audit
 - admin_notifications
 - announcementcenter
 - dashboard
 - encryption
 - files_external
 - gallery
 - notes
 - user_external
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ochjoqynsl8d",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "dsrom-intranet.de",
        "www.dsrom-intranet.de"
    ],
    "datadirectory": "\/www\/htdocs\/w01748a2\/dsrom-intranet.de\/data",
    "overwrite.cli.url": "http:\/\/dsrom-intranet.de",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "d0279cd5",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "V2UQw_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "tempdirectory": "\/www\/htdocs\/w01748a2\/dsrom-intranet.de\/tmp\/",
    "maintenance": false,
    "updater.release.channel": "stable",
    "theme": "",
    "loglevel": "0",
    "defaultapp": "ownnotes",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpsecure": "tls",
    "mail_from_address": "itsupport",
    "mail_domain": "dsrom.de",
    "mail_smtpauth": 1,
    "mail_smtphost": "ssl0.ovh.net",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

<details>
        <summary>LDAP config</summary>
+-------------------------------+-------------------------------------------------+
| Configuration                 |                                                 |
+-------------------------------+-------------------------------------------------+
| hasMemberOfFilterSupport      |                                                 |
| hasPagedResultSupport         |                                                 |
| homeFolderNamingRule          |                                                 |
| lastJpegPhotoLookup           | 0                                               |
| ldapAgentName                 | cn=admin,dc=dsrom,dc=local                      |
| ldapAgentPassword             | ***                                             |
| ldapAttributesForGroupSearch  |                                                 |
| ldapAttributesForUserSearch   |                                                 |
| ldapBackupHost                |                                                 |
| ldapBackupPort                |                                                 |
| ldapBase                      | dc=dsrom,dc=local                               |
| ldapBaseGroups                | dc=dsrom,dc=local                               |
| ldapBaseUsers                 | ou=Users,dc=dsrom,dc=local                      |
| ldapCacheTTL                  | 600                                             |
| ldapConfigurationActive       | 1                                               |
| ldapDefaultPPolicyDN          |                                                 |
| ldapDynamicGroupMemberURL     |                                                 |
| ldapEmailAttribute            | mail                                            |
| ldapExperiencedAdmin          | 0                                               |
| ldapExpertUUIDGroupAttr       |                                                 |
| ldapExpertUUIDUserAttr        |                                                 |
| ldapExpertUsernameAttr        |                                                 |
| ldapGidNumber                 | gidNumber                                       |
| ldapGroupDisplayName          | cn                                              |
| ldapGroupFilter               |                                                 |
| ldapGroupFilterGroups         |                                                 |
| ldapGroupFilterMode           | 0                                               |
| ldapGroupFilterObjectclass    |                                                 |
| ldapGroupMemberAssocAttr      | member                                          |
| ldapHost                      | ldaps://ldap.dsrom.eu                           |
| ldapIgnoreNamingRules         |                                                 |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(mail=%uid))) |
| ldapLoginFilterAttributes     | mail                                            |
| ldapLoginFilterEmail          | 0                                               |
| ldapLoginFilterMode           | 0                                               |
| ldapLoginFilterUsername       | 0                                               |
| ldapNestedGroups              | 0                                               |
| ldapOverrideMainServer        |                                                 |
| ldapPagingSize                | 500                                             |
| ldapPort                      | 636                                             |
| ldapQuotaAttribute            |                                                 |
| ldapQuotaDefault              |                                                 |
| ldapTLS                       | 0                                               |
| ldapUserDisplayName           | displayname                                     |
| ldapUserDisplayName2          |                                                 |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                  |
| ldapUserFilterGroups          |                                                 |
| ldapUserFilterMode            | 0                                               |
| ldapUserFilterObjectclass     | inetOrgPerson                                   |
| ldapUuidGroupAttribute        | auto                                            |
| ldapUuidUserAttribute         | auto                                            |
| turnOffCertCheck              | 0                                               |
| turnOnPasswordChange          | 0                                               |
| useMemberOfToDetectMembership | 1                                               |
+-------------------------------+-------------------------------------------------+

</details>

### Client configuration

**Browser:** Chrome 61.0 

**Operating system:** Windows 8.1

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

{"reqId":"WdX0aFUNhcUAAA201lIAAAAR","level":0,"time":"2017-10-05T08:59:21+00:00","remoteAddr":"79.60.225.26","user":"c38b4430-2e9f-1037-9eda-1ba2ecc451b0","app":"user_ldap","method":"PROPPATCH","url":"\/remote.php\/dav\/calendars\/c38b4430-2e9f-1037-9eda-1ba2ecc451b0\/kalender_shared_by_administrator\/","message":"No DN found for Licata Pietro on ldaps:\/\/ldap.dsrom.eu","userAgent":"Mozilla\/5.0 (Windows NT 6.3; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}

</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - apporder: 0.4.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - issuetemplate: 0.2.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.3
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ownnotes: 0.0.2
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - activity
  - admin_audit
  - admin_notifications
  - announcementcenter
  - dashboard
  - encryption
  - files_external
  - gallery
  - notes
  - user_external

```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "ochjoqynsl8d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dsrom-intranet.de",
            "www.dsrom-intranet.de"
        ],
        "datadirectory": "\/www\/htdocs\/w01748a2\/dsrom-intranet.de\/data",
        "overwrite.cli.url": "http:\/\/dsrom-intranet.de",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "d0279cd5",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "V2UQw_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "tempdirectory": "\/www\/htdocs\/w01748a2\/dsrom-intranet.de\/tmp\/",
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": "0",
        "defaultapp": "ownnotes",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "itsupport",
        "mail_domain": "dsrom.de",
        "mail_smtpauth": 1,
        "mail_smtphost": "ssl0.ovh.net",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** yno

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
+-------------------------------+-------------------------------------------------+
| Configuration                 |                                                 |
+-------------------------------+-------------------------------------------------+
| hasMemberOfFilterSupport      |                                                 |
| hasPagedResultSupport         |                                                 |
| homeFolderNamingRule          |                                                 |
| lastJpegPhotoLookup           | 0                                               |
| ldapAgentName                 | cn=admin,dc=dsrom,dc=local                      |
| ldapAgentPassword             | ***                                             |
| ldapAttributesForGroupSearch  |                                                 |
| ldapAttributesForUserSearch   |                                                 |
| ldapBackupHost                |                                                 |
| ldapBackupPort                |                                                 |
| ldapBase                      | dc=dsrom,dc=local                               |
| ldapBaseGroups                | dc=dsrom,dc=local                               |
| ldapBaseUsers                 | ou=Users,dc=dsrom,dc=local                      |
| ldapCacheTTL                  | 600                                             |
| ldapConfigurationActive       | 1                                               |
| ldapDefaultPPolicyDN          |                                                 |
| ldapDynamicGroupMemberURL     |                                                 |
| ldapEmailAttribute            | mail                                            |
| ldapExperiencedAdmin          | 0                                               |
| ldapExpertUUIDGroupAttr       |                                                 |
| ldapExpertUUIDUserAttr        |                                                 |
| ldapExpertUsernameAttr        |                                                 |
| ldapGidNumber                 | gidNumber                                       |
| ldapGroupDisplayName          | cn                                              |
| ldapGroupFilter               |                                                 |
| ldapGroupFilterGroups         |                                                 |
| ldapGroupFilterMode           | 0                                               |
| ldapGroupFilterObjectclass    |                                                 |
| ldapGroupMemberAssocAttr      | member                                          |
| ldapHost                      | ldaps://ldap.dsrom.eu                           |
| ldapIgnoreNamingRules         |                                                 |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(mail=%uid))) |
| ldapLoginFilterAttributes     | mail                                            |
| ldapLoginFilterEmail          | 0                                               |
| ldapLoginFilterMode           | 0                                               |
| ldapLoginFilterUsername       | 0                                               |
| ldapNestedGroups              | 0                                               |
| ldapOverrideMainServer        |                                                 |
| ldapPagingSize                | 500                                             |
| ldapPort                      | 636                                             |
| ldapQuotaAttribute            |                                                 |
| ldapQuotaDefault              |                                                 |
| ldapTLS                       | 0                                               |
| ldapUserDisplayName           | displayname                                     |
| ldapUserDisplayName2          |                                                 |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                  |
| ldapUserFilterGroups          |                                                 |
| ldapUserFilterMode            | 0                                               |
| ldapUserFilterObjectclass     | inetOrgPerson                                   |
| ldapUuidGroupAttribute        | auto                                            |
| ldapUuidUserAttribute         | auto                                            |
| turnOffCertCheck              | 0                                               |
| turnOnPasswordChange          | 0                                               |
| useMemberOfToDetectMembership | 1                                               |
+-------------------------------+-------------------------------------------------+
```

### Client configuration
**Browser:** Chrome 61.0

**Operating system:** Windows 8.1

**CalDAV-clients:** no

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment]
dup of #606
