### ISSUE TITLE
Install calendar app outside of nextcloud

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/calendar#625]
Is it possible to install calendar outside of nextcloud scope?  
What I want to achieve is that I have another application and the requirement is that add calendar functionality  to it.  
Is this possible? please give some tips

**Comment by tcitworld** [comment]
The calendar app relies on http://sabre.io/ for the backend and https://fullcalendar.io/ for the front-end, so you should be able to do whatever needed with those two.

**Comment by mehrdaad** [comment]
So, how would I extract this plugin? What is proper way of authenticating users? please give some hints. thank you
