### ISSUE TITLE
Hidden shared calendars should be listed in *Hidden*, not *Shared calendars*

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#6259]
### Steps to reproduce

1. Create user a and user b
2. Log in as user a and share a calendar with b
3. Log in as b and hide the shared calendar

### Expected behavior

The calendar moves to the *Hidden* section of the new sidebar (https://github.com/nextcloud/calendar/issues/5083)

### Actual behaviour

The hidden calendar stays in *Shared calendars*

### Calendar app version

5.0

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by stefangweichinger** [comment]
Could we get this behavior toggleable?
At a customer we would prefer to have the possibility to quickle toggle off a calendar without it "hopping" into that section "Hidden". thanks ...

**Comment by ChristophWurst** [comment]
Dear @stefangweichinger! Thank you for your feedback. Please head over to https://github.com/nextcloud/calendar/issues and create a new feature request for this. Thank you very much.
