### ISSUE TITLE
Shared writeable calendar with individual appears broken - how to debug?

### ISSUE THREAD

**Issue by ccoenen** [nextcloud/calendar#626]
I am missing a calendar that has been shared with me. The sharing seems broken, detailed description follows.

* Left half of the screenshot is Chrome with the admin user. Admin owns a calendard called "Things" it has been shared with a user, including write permissions.
* Right half of the screenshot is Firefox with that user logged in. Some shares obviously worked (those are shares via group!). The `Things`-Calendar does _not_ show up. Neither in calendars section nor in subscribed section.

![grafik](https://user-images.githubusercontent.com/124909/31376849-850aeec6-ada6-11e7-95b5-dc4efbdea540.png)

### Steps to reproduce
1. Have two users, one owns a calendar
2. Share with second user
3. Check "write permissions" Box
4. Reload the owner's browser and confirm the shares have been set and stored.

### Expected behaviour
* The sharing should have been applied and visible in the **owner**'s brower. There should be one item for this user, it should have the "can edit" box checked.
* The **user** should now see the calendar, it should be writeable and in the regular calendars list (upper list).

### Actual behaviour
The owner sees the shared user _twice_! once with and once _without_ write permission:

![grafik](https://user-images.githubusercontent.com/124909/31377250-b3faafcc-ada7-11e7-8655-b0cbb4e44380.png)

The user sees the calendar in the subscription section (and it is read-only).

After removing the read-only share entry, the _writable_ stays in place (even across reloads!) but the calendar is gone for the regular user. (this is the state of the first, large screenshot above).

### Server configuration
**Operating system**:
Ubuntu 16.04 w/ latest patches

**Web server:**
Apache2 from Ubuntu packages

**Database:**
MariaDB 10.0.31 from Ubuntu packages

**PHP version:**
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

**Server version:** (see your admin page)
12.0.3

**Calendar version:** (see the apps page)
1.5.5

**Updated from an older installed version or fresh install:**
fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "ocy86resd18f",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED"
        ],
        "datadirectory": "\/var\/www\/nextcloud-data",
        "overwrite.cli.url": "https:\/\/REMOVED",
        "dbtype": "mysql",
        "dbname": "nc2017ws",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "mail_from_address": "services",
        "mail_smtpmode": "smtp",
        "mail_domain": "REMOVED",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "REMOVED",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 2592000,
        "session_lifetime": 604800,
        "skeletondirectory": "",
        "version": "12.0.3.3",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 56 & Chrome 

**Operating system:**
Windows 10

**CalDAV-clients:**
not applicable

#### Web server error log
```
(nothing related)
```

#### Log file (data/nextcloud.log)
```
(nothing related)
```

#### Browser log
```
(nothing out of the ordinary)
```

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/606

**Comment by georgehrke** [comment]
will release 1.5.6 shortly

**Comment by ccoenen** [comment]
Thanks! :-)

**Comment by ccoenen** [comment]
1.5.6 fixed it indeed :-)
