### ISSUE TITLE
Access to the calendar -> 401 error message

### ISSUE THREAD

**Issue by nobody1407** [nextcloud/calendar#627]
### Steps to reproduce
1. open calendar app
2. click "New Subscription"
3. insert the baikal caldav URL (e.g. https://my-domain:port/html/dav.php/calendars/USER/CALENDAR/)

### Expected behaviour
I expect subscribe to caldav calendar

### Actual behaviour
If I select "New Subscription" in the calendar app and insert the baikal url (e.g. https://my-domain:port/html/dav.php/calendars/USER/CALENDAR/), I get the error message "The remote server did not give us access to the calendar (HTTP {401} error)".

Thunderbird, Android and Windows 10 Mobile are working fine with the URL

### Server configuration

**Operating system**:
Debian 8.9

**Web server:**
Nginx 1.12.1

**Database:**
MySQL

**PHP version:**
 7.0.24-1~dotdeb+8.1

**Server version:** (see your admin page)
Nextcloud 12.0.3

**Calendar version:** (see the apps page)
1.5.5

**Updated from an older installed version or fresh install:**
updated

**http://example.com/index.php/settings/integrity/failed**
No errors have been found

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - audioplayer: 2.1.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.2.4
  - drawio: 0.8.8
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.3
  - metadata: 0.5.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - polls: 0.7.3
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.0
  - ransomware_protection: 1.0.4
  - richdocuments: 1.12.35
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - comments
  - encryption
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - user_external
  - user_ldap

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "owncloud2",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "log_type": "owncloud",
        "log_authfailip": true,
        "mail_smtpmode": "php",
        "mail_smtpsecure": "tls",
        "mail_from_address": "nicht-antworten",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "578",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "theme": "",
        "loglevel": 1,
        "activity_expire_days": 30,
        "enable_previews": true,
        "htaccess.RewriteBase": "\/",
        "asset-pipeline.enabled": true,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\BMP",
            "OC\\Preview\\Font",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MP3",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\PNG",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Raw",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\TXT",
            "OC\\Preview\\XBitmap"
        ],
        "preview_max_filesize_image": 50,
        "updater.release.channel": "stable"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
webdav

### Client configuration
**Browser:**
any browser

**Operating system:**
Xubuntu 16.04

**CalDAV-clients:**
Thunderbird, DAVdroid,..

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
without entries
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment]
Subscriptions are only for Webcal.
CalDAV is (and never was) supported.
