### ISSUE TITLE
Events with overlapping time visually overlap

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#6281]
### Steps to reproduce

1. Create an event from 9-10 in calendar a
2. Create an event from 9-10 in calendar b

### Expected behavior

See both events next to each other

### Actual behaviour

See one of the two

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
This is critical. @GretaD @GVodyanov @hamza221 could one of you try to debug/bisect? It could be a regression of fullcalendar too.

**Comment by hamza221** [comment]
https://github.com/nextcloud/calendar/pull/6269/files
