### ISSUE TITLE
Anpassung der Kalender-Details

### ISSUE THREAD

**Issue by AnjuleAK** [nextcloud/calendar#6282]
### Is your feature request related to a problem? Please describe.

Für unsere Vereinsarbeit möchten wir den Kalender öffentlich stellen um eine Platzbelegung anzuzeigen. Leider gibt es Bei der Sichtbarkeit des Termins nur "beschäftigt". Weiterhin wäre es für unsere Organisation wichtig, dass wir die Räume, den Raum-Typ und die Ressourcen selbst benennen können. Dies ist momentan nicht möglich. Bei den Teilnehmern ist es nicht möglich Gruppen einzuladen, was sehr umständlich ist, wenn man mehrere Teilnehmer auf einmal hinzufügen möchte.

### Describe the solution you'd like

- Auswahl der Sichtbarkeit des Termins auf "belegt"
- Räume und Ressourcen selbst anlegen und verwalten
- Raum-Typen selbst anlegen und verwalten
- Gruppen als Teilnehmer (auch ohne E-Mail-Adresse) eintragen können

### Describe alternatives you've considered

Eine Alternative wäre eine Lösung außerhalb von Nextcloud.

### Additional context

Bisherige Lösungsvorschläge bezüglich Ressourcen im Calender sind nicht Ergebnis bringend. Eine einfache Umsetzung ohne Programmierkenntnisse ist uns wichtig.

**Comment by miaulalala** [comment]
Hi! As we are an international company, I'd please ask you to post in English. Thank you!
