### ISSUE TITLE
Recurring event start day don't show in calendar app.

### ISSUE THREAD

**Issue by section1** [nextcloud/calendar#6293]
### Steps to reproduce

1. Create a event starting on Tuesday and then Bi-weekly on Monday.

![bi-weekly](https://github.com/user-attachments/assets/5b73dded-9e08-4753-94e3-ad5f629058b8)

### Expected behavior

Event isn't display in the calendar app at start day (Tuesday 3)

### Actual behaviour

- Calendar app don't show the event in the start day but yes on the next recurrent days(Monday)
- Thunderbird and Mac calendar shows the event start day on Tuesday and then on Mondays

![bi-weekly2](https://github.com/user-attachments/assets/ccc322dc-4ac3-44ec-a595-235116aa21fe)

![bi-weekly3](https://github.com/user-attachments/assets/2a9467c8-0aa6-4fed-b3a5-ef77a36f354f)

### Calendar app version

4.7.16

### CalDAV-clients used

Thunderbird

### Browser

Firefox

### Client operating system

Ubuntu

### Server operating system

Ubuntu

### Web server

Apache

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
Can you export the event as an ICS for me please? You can do so in the three- dot menu on the event modal.

**Comment by section1** [comment]
Hi @miaulalala Thanks for the info about this, and you are right. I do some test in others calendars(including google)and do the same..so i close this case as resolved. thanks as always.
