### ISSUE TITLE
WebCal calendars cannot be seen (selected) by DAVDROID on mobile system

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/calendar#63]
I created a new calendar including web cal subscription (version 1.4)  of my favorite soccer team and deleting the "**old**" static one. After that, DAVDROID 1.3.1 reported "synchronization errors".  Ok, I deleted the appropriate account  and created a new one. After hitting finished, i does not show any of the "newly" created calendars including web cal subscription. There are not visible at all!

In this case I cannot thze schedule of my favorite soccer team!

regards, hitam4450

**Comment by tcitworld** [comment]
Webcal calendars are subscriptions that don't seem to be supported by DAVdroid. Use ICSdroid instead : https://davdroid.bitfire.at/faq/entry/subscribe-ics-file/

**Comment by rfc2822** [comment]
> Webcal calendars are subscriptions that don't seem to be supported by DAVdroid. 

These calendars should be reported as read-only CalDAV calendars by Nextclound, and then be detected by DAVdroid.

Do you know whether Nextcloud reports these subscriptions as calendars?

**Comment by georgehrke** [comment]
> Do you know whether Nextcloud reports these subscriptions as calendars?

No, it does not. It's not a calendar collection, but a subscription.

**Comment by georgehrke** [comment]
These calendars are also not cached on the server, only in the users browser.

**Comment by rfc2822** [comment]
> No, it does not. It's not a calendar collection, but a subscription.

Ah ok, so CalDAV clients can't see it of course.

**Comment by georgehrke** [comment]
They do, this calendar app is also only a caldav client.
The iOS and OS X calendar app will also display it properly.

**Comment by rfc2822** [comment]
> No, it does not. It's not a calendar collection, but a subscription.
/
> They do, this calendar app is also only a caldav client.

As fas as I know the CalDAV RFC, CalDAV clients can see only calendar collections. Have I missed something?

**Comment by georgehrke** [comment]
The subscribed collection is not an official part of the CalDAV standard. It's some extension by apple

**Comment by rfc2822** [comment]
I see, Nextcloud reports:

```
<d:response>
	<d:href>/nextcloud/remote.php/dav/calendars/test/my-subscription/</d:href>
	<d:propstat>
		<d:prop>
		<d:resourcetype>
			<d:collection/>
			<cs:subscribed/>
		</d:resourcetype>
[…]
```

So it's not a calendar collection and thus can't be listed (and synchronized) by DAVdroid.

Thanks for your help.

**Comment by untitaker** [comment]
Is there any reason why only Apple's non-standard extension is used? Couldn't the resource be described like this:

    <d:resourcetype>
        <d:collection/>
        <cs:subscribed/>
       <cs:calendar/>
    </d:resourcetype>

**Comment by georgehrke** [comment]
Because there is no official standard for it and Apples private standard is the most widely used one

**Comment by untitaker** [comment]
What is wrong with describing it as calendar?

**Comment by georgehrke** [comment]
The calendar will be empty. The entries are not stored on the server, but the browser loads them directly.

**Comment by untitaker** [comment]
Also contact birthdays are exposed as calendar but WebCAL subscriptions aren't. Both are described as subscriptions in the Calendar UI.

It wasn't clear to me that the calendar UI is not a pure CalDAV client.

**Comment by georgehrke** [comment]
Subscriptions are just read-only calendars. if you share a calendar with someone read-only it will also show up as subscription.

**Comment by untitaker** [comment]
I'm arguing that it is counter-intuitive to label two things as subscription when they have entirely different semantics in CalDAV.

**Comment by georgehrke** [comment]
Well, but the semantic here is calendars = read-write, subscriptions = readonly. I'm very open for a discussion to rename subscription to something else.

> when they have entirely different semantics in CalDAV.

Sorry, but ordinary users frankly don't give a shit about CalDAV.

**Comment by untitaker** [comment]
>Sorry, but ordinary users frankly don't give a shit about CalDAV. 

Users do give a shit as soon as they use that protocol to sync ownCloud with DAVDroid or any other non-Apple client. They have to give even more of a shit as soon as they notice that only parts of their subscriptions are discovered by standards-conformant CalDAV clients.

**Comment by georgehrke** [comment]
> They have to give even more of a shit as soon as they notice that only parts of their subscriptions are discovered by standards-conformant CalDAV clients.

We are considering making them available as ordinary caldav calendars, but this requires changes to the server-part. It's nothing we can do in a simple calendar release. Something like this would come in a bigger Nextcloud release.

**Comment by untitaker** [comment]
That's totally understandable.

**Comment by jancborchardt** [comment]
@georgehrke @untitaker so for making them available as ordinary CalDAV calendars, should there maybe be a separate planning issue opened? :)

**Comment by fredddii** [comment]
Any news on this? I would like my subscribed calendar feeds to show up on my mobile device.

**Comment by tcitworld** [comment]
For starters, see https://github.com/nextcloud/server/issues/1497

**Comment by leopoldfajtak** [comment]
Are there any news about this? Vdirsyncer still can not sync Nextcloud's WebCal subscriptions, and the workaround on the client side is janky at best.

**Comment by tcitworld** [comment]
@leopoldfajtak please open a new issue with details, as things have changed since then
