### ISSUE TITLE
Allow accept/decline button for secondary email address

### ISSUE THREAD

**Issue by gcolpart** [nextcloud/calendar#6304]
### Is your feature request related to a problem? Please describe.

If I add a secondary email address in my profile, please allow accept/decline button for calendar event where this email is attendee. Please allow also for IMIP email for a new event in "Mail".

**Comment by miaulalala** [comment]
Duplicate of https://github.com/nextcloud/server/issues/40891

**Comment by kesselb** [comment]
> Please allow also for IMIP email for a new event in "Mail".

https://github.com/nextcloud/mail/issues/11349
