### ISSUE TITLE
Sidebar disappears on every click when scrolling through months

### ISSUE THREAD

**Issue by reuterbal** [nextcloud/calendar#631]
### Steps to reproduce
1. Open calendar app on a mobile device (or generally in a window with small enough width to hide the sidebar)
2. Click the 3 parallel bars to display the sidebar
3. Click '<' or '>' to select a different month.

### Expected behaviour
Displayed month is changed and sidebar is still visible, so that I can continue clicking months ahead/back.

### Actual behaviour
Sidebar disappears after each click, thus making it really cumbersome, e.g., to check "Do I have time in three months"?

### General server configuration

**Operating system:** Linux stuart 3.13.0-129-generic #178-Ubuntu SMP Fri Aug 11 12:48:20 UTC 2017 x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 5.6.33

**PHP version:** 5.6.31-6+ubuntu14.04.1+deb.sury.org+1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - ereg
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - geoip
 - gettext
 - iconv
 - json
 - ldap
 - exif
 - mcrypt
 - mysql
 - mysqli
 - pdo_mysql
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - mhash
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** oC 9 -> Nc 10 -> Nc 11 -> Nc 12

**Where did you install Nextcloud from:**  GitHub

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_antivirus: 1.1.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.3
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - passman: 2.1.4
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - encryption
 - files_external
 - survey_client
 - user_external
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
    ],
    "datadirectory": "\/var\/www\/nextcloud\/data",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "appstore.experimental.enabled": true,
    "appstoreurl": "https:\/\/marketplace.owncloud.com\/api\/v0",
    "maintenance": false,
    "updatechecker": true,
    "loglevel": 3,
    "singleuser": false,
    "theme": "",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "htaccess.RewriteBase": "\/",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "updater.release.channel": "stable",
    "mysql.utf8mb4": true
}
```
</details>

<details>
        <summary>LDAP config</summary>
irrelevant
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Operating system:** Ubuntu 16.04.3

### Logs

<details>
        <summary>Web server error log</summary>

```
<empty>
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
<empty>
```
</details>

<details>
        <summary>Browser log</summary>

```
<empty>
```
</details>

**Comment by georgehrke** [comment]
@jancborchardt This is related to the snap.js library you introduced a while ago. 
Do you have any clue how to fix this?

**Comment by jancborchardt** [comment]
I think there's a way to prevent clicks from bubbling up, maybe stopPropagation? Cause on other buttons like the day itself, or the navigation entries of other apps, you want the app-navigation to hide after click.

cc @nextcloud/javascript though

**Comment by miaulalala** [comment]
Can't reproduce
