### ISSUE TITLE
Calendar stuck, if multiple xhr

### ISSUE THREAD

**Issue by 1ucay** [nextcloud/calendar#633]
### Steps to reproduce
1. add multiple ical to calendar with multiple items, for example 2 items each day, I have 9 icals + 5 subscriptions
2. switch to month view
3. clicking fast to next month arrow, for example I want show january of 2021

### Expected behaviour
xhr loading should stop, if is not actual for view

### Actual behaviour
server overload with ajax request, which lead for stuck of mysql server (for me)

### General server configuration

**Operating system:** Linux site.com 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64

**Web server:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.1.9 SVN/1.7.14 mod_perl/2.0.10 Perl/v5.16.3 (cgi-fcgi)

**Database:** mysql 5.5.56

**PHP version:** 7.1.9
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - pcntl
 - readline
 - Reflection
 - SPL
 - session
 - standard
 - cgi-fcgi
 - bz2
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - gmp
 - iconv
 - igbinary
 - imagick
 - intl
 - json
 - exif
 - mcrypt
 - mysqli
 - PDO
 - pdo_mysql
 - pdo_sqlite
 - Phar
 - posix
 - redis
 - shmop
 - SimpleXML
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - xml
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - memcached
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 Build:2017-09-19T21:13:36+00:00 343a69569db0aec48bc99fd3b23da08a7791d82b - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 12

**Where did you install Nextcloud from:**  offical

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**
Webdav

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - announcementcenter: 3.1.0
 - apporder: 0.4.0
 - audioplayer: 2.1.0
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - checksum: 0.3.5
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - deck: 0.2.4
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_clipboard: 0.6.4
 - files_external: 1.3.0
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.1.1
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - locationtracker: 0.1.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.3
 - metadata: 0.5.0
 - music: 0.5.3
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - nextnote: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocdownloader: 1.5.4
 - ocsms: 1.12.1
 - ownnote: 1.08
 - ownpad: 0.5.10
 - passman: 2.1.4
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - qownnotesapi: 17.5.0
 - radio: 0.6.0
 - ransomware_protection: 1.0.4
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - theming_customcss: 1.0.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - weather: 1.5.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - dashboard
 - documents
 - encryption
 - keeweb
 - ojsxc
 - spreed
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "oczllki6dxna",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "site.com"
    ],
    "datadirectory": "\/home\/test\/www\/data",
    "overwrite.cli.url": "https:\/\/site.com",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Prague",
    "installed": true,
    "updater.release.channel": "daily",
    "maintenance": false,
    "theme": "",
    "debug": false,
    "loglevel": 2,
    "mail_from_address": "test",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "site.com",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "mysql.utf8mb4": true,
    "knowledgebaseenabled": false,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3236.0 Safari/537.36

**Operating system:** CentOS

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by tcitworld** [comment]
Please post your browser and server logs, but I'm not sure this issue belongs here.

**Comment by georgehrke** [comment]
No feedback for a month now, closing ...
