### ISSUE TITLE
Shared calendars should allow adding attendees even if the calendar is not yours (make it a selectable option!)

### ISSUE THREAD

**Issue by nano13** [nextcloud/calendar#6363]
### Is your feature request related to a problem? Please describe.

The "fix" https://github.com/nextcloud/calendar/issues/5450 has broken a very important functionality. See the comments there for more details!

### Describe the solution you'd like

Please add this feature back by implementing it properly:

- make this an option per calendar to decide if the owner wants to allow not just editing, but also others to invite people
- if other users are allowed to invite, of course that needs to trigger the invited people to get an actual invitation
- the invitation should show who actually invited them and also whom the cal belongs to

**Comment by kesselb** [comment]
https://github.com/nextcloud/calendar/issues/5674#issuecomment-2271896247
