### ISSUE TITLE
Full page detailed event

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#6378]
### Is your feature request related to a problem? Please describe.

The sidebar editor is crammed and there is not much space for the input fields etc.

### Describe the solution you'd like

It would be nice to have replace the whole grid with a full screen editor. Kind of like Google does.

The sidebar could be reused to show additional fields next to the core details of the event.

There are some challenges though:
1. This would make it impossible to see other events while editing which is currently possible.

**Google Calendar:** (sorry for the German screenshot)
![grafik](https://github.com/user-attachments/assets/3df044e0-a153-45e8-ab2d-21978dbf9fc5)

### Describe alternatives you've considered

Keep it as is.

**Comment by GVodyanov** [comment]
Linking this https://github.com/nextcloud/calendar/issues/5513 as it's a duplicate

**Comment by ChristophWurst** [comment]
Closing as duplicate
