### ISSUE TITLE
Feature Request: Prefix for Privacy-Class

### ISSUE THREAD

**Issue by novij** [nextcloud/calendar#638]
There are some calendar apps which don't provide a privacy setting for events (public, confidential, private). Can you add some prefixes (e.g. P: or C:) as workaround?

Example:
1.) my public event
2.) C:this is a confidential event
3.) P:nobody else can see this event

I've got the idea from this site:
http://coeno.com/offentliche-private-und-vertrauliche-kalenderereignisse-und-wie-man-sie-richtig-nutzt/

**Comment by georgehrke** [comment]
I'm personally not a big fan of this idea. The nextcloud server shall never alter calendar data in my humble opinion.

cc @tcitworld @jancborchardt

**Comment by tcitworld** [comment]
I have the same feeling.
As a workaround, you can work with calendar colors.

**Comment by jancborchardt** [comment]
Agree with @georgehrke and @tcitworld here. This should be fixed at the other calendar apps in question instead.

**Comment by novij** [comment]
I understand your argument about not altering (meta) data and I think it's true, but I don't know another way. Different calendar colors doesn't prevent others from reading event title and body.

The calendar app I'm talking about is the default iOS calendar app. I don't think Apple will listen to me and add this option in the near future :'-(

Maybe you can add this feature and turn it off by default? Or maybe add a sharing option that forces all events shown as confidential (busy). Then it could be done by two calendars - one public and one confidential where others only see "busy".

**Comment by georgehrke** [comment]
> Or maybe add a sharing option that forces all events shown as confidential (busy).

This is related to #39 
Is that what u are looking for? :)

**Comment by novij** [comment]
I'm sorry, that is not exactly what I was looking for. But you're right, it would solve a part of the issue.

But there is still an option missing to set the calendar default or sometimes called server default ("Kalender Standard").
![screenshot_20171019-183018](https://user-images.githubusercontent.com/111357/31815060-ddd6d744-b58b-11e7-8a47-cf6e9421edcb.png)

I'm also in contact with the davdroid developers about this whole issue:
https://forums.bitfire.at/topic/1579/setting-for-calendar-item-privacy-class/7

It is really complicated, because it affects all three parties - client calendar app, caldav connector and caldav server.

And I opened a feature request for the google android calendar and for the iOS calendar to add all three privacy options to events, but at the moment these requests are not online available.

**Comment by georgehrke** [comment]
I'm sorry, I don't have an account in the bitfire forum. 

Do you mind asking them what exactly "server default" is and how it is defined on the server?

**Comment by novij** [comment]
I've got a reply from the Davdroid developer. There was a missunderstanding on my side about the "server default" - as far as i understand, if needed, it has to be implemented by them. I'm sorry for this.

**Comment by georgehrke** [comment]
Yes, I just read their reply.

Server default is very confusing name in that case.

**Comment by georgehrke** [comment]
I hope you don't mind if i go ahead and close this issue.

It's a very special use-case and every new feature means more code we have to maintain and test with every release. You are the first person to request this feature, so demand seems to be rather low.
