### ISSUE TITLE
Missing option for update frequency of web cal subscription

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/calendar#64]
I created a web cal of my favorite soccer team on NC 10.0 server And I would love to see a selectable update frequency in the calendar app, e.g. hourl, daily, weekly, monthly, etc., because i link this calendar by DAVDROID with my mobile systems (cell phone & tablet). Using a possible browser caching for updating the webcal subscription  is no solution, because I do not want to update the calendar first in the browser and in the second stage by DAVDROID in my mobile system. This totally cumbersome and "user unfriendly".

regards, hitam4450

**Comment by tcitworld** [comment]
What's the difference with https://github.com/nextcloud/calendar/issues/60 ? Opening a new issue won't change our opinion on this.

**Comment by georgehrke** [comment]
Webcal calendars are not cached on the caldav server. Unless DavDroid has support for subscriptions/webcal on its own, you won't see it there.

**Comment by rasos** [comment]
Does that mean that subscribed ics calendars are not regularly refreshed?

**Comment by georgehrke** [comment]
@rasos subscribed ics calendars are cached for 2 hours.

**Comment by deepdivingspearo** [comment]
> ics calendars are cached for 2 hours.

Does it cache in the browser for all external subscriptions? I'm struggling with out of date info for a subscription (up to date in the feed, but not in Nextcloud). It's a calendar feed from Freedcamp (https://freedcamp.com/).

I attempted a full clear of my browser cache and forced a refresh but the old data was still there. Just trying to find a work around.
