### ISSUE TITLE
Sidebar editor repetition count for "days" is not put on separate line

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#6429]
### Steps to reproduce

Edit an event with a screen size lower than 960px

![Image](https://github.com/user-attachments/assets/d4026397-ec0e-4269-b8b3-35b367346083)

### Expected behavior

The form field is put on a separate line

### Actual behaviour

The form field breaks the sidebar editor

### Calendar app version

5.0.2 (main)

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by keremsemiz** [comment]
I've fixed this issue! Here is the PR and more details:
https://github.com/nextcloud/calendar/pull/6551
![Image](https://github.com/user-attachments/assets/a5ba7a3a-8298-4778-ac94-751fd349079e)
