### ISSUE TITLE
Add option to change the start of the week

### ISSUE THREAD

**Issue by NotAFile** [nextcloud/calendar#645]
### Steps to reproduce
1. Live in culture where weeks start on Monday
2. Create event on Monday
3. Be confused because you now think it's on Tuesday

### Expected behaviour
NC automagically reads my mind and detects I want the week to start on Monday (a toggle switch might be easier to implement)

### Actual behaviour
Week starts on Sunday and my brain gets confused

**Calendar version:** 1.5.6

**Comment by georgehrke** [comment]
@NotAFile you got an answer in irc about this

**Comment by NotAFile** [comment]
It would be nice to document the answer here too

As I understand it, more detailed locale settings are going to be integrated into the nexcloud core in the future, which would make adding this feature to the calendar redundant.

**Comment by georgehrke** [comment]
Right now, the locale settings are determined based on your language.
If you use US English, u will have MM/DD/YYYY and the week start on Sunday.
If you use german, u will have DD.MM.YYYY and the week start on Monday.

In the future, there will be a dedicated locale option in your personal settings.
You will be able to select english as a language but german as a locale.
Hence you would have an us english GUI with DD.MM.YYYY and the week start on Monday.

Issue: https://github.com/nextcloud/server/issues/1781

**Comment by cave-felem** [comment]
I think the starting of the week should be independent of the locale (which is a geographical description). What is considered the first day of the week depends on culture and religion rather (cf. e.g. https://en.wikipedia.org/wiki/Week).

For example, for many people in Europe or the Middle East Sunday is the first day of the week and I would prefer to leave the decision on what is considered as the first weekday to the end user. Many calendar services actually leave this decision to the user - e.g. Google allows to select Saturday, Sunday or Monday as first day (irrespective of language, locale, etc.). Microsoft does it similarly to offer this kind of flexibility to the end-user.
