### ISSUE TITLE
Add an Export for Calendar to CSV

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/calendar#646]
This allows us to open and edit this Data in Excel or Import it in other software.

It should be possible to create a config file which contain the variable from nextcloud that could be filled with own title to be able to create compatibility with other tools. And Provide an enhanced Config file to allow other easily create their own config file e.g. :

```
$CONFIG = array (
  'separator' => '","',
  'codepage' => 'UTF-8'
#'codepage' => 'ASCII'
# How-to formate the codepage: http://php.net/manual/de/mbstring.supported-encodings.php
  'place' => 'Ort',
  'private' => 'Privat',
  'datetype' => 'UNIX',
#'datetype' => 'YY"-"MM"-"DD',
#'datetype' => 'mm "/" dd "/" y', 
# How-to formate the date: http://php.net/manual/de/datetime.formats.date.php
  'subject' => 'Betreff'
  'rememberdate' => 'Erinnerungam'
  'remembertime' => 'Erinnerungum'
...
);
```

**Comment by georgehrke** [comment]
Just look for an ics to css converter online. This is really nothing to be implemented in nextcloud.

**Comment by tcitworld** [comment]
It could be done without too much work with a 3rd party app inside Nextcloud though. But nothing to do here :)
