### ISSUE TITLE
External caldav sync

### ISSUE THREAD

**Issue by DagNygren** [nextcloud/calendar#6481]
### Is your feature request related to a problem? Please describe.

Having a possibility of adding and syncing to an external "Main" calendar would be really useful as many users probably have workplace calendars that should be included.

**Comment by miaulalala** [comment]
You can already add a subscription calendar. Does that not work for your purposes? Can you elaborate on what you mean by "Main" calendar?

**Comment by DagNygren** [comment]
I mean that the nextcloud calender would be a fullfledged calendar client and that it would be nice to be able to edit and add entries into the remote calendar through the Nextcloud interface. Now it seems to be a readonly view only of the subscription calendars.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/server/issues/1440

Thank you for your report @DagNygren
