### ISSUE TITLE
"sync now" button

### ISSUE THREAD

**Issue by NotAFile** [nextcloud/calendar#649]
Currently when creating an event you might have to wait up to two hours for that event to appear in NC.

Many calendar apps solve this issue with a "sync now" button that you can press to fetch the current state of all calendars, however NC-calendar has no such button.

![screenshot from 2017-11-02 12-36-09](https://user-images.githubusercontent.com/5447747/32324196-db7b1732-bfca-11e7-8bd5-4baf69192ec7.png)
![photo_2017-11-02_12-40-12](https://user-images.githubusercontent.com/5447747/32324255-10f1730c-bfcb-11e7-8b81-18f1a7ed6c03.jpg)
![photo_2017-11-02_12-40-18](https://user-images.githubusercontent.com/5447747/32324258-15296722-bfcb-11e7-8ab5-83709fdf6ffd.jpg)

**Comment by rasos** [comment]
A new event entered on a mobile device and synced via CalDAV should be made visible within seconds. Usually, sync clients push immediately, so it seems to be a matter of triggering a reload of the calendar view.

**Comment by oresch** [comment]
@georgehrke, @NotAFile  in my opinion this issue is more a user's client issue than one of the NC calendar app. So mobile apps or _lightning_ will regularly sync - or by forcing them. The problem @NotAFile mentioned is in my opinion more on the 3rd party client side.
I think this issue is not related to the NC calendar app and shall be closed, sohouldn't it?

**Comment by NotAFile** [comment]
This has been a few years ago, so I don't remember exactly. IIRC, my problem was with the nextcloud app and shared calendars that I had added.

**Comment by oresch** [comment]
@georgehrk so if @NotAFile agrees you shall close this issue. Seams old problem and not further requiered?!

**Comment by NotAFile** [comment]
I doubt this is fixed but I have not used the nextcloud calendar web-app for years.

**Comment by SebastianKrupinski** [comment]
This should no longer be an issue as the calendar not automatically refreshes every 30 seconds. PR https://github.com/nextcloud/calendar/pull/6152
