### ISSUE TITLE
appointments in Buenos Aires creates event with incorrect timezone shift

### ISSUE THREAD

**Issue by anarcat** [nextcloud/calendar#6492]
### Steps to reproduce

1. send your appointment invite link to a friend
2. friend opens link
3. click on the timezone, pick "America/Buenos Aires"
4. pick a time (say `10:00`)
5. confirm the appointment on both ends

### Expected behavior

The event should be created with the proper time, 10:00:00-0300, and shown correctly in the calendar.

### Actual behaviour

It's unclear what's actually happening here. It *seems* like the event is created with the proper time: if I click on the event, it says it's "10:00" with the "America/Buenos Aires" timezone. But when *shown* in the calendar (in *my* timezone, which is America/New York), it's actually  off by three hours. Instead of showing up at 8:00 locally, it shows up at 5:00.

Here's a screenshot showing an event created by the appointment system, and another created by hand in the calendar:

![Image](https://github.com/user-attachments/assets/41ab8cb2-7304-4504-bae7-efa68f78b6c6)

The "meet with me" one is showing up as 5:00 local (10:00UTC) instead of the correct one, below, which shows up as 8:00 local (13:00UTC).

I haven't ran more tests, but it looks like the appointment system might be totally disregarding the timezone picked by the user and just using UTC? But then if that was the case, why does the event show up as 10:00 in BA as a timezone? Here's what the edit dialog looks like:

![Image](https://github.com/user-attachments/assets/c758a24f-776d-4acd-98ad-4ab94c72131d)

### Calendar app version

5.0.1

### CalDAV-clients used

N/A

### Browser

Firefox 128.4.0esr

### Client operating system

Debian Linux

### Server operating system

Debian Linux

### Web server

Other

### Database engine version

Other

### PHP engine version

Other

### Nextcloud version

30.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text

```

### Nextcloud configuration

```Text

```

### Web server error log

```Text

```

### Log file

```Text

```

### Browser log

```Text

```

### Additional info

I only have admin access to nextcloud and do not operate the server. I do not feel like logs would be useful to diagnose this anyways, but let me know if we need to dig those out with the service provider.

This might be similar or related with https://github.com/nextcloud/calendar/issues/6407 and https://github.com/nextcloud/calendar/issues/5873

**Comment by sbe-arg** [comment]
I think I have the same problem. And might have opened a duplicate https://github.com/nextcloud/calendar/issues/6493

**Comment by SebastianKrupinski** [comment]
Resolved: https://github.com/nextcloud/calendar/pull/6478
