### ISSUE TITLE
Appointments time diplayed incorrectly when booked from a different timezone

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud/calendar#6493]
### Steps to reproduce

Set your calendar to your timezone in my case Pacific/Auckland

Create an appointments calendar.

Register an appointment from another timeone such as Asia/Singapore.
Appoitnment time 8am Singapore time.

The appointment is accepted by the server.

In my calendar shows the Appointment is set at 9pm when the diff between Singapore and Auckland is 5hs. It should show the appointment as 12pm.

Is like if is assuming Singapore is in UTC

Oddly is that the caldav sync also shows the incorrect hour. But I get a notification email at the actual time of the event.

I can consistently replicate this issue with different timezones.

Server time is correct.
Server logtimezone is also correct.

An example in the screenshots
Meeting for 4am Singapore time but shows as 5pm in UI and caldav clients. Notif shows correctly at 9am my time.

![Image](https://github.com/user-attachments/assets/38cffb04-716c-4a7e-b97a-4b83f7244309)
![Image](https://github.com/user-attachments/assets/9639b518-fab8-4ffc-bc6d-31fead6d17ab)
![Image](https://github.com/user-attachments/assets/ecfd9066-8752-4b11-b609-4712cb3cea84)

### Expected behavior

caldav and ui show the right times so you can short your schedules properly

### Actual behaviour

makes impossible to knows accurately when your appointments are unless you live by the last minute reminder to attend the events.

### CalDAV-clients used

Thuderbird + DAVx5

### Browser

all

### Client operating system

all

### Server operating system

Ubuntu

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

snap 30.0.2

### Updated from an older installed version or fresh install

None

### List of activated apps

```Text

```

### Nextcloud configuration

```Text

```

### Web server error log

```Text

```

### Log file

```Text

```

### Browser log

```Text

```

**Comment by sbe-arg** [comment]
The bookslot does not validate the Timezone of the calendar where the appointment is gonna be added.

https://github.com/nextcloud/calendar/blob/main/lib/Controller/BookingController.php#L155-L200

Something like this:

The start and end timestamps, originally in UTC, are first converted to the booking user's time zone ($userTimeZone). Then, they are converted to the calendar's time zone ($calendarTimeZone)

```
public function bookSlot(
	int $appointmentConfigId,
	int $start,
	int $end,
	string $displayName,
	string $email,
	string $description,
	string $timeZone
): JsonResponse {
	// Validate email address
	if (!$this->mailer->validateMailAddress($email)) {
		return JsonResponse::fail('Invalid email address', Http::STATUS_UNPROCESSABLE_ENTITY);
	}

	// Ensure start time is before end time
	if ($start > $end) {
		return JsonResponse::fail('Invalid time range', Http::STATUS_UNPROCESSABLE_ENTITY);
	}

	// Get the appointment configuration to retrieve the calendar time zone
	try {
		$config = $this->appointmentConfigService->findById($appointmentConfigId);
		$calendarTimeZone = new DateTimeZone($config->getTimeZone());
	} catch (ServiceException $e) {
		$this->logger->error('No appointment config found for id ' . $appointmentConfigId, ['exception' => $e]);
		return JsonResponse::fail(null, Http::STATUS_NOT_FOUND);
	}

	// Convert start and end times from the booking time zone to the calendar time zone
	try {
		$userTimeZone = new DateTimeZone($timeZone);

		// Convert start time
		$startTime = (new DateTimeImmutable('@' . $start))->setTimezone($userTimeZone);
		$startTimeInCalendarTz = $startTime->setTimezone($calendarTimeZone)->getTimestamp();

		// Convert end time
		$endTime = (new DateTimeImmutable('@' . $end))->setTimezone($userTimeZone);
		$endTimeInCalendarTz = $endTime->setTimezone($calendarTimeZone)->getTimestamp();

		// Book the slot in calendar's time zone
		$booking = $this->bookingService->book(
			$config,
			$startTimeInCalendarTz,
			$endTimeInCalendarTz,
			$calendarTimeZone->getName(),
			$displayName,
			$email,
			$description
		);
	} catch (Exception $e) {
		$this->logger->error('Time zone conversion error', ['exception' => $e]);
		return JsonResponse::fail('Time zone conversion failed', Http::STATUS_INTERNAL_SERVER_ERROR);
	}

	return JsonResponse::success();
}
```

**Comment by SebastianKrupinski** [comment]
Confirmed.

This just happened to myself.

Calendar is set to 'America/Toronto' time zone.

Manually created calendar event in 'America/Los_Angeles' time zone for 14.30

Event shows on calendar at 12.00 but should be 17.30.

Event export shows correct time zone.
 
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//IDN nextcloud.com//Calendar app 5.0.1//EN
CALSCALE:GREGORIAN

BEGIN:VTIMEZONE
TZID:America/Los_Angeles

BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
TZNAME:PDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT

BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
TZNAME:PST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD

END:VTIMEZONE

BEGIN:VEVENT
CREATED:20241115T021729Z
DTSTAMP:20241115T022245Z
LAST-MODIFIED:20241115T022245Z
SEQUENCE:2
UID:bfd37d0d-7acf-415d-92ca-c34b493ab491
DTSTART;TZID=America/Los_Angeles:20241114T143000
DTEND;TZID=America/Los_Angeles:20241115T153000
STATUS:CONFIRMED
SUMMARY:<redacted>
LOCATION:<redacted>
ATTENDEE;CN=<redacted>;CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;RO
 LE=REQ-PARTICIPANT;RSVP=TRUE;SCHEDULE-STATUS=1.1:mailto:<redacted>
ATTENDEE;CN=<redacted>;CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTIO
 N;ROLE=REQ-PARTICIPANT;RSVP=TRUE;SCHEDULE-STATUS=1.1:mailto:<redacted>
ORGANIZER;CN=Sebastian Krupinski:mailto:<redacted>
END:VEVENT

END:VCALENDAR
```

**Comment by SebastianKrupinski** [comment]
Hi @sbe-arg 

This issue seems a lot like the issue that was recently fixed. https://github.com/nextcloud/calendar/pull/6478

The Singapore time zone is a static time zone, meaning no day light savings transitions.

Can you export the event and post it.

**Comment by SebastianKrupinski** [comment]
Resolved: https://github.com/nextcloud/calendar/pull/6478
