### ISSUE TITLE
Style events from invites differently if they need my action

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#6497]
### Is your feature request related to a problem? Please describe.

As a Nextcloud user I have my own events and I get invited to meetings. When I open up my calendar I see all the meetings in my calendar already, because the backend copies them there. However, I might forget to actually respond to the invite, leaving the organizer hanging.

### Describe the solution you'd like

Show events visually different when the attendee status is *NEEDS-ACTION* for me. Once I accept or decline, the event will change to "normal" appearance.

Google shows these events with stripes.

### Describe alternatives you've considered

N/a

### Additional context

N/a

**Comment by jancborchardt** [comment]
Sounds good to me and seems like a possible quick win and closing the gap of expectation. :)

FYI @nimishavijay

**Comment by ChristophWurst** [comment]
> Google shows these events with stripes.

Gnome Evolution shows the titles in bold.

@nimishavijay any preference or other suggestion?

**Comment by nimishavijay** [comment]
@ChristophWurst I'd suggest an outlined event instead of filled in, as discussed in #3869

**Comment by ChristophWurst** [comment]
Whoops, I hadn't realized this was a duplicate.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/3869
