### ISSUE TITLE
Nextcloud ical subscription not working with an ical link that looks correct

### ISSUE THREAD

**Issue by Scoppeniche** [nextcloud/calendar#650]
Hi there,
My coop is using Cobot.me which is a tool to manage coworking space. Cobot is providing an ical link to follow events organised in our space. We are having trouble with this ical link provided with the cobot calendar. It's working correctly in Thunderbird for instance but not in Nextcloud calendar. 
Only the first event of the .ics file is appearing. Other ical links from different sources are working correctly in Nextcloud calendar, but not the Cobot calendar one. Cobot support is telling me they use a standard Ruby library to generate the ical links (ri_cal gem) 

### Steps to reproduce
1. subscribe to the remote calendar  https://la-coop.cobot.me/bookings/feed.ics?key=2f04ed4c937afafef6dcdf74f6e00daa 
2. try to see if you see more than the next coming event
3. ...

### General server configuration

**Operating system:** Linux la-Péniche 3.14.53-grsec-paas-3117c5c #1 SMP PREEMPT Tue Mar 29 19:14:05 UTC 2016 x86_64

**Web server:** Apache/2.4.20 (fpm-fcgi)

**Database:** sqlite3 3.8.7

**PHP version:** 5.6.22-0+deb8u1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - ereg
 - libxml
 - openssl
 - pcre
 - zlib
 - bcmath
 - bz2
 - calendar
 - ctype
 - dba
 - dom
 - hash
 - fileinfo
 - filter
 - ftp
 - gettext
 - SPL
 - iconv
 - mbstring
 - session
 - posix
 - Reflection
 - standard
 - shmop
 - SimpleXML
 - soap
 - sockets
 - Phar
 - exif
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xml
 - xmlreader
 - xmlwriter
 - zip
 - cgi-fcgi
 - PDO
 - apcu
 - curl
 - gd
 - gmp
 - imagick
 - imap
 - intl
 - json
 - ldap
 - mcrypt
 - mongo
 - mssql
 - mysql
 - mysqli
 - pdo_dblib
 - pdo_mysql
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - sasl
 - sqlite3
 - ssh2
 - tidy
 - xmlrpc
 - xsl
 - mhash
 - apc
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**  ???

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - calendar: 1.5.6
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - bruteforcesettings
 - encryption
 - files_external
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "oc9zos0l3gm1",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.la-peniche.fr"
    ],
    "datadirectory": "\/srv\/data\/web\/vhosts\/cloud.la-peniche.fr\/htdocs\/data",
    "overwrite.cli.url": "http:\/\/cloud.la-peniche.fr",
    "dbtype": "sqlite3",
    "version": "12.0.3.3",
    "dbname": "Nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "logtimezone": "UTC",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Operating system:** Windows 7

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by georgehrke** [comment]
> Cobot support is telling me they use a standard Ruby library to generate the ical links (ri_cal gem)

@Scoppeniche The events don't even contain a UID, which is mandatory.
```
BEGIN:VEVENT
DTEND;TZID=Europe/Paris;VALUE=DATE-TIME:20171009T213000
DTSTART;TZID=Europe/Paris;VALUE=DATE-TIME:20171009T183000
SUMMARY:Soirée OpenStreetMap
LOCATION:Coworking-Infolab
END:VEVENT
```

Please tell Cobot support to fix their webcal feed
