### ISSUE TITLE
Calendar partially imported, many faillures

### ISSUE THREAD

**Issue by Valicanto** [nextcloud/calendar#652]
I exported a calendar with almost 3000 events from Nextcloud 9.0.53. I then did a clean install of Nextcloud 12.0.3 on my BananaPi with Ubuntu 14.04 and Nginx. Everytime i try to import the ICS file I get the message ""Partially imported, 2000 failures)" (Everytime it is a different amount of failures, but always around 2000.)

Console in browser says: NetworkError: 502 Bad Gateway
/var/log/php7.0-fpm.log says: WARNING: [pool www] server reached pm.max_children setting (5), consider raising it.

I raised:
pm.max_children = 5000
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 30
pm.max_requests = 5000

I still get error messages like:
WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 188 total children

Has this anything to do with the parallel processes discussed in the [this](https://github.com/nextcloud/calendar/issues/445) topic? If yes, which settings in which files do I have to adjust?

**Comment by georgehrke** [comment]
> Has this anything to do with the parallel processes discussed in the this topic?

I will be able to tell you when you post the javascript log as requested in the issue template

**Comment by georgehrke** [comment]
dup of #445 

please ask configuration questions on the nextcloud forum: https://help.nextcloud.com

**Comment by Valicanto** [comment]
Thank you georgehrke. I will ask it on the nextcloud forum. But to be sure, do you think it is possible to import 3000 events in a calendar with the right configuration? Or is it due to amount of parallel processes that it will likely fail. I have seen several topics about this issue, and none of the posters found a solution.
(Please forgive my lack of knowledge about this topic :))

**Comment by georgehrke** [comment]
It is possible, already imported more than 3000 events :) 

We will definitely fix #445 though and limit the number of concurrent import requests, so import also works as expected without an admin having to apply a special configuration.

**Comment by saidaspen** [comment]
I don't get it. How do I work around this? I don't follow. 
I am using Apache.
