### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by jabiertxof** [nextcloud/calendar#653]
Is posibol handle sub-calendars, main calendar show all childs calendars events and each children his own?

**Comment by georgehrke** [comment]
Can you please explain your feature request better?  I don't understand what you mean.

What are sub calendars? What are chiuldren?

**Comment by jabiertxof** [comment]
Hi @georgehrke  basicaly one subcalendar is a children of main calendar. By this way you can have a structure like:
Zone A
---Room A
---Room B
Zone B:
---Room Z
---Room X
---Room Y
And to better
Zone C:
---Room A
--------Printer A
--------Printer B
---Room B
--------PC 1
The calendar is handled by "Zone" sections showing all active children events
Children events show only his events (For example filtering his zone by a tag or two tags in "Zone C" example)

I hope now is more clear. Thanks for the fast response!

**Comment by georgehrke** [comment]
So you basically want to be able to group calendars? 

What's the use-case?

**Comment by jabiertxof** [comment]
Reduce by colapsing and organization. Im in a bussines who share his resources and want to have it organized for easy access to his data. I know there is resources ICS spec, in the schedule part of jcalendar.js, allow grouping

**Comment by georgehrke** [comment]
So you basically want to be able to manage resources like rooms printers and beamers?

**Comment by jabiertxof** [comment]
yes, also workers time

**Comment by georgehrke** [comment]
then you are basically looking for freebusy support, to manage availability of resources and humans

**Comment by georgehrke** [comment]
#39
