### ISSUE TITLE
Tasks not opened from calendar

### ISSUE THREAD

**Issue by manfredu** [nextcloud/calendar#6533]
### Steps to reproduce

1. Click on a task display on a calendar
2. The task app opens, but does not open the selected task

The not working link called from calender has the following format:
`https://mynextcloud.tld/apps/tasks/calendars/myuser#/calendars/myuser/tasks/task-id.ics`

When I change this to the following the task opens
`https://mynextcloud.tld/apps/tasks/calendars/myuser/tasks/task-id.ics`

### Expected behavior

When I click on a task show in calendar, the task should be opened in the task app.

### Actual behaviour

The tasks app is opend without any task selected

### Calendar app version

5.0.6

### CalDAV-clients used

-

### Browser

Firefox 132.0.2

### Client operating system

Windows 10

### Server operating system

TrueNAS Core / FreeBSD 13.3

### Web server

Other

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

30.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text

```

### Nextcloud configuration

```Text

```

### Web server error log

```Text

```

### Log file

```Text

```

### Browser log

```Text

```

### Additional info

This used to work and stopped working with an update not long ago. But I can't say which exaxtly, because I only npticed it now.

**Comment by manfredu** [comment]
Tasks app 0.16.1

**Comment by manfredu** [comment]
See also [tasks issue 2733](https://github.com/nextcloud/tasks/issues/2733).

**Comment by raimund-schluessler** [comment]
Yes, with Tasks 0.16.0 the URLs for the Tasks app changed. They now come without the `#`.
In the Calendar app it needs to be adjusted here:
https://github.com/nextcloud/calendar/blob/fefe778528180a78c76b364f42decf66dd8f64b0/src/fullcalendar/interaction/eventClick.js#L112

**Comment by raimund-schluessler** [comment]
Related to https://github.com/nextcloud/server/issues/49473.
