### ISSUE TITLE
Can't run make command

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/calendar#654]
### Steps to reproduce
1. cd to the root of project
2. run ``make``

### Expected behaviour
 Command should install all dependencies, and build project
### Actual behaviour 
Terminal outputs error and exits  

This command is run on git bash terminal on windows  

```
$ make
make yarn
make[1]: Entering directory `D:/calendar'
cd js && /c/Program Files (x86)/Yarn/bin/yarn run build
/usr/bin/sh: -c: line 0: syntax error near unexpected token `('
/usr/bin/sh: -c: line 0: `cd js && /c/Program Files (x86)/Yarn/bin/yarn run build'
make[1]: *** [yarn] Error 1
make[1]: Leaving directory `D:/calendar'
make: *** [build] Error 2
```
When ran on windows cmd, error output differs.  
```
$make

The system cannot find the path specified.
'expr' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
make yarn
The system cannot find the path specified.
'expr' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
The system cannot find the path specified.
make[1]: Entering directory `D:/calendar'
cd js &&  run build
'run' is not recognized as an internal or external command,
operable program or batch file.
make[1]: *** [yarn] Error 1
make[1]: Leaving directory `D:/calendar'
make: *** [build] Error 2
```

### Server configuration

**Operating system**: Windows 10

**Calendar version:** 1.5.6

Both yarn and node is installed on my system. I cant confirm that by running ``node -v`` and ``yarn``.

Is there any wrong step taken while trying to build the project?

**Comment by georgehrke** [comment]
Building on windows is not supported. Please get a linux VM / Docker to build the calendar app

**Comment by mehrdaad** [comment]
@georgehrke oh thanks.

**Comment by tcitworld** [comment]
There's also the Linux Subsystem for Windows that might get handy.

**Comment by mehrdaad** [comment]
@tcitworld sorry didn't get what you mean. can explain further?

**Comment by mehrdaad** [comment]
@georgehrke maybe tell that in the README?

**Comment by tcitworld** [comment]
https://msdn.microsoft.com/fr-fr/commandline/wsl/about

**Comment by mehrdaad** [comment]
@tcitworld perfect! didn't know about it. tnx
