### ISSUE TITLE
Imported ICS Calendar only visible for Calendar owner

### ISSUE THREAD

**Issue by swissbyte** [nextcloud/calendar#655]
### Steps to reproduce
1. Log in into nextcloud
2. Create a shared calendar 
3. Import an ics Calendar

### Expected behaviour
I expect that everyone who the calendar is shared with, can see all imported elements from the ics

### Actual behaviour
Only the calendar owner sees the ICS dates. Also when one of the users who the calendar is share with imports the ics

### Server configuration
Nextcloud 12.0.3

**Operating system**: Linux, Debian 9, Dockerized

**Web server:** Apache with PHP 7

**Database:** MySQL

**PHP version:** 7

**Calendar version:** 1.5.6

**Updated from an older installed version or fresh install:** Updated calendar from older version

**Signing status (ownCloud/Nextcloud 9.0 and above):** Nextcloud 12.0.3

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
Empty. No integrity errors

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment]
@swissbyte Wild guess: When you open the ics file in a text editor, every VEVENT block has `CLASS:PRIVATE`?

**Comment by swissbyte** [comment]
@georgehrke You are right! Perfect! Tahnk you so much!! I Guess i have to change this to pulic?
By the way, is there a possibility to automatically synchronize the nextcloud calendar with an ics calendas web url?  Thanks

**Comment by georgehrke** [comment]
> I Guess i have to change this to pulic?

Yes

> By the way, is there a possibility to automatically synchronize the nextcloud calendar with an ics calendas web url? 

If it's webcal: yes, if it's caldav: no

**Comment by georgehrke** [comment]
I raised the following two issues because of this:
#657
#658
