### ISSUE TITLE
Calendar does not show VTODO Items

### ISSUE THREAD

**Issue by swissbyte** [nextcloud/calendar#656]
Is it possible to show VTODO Entries?
Such entries are generated by the task app.

**Comment by georgehrke** [comment]
We won't show all VTODOs, but only ones with a due date

#28

**Comment by swissbyte** [comment]
Yes, the task app defines a DUE date. 
Here is the PUT request from the task app: 

`BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Nextcloud Tasks v0.9.5
BEGIN:VTODO
CREATED:20171115T085443
DTSTAMP:20171115T085446
LAST-MODIFIED:20171115T085446
UID:bvg8mahjlu9
SUMMARY:Test
PRIORITY:0
PERCENT-COMPLETE:0
X-OC-HIDESUBTASKS:0
DUE:20171115T090000
END:VTODO
END:VCALENDAR`

But it is not visible in the Calendar

**Comment by georgehrke** [comment]
Yes, #28 is an open feature request. It’s yet to be implemented

**Comment by swissbyte** [comment]
Thanks for your comment

I would implement it if i would know where to start.
I think it could not be very complicated.
