### ISSUE TITLE
ICS file import does not import events

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/calendar#660]
### Steps to reproduce

1. create a file `test.ics`:

       BEGIN:VCALENDAR
       VERSION:2.0
       CALSCALE:GREGORIAN
       X-WR-CALNAME:test
       X-APPLE-CALENDAR-COLOR:#ff0000
       BEGIN:VEVENT
       DTSTAMP:20171112T131258Z
       DTSTART;TZID=Europe/Berlin:20171119T140000
       DTEND;TZID=Europe/Berlin:20171119T160000
       RRULE:FREQ=MONTHLY;BYDAY=1SU
       SUMMARY:Repeating Entry
       END:VEVENT
       BEGIN:VEVENT
       DTSTAMP:20171112T131258Z
       DTSTART;TZID=Europe/Berlin:20171119T100000
       DTEND;TZID=Europe/Berlin:20171119T110000
       SUMMARY:Test Entry
       END:VEVENT
       END:VCALENDAR

2. import the file using `Import calendar` feature in *Settings &import* menu
3. select `New calendar` in the calendar selector

### Expected behaviour
A new red-colored calendar called *test* should be created, one single an one repeating event should appear in the calendar view.

### Actual behaviour
A new red-colored calendar called *test* is created, but it does not contain any events. `nextcloud.log` has the following:

    {"reqId":"kfGzUNRv2ReAPjYAfgIc","level":4,"time":"2017-11-15T11:36:35+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"mcnesium","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/calendars\/mcnesium\/test\/Nextcloud-O56L9FCD85IHZVJZZKYT.ics","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\UnsupportedMediaType\",\"Message\":\"Validation error in iCalendar: A calendar object on a CalDAV server may only have components with the same UID.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud.example.de.old\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(801): Sabre\\\\CalDAV\\\\Plugin->validateICalendar('BEGIN:VCALENDAR...', 'calendars\\\/mcnes...', true, Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), true)\\n#1 [internal function]: Sabre\\\\CalDAV\\\\Plugin->beforeCreateFile('calendars\\\/mcnes...', 'BEGIN:VCALENDAR...', Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar), true)\\n#2 \\\/var\\\/www\\\/cloud.example.de.old\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/cloud.example.de.old\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1094): Sabre\\\\Event\\\\EventEmitter->emit('beforeCreateFil...', Array)\\n#4 \\\/var\\\/www\\\/cloud.example.de.old\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('calendars\\\/mcnes...', 'BEGIN:VCALENDAR...', NULL)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/cloud.example.de.old\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/cloud.example.de.old\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#8 \\\/var\\\/www\\\/cloud.example.de.old\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/cloud.example.de.old\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/cloud.example.de.old\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/var\\\/www\\\/cloud.example.de.old\\\/remote.php(162): require_once('\\\/var\\\/www\\\/cloud....')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud.example.de.old\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php\",\"Line\":917}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}

The punchline here is propably `"Validation error in iCalendar: A calendar object on a CalDAV server may only have components with the same UID.\"`.

**Comment by georgehrke** [comment]
Yeah, both VEVENTs are missing the UID property, which is mandatory.

Therefore the error is expected

**Comment by mcnesium** [comment]
I see, sorry about that. I would like to suggest to add an error message in the browser though, that tells the user about something being wrong with the file format instead of just not adding anything.
