### ISSUE TITLE
Update to 1.5.6: Server not responding, app cannot be activated

### ISSUE THREAD

**Issue by fdeitelhoff** [nextcloud/calendar#662]
I'm on Nextcloud 12.03 and I was using the Calendar App 1.5.5 since yesterday. After I got the "there's an update" notification, I started the update. After this update my server was not responding (Empty Response Error). After some minutes it was responding again and I could manage to go into the admin area to deactivate the app.

When the app is deactivated, my server is working fine. Now I cannot active the app again because I get the message that "this app makes the server unstable".

Can I delete the app without loosing my calendar entries? Maybe reinstalling will help. There's nothing calendar specific in my log files.

Are there known problems with nextcloud 12.0.3 and the calendar app 1.5.6? Do I have a chance to debug this if the log shows nothing specific to the calendar app?

**Comment by tcitworld** [comment]
> Can I delete the app without loosing my calendar entries? Maybe reinstalling will help. There's nothing calendar specific in my log files.

Absolutely. If Nextcloud doesn't allow to delete the app in the app management section, just delete the `calendar` folder inside `apps/` and reinstall it.

**Comment by fdeitelhoff** [comment]
> Absolutely. If Nextcloud doesn't allow to delete the app in the app management section, just delete the calendar folder inside apps/ and reinstall it.

Okay and I won't lose my calendar entries? I've a database backup but I don't want to restore those tables by myself.

**Comment by tcitworld** [comment]
Starting with Nextcloud 9, the calendar and contact apps are only clients running inside your browser. You won't lose any data with these apps removed.

**Comment by fdeitelhoff** [comment]
Okay, thanks. That's good to know.

But it doesn't change anything. While reinstalling I get the same error (German):

"Fehler: Diese App kann nicht aktiviert werden, da sie den Server instabil macht."

**Comment by georgehrke** [comment]
Does this only apply to the Calendar app?
Can you install / update other apps?

**Comment by fdeitelhoff** [comment]
Only the Calendar app.

I tried to activate the app "Impersonate" and it worked without any problems.

**Comment by georgehrke** [comment]
Can you please enable the debug mode and try to install the calendar app again? 

Maybe there are better logs.

**Comment by fdeitelhoff** [comment]
The debug mode you mentioned is 'debug' => true in the config.php? If yes, I did that.

And then I tried to install the Calendar app again and it works. Without any more logs. I've no idea what happened, but the app version 1.5.6 is now installed and it seems working.

What can I do in the future to get more data? Is there anything else or just the debug mode?

**Comment by georgehrke** [comment]
> The debug mode you mentioned is 'debug' => true in the config.php? If yes, I did that.

Yes

> And then I tried to install the Calendar app again and it works. Without any more logs. I've no idea what happened, but the app version 1.5.6 is now installed and it seems working.

Hm, that's really weird. But I'm glad it works now.
Maybe it was just a temporary issue of the download server.

> What can I do in the future to get more data? Is there anything else or just the debug mode?

Pretty much only debug mode, but please don't leave that enabled for production
