### ISSUE TITLE
In which file/app is fullcalendar script loaded?

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/calendar#663]
Thanks for the efforts on both Nextcloud server and this app.  
I have a basic question, where is full calendar scripts/dependencies loaded?  
Is it loaded in the server program or calendar app loads them itself?  
Can you point me to the file?

**Comment by georgehrke** [comment]
We use gulp to bundle all vendor dependencies into one file:
Hence fullcalendar is part of that vendor.js which is generated when you run gulp (or generally the make file)

https://github.com/nextcloud/calendar/blob/master/js/gulpfile.js#L61

**Comment by mehrdaad** [comment]
@georgehrke in gulpfile some scripts are loaded for build.  
I can't find any ``vendor`` dir either in calenar app or in nextcloud's main source.  
can you describe where is vendor dir built from?  
I want to add another dependency to calendar app. AFAIK I should add it in ``vendorSources`` section of ``gulpfile``. 

https://github.com/nextcloud/calendar/blob/bb0137b24b3e198a47373478f0d82d250ab5909a/js/gulpfile.js#L58   

Can you explain the process of adding another dependency?

**Comment by georgehrke** [comment]
> I can't find any vendor dir either in calenar app or in nextcloud's main source.
can you describe where is vendor dir built from?

It's build with [bower](https://bower.io). Also see https://github.com/nextcloud/calendar/blob/master/js/bower.json

> Can you explain the process of adding another dependency?

Check if it's available via npm or bower. Add it to `js/package.json` for npm or `js/bower.json` for bower, add it to the `vendorSources` array and run make again.

As a side note: You can also hand over Git repositories to Bower and it will clone them locally in the vendor dir. https://github.com/nextcloud/calendar/blob/master/js/bower.json#L7

**Comment by mehrdaad** [comment]
@georgehrke thanks alot.

**Comment by mehrdaad** [comment]
@georgehrke just a another tiny question, I've added an option to full calendar so when initializing full calendar, one can pass another option like ``foo`` to it.  
But I can't the source where calendar app initializes full calendar to pass this additional config to it.  
Can point to the line where full calendar is initialzed?

**Comment by mehrdaad** [comment]
@georgehrke Can you help me please? Haven't found it yet?

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/blob/master/js/app/directives/fullCalendarDirective.js#L106
