### ISSUE TITLE
datetimepicker show incorrect date-format on asia/shanghai-user browser

### ISSUE THREAD

**Issue by cybexr** [nextcloud/calendar#664]
### Expected behaviour
after pickdate, ocdatetimepicker show correct datetime format 
eg. 2017年11月22日

### Actual behaviour
after pickdate now it shows 
2017年111122日， the month-name incorrect

### Server configuration
12.0.3

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/534
