### ISSUE TITLE
What library is used for datepicker in event setting

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/calendar#665]
I'm referencing https://github.com/nextcloud/calendar/blob/master/js/app/directives/datetimepickerDirective.js#L78.  
calling method ``element.find('.events--date').datepicker()`` which library is used for datepicker initialization?  

Also, Where do you set the format for datepicker title?  
I have highlighted the place I'm referencing?  
![download](https://user-images.githubusercontent.com/13661520/33308875-6f803136-d431-11e7-9192-6e9c02083afb.png)

I would appreciate you for answer these 2 questions.

**Comment by georgehrke** [comment]
It's based on the jQuery datepicker. The title is generated by that plugin as well and is not being manipulated by us.

**Comment by mehrdaad** [comment]
@georgehrke Also in https://github.com/nextcloud/calendar/blob/master/templates/editor.popover.php#L24 some properties is determined using ``properties``.  
What is ``properties``? and can it be accessed from ``datetimepickerDirective.js``?
