### ISSUE TITLE
Style in calendar app broken in Nextcloud Beta 13

### ISSUE THREAD

**Issue by onny** [nextcloud/calendar#666]
Hey,
calendar app (1.5.6) style seems to be broken in Nextcloud 13.0 Beta 1

![2017-11-28-160317_swaygrab](https://user-images.githubusercontent.com/757752/33326651-d5420020-d455-11e7-86e1-bd817ce2d5ca.png)

Best regards,
Jonas Heinrich

**Comment by georgehrke** [comment]
will be fixed by #613

let's keep this open for reference.

**Comment by nursoda** [comment]
Similar issue in contacts, too: https://github.com/nextcloud/contacts/issues/453

**Comment by georgehrke** [comment]
This was fixed with #613
