### ISSUE TITLE
revisit supported browsers

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#67]
I'd like to propose to revisit the supported browsers.
Supporting only the very latest Firefox, Safari, Chromium is quite restrictive.

In contrast to Safari do older Firefox and Chromium already provide a good ES6 support, therefore it'd like to do the following:
- add support for Firefox 45+ (which happens to be a long term release) with Calendar 1.5
- add support for Chrome 49+ with Calendar 1.5
- drop support for Safari 9 with 1.6 (That's 1.5 month after the Safari 10 release) and get rid of babel 

@raghunayyar @tcitworld

**Comment by tcitworld** [comment]
Firefox 45 works perfectly with babel-compiled code.

Compiling without babel currently leads to an error with ng-annotate : `Error: StringMap expected string key`

**Comment by georgehrke** [comment]
Okay, then we should consider keeping babel for a while. It works fine for now. What do you think?

**Comment by georgehrke** [comment]
If we keep babel, we can also keep support for Safari 9 for now.

**Comment by tcitworld** [comment]
Yup. Also, babel can brings support for nice es2015+ stuff that we can play with.

**Comment by georgehrke** [comment]
I'll check on browserstack how far we can go back

**Comment by ccoenen** [comment]
What would be the point in removing babel? I do not think "hey, we only support the latest and greatest browsers" is very nice to users. Especially when there's no real benefit from excluding them.

According to this, browser support has been sketchy as recently as two versions back:
http://kangax.github.io/compat-table/es6/

**Comment by georgehrke** [comment]
There are certain features of ES6 that can't be properly handled with Babel. 
For example the let and const keyword become var and const is not constant anymore ...

**Comment by georgehrke** [comment]
But going all ES6 is definitely not reasonable within the next year

**Comment by georgehrke** [comment]
Nextcloud itself aims to support the following browsers:
- Firefox 14+
- Chrome 18+
- Safari 5+

**Comment by tcitworld** [comment]
> There are certain features of ES6 that can't be properly handled with Babel.
For example the let and const keyword become var and const is not constant anymore ...

I think we can configure Babel to ignore this change. However Safari 9 doesn't understand `const`... :'(

**Comment by georgehrke** [comment]
>  However Safari 9 doesn't understand const... :'(

At least not in strict mode. :(
We have to elaborate that. We might consider dropping support for Safari 9 while supporting keeping support for older Firefox and Chromium versions that already support const and let.
Safari has a fairly low share and most users run the latest iOS and OS X/macOS versions.

**Comment by georgehrke** [comment]
> Android Browser in 5.1 has virtually no support at all for ES6 - and Android 5.1, sadly, is still extremely common according to the google

We currently don't aim to support Android anyway.
Fullcalendar's mobile support is still being worked on.

Additionally a mobile device is commonly not shared among different users.
Therefore there is no legitimate reason not to install a free (as in GPL) CalDAV app.

**Comment by georgehrke** [comment]
Ok, so I tested this on browserstack:
- Firefox 45+ works fine 
- Chrome 49+ works fine
- Edge 13+ works actually fine as well

Safari 9+ works just fine as well

Therefore I'd propose to change the supported browsers mentioned above.
Do you agree? @raghunayyar @tcitworld

**Comment by tcitworld** [comment]
:+1:

**Comment by pixi** [comment]
Could you kindly tell me why you don't stick with the browser versions Nextcloud supports?
The Calendar being a core part should not require a different setup. This causes nothing but trouble, imho!

And may I ask: if you want to use the latest technology, why not making a "Lite"-Calendar which can be used with the same versions Nextcloud supports?

**Comment by georgehrke** [comment]
> Could you kindly tell me why you don't stick with the browser versions Nextcloud supports?
The Calendar being a core part should not require a different setup. This causes nothing but trouble, imho!

@pixi The browsers supported by the Nextcloud server are insanely old. We make use of a few modern web standards that are simply not supported by these old browsers.
Both Firefox 45 and Chrome 49 were released in march. Firefox 45 is also a long term support release, so that works great for companies too.

> And may I ask: if you want to use the latest technology, why not making a "Lite"-Calendar which can be used with the same versions Nextcloud supports?

We don't use the very latest technology. These things have been standardized a few years back already. But browsers like Firefox 14 have been released over 4 years ago. If we support Firefox 14, we might as well support Netscape ...

**Comment by georgehrke** [comment]
Also the market share of Firefox 14 - 45 and Chrome 18 - 49 is extremely low.
http://caniuse.com/usage-table

It would take us a big effort to support these browsers and given the tiny market share that's simply not worth it imo.

**Comment by pixi** [comment]
Well, it always depends on your view:
https://www.browser-statistik.de/statistiken/
shows that Firefox 45 and below has a 1/3 share of ~30% of all Browsers… I wouldn't call this tiny!

Anyway, couldn't you just provide a "Calendar Old" (taken from v0.x-Calendar or whatever) which works with all NC-versions? There is no need to update, just being able to use it!

**Comment by georgehrke** [comment]
The 31.8% on https://www.browser-statistik.de/statistiken/ are for all Firefox versions, not just Firefox 45 and below.

The website also provides statistics about different versions.
https://www.browser-statistik.de/statistiken/versionen/

Firefox 45+ makes up 83% of all Firefox users.

> Anyway, couldn't you just provide a "Calendar Old" (taken from v0.x-Calendar or whatever) which works with all NC-versions? There is no need to update, just being able to use it!

v0.x doesn't work with the Nextcloud 9 (nor oC 9) or later.

**Comment by tcitworld** [comment]
Also, your statistics are quite German-centered (I think Germany is one of the only countries in the world where Firefox is more used than Chrome).
