### ISSUE TITLE
More complex recurrence 

### ISSUE THREAD

**Issue by ScreamingDev** [nextcloud/calendar#670]
### Steps to reproduce
1. Create an event
2. Make it recurring an weekdays only

### Expected behaviour
Tell us what should happen

Event happens only on weekdays.

### Actual behaviour
Tell us what happens instead

Not possible right now

### Additional info

Having such complex events is not hard.
A recurrence is not only a string or time that is added to the previous one
it is an array of combinations.

Imagine every first tuesday of the month:

- "+1 month"
- "first thursday of month"

PHP understands that and if you combine such actions more complex rules are possible.

**Comment by georgehrke** [comment]
dup of #10 

Please check for duplicates before creating new events. That would save us a massive amount of work :)
