### ISSUE TITLE
Feature Request: Option to overide jstz detected timezone

### ISSUE THREAD

**Issue by pard68** [nextcloud/calendar#671]
### Issue
While using browser privacy extensions and/or enabling certain privacy settings time defaults to UTC

### Expected behaviour
Have an override option to either disable jstz and set custom timezone, or allow the option to modify jstz's detected timezone and force a user specified timezone.

### Client configuration
**Browser:** Firefox, using uBlock, uMatric, PrivacyBadger, and Privacytools.io recommended Firefox configuration settings.

**Operating system:** Debian

**Comment by georgehrke** [comment]
Dup of #586

Please search for duplicates before creating new issues
That would save us a massive amount of time
Thx
