### ISSUE TITLE
Convert URLs into links inside description

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#674]
On read-only events, it would be nice if URLs were automatically converted into links so that you just have to click on them (since they're read-only, not that easy to select and copy-paste).

**Comment by chrisSCM** [comment]
Actually, this would always be nice to have, not only for read-only events.

**Comment by tcitworld** [comment]
See https://github.com/nextcloud/calendar/issues/2730.

Also the description should always be raw text, rich text needs https://github.com/nextcloud/calendar/issues/3234

**Comment by raimund-schluessler** [comment]
> Also the description should always be raw text, rich text needs #3234

In the Tasks app, links in the title/summary of the event/task are clickable. The same would be possible in the Calendar app, also for other properties, such as URL or location.

But it would require to not always show the input fields.
