### ISSUE TITLE
update calendar 'today'

### ISSUE THREAD

**Issue by luzik** [nextcloud/calendar#678]
### Steps to reproduce
1. Login into nexcloud webpage
2. Goto calendar month view
3. Wait till nextday

### Expected behaviour
Current day 'yellow background' show today

### Actual behaviour
Current day 'yellow background' show yesterday

**Comment by georgehrke** [comment]
This is actually something we should  do upstream. Will report a bug soon.

**Comment by ideadapt** [comment]
The following existing issue in upstream addresses this issue https://github.com/fullcalendar/fullcalendar/issues/3783. 
They treat that as a minor issues, whereas for me, this annoys me almost every day, since my nextcloud calendar is a pinned tab.
