### ISSUE TITLE
can't add event after 1.5.7 update

### ISSUE THREAD

**Issue by nizarus** [nextcloud/calendar#679]
### Steps to reproduce
1. Login into nexcloud
2. Goto calendar application
3. Add event

### Expected behaviour
Event added

### Actual behaviour
No event added

## Server configuration detail

**Operating system:** Linux 2.6.32-773.26.1.lve1.4.35.el6.x86_64 #1 SMP Tue Sep 26 06:34:34 EDT 2017 x86_64

**Webserver:** Apache (litespeed)

**Database:** mysql 5.6.36

**PHP version:** 5.6.32
Modules loaded: Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, litespeed, apcu, bcmath, dom, fileinfo, gd, imap, intl, json, exif, mailparse, mcrypt, memcache, mysql, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, sockets, xmlreader, xmlwriter, zip, mhash, apc, ionCube Loader, Zend OPcache, Zend Guard Loader

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.7
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxmotion: 0.0.5
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.3.2
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ojsxc: 3.3.2
 - password_policy: 1.2.2
 - phonetrack: 0.0.8
 - provisioning_api: 1.2.0
 - rainloop: 5.0.6
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.2
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "ocapuprnh0az",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.kerkeni.tn"
    ],
    "datadirectory": "REMOVED",
    "overwrite.cli.url": "https:\/\/cloud.kerkeni.tn",
    "dbtype": "mysql",
    "version": "12.0.4.3",
    "dbname": "REMOVED",
    "dbhost": "localhost",
    "dbtableprefix": "REMOVED",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "appstore.experimental.enabled": true,
    "mail_smtpmode": "php",
    "mail_from_address": "cloud",
    "mail_domain": "kerkeni.tn",
    "loglevel": 0,
    "theme": "",
    "maintenance": false,
    "updater.release.channel": "stable",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_smtpauthtype": "LOGIN"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by tcitworld** [comment]
Please provide Browser and Nextcloud logs.

**Comment by nizarus** [comment]
After reporting the anomaly to my hosting provider the calendar returned to work as expected. It was a miss configuration with my hosting provider.
