### ISSUE TITLE
Scrolling not possible in left calendar menu

### ISSUE THREAD

**Issue by prilly** [nextcloud/calendar#68]
### Steps to reproduce
1. Add multiple callendars to fill the left menu
2. when the left menu contains so many callendars that the menu needs scrolling to see them all
3. no scrolling function for left menu

### Expected behaviour
It should be possible to scroll the left callendar menu independantly from the main callendar page.

### Actual behaviour
callendars/subscriptions in left menu is hidden when the menu is filling up.

### Server configuration
**Operating system**:
Debian 8
**Web server:**
nginx/apache
**Database:**
mariadb
**PHP version:**
7.0
**Server version:** (see your admin page)
10.0
**Calendar version:** (see the apps page)
1.4.0
**Updated from an older installed version or fresh install:**
upgraded from oc 9.1
**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
Please fill out the entire issue template. Especially the client configuration

**Comment by tcitworld** [comment]
Fixed.
