### ISSUE TITLE
When location and/or description is set for an event, already show that info in the small popover

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#680]
Currently from the small popover it is not visible at all what info is set. Actually that view should be a summary of all info which is set. At the bare minimum of course only showing the basics, but _when it is set_, also showing things like location and/or description (and maybe more).

cc @nextcloud/calendar

**Comment by tcitworld** [comment]
Does it relates to https://github.com/nextcloud/calendar/issues/615 ?

**Comment by jancborchardt** [comment]
No, this is about the popover which shows when you actually click on the event. :)
