### ISSUE TITLE
Request: Select AM / PM of an event by just clicking on AM / PM

### ISSUE THREAD

**Issue by sunjam** [nextcloud/calendar#681]
Thanks for your good work!  I recommend this as an alternative to currently listing all of the times twice (under AM and PM) when editing a Calendar event.

**Comment by georgehrke** [comment]
Can you please explain the benefit of that? 

Let's say you want to select 3:30PM.
Right now you need 2 clicks: Click 3 in the PM section, click 30 in them minutes section
With your approach a user would need 3 clicks: Click PM, Click 3 in the hour section, click 30 in the minutes section.

cc @jancborchardt

**Comment by jancborchardt** [comment]
This would be very confusing as you need to do a mental switch between two lists which look exactly the same. For example when having an event which goes from, say 11:00–13:00.

Also, this doesn’t apply at all for 24h formats so we would need to maintain 2 completely different views.

So this is not happening. I agree though we can improve the timepicker even more. :)
