### ISSUE TITLE
Show double month number in event panel 

### ISSUE THREAD

**Issue by clumsycat** [nextcloud/calendar#687]
### Steps to reproduce
1. language set to zh_CN (chinese(simplified))
2. Click on calendar to create a event.

### Expected behaviour
Show date like "2017年12月21日"

### Actual behaviour
Show "2017年121221“ Without ”月（month in Chinese）“
I have check the zh_CN.js and zh_CN.json， 
![image](https://user-images.githubusercontent.com/7812749/34243049-e8200f82-e659-11e7-9482-3b098dfce24f.png)
![image](https://user-images.githubusercontent.com/7812749/34243056-fa53115e-e659-11e7-8828-3ea2f3e85842.png)

### Server configuration

**Operating system**:
Docker on CentOS 7.0
**Web server:**
not sure, I am using wonderfall/nextcloud docker image
**Database:**
mariadb
**PHP version:**
not sure, I am using wonderfall/nextcloud docker image
**Server version:** (see your admin page)
12.0.3
**Calendar version:** (see the apps page)
1.5.7
**Updated from an older installed version or fresh install:**
fresh
**Signing status (ownCloud/Nextcloud 9.0 and above):**

**language:**
zh_CN
```
No errors have been found.
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no.

### Client configuration
**Browser:**
Chrome 
**Operating system:**
Win 10
**CalDAV-clients:**

### Logs
```
nothing with calendar
```

**Comment by georgehrke** [comment]
dup of #534
