### ISSUE TITLE
Delete only one occurrence of a multiple occurrences event

### ISSUE THREAD

**Issue by meaz** [nextcloud/calendar#688]
### Steps to reproduce
1. Add an event
2. Set occurences for this event (ex: every day at the same time)
3. Delete one of the occurence (ex: the one on wednesday)

### Expected behaviour
Only the occurence deleted should be deleted

### Actual behaviour
All occurences are deleted

I'm not the owner of the server, so I can't give more details. I could ask to the admin, but fisrt want to know if it's a Nextcloud known problem or just a server configuration mistake.

**Comment by markuswochnik** [comment]
It's already in developement, take a look at #7

**Comment by Tokowo** [comment]
This still an issue in 2019...
