### ISSUE TITLE
Use user's full name and email address in the FROM header of invitation emails

### ISSUE THREAD

**Issue by floeschie** [nextcloud/calendar#690]
I use calendar and a couple of clients (Android, KMail, Thunderbird/Lightning) and CalDAV to manage my calendar. Sometimes I invite others to an event. However, those invitation emails have set the name of the Nextcloud instance and the global FROM email address in the FROM header.

This lead to confusion at the invitee's side, because they did not recognize the invitation email as a message from me.

### Steps to reproduce
1. Go to Admin-> Theming
1. Set the _Name_ attribute to some fancy value, e. g. "Yankeedoodle"
1. Go to Admin -> Additional settings
1. In the _Email server_ section, set _Send mode_ to "PHP" and _From address_ to "howdy@yourdomain.com"
1. Go to _Profile_ and set your full name to "John Doe" and your email to "john.doe@yourdomain.com"
1. Make sure PHP can send emails
1. Add your Nextcloud calendar to Thunderbird/Lightning via CalDAV
1. Create a new event in Thunderbird and invite your boss via email

### Expected behaviour
My boss will receive an invitation email with my full name and email address set in the FROM headers (here: `"John Doe" <john.doe@yourdomain.com>`). If no personal email address is set, Nextcloud will use the system wide _From address_ (see step 4) together with my full name ("John Doe").

### Actual behaviour
My boss receives an invitation email from my Nextcloud server, with FROM headers set to `"Yankeedoodle" <howdy@yourdomain.com>`. She will be very confused, because she does not know anyone who's called Yankeedoodle.

### Server configuration
**Operating system**:
Debian

**PHP version:**
7.0

**Server version:** (see your admin page)
12.0.4

**Calendar version:** (see the apps page)
1.5.7

**Updated from an older installed version or fresh install:**
Fresh

**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.2
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "oc9r1nwyuilp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.libertalia.eu"
        ],
        "datadirectory": "/var/mydomain/data",
        "overwrite.cli.url": "https://cloud.mydomain.com",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "no-reply",
        "mail_smtpmode": "php",
        "mail_domain": "mydomain.com",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0,
        "log_type": "syslog",
        "theme": "",
        "maintenance": false,
        "updater.release.channel": "stable",
        "appstore.experimental.enabled": true,
        "mail_smtpauthtype": "LOGIN"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**CalDAV-clients:**
- Thunderbird 52.5.0 (32-Bit) on Windows 10
- CalDAV-Sync app 0.4.23 on Android 8.0 Oreo

**Comment by georgehrke** [comment]
First of all, you said your own that it's related to CalDAV and reproducible on different clients: 
As the comment in the issue template clearly states: 
>Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

Second of all there are plenty of duplicates in the server repo including a reasoning / explanation why that's the case at the moment and why we can't do much about it.

**Comment by georgehrke** [comment]
This seems to be the most recent one that also links to other issues: https://github.com/nextcloud/server/issues/5080
