### ISSUE TITLE
wrong DTEND if only DTSTART is given

### ISSUE THREAD

**Issue by wendy2702** [nextcloud/calendar#692]
Hi all,

i have a problem with ics import. My local waste disposal provides the dates for different waste via ICS Files.

If i import these files i.e.: Schadstoffmobil to my Nextcloud calendar the start and end date is wrong as you can see from attached screenshot.

![ics_nc_import](https://user-images.githubusercontent.com/33424168/34524335-82e79fd0-f09b-11e7-8e6f-a79e01a93919.jpg)

### Steps to reproduce
1. import provided ICS File to NC12.03 Calendar

[iCal_5a4ceb4b18f2b.zip](https://github.com/nextcloud/calendar/files/1600647/iCal_5a4ceb4b18f2b.zip)

### Expected behaviour
Import should work like import at Outlook. Start/End Date should be same in case of one day event.

### Actual behaviour
Currently start/end date is in wrong order. (screenshot above)

### Server configuratio

**Operating system**: Debian Jessie

**Web server:** nginx

**Database:** mysql

**PHP version:**

**Server version:** NC12.03

**Calendar version:** 1.5.7

**Updated from an older installed version or fresh install: fresh

**Comment by georgehrke** [comment]
Example from the ics file:
```
BEGIN:VEVENT
UID:9e36847ff0a3e43fcf1f10923ede2744
SUMMARY:Abfuhrtermin: Schadstoffmobil S1
DESCRIPTION:Ihre Abfuhrtermine als iCal Export – Ein Service der Regio Entsorgung AöR – www.regioentsorgung.de 
CLASS:PUBLIC
DTSTART;VALUE=DATE:20180908
DTSTAMP:20180103T154011Z
END:VEVENT
```

ICS data is valid, bug on our side.
