### ISSUE TITLE
Repeating Events Starting after 7:00 PM on any given Saturday Don't Show on Calendar

### ISSUE THREAD

**Issue by SentToDevNull** [nextcloud/calendar#696]
Occasionally, the event does show on the calendar for 1 or 2 repetitions, but if you navigate to the next week and then navigate back, the event disappears again.

The event always "disappears" if you navigate ~6 weeks past the initial repeating event and then navigate back.

Since my time zone is America/New_York, also known as UTC-5, and since the last 5 hours of my Saturdays stop displaying after navigating around ~6 weeks past an event and then navigating back, it's likely a time zone issue.

### Steps to reproduce
1. Create a weekly repeating event starting at 7:01 PM or later on a Saturday.
2. Navigate ~6 weeks past the event, and then navigate back.
2. Watch it not display on the Nextcloud Calendar page.

### Expected behaviour
The event should be displayed on the calendar.

### Actual behaviour
The event is not displayed on the calendar. (It's still shared to CalDav clients, but the Nextcloud Calendar app just doesn't show it.)

### Server configuration

**Operating system**:
Debian 9.1

**Web server:**
Apache2

**Database:**
MySQL/MariaDB

**PHP version:**
7

**Server version:** (see your admin page)
12.0.4

**Calendar version:** (see the apps page)
1.5.7

**Updated from an older installed version or fresh install:**
updated from an older install (old install was also a 12.X.X release)

**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Activtity
Collaborative Tags
Comments
Deleted Files
Federation
File Sharing
First run wizard
Gallery
Log reader
Monitaoring
Nextcloud Announcements
Notifications
Password policy
PDF viewer
Share by mail
Text editor
Theming
Update Notification
Usage Survey
Versions
Video Player
Activities for shared file downloads
Admin notifications
AppOrder
Brute-force Settings
Calendar
Checksum
Contacts
External Sites
File Access Control
Files Clipboard
Flow Upload Keeweb
Mail
Markdown Editor
Metadata
News
Notes
Phone Sync
Quota Warning
Social Sharing via Email
Tasks
Video Calls
Weather

**Nextcloud configuration:**
$CONFIG = array (
  'instanceid' => 'XXXXXXXXXXXXXX',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'www.example.com',
    1 => 'example.com',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'https://www.example.com/nextcloud',
  'overwriteprotocol' => 'https',
  'dbtype' => 'mysql',
  'version' => '12.0.4.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'XXXXXXXXXXXXXXXXXXX',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_from_address' => 'user',
  'mail_smtpmode' => 'php',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_domain' => 'example.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'mail.example.com',
  'mail_smtpport' => '587',
  'maintenance' => false,
  'updater.secret' => 'XXXXXXXXXXXXXXXXXXXXXXX',
  'theme' => '',
  'loglevel' => 2

**Are you using external storage, if yes which one:** local/smb/sftp/...
nope

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
nope. I do access the CalDav share hosted by the machine externally from a phone, from which I can confirm that events (after 7PM) are stored in the calendar share; they just don't show up on the Nextcloud Calendar page.

### Client configuration
**Browser:**
Google Chrome, Chromium, Firefox, and every other browser I've tried

**Operating system:**
Linux

**CalDAV-clients:**
DavDroid accesses my CalDav share

**Comment by georgehrke** [comment]
What timezone are you in? Maybe there is a relation to the 7pm thing ...

Do you mind sharing an example ics file? That would make reproducing it even easier.

**Comment by SentToDevNull** [comment]
Time zone is America/New_York. Here's an example: https://www.lukasyoder.com/nextcloud/index.php/s/F47F5Zeo8BSXqTp

Edit: The event "disappears" after you navigate 6 weeks past the initial repeating event and then navigate back.

**Comment by georgehrke** [comment]
I can no longer reproduce this with Calendar 2.0.0 beta1
