### ISSUE TITLE
Layout broken with Nextcloud 13beta4 and calendar 1.5.7

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#697]
I just noticed that the sidebar of the calendar is broken on Nextcloud 13 beta 4 with calendar 1.5.7:

![calendar](https://user-images.githubusercontent.com/1589737/34770360-3759deb4-f601-11e7-8221-e03d9cd53cf0.png)

Every black bar represents a calendar name. The last two bars at the bottom are one calendar where the name is split in two lines.

@georgehrke  I saw this at c.nc.com, maybe you can check there as well if you can't reproduce it.

**Comment by georgehrke** [comment]
dup of #666 
fix in #613 (WIP, will be done by today)
