### ISSUE TITLE
Date picker is broken for Traditional Chinese locale (zh_TW)

### ISSUE THREAD

**Issue by yan12125** [nextcloud/calendar#699]
### Steps to reproduce
1. Choose Traditional Chinese, or "正體中文（台灣）" in Nextcloud settings
2. Try to add an event and pick 2018/01/18 (yyyy/mm/dd format)

### Expected behaviour
The event goes to 2018/01/18 as expected

### Actual behaviour
The event goes to 2018/11/08. Two screenshots, which hopefully helps non-Chinese users understanding the bug:
![2018-01-14 01 55 17](https://user-images.githubusercontent.com/1937689/34908649-37ecfc42-f8ce-11e7-8e54-a4969fdd3244.png)
(After clicking on 2018/01/18 of the calendar)
![2018-01-14 01 55 35](https://user-images.githubusercontent.com/1937689/34908650-38255fc4-f8ce-11e7-828d-b5ef4dd613c5.png)
(After clicking on the date)

## Server configuration detail

**Operating system:** Linux 4.14.12-x86_64-linode92 #1 SMP Fri Jan 5 15:34:44 UTC 2018 x86_64

**Webserver:** Apache/2.4.29 (Unix) OpenSSL/1.1.0g (fpm-fcgi)

**Database:** sqlite3 3.21.0

**PHP version:** 7.2.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, curl, gd, pdo_sqlite, pgsql, sqlite3, zip, apcu, Zend OPcache

**Nextcloud version:** 13.0.0 RC 1 - 13.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from an older nextcloud

**Where did you install Nextcloud from:** AUR (Arch User Repository) https://aur.archlinux.org/packages/nextcloud-testing

<details><summary>Signing status</summary>

Array
(issuetemplate itself has an issue :) There's no message about signing states so I guess no)
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - calendar: 1.5.7
 - contacts: 2.0.1
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - files: 1.8.0
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - tasks: 0.9.5 (I use git-master to fit Nexcloud 13)
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - comments
 - encryption
 - federation
 - files_external
 - gallery
 - systemtags
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/127.0.0.1\/nextcloud",
    "dbtype": "sqlite3",
    "version": "13.0.0.10",
    "logtimezone": "UTC",
    "installed": true,
    "appstoreenabled": false,
    "theme": "",
    "loglevel": 2,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpport": "587",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "updater.release.channel": "beta",
    "memcache.local": "\\OC\\Memcache\\APCu"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

<details><summary>LDAP configuration (delete this part if not used)</summary>
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0 (Firefox 58 beta 16)

**Operating system:** macOS 10.13.2 17C205 

## Logs

<details><summary>Nextcloud log</summary>

```
Just quite a few errors from issuetemplate
```
</details>

<details><summary>Browser log</summary>

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-bFNJWllpMVhEaUplbitHTjE3ZUpreWNQOHVJWmhVMGhnamxFWG03UzNrOD06cEhKM0MyUXZKVnN0eHJibjRmcThwVkU4eE5KRHFuUjR4VU1ET2tIcWhpbz0=' 'unsafe-eval'”). Source: (function (ERROR) {

    const V8_STACK_....
calendar:1
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
core.js:1563:2834
Source map error: request failed with status 404
Resource URL: https://chyen.csie.org/nextcloud/core/vendor/core.js?v=4bd9ecd9-0
Source Map URL: purify.min.js.map
[Learn More]
```
</details>

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/534
