### ISSUE TITLE
Invitations - eMail with additional text ?

### ISSUE THREAD

**Issue by frank-github** [nextcloud/calendar#702]
Hi,

if I invite a person, who is using an electronic calender like thunderbird **with installed** lightning addon, everything very fine 
But if a user only running thunderbird **without** lightning installed, he had to read a ICS text, most user do not understood (and for power users hard to read too)
No additional informations are included, most users are helpless.

any way to include plain text description for this event at front of email body ?
I do not know each time, if invited person had an electronic calender or not.

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by georgehrke** [comment]
And this issue was already addressed and will be fixed with Nextcloud 13 :) 

So please don't open another issue.

**Comment by georgehrke** [comment]
You can see screenshots of what it will look like here: https://github.com/nextcloud/server/pull/7193

**Comment by frank-github** [comment]
thanks for quick answer
I will look at server repo.

I do not think this fix really adress my issue. 
This linked panel already shown if user had electronic calender

**Comment by georgehrke** [comment]
> I do not think this fix really adress my issue.
This linked panel already shown if user had electronic calender

I'm not sure what you are referring to here, but the email that previously only contained that one ics file now also contains text with who invited you, the event's title, time, description and location.
(with or without lightning)

**Comment by frank-github** [comment]
Thank you for the detailed information. 
Yeah, you're right. The fix solves my problem to 100%.
Nice that my problem is solved with the next release.
