### ISSUE TITLE
Hide canceled recurring event instead of an additional striked one

### ISSUE THREAD

**Issue by lal12** [nextcloud/calendar#705]
When I create a recurring event (using the WebGUI or an external App) and afterwards delete a single event, internally this is handled by an additional created event with the same properties for this single date, just that is marked as canceled.

External apps are then hiding this single event from the recurring events, but the nextcloud gui is showing both the recurring event and the additional cancelled event with striked text.

I think it would be better to have the same behavior in nextcloud as in the apps. 

If this is approved I guess I could do the code changes. Btw I couldn't find the appropriate labels something like "feature-request" or "to-discuss", maybe anyone could help me out there.

**Comment by georgehrke** [comment]
@lal12 
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/issue_template.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md)

You didnt even tell us what version you use ;) 
So please use the issue template. There is a reason it's there THX!

Furthermore please provide a sample ICS file and screenshots of what it looks like in Nextcloud and what it's supposed to look like (in other clients).

**Comment by lal12** [comment]
@georgehrke, sorry I was maybe a little bit fast there. But I thought of this more like a feature request than a bug, so most of this wouldn't be relevant. 

[asd-2018-01-26.ics.txt](https://github.com/nextcloud/calendar/files/1666151/asd-2018-01-26.ics.txt)

### Steps to reproduce
1. (Create a new calendar)
2. Create a reoccuring event e.g. weekly with the Google Calendar app
3. Delete a single one (not the first, not the last one) of the reocurring events.

### Expected behaviour
Now the WebGUI should not show the removed event.
 
### Actual behaviour
The WebGUI still shows the reoccuring event and additionally an event with the same title just striked through. 

### Server configuration

**Operating system**: Linux

**Web server:** NGINX

**Database:** MariaDB

**PHP version:** 7.0.1

**Server version:** 12.05

**Calendar version:** (see the apps page)

**Updated from an older installed version or fresh install:** Updated several times

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found
```

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Linux Mint

**CalDAV-clients:** Android 7 with Google Calendar App & CalDAV Sync Free

### Logs

#### Browser log
Empty

**Comment by georgehrke** [comment]
What exact program created that particular ics?

```
BEGIN:VEVENT
DTSTAMP:20180126T002337Z
DTSTART;TZID=Europe/Berlin:20180202T013000
DTEND;TZID=Europe/Berlin:20180202T023000
SUMMARY:Asd
CLASS:PUBLIC
STATUS:CANCELLED
UID:9634d460-1738-4500-882a-b7f585b2bc00-caldavsyncadapter
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20180126T002326Z
DTSTART;TZID=Europe/Berlin:20180126T013000
DURATION:PT3600S
RRULE:FREQ=WEEKLY;WKST=MO
SUMMARY:Asd
CLASS:PUBLIC
STATUS:TENTATIVE
UID:f300b3d4-0254-481b-9347-dadc60b009cc-caldavsyncadapter
END:VEVENT
```

I will import this ics into other programs, but the Nextcloud result looks like the expected result to me:
- if you want to delete one occurrence, you usually use `EXDATE`
- if you really want to use `CANCELLED` in that case, you should use a `RECURRENCE-ID` for the cancelled event and both events should have the same `UID`

**Comment by lal12** [comment]
Hey, 
thanks for the info.
I used the Android App CalDAV Sync Free, but after a little bit of research I saw that is no longer maintained. So I switched to OpenSync, which does as you recommend and uses RECCURRENCE-ID.

So I guess it can be closed.
