### ISSUE TITLE
Share NC Calendar with Google Calendar - No Updates!

### ISSUE THREAD

**Issue by prubach** [nextcloud/calendar#706]
### Steps to reproduce
1. Create a NC Calendar and share it publicly
2. Use either of the addresses below to add the calendar "From URL" in Google Calendar:
https://mydomain.com/nextcloud/remote.php/dav/public-calendars/XXXXXXXXXXXXXXXX?export
webcal://mydomain.com/nextcloud/remote.php/dav/public-calendars/XXXXXXXXXXXXXXXX?export
3. Add events in the Cloud Calendar App or from Thunderbird Lightning etc.
 

### Expected behaviour
The calendar in the Google Calendar should get updated with the new events.
It would also be nice to be able to add events from Google Calendar, that doesn't work either.

### Actual behaviour
The calendar in the Google Calendar does not update even after logging out and back or reloading the page.

## Server configuration detail

**Operating system:** Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.33

**PHP version:** 7.0.22-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.5 - 12.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** official Nextcloud repo (installed version 12.04, updated using the site to 12.05)

<details><summary>List of activated apps</summary>

Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.1
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - richdocuments: 1.12.40
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "ocfjps3k7ldb",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.scanway.pl"
    ],
    "datadirectory": "\/mnt\/nextcloud-data",
    "overwrite.cli.url": "http:\/\/cloud.scanway.pl\/nextcloud",
    "dbtype": "mysql",
    "version": "12.0.5.3",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "loglevel": 2,
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0

**Operating system:** : Ubuntu 16.04

**Comment by georgehrke** [comment]
> The calendar in the Google Calendar should get updated with the new events.

I think Google just caches it for very long. Maybe you can find a setting to make Google Calendar reload it more often. The `https://mydomain.com/nextcloud/remote.php/dav/public-calendars/XXXXXXXXXXXXXXXX?export` link is always up to date.

The way WebCal works we don't know who subscribes to it and there isn't this concept of sending push notifications to the subscribers for WebCal.

> It would also be nice to be able to add events from Google Calendar, that doesn't work either.

WebCal is read-only by design and as far as I know Google doesn't offer proper CalDAV sharing APIs that work with other servers, because they want you and everyone around u to use google.

**Comment by alexanderdd** [comment]
I read in another forum that google can take up to 12 hours to refresh external calendars imported via url.

**Comment by cleff** [comment]
Has there been any progress on this issue?  I am having a similar problem.  I can import events from nextcloud but this won't update when new events are added.  When I subscribe to the public version of a nextcloud calendar it acts like it is working but no events are populated.  On the other hand, the android integration works quite well with the davdroid app.  With android being in the google ecosystem, I would have thought this would work.  Coworkers that are using Macs have had no problem with the iCal integration and I have also had no problem with Microsoft Outlook.  I am no software engineer, but this seems to suggest the problem might be on google's side and not on the side of the nextcloud calendar team.

**Comment by rollanders** [comment]
The notion that the change will appear after some delay is incorrect. It does not happen.
