### ISSUE TITLE
Custom color per event [$75]

### ISSUE THREAD

**Issue by tobiasgraeber** [nextcloud/calendar#71]
Hi,
is it possible to add an Option, to change a meetings color in the calendar? 
(it is only defined by calendar-source colour as at the moment) ...sometimes there may be an important meeting and i want to make it stand out by red color for example...(without changing calendar). i think there should some color/Highlight function? any suggestions? maybe tags+a searchbox (filter) could also be great... #ux

**Comment by tcitworld** [comment]
Search is to be developed and tags is to be integrated some time too.

**Comment by ccoenen** [comment]
I do not believe the ical standard has anything like this defined. Is there a precedence in another application? If so, how is that stored? I'd hate to see this implementation of the standard create its own island of unsupported fields.

**Comment by georgehrke** [comment]
Google calendar and Outlook have similar features, but they don't store it in the iCal data.
If we implement this, we would store it in an `X-NEXTCLOUD-COLOR` property

**Comment by ccoenen** [comment]
`X-NEXTCLOUD-*` is exactly what I would like to prevent when I say "island of usupported fields".

**Comment by georgehrke** [comment]
Well, but there is no standard for it.

**Comment by MariusBluem** [comment]
...how does Apple do this? 😁

**Comment by georgehrke** [comment]
Apple does not have the feature to color certain events.

**Comment by ccoenen** [comment]
One could try to bring a proposal forward according to this:

https://tools.ietf.org/html/rfc5545#section-8.2.3

```
   A property is defined by completing the following template.

   Property name:  The name of the property.

   Purpose:  The purpose of the property.  Give a short but clear
      description.

   Value type:  Any of the valid value types for the property value need
      to be specified.  The default value type also needs to be
      specified.

   Property parameters:  Any of the valid property parameters for the
      property MUST be specified.

   Conformance:  The calendar components in which the property can
      appear MUST be specified.

   Description:  Any special notes about the property, how it is to be
      used, etc.

   Format definition:  The ABNF for the property definition needs to be
      specified.

   Example(s):  One or more examples of instances of the property need
      to be specified.
```

I would also not go with `COLOR` as a **property name**, it does not reflect the fact that this is a very optional field. It should, for example, not story the default color of the calendar in my opinion. Using this property is - as stated in the title - more suitable to draw attention. I propose something like `DEFAULT-COLOR-OVERRIDE` or `HIGHLIGHT-COLOR` or something like that.

**purpose** would be "optional override to draw attention to a specific event or todo in a calendar. takes precedence over the calendars default color.

**Value Type** - probably just `TEXT`

**Property Parameters** - hex codes starting with `#` or named css colors (or do we need something else?)

**Comment by ccoenen** [comment]
There's `CATEGORIES` already, maybe supporting categories (and adding display rules to a category) would help the OP as well? This would stay well within the standard without the need for customisations.

**example** "oh hey, this needs to stand out *for a reason*" - the reason being that this is a familiy event. Add the category `family`. BOOM Family styling applied. Event stands out from the rest.

**Comment by ccoenen** [comment]
Upside: Thunderbird / Calendara already supports categories and it will add a tiny color-code to the end of the event (the green things called "Urlaub" also have the category "Urlaub" and the blue appointment on 2016-09-20 has the category "Besprechung", everything else has no category.
 
![categories](https://cloud.githubusercontent.com/assets/124909/18669224/3c15dd2a-7f3a-11e6-87c8-7add6b0375b3.png)

**Comment by georgehrke** [comment]
RFC 7986 introduces `COLOR`. We should use that property :)
https://tools.ietf.org/html/rfc7986#section-5.9

**Comment by aluxnimm** [comment]
We now have experimental support for the new COLOR attribute from RFC 7986 and can map the Outlook category color to the COLOR attribute in [Outlook CalDavSynchronizer](https://github.com/aluxnimm/outlookcaldavsynchronizer/)

Since this is also supported in DAVdroid, see https://forums.bitfire.at/topic/1058/single-event-colors  and some Android calendar apps it would be really useful to be able to show/edit the COLOR in the Nextcloud calendar app for a seamless Outlook and Android integration!

**Comment by georgehrke** [comment]
Absolutely.

I'm still not sure how to map the colors from our rgb color picker to the list of css3 color names yet though. Any suggestions?

**Comment by tcitworld** [comment]
Since the list of possible colors is quite small, we can show a standard select element instead.

**Comment by georgehrke** [comment]
I already see people opening issues why we didn't use the same (full-featured) color-picker as in the left sidebar 🙈

**Comment by aluxnimm** [comment]
Not that small, around 150 possible colors. I needed to map those to the around 25 possible Outlook category colors and used some nearest color metric but not in the RGB space, since this is rather useless.

**Comment by juliushaertl** [comment]
This might be helpful for finding the nearest color value: https://stackoverflow.com/questions/17175664/get-the-closest-color-name-depending-on-an-hex-color/17176082#17176082

**Comment by sachaz** [comment]
Still interested by this feature ;)

**Comment by georgehrke** [comment]
@sachaz Please use the Use [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting +1, 👍 etc. These kinds of comments just unnecessarily notify everyone subscribed to this issue. Thx! :)

**Comment by jookk** [comment]
Really needed +1

**Comment by DiGGeR2** [comment]
Really needed too +1

**Comment by sachaz** [comment]
facebook "like" style ? ;)

**Comment by ediazcomellas** [comment]
Anyone willing to take this issue? I will double the bounty if it is done by end of april 2018.

**Comment by tlehmann7** [comment]
Is that still active?

**Comment by ccoenen** [comment]
- yes, it's still a thing people want
- no, nobody is working on it as far as I know

If someone wants to step forward with a pull request, I bet it would get merged.

**Comment by DiGGeR2** [comment]
YesLe 26 sept. 2018 10:59, tlehmann7 <notifications@github.com> a écrit :Is that still active?

**Comment by UralZima** [comment]
I also need this feature. Please implement it, it is very useful!
I want to create a moon calendar and have different colors for each moonday for easier planning your events according to moonphases and moondays.

**Comment by georgehrke** [comment]
Everyone, as I mentioned above already, please please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting +1, 👍 etc. These kinds of comments just unnecessarily notify everyone subscribed to this issue.

If this doesn't stop i will have to lock this issue. Thx.

**Comment by sachaz** [comment]
Hi I can add 50€ to this feature too if it can motivate some folk

**Comment by tcitworld** [comment]
Both next versions of Safari on MacOS and iOS [will include color pickers](https://caniuse.com/#feat=input-color) therefore we may be able to just rely on standard color pickers.

**Comment by ccoenen** [comment]
The picker seems not to be the issue, but the fact that you would need to convert this to one of the CSS3 color names: 

> The value is a case-insensitive color name taken from the CSS3 set of names, defined in Section 4.3 of [W3C.REC-css3-color-20110607].

As far as I know the browser integrated color pickers return rgb style strings as `value`. (Strings like `#FF0000`) which would not work (well, it _may_ work, but it would be against the spec).

The cite is from https://tools.ietf.org/html/rfc7986#section-5.9
The referenced w3c standard is this section here: https://www.w3.org/TR/2011/REC-css3-color-20110607/#svg-color

**Comment by aluxnimm** [comment]
Actually there exists an errata to that RFC which allows rgb values!
e.g. 
`COLOR:rgb(61\,211\,68)`
https://www.rfc-editor.org/errata_search.php?rfc=7986

**Comment by ccoenen** [comment]
I'm not sure about the errata system in IETF RFCs, but that one is in "reported" state. I don't believe this is wise to build on this, yet.

**Comment by aluxnimm** [comment]
I could add support for it in Outlook CalDav Synchronizer if Nextcloud uses it, but DAVx5 also only supports CSS3 names atm. I can ask in CalConnect mailing lists, if other vendors support it or plan to do so.
We have similar discussions about formatted description property and some vendors like Google calendar  just add HTML tags to the standard description property which should be plain-text according to RFC.

**Comment by IvanKazak** [comment]
> 
> 
> Hi,
> is it possible to add an Option, to change a meetings color in the calendar?
> (it is only defined by calendar-source colour as at the moment) ...sometimes there may be an important meeting and i want to make it stand out by red color for example...(without changing calendar). i think there should some color/Highlight function? any suggestions? maybe tags+a searchbox (filter) could also be great... #ux
> 
> There is a **[$50 open bounty](https://www.bountysource.com/issues/39954046-custom-color-per-event?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github).

I've added $10 more

**Comment by Doriphore** [comment]
i agree with this demand really important for organisation, I just can offer a smile  ;)

**Comment by brycefisher** [comment]
I'm potentially interested in contributing PRs for this feature. Is the COLOR field issue sufficiently clear for a PR to be considered?

**Comment by devillemereuil** [comment]
@brycefisher Maybe a good strategy would be some code updating the COLOR field according to the landing CATEGORY support, see #1540. Well, at least, linking those two, as the UI for categories will be there anyway.

**Comment by georgehrke** [comment]
Please don't mix up CATEGORY and COLOR, they are two fundamentally different properties.

**Comment by ccoenen** [comment]
also #1540 suggests that at a later stage some kind of visual element for categories might be added. A Category -> Color automation is probably not a good idea:
- you can have multiple categories. Which one wins?
- you can have other clients, so category could be set by a different entity that does not set `COLOR` at the same time
- someone could have set `COLOR` manually in addition to a category. Which would take precedence? What if the value in the `COLOR` field was set by the suggested automation and someone updated the category? You wouldn't have a way of knowing of the `COLOR` field was intentionally set or if it was set by an automation. In short: you don't know if you should overwrite it, or not.
- your ruleset might change. "Business is now black". Do you go back and update all your calendar events after-the-fact?

I think [thunderbird's approach (screenshot)](https://github.com/nextcloud/calendar/issues/71#issuecomment-248280751) is much more sane than tying `CATEGORIES` into `COLOR`.

**Comment by devillemereuil** [comment]
I see. My reasoning was that some clients (e.g. all Android clients, as far as I know) don't support CATEGORY but do support COLOR (at least some of them) and linking the two might help having a way to get the information transmitted (at least in a visual way) across clients.

It seems it opens a bigger can of worm than I anticipated... Oh well, it was a mere suggestion, sorry if it was a dumb one.

**Comment by georgehrke** [comment]
https://www.npmjs.com/package/css-color-names
https://www.npmjs.com/package/closest-css-color ?

**Comment by vince-from-nice** [comment]
I've added 15$ to the bounty but the total amount displayed on Github is not (yet) updated.

**Comment by juliushaertl** [comment]
Awesome. Yes, the bountysource github integration is broken since quite some time. I've updated the title manually for now.

**Comment by szaimen** [comment]
🎉

**Comment by vince-from-nice** [comment]
Georg, please claim your bounty :)

**Comment by sachaz** [comment]
I want to contribute to the bounty, how ?

**Comment by vince-from-nice** [comment]
There is a link to bountysource on the top of that page.
