### ISSUE TITLE
Show warning when detected timezone is UTC

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#711]
### Steps to reproduce
1. open Firefox
2. goto about:config
3. enable privacy.resistFingerprinting
4. open calendar app

### Expected behaviour
Calendar works just fine

### Actual behaviour
Calendar view (day / week / month) displays everything as UTC

### What to do now:
- [ ] research what parts about firefox are different in `privacy.resistFingerprinting` mode
- [ ] isolate the issue in our code - Is it our code or a dependency? 
- [ ] fix / report upstream

**Comment by georgehrke** [comment]
With Firefox 59.0b5, https://pellepim.bitbucket.io/jstz/ just gives me UTC.

And according to an admin in the firefox Channel of the Mozilla IRC, privacy.resistFingerprinting will make users appear to be in UTC:
https://mozilla.logbot.info/firefox/20180130#c14213397

So I would propose the following:
- implement #586 
- If we detect UTC, tell the user that this might be related to some privacy feature and ask them to set the timezone manually

**Comment by AshotN** [comment]
Why not default to the server timezone and allow individual users the ability to change in their respective settings

**Comment by georgehrke** [comment]
Default should always be detecting the users current time zone, because that works for most cases. 

If we can only detect UTC, because the user is using some anti fingerprinting mechanism, we should simply ask them to tell us their timezone.

Where should the server timezone come in here?
I really oppose abolishing our automatic timezone detection, because it works just fine in most cases.

**Comment by AshotN** [comment]
The automatic system would be fine if there was a manual override.

**Comment by georgehrke** [comment]
Yes, that's what this entire ticket and the ticket #586 i linked above is just about

**Comment by AshotN** [comment]
A temporary work-around is to just not use the NextCloud Calendar app interface. Rather link a separate program
