### ISSUE TITLE
improve the legibility of divided events

### ISSUE THREAD

**Issue by Berni-MD** [nextcloud/calendar#713]
NC 12.05 

How can I improve the legibility of events from shared calendars? 
Thus calendar with reading rights.

Can I put somewhere about css?
Nowadays the writing is so bright since that one can read almost nothing at all.

I would like to bring a calendar on my homepage online via NC,
but if the visitor goes then for the appointment, he needs really very good eyes :-)

++Lesbarkeit von geteilten Kalendern verbessern++
Wie kann ich die Lesbarkeit von Events aus geteilten Kalendern verbessern? 
Also Kalender mit Leserechten.

Kann ich das irgendwo über eine css einstellen?
Derzeit ist die Schrift nämlich so hell, dass man fast gar nichts lesen kann.

Ich möchte via NC einen Kalender auf meiner Homepage online bringen,
aber wenn der Besucher dann auf den Termin geht, dann braucht er 
wirklich sehr gute Augen :-)

**Comment by georgehrke** [comment]
Duplicate of #555
