### ISSUE TITLE
Expose iCal calendars as regular read-only caldav calenders

### ISSUE THREAD

**Issue by schiessle** [nextcloud/calendar#719]
I added a ical calender to my Calendar at Nextcloud. This works great in the web interface. Once I connect my Android with DavDroid to Nextcloud I also see the ical calendar but if I want to sync it with DavDroid I get a message that I need a additional app to handle ical calendars.

I wonder if it wouldn't be possible to hide from external apps the fact that it is a ical calendar and instead expose it via the CalDAV back-end as a normal calendar which is read-only?

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/1497 ;)
