### ISSUE TITLE
Is it possible to subscribe to/import calendars via command line?

### ISSUE THREAD

**Issue by tterranigma** [nextcloud/calendar#720]
I am trying to automate nextcloud installation with ansible and I was wondering if there is an option to add external calendars. I have found the `occ dav:create-calendar` option to create new calendars.

**Comment by tcitworld** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by tterranigma** [comment]
Followup [here](https://github.com/nextcloud/server/issues/8222)
