### ISSUE TITLE
Make it easier to navigate trhough months

### ISSUE THREAD

**Issue by enoch85** [nextcloud/calendar#727]
I'd like to add left and right buttons (on hover) in the right side calendar view, or even go to last or next month when pressing left or right with the keyboard arrows.

Easier to navigate IMO.

**Comment by georgehrke** [comment]
I'm not sure what you are referring to. All our datepickers have arrows to navigate through months:

![02acf8b6-a836-4c47-b9a5-659fc8ef0492](https://user-images.githubusercontent.com/1250540/36077205-e42abd64-0f67-11e8-95d6-dfff78382b14.jpg)
![f4422890-6b3f-40bd-9508-b480e8d9d37f](https://user-images.githubusercontent.com/1250540/36077206-e4568548-0f67-11e8-9ca0-b0a30892a41d.jpg)

**Comment by enoch85** [comment]
I meant something like this:

![screenshot from 2018-02-11 22 43 24](https://user-images.githubusercontent.com/4511254/36078912-4211244e-0f7d-11e8-89b5-9ce9b37d39ce.png)

**Comment by georgehrke** [comment]
What benefit would that have?

For better navigation we are planning #6

**Comment by enoch85** [comment]
So continuous scrolling by using the arrow keys?

**Comment by georgehrke** [comment]
Mouse scrolling and arrow keys

**Comment by enoch85** [comment]
OK, That's even better.
