### ISSUE TITLE
Pop-up and Audio calendar reminders aren't working in Chrome or Firefox

### ISSUE THREAD

**Issue by willbprog127** [nextcloud/calendar#729]
### Steps to reproduce
Using Chrome and Firefox on Debian Linux and Windows 7 SP1 64-bit, at 4:30 pm I…
* enabled pop-ups for my domain in the browser
* enabled notifications for my domain in the browser
* created a new event for 5:00 pm today in the Calendar app in the browser
* set an audio reminder for 5 minutes before the event
* set a pop-up reminder for 5 minutes before the event
* saved the new event

### Expected behaviour
An audio and also a pop-up notification should happen at 4:55 pm.

### Actual behaviour
No audio or pop-up notification happens.

### Server configuration

**Server Operating system**:
Ubuntu 16.04 32-bit

**Web server:**
Apache 2.4.18

**Database:**
MySQL 5.7

**PHP version:**
7.0.25

**Server version:**
* 12.0.5
* 13.0.0

**Calendar version:**
1.6.0

**Updated from an older installed version or fresh install:**
Fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):**
> No errors found.

**List of activated apps:**
* Activity	2.6.1 Official		
* Calendar	1.6.0		
* Collaborative tags	1.3.0 Official		
* Comments	1.3.0 Official		
* Deleted files	1.3.0 Official		
* Federation	1.3.0 Official		
* File sharing	1.5.0 Official		
* First run wizard	2.2.1 Official		
* Gallery	18.0.0 Official		
* Log Reader	2.0.0 Official
* Monitoring	1.3.0 Official
* Nextcloud announcements	1.2.0 Official		
* Notifications	2.1.2 Official		
* Password policy	1.3.0 Official		
* PDF viewer	1.2.0 Official	
* Share by mail	1.3.0 Official		
* Text editor	2.5.1 Official		
* Theming	1.4.1 Official
* Update notification	1.3.0 Official	
* Usage survey	1.1.0 Official	
* Versions	1.6.0 Official
* Video player	1.2.0

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.*SENSITIVE*.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "*SENSITIVE*",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
https

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
* Chrome 64.0.3282.119 on Debian Linux
* Firefox 58.0.2 (64-bit) on Debian Linux
* Chrome (latest 64-bit) on Windows 7
* Firefox (latest 64-bit) on Windows 7

**Operating system:**
* Linux 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64 GNU/Linux
* Windows 7 SP1 64-bit

#### Web server error log
* SENSITIVE *

#### Log file (data/nextcloud.log)
* SENSITIVE *

#### Browser log

```
www.* SENSITIVE *.com/:1 Error parsing header X-XSS-Protection: 1; 
mode=block, 1; mode=block: expected semicolon at character 
position 14. The default protections will be applied.
core.js?v=7845b140-0:7
 
JQMIGRATE: Migrate is installed, version 1.4.0
core.js?v=7845b140-0:1563 

Deprecation warning: use moment.updateLocale(localeName, 
config) to change an existing locale. 
moment.defineLocale(localeName, config) should only be 
used for creating a new locale See 
http://momentjs.com/guides/#/warnings/define-locale/ for more info.

DevTools failed to parse SourceMap:
https://www.*SENSITIVE*.com/nextcloud/core/vendor/purify.min.js.map
core.js?v=7845b140-0:3 

[Violation] Added non-passive event listener to a scroll-blocking 
'touchstart' event. Consider marking event handler as 'passive' 
to make the page more responsive. See 
https://www.chromestatus.com/feature/5745543795965952
vendor.js:23280 

Attempting to call a FullCalendar method on an element 
with no calendar.
vendor.js:23280 

Attempting to call a FullCalendar method on an element 
with no calendar.
core.js?v=7845b140-0:2 

[Violation] 'DOMContentLoaded' handler took 264ms
(index):1 

[DOM] Password forms should have (optionally hidden) 
username fields for accessibility: (More info: https://goo.gl/9p2vKq) 
merged.js?v=7845b140-0:318 

[Violation] Only request notification permission in 
response to a user gesture.

```

​

**Comment by georgehrke** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/51

**Comment by willbprog127** [comment]
So, the reminders section of each event is just a placeholder or fake?  I'm confused...

**Comment by georgehrke** [comment]
If you sync your calendar with your phone or some desktop application you will get notifications there

**Comment by willbprog127** [comment]
Ohh, I see.  Thank you. :+1:
