### ISSUE TITLE
Sub calendars or so

### ISSUE THREAD

**Issue by Limator** [nextcloud/calendar#731]
Hi at all,

this is not an issue, it is more an feature request.

We want to manage the holidays with an global holiday calendar for alle employees. Is there a way to have an calendar with subcalendars from all employees?
It would be nice to have a structure like this:
- Holidays
-- Lolo Ferrari
-- Uma Thurman
-- Franz Ferdinand
-- King Arthur
When all are activated everybody can see if anybody else has holiday etc. etc.

We could use a calendar with writing rights to everybody, but the problem are the wirting rights to everybody ^^ Everybody could edit or delete the holidays from everybody.

Thank you in advance.

Kind regards,
Herbert

**Comment by georgehrke** [comment]
> Is there a way to have an calendar with subcalendars from all employees?

No, that's not possible.
But you could have one calendar for each employee called  "Holidays - Lolo Ferrari", "Holidays - Uma Thurman", etc. 

We use CalDAV and are thereby limited by the functionality of CalDAV. So we can't just implement new features like this out of the blue.

Such a feature is not supported by CalDAV, hence we can't implement it if we want to provide the same user experience among all clients (not just web, but also Thunderbird/Lightning,ios,macos,outlook calendar, etc.)

> Everybody could edit or delete the holidays from everybody.

In what kind of workplace are you if you can't even trust your coworkers not to remove your vacation from the calendar. ;) 

Did you check out the Activity app? It will show you who created / updated or deleted an event in a calendar.
