### ISSUE TITLE
Left menu doesn't appear on IE11 with NC13 and Calendar 1.6.0

### ISSUE THREAD

**Issue by jacestk** [nextcloud/calendar#732]
Hi, got bugs onto IE11 after fresh upgrade of version 13

It was not crashing with NC12 and Calendar 1.5.6

Help!!

### Steps to reproduce
1. click on calendar icon
2. the left menu appear fine
3. after 1s it is jerking (missing calendard names, colored dots,...)
3. click on a day case
4. clic "abort" from the panel of the new event
5. sometimes the menu appears fine

### Expected behaviour
The left menu should be ok

### Actual behaviour
The left menu does not appear

### Server configuration
NextCloud 13.0.0 fresh update

**Operating system**:
Centos 7.2

**Web server:**
Apache 2.4

**Database:**
mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64)

**PHP version:**
PHP 7.1.13 (cli) (built: Jan  3 2018 11:00:58)

**Server version:** (see your admin page)
13.0.0.0

**Calendar version:** (see the apps page)
1.6.0

**Updated from an older installed version or fresh install:**
fresh update from 12.0.0.29

#### Browser log
DOM7011: Le code de la page a désactivé la mise en cache précédente et suivante. Pour plus d’informations, voir : http://go.microsoft.com/fwlink/?LinkID=291337
Fichier : calendar
HTML1300: Une navigation s’est produite.
Fichier : calendar
HTML1202: http:/xxxxxxxxxxxxxxxxxxx/index.php/apps/calendar/ fonctionne en affichage de compatibilité car l’option « Afficher les sites intranet dans Affichage de compatibilité » est sélectionnée.
Fichier : calendar
HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.
Fichier : calendar, ligne : 79, colonne : 21
HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.
Fichier : calendar, ligne : 91, colonne : 21
HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.
Fichier : calendar, ligne : 103, colonne : 21
HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.
Fichier : calendar, ligne : 115, colonne : 21
HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.
Fichier : calendar, ligne : 127, colonne : 21
JQMIGRATE: Migrate is installed, version 1.4.0
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
TypeError: L’objet ne gère pas la propriété ou la méthode « registerProtocolHandler »
   {
      [functions]: ,
      __proto__: { },
      description: "L’objet ne gère pas la propriété ou la méthode « registerProtocolHandler »",
      message: "L’objet ne gère pas la propriété ou la méthode « registerProtocolHandler »",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: L’objet ne gère pas la propriété ou la méthode « registerProtocolHandler »
   at Anonymous function (http:/xxxxxxxxxxxxxxx/apps/calendar/js/public/app.min.js?v=33e9d56d-15:1:2244)
   at a (http:/xxxxxxxxxxxxxxxxxxxx/apps/calendar/js/public/vendor.ie.min.js?v=33e9d56d-15:4:21154)
   at Anonymous function (http://xxxxxxxxxxxxxxxxx/apps/calendar/js/public/vendor.ie.min.js?v=33e9d56d-15:4:21972)
   at o (http://xxxxxxxxxxxxxxxxxxxxxxxxx/apps/calendar/js/public/vendor.ie.min.js?v=33e9d56d-15:3:31499)
   at pt (http://xxxxxxxxxxxxxxxxxxxxxxxx/apps/calendar/js/public/vendor.ie.min.js?v=33e9d56d-15:4:21912)
   at a (http://xxxxxxxxxxxxxxxxxx/apps/calendar/js/public/vendor.ie.min.js?v=33e9d56d-15:4:7685)
   at ce (http://xxxxxxxxxxxxxxxxxxxxxxxxxx/apps/calendar/js/public/vendor.ie.min.js?v=33e9d56d-15:4:7904)
   at le (http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/apps/calendar/js/public/vendor.ie.min.js?v=33e9d56d-15:4:7239)
   at Anonymous function (http://l81970"
   }

Attempting to call a FullCalendar method on an element with no calendar.
Attempting to call a FullCalendar method on an element with no calendar.

**Comment by georgehrke** [comment]
@skjnldsv Most likely related to your SCSS changes. Any chance you can check this? :)

**Comment by georgehrke** [comment]
@jacestk Can you please provide screenshots?

**Comment by jacestk** [comment]
Here you are!

![agenda](https://user-images.githubusercontent.com/1270552/36405815-09ff52fc-160c-11e8-931d-07a06f476eb4.jpg)

**Comment by skjnldsv** [comment]
Can you try to clear your cache please? :)

**Comment by jacestk** [comment]
No changes...

**Comment by tcitworld** [comment]
Can confirm. IE11 shows the html like this for some reason and then complains of tags endings not matching : 
```html
<li ng-repeat="item in calendarListItems | orderBy: item.calendar.order | calendarListFilter"
	class="app-navigation-list-item"
	ng-class="{
		active: item.calendar.enabled,
		'icon-loading-small': item.displaySpinner(),
		editing: item.isEditing() || item.displayCalDAVUrl || item.displayWebCalUrl
	}">
	<span class="calendarCheckbox app-navigation-entry-bullet"
	  ng-click="triggerEnable(item)"
	  ng-if="item.displayColorIndicator() && !item.calendar.hasWarnings()"
	  ng-style="{ 'background-color' : item.calendar.enabled == true ? item.calendar.color : 'transparent' }">
</span>
<a class="action permanent"
   ng-class="{'icon-error': item.calendar.hasWarnings()}"
   href="#"
   ng-click="triggerEnable(item)"
   title="{{ item.calendar.hasWarnings() ? warningLabel : item.calendar.displayname }}">
	{{ item.calendar.displayname }}
</span>
</a>
```

**Comment by skjnldsv** [comment]
span ending twice?

**Comment by tcitworld** [comment]
Seems so : https://github.com/nextcloud/calendar/blob/master/templates/part.calendarlist.item.php#L36

**Comment by jacestk** [comment]
on my old version:
`<a class="action permanent"
   ng-class="{'calendar-list-cut-name': item.calendar.isShared() || item.calendar.isPublished() }"
   href="#"
   ng-click="triggerEnable(item)"
   ng-show="!item.isEditing()"
   title="{{ item.calendar.displayname }}">
	<span class="icon icon-error"
		  ng-if="item.calendar.hasWarnings()"
		  title="Certains événements de cet agenda sont cassés. Merci de consulter la console JS pour plus d&#039;info.">
		&nbsp;&nbsp;&nbsp;&nbsp;
	</span>
	{{ item.calendar.displayname }}
</a>`

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/calendar/commit/c3c6666fcf140ad34a9ac71ace74069bca80e1eb

#blameskjnldsv

**Comment by georgehrke** [comment]
Is removing that span already fixing support for IE?

**Comment by tcitworld** [comment]
I unfortunately can't tell right now since IE can't access my dev env. But looking at the visual issue, it should.

**Comment by jacestk** [comment]
Nope still goes wrong... :(

**Comment by jacestk** [comment]
I can send a video of the effect...

**Comment by jacestk** [comment]
![ezgif-1-ba17a6c307](https://user-images.githubusercontent.com/1270552/36422488-a8031756-1655-11e8-8a88-43f3a12ca002.gif)
Here is the bug in action!

**Comment by georgehrke** [comment]
@skjnldsv This was fixed by your pull-request in the server as well, right?

**Comment by skjnldsv** [comment]
@georgehrke yes! Nonetheless, There is apparently a small issue on the today button, there must be a float issue around there that needs to be remove (blind guess, can't check right now)

**Comment by jacestk** [comment]
No news?

**Comment by skjnldsv** [comment]
@jacestk It's fixed in the next 13 update

**Comment by georgehrke** [comment]
> Nonetheless, There is apparently a small issue on the today button which shift the data up a bit, there must be a float issue around there that needs to be remove (blind guess, can't check right now)

@skjnldsv This will be fixed as well?

**Comment by skjnldsv** [comment]
@georgehrke needs a fix in calendar :)

**Comment by georgehrke** [comment]
This was fixed with the latest Nextcloud release + the latest Calendar release.
