### ISSUE TITLE
Feature request: Support external calendars

### ISSUE THREAD

**Issue by tuxis-ie** [nextcloud/calendar#733]
Nextcloud is great for sharing files, and supports Caldav & Carddav services in the process! This is great, but there is one feature missing, email. Other products are great for handling email, and support Caldav & Carddav in the proces! This is also great, but the feature of handling files is missing.

A possible solution would be for Nextcloud to support external Caldav calendars. Read/write would be enough. Sharing features would need to be handled by the originating product.

It would be so cool to make Nextcloud a one-stop-shop for users.

**Comment by tcitworld** [comment]
Nextcloud already supports handling CalDAV subscriptions from public WebCal files.

**Comment by tuxis-ie** [comment]
Yes. Readonly, unauthenticated?

**Comment by tcitworld** [comment]
Also, beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
