### ISSUE TITLE
New design for embedding shared calendar

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#741]
Follow up for discussion in https://github.com/nextcloud/calendar/issues/596

- put month name, view names, today button, current date(range), subscribe/download button on top
- use entire width of screen for calendar grid

**Comment by arunikayadav42** [comment]
Can I please work on this issue :) ?It seems quite an easy one

**Comment by georgehrke** [comment]
@arunikayadav42 Let's please finish one issue after the other :)

**Comment by arunikayadav42** [comment]
Can I now please get started with this one :) ?

**Comment by arunikayadav42** [comment]
Can I get started with this issue please @georgehrke :) ?

**Comment by georgehrke** [comment]
@arunikayadav42 Yes, you can work on this of you want to, but please not that #765 is not done yet.

**Comment by georgehrke** [comment]
We should start with some mock ups here first
@arunikayadav42 Feel free to post some mock ups

**Comment by alexanderdd** [comment]
@arunikayadav42 I would also love to see some mock-ups.
(Looks like the other issue that was mentioned above is now solved)

**Comment by georgehrke** [comment]
Implemented in https://github.com/nextcloud/calendar/pull/926
