### ISSUE TITLE
Calendar does not scale well on iPad. The calendars in left hand column not visible

### ISSUE THREAD

**Issue by rollanders** [nextcloud/calendar#742]
### Steps to reproduce
1. Open NC13 in Safari on iPad
2. Open Calendar
3.

### Expected behaviour
The names of the calendars in the left hand column should be visible 

### Actual behaviour
The names of the calendars are not visible

![20180225_200330](https://user-images.githubusercontent.com/36486009/36645384-289b91ac-1a68-11e8-9360-ff4fc6818452.jpg)

**Comment by georgehrke** [comment]
@skjnldsv Any chance you can check the misaligned icons? Looks related to the IE issue.

@rollanders iOS natively supports CalDAV. Generally I recommend just using the native Calendar app, as mobile support is not a priority at the moment.

**Comment by skjnldsv** [comment]
Did you tried clearing your cache ? :)

**Comment by skjnldsv** [comment]
This requires a server fix!
See https://github.com/nextcloud/server/pull/8573
