### ISSUE TITLE
No event created for attendees, invited from shared calendar

### ISSUE THREAD

**Issue by pinowthebird** [nextcloud/calendar#746]
### Steps to reproduce
1. Create new event
2. Assign to shared calendar
3. Invite attendees

### Expected behaviour
Add event to calendar of attendees.

### Actual behaviour
No event for attendees.

**Comment by georgehrke** [comment]
As our issue template states: Issues belonging to the CalDAV server belong into the server repo.

Furthermore there already happens to be an issue for this: https://github.com/nextcloud/server/issues/3830
