### ISSUE TITLE
Use webcals URI scheme when accessing via HTTPS (PFS directive)

### ISSUE THREAD

**Issue by Somebodyisnobody** [nextcloud/calendar#748]
### Steps to reproduce

1. Create and share a calendar
2. Open shared calendar
3. Click right on "subscribe" to copy the link of the button and paste it somewhere to take a look on it.

### Expected behaviour
Nextcloud applies PFS to the webcal-link and forms it into an webcals-link

### Actual behaviour
If i access via TLS the subscribtion link is still webcal://

I cannot find an offical URI scheme but all of my clients does support the webcals://-sheme
Some examples:
- CalDAV for Android
- WebcalSync
- Thunderbird (acc. to serverlog)
- Outlook (acc. to serverlog)

@georgehrke said in https://github.com/nextcloud/server/issues/8039#issuecomment-361098617

> What the calendar app does for webcal is the following: try https, if that fails, fall back to http. And that's pretty much what I expect from any other webcal client.

I tested that with Outlook:
My server is running on TLS at port 444 (DNAT because of internal routes), so my scheme is webcals://my.domain:444/remote.php/dav/.....
- If i enter webcal://my.domain:444/remote.php/dav/..... Outlook just does nothing, webserver logs "400 (Bad request)"
- If i enter the webcals:// version Outlook wizard continues.

So in fact what Georg expects from other webcal clients isn't what other developers think... 😯 😞 
Considering the unofficial support of "webcals://" and the Outlook-test it would be appropriate to apply PFS accordingly and use webcals:// when accessing via HTTPS.

### Server configuration

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.2

**Server version:** 13

**Calendar version:** 1.6.0

**Updated from an older installed version or fresh install:** updated

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** newest FF

**CalDAV-clients:** Thunderbird, WebcalSync, CalDAV and infrequently Outlook

**Comment by georgehrke** [comment]
PFS = Perfect forward secrecy?

**Comment by georgehrke** [comment]
- [ ] but that also means that we have to support `webcals` ourselves

**Comment by Somebodyisnobody** [comment]
> https://github.com/nextcloud/calendar/issues/748#issuecomment-369743506

Yeah i meant Perfect forward secrecy.

**Comment by arunikayadav42** [comment]
Can I please get started with working on this issue?

**Comment by Somebodyisnobody** [comment]
Sorry for the stupid question but what are you waiting for (or who's asked)?

**Comment by arunikayadav42** [comment]
could you please help me get started with the same please :)

**Comment by Somebodyisnobody** [comment]
how could I help you? I can partially read PHP but otherwise I'm more of a logic person.
How can we both work on a snippet of code?

**Comment by arunikayadav42** [comment]
Like please tell me what file contains the bug :)

**Comment by georgehrke** [comment]
You can just search the code for `webcam://`. That should lead you to the correct file. 

I‘m not sure whether this issue is in a php or a JavaScript file.

**Comment by Somebodyisnobody** [comment]
Ok i searched in the rep for "webcal" and in my browser for "webcal://"
Seems that [calendar/js/app/utility/webcalUtility.js](https://github.com/nextcloud/calendar/blob/49b48a745960fee4ff8e22a17e57a4eb3cf828ea/js/app/utility/webcalUtility.js) is just for importing calendars into nextcloud. It replaces webcal:// to https:// like @georgehrke said.

But i found something by searching for "subscribe" that is written in php: 
https://github.com/nextcloud/calendar/blob/17e69514ec0dbd1aa525bde59caf2c76ff352f69/templates/public.php#L12-L15

Maybe this is an approach for you.

**Comment by arunikayadav42** [comment]
cool @Somebodyisnobody I will look into it :)

**Comment by Somebodyisnobody** [comment]
@arunikayadav42 do you have news for us?

**Comment by Somebodyisnobody** [comment]
"webcalURL" is defined in https://github.com/nextcloud/calendar/blob/28dc8bf407fc52cc6f8c08af94f2ad66c5b99dfc/controller/viewcontroller.php#L226

**Comment by arunikayadav42** [comment]
I am still looking into the same.Need two more days please due to some technical glitches :)

**Comment by georgehrke** [comment]
This has been fixed in #926 

https://github.com/nextcloud/calendar/blob/master/src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue#L154L159
