### ISSUE TITLE
Label "Personal" not translated wenn new calendar added to sharees

### ISSUE THREAD

**Issue by daCaPo** [nextcloud/calendar#749]
### Steps to reproduce
1. Create a new user (calendar "Personal" gets automatically created, labeld "Persönlich" in the German UI)

2. Share this calendar with another user or group with a German/non-English UI language

### Expected behaviour
The sharee should see the calendar title translated just like the owner (e. g., "Persönlich (Name)" in German)

### Actual behaviour
The calendar is shown as "Personal (Name)", wich might be misleading when using NextCloud in a company that runs an HR department ;-)

### Server configuration

**Database:**
MySQL

**PHP version:**
7.0

**Server version:** (see your admin page)
13.0.0

**Calendar version:** (see the apps page)
1.6.0

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by daCaPo** [comment]
Isn't this a client issue? Where does the translation happen? In the database, the label is "Personal" even when working with a German UI.

**Comment by georgehrke** [comment]
> Where does the translation happen?

It happens in the server. :)

> In the database, the label is "Personal" even when working with a German UI.

If the uri is `personal` and the displayname is `Personal`, then the name is localized on the fly.
