### ISSUE TITLE
Set the first day of the week to Monday

### ISSUE THREAD

**Issue by dan-cristian** [nextcloud/calendar#752]
Is it possible to add a Setting entry to change the first day of the week to be Monday?

**Comment by georgehrke** [comment]
Please use the search before creating a new issue. This issue has been reported many times already ;) 

The nextcloud server will introduce a region option instead.
https://github.com/nextcloud/server/issues/1781

**Comment by dan-cristian** [comment]
Thanks for the fast response. I tried search first but could not find this.
