### ISSUE TITLE
“Today” box contrast

### ISSUE THREAD

**Issue by raphaelbastide** [nextcloud/calendar#761]
The “Today” box currently have a `#fcf8e3` (light yellow) background colour. However, on my screen, I have real difficulties to discern it from normal days. I am sure other user with low quality / light power screen, or vision disorder, can experience the same. I suggest to make the Today box contrasting more with other days. I also suggest to add another graphic detail that identify today: e.g. make the day’s number in bold.

Before:  
![screenshot_2018-03-07_10-34-50](https://user-images.githubusercontent.com/193122/37084917-07388630-21f4-11e8-96da-a90a580cfc56.png)

After:  
![screenshot_2018-03-07_10-40-26](https://user-images.githubusercontent.com/193122/37084925-0c0dadfc-21f4-11e8-874d-113dd5d359e5.png)

**Comment by georgehrke** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Contrast is indeed pretty low :/

**Comment by jancborchardt** [comment]
Relevant pull request (which needs help) is at https://github.com/nextcloud/calendar/pull/818 :)

**Comment by LuftschloesserUser** [comment]
Would someone be so kind and point me to the file which contains the color code?
I tired different color codes in all files I could find, but none seemed to have effect on the actual background color.

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/pull/850 added a circle around the day number.

Calendar 2 will completely abolish the today color, because it's causing too much trouble in dark mode and the coloured circle is a good indicator:
![7BDE4EC9-EEB3-4202-B868-A4BBDCA77F4B](https://user-images.githubusercontent.com/1250540/64857416-bf68e480-d624-11e9-8551-29042d5d4ee9.png)

**Comment by raphaelbastide** [comment]
After an update to 25.0.1, I am still experiencing a very low “Today” box contrast with the dark theme. 

![Screenshot_2022-11-28_17-47-40](https://user-images.githubusercontent.com/193122/204335615-74f96803-8810-43f2-85e7-d0b6ce817fa0.png)
