### ISSUE TITLE
Davdroid is not syncing with NC13 

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/calendar#762]
Is only me that is facing problems with NC13 calendar synchronization with davdroid? 
I have the latest stable versions

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Server version:** (see your admin page)

**Calendar version:** (see the apps page)

**Updated from an older installed version or fresh install:**

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment]
If you have actual bug reports related to the CalDAV server, report them in the server repo please: https://github.com/nextcloud/server/issues
In case you open an issue there, please describe what issues you are facing and please actually use the issue template.

If you just have the question if other users are facing the same issue to find out whether its a general issue or just a configuration issue on your side ask on https://help.nextcloud.com please

**Comment by Ricardosgeral** [comment]
A think that maybe relevant to post here since I think the sync stop working maybe when I updated last version of calendar

**Comment by tcitworld** [comment]
It **really** shouldn't be linked, since the calendar app is only a CalDAV client such as DAVdroid. I advise you to : 
* Remove the account from DAVdroid and add it back again to try
* Test with other CalDAV-compatible clients
* Have a look at the DAVdroid forum for related issues.

If you can't find anything, then please file a bug on the server repo.
