### ISSUE TITLE
Wrong datetime format under zh-tw locale (probably zh-cn also)

### ISSUE THREAD

**Issue by fweng322** [nextcloud/calendar#763]
### Steps to reproduce
1. Change language to Traditiona Chinese (zh_TW)
2. Add/Edit an event on calendar
3. The date time format is '2018年03319' which is wrong

### Expected behaviour
The date time format should be '2018年03月19日'

### Actual behaviour
The date time format becomes '2018年03319'

![nextcloud1](https://user-images.githubusercontent.com/1000315/37238001-a92159d0-2457-11e8-853c-c7f2423fecb6.png)

**Comment by fweng322** [comment]
My version is Nextcloud 13.0.0 with calendar 1.5.8.  I changed all the zh-tw/zh-cn date time format defined in js/public/vendor.js and js/public/vendor.min.js from 'YYYY年MMMD日' to 'YYYY年MM月DD日' and it worked correctly.  However in the git there's no such files, which seems to be generated during installation.

**Comment by georgehrke** [comment]
@fweng322 Please search for duplicates before creating new issues ;) 
![7db63a6b-33c9-4846-ad7c-31b4f8e37bdc](https://user-images.githubusercontent.com/1250540/37241125-6277b4aa-2454-11e8-9231-496cfc2b5b42.jpg)

#534
