### ISSUE TITLE
css issue: fc-short events overlap with those following them

### ISSUE THREAD

**Issue by a14a** [nextcloud/calendar#767]
**Steps to reproduce**

    Upgrade to Nextcloud 13
    Open Calendar app
    Create a 30-minute event (styled fc-short)
    Create a second event immediately following it

**Expected behaviour**
Should have standard size, as it did in NC 12.

**Actual behaviour**
fc-short is a few pixels longer and therefore overlaps with the event after it, causing both to occupy less space, adding to visual clutter as if they were simultaneous.

![image](https://user-images.githubusercontent.com/37151990/37252931-8ebf740c-253b-11e8-97b1-6d629dafc1ac.png)

**Environment details**
*Operating system:* Debian Stretch (up to date)
*Web server:* nginx/1.10.3
*Database:* 10.1.26-MariaDB
*PHP version:* 5.6.30-0+deb8u1
*Nextcloud version:* 13.0.0
*Updated from an older Nextcloud/ownCloud or fresh install:* Upgraded from 12
*Where did you install Nextcloud from:* admin page / installer
*Signing status:* no errors upon signing: http://example.com/index.php/settings/integrity/failed reports "No errors have been found."
*Calendar version:* 1.6.1, 1.6.2 alpha
*Where did you install Calendar from:* apps page / updated after NC upgrade

*Browser:* Firefox 45 / Chrome 64 / Opera 51 / Samsung Internet 6.4.10.5
*Operating system:* Linux, Android 5

**Comment by georgehrke** [comment]
![7334bc64-6dff-452b-bdf2-fdfb99dd3248](https://user-images.githubusercontent.com/1250540/37253006-19fad0da-252c-11e8-9867-a819da67e56c.jpg)

I can't reproduce this.

@tcitworld @skjnldsv Can you produce this?

**Comment by a14a** [comment]
i'll set up a vanilla install to try and reproduce. mine is supposed to be vanilla though :)

The difference in the size of time grid event is visible in comparison:
![image](https://user-images.githubusercontent.com/37151990/37253984-1b41ed3e-254a-11e8-9e28-9715bb84e2f9.png)

I've attached the code blocks for the last screenshot, 
[events.txt](https://github.com/nextcloud/calendar/files/1800387/events.txt)

fc-short has `bottom: -209.8px`, while the normal event has `bottom: -205.4px` .

**Comment by georgehrke** [comment]
What kind of screen are you working on? 
I might not be able to reproduce this because i'm working on a HDPI screen.

**Comment by a14a** [comment]
Thanks for the quick feedback @georgehrke ! I have verified the issue on a vanilla install, it's still there. Also tested on a 13" FHD laptop running Win 10. 

However, it's somewhat intermittent, and i'm unable to locate a pattern yet. After a dozen iterations, i managed to have two fc-short events immediately following each other with normal width like your screenshot shows. Simply adding a third event immediately following them should demonstrate the issue; also, a longer event immediately following a single fc-short also does.

Here's a clean container showing the problem: http://185.72.156.4:8080/apps/calendar/ nktest nktest

![image](https://user-images.githubusercontent.com/37151990/37255898-2f58828c-2564-11e8-9700-60e599b91a8a.png)

**Comment by a14a** [comment]
As reported originally, this is caused by events being a few pixels too long. Turns out this is intentional:

```
js/public/app.js:2048

agendaEventMinHeight: 21
```

On my devices (including HiDPI ones) the 30-minute height is like 17 pixels, so they obviously overlap if the minimum setting exceeds that. It's up to you to decide why that minimum setting is required in the first place, i'll be testing with it set to 5 just to see if any events really get that small - but i don't really think the min height setting is necessary at all.

**Comment by a14a** [comment]
i've been running my test system with agendaEventMinHeight: 5 for 9 months now, and can confidently say the issue never surfaced on any of my platforms, so give it a shot!

**Comment by divansantana** [comment]
@a14a strangely still have the issue after editing `/var/www/nextcloud/apps/calendar/js/public/app.js` and making that change.

Either way, would think this would bug more people and someone would fix it.

**Comment by severinkaderli** [comment]
I also have this issue running NC 16.0.3 and it is quite annoying.

![image](https://user-images.githubusercontent.com/3110114/61316270-ea8baf00-a800-11e9-9d85-3e6a9918af49.png)

**Comment by georgehrke** [comment]
I hope the update to full calendar 4.0 will solve this.

@severinkaderli What's really weird in your case is that event1 and event2 don't have this issue, but event2 and event3 do, although all of them have the same length.

**Comment by st3iny** [comment]
I can't reproduce this anymore. Seems to have been fixed.

![image](https://github.com/user-attachments/assets/3199fa61-0ad0-4851-bc5f-490117f4947a)
