### ISSUE TITLE
Shared calendar broken after privacy status switch

### ISSUE THREAD

**Issue by AlexanderSchaper** [nextcloud/calendar#768]
### Steps to reproduce
1. User A has calendar A (not default calendar) which is shared with group RW_A. Group RW_A is checked to edit calendar A.
2. User B, member of group RW_A, adding entries to calendar A with title, description and "if shared show full entry", which is default.
3. Calendar A is shared via link by user A, too.
4. Now User B changes one entry from "if shared show full entry" to "if shared only show busy" User B sees "Busy" for this entry. User A sees still the full entry.
5. User B changes this entry back to "if shared show full entry". Now User A and B seeing "Busy" and the entry is empty -> overwritten - all informations are gone, except time and date.

### Expected behaviour
1. User with read write access to a calender should still see the full entry. Only public shared link should show "Busy"
2. After resetting the entries visibility/privacy by user B, the entry should not be overwritten in NC. 

### Actual behaviour
Step 4. and 5. above.
User with read write access changes privacy of an entry and gets titel "busy". Changing it back overwrite the original entry and informations. New Title for all is "busy", all additional details are gone.

### Server configuration

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 13.0.0

**Calendar version:** 1.6.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from NC 12

**Updated from an older installed version or fresh install:** Update from 1.5.6

**Are you using external storage, if yes which one:** None

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Chrome, Firefox - all latest stable

**CalDAV-clients:** NC Webclient, Thunderbird 52.6.0 with Lighning 5.4

**Comment by georgehrke** [comment]
This is a duplicate, looking for the original topic ...

**Comment by georgehrke** [comment]
#657 / #658

**Comment by AlexanderSchaper** [comment]
Sorry, but this is not about importing a calendar. About new and shared entries which are changed in visibility/privacy.

**Comment by georgehrke** [comment]
Yes, #657 is about creating events with custom visibility in a calendar shared with you.
Fixing #657 also includes prohibiting editing events that are shown as busy only to you.

**Comment by AlexanderSchaper** [comment]
OK, thanks. Is there a roadmap for 1.8 where it should fixed or a general roadmap for calendar?

**Comment by georgehrke** [comment]
You can see our roadmap here: https://github.com/nextcloud/calendar/milestones

There is a good chance it will be fixed earlier though, but this issue will probably require some modifications to the Nextcloud server.

It all comes down to one issue: A calendar object belongs to a calendar and a calendar has exactly one owner.
Hence the visibility rule is always treated as if the owner created the calendar object.

So I have to do some research what the calendar standard says about this and how other CalDAV servers handle this:
- Either we introduce ownership for each calendar object
or
- No one besides the owner is allowed to create events with a visibility other than public.

Most likely it's gonna be the second, given how CalDAV works.

**Comment by AlexanderSchaper** [comment]
Thanks for your information. :)
