### ISSUE TITLE
Order All-day events by calendar (and alphabetically within same calendar)

### ISSUE THREAD

**Issue by jgillet** [nextcloud/calendar#769]
Hi

It would be very nice to have an option to order the all-day tasks either 1) by calendars (and then alphabetically) or 2) alphabetically - all calendars mixed up (as the default behavior is!).

Lots of people are upset about the new version of Google Calendar as Google simply trashed that functionality, and those people are looking to a serious alternative! And... voilà! Would be great to get'em! ;-)

Cheers,
Jeremy

**Comment by georgehrke** [comment]
I like this idea. Actually (1) should be the default I think - no need to make it configurable.
(Once we allow ordering calendars in the sidebar, it should also reflect that order)

cc @nextcloud/designers 

It's also fairly easy to implement: https://fullcalendar.io/docs/eventOrder

**Comment by arunikayadav42** [comment]
Can I please work on this issue :)

**Comment by jancborchardt** [comment]
Good call @georgehrke – alphabetical sorting definitely makes no sense, and ordering by calendar order is proper. (And yes, no need for configuration. :)
