### ISSUE TITLE
Unable to delete one event in a repeating event list

### ISSUE THREAD

**Issue by rocky4546** [nextcloud/calendar#770]
### Steps to reproduce
1. Create a repeating event.  I did weekly, 10 times.
2. Delete the second event of the repeating events.  The display shows the date of the first event no matter which event is chosen
3. Review the events to see that all events have been deleted.  

### Expected behaviour
Tell us what should happen: Normally, the calendar app gives a choice to delete this one or all.

### Actual behaviour
Tell us what happens instead: It does not ask and always deletes all

### Server configuration

Use default configuration.  This is easy to reproduce.

**Operating system**:
Ubuntu 16.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.22

**Server version:** (see your admin page)
13.0.0

**Calendar version:** (see the apps page)
1.6.1

**Updated from an older installed version or fresh install:**
New Calendar install.  Upgraded Nextcloud install

**Signing status (ownCloud/Nextcloud 9.0 and above):**
Not sure what a signing status is...

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by arunikayadav42** [comment]
Is anybody working on this issue or can I get started with this one please :)

**Comment by georgehrke** [comment]
@rocky4546 please search for duplicates before creating new issues in the future

#7

**Comment by rocky4546** [comment]
Sorry about that.  I looked through the list twice and never saw the duplicate issue.  Looking through #7, it looks like other people associated with deleting repeating events also could not find it.  Maybe the title, although accurate for the change, could have included the word delete to help us find it better.  Just a thought.  I see it is close to being fixed.  Thanks for all the hard work.
