### ISSUE TITLE
Screenshots corrupted for https://apps.nextcloud.com/apps/calendar

### ISSUE THREAD

**Issue by scheinercc** [nextcloud/calendar#771]
### Steps to reproduce
1. go to https://apps.nextcloud.com/apps/calendar
2. no screenshots load
3. Check network tab and see 404 errors

<img width="563" alt="image" src="https://user-images.githubusercontent.com/817856/37317421-e1fa62f2-26b8-11e8-94b2-28dc49ae5f4c.png">

**Comment by tcitworld** [comment]
Linked to https://github.com/nextcloud/calendar/pull/738,

@georgehrke please update the apps page.

**Comment by georgehrke** [comment]
The issue is that i uploaded 1.5.8 after I uploaded 1.6.1
The tarball of 1.5.8 still links to the 1.png, 2.png, 3.png, 4.png, while the tarball of 1.6.1 already links to the new one.

As I don't want to upload a new release at the moment, the hot fix will be to create 1.png, 2.png, 3.png, 4.png
