### ISSUE TITLE
Possibility to organise User calendar in alphabetic Order

### ISSUE THREAD

**Issue by ad1rie1** [nextcloud/calendar#773]
Hello, 

It can be good to organise calendar user to Alphabetic order. 

As you can see, when we have many user is hard to find one specific user : 

![image](https://user-images.githubusercontent.com/1949622/37393053-5096b9c4-2770-11e8-9471-13554e5c34f4.png)

**Comment by georgehrke** [comment]
We are looking forward to make the calendar list sortable: #9 
Would that already fix your issue?

**Comment by ad1rie1** [comment]
yes :)
