### ISSUE TITLE
Send invite notifications through remote client (Thunderbird, Google Calendar etc.)

### ISSUE THREAD

**Issue by myset** [nextcloud/calendar#775]
### Steps to reproduce
1. Create new event into my calendar
2. Invite attendees 

### Expected behaviour
Considering "CalDAV Server Send invitations to attendees" is disabled.
I expected that NC delegate this task to the originator remote client calendar setup (Thunderbird, Google Calendar etc.)

### Actual behaviour
Notification email are not transmitted. Remote calendar client is not notified to handle invites or cancellations notifications. 

### Enhancement proposal
I propose you to introduce per-calendar option (checkbox) for remote client based invites or cancellation notifications (Ex. External client notification).

### Server configuration

**Operating system**:CentOS 7
**Web server:** Apache Httpd
**Database:** MySQL 5.6
**PHP version:** 7.1
**Server version:** 13.0.0 (stable channel)
**Calendar version:** 1.6.1
**Updated from an older installed version or fresh install:** No

### Client configuration
**Browser:** Mozilla Firefox
**Operating system:** Mac OSX 10.13.3, Android, Ubuntu 16.04
**CalDAV-clients:** Thunderbird 52.6 Lighting 5.4.6, Google Calendar

Thank you

**Comment by georgehrke** [comment]
This issue belongs in the server and there is a duplicate, looking for it ...

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/8423

**Comment by myset** [comment]
Ok georgehrke ...

I was consider it much more appropriate this issue in this repository.

Thank you for your great work
