### ISSUE TITLE
Missing name when using the dropdown for location -> contacts

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/calendar#776]
I am using nextcloud 13 on debian 8, lamp stack

I already menstioned in 
https://github.com/nextcloud/calendar/issues/367 but it seems considered a bug:

When I add an location from the contacts list, let's say : Aunt Betsy.
When I type Au it starts showing Aunt Betsy in the dropdown. When I select, I only get to see the address being set. The name "Aunt Betsy" is left out.

**Comment by pieter-groeneweg** [comment]
I take it that "Good First Issue" means something as something for beginners :)

I took a peak at the contactcontroller.php and in line 70 it shows:
`$address = trim(preg_replace("/\n+/", "\n", str_replace(';', "\n", $address)));`
I changed that to:
`$address = $name . "\n" . trim(preg_replace("/\n+/", "\n", str_replace(';', "\n", $address)));`

It appears to work. There probably is better or more consistent way, but still i liked to share..

**Comment by pieter-groeneweg** [comment]
How do you mean with javascript.. it is the $name that is missing from the addresses in when selected in the locations dropdown. How do I make that visible using javascript?

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/blob/v1.6.1/js/app/controllers/editorcontroller.js#L313

It would basically be item.name + newline + item.label

**Comment by georgehrke** [comment]
Or better here already: https://github.com/nextcloud/calendar/blob/v1.6.1/js/app/controllers/editorcontroller.js#L303

location.name + "\n" + location.label

**Comment by pieter-groeneweg** [comment]
so I was look for calendar/js/app/controllers/
I cannot get further than calendar/js/ and then the only folder is "public"... 
Only showing app*.js and vendor*.js files
and I am sure I am on 1.6.1

Am I missing something important here... I installed/enabled through apps admin...?
Maybe I am doing something wrong?

**Comment by georgehrke** [comment]
Yes, in order to change the javascript code you need to clone this git repository and run the make command to modify the javascript source code

**Comment by pieter-groeneweg** [comment]
Then I need to install and set that up that first... :(
No other way of testing this?

**Comment by AasthaGupta** [comment]
@georgehrke I'd like to work on this.
