### ISSUE TITLE
add some hints for best migration to nextcloud-calendar

### ISSUE THREAD

**Issue by DJCrashdummy** [nextcloud/calendar#777]
it is not a big issue, but it could save much time and headache (especially for newbies):

in advance i use nextcloud mainly as sync-server and its webGUI as fallback solution... now i had to move local calendars (with special recurring events and tasks) into the cloud and because i was also changing the client, i simply used the **import-function within nextcloud**, but then the **calendar was messed up**! :disappointed: (some events were present with the hint that this recurring-rule is not supported, but **some events completely vanished**!)

BUT when i create a new calendar in the webGUI, integrate it into the local client and then **move the events within the client** from the old calendar to the new one, **everything is fine** (and it seems also in the webGUI)! at least the ics-file downloaded via the webGUI is almost identical to the original ics-file. :relieved: 

i would suggest to include a mini migration-guide resp. hint for a flawless migration in the readme or at least at the wiki (although it seems not to be used that much)...!

**Comment by georgehrke** [comment]
>  i simply used the import-function within nextcloud

What did the import function show you? If events are missing, it probably told you that were where errors while importing.

> some events were present with the hint that this recurring-rule is not supported,

This hint is only about **editing** those rules. They should still be displayed correctly.

**Comment by DJCrashdummy** [comment]
> What did the import function show you?

i tried it with several calendars, and some were imported without any hassle, but the most problematic one kept the "importing-info" for ages (more than 15-20 minutes), although the calendar only contains a handful of entries. but after reloading, the calendar was displayed and seemed to be imported.
i also had a look at the admin-logs, but neither down to the info- nor debug-level, there wasn't even a word about it. (another sign, why i assumed it should have worked.)

> This hint is only about editing those rules. They should still be displayed correctly.

yes, this hint is displayed when opening the event, where you may edit it (if supported).
--> this is perfectly fine for me (as long as the event stays untouched, is synced anyway and can be edited with other clients - which all seems to be the case :+1:).
whats really problematic is, that **some events completely vanished**!

---
BUT i have to admit, i may have mixed some things in order to get everything working:
thinking once again about the whole process and its details, it may be possible, that **recurring todos caused some issues while importing** and the vanished entries may be a consequential error. :confused:

**Comment by georgehrke** [comment]
>  but the most problematic one kept the "importing-info" for ages (more than 15-20 minutes), although the calendar only contains a handful of entries. but after reloading, the calendar was displayed and seemed to be imported.

What are you referring to by importing-info? The progress bar? 

> whats really problematic is, that some events completely vanished!

Did the import show you some error message that the import failed for a certain number of events? 

> --> this is perfectly fine for me (as long as the event stays untouched, is synced anyway and can be edited with other clients - which all seems to be the case 👍).

Yes, the recurrence rule is only reset / change if you decide to edit the recurrence setting. Otherwise it stays untouched.

---

It would be really important to have the javascript error log / browser network log here to find out what kind of errors we are talking about.

**Comment by DJCrashdummy** [comment]
> What are you referring to by importing-info? The progress bar?

yes and no...:
![nextcloud](https://user-images.githubusercontent.com/26110463/37565676-cf879bbe-2aad-11e8-88d6-4500e5dd340d.png)

> Did the import show you some error message that the import failed for a certain number of events?

no, not any message at all! neither within the import-function nor in the nextcloud-logs.
as already said, the only "error-indicator" is the stalled import.

---

> It would be really important to have the javascript error log / browser network log here to find out what kind of errors we are talking about.

if you can give me some hints/advise/recourses how i can gather and provide this info (firefox & linux preferred) i'll do it with pleasure.

---

while retrying i noticed some interesting and irritating behavior:
- when i try to import the calendar in question, the first existing calendar is selected by default in the import-message (and everything seems fine)
- when i choose to create a new calendar, also everything seems fine
- BUT when i change the calendar to an other existing one (an empty and in nextcloud newly created one), in front of the drop-down a small (and a little but cut) exclamation mark shows up with the tool-tip "the file contains objects, which are not compatible with the chosen calendar"
- and when i change back to the first calendar (which was chosen by default without any notice), the notice stays there!

**Comment by DJCrashdummy** [comment]
additional i have to say: for sure, importing, editing and processing everything correct and not having to think about anything would be the ideal solution... but as a "quick workaround" i think of a hint - like described in my initial post - in the readme and maybe also in conjunction with this exclamation mark while importing (which is IMHO a kind of misleading), because the calendars seem to support the recurring-rules of the todos, only nextcloud may have problems displaying them?!
--> else my "alternative migration-process" from the initial post wouldn't have worked.

**Comment by DJCrashdummy** [comment]
and funny once again...
if i import the calendar (with recurring todos and alarms) into an existing calendar in defiance of the described exclamation mark, the import-process does NOT stall and the elements seem to get imported.
to check what didn't work i downloaded the ics-file from nextcloud and beside differences in the "calendar-header" which are present in all calendars from nextcloud, only in the `VALARM`-section were differences present:
the line `TRIGGER;VALUE=DURATION;RELATED=END:PT0S` was changed to `TRIGGER;RELATED=END:PT0S`.
