### ISSUE TITLE
Calendar Sorting

### ISSUE THREAD

**Issue by tomas-chrastina** [nextcloud/calendar#782]
Hi,

it would be helpful to add option/action to sort list of Calendars e.g:
- checkbox to do it automatically by selected order (A-Z/Z-A ?, ...)
- Actions to sort all records by specified order
- Action to sort list manually - Drag and Drop?

Thank you in advance for consider it.

--
Best regards,
Tomas.

**Comment by georgehrke** [comment]
Duplicate of #9
