### ISSUE TITLE
[Feature Request] Sync FROM external CalDAV/EAS Calendar provider

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/calendar#783]
I'd really like to use the Calendar app to aggregate a whole bunch of calendars that are provided by external servers (Zimbra/Exchange/Gmail, etc).

Now, I can't seem to find a way to do this, so I suspect this isn't currently baked in.

My understanding is the Calendar app primarily relies on CalDAV, but I would like it if it could also interface via EAS (Exchange ActiveSync). An open-source example of EAS serving is Z-push.

Is there any way we could get something like this going on? I'd love it if we could! :D

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/252

**Comment by BloodyIron** [comment]
@georgehrke oops! Sorry D:
