### ISSUE TITLE
Feature Request: Pick first day of week

### ISSUE THREAD

**Issue by Ox0000** [nextcloud/calendar#785]
### Steps to reproduce
1. Install & Activate Calendar
2. Navigate to Calendar
3. Select the display type to be 'week'
4. Observe how the week runs from Sunday to Saturday
5. Open 'Settings & import'

### Expected behaviour
There is a setting to set what the first day of the week should be (Sunday, Monday, Friday or wednesday for all I care) just like any other calendaring solution. This setting should be on a per-user basis.

### Actual behaviour
There is no such setting. I'm stuck with the US-ian way of doing weeks, namely Sunday -&gt; Saturday instead of - for instance - Monday -&gt; Sunday

### Server configuration

**Operating system**: Debian Linux

**Web server:** Apache

**PHP version:** 7

**Server version:** 13.0.1

**Calendar version:** 1.6.1

### Client configuration
**Browser:** Firefox (latest)

**Comment by georgehrke** [comment]
See https://github.com/nextcloud/server/issues/1781

We won't introduce this option but a region setting in the server that will influence the first day of the week.

**Comment by Ox0000** [comment]
That's reasonable. I'm looking forward to that region setting!
