### ISSUE TITLE
mehrere Kalender mischen

### ISSUE THREAD

**Issue by Berni-MD** [nextcloud/calendar#786]
### Steps to reproduce
1. Einbinden von Kalendern in eine Webseite, über Iframe

### Expected behaviour
Wenn man mehrere Kalender zur Online-Anzeige "mischen" könnte, 
dann wäre es z.B. möglich zusätzlich zu den eigentlichen Terminen auch
Feiertage und Ferien mit auszugeben.

### Actual behaviour
Es kann immer nur ein einzelner Kalender eingebunden werden.

### Server configuration

**Operating system**: NC 13.0.1

**Database:** SQLite

**PHP version:** 7.0

**Comment by georgehrke** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/708

Furthermore report bugs / feature requests in english please
