### ISSUE TITLE
use vue-router

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#787]
Follow up for #540 

When migrating to vue.js we should make use of vue-router.

We need some obvious routes like:
- `/edit/:editView/:calendar/:objectUri` (`:editView` being `popover` or `sidebar`)
- `/edit/sidebar/:calendar/:objectUri` (`:section` being `details`, `attendees`, `recurrence`, `reminders`, ...)
- `/new/:editView/:dtstart/:dtend`

Should we also offer routes for the following?
- `/:view/` (`:view` being `agendaDay`, `agendaWeek`, `month` and `list` in the future)
- `/:view/:start/:end` Especially interesting for list view, but also later on for other views when we have continuous scrolling
- ... 

Anything else we need routes for?

**Comment by tcitworld** [comment]
Things I can imagine but which will require more developments :
- a "view single event" route
- a route to display only one or multiple calendars (for iframes).

**Comment by georgehrke** [comment]
@skjnldsv We have certain routes that don't change the entire right area, but either only add a new element (sidebar) or a popover (editor / import). Is that also possible with vue-router?

**Comment by georgehrke** [comment]
> Should we also offer routes for the following?
> [...]
> - `/:view/:start/:end` Especially interesting for list view, but also later on for other views when we have continuous scrolling

this might be problematic after all, because if people bookmark the calendar app, they will bookmark a certain timeframe, which is not the expected behavior.

**Comment by tcitworld** [comment]
Yeah, but there's no way to pass these parameters from outside vue-router then (typically from other apps or public view).

**Comment by skjnldsv** [comment]
You can create a redirection then. Use the variables, store them and redirect to the main page while using the vars. That way you cannot directly favorite a redirection page and you keep the direct access behaviour.

**Comment by georgehrke** [comment]
@nickvergessen Do you need special routes for https://github.com/nextcloud/server/issues/11015 ?

**Comment by nickvergessen** [comment]
Well calendar is not high on the list for that atm, just a good example.
I think for now a link to the calendar app is sufficient.

For activities and notifications however a link to an event would be nice to have.
