### ISSUE TITLE
Unable import ISC Google calendar using version 1.4.0 and user quotas (known bug?)

### ISSUE THREAD

**Issue by danjde** [nextcloud/calendar#788]
HI Friends,
using Owncloud v.9.1.1-1.2 (installed via deb) on a Debian Jessie environment 
I'm experiencing problems importing a recent Google calendar ICS. This problem seems random and seems to be linked to the user quotas.

Eventually, as an attempt, for upgrade Calendar from 1.4.0 to the latest version compatible with Owncloud v.9.1.1-1.2 could you suggest the best way?

Many many thanks!

Davide
Italy

**Comment by schiessle** [comment]
I just tested it with Nextcloud 13 and Calendar 1.6.1 which works nicely.

> could you suggest the best way?

I would suggest to upgrade to Nextcloud. If you don't want to do it I would suggest to report it to ownCloud (https://github.com/owncloud/calendar) and hope that they are able to help you.

**Comment by danjde** [comment]
Ok, I consider the upgrade!

Thanks schiessle!


Davide
