### ISSUE TITLE
No Calendar app on Nextcloud 10.0.4?

### ISSUE THREAD

**Issue by danjde** [nextcloud/calendar#791]
Hi Friends,
I've upgraded Owncloud 9.1.1 to [Nextcloud 10.0.4](https://download.nextcloud.com/server/releases/nextcloud-10.0.4.tar.bz2), using occ and all is gone fine!
But now on the apps the Calendar it's not found!

Is it normal? It's not so important, only to understand, because on Nextcloud/Calendar page you write:

> In your Nextcloud, simply navigate to »Apps«, choose the category »Organization«, find the Calendar app and enable it. Then open the Calendar app from the app menu.

many thanks!

Davide

**Comment by tcitworld** [comment]
Upgrade at least to Nextcloud 11 to use the 1.5.8 version of the app, but we advise you to be on 13 anyway.

**Comment by trumpetboy101** [comment]
I also found it to be in Office and text, not Organization, on version 13.

**Comment by georgehrke** [comment]
As @tcitworld said, Nextcloud 10 is EOL hence we don't support it anymore.

**Comment by danjde** [comment]
> As @tcitworld said, Nextcloud 10 is EOL [..]

Well, in fact I've migrated to NextCloud.

Thanks.

davide
