### ISSUE TITLE
ModSecurity: Access denied with code 400

### ISSUE THREAD

**Issue by danjde** [nextcloud/calendar#792]
Using Nextcloud 10.0.4 and Calendar 1.5.3 on Debian Jessie VPS, obain this error, from "modsecurity":

```

[Sat Apr 07 20:06:29.349453 2018] [:error] [pid 15231] [client 123.123.12.12] ModSecurity: JSON support was not enabled [hostname "www.mysite.org"] [uri "/owncloud/index.php/apps/calendar/v1/config"] [unique_id "WskIpX8AAQEAADt-q9UAAAAK"]
[Sat Apr 07 20:06:29.349513 2018] [:error] [pid 15231] [client 123.123.12.12] ModSecurity: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "/etc/modsecurity/modsecurity.conf"] [line "61"] [id "200002"] [msg "Failed to parse request body."] [data ""] [severity "CRITICAL"] [hostname "www.mysite.org"] [uri "/owncloud/index.php/apps/calendar/v1/config"] [unique_id "WskIpX8AAQEAADt-q9UAAAAK"]
```

This error is generated only by Calendar app, not from the others.
Should I anyway install the latest [stable Calendar version](https://github.com/nextcloud/calendar/releases/download/v1.6.1/calendar.tar.gz) on Nextcloud 10.0.4?
Or whitelist  "/owncloud/index.php/apps/calendar/v1/config" from ModSecurity policy?

Many thanks again!

Davide

**Comment by georgehrke** [comment]
You should but be able to whitelist `index.php/apps/calendar/v1/config`.

Please note that we generally don't consider mod-security as supported: https://github.com/nextcloud/calendar/wiki/FAQs

**Comment by danjde** [comment]
> Please note that we generally don't consider mod-security as supported [..]

Yes, I know,

thanks anyway for your kind answer!

davide
