### ISSUE TITLE
Cannot view calendar in Chromium

### ISSUE THREAD

**Issue by benkibbey** [nextcloud/calendar#793]
### Steps to reproduce
1. Load the Calendar app in Nextcloud

### Expected behaviour
Should be able to see the calendar.

### Actual behaviour
Between the < previous and > next month selector is: {{ | dt datepickerFilter:selectedView }}. The Day Week Month and Today buttons are available but don't do anything.

**Operating system**:
Debian "Testing"

**Web server:**
Lighttpd 1.4.49

**Database:**
Postgresql 10.3

**PHP version:**
7.2

**Server version:**
git stable-13

**Calendar version:**
1.6.1

**Signing status (ownCloud/Nextcloud 9.0 and above):**
Failed due to permissions changes only.

### Client configuration
**Browser:**
Chromium 65.0.3325.146

Firefox 58 *does* work correctly.

**Operating system:**
Debian GNU/Linux (Testing) x86_64

**Comment by tcitworld** [comment]
There's no reason for it to work on latest Firefox but not latest Chromium. Have you checked your browser extensions and the browser logs ?

**Comment by benkibbey** [comment]
Just upgraded to Chromium 66.0.3359.26 (Debian testing) with the same results. Attached is the chromium debug log with a fresh user directory and without any extensions installed. Thanks.
[chrome_debug.log](https://github.com/nextcloud/calendar/files/1888168/chrome_debug.log)

**Comment by tcitworld** [comment]
Sorry, I meant logs inside Chromium (Ctrl + Maj + J probably).
Nextcloud logs may also be helpful.

**Comment by benkibbey** [comment]
OK. There wasn't anything in the nextcloud log. Below is the chromium log. I noticed there is now a Timezone setting in the Calendar app but I cant select anything and it is empty. I tried setting the Calendar 'timezone' config setting manually with 'occ' but have the same results with nothing in the Timezone setting selector.

core.js?v=4d5125a8-0:7 JQMIGRATE: Migrate is installed, version 1.4.0
core.js?v=4d5125a8-0:1563 Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
w @ core.js?v=4d5125a8-0:1563
y @ core.js?v=4d5125a8-0:1563
_a @ core.js?v=4d5125a8-0:1563
(anonymous) @ vendor.js:35816
(anonymous) @ vendor.js:35816
(anonymous) @ vendor.js:35816
t @ vendor.js:35816
(anonymous) @ vendor.js:35816
t @ vendor.js:35816
(anonymous) @ vendor.js:35821
t @ vendor.js:35816
(anonymous) @ vendor.js:35816
(anonymous) @ vendor.js:35816
(anonymous) @ vendor.js:35816
(anonymous) @ vendor.js:35816
vendor.js:7140 RangeError: Unsupported time zone specified undefined
    at Object.DateTimeFormat (/nextcloud/index.php/apps/calendar/native)
    at a (vendor.js:43567)
    at Object.c [as determine] (vendor.js:43778)
    at Object.getDetected (app.min.js?v=4d5125a8-0:4)
    at Object.<anonymous> (app.min.js?v=4d5125a8-0:1)
    at Object.o [as invoke] (vendor.js:2672)
    at c.instance (vendor.js:5781)
    at h (vendor.js:4944)
    at o (vendor.js:4280)
    at vendor.js:4280
(anonymous) @ vendor.js:7140
(anonymous) @ vendor.js:5874
$apply @ vendor.js:10235
(anonymous) @ vendor.js:916
o @ vendor.js:2672
o @ vendor.js:914
de @ vendor.js:934
le @ vendor.js:875
(anonymous) @ vendor.js:15525
j @ core.js?v=4d5125a8-0:2
fireWith @ core.js?v=4d5125a8-0:2
ready @ core.js?v=4d5125a8-0:2
I @ core.js?v=4d5125a8-0:2

**Comment by georgehrke** [comment]
> git stable-13

Wild guess: You installed the calendar from git as well?

**Comment by benkibbey** [comment]
Actually, no. The calendar version is 1.6.1 from the Nextcloud apps. I should try the git version as well, of course. I will get back to you.

**Comment by georgehrke** [comment]
> I should try the git version as well, of course. I will get back to you.

No, you shouldn't. (I won't work unless you run the make command)
I just thought you did because you also cloned the server from git.

Is there anything in the Nextcloud log?

**Comment by benkibbey** [comment]
With full debugging this is the only thing that may indicate something weird:

{"reqId":"909Kn8UA5kVaJ4oSV0Kr","level":0,"time":"2018-04-28T23:17:03+00:00","remoteAddr":"127.0.0.1","user":"--","app":"core","method":"GET","url":"\/nextcloud\/index.php\/login","message":"Scss is disabled for \/media\/caviar-files_enc\/var\/www\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.117 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"909Kn8UA5kVaJ4oSV0Kr","level":0,"time":"2018-04-28T23:17:03+00:00","remoteAddr":"127.0.0.1","user":"--","app":"core","method":"GET","url":"\/nextcloud\/index.php\/login","message":"Scss is disabled for \/media\/caviar-files_enc\/var\/www\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.117 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"909Kn8UA5kVaJ4oSV0Kr","level":0,"time":"2018-04-28T23:17:03+00:00","remoteAddr":"127.0.0.1","user":"--","app":"core","method":"GET","url":"\/nextcloud\/index.php\/login","message":"Scss is disabled for \/media\/caviar-files_enc\/var\/www\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.117 Safari\/537.36","version":"13.0.2.1"}

**Comment by gagbo** [comment]
I have the same behaviour on all browsers with Nextcloud 13.0.2 and a mariadb database.

Which logs can I provide to be more useful ?

Interesting note : I thought the caldav was broken since I noticed this bug after a painful migration from owncloud 9.1.5 to nextcloud 13.0.2, but I actually can synchronize calendars between my phone and KOrganizer using my nextcloud instance, so I think it's really "just" the application having some issues

**Comment by georgehrke** [comment]
@gagbo The same behavior with ` {{ | dt datepickerFilter:selectedView }}`?

Generally Nextcloud.log and javascript log would be great.

Do you have the same error:
`vendor.js:7140 RangeError: Unsupported time zone specified undefined
at Object.DateTimeFormat (/nextcloud/index.php/apps/calendar/native)
`

Can you execute this in your browser console and share the result with us please?
`document.querySelector('#fullcalendar').getAttribute('data-timezone')`

What timezone are you in? 
What does https://pellepim.bitbucket.io/jstz/ display?

**Comment by gagbo** [comment]
My issue (then again that has nothing to do with calendar) was this : 

- In my `config.php` I had set a path for the store downloaded apps which was different than the path to code
    * Nextcloud code (and root of the website with `index.php`) is at `/usr/share/nextcloud`
    * Store apps are stored at `/var/lib/nextcloud/apps` with an alias `/apps-appstore`
```php
apps_paths =>
    array (
        ...
        1 =>
        array (
            'path' => '/var/lib/nextcloud/apps',
            'url' => '/apps-appstore',
            'writable' => true,
        ),
    )
```

Now it becomes a little shady because I don't know enough of Apache to be sure that what I'm explaining is easily understandable, or true. I'll just explain it the way I understood it.

That means that whenever I want to access the apps from the appstore (calendar here), nextcloud will look for it under `${nextcloud_root}/apps-appstore/calendar/...`. And without any special setting, Apache will look for the files in `/usr/share/nextcloud/apps-appstore` folder, since it's the folder that's defined as `DocumentRoot`. To change this behaviour, I added the special alias with the correct path in my nexcloud.conf apache file : 
```conf
DocumentRoot /usr/share/nextcloud
Alias /apps-appstore /var/lib/nextcloud/apps
# Do the same with assets because I also wanted to externalize this
Alias /assets /var/lib/nextcloud/assets

# Make the directory readable (Using the same settings as with the root folder)
<Directory /var/lib/nextcloud>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow, deny
        allow from all
</Directory>
```
And everything works. I should probably not leave (even parts of) config from my server on the wild, so I'll delete this soon enough, but hopefully there's nothing too sensitive in these

**Comment by benkibbey** [comment]
I have made some progress. It was working in Firefox but I kept getting an "Unable to determine timezone. Setting to UTC" (or something similar to those words) banner so I set the timezone manually in the calendar settings then loaded the Calendar app in Chromium and all is well. Almost all anyway. The timezone selector in Chromium doesn't show anything.

Let me know if you need more info for help with fixing this for reals.
