### ISSUE TITLE
use FullCalendar navLinks

### ISSUE THREAD

**Issue by cptMikky** [nextcloud/calendar#796]
All newly created events are set to "All day Event" by default.

I don't know how about you, but a vast majority of my calendar events are **not** All day events.

I'd like the All day event to be unchecked when creating a new event.

**Comment by georgehrke** [comment]
@Mannshoch please see #184

**Comment by georgehrke** [comment]
@cptMikky You are aware that in the day and week view, you can just drag to create a time-range? 

Furthermore you can just click the disabled time input, without disabling all-day first.

**Comment by cptMikky** [comment]
@georgehrke I personally mostly use Month view and even though clicking seems to do what you describe, it's rather non-intuitive and doesn't work with keyboard, i.e. you cannot "tab" into the field.

**Comment by cptMikky** [comment]
It would, however, be quite neat to have the same drag capability in month view :) Just a narrow column in each day cell where one could simply drag in a pre-defined interval and steps (say 9-17, 30min steps, you get the point). The cells are big enough for this.

**Comment by georgehrke** [comment]
> It would, however, be quite neat to have the same drag capability in month view :)

You do have the same capability to create multi day events.

> Just a narrow column in each day cell where one could simply drag in a pre-defined interval and steps (say 9-17, 30min steps, you get the point). The cells are big enough for this.

What about events outside 9-17? what if you have only three events 10-10:15 10:15-10:30 10:30-10:45 10:45 - 11? They would be barely readable if you had that grid.

> doesn't work with keyboard, i.e. you cannot "tab" into the field.

Maybe we should introduce a keyboard shortcut.

cc @nextcloud/designers

**Comment by cptMikky** [comment]
@georgehrke 
> >     Just a narrow column in each day cell where one could simply drag in a pre-defined interval and steps (say 9-17, 30min steps, you get the point). The cells are big enough for this.
> 
> What about events outside 9-17? what if you have only three events 10-10:15 10:15-10:30 10:30-10:45 10:45 - 11? They would be barely readable if you had that grid.

You misunderstood - the narrow columnt would be just an input element, see the pink rectangle in the pictures below- one could click-drag inside the rectangle to create a timespan just like in day view, only smaller. An instant tooltip would probably be needed whenever one hovers above it with the time the current cursor position represent within that day.

![before](https://user-images.githubusercontent.com/10010448/39191992-6ca3cf8e-47d8-11e8-872f-839e667f7115.png)
![after](https://user-images.githubusercontent.com/10010448/39191994-6e6ff2ca-47d8-11e8-8be7-366a7a5d9e4a.png)

> Maybe we should introduce a keyboard shortcut.

wouldn't it be **much** easier to just leave the All-Day checkbox unchecked?

@jancborchardt 
Not even multi-day events usualy start and end at midnight on the respective starting and ending days. Also, I have yet to encounter a calendar client that would behave like this. Not a single app I have used, except Nextcloud/ownCloud calendar, forces all-day events on multiweek/month view and I don't see how would one expect such a behavior. I mean, how many times does one create end-to-end all day events, ever?

**Comment by georgehrke** [comment]
> > Maybe we should introduce a keyboard shortcut.

> wouldn't it be much easier to just leave the All-Day checkbox unchecked?

I see absolutely no issue with keyboard usage, because the tabulator index is the following:
1. Title
2. Calendar
3. All-Day checkbox
4. Start Date
5. Start Time
6. End Date
7. End Time

So if you want to create a timed event, you can simply hit the space key when you reach the all day check box while tabbing.

---

>  I mean, how many times does one create end-to-end all day events, ever?

I create them rather often. And if i create a timed event, i have to set a custom time anyway, so i don't see how one could save time here.

--- 

> one could click-drag inside the rectangle to create a timespan just like in day view, only smaller. An instant tooltip would probably be needed whenever one hovers above it with the time the current cursor position represent within that day.

I'm not sure about that proposal. Any input @nextcloud/designers ?

**Comment by cptMikky** [comment]
> I see absolutely no issue with keyboard usage, because the tabulator index is the following:
> ...
> So if you want to create a timed event, you can simply hit the space key when you reach the all day check box while tabbing.

I didn't know that unitl you pointed it out as there is no visual clue (at least in Firefox 59 and Chromium 66) that the checkbox is actually selected and the tab order is different from visual order which makes it even more counter-intuitive.

Also this doesn't make the problem go away, it just trades extraneous clicks for extraneous key presses while the original issue remains.

> > I mean, how many times does one create end-to-end all day events, ever?
> 
> I create them rather often. And if i create a timed event, i have to set a custom time anyway, so i don't see how one could save time here.

I don't, which ironcially makes the default being wrong in average case anyway.

**Comment by jancborchardt** [comment]
The proposal seems very finnicky and more confusing than discoverable.

How do Google Calendar and iOS Calendar do it?

**Comment by cptMikky** [comment]
The clickdrag proposal was just a wild idea.

Anyway, speaking of Google Calendar - it has different UI with reversed logic **but** it does something even better: it opens a day in Day View when clicking on the date. Nextcloud, on the other hand, immediately creates a new event regardless where in the day cell you click, which, together with default all-day, makes long-term planning a PITA.

If Nextcloud did this, the default all-day would be much less of an issue.

**Comment by jancborchardt** [comment]
How about in the month view we simply remember what was chosen last?

- By default it’s all-day events
- If in the new event dialog you uncheck »All day« the default is switched to the time – say 10:00 – 11:00 by default.
- When you create another event and check »All day« again, the default is switched to all day again.

**Comment by cptMikky** [comment]
Sounds reasonable. 

I like the Gmail date-click feature too though but I guess it deserves its own issue.

**Comment by jancborchardt** [comment]
@newhinton yes, that sounds great! :)

Are you coming to our conference in Berlin end of August btw? https://nextcloud.com/conf – there’s possibility of travel funding for contributors, infos on the page. :)

**Comment by newhinton** [comment]
@jancborchardt Yeah, a trip to berlin would be cool :D I will come over for a few days! :)

**Comment by newhinton** [comment]
@georgehrke I am currently stuck at implementing this. I propagate the state from the backend to javascript, via a div-tag (which in itself is a workaround, but i'd suggest that we take a look at this in my future-pull-request). After that i toggle the all-day-checkbox appropriately.
Sadly, this does not work. My research showed that the eventsettings are stored in $scope.properties. If i edit those values, the ui changes accordingly. However, it does get buggy after storing them, the values are changing after the save. 

I am observing the following:
- open the edit/new-popover
- check console-log where the current properties are shown
- keep values from default and save
- check console-log where the updated properties are shown
-> those two objects are the same
- reopen the same entry
-> now the object changed and the date- and allday-value to different ones

[Branch i'm working on](https://github.com/nextcloud/calendar/tree/feature/796/do-not-default-new-events)

**Comment by georgehrke** [comment]
We will have to implement [navLinkDayClick](https://fullcalendar.io/docs/navLinkDayClick) and [navLinkWeekClick](https://fullcalendar.io/docs/navLinkWeekClick) to properly work with routing
