### ISSUE TITLE
implement  a search function [$90]

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#8]

**Comment by georgehrke** [comment]
Using the ordinary search is unbearable slow, we need some changes to the CalDAV server here.

**Comment by MariusBluem** [comment]
> Using the ordinary search is unbearable slow, we need some changes to the CalDAV server here.

The changes are now there (https://github.com/nextcloud/server/pull/4098) ... What is the state here? @georgehrke

**Comment by georgehrke** [comment]
We can now implement a performant search with our CalDAV server. So we just need to implement it ;)

**Comment by MariusBluem** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=39064059)](https://www.bountysource.com/issues/39064059-implement-a-search-function?utm_source=39064059&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by georgehrke** [comment]
requires being able to link to events are dates
#21

**Comment by kakohari** [comment]
How is the data stored in the calendarobjects table, especially the calendardata field? Haven't found the table specs/documentation or the code storing it. It changed from NC10 -> NC11 I think, where in NC10 you have been able to find cleartext ics-data in the field.

**Comment by tcitworld** [comment]
It didn't change.

**Comment by kakohari** [comment]
From old backups I can say that OC seemed to use cleartext while NC seems to use "_binary" as seen in the latest sql dump. Correction: change might have been made from OC to NC, but not from NC10 -> NC11.

**Comment by georgehrke** [comment]
The column type might have changed, i don't recall, but the actual data we store in there was and is RFC 5545 based ical data.

**Comment by frommMoritz** [comment]
> There is a **[$30 open bounty](https://www.bountysource.com/issues/39064059-implement-a-search-function?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github).

By now the bounty has rissen to $60!

**Comment by WNYmathGuy** [comment]
I was just about to ask for this feature. :wink: Because of the delay between altering certain types of calendar events and them being rendered I tend to think I may have made a bad edit. I realize at that point that I have no tool to do a text search for the event.

I don't know if this would help but a calendar mode we don't have is the event list, where it's just a simple linear display of data for the calendar. Like an infinite scroll blog. Well if that display mode is possible, couldn't the search just be implemented on the displayed text? Filters for that rendering could be date range & simple buttons like a year, month, next 365 days, last 365 days, a logical named calendar, my events or shared events.

I feel like solving this problem is harder than it seems until a person starts to work on it.

**Comment by SuperSandro2000** [comment]
I just added another $10.

**Comment by alexanderdd** [comment]
@WNYmathGuy yes search results should be listed in agenda view IMO.

Does that mean that https://github.com/nextcloud/calendar/issues/402 needs to be fixed first, and only then search can be implemented?

**Comment by georgehrke** [comment]
Putting into backlog in favour of https://github.com/nextcloud/server/issues/20918

**Comment by SLYtiger16** [comment]
I and colleagues would be willing to add a decent bounty on this if this and duplicate #113 could be worked on...

**Comment by georgehrke** [comment]
@SLYtiger16 Please see https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943

**Comment by SLYtiger16** [comment]
@georgehrke is there an alternative method you wish to you to incentivize development on specific issues?

**Comment by georgehrke** [comment]
> @georgehrke is there an alternative method you wish to you to incentivize development on specific issues?

Actual code / pull-requests are the best contribution possible.

Regarding this issue in particular, i'm currently implementing nextcloud/server#20918, which will also solve this ticket.

**Comment by SLYtiger16** [comment]
@georgehrke which properties of an event will be indexed in a search for the Nextcloud/server PR?
Might I suggest at least summary, description, and attendees?

**Comment by georgehrke** [comment]
The following properties are being indexed already:
https://github.com/nextcloud/server/blob/4cac0f6895cf4bda4dda0b7cb3b843546eb0a952/apps/dav/lib/CalDAV/CalDavBackend.php#L136

We will use the following one for the search:
- Title of event
- Location
- Description
- Email of attendees
- Name of attendees
- Email of organizer
- Name of organizer

**Comment by SLYtiger16** [comment]
@georgehrke I was thinking about this and would like to ask, will this nextcloud/server PR add the ability to find an event via search just like files and folders displayed in a list, or will this allow the calendar view of events to be filtered to only events with matching properties? 
I personally find limited but beneficial use in the former and absolute daily need in the latter...

**Comment by georgehrke** [comment]
It will be a list for now, see https://github.com/nextcloud/server/pull/21971 for the current design.
I can't say for sure whether it will allow apps to implement their own "in-content" search later own.

**Comment by SLYtiger16** [comment]
Would it be antithetical to the future of nextcloud to implement a filter in the calendar separate from the unified search? A calendar view filter is beneficial when looking types of events or those with certain attendees or summary traits. It is most beneficial if results can still be visualized in the standard calendar formats by limiting the events rendered. I would not be opposed to opening a new issue anda loose attempt at a PR (not great with vue.js yet) as long as it would not be a waste of everyone's time.

**Comment by georgehrke** [comment]
The calendar should definitely implement the Unified Search with the list view, because that's the primary use-case for search. As a user, I want to be able to search the entire calendar, not just the current month. 

That's what this issue was always about.

If you want to discuss your filtering approach, please open a new issue, but I'm not sure it's a feature we will include in this app.

**Comment by alexanderdd** [comment]
> georgehrke I was thinking about this and would like to ask, will this nextcloud/server PR add the ability to find an event via search just like files and folders displayed in a list, or will this allow **the calendar view of events to be filtered to only events with matching properties?**
> I personally find limited but beneficial use in the former and absolute daily need in the latter...

filtering in week view (and day/month) would be **incredible**! @SLYtiger16 do you know any software or web service that does this? I could not find one..

It would allow to create digital signage boards for rooms in an office. Put name of the room in description of events, set the filter to that room name, display that page on a small tablet next to the door of the room. Wow!

**Comment by SLYtiger16** [comment]
@alexanderdd I wrote one for a proprietary program which also is utilizing fullcalendar.js.

It was SUPER easy, it was written is JavaScript and simply implements an `events_array.filter()` testing for a `string.toLowerCase()` match on the "search" input value vs. the `event.summary` `event.description` `event.location` and the properties of `event.attendees`.

It would be a super simple implementation which simply limits the events for a document rerender

**Comment by alexanderdd** [comment]
@SLYtiger16  I opened a separate issue for filtering as Georg suggested

**Comment by voarsh2** [comment]
This is closed but no search function?

**Comment by tcitworld** [comment]
There's a search function in Nextcloud 20 (Calendar App 2.1)
