### ISSUE TITLE
Don't let user share events via mail when no mailserver is configured

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/calendar#800]
Don't let user share events via mail when no mailserver is configured

![image](https://user-images.githubusercontent.com/16019165/38731802-16868c32-3f1c-11e8-8574-e7eb1a6c5f54.png)

**Comment by georgehrke** [comment]
@BornToBeRoot This is a difficult one. Depending on the configuration of your php installation, email might work out of the box without the need to configure anything in the admin panel.

@tcitworld How should we handle this?

**Comment by georgehrke** [comment]
@tcitworld ^

**Comment by georgehrke** [comment]
Closing, because we can't properly detect if the mail settings where properly configured.

**Comment by tcitworld** [comment]
Only way I see would be to have a confirmation step inside the test config email, and requiring sending a test email on each configuration change.
Is it worth it to open a bug against server ?
