### ISSUE TITLE
Change app id

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/calendar#802]
I've added some features to calendar app now I want to change application id so that modified calendar and base calendar can be installed side by side.  
I can build project successfully.  
What properties should be edited in order to make application runnable side by side with the original calendar?

**Comment by tcitworld** [comment]
Probably only ID inside `appinfo/info.xml`

**Comment by mehrdaad** [comment]
Tried it by I get error ``no app in context``. besides, Base directory should be renamed as calendar app is installed in calendar directroy.

**Comment by tcitworld** [comment]
Indeed, the app directory name should match the id.

**Comment by mehrdaad** [comment]
> Indeed, the app directory name should match the id.

It does. Also I have changed namespaces.  Also I have changed ``namespace`` property in info.xml

**Comment by mehrdaad** [comment]
@tcitworld I have no idea why this exception ``Class 'OCA\\\\DornaCalendar\\\\AppInfo\\\\Application' not      
 found`` occurs. This exception use to occur even before changin class name to ``DornaCalendar``

**Comment by mehrdaad** [comment]
Can anybody guide me please?

**Comment by mehrdaad** [comment]
@georgehrke It's almost a week I'm stumbling upon this. Can you guide me abit?

**Comment by georgehrke** [comment]
What did you rename the folder to? It might be an issue with capitalization.

**Comment by mehrdaad** [comment]
named both id and folder to dcalendar.  
Did get error then tried to change classNames too. No luck yet

**Comment by georgehrke** [comment]
And the current error message is `Class 'OCA\\\\Dcalendar\\\\AppInfo\\\\Application' not found`?

**Comment by mehrdaad** [comment]
yes

**Comment by georgehrke** [comment]
Did you try incrementing the version number to trigger an app update?

**Comment by mehrdaad** [comment]
yes upgraded to 1.8.0.  In next Nextcloud boot, It indicates it needs an update. Hit update wait. then go to apps page hit enable. then I get the same error

**Comment by georgehrke** [comment]
Then I've no clue what's causing it.

I'm gonna close this issue, because it's not related to the calendar app but to the modifications you applied to it. 

Please ask your question on IRC in our developer channel: #nextcloud-dev on freenode or on the developer section of our forum: https://help.nextcloud.com/c/dev

**Comment by mehrdaad** [comment]
@georgehrke alright thanks. just one question:  
Technically what should you change in order to change the app name?
