### ISSUE TITLE
Error: EPERM: operation not permitted, chmod

### ISSUE THREAD

**Issue by n0whereRuoxi** [nextcloud/calendar#808]
<img width="797" alt="screen shot 2018-04-25 at 10 31 56 am" src="https://user-images.githubusercontent.com/13626285/39252553-edb0836a-4873-11e8-882d-044f4de45cb1.png">
I am getting these error when I make. Don't know how to fix it.
I used 'sudo chmod ugo+wrx /var/www/html/nextcloud/ -Rf'

**Comment by tcitworld** [comment]
It seems your files are in `/home/cmsc435`... and not in `/var/www/html/nextcloud`.

**Comment by n0whereRuoxi** [comment]
fixed. Never chmod after make and make again, bad stuffs will happen
