### ISSUE TITLE
To get all events within a calendar using VEventService

### ISSUE THREAD

**Issue by n0whereRuoxi** [nextcloud/calendar#813]
The 'getAll' function in VEventService needs both start and end parameters to get all events in the time range. How can I get all events without specifying time range?
(i.e. what is the start and end of all time in MomentJS)

**Comment by georgehrke** [comment]
@n0whereRuoxi Such a method is not implemented at the moment. It's not uncommon for users who use calendar applications for years to have tens of thousands of events dating back many many years. 

If the calendar application loaded all events, it would take minutes to load the calendar grid.
Some servers may even timeout if you send a PROPFIND for all events including their calendar-data at the same time.

> How can I get all events without specifying time range?

You would have to implement a custom method for that in the VEventController.
