### ISSUE TITLE
Upgrade Fedora 26 to 27 breaks calendar Nextcloud app (maybe a problem with new version php-sabre-dav)

### ISSUE THREAD

**Issue by omerule** [nextcloud/calendar#814]
### Steps to reproduce
1. On Fedora 26: dnf install nextcloud , working for more than a year with calendar app
2. On Fedora 26: dnf upgrade to Fedora 27, in browser left pane won't display any calendar
3. On Fedora 27: downgrade php-sabre-dav-3.2.2-2.fc27.noarch > php-sabre-dav-3.0.9-4.fc26.noarch
4. Calendar are visible again

### Expected behaviour
See calendars in browser

### Actual behaviour
Calendars won't "load"  in left pane indicator keeps spinning...
And Android app complaining about unable to retrieve calendar 
### Server configuration

**Operating system**:
Fedora 27 arm
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7
**Server version:** (see your admin page)
10
**Calendar version:** (see the apps page)
1.4.1
**Updated from an older installed version or fresh install:**

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

### Logs
{caldav} Exception: 
{"Message":"HTTP\/1.1 404 Principal with name users not found","Exception":"Sabre\\DAV\\Exception\\NotFound","Code":0,"Trace":"
#0 \/usr\/share\/php\/Sabre\/DAV\/Tree.php(76): Sabre\\DAVACL\\AbstractPrincipalCollection->getChild('users')\
n#1 \/usr\/share\/php\/Sabre\/DAV\/Tree.php(71): Sabre\\DAV\\Tree->getNodeForPath('principals\/user...')\
n#2 \/usr\/share\/php\/Sabre\/DAVACL\/Plugin.php(341): Sabre\\DAV\\Tree->getNodeForPath('principals\/user...')\
n#3 \/usr\/share\/php\/Sabre\/DAVACL\/Plugin.php(396): Sabre\\DAVACL\\Plugin->getPrincipalMembership('principals\/user...')\
n#4 \/usr\/share\/php\/Sabre\/DAVACL\/Plugin.php(664): Sabre\\DAVACL\\Plugin->principalMatchesPrincipal('principals\/name')\
n#5 \/usr\/share\/php\/Sabre\/DAVACL\/Plugin.php(196): Sabre\\DAVACL\\Plugin->getCurrentUserPrivilegeSet(Object(OCA\\DAV\\CalDAV\\Calendar))\
n#6 \/usr\/share\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/DavAclPlugin.php(51): Sabre\\DAVACL\\Plugin->checkPrivileges('calendars\/name\/...', Array, 1, false)\
n#7 \/usr\/share\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/DavAclPlugin.php(81): OCA\\DAV\\Connector\\Sabre\\DavAclPlugin->checkPrivileges('calendars\/name\/...', '{DAV:}read', 1, false)\
n#8 \/usr\/share\/nextcloud\/apps\/dav\/lib\/Connector\/LegacyDAVACL.php(86): OCA\\DAV\\Connector\\Sabre\\DavAclPlugin->propFind(Object(Sabre\\DAV\\PropFind), Object(OCA\\DAV\\CalDAV\\Calendar))\
n#9 [internal function]: OCA\\DAV\\Connector\\LegacyDAVACL->propFind(Object(Sabre\\DAV\\PropFind), Object(OCA\\DAV\\CalDAV\\Calendar))\
n#10 \/usr\/share\/php\/Sabre\/Event\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\
n#11 \/usr\/share\/php\/Sabre\/DAV\/Server.php(1058): Sabre\\Event\\EventEmitter->emit('propFind', Array)\
n#12 \/usr\/share\/php\/Sabre\/DAV\/Server.php(980): Sabre\\DAV\\Server->getPropertiesByNode(Object(Sabre\\DAV\\PropFind), Object(OCA\\DAV\\CalDAV\\Calendar))\
n#13 \/usr\/share\/php\/Sabre\/DAV\/Server.php(1665): Sabre\\DAV\\Server->getPropertiesIteratorForPath('calendars\/name\/...', Array, 0)\
n#14 \/usr\/share\/php\/Sabre\/DAV\/CorePlugin.php(355): Sabre\\DAV\\Server->generateMultiStatus(Object(Generator), false)\
n#15 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\
n#16 \/usr\/share\/php\/Sabre\/Event\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\
n#17 \/usr\/share\/php\/Sabre\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\
n#18 \/usr\/share\/php\/Sabre\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\
n#19 \/usr\/share\/nextcloud\/apps\/dav\/appinfo\/v1\/caldav.php(88): Sabre\\DAV\\Server->exec()\
n#20 \/usr\/share\/nextcloud\/remote.php(165): require_once('\/usr\/share\/next...')
\n#21 {main}","File":"\/usr\/share\/php\/Sabre\/DAVACL\/AbstractPrincipalCollection.php","Line":118,"User":"name"}

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment]
@omerule The Fedora package is not maintained by us. Can you please report this to the corresponding maintainer?
