### ISSUE TITLE
Colors of events on public calendar are hard to read

### ISSUE THREAD

**Issue by SansPseudoFix** [nextcloud/calendar#815]
### Steps to reproduce
1. share a public calendar
2. create an event
3. access to the public link
4. click on an event

![calendar_color_event](https://user-images.githubusercontent.com/6507951/39584064-cbe3ad00-4ef1-11e8-9ac3-4b570d63cf42.png)

### Expected behaviour
A better contrast. 

### Actual behaviour
It's quite hard to read: `background-color: #ebebeb`, `color: rgba(0, 0, 0, 0.4)` and `opacity: 0.5` is a bit too much the same shade.

### Client configuration
**Browser:** Firefox 52.7.3, Firefox 61.0a1 and Chromium 66.0.3359.117

**Operating system:** Debian Stretch

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/issues/555

**Comment by SansPseudoFix** [comment]
Argh…Sorry about it.
