### ISSUE TITLE
Cannot customize color and name for exernal Calendars

### ISSUE THREAD

**Issue by SeLLeRoNe** [nextcloud/calendar#816]
### Steps to reproduce
1. Create a calendar or link an external one (ex: https://www.gov.uk/bank-holidays/england-and-wales.ics)
2. Edit the calendar and modify color and name and save
3. Reload the page, Custom color and Custom name has changed

### Expected behaviour
It should mantain custom name and custom color

### Actual behaviour
It define a color and a name the first time and it stick with it (or maybe got the name from the calendar URL, not sure)

### Server configuration

CentOS 7.4 64Bit

Nginx 1.13.10 as Reverse proxy for Apache 2.4.33

MariaDB 10.2.14

PHP 5.6.36

Not sure what "check your admin page" means, anyway latest version downloaded and installed today

Cannot find it, anyway installed today

Fresh install

```
No errors have been found.
```

**List of activated apps:**

```
>php occ app:list
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - checksum: 0.4.0
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - deck: 0.3.1
  - defaultlinkopen: 1.0.0
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_frommail: 0.1.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.7.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - quicknotes: 0.1.3
  - quota_warning: 1.2.0
  - richdocuments: 2.0.8
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
Disabled:
  - dashboard
  - encryption
  - user_ldap
```

**Nextcloud configuration:**

```
>php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.crazynetwork.it"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.crazynetwork.it",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
Chrome 64Bit 66.0.3359.139

Windows 10 64 Bit

#### Web server error log
```
No errors in webservers logs file
```

#### Log file (data/nextcloud.log)
```
No errors
```

#### Browser log
```
Insert your browser log here, this could for example include:

Console log from the browser:
Uncaught (in promise) Error: Updating calendar failed
    at app.js:5436
(anonymous) @ app.js:5436
Promise.then (async)
e.performUpdate @ app.js:739
fn @ VM653:4
i @ vendor.js:13216
$eval @ vendor.js:10200
$apply @ vendor.js:10230
(anonymous) @ vendor.js:13221
dispatch @ core.js?v=8d80a2f8-8:3
r.handle @ core.js?v=8d80a2f8-8:3

```

**Comment by georgehrke** [comment]
> Create a calendar or link an external one

So this applies to both writable calendars and read-only calendars / subscriptions? 

> Uncaught (in promise) Error: Updating calendar failed

This looks like an server related error. Are you absolutely sure there is no related entry in the Nextcloud.log / web servers error log? 

Can you check the Browser Network console to check what status code was returned by that request?

**Comment by SeLLeRoNe** [comment]
Hi George,
Yes, that happen to remote calendar which are read-only but also to the personal calendar hosted on nextcloud itself.

I am going to paste the logs from Nginx, Apache and Nextcloud all tailed togheter while I login, go to calnedar and try to change color and name and of course the network call which might fail:

And that's it, I have found the problem for an error that in the console I didn't see preiously, the option PROPPATCH wasn't allowed on the webserver, now it is and everything is working.

Sorry for the waste of time :)
Best regards

**Comment by ichbestimmtnicht** [comment]
I dont want to open an extra issue for this..

I would be neat to allow copying of at least the description of the subscribed calendar to inform friends or colleagues without a proper software about some events. Like the Meteor shower info from https://cantonbecker.com/astronomy-calendar-files/astrocal.ics today. All entries are greyed out, can't be marked neither copied....

I am using Nextcloud hosted on cloud.disroot.org (it's not a point of interest for this i think, but before you ask me for serverlogs....)

**Comment by georgehrke** [comment]
@ichbestimmtnicht Please comment in https://github.com/nextcloud/calendar/issues/555, this ticket is absolutely not related to what you are talking about.

Closing because it was a configuration issue of @SeLLeRoNe's server.
