### ISSUE TITLE
Allow editing location in the simple event editor

### ISSUE THREAD

**Issue by benwaffle** [nextcloud/calendar#817]
I tend to fill out the location for most events I add on my calendar. Would be great if i didn't have to click 'more' every time. What do other users/devs think?

**Comment by slideup-benni** [comment]
maybe this issue is related to xhttps://github.com/nextcloud/calendar/issues/584

**Comment by benwaffle** [comment]
No, it's not the same issue

**Comment by georgehrke** [comment]
Duplicate of #680
