### ISSUE TITLE
Wrong css ouput file name ?

### ISSUE THREAD

**Issue by blacksponge** [nextcloud/calendar#820]
Hello,
When accessing the app, the css of the application is not loaded. The application is looking for app.min.css but either in the release archive or when I build myself the output file is app.min.scss.

Nextcloud version : 10.0.4
Calendar version : 1.6.1
Nextcloud log:
```
{"reqId":"3pQWb5o1aOm7wXrVh+Zh","remoteAddr":"xx.xx.xx.xx","app":"calendar","message":"Could not find resource file \"\/apps2\/calendar\/css\/public\/app.min.css\"","level":3,"time":"2018-05-08T01:30:56+00:00","method":"GET","url":"\/apps\/calendar\/","user":"BlackSponge","version":"9.1.4.2"}
```

**Comment by georgehrke** [comment]
@skjnldsv

**Comment by skjnldsv** [comment]
@blacksponge the scss files are automatically compiled by the server.
It should be present into your data/appdata_xxxxxx/css folder :)

**Comment by blacksponge** [comment]
If I understand what your saying is that the app.min.css should be present in the data/appdata_xxx/css folder ? But I don't see such directory... Am I missing something?
```
# ls -la /usr/share/nextcloud/data
total 1132
drwx------. 11 web web   4096 Mar 21 20:01 ./
drwxr-xr-x. 15 web web   4096 Mar  5 14:14 ../
drwxrwxr-x.  3 web web   4096 Mar  3 12:52 admin/
drwxr-xr-x.  8 web web   4096 May  7 09:54 BlackSponge/
drwxr-xr-x.  2 web web   4096 Feb  3 01:21 files_external/
drwxr-xr-x.  8 web web   4096 Mar 23 11:49 guest/
-rw-r--r--.  1 web web    284 Mar  3 12:52 .htaccess
-rw-r--r--.  1 web web      0 Mar  3 12:52 index.html
-rw-r-----.  1 web web  51058 Mar  3 06:00 nextcloud.03032018.log
-rw-r-----.  1 web web 213316 May  8 03:30 nextcloud.log
-rw-r-----.  1 web web 104963 Feb 22 13:17 nextcloud.log.220218
-rw-r--r--.  1 web web      0 May  8 03:07 .ocdata
-rw-r--r--.  1 web web 352256 Mar  3 12:51 owncloud.db
-rw-r--r--.  1 web web  32768 Mar  3 12:51 owncloud.db-shm
-rw-r--r--.  1 web web  86552 Mar  3 12:51 owncloud.db-wal
-rw-r--r--.  1 web web 211121 Feb  3 02:15 themedbackgroundlogo
-rw-r--r--.  1 web web  36066 Feb  3 02:08 themedinstancelogo
```

**Comment by skjnldsv** [comment]
@blacksponge 
> Nextcloud version : 10.0.4

I just noticed my bad.
You're too much behind, you need to upgrade to at least stable12 to get the scss functionnality.
The calendar app is probably not compatible to earlier versions.

For security issues I suggest you upgrade to newer versions as well (13 is our latest)

**Comment by blacksponge** [comment]
Okay then I will do that, thank you for your help :)

**Comment by skjnldsv** [comment]
You're very welcome :)
