### ISSUE TITLE
Entry only "tentative" while entering with android instead of "confirmed" - normal?

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/calendar#823]
NC 13.02
Calendar 1.6.1
Samsung Galaxy Note 8 / Samsung Galaxy S7 (using Davdroid)

while entering an entry in the calendar, this entry will be shown as "tentative" in the web-interface (see screenshot). Is that normal, or can I switch to "confirmed" by default"??

![image](https://user-images.githubusercontent.com/6906390/39918426-b1d6cc7e-5510-11e8-90bd-0dd49d4d4bb5.png)

Thank you

**Comment by GLLM** [comment]
+1 for this.
Been on my wishlist for long : ability to choose if all new events are confirmed or to be confirmed !

**Comment by kangaroo72** [comment]
which mobile you're using?

**Comment by georgehrke** [comment]
@kangaroo72 What client do you use? 

The default in the Nextcloud calendar is confirmed. If it's set to tentative, your client must be setting that value.

**Comment by kangaroo72** [comment]
I've just encountered, that is a issue featured by Samsung :-(
Now I'm using "Business Calender Pro" - working nice with that app.
@GLLM can you confirm?

**Comment by georgehrke** [comment]
> Been on my wishlist for long : ability to choose if all new events are confirmed or to be confirmed !

@GLLM What's the use-case for that? This would only affect the web client. We won't change the value sent to us by clients.

**Comment by kangaroo72** [comment]
I can confirm now, that it's not an NC-Issue. The samsung-devs have done crap :-(
Recommendation is "Business Calendar Pro" as posted already - closing ...

**Comment by GLLM** [comment]
@georgehrke : indeed : Samsung. ETAR is not doing this crap ;-)

**Comment by libgradev** [comment]
Same here (Note 8, Android 9): Installed the standard Google Calendar.
