### ISSUE TITLE
Calendar e-mail reminders are not being sent

### ISSUE THREAD

**Issue by websafe** [nextcloud/calendar#825]
Calendar event reminders are not being sent.

1) Test e-mail in Nextcloud is sent and arrives as expected.
2) Cron is configured and run every 15 minutes
3) but about two updates ago no calendar event email-reminders are being sent.

Is this a common problem? Passwords are ok, connection from the nextcloud machine to the smtp server is OK (see 1) but the Calendar App is not sending reminders...

I'm on: **13.0.2**
Channel: **stable**
Background jobs: **cron**

**Comment by georgehrke** [comment]
If you set up a email reminder in the calendar app, you should see a warning that email reminders are not implemented yet. Is that warning not visible?

**Comment by StCyr** [comment]
Damned,

I've just been hit by the same issue right now :-(

**Comment by m-a-v** [comment]
Are there any plans to support this feature in the near future?

**Comment by TildeSlashC0re** [comment]
I could swear this was supported in the past. O_O
