### ISSUE TITLE
Default visibility for shared calendar

### ISSUE THREAD

**Issue by Loxeno** [nextcloud/calendar#827]
Hi,

Use case :
I want to populate my professionnal calendar and share my free/busy times with co-workers and partners.
For now, I can configure this with per event visibility, but can't configure it for a whole calendar, so I have to set it for EVERY event...

I want this to be shared via CalDAV or weblink.

It seems that it can be done with free/busy support, but can't find any documentation and I don't know if it fit my needs.

By advance, thank you.

**Comment by georgehrke** [comment]
The feature you are asking for is not implemented at the moment. I closed it, because #725 is exactly the same feature request.

**Comment by Loxeno** [comment]
Okay, thank you.

Does a roadmap exist ? Do you target a specific version of NC ?
When will it be accessible ?

**Comment by georgehrke** [comment]
As you can see in #725, we still consider it a proposed enhancement. Unlike an approved enhancement, there is no roadmap for it and it's not sure whether it will be implemented.
