### ISSUE TITLE
Feature request: Add trash bin and versioning for deleted calendars (and tasks)

### ISSUE THREAD

**Issue by GoetheG** [nextcloud/calendar#828]
Hey guys,

I am having a look at Nextcloud from a regular user perspective with a little technological experience. For me everythig has to be easy to use. This is the only way I think that open source software can really succeed. At this point I'd like to thank all the contributers here for their great work!

It can always happen that somebody deletes a calendar entry, a whole calendar and/or parts of a calendar entry. I a work routine this can be a disaster. Especially, if there's nobody who can restore the deleted and/or changed item. Therefore I'd like to suggest a trash bin for the calendar app. This could give the user the ability to restore a deleted entry by himself.

Is there a chance this function will be implemented in the future?

Thanks guys :)

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

There already is an issue for the trashbin: https://github.com/nextcloud/server/issues/1662

**Comment by GoetheG** [comment]
Thank you for your reply @georgehrke. The app is really getting better every quarter :).
