### ISSUE TITLE
Add a button to the Event to 'join Meeting' when an event has a URL

### ISSUE THREAD

**Issue by Peterede** [nextcloud/calendar#832]
I want to add a button to the event so that if it has a URL for a video conference the user can click a button to 'join Meeting'.  I am thinking I could add this in editor.popover.php:

		<fieldset class="events--fieldset pull-left" ng-if="is_meeting">
			<button ng-click="joinMeeting()" ng-if="!is_new" class="events--button button btn" type="button" tabindex="109">
				<?php p($l->t('Join Meeting')); ?>
			</button>
		</fieldset>
This would take the user to the meeting in the talk app.

**Comment by georgehrke** [comment]
We are already working on that in https://github.com/nextcloud/calendar/pull/565, you are very welcome to contribute :)
