### ISSUE TITLE
Bad  UX for ical entries

### ISSUE THREAD

**Issue by sanpii** [nextcloud/calendar#835]
### Steps to reproduce

1. Subscribe to a iCal calendar
2. Display an entry

The subscribed ical entries are readonly. Using the html attribute `readonly` cause two UX issues:

* I can’t select text in entry description (like url or adress) to copy/paste them ;
* the entry details are unreadable (low contrast), as you can see on the screenshoot (on firefox 60, but it’s the same on chromium).

![2018-06-04-184754_1676x989_scrot](https://user-images.githubusercontent.com/113045/40930964-c37332fe-6818-11e8-8cf0-997d0c6ad701.png)

**Comment by georgehrke** [comment]
Please search for existing issues before creating new ones ...
https://github.com/nextcloud/calendar/issues/555
