### ISSUE TITLE
Web-GUI: Delete calendar not possible on Firefox Mobile for Android, both mobile view or "view desktop page"

### ISSUE THREAD

**Issue by michaelof** [nextcloud/calendar#838]
Firefox Mobile for Android: latest version

--> Please let me know if you evaluate this as a Firefox issue, I'll open a Bugzilla issue for Firefox then <--

### Steps to reproduce
1. Create a calendar logged into NC via Firefox Mobile for Android
2. Try to delete newly created (or any) calendar:
- Tap on "..." for to-be-deleted calendar
- Tap on "delete"

### Expected behaviour
Calendar should be deleted, similar as it works e.g. with Firefox on Linux:
- after klick on "delete" a red counter is shown (3/2/1 secs, then Trash bin shown)
- when hover above red trash bin, popup shows "are you sure?"
- clicking on red trash bin deletes calendar

### Actual behaviour
- after tap on "delete" a red counter is shown (3/2/1 secs, then trash bin shown)
- sometimes, not always, popup is (partially) shown "sure?"
- click on red trash bin restarts counter, always.
So no chance to delete finally

### Server configuration

**Operating system:** Linux 4.12.14-lp150.12.4-default #1 SMP Tue May 22 05:17:22 UTC 2018 (66b2eda) x86_64
OpenSuse 15.0

**Webserver:** Apache (apache2handler)
2.4.33

**Database:** mysql 10.2.14

**PHP version:** 7.2.5
Modules loaded: Core, date, libxml, pcre, filter, hash, Reflection, SPL, session, SimpleXML, standard, xml, mysqlnd, apache2handler, bz2, ctype, curl, dom, mbstring, fileinfo, gd, gettext, iconv, imagick, intl, json, ldap, exif, mysqli, openssl, PDO, pdo_mysql, pdo_sqlite, zlib, posix, soap, sockets, sqlite3, tokenizer, xmlreader, xmlwriter, zip, Phar, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Updated a while ago from OC to NC

**Where did you install Nextcloud from:** unknown
OpenSuse rpms

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - audioplayer: 2.3.0
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.6
 - encryption: 2.0.0
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.2.1
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - drop_account
 - music
 - user_external
 - user_ldap

```
</details>

**Comment by Gatak** [comment]
I just tested this on Android 8 with Opera Flow browser on NC 13.0.5. Exactly the same issue. The counter just restarts when tapping on the thrash can.

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler Do you have the same issue in the Tasks app?

Yes, I see the same on the Task app with Safari on iOS11. Weird, that this only happens in mobile browsers.

**Comment by apoger** [comment]
Same here with Firefox 63.0.2 and android 9.

**Comment by StAn187** [comment]
Bug is still there 😢

**Comment by georgehrke** [comment]
@StAn187 Did you test version 2.0?

**Comment by georgehrke** [comment]
We actually changed the way undo a calendar deletion works in 2.0. Should work now, although i didn't test it yet.

**Comment by michaelof** [comment]
I've just tested with Calendar 2.0.0 on NC 18.0 .0, with Firefox for Android 68.3.0:

Issue is *** FIXED ***

Thank you !!!

**Comment by georgehrke** [comment]
@michaelof Thanks for testing.
In that case I will close this issue.

A backport to version 1.7.x is not planned.
