### ISSUE TITLE
Allow for .ics file export for sync with Outlook

### ISSUE THREAD

**Issue by c0fe** [nextcloud/calendar#843]
I would like to make a suggestion for a feature to add the ability for a user to extract a link to the .ics file so that they can add it into Outlook and other email clients for synchronized calendars. Right now there are solutions that are more unofficial ways to get around getting this done but nonetheless are a needless hassle for users.

**Comment by georgehrke** [comment]
> I would like to make a suggestion for a feature to add the ability for a user to extract a link to the .ics file 

you can just copy the download link in the three-dot-menu of each calendar. That link is just an ics file for your calendar.

If you are using outlook, i would recommend using the Outlook CalDAV synchronizer though: https://nextcloud.com/blog/nextcloud-offers-caldav-synchronizer-for-outlook-users/
