### ISSUE TITLE
shared public calendar can not be downloaded

### ISSUE THREAD

**Issue by tmuellerdatabay** [nextcloud/calendar#845]
### Steps to reproduce
1. login
2. go to calendar app
3. click on "share link" 
--> public access
4. it will open "https://DOMAIN.DE/index.php/apps/calendar/p/34kBLefeF5A6bigy/Prename-Lastname"
5. click on the right side on "download"
6 . Link: https://DOMAIN.DE/remote.php/dav/public-calendars/34kBLefeF5A6bigy?export
Message in Browser:

> This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.

### Expected behaviour
Download a calender as a ics file 

### Actual behaviour
We are getting responded: 

> This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.

### Server configuration
**Web server:** nginx/1.14.0

**Database:** mysql  Ver 15.1 Distrib 10.1.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

**Server version:** 13.0.3

**Calendar version:** (see the apps page)

**Updated from an older installed version or fresh install:**

**List of activated apps:**

Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - deck: 0.3.1
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_external: 0.4
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_external

**Nextcloud configuration:**
root@intel2-vm06:/srv/www/cloud.databay.de/nextcloud# sudo -u www-data php occ config:list system
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "ldapIgnoreNamingRules": false,
        "singleuser": false,
        "trusted_domains": [
            "cloud.databay.de"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": "2",
        "forceSSLforSubdomains": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": true,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "overwrite.cli.url": "https:\/\/cloud.databay.de",
        "instanceid": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome 67.0.3396.87 e.g., also all other browser.

**Comment by georgehrke** [comment]
> Server version: 13.0.3

You are using an outdated version. We fixed a bug related to this in 13.0.4.

**Comment by georgehrke** [comment]
Please speak up if this issue still exists in 13.0.4, will close this issue in the meantime
