### ISSUE TITLE
[Feature Request] Allow to remove readonly Elements from Webcal

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/calendar#846]
I added some Webcal into Nextcloud. Now I detect that not all events they ship are as interesting that I wish to keep them in my calendar. Please allow to remove/blacklist these entries.

**Comment by georgehrke** [comment]
👎 from my side

Reasons:
- It won't be compatible with clients that natively support caldav subscriptions
- many webcal providers randomly change the UID of events (if they assign any at all ...), so there is no precise way to store what events to remove / they will appear again very fast
- using regex or whatever to match titles would be an extreme overkill and no ordinary user would understand it.

@tcitworld What's your opinion?

**Comment by tcitworld** [comment]
:-1: too.

Better find or build a dedicated service to filter your WebCal feed (I'll look into it).

**Comment by Mannshoch** [comment]
From my point of view. The iCal I subscribed contain a UID and it seems it is unique. the PRODID entry tells me that https://github.com/iCalcreator is the app that generate this.
