### ISSUE TITLE
Datepicker overlaps calendarlist

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#85]
With latest merges, the date picker overlaps the calendar list. Blame me, I guess.

![calendar-datepicker-overlap](https://cloud.githubusercontent.com/assets/2197836/18793557/901673b6-81bb-11e6-9f32-86314bc5f22b.png)

**Comment by georgehrke** [comment]
No, blame me. I'm pretty sure this has to do with my scrollable fix :/ 
Do you want to look into it?

**Comment by georgehrke** [comment]
because I made the scrollable div absolute 🙈

**Comment by tcitworld** [comment]
Of course, but I didn't think of checking this. :-)

**Comment by tcitworld** [comment]
Maybe make the whole `#app-navigation` navigation scrollable.

**Comment by georgehrke** [comment]
@jancborchardt said only the calendar list itself should be scrollable.
Making the entire app-navigation scrollable would be the easier solution though

**Comment by tcitworld** [comment]
Also, clicking on date picker closes the side panel on mobile view. Work to do here. :-)

**Comment by georgehrke** [comment]
Yes, that's some issue caused by snap.js 👿

**Comment by raghunayyar** [comment]
This is working for me. Any specific configuration you talking about? @tcitworld

**Comment by georgehrke** [comment]
@raghunayyar Did you pull recently? 🙈

**Comment by raghunayyar** [comment]
Yes, I will five minutes back and did a grunt build as well :P

**Comment by tcitworld** [comment]
@raghunayyar  So it works without issues for you on master ? I have this on latest Firefox and Chromium. :(

**Comment by eppfel** [comment]
Not working here either..

**Comment by raghunayyar** [comment]
Damn, it doesnt work for me too. I hadn't updated my origin. Sigh.

**Comment by raghunayyar** [comment]
I will have a look this weekend.

**Comment by tcitworld** [comment]
@raghunayyar Did you have time to have a look ?

**Comment by raghunayyar** [comment]
Yes, its a PR now.
