### ISSUE TITLE
Importer should assign random UID to events without UID

### ISSUE THREAD

**Issue by r100gs** [nextcloud/calendar#857]
Import Issue of ics

When I try to import this calendar I get an error. Severel other ics files can be imported fine.
[Schnaittach_Sudetenstr_2018b.zip](https://github.com/nextcloud/calendar/files/2140241/Schnaittach_Sudetenstr_2018b.zip)
I am using Nextcloud 13.0.4 as an univention docker
Calendar is 1.6.1

Error in log:

Fatal | webdav | Sabre\DAV\Exception\UnsupportedMediaType: Validation error in iCalendar: A calendar object on a CalDAV server may only have components with the same UID./var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 801: Sabre\CalDAV\Plugin->validateICalendar('BEGIN VCALENDAR...', 'calendars/stefa...', true, Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response), true)[internal function] Sabre\CalDAV\Plugin->beforeCreateFile('calendars/stefa...', 'BEGIN VCALENDAR...', Object(OCA\DAV\CalDAV\Calendar), true)/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1094: Sabre\Event\EventEmitter->emit('beforeCreateFil...', Array)/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 529: Sabre\DAV\Server->createFile('calendars/stefa...', 'BEGIN VCALENDAR...', NULL)[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/apps/dav/lib/Server.php - line 287: Sabre\DAV\Server->exec()/var/www/html/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()/var/www/html/remote.php - line 164: require_once('/var/www/html/a...'){main}
-- | -- | --

**Comment by georgehrke** [comment]
ICS is technically invalid, because the events don't contain UIDs.

To be able to deal with ICS files like this, our importer should automatically assign UIDs if not given.

**Comment by georgehrke** [comment]
Implemented in https://github.com/nextcloud/calendar/pull/926
