### ISSUE TITLE
Not all calendars visible in Web-UI

### ISSUE THREAD

**Issue by sm8ps** [nextcloud/calendar#863]
### Steps to reproduce
1. Have five users in a group, each sharing a personal calendar with this group.
2. Verify in the Web-UI that these calendars are "there".

### Expected behaviour
The list of shared calendars should be scrollable and show all shared calendars (for personal calendars the same).

### Actual behaviour
The list of shared calendars seems incomplete unless a rather tiny screen resolution is used. This is not obvious at all (especially after 2 a.m.).

## Server configuration detail

**Operating system:** Linux 4.15.0-24-generic #26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018 x86_64

**Webserver:** nginx/1.15.1 (fpm-fcgi)

**Database:** mysql 10.3.8

**PHP version:** 7.2.7-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, inotify, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.4 - 13.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** TAR-ball

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - apporder: 0.4.1
 - audioplayer: 2.3.1
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.7
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_inotify: 0.1.2
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.2
 - impersonate: 1.0.4
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - ransomware_protection: 1.1.1
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - unsplash: 1.1.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - deck
 - encryption
 - files_markdown
 - lsd
 - ownpad
 - tasks
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "lxcnextcloud.okunterhof5.ch",
        "lxcNextCloud",
        "nextcloud.wildi.name"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/lxcnextcloud.okunterhof5.ch",
    "dbtype": "mysql",
    "version": "13.0.4.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "logtimezone": "Europe\/Zurich",
    "loglevel": "2",
    "log_rotate_size": 10485760,
    "skeletondirectory": "",
    "share_folder": "\/Mit mir geteilt",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "force_language": "de",
    "trashbin_retention_obligation": "disabled",
    "versions_retention_obligation": "disabled",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by tcitworld** [comment]
Could you give us your resolution and maybe a screenshot ?

**Comment by sm8ps** [comment]
10.6 inches (27 cm) 1920x1080[9] (208 ppi) screen with 16:9 aspect ratio. Due to the small size I run Firefox with 170% magnification.
## Screenshots with missing calendars
Magnification factor is 170%. User has two personal calendars and the list of shared calendars shows only three. I just realized that this list does have a scroll bar. Nevertheless, one calender is missing (see below). 
![auswahl_003](https://user-images.githubusercontent.com/3989424/42418496-1fd0fec0-82a2-11e8-9a2b-56dceb9b6c09.png)
Fully scrolled down; three shared calendars visible while there are four (see below).
![auswahl_004](https://user-images.githubusercontent.com/3989424/42418495-1fb37b5c-82a2-11e8-8a53-33ce3c0d9365.png)
## Screenshots with all calendars showing
Magnification factor is 150%. User sees all four shared calendars.
![auswahl_005](https://user-images.githubusercontent.com/3989424/42418494-1f91b6d4-82a2-11e8-8678-84a258eb0dc3.png)

**Comment by wiertz** [comment]
To be more precise: under certain circumstances (resolution?) the last, bottom of the list calendar is not visible in Firefox. I have the same issue on a Mac on current Nextcloud and Calendar versions. Safari correctly shows all calendars on the same system. It seems as if the last calendar might be covered by the "Einstellungen & Import" Div ("Settings & Import", div id "app-settings"), as the bottom of the scrollbar looks cutoff, too (see red arrow in attached image).

![broken calendar view](https://user-images.githubusercontent.com/19712668/44583413-7ccc3400-a7a5-11e8-8a51-fa2894e97daa.jpg)

**Comment by georgehrke** [comment]
@tcitworld This was fixed by https://github.com/nextcloud/calendar/pull/887, right?

**Comment by wiertz** [comment]
I just manually did the patch #887 on my system and it does fix the issue.

**Comment by tcitworld** [comment]
Yup, sorry for not closing.
