### ISSUE TITLE
When a user is set Disabled calendar appear in Shared calendar

### ISSUE THREAD

**Issue by ad1rie1** [nextcloud/calendar#866]
### Steps to reproduce
1. Create user and add event to calendar
2. share the calendar with other people
3. Disable the user, the shared calendar is visible

### Expected behaviour
The calendar diseapear of shared calendar

### Actual behaviour
The calendar is vsible 

### Server configuration
NC 13

**Calendar version:** (see the apps page)
1.6.1

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
