### ISSUE TITLE
Broken calendars break update of Nextcloud

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/calendar#873]
Hi,
One of our users used this tool to sync his calendars: [OGS](https://phw198.github.io/OutlookGoogleCalendarSync/) and this messed up his calendars.

Sadly, this broke the upgrade process. Error:
>now NC is stuck in the update process. Just wanted to send you the error msg: 
> Update to 13.0.5 Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT `calendarid`, `uri` FROM `oc_calendarobjects` WHERE `calendardata` LIKE ?' with params ["%;VALUE=:%"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'calendardata' in 'where clause' 
> Detailed logs
> Preparing update
> Set log level to debug 
> Turned on maintenance mode 
> Updating database schema
> Updated database
> Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT `calendarid`, `uri` FROM `oc_calendarobjects` WHERE `calendardata` LIKE ?' with params ["%;VALUE=:%"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'calendardata' in 'where clause'
> The update was unsuccessful.
> Please report

I suppose disabling the calendar app would help, any other tips and perhaps what info we would need to fix this?

**Comment by georgehrke** [comment]
@jospoortvliet Disabling the calendar app won't have any affect, because all contacts and calendar data is stored in the dav app nowadays.

>  OGS and this messed up his calendars.

Are you sure it's only that? The error message indicates a missing column in the database. I see no way for a CalDAV client to alter the database.

Can you check if the database looks ok? Feel free to ping me directly if you want to send me screenshots to check.

**Comment by yankhr** [comment]
Thanks @georgehrke How can I check the database?

**Comment by georgehrke** [comment]
> How can I check the database?

It's best to contact your administrator about that.

> One of our users used this tool to sync his calendars

I presume that's @jospoortvliet ?

**Comment by jospoortvliet** [comment]
@yankhr sorry for the bad experience. Yeah, when things break, a self-hosted server requires of course more knowledge than what the average normal person has... That is why we also have a lot of providers.

Perhaps @georgehrke can provide some info on how to check what might be wrong, if he's willing to pursue this problem. Otherwise, I guess we have to close this, though I'm unhappy with a problem with the Calendar handling that can break upgrades :cry:

**Comment by georgehrke** [comment]
@yankhr If you are using a normal Webhoster they will usually provide you a MySQL database and GUI access via phpMyAdmin or a similar software.

If they do, you have to select the appropriate database (see the `dbname` inside `config/config.php` for that). Afterwords you have to select the table `oc_calendarobjects` and check if there is a column `calendardata`.

> Otherwise, I guess we have to close this, though I'm unhappy with a problem with the Calendar handling that can break upgrades 😢

I'm still extremely puzzled how a CalDAV client is supposed to delete an entire column in the database. :/
to be honest I kind of doubt that's the reason.

**Comment by yankhr** [comment]
thanks a lot @georgehrke 
i have phpmyadmin access. going to check it and report here ;)

**Comment by yankhr** [comment]
![dbadmin hosteurope de](https://user-images.githubusercontent.com/41786383/43532413-4f06f6b8-95b2-11e8-9ada-208445d60565.png)

**Comment by yankhr** [comment]
I just logged into my database and there is no column "calenderdata" :/

**Comment by georgehrke** [comment]
Are you absolutely sure it's related to [OutlookGoogleCalendarSync](https://phw198.github.io/OutlookGoogleCalendarSync/)?

Does anybody else have access to the database?
Is any other application using the same database?

I don't see any way to delete a database column via simple CalDAV access and without having reliable reproduction steps, it's impossible to fix this issue.

**Comment by yankhr** [comment]
Thanks @georgehrke 
No, I'm not completely sure. I imported my Google Calendars and then mixed them up quite bad with this Outlook Syncing Tool. But no other software has contact with the database.

I just deleted the installation and the database and installed it again. As I am back to Google Calender and only using Nextcloud for file storage and syncing, I hope it will work fine now.

Btw while installing Nextcloud again I recognized the database password must be quite short. I created a password with 15-20 characters and Nextcloud wouldn't accept it. Also there is no proper warning to it. Just some error about no being able to connect to the database.

**Comment by georgehrke** [comment]
> Btw while installing Nextcloud again I recognized the database password must be quite short. I created a password with 15-20 characters and Nextcloud wouldn't accept it. Also there is no proper warning to it. Just some error about no being able to connect to the database.

Can you please report this in https://github.com/nextcloud/server/issues :)
