### ISSUE TITLE
Iframe default view settings

### ISSUE THREAD

**Issue by Ryonez** [nextcloud/calendar#875]
Hi there.

I've been trying to get the default view for an iframe to be day rather than month, as it'd work great in the sidebar for my site. How do I pass this variable on so it works?

**Comment by Ryonez** [comment]
Nothing? I can see a default view flag there, there must be a way to set it.

**Comment by georgehrke** [comment]
This is not possible at the moment.

I will close this as a duplicate of https://github.com/nextcloud/calendar/issues/787, because we are already planning to include the view as a url parameter there
