### ISSUE TITLE
[Nc 14] Sidebar on adding a new event atop of calendar view

### ISSUE THREAD

**Issue by blizzz** [nextcloud/calendar#876]
### Steps to reproduce
1. Have "skip simple event editor" enabled
2. be on 14 beta
3. add a new event

### Expected behaviour

The event sidebar  should appear on the right and decrease the width of the calendar view (as with Nc 13)

### Actual behaviour

The event sidebar is put on top, the calendar view is pushed down, below the fold.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL 

**PHP version:** 7.0

**Server version:** 14.0.0.13

**Calendar version:** 1.6.1

**Updated from an older installed version or fresh install:** updated

**Signing status (ownCloud/Nextcloud 9.0 and above):** 👍

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration

**Browser:** FF 61.0.1

**Operating system:** Antergos

**CalDAV-clients:** WebUI

#### Browser log
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://cloud.nextcloud.com/apps/files/ (“script-src”).

Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info. sentry.js:1:7668

<script> source URI is not allowed in this document: “https://cloud.nextcloud.com/apps/notifications/js/notifications.js?v=59c93372-49”. calendar:44

Attempting to call a FullCalendar method on an element with no calendar.
sentry.js:1:7668
```

**Comment by ChristophWurst** [comment]
Ref https://github.com/orgs/nextcloud/projects/15#card-11847167.
