### ISSUE TITLE
Sync to Thunderbird Lightning

### ISSUE THREAD

**Issue by adi-dev** [nextcloud/calendar#877]
The synchronization with Thunderbird Lighting seams to be broken. Not sure if it's Nextcloud side or Thunderbird.

### Steps to reproduce
Subscribe new calendar in Thunderbird as CalDAV with link: `https://site.address/remote.php/dav/calendars/username/testcalendar/`

### Expected behaviour
Read/write access from Thunderbird to Nextcloud Calendar

### Actual behaviour
Events from Nextcloud Calendar/Tasks are not shown in Thunderbird, events created in Thunderbird don't show in Nextcloud.
Additionally in console:
```
[calCachedCalendar] replay action failed: null, uri=https://site.address/remote.php/dav/calendars/username/testcalendar/, result=2147500037, operation=[xpconnect wrapped calIOperation]  calCachedCalendar.js:331:29
```

### Server configuration
Nextcloud 13.0.5
Ubuntu
PHP Version 7.7.7
Database: mysql 10.1.30 (MariaDB)
Calendar 1.6.1
Updated from an older version (I think, last clean install was around Nextcloud 12)

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

Depending on your Thunderbird issue it might be https://github.com/nextcloud/server/issues/10134

**Comment by adi-dev** [comment]
@georgehrke you're right, it's Thunderbir 60.0b10. I'll be monitoring this issue. Hope I can do some input. Cheers
