### ISSUE TITLE
Show RSVP status of participants [$50]

### ISSUE THREAD

**Issue by dphi** [nextcloud/calendar#879]
Related to #144 . If you can accept/ decline/ .. invitations, then it should also be possible to view the RSVP status of participants in the calendar app. 

Great would be to see the rsvp status of the event
- in the detail page of an event, and
- in the overview with a text hint like, eg,  '#accepts/#tentative/#declined/#not_responded' -> '1/2/0/5'

**Comment by MisterY** [comment]
Adding some search keywords: attendees, participants, invitees ;)

**Comment by pwFoo** [comment]
Yes, I would plan group events with nextcloud calendar and without a list of accepted / declined invites it isn't possible.
Also the notification (nextcloud app) should contain if the person accepted or declined the invite.

**Comment by fert4342** [comment]
I would like to second this issue.

Without a way to see if attendees have accepted/declined an invitation, the calendar app is pretty much useless. Please fix this.

Thank you for your work

**Comment by sebclemens** [comment]
Pleas support this. At least to send an email to the calendar owner to let him know about the response.

**Comment by tbabej** [comment]
I agree this is critical, hence we put 50 USD bounty on this.

**Comment by Upperholme** [comment]
We can't make use of Nextcloud's calendar if we can't track responses to event invitations. This looks to be a major omission.

**Comment by bazzspeed** [comment]
Interestingly I can see the statuses in the Android Calendar App, so at least that's better than nothing.

**Comment by georgehrke** [comment]
@bazzspeed Yes, the data from the user's response is obviously saved in the calendar data.
The only thing missing is showing that status in the web calendar. That's what this ticket is about

**Comment by pwFoo** [comment]
Response is shown in my android calendar by email address (isn't a contact at the moment), but missing in web calendar.
Following here because it would be important for my use case.

**Comment by georgehrke** [comment]
@pwFoo Please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting +1, 👍 etc. These kinds of comments just unnecessarily notify everyone subscribed to this issue. Thx! :)
