### ISSUE TITLE
Contrast and readability could be improved

### ISSUE THREAD

**Issue by alexara** [nextcloud/calendar#880]
Comparing the current Nextcloud Calendar to others products, I think there's a vast space for improvements. Here are my ideas about improving the readability :)

1. I would suggest to increase the overall contrast to improve the clarity.

2. Tiny and low contrast fonts make it difficult to read. Therefore I would suggest to increase the contrast and to make important keywords bigger and/or bold.

3. If you choose the "day view", the whole day is displayed yellow. This may makes sense to indicate the current day as long as other days are displayed as well.
I suggest to remove the yellow color from the "day view" and instead to indicate it on a different way.
Eg by coloring the "Today button", whenever the current day is shown or to color only the weekday at the top of the calendar.

4. The week overview displays a line for each "half an hour". Removing would not be great loss but  make it more clear.

The following screenshots show a) the current version of the NC calendar and b) an example of a calendar I consider easier to work with regarding the UI:

a) 

![screenshot_20180803_113128](https://user-images.githubusercontent.com/13819719/43636133-83296ee8-9711-11e8-81f0-376e6d0d19b4.png)

![screenshot_20180803_120800](https://user-images.githubusercontent.com/13819719/43637627-fdcc1426-9715-11e8-9487-8de56f9cfab3.png)

b)

![screenshot_20180803_113014](https://user-images.githubusercontent.com/13819719/43636137-85059b10-9711-11e8-9409-e9d95ebe88c1.png)

![screenshot_20180803_114645](https://user-images.githubusercontent.com/13819719/43636713-29140aa6-9713-11e8-82c8-a1b620d1bd08.png)

alex

**Comment by georgehrke** [comment]
@nextcloud/designers

**Comment by tcitworld** [comment]
Agreed with increase opacity for everything related to dates.

**Comment by jancborchardt** [comment]
@alexara sounds good! :) We could proceed like this:
- Could you post a more detailed breakdown of what you would enhance. One list item per issue ideally, so it’s self-contained :ballot_box_with_check: 
- If you like, it would be awesome if you want to get involved and submit pull requests for the proposed changes. :rocket:

**Comment by alexanderdd** [comment]
See also https://github.com/nextcloud/calendar/issues/555

**Comment by oerms** [comment]
The functionality of the Nextcloud Calendar app is great generally speaking. Most tasks are easily done.
The major usability hindrance IMHO is the poor legibility of practically everything. There are good examples how to do better. **I strongly back this issue!**

I am willing to try and work on this myself for a bit. How do I edit the CSS sheet and what can I do to push my changes to the master/next release?

**Comment by georgehrke** [comment]
ping @oerms :)

**Comment by jancborchardt** [comment]
Also note that a big part of this has been fixed already with Nextcloud 15 as we moved from a Light body font to Regular weight which is much better to read.

**Comment by georgehrke** [comment]
Closing since neither @oerms nor @alexara provided any feedback for half a year now.

As we said multiple times above, please create an individual ticket per issue. Thanks!
