### ISSUE TITLE
[feature request] Allow for custom start-of-week day on the calendar.

### ISSUE THREAD

**Issue by slashfoo** [nextcloud/calendar#889]
Right now the calendar month/week views are fixed on "sunday" as start of week, but neither of those are the settings I normally use in my calendars, I'm used to Saturday and Monday being options for start-of-week. I think this should be configurable in the application settings, or the user settings.

**Comment by georgehrke** [comment]
See nextcloud/server#1781

We won't introduce this option but a region setting in the server that will influence the first day of the week.
