### ISSUE TITLE
Starting Weekday: Monday

### ISSUE THREAD

**Issue by Ra-Na** [nextcloud/calendar#890]
_Please_  add the possibility to view the week starting on Monday and ending on Sunday.

**Comment by georgehrke** [comment]
See nextcloud/server#1781

We won't introduce this option but a region setting in the server that will influence the first day of the week.

**Comment by Ra-Na** [comment]
Am I supposed to guess that the global language setting changes the calender view behaviour? I assumed that this can be adjusted separately.

**Comment by jkelly99** [comment]
I would also like to put my vote in for 24 h clock settings and Monday start of week without needing to change locale settings. I am in the US and work in a medical setting. We use US date format, 24 hr clock, and Monday start of week.

**Comment by fonata** [comment]
My solution: I added `'default_locale' => 'de_DE',` to the file `nextcloud/config/config.php`.
