### ISSUE TITLE
[Nc14] Accepting an invitation from an email does not add the event to the calendar 

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/calendar#892]
Accepting an invitation from an email does not add the event to the calendar (any of the calendars).

Email:

![image](https://user-images.githubusercontent.com/295122/44406223-5dda6180-a55b-11e8-8867-60f6f6bde0d5.png)

Clicking on "Accept":

![image](https://user-images.githubusercontent.com/295122/44406233-66cb3300-a55b-11e8-99f8-55ad9d188f8c.png)

**When I open the Nextcloud calendar app (web UI) though, there is no event entry for the date that I just accepted. I would expect that there would be an event in my calendar.**

I can only add the event to my calendar when I import the .ics attachment in the email via my email client (in my case Evolution). But I would expect that the "Accept" button that leads to the NC web UI does exactly that for me.

Additionally: if you have more than one calendar, the user should get asked which calendar to add it to.

Not sure if this is now more of a bug or an enhancement. Happening on the current calendar app version on cloud.nextcloud.com

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
