### ISSUE TITLE
Give a name or title to a calendar you subscribe to

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/calendar#894]
### Steps to reproduce
1. Using the new subscription option
2. Enter ical address
3. The calendar appears  Yay!
4. Calendar Title in the sidebar is calendar URL - not human readable
5. Confused because I can't tell which calendar I'm looking at

### Expected behaviour
Tell us what should happen
When subscribing o a calendar you should be able to give it a name not just the subscription link or it should be able to determine name from ical metadata (is that a thing? I confess I know nothing about how ical works)

### Actual behaviour
Calendar gets added with the calendar name in sidebar being the calendars subscription url

Edit: This appears to happen only on some calendars, on others it works as expected.

**Comment by tcitworld** [comment]
The name should be properly extracted from the WebCal feed.
Can you try with this one for instance ? webcal://i.cal.to/ical/81/bayern/ferien/b52d3fa1.28a0b14d-b3198c46.ics#Ferien+-+Bayern
If detection fails, the title is the URL since we don't have any other information, but you can edit it.

**Comment by ashgoodman** [comment]
Thanks, didn't realize I could edit it after subscription. That helps tremendously.
