### ISSUE TITLE
Multiple public calendars with one link

### ISSUE THREAD

**Issue by SansPseudoFix** [nextcloud/calendar#900]
Hi,

Sometimes you want to share many calendars (read-only) with people, but instead of using one link per calendar, it could be great to have a *meta-link* which displays the list of calendars on the left side (maybe add possibility to display/hide them?).

To sum up: the same display than private display but for public link.

**Comment by georgehrke** [comment]
Please search for existing issues before creating new ones ...

Duplicate of https://github.com/nextcloud/calendar/issues/708

**Comment by SansPseudoFix** [comment]
Actually, I did and I really don't know why I missed this one. Sorry about that.
