### ISSUE TITLE
All changes to tasks are lost

### ISSUE THREAD

**Issue by ygoe** [nextcloud/calendar#905]
### Steps to reproduce
1. Unknown

### Expected behaviour
Changes should be reliably saved.

### Actual behaviour
All changes to tasks I made yesterday on my office computer are now lost. Everything is in its old state, in the web and on my synchronised phone. I have suddenly lost all trust in this application and will look for alternatives before I lose more data.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Unsure

**PHP version:** 7.0

**Server version:** 13.x

**Calendar version:** Unsure

**Updated from an older installed version or fresh install:** Fresh install, some time ago

**Comment by georgehrke** [comment]
I'm sorry that you lost data, but with reproduction steps "Unknown" there is absolutely no way for us to help you.

Furthermore this is the wrong repository. If you had issues with the Nextcloud tasks app, please report your issue in https://github.com/nextcloud/tasks/. If you had issue with a Task-App on your mobile phone or desktop, that's syncing via CalDAV and the CalDAV-sync failed, please report it in https://github.com/nextcloud/server
