### ISSUE TITLE
Copy events from a calendar to another

### ISSUE THREAD

**Issue by livier** [nextcloud/calendar#906]
### Steps to reproduce
1. Open an event that I want to copy on another calendar
2. When I have right access to the original Calendar, I can transfert the event to another, nice.
3. but I cannot, or I did not see how, copy it ton another calendar.  
4. appreciating your job anyway

### Expected behaviour
It would specialy be nice to open public calendars provoded by frindly organisations (ex: https://agendadulibre.qc.ca/events.ics) and copy some of then in my private or shared calendar.

### Actual behaviour
Just changing event fron a calendar to another, *if* I have right access to both

### Steps to reproduce
1. Open an event that I want to copy on another calendar
2. When I have right access to the original Calendar, I can transfert the event to another, nice.
3. but I cannot, or I did not see how, copy it ton another calendar.  
4. appreciating your job anyway

### Expected behaviour
It would specialy be nice to open public calendars provoded by frindly organisations (ex: https://agendadulibre.qc.ca/events.ics) and copy some of then in my private or shared calendar.

### Actual behaviour
Just changing event fron a calendar to another, *if* I have right access to both

## Server configuration detail

**Operating system:** Linux 2.6.32-26-pve #1 SMP Mon Oct 14 08:22:20 CEST 2013 x86_64

**Webserver:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 5.5.60

**PHP version:** 

7.0.30-1~dotdeb+8.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.5 - 13.0.5.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - apporder: 0.5.0
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.1
 - cms_pico: 0.9.7
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.7
 - deck: 0.4.1
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_linkeditor: 1.0.7
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - gallery: 18.0.0
 - impersonate: 1.0.4
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.8.3
 - nextcloud_announcements: 1.2.0
 - notes: 2.4.1
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - password_policy: 1.3.0
 - polls: 0.8.3
 - provisioning_api: 1.3.0
 - qownnotesapi: 18.8.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.2.5
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.7
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - announcementcenter
 - circles
 - dashboard
 - encryption
 - external
 - files_clipboard
 - files_frommail
 - firstrunwizard
 - groupfolders
 - rainloop
 - socialsharing_email
 - spreedme
 - user_external
 - user_ldap
 - w2g2

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "un.autre.domaine.tld",
        "cloud.penserpouragir.org"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.penserpouragir.org",
    "Overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "13.0.5.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 3,
    "maintenance": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** FAKE : Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0

**Operating system:** Ubuntu

**Comment by tlehmann7** [comment]
Hey, you can import your calendar to your Smartphone or another Calendar Manager. I don´t mean the subscription, i mean the WebDAV / CalDAV Link, so sign in with your nextcloud account. In a 3rd party app you should be able to copy events :-)

**Comment by milankni** [comment]
This is similar to cloning events within the same calendar (ctrl + drag to other day like with files or like in other desktop calendar apps or at least with Edit GUI).
https://github.com/nextcloud/calendar/issues/113

**Comment by alexanderdd** [comment]
+1

**Comment by livier** [comment]
up ^_^

**Comment by georgehrke** [comment]
@livier 
Please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting +1, 👍 etc. These kinds of comments just unnecessarily notify everyone subscribed to this issue. Thx! :)

**Comment by georgehrke** [comment]
Closing as Duplicate of https://github.com/nextcloud/calendar/issues/113

**Comment by beedell-roke** [comment]
@GeorgEhrke, how is this a duplicate? Doesn't [`issues/113`](https://github.com/nextcloud/calendar/issues/113#issue-180860766) refer to individual events?

**Comment by alexanderdd** [comment]
@RokeJulianLockhart with the duplicate button introduced via https://github.com/nextcloud/calendar/issues/113 , a duplicate of the event is created, and you can change the calendar where this new event should be saved. So this issue here is resolved. 

(this issue here referred to individual events, just as #113 )

Thanks everyone 🙏

**Comment by OtharSmirnow** [comment]
Hi,
I know it's long since previous post but "Duplicate" does not work for "external" events. I can download the ics, but can not copy event from "read only" calendar.

**Comment by SebastianKrupinski** [comment]
hi @OtharSmirnow, 

What do you mean by external events?

**Comment by OtharSmirnow** [comment]
A colleague received an invite to a meeting. He shared a calendar with me, I want to copy this event to my calendar.
current process is to export event and then import to my calendar.
Same thing is for events from eg. shared google.calendar.

For shared nextcloud calendars duplicate button is available.
