### ISSUE TITLE
broken window positioning when editing an event 

### ISSUE THREAD

**Issue by mbiebl** [nextcloud/calendar#907]
Version: 14.0

When editing an existing event I get a broken window position as shown in the attached screenshot.
Notice how the dialog is cut off at the top.
![bildschirmfoto von 2018-09-17 09-51-46](https://user-images.githubusercontent.com/3609611/45611421-b0764300-ba5f-11e8-802e-5e3090722a2e.png)

**Comment by mbiebl** [comment]
In my case, I wanted to edit the "Test" event

**Comment by tcitworld** [comment]
Could you fill the issue template with other informations (browser version and browser logs most importantly) ?

**Comment by mbiebl** [comment]
FF 62, Chrome 69

**Comment by georgehrke** [comment]
@mbiebl Please fill the entire [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/issue_template.md) ...

**Comment by mbiebl** [comment]
Oh sigh,

**Comment by mbiebl** [comment]
Oh well, seems I was wrong. It's also reproducible at https://demo.nextcloud.com/
You can get all info you want about this installation there.

**Comment by mbiebl** [comment]
![bildschirmfoto von 2018-10-07 15-30-13](https://user-images.githubusercontent.com/3609611/46582397-48a38e80-ca46-11e8-9730-c15309829b01.png)
