### ISSUE TITLE
Other people accepting event invitation results in email saying "invitation updated"

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/calendar#912]
### Steps to reproduce
1. Create an event and invite other people
2. Have a person confirm their attendance (or reject, I guess)
3. Check your emails

### Expected behaviour
You get an email saying: »Christoph confirmed the invitation« or »Christoph rejected the invitation«

### Actual behaviour
This:
![screenshot from 2018-09-19 21-58-36](https://user-images.githubusercontent.com/925062/45777920-68ba0c00-bc57-11e8-9c33-af5521d38a32.png)

cc @georgehrke @nextcloud/calendar

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by georgehrke** [comment]
reopened in https://github.com/nextcloud/server/issues/11539
