### ISSUE TITLE
Setup transifex

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#92]
@MorrisJobke :)

**Comment by georgehrke** [comment]
ping @MorrisJobke :)

**Comment by MorrisJobke** [comment]
Okay okay ... I will have a look ... soonish 🙈

**Comment by tcitworld** [comment]
For some reason new strings aren't translated or displayed at all in transifex. :(

**Comment by MorrisJobke** [comment]
> For some reason new strings aren't translated or displayed at all in transifex. :(

I forgot to add the cronjob 🙈 Sorry - should work now :)

**Comment by MorrisJobke** [comment]
And thanks for the heads up

**Comment by tcitworld** [comment]
No worries. :-)
