### ISSUE TITLE
Auto-complete URL's from Bookmarks app into Calendar

### ISSUE THREAD

**Issue by sunjam** [nextcloud/calendar#927]
Would likely need issue #674, but I would find it very useful to auto-complete/import/sync links from the [Bookmarks app](https://github.com/nextcloud/bookmarks) into my calendars and vice-versa.

**Comment by georgehrke** [comment]
@sunjam What's the use case here?
I assume you want an autocomplete for the description field?

**Comment by sunjam** [comment]
Hi, I would love auto-complete of url's from the bookmarks app into the description field of Calendar entries! For me, those urls will already be in my Nextcloud Bookmarks app.  If I cannot remember them, it would be awesome to use some form of auto-completion.

**Comment by georgehrke** [comment]
I'm closing this, because it seems like a very special / uncommon use-case to me. Auto-completion in the description field is tricky anyway and there is no real advantage of simply copy and pasting a link.
