### ISSUE TITLE
MigrationException with Nextcloud 10

### ISSUE THREAD

**Issue by voidzero** [nextcloud/calendar#93]
### Steps to reproduce
1. Did the upgrade from nextcloud 9.0.53 to 10.0.0
2. Ran `./occ upgrade`
3. Got presented with the following error:

<pre>OC\DB\MigrationException: An exception occurred while executing
'ALTER TABLE nxt_nxt_calendars_xymyfzoytq83y ALTER components TYPE VARCHAR(20)':

SQLSTATE[22001]: String data, right truncated: 7 ERROR: 
value too long for type character varying(20)
Update failed
</pre>

### Expected behaviour
The migration should succeed

### Actual behaviour
See above

### Server configuration
**Operating system**:
Funtoo Linux (Gentoo derivative)

**Web server:**
nginx

**Database:**
postgresql 9.5.4

**PHP version:**
5.6.26

**Server version:** (see your admin page)
10.0.0

**Calendar version:** (see the apps page)
1.3.1

**Updated from an older installed version or fresh install:**
Updated from 9.0.53

**Comment by georgehrke** [comment]
Can you reproduce the same behavior with Nextcloud 10?

**Comment by voidzero** [comment]
Golly. My apologies :blush:

Yes this applies to Nextcloud, not Owncloud!

**Comment by georgehrke** [comment]
Okay :)

this is a server issue. please report it in http://github.com/nextcloud/server

**Comment by voidzero** [comment]
Will do. Thanks.
