### ISSUE TITLE
Calendar event location autocompletion delivering problematic multi-line locations

### ISSUE THREAD

**Issue by brad2014** [nextcloud/calendar#933]
When entering the *event location* of a calendar event, the address taken from contact autocompletion is  translated to a multi-line format, which is problematic in a few ways:

1.  The event location input field doesn't expand to display the multi-line location when it is stuffed, so the autocompleted address is invisible until the user types in the field (causing it to resize).
2.  Other applications (Thunderbird, Google Calendar), more or less expect locations in VCAL and ICS files (e.g. attached to meeting invitations) to be on a single line.  Thunderbird, for example, renders multiline locations by concatenating the lines: "123 High StreetSan FranciscoCA94114US".  Ugly!

### Steps to reproduce
1.  In the calendar window, enter a new event 
2.  In the event location field, type in the name of a contact who has an address, and select the contact
3.  Notice the address isn't fully visible (the field is only one line high, but the address is multiline), and when the iMip message is sent, notice it has a multi-line location that will choke other mail clients.

### Expected behaviour
1.  Instead of rendering the address as
123 High Street
San Francisco
CA
94114
US

Translate it to:
123 High Street, San Francisco, CA, 94114, US

(Aside: this address format is suitable for pasting into mapping services, like openstreetmap or google maps.  If only the iMip email had a link to pull up the map...)
(Aside:  roundcube has a configuration variable that controls the order of address fields, allowing the postal code to come in the right place for the users locale - does nextcloud).

**Comment by georgehrke** [comment]
Hey,

first of all: Thanks for the pull-request!

> The event location input field doesn't expand to display the multi-line location when it is stuffed, so the autocompleted address is invisible until the user types in the field (causing it to resize).

That's definitely a bug that should be fixed independently from this issue.

> Other applications (Thunderbird, Google Calendar), more or less expect locations in VCAL and ICS files (e.g. attached to meeting invitations) to be on a single line. Thunderbird, for example, renders multiline locations by concatenating the lines: "123 High StreetSan FranciscoCA94114US". Ugly!

I'm usually not a big fan of compromising usability to make up for shortcomings in other clients, but "23 High StreetSan FranciscoCA94114US" is indeed really ugly. Nevertheless Thunderbird should obviously allow to create multiline locations, since this is a valid value.

Any objections? @tcitworld @jancborchardt @skjnldsv  

> (Aside: this address format is suitable for pasting into mapping services, like openstreetmap or google maps. If only the iMip email had a link to pull up the map...)

Please open a feature request in the server repo. I guess it's kind of obvious that Nextcloud, being all about privacy and taking back control of your data, can't link to Google Maps. OSM should be something we should be able to consider though. (Although admins should probably have the option to point to some custom search endpoint) 🙂 

> (Aside: roundcube has a configuration variable that controls the order of address fields, allowing the postal code to come in the right place for the users locale - does Nextcloud).

Right now we read that value straight from the `ADR` field in the contact's vcard. Not sure if it's already supposed to be in the right order. @skjnldsv Is it?

**Comment by skjnldsv** [comment]
> Right now we read that value straight from the `ADR` field in the contact's vcard. Not sure if it's already supposed to be in the right order. @skjnldsv Is it?

No other way around that :)
We are compliant with the rfc here : https://tools.ietf.org/html/rfc6350#section-6.3.1
The order here is: 
the post office box;

> 1.  the extended address (e.g., apartment or suite number);
> 2. the street address;
> 3. the locality (e.g., city);
> 4. the region (e.g., state or province);
> 5. the postal code;
> 6. the country name (full name in the language specified in
> 7. Section 5.1).

**Comment by brad2014** [comment]
Since I inadvertently started it, I'll move the ordering question to a separate issue.

**Comment by brad2014** [comment]
With respect to getting event location addresses to "look right" in IMip mail (which goes to my contacts under my name, and so I want it to look good), I think the goal should be to have them presented the way the postal services specify them.  Unless one plans on implementing the disaster that is [UPU-S42](http://www.upu.int/uploads/tx_sbdownloader/sheetAddressingS42InternationalAddressingStandardsFactSheetEn.pdf), nextcloud could rely on the user typing each postal address (as free text) the way they want it to look in email, rather than assembling the individual fields in the right order, which might be different for every address.

**Comment by georgehrke** [comment]
fixed with https://github.com/nextcloud/calendar/pull/934
