### ISSUE TITLE
Support iMip emails that don't link to server, for nextcloud servers on a private network

### ISSUE THREAD

**Issue by brad2014** [nextcloud/calendar#935]
Feature request:

Support nextcloud servers that are on a private network (e.g. at home) which, for privacy/security are not accessible from the public internet: 

Have a system configuration setting that tells the CalDAV IMip mail generator (and any other mail generator that sends mails to 3rd parties externally) to exclude URL's that refer to the server.  For example, IMip mails have image icons (which should be bundled with the email), and accept/decline buttons (These can simply be suppressed from the emails when that global setting is turned on—clients will accept/decline via iMIP replies instead).

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues

**Comment by georgehrke** [comment]
btw, this should probably apply to all emails sent out by Nextcloud and not just invitations, right?

**Comment by pirate** [comment]
For anyone landing here via Google, the relevant issue over at nextcloud/server is here: https://github.com/nextcloud/server/issues/17187
