### ISSUE TITLE
Asking for username and password Office 2013

### ISSUE THREAD

**Issue by pmisner** [nextcloud/calendar#94]
### Steps to reproduce
1. put webdav link in  outlook 2013 publsh to calendar
2. asks for username and password
3. put in owncloud username and password
4. Password incorrect, try again

### Expected behaviour
Password should be accepted. 

### Actual behaviour
Password not accepted. 

### Server configuration
Linux (hosted at ihostww) using Fantastico

**Web server:**
Apache

**Database:**
My SQL
**PHP version:**
Unknown
**Server version:** (see your admin page)
9.11
**Calendar version:** (see the apps page)
1.40
**Updated from an older installed version or fresh install:**
Fresh
**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Chrome
**Operating system:**
Window 7
**CalDAV-clients:**
Outlook 2013
#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by georgehrke** [comment]
can you reproduce the same issue with Nextcloud?

**Comment by georgehrke** [comment]
@pmisner ^

**Comment by georgehrke** [comment]
missing feedback from user, closing
