### ISSUE TITLE
Enhancement: Calender reminder via Talk

### ISSUE THREAD

**Issue by g6094199** [nextcloud/calendar#942]
Hi !

Atm we can have calender remindes via email, audio and pop-up.
The option to be reminded via Talk would be the next logical option ;-)

Sash

**Comment by georgehrke** [comment]
Can you please elaborate on that? 

How would a reminder of the talk app (I assume?) be any different from a regular pop-up reminder?

**Comment by g6094199** [comment]
Hi,

Ok. I was unclear on that. I think of using the Android Talk App, where it might be usefull to receive reminders as messages.
Indeed on the web-gui a pop-up is doing a good job.

**Comment by georgehrke** [comment]
> Ok. I was unclear on that. I think of using the Android Talk App, where it might be usefull to receive reminders as messages.

I honestly still don't see how a message in the Android Talk app is any way superior to an ordinary notification from your Android calendar.

Plus receiving a message, people will expect to be able to reply with questions like "How long is the meeting", "Who is attending", "show the description", "Call attendee xyz", "How long will I need to reach [given current traffic]" etc etc. And we really don't have the workforce to implement an assistant like that.
