### ISSUE TITLE
clander not correctly shown

### ISSUE THREAD

**Issue by aaron-git** [nextcloud/calendar#945]
Hello Guy's,

I can't use my Calender it isn't corretly shown.
My machine is a Ubuntu 18.04 and php-7.2 with the Apache Web-Server.
I use the 14.0.3 Version of the nextcloud server and for the calendar the version 1.6.3

I didn't set any special settings.
Do you have an Idea, why it doesn't work?

Best regards 

Aaron

![nextcloud](https://user-images.githubusercontent.com/13673339/48585095-dd45ba00-e92b-11e8-869d-68885f5f38ec.jpg)

**Comment by georgehrke** [comment]
Wild guess: instead of downloading it from the App Store you did a git clone?

**Comment by georgehrke** [comment]
Closing, because there was no feedback.

Most likely related to just cloning the calendar repo, which is not supported. Please  install from the App Store.
