### ISSUE TITLE
Generic CALDAV URL for shared calendar no longer works

### ISSUE THREAD

**Issue by stweil** [nextcloud/calendar#973]
Test condition:
User "master" has shared the calendar "feiertage" with a group.
User "client" is part of that group and should be allowed to access the calendar.

Until recently user "client" and all other members of the group could access the calendar using the URL https://servername/remote.php/dav/calendars/master/feiertage/.

Now only the URL https://servername/remote.php/dav/calendars/client/feiertage_shared_by_master/ works, so every user must use a user specific URL.

**Comment by georgehrke** [comment]
Access to https://servername/remote.php/dav/calendars/master/feiertage/ for other users then `master` was never officially supported and this URL is and was never displayed to user `client`.

The only documented and supported way to access the shared calendar for `client` is via the URL `https://servername/remote.php/dav/calendars/client/feiertage_shared_by_master/`
