### ISSUE TITLE
Select contacts for birthday calendar (or show only activ calendars)

### ISSUE THREAD

**Issue by omocinteractive** [nextcloud/calendar#979]
### Expected behaviour
Select contacts for birthday calendar or only show birthdays from active calendars

### Actual behaviour
All birthdays are shown (also of a inactive contact book with archived contacts)

### Server configuration
**Calendar version:** (see the apps page)
1.64

**Comment by georgehrke** [comment]
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.
Please report issues related to the CalDAV server in Nextcloud's server repo: https://github.com/nextcloud/server/issues
